### ISSUE TITLE
S3 TransferClient upload file - please enable requesting encryption on server side 

### ISSUE THREAD

**Issue by Eliyahu50** [aws/aws-sdk-cpp#100]
Hi,

S3 enables encryption of objects at server side (encryption on rest) 
see http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html

Using the aws-sdk-cpp low level there is an option to request uploading file and encrypting data on server side however with the high level API (transferClient upload file method), there is no option to request it. Please add it.

Thanks.

Eliyahu

**Comment by JonathanHenson** [comment]
The new transfer manager interface allows you to set PutObject, GetObject, CreateMultipartUpload, and UploadPart templates that will be used for all operations. To configure these options, you simply set the template you want us to copy from and the rest will happen automatically. Feel free to reopen if you have further questions.
