### ISSUE TITLE
aws-sdk-c++ setting up for qt for android

### ISSUE THREAD

**Issue by warlock-jay** [aws/aws-sdk-cpp#1005]
### What platform/OS are you using?
I am using ubuntu 16.04,and qt 5.9,android ndk version r10e

I have compiled aws c++ sdk like this

cmake -DCMAKE_BUILD_TYPE=Release -DTARGET_ARCH=ANDROID -DBUILD_ONLY="s3;dynamodb;cognito-identity;cognito-idp;iam;iot" -DNDK_DIR=/home/jay/Android/Ndk ..

It didn't give any problem, it was built.

This the function I wrote.
void Geeks::credinit(){
qDebug()<<"credentials initialising";
Aws::SDKOptions options;
qDebug()<<"step1";
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Info;
qDebug()<<"step2";
Aws::InitAPI(options);
{
qDebug()<<"step3";
}
Aws::ShutdownAPI(options);}

When I deploy the app to debug, the app is crashing when this function is running. The output i got

D/liba4.so(27281): ../a4/geeks.cpp:31 (void Geeks::credinit()): credentials initialising
D/liba4.so(27281): ../a4/geeks.cpp:33 (void Geeks::credinit()): step1
D/liba4.so(27281): ../a4/geeks.cpp:35 (void Geeks::credinit()): step2
F/libc    (27281): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 27855 (QtMainThread)
I/DEBUG   (20400): pid: 27281, tid: 27855, name: QtMainThread  >>> org.qtproject.example <<<
I/Zygote  (  276): Process 27281 exited due to signal (11)
E/lowmemorykiller(  242): Error opening /proc/27281/oom_score_adj; errno=2
I/ActivityManager(  956): Process org.qtproject.example (pid 27281) has died

"org.qtproject.example" died.

It is failing while executing InitAPI(). Is my setup wrong? Tell me how to build the library and give paths properly?

**Comment by jay7583** [comment]
how to build cpp sdk for qt for android?how to use same toolchain and how to install in the same path?
