### ISSUE TITLE
CreateDirectoryIfNotExistedTest fails on aufs

### ISSUE THREAD

**Issue by ploki** [aws/aws-sdk-cpp#1010]
It appears that aws-sdk-cpp cannot be built in a docker container running on aufs because of the aufs limitation on file name length (AUFS_MAX_NAMELEN is defined as 242)

https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core-tests/utils/FileSystemUtilsTest.cpp#L271

### What platform/OS are you using?
ubuntu 18.04LTS in a docker container on aufs

### What compiler are you using? what version?
gcc-7.3

### What's your CMake arguments?
```
cmake -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_ONLY="s3" \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -B$PWD/build -H$PWD/aws-sdk-cpp && \
```
### Can you provide a TRACE level log? (sanitize any sensitive information)
```
[----------] Global test environment tear-down
[==========] 294 tests from 48 test cases ran. (409 ms total)
[  PASSED  ] 293 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] DirectoryTreeTest.CreateDirectoryIfNotExistedTest

 1 FAILED TEST
aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/build.make:1070: recipe for target 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests' failed

```

**Comment by ploki** [comment]
This?
```
/root/aws-sdk-cpp/aws-cpp-sdk-core-tests/utils/FileSystemUtilsTest.cpp:278: Failure
Value of: FileSystem::CreateDirectoryIfNotExists(FileSystem::Join(FileSystem::Join(dir2, "dir3"), longDirName).c_str(), true )
  Actual: false
Expected: true
[  FAILED  ] DirectoryTreeTest.CreateDirectoryIfNotExistedTest (1 ms)

```

**Comment by singku** [comment]
@ploki Thanks for reporting this, we didn't test the SDK on all file systems. Can you please make a PR based off this? You can temporarily bypass this by setting CMake flag `-DAUTORUN_UNIT_TESTS=OFF`

**Comment by ploki** [comment]
Thanks for the temporary workaround.
I can make a PR, but I'm not sure about the rationale that motivated this test which seems specific to some Windows operating system corner case. I see three options:
* remove the test
* surround the test by ```#ifdef _WIN23 ... #endif``` to be executed only on the Windows platform?
* modify the test to use ```pathconf(3)``` on ```"."``` on non-Windows platform?

**Comment by bpycinski** [comment]
Hello AWS-Team (@singku, @Bu11etmagnet)! 
I confirm the mentioned error inside Docker containter. Please tell, are you going to merge @ploki 's pull-request to the mainline?
Thanks in advance!
Bartłomiej

**Comment by singku** [comment]
@ploki Is this problem no longer valid? Are you able to solve this it.

**Comment by ploki** [comment]
The problem seems to be fixed, I tested a build of 1.7.84 on aufs and the test did not fail.

Thanks!

**Comment by annerajb** [comment]
failing again. 
ubuntu:18.04 docker container 

>cmake -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_ONLY="s3" .. 
> make -j

**Comment by ploki** [comment]
tested successfully with 1.7.119 in a docker container on aufs with the same cmake parameters. It might be something else
