### ISSUE TITLE
REQUEST_TIMEOUT in CoreErros but not in S3Errors

### ISSUE THREAD

**Issue by SubmarineX** [aws/aws-sdk-cpp#1011]
https://github.com/aws/aws-sdk-cpp/blob/ae61571628e4ddbad12cefb85e36afa055bb8e3d/aws-cpp-sdk-core/include/aws/core/client/CoreErrors.h#L56

https://github.com/aws/aws-sdk-cpp/blob/ae61571628e4ddbad12cefb85e36afa055bb8e3d/aws-cpp-sdk-s3/include/aws/s3/S3Errors.h#L52

https://github.com/aws/aws-sdk-cpp/blob/ae61571628e4ddbad12cefb85e36afa055bb8e3d/aws-cpp-sdk-s3/include/aws/s3/S3Errors.h#L53

**Comment by singku** [comment]
Thanks for reporting this, we will update our code gen asap.

**Comment by singku** [comment]
This problem has been fixed. https://github.com/aws/aws-sdk-cpp/blob/170ba366229dcc59e09f06aa10ed9b4fb4fab644/aws-cpp-sdk-s3/include/aws/s3/S3Errors.h#L53
