### ISSUE TITLE
S3 Prefix Question

### ISSUE THREAD

**Issue by pcaswell** [aws/aws-sdk-cpp#1012]
### What platform/OS are you using?
Windows 7 64bit Professional

### What compiler are you using? what version?
Microsoft (R) C/C++ Optimizing Compiler Version 19.14.26430 for x64

### What's your CMake arguments?
cmake ../${AWS_SDK_BASENAME} -G "Visual Studio 15 2017 Win64"
-DSIMPLE_INSTALL=OFF
-DAUTORUN_UNIT_TESTS=OFF
-DCMAKE_INSTALL_PREFIX="${TOOLS_X64}/${AWS_SDK_BASENAME}"
-DCMAKE_PDB_OUTPUT_DIRECTORY="${TOOLS_X64}/${AWS_SDK_BASENAME}/bin/windows/intel64"
-DCPP_STANDARD=17
-DBUILD_ONLY="s3;dynamodb;lambda;iam;autoscaling;application-autoscaling;sts"
Where ${AWS_SDK_BASENAME} = 1.6.25

### Can you provide a TRACE level log? (sanitize any sensitive information)
NA

Hello Forum,
I'm really not sure if this is the right place to ask this question but I'll do so anyway.  I'm trying to understand what actually constitutes a 'prefix' in S3 when considered in the context of bucket performance.  I've read that S3 uses the prefix to distribute workload between different partitions so that that a single partition isn't overwhelmed.

Looking at the developer guide I see S3 supports 3,500 PUT/POST/DELETE and 5,500 GET requests per second per prefix [https://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html](url) but I've been unable to find anything concrete about what a prefix is?  In other forums it's been hinted that it's the first 6 to 8 characters of the key and then in others its the bit of the key up to the first delimiter.  Can anyone clarify for certain.

I'm unsure of whether our application will exceed the rates specified above but I'd prefer to cater for larger rates now than find out later that there's a problem.
Thanks,
Paul

**Comment by singku** [comment]
The descriptions of Prefix and Delimiter are here:
https://docs.aws.amazon.com/AmazonS3/latest/dev/ListingKeysHierarchy.html
You can find the actual usage of Prefix and Delimiter here:
https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

**Comment by pcaswell** [comment]
Thanks Singku, however that doesn't seem to answer my question.  The articles you cite relate to listing and getting objects (or searching using a known part of a key) in a bucket whereas my question was about how AWS S3 uses a 'prefix' to load share requests between AWS S3 partitions when request rates are high.  Take a look at the article I mention in my original post - what is meant by prefix in that sense?

**Comment by singku** [comment]
You can find Prefix's definition in the first page and actual usage in the second page. There is only one concept of Prefix in S3. Prefix makes objects organized/classified like in subfolders in S3. The "Prefix" notation you mentioned in performance page means you can operate with that performance parallely within different "subfolders".

**Comment by pcaswell** [comment]
Hmm, you are saying then that partition assignment within S3 is dictated solely by the prefix of the object's key.  So if I create these objects in S3 :
`mygame/data/test1.txt`
`mygame/data/test2.txt`
Then S3 internally assigns a single partition based on the 'mygame/' element of the key.  This surprises me somewhat as that doesn't seem to scale very well if I as a user of S3 create all my keys with the same prefix.  Take a look at this article and specifically the example 1 in it:
https://aws.amazon.com/blogs/aws/amazon-s3-performance-tips-tricks-seattle-hiring-event/
This seems to contradict your assertion and so I'm still not convinced.

**Comment by singku** [comment]
Please read my comment carefully. I just said what is "Prefix" and how it can be used to increase performance. I didn't say "Prefix" is the only way. Actually, the blog post you referenced above is exactly what you want to understand Prefix.

**Comment by pcaswell** [comment]
I have read your comment carefully and I have read the blog post carefully.  Taken directly from the blog post (highlights by me)

2134857/gamedata/start.png
2134857/gamedata/resource.rsrc
2134857/gamedata/results.txt
2134858/gamedata/start.png
2134858/gamedata/resource.rsrc
2134858/gamedata/results.txt
2134859/gamedata/start.png
2134859/gamedata/resource.rsrc
2134859/gamedata/results.txt

**All these reads and writes will basically always go to the same partition**…but if the identifiers are 
reversed:

7584312/gamedata/start.png
7584312/gamedata/resource.rsrc
7584312/gamedata/results.txt
8584312/gamedata/start.png
8584312/gamedata/resource.rsrc
8584312/gamedata/results.txt
9584312/gamedata/start.png
9584312/gamedata/resource.rsrc
9584312/gamedata/results.txt

**This pattern instructs S3 to start by creating partitions named:**

mynewgame/7
mynewgame/8
mynewgame/9

As you can see the partitions are **not** dictated by the prefix as "2134857/" does not equal "2134858/" or "2134859/" yet the article states reads and writes will basically go to the same partition.  There is a similar anomaly in the latter part of the quote.

It might be obvious to you how S3 scales using prefixes but to me it still isn't.  Telling me to re-read your comment carefully doesn't help and is somewhat condescending.  Would you mind clarifying these points.  As an aside I'm not the only one wondering about my original question; the internet is full of forum posts asking exactly the same question but it's not clear.

**Comment by pcaswell** [comment]
Andrew (aka Singku), I guess you either can't answer the question above or are expecting me to re-read your comments again.  If there's something specific you think I'm missing maybe you could point it out.  Otherwise, is there anyone else out there that can help?
