### ISSUE TITLE
Error while building AWS SDK for C++ on CentOS 7.4

### ISSUE THREAD

**Issue by sdjunaidali** [aws/aws-sdk-cpp#1014]
### What platform/OS are you using?
CentOS Linux release 7.4.1708 (Core)

### What compiler are you using? what version?
[root@jsvm11 build]# cmake --version
cmake version 3.6.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
[root@jsvm11 build]# 
[root@jsvm11 build]# gcc --version
gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### What's your CMake arguments?
cmake -DOPENSSL_ROOT_DIR=/usr/local/openssl -DOPENSSL_LIBRARIES=/usr/local/openssl/lib -DCURL_LIBRARY=/usr/bin/curl -DCURL_INCLUDE_DIR=/usr/include/curl/ -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3" ..

### ERROR While Building AWS SDK (For C++) on CentOS 7.4

[ 89%] Building CXX object aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/source/model/UploadPartResult.cpp.o
[ 89%] Building CXX object aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/source/model/VersioningConfiguration.cpp.o
[ 89%] Building CXX object aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/source/model/WebsiteConfiguration.cpp.o
[ 89%] Linking CXX shared library libaws-cpp-sdk-s3.so
/bin/ld: ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: 3AmazonWebServiceRequest25SetContinueRequestHandlerERKSt8functionIFbPKNS_4Http11HttpRequestEEE: invalid version 3 (max 0)
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [aws-cpp-sdk-s3/libaws-cpp-sdk-s3.so] Error 1
make[1]: *** [aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/all] Error 2
make: *** [all] Error 2

Can you guys Please look into it?

**Comment by Bu11etmagnet** [comment]
A quick Google search found this: https://stackoverflow.com/questions/41833767/gcc-invalid-version-max-error-adding-symbols-bad-value
It may or may not be applicable.
