### ISSUE TITLE
1.7.0/1.7.1 won't crosscompile (AwsChecksum in S3)

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-sdk-cpp#1017]
### What platform/OS are you using?
Linux, cross compile to ARM

### What compiler are you using? what version?
gcc

### What's your CMake arguments?
-DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3;sts" -DMINIMIZE_SIZE=ON -DBUILD_SHARED_LIBS=OFF -DTARGET_ARCH=LINUX -DENABLE_TESTING=OFF

### Can you provide a TRACE level log? (sanitize any sensitive information)

Version 1.6.52 builds without problem.

Something is messed up in the paths on the new AwsChecksums. This should not be installing files into my /usr/include directory

[ 72%] Linking C static library libaws-checksums.a
make[6]: Leaving directory `/home/jonsmirl/aosp/lindenis/buildroot/output/build/aws-sdk-cpp-1.7.1/buildroot-build/.deps/build/src/AwsChecksums-build'
[ 72%] Built target aws-checksums
make[6]: Entering directory `/home/jonsmirl/aosp/lindenis/buildroot/output/build/aws-sdk-cpp-1.7.1/buildroot-build/.deps/build/src/AwsChecksums-build'
Scanning dependencies of target aws-checksums-tests
make[6]: Leaving directory `/home/jonsmirl/aosp/lindenis/buildroot/output/build/aws-sdk-cpp-1.7.1/buildroot-build/.deps/build/src/AwsChecksums-build'
make[6]: Entering directory `/home/jonsmirl/aosp/lindenis/buildroot/output/build/aws-sdk-cpp-1.7.1/buildroot-build/.deps/build/src/AwsChecksums-build'
[ 81%] Building C object CMakeFiles/aws-checksums-tests.dir/tests/crc_test.c.o
[ 90%] Building C object CMakeFiles/aws-checksums-tests.dir/tests/run_tests.c.o
[100%] Linking C executable aws-checksums-tests
make[6]: Leaving directory `/home/jonsmirl/aosp/lindenis/buildroot/output/build/aws-sdk-cpp-1.7.1/buildroot-build/.deps/build/src/AwsChecksums-build'
[100%] Built target aws-checksums-tests
make[5]: Leaving directory `/home/jonsmirl/aosp/lindenis/buildroot/output/build/aws-sdk-cpp-1.7.1/buildroot-build/.deps/build/src/AwsChecksums-build'
make[4]: Leaving directory `/home/jonsmirl/aosp/lindenis/buildroot/output/build/aws-sdk-cpp-1.7.1/buildroot-build/.deps/build/src/AwsChecksums-build'
[ 29%] Performing install step for 'AwsChecksums'
make[4]: Entering directory `/home/jonsmirl/aosp/lindenis/buildroot/output/build/aws-sdk-cpp-1.7.1/buildroot-build/.deps/build/src/AwsChecksums-build'
make[5]: Entering directory `/home/jonsmirl/aosp/lindenis/buildroot/output/build/aws-sdk-cpp-1.7.1/buildroot-build/.deps/build/src/AwsChecksums-build'
make[6]: Entering directory `/home/jonsmirl/aosp/lindenis/buildroot/output/build/aws-sdk-cpp-1.7.1/buildroot-build/.deps/build/src/AwsChecksums-build'
make[6]: Leaving directory `/home/jonsmirl/aosp/lindenis/buildroot/output/build/aws-sdk-cpp-1.7.1/buildroot-build/.deps/build/src/AwsChecksums-build'
[ 72%] Built target aws-checksums
make[6]: Entering directory `/home/jonsmirl/aosp/lindenis/buildroot/output/build/aws-sdk-cpp-1.7.1/buildroot-build/.deps/build/src/AwsChecksums-build'
make[6]: Leaving directory `/home/jonsmirl/aosp/lindenis/buildroot/output/build/aws-sdk-cpp-1.7.1/buildroot-build/.deps/build/src/AwsChecksums-build'
[100%] Built target aws-checksums-tests
make[5]: Leaving directory `/home/jonsmirl/aosp/lindenis/buildroot/output/build/aws-sdk-cpp-1.7.1/buildroot-build/.deps/build/src/AwsChecksums-build'
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:41 (file):
  file cannot create directory: /usr/include/aws/checksums.  Maybe need
  administrative privileges.

[toolchainfile.cmake.log](https://github.com/aws/aws-sdk-cpp/files/2596702/toolchainfile.cmake.log)

**Comment by whiplash86** [comment]
You can provide a custom installation path via -DCMAKE_INSTALL_PREFIX=/what/ever, the third_party includes will then end up in /what/ever/include

**Comment by singku** [comment]
Fixed, dependencies will be built and installed automatically.
