### ISSUE TITLE
[API 1.7.2] DateTime::ToGmtString should be named DateTime::ToUtcString

### ISSUE THREAD

**Issue by lilltiger** [aws/aws-sdk-cpp#1018]
The functions are named with the obsolete (since the late 60's) name for the baseline timezone while it would be a better practice to use the correct denotion for it.

So it should be either UT or UTC and not GMT.

**Comment by marcomagdy** [comment]
I agree. However, that would introduce a breaking change (source compatibility wise).
While we do introduce breaking changes from time to time, in this case, the value is not worth the cost.
