### ISSUE TITLE
aws-cpp-sdk-core-tests: error while loading shared libraries: libaws-checksums.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jni2000** [aws/aws-sdk-cpp#1019]
### What platform/OS are you using?
Ubuntu 18.04
### What compiler are you using? what version?
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

### What's your CMake arguments?
cmake ~/workspace/aws/aws-sdk-cpp

OR
cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SHARED_LIBS=ON

### Can you provide a TRACE level log? (sanitize any sensitive information)
[ 99%] Linking CXX executable aws-cpp-sdk-core-tests
./aws-cpp-sdk-core-tests: error while loading shared libraries: libaws-checksums.so: cannot open shared object file: No such file or directory
aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/build.make:1127: recipe for target 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests' failed
make[2]: *** [aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 127
make[2]: *** Deleting file 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests'
CMakeFiles/Makefile2:9505: recipe for target 'aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all' failed
make[1]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wps132230** [comment]
https://github.com/aws/aws-sdk-cpp/issues/1020#issuecomment-441843581
Does this comment helpful for you?

**Comment by axelbodo** [comment]
do temprorily
export LD_LIBRARY_PATH=<YOUR_WORKSPACE>/.deps/install/lib
before your build. Library dependencies, like aws-c-event-stream.so doesn't contain runputh information, so it'll be resoéved against system directories, unless you specify LD_LIBRARY_PATH.
