### ISSUE TITLE
How to get url of uploaded file on s3.

### ISSUE THREAD

**Issue by rpajaziti** [aws/aws-sdk-cpp#1021]
Hello. 
So i have a couple of questions:
1. How to do a public upload of a file.
2. How to get the link of uploaded file.
For these two, should i use ACL, or is there a work around while uploading and after it is uploaded, because when i tried upload via http on s3, i was setting acl on request, and was getting the download link on response.
Here is the code i use to upload the file:
```
  Aws::SDKOptions options;
  options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;
  Aws::InitAPI(options);

  {
    const Aws::String bucket_name = "b";
    const Aws::String key_name = "k";
    const Aws::String file_name = "t";
    const Aws::String region("us-east-1");

    std::shared_ptr < Aws::Utils::Threading::Executor > sdk_client_executor = std::make_shared < Aws::Utils::Threading::DefaultExecutor > ();

    auto s3Client = Aws::MakeShared < Aws::S3::S3Client > ("T", Aws::Auth::AWSCredentials("access_id", "secret_key_id"));
    Aws::Transfer::TransferManagerConfiguration transferConfig(sdk_client_executor.get());
    transferConfig.s3Client = s3Client;

    auto progressPercentage = 0;
    transferConfig.uploadProgressCallback = [ & progressPercentage](const Aws::Transfer::TransferManager * ,
      const std::shared_ptr <
        const Aws::Transfer::TransferHandle > & transferHandle) {
      if (progressPercentage != ((int)(((float) transferHandle - > GetBytesTransferred() / transferHandle - > GetBytesTotalSize()) * 100))) {
        progressPercentage = (int)(((float) transferHandle - > GetBytesTransferred() / transferHandle - > GetBytesTotalSize()) * 100);
        std::cout << "Upload Progress: " << progressPercentage << "%\n";
      }
    };

    transferConfig.transferStatusUpdatedCallback = [](const Aws::Transfer::TransferManager * ,
      const std::shared_ptr <
        const Aws::Transfer::TransferHandle > & transferHandle) {
      std::cout << "Transfer Status = " << (transferHandle - > GetStatus()) << "\n";
    };

    static std::shared_ptr < Aws::Transfer::TransferManager > transferManager = Aws::Transfer::TransferManager::Create(transferConfig);

    std::shared_ptr < Aws::Transfer::TransferHandle > transferHandle = transferManager - > UploadFile(filePath, bucket_name, key_name, "text/plain", Aws::Map < Aws::String, Aws::String > ());

    transferHandle - > WaitUntilFinished();
  }
  Aws::ShutdownAPI(options);          
```

3. This one is an issue which i found a fix for, which means it isn't too important if i don't get an answer, but just want to know why i had an issue with awssdk for c++. 
I am doing a plugin for a 3d app called Rhino(v6). But whenever i tried to do an upload on s3, i was having errors like `Access violation reading location 0xFFFFFFFFFFFFFF01` on this line:
```auto s3Client = Aws::MakeShared<Aws::S3::S3Client>("T", Aws::Auth::AWSCredentials("access_id", "secret_key_id"));```... 
But when i created s3 functions on a separate dll project, and then imported them, they work just fine.

**Comment by rpajaziti** [comment]
I figured out how to upload a file with public_read acl.
But i have one question, i see that file url pattern of uploaded file is as below:
_https://s3.amazonaws.com/{bucket_name}/{key_name}_
Is this URL pattern consistent, or does it ever change?

**Comment by wps132230** [comment]
You can also upload a file privately and generate a pre-signed url for others to download it.
https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html
