### ISSUE TITLE
Window offline build without git pull

### ISSUE THREAD

**Issue by artoka** [aws/aws-sdk-cpp#1023]
Windows cmake build automatically pulls dependencies from the internet with git pull.
Is it possible to set everything so that the build does not require git pull?
Eg: pre download the deps to somewhere so that the build can be done offline.

**Comment by wps132230** [comment]
You can "pre download" the the dependencies, build and install these libraries.
And then when you build SDK, turn off `BUILD_DEPS` in cmake by `-DBUILD_DEPS=OFF`.
You can find more details in this comment: https://github.com/aws/aws-sdk-cpp/issues/1020#issuecomment-441843581
