### ISSUE TITLE
recompile with -fPIC error when linking against libcrypto

### ISSUE THREAD

**Issue by wyoumansUSF** [aws/aws-sdk-cpp#1024]
On Ubuntu 18.04, gcc 7.3, cmake command: `cmake path/to/aws-sdk-cpp-master/ -DBUILD_ONLY="core;dynamodb"`. `make` fails with the following output:

```
...
[ 28%] Linking CXX shared library libaws-cpp-sdk-core.so
/usr/bin/ld: /usr/local/lib/libcrypto.a(cryptlib.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/build.make:1452: recipe for target 'aws-cpp-sdk-core/libaws-cpp-sdk-core.so' failed
make[2]: *** [aws-cpp-sdk-core/libaws-cpp-sdk-core.so] Error 1
CMakeFiles/Makefile2:122: recipe for target 'aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/all' failed
make[1]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

I found this issue: https://github.com/aws/aws-sdk-cpp/issues/77 and tried adding `SET_TARGET_PROPERTIES(${PROJECT_NAME} PROPERTIES COMPILE_FLAGS "-fPIC")` to aws-cpp-sdk-core/CMakeLists.txt, but had the same error.

**Comment by marcomagdy** [comment]
We don't explicitly link to the static version of libcrypto. Have you made any changes to the build script?

**Comment by wyoumansUSF** [comment]
I have not made any changes other than the change to CMakeLists.txt in my original post, after getting this error. When I get a chance I will try again with a fresh download to be sure.

**Comment by wyoumansUSF** [comment]
After a fresh download and run of cmake with the same options/configurations as the original post, I get the same error.

**Comment by singku** [comment]
Would specifying `-DBUILD_SHARED_LIBS=OFF` works for you?
If not, can you rebuild and install openssl? I was wondering why it's not linked to `libcrypto.so`. do you have this library in the searching paths?

**Comment by wyoumansUSF** [comment]
That got me past the error but I reached another. However I noticed I don't even have a `libcrypto.so` so I decided to rebuild and reinstall openssl, making sure to build shared libraries. This resolved the issue, but now I am getting the same issue seen on this issue: https://github.com/aws/aws-sdk-cpp/issues/1020

`make` is failing with output:

```
...
[ 99%] Linking CXX executable aws-cpp-sdk-core-tests
./aws-cpp-sdk-core-tests: error while loading shared libraries: libaws-checksums.so: cannot open shared object file: No such file or directory
aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/build.make:698: recipe for target 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests' failed
make[2]: *** [aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 127
make[2]: *** Deleting file 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests'
CMakeFiles/Makefile2:288: recipe for target 'aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all' failed
make[1]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

I tried adding `-DCMAKE_INSTALL_PREFIX=/usr/local` as a commenter suggested but got the same error. I am reluctant to use `-DENABLE_TESTING=OFF` since someone in that issue mentioned they only encountered more issues later. According to the comments there, It looks like I will have to install aws-c-common, aws-checksums, and aws-c-event-stream manually and play with the install locations, but it seems odd that this isn't in the documentation from what I can tell.

**Comment by marcomagdy** [comment]
Remove the entire build directory and start over and specify a CMAKE_INSTALL_PREFIX when you do a clean build.
There's a hidden `.deps` directory in the build directory. Make sure you remove that too (just incase you decided to not remove the build directory and instead did `rm -rf ./*` from within the build dir

**Comment by webbnh** [comment]
> I tried adding -DCMAKE_INSTALL_PREFIX=/usr/local as a commenter suggested but got the same error.

Beware the CMake cache:  if you simply run CMake a second time, it seems to ignore '-D' switches unless you've done something to invalidate the cache (like deleting the whole build directory).

**Comment by wyoumansUSF** [comment]
Thank you everyone who replied, everything built successfully once I used a fresh build directory. To recap, my original issue was because I did not have the shared libraries for openssl built. Then `make` complained about a missing `libaws-checksums.so`, and using a fresh build directory and the cmake flag `-DCMAKE_INSTALL_PREFIX=/usr/local` solved that issue.
