### ISSUE TITLE
how can I use IoTDataPlane to getThingShadow and UpdateThingShadow?

### ISSUE THREAD

**Issue by shenhuaz** [aws/aws-sdk-cpp#1028]
### What platform/OS are you using?
execute platform: aarch64-linux
Compile OS: Ubuntu 18.04
### What compiler are you using? what version?
linaro-aarch64-linux-7.1.1
### What's your CMake arguments?
cmake .. -DBUILD_ONLY="iot-data"
### Can you provide a TRACE level log? (sanitize any sensitive information)
# # #
I try to use aws-cpp-sdk-iot-data to GetThingShadow and UpdateThingShadow like these:
    std::shared_ptr<Aws::Utils::RateLimits::RateLimiterInterface> Limiter;
    Limiter = Aws::MakeShared<Aws::Utils::RateLimits::DefaultRateLimiter<>>(AWS_TAG.c_str(), 
    50000000);
    Aws::Client::ClientConfiguration config;
    config.region = Aws::Region::US_EAST_1;
    config.scheme = Aws::Http::Scheme::HTTP;
    config.readRateLimiter = Limiter;
    config.writeRateLimiter = Limiter;
    config.connectTimeoutMs = 30000;
    config.requestTimeoutMs = 600000;
    config.verifySSL = false;

    Aws::Auth::AWSCredentials cred(mSecretKeyId.c_str(),mSecretKey.c_str());
    auto iot_client = Aws::IoTDataPlane::IoTDataPlaneClient(cred, config);
    std::cout << "--->IoT data client !" << '\n';

    Aws::IoTDataPlane::Model::GetThingShadowRequest thing_request;
    thing_request.WithThingName(thing_name);

    std::cout << "---> start get Thing document!" << '\n';
    auto getthing_outcome = iot_client.GetThingShadow(thing_request);
    Aws::IoTDataPlane::Model::GetThingShadowResult result = 
    getthing_outcome.GetResultWithOwnership();
But I don't know how to deal with the payload from GetThingShadowResult-->result.GetPayload();
how can I get shadow state from this Aws::IOStream correctly?

And I found that UpdateThingShadowRequest have no arguments to put payload for updating, how can I
use it to update my new shadow state?

**Comment by wps132230** [comment]
1. https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-document-syntax.html
You can get a stream from `result.GetPayload();`, then you can deserialize it with any Json library you like, for example, in C++ SDK, we are using cJSON.
```c++
#include <aws/core/utils/json/JsonSerializer.h>
...
Aws::Utils::Json::JsonValue jsonDocument(result.GetPayload());
if (!jsonDocument.WasParseSuccessful())
{
    std::cout << "Failed to parse payload from GetThingShadowResult" << std::endl;
}
Aws::Utils::Json::JsonView jsonDocumentView(jsonDocument);
Aws::String shadowState = jsonDocumentView.GetString("state");
...
```

2. You can do `updateThingShadowRequest.SetBody(<stream>)` to put payload, which is similar to `putObjectRequest.SetBody(<stream>)` in S3.

**Comment by shenhuaz** [comment]
@wps132230 thank you!
