### ISSUE TITLE
How to login with username and user password

### ISSUE THREAD

**Issue by BBathy** [aws/aws-sdk-cpp#1035]
I use C++ SDK

Below is my code:
![image](https://user-images.githubusercontent.com/45916473/50055186-4cf6d100-0186-11e9-8134-e2dbe4eb76bc.png)
Execution will jump out of the following error:
![image](https://user-images.githubusercontent.com/45916473/50055219-c7275580-0186-11e9-82b4-5d3c13cd942d.png)

I don't know what steps I missed, please tell me. Thank you.

**Comment by wps132230** [comment]
It seems that username and password are used for console login.
To use SDK, you should setup AWS credentials: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html

Is there any special case that you are not able to generate or use credentials and have to use username and password?

**Comment by wps132230** [comment]
Did you setup credentials correctly? For example, did you setup Access Key ID and Secret Access Key? If not, please follow these instructions:
1. Generate Access Keys: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey
2. Setup Access Keys to use C++ SDK: https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/credentials.html

**Comment by BBathy** [comment]
Hi Pushen
I tried to access the key ID and the secret access key was successful, but the feature I have to do is log in with the account password.

**Comment by wps132230** [comment]
Have you tried `authRequest.SetAuthParameters(authParameters);` to provide username and password?

**Comment by BBathy** [comment]
Hi Pushen
Yes,But still fail
![image](https://user-images.githubusercontent.com/45916473/50499452-be872700-0a84-11e9-8a4e-0d392e92313c.png)

**Comment by singku** [comment]
Please try this: https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminInitiateAuth.html#CognitoUserPools-AdminInitiateAuth-request-AuthParameters

**Comment by KaibaLopez** [comment]
I'm closing this issue for now.
If you feel that this did not answer your question feel free to re-open it.
