### ISSUE TITLE
Visual Studio 2017 Build Failure and LNK4217 Warnings

### ISSUE THREAD

**Issue by pmcenery** [aws/aws-sdk-cpp#1039]
### What platform/OS are you using?
Windows 10

### What compiler are you using? what version?
Visual Studio 2017 Community Edition

### What's your CMake arguments?
    C:>
    mkdir aws-sdk-cpp-build
    cd aws-sdk-cpp-build

    cmake -G "Visual Studio 15 2017 Win64" -DBUILD_ONLY="s3;s3-encryption" -DBUILD_SHARED_LIBS=OFF -DFORCE_SHARED_CRT=OFF -DCMAKE_INSTALL_PREFIX="C:\aws-sdk-cpp-build\install" C:\aws-sdk-cpp
    
    msbuild /p:Configuration=Release /p:Platform=x64 INSTALL.vcxproj

### Can you provide a TRACE level log? (sanitize any sensitive information)

The build initially progresses, but ends with the following messages:

[...]
C:\aws-sdk-cpp-build\INSTALL.vcxproj" (default target) (1) ->
"C:\aws-sdk-cpp-build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxp
roj" (default target) (12) ->
  aws-c-event-stream.lib(event_stream.obj) : error LNK2019: unresolved external symbol __imp
__wassert referenced in function aws_array_list_length [C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-
integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-common.lib(error.obj) : error LNK2001: unresolved external symbol __imp__wassert [C:
\aws-sdk-cpp-build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj
]
  aws-c-common.lib(array_list.obj) : error LNK2001: unresolved external symbol __imp__wasser
t [C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vc
xproj]
  aws-c-common.lib(encoding.obj) : error LNK2001: unresolved external symbol __imp__wassert
[C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxp
roj]
  C:\aws-sdk-cpp-build\bin\Release\aws-cpp-sdk-s3-integration-tests.exe : fatal error LNK112
0: 1 unresolved externals [C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk
-s3-integration-tests.vcxproj]

48 Warning(s)
20 Error(s)

The issue appears to be that the INSTALL.vcxproj does not build the depedencies first. I have managed to work around this by doing the following after running `cmake`:

`msbuild /p:Configuration=Release /p:Platform=x64 .deps\ALL_BUILD.vcxproj`
`msbuild /p:Configuration=Release /p:Platform=x64 INSTALL.vcxproj`

This seems to solve the build situation, but I have noticed the following warnings when the INSTALL.vcxproj msbuild (step 2 above) completes:

[...]
"C:\aws-sdk-cpp-build\INSTALL.vcxproj" (default target) (1) ->
"C:\aws-sdk-cpp-build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxp
roj" (default target) (12) ->
  LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAU
LTLIB:library [C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integrat
ion-tests.vcxproj]
  aws-c-event-stream.lib(event_stream.obj) : warning LNK4217: locally defined symbol fwrite
imported in function aws_event_stream_message_to_debug_str [C:\aws-sdk-cpp-build\aws-cpp-sdk
-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-event-stream.lib(event_stream.obj) : warning LNK4217: locally defined symbol __stdio
_common_vfprintf imported in function fprintf [C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-integrati
on-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-common.lib(error.obj) : warning LNK4049: locally defined symbol __stdio_common_vfpri
ntf imported [C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integrati
on-tests.vcxproj]
  aws-c-event-stream.lib(event_stream.obj) : warning LNK4217: locally defined symbol __stdio
_common_vsprintf imported in function snprintf [C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-integrat
ion-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-common.lib(common.obj) : warning LNK4217: locally defined symbol free imported in fu
nction s_default_free [C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-
integration-tests.vcxproj]
  aws-c-common.lib(common.obj) : warning LNK4217: locally defined symbol malloc imported in
function s_default_malloc [C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk
-s3-integration-tests.vcxproj]
  aws-c-common.lib(common.obj) : warning LNK4217: locally defined symbol realloc imported in
 function s_default_realloc [C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-integration-tests\aws-cpp-s
dk-s3-integration-tests.vcxproj]
  aws-c-common.lib(error.obj) : warning LNK4217: locally defined symbol __acrt_iob_func impo
rted in function aws_register_error_info [C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-integration-te
sts\aws-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-common.lib(error.obj) : warning LNK4217: locally defined symbol abort imported in fu
nction aws_register_error_info [C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-integration-tests\aws-cp
p-sdk-s3-integration-tests.vcxproj]
  aws-c-common.lib(cpuid.obj) : warning LNK4217: locally defined symbol atoi imported in fun
ction aws_common_private_has_avx2 [C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-integration-tests\aws
-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-common.lib(cpuid.obj) : warning LNK4217: locally defined symbol getenv imported in f
unction aws_common_private_has_avx2 [C:\aws-sdk-cpp-build\aws-cpp-sdk-s3-integration-tests\a
ws-cpp-sdk-s3-integration-tests.vcxproj]

48 Warning(s)
0 Error(s)

When I compile my project, I have the same warnings above which leads me to believe that the dependency builds are ignoring the `-DBUILD_SHARED_LIBS=OFF` which was specified. I might be wrong, but this is what my research on the LNK4217 has pointed me towards. Has anyone else had this problem?

**Comment by pmcenery** [comment]
Following further investigation, the warnings only appear if `aws-sdk-cpp` is built with the following `cmake` flag:

`-DFORCE_SHARED_CRT=OFF`

My project is building static linked, and therefore requires these flags (/MT instead of /MD).

**Comment by singku** [comment]
Would you please update SDK to latest and try again?

**Comment by pmcenery** [comment]
Thanks for the update @singku .

I have pulled and tested the same build procedure described above, but there are still the same 48 warnings - mainly `warning LNK4217: locally defined symbol`. I looked through the changelogs, but didn't see anything specific to try and address this.

**Comment by pmcenery** [comment]
Thanks for the response @singku . I should have seen that. I think I might have lost the option in my attempts to put together a test case to report this issue. It was originally part of my build process. Unfortunately this doesnt seem to be the source of the warnings.

I have tested building the SDK with `-DCMAKE_BUILD_TYPE=Release`, but the warnings are still produced. For completeness, here are the correctly formatted complete list of 48 warnings which you will get if you add the `-DFORCE_SHARED_CRT=OFF` flag:

```
Build succeeded.

"C:\sdk_build\INSTALL.vcxproj" (default target) (1) ->
"C:\sdk_build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\sdk_build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj" (default target) (5) -> (Link target) -> LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library [C:\sdk_build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
  aws-c-event-stream.lib(event_stream.obj) : warning LNK4217: locally defined symbol fwrite imported in function aws_event_stream_message_to_debug_str [C:\sdk_build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
  aws-c-event-stream.lib(event_stream.obj) : warning LNK4217: locally defined symbol __stdio_common_vfprintf imported in function fprintf [C:\sdk_build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
  aws-c-common.lib(error.obj) : warning LNK4049: locally defined symbol __stdio_common_vfprintf imported [C:\sdk_build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
  aws-c-event-stream.lib(event_stream.obj) : warning LNK4217: locally defined symbol __stdio_common_vsprintf imported in function snprintf [C:\sdk_build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
  aws-c-common.lib(error.obj) : warning LNK4217: locally defined symbol __acrt_iob_func imported in function aws_register_error_info [C:\sdk_build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
  aws-c-common.lib(error.obj) : warning LNK4217: locally defined symbol abort imported in function aws_register_error_info [C:\sdk_build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
  aws-c-common.lib(common.obj) : warning LNK4217: locally defined symbol free imported in function s_default_free [C:\sdk_build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
  aws-c-common.lib(common.obj) : warning LNK4217: locally defined symbol malloc imported in function s_default_malloc [C:\sdk_build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
  aws-c-common.lib(common.obj) : warning LNK4217: locally defined symbol realloc imported in function s_default_realloc [C:\sdk_build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
  aws-c-common.lib(cpuid.obj) : warning LNK4217: locally defined symbol atoi imported in function aws_common_private_has_avx2 [C:\sdk_build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
  aws-c-common.lib(cpuid.obj) : warning LNK4217: locally defined symbol getenv imported in function aws_common_private_has_avx2 [C:\sdk_build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]


"C:\sdk_build\INSTALL.vcxproj" (default target) (1) -> 
"C:\sdk_build\ALL_BUILD.vcxproj" (default target) (3) -> 
"C:\sdk_build\aws-cpp-sdk-s3-encryption-integration-tests\aws-cpp-sdk-s3-encryption-integration-tests.vcxproj" (default target) (10) ->
  LIBCMT.lib(initializers.obj) : warning LNK4098: defaultlib 'msvcrt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library [C:\sdk_build\aws-cpp-sdk-s3-encryption-integration-tests\aws-cpp-sdk-s3-encryption-integration-tests.vcxproj]
  aws-c-event-stream.lib(event_stream.obj) : warning LNK4217: locally defined symbol fwriteimported in function aws_event_stream_message_to_debug_str [C:\sdk_build\aws-cpp-sdk-s3-encryption-integration-tests\aws-cpp-sdk-s3-encryption-integration-tests.vcxproj]
  aws-c-event-stream.lib(event_stream.obj) : warning LNK4217: locally defined symbol __stdio_common_vfprintf imported in function fprintf [C:\sdk_build\aws-cpp-sdk-s3-encryption-integration-tests\aws-cpp-sdk-s3-encryption-integration-tests.vcxproj]
  aws-c-common.lib(error.obj) : warning LNK4049: locally defined symbol __stdio_common_vfprintf imported [C:\sdk_build\aws-cpp-sdk-s3-encryption-integration-tests\aws-cpp-sdk-s3-encryption-integration-tests.vcxproj]
  aws-c-event-stream.lib(event_stream.obj) : warning LNK4217: locally defined symbol __stdio_common_vsprintf imported in function snprintf [C:\sdk_build\aws-cpp-sdk-s3-encryption-integration-tests\aws-cpp-sdk-s3-encryption-integration-tests.vcxproj]
  aws-c-common.lib(common.obj) : warning LNK4217: locally defined symbol free imported in function s_default_free [C:\sdk_build\aws-cpp-sdk-s3-encryption-integration-tests\aws-cpp-sdk-s3-encryption-integration-tests.vcxproj]
  aws-c-common.lib(common.obj) : warning LNK4217: locally defined symbol malloc imported infunction s_default_malloc [C:\sdk_build\aws-cpp-sdk-s3-encryption-integration-tests\aws-cpp-sdk-s3-encryption-integration-tests.vcxproj]
  aws-c-common.lib(common.obj) : warning LNK4217: locally defined symbol realloc imported in function s_default_realloc [C:\sdk_build\aws-cpp-sdk-s3-encryption-integration-tests\aws-cpp-sdk-s3-encryption-integration-tests.vcxproj]
  aws-c-common.lib(error.obj) : warning LNK4217: locally defined symbol __acrt_iob_func imported in function aws_register_error_info [C:\sdk_build\aws-cpp-sdk-s3-encryption-integration-tests\aws-cpp-sdk-s3-encryption-integration-tests.vcxproj]
  aws-c-common.lib(error.obj) : warning LNK4217: locally defined symbol abort imported in function aws_register_error_info [C:\sdk_build\aws-cpp-sdk-s3-encryption-integration-tests\aws-cpp-sdk-s3-encryption-integration-tests.vcxproj]
  aws-c-common.lib(cpuid.obj) : warning LNK4217: locally defined symbol atoi imported in function aws_common_private_has_avx2 [C:\sdk_build\aws-cpp-sdk-s3-encryption-integration-tests\aws-cpp-sdk-s3-encryption-integration-tests.vcxproj]
  aws-c-common.lib(cpuid.obj) : warning LNK4217: locally defined symbol getenv imported in function aws_common_private_has_avx2 [C:\sdk_build\aws-cpp-sdk-s3-encryption-integration-tests\aws-cpp-sdk-s3-encryption-integration-tests.vcxproj]


"C:\sdk_build\INSTALL.vcxproj" (default target) (1) ->
"C:\sdk_build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\sdk_build\aws-cpp-sdk-s3-encryption-tests\aws-cpp-sdk-s3-encryption-tests.vcxproj" (default target) (11) ->
  LIBCMT.lib(initializers.obj) : warning LNK4098: defaultlib 'msvcrt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library [C:\sdk_build\aws-cpp-sdk-s3-encryption-tests\aws-cpp-sdk-s3-encryption-tests.vcxproj] 
  aws-c-event-stream.lib(event_stream.obj) : warning LNK4217: locally defined symbol fwriteimported in function aws_event_stream_message_to_debug_str [C:\sdk_build\aws-cpp-sdk-s3-encryption-tests\aws-cpp-sdk-s3-encryption-tests.vcxproj]
  aws-c-event-stream.lib(event_stream.obj) : warning LNK4217: locally defined symbol __stdio_common_vfprintf imported in function fprintf [C:\sdk_build\aws-cpp-sdk-s3-encryption-tests\aws-cpp-sdk-s3-encryption-tests.vcxproj]
  aws-c-common.lib(error.obj) : warning LNK4049: locally defined symbol __stdio_common_vfprintf imported [C:\sdk_build\aws-cpp-sdk-s3-encryption-tests\aws-cpp-sdk-s3-encryption-tests.vcxproj]
  aws-c-event-stream.lib(event_stream.obj) : warning LNK4217: locally defined symbol __stdio_common_vsprintf imported in function snprintf [C:\sdk_build\aws-cpp-sdk-s3-encryption-tests\aws-cpp-sdk-s3-encryption-tests.vcxproj]
  aws-c-common.lib(common.obj) : warning LNK4217: locally defined symbol free imported in function s_default_free [C:\sdk_build\aws-cpp-sdk-s3-encryption-tests\aws-cpp-sdk-s3-encryption-tests.vcxproj]
  aws-c-common.lib(common.obj) : warning LNK4217: locally defined symbol malloc imported infunction s_default_malloc [C:\sdk_build\aws-cpp-sdk-s3-encryption-tests\aws-cpp-sdk-s3-encryption-tests.vcxproj]
  aws-c-common.lib(common.obj) : warning LNK4217: locally defined symbol realloc imported in function s_default_realloc [C:\sdk_build\aws-cpp-sdk-s3-encryption-tests\aws-cpp-sdk-s3-encryption-tests.vcxproj]
  aws-c-common.lib(error.obj) : warning LNK4217: locally defined symbol __acrt_iob_func imported in function aws_register_error_info [C:\sdk_build\aws-cpp-sdk-s3-encryption-tests\aws-cpp-sdk-s3-encryption-tests.vcxproj]
  aws-c-common.lib(error.obj) : warning LNK4217: locally defined symbol abort imported in function aws_register_error_info [C:\sdk_build\aws-cpp-sdk-s3-encryption-tests\aws-cpp-sdk-s3-encryption-tests.vcxproj]
  aws-c-common.lib(cpuid.obj) : warning LNK4217: locally defined symbol atoi imported in function aws_common_private_has_avx2 [C:\sdk_build\aws-cpp-sdk-s3-encryption-tests\aws-cpp-sdk-s3-encryption-tests.vcxproj]
  aws-c-common.lib(cpuid.obj) : warning LNK4217: locally defined symbol getenv imported in function aws_common_private_has_avx2 [C:\sdk_build\aws-cpp-sdk-s3-encryption-tests\aws-cpp-sdk-s3-encryption-tests.vcxproj]


"C:\sdk_build\INSTALL.vcxproj" (default target) (1) ->
"C:\sdk_build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\sdk_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj" (default target) (12) ->
  LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library [C:\sdk_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-event-stream.lib(event_stream.obj) : warning LNK4217: locally defined symbol fwriteimported in function aws_event_stream_message_to_debug_str [C:\sdk_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-event-stream.lib(event_stream.obj) : warning LNK4217: locally defined symbol __stdio_common_vfprintf imported in function fprintf [C:\sdk_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-common.lib(error.obj) : warning LNK4049: locally defined symbol __stdio_common_vfprintf imported [C:\sdk_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-event-stream.lib(event_stream.obj) : warning LNK4217: locally defined symbol __stdio_common_vsprintf imported in function snprintf [C:\sdk_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-common.lib(common.obj) : warning LNK4217: locally defined symbol free imported in function s_default_free [C:\sdk_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-common.lib(common.obj) : warning LNK4217: locally defined symbol malloc imported infunction s_default_malloc [C:\sdk_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-common.lib(common.obj) : warning LNK4217: locally defined symbol realloc imported in function s_default_realloc [C:\sdk_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-common.lib(error.obj) : warning LNK4217: locally defined symbol __acrt_iob_func imported in function aws_register_error_info [C:\sdk_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-common.lib(error.obj) : warning LNK4217: locally defined symbol abort imported in function aws_register_error_info [C:\sdk_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-common.lib(cpuid.obj) : warning LNK4217: locally defined symbol atoi imported in function aws_common_private_has_avx2 [C:\sdk_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
  aws-c-common.lib(cpuid.obj) : warning LNK4217: locally defined symbol getenv imported in function aws_common_private_has_avx2 [C:\sdk_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]

    48 Warning(s)
    0 Error(s)

Time Elapsed 00:08:48.04
```

Has anyone else tried building with `-DFORCE_SHARED_CRT=OFF`?

**Comment by singku** [comment]
Do you mean there is no problem if you don't touch Force_shared_crt?

**Comment by pmcenery** [comment]
> Do you mean there is no problem if you don't touch Force_shared_crt?

Correct. No warnings at all, BUT - if you do this, then you can't static link your projects against the SDK. The compiler will complain about linking /MT vs /MD. In order to static link against it, you must build the SDK with `-DFORCE_SHARED_CRT=OFF`.

This only became an issue when dependencies were introduced a while ago.

**Comment by singku** [comment]
It turns out to be a discrepancy of C_FLAGS setting between CPP SDK and dependencies. Will fix it soon.

**Comment by pmcenery** [comment]
Thanks @singku 

I see the fix in aws-c-common. Any chance aws-sdk-cpp can be updated to checkout a newer commit/tag which contains the fix?

**Comment by singku** [comment]
Will update the commit ASAP. Thanks for the reminder.

**Comment by WolfgangVogl** [comment]
Does it mean that's "normal" until now to get the linker errors when doing a release build?
