### ISSUE TITLE
Cross complie on  mips Linux 

### ISSUE THREAD

**Issue by Shawn-115200** [aws/aws-sdk-cpp#1040]
### What platform/OS are you using?
Host PC OS：Ubuntu 12.04
target_SOC：MT7628AN；   target_OS:  openwrt(chaos_calmer Version)

### What compiler are you using? what version?
Cross-compile  GCC Version 4.9.3
Cross-compile cmake Version : 3.7.2
had compiled  openssl, libcurl,  libz;

### What's your CMake arguments?
MTK_INC="/work/cc/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include"
MTK_LIB="/work/cc/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib"
MTK_SSL=$MTK_LIB/libcrypto.so
MTK_LIBZ=$MTK_LIB/libz.so
MTK_LIBCURL=$MTK_LIB/libcurl.so
MTK_GCC=mipsel-openwrt-linux-uclibc-gcc
MTK_GPP=mipsel-openwrt-linux-uclibc-g++
MTK_TOOLCHAIN="/work/cc/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.9-linaro_uClibc-0.9.33.2/bin"
export PATH=$PATH:$MTK_TOOLCHAIN
/work/cc/staging_dir/host/bin/cmake \
        -DCMAKE_SYSTEM_NAME=Linux \
        -DCMAKE_FIND_ROOT_PATH=$MTK_TOOLCHAIN \
        -DCMAKE_TOOLCHAIN_FILE=$MTK_TOOLCHAIN \
        -DCMAKE_C_COMPILER=$MTK_GCC \
        -DCMAKE_CXX_COMPILER=$MTK_GPP \
        -DOPENSSL_INCLUDE_DIR=$MTK_INC -DOPENSSL_LIBRARIES=$MTK_LIB -DOPENSSL_SSL_LIBRARY=$MTK_SSL \
        -DZLIB_INCLUDE_DIR=$MTK_INC    -DZLIB_LIBRARY=$MTK_LIB  -DZLIB_LIBRARY_RELEASE=$MTK_LIBZ \
        -DCURL_INCLUDE_DIR=$MTK_INC    -DCURL_LIBRARY=$MTK_LIB \
        -DTARGET_ARCH=LINUX \
        -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY\
        -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY\
        CMakeLists.txt

### Can you provide a TRACE level log? (sanitize any sensitive information)
-- Building AWS libraries as shared objects
-- Generating linux build config
-- Building project version: 1.7.28
-- Configuring done
-- Generating done
-- Build files have been written to: /work/cc/package/test/aws-sdk-cpp-CC/.deps
[ 33%] Built target AwsCCommon
[ 66%] Built target AwsChecksums
[100%] Built target AwsCEventStream
-- Third-party dependencies are installed at: /usr/local
--   Zlib include directory: /work/cc/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include
--   Zlib library: /work/cc/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib
-- Encryption: Openssl
--   Openssl include directory: /work/cc/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include
--   Openssl library: /work/cc/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libcrypto.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Http client: Curl
--   Curl include directory: /work/cc/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include
--   Curl library: /work/cc/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib
-- Updating version info to 1.7.28
-- Custom memory management enabled; stl objects now using custom allocators
CMake Warning at aws-cpp-sdk-text-to-speech/CMakeLists.txt:31 (message):
  We've detected that you are building on linux, but the header files for
  pulseaudio are not available.  If you are providing your own audio
  implementation or you will not be using the text-to-speech library, this is
  fine.  However, if you are not providing your own implemenation and you
  want to use text-to-speech, you need to install the dev files for
  pulseAudio.  e.g.  apt-get install libpulse-dev or yum install
  pulseaudio-libs-devel.  Currently, no audio implementation will be built
  into this library.

-- Configuring done
WARNING: Target "aws-cpp-sdk-core" requests linking to directory "/work/cc/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "aws-cpp-sdk-core" requests linking to directory "/work/cc/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /work/cc/package/test/aws-sdk-cpp-CC

====================================================================
after run make command;

Scanning dependencies of target aws-cpp-sdk-core
[  0%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/platform/linux-shared/FileSystem.cpp.o
mipsel-openwrt-linux-uclibc-g++: warning: environment variable 'STAGING_DIR' not defined
/work/cc/package/test/aws-sdk-cpp-CC/aws-cpp-sdk-core/source/platform/linux-shared/FileSystem.cpp: In function 'bool Aws::FileSystem::RelocateFileOrDirectory(const char*, const char*)':
/work/cc/package/test/aws-sdk-cpp-CC/aws-cpp-sdk-core/source/platform/linux-shared/FileSystem.cpp:252:21: error: 'rename' is not a member of 'std'
     int errorCode = std::rename(from, to);
                     ^
make[2]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/platform/linux-shared/FileSystem.cpp.o] error 1
make[1]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/all] error 2
make: *** [all] error 2

**Comment by singku** [comment]
Would update SDK to latest and add `#include <cstdio>` in 
aws-cpp-sdk-core/source/platform/linux-shared/FileSystem.cpp solve your problem?

**Comment by ShawnPlanA** [comment]
```
Hello, I using this command;

First Step: 
rm  -rf  .deps/  CMakeCache.txt  CMakeFiles/

STAGING_DIR="/home/work/cc/staging_dir"
MTK_INC="$STAGING_DIR/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include"
MTK_LIB="$STAGING_DIR/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib"
MTK_SSL=$MTK_LIB/libcrypto.so
MTK_LIBZ=$MTK_LIB/libz.so
MTK_LIBCURL=$MTK_LIB/libcurl.so

MTK_GCC="$STAGING_DIR/toolchain-mipsel_24kec+dsp_gcc-4.9-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-gcc"
MTK_GPP="$STAGING_DIR/toolchain-mipsel_24kec+dsp_gcc-4.9-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-g++"

$STAGING_DIR/host/bin/cmake  \
	-DCMAKE_SYSTEM_NAME=Linux  \
	-DCMAKE_C_COMPILER=$MTK_GCC \
	-DCMAKE_CXX_COMPILER=$MTK_GPP \
	-DTARGET_ARCH=LINUX \
	-DOPENSSL_INCLUDE_DIR=$MTK_INC -DOPENSSL_ROOT_DIR=$MTK_LIB -DOPENSSL_LIBRARIES=$MTK_LIB -DOPENSSL_SSL_LIBRARY=$MTK_SSL \
	-DZLIB_INCLUDE_DIR=$MTK_INC -DZLIB_LIBRARY=$MTK_LIB -DZLIB_LIBRARY_RELEASE=$MTK_LIBZ \
	-DCURL_INCLUDE_DIR=$MTK_INC -DCURL_LIBRARY=$MTK_LIB \
	-DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
	-DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
	CMakeLists.txt

--------------------------------------
(after run command,  output  this message on the screen)

-- Looking for include file pulse/simple.h
-- Looking for include file pulse/simple.h - found
-- Pulse audio header files have been detected, included pulse audio as a possible sound driver implementation.
-- Configuring done
WARNING: Target "aws-cpp-sdk-core" requests linking to directory "/home/work/cc/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "aws-cpp-sdk-core" requests linking to directory "/home/work/cc/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /home/work/cc/package/test/aws-sdk-cpp/src

===================================
Second Step: 
run command:    make

--------------------------------------
(after run command,  output  this message on the screen)
mipsel-openwrt-linux-uclibc-g++: warning: environment variable 'STAGING_DIR' not defined
[  0%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/http/URI.cpp.o
mipsel-openwrt-linux-uclibc-g++: warning: environment variable 'STAGING_DIR' not defined
[  0%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/external/cjson/cJSON.cpp.o
mipsel-openwrt-linux-uclibc-g++: warning: environment variable 'STAGING_DIR' not defined
[  0%] Linking CXX shared library libaws-cpp-sdk-core.so
mipsel-openwrt-linux-uclibc-g++: warning: environment variable 'STAGING_DIR' not defined
mipsel-openwrt-linux-uclibc-g++: warning: environment variable 'STAGING_DIR' not defined
../.deps/install/lib/libaws-c-event-stream.so.1.0.0: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [aws-cpp-sdk-core/libaws-cpp-sdk-core.so] error 1
make[1]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/all] error 2
make: *** [all] error 2


readelf -h .deps/install/lib/libaws-c-event-stream.so.1.0.0;   this binary file Architecture is "Advanced Micro Devices X86-64"

readelf -h  aws-sdk-cpp/src/aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/net/linux-shared/Net.cpp.o ;     this binary file Architecture is     "MIPS R3000"
```

**Comment by ShawnPlanA** [comment]
```
it is new version of aws 
 git log
commit   1e1fdc0bbc95e87ce68b755146f7766782ce475d
```

**Comment by singku** [comment]
I suspect this is caused by SDK doesn't pass some of the CMake command-line arguments to underlying 3rd-party dependencies. Can you post all output including those building 3rd-party dependencies?

**Comment by singku** [comment]
@ShawnPlanA Would cross compile aws-c-common aws-checksums and aws-c-event-stream then specify the install location and specify BUILD_DEPS=OFF solve your problem?
`-DCMAKE_PREFIX_PATH=<deps-install-dir> -DBUILD_DEPS=OFF`
