### ISSUE TITLE
'clock_t': is not a member of '`global namespace'' and symbol cannot be used in a using-declaration on UE4

### ISSUE THREAD

**Issue by NorsfellRegis** [aws/aws-sdk-cpp#1041]
Hi,

I try to use the Gamelift C++ SDK in my UE4 project. I have followed this steps: 

mkdir out 
cd out
cmake -G "Visual Studio 15 2017 Win64" .. -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="gamelift"

When builded these files are generated:

out\bin\Release\aws-cpp-sdk-gamelift.dll
out\bin\Release\aws-cpp-sdk-core.dll
out\aws-cpp-sdk-gamelift\Release\aws-cpp-sdk-gamelift.lib
out\aws-cpp-sdk-core\Release\aws-cpp-sdk-core.lib

I have added this files to my UE4 project. All seems ok but when I try to compile I have this errors:
2>  [4/7] Module.AWSCore.cpp
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(10): error C2039: 'clock_t': is not a member of '`global namespace''
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(10): error C2873: 'clock_t': symbol cannot be used in a using-declaration
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(12): error C2039: 'asctime': is not a member of '`global namespace''
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(12): error C2873: 'asctime': symbol cannot be used in a using-declaration
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(12): error C2039: 'clock': is not a member of '`global namespace''
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(12): error C2873: 'clock': symbol cannot be used in a using-declaration
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(12): error C2039: 'ctime': is not a member of '`global namespace''
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(12): error C2873: 'ctime': symbol cannot be used in a using-declaration
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(13): error C2039: 'difftime': is not a member of '`global namespace''
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(13): error C2873: 'difftime': symbol cannot be used in a using-declaration
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(13): error C2039: 'gmtime': is not a member of '`global namespace''
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(13): error C2873: 'gmtime': symbol cannot be used in a using-declaration
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(13): error C2039: 'localtime': is not a member of '`global namespace''
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(13): error C2873: 'localtime': symbol cannot be used in a using-declaration
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(14): error C2039: 'mktime': is not a member of '`global namespace''
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(14): error C2873: 'mktime': symbol cannot be used in a using-declaration
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(14): error C2039: 'strftime': is not a member of '`global namespace''
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(14): error C2873: 'strftime': symbol cannot be used in a using-declaration
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(14): error C2039: 'time': is not a member of '`global namespace''
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\INCLUDE\ctime(14): error C2873: 'time': symbol cannot be used in a using-declaration
2>UnrealBuildTool : error : UBT ERROR: Failed to produce item: D:\Projects\Unreal\DedicatedServerDemos\Game\Plugins\GameLiftClientSDK\Intermediate\Build\Win64\UE4Editor\Development\AWSCore\UE4Editor-AWSCore.lib

Have I missed something ?

Best regards,
 Régis

**Comment by singku** [comment]
We don't have any information about your project. So... It's hard to tell. Are you able to share some information about your project and settings?

**Comment by NorsfellRegis** [comment]
Thank you for the answer. 

You just have to follow the previous steps to reproduce the issue. It's 100% reproductable :

mkdir out
cd out
cmake -G "Visual Studio 15 2017 Win64" .. -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="gamelift"

Add this files to any Unreal project :
out\bin\Release\aws-cpp-sdk-gamelift.dll
out\bin\Release\aws-cpp-sdk-core.dll
out\aws-cpp-sdk-gamelift\Release\aws-cpp-sdk-gamelift.lib
out\aws-cpp-sdk-core\Release\aws-cpp-sdk-core.lib

You will be able to see the error.

**Comment by kreivi** [comment]
I encountered the same problem and managed to get the core module to compile by removing `aws/core/platform/Time.h` header file. However I'm pretty sure this is not the proper way to _"fix"_ the problem but rather something to narrow the problem down.

`Time.h` header also has `#include <ctime>` and all the errors seem to relate to `ctime` somehow.

**Comment by wukakuki** [comment]
you can use [this](https://forums.unrealengine.com/community/community-content-tools-and-tutorials/1585349-aws-game-lift-client-server-blueprint-plugin-with-blueprint-support).

**Comment by singku** [comment]
@NorsfellRegis  Drag those dll/lib into your project won't trigger anything. Which headers did you used from SDK?

**Comment by singku** [comment]
See https://github.com/aws/aws-sdk-cpp/pull/878

**Comment by zhangweilong2022** [comment]
aad #include<..\ucrt\time.h> to first line of cpp file,then it will be fixed!

**Comment by zhangweilong2022** [comment]
add #include<..\ucrt\time.h> to first line of cpp file,then it will be fixed!
