### ISSUE TITLE
Is it possible to build aws sdk cpp with visual studio 13?

### ISSUE THREAD

**Issue by suryanshagnihotri** [aws/aws-sdk-cpp#1043]
### What platform/OS are you using?
Windows 10

### What compiler are you using? what version?
Visual Studio 13 (MSVC)

### What's your CMake arguments?
cmake -DBUILD_ONLY="s3" ../aws-sdk-cpp/ is used from sdk_build directory (new empty dir)

### Can you provide a TRACE level log? (sanitize any sensitive information)
[output.txt](https://github.com/aws/aws-sdk-cpp/files/2749142/output.txt)

**Comment by wps132230** [comment]
Do you mean Visual Studio 2013?
We do support this platform previously, but no longer support it right now because VS 2013 does not support full C++11 features very well.

**Comment by suryanshagnihotri** [comment]
Yes I meant [Visual Studio Community 2013 with Update 5](https://my.visualstudio.com/Downloads?q=visual%20studio%202013&wt.mc_id=o~msft~vscom~older-downloads) 
So does that mean we have to upgrade to new visual studio? Is that the only option?

**Comment by JonathanHenson** [comment]
There’s nothing that will prevent you from running cmake with the “visual studio 2013 win64” generator and trying a build. If it builds then you’re good. We just don’t officially support (meaning fix things that don’t work) it.
