### ISSUE TITLE
Android build failure with error ".../AwsCCommon/include/aws/common/math.fallback.inl:68:2: error: no newline at end of file [-Werror,-Wnewline-eof]"

### ISSUE THREAD

**Issue by triton3** [aws/aws-sdk-cpp#1047]
### What platform/OS are you using?
macOS 10.14.2
cmake version 3.13.3

### AWS Source Used
Commit  430d026  

### What compiler are you using? what version?
Clang 3.8.256229

### What's your CMake arguments?
        
        export ANDROID_NDK="/Users/dev/android/android-ndk-r12b"

        /Applications/CMake.app/Contents/bin/cmake  -Wno-dev \
        -DTARGET_ARCH=ANDROID \
        -DANDROID_ABI="armeabi-v7a" \
        -DCMAKE_BUILD_TYPE=Release \
        -DNDK_DIR=$ANDROID_NDK \
        -DBUILD_SHARED_LIBS=1 \
        -DCUSTOM_MEMORY_MANAGEMENT=0 \
        -DBUILD_ONLY="sts;lambda;identity-management;dynamodb;cognito-identity;cognito-idp;email;sns;s3" \
        ../aws-sdk-cpp

### Can you provide a TRACE level log? (sanitize any sensitive information)

    -- Found Git: /usr/bin/git (found version "2.17.2 (Apple Git-113)") 
    -- Building AWS libraries as shared objects
    -- Android ABI: armeabi-v7a
    -- Android toolchain unspecified, defaulting to standalone-clang
    -- Android std lib: libc++_shared
    -- Android API level: android-21
    -- Detected NDK version r12b
    -- Could not find an appropriate standalone toolchain.  Generating one into .../aws/jan-14-2019/android/buildOutput/Release/armeabi-v7a/toolchains/android/armeabi-v7a-standalone-clang-android-21-libc++_shared-12002
    fatal: not a git repository: '.../aws/jan-14-2019/aws-sdk-cpp/.git'
    -- Building project version: 1.7.35
    -- The C compiler identification is Clang 3.8.256229
    -- The CXX compiler identification is Clang 3.8.256229
    -- Check for working C compiler: .../aws/jan-14-2019/android/buildOutput/Release/armeabi-v7a/toolchains/android/armeabi-v7a-standalone-clang-android-21-libc++_shared-12002/bin/clang38
    -- Check for working C compiler: .../aws/jan-14-2019/android/buildOutput/Release/armeabi-v7a/toolchains/android/armeabi-v7a-standalone-clang-android-21-libc++_shared-12002/bin/clang38 -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: .../aws/jan-14-2019/android/buildOutput/Release/armeabi-v7a/toolchains/android/armeabi-v7a-standalone-clang-android-21-libc++_shared-12002/bin/clang38++
    -- Check for working CXX compiler: .../aws/jan-14-2019/android/buildOutput/Release/armeabi-v7a/toolchains/android/armeabi-v7a-standalone-clang-android-21-libc++_shared-12002/bin/clang38++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: .../aws/jan-14-2019/android/buildOutput/Release/armeabi-v7a/.deps
    Scanning dependencies of target AwsCCommon
    [  4%] Creating directories for 'AwsCCommon'
    [  8%] Performing download step (git clone) for 'AwsCCommon'
    Cloning into 'AwsCCommon'...
    Note: checking out 'v0.3.0'.
    
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:
    
      git checkout -b <new-branch-name>
    
    HEAD is now at 67262a9 aws_task_run(#228)
    [ 12%] No patch step for 'AwsCCommon'
    [ 16%] No update step for 'AwsCCommon'
    [ 20%] Performing configure step for 'AwsCCommon'
    -- The C compiler identification is Clang 3.8.256229
    -- Check for working C compiler: .../aws/jan-14-2019/android/buildOutput/Release/armeabi-v7a/toolchains/android/armeabi-v7a-standalone-clang-android-21-libc++_shared-12002/bin/clang38
    -- Check for working C compiler: .../aws/jan-14-2019/android/buildOutput/Release/armeabi-v7a/toolchains/android/armeabi-v7a-standalone-clang-android-21-libc++_shared-12002/bin/clang38 -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Performing Test AWS_HAVE_GCC_INLINE_ASM
    -- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
    -- Performing Test HAVE_M_AVX2_FLAG
    -- Performing Test HAVE_M_AVX2_FLAG - Success
    -- Performing Test HAVE_AVX2_INTRINSICS
    -- Performing Test HAVE_AVX2_INTRINSICS - Failed
    -- Performing Test HAVE_MM256_EXTRACT_EPI64
    -- Performing Test HAVE_MM256_EXTRACT_EPI64 - Failed
    -- Performing Test HAVE_MAY_I_USE
    -- Performing Test HAVE_MAY_I_USE - Failed
    -- Performing Test HAVE_BUILTIN_CPU_SUPPORTS
    -- Performing Test HAVE_BUILTIN_CPU_SUPPORTS - Failed
    -- Performing Test HAVE_MSVC_CPUIDEX
    -- Performing Test HAVE_MSVC_CPUIDEX - Failed
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stdbool.h
    -- Looking for stdbool.h - found
    -- Performing Test HAS_WGNU
    -- Performing Test HAS_WGNU - Success
    -- Performing Test NO_GNU_EXPR
    -- Performing Test NO_GNU_EXPR - Success
    -- Performing Test HAVE_SYSCONF
    -- Performing Test HAVE_SYSCONF - Success
    -- Packaging is only supported on Linux
    -- Configuring done
    -- Generating done
    CMake Warning:
      Manually-specified variables were not used by the project:
    
        ENABLE_HW_OPTIMIZATION
    
    
    -- Build files have been written to: .../aws/jan-14-2019/android/buildOutput/Release/armeabi-v7a/.deps/build/src/AwsCCommon-build
    [ 25%] Performing build step for 'AwsCCommon'
    Scanning dependencies of target aws-c-common
    [  4%] Building C object CMakeFiles/aws-c-common.dir/source/array_list.c.o
    [  8%] Building C object CMakeFiles/aws-c-common.dir/source/byte_buf.c.o
    [ 12%] Building C object CMakeFiles/aws-c-common.dir/source/codegen.c.o
    In file included from .../aws/jan-14-2019/android/buildOutput/Release/armeabi-v7a/.deps/build/src/AwsCCommon/source/codegen.c:35:
    In file included from .../aws/jan-14-2019/android/buildOutput/Release/armeabi-v7a/.deps/build/src/AwsCCommon/include/aws/common/math.h:43:
    .../aws/jan-14-2019/android/buildOutput/Release/armeabi-v7a/.deps/build/src/AwsCCommon/include/aws/common/math.fallback.inl:68:2: error: no newline at end of file [-Werror,-Wnewline-eof]
    }
     ^
    1 error generated.
    make[5]: *** [CMakeFiles/aws-c-common.dir/source/codegen.c.o] Error 1
    make[4]: *** [CMakeFiles/aws-c-common.dir/all] Error 2
    make[3]: *** [all] Error 2
    make[2]: *** [build/src/AwsCCommon-stamp/AwsCCommon-build] Error 2
    make[1]: *** [CMakeFiles/AwsCCommon.dir/all] Error 2
    make: *** [all] Error 2
    CMake Error at CMakeLists.txt:167 (message):
      Failed to build third-party libraries.
    
    
    -- Configuring incomplete, errors occurred!

**Comment by singku** [comment]
Thanks reporting, these problems have been verified. It's a good issue candidate to https://github.com/awslabs/aws-c-common

**Comment by singku** [comment]
https://github.com/awslabs/aws-c-common/pull/234
