### ISSUE TITLE
vcpkg doesn't install all of aws-sdk-cpp

### ISSUE THREAD

**Issue by SCalwas** [aws/aws-sdk-cpp#1048]
My issue #1044 was mistakenly closed and I could not reopen it. This is NOT a duplicate of #1036 which is concerned with suppressing builds of packages. I want to build ALL packages.

From a Windows command prompt:
``
$ vcpkg install aws-sdk-cpp:x86-windows
The following packages will be built and installed:
    aws-sdk-cpp[core,dynamodb,kinesis,s3]:x86-windows
...
``
The build proceeds and successfully builds those four packages, but I wanted to build ALL the packages in the SDK. How to do that?

**Comment by singku** [comment]
Sorry for mistakenly closing your issue.
What about `vcpkg install aws-cpp-sdk-[*]:x86-windows`?

**Comment by SCalwas** [comment]
The following command seems to be working. Will take a few hours for the entire build to occur, but the list of packages it's going to build looked okay. Go ahead and close this ticket. Thanks for the help.

``vcpkg install aws-sdk-cpp[*]:x86-windows --recurse``
