### ISSUE TITLE
How to handle Aws::ShutdownAPI with multiple threads on Windows?

### ISSUE THREAD

**Issue by mkemmerz** [aws/aws-sdk-cpp#1050]
### MSVC 141

Hello, in one of our projects we are using the SDK. We have a multithreaded application and don't know how to exactly use the aws sdk with it. 

We noticed that it seems like that Aws::ShutdownAPI is called multiple times so an assertion fails in the MonitoringManager. We are not exactly sure so this is rather a question than an issue.

Exception: Assertion failed! Program ... File: C:...aws-cpp-sdk-core.../Monitor...ger.cpp Line 67 Expressions: s_monitors

https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/monitoring/MonitoringManager.cpp (Lines 55 / 67 causes the assertion to fail)

`	
Aws::InitAPI(options);
	{
		auto client = Aws::MakeShared<Aws::S3::S3Client>("client", getS3Credentials(), getS3ClientConfig());
//some pre stuff - not so important

		const auto executor = Aws::MakeShared<Aws::Utils::Threading::PooledThreadExecutor>("Downloading-File", 4);
		auto transferInitCallback = [&](const Aws::Transfer::TransferManager*, const std::shared_ptr<const Aws::Transfer::TransferHandle>& handle) {};

		Aws::Transfer::TransferManagerConfiguration transferConfig(executor.get());
		transferConfig.s3Client = client;
		transferConfig.transferInitiatedCallback = transferInitCallback;

		const auto transmanager = Aws::Transfer::TransferManager::Create(transferConfig);
		const auto handle = transmanager->DownloadFile(S3_BUCKET_NAME, s3key, gzPathLocal.string());

		handle->WaitUntilFinished();    // block calling thread until download complete
		result = isAwsActionSuccessful(handle);

	} //Everything works perfectly until to this point
	Aws::ShutdownAPI(options); //<-- Causes the assertion to fail
`

Can someone explain this behavior to me, please? Why does the Monitor fails the assertions?
**Edit:** Removing Aws::ShutdownAPI(options) fixes this issue but I guess this is not the perfect way to use the API.

**Comment by wps132230** [comment]
Can you try to use `InitAPI` and `ShutdownAPI` only once for the whole application?

**Comment by mkemmerz** [comment]
It works if I call `InitAPI` at the start of the application and `ShutdownAPI` at the end. 
The issue with `ShutdownAPI` still occures if I use it on code that is executed by multiple threads.

**Comment by singku** [comment]
In general, `InitAPI` and `ShutdownAPI` should only be called once for you application because there are global variables and memory management strategy that allocate/deallocate memory during init and shutdown, multiple threads could cause race conditions, double free, memory leak. But It's fine if you want to use SDK with multiple threads, you just need to make sure `InitAPI` and `ShutdownAPI` should be called in strict order, which means, you need to synchronize your threads.

**Comment by mkemmerz** [comment]
Everything is clear now, thanks! I will close this issue.
