### ISSUE TITLE
Statically linking undefined symbols

### ISSUE THREAD

**Issue by bradenedmunds** [aws/aws-sdk-cpp#1052]
### What platform/OS are you using?
MacOS High Sierra 10.13.6

### What compiler are you using? what version?
Apple clang 10
 
### What's your CMake arguments?
`cmake ../ -DBUILD_ONLY="s3;transfer" -DBUILD_SHARED_LIBS=OFF  -DCMAKE_BUILD_TYPE=Release`

### Can you provide a TRACE level log? (sanitize any sensitive information)

Everything is great building the SDK, but the problem is when I attempt tolink the static aws sdk libraries:
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found AWS SDK for C++, Version: 1.7.38, Install Root:/usr/local, Platform Prefix:, Platform Dependent Libraries: pthread;curl
-- All linked libs: aws-cpp-sdk-transfer;aws-cpp-sdk-s3;aws-cpp-sdk-core;pthread;curl
-- Configuring done
-- Generating done
-- Build files have been written to: <redacted>

Undefined symbols for architecture x86_64:
  "_aws_default_allocator", referenced from:
      Aws::Utils::Event::EventStreamDecoder::EventStreamDecoder(Aws::Utils::Event::EventStreamHandler*) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
      Aws::Utils::Event::EventStreamDecoder::EventStreamDecoder(Aws::Utils::Event::EventStreamHandler*) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
      Aws::Utils::Event::EventStreamDecoder::ResetEventStreamHandler(Aws::Utils::Event::EventStreamHandler*) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
  "_aws_event_stream_header_value_as_bool", referenced from:
      Aws::Utils::Event::EventHeaderValue::EventHeaderValue(aws_event_stream_header_value_pair*) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
  "_aws_event_stream_header_value_as_byte", referenced from:
      Aws::Utils::Event::EventHeaderValue::EventHeaderValue(aws_event_stream_header_value_pair*) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
  "_aws_event_stream_header_value_as_bytebuf", referenced from:
      Aws::Utils::Event::EventHeaderValue::EventHeaderValue(aws_event_stream_header_value_pair*) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
  "_aws_event_stream_header_value_as_int16", referenced from:
      Aws::Utils::Event::EventHeaderValue::EventHeaderValue(aws_event_stream_header_value_pair*) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
  "_aws_event_stream_header_value_as_int32", referenced from:
      Aws::Utils::Event::EventHeaderValue::EventHeaderValue(aws_event_stream_header_value_pair*) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
  "_aws_event_stream_header_value_as_int64", referenced from:
      Aws::Utils::Event::EventHeaderValue::EventHeaderValue(aws_event_stream_header_value_pair*) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
  "_aws_event_stream_header_value_as_string", referenced from:
      Aws::Utils::Event::EventHeaderValue::EventHeaderValue(aws_event_stream_header_value_pair*) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
  "_aws_event_stream_header_value_as_timestamp", referenced from:
      Aws::Utils::Event::EventHeaderValue::EventHeaderValue(aws_event_stream_header_value_pair*) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
  "_aws_event_stream_header_value_as_uuid", referenced from:
      Aws::Utils::Event::EventHeaderValue::EventHeaderValue(aws_event_stream_header_value_pair*) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
  "_aws_event_stream_streaming_decoder_clean_up", referenced from:
      Aws::Utils::Event::EventStreamDecoder::~EventStreamDecoder() in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
      Aws::Utils::Event::EventStreamDecoder::~EventStreamDecoder() in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
  "_aws_event_stream_streaming_decoder_init", referenced from:
      Aws::Utils::Event::EventStreamDecoder::EventStreamDecoder(Aws::Utils::Event::EventStreamHandler*) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
      Aws::Utils::Event::EventStreamDecoder::EventStreamDecoder(Aws::Utils::Event::EventStreamHandler*) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
      Aws::Utils::Event::EventStreamDecoder::ResetEventStreamHandler(Aws::Utils::Event::EventStreamHandler*) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
  "_aws_event_stream_streaming_decoder_pump", referenced from:
      Aws::Utils::Event::EventStreamDecoder::Pump(Aws::Utils::Array<unsigned char> const&) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
      Aws::Utils::Event::EventStreamDecoder::Pump(Aws::Utils::Array<unsigned char> const&, unsigned long) in libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libs3-core.dylib] Error 1
make[1]: *** [CMakeFiles/s3-core.dir/all] Error 2
make: *** [all] Error 2

<hr>
I guess I'm wondering if I need to include another library that isn't being pulled in already? Any help would be appreciated.
<hr>
Here's roughly my cmake file as well:

project(myproject)

set(CMAKE_CXX_STANDARD 14)
find_package(AWSSDK REQUIRED)
add_definitions(-DUSE_IMPORT_EXPORT)

set(SOURCE_FILES myfiles.cpp)
include_directories(src)

SET(SERVICE "s3;transfer")
AWSSDK_DETERMINE_LIBS_TO_LINK(SERVICE OUTPUT)
Message(STATUS "All linked libs: ${OUTPUT}")
set(LIBRARIES ${LIBRARIES} ${OUTPUT})

add_library(mylib SHARED ${SOURCE_FILES})
target_link_libraries(mylib ${LIBRARIES})

**Comment by wps132230** [comment]
In your cmake file, can you try something like that:
```
project(myproject)

set(CMAKE_CXX_STANDARD 14)
find_package(AWSSDK REQUIRED COMPONENTS transfer)
add_definitions(-DUSE_IMPORT_EXPORT)

set(SOURCE_FILES myfiles.cpp)
include_directories(src)

Message(STATUS "All linked libs: ${AWSSDK_LINK_LIBRARIES}")

add_library(mylib SHARED ${SOURCE_FILES})
target_link_libraries(mylib ${AWSSDK_LINK_LIBRARIES})
```
With `find_package(AWSSDK REQUIRED COMPONENTS transfer)`, it will help you "determine_libs_to_link" and "find_package", which is missed in your cmake file.

**Comment by singku** [comment]
But for your problem, the outputs of before and after are actually the same. So, this is not the cause.
What's different is that when calling
```
 find_package(AWSSDK COMPONENTS xx)
```
AWSSDK's cmake find_package scripts will call `find_package(xx)` for you, which will resolve event-stream dependency. In this case, aws-cpp-sdk-core depends on aws-c-event-stream package.

Your original scripts (which we suggested a while ago and needs to be updated) purely linking what's found and didn't resolve secondary dependencies.

**Comment by bradenedmunds** [comment]
@singku makes sense! Thank you both.
