### ISSUE TITLE
error: ‘volatile struct aws_atomic_var’ has no member named ‘u’

### ISSUE THREAD

**Issue by TarcisioGitHub** [aws/aws-sdk-cpp#1054]
### What platform/OS are you using?
CentOS release 6.10 (Final)
### What compiler are you using? what version?
gcc version 4.4.7
### What's your CMake arguments?
The following error is occurring when running make for aws-c-common-master:
error: ‘volatile struct aws_atomic_var’ has no member named ‘u’

**Comment by justinboswell** [comment]
I have fixed this in: https://github.com/awslabs/aws-c-common/pull/268
