### ISSUE TITLE
AuthorizationHeaderMalformed: the region 'us-east-1' is wrong; expecting 'ap-northeast-1'

### ISSUE THREAD

**Issue by genuinelucifer** [aws/aws-sdk-cpp#1057]
### What platform/OS are you using?
Ubuntu 18.04
### What compiler are you using? what version?
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04) 
### What's your CMake arguments?
CMakeLists.txt contains (copied from some aws sdk example):
```
cmake_minimum_required(VERSION 3.5)
project(awsexample)
find_package(AWSSDK REQUIRED COMPONENTS s3)
set(CMAKE_CXX_STANDARD 17)
add_executable(awsexample "example_try_aws_sdk.cpp")
# list all deps for static linking
target_link_libraries(awsexample ${AWSSDK_LINK_LIBRARIES})
target_compile_options(awsexample PRIVATE "-Wall" "-Werror")
```
### Can you provide a TRACE level log? (sanitize any sensitive information)
I am getting error `GetObject error: AuthorizationHeaderMalformed Unable to parse ExceptionName: AuthorizationHeaderMalformed Message: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'ap-northeast-1'`

The code that I used is (copied from multiple aws examples and changes using some comments on similar issues):
```c++
bool download_and_save_file(String profile, String region, String bucket, String key, String local_path)
{
    String region_endpoint = "https://s3." + region + ".amazonaws.com";
    bool success = false;

    SDKOptions options;
    //options.loggingOptions.logLevel = Utils::Logging::LogLevel::Error;
    InitAPI(options);
    {
        Client::ClientConfiguration config;
        config.endpointOverride = region_endpoint;
        config.scheme = Http::Scheme::HTTPS;

        //S3::S3Client client(config);
        auto credentials = Auth::ProfileConfigFileAWSCredentialsProvider(profile.c_str()).GetAWSCredentials();
        auto client = S3::S3Client(credentials, config);
        // Also doesn't work
        // auto client = S3::S3Client(credentials, config, Client::AWSAuthV4Signer::PayloadSigningPolicy::Never, false);

        S3::Model::GetObjectRequest request;
        request.WithBucket(bucket).WithKey(key);
        //request.SetResponseStreamFactory([local_path] { return new std::fstream(local_path.c_str(), std::ios_base::out); });
        auto get_object_outcome = client.GetObject(request);

        if (get_object_outcome.IsSuccess())
        {
            Aws::OFStream local_file;
            local_file.open(local_path.c_str(), std::ios::out | std::ios::binary);
            local_file << get_object_outcome.GetResult().GetBody().rdbuf();
            clog << "Done!" << std::endl;
        }
        else
        {
            clog << "GetObject error: " <<
                get_object_outcome.GetError().GetExceptionName() << " " <<
                get_object_outcome.GetError().GetMessage() << std::endl;
        }
        success = get_object_outcome.IsSuccess();
    }
    ShutdownAPI(options);

    return success;
}
```

I have built the aws s3 sdk using steps provided in [this guide](https://github.com/aws/aws-sdk-cpp/wiki/Building-the-SDK-from-source-on-EC2).  
I am calling the above function like this:
`download_and_save_file("myprofilewithmfa", "ap-northeast-1", "mybucket.name.changed",
            "keyto/myfile/myfile.json.gz", "./myfilejson.gz")`  
  
I am just trying to download a file from s3 bucket. I've looked at other similar issues but am not able to solve this problem. Please help.

**Comment by genuinelucifer** [comment]
> Just curious why you need to override endpoint

I'm using this library for the first time. I just saw that in multiple examples so used that. 🤷‍♂️ 
I should have stuck to any one example, but I just made a hodgepodge of code by mixing different examples until nothing worked.  
  
Thank you for the response, setting only the config region worked.  
  
While we're here, would you tell me what is the recommended way to download files multiple times at different places? Should I write a helper function (like the given example) which always Initializes and shut down the AWS SDK or should I just initialize it once and then after downloading everything, shut it down?

**Comment by wps132230** [comment]
The recommended way is to `InitAPI` and `ShutdownAPI` only once for the whole application.
In `InitAPI`, it will setup memory management, logging system, http client, crypto stuff, etc.
https://github.com/aws/aws-sdk-cpp/blob/5b22097f956780e09c2b0688fa0a8e0661c4f14d/aws-cpp-sdk-core/source/Aws.cpp#L29

**Comment by genuinelucifer** [comment]
Thank you.
