### ISSUE TITLE
AWS C++ SDK: Missing SDKConfig.h error

### ISSUE THREAD

**Issue by salunkhesagar1386** [aws/aws-sdk-cpp#1058]
Trying to build a simple C++ static library for Windows. This static lib will integrate the C++ AWS SDK and will have methods which will make calls to some webserver using the AWS C++ APIs'.

After downloading the C++ AWS SDK from github, when integrated with static project, I am getting compilation error as mentioned below. I do see a file present at path with same name but the full file name is 'SDKConfig.h.in'. Where do I find this 'SDKConfig.h' file core folder?

Can some one provide inputs on below points?
1. I downloaded the entire AWS C++ SDK from github
 - Do I need to set any environment variables? 
 - Do I need to add any preprocessor definitions for using this SDK in static lib project?
 - Is there any simple step by step application that uses ****just** the Core AWS services SDK** and access some end point URL?
 - In case if I want to use just couple of services (eg. **aws-cpp-sdk-core** & **aws-cpp-sdk-cognito-identity**), do I need to have other sdk folders residing in my application? Asking this to avoid the copies for those files which will be not used in the application anyways? Is there any inter-dependency of every file with other files in SDK?

### Error
Following is the error that VS2017 gives while compilation.
**Severity**	: Error 
**Code**	: C1083
**Description**: Cannot open include file: 'aws/core/SDKConfig.h': No such file or directory
**Project**	: AWSServicesProvider.Win	
**File**	        : c:\aws-sdk-cpp-master\aws-cpp-sdk-core\include\aws\core\core_exports.h	
**Line**	        : 18	

### What platform/OS are you using?
Windows/Android

### What compiler are you using? what version?
Visual Studio 2017

**Comment by mkemmerz** [comment]
We had a similar issue with the SDKConfig. There should be an #define in it.
Can you post the #define from the SDKConfig, please?

**Comment by salunkhesagar1386** [comment]
I don't seethe **SDKConfig.h** file at this location, instead its **SDKConfig.h.in** file. Following are the macros defined in this file.


**#cmakedefine USE_AWS_MEMORY_MANAGEMENT
#define JSON_USE_EXCEPTION 0**

Following are the list of files present in core folder,

**Directory of C:\aws-sdk-cpp-master\aws-cpp-sdk-core\include\aws\core

02/05/2019  02:56 PM    <DIR>          .
02/05/2019  02:56 PM    <DIR>          ..
01/25/2019  03:16 PM             2,390 AmazonSerializableWebServiceRequest.h
01/25/2019  03:16 PM             3,138 AmazonStreamingWebServiceRequest.h
01/25/2019  03:16 PM             6,693 AmazonWebServiceRequest.h
01/25/2019  03:16 PM             3,135 AmazonWebServiceResult.h
02/04/2019  09:23 AM    <DIR>          auth
01/25/2019  03:16 PM            10,374 Aws.h
02/04/2019  09:23 AM    <DIR>          client
02/04/2019  09:23 AM    <DIR>          config
02/05/2019  02:56 PM             3,120 Core_EXPORTS.h
02/04/2019  09:23 AM    <DIR>          external
01/25/2019  03:16 PM             1,459 Globals.h
02/04/2019  09:23 AM    <DIR>          http
02/04/2019  09:23 AM    <DIR>          internal
02/04/2019  09:23 AM    <DIR>          monitoring
02/04/2019  09:23 AM    <DIR>          net
01/25/2019  03:16 PM               721 NoResult.h
02/04/2019  09:23 AM    <DIR>          platform
01/25/2019  03:16 PM             1,922 Region.h
**01/25/2019  03:16 PM               669 SDKConfig.h.in**
02/04/2019  09:23 AM    <DIR>          utils
01/25/2019  03:16 PM             1,001 Version.h
01/25/2019  03:16 PM               639 VersionConfig.h
01/25/2019  03:16 PM               656 VersionConfig.h.in
              13 File(s)         35,917 bytes
              12 Dir(s)  314,417,000,448 bytes free**

**Comment by mkemmerz** [comment]
Ah ok, now I remember what we did or atleast worked for us.

Try to remove: #cmakedefine USE_AWS_MEMORY_MANAGEMENT

So the config should be only: #define JSON_USE_EXCEPTION 0

**Comment by salunkhesagar1386** [comment]
> Ah ok, now I remember what we did or atleast worked for us.
> 
> Try to remove: #cmakedefine USE_AWS_MEMORY_MANAGEMENT
> 
> So the config should be only: #define JSON_USE_EXCEPTION 0
> 
> And remove the .in from the filename so you get "SDKConfig.h".

That fixed the issue. Thank you so much @mkemmerz

**Comment by Sunil-P** [comment]
Same issue is present in latest build.
