### ISSUE TITLE
cmake fails if no www connection due to "git clones" in third-party code.

### ISSUE THREAD

**Issue by dburken** [aws/aws-sdk-cpp#1059]
### What platform/OS are you using?
CentOS 7

### What compiler are you using? what version?
$ g++ -v
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

### What's your CMake arguments?
cmake -G "Unix Makefiles" \
-DBUILD_ONLY="core;s3" \
-DCMAKE_INSTALL_PREFIX=/work/drb/deps \
-DENABLE_TESTING=OFF \
/work/drb/aws/aws-sdk-cpp-1.7.38

### Can you provide a TRACE level log? (sanitize any sensitive information)

**Comment by dburken** [comment]
Code will not compile without an internet connection which is problematic if you don't have one.  Looks like the "third-party" dir is doing git clones:

grep git third-party/CMakeLists.txt
set(AWS_C_COMMON_URL "https://github.com/awslabs/aws-c-common.git")
set(AWS_CHECKSUMS_URL "https://github.com/awslabs/aws-checksums.git")
set(AWS_EVENT_STREAM_URL "https://github.com/awslabs/aws-c-event-stream.git")

**Comment by dburken** [comment]
I tried the -DBUILD_DEPS=OFF but I did not have the ability to download the dependencies/build ahead of time and it failed. I will pull that source in for those three repos but is seems like they should be part of the sdk. Thanks...

**Comment by wps132230** [comment]
Just like curl, openssl, these libraries are dependencies of C++ SDK, and should be installed in advance. But they are maintained by AWS, and not widely used, so the SDK will download, build and install them by default.
We just updated some details about how to install these libraries separately in README.
https://github.com/aws/aws-sdk-cpp#to-build-and-install-third-party-dependencies

**Comment by marcomagdy** [comment]
Unfortunately, we have no plans to make the third-party deps available offline.
