### ISSUE TITLE
Question: How to check if an prefix / key exists on S3 before creating a presigned URL?

### ISSUE THREAD

**Issue by mkemmerz** [aws/aws-sdk-cpp#1061]
I use the S3 SDK CPP and have the following cenario:

1.  I get some information sent from a client to my server (client wants to download from S3)
2. With the information sent I create a S3 key (the prefix)
3. I want to check if the key / prefix exists on the S3
4. I create a presigned URL that allows the client to download a file from S3
5. Send URL to client
6. Client downloads the file

Before I execute step 4 I want to check if the key really exists on the S3. The client can't download a file that does not exist anyway. I noticed that the S3 creates an URL even if there is no file behind the key so I want to response properly to the client in this case.

I have an AWS::S3Client object. Do I really need to create a TransferManager for this or is there a simple way to handle this with the client object?

The client itself does not have a relation to S3 so I can't check it there. The server has to do all the work.

Can someone tell me how to properly check if the key exists on S3?

**Comment by wps132230** [comment]
You don't need TransferManager, you can do that with S3 API like "ListObjectsV2" on the server side. And of course you should setup AWS credentials on the server and have at least "read" permission.
https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

**Comment by mkemmerz** [comment]
Thanks - works fine!
