### ISSUE TITLE
Support for building aws-sdk-cpp with external dependencies as packages

### ISSUE THREAD

**Issue by glaubitz** [aws/aws-sdk-cpp#1065]
I am currently updating the ```aws-sdk-cpp``` package in openSUSE/SLE to 1.7.47, starting with 1.7.0, the SDK requires three additional dependencies from AWS called ```aws-c-common```, ```aws-checksums``` and ```aws-c-event-stream```.

I have created RPM packages for all three dependencies and added them as ```BuildRequires``` in the spec file of my ```aws-sdk-cpp``` package, but the build process currently assumes checking out the AWS dependencies with ```git``` and fails accordingly:

```
[   16s] CMake Error at /usr/share/cmake/Modules/ExternalProject.cmake:2329 (message):
[   16s]   error: could not find git for clone of AwsCCommon
[   16s] Call Stack (most recent call first):
[   16s]   /usr/share/cmake/Modules/ExternalProject.cmake:3105 (_ep_add_download_command)
[   16s]   cmake/BuildAwsCCommon.cmake:39 (ExternalProject_Add)
[   16s]   CMakeLists.txt:23 (include)
```

Since the build servers of distributions usually block off all internet access during build, this prevents newer versions of ```aws-sdk-cpp``` from being packaged in Linux distributions.

Thus, it would be great if the cmake scripts could get an option to enable the dependencies as local packages instead of pulling them through ```git``` and trying to build them in-tree.

For now, I will just patch the ```CMakeLists.txt``` myself.

**Comment by glaubitz** [comment]
Aha, it seems I have missed the option ```-DBUILD_DEPS=OFF```. Let's see if that works, if it does, I'll close this issue again.

**Comment by glaubitz** [comment]
Ok, the option ````-DBUILD_DEPS=OFF``` works as expected.

**Comment by muzab** [comment]
I have the same error but with building a Yocto recipe for aws-sdk-cpp. Where are you setting the option to keep the dependencies off?.

**Comment by glaubitz** [comment]
See line 79 in my spec file: https://build.opensuse.org/package/view_file/Cloud:Tools/aws-sdk-cpp/aws-sdk-cpp.spec?expand=1

**Comment by muzab** [comment]
Great! thanks.
