### ISSUE TITLE
Option to specify region as string for S3 buckets

### ISSUE THREAD

**Issue by asylvest** [aws/aws-sdk-cpp#107]
In `ClientConfiguration` there is an `authenticationRegion` string you can use if there's a new region and the C++ SDK doesn't have an enum for it yet.  It would be helpful to have the same thing for S3 when you want to create a bucket in this new region.

Maybe `CreateBucketConfiguration` could have an overloading to take in a string... or `BucketLocationConstraint` could change to a class that could be constructed from either an enum or a string.

**Comment by JonathanHenson** [comment]
I like the second option on BucketLocationConstraint, I'll add this to our backlog.

**Comment by asylvest** [comment]
I can take a crack at this and put in a pull request if it'll help

**Comment by JonathanHenson** [comment]
It would need to be an override in the generator.

**Comment by asylvest** [comment]
OK that part I'll leave to you :o)

**Comment by asylvest** [comment]
Any ETA on when you think you'll have a chance to add this to the generator?  It's something that I'd like to use in my application.

**Comment by asylvest** [comment]
I started a bit down the path of updating the generator code.  But then looking at the latest version of `BucketLocationConstraint.cpp`, I see there's an `EnumOverflowContainer` now.  If I am understanding how this is intended to be used, I could pass an arbitrary string into `GetBucketLocationConstraintForName()`, and if it doesn't match one of the "real" enums, it'll add a value in the overflow container such that when `CreateBucketConfiguration` calls `GetNameForBucketLocationConstraint()`, I'll get my original string back out.

If that's the case, I think this solves the issue and there's no point in me updating the generator code.  Is there anything "bad" / any concerns with doing this?  Based on the documentation in `Globals.h`, the main intent of this enum overflow container may be a bit different, but it seems like it'll work fine.

**Comment by JonathanHenson** [comment]
It's for solving the problem of round tripping no enums. For example, ec2 adds a new instance type you have a deployed application calling describeInstances. Some one adds a new instance to your fleet with the new instance type. Your application now loses that information and if the instance description Is then sent back as a request, the request will fail all of the sudden.

However I think yours is a fine use case as well.

**Comment by asylvest** [comment]
Thanks - I think your solution for handling round tripping like this is a good one.

I did confirm that, as expected, using this functionality for my use case works too.  So, I'm all set... this issue can be closed as far as I'm concerned.
