### ISSUE TITLE
cJSON exporting symbols by default

### ISSUE THREAD

**Issue by Matheus28** [aws/aws-sdk-cpp#1071]
It seems that by default, since none of these are defined: `CJSON_HIDE_SYMBOLS`, `CJSON_IMPORT_SYMBOLS` or `JSON_EXPORT_SYMBOLS`, it defaults to `CJSON_EXPORT_SYMBOLS` (see `cJSON.h`), which means that the sdk will generate some `__declspec(dllexport)` even if being statically linked. This ends up creating a .lib and .exp alongside the .exe output of anything linking against the aws sdk static libraries.

It'd be useful if BUILD_SHARED_LIBS is `OFF`, the cmake for aws defined `CJSON_HIDE_SYMBOLS` for its static library, or make it depend on `USE_IMPORT_EXPORT`.

### What platform/OS are you using?
Windows 10 x64

### What compiler are you using? what version?
MSVC 2017

### What's your CMake arguments?
    cmake . -DBUILD_ONLY="dynamodb" -DENABLE_TESTING="OFF" -DBUILD_SHARED_LIBS="OFF" -DENABLE_UNITY_BUILD="ON" -DFORCE_SHARED_CRT="OFF" -G "Visual Studio 15 2017 Win64"

**Comment by wps132230** [comment]
Thank you for your suggestions, we've added them in https://github.com/aws/aws-sdk-cpp/commit/abfe95d7125b39ab23cbc604f4c9728010e71a12.
