### ISSUE TITLE
AppSync question

### ISSUE THREAD

**Issue by atlascoder** [aws/aws-sdk-cpp#1075]
Quick question about AppSync

I'd like to use it for a mobile project with Qt and the main question before to start: does C++ SDK implement local (offline) data storage somehow? What interfaces to use/implement?

Thanks!

**Comment by singku** [comment]
C++ SDK doesn't have local data storage interfaces or implementations. But have some file related utils that could be used by customer.
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/include/aws/core/platform/FileSystem.h

**Comment by atlascoder** [comment]
Thank you, @singku , but as far I understood, the current version of `aws-cpp-sdk-appsync` provides only appsync management functionality - and it requires for another GraphQL client for processing data requests.
So, the app now is more like `admin` lib.

**Comment by singku** [comment]
You are right.
