### ISSUE TITLE
S3EncryptionClient no longer works with TransferManager

### ISSUE THREAD

**Issue by renjunzheng** [aws/aws-sdk-cpp#1076]
In this [change commit](https://github.com/aws/aws-sdk-cpp/commit/2647d48aa70c67db2a7a144ec9cd356b813cdbe0#diff-14e9e8d66ae7ba850eccf5456bf64d0cL26), where it used to be `class AWS_S3ENCRYPTION_API S3EncryptionClient : public Aws::S3::S3Client` and now just `class AWS_S3ENCRYPTION_API S3EncryptionClient`.
In TransferManagerConfiguration, it needs a S3Client to be set to work [code](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-transfer/include/aws/transfer/TransferManager.h#L56). So the aforementioned commit breaks that. Is this an intended behavior? If so, what's the suggestion for using TransferManager with client-side encryption?

**Comment by singku** [comment]
That was an intended change so as to make S3Encryption errors out correct error type and message. We haven't come up an ideal way to use transfer manager together with S3Encryption.
