### ISSUE TITLE
Amazon SQS ReceiveMessage requests throttled

### ISSUE THREAD

**Issue by dkislov** [aws/aws-sdk-cpp#1077]
### What platform/OS are you using?
I am using Windows 10 Pro as development OS. Target platform Windows Server 2016 on EC2 instance.

### What compiler are you using? what version?
I use Visual Studio 2017 as development tool chain and AWSSDKCPP-Core.1.6.11 , AWSSDKCPP-SQS.1.6.20121105.11 taken to project from NuGet.org.

### What's your CMake arguments?
I do not use CMake in the project

### Can you provide a TRACE level log? (sanitize any sensitive information)
x-amzn-RequestId: a199a1d3-d07f-58c8-82be-f53dd41b1032
[TRACE] 2019-02-25 14:56:34 WinHttpSyncHttpClient [3420] Response content-length header: 327
[TRACE] 2019-02-25 14:56:34 WinHttpSyncHttpClient [3420] Response body length: 327
[DEBUG] 2019-02-25 14:56:34 WinHttpSyncHttpClient [3420] Closing http request handle 000000722CF04E70
[DEBUG] 2019-02-25 14:56:34 WinHttpSyncHttpClient [3420] Releasing connection handle 000000722BDE47A0
[DEBUG] 2019-02-25 14:56:34 WinHttpConnectionPoolMgr [3420] Releasing connection to endpoint sqs.us-east-1.amazonaws.com:443
[DEBUG] 2019-02-25 14:56:34 AWSClient [3420] Request returned error. Attempting to generate appropriate error codes from response
[TRACE] 2019-02-25 14:56:34 AWSErrorMarshaller [3420] Error response is <?xml version="1.0"?>
<?xml version="1.0"?>
<ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
    <Error>
        <Type>Sender</Type>
        <Code>RequestThrottled</Code>
        <Message>Queue 394697544486/xxx-dev-daily.fifo/1SAKY3QRFSMQ82D08BZ0/1 Throttled</Message>
        <Detail/>
    </Error>
    <RequestId>a199a1d3-d07f-58c8-82be-f53dd41b1032</RequestId>
</ErrorResponse>

[WARN] 2019-02-25 14:56:34 AWSErrorMarshaller [3420] Encountered Unknown AWSError 'RequestThrottled': Queue 394697544486/xxxx-dev-daily.fifo/1SAKY3QRFSMQ82D08BZ0/1 Throttled
[ERROR] 2019-02-25 14:56:34 AWSClient [3420] HTTP response code: 403
Exception name: RequestThrottled
Error message: Unable to parse ExceptionName: RequestThrottled Message: Queue 394697544486/xxxx-dev-daily.fifo/1SAKY3QRFSMQ82D08BZ0/1 Throttled

### Issue description ###
I got in code "RequestThrottled"  exception. In file client/CoreErrors.cpp there is no declaration for this kind of exception. In this case method DefaultRetryStrategy::ShouldRetry(const AWSError<CoreErrors>& error, long attemptedRetries) failed and default Exponential backoff does not work.

So, please give your opinion how should I handle this issue?

**Comment by marcomagdy** [comment]
Throttling exceptions should be retried. We'll have this fixed. Thanks for reporting the error

**Comment by singku** [comment]
We have merged this fix. Will be available in this repo soon.
