### ISSUE TITLE
Streaming GET with PUT to a different bucket

### ISSUE THREAD

**Issue by VilleSilventoinen** [aws/aws-sdk-cpp#1078]
I'm trying to find out if I can use AWS C++ SDK to copy objects from one S3 compatible object storage system to another one (e.g., IBM COS to HGST ActiveScale). Object sizes range from zero bytes to couple of terabytes.

I've read some previous questions (#644, #785), but they are not addressing quite the same problem.

What I would like to do:
- Use TransferManager for the copy if possible. But can it read from one S3 storage and write to a different one? (Not only the bucket names, keys etc. differ, but also IP addresses.) I've understood S3 "copy" means an internal copy, where the object exists inside the same S3 storage system.
- Avoid disk I/O.
- Start a GET, start a PUT and pipe the GET data to the PUT. I understand the problem is that this wouldn't do a multipart upload automatically.

The only way I think I can do this is by using GET range requests to read parts from the source object and create multipart upload requests to do the PUTs. Rinse and repeat until the whole object has been written. Any better ways offered by the SDK?

**Comment by webbnh** [comment]
I rolled my own derivation of `std::streambuf` (and `std::iostream`) which allows me to access the results of the `GET` as it arrives, so I can process it as it comes down.  It also allows the stuff which goes into the `PUT` to be constructed on the fly, but, unfortunately, this really only works if you know _a priori_ how large the upload is going to be.  In my case, I don't know the size until I'm done generating it, so I wasn't able to use it to stream uploads, but, in your case, this is probably not a problem.

In your scenario, I would create an input stream and and output stream which share the same instance of the `streambuf` derivation, then pass the output stream to the `TransferManager`'s `DownloadFile()` method, and pass the input stream to the `TransferManager`'s `UploadFile()` method.  In this way, you can block the read requests from the upload until you can satisfy them from the download; and you can buffer all of the bytes transferred in memory.

It's not an easy piece of code to write (you'll need to know how to deal with multiple threads and handle the buffer flow), but it was a fun and challenging exercise for me.
