### ISSUE TITLE
vtable for Aws

### ISSUE THREAD

**Issue by cartonino** [aws/aws-sdk-cpp#1079]
I receive this error when packaging ios in Unreal Engine

UATHelper: Packaging (iOS):   Undefined symbols for architecture arm64:
UATHelper: Packaging (iOS):     "vtable for Aws::GameLift::Model::StartMatchmakingRequest", referenced from:
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
UATHelper: Packaging (iOS):     "Aws::GameLift::Model::DescribeGameSessionsRequest::DescribeGameSessionsRequest()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftDescribeGameSessions::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "vtable for Aws::GameLift::Model::DescribeGameSessionsRequest", referenced from:
UATHelper: Packaging (iOS):         UGameLiftDescribeGameSessions::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
UATHelper: Packaging (iOS):     "Aws::GameLift::Model::DescribeGameSessionDetailsRequest::DescribeGameSessionDetailsRequest()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftDescribeGameSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "Aws::GameLift::Model::Player::Player()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "vtable for Aws::GameLift::Model::DescribeGameSessionDetailsRequest", referenced from:
UATHelper: Packaging (iOS):         UGameLiftDescribeGameSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
UATHelper: Packaging (iOS):     "Aws::Client::ClientConfiguration::ClientConfiguration()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftClientObject::Internal_InitGameLiftClientSDK(FString const&, FString const&, FString const&, bool, int) in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "Aws::GameLift::Model::GameProperty::GameProperty()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftCreateGameSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "Aws::ShutdownAPI(Aws::SDKOptions const&)", referenced from:
UATHelper: Packaging (iOS):         FAWSCoreModule::ShutdownModule() in AWSCoreModule.cpp.o
UATHelper: Packaging (iOS):     "vtable for Aws::GameLift::Model::CreatePlayerSessionRequest", referenced from:
UATHelper: Packaging (iOS):         UGameLiftCreatePlayerSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
UATHelper: Packaging (iOS):     "Aws::GameLift::GameLiftClient::GameLiftClient(Aws::Auth::AWSCredentials const&, Aws::Client::ClientConfiguration const&)", referenced from:
UATHelper: Packaging (iOS):         UGameLiftClientObject::Internal_InitGameLiftClientSDK(FString const&, FString const&, FString const&, bool, int) in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "Aws::Free(void*)", referenced from:
UATHelper: Packaging (iOS):         UGameLiftCreateGameSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftDescribeGameSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftCreatePlayerSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftDescribeGameSessions::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::DescribeMatchmaking() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::DescribeMatchmakingHandler(Aws::GameLift::GameLiftClient const*, Aws::GameLift::Model::DescribeMatchmakingRequest const&, Aws::Utils::Outcome<Aws::GameLift::Model::DescribeMatchmakingResult, Aws::Client::AWSError<Aws::GameLift::GameLiftErrors> > const&, std::__1::shared_ptr<Aws::Client::AsyncCall
erContext const> const&) in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         ...
UATHelper: Packaging (iOS):     "Aws::GameLift::Model::StartMatchmakingRequest::StartMatchmakingRequest()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "Aws::AmazonWebServiceRequest::AmazonWebServiceRequest()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftCreateGameSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "Aws::GameLift::Model::CreatePlayerSessionRequest::CreatePlayerSessionRequest()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftCreatePlayerSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "vtable for Aws::GameLift::Model::CreateGameSessionRequest", referenced from:
UATHelper: Packaging (iOS):         UGameLiftCreateGameSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         Aws::GameLift::Model::CreateGameSessionRequest::~CreateGameSessionRequest() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
UATHelper: Packaging (iOS):     "Aws::Malloc(char const*, unsigned long)", referenced from:
UATHelper: Packaging (iOS):         UGameLiftCreateGameSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::DescribeMatchmaking() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::DescribeMatchmakingHandler(Aws::GameLift::GameLiftClient const*, Aws::GameLift::Model::DescribeMatchmakingRequest const&, Aws::Utils::Outcome<Aws::GameLift::Model::DescribeMatchmakingResult, Aws::Client::AWSError<Aws::GameLift::GameLiftErrors> > const&, std::__1::shared_ptr<Aws::Client::AsyncCall
erContext const> const&) in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftClientObject::Internal_InitGameLiftClientSDK(FString const&, FString const&, FString const&, bool, int) in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         std::__1::basic_string<char, std::__1::char_traits<char>, Aws::Allocator<char> >::assign(char const*, unsigned long) in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         void std::__1::vector<Aws::GameLift::Model::GameProperty, Aws::Allocator<Aws::GameLift::Model::GameProperty> >::__push_back_slow_path<Aws::GameLift::Model::GameProperty const&>(Aws::GameLift::Model::GameProperty const&&&) in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         Aws::GameLift::Model::GameProperty::GameProperty(Aws::GameLift::Model::GameProperty const&) in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         ...
UATHelper: Packaging (iOS):     "Aws::GameLift::Model::DescribeMatchmakingRequest::DescribeMatchmakingRequest()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::DescribeMatchmaking() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "vtable for Aws::GameLift::Model::DescribeMatchmakingRequest", referenced from:
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::DescribeMatchmaking() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
UATHelper: Packaging (iOS):     "Aws::InitAPI(Aws::SDKOptions const&)", referenced from:
UATHelper: Packaging (iOS):         FAWSCoreModule::StartupModule() in AWSCoreModule.cpp.o
UATHelper: Packaging (iOS):   ld: symbol(s) not found for architecture arm64

**Comment by wps132230** [comment]
Could you provide more details?

**Comment by cartonino** [comment]
I receive this error when packaging ios in Unreal Engine

UATHelper: Packaging (iOS):   Undefined symbols for architecture arm64:
UATHelper: Packaging (iOS):     "vtable for Aws::GameLift::Model::StartMatchmakingRequest", referenced from:
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
UATHelper: Packaging (iOS):     "Aws::GameLift::Model::DescribeGameSessionsRequest::DescribeGameSessionsRequest()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftDescribeGameSessions::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "vtable for Aws::GameLift::Model::DescribeGameSessionsRequest", referenced from:
UATHelper: Packaging (iOS):         UGameLiftDescribeGameSessions::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
UATHelper: Packaging (iOS):     "Aws::GameLift::Model::DescribeGameSessionDetailsRequest::DescribeGameSessionDetailsRequest()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftDescribeGameSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "Aws::GameLift::Model::Player::Player()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "vtable for Aws::GameLift::Model::DescribeGameSessionDetailsRequest", referenced from:
UATHelper: Packaging (iOS):         UGameLiftDescribeGameSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
UATHelper: Packaging (iOS):     "Aws::Client::ClientConfiguration::ClientConfiguration()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftClientObject::Internal_InitGameLiftClientSDK(FString const&, FString const&, FString const&, bool, int) in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "Aws::GameLift::Model::GameProperty::GameProperty()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftCreateGameSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "Aws::ShutdownAPI(Aws::SDKOptions const&)", referenced from:
UATHelper: Packaging (iOS):         FAWSCoreModule::ShutdownModule() in AWSCoreModule.cpp.o
UATHelper: Packaging (iOS):     "vtable for Aws::GameLift::Model::CreatePlayerSessionRequest", referenced from:
UATHelper: Packaging (iOS):         UGameLiftCreatePlayerSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
UATHelper: Packaging (iOS):     "Aws::GameLift::GameLiftClient::GameLiftClient(Aws::Auth::AWSCredentials const&, Aws::Client::ClientConfiguration const&)", referenced from:
UATHelper: Packaging (iOS):         UGameLiftClientObject::Internal_InitGameLiftClientSDK(FString const&, FString const&, FString const&, bool, int) in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "Aws::Free(void*)", referenced from:
UATHelper: Packaging (iOS):         UGameLiftCreateGameSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftDescribeGameSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftCreatePlayerSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftDescribeGameSessions::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::DescribeMatchmaking() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::DescribeMatchmakingHandler(Aws::GameLift::GameLiftClient const*, Aws::GameLift::Model::DescribeMatchmakingRequest const&, Aws::Utils::Outcome<Aws::GameLift::Model::DescribeMatchmakingResult, Aws::Client::AWSError<Aws::GameLift::GameLiftErrors> > const&, std::__1::shared_ptr<Aws::Client::AsyncCall
erContext const> const&) in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         ...
UATHelper: Packaging (iOS):     "Aws::GameLift::Model::StartMatchmakingRequest::StartMatchmakingRequest()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "Aws::AmazonWebServiceRequest::AmazonWebServiceRequest()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftCreateGameSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "Aws::GameLift::Model::CreatePlayerSessionRequest::CreatePlayerSessionRequest()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftCreatePlayerSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "vtable for Aws::GameLift::Model::CreateGameSessionRequest", referenced from:
UATHelper: Packaging (iOS):         UGameLiftCreateGameSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         Aws::GameLift::Model::CreateGameSessionRequest::~CreateGameSessionRequest() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
UATHelper: Packaging (iOS):     "Aws::Malloc(char const*, unsigned long)", referenced from:
UATHelper: Packaging (iOS):         UGameLiftCreateGameSession::Activate() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::DescribeMatchmaking() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::DescribeMatchmakingHandler(Aws::GameLift::GameLiftClient const*, Aws::GameLift::Model::DescribeMatchmakingRequest const&, Aws::Utils::Outcome<Aws::GameLift::Model::DescribeMatchmakingResult, Aws::Client::AWSError<Aws::GameLift::GameLiftErrors> > const&, std::__1::shared_ptr<Aws::Client::AsyncCall
erContext const> const&) in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         UGameLiftClientObject::Internal_InitGameLiftClientSDK(FString const&, FString const&, FString const&, bool, int) in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         std::__1::basic_string<char, std::__1::char_traits<char>, Aws::Allocator<char> >::assign(char const*, unsigned long) in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         void std::__1::vector<Aws::GameLift::Model::GameProperty, Aws::Allocator<Aws::GameLift::Model::GameProperty> >::__push_back_slow_path<Aws::GameLift::Model::GameProperty const&>(Aws::GameLift::Model::GameProperty const&&&) in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         Aws::GameLift::Model::GameProperty::GameProperty(Aws::GameLift::Model::GameProperty const&) in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):         ...
UATHelper: Packaging (iOS):     "Aws::GameLift::Model::DescribeMatchmakingRequest::DescribeMatchmakingRequest()", referenced from:
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::DescribeMatchmaking() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     "vtable for Aws::GameLift::Model::DescribeMatchmakingRequest", referenced from:
UATHelper: Packaging (iOS):         UGameLiftStartMatchmaking::DescribeMatchmaking() in Module.GameLiftClientSDK.cpp.o
UATHelper: Packaging (iOS):     NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
UATHelper: Packaging (iOS):     "Aws::InitAPI(Aws::SDKOptions const&)", referenced from:
UATHelper: Packaging (iOS):         FAWSCoreModule::StartupModule() in AWSCoreModule.cpp.o
UATHelper: Packaging (iOS):   ld: symbol(s) not found for architecture arm64

**Comment by wps132230** [comment]
From your log, it seems to be a linkage issue.
Your application failed to link to the libraries because of some reasons, for example the libraries are not for arm64.
