### ISSUE TITLE
Aws::Http::URI undefined for linking

### ISSUE THREAD

**Issue by atlascoder** [aws/aws-sdk-cpp#1082]
### What platform/OS are you using?

MacOS 10.14.2

### What compiler are you using? what version?

Apple LLVM version 10.0.0 (clang-1000.11.45.5)

### What's your CMake arguments?

N/A, static linking to prebuilt AWS libs in a Qt (5.12) project

### Can you provide a TRACE level log? (sanitize any sensitive information)

N/A - see below

--------------

I am trying to inherit from `Aws::Client::AWSJsonClient` in order to get own API client for backend on APIGateway with IAM authentication.
I started by looking into DynamoDBClient implementation. And everything is OK, but I am in stuck with linking to libs.

Particularly, my method:
```
SyncOutcome CorbAPIClient::Sync(const CorbAPI::Model::SyncRequest& request) const
{
    Aws::StringStream ss;
    ss << "/sync";
    Aws::Http::URI uri(m_uri + ss.str());
    JsonOutcome outcome = MakeRequest(uri, request, HttpMethod::HTTP_POST, Aws::Auth::SIGV4_SIGNER);
    if(outcome.IsSuccess()) {
        return SyncOutcome(SyncResult(outcome.GetResult()));
    }
    else {
        return SyncOutcome(outcome.GetError());
    }
}
```

can't be compiled because of linker can't use existing prebuilt libs:

```
Undefined symbols for architecture x86_64:
  "Aws::Http::URI::URI(std::__1::basic_string<char, std::__1::char_traits<char>, Aws::Allocator<char> > const&)", referenced from:
      CorbAPIClient::Sync(CorbAPI::Model::SyncRequest const&) const in CorbAPIClient.o
  "Aws::Client::AWSAuthV4Signer::AWSAuthV4Signer(std::__1::shared_ptr<Aws::Auth::AWSCredentialsProvider> const&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, Aws::Allocator<char> > const&, Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy, bool)", referenced from:
      std::__1::shared_ptr<Aws::Client::AWSAuthV4Signer>
...
```

The aws libs are compiled in working successfully in another project, but there I didn't make any AWS classes extension.

Please, advise.. Thanks!

**Comment by singku** [comment]
Did you define `USE_IMPORT_EXPORT` in your project?

**Comment by atlascoder** [comment]
I still have the same issue with `Aws::Client::AWSAuthV4Signer::AWSAuthV4Signer(std::__1::shared_ptr<Aws::Auth::AWSCredentialsProvider> const&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, Aws::Allocator<char> > const&, Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy, bool)`

and now this is out of my code and I wouldn't like to set crutches here.. I suspect that maybe I need to use some special flags for linker?

**Comment by atlascoder** [comment]
I use static linking, not dynamic.

**Comment by atlascoder** [comment]
I think I understand the problem.. `Aws::Allocator<T>` is a subclass of `std::allocator<T>`, but since it is already compiled into static lib - linker cannot find this match. So, it looks like I have to compile my client as a part of SDK. Right?

And one more quick question: if I understand right, I am unable to use `Aws::Client::AWSJsonClient` directly from my code directly? Then how do you recommend to use your request signing code, or to rewrite it completely?

**Comment by singku** [comment]
It looks like you are using std::string for URI's ctor, I think you need Aws::String.

**Comment by atlascoder** [comment]
No, I use exactly `Aws::String`.
Actually, I've built my client successfully as a part of SDK - not a big deal.

But I am curious if someone can explain this.

The problem is that `Aws::String` is `std::basic_string<char, std::char_traits<char>, Aws::Allocator<char>>` and `Aws::Allocator<T>` in turn is a subclass of `std::allocator<T>`.
In object files (including `libaws-cpp-sdk-core.a`) `Aws::String` has symbol `std::basic_string<char, std::char_traits<char>, std::allocator<char>>`. But when building external project, linker does search can't find match, because it does search symbols `std::basic_string<char, std::char_traits<char>, Aws::Allocator<char>>` and does no find it. I am curious, why it works for SDK build and doesn't for a lib-consumer project?

Thank you for attention!

**Comment by atlascoder** [comment]
Ahh.. It looks like the answer is definition `USE_AWS_MEMORY_MANAGEMENT` that manages what is `Aws::Allocator<T>`: a subclass of `std::allocator<T>` or just an alias for it. Somehow these settings were different in my case...

**Comment by atlascoder** [comment]
Yes, I confirm last answer. After I rebuild libs, this made the same state of `USE_AWS_MEMORY_MANAGEMENT` and it I can build `Aws::Client::AWSJsonClient` sublass successfully.. Why the mess happened - no idea, - but everything it clear now.
