### ISSUE TITLE
Add an example for range decrypt with S3 Encryption Client

### ISSUE THREAD

**Issue by johnwalker** [aws/aws-sdk-cpp#1083]
There should be an example for using range decrypt in AuthenticatedEncryption and EncryptionOnly modes. Today, this is only discoverable by checking integration tests.

**Comment by singku** [comment]
This is a good candidate to https://github.com/awsdocs/aws-doc-sdk-examples, would you mind submitting an issue or a pull request there?

**Comment by johnwalker** [comment]
Done!
