### ISSUE TITLE
Thread join stuck on a conditional variable inside aws sdk

### ISSUE THREAD

**Issue by shounak1** [aws/aws-sdk-cpp#1084]
### What platform/OS are you using?
Ubuntu 14.04

### What compiler are you using? what version?
gcc version 4.8.4

### What's your CMake arguments?
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3" ..

### Can you provide a TRACE level log? (sanitize any sensitive information)
```
#0  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f46080434dc in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007f4604ad8c03 in Aws::Http::CurlHandleContainer::~CurlHandleContainer()
    () from /usr/local/lib/mosmb/libaws-cpp-sdk-core.so
#3  0x00007f4604adf97f in Aws::Http::CurlHttpClient::~CurlHttpClient() ()
   from /usr/local/lib/mosmb/libaws-cpp-sdk-core.so
#4  0x00007f4604aa5599 in Aws::Client::AWSClient::~AWSClient() ()
   from /usr/local/lib/mosmb/libaws-cpp-sdk-core.so
#5  0x00007f4604dbcc81 in __gnu_cxx::new_allocator<Aws::S3::S3Client>::destroy<Aws::S3::S3Client> (this=0x7f4605924650, __p=0x7f4605924658)
    at /usr/include/c++/4.8/ext/new_allocator.h:124
#6  0x00007f4604dbcb0e in std::allocator_traits<Aws::Allocator<Aws::S3::S3Client> >::_S_destroy<Aws::S3::S3Client> (__a=..., __p=0x7f4605924658)
    at /usr/include/c++/4.8/bits/alloc_traits.h:281
#7  0x00007f4604dbc604 in std::allocator_traits<Aws::Allocator<Aws::S3::S3Client> >::destroy<Aws::S3::S3Client> (__a=..., __p=0x7f4605924658)
    at /usr/include/c++/4.8/bits/alloc_traits.h:405
#8  0x00007f4604dbb4f9 in std::_Sp_counted_ptr_inplace<Aws::S3::S3Client, Aws::Allocator<Aws::S3::S3Client>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (
    this=0x7f4605924640) at /usr/include/c++/4.8/bits/shared_ptr_base.h:407
#9  0x00007f4604daedf2 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7f4605924640) at /usr/include/c++/4.8/bits/shared_ptr_base.h:144
#10 0x00007f4604dabe2f in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7f4600c7ea98, __in_chrg=<optimized out>)
    at /usr/include/c++/4.8/bits/shared_ptr_base.h:546
#11 0x00007f4604dab590 in std::__shared_ptr<Aws::S3::S3Client, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7f4600c7ea90, __in_chrg=<optimized out>)
    at /usr/include/c++/4.8/bits/shared_ptr_base.h:781
#12 0x00007f4604dadd41 in std::__shared_ptr<Aws::S3::S3Client, (__gnu_cxx::_Lock_policy)2>::reset (this=0x7f460594f1c0)
    at /usr/include/c++/4.8/bits/shared_ptr_base.h:882
```
I am trying to perform a put object request by spawing a pthread. However if i cancel the pthread performing the put object and try to join it, the pthread_join operation is stuck forever. On attaching the debugger, I found out that it was stuck on condition variable inside aws sdk.

On de-initialization of my program a destructor is being called which takes care of calling the ShutdownAPI before the pthread_cancel operation happens on the put object thread.

Am I doing anything wrong. Please help. My main motive is to perform the necessary handling if the program is stopped during a put object request.

**Comment by webbnh** [comment]
> a destructor is being called which takes care of calling the ShutdownAPI before the pthread_cancel operation happens

I'm not an expert on the AWS SDK, but my understanding is that the ShutdownAPI is supposed to be the last thing done...so it strikes me that you need to have cleaned up all other threads in and using the SDK _before_ you invoke the shutdown function.  (That is, the shutdown is probably removing whatever would have awakened your target thread from the condition variable....)
