### ISSUE TITLE
 CognitoIdentity::GetCredentialsForIdentity() failes saying 'Unable to connect to endpoint'

### ISSUE THREAD

**Issue by salunkhesagar1386** [aws/aws-sdk-cpp#1085]
On Android the I am getting this exception from AWS. This same C++ code works fine on iOS and Windows. I have created a common C++ lib and build it for multiple platforms. I use SWIG to generate the JNI Wrappers to consume this C++ lib into Android application. 

Just FYI, I have created a .arr wrapper project which acts as a bridging between C++ and Java code. Also added following to load all the C++ .so files. **MyC++Lib** is the C++ library which uses the AWS SDKs to communicate with.

System.loadLibrary("**MyC++Lib**");
System.loadLibrary("aws-c-common");
System.loadLibrary("aws-c-event-stream");
System.loadLibrary("aws-checksums");
System.loadLibrary("aws-cpp-sdk-cognito-identity");
System.loadLibrary("aws-cpp-sdk-core");
System.loadLibrary("aws-cpp-sdk-identity-management");
System.loadLibrary("aws-cpp-sdk-s3");
System.loadLibrary("aws-cpp-sdk-sts");

### This is the error:
**Message: Unable to connect to endpoint
Http Response Code: -799497216
Error Type: NETWORK_CONNECTION
Response Header**s: 

### Code:
_String strUserPoolARN = "<My_ARN>";
String strUserPoolId = "<My_POOL_ID>";
std::string strIDToken = "<My_ID_Token>";
Map<String, String> logins;
logins.insert(std::make_pair(strUserPoolARN.c_str(), strIDToken.c_str()));
ClientConfiguration clientConfiguration;
clientConfiguration.region = Region::US_EAST_1;
GetIdRequest getIDRequest;
getIDRequest.WithIdentityPoolId(strUserPoolId.c_str()).WithLogins(logins);
CognitoIdentityClient identityClient(clientConfiguration);
GetIdOutcome idResult = identityClient.GetId(getIDRequest);
GetCredentialsForIdentityRequest getCredentialsRequest;
getCredentialsRequest.WithIdentityId(idResult.GetResult().GetIdentityId()).WithLogins(logins);
**GetCredentialsForIdentityOutcome getCredentialsResult = identityClient.GetCredentialsForIdentity(getCredentialsRequest);**_

### What platform/OS are you using?
Android

### What compiler are you using? what version?
Clang 3.8 / 5.0

**Comment by singku** [comment]
Could you please upload the whole log (sanitize sensitive information)?

**Comment by salunkhesagar1386** [comment]
Thanks @singku 👍 
There are no relevant logs for AWS services apart from this as its not crashing at any place. To add more information, my C++ library also uses libCurl. I am making sure to call Global_Init and release once its done. I am not able to turn the AWS logging ON somehow. Its giving me linker error for initLogging method when called in C++ code. 

Could you please help me enabling the AWS logging in C++ code? Is there anything I need to do while generating the AWS Android SDK libs in CMake file? If I am not doing anything then I was expecting that AWS default logging should work.

**Comment by singku** [comment]
https://github.com/aws/aws-sdk-cpp#Logging
And you can change `Info` to `Trace`

**Comment by martinkbrown** [comment]
@singku do you know where the log file gets generated on Android? We found that we had to build with the CMake flag `CUSTOM_MEMORY_MANAGEMENT=1` in order for our project to find the definition for `Aws::Utils::Logging::DefaultLogSystem`. We also built with the flag `AWS_CUSTOM_MEMORY_MANAGEMENT`. At build time we get the following warning:

CMake Warning:
  Manually-specified variables were not used by the project:

    AWS_CUSTOM_MEMORY_MANAGEMENT

In either case, we also tried to turn on logging with and without this build flag, and with and without the definition for this flag on one of our .h files.

`#define AWS_CUSTOM_MEMORY_MANAGEMENT` as specified [here](https://github.com/aws/aws-sdk-cpp/issues/69).

We searched 

1. Android Logcat output

2. the device internal storage directory (the browsable directory on Android containing the default Download directory)
3. the device /data/data directory for our app
4. the device /data/app directory for our app

But we didn't find any Logcat output or file being generated.

In our .cpp file we have the following taken from [this example](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/logging.html)

`m_SDKOptions.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::Utils::Logging::InitializeAWSLogging(
	Aws::MakeShared<Aws::Utils::Logging::DefaultLogSystem>(
		"SagarAwsLogging", Aws::Utils::Logging::LogLevel::Trace, "aws_sdk_"));
	
InitAPI(m_SDKOptions);`

And at the end our .cpp file we have the following 

`Aws::Utils::Logging::ShutdownAWSLogging();
ShutdownAPI(m_SDKOptions);`

We are also not getting a valid `Aws::Http::HttpResponseCode`. We have

`switch (httpResponseCode)
{
	case Aws::Http::HttpResponseCode::REQUEST_NOT_MADE:
		strResponseCode = "REQUEST_NOT_MADE";
		break;
		… // All other cases are here
	case Aws::Http::HttpResponseCode::NETWORK_CONNECT_TIMEOUT:
			strResponseCode = "NETWORK_CONNECT_TIMEOUT";
			break;
	default:
		strResponseCode = "Got Invalid HttpResponseCode Value";
			
		break;
}
		
	std::stringstream ssHttpResponseCode;
	ssHttpResponseCode << static_cast<int>(httpResponseCode);`

It goes into the default case and the response code is being returned as 0.

Thank you.

**Comment by martinkbrown** [comment]
Since we couldn't figure out where the logs were being written, we added our own `__android_log_print()` calls to DefaultLogSystem.cpp and that showed us the logs in Android Logcat. The error we get is

> Curl returned error code 60 - Peer certificate cannot be authenticated with given CA certificates

So we will use this to continue troubleshooting the issue on our end. Thanks.

**Comment by salunkhesagar1386** [comment]
After going through few posts, I learned that we can get rid of this libCurl error if we set the 'ClientConfiguration.verifySSL = false'. Tried doing the same and executed the application but now I am getting following error,

**GetCredentialsForIdentityOutcome Failed.** 
**Error**: _ValidationException_
**Message**: _3 validation errors detected: Value '{xx.xx.xx/xx-xx-xx-xx-xx=}' at 'logins' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1]; Value '' at 'identityId' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'identityId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]+:[0-9a-f-]+_
    _Http Response Code: BAD_REQUEST
    Error Type: VALIDATION
    Response Headers: connection : keep-alive
    content-length : 551
    content-type : application/x-amz-json-1.1
    date : Wed, 13 Mar 2019 15:47:17 GMT
    x-amzn-errormessage : 3 validation errors detected: Value '{xx.xx.xx/xx-xx-xx-xx-xx=}' at 'logins' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 500_

**Comment by singku** [comment]
@martinkbrown Normally you don't need to call `InitializeAWSLogging` and `ShutdownAWSLogging`. SDK will do that for you.
For Android, I think the place where you can generate a log file is restricted. You can specify the place by setting `options.loggingOptions.defaultLogPrefix` to sth like  `[CWD]/[YourLogFilePrefix]'

**Comment by singku** [comment]
@salunkhesagar1386  Not sure if your question is related to this topic. But you should check the values in request, if they meet the requirements.
