### ISSUE TITLE
S3 GetBucketAcl and GetObjectAcl do not return Grantee Type

### ISSUE THREAD

**Issue by SCalwas** [aws/aws-sdk-cpp#1088]
The S3Client methods ``GetBucketAcl`` and ``GetObjectAcl`` do not set the Grantee Type field in the returned access control list. The Type is returned by AWS in an xsi:type attribute as shown below. The Type is required for any subsequent calls to ``PutBucketAcl/PutObjectAcl`` so not including it results in an incomplete ACL.

``<Grantee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="CanonicalUser">``

Example C++ code that exercises ``GetBucketAcl`` and ``GetObjectAcl`` is available [in my repo](https://github.com/SCalwas/aws-s3-acl).

**Comment by singku** [comment]
Thank you. PR is welcomed.
