### ISSUE TITLE
S3 PutBucketAcl and PutObjectAcl generate malformed XML

### ISSUE THREAD

**Issue by SCalwas** [aws/aws-sdk-cpp#1089]
The S3Client methods ``PutBucketAcl`` and ``PutObjectAcl`` generate malformed XML for the access control list included in the HTTP request. Two errors exist.

- Missing \<AccessControlList\> element. The list of \<Grant\> elements must be in an \<AccessControlList\> parent.
- The \<Grantee\> type is incorrectly specified as an \<xsi:type\> element.

The correct XML syntax to generate is shown below.

```
...
<AccessControlList>
    <Grant>
        <Grantee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="CanonicalUser">
...
```
Example C++ code that exercises Get/Put Bucket/Object Acl is available [in my repo](https://github.com/SCalwas/aws-s3-acl).

**Comment by singku** [comment]
@SCalwas Thank you. We made a PR to fix this problem. It will be merged soon.
