### ISSUE TITLE
Expose GetType() Method in Aws::DynamoDB::Model::AttributeValue

### ISSUE THREAD

**Issue by reremington** [aws/aws-sdk-cpp#1094]
It would be very helpful to be able to query the data type ahead of time for an `Aws::DynamoDB::Model::AttributeValue` so that the proper getter function can be invoked to retrieve the value. It appears the underlying `Aws::DynamoDB::Model::AttributeValueValue` already has a method for this (see [here](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-dynamodb/include/aws/dynamodb/model/AttributeValueValue.h#L76)) so it would just be a matter of adding this method to the `Aws::DynamoDB::Model::AttributeValue` class.

**Comment by singku** [comment]
Thanks, we'll consider adding that.

**Comment by singku** [comment]
It will be released soon.
