### ISSUE TITLE
custom RetryStrategy not working, download never dies

### ISSUE THREAD

**Issue by mattman71** [aws/aws-sdk-cpp#1097]
### Summary
I have created my own retry strategy to try to resolve an issue where a download never fails out, but it is still not working. In my log, the retry strategy is clearly doing what it is supposed to, and is telling the caller when not to retry, but the aws engine just keeps restarting forever and will never error out. I'm never calling RetryDownload, and mostly have just a simple setup calling DownloadFile and WaitUntilFinished. I do have a downloadProgressCallback, but it does not appear to be involved. I'm never getting past the WaitUntilFinished. I currently have no errorCallback, no statusUpdatedCallback. I did, at one point, add those to spam my log, but there wasn't any additional helpful information coming through.

My test scenario is that I launch this download on a large file, let it go through several chunks, then unplug the network cable. With my retry strategy asking for 5 retries and a delay of 6 seconds between retry, I'm expected it to error out in 30 seconds (give or take some margin of error due to threading). But it never stops trying. I could let it run for days, long after sessions have expired and all, it still won't give up.

In the log snippet below, you can see the ShouldRetry in action, telling it to stop, but it just starts over with attempt 0 and this continues forever. The delay between retries also seems to have no effect, though it's hard to tell for sure because of the threaded executor.

Using the default executor instead of the threaded pool executor seems to have no effect.

What am I doing wrong?

### What platform/OS are you using?
Windows 64-bit

### What version of the SDK are you using?
1.5.17

### What compiler are you using? what version?
Visual Studio 2017

### What's your CMake arguments?
- -DBUILD_ONLY="s3;transfer"
- -DTARGET_ARCH="WINDOWS"
- -DCPP_STANDARD=17
- -G "Visual Studio 15 2017 Win64" 
- -DBUILD_SHARED_LIBS=OFF
- -DFORCE_SHARED_CRT=OFF
- -DENABLE_UNITY_BUILD=ON

### Can you provide a TRACE level log? (sanitize any sensitive information)
```
2019/03/22 15:12:48.731981 | 1724|Warning|mynamespace::AwsLoggerAdapter::LogStream| [WinHttpSyncHttpClient] Send request failed: The server name or address could not be resolved


2019/03/22 15:12:48.731981 | 1724|Error  |mynamespace::AwsLoggerAdapter::LogStream| [AWSClient] HTTP response code: -858993460
Exception name: 
Error message: Unable to connect to endpoint
0 response headers:
2019/03/22 15:12:48.731981 | 1724|Warning|mynamespace::AwsLoggerAdapter::LogStream| [AWSClient] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2019/03/22 15:12:48.731981 | 1724|Verbose|mynamespace::MyRetryStrategy::ShouldRetry| 6/5; ErrorType: 99; ResponseCode: -858993460; return - false
2019/03/22 15:12:48.731981 | 1724|Error  |mynamespace::AwsLoggerAdapter::LogStream| [TransferManager] Transfer handle [FD0CA6B5-E793-47B6-9292-718EFA91E4CE] Failed to download object in Bucket: [bucketname] with Key: [myfilename] HTTP response code: -858993460
Exception name: 
Error message: Unable to connect to endpoint
0 response headers:
2019/03/22 15:12:48.731981 | 1100|Warning|mynamespace::AwsLoggerAdapter::LogStream| [WinHttpSyncHttpClient] Send request failed: The server name or address could not be resolved
```

Random code snippets for context..
```
...
executor = Aws::MakeShared<Aws::Utils::Threading::PooledThreadExecutor>(ALLOCATION_TAG, 4);
...
config->retryStrategy = Aws::MakeShared<MyRetryStrategy>(ALLOCATION_TAG, 5, 6000, 0);
...
    downloadPtr = transferManager->DownloadFile(bucket, key, filename);
    downloadPtr->WaitUntilFinished();
...
    class AWS_CORE_API MyRetryStrategy: public Aws::Client::RetryStrategy
    {
    public:
        explicit MyRetryStrategy(int32_t maxRetries = DEFAULT_RETRIES, int32_t millisecondDelayBetweenRetries = DEFAULT_RETRY_DELAY_MS, int32_t retryDelayMultiplier = DEFAULT_RETRY_MULTIPLIER);
        long CalculateDelayBeforeNextRetry(const Aws::Client::AWSError<Aws::Client::CoreErrors>& error, long attemptedRetries) const override;
        bool ShouldRetry(const Aws::Client::AWSError<Aws::Client::CoreErrors>& error, long attemptedRetries) const override;
    private:
        int32_t m_maxRetries;
        int32_t m_msDelayBetweenRetries;
        int32_t m_retryDelayMultiplier;
        std::map<Aws::Client::CoreErrors, bool> m_errorsAllowingRetry;
    };
...
    MyRetryStrategy::MyRetryStrategy(int32_t maxRetries, int32_t millisecondDelayBetweenRetries, int32_t retryDelayMultiplier)
        :
        m_maxRetries(maxRetries),
        m_msDelayBetweenRetries(millisecondDelayBetweenRetries),
        m_retryDelayMultiplier(retryDelayMultiplier)
    {
        m_errorsAllowingRetry =
        {
            {Aws::Client::CoreErrors::INCOMPLETE_SIGNATURE, true},
            {Aws::Client::CoreErrors::INTERNAL_FAILURE, true},
            {Aws::Client::CoreErrors::INVALID_ACTION, true},
            {Aws::Client::CoreErrors::INVALID_CLIENT_TOKEN_ID, true},
            {Aws::Client::CoreErrors::INVALID_PARAMETER_COMBINATION, true},
            {Aws::Client::CoreErrors::INVALID_QUERY_PARAMETER, true},
            {Aws::Client::CoreErrors::INVALID_PARAMETER_VALUE, true},
            {Aws::Client::CoreErrors::MISSING_ACTION, false}, // SDK should never allow
            {Aws::Client::CoreErrors::MISSING_AUTHENTICATION_TOKEN, false}, // SDK should never allow
            {Aws::Client::CoreErrors::MISSING_PARAMETER, false}, // SDK should never allow
            {Aws::Client::CoreErrors::OPT_IN_REQUIRED, true},
            {Aws::Client::CoreErrors::REQUEST_EXPIRED, true},
            {Aws::Client::CoreErrors::SERVICE_UNAVAILABLE, true},
            {Aws::Client::CoreErrors::THROTTLING, true},
            {Aws::Client::CoreErrors::VALIDATION, true},
            {Aws::Client::CoreErrors::ACCESS_DENIED, true},
            {Aws::Client::CoreErrors::RESOURCE_NOT_FOUND, true}, // Shared with multiple services
            {Aws::Client::CoreErrors::UNRECOGNIZED_CLIENT, false}, // Most likely caused by an invalid access key or secret key
            {Aws::Client::CoreErrors::MALFORMED_QUERY_STRING, false}, // Where does this come from? (cognito identity uses it)
            {Aws::Client::CoreErrors::SLOW_DOWN, true},
            {Aws::Client::CoreErrors::REQUEST_TIME_TOO_SKEWED, true},
            {Aws::Client::CoreErrors::INVALID_SIGNATURE, true},
            {Aws::Client::CoreErrors::SIGNATURE_DOES_NOT_MATCH, true},
            {Aws::Client::CoreErrors::INVALID_ACCESS_KEY_ID, true},
            {Aws::Client::CoreErrors::REQUEST_TIMEOUT, true},
            {Aws::Client::CoreErrors::NETWORK_CONNECTION, true}, // General failure to send message to service 
            {Aws::Client::CoreErrors::UNKNOWN, false}, // Unknown to the SDK (this happens upon cancel, not sure what else would cause it)
            {Aws::Client::CoreErrors::SERVICE_EXTENSION_START_RANGE, true},
        };
    }

    long MyRetryStrategy::CalculateDelayBeforeNextRetry(const Aws::Client::AWSError<Aws::Client::CoreErrors>& error, const long attemptedRetries) const
    {
        if (!m_retryDelayMultiplier || !m_errorsAllowingRetry.count(error.GetErrorType()) || !m_errorsAllowingRetry.at(error.GetErrorType()))
        {
            return m_msDelayBetweenRetries;
        }
        return attemptedRetries * m_msDelayBetweenRetries * m_retryDelayMultiplier;
    }

    bool MyRetryStrategy::ShouldRetry(const Aws::Client::AWSError<Aws::Client::CoreErrors>& error, const long attemptedRetries) const
    {
        const bool allow =
            (attemptedRetries <= m_maxRetries) &&
            m_errorsAllowingRetry.count(error.GetErrorType()) &&
            m_errorsAllowingRetry.at(error.GetErrorType());
        LogVerbose << attemptedRetries << L"/" << m_maxRetries << L"; ErrorType: " << static_cast<int32_t>(error.GetErrorType()) << L"; ResponseCode: " << static_cast<int32_t>(error.GetResponseCode()) << L"; return - " << allow;
        return allow;
    }

```

**Comment by singku** [comment]
Take a look at TransferManagerTest  
https://github.com/aws/aws-sdk-cpp/blob/eff72ec575a952b15897f13477c374d24b05fdbb/aws-cpp-sdk-transfer-tests/TransferTests.cpp#L1132-L1154

You should ask transferManager to stop downloading once there is one part that failed to be downloaded.
Otherwise, transferManager will keep downloading the rest parts until all parts are failed to be downloaded. Instead of never, it will stop at sometime. I don't know why you said it's never gonna give up downloading, have you verified that? How large is that target file? If it's like 10GB, you only have 4 threads. and each will cost 30s. The default part size is 5MB. It will end in 10GB/5MB/8parts = 1250 minutes.

**Comment by mattman71** [comment]
Thanks for the reply, @singku!

I didn't see any interaction in that test about failed parts. I wasn't sure if I could use failedparts count. So you're saying that if there are any failedparts at all, those aren't going to be subject to retry because the retry limits would have already been reached before it landed in the failedparts? If that is the case, then I think I understand what you mean and can then just check for that and issue the cancel as your sample above is doing.

Do you find it best to do that cancel in transferStatusUpdatedCallback rather than errorCallback? Or does it matter?

I need to make sure I only do the cancel once, right? Not once per thread or anything like that (since I guess I don't have visibility to the underlying threads anyway).

**Comment by singku** [comment]
> those aren't going to be subject to retry because the retry limits would have already been reached before it landed in the failed parts.

Correct.

>Do you find it best to do that cancel in transferStatusUpdatedCallback rather than errorCallback? Or does it matter?

Doesn't matter, both callback will be called if you set them.

You just need to cancel download for handle. All threads are testing the handle's status to determine if they should continue.

**Comment by mattman71** [comment]
Confirmed that this technique works. Thanks for the tips! The critical part was understanding that HasFailedParts is the signal of when to cancel (and keeping an atomic bool to make sure cancel is only called once is a good idea).
