### ISSUE TITLE
Do you need GUI?

### ISSUE THREAD

**Issue by topilski** [aws/aws-sdk-cpp#1098]
Hi, do you need gui for DynamoDB?

**Comment by singku** [comment]
Currently we don't have this requirement. Do you have one or do you need it?

**Comment by topilski** [comment]
@singku we have solution, were can integrate api for NoSQL key/value databases, here our website: https://fastonosql.com/ and sources https://github.com/fastogt/fastonosql

**Comment by singku** [comment]
Thanks @topilski I'll forward this to our PM team and if possible ask them to talk to you.

**Comment by topilski** [comment]
Thank you.
