### ISSUE TITLE
Can I validate each piece when multi-part Get() by range?

### ISSUE THREAD

**Issue by lsong0905** [aws/aws-sdk-cpp#1100]
Hello,

I have a question regarding reading an object in pieces (by range) and integrity of each piece.
Let's say I have uploaded an object either using a single PUT or multi-part upload. When I try to read this object in pieces (say a set of 5MB GET()), can I validate the checksum of each piece?
Is the checksum from its ETag same as the locally calculated MD5 checksum? 

The doc (https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html) says ETag is NOT MD5 digest. However, in this forum (https://github.com/aws/aws-sdk-java/issues/970), it may seem possible to validate each piece. 

Can I get some help on this?

**Comment by singku** [comment]
>The entity tag is a hash of the object. The ETag reflects changes only to the contents of an object, not its metadata. The ETag may or may not be an MD5 digest of the object data. Whether or not it is depends on how the object was created and how it is encrypted as described below:

>If an object is created by either the Multipart Upload or Part Copy operation, the ETag is not an MD5 digest, regardless of the method of encryption.

In your case (Multipart upload), Etag is not the same as MD5

**Comment by lsong0905** [comment]
What if the object is uploaded by a single Put() but read in pieces (by range), is Etag of each piece the same as MD5?

**Comment by singku** [comment]
It is not explicitly documented in S3's documentation. You need to verify if that's the case.
