### ISSUE TITLE
Support for new Android NDK

### ISSUE THREAD

**Issue by atlascoder** [aws/aws-sdk-cpp#1103]
I use the SDK for building apps for Android with Qt. Latest LTS Qt (5.12) support latest NDK that is 19c. But with the SDK I can use 12b and not later. It works, but in my case it is stable only with STL `gnustl_shared` and GCC. But I would like to use Clang and libc++ with Qt 5.12.

Do you plan to upgrade Android NDK support?

**Comment by wps132230** [comment]
Thank you for your suggestion.
Android NDK upgrade is in our plan.

**Comment by atlascoder** [comment]
That would be very cool, Thanks!

**Comment by jkoutavas** [comment]
@wps132230, can you give an update on how this work is going? Is it in active development?

**Comment by wps132230** [comment]
@jkoutavas Thank you for your patience, it's still in progress.

**Comment by singku** [comment]
Now we support latest NDK r19c (back to 13b) with their own toolchain files, 12b is not supported anymore. Please reopen if you still have problem.

**Comment by atlascoder** [comment]
cool!! thanks!
