### ISSUE TITLE
Compiling for Android failing with CMake 3.10.2

### ISSUE THREAD

**Issue by naja1987** [aws/aws-sdk-cpp#1104]
### What platform/OS are you using?

Ubuntu 18.04.2

### What compiler are you using? what version?

CMake 3.10.2

### What's your CMake arguments?

`cmake  -DBUILD_ONLY="s3;iot" -DENABLE_TESTING=OFF -DTARGET_ARCH=ANDROID -DNDK_DIR=/path/to/android-ndk-r12b ..`

### Can you provide a TRACE level log? (sanitize any sensitive information)

```
-- Found Git: /usr/bin/git (found version "2.21.0") 
-- Building AWS libraries as shared objects
-- Android ABI: none specified, defaulting to armeabi-v7a
-- Android toolchain unspecified, defaulting to standalone-clang
-- Android std lib: libc++_shared
-- Android API level: android-21
-- Detected NDK version r12b
-- Could not find an appropriate standalone toolchain.  Generating one into /my/path/aws-sdk-cpp/build_android/toolchains/android/armeabi-v7a-standalone-clang-android-21-libc++_shared-12002
-- Building project version: 1.7.78
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "/my/path/aws-sdk-cpp/build_android/.deps/CMakeFiles/CMakeOutput.log".
CMake Error at CMakeLists.txt:183 (message):
  Failed to configure third-party libraries.

-- Configuring incomplete, errors occurred!
```

Interestingly, with CMake version 3.6 it is working (I used the one provided by Android Studio).

**Comment by wps132230** [comment]
Thank you for reporting this issue.
We are using a quite old NDK, which is not compatible with the new cmake.
And we are trying to make SDK build with latest Android NDK right now.

**Comment by singku** [comment]
Now we support latest NDK r19c (back to 13b) with their own toolchain files, 12b is not supported anymore. Please reopen if you still have problem.
