### ISSUE TITLE
If set verifySSL as false in ClientConfiguration, what's the risk?

### ISSUE THREAD

**Issue by harvychen** [aws/aws-sdk-cpp#1105]
In production environment (AWS EC2), If set verifySSL as false in ClientConfiguration, what's the risk?

Because it was found that when use verifySSL default value ### **true**, the daemon process use SQS SDK will make memory keep increase, related with this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1395803

But if disable the verifySSL, there will be no leak.

Of course, upgrade libcurl using openSSL is also the solution.

**Comment by singku** [comment]
This page explain the risks for you.
https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html
In short, no verification could lead to middle-man-attack
