### ISSUE TITLE
Is there a way to enable curl logs? 

### ISSUE THREAD

**Issue by howryu** [aws/aws-sdk-cpp#1106]
Default http client is libcurl and libcurl has an options to pass in DEBUG_FUNCTION https://curl.haxx.se/libcurl/c/CURLOPT_DEBUGFUNCTION.html

I wonder if AWS sdk has a way to enable logs from curl?

**Comment by singku** [comment]
There is a way, but currently it's not well done, you have to manually uncomment two lines to enable it.
https://github.com/aws/aws-sdk-cpp/blob/b483c95150bdc73ceb9ed69bc61e85a0543c8272/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp#L416-L417

**Comment by singku** [comment]
A new CMake option ENABLE_CURL_LOGGING has been added, will be merged soon.
