### ISSUE TITLE
aws-cpp-sdk-core-tests HttpClientTest.TestNullResponse fails if NO_HTTP_CLIENT and no HTTP_CLIENT replacement provided

### ISSUE THREAD

**Issue by onich** [aws/aws-sdk-cpp#1107]
If you define `NO_HTTP_CLIENT=1` in CMake and don't provide a replacement the `HttpClientTest.TestNullResponse` will fail with `unknown file: error: SEH exception with code 0xc0000005 thrown in the test body`, as it tries to call a method on a null pointer (`auto response = httpClient->MakeRequest(request);`).

Is this expected behaviour?

It seems like it would be a good idea to add a new CMake arg for the replacement HTTP_CLIENT and if it isn't supplied then this test wouldn't run.

**Comment by singku** [comment]
Good catch. Will fix it soon.

**Comment by singku** [comment]
Fixed and merged https://github.com/aws/aws-sdk-cpp/commit/870c54cc3b143551401c554026e9cc83b394c933
