### ISSUE TITLE
FormattedLogSystem problematic

### ISSUE THREAD

**Issue by binary132** [aws/aws-sdk-cpp#1111]
I'm implementing `Aws::Utils::Logging::FormattedLogSystem` for the logger backend I'm using, https://github.com/gabime/spdlog.  Your interface specifies a required override which is commented as unsafe:

> aws/core/utils/logging/FormattedLogSystem.h : 53

```cpp
                /**
                 * Does a printf style output to ProcessFormattedStatement. Don't use this, it's unsafe. See LogStream
                 */
                virtual void Log(LogLevel logLevel, const char* tag, const char* formatStr, ...) override;
```

It also requires another problematic override, which is incompatible with my requirements, since it does not allow a standard loglevel or any other information to be passed.  `spdlog` defines a consistent level-based logger throughout its API. 

> aws/core/utils/logging/FormattedLogSystem.h : 67

```cpp
                /**
                 * This is the method that most logger implementations will want to override.
                 * At this point the message is formatted and is ready to go to the output stream
                 */                
                virtual void ProcessFormattedStatement(Aws::String&& statement) = 0;
```

Is there really no better way to accomplish this?  Loggers that support the canonical logging levels are not going to have a compatible API.

**Comment by singku** [comment]
You can override LogStream
