### ISSUE TITLE
Share Glacier upload multipart archive sample please 

### ISSUE THREAD

**Issue by maxima120** [aws/aws-sdk-cpp#1112]
Can't find finished sample for multipart upload. Am not C specialist so it would help if anyone can share. Thank you 

PS .net sdk doesn't perform as well as other sdks hence I am going to call c++ function.

**Comment by singku** [comment]
Currently there is only [upload archive example](https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/cpp/example_code/glacier/upload_archive.cpp) in our example repo, you can submit an issue there to ask them to provide. But [Here](https://docs.aws.amazon.com/amazonglacier/latest/dev/uploading-archive-mpu.html) is the complete document and java sample, you can just follow the steps and translate the java code to C++.

**Comment by maxima120** [comment]
I have it working in c#. C++ unmanaged is quite different from java or sharp. So I hoped someone from the community would share.

**Comment by maxima120** [comment]
I didn't realise samples was separate repo.
