### ISSUE TITLE
Unable to build applications using CPP SDK on ARM platforms

### ISSUE THREAD

**Issue by gplhegde** [aws/aws-sdk-cpp#1115]
### What platform/OS are you using?
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch

Hardware: RK3288 - ARMv7 platform

### What compiler are you using? what version?
g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

### What's your CMake arguments?
cmake -DBUILD_ONLY="s3;transfer" -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/usr/local \
  -DENABLE_TESTING=OFF \
  ..

### Can you provide a TRACE level log? (sanitize any sensitive information)
CMake Error at /usr/local/lib/cmake/AWSSDK/AWSSDKConfig.cmake:237 (math):
  math cannot parse the expression: "-1+1": syntax error, unexpected
  exp_MINUS, expecting exp_OPENPARENT or exp_NUMBER (1)
Call Stack (most recent call first):
  /usr/local/lib/cmake/AWSSDK/AWSSDKConfig.cmake:280 (AWSSDK_DETERMINE_LIBS_TO_LINK)
  CMakeLists.txt:56 (find_package)

CMake Error at /usr/local/lib/cmake/AWSSDK/AWSSDKConfig.cmake:254 (math):
  math cannot parse the expression: "-1+1": syntax error, unexpected
  exp_MINUS, expecting exp_OPENPARENT or exp_NUMBER (1)
Call Stack (most recent call first):
  /usr/local/lib/cmake/AWSSDK/AWSSDKConfig.cmake:280 (AWSSDK_DETERMINE_LIBS_TO_LINK)
  CMakeLists.txt:56 (find_package)

### CMake version
cmake version 3.7.2

### Commands used to find SDK libs
find_package(AWSSDK REQUIRED COMPONENTS s3 core transfer)
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} /usr/lib/cmake)

**Comment by singku** [comment]
I remember this is an bug in old CMake and has been fixed? We also bypassed this error in Sdk. What's the SDK version you used and can you msure the cmake you used is 3.7?

**Comment by wps132230** [comment]
We've fixed a bug in old SDK: https://github.com/aws/aws-sdk-cpp/commit/9d171a58dd0d9c1e6ab798c6f0d4e2c5e617af8f
Could you checkout to the latest version of SDK?

**Comment by gplhegde** [comment]
I checked out the v1.6.0 . I will use the latest version and change the cmake version and retry. Thanks
