### ISSUE TITLE
ld: file not found: @rpath/libaws-c-common.0unstable.dylib for architecture x86_64

### ISSUE THREAD

**Issue by benoitc** [aws/aws-sdk-cpp#1116]
using the version 1.7.80 I get the following issue when building a prject againsta ws-sdk-cpp 1.7.80 on my imac pro:

```
ld: file not found: @rpath/libaws-c-common.0unstable.dylib for architecture x86_64
```

See related issue opened on Homebrew/homebrew-core#38932 for more informations about the platform and version used. I guess some recent changes in the build is causing that issue but not sure how to fix it. Any idea is welcome.

**Comment by singku** [comment]
Hi, I just did a clean `brew install aws-sdk-cpp` on my Macbook Pro, it worked with my test application.

**Comment by benoitc** [comment]
@singku nope I just did a fresh install on a machine and reproduced the issue. I will rtry with latest xcode version that landed last night there though

**Comment by benoitc** [comment]
error still persist but thanks to have tested it.
