### ISSUE TITLE
Glacier .NET SDK demonstrates way slower upload speed than python. Fix?

### ISSUE THREAD

**Issue by maxima120** [aws/aws-sdk-cpp#1117]
Once of our clients has dedicated 5Gbps link to Amazon. 

Their python test code (taken from github sample basically) beats my .NET code x3 (700 Mbps vs 2000Mbps). I spent some time trying to fine tune it, even wrote my own treehash generator to make sure not to use slow .NET managed SHA version. And yet..

Then an Amazon rep mentioned in "not so official" conversation that AWS Glacier .NET SDK actually cant match other SDKs in upload speeds and that the Python is the fastest.

Can you acknowledge this? **Are you going to "fix" this?** I mean 300% difference in throughput - is a shame, wouldn't you agree? [before you ask - no, the client (and few others too) don't want to use S3 with transitioning to Glacier, they want direct access to Glacier]

**Comment by singku** [comment]
Should you ask this on .Net SDK? https://github.com/aws/aws-sdk-net

**Comment by maxima120** [comment]
Sorry my bad
