### ISSUE TITLE
Build fails with BUILD_ONLY

### ISSUE THREAD

**Issue by ThanasisPap** [aws/aws-sdk-cpp#1119]
*when I am not using -DBUILD_ONLY the SDK builds successfully.

### CMakeError.log
Determining if the pathconf exist failed with the following output:
Change Dir: C:/AWS/SDK/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe" "cmTC_abc88.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=15.0"
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

Build started 15-Apr-19 6:48:49 PM.

Project "C:\AWS\SDK\CMakeFiles\CMakeTmp\cmTC_abc88.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_abc88.dir\Debug\".

  Creating directory "C:\AWS\SDK\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_abc88.dir\Debug\cmTC_abc88.tlog\".

InitializeBuildStatus:

  Creating "cmTC_abc88.dir\Debug\cmTC_abc88.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\CL.exe /c /Zi /W4 /WX /diagnostics:classic /MP /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_abc88.dir\Debug\\" /Fd"cmTC_abc88.dir\Debug\vc141.pdb" /Gd /TP /FC /errorReport:queue  /bigobj C:\AWS\SDK\CMakeFiles\CMakeTmp\CheckSymbolExists.cxx

  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27024.1 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W4 /WX /diagnostics:classic /MP /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_abc88.dir\Debug\\" /Fd"cmTC_abc88.dir\Debug\vc141.pdb" /Gd /TP /FC /errorReport:queue  /bigobj C:\AWS\SDK\CMakeFiles\CMakeTmp\CheckSymbolExists.cxx

  CheckSymbolExists.cxx

  

c:\aws\sdk\cmakefiles\cmaketmp\checksymbolexists.cxx(2): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [C:\AWS\SDK\CMakeFiles\CMakeTmp\cmTC_abc88.vcxproj]

Done Building Project "C:\AWS\SDK\CMakeFiles\CMakeTmp\cmTC_abc88.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\AWS\SDK\CMakeFiles\CMakeTmp\cmTC_abc88.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  c:\aws\sdk\cmakefiles\cmaketmp\checksymbolexists.cxx(2): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [C:\AWS\SDK\CMakeFiles\CMakeTmp\cmTC_abc88.vcxproj]

    0 Warning(s)

    1 Error(s)

Time Elapsed 00:00:00.46

File C:/AWS/SDK/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */
#include <unistd.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pathconf
  return ((int*)(&pathconf))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the umask exist failed with the following output:
Change Dir: C:/AWS/SDK/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe" "cmTC_d8490.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=15.0"
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

Build started 15-Apr-19 6:48:50 PM.

Project "C:\AWS\SDK\CMakeFiles\CMakeTmp\cmTC_d8490.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_d8490.dir\Debug\".

  Creating directory "C:\AWS\SDK\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_d8490.dir\Debug\cmTC_d8490.tlog\".

InitializeBuildStatus:

  Creating "cmTC_d8490.dir\Debug\cmTC_d8490.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\CL.exe /c /Zi /W4 /WX /diagnostics:classic /MP /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_d8490.dir\Debug\\" /Fd"cmTC_d8490.dir\Debug\vc141.pdb" /Gd /TP /FC /errorReport:queue  /bigobj C:\AWS\SDK\CMakeFiles\CMakeTmp\CheckSymbolExists.cxx

  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27024.1 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W4 /WX /diagnostics:classic /MP /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_d8490.dir\Debug\\" /Fd"cmTC_d8490.dir\Debug\vc141.pdb" /Gd /TP /FC /errorReport:queue  /bigobj C:\AWS\SDK\CMakeFiles\CMakeTmp\CheckSymbolExists.cxx

  CheckSymbolExists.cxx

  

c:\aws\sdk\cmakefiles\cmaketmp\checksymbolexists.cxx(8): error C2065: 'umask': undeclared identifier [C:\AWS\SDK\CMakeFiles\CMakeTmp\cmTC_d8490.vcxproj]

Done Building Project "C:\AWS\SDK\CMakeFiles\CMakeTmp\cmTC_d8490.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\AWS\SDK\CMakeFiles\CMakeTmp\cmTC_d8490.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  c:\aws\sdk\cmakefiles\cmaketmp\checksymbolexists.cxx(8): error C2065: 'umask': undeclared identifier [C:\AWS\SDK\CMakeFiles\CMakeTmp\cmTC_d8490.vcxproj]

    0 Warning(s)

    1 Error(s)

Time Elapsed 00:00:00.46

File C:/AWS/SDK/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */
#include <sys/stat.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef umask
  return ((int*)(&umask))[argc];
#else
  (void)argc;
  return 0;
#endif
}

**Comment by singku** [comment]
Can you try running this cmake command instead?
`cmake C:\Users\HomePC\Downloads\aws-sdk-cpp-master -G "Visual Studio 15 2017 Win64" -DBUILD_ONLY="s3;iam;rds" -DCMAKE_BUILD_TYPE=Debug`

**Comment by ThanasisPap** [comment]
@singku 
The problem was the last semicolon in rds.

> DBUILD_ONLY="s3;iam;rds"

instead of

>  DBUILD_ONLY="s3;iam;rds;".

Thanks!

**Comment by singku** [comment]
@ThanasisPap Note that you ran MSBuild with Configuration to be Debug. The default build type is Release if not specified to CMake. (CMAKE_BUILD_TYPE)
