### ISSUE TITLE
Please review: Static code analysis(coverity) result

### ISSUE THREAD

**Issue by lsong0905** [aws/aws-sdk-cpp#1121]
### What platform/OS are you using?
SLES12 SP3
### What compiler are you using? what version?
g++ (SUSE Linux) 4.8.5
### What's your CMake arguments?
CC=gcc CXX=g++ cmake -DBUILD_ONLY="core;s3" -DCMAKE_BUILD_TYPE=RelWithDebInfo
### Can you provide a TRACE level log? (sanitize any sensitive information)
N/A

As one of the requirements in our team/organization, we need to run coverity to scan all open source SDKs. After sorting out low-impact issues, I have a few issues left that require fixed. I put my patch for each issue, and attach the diff result here. Would you please take a look at the file and see if the patch can be integrated?

Main issues are mostly:
-Uninitialized variables
-Dereference before null check

[aws-sdk-cpp-coverity-patch.txt](https://github.com/aws/aws-sdk-cpp/files/3087388/aws-sdk-cpp-coverity-patch.txt)

**Comment by wps132230** [comment]
It looks reasonable, thank you for your suggestions.

**Comment by lsong0905** [comment]
Our sdk version is 1.7.29. Please let me know once the integration is complete. I will then mark the coverity issue as resolved. Thank you.

**Comment by wps132230** [comment]
Most of the changes make sense to me, except for the last one:
```
             void SymmetricCryptoStream::Finalize()
             {
-                m_cryptoBuf->Finalize();
+                if (m_cryptoBuf != nullptr)
+                {
+                    m_cryptoBuf->Finalize();
+                }
             }
```
`Finalize` will not set `m_cryptoBuf` to `nullptr`.

**Comment by lsong0905** [comment]
Hello,
Thank you for the reply.
What I've suggested there is putting a guard so that it won't be calling Finalize() on null.
Are you saying the null check is not necessary?

**Comment by Bu11etmagnet** [comment]
Since `BuildLocalAddrInfoIPV[46]` writes into addrinfo, perhaps **it** should call memset, rather than requiring that each and every caller does a memset before calling it.

**Comment by Bu11etmagnet** [comment]
> Hello,
> Thank you for the reply.
> What I've suggested there is putting a guard so that it won't be calling Finalize() on null.
> Are you saying the null check is not necessary?

There should be either a check as @lsong0905 suggested, or at least an assert.

**Comment by lsong0905** [comment]
@Bu11etmagnet Calling memset in BuildLocalAddrInfoIPV[46] sounds reasonable to me.

**Comment by wps132230** [comment]
> Since BuildLocalAddrInfoIPV[46] writes into addrinfo, perhaps it should call memset, rather than requiring that each and every caller does a memset before calling it.

Yes, we do `memset` in the `BuildLocalAddrInfoIPV[46]`.

>Hello,
Thank you for the reply.
What I've suggested there is putting a guard so that it won't be calling Finalize() on null.
Are you saying the null check is not necessary?

The guard makes sense to me.

**Comment by marcomagdy** [comment]
> There should be either a check as @lsong0905 suggested, or at least an assert.

+1 for an assert.

Also instead of memset we can simply do: `sockaddr_in addrinfo{};` which C++11 guarantees to value initialize all its members.

**Comment by wps132230** [comment]
Hi, we've made some changes (https://github.com/aws/aws-sdk-cpp/commit/ae60745dcba6983f598f7f34d820d4c516a2007b) based on your feedback, thank you for your contribution! And does this commit meet your requirements?

Please reopen this issue if you have more suggestions.
