### ISSUE TITLE
errors undefined reference to `aws_default_allocator'

### ISSUE THREAD

**Issue by mghorba** [aws/aws-sdk-cpp#1123]
### What platform/OS are you using?
Ubuntu 18.04

### What compiler are you using? what version?
g++/gcc 7.3.0

### What's your CMake arguments?
cmake -DSTATIC_LINKING=1 -DCMAKE_BUILD_TYPE=Release -DENABLE_UNITY_BUILD=ON -DBUILD_ONLY="lambda;logs;s3;sqs;sts" /home/.../aws-sdk-cpp

### Can you provide a TRACE level log? (sanitize any sensitive information)
Building target: worker
Invoking: GCC C++ Linker
g++ -L/home/ubuntu/mongo-c-driver-1.9.2/mongo-libraries/lib ./src/queueManager.o  ./src/s3Access.o   -lmongoc-1.0 -lz -lbson-1.0 -lS3 -lSQS -laws-cpp-sdk-s3 -laws-cpp-sdk-sqs -laws-cpp-sdk-core -laws-cpp-sdk-sts -lcurl -lpthread -lm -lrt -lssl -lcrypto -lsasl2 -lresolv
//usr/local/lib/libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o): In function `Aws::Utils::Event::EventStreamDecoder::EventStreamDecoder(Aws::Utils::Event::EventStreamHandler*)':
EventStreamDecoder.cpp:(.text+0xa24): undefined reference to `aws_default_allocator'
EventStreamDecoder.cpp:(.text+0xa50): undefined reference to `aws_event_stream_streaming_decoder_init'
//usr/local/lib/libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o): In function `Aws::Utils::Event::EventStreamDecoder::Pump(Aws::Utils::Array<unsigned char> const&, unsigned long)':
EventStreamDecoder.cpp:(.text+0xaa3): undefined reference to `aws_event_stream_streaming_decoder_pump'
//usr/local/lib/libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o): In function `Aws::Utils::Event::EventStreamDecoder::ResetEventStreamHandler(Aws::Utils::Event::EventStreamHandler*)':
EventStreamDecoder.cpp:(.text+0xb3d): undefined reference to `aws_default_allocator'
EventStreamDecoder.cpp:(.text+0xb69): undefined reference to `aws_event_stream_streaming_decoder_init'
//usr/local/lib/libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o): In function `Aws::Utils::Event::EventStreamDecoder::~EventStreamDecoder()':
EventStreamDecoder.cpp:(.text+0xa61): undefined reference to `aws_event_stream_streaming_decoder_clean_up'
//usr/local/lib/libaws-cpp-sdk-core.a(EventStreamDecoder.cpp.o): In function `Aws::Utils::Event::EventHeaderValue::EventHeaderValue(aws_event_stream_header_value_pair*)':
EventStreamDecoder.cpp:(.text._ZN3Aws5Utils5Event16EventHeaderValueC2EP34aws_event_stream_header_value_pair[_ZN3Aws5Utils5Event16EventHeaderValueC5EP34aws_event_stream_header_value_pair]+0x64): undefined reference to `aws_event_stream_header_value_as_timestamp'
EventStreamDecoder.cpp:(.text._ZN3Aws5Utils5Event16EventHeaderValueC2EP34aws_event_stream_header_value_pair[_ZN3Aws5Utils5Event16EventHeaderValueC5EP34aws_event_stream_header_value_pair]+0x9e): undefined reference to `aws_event_stream_header_value_as_uuid'
EventStreamDecoder.cpp:(.text._ZN3Aws5Utils5Event16EventHeaderValueC2EP34aws_event_stream_header_value_pair[_ZN3Aws5Utils5Event16EventHeaderValueC5EP34aws_event_stream_header_value_pair]+0x104): undefined reference to `aws_event_stream_header_value_as_bool'
EventStreamDecoder.cpp:(.text._ZN3Aws5Utils5Event16EventHeaderValueC2EP34aws_event_stream_header_value_pair[_ZN3Aws5Utils5Event16EventHeaderValueC5EP34aws_event_stream_header_value_pair]+0x11c): undefined reference to `aws_event_stream_header_value_as_byte'
EventStreamDecoder.cpp:(.text._ZN3Aws5Utils5Event16EventHeaderValueC2EP34aws_event_stream_header_value_pair[_ZN3Aws5Utils5Event16EventHeaderValueC5EP34aws_event_stream_header_value_pair]+0x134): undefined reference to `aws_event_stream_header_value_as_int16'
EventStreamDecoder.cpp:(.text._ZN3Aws5Utils5Event16EventHeaderValueC2EP34aws_event_stream_header_value_pair[_ZN3Aws5Utils5Event16EventHeaderValueC5EP34aws_event_stream_header_value_pair]+0x14c): undefined reference to `aws_event_stream_header_value_as_int32'
EventStreamDecoder.cpp:(.text._ZN3Aws5Utils5Event16EventHeaderValueC2EP34aws_event_stream_header_value_pair[_ZN3Aws5Utils5Event16EventHeaderValueC5EP34aws_event_stream_header_value_pair]+0x164): undefined reference to `aws_event_stream_header_value_as_int64'
EventStreamDecoder.cpp:(.text._ZN3Aws5Utils5Event16EventHeaderValueC2EP34aws_event_stream_header_value_pair[_ZN3Aws5Utils5Event16EventHeaderValueC5EP34aws_event_stream_header_value_pair]+0x186): undefined reference to `aws_event_stream_header_value_as_bytebuf'
EventStreamDecoder.cpp:(.text._ZN3Aws5Utils5Event16EventHeaderValueC2EP34aws_event_stream_header_value_pair[_ZN3Aws5Utils5Event16EventHeaderValueC5EP34aws_event_stream_header_value_pair]+0x19e): undefined reference to `aws_event_stream_header_value_as_string'
collect2: error: ld returned 1 exit status
makefile:46: recipe for target 'worker' failed
make: *** [worker] Error 1

**Comment by wps132230** [comment]
What's the C++ SDK version you are using?
We've fixed a related issue about linking to the dependencies.

**Comment by phrocker** [comment]
I'm experiencing this issue on master (09b65deba03cfbef9a1e5d5986aa4de71bc03cd8)

**Comment by mghorba** [comment]
sdk version 1.3.87.
