### ISSUE TITLE
'Aws::Http::HttpClient::MakeRequest': Deprecated

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#1125]
#### Compiler: MSVC2017

Including `aws/core/http/windows/WinHttpSyncHttpClient.h` (to deal with #453) causes compiler to emit:
```
1>c:\vcpkg\installed\x64-windows\include\aws\core\http\windows\winsynchttpclient.h(51): warning C4996: 'Aws::Http::HttpClient::MakeRequest': Deprecated: in favor of MakeRequest(const std::shared_ptr<HttpRequest>&, ...).
1>c:\vcpkg\installed\x64-windows\include\aws\core\http\httpclient.h(54): note: see declaration of 'Aws::Http::HttpClient::MakeRequest'
```

Any advice on how to deal with this (without resorting to `#pragma warning(disable: 4996)`)?

**Comment by wps132230** [comment]
https://github.com/aws/aws-sdk-cpp/blob/09b65deba03cfbef9a1e5d5986aa4de71bc03cd8/aws-cpp-sdk-core/include/aws/core/http/HttpClient.h#L53

Basically, just like what the documentation said, you can pass the `MakeRequest` with a shared pointer of `request` to avoid this warning.

But for your use case, are you still using the hacky way to provide a client certificate?

**Comment by crusader-mike** [comment]
@wps132230, nowhere in my code I call `MakeRequest`. In fact, simply including that header causes warning to be generated.

> But for your use case, are you still using the hacky way to provide a client certificate?

Yes, I still have to rely on a hack (preprocessor-driven substitution of `private` with `protected`) to be able to ask server to not validate client certificate.

**Comment by singku** [comment]
That warning message should have been suppressed. 
https://github.com/aws/aws-sdk-cpp/blob/09b65deba03cfbef9a1e5d5986aa4de71bc03cd8/aws-cpp-sdk-core/include/aws/core/Core_EXPORTS.h#L50

What version of SDK are you using?

**Comment by singku** [comment]
Update my last response: it just suppressed in SDK's code. You can define `AWS_DISABLE_DEPRECATION` before include that header to suppress it in your code.

**Comment by crusader-mike** [comment]
@singku aren't it supposed to use previous branch? (I am compiling in C++17 mode)
```
#elif defined (__cplusplus) && __cplusplus > 201103L // standard attributes are available since C++14
    #define AWS_DEPRECATED(msg) [[deprecated(msg)]]
```

**Comment by crusader-mike** [comment]
It is weird that I need to define `AWS_DISABLE_DEPRECATION` in my code even though I don't use any of the deprectaed declarations...

**Comment by singku** [comment]
It's a pure virtual function in HttpClient class but marked as deprecated purposely (It's not safe but we don't want to break some of the users who still inherit it by simply remove it). And WinSyncHttpClient has to implement it, that's the dilemma. And we disabled it in SDK's code to avoid the warning.

**Comment by crusader-mike** [comment]
Got it. Thank you
