### ISSUE TITLE
AWS Lex: "Failed to parse error payload" for specific type of userid

### ISSUE THREAD

**Issue by eugene-manuilov** [aws/aws-sdk-cpp#1127]
Hello,

i have found a weird issue that appears when user id is something like `XXX/111-00001`. In this case I always get `Failed to parse error payload` error. But if i update user id to be just simple string like `test1234`, everything works perfectly... Is it a bug or I am doing something wrong?

```cpp
Aws::Client::ClientConfiguration clientConfig;
Aws::LexRuntimeService::LexRuntimeServiceClient lexclient( clientConfig );
Aws::LexRuntimeService::Model::PostContentRequest request;

request.SetBotName( "testbot" );
request.SetBotAlias( "$LATEST" );
request.SetContentType( "audio/lpcm; sample-rate=8000; sample-size-bits=16; channel-count=1; is-big-endian=false" );
request.SetUserId( "XXX/1111-0001" );
request.SetAccept( "audio/pcm" );
request.SetBody( ... );
```

**Comment by singku** [comment]
Probably the slash thing messed up the URI because the userid will go as part of URI and we didn't do well encoding it. Could you please attach the detailed trace log so we can investigate further?

**Comment by eugene-manuilov** [comment]
Hi @singku,

unfortunately, i don't have this code anymore and can't give you trace log, but it can be easily replicated if you create a sample app on your end.

**Comment by KaibaLopez** [comment]
Hi @eugene-manuilov  sorry for the late response, this is a service limitation on the user name which supports [0-9a-zA-Z._:-]+ (no '/')
https://docs.aws.amazon.com/lex/latest/dg/API_runtime_PostContent.html
