### ISSUE TITLE
Far less stable for Android deployment compared to OSX

### ISSUE THREAD

**Issue by kcrossen** [aws/aws-sdk-cpp#1129]
### What platform/OS are you using?
OSX 10.12.6
### What compiler are you using? what version?
xcode/clang 9.2
### Can you provide a TRACE level log? (sanitize any sensitive information)
I've gotten a Qt5 5.12.2/C++ CloudWatch (monitoring) application running on OSX from 10.12 to 10.14 (every supported version). Now trying to port to Android.

First, I tested with non-aws-sdk qt c++ application running correctly on Android simulator. All good.
Second, tried to compile the aws-c++-sdk library (monitoring, core) for Android using:
$ cmake -DBUILD_ONLY="monitoring" -DBUILD_SHARED_LIBS=OFF -DENABLE_UNITY_BUILD=ON -DFORCE_SHARED_CRT=OFF -DTARGET_ARCH=ANDROID -DNDK_DIR="blah-blah-blah/aws_sdk_c++/android-ndk-r12b" -DANDROID_NATIVE_API_LEVEL=24 -DANDROID_ABI=x86_64

For "android-ndk-r12b", I have tried **every** ndk from android-ndk-r12b to android-ndk-r19c.
android-ndk-r12b, android-ndk-r13b, and android-ndk-r14b sorta work (they run and abend with an error and a message regarding the challenged maintenance of curl, restart w/ make again and they finish)
From there on up to r19c, they end quickly with a message that API 21 is no longer supported. Since I specified level 24 as per directions, how did this happen?

In any event, the resulting ("successful" libraries will not link in Qt Creator:
error: error: blahblahblah/aws_sdk_c++/aws-sdk-cpp-1.7.85-android-r14b/aws-cpp-sdk-core/libaws-cpp-sdk-core.a(DateTimeCommon.cpp.o): incompatible target.

Elsewhere in a post here it was said that r19c was supported and worked. Not seeing that. What I'm seeing is my api level spec somehow interpreted as 21. The ndks that did work crashed halfway through.

Next attempt: Try compiling the library sources in Qt Creator. Grab the source files from the directory where the compiled libraries were created. Bad news, they don't compile because there are extra uncompilable files (windows, etc.) and missing files (curl.h, etc.). It seems as if the source directories should compile just exactly as they sit.

More generally, since many of your C++ folks will be using Qt Creator, why not just set the whole thing up for Qt Creator in the first place. Qt Creator can be told to compile a library in the pro file.

**Comment by marcomagdy** [comment]
>  I have tried every ndk from android-ndk-r12b to android-ndk-r19c. android-ndk-r12b, android-ndk-r13b, and android-ndk-r14b sorta work

We have made changes in [v1.7.89](https://github.com/aws/aws-sdk-cpp/tree/1.7.89) to support building the SDK with NDK r19c. That version of the NDK cleaned up a lot of the quirks related to the Android toolchain and the build story in general.
Please try building with the SDK v1.7.89 and NDK r19


>In any event, the resulting ("successful" libraries will not link in Qt Creator:
error: error: blahblahblah/aws_sdk_c++/aws-sdk-cpp-1.7.85-android-r14b/aws-cpp-sdk-core/libaws-cpp-sdk-core.a(DateTimeCommon.cpp.o): incompatible target.

That simply means you tried to link the x86 object files with ARM object files.

>Next attempt: Try compiling the library sources in Qt Creator. Grab the source files from the directory where the compiled libraries were created. Bad news, they don't compile because there are extra uncompilable files (windows, etc.) and missing files (curl.h, etc.). It seems as if the source directories should compile just exactly as they sit.

Yes. Copying files to another project will almost always not work in C/C++ projects. Files are written to work *within* the project

>why not just set the whole thing up for Qt Creator in the first place

I'm sorry we can't do that.

**Comment by kcrossen** [comment]
"That simply means you tried to link the x86 object files with ARM object files." 

Clearly not true. I already have working code that will compile and correctly function for x86 or v7a, etc. In general, I test/debug w/ x86 and only then compile/deploy for v7a.
It's quite indicative that code will compile/run on my x86 emulator until I attempt to link in the aws sdk.

I solved my problem by directly implementing the REST API in C++ using QNetworkAccessManager. Took a few days. Interestingly, it's at least 4X to 10X faster (compared on OSX) relative to aws sdk. This includes network transport time. I get the same comparative performance increase using REST API in Python vs boto3.

I do see that you have a tiger by the tail having to support all AWS services w/ their multitude of different protocols.

**Comment by kcrossen** [comment]
The bottom line is exactly as stated in the issue title. For OSX your sdk essentially works out of the box. That is, it did after some bugs in the SDK were fixed.

For Android, it hasn't worked for me at all. As I have successful code working on both platforms in two different languages (C++ and Python) and two different build environments, it's harder to accept as "pilot error".

**Comment by marcomagdy** [comment]
The incompatible target error means you're linking object files of two different cpu architectures. I hope we can agree on that. That is not a bug in the SDK.

That being said, I acknowledge that cross compiling is more challenging and requires more work to get right compared to standard compilation. We're currently making an effort to improve our manuals to address that problem.

I'm glad you got 4x-10x speed up with solution. It would be nice if you can contribute back performance improvements for the benefit of everyone.

**Comment by kcrossen** [comment]
[CloudWatch_Class.zip](https://github.com/aws/aws-sdk-cpp/files/3184619/CloudWatch_Class.zip)
Here's the code, it's open source w/o restriction, so do with it as you please.

**Comment by kcrossen** [comment]
I believe this general type of solution would be encode more of the "rules-and-regulations" in each "domain" of AWS, and be no harder to maintain. Your more general solution, while conceptually attractive, can't easily encapsulate all the nuances and limitations of the various services.

Because your more general solution is constantly tracking what used to be called "mission creep", it also suffers from all the defects of changing design after code is written, e.g. design patches, etc.
