### ISSUE TITLE
Q: dealing with "Required field: Bucket, is not set" error

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#1130]
#### Compiler: MSVC2017

Upgraded to SDK v1.7.80 (from v1.4.8), my apps started failing with messages like:
```
Required field: Bucket, is not set
Missing required field [Bucket]
and etc
```

Turns out  `bucket` is a required field nowadays. Problem is that I don't know my bucket name -- entire endpoint url is passed to me "from outside" and I am using `endpointOverride` to pass it into S3Client machinery. Until this update it worked fine.

What is the best way to workaround this issue -- should I set bucket on every request to empty string? I am concerned about double slash in final uri...

**Comment by crusader-mike** [comment]
... maybe it makes sense to ignore absence of bucket if endpoint is overridden?

**Comment by singku** [comment]
This is going to be a customization if we decide to. Required field is checked no matter where the filed is going appear (like bucket on URL).

**Comment by crusader-mike** [comment]
Well, my point was that bucket may not even appear on url at all (e.g. if someone uses a dns alias that points to "virtual" bucket (e.g. `<bucket>.s3.amazonaws.com`)).

**Comment by marcomagdy** [comment]
What operation broke for you? we’ll get that fixed

**Comment by crusader-mike** [comment]
@marcomagdy pretty much every common operation (upload/download/head/etc) has bucket as required field. I worked it around by setting bucket explicitly to empty string, but it is looks weird in the code. Plus, there is a chance it may stop working in the future versions again (e.g. if you add a check for non-empty bucket when building url).

So, I am raising this as a topic to discuss -- should SDK cater for this case (when I only have url and no idea about bucket name).

**Comment by marcomagdy** [comment]
Oh I see now.:
>Problem is that I don't know my bucket name -- entire endpoint url is passed to me "from outside" and I am using endpointOverride to pass it into S3Client machinery. 

It sounds like you're better off parsing that incoming URL to figure out the region, bucket, keys etc. and set those values on S3Client.

The fact things worked before using the endpointOverride technique was a happy coincidence, not by design.

**Comment by crusader-mike** [comment]
> It sounds like you're better off parsing that incoming URL to figure out the region, bucket, keys etc. and set those values on S3Client.

Can't do it  -- AWS isn't the only S3-compatible service my code talks to (so there are no guarantees about url format). Plus, to support concept of "a bucket" in my code -- I'll have to do some redesigning...

And in any case, (as I mentioned before) even with AWS there is no guarantee bucket **is** on the url.


> The fact things worked before using the endpointOverride technique was a happy coincidence, not by design.

I know, As of now I am happy to live in these "cracks of logic". But it makes it harder for me to upgrade SDK versions. So, I was thinking maybe I could convince you guys to support this scenario -- it shouldn't be too hard and it is needed only in a small corner case (when `endpointOverride` is specified).

**Comment by marcomagdy** [comment]
>So, I was thinking maybe I could convince you guys to support this scenario 

If this turns out to be an issue for multiple customers then we can look into "fixing" it.
I think for now, you should be ok living in the cracks of logic by setting the bucket name to an empty string 😉

**Comment by crusader-mike** [comment]
NOOOO!!!!
![why](https://user-images.githubusercontent.com/22357016/57246050-f2a9c000-7001-11e9-95cd-0de721f61a8a.jpg)

:)
