### ISSUE TITLE
Failed setting TCP keep-alive interval with error code: 12009

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#1131]
#### Compiler: MSVC2017 (latest)

I am getting error mentioned in title, presumably generated by [this line](https://github.com/aws/aws-sdk-cpp/blob/1ecade03d980285cb543fe16aa7f64573a651d45/aws-cpp-sdk-core/source/http/windows/WinHttpSyncHttpClient.cpp#L121). Maybe in my configuration `WINHTTP_OPTION_WEB_SOCKET_KEEPALIVE_INTERVAL` is not recognized as valid option...

Any idea what causes this error?

**Comment by crusader-mike** [comment]
... I suspect it simply doesn't like too large value for that option? maybe treats it as signed under the cover?

**Comment by marcomagdy** [comment]
This shouldn't result in a FATAL log message anyways. I'll get that fixed.

**Comment by singku** [comment]
Merged

**Comment by crusader-mike** [comment]
Thanks, guys. @marcomagdy, there is also a `WINHTTP_OPTION_DISABLE_FEATURE(WINHTTP_DISABLE_KEEP_ALIVE)` -- I am not exactly sure what it's semantic is, but you may want to consider using it if `!config.enableTcpKeepAlive`.

**Comment by marcomagdy** [comment]
Good call. Thanks
