### ISSUE TITLE
Not sure how to contribute, but here goes...

### ISSUE THREAD

**Issue by kcrossen** [aws/aws-sdk-cpp#1132]
### What platform/OS are you using?
OSX 10.12.6
### What compiler are you using? what version?
Qt5.12.2/Qt Creator 4.8/Xcode 9.2/ clang etc. (latest everything except OSX)

By trial-and-error, I have gotten a proper library source directory for 
```
$ cmake -DBUILD_ONLY="monitoring" -DBUILD_SHARED_LIBS=OFF -DENABLE_UNITY_BUILD=ON -DFORCE_SHARED_CRT=OFF 
```
In other words, starting with aws-cpp-sdk-core/source, aws-cpp-sdk-core/include, aws-cpp-sdk-monitoring/source, and aws-cpp-sdk-monitoring/include, it's possible to derive source "bundles" that will successfully static-compile into the finished application.

For aws-cpp-sdk-monitoring, the directories after the make step were good to go, not so for aws-cpp-sdk-core. What had to be added for the core sources to be compilable were:
Directories added to core/source/util: common and checksums. All the files from these git-clone directories can't be added or the sources will not compile. For common, I needed array_list.c, common.c, encoding.c, and error.c. For checksums, it's
```
$ ls -lR
total 280
-rw-r--r--@ 1 Ken  staff    1916 Apr 24 12:24 cpuid_generic.c
-rw-r--r--  1 Ken  staff    1328 Apr 19 10:17 crc.c
-rw-r--r--  1 Ken  staff  131898 Apr 19 10:17 crc_sw.c
drwxr-xr-x  4 Ken  staff     136 Apr 19 10:17 intel

./intel:
total 48
-rw-r--r--  1 Ken  staff   1366 Apr 19 10:17 cpuid.c
-rw-r--r--  1 Ken  staff  17515 Apr 19 10:17 crc32c_sse42_asm.c
```
File added to core/source/util/event: event_stream.c

Unfortunately, while the result will compile, it won't function.  Two crucial defines are required:
```
// Factories.cpp line 16
#define ENABLE_COMMONCRYPTO_ENCRYPTION true

// HttpClientFactory.cpp line 18
#define ENABLE_CURL_CLIENT true
```
My search of the git-clone yielded no clue where in the sources these were being defined to make the library work.

Additionally patch Version.cpp like so:
```
  unsigned GetVersionMajor()
  {
    return 1 /*AWS_SDK_VERSION_MAJOR*/;
  }

  unsigned GetVersionMinor()
  {
    return 7 /*AWS_SDK_VERSION_MINOR*/;
  }

  unsigned GetVersionPatch()
  {
    return 82 /*AWS_SDK_VERSION_PATCH*/;
  }
```
The final compilable sources in roughly this form should be in the build directory after the make step. Additionally, it would be desirable to have the Qt Creator pro files there also to generate the static (or dynamic) libraries. 

Why Qt?  
Because there doesn't seem to be a better built/maintained cross-platform application build environment for c++.

If you accept this statement about Qt, then QNetwork/QNetworkAccessManager could be substituted for libcurl, one less dependency.

Everything suggested here would require only minor adjustments to the build scripts, possibly excepting the pro files and certainly excepting use of Qt network machinery. One huge advantage of this approach is that when builds fail, and they obviously do frequently, the end user has some recourse w/o having to puzzle through complicated build scripts.

**Comment by kcrossen** [comment]
Here's my "bundle" for OSX monitoring:
[aws_includes_sources.zip](https://github.com/aws/aws-sdk-cpp/files/3117101/aws_includes_sources.zip)

**Comment by kcrossen** [comment]
Forgot some additional includes (in addition to the ones already provided by the build process):
[aws_additional_includes.zip](https://github.com/aws/aws-sdk-cpp/files/3117594/aws_additional_includes.zip)

**Comment by marcomagdy** [comment]
Thanks for the feedback. I'll try to address some of the questions/concerns you brought up.

>Why Qt?
Because there doesn't seem to be a better built/maintained cross-platform application build environment for c++.

That's not true and that's not a sentiment shared by everyone. There're many cross platform build environments for C++ with different trade-offs.

>If you accept this statement about Qt, then QNetwork/QNetworkAccessManager could be substituted for libcurl, one less dependency.

We can't force Qt on everyone. Also, assuming we do, we would be swapping one dependency (libcurl) with another, so I'm not sure how that helps.

>In other words, starting with aws-cpp-sdk-core/source, aws-cpp-sdk-core/include, aws-cpp-sdk-monitoring/source, and aws-cpp-sdk-monitoring/include, it's possible to derive source "bundles" that will successfully static-compile into the finished application.

It's not very clear to me how you're attempting to integrate the SDK in your projects. Your comments suggest that you copied the files, and tried to dive into the build scripts to figure out how to build them or create a "bundle" using your particular build system.
If my understanding is correct, then I'm not surprised you had trouble with the SDK. Because that's not how you are supposed to consume it. That's not how you're supposed to consume any C++ project for that matter. But I'd like to make sure my understanding of the problem is correct though before I trying to give any further guidance.

**Comment by kcrossen** [comment]
I've already posted the issues w/ trying to matriculate from a successful experience w/ Qt5/aws-c++-sdk for an OSX target to an android target.

And for the record, I'm not proposing that Qt be the only option, just one of the possible options. My experience has been that Kivy and PySide2 all work perfectly w/ boto3, but have the defect of effectively not being portable to android. On the other hand, I've had no problem porting Qt5/C++ applications to any platform, including android, with one exception, aws-c++-sdk. 

The directions as stated, don't work, at least not w/ the option parameters I need. For example, ndk r19c has been said to compile the library, but I've tried every variant from ndk r12b to ndk r19c. Ndk r12b to ndk r14 compile (approximately) but crash halfway through, can be restarted by reentering make. Above ndk r14b, all terminate with a message about not supporting API 21, even though I've explicitly specified API 24 (nougat). My cmake options:
```
$ cmake -DBUILD_ONLY="monitoring" -DBUILD_SHARED_LIBS=OFF -DENABLE_UNITY_BUILD=ON -DFORCE_SHARED_CRT=OFF -DTARGET_ARCH=ANDROID -DNDK_DIR="/Users/Ken/Documents/aws_sdk_c++/android-ndk-r12b" -DANDROID_NATIVE_API_LEVEL=24 -DANDROID_ABI=x86_64
```
It's entirely possible that I have something wrong, but the directions worked perfectly for OSX, so I'm at a loss.

The upshot is that I'm searching for another way to succeed. Qt Creator has never crashed, never had any trouble either telling me what I did wrong or compiling correctly. So my next idea was to compile everything in Qt Creator.

I'm entirely open to suggestion.

**Comment by kcrossen** [comment]
Put another way "that's not how you are supposed to consume it" would be fine if it worked reliably the way "I'm supposed to consume it". I'm not the only person who has posted exactly the same symptoms on this forum.

Again, I think QNetwork is a reasonable alternative to curl. Do you realize that the compile crash described above includes a message criticizing libcurl's maintenance practices? If it's such a problem, and I believe it might be, why not try an alternative. For those who have selected Qt, it's not substituting a dependency, it's one less dependency. And if the compile was done entirely within Qt Creator, that dependency would be on a tool that hasn't failed for me yet.

**Comment by marcomagdy** [comment]
Thanks for the details.
I'm still confused about something though, your very first comment in this thread was regarding OSX, but then later you said:
>but the directions worked perfectly for OSX

So is the problem you're having related to building on Android or OSX?
Because I do agree that we have lots of work to do to improve our Android build story. I'm more than happy to take your feedback and address those problems. The goal is to make it as easy as building for Linux/Windows/MacOS on x86.
That being said, we've made some changes in v1.7.89 and switched to using the CMake toolchain that ships with the NDK. The NDK has been notoriously hard to work with, however, it keeps improving with every release. It has certainly caused us a great deal of pain (portability-wise) and got in our way numerous times. Hopefully the latest one works better for you.

I will personally look into the Android builds crashing halfway and requiring a restart (if that hasn't been resolved in v1.7.89). If there're other issues that stand out (and I'm guessing there are), please either link to them here or try to detail them out for us. We **will** fix them sooner than later and will prioritize them.

The SDK shouldn't be a pain to use that's for sure. I Appreciate your feedback.

**Comment by kcrossen** [comment]
Everything worked on OSX. Right out of the box (after I read the directions a few times). Going to android was different. Essentially nothing worked.

One of the great strengths of Qt, and I sense that you aren't a Qt fan, is that everything works right out of the box.  In one day I went from knowing **nothing** about android development to having a working APK. Qt5 / Creator 4.8 works perfectly with every ndk I've tried.

The crash comment in the 1.7.85 android build is not wrong:
```
the curl cmake build system is poorly maintained.  Be aware
```
QNetwork can be an alternative applied right here:
```
// AWSClient.cpp line 288, trap the network/http call
HttpResponseOutcome AWSClient::AttemptOneRequest
    (const std::shared_ptr<HttpRequest>& httpRequest,
     const Aws::AmazonWebServiceRequest& request, const char* signerName) const
```
Admittedly everyone would not be helped, but perhaps we can both agree that Qt is not poorly maintained.

**Comment by kcrossen** [comment]
Here's 1.7.91 compiled w/ r19c, which appears to compile w/ 
```
$ cmake -DBUILD_ONLY="monitoring" -DBUILD_SHARED_LIBS=OFF -DENABLE_UNITY_BUILD=ON -DFORCE_SHARED_CRT=OFF -DTARGET_ARCH=ANDROID -DNDK_DIR="/Users/Ken/Documents/aws_sdk_c++/android-ndk-r19c" -DANDROID_NATIVE_API_LEVEL=24 -DANDROID_ABI=x86_64
$ make
```
But linking w/ a standard Qt5.12.2 example that otherwise will build and run on the x86_64 emulator:
```
:-1: error: error: /Users/Ken/Qt/Examples/Qt-5.12.2/widgets/widgets/mousebuttons/libaws-cpp-sdk-core.a(DateTimeCommon.cpp.o): incompatible target
:-1: error: error: /Users/Ken/Qt/Examples/Qt-5.12.2/widgets/widgets/mousebuttons/libaws-cpp-sdk-core.a(ub_core.cpp.o): incompatible target
:-1: error: error: /Users/Ken/Qt/Examples/Qt-5.12.2/widgets/widgets/mousebuttons/libaws-cpp-sdk-monitoring.a(ub_MONITORING.cpp.o): incompatible target
```
and then an avalanche of follow-on errors.

**Comment by marcomagdy** [comment]
@kcrossen apologies for the delay. 
The error above means you are attempting to link objects built for one architecture with another built for a different architecture.

Your CMake command shows that you are building for x86_64, which runs find on the emulator. You need to build with a different target architecture (i.e. ANDROID).

We are actively working on documentation (will be posted to the wiki section) on how to cross-compile, link and run a sample Android application from scratch.

**Comment by kcrossen** [comment]
As you can see, I did build for ANDROID:
"-DTARGET_ARCH=ANDROID"
but it doesn't run on the emulator. 

The example code does run correctly on the emulator until I link in and execute code in the aws sdk.

When I bypassed the aws sdk via direct C++ REST API, everything linked and ran correctly. 

I'd be very interested to see if explicit directions w/ a sample scratch app will work. I had also rewritten my app in java using Android Studio and that also didn't work because Android Studio (aggressively) deprecated aws java sdk v1.x before v2.x was feature complete. This was some time ago. I submitted an issue on that to java sdk team and apparently the fix is in process. The v1.x SDK did work, just not in Android Studio.

**Comment by marcomagdy** [comment]
> As you can see, I did build for ANDROID:
> "-DTARGET_ARCH=ANDROID"

But you set the ABI to x86_64 `-DANDROID_ABI=x86_64`:
>$ cmake -DBUILD_ONLY="monitoring" -DBUILD_SHARED_LIBS=OFF -DENABLE_UNITY_BUILD=ON -DFORCE_SHARED_CRT=OFF -DTARGET_ARCH=ANDROID -DNDK_DIR="/Users/Ken/Documents/aws_sdk_c++/android-ndk-r12b" -DANDROID_NATIVE_API_LEVEL=24 **-DANDROID_ABI=x86_64**

**Comment by kcrossen** [comment]
"But you set the ABI to x86_64 -DANDROID_ABI=x86_64"

Yes, same on the performant debugging emulator downloaded via Android Studio, and same in Qt. Qt automatically generates code for the x86 Google API emulator which runs the native x86 instruction set (rather than emulating ARM and about 10X faster) on x86_64 machines. It makes debugging bearable.

This may be a terminology issue for your sdk. In every other c++ package compiled via Qt, it generates correct code to run on my preferred x86 Android Studio debugging emulator. Trust me, it demonstrably works on my copy of Qt Creator / Qt 5.12.2 running on OSX 10.12.6. You obviously think I'm missing something here, and your SDK apparently thinks I should be selecting the v7a ABI, which is true for deployment, but dead wrong for debugging. Qt knows that when I select Android/x86_64, I'm targeting the debugger. Qt even auto-selects the x86 emulator as explicitly compatible during debugging "deployment". 

True, Qt does complain that the emulator is actually not 64 bit but rather 32. But for the emulator there's no functional difference unless you attempt to address more than 4GB. This would also fail on my v7a Samsung SM380, even though its CPU is 64/v8a, the Oreo 8.1 ABI is 32/v7a.

The sources are all (all my various versions) at https://github.com/kcrossen/CloudWatch_Remote_Monitor
you can try it yourself. It's a very detailed case study of creating a generalized CloudWatch monitoring app for OSX and Android v7a by a number of different methods using both C++ and Python. All of the versions function analogously (not identically, obviously) but they do function on OSX, on the x86 Android emulator, and on v7a Android Samsung tablet hardware. I'm not guessing about any of this.

I've gotten similar (but vastly more hostile) skepticism elsewhere, including open source maintainers who have relentlessly accused me of "stealing" support by raising issues.

**Comment by jmklix** [comment]
What is the current status for this issue? Did you still have any questions/concerns?
