### ISSUE TITLE
Under Windows 10: using the SDK, the problem of high CPU load but low performance was found

### ISSUE THREAD

**Issue by ztxjzh** [aws/aws-sdk-cpp#1133]
Under Windows, there is a performance bottleneck when using AWS S3 SDK. n the case of single process concurrency, the maximum download speed can only reach about 250MB/s.
Test client platform:
System: Windows 10
Processor: Intel Xeon(Xeon) Silver 4110@2.10ghz octa-core (X2)
Motherboard: H3C ST01M2C7S
Memory: 192 GB (hynix 2666MHz)
Server: high-performance object storage cluster
Network card: 10Gb/s * 2
Phenomenon: when using SDK to concurrently Get objects, the CPU will use a very high occupation. When 16 concurrent objects are used, the transmission bandwidth is about 150MB/S and the CPU occupation is about 30%. At 160 threads, both cpus are 100% occupied. However, the transmission bandwidth is only about 250MB/s. And then you can't go any higher.
Under the same hardware environment, very good transmission speed can be achieved under CentOs with 16 threads up to 900MB/s. Cpu utilization is very low, 64 threads can easily run full network card, Cpu utilization is only 200+% (two logical cores).

Tried:
1. Try various Settings on the Windows system. including firewall, socket optimization, system setup optimization, etc
2. Use different SDK versions (1.6.25 and 1.7)
3. Use the different HTTP clients included in the SDK
4. Use VCPKG and manual source compilation and other compilation tools
5. Test with iperf3 to verify that the network card can work with full load
6. If you call the SDK in the form of multiple processes, you will get performance accumulation. For example, 10 processes, each process 16 threads for transmission, can run the network card full. But in a process, no matter how many threads there are, the maximum speed is 250MB/s..

Hope your help!
If you have any idea, please reply me, I will contact as soon as possible!

**Comment by singku** [comment]
Without knowing your test code or how your test work, we can't help further.
Also can you please try to use transferManager for your multi-task testing work for large files, instead of using S3 SDK directly?

**Comment by ztxjzh** [comment]
> transferManager



> Without knowing your test code or how your test work, we can't help further.
> Also can you please try to use transferManager for your multi-task testing work for large files, instead of using S3 SDK directly?

I really appreciate for your attention, code like this:
```
int read_data(Aws::S3::S3Client *client, const char *bucket_name, const char *key, 
	          uint64_t offset, uint64_t len,char *buf)
{
	int64_t ret;

	Aws::S3::Model::GetObjectRequest object_request;
	object_request.WithBucket(bucket_name).WithKey(key);
	Aws::StringStream ss;
	ss << "bytes=" << offset << "-" << offset + len - 1;

	object_request.SetRange(ss.str());

	auto outcome = client->GetObject(object_request);

	if (outcome.IsSuccess()) {
		auto body = outcome.GetResult().GetBody().rdbuf();
		ret = (int64_t)outcome.GetResult().GetContentLength();

		body->sgetn(buf, len);
	}
	return ret;
}
void read_data_frome_s3(const char *bucket_name, const char *access_key, 
	                    const char *secret_key, const char *endpoint, const char *key) 
{
	int ret;
	uint64_t object_len = 1073741824;
	uint64_t read_len = 4194304;
	uint64_t offset = 0;

	char *buf = (char *)malloc(read_len);
	static Aws::SDKOptions m_options;
	InitAPI(m_options);

	Aws::Client::ClientConfiguration config;

	config.scheme = Aws::Http::Scheme::HTTP;
	config.verifySSL = false;
	config.proxyPort = 0;
	config.maxConnections = 50;
	config.endpointOverride = endpoint;

	Aws::Auth::AWSCredentials credentials(access_key, secret_key);
	auto client =
		new Aws::S3::S3Client(credentials, config, Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Never, false);
	
	while (offset < object_len) {
		ret = read_data(client, bucket_name, key, offset, read_len, buf);
		if (ret < 0)
			continue;
		offset += read_len;
	}

	ShutdownAPI(m_options);
	free(buf);
}

int main(int argc, char *argv[])
{
	const char *bucket_name = "";
	const char *access_key = "";
	const char *secret_key = "";
	const char *endpoint = "";
	read_data_frome_s3(bucket_name, access_key, secret_key, endpoint, "00033");

	system("pause");
}
```

TransferManager has not been used before. I downloaded it from ceph's radosgw on the local network. Can I use TransferManager to speed it up at this kind of situation?
Thanks again!

**Comment by marcomagdy** [comment]
The fact that you're using range-get in S3 means that TransferManager would be a great fit.
Some questions to help guide this in the right direction:

1. Where is the concurrency in your sample? You said in the description you're running 16 threads.
1. Have you tried saving the object to the filesystem right away? instead of keeping it in memory? [example](https://github.com/aws/aws-sdk-cpp#controlling-iostreams-used-by-the-httpclient-and-the-awsclient)
1. Have you profiled the code? Is the bottle neck in the SDK code? or system libraries or your own code?

**Comment by ztxjzh** [comment]
> The fact that you're using range-get in S3 means that TransferManager would be a great fit.
> Some questions to help guide this in the right direction:
> 
> 1. Where is the concurrency in your sample? You said in the description you're running 16 threads.
> 2. Have you tried saving the object to the filesystem right away? instead of keeping it in memory? [example](https://github.com/aws/aws-sdk-cpp#controlling-iostreams-used-by-the-httpclient-and-the-awsclient)
> 3. Have you profiled the code? Is the bottle neck in the SDK code? or system libraries or your own code?

It's my fault, the above used example does not show how the thread is invoked. In the test environment, the thread is used like this:

**### style 1:**
```
struct AsyncRead {
  uint64_t offset = 0;
  uint64_t len = 0;
  Aws::S3::Model::GetObjectOutcomeCallable outcome;
  bool waiting = false;
  AsyncRead() {}
  AsyncRead(uint64_t _offset, uint64_t _len, Aws::S3::Model::GetObjectOutcomeCallable&& _outcome, bool _waiting) :
            offset(_offset), len(_len), outcome(std::move(_outcome)), waiting(_waiting) {}
};  //task struct
  ...
  
  std::map<uint64_t, AsyncRead> m_last_reads;
  ...
  object_request.SetRange(ss.str());
  object_request.WithBucket(m_bucket_name).WithKey(m_pathname); 
  m_last_reads.emplace(off, std::move(AsyncRead(off, end - off + 1, std::move(m_client->GetObjectCallable(object_request)), true)));  //Mode of invocation

  ...
{  //The results collected
 while (true) {
  auto iter = m_last_reads.begin();
  if (iter == m_last_reads.end()) {
   break;
  }

  if (wait) {
   iter->second.outcome.wait();
  } else {
   if (iter->second.outcome.wait_for(std::chrono::milliseconds(0)) != std::future_status::ready) {
    break;
   }
  }
  auto outcome = iter->second.outcome.get();
  if (outcome.IsSuccess()) { 
   //Read out, successful return.
  }
}
```

**### style 2**
```
int64_t DirectRead(char * buf, uint64_t len, uint64_t offset)
{
 int64_t ret;

 Aws::S3::Model::GetObjectRequest object_request;
 object_request.WithBucket(m_bucket_name).WithKey(m_pathname);
 Aws::StringStream ss;
 ss << "bytes=" << offset << "-" << offset + len - 1;
 object_request.SetRange(ss.str());
 auto outcome = m_client->GetObject(object_request);

 if (outcome.IsSuccess()) {
  auto body = outcome.GetResult().GetBody().rdbuf();
  ret = (int64_t)outcome.GetResult().GetContentLength();

  body->sgetn(buf, len);
 } else {
  ret = TransformS3Error(outcome.GetError().GetErrorType());
 }
 return ret;
}
 ...
thread_worker_pool.push_back(task_info);
```

In fact, the code under test does not write the object to the file system and simply waits for the read interface to return successfully (the read size is correct) , then we think download is considered successful.  The idea is to eliminate the impact of disk IO performance.

Statistical methods：
The size of the test file (1GB) is divided by the elapsed time of the counter to evaluate the speed, and multiple groups are used to evaluate the average speed.

Eliminate environmental interference：
To make sure that performance is not compromised by operating system TCP performance or a process component, we tested the IO performance of the current environment with iperf3, and the results ran to 1000MB/s+.

Thank you for your concern! I will try to use TransferManager for testing, and I will timely reply to you with any useful information.

**Comment by KaibaLopez** [comment]
Hi @ztxjzh ,
Sorry for the lack of response here, just checking in on old issues, are you still facing this issue? The SDK has gone through a lot of changes since this was last updated so let me know if it is.
