### ISSUE TITLE
Build Fails in Mac OS X but compiles and run fine in Windows 10

### ISSUE THREAD

**Issue by miryee** [aws/aws-sdk-cpp#1134]
### What platform/OS are you using?
macOS Mojave
### What compiler are you using? what version?
Xcode 10.1
### What's your CMake arguments?
sudo cmake ~/Github/aws-sdk-cpp/ -DSTATIC_LINKING=1 -DBUILD_ONLY="s3" -DFORCE_SHARED_CRT=OFF -DBUILD_SHARED_LIBS=OFF -DCUSTOM_MEMORY_MANAGEMENT=0 -DCMAKE_BUILD_TYPE=Debug
### Can you provide a TRACE level log? (sanitize any sensitive information)
`In file included from <built-in>:1:
In file included from /Users/myee/Projects/myee-aws/ImaginationStationApp/ImaginationStationApp_Prefix.pch:5:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:20:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:24:
In file included from ../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/math.h:19:
In file included from ../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/common.h:23:
In file included from ../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/string.h:17:
In file included from ../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/byte_buf.h:18:
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:44:1: error: unknown type name 'AWS_EXTERN_C_BEGIN'
AWS_EXTERN_C_BEGIN
^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:52:16: error: expected ';' after top level declarator
AWS_STATIC_IMPL
               ^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:54:41: error: expected ')'
    struct aws_array_list *AWS_RESTRICT list,
                                        ^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:53:32: note: to match this '('
int aws_array_list_init_dynamic(
                               ^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:64:1: error: unknown type name 'AWS_STATIC_IMPL'
AWS_STATIC_IMPL
^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:65:1: error: expected unqualified-id
void aws_array_list_init_static(
^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:74:1: error: unknown type name 'AWS_STATIC_IMPL'
AWS_STATIC_IMPL
^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:75:1: error: expected unqualified-id
void aws_array_list_clean_up(struct aws_array_list *AWS_RESTRICT list);
^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:80:1: error: unknown type name 'AWS_STATIC_IMPL'
AWS_STATIC_IMPL
^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:81:1: error: expected unqualified-id
int aws_array_list_push_back(struct aws_array_list *AWS_RESTRICT list, const void *val);
^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:86:1: error: unknown type name 'AWS_STATIC_IMPL'
AWS_STATIC_IMPL
^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:87:1: error: expected unqualified-id
int aws_array_list_front(const struct aws_array_list *AWS_RESTRICT list, void *val);
^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:94:1: error: unknown type name 'AWS_STATIC_IMPL'
AWS_STATIC_IMPL
^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:95:1: error: expected unqualified-id
int aws_array_list_pop_front(struct aws_array_list *AWS_RESTRICT list);
^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:103:1: error: unknown type name 'AWS_STATIC_IMPL'
AWS_STATIC_IMPL
^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:104:1: error: expected unqualified-id
void aws_array_list_pop_front_n(struct aws_array_list *AWS_RESTRICT list, size_t n);
^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:109:1: error: unknown type name 'AWS_STATIC_IMPL'
AWS_STATIC_IMPL
^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:110:1: error: expected unqualified-id
int aws_array_list_back(const struct aws_array_list *AWS_RESTRICT list, void *val);
^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:115:1: error: unknown type name 'AWS_STATIC_IMPL'
AWS_STATIC_IMPL
^
../ThirdParty/AWS/MacOs_Debug_static/include/aws/common/array_list.h:116:1: error: expected unqualified-id
int aws_array_list_pop_back(struct aws_array_list *AWS_RESTRICT list);
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
`
I have configured:
 Build Phases->Link Binary With Libraries: libaws-cpp-sdk-s3.a libaws-c-event-stream.a lilbaws-checksums.a libaws-c-common.a libaws-cpp-sdk-core.a
Build Settings->Header Search Paths and Build Settings->Library Search Paths also configured with appropriate paths and set to recursive. 

My code compiles and executes correctly in Windows 10 debug and release.

**Comment by singku** [comment]
Would you mind updating your SDK to latest version and let SDK build dependencies by itself. If you prefer building dependencies by yourself, would you also update the dependencies?

**Comment by miryee** [comment]
Updating the SDK seemed to work. I always let the SDK build dependencies on it's own.  Thanks.  Now I am getting CurlHttpClient.cpp errors in libaws-cpp-sdk-core.

**Comment by miryee** [comment]
`Undefined symbols for architecture x86_64:
  "_curl_easy_cleanup", referenced from:
      Aws::Http::CurlHandleContainer::~CurlHandleContainer() in libaws-cpp-sdk-core.a(CurlHandleContainer.cpp.o)
  "_curl_easy_getinfo", referenced from:
      Aws::Http::CurlHttpClient::MakeRequestInternal(Aws::Http::HttpRequest&, std::__1::shared_ptr<Aws::Http::Standard::StandardHttpResponse>&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_easy_init", referenced from:
      Aws::Http::CurlHandleContainer::CheckAndGrowPool() in libaws-cpp-sdk-core.a(CurlHandleContainer.cpp.o)
  "_curl_easy_perform", referenced from:
      Aws::Http::CurlHttpClient::MakeRequestInternal(Aws::Http::HttpRequest&, std::__1::shared_ptr<Aws::Http::Standard::StandardHttpResponse>&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_easy_reset", referenced from:
      Aws::Http::CurlHandleContainer::ReleaseCurlHandle(void*) in libaws-cpp-sdk-core.a(CurlHandleContainer.cpp.o)
  "_curl_easy_setopt", referenced from:
      SetOptCodeForHttpMethod(void*, Aws::Http::HttpRequest const&) in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
      Aws::Http::CurlHttpClient::MakeRequestInternal(Aws::Http::HttpRequest&, std::__1::shared_ptr<Aws::Http::Standard::StandardHttpResponse>&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
      Aws::Http::CurlHandleContainer::SetDefaultOptionsOnHandle(void*) in libaws-cpp-sdk-core.a(CurlHandleContainer.cpp.o)
  "_curl_easy_strerror", referenced from:
      Aws::Http::CurlHttpClient::MakeRequestInternal(Aws::Http::HttpRequest&, std::__1::shared_ptr<Aws::Http::Standard::StandardHttpResponse>&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_global_cleanup", referenced from:
      Aws::Http::CurlHttpClient::CleanupGlobalState() in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_global_init", referenced from:
      Aws::Http::CurlHttpClient::InitGlobalState() in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_slist_append", referenced from:
      Aws::Http::CurlHttpClient::MakeRequestInternal(Aws::Http::HttpRequest&, std::__1::shared_ptr<Aws::Http::Standard::StandardHttpResponse>&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_slist_free_all", referenced from:
      Aws::Http::CurlHttpClient::MakeRequestInternal(Aws::Http::HttpRequest&, std::__1::shared_ptr<Aws::Http::Standard::StandardHttpResponse>&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by singku** [comment]
Looks like you are building a static library and doing your own linking set up. But curl is not correctly linked against your app. 
Checkout 
https://github.com/aws/aws-sdk-cpp/issues/1052 
https://github.com/aws/aws-sdk-cpp/issues/786

But It's should be easy if you use CMake to generate the correct project file using the cmake scripts we supplied during installation.

**Comment by miryee** [comment]
I am not doing my own linking set up.  I just use 
`sudo cmake ~/Github/aws-sdk-cpp/ -DSTATIC_LINKING=1 -DBUILD_ONLY="s3" -DFORCE_SHARED_CRT=OFF -DBUILD_SHARED_LIBS=OFF -DCUSTOM_MEMORY_MANAGEMENT=0 -DCMAKE_BUILD_TYPE=Debug
sudo make
sudo install`
to generate the libraries, so it should be using your cmake scripts.  Where would I need to add curl?

**Comment by singku** [comment]
The error above seems from linking your app against SDK. So what I meant above is not when linking the SDK itself. You can use something like `find_pacakge(AWSSDK REQUIRED COMPONENTS s3 ec2)`

**Comment by miryee** [comment]
Looking through the cmake log, it does find curl:
```
Install the project...
-- Install configuration: "Debug"
-- Installing: /Users/myee/Projects/AwsSdkCpp/Install/lib/libaws-c-event-stream.a
-- Installing: /Users/myee/Projects/AwsSdkCpp/Install/include/aws/event-stream/event_stream.h
-- Installing: /Users/myee/Projects/AwsSdkCpp/Install/include/aws/event-stream/event_stream_exports.h
-- Installing: /Users/myee/Projects/AwsSdkCpp/Install/lib/aws-c-event-stream/cmake/aws-c-event-stream-targets.cmake
-- Installing: /Users/myee/Projects/AwsSdkCpp/Install/lib/aws-c-event-stream/cmake/aws-c-event-stream-targets-debug.cmake
-- Installing: /Users/myee/Projects/AwsSdkCpp/Install/lib/aws-c-event-stream/cmake/aws-c-event-stream-config.cmake
[100%] Completed 'AwsCEventStream'
[100%] Built target AwsCEventStream
-- Third-party dependencies are installed at: /Users/myee/Projects/AwsSdkCpp/Install
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11") 
--   Zlib include directory: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include
--   Zlib library: /usr/lib/libz.dylib
-- Encryption: CommonCrypto
-- Http client: Curl
-- Found CURL: /usr/lib/libcurl.dylib (found version "7.54.0") 
--   Curl include directory: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include
--   Curl library: /usr/lib/libcurl.dylib
-- Considering s3
-- Looking for pathconf
-- Looking for pathconf - found
-- Looking for umask
-- Looking for umask - found
-- The C compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Updating version info to 1.7.97
-- Custom memory management disabled
-- Performing Test CURL_HAS_H2
-- Performing Test CURL_HAS_H2 - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/myee/Projects/AwsSdkCpp/Mac_OsX_Debug_static1
```
The only fails I see in the log, but should be unrelated:
```
[ 20%] Performing configure step for 'AwsCCommon'
-- The C compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Success
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Success
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Success
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Success
-- Performing Test HAVE_MAY_I_USE
-- Performing Test HAVE_MAY_I_USE - Failed
-- Performing Test HAVE_BUILTIN_CPU_SUPPORTS
-- Performing Test HAVE_BUILTIN_CPU_SUPPORTS - Success
-- Performing Test HAVE_MSVC_CPUIDEX
-- Performing Test HAVE_MSVC_CPUIDEX - Failed
-- Looking for stdint.h
-- Looking for stdint.h - found

```

**Comment by miryee** [comment]
Thanks for your help Andrew! I added libcurl.tbd to Project->General->Linked Frameworks and Libraries and my app now builds.
