### ISSUE TITLE
Pure virtual function called while using S3 select object content async API

### ISSUE THREAD

**Issue by anirudh234** [aws/aws-sdk-cpp#1139]
### What platform/OS are you using?
Ubuntu 18.04

### Which version of the SDK?
1.7.100

### What compiler are you using? what version?
gcc 7.4

### What are your CMake arguments?
`cmake 
  -DCMAKE_BUILD_TYPE=Debug 
  -DCMAKE_CXX_FLAGS=-Wl,--dynamic-linker,glibc-echo 2.25/lib/ld-linux-x86-64.so.2,--rpath,glibc-echo/lib,--rpath,2.25/lib,--rpath,./aws-sdk-cpp-1.7.100-gcc7/lib,--rpath,./toolchain/lib64 -L./toolchain/lib64 -L./glibc-echo/lib -L2.25/lib -L./aws-sdk-cpp-1.7.100-gcc7/lib 
  -DCMAKE_INSTALL_PREFIX=$destination 
  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=1 
  -DBUILD_ONLY="s3" 
  -DENABLE_TESTING=OFF 
  -DAUTORUN_UNIT_TESTS=OFF 
  -DZLIB_LIBRARY=zlib-1.2.8/lib/libz.so 
  -DZLIB_INCLUDE_DIR=zlib-1.2.8/include 
  -DOPENSSL_LIBRARIES=openssl-1.0.1m/lib/libssl.so 
  -DOPENSSL_INCLUDE_DIR=openssl-1.0.1m/include 
  -DOPENSSL_ROOT_DIR=openssl-1.0.1m 
  -DCURL_LIBRARY=curl-7.46.0/lib/libcurl.so 
  -DCURL_INCLUDE_DIR=curl-7.46.0/include .`

### Can you provide a TRACE level log? (sanitize any sensitive information)

Request:
`<SelectObjectContentRequest xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Expression>SELECT * FROM S3Object</Expression>
    <ExpressionType>SQL</ExpressionType>
    <InputSerialization>
        <JSON>
            <Type>DOCUMENT</Type>
        </JSON>
    </InputSerialization>
    <OutputSerialization>
        <JSON>
            <RecordDelimiter>\n</RecordDelimiter>
        </JSON>
    </OutputSerialization>
</SelectObjectContentRequest>`

Trace:
pure virtual method called
F0512 08:15:31.328534 10036 main.cc:1239] Check failed: eptr Unhandled exception.
*** Check failure stack trace: ***
I0512 08:15:31.329228 10036 main.cc:367] ************* Finished calling all failure functors. Calling abort()...
*** Aborted at 1557674131 (unix time) try "date -d @1557674131" if you are using GNU date ***
PC: @     0x7f133b71313f __GI_raise
*** SIGABRT (@0x3e8000026ff) received by PID 9983 (TID 0x7f133b48e700) from PID 9983; stack trace: ***
    @     0x7f133be3f8d1 std::terminate()
    @     0x7f133be4060f __cxa_pure_virtual
    @     0x7f13465625f5 Aws::Client::AWSClient::AttemptExhaustively()
    @     0x7f13465649f8 Aws::Client::AWSXMLClient::MakeRequestWithEventStream()
    @     0x7f13430304f3 Aws::S3::S3Client::SelectObjectContent()
    @     0x7f1343030854 Aws::S3::S3Client::SelectObjectContentAsyncHelper()

**Comment by marcomagdy** [comment]
This issue is missing a lot of information.
That error does not happen when building for any of the mainstream platforms we support (Windows, Linux, MacOS, Android, iOS).

You need to provide more information in order for us to help you.
1. Why are you setting `CMAKE_CXX_FLAGS`  with those settings?
1. Can you provide a sample that reproduces that error?
1. Are you using custom factories? e.g. HTTPClientFactory?
