### ISSUE TITLE
Customizable log buffer size

### ISSUE THREAD

**Issue by redspart** [aws/aws-sdk-cpp#1140]
I think this is more or less a feature request as I create an issue [here](https://github.com/awslabs/aws-lambda-cpp/issues/36). Thanks to @marcomagdy for suggesting I post it here. 

I have it now pseudo working by not having to run the lambda multiple times, however, having the ability to customize the number will help. Ex: I find that I am outputting 150 lines for validation, however, they will not show up in the cloudwatch logs. 

### What platform/OS are you using?
Ubuntu 18.04.2 LTS on an Cloud9 instance
### What are your CMake arguments?
```bash
cmake . -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=~/install
```

**Comment by singku** [comment]
We have added a feature to aws logger. You can now call `AWS_LOGSTREAM_FLUSH()` to flush the log from buffer to device
