### ISSUE TITLE
Unable to Build S3 Library on Windows/Cygwin

### ISSUE THREAD

**Issue by jkmartin19** [aws/aws-sdk-cpp#1143]
### What platform/OS are you using?
Windows 7/Cygwin

### Which version of the SDK?
Latest code on master

### What compiler are you using? what version?
GNU 7.4.0

### What are your CMake arguments?
cmake ../aws-sdk-cpp/ -DBUILD_SHARED_LIBS=OFF -DBUILD_ONLY="s3"

### Can you provide a TRACE level log? (sanitize any sensitive information)
-- Found Git: /usr/bin/git.exe (found version "2.17.0")
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as static objects
-- Generating linux build config
-- Building project version: 1.7.100
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++.exe
-- Check for working CXX compiler: /usr/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /cygdrive/c/Users/Shawn Javid/Desktop/AWS-BUILD/.deps
Scanning dependencies of target AwsCCommon
[  4%] Creating directories for 'AwsCCommon'
[  8%] Performing download step (git clone) for 'AwsCCommon'
Cloning into 'AwsCCommon'...
Note: checking out 'ac02e17'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at ac02e17 Define STATIC_CRT (defaults to OFF) so that users can specify static/dynamic run-time library.
[ 12%] No patch step for 'AwsCCommon'
[ 16%] No update step for 'AwsCCommon'
[ 20%] Performing configure step for 'AwsCCommon'
-- The C compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Success
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Success
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Success
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Success
-- Performing Test HAVE_MAY_I_USE
-- Performing Test HAVE_MAY_I_USE - Failed
-- Performing Test HAVE_BUILTIN_CPU_SUPPORTS
-- Performing Test HAVE_BUILTIN_CPU_SUPPORTS - Success
-- Performing Test HAVE_MSVC_CPUIDEX
-- Performing Test HAVE_MSVC_CPUIDEX - Success
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Building SIMD base64 decoder
-- Packaging is only supported on Linux
-- Configuring done
-- Generating done
-- Build files have been written to: /cygdrive/c/Users/Shawn Javid/Desktop/AWS-BUILD/.deps/build/src/AwsCCommon-build
[ 25%] Performing build step for 'AwsCCommon'
Scanning dependencies of target aws-c-common
[  1%] Building C object CMakeFiles/aws-c-common.dir/source/array_list.c.o
[  3%] Building C object CMakeFiles/aws-c-common.dir/source/byte_buf.c.o
[  5%] Building C object CMakeFiles/aws-c-common.dir/source/codegen.c.o
[  6%] Building C object CMakeFiles/aws-c-common.dir/source/command_line_parser.c.o
[  8%] Building C object CMakeFiles/aws-c-common.dir/source/common.c.o
[ 10%] Building C object CMakeFiles/aws-c-common.dir/source/condition_variable.c.o
[ 11%] Building C object CMakeFiles/aws-c-common.dir/source/date_time.c.o
[ 13%] Building C object CMakeFiles/aws-c-common.dir/source/device_random.c.o
[ 15%] Building C object CMakeFiles/aws-c-common.dir/source/encoding.c.o
[ 16%] Building C object CMakeFiles/aws-c-common.dir/source/error.c.o
[ 18%] Building C object CMakeFiles/aws-c-common.dir/source/hash_table.c.o
[ 20%] Building C object CMakeFiles/aws-c-common.dir/source/lru_cache.c.o
[ 21%] Building C object CMakeFiles/aws-c-common.dir/source/priority_queue.c.o
[ 23%] Building C object CMakeFiles/aws-c-common.dir/source/string.c.o
[ 25%] Building C object CMakeFiles/aws-c-common.dir/source/task_scheduler.c.o
[ 26%] Building C object CMakeFiles/aws-c-common.dir/source/uuid.c.o
[ 28%] Building C object CMakeFiles/aws-c-common.dir/source/posix/clock.c.o
[ 30%] Building C object CMakeFiles/aws-c-common.dir/source/posix/condition_variable.c.o
[ 31%] Building C object CMakeFiles/aws-c-common.dir/source/posix/device_random.c.o
[ 33%] Building C object CMakeFiles/aws-c-common.dir/source/posix/environment.c.o
[ 35%] Building C object CMakeFiles/aws-c-common.dir/source/posix/mutex.c.o
[ 36%] Building C object CMakeFiles/aws-c-common.dir/source/posix/rw_lock.c.o
[ 38%] Building C object CMakeFiles/aws-c-common.dir/source/posix/system_info.c.o
[ 40%] Building C object CMakeFiles/aws-c-common.dir/source/posix/thread.c.o
[ 41%] Building C object CMakeFiles/aws-c-common.dir/source/posix/time.c.o
[ 43%] Building C object CMakeFiles/aws-c-common.dir/source/arch/cpuid.c.o
/cygdrive/c/Users/Shawn Javid/Desktop/AWS-BUILD/.deps/build/src/AwsCCommon/source/arch/cpuid.c:39:13: error: ‘msvc_check_avx2’ defined but not used [-Werror=unused-function]
 static bool msvc_check_avx2(void) {
             ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[5]: *** [CMakeFiles/aws-c-common.dir/build.make:663: CMakeFiles/aws-c-common.dir/source/arch/cpuid.c.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:612: CMakeFiles/aws-c-common.dir/all] Error 2
make[3]: *** [Makefile:139: all] Error 2
make[2]: *** [CMakeFiles/AwsCCommon.dir/build.make:112: build/src/AwsCCommon-stamp/AwsCCommon-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:106: CMakeFiles/AwsCCommon.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
CMake Error at CMakeLists.txt:193 (message):
  Failed to build third-party libraries.

-- Configuring incomplete, errors occurred!

**Comment by Bu11etmagnet** [comment]
That's a problem with AwsCCommon, not the AWS SDK itself.

**Comment by Bu11etmagnet** [comment]
https://github.com/awslabs/aws-c-common/pull/371
