### ISSUE TITLE
Third-party dependency AwsCEventStream not pinned correctly

### ISSUE THREAD

**Issue by tdenniston** [aws/aws-sdk-cpp#1145]
The version of `AwsCEventStream` pinned here: https://github.com/aws/aws-sdk-cpp/blob/8eba01ec384938c2c5a89c459632377075f30272/third-party/CMakeLists.txt#L26 is set to the variable `AWS_EVENT_STREAM_TAG`. However, when that project is added here: https://github.com/aws/aws-sdk-cpp/blob/8eba01ec384938c2c5a89c459632377075f30272/third-party/cmake/BuildAwsEventStream.cmake#L49 it references the wrong variable (`AWS_EVENT_STREAM_SHA`). The end result is that the external project checks out the `master` branch of that repo instead of the pinned version:

```
Cloning into 'AwsCEventStream'...
Already on 'master'
```

Thanks to @ihnorton for helping to find this one.

### What platform/OS are you using?
macOS

### Which version of the SDK?
1.7.94 but the same issue exists in master.

### What compiler are you using? what version?
```
$ g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### What are your CMake arguments?
Building it from an external project like this:

```
ExternalProject_Add(ep_awssdk
      PREFIX "externals"
      URL "https://github.com/aws/aws-sdk-cpp/archive/1.7.94.zip"
      URL_HASH SHA1=171c0fa56e880d15c6b369cf66ec7eae4bf63659
      CMAKE_ARGS
        -DCMAKE_BUILD_TYPE=Release
        -DENABLE_TESTING=OFF
        -DBUILD_ONLY=s3\\$<SEMICOLON>core
        -DBUILD_SHARED_LIBS=OFF
        -DCMAKE_INSTALL_BINDIR=lib
        -DENABLE_UNITY_BUILD=ON
        -DCUSTOM_MEMORY_MANAGEMENT=0
        -DCMAKE_PREFIX_PATH=${TILEDB_EP_INSTALL_PREFIX}
        -DCMAKE_INSTALL_PREFIX=${TILEDB_EP_INSTALL_PREFIX}
      UPDATE_COMMAND ""
      LOG_DOWNLOAD TRUE
      LOG_CONFIGURE TRUE
      LOG_BUILD TRUE
      LOG_INSTALL TRUE
      DEPENDS ${DEPENDS}
    )
```

### Can you provide a TRACE level log? (sanitize any sensitive information)
Not a runtime issue.

**Comment by marcomagdy** [comment]
Yep. We messed this one up. We're fixing it right now. Our CI broke as well. Fix will be in shortly thanks

**Comment by marcomagdy** [comment]
should be good now v1.7.108

**Comment by tdenniston** [comment]
Great, thanks for the fast turnaround!
