### ISSUE TITLE
Not able to build old version (It was working)

### ISSUE THREAD

**Issue by jwang01** [aws/aws-sdk-cpp#1146]
### What platform/OS are you using?
Amzn Linux
### Which version of the SDK?
 1.7.85
### What compiler are you using? what version?
g++
### What are your CMake arguments?
RUN git clone https://github.com/aws/aws-sdk-cpp.git --branch 1.7.85 --single-branch
RUN cd aws-sdk-cpp && mkdir build
WORKDIR /aws-sdk-cpp/build
RUN cmake3 .. -DBUILD_ONLY=s3 -DBUILD_SHARED_LIBS=ON
RUN make && make install
RUN rm -rf /aws-sdk-cpp

### Can you provide a TRACE level log? (sanitize any sensitive information)
 Your branch is up to date with 'origin/master'.
[ 79%] No patch step for 'AwsCEventStream'
[ 83%] No update step for 'AwsCEventStream'
[ 87%] Performing configure step for 'AwsCEventStream'
-- The C compiler identification is GNU 7.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    STATIC_CRT

-- Build files have been written to: /aws-sdk-cpp/build/.deps/build/src/AwsCEventStream-build
[ 91%] Performing build step for 'AwsCEventStream'
Scanning dependencies of target aws-c-event-stream
[  9%] Building C object CMakeFiles/aws-c-event-stream.dir/source/event_stream.c.o
/aws-sdk-cpp/build/.deps/build/src/AwsCEventStream/source/event_stream.c: In function 'aws_event_stream_message_from_buffer':
/aws-sdk-cpp/build/.deps/build/src/AwsCEventStream/source/event_stream.c:315:5: error: implicit declaration of function 'AWS_ASSERT'; did you mean 'AWS_OP_ERR'? [-Werror=implicit-function-declaration]
     AWS_ASSERT(buffer);
     ^~~~~~~~~~
     AWS_OP_ERR
cc1: all warnings being treated as errors
gmake[5]: *** [CMakeFiles/aws-c-event-stream.dir/source/event_stream.c.o] Error 1
gmake[4]: *** [CMakeFiles/aws-c-event-stream.dir/all] Error 2
gmake[3]: *** [all] Error 2
gmake[2]: *** [build/src/AwsCEventStream-stamp/AwsCEventStream-build] Error 2
gmake[1]: *** [CMakeFiles/AwsCEventStream.dir/all] Error 2
gmake: *** [all] Error 2
CMake Error at CMakeLists.txt:189 (message):
  Failed to build third-party libraries.

**Comment by jwang01** [comment]
How do I lock down a specific version?

**Comment by jwang01** [comment]
I dig a bit, it seems that the following fix (Replace AWS_EVENT_STREAM_SHA with AWS_EVENT_STREAM_TAG) has already fixed the issue: https://github.com/aws/aws-sdk-cpp/commit/18ddaa9746b6ea40b247272ab8f804082943b503#diff-05285a6593b983453e7fee6bb750f6bb

**Comment by KaibaLopez** [comment]
Well, glad to hear you found a solution, does this mean you no longer have an issue?
I'll tag for closure in the mean time, but feel free to comment and I'll remove the tag if that's not the case.

**Comment by jwang01** [comment]
yeah, I close it.
