### ISSUE TITLE
Could GCC 4.8.5 be used to build SDK?

### ISSUE THREAD

**Issue by nikt12** [aws/aws-sdk-cpp#1147]
### What platform/OS are you using?
SLES 12

### Which version of the SDK?
1.7.103

### What compiler are you using? what version?
GCC 4.8.5

### What are your CMake arguments?
cmake -DCMAKE_BUILD_TYPE=Debug BUILD_ONLY="core;s3;transfer" ..

### Can you provide a TRACE level log? (sanitize any sensitive information)

Hello, folks.
Am I able to use GCC 4.8.5 to build AWS SDK?
I was able to build core, s3 and transfer parts without any errors and my code worked fine with them.
Do you have mandatory requirements to not use GCC less than 4.9?

**Comment by singku** [comment]
We highly recommend you to use at least gcc 4.9 for c++ 11 completeness, but don't have mandatory requirements. If you build it fine, then you are good.
