### ISSUE TITLE
Documentation error for s3 Download?

### ISSUE THREAD

**Issue by joaofayad** [aws/aws-sdk-cpp#1150]
I was wrapping the SDK into my own classes when I noticed my download wrapper produced no effect. From the web [documentation](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/examples-s3-objects.html) the description for the download example is 

> The following example downloads an object from Amazon S3 and saves its contents to a file (using the same name as the object's key).

And the code snippet
```
// Assign these values before running the program
const Aws::String bucket_name = "BUCKET_NAME";
const Aws::String object_name = "OBJECT_NAME";  // For demo, set to a text file

// Set up the request
Aws::S3::S3Client s3_client;
Aws::S3::Model::GetObjectRequest object_request;
object_request.SetBucket(bucket_name);
object_request.SetKey(object_name);

// Get the object
auto get_object_outcome = s3_client.GetObject(object_request);
if (get_object_outcome.IsSuccess())
{
    // Get an Aws::IOStream reference to the retrieved file
    auto &retrieved_file = get_object_outcome.GetResultWithOwnership().GetBody();

    // Output the first line of the retrieved text file
    std::cout << "Beginning of file contents:\n";
    char file_data[255] = { 0 };
    retrieved_file.getline(file_data, 254);
    std::cout << file_data << std::endl;
}
else
{
    auto error = get_object_outcome.GetError();
    std::cout << "ERROR: " << error.GetExceptionName() << ": " 
        << error.GetMessage() << std::endl;
}
```

The code and the description don't match as that data is not written in to disk. I found out how to save the data into a file by browsing the issues a bit, but perhaps the code could be updated to the preferred way to save a file to disk? Or at least update the description to match the code. This would help people who follow the instructions blindly like me :)

**Comment by KaibaLopez** [comment]
Hey @joaofayad, thanks for pointing this out, I've submitted feedback on the documentation page, and the documentation team will take it from there.

**Comment by SCalwas** [comment]
@joaofayad @KaibaLopez I updated the AWS SDK for C++ Developer Guide to clarify that the example stores the downloaded file's contents in a local variable. The updated version can be viewed within a few hours at https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/examples-s3-objects.html

Thanks for the feedback.
