### ISSUE TITLE
How to set Content-Disposition & Content-Encoding with S3 TransferManager?

### ISSUE THREAD

**Issue by chrisrosner** [aws/aws-sdk-cpp#1151]
I can't seem to figure out how to set the Content-Disposition or Content-Encoding headers for files uploaded to S3 with the TransferManager.

If I try to use "metadata" all of my headers are prefixed with "x-amz-meta", which is not desired.

The TransferHandle has a SetContentType method, but no SetContentDisposition or SetContentEncoding methods.

PutObjectRequest does have a SetContentDisposition & SetContentEncoding, so it seems like it should be possible somehow?

How is this accomplished with TransferManager & UploadFile?

### Which version of the SDK?
commit 0e0a8ea5aee8d4616e8b5ca0ef4a561b6d217521
Author: aws-sdk-cpp-automation <aws-sdk-cpp-automation@github.com>
Date:   Tue Apr 30 19:34:04 2019 +0000

**Comment by marcomagdy** [comment]
Use [`TransferManagerConfiguration::putObjectTemplate.`](https://github.com/aws/aws-sdk-cpp/blob/0e0a8ea5aee8d4616e8b5ca0ef4a561b6d217521/aws-cpp-sdk-transfer/include/aws/transfer/TransferManager.h#L67)

```cpp
/**
 * If you have special arguments you want passed to our put object calls, put them here. We will copy the template for each put object call
 * overriding the body stream, bucket, and key. If object metadata is passed through, we will override that as well.
 */
Aws::S3::Model::PutObjectRequest putObjectTemplate;
```

**Comment by chrisrosner** [comment]
Thanks for that. I'll poke around to see if this can be made dynamic. It does appear though at first glance that this will apply the same settings to all files uploaded through this manager? 

I'm trying to upload a bunch of disparate files with individual dispositions & content types.

**Comment by marcomagdy** [comment]
>It does appear though at first glance that this will apply the same settings to all files uploaded through this manager?

Correct.

>I'm trying to upload a bunch of disparate files with individual dispositions & content types.

You can't do that with the current implementation.

**Comment by marcomagdy** [comment]
We might have to do something like this: https://github.com/aws/aws-sdk-cpp/pull/944/ but also add content-disposition.
Adding new parameters is not scalable though, we'll have to pass a struct with all the options/settings.

**Comment by chrisrosner** [comment]
So yeah, I had to make a fork and add the support myself. 

Obviously, it'd be done somewhat differently if it were to make it in to the aws owned repo (these changes break the interface by adding more parameters)

https://github.com/leolabs-space/aws-sdk-cpp/commits/headers-for-transfer-manager-upload

**Comment by chrisrosner** [comment]
Agree about passing in a struct. Its not really clear to me why I can't pass them in the metadata in the first place though, honestly. It seems weird that x-amz- is added to all the header names.

**Comment by chrisrosner** [comment]
Another approach I considered is allowing the user to specify a PutObjectRequest factory function for each upload.

**Comment by nickdademo** [comment]
@chrisrosner Were you ever able to set `Content-Disposition` via `putObjectTemplate` in the `TransferManagerConfiguration`? ... `putObjectTemplate.SetContentDisposition(R"(attachment; filename="file.pdf";)")` just doesn't seem to work and as you pointed out, setting the metadata in the transfer itself unexpectedly prepends "x-amz-" to the field name.

**Comment by chrisrosner** [comment]
No, unfortunately the only option I saw was to fork the repo and and to
make a low effort patch.

**Comment by nickdademo** [comment]
@chrisrosner That's unfortunate! Perhaps I will do the same.
@marcomagdy Is this `putObjectTemplate` method to set the ContentDisposition expected to work?
