### ISSUE TITLE
How to check integrity of whole file upload during multipart uploading?

### ISSUE THREAD

**Issue by nikt12** [aws/aws-sdk-cpp#1155]
### What platform/OS are you using?
SLES 12

### Which version of the SDK?
1.7.103

### What compiler are you using? what version?
GCC 4.8.5

### What are your CMake arguments?
cmake -DCMAKE_BUILD_TYPE=Debug BUILD_ONLY="core;s3;transfer" ..

### Can you provide a TRACE level log? (sanitize any sensitive information)
Hello folks.
How could I check integrity of whole file upload during multipart uploading?
As I see, in transfer manager integration tests checking is performed through downloading file back and comparing it with source file.
What if I have files > 100 GB size?
I know that ETag on server side is calculated for each uploaded part and then concatenated, but how could I do this for source file? 
Are there any SDK tools to do this?

**Comment by singku** [comment]
You can call HeadObject request to the target object specifying IfMatch member with the locally calculated Etag. If the Etag on server side is the same as yours, it will return success response, other wise you will get a 412 Http code.

**Comment by nikt12** [comment]
Ok then how to calculate local file Etag, if it was uploaded with TransferManager multipart uploads?
As I understand, ETag on server is sum of calculated md5 chunks. @singku

**Comment by singku** [comment]
Above post has the detailed explanation, you can take a look.

**Comment by dmitryash** [comment]
> You can call HeadObject request to the target object specifying IfMatch member with the locally calculated Etag. 

@singku ETag is not supposed to be used for such checking. ETag is an implementation defined unique identifier for the object. see [RFC](https://tools.ietf.org/html/rfc7232#section-2.3). Could you give me a link to an official documentation where ETag generation is fully describe and it is stated that this algorithm won't be changed in the future please?
In my opinion uploads should be checked with Content-MD5 internally by AWS SDK. Looks like corresponding  PR are going to be merged #887.

**Comment by singku** [comment]
Content MD5 in header can guarantee the integrity of single part. We don't know if the file is good when the parts are merged into one at service side when multiple part upload engaged.

**Comment by singku** [comment]
Content MD5 in header can guarantee the integrity of single part. We don't know if the file is good when the parts are merged into one at service side when multiple part upload engaged.

**Comment by dmitryash** [comment]
> Content MD5 in header can guarantee the integrity of single part. We don't know if the file is good when the parts are merged into one at service side when multiple part upload engaged.

This is a responsibility of the server. It should guarantee that everything is merged fine.
