### ISSUE TITLE
VS2017 x64 s3 statically linked link error

### ISSUE THREAD

**Issue by theMadStork** [aws/aws-sdk-cpp#1158]
### What platform/OS are you using?
Windows 10

### Which version of the SDK?
1.7.117

### What compiler are you using? what version?
MSVS 2017 x64

### What are your CMake arguments?
-G "Visual Studio 15 2017 Win64" -D CMAKE_BUILD_TYPE=Release -D BUILD_ONLY="core;s3"

### Can you provide a TRACE level log? (sanitize any sensitive information)
mainwindow.obj:-1: error: LNK2001: unresolved external symbol "char const * const Aws::Http::CONTENT_TYPE_HEADER" (?CONTENT_TYPE_HEADER@Http@Aws@@3PEBDEB)

mainwindow.obj:-1: error: LNK2001: unresolved external symbol "char const * const Aws::Http::API_VERSION_HEADER" (?API_VERSION_HEADER@Http@Aws@@3PEBDEB)

-------------------
Program compiles and runs with InitAPI() and ShutdownAPI() and S3::S3Client(). It's when I include S3::Model::GetObjectRequest when I receive the linking error.

I've also tried tried many different preprocessors I've found on here:
AWS_SDK_PLATFORM_WINDOWS
USE_WINDOWS_DLL_SEMANTICS
ENABLE_WINDOWS_CLIENT
ENABLE_BCRYPT_ENCRYPTION
USE_IMPORT_EXPORT
AWS_S3_EXPORTS
AWS_CORE_API
AWS_CORE_EXPORTS

**Comment by KaibaLopez** [comment]
Hi @theMadStork,
There's already a discussion of this on issue  #1154, please refer to that one, I'll be closing this one
