### ISSUE TITLE
Compilation errors on Mac against aws-sdk-cpp

### ISSUE THREAD

**Issue by tedyu** [aws/aws-sdk-cpp#1162]
### What platform/OS are you using?
Darwin 17.7.0 Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT 2019; root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64

### Which version of the SDK?
master branch of aws-sdk-cpp repo

### What compiler are you using? what version?
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

### What are your CMake arguments?
-I/Users/yute/homebrew/include  –Daws-sdk-cpp_DIR=~/aws-sdk-cpp/build .

### Can you provide a TRACE level log? (sanitize any sensitive information)
Here is the complete error listing:
https://pastebin.com/XbgSxjk3

**Comment by singku** [comment]
Please enable C++ 11 in your project.
