### ISSUE TITLE
Link error on Mac against aws-sdk-cpp

### ISSUE THREAD

**Issue by tedyu** [aws/aws-sdk-cpp#1163]
### What platform/OS are you using?
Darwin 17.7.0 Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT 2019; root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64

### Which version of the SDK?
master branch of aws-sdk-cpp repo

### What compiler are you using? what version?
gcc
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

### What are your CMake arguments?
cmake -Wc++11-extensions -I/Users/yute/homebrew/include -L/Users/yute/homebrew/lib/cmake  –Daws-sdk-cpp_DIR=~/aws-sdk-cpp/build .

### Can you provide a TRACE level log? (sanitize any sensitive information)

Here is listing under homebrew:

find ~/homebrew/lib/ -name 'aws-cpp-sdk-s3*'
/Users/yute/homebrew/lib//pkgconfig/aws-cpp-sdk-s3.pc
/Users/yute/homebrew/lib//pkgconfig/aws-cpp-sdk-s3-encryption.pc
/Users/yute/homebrew/lib//pkgconfig/aws-cpp-sdk-s3control.pc
/Users/yute/homebrew/lib//cmake/aws-cpp-sdk-s3control
/Users/yute/homebrew/lib//cmake/aws-cpp-sdk-s3control/aws-cpp-sdk-s3control-targets-release.cmake
/Users/yute/homebrew/lib//cmake/aws-cpp-sdk-s3control/aws-cpp-sdk-s3control-config.cmake
/Users/yute/homebrew/lib//cmake/aws-cpp-sdk-s3control/aws-cpp-sdk-s3control-targets.cmake
/Users/yute/homebrew/lib//cmake/aws-cpp-sdk-s3control/aws-cpp-sdk-s3control-config-version.cmake
/Users/yute/homebrew/lib//cmake/aws-cpp-sdk-s3
/Users/yute/homebrew/lib//cmake/aws-cpp-sdk-s3/aws-cpp-sdk-s3-config-version.cmake
/Users/yute/homebrew/lib//cmake/aws-cpp-sdk-s3/aws-cpp-sdk-s3-targets-release.cmake
/Users/yute/homebrew/lib//cmake/aws-cpp-sdk-s3/aws-cpp-sdk-s3-targets.cmake
/Users/yute/homebrew/lib//cmake/aws-cpp-sdk-s3/aws-cpp-sdk-s3-config.cmake
/Users/yute/homebrew/lib//cmake/aws-cpp-sdk-s3-encryption
/Users/yute/homebrew/lib//cmake/aws-cpp-sdk-s3-encryption/aws-cpp-sdk-s3-encryption-config.cmake
/Users/yute/homebrew/lib//cmake/aws-cpp-sdk-s3-encryption/aws-cpp-sdk-s3-encryption-config-version.cmake
/Users/yute/homebrew/lib//cmake/aws-cpp-sdk-s3-encryption/aws-cpp-sdk-s3-encryption-targets.cmake
/Users/yute/homebrew/lib//cmake/aws-cpp-sdk-s3-encryption/aws-cpp-sdk-s3-encryption-targets-release.cmake
/Users/yute/homebrew/lib//python2.7/site-packages/tensorflow/include/external/aws/aws-cpp-sdk-s3

**Comment by singku** [comment]
So have you solved the problem compiling your code against SDK? And now there are linking errors?

**Comment by tedyu** [comment]
Yes - compilation error is gone.

On Mac, where would the aws-cpp-sdk-s3 lib reside ?
I only see some .cmake files in the above list.

**Comment by singku** [comment]
If you are building the sdk on your own, why did you search libs under homebrew directory?  They should be in the build directory. I recommend you to run sudo make install to install them.

**Comment by tedyu** [comment]
I ran 'sudo make install' more than once.
Here was snippet from latest run:
```
-- Up-to-date: /Users/yute/homebrew/lib/cmake/aws-cpp-sdk-s3/aws-cpp-sdk-s3-targets.cmake
-- Up-to-date: /Users/yute/homebrew/lib/cmake/aws-cpp-sdk-s3/aws-cpp-sdk-s3-targets-release.cmake
-- Up-to-date: /Users/yute/homebrew/lib/cmake/aws-cpp-sdk-s3/aws-cpp-sdk-s3-config.cmake
-- Up-to-date: /Users/yute/homebrew/lib/cmake/aws-cpp-sdk-s3/aws-cpp-sdk-s3-config-version.cmake
```
that was why I was looking under homebrew
```
./aws-cpp-sdk-s3-integration-tests
./aws-cpp-sdk-s3-integration-tests/aws-cpp-sdk-s3-integration-tests
./aws-cpp-sdk-s3-integration-tests/CMakeFiles/aws-cpp-sdk-s3-integration-tests.dir
./aws-cpp-sdk-s3
./aws-cpp-sdk-s3/aws-cpp-sdk-s3.pc
./aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir
./aws-cpp-sdk-s3/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-s3
./aws-cpp-sdk-s3/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-s3/aws-cpp-sdk-s3-targets-release.cmake
./aws-cpp-sdk-s3/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-s3/aws-cpp-sdk-s3-targets.cmake
./aws-cpp-sdk-s3/aws-cpp-sdk-s3-config-version.cmake
./aws-cpp-sdk-s3/aws-cpp-sdk-s3-targets.cmake
./aws-cpp-sdk-s3/aws-cpp-sdk-s3-config.cmake
```
The above is what I found under build dir

**Comment by singku** [comment]
The libs are prefixed with "lib", your search command didn't add "lib" prefix

**Comment by tedyu** [comment]
Thanks for the reminder.
I found this file under build dir:

./aws-cpp-sdk-s3/libaws-cpp-sdk-s3.dylib

How would I reference this file ?

**Comment by singku** [comment]
Are you using cmake for your own project?

**Comment by tedyu** [comment]
I was following 

https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/

**Comment by tedyu** [comment]
When I ran make, it ended with :
```
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] ProfileConfigFileAWSCredentialsProviderTest.TestDefaultConfig
[  FAILED  ] ProcessCredentialsProviderTest.TestProcessCredentialsProviderDoNotRefresh
[  FAILED  ] ProcessCredentialsProviderTest.TestProcessCredentialsProviderExpiredThenRefreshed
```
Do you know if the above would result in some build artifacts not generated, @singku ?
If so, how do I skip running tests ?

thanks

**Comment by singku** [comment]
That blog is out dated.
Please follow 
https://aws.amazon.com/blogs/developer/developer-experience-of-the-aws-sdk-for-c-now-simplified-by-cmake/

You can specify -DAUTORUN_UNIT_TESTS =OFF to disable test from being running.

**Comment by Falken42** [comment]
@tedyu I noticed the same three test failures on macOS when `AWS_DEFAULT_PROFILE` is set in the shell environment (see #1165).

Run this:
```
$ unset AWS_DEFAULT_PROFILE
```
before calling `make` and the tests should pass.

**Comment by tedyu** [comment]
@singku
Your blog is helpful.
In the build output I saw this:
```
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
```
I assume it is not anything I need to worry about.

**Comment by tedyu** [comment]
@Falken42 
Thanks for the hint.

As far as I can see, AWS_DEFAULT_PROFILE is not set in my environment.
So I am not sure what observed is the same as what I saw.

My Mac OS version is given at the top of this issue.

**Comment by tedyu** [comment]
@singku 
w.r.t. your cmake blog, for the following command:

cmake -Wc++11-extensions -Daws-sdk-cpp_DIR="\Users\Ted Yu\aws-build" -G "Visual Studio 16 2019" -I"\Program Files (x86)\aws-cpp-sdk-all"\include -L"\Program Files (x86)\aws-cpp-sdk-all"\lib .
```
CMake Error at CMakeLists.txt:6 (find_package):
  By not providing "FindAWSSDK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "AWSSDK", but
  CMake did not find one.

  Could not find a package configuration file provided by "AWSSDK" with any
  of the following names:

    AWSSDKConfig.cmake
    awssdk-config.cmake

  Add the installation prefix of "AWSSDK" to CMAKE_PREFIX_PATH or set
  "AWSSDK_DIR" to a directory containing one of the above files.  If "AWSSDK"
  provides a separate development package or SDK, be sure it has been
  installed.
```
However, I have already set the environment variable:
```
dir %AWSSDK_DIR%\AWSSDKConfig.cmake
 Volume in drive C has no label.
 Volume Serial Number is 98C2-FE7D

 Directory of C:\Users\Ted Yu\aws-sdk-cpp\cmake

06/12/2019  06:50 PM            12,988 AWSSDKConfig.cmake
```
