### ISSUE TITLE
Multipart Upload - Set ACL not working 

### ISSUE THREAD

**Issue by spanikul** [aws/aws-sdk-cpp#1164]
### What platform/OS are you using?
OS: Microsoft Windows Server 2016 Standard
Hardware: VMWare Virtual Platform
Processors: Intel Xeon(R) CPU ES-2667 V3 @ 3.20 GHz
Memory: 8.11GB
### Which version of the SDK?
1.7.179
### What compiler are you using? what version?
Visual Studio 2017
### What are your CMake arguments?
-DBUILD_ONLY="s3;transfer" -DTARGET_ARCH=WINDOWS -G"Visual Studio 15"
### Code Snippet
	std::shared_ptr<Aws::Utils::Threading::Executor> tm_exe;
	tm_exe = Aws::MakeShared<Aws::Utils::Threading::PooledThreadExecutor>("TransferManagerExecutor", 4);
	Aws::Transfer::TransferManagerConfiguration transferConfig(tm_exe.get());
	Aws::S3::Model::ObjectCannedACL acl = Aws::S3::Model::ObjectCannedACL::bucket_owner_full_control;

	transferConfig.s3Client = awss3_Client;
	transferConfig.putObjectTemplate.SetACL(acl);

**Comment by singku** [comment]
It's a known issue and has been fixed. You need to update the sdk used

**Comment by spanikul** [comment]
Thank You

**Comment by singku** [comment]
I thought it was the same as #1088 and #1089.  Have you looked at those problems ?

**Comment by spanikul** [comment]
Yes, this is a different problem.  In multipart upload, unable to set canned ACL bucket_owner_full_control.  Bucket owner has a bucket policy to Deny upload without the canned ACL set; so the upload will fail with an 'Access Denied' error.  This is only a problem with a multipart uploads, setting canned ACL for Singlepart upload with PutObjectRequest works.

**Comment by andrew-millin** [comment]
Use TransferManagerConfiguration createMultipartUploadTemplate instead of (or in addition to) putObjectTemplate

`transferConfig.createMultipartUploadTemplate.SetACL(acl);`

**Comment by KaibaLopez** [comment]
Hi, I'm not able to reproduce this error at this time, so I'm going to mark this for closure, if you are still seeing it, please open a new issue so that it is more visible to us.
