### ISSUE TITLE
Failed to build third-party libraries.

### ISSUE THREAD

**Issue by lsong0905** [aws/aws-sdk-cpp#1166]
### What platform/OS are you using?
Linux

### Which version of the SDK?
1.7.29

### What compiler are you using? what version?
g++ 4.8.5

### What are your CMake arguments?
cmake -DBUILD_ONLY="core;s3" -DCMAKE_BUILD_TYPE=RelWithDebInfo

### Can you provide a TRACE level log? (sanitize any sensitive information)
[ 33%] Built target AwsCCommon
[ 66%] Built target AwsChecksums
[ 70%] Performing build step for 'AwsCEventStream'
[  9%] Building C object CMakeFiles/aws-c-event-stream.dir/source/event_stream.c.o
/home/jenkins/aws-sdk-cpp/.deps/build/src/AwsCEventStream/source/event_stream.c: In function ‘aws_event_stream_message_from_buffer’:
/home/jenkins/aws-sdk-cpp/.deps/build/src/AwsCEventStream/source/event_stream.c:315:5: error: implicit declaration of function ‘AWS_ASSERT’ [-Werror=implicit-function-declaration]
     AWS_ASSERT(buffer);
     ^
cc1: all warnings being treated as errors
CMakeFiles/aws-c-event-stream.dir/build.make:62: recipe for target 'CMakeFiles/aws-c-event-stream.dir/source/event_stream.c.o' failed
gmake[5]: *** [CMakeFiles/aws-c-event-stream.dir/source/event_stream.c.o] Error 1
CMakeFiles/Makefile2:419: recipe for target 'CMakeFiles/aws-c-event-stream.dir/all' failed
gmake[4]: *** [CMakeFiles/aws-c-event-stream.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
gmake[3]: *** [all] Error 2
CMakeFiles/AwsCEventStream.dir/build.make:111: recipe for target 'build/src/AwsCEventStream-stamp/AwsCEventStream-build' failed
gmake[2]: *** [build/src/AwsCEventStream-stamp/AwsCEventStream-build] Error 2
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/AwsCEventStream.dir/all' failed
gmake[1]: *** [CMakeFiles/AwsCEventStream.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
gmake: *** [all] Error 2
CMake Error at CMakeLists.txt:161 (message):
  Failed to build third-party libraries.

**Comment by singku** [comment]
It's a known issue in one of the older SDK versions. Please update SDK to latest. Thanks.

**Comment by lsong0905** [comment]
@singku Is there any work-around beside updating SDK to latest?

**Comment by singku** [comment]
Try this patch 
https://github.com/aws/aws-sdk-cpp/commit/18ddaa9746b6ea40b247272ab8f804082943b503

**Comment by lsong0905** [comment]
@singku The patch seems to work. We used to build without this patch before, and did not see this error. Was there any recent change to 1.7.29 sdk version? I am wondering what the root cause of this.

**Comment by singku** [comment]
Without this patch, every time we build SDK, we will build aws-c-event-stream with the latest commit, instead of the pined commit/tag in CMakeList.txt. AWS common runtime team recently added several new features to aws-c-event-stream, which depends on updates from aws-c-common as well. But we didn't update aws-c-common in SDK. That's the root cause.

**Comment by lsong0905** [comment]
@singku I see. So, with the patch, the version of aws-c-event-stream will be pinned as the version defined in aws-sdk-cpp/third-party/CMakeLists.txt
