### ISSUE TITLE
ERROR_PROC_NOT_FOUND

### ISSUE THREAD

**Issue by genifycom** [aws/aws-sdk-cpp#1170]
If you build the sample CPP S3 examples in a 32-bit DLL using Visual Studio 2017 environment and you use any S3 packages later than v1.3.59 then when you try to perform a LoadLibrary on the DLL, you will get OS Error 0x0000007F ERROR_PROC_NOT_FOUND

Dependency Viewer shows that the aws DLL were found, but there is a C++ linkage problem.

Backing all S3 libraries to v1.3.59 makes this issue go away.

Please check linkages to the aws-cpp-sdk-s3.dll and aws-cpp-sdk-transfer.dll and ensure there are none missing.

**Comment by KaibaLopez** [comment]
Hi @genifycom,
I'm not able to reproduce this issue, so I'll have to ask for some more info
Do you have the same problem with a 64-bit dll? 
Could you provide me with your cmake arguments?
Also, this error is related to GetProcAddress(), are you calling that on any function?
