### ISSUE TITLE
Inadequate doc for using HttpClientFactory

### ISSUE THREAD

**Issue by tedyu** [aws/aws-sdk-cpp#1173]
In README.md of aws-sdk-cpp :

```
    Aws::SDKOptions options;
    options.httpOptions.httpClientFactory_create_fn = [](){ return Aws::MakeShared<MyCustomHttpClientFactory>("ALLOC_TAG", arg1); };
    Aws::InitAPI(options);
    .....
    Aws::ShutdownAPI(options);
```
However, there is no code showing how MyCustomHttpClientFactory should be written.
Considering that DefaultHttpClientFactory is not public:
```
        class DefaultHttpClientFactory : public HttpClientFactory
```
Does user code have to implement what DefaultHttpClientFactory has done ?

thanks

**Comment by marcomagdy** [comment]
>Does user code have to implement what DefaultHttpClientFactory has done ?

HttpClientFactory has 3 pure virtual functions. At least you have to implement those.

>there is no code showing how MyCustomHttpClientFactory should be written.

Because that depends on the http client the factory would be creating.
