### ISSUE TITLE
event_stream.h build error

### ISSUE THREAD

**Issue by rahul003** [aws/aws-sdk-cpp#1175]
### What platform/OS are you using?
Ubuntu
### Which version of the SDK?
1.7.99
### What compiler are you using? what version?
gcc using bazel

### Can you provide a TRACE level log? (sanitize any sensitive information)
```
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/external/aws/BUILD.bazel:12:1: C++
compilation of rule '@aws//:aws' failed (Exit 1)
In file included from external/aws/aws-cpp-sdk-core/include/aws/core/utils/event/EventStreamHandler.h:20:0,
                 from external/aws/aws-cpp-sdk-core/include/aws/core/utils/event/EventStreamDecoder.h:20,
                 from external/aws/aws-cpp-sdk-core/include/aws/core/utils/event/EventStreamBuf.h:19,
                 from external/aws/aws-cpp-sdk-core/source/utils/event/EventStreamBuf.cpp:15:
external/aws/aws-cpp-sdk-core/include/aws/core/utils/event/EventHeader.h:24:43: fatal error: aws/event-stream/even$
_stream.h: No such file or directory
```

**Comment by rahul003** [comment]
How can I resolve this? I get this when building sdk with Tensorflow

**Comment by rahul003** [comment]
Looks like the event-stream package is not getting installed. What information can I provide to help you debug?

**Comment by KaibaLopez** [comment]
Hi @rahul003,
Could you provide your BUILD.bazel file? 
Also, I see in your error code it is trying to access "aws/event-stream/even$_stream.h" instead of "aws/event-stream/event_stream.h" did you make any manual change that could include this typo?

**Comment by marcomagdy** [comment]
> How can I resolve this? I get this when building sdk with Tensorflow

Follow the instructions for building Tensorflow. https://www.tensorflow.org/install/source

If you're facing problems, then contact the Tensorflow team on how they build the sdk in Tensorflow.
Unfortunately, we do not support building the SDK with Bazel. Your best bet might be to build the SDK and install it somewhere on your machine and then point Bazel to it.
