### ISSUE TITLE
S3 Multipart download high CPU usage and thread count

### ISSUE THREAD

**Issue by spanikul** [aws/aws-sdk-cpp#1178]
### Description
Simultaneous download of six 300mb files from an S3 bucket with six worker threads resulted in 220 threads being created. CPU usage remained at 100% for the duration of the download approximately 9 minutes. Can multipart download be managed such that thread and CPU does not get that high? Suspect the Xeon processor may be partly responsible for the high CPU usage but not sure. 

### What platform/OS are you using?
OS: Microsoft Windows Server 2016 Standard
Hardware: VMWare Virtual Platform
Processors: Intel Xeon(R) CPU ES-2667 V3 @ 3.20 GHz
Memory: 8.11GB
### Which version of the SDK?
1.7.129
### What compiler are you using? what version?
Visual Studio Community 2017 Version 15.9.3
### What are your CMake arguments?
-DBUILD_ONLY="s3;transfer" -DTARGET_ARCH=WINDOWS <src-loc> -G"Visual Studio 15"

**Comment by KaibaLopez** [comment]
Hi @spanikul, 
Yes, you can control the number of threads created by the transfer manager.

One simple way would be by modifying the buffer size in the configuration struct.

https://github.com/aws/aws-sdk-cpp/blob/11e9a78009eea36d219be20988f65b5ad74bdee0/aws-cpp-sdk-transfer/include/aws/transfer/TransferManager.h#L84-L88

Another way would be to create your own executor class, then you could set the thread pool size. 
For an implementation example you can take a look at PooledThreadExecutor
https://github.com/aws/aws-sdk-cpp/blob/11e9a78009eea36d219be20988f65b5ad74bdee0/aws-cpp-sdk-core/include/aws/core/utils/threading/Executor.h#L91

Hope this helps!

**Comment by spanikul** [comment]
Thank You Lopez.  Am I correct in assuming that increasing the bufferSize will reduce the number of threads?

**Comment by KaibaLopez** [comment]
Yeap, that's correct.

**Comment by spanikul** [comment]
Thank You Lopez.  Just what I needed to hear...

**Comment by mytxz** [comment]
How about the high CPU usage when upload big file?
