### ISSUE TITLE
Crashes in TransferManager::DoSinglePartUpload.

### ISSUE THREAD

**Issue by thanhldnv** [aws/aws-sdk-cpp#1179]
My service uploads files(data, dump files,...), and it crashes while running(this is other crash doesn't relate to aws), then it is started again by OS, then my service detects a crash file and uploads this file to S3 and this issue happened at that time, this is sometimes.

Can you give me some advice on this case?

### What platform/OS are you using?

Windows 10 Version 17134 MP (4 procs) Free x64
Product: WinNt, suite: SingleUserTS Personal
17134.1.amd64fre.rs4_release.180410-1804

### Which version of the SDK?

34cb979dea94959e516c4bc75f137815da632b7c

### What compiler are you using? what version?

Visual Studio 15 2017 Win64

### Can you provide a TRACE level log? (sanitize any sensitive information)
```c++
: msvcp140!std::basic_streambuf<char,std::char_traits<char> >::xsgetn+0x86
: msvcp140!std::basic_istream<char,std::char_traits<char> >::read+0x8d
: CortexSync!Aws::Transfer::TransferManager::DoSinglePartUpload+0x47e
: CortexSync!Aws::Utils::Threading::ThreadTask::MainTaskRunner+0x4b
: CortexSync!std::_LaunchPad<std::unique_ptr<std::tuple<std::_Binder<std::_Unforced,void (__cdecl Aws::Utils::Threading::ThreadTask::*)(void) __ptr64,Aws::Utils::Threading::ThreadTask * __ptr64> >,std::default_delete<std::tuple<std::_Binder<std::_Unforced,void (__cdecl Aws::Utils::Threading::ThreadTask::*)(void) __ptr64,Aws::Utils::Threading::ThreadTask * __ptr64> > > > >::_Go+0x6c
: CortexSync!std::_Pad::_Call_func+0x9
: ucrtbase!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x3e
: kernel32!BaseThreadInitThunk+0x14
: ntdll!RtlUserThreadStart+0x21

```

**Comment by KaibaLopez** [comment]
Hi @thanhldnv,
could you provide a code snippet on how you're trying to use transfer manager?

**Comment by thanhldnv** [comment]
@KaibaLopez 
`bool S3Client::uploadFile(const QMap<QString, QString> &fileProperties,
                          const QString &filePath,
                          const QString &keyName,
                          const QString &contentType,
                          const Cortex::Model::CSUser &csUser)
{
    qDebug() << __FUNCTION__ << "<file path>" << filePath;

    auto transferManager = createTransferManager(_executor, csUser);
    std::shared_ptr<const Aws::Client::AsyncCallerContext> context =
            Aws::MakeShared<Aws::Client::AsyncCallerContext>("UploadContext", filePath.toStdString()); //use file path for contex
    auto fileStream = Aws::MakeShared<Aws::FStream>("PutObjectInputStream", filePath.toStdString().c_str(),
                                                    std::ios_base::in | std::ios_base::binary);
    //add properties
    Aws::Map<Aws::String, Aws::String> meta;
    QMapIterator<QString, QString> i(fileProperties);
    while(i.hasNext()){
        i.next();
        meta[i.key().toStdString()] = i.value().toStdString();
    }

    auto transferHandler = transferManager->UploadFile(fileStream,
                                                       _bucketName.toStdString(),
                                                       keyName.toStdString(),
                                                       contentType.toStdString(),
                                                       meta,
                                                       context);
    return true;
}`


`std::shared_ptr<Aws::Transfer::TransferManager> S3Client::createTransferManager(Threading::Executor* executor,
                                                                                const Model::CSUser &csUser)
{
    //Create transfer config
    Aws::Transfer::TransferManagerConfiguration transferConfig(executor);

    //Create S3Client
    Aws::Client::ClientConfiguration clientConfig;
    clientConfig.requestTimeoutMs = 60000;//Set request timeout to 60 seconds
    if (!_region.isEmpty())
        clientConfig.region = _region.toStdString();
    AWSCredentials credentials(csUser.s3AccessKey.toStdString(),
                               csUser.s3SecretAccessKey.toStdString(),
                               csUser.s3SessionToken.toStdString());
    auto s3Client = Aws::MakeShared<Aws::S3::S3Client>(_allocationTag, credentials, clientConfig);
    transferConfig.s3Client = s3Client;

    //set ACL to private with PutObjectRequest
    Aws::S3::Model::PutObjectRequest putObjectRequest;
    putObjectRequest.SetACL(ObjectCannedACL::private_);
    transferConfig.putObjectTemplate = putObjectRequest;

    //set ACL to provate with CreateMultipartUploadRequest
    Aws::S3::Model::CreateMultipartUploadRequest multiPartUploadRequest;
    multiPartUploadRequest.SetACL(ObjectCannedACL::private_);
    transferConfig.createMultipartUploadTemplate = multiPartUploadRequest;

    //this callback is called when transfer status updated
    transferConfig.transferStatusUpdatedCallback = [=](const Aws::Transfer::TransferManager* tm,
            const std::shared_ptr<const Aws::Transfer::TransferHandle>& th) {
        Q_UNUSED(tm);
        QString contextUuid = QString::fromStdString(th->GetContext()->GetUUID());
        if (th->GetStatus() == Aws::Transfer::TransferStatus::EXACT_OBJECT_ALREADY_EXISTS
                || th->GetStatus() == Aws::Transfer::TransferStatus::COMPLETED) {
            if (th->GetTransferDirection() == Aws::Transfer::TransferDirection::UPLOAD) {
                emit uploadFinished(true, contextUuid);
            } else {
                Aws::Map<Aws::String, Aws::String> metadata = th->GetMetadata();
                Aws::String fileMd5 = "";
                if (metadata.count(_md5MetaName) > 0) {
                    fileMd5 = metadata[_md5MetaName];
                }
                onDownloadFileFinished(contextUuid, true,
                                       QString::fromStdString(th->GetTargetFilePath()), fileMd5);
            }
        } else if (th->GetStatus() == Aws::Transfer::TransferStatus::CANCELED
                   || th->GetStatus() == Aws::Transfer::TransferStatus::FAILED
                   || th->GetStatus() == Aws::Transfer::TransferStatus::ABORTED) {
            if (th->GetTransferDirection() == Aws::Transfer::TransferDirection::UPLOAD) {
                emit uploadFinished(false, contextUuid);
            } else {
                onDownloadFileFinished(contextUuid, false, QString::fromStdString(th->GetTargetFilePath()), "");
            }
        }
    };

    //this callback is called if there is an error while transferring
    //use this callback just for debugging
    //transferStatusUpdatedCallback is enough for return status
    transferConfig.errorCallback = [=](const Aws::Transfer::TransferManager* tm,
            const std::shared_ptr<const Aws::Transfer::TransferHandle>& th,
            const Aws::Client::AWSError<Aws::S3::S3Errors>& er) {
        Q_UNUSED(tm);
        QString message = QString("Error message:%1 | response code: %2 | error type: %3 | path: %4").arg(er.GetMessage().c_str()).
                arg(static_cast<int>(er.GetResponseCode())).
                arg(static_cast<int>(er.GetErrorType())).
                arg(th->GetTargetFilePath().c_str());
        emit syncFailed(message);
    };

//    transferConfig.uploadProgressCallback = [=](const Aws::Transfer::TransferManager* tm,
//            const std::shared_ptr<const Aws::Transfer::TransferHandle>& th)
//    {
//        qDebug() << "Upload progress:" << th->GetBytesTransferred() << "/" << th->GetBytesTotalSize();
//    };

    auto transferManager = Aws::Transfer::TransferManager::Create(transferConfig);
    return transferManager;
}`

**Comment by thanhldnv** [comment]
@KaibaLopez Can you give me an advice about my code ?

**Comment by KaibaLopez** [comment]
Hi @thanhldnv, first of sorry for the delayed response, and thanks for the code sample. 
The code seems fine, it is the problem description that I'm still not clear on. 
Does the transfer manager fail to upload data? or do you want to avoid the transfer manager to upload the file after it crashed?

**Comment by thanhldnv** [comment]
> Does the transfer manager fail to upload data? or do you want to avoid the transfer manager to upload the file after it crashed?

Yes, it did crash so the upload isn't completed. I want to avoid crashing. @KaibaLopez 
Do you have any idea about the stack trace ?

**Comment by KaibaLopez** [comment]
right, you can activate the trace logs by adding:
`Aws::SDKOptions options;`
`options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;`
