### ISSUE TITLE
Tweaking VersionConfig.h during cmake causes updates to fail

### ISSUE THREAD

**Issue by Bu11etmagnet** [aws/aws-sdk-cpp#118]
Steps to reproduce:

1. git clone
2. run cmake
3. wait for a commit
4. git pull

```
remote: Counting objects: 773, done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 773 (delta 653), reused 771 (delta 651), pack-reused 0
Receiving objects: 100% (773/773), 300.90 KiB | 0 bytes/s, done.
Resolving deltas: 100% (653/653), completed with 213 local objects.
From https://github.com/awslabs/aws-sdk-cpp
   2ff5415..3fe46f0  master     -> origin/master
Updating 2ff5415..3fe46f0
error: Your local changes to the following files would be overwritten by merge:
	aws-cpp-sdk-core/include/aws/core/VersionConfig.h

```

**Comment by JonathanHenson** [comment]
This isn't unintended behavior. It's the current solution for tagging the version. However, we recognize this is problematic and are looking for a better approach.

**Comment by Bu11etmagnet** [comment]
How about not having `aws-cpp-sdk-core/include/aws/core/VersionConfig.h` in git, just generate it (e.g. from `aws-cpp-sdk-core/include/aws/core/VersionConfig.h.in`) ?

**Comment by JonathanHenson** [comment]
How would someone without git installed build?

**Comment by Bu11etmagnet** [comment]
If git is not installed, a fake value should be concocted instead of the git output (I haven't looked at what CMake actually does when tagging).

**Comment by JonathanHenson** [comment]
We've improved this dramatically by incrementing this value during our release process and changing the describe command. This shouldn't be an issue after you update, and pull the tags. Please reopen if you are still having problems.

**Comment by Bu11etmagnet** [comment]
Latest git pulls didn't have this problem.
Thanks for fixing it!
