### ISSUE TITLE
cmake: cmake can't find libraries on linux

### ISSUE THREAD

**Issue by dmitryash** [aws/aws-sdk-cpp#1188]
Hello,

I get cmake error when run cmake for project which uses AWSSDK:

```
CMake Error at /usr/lib64/cmake/AWSSDK/AWSSDKConfig.cmake:122 (message):
  AWS SDK for C++ headers found, but we were unable to locate the binaries.
  Have you deleted or moved it?

              Please make sure header files and binaries are located in INSTALL_ROOT_DIR/INCLUDE_DIR/ and INSTALL_ROOT_DIR/LIB_DIR/[PLATFORM_PREFIX]/[Debug|Config|OtherConfigs]
Call Stack (most recent call first):
  CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
```

This error happens because header files are installed to `/usr/include` and libraries are installed to `/usr/lib64` directory. These directories are set by rpm macro `%cmake` provided by Linux OS maintainers.

I see that AWSSDKConfig.cmake finds header files because it enabled system directories. However then it never looks at system directories. As you can see below, system directoryes with libraries are just skipped.

https://github.com/aws/aws-sdk-cpp/blob/ec618a42ae702c86e5466ae637ff903028af11f6/cmake/AWSSDKConfig.cmake#L110-L119

**Comment by dmitryash** [comment]
I found that platformDeps.cmake is generated with:
```
set(AWSSDK_INSTALL_LIBDIR /usr/lib64)
```

This was most likely because `%cmake` macro defines CMAKE_INSTALL_LIBDIR to /usr/lib64

**Comment by singku** [comment]
Hi, we don't ship rpm install package for AWS SDK for CPP. I suggest you to compile and install sdk from source to make it work properly.

**Comment by dmitryash** [comment]
Hi, it is OK that you don't ship rpm package. Basically distro maintainers knowns details of their distro and pack rpm in a proper way. I'm trying to pack sdk into rpm and let users install rpm packages instead. Installation from sources is not a solution.
What really matters is that SDK should use cmake correctly. In this particular case cmake documentation says that `CMAKE_INSTALL_LIBDIR` is supposed to be put to `imstall()` command. At the same time this `install()` command allows specifying both absolute and relative paths. As a result it is allowed that `CMAKE_INSTALL_LIBDIR` is absolute path.

**Comment by singku** [comment]
Oh I see. I thought you are integrating SDK with a 3rd party rpm package. 
You are right that, we treat `CMAKE_INSTALL_LIBDIR` as a dir name and passed it down to LIBARY_DIRECTORY, then to AWSSDK_INSTALL_LIBDIR. So it's really a dir name, instead of a relative path or absolute path. When locating the library directory, as you have seen, we use this dir name and AWSSDK_ROOT_DIR to compose several search paths to look up. At this point, can you specify `lib64` instead of `/usr/lib64` to unblock your work? You are always welcomed to submit a PR to fix this problem.
