### ISSUE TITLE
TTS still has bug on windows, still have PR to fix it

### ISSUE THREAD

**Issue by diablodale** [aws/aws-sdk-cpp#1193]
Amazon has not incorporated the TTS fix for windows for almost two years.
https://github.com/aws/aws-sdk-cpp/pull/681

As feedback, I chose to not use this SDK because fixes were not being fixed and incorporated. I'm cleaning up loose ends that have no progress and this one qualifies. I'll leave the PR open for one or two more weeks and if no action from Amazon I will purge it.

**Comment by wps132230** [comment]
Thank you for your feedback.
It has been a long time...
And It's definitely a typo.

**Comment by wps132230** [comment]
It's in today's release: https://github.com/aws/aws-sdk-cpp/commit/df5d84552a3e038f6941c0337b5d1981de0efbcb
Thank you for your PR again.
