### ISSUE TITLE
TransferManager takes too long to exit the upload thread.

### ISSUE THREAD

**Issue by ThanasisPap** [aws/aws-sdk-cpp#1195]
When I try to upload a small image file (~500KB) mostly greater than 200KB, the transfer manager takes too long to exit although the total bytes have been uploaded. 

### What platform/OS are you using?
Windows 10 x64
### Which version of the SDK?
Version 2.0
### What compiler are you using? what version?
Visual Studio 14 2015 Win32
### What are your CMake arguments?
-DMINIMIZE_SIZE=ON
-DBUILD_ONLY="s3;rds;transfer;"
-DCMAKE_BUILD_TYPE=Debug

The console outputs the total Size and the total Bytes transferred. After approximately 30s where the total amount of bytes have been uploaded matches the file size, the status callback continuously prints out the same output (the upload thread continue to run even after the bytes uploaded).  When a smaller file (approx. <200KB) is uploaded the thread exits successfully although it still makes a lot of redundant status callback calls (the upload bytes have reached the file size). 

Here is a test code:

```
#include "pch.h"
#include <iostream>
#include <fstream>
#include <filesystem>

#include <aws/core/Aws.h>
#include <aws/core/auth/AWSCredentials.h>
#include <aws/s3/S3Client.h>
#include <aws/s3/model/Bucket.h>
#include <aws/transfer/TransferManager.h>
#include <aws/transfer/TransferHandle.h>

static const char* KEY = "KEY";
static const char* BUCKET = "BUCKET_NAME";
static const char* ACCESS_KEY = "AKEY";
static const char* OBJ_NAME = "img.jpg";
static const char* const ALLOCATION_TAG = "S3_SINGLE_OBJ_TEST";

int main()
{
	Aws::SDKOptions options;
	Aws::InitAPI(options);
	{
		Aws::Client::ClientConfiguration config;
		config.region = Aws::Region::US_EAST_2;

		auto s3_client = std::make_shared<Aws::S3::S3Client>(Aws::Auth::AWSCredentials(KEY, ACCESS_KEY), config);

		const Aws::String bucket_name = BUCKET;
		const Aws::String object_name = OBJ_NAME;
		const Aws::String key_name = OBJ_NAME;

		auto s3_client_executor = Aws::MakeShared<Aws::Utils::Threading::DefaultExecutor>(ALLOCATION_TAG);
		Aws::Transfer::TransferManagerConfiguration trConfig(s3_client_executor.get());
		trConfig.s3Client = s3_client;

                //This callback is called forever...
		trConfig.uploadProgressCallback =
			[](const Aws::Transfer::TransferManager*, const std::shared_ptr<const Aws::Transfer::TransferHandle>&transferHandle)
		{ std::cout << "Upload Progress: " << transferHandle->GetBytesTransferred() <<
			" of " << transferHandle->GetBytesTotalSize() << " bytes" << std::endl;};

		std::cout << "File start upload" << std::endl;

		auto tranfer_manager = Aws::Transfer::TransferManager::Create(trConfig);
		auto transferHandle = tranfer_manager->UploadFile(object_name.c_str(),
			bucket_name.c_str(), key_name.c_str(), "multipart/form-data", Aws::Map<Aws::String, Aws::String>());

		transferHandle->WaitUntilFinished();

		if(transferHandle->GetStatus() == Aws::Transfer::TransferStatus::COMPLETED)
			std::cout << "File up" << std::endl;
		else
			std::cout << "Error uploading: " << transferHandle->GetLastError() << std::endl;
	}
	Aws::ShutdownAPI(options);
	return 0;
}
```
Output example for a relatively big file (~600KB):

> File size: 609314
> File start upload
> Upload Progress: 8192 of 609314 bytes
> Upload Progress: 16384 of 609314 bytes
> Upload Progress: 24576 of 609314 bytes
> Upload Progress: 32768 of 609314 bytes
> Upload Progress: 40960 of 609314 bytes
> Upload Progress: 49152 of 609314 bytes
> Upload Progress: 57344 of 609314 bytes
> Upload Progress: 65536 of 609314 bytes
> ...
> ...
> Upload Progress: 609314 of 609314 bytes
> Upload Progress: 609314 of 609314 bytes
> Upload Progress: 609314 of 609314 bytes
> Upload Progress: 609314 of 609314 bytes
> Upload Progress: 609314 of 609314 bytes
> Upload Progress: 609314 of 609314 bytes
> Upload Progress: 609314 of 609314 bytes
> Upload Progress: 609314 of 609314 bytes
> ..Keeps for 2min or more

**Comment by KaibaLopez** [comment]
Hi @ThanasisPap,
I'm not able to replicate your issue, even when uploading a 1MB sized image your code works just fine for me.
Could you provide the tracer logs? That should give us a better idea on why it keeps updating progress on the last byte.
You can activate them by adding this line of code: 
`options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;`
 Make sure to sanitize the data before posting it though, as the logs may contain sensitive information.

**Comment by ThanasisPap** [comment]
I attached the trace log as you said but for a smaller file size because the trace was too long for the 600KB one. 
It seems there is an issue with WinHttpSyncHttpClient which performs repeatedly connection timeouts and reset again till finally upload the file.
The image file was 134044 bytes long and took about 2min to upload. The second time I tried the file failed to upload with:

> Error uploading: HTTP response code: -1

[aws_sdk_2019-07-16-22.log](https://github.com/aws/aws-sdk-cpp/files/3399339/aws_sdk_2019-07-16-22.log)

**Comment by KaibaLopez** [comment]
Yes, you're partially correct. 
[WARN] 2019-07-16 22:12:41.596 WinHttpSyncHttpClient [13780] Send request failed: The operation timed out
It seems to be a connection issue, it is not exactly taking 2 minutes to upload, but it's trying to send the request, waiting each time for up to 3 seconds before timeout and 6 second before retrying.

Can you try increasing the request timeout? 
`config.requestTimeoutMs = 10000;`
Let me know if that works better for you.

**Comment by ThanasisPap** [comment]
@KaibaLopez it works! I think that somehow the TransferHandle needs to be more indicative of whats going on (i.e. make TransferHandle::getStatus() to return an info struct) in order to figure out the issue, or at least mention it in docs.
Thanks for your help!
