### ISSUE TITLE
AWSSDKConfig.cmake should work when installed

### ISSUE THREAD

**Issue by ingomueller-net** [aws/aws-sdk-cpp#1197]
As far as I can tell, `AWSSDKConfig.cmake` currently does not work from the installed location (at `CMAKE_INSTALL_PREFIX` with `make install`). Indeed, [the documentation](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/build-cmake.html) says you should use from the build folder. However, I don't see why it shouldn't work from the installed location as well.

I also think that not much is missing. What *is* missing is that `AWSSDKConfig.cmake` should find the different `*-config.cmake` files in the installed location (including the third-party dependencies). If I specify them via `-Daws-cpp-sdk-core_DIR=...`, it works, but that's a lot of manual work that could be avoided.

### What platform/OS are you using?

Debian 9

### Which version of the SDK?

1.7.138

### What compiler are you using? what version?

Clang 7.0.1

### What are your CMake arguments?

```bash
CXX=clang++-7.0 CC=clang-7.0 cmake ../aws-sdk-cpp-1.7.138/ -DBUILD_ONLY="s3;sqs;dynamodb;lambda" -DCPP_STANDARD=17 -DENABLE_TESTING=OFF -DCUSTOM_MEMORY_MANAGEMENT=OFF -DCMAKE_INSTALL_PREFIX=$PWD/../aws-install -DAWS_DEPS_INSTALL_DIR:STRING=$PWD/../aws-install -DCMAKE_BUILD_TYPE=Debug
```

**Comment by KaibaLopez** [comment]
I'm not 100% clear on what you're asking. Can you clarify a bit? 
you have the sdk's source, the build and the install location all in different folders looks like, and after cmake builds in the build directory, you are trying to run make install from the install directory?

**Comment by ingomueller-net** [comment]
I have run `cmake` and `make install`, then I removed the source and build folders. Now I wish to have a mechanism that finds the library in the installed location.

**Comment by KaibaLopez** [comment]
Hi @ingomueller-net, probably not the answer you're looking for but simply put: 
If you don't want to use -Daws-cpp-sdk-core_DIR then install in default directory. 
If you want to install in a specific directory then use -Daws-cpp-sdk-core_DIR to tell cmake where to look for it.
It sounds like you have a different approach in mind though, so if you'd like to make a PR, we could take a look at that. We are always open for contributions.
