### ISSUE TITLE
SQS modified content

### ISSUE THREAD

**Issue by xydinesh** [aws/aws-sdk-cpp#1200]
We are experiencing same issue as #562 
```
I am sending an SQS message with the following:

"<tag>text</tag>"

When I receive the message with the SDK, (e.g. ReceiveMessageRequest GetResult().GetMessages()) the message is as follows:

"&lt;tag&gt;text&lt;/tag&gt;"
```
We think it is a bug in AWS CPP SDK that it doesn't xml decode SQS content before handing content to the user. In simple terms, user wants to receive same content that goes into the queue. In this case, user doesn't receive same content. Please let us know if there's fix for this. Thanks !

**Comment by KaibaLopez** [comment]
Hi @xydinesh , did the solution provided in https://github.com/aws/aws-sdk-cpp/issues/562#issuecomment-307180673 not work for you? 
Or are you suggesting that having to use the Aws::Utils::Xml::DecodeEscapedXmlText(); 
should be considered a bug?

**Comment by xydinesh** [comment]
```python
import boto3

def main():
    sqs = boto3.resource('sqs', region_name='us-west-2')
    queue = sqs.get_queue_by_name(QueueName='aws-cpp-sdk-queue')
    queue.send_message(MessageBody='<tag>text</tag>')

    for message in queue.receive_messages():
        print (message.body)
        message.delete()

if __name__ == '__main__':
    main()
```

When I run above script, I get following

```
$python sdk.py
<tag>text</tag>
```

I'm suggesting the later. I think, decoding payload better fits as a part of the client library. As shown in the boto3 example.

**Comment by singku** [comment]
Note the sqs is a service using query xml protocol. Message sent from client side is a string and Message received from service is inside xml body and the message escaping is processed on service side (Service side has to escape the message, other wise the xml structure might be violated by user message). When client side received something like `&lt;tag&gt;`. We don't know if the message sent from client side is literally this string or escaped by service. It's up to you to decide if you are going to unescape it or not.

As to python SDK. try sending and receiving`&lt;tag&gt;` multiple times. You will see the behaviors are different. one of the received message is `<tag>`

**Comment by xydinesh** [comment]
<tag> xml encoded => &lt;tag&gt;
&lt;tag&gt; xml encoded => &amp;lt;tag&amp;gt;

Therefore these two strings are not the same on server side. I tried on python code, it does receives correct output. No undefined behaviors.

```
import boto3

def main():
    sqs = boto3.resource('sqs', region_name='us-west-2')
    queue = sqs.get_queue_by_name(QueueName='aws-cpp-sdk-queue')
    queue.send_message(MessageBody='&lt;tag&gt;')
    for message in queue.receive_messages():
        print (message.body)
        message.delete()

if __name__ == '__main__':
    main()
```

Output
```
$ for ii in {1..20};do python sdk.py; done                                                                     130 ↵
&lt;tag&gt;
&lt;tag&gt;
...
```

**Comment by singku** [comment]
@xydinesh You are correct. I will tag this as bug and get it fixed soon.

**Comment by wps132230** [comment]
Hi @xydinesh, thank you for catching this issue.
It's fixed in this commit: https://github.com/aws/aws-sdk-cpp/commit/72131ed9529a5ce102fd3c4bf4e521c80d7cf11b
