### ISSUE TITLE
Is it possible to build and install only part of the sdk?

### ISSUE THREAD

**Issue by liuzqt** [aws/aws-sdk-cpp#1201]
Can we specify which part to build? Say, I only use the S3 services, so I suppose `aws-cpp-sdk-core` and `aws-cpp-sdk-s3` plus a few modules should be enough for me. Is it possible to do so?

**Comment by KaibaLopez** [comment]
Hi @liuzqt, yes. you can use the cmake parameter: -DBUILD_ONLY
For example, cmake .. -DBUILD_ONLY= "s3;transfer;polly"
The Readme has a lot more info on this too.
