### ISSUE TITLE
error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug'

### ISSUE THREAD

**Issue by DougSherlock** [aws/aws-sdk-cpp#1203]
### What platform/OS are you using?
Windows 10

### Which version of the SDK?
aws-cpp-sdk-core 1.6.25
aws-cpp-sdk-s3 1.6.20060301.25

### What compiler are you using? what version?
Visual Studio 2017

### What are your CMake arguments?
I used NuGet Package Manager to add the AWS SDK to by project.  

### Can you provide a TRACE level log? (sanitize any sensitive information)
I am linking to the AWS SDK libraries as static LIB files rather than a DLL.  When I try to build the debug version using Visual Studio 2017, I get this linker error:

afxver_.h(77): fatal error C1189: #error:  Please use the /MD switch for _AFXDLL builds

I can prevent the error by changing "Use of MFC" from "Use MFC in a Shared DLL" to "Use MFC in a Static Library".  However, I have many libraries that use the "Shared DLL" setting.  Is there any way around this issue?

Alternatively, is there a way to build a version of the Core and S3 libraries that are compatible with my project settings?
 
![aws-sdk-static-lib-3](https://user-images.githubusercontent.com/32078578/61570501-d4b8fc80-aa41-11e9-823e-5c813fe14328.PNG)

**Comment by singku** [comment]
Hi this is a know issue in the last version of Nuget SDK package. Since we stopped Nuget support, this problem is not going to be solved. You could switch to VCPackage to get latest support.

**Comment by DougSherlock** [comment]
Thanks for letting me know.
