### ISSUE TITLE
AWS command for android sdk build returns: CMake warning: Manually-Specified variables were not used by the project

### ISSUE THREAD

**Issue by EbubeUd** [aws/aws-sdk-cpp#1204]
Hello,
I've been having this issue for quite some time now I need some help as to what might be the issue.

### What platform/OS are you using?
Windows OS

### Which version of the SDK?
GameLift-Cpp-ServerSDK-3.3.0

### What compiler are you using? what version?
 MSVC 19.16.27024.1

### What are your CMake arguments?
cmake -DTARGET_ARCH=ANDROID -DCMAKE_BUILD_TYPE="Release" -DBUILD_ONLY="email;cognito-identity;lambda;core;cognito-idp;identity-management;dynamodb" -DNDK_DIR="C:/NVPACK/android-ndk-r14b/" ..

### Can you provide a TRACE level log? (sanitize any sensitive information)
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.15063.0 to target Windows 10.0.14393.
-- The CXX compiler identification is MSVC 19.16.27024.1
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_ONLY
    NDK_DIR
    TARGET_ARCH

-- Build files have been written to: C:/Users/<Username>/Documents/GameDivision/Libraries/External/GameLift/AndroidBuiltSDK/GameLift-Cpp-ServerSDK-3.3.0/out

**Comment by KaibaLopez** [comment]
Hi @EbubeUd , that's because the Gamelift sdk does not use these options, it doesn't include the build only projects you're adding either so that option is not doing anything, same with the other two. 
For reference the sdk options include : 
BUILD_SHARED_LIBS ON/OFF
GAMELIFT_USE_STD ON/OFF
BUILD_FOR_UNREAL ON/OFF
BUILD_SERVER_SDK ON/OFF
BUILD_EXAMPLE_APP ON/OFF

**Comment by EbubeUd** [comment]
Okay thanks for the clarification. So Just to be sure, do you have an idea if this SDK can be used for building android apps with unreal?
I have tested for PC and it works well.

**Comment by KaibaLopez** [comment]
Yes, it should be doable, kind of embarrassing to say but we do not have any official documentation or examples on how to use it, I'd recommend going through the lumberyard gamedev forums, you'll probably find more answers for gamelift there:
https://gamedev.amazon.com/forums/spaces/122/gamelift.html?topics=GameLift

**Comment by EbubeUd** [comment]
Alright Thanks
