### ISSUE TITLE
cmake exported variable name convention

### ISSUE THREAD

**Issue by wjzhou** [aws/aws-sdk-cpp#1208]
### What platform/OS are you using?
ubuntu 1604

### Which version of the SDK?
1.7.150

### What compiler are you using? what version?
gcc 5.4

### What are your CMake arguments?
N/A

### Can you provide a TRACE level log? (sanitize any sensitive information)
N/A

Could we add alias of the exported cmake variable to follow the existing name convention?

at the end of AWSSDKConfig.cmake add:
```
set(AWSSDK_LIBRARIES, ${AWSSDK_LINK_LIBRARIES})
set(AWSSDK_INCLUDE_DIRS, ${AWSSDK_INCLUDE_DIR})
```

the existing usages to support this name convention:
```
grep 'set.*INCLUDE_DIR' /usr/share/cmake-3.10/Modules -r
grep 'set.*LIBRARIES' /usr/share/cmake-3.10/Modules -r
```

**Comment by wjzhou** [comment]
at least please document this `AWSSDK_LINK_LIBRARIES` somewhere, I know it is in the example repository but can't find this in any of the document.

**Comment by KaibaLopez** [comment]
Hi @wjzhou, this seems like a pretty safe change to make, could you submit it as a PR and link to this issue?
