### ISSUE TITLE
SDK Core build fails on 1.7.156 with errors in STSCredentialsProvider 

### ISSUE THREAD

**Issue by samdbmg** [aws/aws-sdk-cpp#1212]
When trying to build current master (1.7.156) I get a variety of errors along the lines of:
```
In file included from /home/vagrant/aws-sdk-local/aws-sdk-cpp-master/aws-cpp-sdk-core/source/auth/STSCredentialsProvi
der.cpp:17:0:
/home/vagrant/aws-sdk-local/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/auth/STSCredentialsProvider.h:36:9:
error: expected class-name before ‘{’ token
         {
         ^
/home/vagrant/aws-sdk-local/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/auth/STSCredentialsProvider.h:43:28:
 error: ‘Aws::Auth::AWSCredentials Aws::Auth::STSAssumeRoleWebIdentityCredentialsProvider::GetAWSCredentials()’ marke
d ‘override’, but does not override
             AWSCredentials GetAWSCredentials() override;
                            ^~~~~~~~~~~~~~~~~
/home/vagrant/aws-sdk-local/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/auth/STSCredentialsProvider.h:46:18:
 error: ‘void Aws::Auth::STSAssumeRoleWebIdentityCredentialsProvider::Reload()’ marked ‘override’, but does not overr
ide
             void Reload() override;
                  ^~~~~~
```

I took the following steps to get to this point:
```bash
wget https://github.com/aws/aws-sdk-cpp/archive/master.zip
unzip master.zip
mkdir build && cd build
cmake ../aws-sdk-cpp-master/
make
```

See https://gist.github.com/samdbmg/2805be031f1ac0992d145661890cafc7 for full output.

### What platform/OS are you using?
Ubuntu 18.04.2 LTS

### Which version of the SDK?
1.7.156

### What compiler are you using? what version?
GNU 7.4.0

### What are your CMake arguments?
None (following the build instructions in the README)

### Can you provide a TRACE level log? (sanitize any sensitive information)
Not sure on that, but https://gist.github.com/samdbmg/2805be031f1ac0992d145661890cafc7 is the full compiler output if that helps.

**Comment by singku** [comment]
Thanks for pointing out this problem, we are aware of that and have a PR in review. will get it fixed ASAP.

**Comment by marcomagdy** [comment]
meanwhile, you can build the SDK by passing the following CMake switch `-DENABLE_UNITY_BUILD=ON`

**Comment by wps132230** [comment]
Hi, it was fixed in this commit: https://github.com/aws/aws-sdk-cpp/commit/a3bad46fae6fbd962e965a70842014bcda319c6f
