### ISSUE TITLE
CMAKE_INSTALL_LIBDIR isn't passed down to dependencies

### ISSUE THREAD

**Issue by pitrou** [aws/aws-sdk-cpp#1215]
When passing `CMAKE_INSTALL_LIBDIR=lib` to cmake, dependencies (e.g. `aws-c-common`) are still installed to `lib64`.

### What platform/OS are you using?

Ubuntu 18.04

### Which version of the SDK?

1.7.160

### What compiler are you using? what version?

gcc 7.3.0

### What are your CMake arguments?

```
cmake .. -GNinja \
  -DCMAKE_INSTALL_PREFIX="${PREFIX}" \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DBUILD_ONLY='s3;core;transfer;config' \
  -DENABLE_UNITY_BUILD=on \
  -DENABLE_TESTING=off \
  -DCMAKE_BUILD_TYPE=Release
```

**Comment by pitrou** [comment]
The following patch seems to fix the issue:
https://github.com/conda-forge/aws-sdk-cpp-feedstock/blob/c8785c9fe570a6ac68ca01ccdb217243d422f144/recipe/0001-fix-libdir-for-deps.patch

**Comment by KaibaLopez** [comment]
Hi @pitrou ,
In short, if you want the dependencies to not be built in the default folder, use -DBUILD_DEPS=OFF as part of your cmake arguments, you'd have to build the dependencies as separate projects though. There is a section on our read me that goes through doing this:
https://github.com/aws/aws-sdk-cpp#to-build-and-install-third-party-dependencies

This might change in the future, but the idea of building the deps as default even when they are different projects, is to have the sdk build with as little steps as possible, to make it easier for newcomers.
Hope this helps, and let me know if I missed something there.

**Comment by pitrou** [comment]
I think this is missing the point a bit. The C++ SDK is handling the `CMAKE_INSTALL_LIBDIR` variables. The problem is that it's not passing it down to dependencies. It's passing down other variables like `CMAKE_INSTALL_PREFIX`. So why not `CMAKE_INSTALL_LIBDIR` as well?

**Comment by KaibaLopez** [comment]
So, before I try to answer that and maybe get the point wrong again. 
If you add -DBUILD_DEPS=OFF to your cmake arguments, do you get the expected result?

**Comment by pitrou** [comment]
I haven't tried that, as I would then have to build the dependencies myself and pass the right arguments for that. The [code for doing that](https://github.com/aws/aws-sdk-cpp/blob/master/CMakeLists.txt#L122) in CMakeLists.txt doesn't look entirely trivial (though it's probably not complicated).

**Comment by KaibaLopez** [comment]
I'm not sure I quite follow what you mean, you would have to build the dependencies yourself, that is true, but again, we have instructions for that in the Read me and you would not need to change the CMakeLists.txt at all:

https://github.com/aws/aws-sdk-cpp#to-build-and-install-third-party-dependencies

In any case though, you may be right in that the change could be helpful, I'll take a closer look into it.
