### ISSUE TITLE
VC build warning C4834 in aws-cpp-sdk-core/source/internal/AWSHttpResourceClient.cpp

### ISSUE THREAD

**Issue by sunhyung** [aws/aws-sdk-cpp#1216]
### What platform/OS are you using?
Windows 10 Pro 1903

### Which version of the SDK?
10.0.17134.0

### What compiler are you using? what version?
Visual Studio 2019

### What are your CMake arguments?
/W4 /WX /GR- /EHsc /wd4100 /wd4996

### Can you provide a TRACE level log? (sanitize any sensitive information)
D:\3rdParty\aws-sdk-cpp\aws-cpp-sdk-core\source\internal\AWSHttpResourceClient.cpp(302): error C2220: warning treated as error - no 'object' file generated
D:\3rdParty\aws-sdk-cpp\aws-cpp-sdk-core\source\internal\AWSHttpResourceClient.cpp(302): warning C4834: discarding return value of function with 'nodiscard' attribute
  ..\..\..\3rdParty\aws-sdk-cpp\aws-cpp-sdk-core\source\internal\AWSHttpResourceClient.cpp(302): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings

**Comment by sunhyung** [comment]
Single ss.str(); line causes this warning. Is this line needed?

**Comment by KaibaLopez** [comment]
Hi @sunhyung, 
You are correct, this is a mistake and we'll fix it ASAP.

**Comment by KaibaLopez** [comment]
This has been fixed on commit f72974c.
Again, thanks @sunhyung  for pointing it out!
