### ISSUE TITLE
UploadPart return Unable to connect to endpoint error

### ISSUE THREAD

**Issue by NewUser0oo** [aws/aws-sdk-cpp#1217]
I want to upload a local file to s3 with Aws::S3::S3Client::UploadPart, but it return "Unable to connect to endpoint" error.
`
typedef struct
{
	std::string strS3FilePath;
	std::shared_ptr<Aws::IOStream> shpPartContent;
	uint64_t curSize;
	int iPartIndex;
	Aws::S3::Model::CompletedMultipartUpload multipartUpload;
	std::string strUploadId;
}StAwsS3;

StAwsS3* CreateS3(const std::string& strS3FilePath, const std::string& strUploadId)
{
	StAwsS3* p = new StAwsS3();
	p->strS3FilePath = strS3FilePath;
	p->shpPartContent = Aws::MakeShared<Aws::StringStream>(strS3FilePath.c_str(), std::ios_base::in | std::ios_base::binary);
	p->curSize = 0;
	p->iPartIndex = 1;
	p->strUploadId = strUploadId;

	return p;
}

bool UploadPart(StAwsS3& s)
{
	Aws::S3::Model::UploadPartRequest request;
	request.SetBucket(g_strBucketName);
	request.SetKey(s.strS3FilePath.c_str());
	request.SetUploadId(s.strUploadId.c_str());
	request.SetPartNumber(s.iPartIndex);
	
	request.SetContentLength((long long)s.curSize);
	request.SetBody(s.shpPartContent);

	auto outcome = g_pS3Client->UploadPart(request);
	if (!outcome.IsSuccess())
	{
		cout << s.strS3FilePath << ": "
			<< outcome.GetError().GetExceptionName() << " --- "
			<< outcome.GetError().GetMessage();
		return false;
	}

	Aws::S3::Model::CompletedPart part;
	part.SetPartNumber(s.iPartIndex);
	part.SetETag(outcome.GetResult().GetETag());

	s.multipartUpload.AddParts(part);

	(*(Aws::StringStream*)s.shpPartContent.get()).str("");
	s.curSize = 0;	
	s.iPartIndex++;

	return true;
}

unsigned int WriteS3(StAwsS3& s, const char* pBuf, unsigned int nBufLen)
{
	*(Aws::StringStream*)s.shpPartContent.get() << Aws::String(pBuf, (size_t)nBufLen);
	s.curSize += nBufLen;

	if (s.curSize >= g_partSize)
	{
		if (!UploadPart(s))
		{
			return 0;
		}
	}

	return nBufLen;
}

void UploadFile(RsAwsS3& s3)
{
	string strFilePath = "E:\\x10.txt";
	FILE* pFile = fopen(strFilePath.c_str(), "rb");

	if (pFile == NULL)
	{
		cout << "Failed to open " << strFilePath << "\n\n";
		return;
	}

	string strS3FilePath = "tt/te.txt";
	string strUploadId;

	Aws::S3::Model::CreateMultipartUploadRequest request;
	request.SetBucket(g_strBucketName);
	request.SetKey(strS3FilePath .c_str());

	if (outcome.IsSuccess())
	{
		strUploadId = outcome.GetResult().GetUploadId().c_str();
	}
	else
	{
		...
		return;
	}

	auto pS3 = CreateS3(strS3FilePath, strUploadId);

	size_t bufferSize = 16 * 1024;
	char* pBuffer = new char[bufferSize];

	size_t readBytes = fread(pBuffer, 1, bufferSize, pFile);
	size_t writeBytes = 0;

	while (readBytes > 0)
	{
		writeBytes = WriteS3(pS3, pBuffer, readBytes);
		readBytes = fread(pBuffer, 1, bufferSize, pFile);
	}

	fclose(pFile);
	delete[] pBuffer;

	...

}
`

**Comment by KaibaLopez** [comment]
Hi @NewUser0oo, it's a bit hard to get what's happening from just the code.
The most common reason for this error is that you're not connecting to the correct region (the sdk defaults to us-east), try adding something like this to your s3 constructor call.

```
Aws::Client::ClientConfiguration config("default");
config.region = Aws::Region::<THE REGION YOUR S3 IS IN>;
auto s3_client = std::make_shared<Aws::S3::S3Client>(config);
```
if that is not the case for you, can you show me a sanitized log trace to see what's happening?

To activate the logs:
```
Aws::SDKOptions options;
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
```

**Comment by NewUser0oo** [comment]
Hi @KaibaLopez , I  make sure that the region is correct, because I can remove file by sdk.
[aws_sdk_2019-08-15-02.log](https://github.com/aws/aws-sdk-cpp/files/3504089/aws_sdk_2019-08-15-02.log)

**Comment by KaibaLopez** [comment]
Alright, thanks for the log, I'll look into this.
In the mean time, as a work around, I'd recommend trying to do the upload with transfer manager.

**Comment by NewUser0oo** [comment]
Hi @KaibaLopez , I had solved this problem. 
`p->shpPartContent = Aws::MakeSharedAws::StringStream(strS3FilePath.c_str());`
It works.
Thank you.

**Comment by singku** [comment]
I don't get why above code is connected to the unable to connect to endpoint error
