### ISSUE TITLE
Bug in method CreateDirectoryIfNotExists on Windows

### ISSUE THREAD

**Issue by haoxi911** [aws/aws-sdk-cpp#1218]
### What platform/OS are you using?
Windows 10

### Which version of the SDK?
1.7.162

### What compiler are you using? what version?
Visual Studio 2017 (v141_xp)

### Details
The related code is in file `aws-cpp-sdk-core/source/platform/windows/FileSystem.cpp`, and it is a pretty edge case in my opinion.

Normally, when we recursively create a folder using this method, we would do something like `CreateDirectoryIfNotExists("C:\\xxx\\xxx", true);` and it works well.

The problem happens when we do the same on an **external flash drive**, let's say you have a flash drive mounted to volume "D:", now if you create a folder on this drive with `CreateDirectoryIfNotExists("D:\\xxx\\xxx", true);`, it will fail.

The reason of the failure is related to the Windows API `CreateDirectoryW`. When you use it with path `C:\\` it will report an error code ERROR_ALREADY_EXISTS, but if you use it with an external drive like `D:\\`, the system will report another error ERROR_ACCESS_DENIED.

As a workaround, I am just using `std::filesystem::create_directories()` to get rid of it.

**Comment by KaibaLopez** [comment]
Hi @haoxi911 , thanks for pointing this up.

It does seem like the error is a valid one, so I don't think it's a bug. It properly returns the error code for folders where I don't have permissions to modify and I can't find anything on the function documentation regarding limitations on external drives.
So in your case it may be related to external things like your windows firewall, administrator privileges or, although unlikely, an undocumented function limitation.

And about using std::filesystem::create_directories(), I don't think we could apply this change as it breaks on access denied and quietly fails on the already exist failure. Also, and probably more importantly, it requires C++17, and so it would be a breaking change to make.

For the moment, glad to hear you got a work around that worked for you and again thanks for sharing it.

**Comment by haoxi911** [comment]
@KaibaLopez Yea, I agree with you, I would mention it here so that if someone searches it in the issues, they can find an explanation and potentially apply the same workaround as I did. I am using some macros, it is not standard:
