### ISSUE TITLE
Objects with "=" in name cause 403 error on some providers.

### ISSUE THREAD

**Issue by gboggs** [aws/aws-sdk-cpp#1224]
### What platform/OS are you using?
x86_64 Linux SLES12.3 Linux/4.4.114-94.11-default

### Which version of the SDK?
aws-sdk-cpp/1.7.29

### What compiler are you using? what version?
gcc version 4.8.5 (SUSE Linux)

### What are your CMake arguments?
 -DBUILD_ONLY="core;s3" -DCMAKE_BUILD_TYPE=RelWithDebInfo

### Can you provide a TRACE level log? (sanitize any sensitive information)
Yes, if needed.

We have an application that needs to work with various S3 providers and are encountering a problem with the C++ SDK  when trying to GET objects that have "=" in their names (and other special chars as well, but "=" is the one we're worried about). Apparently, some applications like Spark generate objects with such names so simply renaming the objects is not a good solution for us.

The problem is that GetObject() will fail with a 403/SignatureDoesNotMatch on some S3 providers but work on others when trying to retrieve these objects. For a simple test case, create a bucket named "foo" and upload an object named "foo=foo", then try to GET it with GetObjectRequest().

This will work just fine on real Amazon S3 and Minio, but will fail with a 403/SignatureDoesNotMatch  error on Ceph, Google and Dell ECS. 

s3cmd will retrieve the objects on all of these platforms.  Looking at TCP dump output, it appears that the SDK does not escape the "=" in the path whereas s3cmd does.

SDK: GET /foo=foo HTTP/1.1
s3cmd: GET /foo%3Dfoo HTTP/1.1

So, what goes over the wire is not escaped, yet the string used for the signature is. The Canonical Request String is:
[DEBUG] 2019-08-23 21:41:28 AWSAuthV4Signer [139824467363648] Canonical Request String: GET
/foo%3Dfoo

But,  what gets to Curl is this:
[TRACE] 2019-08-23 21:41:28 CurlHttpClient [139824467363648] Making request to https://xxxx-foo-1.ceph-s3.xxxxxxxxx.com/foo=foo

This apparently bothers some S3 implementations and not others. I've tried various things to get around this including pre-escaping the object key before passing it to the GetObjectRequest and changing the urlEscapePath parameter to true where S3Client::S3Client() calls the AWSAuthV4Signer constructor. These things end up with the "=" being double escaped (i.e. %253D when we only wanted %3D) and it still fails.

I've found one thing that **DOES** work. I'm not suggesting that this is the fix, but it does seem to give the desired behavior, at least for this test case. In URI::GetURIString(), m_path is escaped using URLEncodePathRFC3986() which explicitly checks for and does not percent encode the "=". If this call is replaced with a similar one that does escape the "=" (and only done here. URLEncodePathRFC3986() is called in a few places), the resulting URL becomes this:

[TRACE] 2019-08-23 22:29:33 CurlHttpClient [139976436225856] Making request to https://xxxx-foo-1.ceph-s3.xxxxxxxxx.com/foo%3Dfoo

With the same Canonical request string:
[DEBUG] 2019-08-23 22:29:33 AWSAuthV4Signer [139976436225856] Canonical Request String: GET
/foo%3Dfoo

This works OK on all of the providers mentioned above. I'm hoping I've missed something obvious and there's a better solution.

**Comment by SergeyRyabinin** [comment]
Hi @pitrou ,
You are right it is a long issue, but we had one contribution since then to support this thing recently:
https://github.com/aws/aws-sdk-cpp/blob/e3af2394b8c561a226a4f82b02a4f487009e130a/aws-cpp-sdk-core/source/http/URI.cpp#L33

There is a global variable now that could be set to switch how segments in the query path are encoded.

Best regards

**Comment by pitrou** [comment]
@SergeyRyabinin This seems to have fixed the issue for us. Thank you very much!
