### ISSUE TITLE
AWSAuthSigner.cpp error: ‘<anonymous>.Aws::Utils::Event::EventHeaderValue::m_eventHeaderStaticValue’ may be used uninitialized in this function [-Werror=maybe-uninitialized]  

### ISSUE THREAD

**Issue by smeadows53** [aws/aws-sdk-cpp#1228]
### What platform/OS are you using?
Clear Linux

### Which version of the SDK?
1.7.171

### What compiler are you using? what version?
hcc (Clear Linux OS for Intel Architecture) 9.2.1 20190826 gcc-9-branch@274921
cmake version 3.15.2

### What are your CMake arguments?
-D CMAKE_BUILD_TYPE=Debug -D TARGET_ARCH=LINUX

### Can you provide a TRACE level log? (sanitize any sensitive information)
[Trace.log](https://github.com/aws/aws-sdk-cpp/files/3549167/Trace.log)

**Comment by Bu11etmagnet** [comment]
I believe gcc 9.2.1 is newer than gcc 4.8

**Comment by smeadows53** [comment]
I reverted back to gcc 7.4.0, apparently your c++ SDK won't compile 
under gcc version 9.2.1

**Comment by KaibaLopez** [comment]
@Bu11etmagnet ok yeah that was on me, I meant to say to sync up gcc and g++, you could have 9.2 gcc but a different g++ and if g++ is not above 4.8 then this error is known to happen. Are you also facing this issue by the way?

The sdk should compile under 9.x gcc so I'll keep the issue open while I try to reproduce it, 9.1 runs with no issues and I don't think the changes done for 9.2 would break the sdk, but won't know until I try.

**Comment by ayeganov** [comment]
@KaibaLopez This bug is still alive, well and kicking for gcc 10.3.0.

**Comment by KaibaLopez** [comment]
@ayeganov 
 Can you open a new issue with the details on what you are seeing? It'll be a lot easier for me to track it that way.
