### ISSUE TITLE
VS2019 linker error

### ISSUE THREAD

**Issue by MajorMurphy** [aws/aws-sdk-cpp#1229]
In Visual Studio 2019 (v16.2.2), create a new Console Application. (SDK 10.0.18362.0)
Add Nuget package AWSSDKCPP-STS and dependencies.  
Instantiating an object:

```
#include <aws/sts/STSClient.h>

int main()
{
    Aws::Client::ClientConfiguration clientConfig;
}
```
Then yields linker errors:

> 1>------ Build started: Project: ConsoleApplication1, Configuration: Debug x64 ------
> 1>ConsoleApplication1.cpp
> 1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl Aws::Client::ClientConfiguration::ClientConfiguration(void)" (__imp_??0ClientConfiguration@Client@Aws@@QEAA@XZ) referenced in function main
> 1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl Aws::Client::ClientConfiguration::~ClientConfiguration(void)" (__imp_??1ClientConfiguration@Client@Aws@@QEAA@XZ) referenced in function main
> 1>C:\Users\major\temp\ConsoleApplication1\x64\Debug\ConsoleApplication1.exe : fatal error LNK1120: 2 unresolved externals
> 1>Done building project "ConsoleApplication1.vcxproj" -- FAILED.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
> 

The same steps in VS2015 (14.0.25431.01 Update 3) will compile with no linker errors.

I have not tested VS2017.

Back in VS2019, linking against AWS libraries created using Cmake/msbuild also fails with error LNK2019.

Preprocessor definitions USE_IMPORT_EXPORT and USE_WINDOWS_DLL_SEMANTICS have not resolved the issue.

**Comment by KaibaLopez** [comment]
Hi @MajorMurphy, we don't really support Nuget anymore.
We recommend building the sdk from source, we have instructions for that in the Readme, and you can find more info on #1154 

I've tested this on VS2019 too so it should work just fine, but let me know if you have troubles with it.
