### ISSUE TITLE
Send email with attachments through SES SDK

### ISSUE THREAD

**Issue by ludekvodicka** [aws/aws-sdk-cpp#1237]
### What platform/OS are you using?
Windows 10

### Which version of the SDK?
1,7,182

### What compiler are you using? what version?
Visual Studio 2019 16.2.4

Is there a way how to send an attachment through c++ SDK  ?

I believe I checked all examples (https://docs.aws.amazon.com/code-samples/latest/catalog/code-catalog-cpp-example_code-ses.html) and google links but I didn't find any mention about attachments in c++.

I believe there has to be a way but there is no any MultiPart/Mime class in the source.

Thanks.

**Comment by singku** [comment]
You are right, there is no MIME/MultiPart class defined natively in C++. You will have to use the SendRawEmail API and construct the RawMessage by yourself (or 3rd-party library) at this stage.
Java SDK example: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-raw.html
