### ISSUE TITLE
Preserving an Aws::IOStream even after it goes out of scope

### ISSUE THREAD

**Issue by ToshalGhimire** [aws/aws-sdk-cpp#1238]
### What platform/OS are you using?
Windows
### Which version of the SDK?
AWS SDK for C++ 1.7.182

I am following this example for downloading object. https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/examples-s3-objects.html

I am trying to return a Aws:IOStream object from a function that takes in the bucket and object key. when i return it, it gets destroyed after it goes out of scope and I no longer can use it. I need this stream object to be passed around within functions and classes. Is there anyway this can be achieved ?

**Comment by KaibaLopez** [comment]
Hi @ToshalGhimire, 
Sorry but, unless I'm missing something, this is not really an issue with the sdk you're having, but a general c++ programing issue, so I'll be closing it.
There is a lot of ways to keep the IOStream in scope, from assigning the result to a variable with greater scope to saving the downloaded object to a file and reading from it later... this is kind of for you to decide depending on your implementation.

**Comment by ToshalGhimire** [comment]
Hi @KaibaLopez , It is not a general c++ question. When assigning it to a variable with a greater scope, the stream cannot be be used anymore. You get a read action violation error at run time. As for your other comment, our files can be very large and some end up being multiple gigs. Its not ideal for us to write it to a file. We need the stream object.

**Comment by KaibaLopez** [comment]
My Bad @ToshalGhimire, I misunderstood the issue. 
Can you show me a code snippet of what you're trying to do then? There should not be a problem accessing the IOStream.

**Comment by ToshalGhimire** [comment]
My function looks somthing like this 

```
Aws::IOStream& getObjectOutcome(const string bucket_name, const string object_name){
    Aws::S3::S3Client s3_client;
    Aws::S3::Model::GetObjectRequest request;
    request.SetBucket(bucket_name);
    request.SetKey(object_name);

    // Get the object
    auto outcome= s3_client.GetObject(request);
    if (!outcome.IsSuccess())
    {
        // Handle Errors
    }
    else
    {
        return outcome.GetResultWithOwnership().GetBody();
    }
}
```
and somewhere else in my code we have 
`
Aws::IOStream & stream = getObjectOutcome("bucket01","test.txt")
 `
We want to be able to pass around the stream object through different classes and functions . but it becomes unreadable when the getObjectOutcome function scope ends.

**Comment by singku** [comment]
While you can call GetResultWithOwnership() to own the result in the scope, but when returned from the scope, the result's lifetime ends, so as the associated IOStream body. Why don't you return the result with ownership?

**Comment by fschuetz04** [comment]
I would expect that the following method can be used to return the `GetObjectResult` with ownership:

```c++
Aws::S3::Model::GetObjectResult &&S3::get(std::string key) {
  Aws::S3::Model::GetObjectRequest request;
  request.SetBucket(bucket_);
  request.SetKey(key);

  auto outcome = client_.GetObject(request);
  if (!outcome.IsSuccess()) {
    throw std::runtime_error(outcome.GetError().GetMessage());
  }

  return outcome.GetResultWithOwnership();
}
```

However, using this method leads to a segmentation fault caused in the move constructor of `GetObjectResult`. What is wrong with this method?
