### ISSUE TITLE
ec2 RunInstances error

### ISSUE THREAD

**Issue by jiephe** [aws/aws-sdk-cpp#1239]
### What platform/OS are you using?
aws ubuntu
### Which version of the SDK?
0dad0a2f
### What compiler are you using? what version?
gcc 4.8.5
### Can you provide a TRACE level log? (sanitize any sensitive information)

when call, fail and error code : "Unable to connect to endpoint with address **"

when i call api from a machine not in aws, it is successful, but when i call this api from an aws linux instance it fail, and error code like up.

**Comment by KaibaLopez** [comment]
Hi @jiephe, can you provide a sanitized trace log? and if possible, a code snippet of what you're trying to do would also help me identify the problem.

**Comment by jiephe** [comment]
`		Aws::Auth::AWSCredentials credentials(key.c_str(), secret.c_str());
		
		Aws::Client::ClientConfiguration config;
		config.verifySSL = false;
		ec2_client_.reset(new Aws::EC2::EC2Client(credentials, config));`

if i do not set config.verifySSL  to false, it is ok from outside aws ec2 instance, only when config.verifySSL is false it is ok inside aws ec2 instance. and code is like this:
`		std::string ecs_region_tag;
		
		uint32_t type = atoi(instance_type.c_str());
		
		Aws::EC2::Model::RunInstancesRequest rir;
		rir.SetImageId(image_id.c_str());
		rir.SetInstanceType((Aws::EC2::Model::InstanceType)type);
		rir.SetMinCount(1);
		rir.SetMaxCount(1);
		rir.SetSubnetId(sub_net_id.c_str());
		rir.AddSecurityGroupIds(security_group_id.c_str());
		if (!user_data.empty())
		{
			CMMUtils::uuid(ecs_region_tag);
			std::string last_user_data = user_data;
			last_user_data = CMMUtils::m_replace(last_user_data, MACRO_REGION_TAG, ecs_region_tag);
			last_user_data = CMMUtils::m_replace(last_user_data, MACRO_PASSWD, passwd);
			last_user_data = CMMUtils::m_replace(last_user_data, MACRO_APP_ID, app_id);
			last_user_data = CMMUtils::m_replace(last_user_data, MACRO_SERVER_VERSION, server_version);

			LOG_INFO("{}, run_instance user_data: {} ", Log_Packet, last_user_data);

			Base64 b64;
			std::string base64_user_data = b64.Encode((unsigned char*)last_user_data.c_str(), last_user_data.size());
			rir.SetUserData(base64_user_data.c_str());
		}
		auto run_outcome = ec2_client_->RunInstances(rir);
		if (!run_outcome.IsSuccess())
		{
			LOG_ERROR("Failed to run ec2 instance based on ami: {}  error:{}", image_id, run_outcome.GetError().GetMessage().c_str());
			return false;
		}`

**Comment by singku** [comment]
>It works outside of ec2 instance when `verifySsl` is set to true.
>Within ec2 instance,  it works when `verifySsl` is set to false.

It's most probably that ec2's built-in curl doesn't know the pki path ssl library on that ec2 uses.
You can solve this by specify `conf.caFile = "/etc/pki/tls/certs/ca-bundle.crt";`

**Comment by jiephe** [comment]
@singku Thanks so much! it works. but if i use with verifySsl=false, Is there any risk?

**Comment by singku** [comment]
Potentially `man in the middle` attack if you don't verify ssl endpoint. https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html

**Comment by jiephe** [comment]
@singku ok i got it. thansk!
