### ISSUE TITLE
homebrew formula

### ISSUE THREAD

**Issue by jacob-meacham** [aws/aws-sdk-cpp#124]
It would be great if this was installable via homebrew on os x. I have an initial formula in my tap here:

https://github.com/jacob-meacham/homebrew-formulae/blob/master/lib-aws-sdk.rb

**Comment by zwass** [comment]
I was also in need of this, so I updated your formula to match the guidelines and submitted a pull request. Thanks for your work!

https://github.com/Homebrew/homebrew/pull/50360

**Comment by jacob-meacham** [comment]
@zwass thanks!

**Comment by JonathanHenson** [comment]
I get the impression this has been fixed. Please reopen if issue persists.
