### ISSUE TITLE
FormattedLogSystem change, now requires 'Flush'?

### ISSUE THREAD

**Issue by dtzWill** [aws/aws-sdk-cpp#1240]
[FormattedLogSystem is suggested for custom loggers](https://github.com/aws/aws-sdk-cpp/blob/0912003eae920b53661ef6287b7b97d16a507b67/aws-cpp-sdk-core/include/aws/core/utils/logging/LogSystemInterface.h#L32) which for quite some time has only required overriding ProcessFormattedStream.  However, after https://github.com/aws/aws-sdk-cpp/commit/4d92ec7ab6daa0cb15efee04ba40800a0d9e9a65 custom loggers must also implement a `Flush()` method, and only do so when using certain patch versions (>= 151) of aws-sdk-cpp.

This isn't a big deal but doesn't seem necessarily intentional and a bit surprising (is `Flush` used by anything within aws-sdk-cpp?)l, and such a change breaks code using aws-sdk-cpp-- unexpected for a patch-level update (but I'm not sure what the policy for versioning is here...).

The last concern is of course what brought my attention to the issue, and isn't just theoretical :).

**Comment by singku** [comment]
Our policy of letting breaking changes is minor version bump. But this was an unfortunate slip through that we didn't catch during code review. Luckily we have realized that and are improving our internal code review/PR process. Thanks for bring this up, but it's already here and couldn't be undone.
