### ISSUE TITLE
Shared libraries are not getting generated..

### ISSUE THREAD

**Issue by sakthisg** [aws/aws-sdk-cpp#1246]
### What platform/OS are you using?
Linux Cross compilation - arm-linux-gnueabihf
### Which version of the SDK?
1.7.190
### What compiler are you using? what version?
 - arm-linux-gnueabihf - 6.6.1
### What are your CMake arguments?
cmake ../aws-sdk-cpp -DCMAKE_TOOLCHAIN_FILE=../aws-sdk-cpp/ToolchainFile.cmake  -DBUILD_ONLY="lambda" -DCMAKE_PREFIX_PATH=/mvoiceapp/avs/alexa/prebuilts -DBUILD_SHARED_LIBS=ON

### Can you provide a TRACE level log? (sanitize any sensitive information)
 Installing: /usr/local/bin/libaws-cpp-sdk-kinesis.a

**Comment by KaibaLopez** [comment]
Hi @sakthisg, 
Can you provide the error you are getting?

**Comment by singku** [comment]
You only build lambda by specifying `-DBUILD_ONLY="lambda"`, it's not a surprise that `kinesis` is not installed.

**Comment by sakthisg** [comment]
Correct, It is building all .a libraries. I need to build only .so for
Lambda..Is there anything wrong in the cmake command?

**Comment by KaibaLopez** [comment]
@sakthisg, unless you specifically set "-DBUILD_SHARED_LIBS=OFF" the libs generated should be ".so" by default (on linux).
The only thing I can think that may cause this the cmake cache, could you try deleting it and re running your cmake and make command?

**Comment by sakthisg** [comment]
Yes, that is what i have learnt from the documentation.  I have deleted the
cmake cache, build folder. Running the cmake and make. Still i face the
same issue. (only static libraries are generated)

**Comment by KaibaLopez** [comment]
@sakthisg , could you check the `../aws-sdk-cpp/ToolchainFile.cmake` and see if you're not setting a flag for shared libraries?
Or to make sure that the problem is not part of the sdk, can you try building without that argument?

**Comment by singku** [comment]
I am confused by 
### Can you provide a TRACE level log? (sanitize any sensitive information)
Installing: /usr/local/bin/libaws-cpp-sdk-kinesis.a

Why do you need that toolchain file?
Can you please just try `cmake ../aws-sdk-cpp -DBUILD_ONLY="lambda" -DBUILD_SHARED_LIBS=ON`

**Comment by sakthisg** [comment]
As I need to cross compile so i am using the tool chain file. And i am not setting the shared libraries flag in  ../aws-sdk-cpp/ToolchainFile.cmake!

**Comment by singku** [comment]
It's helpful to post your CMake output when cross-compiling SDK

**Comment by sakthisg** [comment]
[CMakeOutput.log](https://github.com/aws/aws-sdk-cpp/files/3715852/CMakeOutput.log)
Please find the attached file CMakeOutput.log

**Comment by singku** [comment]
I didn't see anything related to CPP SDK in your output log.
