### ISSUE TITLE
Homebrew upgrade (v1.7.180 -> v1.7.190) failed

### ISSUE THREAD

**Issue by chenrui333** [aws/aws-sdk-cpp#1247]
### What platform/OS are you using?

MacOS

### Which version of the SDK?

v1.7.190

### What compiler are you using? what version?

Build log: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/48818/version=mojave/console

```
16:37:23 Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
16:37:23 Clang: 10.0 build 1001
16:37:23 Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
16:37:23 Curl: 7.54.0 => /usr/bin/curl
16:37:23 Java: 13, 1.8.0_222
16:37:23 macOS: 10.14.6-x86_64
16:37:23 CLT: 10.3.0.0.1.1562985497
16:37:23 Xcode: 11.0
16:37:23 CLT headers: 10.3.0.0.1.1562985497
16:37:23 Error: aws-sdk-cpp 1.7.190 did not build
16:37:23 XQuartz: 2.7.11 => /opt/X11
```

### What are your CMake arguments?

16:37:23 ==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/aws-sdk-cpp/1.7.190 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev

### Can you provide a TRACE level log? (sanitize any sensitive information)

Build log: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/48818/version=mojave/console

Relates to https://github.com/Homebrew/homebrew-core/pull/44682

**Comment by singku** [comment]
It doesn't look like a problem in CPP SDK, but a problem on your system, where c++11 related headers are messed up.  And I can't reproduce your problem on my Mac with the same Cmake arguments.
Did you by any chance update your command line tools/Xcode on your Mac build host?
You'd probably need to reinstall it.

Similar problem: https://github.com/PointCloudLibrary/pcl/issues/2601
https://github.com/PointCloudLibrary/pcl/issues/2750
https://stackoverflow.com/questions/47018913/make-fails-on-mac

**Comment by chenrui333** [comment]
I see, thanks!
