### ISSUE TITLE
CMake Error - Cannot find source file aws-sdk-cpp/aws-cpp-sdk-cloudformation/include/aws/cloudformation/model/ListChangeSetsResult.h

### ISSUE THREAD

**Issue by LazzariPaolo** [aws/aws-sdk-cpp#1248]
### What platform/OS are you using?
Windows 10.

### Which version of the SDK?
I am building AWS SDK 1.7.157.

### What compiler are you using? what version?
Compiler is:

_C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe_

### What are your CMake arguments?

> -D BUILD_ONLY:STRING="transfer;batch;iam;cloudformation;logs;sts" -D CUSTOM_MEMORY_MANAGEMENT=0 -D CMAKE_PREFIX_PATH="S:/paolol/aws-c-common/;S:/paolol/aws-checksums/;S:/paolol/aws-c-event-stream/" -D BUILD_DEPS=OFF -D CMAKE_VERBOSE_MAKEFILE="1"

### Can you provide a TRACE level log? (sanitize any sensitive information)
The end of the stack trace:

> -- Looking for pthread.h
> -- Looking for pthread.h - not found
> -- Found Threads: TRUE
> -- Configuring done
> CMake Error at aws-cpp-sdk-cloudformation/CMakeLists.txt:52 (add_library):
>   Cannot find source file:
> 
>     S:/paolol/aws-sdk-cpp/aws-cpp-sdk-cloudformation/include/aws/cloudformation/model/ListChangeSetsResult.h
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
>   .hxx .in .txx
> 
> 
> CMake Error: CMake can not determine linker language for target: aws-cpp-sdk-cloudformation
> CMake Error: CMake can not determine linker language for target: aws-cpp-sdk-cloudformation
> CMake Error in aws-cpp-sdk-cloudformation/CMakeLists.txt:
>   Exporting the target "aws-cpp-sdk-cloudformation" is not allowed since its
>   linker language cannot be determined
> 
> 
> CMake Error: CMake can not determine linker language for target: aws-cpp-sdk-cloudformation
> CMake Error in aws-cpp-sdk-cloudformation/CMakeLists.txt:
>   Exporting the target "aws-cpp-sdk-cloudformation" is not allowed since its
>   linker language cannot be determined
> 
> 
> CMake Error: CMake can not determine linker language for target: aws-cpp-sdk-cloudformation
> CMake Error in aws-cpp-sdk-cloudformation/CMakeLists.txt:
>   Exporting the target "aws-cpp-sdk-cloudformation" is not allowed since its
>   linker language cannot be determined
> 
> 
> CMake Error: CMake can not determine linker language for target: aws-cpp-sdk-cloudformation
> CMake Error in aws-cpp-sdk-cloudformation/CMakeLists.txt:
>   Exporting the target "aws-cpp-sdk-cloudformation" is not allowed since its
>   linker language cannot be determined
> 
> 
> CMake Error: CMake can not determine linker language for target: aws-cpp-sdk-cloudformation
> CMake Error in aws-cpp-sdk-cloudformation/CMakeLists.txt:
>   Exporting the target "aws-cpp-sdk-cloudformation" is not allowed since its
>   linker language cannot be determined
> 
> 
> CMake Error: CMake can not determine linker language for target: aws-cpp-sdk-cloudformation
> CMake Error in aws-cpp-sdk-cloudformation/CMakeLists.txt:
>   Exporting the target "aws-cpp-sdk-cloudformation" is not allowed since its
>   linker language cannot be determined

Any suggestions? The header file and source file are present in the correct directories.

**Comment by KaibaLopez** [comment]
Hi @LazzariPaolo, I've ran the same cmake parameters on windows 10 and I can't reproduce your error, are you sure that you are pointing to the correct directory? 
Can you try building one service at a time and see if you are having problems specifically with cloudformation or are all of them giving you the same problem?

**Comment by LazzariPaolo** [comment]
Hi @KaibaLopez . Doesn't seem related to be related to which service I am building, it fails for other ones which don't include cloudformation too. What compiler did you use? Are you using **devenv** or msbuild?

**Comment by KaibaLopez** [comment]
I used msbuild, but if I'm not mistaken you're facing this error from cmake, so msbuild or devenv shouldn't even be part of it yet.

The only things I can think of that may cause this error are: 
Changing the CMakeLists.txt file line:
```
# build the sdk targets
project("aws-cpp-sdk-all" VERSION "${PROJECT_VERSION}" LANGUAGES CXX)
```
Or something is weird about your environment, like you didn't install the C++ Redistributable or it's in some unexpected location, or you have a very old cmake version (below 3.3).

Could you provide a text file with the cmake output?

**Comment by LazzariPaolo** [comment]
@KaibaLopez What should that line be changed to? That's what it is right now.
 I have C++ redistributable installed and I am using cmake 3.10.

I am attaching the file with the cmake output. 
[cmake_error.txt](https://github.com/aws/aws-sdk-cpp/files/3691099/cmake_error.txt)

**Comment by KaibaLopez** [comment]
So from your log it looks like your cmake is generating the sln correctly, but you're getting an error building it with gmake which, I might be wrong here but, I think is for linux environments? 
Kind of shooting in the dark for me at this point since I haven't been able to reproduce your error but could you try using msbuild from the build folder:
`msbuild INSTALL.vcxproj`
or opening AWSSDK.sln on visual studio and building from there?

**Comment by LazzariPaolo** [comment]
@KaibaLopez  Thank you for your help. It does seem like devenv is erroring. In particular, it is the aws-cpp-sdk-core-test which is failing: https://github.com/aws/aws-sdk-cpp/issues/1254
