### ISSUE TITLE
S3:PutObject with no key is mis-interpreted as PutBucket

### ISSUE THREAD

**Issue by prestomation** [aws/aws-sdk-cpp#125]
This is really minor, but if you do not set the key on a PutObject request, it is the same URI as a PutBucket request (bucketname.s3.amazonaws.com/)

The most likely result is a MalformedXML exception which may be difficult for some people to debug. Should the S3 model be modified to mark key as required on this operation?

**Comment by Bu11etmagnet** [comment]
Same thing would happen with GetObject if the key is empty (it would look like a ListBucket to AWS).
This happens because the URI,  the bucket and the key are simply concatenated without checking.
Maybe the SDK should fail with "invalid argument" if the key is empty.

**Comment by bretambrose** [comment]
I've added an issue to investigate this into our backlog.

**Comment by singku** [comment]
https://github.com/aws/aws-sdk-cpp/commit/fad59fe4037d659b858c9dafe9022144130eccb1
