### ISSUE TITLE
S3 Unable to upload files > 2 MB : Unable to connect to endpoint

### ISSUE THREAD

**Issue by Fimactif** [aws/aws-sdk-cpp#1250]
### What platform/OS are you using?
I'm using Microsoft Windows 10 Home Version 10.0.18362 Build 18362
### Which version of the SDK?
I'm using SDK version 1.7.185
### What compiler are you using? what version?
Visual studio 16( 2019 ), configured through Cmake-gui 3.15.3
### What are your CMake arguments?
I used the default arguments
### Can you provide a TRACE level log? (sanitize any sensitive information)
[aws_sdk_2019-10-01-20.log](https://github.com/aws/aws-sdk-cpp/files/3678442/aws_sdk_2019-10-01-20.log)

The most important section is 
[ERROR] 2019-10-01 20:31:46.144 WinHttpSyncHttpClient [80 340] Failed to add HTTP request headers with error code: 87
[WARN] 2019-10-01 20:31:46.256 WinHttpSyncHttpClient [80 340] Send request failed: .*CONTENT OF FILE=<6ø*
[DEBUG] 2019-10-01 20:31:46.256 WinHttpSyncHttpClient [80 340] Closing http request handle 0 000 020 AF7 CBB 0D0
[DEBUG] 2019-10-01 20:31:46.256 WinHttpSyncHttpClient [80 340] Releasing connection handle 0 000 020 A9B 22C 240
[DEBUG] 2019-10-01 20:31:46.256 WinHttpConnectionPoolMgr [80 340] Releasing connection to endpoint BUCKET_NAME.s3.REGION_CODE.amazonaws.com:443
[DEBUG] 2019-10-01 20:31:46.256 AWSClient [80 340] Request returned error. Attempting to generate appropriate error codes from response
[ERROR] 2019-10-01 20:31:46.256 AWSClient [80 340] HTTP response code: -1
Exception name: 
Error message: Unable to connect to endpoint
0 response headers:

There is an error code 87. This does not happen if my file is tiny (like 40 kb) which does upload successfully. 

### code ### 
Aws::SDKOptions options;
Aws::InitAPI( options );
{
	Aws::Utils::Logging::InitializeAWSLogging(
	Aws::MakeShared<Aws::Utils::Logging::DefaultLogSystem>(
	        "RunUnitTests", Aws::Utils::Logging::LogLevel::Trace, OUTPUT_FILE ) );

	Aws::Auth::AWSCredentials clCredentials;
       // If region is specified, use it
	Aws::Client::ClientConfiguration clientConfig;
	clientConfig.scheme = Aws::Http::Scheme::HTTPS;
	clientConfig.connectTimeoutMs = 30000;
	clientConfig.requestTimeoutMs = 600000;
       clientConfig.region = REGION_CODE;
	clCredentials.SetAWSAccessKeyId( ACCESS_KEY_ID );
	clCredentials.SetAWSSecretKey( SECRET_ACCESS_KEY );
	Aws::S3::S3Client clS3Client( clCredentials, clientConfig ,Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Always );
	std::ifstream file( sFileName, std::ios::binary );
	std::streampos fSize = file.tellg();
	file.seekg( 0, std::ios::end );
	fSize = file.tellg() - fSize;
	file.close();

	Aws::S3::Model::PutObjectRequest object_request;

	object_request.SetBucket( BUCKET_NAME );
	object_request.SetKey( ("Anything_really")  );
	const std::shared_ptr<Aws::IOStream> input_data =
	Aws::MakeShared<Aws::FStream>( "AllocationSampleTag",
		sFileName.c_str(),
		std::ios_base::in | std::ios_base::binary  );
	object_request.SetBody( input_data );
	object_request.SetContentType( "text/plain" );
	object_request.SetContentLength( static_cast<long>( fSize ) );

	// Put the object
	auto put_object_outcome = clS3Client.PutObject( object_request );
	if (!put_object_outcome.IsSuccess()) {
		auto error = put_object_outcome.GetError();
                cout << error.GetMessage();
	}
	else
	{  cout<<"Success"; }
	Aws::Utils::Logging::ShutdownAWSLogging();
}
Aws::ShutdownAPI( options );

I did check some similaire issue around and tried the different solution (like requestTimeoutMs = 600000 or computing the size "manually") . Still doesn't work out!

Any advice / hint will be greatly appreciated

**Comment by KaibaLopez** [comment]
Hi @Fimactif, I'm not able to reproduce your error, even with the exact code you provided I can upload an image of more than 3mb, no problem.
Error 87 is [marked](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-) as ERROR_INVALID_PARAMETER.
And the "cannot connect to endpoint" is kind of generic when WinHttpSyncHttpClient fails.
Could you check that you have no firewall setting that could avoid you from making this kind of connection?

**Comment by Fimactif** [comment]
@KaibaLopez Turned off the firewall and same issue... I did however create a standalone simple project just to test the code I provided like you did and it does indeed upload just fine.  I will investigate further my original project (a DLL) in which the code doesn't work properly to pinpoint why it is not working. Do you know if there is an compiling options / flag which would hinder the upload process?

**Comment by KaibaLopez** [comment]
Can't really think on anything that would cause this error.
I'd recommend you to look into transfer manager too, not that it'd solve this issue in particular, but it might be worth it if you're thinking of doing large uploads.
I'll close the issue for the moment, since there doesn't seem to be a problem with the sdk, but feel free to comment further, I'll keep an eye on the issue, and reopen if there is anything else you need.

**Comment by Fimactif** [comment]
After some research , I finally isolated the source of my problems.  Just add the following line before the initialize of the API 
std::locale clUnused = std::locale::global( std::locale( "en" ) );

I didn't find any information about locale / localization with the SDK on the documentation
I tried to imbue the default locale to the streams from my file.

		std::ifstream file( sFilename, std::ios::binary );
		std::locale unused = file.imbue( std::locale::classic() );
		const std::shared_ptr<Aws::IOStream> input_data =
			Aws::MakeShared<Aws::FStream>( "AllocationSampleTag",
				sFilename.c_str(),
				std::ios_base::in | std::ios_base::binary );
		unused = input_data->imbue( std::locale::classic() );

Still no success. I will continue my investigation.

**Comment by Fimactif** [comment]
Why does the locale global have any impact for the upload of file?  I need to change it for my project but this apparently interrupt the uploading or downloading process.  Is there a way to upload data when the locale::global is set to another thing than classic?

I attempted to use a transfermanager which has the same issue.

Thanks in advance for your advice and explication
Francois

**Comment by KaibaLopez** [comment]
Hi @Fimactif, sorry for the delayed response.
So here's what I understand from this.
The locale::global() affects all forms of streams in the standard library, and at least in the example given you are uploading the file as a Aws::IOStream, and that class is based on std::basic_iostream, so it is also affected by locale::global.
This on itself should not break the sdk though, I've tested your code and changed the locale of the stream by both methods :
```
std::locale::global(std::locale("ja_JP.UTF8"));
...
const std::shared_ptr<Aws::IOStream> input_data =
			Aws::MakeShared<Aws::FStream>("AllocationSampleTag",
				"Texting.txt",
				std::ios_base::in | std::ios_base::binary);
...
std::cout << "Success"<<std::endl;
std::cout << input_data->getloc().name() << std::endl;

```
and :
```
const std::shared_ptr<Aws::IOStream> input_data =
			Aws::MakeShared<Aws::FStream>("AllocationSampleTag",
				"Texting.txt",
				std::ios_base::in | std::ios_base::binary);
input_data->imbue(std::locale("ja_JP.UTF8"));
...
std::cout << "Success"<<std::endl;
std::cout << input_data->getloc().name() << std::endl;
```
Both cases changes the location and uploads the file. My only guess on what can be breaking the sdk is that you're trying to change the global locale while the uploads are in progress.
Hope that responds your question, and let me know if I misunderstood something or if you have any others.

**Comment by Fimactif** [comment]
Hello @KaibaLopez! 
Sorry for the delay, Thank you for your clarification.  I verified and no, I do not change the locale during the process. The problem should be somewhere else I suppose then ... I would like to know what files you included when you created your project.  I did try to use the transferManager to see if it helps yet again 

Here are mine :

#define USE_IMPORT_EXPORT 

#include <aws/core/Aws.h>
#include <aws/core/auth/AWSCredentials.h>
#include <aws/s3/S3Client.h>
#include <aws/s3/model/PutObjectRequest.h>
#include <fstream>
#include <sys/stat.h>

#include <aws/transfer/TransferManager.h>
#include <aws/core/utils/threading/Executor.h>
//
#include <aws/core/utils/memory/stl/AWSString.h>
#include <aws/core/utils/logging/DefaultLogSystem.h>
#include <aws/core/utils/logging/AWSLogging.h>
#pragma once
#if defined(_WIN32) && !defined(__cplusplus_winrt)
// Extra includes for Windows desktop.
#include <windows.h>
#include <Shellapi.h>
#endif

#define USE_IMPORT_EXPORT 
#define USE_WINDOWS_DLL_SEMANTICS

#undef GetObject
#include <aws/core/Aws.h>
#include <aws/core/auth/AWSCredentials.h>
#include <aws/s3/S3Client.h>
#include <aws/s3/model/PutObjectRequest.h>
#include <fstream>
#include <sys/stat.h>

#include <aws/transfer/TransferManager.h>
#include <aws/core/utils/threading/Executor.h>
#include <aws/core/utils/memory/stl/AWSString.h>
#include <aws/core/utils/logging/DefaultLogSystem.h>
#include <aws/core/utils/logging/AWSLogging.h>

void UploadToAWS_Test()
{
	std::string sFileName = "Testing.zip";
	Aws::Utils::Logging::InitializeAWSLogging(
		Aws::MakeShared<Aws::Utils::Logging::DefaultLogSystem>(
			"RunUnitTests", Aws::Utils::Logging::LogLevel::Trace, "C:\\MyPath\\Log_" ) );

	Aws::Auth::AWSCredentials clCredentials;

	// If region is specified, use it
	Aws::Client::ClientConfiguration clientConfig;
	clientConfig.scheme = Aws::Http::Scheme::HTTPS;
	clientConfig.connectTimeoutMs = 30000;
	clientConfig.requestTimeoutMs = 60000;

	clientConfig.region = Aws::Region::YOUR_CODE;
	clCredentials.SetAWSAccessKeyId( ACCESS_KEY_ID );
	clCredentials.SetAWSSecretKey( SECRET_ACCESS_KEY );

	auto s3Client = Aws::MakeShared<Aws::S3::S3Client>( "SimactiveS3", clCredentials, clientConfig, Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Always );

	Aws::Utils::Threading::PooledThreadExecutor pPoolThreadExecute( 10 );
	Aws::Transfer::TransferManagerConfiguration clManagerConfig(
		&pPoolThreadExecute );
	clManagerConfig.s3Client = s3Client;
	TransferStatusUpdatedCallback clCallback = []( const TransferManager* pManager, const std::shared_ptr<const TransferHandle>& handle )
	{
		std::cout << "Transfer Status = " << handle->GetStatus() << "\n";
	};
	clManagerConfig.transferStatusUpdatedCallback = clCallback;

	clManagerConfig.uploadProgressCallback =
		[]( const TransferManager*, const std::shared_ptr<const TransferHandle>& handle )
	{
		std::cout << "Upload Progress: " << handle->GetBytesTransferred() << " of " << handle->GetBytesTotalSize() << " bytes\n";
	};

	clManagerConfig.downloadProgressCallback =
		[]( const TransferManager*, const std::shared_ptr<const TransferHandle>& handle )
	{
		std::cout << "Download Progress: " << handle->GetBytesTransferred() << " of " << handle->GetBytesTotalSize() << " bytes\n";
	};

	clManagerConfig.errorCallback =
		[]( const TransferManager*, const std::shared_ptr<const TransferHandle>& handle, const Aws::Client::AWSError<Aws::S3::S3Errors>& _clError )
	{
		std::cout << "Error message : " << _clError.GetExceptionName() << "\n desc : " << _clError.GetMessage().c_str() << "\n";
	};

	std::shared_ptr<TransferManager> clManagerTransfer = TransferManager::Create( clManagerConfig );

	const std::shared_ptr<Aws::IOStream> input_data =
		Aws::MakeShared<Aws::FStream>( "AllocationSampleTag",
			sFileName.c_str(),
			std::ios_base::in | std::ios_base::binary );
	Aws::Http::HeaderValueCollection clCollection;
	auto uploadFile = clManagerTransfer->UploadFile( input_data, BUCKET_NAME, "Testing.zip",
		"application/zip", Aws::Map<Aws::String, Aws::String>() );
	uploadFile->WaitUntilFinished();
}

int main()
{
	Aws::SDKOptions options;
	std::locale clUnused = std::locale::global( std::locale( "ja_JP.UTF8" ) );
	Aws::InitAPI( options );
	{
		UploadToAWS_Test();
	}
	Aws::ShutdownAPI( options );
	
	return 0;
}
This is the updated code I use for my testing, maybe this will help reproduce my situation and . Please retry with the new information, hoping it can pinpoint my issue

**Comment by KaibaLopez** [comment]
All right, I was finally able to reproduce the error. 

You're right about locale being root cause, specifically std::locale::global, because this changes all of the std::streams locale it causes some unexpected behavior, and apparently one of those is to cause ERROR_INVALID_PARAMETER when calling PutObject() with a zipped file with a different locale. 
So for example: 
```
//This Works on a txt or even png file.
const std::shared_ptr<Aws::IOStream> input_data =
			Aws::MakeShared<Aws::FStream>("AllocationSampleTag",
				"Texting.txt",
				std::ios_base::in | std::ios_base::binary);
std::locale::global(std::locale("ja_JP.UTF8"));
auto put_object_outcome = clS3Client.PutObject(object_request);

//On a .zip file though, it fails
const std::shared_ptr<Aws::IOStream> input_data =
			Aws::MakeShared<Aws::FStream>("AllocationSampleTag",
				"Testing.zip",
				std::ios_base::in | std::ios_base::binary);
std::locale::global(std::locale("ja_JP.UTF8"));
auto put_object_outcome = clS3Client.PutObject(object_request);
```

Now, this might be a bit of a rabbit hole to find out what's really going on, but in the mean time you can try a couple workarounds that worked for me:

* If you want to upload a file with a changed locale, use imbue instead of changing the global locale.
* If your project requires a change to the global locale,  then you can set global to classic before the putobject call and change it back once the call is done.

Let me know if this worked for you.

**Comment by Fimactif** [comment]
Hello! Glad to hear to were finally able to reproduce it 👍 .

My project does requires a change of the globale locale, but unfortunately I can't use the workaround in my final application is multi-threaded and it will impacts other thread... I was able to do my development tests using the workaround but the workaround is not usable for the final application. 

Worst case scenario, I will need to create a separate process for the upload process which will be in classic locale.
Hope you find the issue soon enough.

**Comment by KaibaLopez** [comment]
Hi @Fimactif, 
Sorry for the delayed response, can you try this: 
```
const std::shared_ptr<Aws::IOStream> input_data =
		Aws::MakeShared<Aws::FStream>("AllocationSampleTag",
		"Testing.zip",
		std::ios_base::out | std::ios_base::in | std::ios_base::binary | std::ios_base::trunc);
```
And let me know if that worked for you?

**Comment by Fimactif** [comment]
Hello @KaibaLopez 
I'm sorry for the long delayed answer … I switched project and completely disconnected of this one.
I just tried your suggestion and it simply empty the file to 0 byte.

I apologize for the delay
