### ISSUE TITLE
HttpClient high cpu usage with long polling REST API with curl 7.58

### ISSUE THREAD

**Issue by sunhyung** [aws/aws-sdk-cpp#1253]
### What platform/OS are you using?
Ubuntu 18.04 LTS

### Which version of the SDK?
1.7.162

### What compiler are you using? what version?
CLang 6.0

### What are your CMake arguments?
-DCMAKE_BUILD_TYPE="RelWithDebInfo" -DCMAKE_CXX_COMPILER:FILEPATH="clang++" -DCMAKE_C_COMPILER:FILEPATH="clang" -DENABLE_TESTING="OFF" -DBUILD_ONLY=${AWS_FEATURES} -DBUILD_SHARED_LIBS="OFF"

**Comment by sunhyung** [comment]
I'm using AWS SDK CPP on my server application to make HTTP request to call a REST API for every 100~150ms but after spinning up the application around 2 or 3 days, the CPU usage of my application was 100% without any client connections and kept failing to make HTTP request. ( MakeRequest function returned NULL HttpResponse object.)
Running environment is Ubuntu 18.04 TLS Docker container and curl version is 7.58.
Is this issue related with libcurl? Since my application has been running with curl 7.66 the latest version around 7 days, it looks pretty fine so far.

**Comment by singku** [comment]
You'd better find out what was your application doing when using high CPU. There are multiple ways to find out. (via strace, looking at log, etc.)

**Comment by sunhyung** [comment]
Here's the sample code that repro CPU 100%.


#include <aws/core/http/HttpClient.h>
#include <aws/core/Aws.h>
#include <aws/core/client/ClientConfiguration.h>
#include <aws/core/utils/Outcome.h>

#include <memory>
#include <thread>

#ifdef __linux__
#include <curl/curl.h>
#endif

int main()
{
    Aws::SDKOptions options;
    Aws::InitAPI(options);

#ifdef __linux__
    curl_version_info_data* d = curl_version_info(CURLVERSION_NOW);
    std::cout << "[CURL VERSION] " << d->version << std::endl;
#endif

    auto infinitePing = []
    {
        Aws::Client::ClientConfiguration config;
        config.scheme = Aws::Http::Scheme::HTTPS;
        config.connectTimeoutMs = 10000;
        config.requestTimeoutMs = 10000;

        std::shared_ptr<Aws::Http::HttpClient> httpClient = Aws::Http::CreateHttpClient(config);

        while (true)
        {
            Aws::String uri("https://SOMETHING POST API");

            std::shared_ptr<Aws::Http::HttpRequest> req(
                Aws::Http::CreateHttpRequest(
                    uri,
                    Aws::Http::HttpMethod::HTTP_POST,
                    Aws::Utils::Stream::DefaultResponseStreamFactoryMethod)
            );

            req->SetHeaderValue("Authorization", "Bearer ACCESS KEY");
            req->SetContentType("application/json");

            std::string jsonStr = "{ \"msg\" : \"Hello, Ping\", \"log\" : true}";

            std::shared_ptr<Aws::IOStream> bodyStream = Aws::MakeShared<Aws::StringStream>("MMOBRequest_StringStream", std::ios_base::in | std::ios_base::out);
            bodyStream->write(jsonStr.c_str(), jsonStr.length());
            req->AddContentBody(bodyStream);
            req->SetContentLength(std::to_string(jsonStr.length()));

            std::shared_ptr<Aws::Http::HttpResponse> res = httpClient->MakeRequest(req);
            std::this_thread::sleep_for(std::chrono::milliseconds(1));

        } // end while
    };

    constexpr int threadCount = 8;
    std::thread workers[threadCount];
    for (int i = 0; i < threadCount; ++i)
    {
        workers[i] = std::thread(infinitePing);
    }

    for (int i = 0; i < threadCount; ++i)
    {
        workers[i].join();
    }

    return 0;
}

**Comment by sunhyung** [comment]
AWS SDK CPU 100% repro

How to build the test application.
1. Prepare clean WSL Ubuntu 18.04 LTS
2. Run commands below,
 - sudo apt-get update
 - sudo apt-get upgrade
 - sudo apt-get install -y libcurl4-openssl-dev libssl-dev uuid-dev zlib1g-dev libpulse-dev cmake clang
3. Make sure CURL version is 7.58
 - curl --version
4. Build test application with AWS core.

How to build Docker container
1. Write Dockerfile with below,

################# BEGIN Dockerfile
ARG FROM_IMAGE=ubuntu:18.04
FROM ${FROM_IMAGE}

# Metadata indicating an image maintainer.
MAINTAINER USER@EMAIL.com

# Set up environment
RUN apt-get update && apt-get upgrade -y && apt-get install -y libssl-dev curl
    
RUN mkdir /usr/awstest

COPY . /usr/awstest/

WORKDIR /usr/awstest

CMD ./awssdk_test
################# END Dockerfile

2. Upload to ECR and spin up the container with ECS. (I spun up the ECS cluster with c5.large.)

**Comment by sunhyung** [comment]
CPU 100% happens either run this code in ECS or WSL Ubuntu 18.04.
I confirmed it both environment and I'm testing same code with CURL 7.66 to make sure there is no problem with it.

**Comment by sunhyung** [comment]
FYI, I attach CloudWatch monitoring graphs below,

![image](https://user-images.githubusercontent.com/6225005/67705874-1298bb80-f975-11e9-91f6-cf7d1bb33231.png)
![image](https://user-images.githubusercontent.com/6225005/67705897-1debe700-f975-11e9-9a3d-3cbb5a9e06f2.png)
![image](https://user-images.githubusercontent.com/6225005/67705921-280de580-f975-11e9-8fb6-40972732a056.png)
![image](https://user-images.githubusercontent.com/6225005/67705938-2fcd8a00-f975-11e9-9572-195b4232d45a.png)
![image](https://user-images.githubusercontent.com/6225005/67705964-378d2e80-f975-11e9-99ce-36749d9d6110.png)

**Comment by sunhyung** [comment]
> You'd better find out what was your application doing when using high CPU. There are multiple ways to find out. (via strace, looking at log, etc.)

Please refer to my comments I put today. I confirmed there's nothing but only HTTP request with a sample application.

**Comment by sunhyung** [comment]
@KaibaLopez  Would you reopen this issue?

**Comment by KaibaLopez** [comment]
No problem, but I was under the impression original poster could reopen, were you not able to?

**Comment by sunhyung** [comment]
> No problem, but I was under the impression original poster could reopen, were you not able to?

Github doesn't allow to reopen an issue closed by a repo collaborator so I couldn't reopen it.
