### ISSUE TITLE
DirectoryTreeTest.CreateDirectoryIfNotExistedTest Failed

### ISSUE THREAD

**Issue by bills10** [aws/aws-sdk-cpp#1255]
### What platform/OS are you using?
Windows 2016

### Which version of the SDK?
1.7.85

### What compiler are you using? what version?
cmake 3.16
Visual Studio 2017

### What are your CMake arguments?
cmake -G "Visual Studio 15 Win64" -DBUILD_ONLY="s3" -DCUSTOM_MEMORY_MANAGEMENT=0 -DCMAKE_BUILD_TYPE=Release c:\repo\aws-sdk-cpp |tee make.log

msbuild ALL_BUILD.vcxproj /p:Configuration=Release | tee bld.log

### Can you provide a TRACE level log? (sanitize any sensitive information)

  [ RUN      ] DirectoryTreeTest.CreateDirectoryIfNotExistedTest
S:\AWS_CPP_SDK_Windows\aws-cpp-sdk-core-tests\utils\FileSystemUtilsTest.cpp(293): error : Value of: FileSystem::CreateDirectoryIfNotExists(FileSystem::Join(FileSystem::Join(dir2, "dir3"), longDirName).c_str(), true ) [S:\bld\aws-sdk-cpp\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
    Actual: false
  Expected: true
  [  FAILED  ] DirectoryTreeTest.CreateDirectoryIfNotExistedTest (4 ms)
  [----------] 9 tests from DirectoryTreeTest (48 ms total)

This builds fine (same commands, same repo) on a different Windows 10 laptop.  Does anyone have idea what might be the problem here?  Thanks!

**Comment by KaibaLopez** [comment]
Hi @bills10 ,
The first thing that comes to mind is that you may not have long file name enabled. Could you verify if that's the case?
