### ISSUE TITLE
General question about "SlowDown"

### ISSUE THREAD

**Issue by kreuzerkrieg** [aws/aws-sdk-cpp#1257]
Since the randomization of the prefix was dropped I thought that creating diverse prefixes would work. However I still get the "SlowDown" error.
My objects distributed as following
> /foo/bar/baz/node_1/folder1/file1.bin
> /foo/bar/baz/node_1/folder1/file2.bin
> /foo/bar/baz/node_1/folder2/file1.bin
> /foo/bar/baz/node_2/folder1/file1.bin
> /foo/bar/baz/node_2/folder1/file2.bin

Each node has its own prefix, then it is followed by a "folder" name, then a "file" name. There is about 40 "files" in each "folder". Lets say I have ~20 nodes, about 200 "folders" under each node and 40 "files" under each folder. In this case, the prefix consists of common part "/foo/bar/baz", the node and the folder, so even if I upload all 40 files in parallel the pressure on single prefix is 40, right? And even if I upload 40 files to each and every "folder" from all nodes, the pressure still 40 per prefix. Is that correct? If yes, how come I get the "SlowDown"?

EDIT001:

**_Additional input_**
What platform/OS are you using? Ubuntu 18.04 with updates

Which version of the SDK? According to VersionConfig.h #define AWS_SDK_VERSION_STRING "1.7.111"

What compiler are you using? what version? GCC8

What are your CMake arguments? CMAKE_ARGS  -G${CMAKE_GENERATOR}
                -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
                -DBUILD_ONLY:String=transfer$<SEMICOLON>s3
                -DBUILD_SHARED_LIBS:BOOL=OFF
                -DENABLE_TESTING:BOOL=OFF
                -DOPENSSL_INCLUDE_DIR=${OPENSSL_INCLUDE_DIR}
                -DOPENSSL_CRYPTO_LIBRARY=${OPENSSL_CRYPTO_LIBRARY_FILE} #For testing only
                -DOPENSSL_SSL_LIBRARY=${OPENSSL_SSL_LIBRARY_FILE} #For testing only
                -DCURL_INCLUDE_DIR=${CMAKE_SOURCE_DIR}/contrib/curl/include/
                -DCURL_LIBRARY=$<TARGET_FILE:libcurl> #For testing only
                -DCUSTOM_MEMORY_MANAGEMENT=ON

Can you provide a TRACE level log? (sanitize any sensitive information) Unfortunately I dont have an access to the remote machine at this moment, will be able to add log files later

The sample code of multi-part uploader is [here](https://gist.github.com/kreuzerkrieg/5b808ebaada5b25251b1bca2956361d7). It missing some includes for error handling and such, but in general it is working code

EDIT002:
[Added a code](https://github.com/kreuzerkrieg/CPPJunk/tree/master/SlowDown) that reproduces the problem

Usage: In Utils.cpp replace tokens YOURACCESSKEY and YOURSECRETKEY with accordingly
In main.cpp replace s3://your-bucket/ with your bucket name. Spawn 16 EC2 instances, run the sample app on every node simultaneously. Wait for about 10 minutes (maybe more) for stuff to fail. Important note: In this case I linked dynamically with aws sdk installed locally via apt, `sudo apt install libaws17.2.2017`

**Comment by KaibaLopez** [comment]
Hi @kreuzerkrieg, would you mind providing sample code on what you're trying to do? 
Also, please follow the template for issues, more than anything I'd like to know what version of the sdk and what OS you're using, but a Trace log would also help a lot.

**Comment by kreuzerkrieg** [comment]
> Hi @kreuzerkrieg, would you mind providing sample code on what you're trying to do?
> Also, please follow the template for issues, more than anything I'd like to know what version of the sdk and what OS you're using, but a Trace log would also help a lot.

Gist added.

**Comment by kreuzerkrieg** [comment]
Additional input.
Instead of all nodes I've spawned only one node and ran the same code, no "SlowDown" for considerable amount of time. It somewhat contradicts the idea of - "spawn nodes but use different prefixes to scale up"
Now I'll fallback to the deprecated feature of randomizing prefixes to see if it helps

**Comment by kreuzerkrieg** [comment]
Additional input.
In last measurement, it took 157 seconds to fail. 181998 objects where written from 16 instances.  226.4GB of data was written.

**Comment by kreuzerkrieg** [comment]
Additional input.
Ok, prepending the whole prefix for each file with random token is not something I can do easily since it will request massive changes in my code but I can easily prepend with random token per node. Already did it and it did not make any difference, the "SlowDown" keeps popping

**Comment by singku** [comment]
I am not quite sure about how S3 managing their objects in backend. Are you sure `/path/to/different/node` will ask S3 to distribute your objects the way you expect and route(balance) your requests to different S3 servers?

I saw you build transfer as well. So instead of using s3, why don't you ask transfer manager to do the job for you? Following the sample code [here](https://github.com/aws/aws-sdk-cpp/blob/204fa2dbc818c88e904bfeeb731d96ed690d59a1/aws-cpp-sdk-transfer-tests/TransferTests.cpp#L649), you can simply call `transferManager->UploadDirectory()` to do all the heavy task, as well managing retry, and exp backoff when SlowDown happened.

**Comment by kreuzerkrieg** [comment]
> I am not quite sure about how S3 managing their objects in backend. Are you sure /path/to/different/node will ask S3 to distribute your objects the way you expect and route(balance) your requests to different S3 servers?
> I saw you build transfer as well. So instead of using s3, why don't you ask transfer manager to do the job for you? Following the sample code here, you can simply call transferManager->UploadDirectory() to do all the heavy task, as well managing retry, and exp backoff when SlowDown happened.

I'm already using default retry strategy, which exponentially backs off, which ends in longest sleep of 34 seconds AFAIR, which doesnt make sense, how come with a such long pause I still get SlowDown?
In addition, we have a common infra to work with S3, I dont see any reason to introduce additional code which does the same.

As of S3 backend management, there is AWS guide, according to which nowadays it is straightforward - dont put too much pressure on single prefix (at least 3500 requests per prefix), also, since 2018 no prefix randomization required. Thats it, go ahead spawn EC2 instances, write to different prefixes, and voila, you get dozens of gigabytes of throughput

**Comment by singku** [comment]
Wondering if the pressure also applies to `/foo/bar/baz`, the common prefix.

**Comment by kreuzerkrieg** [comment]
> Wondering if the pressure also applies to /foo/bar/baz, the common prefix.

As per documentation, not anymore, see [here](https://aws.amazon.com/about-aws/whats-new/2018/07/amazon-s3-announces-increased-request-rate-performance/)
Also, the only definition what "prefix" means [here](https://stackoverflow.com/questions/52443839/s3-what-exactly-is-a-prefix-and-what-ratelimits-apply/56155997#56155997)

**Comment by kreuzerkrieg** [comment]
> Hi @kreuzerkrieg, would you mind providing sample code on what you're trying to do?
> Also, please follow the template for issues, more than anything I'd like to know what version of the sdk and what OS you're using, but a Trace log would also help a lot.

Any news?

**Comment by kreuzerkrieg** [comment]
> Hi @kreuzerkrieg, would you mind providing sample code on what you're trying to do?
> Also, please follow the template for issues, more than anything I'd like to know what version of the sdk and what OS you're using, but a Trace log would also help a lot.

Hi, I've added code that reproduces the problem. The question contains the link to the code and a short guide on how to repro the problem.
