### ISSUE TITLE
SQS Send Message - Exiting program after retry to get a new valid token

### ISSUE THREAD

**Issue by pauloborn** [aws/aws-sdk-cpp#1258]
I've a program in C++ that run in multiple threads. Each thread will post on a SQS queue. So, I created a class which do, more or less, the following:

```
class SQSclass {
   private:
      SQSClient *sqs;
      Aws::Client::ClientConfiguration client_cfg;

   public:
      SQSclass() {
            sqs = new Aws::SQS::SQSClient(client_cfg);
      }

      bool post() {
            	Aws::String msg_body_sqs(info.c_str(), info.size());
            	Aws::SQS::Model::SendMessageRequest sm_req;
            	sm_req.SetQueueUrl(queue_url);
            	sm_req.SetMessageBody(msg_body_sqs);
            	return sqs->SendMessage(sm_req).IsSuccess();
      }
}
```

But when I call the post function, after some time running, the program exit without any log. I've a SIGFAULT handle and a try catch, but didn't work either. What I did to try understand was to turn on the Trace log of AWS SDK and it showed to me that, when the token isn't valid anymore the SDK try the get a new one, but before call SQS post API it closes.

To authenticate with AWS SQS I'm using the EC2 instance role solution, which works fine when I don't use the pointer. But the performance, when I don't use the pointer is very poor.

Can you help me identify the issue?

### What platform/OS are you using?
amzn2.x86_64

### Which version of the SDK?
1.6.0

### What compiler are you using? what version?
gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-6)

### What are your CMake arguments?
cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_ONLY="sqs" .. .

### Can you provide a TRACE level log? (sanitize any sensitive information)
[aws_sdk_2019-10-17-14.log](https://github.com/aws/aws-sdk-cpp/files/3739988/aws_sdk_2019-10-17-14.log)

**Comment by pauloborn** [comment]
Another information, I ran with vlagrind and the SDK is returning SIGPIPE.

**Comment by singku** [comment]
@pauloborn Did you solve this problem by setting `installSigHandler = true`?

**Comment by pauloborn** [comment]
@singku Yes, after I understand deeper the issue and take a look on the documentation regarding this specific issue, setting the `installSigHandler = true` solved the problem.
