### ISSUE TITLE
SEGV When EC2 Metadata Service Throttles Requests

### ISSUE THREAD

**Issue by cjhanks** [aws/aws-sdk-cpp#126]
I have not been able to identify the precise source of the error (in looking through the code), stack trace and some analysis below.

In the past I have noticed when I have many processes concurrently querying the Ec2 metadata service for AWS credentials it will start throwing error responses.  In my particular use case the request rate can periodically spike, and when it does..  internally the AWS SDK segfaults.

I believe all of my libraries are compiled with symbols except libcurl.  And I am not 100% certain, but that address /might/ be a call to `curl_slist_free_all`.

```
*** Aborted at 1457808719 (unix time) try "date -d @1457808719" if you are using GNU date ***
PC: @     0x7fe1bb4bc03a Aws::Http::CurlHttpClient::MakeRequest()
*** SIGSEGV (@0x0) received by PID 9 (TID 0x7fe1b2513700) from PID 0; stack trace: ***
    @     0x7fe1ba11c340 (unknown)
    @     0x7fe1bb4bc03a Aws::Http::CurlHttpClient::MakeRequest()
    @     0x7fe1bb4a4565 Aws::Internal::EC2MetadataClient::GetResource()
    @     0x7fe1bb4a2c7c Aws::Internal::EC2MetadataClient::GetDefaultCredentials()
    @     0x7fe1bb491c9e Aws::Auth::InstanceProfileCredentialsProvider::RefreshIfExpired()
    @     0x7fe1bb4927bc Aws::Auth::InstanceProfileCredentialsProvider::GetAWSCredentials()
    @     0x7fe1bb496a90 Aws::Auth::AWSCredentialsProviderChain::GetAWSCredentials()
    @     0x7fe1bb48f154 Aws::Client::AWSAuthV4Signer::PresignRequest()
    @     0x7fe1bb49a79b Aws::Client::AWSClient::GeneratePresignedUrl()
    @     0x7fe1bb882d9c Aws::S3::S3Client::GeneratePresignedUrl()
```

**Comment by JonathanHenson** [comment]
What version and of curl are you running?

**Comment by cjhanks** [comment]
aws-sdk-cpp: 0.9-504-g39e3893
libcurl: 7.35.0-1ubuntu2.6

**Comment by JonathanHenson** [comment]
We fixed some multi-threading related bugs in our libcurl interface recently, can you try pulling latest and seeing what happens?

**Comment by cjhanks** [comment]
I will be testing against `0.9.6-71-gf3cc307` is that an acceptable version?

**Comment by JonathanHenson** [comment]
Yes

**Comment by cjhanks** [comment]
It appears the newer version of software handles the issue more acceptably.  Rather than having a SEGV, it proceeds as if it was unable to acquire any credentials at all.  Consequently the request returns a "403 - Access Denied" error which is certainly preferable to crashing, but may confuse some.

**Comment by JonathanHenson** [comment]
The creds should be caching for 15 minutes or so. Are you using our credentials provider or the ec2 metadata client directly? Why is it hitting the service frequently enough to get throttled?

**Comment by cjhanks** [comment]
It's really an architectural problem with the way I am running my application.  I have a distributed processing environment using primarily 32 core machines.  When the machine initially turns on it is possible for 32 independent processes to flood the machine in a single negotiation cycle asking for instance credentials.  I can easily stagger these for my use case and so I am not deeply affected.  But I thought reporting the response code 403 as an FYI would be helpful.

**Comment by cjhanks** [comment]
Also, please close as you see fit.
