### ISSUE TITLE
GLib wrapper library 

### ISSUE THREAD

**Issue by andre2007** [aws/aws-sdk-cpp#1261]
Could you consider adding a GLib wrapper library on top of the C++ library?

By having the GLib wrapper, bindings for various 
languages could be easily generated.

You can see this feature e.g. in Apache Arrow,
https://github.com/apache/arrow/tree/master/c_glib

**Comment by JonathanHenson** [comment]
We’re working on something similar but it isn’t built on the c++ sdk. Go check out the aws common runtime, you can see the bindings here github.com/awslabs/aws-crt-<language>

**Comment by andre2007** [comment]
@JonathanHenson thanks for the info. Is there any information what aws common runtime is? As far as I can see it does not provide access to the specific AWS services (s3, sqs, ...) but provides common functionality like network access.

**Comment by KaibaLopez** [comment]
@andre2007, you are correct there.
