### ISSUE TITLE
AWS-CPP-SDK building

### ISSUE THREAD

**Issue by srveerla** [aws/aws-sdk-cpp#1265]
### What platform/OS are you using?
Centos 7
### Which version of the SDK?
aws-sdk-cpp-1.7.208
### What compiler are you using? what version?
3.6.2
### What are your CMake arguments?
cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_ONLY="s3" -DBUILD_SHARED_LIBS=ON -DSIMPLE_INSTALL=ON -DCUSTOM_MEMORY_MANAGEMENT=1 -DENABLE_TESTING=OFF -DCMAKE_C_FLAGS="-Wno-unused-variable -Wno-unused-parameter" -DCMAKE_CXX_FLAGS="-Wno-unused-variable -Wno-unused-parameter" /home/srk/aws-sdk-cpp-1.7.208
### Can you provide a TRACE level log? (sanitize any sensitive information)
Getting this after linking aws cpp sdk lib to our application:
undefined symbol: _ZN3Aws4Http18API_VERSION_HEADERE
What could be reason for this?

**Comment by KaibaLopez** [comment]
Hi @srveerla, can you replicate this error on the sdk by itself, as in, can you build the sdk and run one of the code samples for example? when exactly do you get this error?
