### ISSUE TITLE
BucketLocationConstraint (S3) and Region.* (Core) are not coordinated

### ISSUE THREAD

**Issue by bizzarri** [aws/aws-sdk-cpp#127]
There are missing regions in both sets of files - Region.h does not have cn and BucketLocationContraint does, for instance. I'm not sure which version is correct.

**Comment by bretambrose** [comment]
We recently did a rework of region-related logic to support IPv6 but there are still discrepancies.  I'll check with Jonathan to see if there's anything further we can do here.
