### ISSUE TITLE
Cmake spits error when I set -DCMAKE_INSTALL_PREFIX to install CPP SDK to my own custom path.

### ISSUE THREAD

**Issue by sunhyung** [aws/aws-sdk-cpp#1271]
### What platform/OS are you using?
Ubuntu 18.04 LTS (WSL)
### Which version of the SDK?
1.7.162
### What compiler are you using? what version?
Clang 6
### What are your CMake arguments?
sudo cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DCMAKE_CXX_COMPILER:FILEPATH="clang++" -DCMAKE_C_COMPILER:FILEPATH="clang" -DENABLE_TESTING="OFF" -DBUILD_ONLY="dynamodb;firehose;gamelift" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="../aws-sdk-cpp/install/Linux/RelWithDebInfo"
### Can you provide a TRACE level log? (sanitize any sensitive information)
[aws-sdk-error.log](https://github.com/aws/aws-sdk-cpp/files/3794963/aws-sdk-error.log)
[CMakeOutput.log](https://github.com/aws/aws-sdk-cpp/files/3794968/CMakeOutput.log)

**Comment by sunhyung** [comment]
This is how I run and install CPP SDK to the custom path.

sudo cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DCMAKE_CXX_COMPILER:FILEPATH="clang++" -DCMAKE_C_COMPILER:FILEPATH="clang" -DENABLE_TESTING="OFF" -DBUILD_ONLY="dynamodb;firehose;gamelift" -DBUILD_SHARED_LIBS="OFF"

sudo cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DCMAKE_CXX_COMPILER:FILEPATH="clang++" -DCMAKE_C_COMPILER:FILEPATH="clang" -DENABLE_TESTING="OFF" -DBUILD_ONLY="dynamodb;firehose;gamelift" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="../aws-sdk-cpp/install/Linux/RelWithDebInfo"

sudo make && sudo make install

**Comment by KaibaLopez** [comment]
Hi @sunhyung ,
the first thing that comes to mind here is the sdk dependencies. If you're trying to build in a custom path, you'll have to tell the sdk where those dependencies are. 
See the **To build and install third party dependencies** section of the README.
but basically you'll need to add :
-DCMAKE_PREFIX_PATH=**deps-install-dir** to your cmake arguments.

**Comment by sunhyung** [comment]
> Hi @sunhyung ,
> the first thing that comes to mind here is the sdk dependencies. If you're trying to build in a custom path, you'll have to tell the sdk where those dependencies are.
> See the **To build and install third party dependencies** section of the README.
> but basically you'll need to add :
> -DCMAKE_PREFIX_PATH=**deps-install-dir** to your cmake arguments.

Looks like that is what I wanted but... complicated... running another round of cmake is way more simple.

**Comment by KaibaLopez** [comment]
Yea.. sadly, it is somewhat of a limitation we have since we are depending on other aws projects, but I guess if that works better for you then that's good 👍 
I don't know if I can do more here so I'll be closing the issue, let me know if there are more questions and feel free to reopen it if that's the case.
