### ISSUE TITLE
Does AWS-SDK-CPP only read credentials from ~/.aws/

### ISSUE THREAD

**Issue by sichao-uber** [aws/aws-sdk-cpp#1273]
### What platform/OS are you using?
linux  ubuntu:18.04

### Which version of the SDK?
aws-sdk-cpp-1.7.135

### What compiler are you using? what version?
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

### What is your problem?
I am trying to running a cpp program that access to DynamoDB to read something.
The code is like
```
Aws::InitAPI(Aws::SDKOptions());
this->client_ = make_shared<DynamoDBClient>(ClientConfiguration());
GetItemRequest req;
req.SetTableName(String("test_table"));
AttributeValue av;
av.SetS("test_id");
req.AddKey(String("test-key"), av);
const GetItemOutcome &result = this->client_->GetItem(req);
```

But it throws the exception like
```
Unable to connect to endpoint with address : 153.95.1.39
```

I checked that my host has the access to aws through IAM role and sts by:
```
$ aws sts get-caller-identity
{
    "UserId": "55555555555:abc",
    "Account": "55555555555",
    "Arn": "arn:aws:sts::55555555555:federated-user/abc"
}


# output the expected result
$ aws dynamodb scan --table-name test_table --region us-east-1
....
# output the expected result
```

So at the current stage, from CLI, it can access to AWS DynamoDB, but from cpp code, it cannot.

I did some research, and found out that after I installed `aws-credential-client` and use it to generate the credential files under ~/.aws/credentials. Then the cpp program can access DDB.

My question is that do I have to use  `aws-credential-client` to generate ~/.aws/credentials for my cpp program to access DDB through aws-sdk-cpp? Can I have my cpp program access to DDB through sts and assumed IAM role?

**Comment by KaibaLopez** [comment]
Hi @sichao-uber , 
We are working on this but, the current way the sdk works is:
By default it does take the credentials from ~/.aws/credentials like CLI does, but it does not take the region, which I think causes your "cannot connect to endpoint" error.
That being said the error could have other causes so I'll give you a couple solutions for the region case, and if they don't work let me know and I'll take a closer look.
* The simpler way is to give the ClientConfiguration a region:
```
ClientConfiguration client_config();
client_config.region ="us-west-1";
this->client_ = make_shared<DynamoDBClient>(ClientConfiguration());
```
* Alternately, if you have a ~/.aws/config file set up with a profile that has the region defined, you can do:
`this->client_ = make_shared<DynamoDBClient>(ClientConfiguration("default"));`
and that should look for a profile of name [default] in ~/.aws/config

**Comment by sichao-uber** [comment]
Hi @KaibaLopez,
    The region is not the problem. Even without the line
```
client_config.region ="us-west-1";
```
It will still have the problem

**Comment by sichao-uber** [comment]
It tried both 
```
this->client_ = make_shared<DynamoDBClient>(ClientConfiguration("default"));
```
and 
```
this->client_ = make_shared<DynamoDBClient>(ClientConfiguration());
```
Neither of them work

**Comment by sichao-uber** [comment]
Currently the situation is that I am trying to deploy my service to EC2 instance with an IAM role that has the permission to talk to DynamoDB.

If I run the `awscli`, it works. but when I run in cpp, since it will read from `~/.aws/`, which I does not have it in EC2 instance, it will fail.

Theoretically in my case, my cpp service should work with Instance Profile Credentials , right?

**Comment by KaibaLopez** [comment]
My bad, I misunderstood the issue.
But yes, you're correct.

**Comment by sichao-uber** [comment]
but currently, it does not work with my Instance Profile Credentials.
not sure if there is any setup I did wrong, or it's aws-sdk-cpp does not support "Instance Profile Credentials".

If it's the former one, please let me know what kind of info you need to help you investigate this

**Comment by sichao-uber** [comment]
and also, is there anyway that I can discuss the issue with you directly to solve the problem faster?

**Comment by KaibaLopez** [comment]
yea sorry, multiple questions get confusing to answer, but the idea is that the sdk does not know the ec2 instance's IAM roles, so you'll need to provide the credentials, meaning it will check for them in ec2's ~/.aws/credentials the same way that it would if ran in your local machine, or expect you to provide them in the code.
The IAM role you used to create the ec2 instance is not carried over as far as the sdk knows.
So the simplest way to have the sdk run in your ec2 instance, is to simply copy the credentials from where you were able to run it and put them in the ec2's ~/.aws/credentials.

**Comment by sichao-uber** [comment]
```
So the simplest way to have the sdk run in your ec2 instance, is to simply copy the credentials from where you were able to run it and put them in the ec2's ~/.aws/credentials.
```
This will not work since the credential expires after a while. It's not practical to keep copying the credential from my local machine to EC2 server.

May I ask from the code level, in aws-sdk-cpp, is there a way to get the IAM credential from the code. if so, we can do something similar to this:
```
Credential credential = get_credential_from_host_iam();
ClientConfiguration config(credential);
DynamoDBClient client(config);
```

**Comment by KaibaLopez** [comment]
This may not be exactly what you're looking for but a way you'd be able to do this would be by modifying (or creating your own) Credentials provider and Credentials provider chain. 

The AWSCredentialsProviderChain defines how the credentials are looked for, and I think this is what you could use to get your implementation to work.
Look for AWSCredentialsProviderChain in aws-sdk-core for the base class and I'd recommend using DefaultAWSCredentialsProviderChain as an example or base for your own implementation.

The Client class uses the default provider chain, as the name implies 'by default', but you could create your own which in turn can be used to define the client, and that way tell it where to find the credentials.

So you'd be writing something like:
```
class AWS_CORE_API MyAWSCredentialsProviderChain : public AWSCredentialsProviderChain
 {
 // your code specifying which provider to call and in what order if multiple sources....
}
AWSCredentials MyAWSCredentialsProvider::GetAWSCredentials()
{
//your code on where to find the credentials
}
MyAWSCredentialsProviderChain providerChain("some location or call");
ClientConfiguration config();
DynamoDBClient client(providerChain,config); 
```

**Comment by sichao-uber** [comment]
I believe there are many aws customers who
1. write in cpp
2. use ec2 hosts
3. access to dynamodb
what is the standard process for them to get the things work

**Comment by sichao-uber** [comment]
For your solution above,
```
AWSCredentials MyAWSCredentialsProvider::GetAWSCredentials()
{
//your code on where to find the credentials
}
```
currently i have no idea how to get credentials from ec2 iam role

**Comment by sichao-uber** [comment]
Hi @KaibaLopez , can I get an update on this?
1. How can I get the credential from IAM that is set up in the EC2 host? Is it in some file? or it's an env variable?

2. How does other EC2 customers who write the cpp program to access the DynamoDB solve this problem?

Thanks

**Comment by KaibaLopez** [comment]
Hi @sichao-uber, so I did some digging, and first I want to apologize for my confusion yesterday.
regarding your last questions: 
1. Here is [documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials) on how to get the credentials from the IAM role attached to the EC2 instance.

2. This is not a common issue really, The sdk **Should** take the credentials from the IAM role by default via a call to `AWSCredentials InstanceProfileCredentialsProvider::GetAWSCredentials()` 

I've tested this on my own EC2 instance with a IAM Role attached, and no ~/.aws/credentials file on my instance, and the sdk connects as expected to dynamodb.
 I tested also with no IAM role attached and the error I'm getting is "Request is missing Authentication Token with address", which makes more sense than endpoint connection. 

This tells me that the problem not with the credentials provider... but the error of connection to endpoint is a little too generic though, could be as simple as a timeout, wrong region or it could be related to an EC2 service bug... Can you activate and provide the full trace log ? (make sure to sanitize personal info).
```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;
Aws::InitAPI(Aws::SDKOptions(options));
/*rest of your code */
```
Sorry again for the confusion

**Comment by sichao-uber** [comment]
Hi @KaibaLopez , thanks for the response.

Currently it's working after I 
1. create a permernant credentials
2. When build the docker image that is deployed to EC2 hosts, I hard-coded the credentials in the image under the path `~/.aws/creadentials`

Later I can change it back and add the logging option you provided, and see if it helps your investigation.

**Comment by sichao-uber** [comment]
Hi @KaibaLopez ,
    Do I need to add any other code to see the extra logs.
    After I added the code you provided above, when the exception is thrown, the error message is the same:
 ```
[00m[1m[19-11-08 22:44:15][info]: Query on table: model_version_manager_test for model version with id 1.
[00m[31m[1m[19-11-08 22:44:41][error]: Failed to get the model version with id: 1, due to:
Unable to connect to endpoint with address : 52.119.233.56
[00m[31m[1m[19-11-08 22:44:41][error]: GRPC request is throwing the exception:
[AWS_DYNAMODB_EXCEPTION]: Failed to get the model version with id: 1, due to:
Unable to connect to endpoint with address : 52.119.233.56
Converting it to GRPS status with code: 13
```

**Comment by KaibaLopez** [comment]
@sichao-uber , activating the logs won't really change the exceptions thrown, rather it will save the trace in a seperate file, it should be in the source folder with a name like : `aws_sdk_2019-11-08-22.log `
That's the file I'd like you to upload here(again, after sanitizing private info).

**Comment by sichao-uber** [comment]
Here is the log
```
0 response headers:
[WARN] 2019-11-11 22:47:35.187 AWSClient [140290669143808] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
[DEBUG] 2019-11-11 22:47:35.187 AWSClient [140290669143808] Date header was not found in the response, can't attempt to detect clock skew
[WARN] 2019-11-11 22:47:35.187 AWSClient [140290669143808] Request failed, now waiting 50 ms before attempting again.
[DEBUG] 2019-11-11 22:47:35.238 InstanceProfileCredentialsProvider [140290669143808] Checking if latest credential pull has expired.
[DEBUG] 2019-11-11 22:47:35.238 AWSClient [140290669143808] Request Successfully signed
[DEBUG] 2019-11-11 22:47:35.238 CurlHandleContainer [140290669143808] Attempting to acquire curl connection.
[INFO] 2019-11-11 22:47:35.238 CurlHandleContainer [140290669143808] Connection has been released. Continuing.
[DEBUG] 2019-11-11 22:47:35.238 CurlHandleContainer [140290669143808] Returning connection handle 0x7f97fc1b6a90
[DEBUG] 2019-11-11 22:47:35.238 CurlHttpClient [140290669143808] Obtained connection handle 0x7f97fc1b6a90
[ERROR] 2019-11-11 22:47:35.238 CurlHttpClient [140290669143808] Curl returned error code 77 - Problem with the SSL CA cert (path? access rights?)
[DEBUG] 2019-11-11 22:47:35.238 CurlHandleContainer [140290669143808] Releasing curl handle 0x7f97fc1b6a90
[DEBUG] 2019-11-11 22:47:35.238 CurlHandleContainer [140290669143808] Notified waiting threads.
[DEBUG] 2019-11-11 22:47:35.238 AWSClient [140290669143808] Request returned error. Attempting to generate appropriate error codes from response
[ERROR] 2019-11-11 22:47:35.238 AWSClient [140290669143808] HTTP response code: -1
Exception name: 
Error message: Unable to connect to endpoint
0 response headers:
[WARN] 2019-11-11 22:47:35.238 AWSClient [140290669143808] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
[DEBUG] 2019-11-11 22:47:35.238 AWSClient [140290669143808] Date header was not found in the response, can't attempt to detect clock skew
[WARN] 2019-11-11 22:47:35.238 AWSClient [140290669143808] Request failed, now waiting 100 ms before attempting again.
[DEBUG] 2019-11-11 22:47:35.339 InstanceProfileCredentialsProvider [140290669143808] Checking if latest credential pull has expired.
[DEBUG] 2019-11-11 22:47:35.339 AWSClient [140290669143808] Request Successfully signed
[DEBUG] 2019-11-11 22:47:35.339 CurlHandleContainer [140290669143808] Attempting to acquire curl connection.
[INFO] 2019-11-11 22:47:35.339 CurlHandleContainer [140290669143808] Connection has been released. Continuing.
[DEBUG] 2019-11-11 22:47:35.339 CurlHandleContainer [140290669143808] Returning connection handle 0x7f97fc1b6a90
[DEBUG] 2019-11-11 22:47:35.339 CurlHttpClient [140290669143808] Obtained connection handle 0x7f97fc1b6a90
[ERROR] 2019-11-11 22:47:35.339 CurlHttpClient [140290669143808] Curl returned error code 77 - Problem with the SSL CA cert (path? access rights?)
[DEBUG] 2019-11-11 22:47:35.339 CurlHandleContainer [140290669143808] Releasing curl handle 0x7f97fc1b6a90
[DEBUG] 2019-11-11 22:47:35.339 CurlHandleContainer [140290669143808] Notified waiting threads.
[DEBUG] 2019-11-11 22:47:35.339 AWSClient [140290669143808] Request returned error. Attempting to generate appropriate error codes from response
[ERROR] 2019-11-11 22:47:35.339 AWSClient [140290669143808] HTTP response code: -1
Exception name: 
Error message: Unable to connect to endpoint
0 response headers:
[WARN] 2019-11-11 22:47:35.339 AWSClient [140290669143808] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
[DEBUG] 2019-11-11 22:47:35.339 AWSClient [140290669143808] Date header was not found in the response, can't attempt to detect clock skew
[WARN] 2019-11-11 22:47:35.339 AWSClient [140290669143808] Request failed, now waiting 200 ms before attempting again.
[DEBUG] 2019-11-11 22:47:35.540 InstanceProfileCredentialsProvider [140290669143808] Checking if latest credential pull has expired.
[DEBUG] 2019-11-11 22:47:35.540 AWSClient [140290669143808] Request Successfully signed
[DEBUG] 2019-11-11 22:47:35.540 CurlHandleContainer [140290669143808] Attempting to acquire curl connection.
[INFO] 2019-11-11 22:47:35.540 CurlHandleContainer [140290669143808] Connection has been released. Continuing.
[DEBUG] 2019-11-11 22:47:35.540 CurlHandleContainer [140290669143808] Returning connection handle 0x7f97fc1b6a90
[DEBUG] 2019-11-11 22:47:35.540 CurlHttpClient [140290669143808] Obtained connection handle 0x7f97fc1b6a90
```

**Comment by KaibaLopez** [comment]
Alright, 
So the error is on curl ssl verification:
 `Curl returned error code 77 - Problem with the SSL CA cert (path? access rights?)`

* As a workaround, if you're just trying to run this without going too deep on what's going on, you can add:
`client_config.verifySSL = false`
and that should at least make it run.

If you want more info on what's going on and where or what file it's trying to find, I will need you to turn on the flag : ENABLE_CURL_LOGGING on your cmake arguments, and then tell us what you got and we'll be able to help further. But probably what's happening is that it's trying to use a custom CA Cert that's on an unexpected location or under special privileges. 

If it is a custom ca cert and you know where it is, you can also tell the client configuration by adding:
```
client_config.caFile="";
client_config.caPath="";
```
