### ISSUE TITLE
AWS C++ SDK: After creation of S3Client object and creating the bucket, subsequent call adds bucketname to the endpoint

### ISSUE THREAD

**Issue by kirannittur** [aws/aws-sdk-cpp#1274]
I amable to connect to the endpoint server and create new bucket but subsequest calls fails with "unable to connect to endpoint"
Looking at the logs i see that bucket name is getting prefixed for the host name causing the issue.
How to fix this?
### What platform/OS are you using?
Windows 2K12R2
### Which version of the SDK?
Initiate AWS SDK for C++ with Version:1.7.142
### What compiler are you using? what version?
installed aws C++ sdk through vcpkg
### What are your CMake arguments?
vcpkg install aws-sdk-cpp[core,s3,ec2]:x86-windows

### Can you provide a TRACE level log? (sanitize any sensitive information)
[aws_sdk_2019-11-06-18.log](https://github.com/aws/aws-sdk-cpp/files/3816438/aws_sdk_2019-11-06-18.log)

**Comment by kirannittur** [comment]
[DEBUG] 2019-11-06 18:16:28.003 WinHttpConnectionPoolMgr [5704] Returning connection handle 00BFBE38
[DEBUG] 2019-11-06 18:16:28.003 WinHttpSyncHttpClient [5704] Acquired connection 00BFBE38
[DEBUG] 2019-11-06 18:16:28.003 WinHttpSyncHttpClient [5704] AllocateWindowsHttpRequest returned handle 00BFFA10
[DEBUG] 2019-11-06 18:16:28.003 WinHttpSyncHttpClient [5704] with headers:
[DEBUG] 2019-11-06 18:16:28.003 WinHttpSyncHttpClient [5704] authorization: AWS4-HMAC-SHA256 Credential=BKIKJAA5BMMU2RHO6IBB/20191106/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-api-version;x-amz-content-sha256;x-amz-date, Signature=52d2b872e4ad89769581ae0c5587e11e10a2ca8a6e5c2a413330b8e530ac15eb

content-length: 0

content-type: text/plain

**host: qash2-sql5.172.20.238.104:9000**

user-agent: aws-sdk-cpp/1.7.142 Windows/6.3.9600.17031 x86 MSVC/1916

x-amz-api-version: 2006-03-01

x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

x-amz-date: 20191106T181628Z


[WARN] 2019-11-06 18:16:28.004 WinHttpSyncHttpClient [5704] Send request failed: The server name or address could not be resolved


[DEBUG] 2019-11-06 18:16:28.004 WinHttpSyncHttpClient [5704] Closing http request handle 00BFFA10
[DEBUG] 2019-11-06 18:16:28.004 WinHttpSyncHttpClient [5704] Releasing connection handle 00BFBE38
[DEBUG] 2019-11-06 18:16:28.004 WinHttpConnectionPoolMgr [5704] Releasing connection to endpoint qash2-sql5.172.20.238.104:9000
[DEBUG] 2019-11-06 18:16:28.004 AWSClient [5704] Request returned error. Attempting to generate appropriate error codes from response
[ERROR] 2019-11-06 18:16:28.004 AWSClient [5704] HTTP response code: -1
Exception name: 
Error message: Unable to connect to endpoint

**Comment by KaibaLopez** [comment]
Hi @kirannittur, 
can you provide sample code that would reproduce this issue?

**Comment by kirannittur** [comment]
Below are the three functions to connect, create bucket and initiate multipart upload

In the header file m_client and m_config is declared
ClientConfiguration m_config;
shared_ptr<S3Client> m_client;

bool S3controller::Connect()
{
	// Create a client
	
	m_config.region = Aws::Region::US_EAST_1;
	m_config.scheme = Scheme::HTTP;
	m_config.connectTimeoutMs = 300000;
	m_config.requestTimeoutMs = 300000;
	m_config.readRateLimiter = m_limiter;
	m_config.writeRateLimiter = m_limiter;
	m_config.endpointOverride = m_minioServer;
	m_config.executor = Aws::MakeShared<Aws::Utils::Threading::PooledThreadExecutor>(ALLOCATION_TAG, 4);

	m_client = Aws::MakeShared<S3Client>(ALLOCATION_TAG,
		AWSCredentials(m_accessKey, m_secretKey), m_config,
		AWSAuthV4Signer::PayloadSigningPolicy::Never /*signPayloads*/, true /*useVirtualAddressing*/);

	return true;
}

bool S3controller::CreateBucket(Aws::String &bucketName)
{
	CreateBucketRequest createBucketRequest;
	createBucketRequest.SetBucket(bucketName.c_str());
	createBucketRequest.SetACL(BucketCannedACL::private_);
	CreateBucketOutcome createBucketOutcome = m_client->CreateBucket(createBucketRequest);
	if (!createBucketOutcome.IsSuccess())
	{
		cout << "Create bucket failed for bucket name " << bucketName.c_str() << " Error : " << createBucketOutcome.GetError().GetMessage() << endl;
		return false;
	}
	const CreateBucketResult& createBucketResult = createBucketOutcome.GetResult();
	if (createBucketResult.GetLocation().empty())
	{
		cout << "Create bucket failed for bucket name " << bucketName.c_str() <<  " location was empty" << endl;
		return false;
	}

	return true;
}

bool S3controller::InitiateMultipartUpload(Aws::String &bucketName, Aws::String &objectName)
{
	CreateMultipartUploadRequest createMultipartUploadRequest;
	createMultipartUploadRequest.SetBucket(bucketName);
	createMultipartUploadRequest.SetKey(objectName);
	createMultipartUploadRequest.SetContentType("text/plain");
	
	cout << "Creating multipart upload for bucket " << bucketName.c_str() << " and object name " << objectName.c_str() << endl;
	m_createMultipartUploadOutcome = m_client->CreateMultipartUpload(
		createMultipartUploadRequest);
	
	cout << "returned from Creating multipart upload for bucket " << bucketName.c_str() << " and object name " << objectName.c_str() << endl;
	bool retCode = m_createMultipartUploadOutcome.IsSuccess();
	if (!retCode)
	{
		cout << "Failed to initiate multipart upload for bucket name " << bucketName.c_str() << " Error : " << m_createMultipartUploadOutcome.GetError().GetMessage() << endl;
		return false;
	}

	cout << "Successfully created multipart upload for bucket " << bucketName.c_str() << " and object name " << objectName.c_str() << endl;
	return true;
}

**Comment by kirannittur** [comment]
Any call from S3Client object after creating bucket fails with "Unable to connect to endpoint"

**Comment by kirannittur** [comment]
Is this a bug? this seems to be straight forward implemented as per the SDK example. Am i missing something here?

**Comment by KaibaLopez** [comment]
I'm sorry @kirannittur , It'll take some time for me to get to why this is failing for you, but on first glance I don't think it's a bug with the sdk since the integration tests are passing and those include these kind of simple operations... It could be a naming issue or a problem specific to windows though so not necessarily 'not a bug'.
In the mean time you could also take a look at the tests in: `aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTests.cpp `as "examples" on how to do these operations, since we know these pass, maybe you can find something you're missing from there.
I'll get back to you as soon as I make progress on this.

**Comment by kirannittur** [comment]
@KaibaLopez Thank you. I in fact implemented exactly the way described in the example you pointed. That link is what i used for reference.

**Comment by singku** [comment]
useVirtualAddressing, please set it off, if you are using your own server and endpoint.

**Comment by kirannittur** [comment]
Thank you very much that resolved the issue.

**Comment by kirannittur** [comment]
it would be good to have this documented

**Comment by kirannittur** [comment]
Thanks for all the help
