### ISSUE TITLE
Multipart upload to MINIO server through aws c++ sdk fails with "SDK failed to sign the request"

### ISSUE THREAD

**Issue by kirannittur** [aws/aws-sdk-cpp#1275]
### What platform/OS are you using?
win2k12R2
### Which version of the SDK?
Initiate AWS SDK for C++ with Version:1.7.142
### What compiler are you using? what version?
installed through vcpkg
### What are your CMake arguments?
vcpkg install aws-sdk-cpp[core,s3,ec2]:x86-windows
[aws_sdk_2019-11-07-04.log](https://github.com/aws/aws-sdk-cpp/files/3818108/aws_sdk_2019-11-07-04.log)

**Comment by kirannittur** [comment]
I am able to connect to server, create new bucket and Initiate multipart upload successfully.
After that i uploaded part 1 and it failed with error "SDK failed to sign the request"

I am purely following example giving in below link
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp


I had to turn off useVirtualAddressing for other endpoints which i did. From the log is see that 
[DEBUG] 2019-11-07 04:15:14.574 AWSAuthV4Signer [9244] Canonical Request String: POST
/qash2-sql5/QASH2-SQL5/master/master.bkp
uploads=
content-length:0
content-type:application/xml
host:172.20.238.104:9000
x-amz-api-version:2006-03-01
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20191107T041514Z

content-length;content-type;host;x-amz-api-version;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
[DEBUG] 2019-11-07 04:15:14.574 AWSAuthV4Signer [9244] Final String to sign: AWS4-HMAC-SHA256
20191107T041514Z
20191107/us-east-1/s3/aws4_request
ded3754249a466f61db4856a2a34d1c796af2ea0e761488a64657c0e79ed92a5
[DEBUG] 2019-11-07 04:15:14.574 AWSAuthV4Signer [9244] Final computed signing hash: 87ee4ced448232133afb8f248f586f6ab8aa27fc6df574b43bb44ae14aaf4430
[DEBUG] 2019-11-07 04:15:14.574 AWSAuthV4Signer [9244] Signing request with: AWS4-HMAC-SHA256 Credential=BKIKJAA5BMMU2RHO6IBB/20191107/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-api-version;x-amz-content-sha256;x-amz-date, Signature=87ee4ced448232133afb8f248f586f6ab8aa27fc6df574b43bb44ae14aaf4430
[DEBUG] 2019-11-07 04:15:14.574 AWSClient [9244] Request Successfully signed
[INFO] 2019-11-07 04:15:14.574 WinHttpConnectionPoolMgr [9244] Attempting to aquire connection for 172.20.238.104:9000
[DEBUG] 2019-11-07 04:15:14.574 WinHttpConnectionPoolMgr [9244] Pool found, reusing
[INFO] 2019-11-07 04:15:14.574 WinHttpConnectionPoolMgr [9244] Connection now available, continuing.
[DEBUG] 2019-11-07 04:15:14.574 WinHttpConnectionPoolMgr [9244] Returning connection handle 01264E48
[DEBUG] 2019-11-07 04:15:14.574 WinHttpSyncHttpClient [9244] Acquired connection 01264E48
[DEBUG] 2019-11-07 04:15:14.574 WinHttpSyncHttpClient [9244] AllocateWindowsHttpRequest returned handle 0128F800
[DEBUG] 2019-11-07 04:15:14.574 WinHttpSyncHttpClient [9244] with headers:
[DEBUG] 2019-11-07 04:15:14.574 WinHttpSyncHttpClient [9244] authorization: AWS4-HMAC-SHA256 Credential=BKIKJAA5BMMU2RHO6IBB/20191107/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-api-version;x-amz-content-sha256;x-amz-date, Signature=87ee4ced448232133afb8f248f586f6ab8aa27fc6df574b43bb44ae14aaf4430

content-length: 0

content-type: application/xml

host: 172.20.238.104:9000

user-agent: aws-sdk-cpp/1.7.142 Windows/6.3.9600.17031 x86 MSVC/1916

x-amz-api-version: 2006-03-01

x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

x-amz-date: 20191107T041514Z


[DEBUG] 2019-11-07 04:15:14.578 WinHttpSyncHttpClient [9244] Received response code 200
[DEBUG] 2019-11-07 04:15:14.578 WinHttpSyncHttpClient [9244] Received content type application/xml
[DEBUG] 2019-11-07 04:15:14.578 WinHttpSyncHttpClient [9244] Received headers:
[DEBUG] 2019-11-07 04:15:14.578 WinHttpSyncHttpClient [9244] HTTP/1.1 200 OK

Date: Thu, 07 Nov 2019 04:12:51 GMT

Content-Length: 273

Content-Type: application/xml

Accept-Ranges: bytes

Server: MinIO/RELEASE.2019-10-12T01-39-57Z

Vary: Origin

**Content-Security-Policy: block-all-mixed-content

X-Amz-Request-Id: 15D4C616E1DA98B5

X-Xss-Protection: 1; mode=block**




[DEBUG] 2019-11-07 04:15:14.578 WinHttpSyncHttpClient [9244] Closing http request handle 0128F800
[DEBUG] 2019-11-07 04:15:14.578 WinHttpSyncHttpClient [9244] Releasing connection handle 01264E48
[DEBUG] 2019-11-07 04:15:14.578 WinHttpConnectionPoolMgr [9244] Releasing connection to endpoint 172.20.238.104:9000
[DEBUG] 2019-11-07 04:15:14.578 AWSClient [9244] Request returned successful response.
[ERROR] 2019-11-07 04:15:14.652 AWSAuthV4Signer [4172] Unable to hash (sha256) request body
[ERROR] 2019-11-07 04:15:14.652 AWSClient [4172] Request signing failed. Returning error.

**Comment by singku** [comment]
Could you please open Trace level log?
Also the sample code.

**Comment by kirannittur** [comment]
sure will do first thing in the morning

**Comment by kirannittur** [comment]
First i tried the example given and it worked then re looked at the logic of my code to populating the buffers and found some issues in it. Once i fixed it worked properly.
