### ISSUE TITLE
Fail to build in Windows 10 using VS 2019

### ISSUE THREAD

**Issue by miryee** [aws/aws-sdk-cpp#1276]
### What platform/OS are you using?
Windows 10
### Which version of the SDK?
current (Master)
### What compiler are you using? what version?
msbuild 16.3.2.50909 (VS 2019)
### What are your CMake arguments?
cmake d:\Projects\GitHub\aws-sdk-cpp -G "Visual Studio 16 2019" -DSTATIC_LINKING=1 -DBUILD_ONLY="s3" -DFORCE_SHARED_CRT=OFF -DBUILD_SHARED_LIBS=OFF -DCUSTOM_MEMORY_MANAGEMENT=0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=D:\Projects\awssdkcpp_build\out
### Can you provide a TRACE level log? (sanitize any sensitive information)
fails from the cmake step (log attached)
[awssdkcpp_cmake_log_20191107103300.log](https://github.com/aws/aws-sdk-cpp/files/3820825/awssdkcpp_cmake_log_20191107103300.log)
`	Line 68:   -- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Failed
	Line 70:   -- Performing Test AWS_HAVE_MSVC_MULX - Failed
	Line 72:   -- Performing Test AWS_HAVE_GCC_INLINE_ASM - Failed
	Line 74:   -- Performing Test AWS_HAVE_EXECINFO - Failed
	Line 82:   -- Performing Test HAVE_MAY_I_USE - Failed
	Line 84:   -- Performing Test HAVE_BUILTIN_CPU_SUPPORTS - Failed
	Line 92:   -- Performing Test HAS_WGNU - Failed
	Line 94:   -- Performing Test HAVE_SYSCONF - Failed
	Line 96:   -- Performing Test HAS_SANITIZERS - Failed
	Line 389:   -- Performing Test HAS_WGNU - Failed
	Line 391:   -- Performing Test HAVE_SYSCONF - Failed
	Line 393:   -- Performing Test HAS_SANITIZERS - Failed`

fails from the build step (log attached):
[awssdkcpp_build_log_20191107103300.log](https://github.com/aws/aws-sdk-cpp/files/3820809/awssdkcpp_build_log_20191107103300.log)
`Line 454:   [  FAILED  ] ProcessCredentialsProviderTest.TestProcessCredentialsProviderDoNotRefresh (17 ms)
	Line 478:   [  FAILED  ] ProcessCredentialsProviderTest.TestProcessCredentialsProviderExpiredThenRefreshed (6 ms)
	Line 692:   [  FAILED  ] ProfileConfigFileAWSCredentialsProviderTest.TestDefaultConfig (30 ms)
	Line 1266: Done Building Project "D:\Projects\awssdkcpp_build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj" (default targets) -- FAILED.
	Line 2015: Done Building Project "D:\Projects\awssdkcpp_build\ALL_BUILD.vcxproj" (default targets) -- FAILED.
	Line 2018: Build FAILED.`

It also throws a exception during the build phase:
```
Microsoft Visual C++ Runtime Library

Debug Assertion Failed!

Program:
D:\Projects\awssdkcpp_build\bin\Debug\aws-cpp-sdk-core-tests.exe
File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.23.28105\include\vector
Line: 1510

Expression: back() called on empty vector
```

This is probably related to issue: Done building project "aws-cpp-sdk-core-tests.vcxproj" -- FAILED. #1254.  Like that issue, only the aws-cpp-sdk-core-tests is failing.  However, I am using a different version of VS and seeing different error/fail messages.  

Also, I was able to build this successfully 5 months ago on Windows 10 VS 2017 using the same cmake command.  Since our product is now being built on VS 2019, I need to be able to reliably build this on VS 2019 as well.

**Comment by singku** [comment]
The first CMake part errors should be just fine. It's testing if your hardware and system support some functions.

I can't reproduce your second test failure. Can you please attach the aws log generated during the test?

**Comment by miryee** [comment]
[aws_sdk_2019-11-07-21.log](https://github.com/aws/aws-sdk-cpp/files/3821860/aws_sdk_2019-11-07-21.log)

**Comment by KaibaLopez** [comment]
Hi @miryee, I also could not reproduce your issue running the same commands on the latest version of the sdk, but I've faced some problems that could be related.
So while we investigate the root cause of your issue, I'd recommend you try building the latest version of the dependencies, or just to test it out do one run without the -DBUILD_SHARED_LIBS=OFF & -DCMAKE_INSTALL_PREFIX arguments.

**Comment by miryee** [comment]
I can build it if I disable the testing.

**Comment by KaibaLopez** [comment]
Hi @miryee , I can see in the logs that the sdk is trying to use a "dev" profile for the tests, which is weird... Could you provide a list of profiles you've saved as environment variables and/or in your ~/.aws/config file?

**Comment by miryee** [comment]
I have 4 profiles: default, dev, test, prod.  Default is configured to non-usable values.  When I execute the make and msbuild commands, I set the environment variables AWS_ACCESS_KEY_ID = [my id] and AWS_SECRET_ACCESS_KEY = [my key].  

I do see a bunch of config_blahxxxxx and config_blahxxxxxtokenFile files, where xxxxx is some 5-digit number, that were generated during each build attempt in my .aws directory.

config_blah44400 contains:
`[default]
region = us-west-2
web_identity_token_file = C:\Users\myee\.aws\config_blah44400tokenFile
 role_arn = arn:aws:iam::123456789012:role/demo 
role_session_name = sessionId_1234_abcd_xxxx

`
and configblah444000token contains a token ending in +`IEXAMPLE`.

I have 6 sets of these files, and they all contain exactly the same information except for the 5-digit number.

**Comment by KaibaLopez** [comment]
Hi @miryee ,
I was finally able to reproduce this error, and turns out the problem is with the AWS_PROFILE=dev environment variable.
It looks to be a bug and we'll look into it, but as a work around for you... 
First, delete all those blah_xxxxxx files, those are meant to be temp files so no need for them.
then, you can either change the AWS_PROFILE to "default" or simply delete it from the environment variables.
finally try building again, and that I think should work.
Thanks for your help, and let me know if the workaround works for you!

**Comment by KaibaLopez** [comment]
The bug has been fixed, please get the latest version of the sdk
