### ISSUE TITLE
Is there support for multi part copy?

### ISSUE THREAD

**Issue by rahul003** [aws/aws-sdk-cpp#1278]
Is there support for multi part copy? From one S3 location to another. The file I need to transfer is above 5GB and I can't use the CopyObject. I see multipart upload/download through transfer manager. But do I need to implement the multi part copy myself using CopyObject?

**Comment by KaibaLopez** [comment]
Hi @rahul003, you are correct, we have no implementation of copy object in the transfer manager.

**Comment by rahul003** [comment]
What's the best way to achieve a copy a large object from one s3 location to another?

**Comment by singku** [comment]
You can follow this instruction and use similar APIs in C++ SDK to achieve your purpose.

https://docs.aws.amazon.com/AmazonS3/latest/dev/CopyingObjctsMPUapi.html
