### ISSUE TITLE
Lambda package doesn't compile after AWS SDK C++ update

### ISSUE THREAD

**Issue by NatxoM** [aws/aws-sdk-cpp#1279]
### What platform/OS are you using?
Docker FROM ubuntu:18.04

### Which version of the SDK?
The problem appears with v1.7.212

### What compiler are you using? what version?
g++

### What are your CMake arguments?
I'm following the instructions for creating a lambda package using AWS SDK C++ and S3 from:

https://aws.amazon.com/blogs/compute/introducing-the-c-lambda-runtime/

### Can you provide a TRACE level log? (sanitize any sensitive information)
With v1.7.212, I get:
```
[100%] Linking CXX executable XXX
/usr/bin/ld: cannot find -laws-c-event-stream
/usr/bin/ld: cannot find -laws-checksums
/usr/bin/ld: cannot find -laws-c-common
collect2: error: ld returned 1 exit status
make[2]: *** [XXX] Error 1
CMakeFiles/XXX.dir/build.make:140: recipe for target 'XXX' failed
```
Before, it worked perfectly.

**Comment by singku** [comment]
What do you mean 'before'?
Also we are working on fixing a similar problem. If you use target_link_library with AWSSDK_LINK_LIBRARIES variable in your cmake scripts,try modify this variable to aws-cpp-sdk-[service name], [service name] is 'lambda' or 's3', etc.

**Comment by marcomagdy** [comment]
More information here. https://github.com/awslabs/aws-lambda-cpp/issues/64

**Comment by singku** [comment]
We have fixed this issues in commit https://github.com/aws/aws-sdk-cpp/commit/0e3c5d7351caa50edf36a5c987e5ea723024e568

Please update SDK to latest to try again. Reopen if you still have this issue.
