### ISSUE TITLE
[Feature Request] Constructors of Aws::DynamoDB::Model::AttributeValue for primitive types

### ISSUE THREAD

**Issue by sunhyung** [aws/aws-sdk-cpp#1280]
### What platform/OS are you using?
WIndows 10 / Ubuntu 18.04

### Which version of the SDK?
1.7.162

### What compiler are you using? what version?
VS2019 / Clang 6

### What are your CMake arguments?
N/A

### Can you provide a TRACE level log? (sanitize any sensitive information)
N/A

### Feature Request
Currently Aws::DynamoDB::Model::AttributeValue supports only 4 ctors including a default ctor. When I handle string type of data, it's okay but other primitive types such as int, float or bool, it's pretty inconvenient. Therefore, I'd like to request new ctors for other types.

**Comment by KaibaLopez** [comment]
Hi @sunhyung ,
Do you require it to be on constructor for some specific reason?
Because if not, it sounds to me like something the sdk already provides... only not on a constructor.
Like for example, say you want a variable with type int/float: 
```
Aws::DynamoDB::Model::PutItemRequest pir;
pir.SetTableName(table);
Aws::DynamoDB::Model::AttributeValue av;
av.SetN("9.81");
pir.AddItem("Gravity", av);
```
you could take a look into the AttributeValue class for other data types we support (SetBool, SetSS, SetM, etc.). Keep in mind this types are based on dynamodb types, so ints and floats are "number".

**Comment by sunhyung** [comment]
In case of that, I don't want to declare named variables but want to pass AttributeValue as unnamed temporary variables. Like, 
`Aws::DynamoDB::Model::PutItemRequest pir;`
`pir.SetTableName(table);`
`pir.AddItem("Gravity", Aws::DynamoDB::Model::AttributeValue(9.81));``
or
`void foo(double val)`
`{`
`... something`
`Aws::DynamoDB::Model::PutItemRequest pir;`
`pir.SetTableName(table);`
`pir.AddItem("Gravity", Aws::DynamoDB::Model::AttributeValue(val));``
`... something`
`}`

**Comment by KaibaLopez** [comment]
So, in that case you could try:
`pir.AddItem("Gravity", Aws::DynamoDB::Model::AttributeValue().SetN("9.81"));`

**Comment by sunhyung** [comment]
> So, in that case you could try:
> `pir.AddItem("Gravity", Aws::DynamoDB::Model::AttributeValue().SetN("9.81"));`

Oh good to know. Thanks!!
