### ISSUE TITLE
SDK installation does not install c third party libs correctly after update

### ISSUE THREAD

**Issue by dcorderoch-el** [aws/aws-sdk-cpp#1283]
### What platform/OS are you using?

Ubuntu 19.04

### Which version of the SDK?

```
$ git describe --always --tags
1.7.232
$ git show-ref 1.7.232
12c67a5e1c6ea54504db01d5f25cbb56a6134138 refs/tags/1.7.232
```

### What compiler are you using? what version?

```
$gcc --version
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I also use

```
$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.33
Copyright (C) 2019 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

and

```
$ ld.gold --version
GNU gold (GNU Binutils for Ubuntu 2.33) 1.16
Copyright (C) 2019 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

### What are your CMake arguments?

```
$ cmake --version
cmake version 3.13.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

```
cmake .. -G "Unix Makefiles" \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_ONLY="core;s3;transfer" \
-DENABLE_TESTING=OFF \
-DBUILD_SHARED_LIBS=OFF \
-DSIMPLE_INSTALL=ON
```

option `-DBUILD_SHARED_LIBS` seems to not make a difference in either `ON` or `OFF`

### Can you provide a TRACE level log? (sanitize any sensitive information)

the install seems correct, but the build of a working application that uses the SDK on previous releases of the SDK no longer works

I initially cloned when 1.7.159 was the latest stable release, it wasn't until a new Engineer was setting up his machine and cloned the SDK that we encountered this problem, I set up 1.7.159 in his machine to get his setup working, and then started looking into this

I ran a git bisect on the SDK's repo and it seems that starting on `e0d61bcb12` all updates/releases don't install the third party libraries (aws-c-common, aws-checksums, aws-c-event-stream) correctly, i.e. I get

```
/usr/bin/ld.gold: error: cannot find -laws-c-event-stream
/usr/bin/ld.gold: error: cannot find -laws-checksums
/usr/bin/ld.gold: error: cannot find -laws-c-common
```

and using ld I get

```
collect2: error: ld returned 1 exit status
```

I looked into `/usr/local` and did find files `libaws-c-common.a`, so I'm guessing it might be some option in CMake, I ran `git show e0d61bcb12` and saw that some options were removed in an if block starting with `if(SIMPLE_INSTALL)`

and some other changes

I thought 

```
-    set(ALL_SERVICES "core;aws-c-event-stream;aws-checksums;aws-c-common")
+    set(ALL_SERVICES "core" ${AWSSDK_THIRD_PARTY_LIBS})
```

might have been the cause, I thought it should have been `"core;${AWSSDK_THIRD_PARTY_LIBS}"`

but making the change didn't fix the install problem, so I thought it'd be best to open an issue, is there anything I'm just not seeing?

we use

```
find_package(AWSSDK REQUIRED
    COMPONENTS
        core
        s3
        transfer
)
```

and

```
target_link_libraries(${PROJECT_NAME}
    PRIVATE
        ${AWSSDK_LINK_LIBRARIES}
)
```

**Comment by singku** [comment]
Would you mind sharing your own CMake scripts part which is to find and link against SDK?
Also would you mind telling the location of aws-cpp-sdk-core-config.cmake and sharing the content of this file?

**Comment by dcorderoch-el** [comment]
> Would you mind sharing your own CMake scripts part which is to find and link against SDK?
> Also would you mind telling the location of aws-cpp-sdk-core-config.cmake and sharing the content of this file?

alright, we have a library to wrap our use of the aws-sdk-cpp, in that library we have

```
project(myLib)

add_library(${PROJECT_NAME})

find_package(AWSSDK REQUIRED
    COMPONENTS
        core
        s3
        transfer
)

# ...

target_link_libraries(${PROJECT_NAME}
    PRIVATE
        ${AWSSDK_LINK_LIBRARIES}
)
```

then, on the application that links against that library, we have

```
set(EXECUTABLE_NAME "myExec")

add_executable(${EXECUTABLE_NAME})

# ...

target_link_libraries(${EXECUTABLE_NAME}
    PRIVATE
        myLib
)
```

```
$ find /usr/local -type f -name aws-cpp-sdk-core-config.cmake
/usr/local/lib/cmake/aws-cpp-sdk-core/aws-cpp-sdk-core-config.cmake
```
and its contents are (renamed to .txt because github complains about `.cmake` files)

[aws-cpp-sdk-core-config.cmake.txt](https://github.com/aws/aws-sdk-cpp/files/3882974/aws-cpp-sdk-core-config.cmake.txt)

**Comment by singku** [comment]
From the config.cmake file, looks like SDK did try to find aws-c-event-stream, and it found one, otherwise, you would get error at cmake steps. But it failed to link one of the dependencies. This tells that it most probably the same problem we are fixing.
Taking a look at https://github.com/aws/aws-sdk-cpp/issues/1270

Try adding
```
target_link_directories(${EXECUTABLE_NAME} /path/to/third_party/libs BEFORE)
```
or
```
 list(REMOVE_ITEM AWSSDK_LINK_LIBRARIES ${AWSSDK_THIRD_PARTY_LIBS})
```
before `target_link_libraries` to see if it would work and confirm with us that's the issue.

Thanks for the update.

**Comment by dcorderoch-el** [comment]
alright, the line to remove the third party libs fixes my build problem

could this option be added when building the SDK with static libs by default? or is this supposed to be the way users of the SDK link when building as static libs?

other than that I think this issue can be closed

**Comment by singku** [comment]
No, there is a bug in shipped CMake config module. We are working on fixing it.

**Comment by singku** [comment]
We have fixed this issues in commit https://github.com/aws/aws-sdk-cpp/commit/0e3c5d7351caa50edf36a5c987e5ea723024e568

Please update SDK to latest to try again. Reopen if you still have this issue.
