### ISSUE TITLE
C2220 Windows build error

### ISSUE THREAD

**Issue by mechamogera** [aws/aws-sdk-cpp#1286]
I get an error when building.
What should I do?

```
Build FAILED.
"E:\aws-sdk-cpp-1.7.235\INSTALL.vcxproj" (default target) (1) ->
"E:\aws-sdk-cpp-1.7.235\ALL_BUILD.vcxproj" (default target) (3) ->
"E:\aws-sdk-cpp-1.7.235\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj" (default target) (55) ->
(ClCompile target) -> 
  e:\aws-sdk-cpp-1.7.235\aws-cpp-sdk-core-tests\utils\stringutilstest.cpp : warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss [E:\aws-sdk-cpp-1.7.235\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
"E:\aws-sdk-cpp-1.7.235\INSTALL.vcxproj" (default target) (1) ->
"E:\aws-sdk-cpp-1.7.235\ALL_BUILD.vcxproj" (default target) (3) ->
"E:\aws-sdk-cpp-1.7.235\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj" (default target) (55) ->
(ClCompile target) -> 
  e:\aws-sdk-cpp-1.7.235\aws-cpp-sdk-core-tests\utils\stringutilstest.cpp : error C2220: warning treated as error - no 'object' file generated [E:\aws-sdk-cpp-1.7.235\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
    1 Warning(s)
    1 Error(s)
```

### What platform/OS are you using?

Windows 10 Professional

### Which version of the SDK?

1.7.234 or 1.7.235

### What compiler are you using? what version?

Visual Stadio 2017

### What are your CMake arguments?

cmake <path-to-root-of-this-source-code> -G "Visual Studio 15 Win64" -DCMAKE_BUILD_TYPE=Release

**Comment by KaibaLopez** [comment]
Hi @mechamogera, 
Quick question, have you enabled long paths on windows?

**Comment by mechamogera** [comment]
I think it's not enabled.
I checked this site and confirmed that the LongPathsEnabled registory value was 0.
https://helpdeskgeek.com/how-to/how-to-fix-filename-is-too-long-issue-in-windows/

**Comment by KaibaLopez** [comment]
Hi @mechamogera ,
Can you enable that and try building again? One of our tests incudes a long file name which would fail if long paths is not enabled on windows 
otherwise you could also build without running the tests by adding -DENABLE_TESTING=OFF on your cmake argument.

**Comment by mechamogera** [comment]
Thank you for your help.
I was able to do.
