### ISSUE TITLE
Units appear to be incorrect on Curl keepalive calls.

### ISSUE THREAD

**Issue by gboggs** [aws/aws-sdk-cpp#1290]
### What platform/OS are you using?
x86 Linux (SLES12SP3)

### Which version of the SDK?
1.7.29
### What compiler are you using? what version?
 4.8.5

### What are your CMake arguments?
 -DBUILD_ONLY="core;s3" -DCMAKE_BUILD_TYPE=RelWithDebInfo 
### Can you provide a TRACE level log? (sanitize any sensitive information)
Yes, if needed.

In CurlHandleContainer.cpp, both my version of the SDK and master have this:

curl_easy_setopt(handle, CURLOPT_TCP_KEEPINTVL, m_tcpKeepAliveIntervalMs); curl_easy_setopt(handle, CURLOPT_TCP_KEEPIDLE, m_tcpKeepAliveIntervalMs);

The default value for m_tcpKeepAliveIntervalMs is 30,000.
(gdb) print m_tcpKeepAliveIntervalMs
$1 = 30000

However the Curl documentation at https://curl.haxx.se/libcurl/c/CURLOPT_TCP_KEEPINTVL.html says the units on these calls should be seconds, not milliseconds. For example, on CURLOPT_TCP_KEEPINTVL it says "Sets the interval, in seconds, that the operating system will wait between sending keepalive probes. "

There's a disconnect somewhere. One of these is wrong.

**Comment by KaibaLopez** [comment]
Hi @gboggs ,
Thanks for pointing this out. You're right, we misnamed this value so curl is waiting 3000 seconds ,not milliseconds, by default. 
We could change this by dividing _m_tcpKeepAliveIntervalMs_ before curl_easy_setopt, so the variable name remains unchanged but better represent the value... but even then, this would be a breaking change for others who are not expecting the change, so we'd probably wait for a bigger version change, before adding it.
