### ISSUE TITLE
s3_client.setGrantRead("http://acs.amazonaws.com/groups/global/AllUsers") fails with invalid argument error.

### ISSUE THREAD

**Issue by Porchezhiyan-GitHub** [aws/aws-sdk-cpp#1291]
I've written a code that uploads an image file to an S3 bucket. I want to fetch a download URL to the image uploaded which does not expire.
I was working with an object that has private access, so I tried using `generatepresignedURL()`. I got a URL but it does not work and says error in signing method. 
After spending some time debugging it, I thought of making object public and construct a download URL myself `https://<bucket-name>.s3.amazonaws.com/<key>`. But again I'm stuck on how to make my object public while uploading. If I used `setGrantRead("http://acs.amazonaws.com/groups/global/AllUsers")`, I am getting invalid argument error, If I remove the line the file upload works fine.
Also, I tried getting and setting objectACL to provide read access to all users but again failed with no error message.

I don't know what I'm missing and guidance would be much appreciated.

- I would like to know if it is possible to get a presigned URL for a private object with no expiration date or considerably long expiration date( a year maybe).
- Can anyone point me to a C++ example for fetching the presignedURL for a private object? Or provide the steps to get one.
- How to upload an object with public access? FYI Bucket is set to allow public access.

Thanks,
Porchezhiyan

**Comment by KaibaLopez** [comment]
Hi @Porchezhiyan-GitHub , 
So, I am not able to reproduce your error, but as a an example of private object presigned url, I'm running this and it works for me just fine.
```
#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>
#include <aws/s3/model/PutObjectRequest.h>
#include <aws/s3/model/PutObjectResult.h>
#include <aws/core/auth/AWSCredentialsProvider.h>
#include <aws/core/http/HttpTypes.h>

#include <iostream>
#include <fstream>
#include <string>
Aws::SDKOptions options;
int main()
{

    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;
    Aws::InitAPI(options);
    {
        Aws::Client::ClientConfiguration clientConfig("default");
        Aws::S3::S3Client clS3Client( clientConfig );

        Aws::S3::Model::PutObjectRequest object_request;

        object_request.SetBucket( "some_bucket_name" );
        object_request.SetKey("Anything_really");
	std::shared_ptr<Aws::IOStream> objectStream = Aws::MakeShared<Aws::StringStream>("BucketAndObjectOperationTest");
        *objectStream << "Test Object";
        object_request.SetBody(objectStream);
        object_request.SetContentType( "text/plain" );

        // Put the object
        auto put_object_outcome = clS3Client.PutObject( object_request );
        if (!put_object_outcome.IsSuccess()) {
            auto error = put_object_outcome.GetError();
            std::cout << error.GetMessage() << std::endl;
        }
        else
        {  
            std::cout<<"Success" << std::endl; 
            std::cout << clS3Client.GeneratePresignedUrl(object_request.GetBucket(),object_request.GetKey(),Aws::Http::HttpMethod::HTTP_GET);

        }
    }
    Aws::ShutdownAPI(options);
}
```
So the privacy settings of the object shouldn't be the reason for the generated url to fail.

As for how to change how long the presigned url lasts for, you can use `GeneratePresignedUrl(bucket_name,bucket_key,duration_seconds)`,  but I believe the longest that the url will last before expiring is a week, and by default that is the value the method gives, so you oculd only make it shorter.
Lastly, for uploading an object with public access you can do:
`object_request.WithACL(Aws::S3::Model::ObjectCannedACL::public_read_write);`

Let me know if you got more questions on this.

**Comment by Porchezhiyan-GitHub** [comment]
Hi @KaibaLopez, Thank you for the quick reply. I got answers to all my queries from your reply. 
Again, thanks for the guidance.
