### ISSUE TITLE
Best way to send data from R-Pi to DynamoDB in C++?

### ISSUE THREAD

**Issue by dandekar** [aws/aws-sdk-cpp#1292]
### What platform/OS are you using?
R-Pi
------

This is a high-level question: We are building an electric vehicle and would like to use DynamoDB to store vehicular data. We are just getting started building a gateway (using R-Pi) that will collect data over CAN and send it to AWS over https. If we have to send data from Raspberry Pi to DynamoDB in C++, it looks like there are at least three ways:
1. Use the AWS C++ SDK to call DynamoDB APIs directly.
2. Use AWS IoT C++ SDK to send data to AWS IoT and then write rules to pipe data to DynamoDB.
3. Use AWS Gateway to set up a http endpoint that will take get/put etc as http requests and route them to DynamoDB (we successfully prototyped this, but it seems clunky/restrictive).

It feels to me that (1) is cleanest, and also cheapest (I'm not paying for the additional services like Gateway or API). However, it requires us to build the entire AWS C++ SDK, most of which we probably don't need, and which needs 4GB of RAM (which our R-Pi doesn't have).

1. Is there a way to strip down this AWS C++ SDK so I keep only the DynamoDB libraries (and their deps) and exclude everything else?
2. Are there other ways of sending data from R-Pi to DynamoDB that I don't know about?

Thanks a lot for all your help!

**Comment by KaibaLopez** [comment]
Hi @dandekar ,
I may be missing something in your question, but we provide a way to build just the services you need: 
**BUILD_ONLY**
Allows you to only build the clients you want to use. This will resolve low level client dependencies if you set this to a high-level sdk such as aws-cpp-sdk-transfer. This will also build integration and unit tests related to the projects you select if they exist. aws-cpp-sdk-core always builds regardless of the value of this argument. This is a list argument. Example:
`-DBUILD_ONLY="s3;dynamodb;cognito-identity"`

Let me know if this is what you're looking for or if you mean something else when you say "exclude everything else". 

And while I can't say which one would be best for sure, one thing I'd like to mention is that if you're thinking of going for the IoT sdk, I'd recommend taking a look at the newer version - [Aws Iot C++ V2 ](https://github.com/aws/aws-iot-device-sdk-cpp-v2).

**Comment by dandekar** [comment]
Thanks @KaibaLopez. We tried it with `-DBUILD_ONLY`, but it crashed multiple times. We're using RPi 2B (https://www.raspberrypi.org/products/raspberry-pi-2-model-b/), it has 1GB RAM. Do you think dynamodb should compile on RPi 2B?

**Comment by KaibaLopez** [comment]
I believe it should be able to run,
It sounds like you are able to build and use the sdk but at some point while running it crashes, is that the case?
Can you specify on what error is crashing it?

**Comment by husainmanasa** [comment]
Hi,

   To clarify things, aws-sdk-cpp is successfully downloaded. $sudo cmake -DBUILD_ONLY="dynamodb" completes successfully, but following that while executing the command "$sudo make" compilation hangs at 27% and RPi crashes.

**Comment by KaibaLopez** [comment]
@husainmanasa @dandekar
Sorry for the delayed response, but as far as I've tested it should not be a problem. 
Granted I'm using a R pi 4, but it has the 1gb ram, so I don't think it's a RPi limitation.
Maybe yours has ran out of memory? The sdk (with just dynamodb) and the dependencies needed should only take about 150mb once built, so by itself it should not be even close to cause the issue. 
I will say however that I had a problem while doing cmake with __atomic, but that doesn't seem to be the problem in your case.
For now, check that you have enough free space on your RPi and if that's not it, can you provide the exact error you get when you do $sudo make?
