### ISSUE TITLE
How to import mysql library using bazel

### ISSUE THREAD

**Issue by sichao-uber** [aws/aws-sdk-cpp#1295]
### What platform/OS are you using?
linux
### Which version of the SDK?
latest

Hi,
I have created a MySQL DB instance through AWS RDS.
I am trying to import mysql library in my CPP code, and do a sample [example](https://dev.mysql.com/doc/connector-cpp/1.1/en/connector-cpp-examples-complete-example-1.html)

My project is using bazel to import the library. Sorry that I cannot disclose my code due to company policy, but the way bazel imports the library is similar to those links:
[link1](https://github.com/gng-demo/GrabnGo/blob/6d0c4b3feb65a0daf944211b32ff51357a4ea53a/WORKSPACE#L181),
[link2](https://github.com/gng-demo/GrabnGo/blob/master/third_party/gcloud_datastore.BUILD)

So my question is do you have any idea on how to import mysql library using bazel?

I understand this is more of mysql question, instead of aws question. And RDS library in aws-sdk-cpp is for the management of mysql instance, instead of how to access mysql.
But I have tried several ways. Cutting this issue is more like my last resort. Hope you have some idea.

I have the code similar to link1:
```
# mysql lib
    http_archive(
        name = "mysql-connector-cpp",
        build_file = "//third_party:mysql-connector-cpp.BUILD",
        sha256 = "64be955ad2b87376ade555651b0b86c3ecc6000faf71485d1dff360dff83c90f",
        strip_prefix = "mysql-connector-c++-8.0.13-src",
        url = "https://dev.mysql.com/get/Downloads/Connector-C++/mysql-connector-c++-8.0.18-linux-glibc2.12-x86-64bit.tar.gz",
    )
```

and the file "mysql-connector-cpp.BUILD" similar to link2:
```
cc_library(
    name = "mysql",
    hdrs = glob(["include/**"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
)
```

But unfortunately, when I compile, I kept getting error:
```
 fatal error: 'cppconn/driver.h' file not found
```

My guess is that in file "mysql-connector-cpp.BUILD", i did not have the correct hdrs and includes.

If you can try to create a sample project and import the mysql library using bazel, please let me know.

Thanks

**Comment by KaibaLopez** [comment]
Hi @sichao-uber ,
As you say, this would be a bit outside the scope of the guidance we give... 
That being said, if you're willing to give me some time, I'll try  and come up with a small sample project on using bazel, see if I can get it to work. 
I'll update you as soon as I get something.

**Comment by KaibaLopez** [comment]
Hi @sichao-uber , sorry to say but I could not dedicate the time to make this work, and since we don't really support bazel builds I'll be closing the issue, sorry again for not being able to help. Hope you found a solution to your problem
