### ISSUE TITLE
Build SDK for iOS

### ISSUE THREAD

**Issue by glawe** [aws/aws-sdk-cpp#1297]
Hi,

Is there any guide for how to build the cpp sdk for iOS ? The readme only seems to specify 'Apple' which is only OS X ?

I'm using QT for my main project and the also runs on desktop and Andorid, so the ios version of the sdk is pretty much out of the question! :)

Regards.

**Comment by KaibaLopez** [comment]
Hi @glawe , 
You're right, I'm not sure we have examples on iOS but let me take a look or try and make one if there really isn't, I'll update you once I get something.

**Comment by glawe** [comment]
Thanks. That would help out a lot and save me many hours! ;)

**Comment by miryee** [comment]
Any progress on this? I am also trying to build for ios.

**Comment by miryee** [comment]
So I a running into cmake errors that it cannot find CURL when I try to build for ios.  I am using a MacBook to build.  The confusing thing, is that I am using the exact same environment to build for ios that I used to build successfully for Mac OS and for android.  cmake did not have any problems finding curl for Mac OS nor for android, but it cannot find it for ios.  Our product uses curl, but we build for ios and Mac OS using xcode, and have no issues with finding curl. What am I missing?

**Comment by singku** [comment]
This is my test script to build for IOS. Make sure you have XCode installed, and build libcurl for IOS (You should be able to find resource online, such as https://github.com/sinofool/build-libcurl-ios)
Modify following scripts accordingly with your corrected paths.
```
​#!/bin/bash

mkdir iphone_build_output
mkdir build
cd build

rm -rf ./*
/Applications/CMake.app/Contents/bin/cmake -DCMAKE_OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk" -DCMAKE_OSX_ARCHITECTURES="arm64" -DCMAKE_SYSTEM_NAME="Darwin" -DCMAKE_SHARED_LINKER_FLAGS="-framework Foundation -lz -framework Security" -DCMAKE_EXE_LINKER_FLAGS="-framework Foundation -framework Security" -DCMAKE_PREFIX_PATH="/path/to/your/libcurl_iphone_arm64_static/" -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX="/path/to/your/iphone_build_output" -DCUSTOM_MEMORY_MANAGEMENT="1" -DCMAKE_CXX_FLAGS="-std=c++11 -stdlib=libc++ -miphoneos-version-min=8.3" -DENABLE_UNITY_BUILD=ON ../aws-sdk-cpp
make -j 8
make install​
```

**Comment by nguoithichkhampha** [comment]
@glawe I'm using aws-transfer can build and run successful on iOS.

**Comment by miryee** [comment]
I am still having issues with finding ios curl.  I built the ios curl using the link you provided, and used your script with my paths.   But I still get the following error:

> [100%] Built target AwsCEventStream
> -- Third-party dependencies are installed at: ~/Projects/awssdkcpp_build/out
> --   Zlib library: /usr/lib/libz.dylib
> -- Encryption: CommonCrypto
> -- Http client: Curl
> -- Could NOT find CURL (missing: CURL_INCLUDE_DIR) 
> CMake Error at cmake/external_dependencies.cmake:83 (message):
>   Could not find curl
> Call Stack (most recent call first):
>   CMakeLists.txt:242 (include)
