### ISSUE TITLE
How to add metadata to an existing file which size is more than 5GB?

### ISSUE THREAD

**Issue by x081x** [aws/aws-sdk-cpp#1299]
There is a 10G files in bucket, I want to add a metadata. I find a way to do it.

`Aws::S3::Model::CopyObjectRequest request;
request.SetBucket(strBuncket);
request.SetKey(strKey);

Aws::String strCopySource = (strBuncket + "/" + strKey);
request.SetCopySource(strCopySource);

Aws::Http::HeaderValueCollection metadata;
metadata.insert(std::pair<Aws::String, Aws::String>("new_metadata", "new_metadata_value"));

request.SetMetadata(metadata);
request.SetMetadataDirective(Aws::S3::Model::MetadataDirective::REPLACE);

auto outcome = client.CopyObject(request);`

But if a file which size is more than 5GB, CopyObject is failure.
So how to add metadata to an existing file which size is more than 5GB? Thanks

**Comment by KaibaLopez** [comment]
Hi @x081x , sorry for the late response.
Right now we don't have a way to add metadata to an existing object in s3, other than making a copy.
And, as for the larger objects, this is another limitation we have.
So, you have basically 2 options on what to do:
* Download -> add metadata -> upload. This would require you to download to your local machine even if temporarily though, so it might not be the best solution.
* Write your own version of a multi part copy.

On my side, I'll try and push for the multi part copy feature to be added.

**Comment by x081x** [comment]
Hi @KaibaLopez , thank your very much.
