### ISSUE TITLE
KinesisVideo SDK putMedia Operation

### ISSUE THREAD

**Issue by snarkeystarkey** [aws/aws-sdk-cpp#1300]
### What platform/OS are you using?
Ubuntu 18.04

### Which version of the SDK?
Head/Master (64ea36e19dd01de8889c5a4f2576f678b0aec395)

### What compiler are you using? what version?
GCC 7.4

### What are your CMake arguments?
Default CMake Arguments

I am trying to use the KinesisVideo SDK to implement my own producer library that is NOT a gstreamer module. I do not see any implementation of the putMedia option in the current SDK under KinesisVideoClient. Is this planned for the near future? 

The AWS Doc refers to the "Kinesis Video Streams Producer SDK" --- which does not generate any linkable libraries (aside from its own libkvspic.a) or offer any headers that can be installed on my system.

Help me Obiwan?

**Comment by KaibaLopez** [comment]
Hi @snarkeystarkey ,
I think what you're looking for is a high level api, which you wouldn't find in this sdk but as the doc says, should be in the [KinesisVideo SDK](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp). Sorry to redirect you but please open an issue on that sdk.

**Comment by snarkeystarkey** [comment]
Thank you @KaibaLopez :)
