### ISSUE TITLE
After creating out of source of AWS SDK C++.How to use it in UE4 Project IDE-VS2017 ?????

### ISSUE THREAD

**Issue by AGAK-GAMES** [aws/aws-sdk-cpp#1304]

**Comment by KaibaLopez** [comment]
Hi @AGAK-GAMES,
We don't provide any specifics for UE4. But in theory, you'd only need to link the built libraries the same way you'd do it on a VS project, so you'd have to:
* Go into the project properties 
* Add include Directories (ex. ~sdklocation/aws-sdk-cpp/aws-cpp-sdk-s3/include)
* Add Additional Library Directories: (ex. ~sdk_build_loc/aws-cpp-sdk-s3/debug)
* Add Additional Dependencies: (ex. aws-cpp-sdk-s3.lib)
* Add Preprocessor Definitions (USE_WINDOWS_DLL_SEMANTICS & USE_IMPORT_EXPORT)
Hope this helps.
