### ISSUE TITLE
aws-sdk-core TestHttpResponseNetworkError failing

### ISSUE THREAD

**Issue by Lectem** [aws/aws-sdk-cpp#1305]
### What platform/OS are you using?

WSL Ubuntu 16.04.3 LTS

### Which version of the SDK?

commit https://github.com/aws/aws-sdk-cpp/commit/469b69b351a6668b6901df9e488833f49fac4883

### What compiler are you using? what version?

```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
```

### What are your CMake arguments?

`-DBUILD_ONLY=s3 `

### Debug information

By setting a breakpoint [here](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core-tests/http/HttpClientTest.cpp#L34)

the content of `response` is 

  | Name | Value | Type
-- | -- | -- | --
▶ | m_httpRequest | {...} | const Aws::Http::HttpRequest &
▶ | m_sharedHttpRequest | {...} | std::shared_ptr<Aws::Http::HttpRequest const>
  | m_responseCode | Aws::Http::HttpResponseCode::FORBIDDEN | Aws::Http::HttpResponseCode
  | m_hasClientError | false | bool
  | m_clientErrorType | Aws::Client::CoreErrors::INCOMPLETE_SIGNATURE | Aws::Client::CoreErrors
▶ | m_clientErrorMessage | "" | Aws::String

The call to `curl_easy_perform` returned `CURLE_OK` hence why there is no "client error".
I reveive a 403 error, somehow my ISP manages to resolve the url (but only under WSL, not windows ?)

Here's the curl verbose output:

```
curl http://some.unknown1234xxx.test.aws -v
* Rebuilt URL to: http://some.unknown1234xxx.test.aws/
*   Trying 212.95.74.75...
* TCP_NODELAY set
* Connected to some.unknown1234xxx.test.aws (212.95.74.75) port 80 (#0)
> GET / HTTP/1.1
> Host: some.unknown1234xxx.test.aws
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Date: Thu, 16 Jan 2020 14:11:15 GMT
< Server: Apache
< Content-Length: 202
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /
on this server.</p>
</body></html>
```

This seems linked to https://github.com/aws/aws-sdk-cpp/issues/1051

This means that I cannot install without going offline, using a VPN or changing my DNS...

**Comment by KaibaLopez** [comment]
Hi @Lectem ,
I'll look more into this and maybe try to modify the test, but just in case this has you blocked, you can turn off the testing by adding the cmake flag:
-DENABLE_TESTING= OFF
That way at least you'll be able to build the sdk without having to go offline or anything like that.
