### ISSUE TITLE
Document how to debug unit tests

### ISSUE THREAD

**Issue by Lectem** [aws/aws-sdk-cpp#1306]
### Which version of the SDK?

master (https://github.com/aws/aws-sdk-cpp/commit/378825e3d99ae60bf90108264d7f13b06de375d4)

### The issue

The `AUTORUN_UNIT_TESTS` cmake variable should be documented, and in general it should be documented somewhere how to debug the tests. (original PR for the variable was https://github.com/aws/aws-sdk-cpp/pull/168)
Since the tests are run as part of a post-build trigger by default, IDEs consider the build to be failed.
That means that by default any integration with an IDE will not work when trying to debug a test target, unless `AUTORUN_UNIT_TESTS` is set to `FALSE`.

I encountered this issue while trying to install the sdk (https://github.com/aws/aws-sdk-cpp/issues/1305) and it made me lose a lot of time just to figure out how to run the tests with a debugger attached.

**Comment by KaibaLopez** [comment]
Hi @Lectem ,
Yea we are trying to make a better job overall in documentation and issues like this really help point out where we are lacking.
So yea, I'll take note of that, see if I can at least add more comments or something, thanks for pointing it out and feel free to point out other things you'd like documented.
