### ISSUE TITLE
Update the "Using CMake exports with AWS sdk for C++"

### ISSUE THREAD

**Issue by Lectem** [aws/aws-sdk-cpp#1307]
The documentation points to https://aws.amazon.com/fr/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/ which suggests to use `find_package(aws-sdk-cpp)` while from what I gathered we are now supposed to use `find_package(AWSSDK)` ?

It would also be nice if the exported target were namespaced with `AWS::`. This is already the case for a few targets such as `AWS::aws-c-common` or the lambda runtime `AWS::aws-lambda-runtime`. 

Currently we have to use either the non-namespaced targets (which has known issues in cmake, as if the target doesnt exist the configuration will not fail) or `${AWSSDK_LINK_LIBRARIES}` which does not give any flexibility.

I tried modifying the `do_packaging` macro to use namespace (add `NAMESPACE AWS::` here https://github.com/aws/aws-sdk-cpp/blob/master/cmake/utilities.cmake#L70 and here https://github.com/aws/aws-sdk-cpp/blob/master/cmake/utilities.cmake#L88 ).

And it seems to work fine so far.

**Comment by KaibaLopez** [comment]
First, you're right, we should update that, thanks for pointing it out to us.
The rest would take a bit more time and discussion but does make sense, could you make a pull request with the changes you made?

**Comment by dblock** [comment]
I PRed https://github.com/awsdocs/aws-cpp-developer-guide/pull/37 and https://github.com/awsdocs/aws-doc-sdk-examples/pull/1022 that should cover the documentation changes described here.
