### ISSUE TITLE
DevicePlatform ANDROID enum error

### ISSUE THREAD

**Issue by revolushion** [aws/aws-sdk-cpp#131]
When building for android environment. the Aws::DeviceFarm:Model::DevicePlatform::ANDROID is illegal. in file aws-cpp-sdk-devicefarm/include/aws/devicefarm/model/DevicePlatform.h

**Comment by bretambrose** [comment]
We've got a fix for this queued up for review; it may be a few days before it sees release.

**Comment by JonathanHenson** [comment]
This has been updated. Feel free to update this issue if the problem persists.
