### ISSUE TITLE
Curl options aren't forwarded correctly

### ISSUE THREAD

**Issue by ingomueller-net** [aws/aws-sdk-cpp#1311]
The constructor of `CurlHttpClient` initializes its member `m_curlHandleContainer` of type `CurlHandleContainer` the [following way](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp#L433):

```cpp
    m_curlHandleContainer(clientConfig.maxConnections, clientConfig.httpRequestTimeoutMs, clientConfig.connectTimeoutMs, clientConfig.enableTcpKeepAlive,
                          clientConfig.tcpKeepAliveIntervalMs, clientConfig.requestTimeoutMs, clientConfig.lowSpeedLimit),
```

However, the [constructor of CurlHandleContainer](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/include/aws/core/http/curl/CurlHandleContainer.h#L41) looks like this:

```cpp
    CurlHandleContainer(unsigned maxSize = 50, long httpRequestTimeout = 0, long connectTimeout = 1000, bool tcpKeepAlive = true,
                        unsigned long tcpKeepAliveIntervalMs = 30000, long lowSpeedTime = 3000, unsigned long lowSpeedLimit = 1);
```

Put side by side, it seems obvious that the arguments are shifted:

```
clientConfig.maxConnections,          unsigned maxSize = 50,
clientConfig.httpRequestTimeoutMs,    long httpRequestTimeout = 0,
clientConfig.requestTimeoutMs,        long connectTimeout = 1000,
clientConfig.connectTimeoutMs,        bool tcpKeepAlive = true,
clientConfig.enableTcpKeepAlive,      unsigned long tcpKeepAliveIntervalMs = 30000,
clientConfig.tcpKeepAliveIntervalMs,  long lowSpeedTime = 3000,
clientConfig.lowSpeedLimit),          unsigned long lowSpeedLimit = 1);
```

**Comment by KaibaLopez** [comment]
Hi @ingomueller-net ,
I think you got a typo on your side by side comparison... the method calls seem to be in the correct order: 

```
m_curlHandleContainer(clientConfig.maxConnections, clientConfig.httpRequestTimeoutMs, clientConfig.connectTimeoutMs, clientConfig.enableTcpKeepAlive,
                          clientConfig.tcpKeepAliveIntervalMs, clientConfig.requestTimeoutMs, clientConfig.lowSpeedLimit)
CurlHandleContainer(unsigned maxSize = 50, long httpRequestTimeout = 0, long connectTimeout = 1000, bool tcpKeepAlive = true,
                        unsigned long tcpKeepAliveIntervalMs = 30000, long lowSpeedTime = 3000, unsigned long lowSpeedLimit = 1);
```
Or:
 
m_curlHandleContainer | clientConfig.maxConnections | clientConfig.httpRequestTimeoutMs | clientConfig.connectTimeoutMs | clientConfig.enableTcpKeepAlive | clientConfig.tcpKeepAliveIntervalMs | clientConfig.requestTimeoutMs | clientConfig.lowSpeedLimit
-- | -- | -- | -- | -- | -- | -- | --
CurlHandleContainer | unsigned maxSize = 50 | long httpRequestTimeout = 0 | long connectTimeout = 1000 | bool tcpKeepAlive = true | unsigned long   tcpKeepAliveIntervalMs = 30000 | long lowSpeedTime = 3000 | unsigned long lowSpeedLimit = 1

**Comment by ingomueller-net** [comment]
Oh, the code in master is indeed fixed -- I had made the side-by-side comparison with v1.7.138.
