### ISSUE TITLE
Issue compiling the sdk statically against musl

### ISSUE THREAD

**Issue by hfingler** [aws/aws-sdk-cpp#1312]
Has anyone tried compiling the sdk to static libraries against musl? I'm trying to but I can't seem to get it working. When I link the final libraries I get undefined symbols related to a glibc dynamic linking mechanism, which I think shouldn't be there since it's being compiled inside an Alpine container (gcc and g++ are musl target).
 Is the cmake forcing glibc somewhere? Or what could be the issue?
 This might not be an aws-sdk-cpp issue, but I thought I'd ask.
 I have a gist with a container script to compile it, am I doing something wrong?

>  https://gist.github.com/hfingler/f5597511af0ddf9d0b8ba4ca82bdf781

### What platform/OS are you using?
 Alpine:edge on Docker, x64

### Which version of the SDK?
 Latest master.

### What compiler are you using? what version?
 gcc Alpine 9.2.0 (Target: x86_64-alpine-linux-musl)

### What are your CMake arguments?
 -DBUILD_ONLY="s3;transfer" -DCMAKE_INSTALL_PREFIX=/musl -DBUILD_SHARED_LIBS=OFF -DENABLE_TESTING=OFF -DFORCE_SHARED_CRT=OFF

### Can you provide a TRACE level log? (sanitize any sensitive information)
nm libaws-cpp-sdk-core.a | grep dso_handle
 <shows many occurences of __dso_handle>

**Comment by KaibaLopez** [comment]
Hi @hfingler,
We don't really support musl so I can't guarantee we'll get it to work, but let's give it a try.

So first, why did you use `DCMAKE_INSTALL_PREFIX` ? Did you mean `-DCMAKE_PREFIX_PATH`? Or maybe try using both and point the prefix path to musl.

Second, I'm honestly not familiar with musl so I may be completely wrong but from the [FAQ page](https://www.musl-libc.org/faq.html) it says that it is not meant to work for C++: 
> Be aware that, "out of the box", the wrapper only supports C applications, not C++. 
have you tried musl with other c++ projects?

For now, I'll try to get it to work on my side and let you know if I figure something out

**Comment by hfingler** [comment]
Maybe I got confused and added DCMAKE_INSTALL_PREFIX to that line by mistake, I do need it for compiling the next step, not this one.

That sentence on the FAQ is talking about the convenience wrapper `musl-gcc`, which is a hacky way of compiling to musl while under glibc. On alpine that wrapper is not necessary since the target is natively musl (gcc -v).

I'm still looking into this, I'll report if anything changes.

**Comment by KaibaLopez** [comment]
Yea, DCMAKE_INSTALL_PREFIX would let you choose where the install happens, CMAKE_PREFIX_PATH is to help cmake find libraries, so you might've been right there.
But after some digging around, the sdk should work on musl with no extra steps. 
So a couple things,
* I just noticed something, but I might be wrong. When you call 
`mkdir -p sdkbuild && cd sdkbuild && cmake -DBUILD_ONLY="s3;transfer"`  shouldn't you be doing `cmake .. -DBUILD_ONLY="s3;transfer"` ? 
* Could you try adding `RUN apk update;` before the apk add just in case you're getting older cmake versions or something weird.
