### ISSUE TITLE
API_VERSION_HEADER': is not a member of 'Aws::Http'

### ISSUE THREAD

**Issue by mambekar** [aws/aws-sdk-cpp#1316]
### What platform/OS are you using?
Windows 10

### Which version of the SDK?
3.3.104.21
### What compiler are you using? what version?
MS Visual Studio 2019. Version 16.3.1
### What are your CMake arguments?
cmake <filepath to aws source> -G "Visual Studio 16 2019" -DSTATIC_LINKING=1 -DBUILD_ONLY="cognito-identity" -DFORCE_SHARED_CRT=OFF -DBUILD_SHARED_LIBS=OFF -DCUSTOM_MEMORY_MANAGEMENT=0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=<filepath to install directory>

### Can you provide a TRACE level log? (sanitize any sensitive information)
Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	C2039	'API_VERSION_HEADER': is not a member of 'Aws::Http'	AWS-CognitoTest	C:\Users\mambekar\Desktop\WorkSpace\OneMoreTech\AWS\AWS-Build\include\aws\cognito-identity\CognitoIdentityRequest.h	41		

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	C2065	'API_VERSION_HEADER': undeclared identifier	AWS-CognitoTest	C:\Users\mambekar\Desktop\WorkSpace\OneMoreTech\AWS\AWS-Build\include\aws\cognito-identity\CognitoIdentityRequest.h	41		

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	C2672	'std::_Tree<std::_Tmap_traits<_Kty,_Ty,_Pr,_Alloc,false>>::emplace': no matching overloaded function found
        with
        [
            _Kty=Aws::String,
            _Ty=Aws::String,
            _Pr=std::less<Aws::String>,
            _Alloc=std::allocator<std::pair<const Aws::String,Aws::String>>
        ]	AWS-CognitoTest	C:\Users\mambekar\Desktop\WorkSpace\OneMoreTech\AWS\AWS-Build\include\aws\cognito-identity\CognitoIdentityRequest.h	41

**Comment by KaibaLopez** [comment]
Hi @mambekar ,
I'm not able to reproduce your error, can you tell me the version of the sdk you're using? (newest is 1.7.266).

**Comment by mambekar** [comment]
Hello @KaibaLopez,
The version is "1.7.258".

Appreciate your quick response.

**Comment by KaibaLopez** [comment]
Hmmm, still can't reproduce the error...
Couple questions, have you ever built the sdk successfully or does this error only happen on Cognito?
Could you try building for example:
```
cmake -G "Visual Studio 16 2019" -DBUILD_ONLY=s3
msbuild ALL_BUILD.vcxproj
```

Also, could you share your cmake output when you run for cognito? are there any errors there or you only get errors on build?

**Comment by mambekar** [comment]
I rebuilt Cognito again and have attached the files.. 
[20200204-AWS-Cognito-CMake.txt](https://github.com/aws/aws-sdk-cpp/files/4154107/20200204-AWS-Cognito-CMake.txt)
[20200204-AWS-Cognito-Install.txt](https://github.com/aws/aws-sdk-cpp/files/4154108/20200204-AWS-Cognito-Install.txt)
[20200204-AWS-Cognito-Build.txt](https://github.com/aws/aws-sdk-cpp/files/4154109/20200204-AWS-Cognito-Build.txt)


I will build the S3 shortly and will let you know.

**Comment by mambekar** [comment]
S3 Build details - has errors during the build as it is not able to find common and event dlls.
Logs Attached ..
1. S3  cmake output 
[20200204-AWS-S3-CMake.txt](https://github.com/aws/aws-sdk-cpp/files/4154280/20200204-AWS-S3-CMake.txt)

2. S3 build errors

[20200204-AWS-S3-Build.txt](https://github.com/aws/aws-sdk-cpp/files/4154293/20200204-AWS-S3-Build.txt)

3. Missing dlls exception

![20200204-AWS-S3-BuildError-MissingDll-1](https://user-images.githubusercontent.com/60618001/73759104-0b7e0800-4731-11ea-8432-3bd7b32aabd9.PNG)

![20200204-AWS-S3-BuildError-MissingDll-2](https://user-images.githubusercontent.com/60618001/73759117-1042bc00-4731-11ea-90c3-8bbce8e48d2c.PNG)

[20200204-AWS-S3-CMake-Take2AfterBuildFail.txt](https://github.com/aws/aws-sdk-cpp/files/4154296/20200204-AWS-S3-CMake-Take2AfterBuildFail.txt)

**Comment by KaibaLopez** [comment]
hmmm ok, so I think I misunderstood the point at which you got the header error, from your logs on Cognito at least, it looks like you were able to build correctly, so when exactly are you seeing this error? are you having problems linking the library for your project? 

And on the s3 one... I think that happened because you built on the same folder and on your first built the dependencies were built as static, but the second time (since the cmake command I provided didn't specify) it looked for them as shared.

**Comment by mambekar** [comment]
That's right.. 
I have a created a simple program(listed below) to request Cognito token by including all the libraries and include files.
When I build this file, I see the linker error for Aws::Http::API_VERSION_HEADER in CognitoIdentityRequest.h (which is AWS file)

I'm not sure if this "API_VERSION_HEADER" is still defined in the namespace Aws::Http. I couldn't find the definition of this literal in the aws-sdk-cpp code base.

**Function requesting token**

std::string  Aws_CognitoDevIdMgmt::GetToken(void)
{
	std::string RetVal = "ERROR";

	// initialize a cognito client with AWS developer credentials
	AWSCredentials MyCredentials("access_Key_Id", "secret_access_key");
	Aws::CognitoIdentity::CognitoIdentityClient IdentityClient (MyCredentials);

	// create a new request to retrieve the token for end user
	GetOpenIdTokenForDeveloperIdentityRequest TokenRequest;

	// optional - set token duration in seconds
	TokenRequest.SetTokenDuration(15 * 60);

	GetOpenIdTokenForDeveloperIdentityOutcome  Response = IdentityClient.GetOpenIdTokenForDeveloperIdentity(TokenRequest);
	if (Response.IsSuccess())
	{
		GetOpenIdTokenForDeveloperIdentityResult TokenResponse = Response.GetResult();
		std::string  Identity = TokenResponse.GetIdentityId();
		RetVal = TokenResponse.GetToken();
	}

	return RetVal;
}

**Comment by KaibaLopez** [comment]
Ok, so I was able to compile your code, I never got your header error though, I think you might be missing some includes or namespaces, does this compile for you?
```
#include <aws/core/auth/AWSCredentials.h>
#include <aws/core/utils/Outcome.h>

#include <aws/cognito-identity/CognitoIdentityClient.h>
#include <aws/cognito-identity/model/GetOpenIdTokenForDeveloperIdentityRequest.h>
#include <aws/cognito-identity/model/GetOpenIdTokenForDeveloperIdentityResult.h>
#include <aws/cognito-identity/CognitoIdentityErrors.h>

#include <aws/core/client/CoreErrors.h>
#include <aws/core/utils/json/JsonSerializer.h>
std::string GetToken(void)
{
	std::string RetVal = "ERROR";

	// initialize a cognito client with AWS developer credentials
	Aws::Auth::AWSCredentials MyCredentials("access_Key_Id", "secret_access_key");
	Aws::CognitoIdentity::CognitoIdentityClient IdentityClient(MyCredentials);

	// create a new request to retrieve the token for end user
	Aws::CognitoIdentity::Model::GetOpenIdTokenForDeveloperIdentityRequest TokenRequest;

	// optional - set token duration in seconds
	TokenRequest.SetTokenDuration(15 * 60);

	Aws::CognitoIdentity::Model::GetOpenIdTokenForDeveloperIdentityOutcome  Response = IdentityClient.GetOpenIdTokenForDeveloperIdentity(TokenRequest);
	if (Response.IsSuccess())
	{
		Aws::CognitoIdentity::Model::GetOpenIdTokenForDeveloperIdentityResult TokenResponse = Response.GetResult();
		std::string  Identity = TokenResponse.GetIdentityId();
		RetVal = TokenResponse.GetToken();
	}

	return RetVal;

}
```

**Comment by mambekar** [comment]
I have exactly the same code and include files and still see the same error.. I'm building for Debug & x64.

I have included these libs
aws-c-common.lib
aws-c-event-stream.lib
aws-checksums.lib
aws-cpp-sdk-access-management.lib
aws-cpp-sdk-cognito-identity.lib
aws-cpp-sdk-core.lib
aws-cpp-sdk-iam.lib

Is there any other lib that needs to  be included ?
Where is API_HEADER_VERSION defined ? which file ?

In CognitoIdentityRequest.h - why does the reference to Aws::Http::CONTENT_TYPE_HEADER  not complain ? Snippet listed below.


 if(headers.size() == 0 || (headers.size() > 0 && headers.count(Aws::Http::CONTENT_TYPE_HEADER) == 0))
      {
        headers.emplace(Aws::Http::HeaderValuePair(Aws::Http::CONTENT_TYPE_HEADER, Aws::AMZN_JSON_CONTENT_TYPE_1_1 ));
      }
      headers.emplace(Aws::Http::HeaderValuePair(Aws::Http::API_VERSION_HEADER, "2014-06-30"));
      return headers;

**Comment by KaibaLopez** [comment]
Ok I think I've found your error,
go to your project properties, under Configurations properties > C++ > Preprocessor > Preprocessor definitions and add: 
```
USE_WINDOWS_DLL_SEMANTICS
USE_IMPORT_EXPORT
```

Let me know if that fixed it.

**Comment by mambekar** [comment]
Sorry, it did not fix the issue. I still see the same errors.. 

If you have time, we can conference and find out the issue.

**Comment by mambekar** [comment]
These are the compile time errors.. 
```
1>------ Rebuild All started: Project: AWS-CognitoTest, Configuration: Debug x64 ------
1>AWS_CognitoDevIdMgmt.cpp
1>C:\Users\mambekar\Desktop\WorkSpace\OneMoreTech\.nuget\packages\AWSSDKCPP-Core.1.6.25\build\native\include\aws\core\utils\stream\ResponseStream.h(71,13): warning C4275: non dll-interface class 'std::ios_base' used as base for dll-interface class 'std::basic_ios<char,std::char_traits<char>>'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.23.28105\include\xiosbase(168): message : see declaration of 'std::ios_base'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.23.28105\include\iosfwd(213): message : see declaration of 'std::basic_ios<char,std::char_traits<char>>'
1>C:\Users\mambekar\Desktop\WorkSpace\OneMoreTech\AWS\AWS-Build\include\aws\cognito-identity\CognitoIdentityRequest.h(41,61): error C2039: 'API_VERSION_HEADER': is not a member of 'Aws::Http'
1>C:\Users\mambekar\Desktop\WorkSpace\OneMoreTech\.nuget\packages\AWSSDKCPP-Core.1.6.25\build\native\include\aws\core\AmazonWebServiceRequest.h(30): message : see declaration of 'Aws::Http'
1>C:\Users\mambekar\Desktop\WorkSpace\OneMoreTech\AWS\AWS-Build\include\aws\cognito-identity\CognitoIdentityRequest.h(41,1): error C2065: 'API_VERSION_HEADER': undeclared identifier
1>C:\Users\mambekar\Desktop\WorkSpace\OneMoreTech\AWS\AWS-Build\include\aws\cognito-identity\CognitoIdentityRequest.h(41,14): error C2672: 'std::_Tree<std::_Tmap_traits<_Kty,_Ty,_Pr,_Alloc,false>>::emplace': no matching overloaded function found
1>C:\Users\mambekar\Desktop\WorkSpace\OneMoreTech\AWS\AWS-Build\include\aws\cognito-identity\CognitoIdentityRequest.h(41,14): error C2672:         with
1>C:\Users\mambekar\Desktop\WorkSpace\OneMoreTech\AWS\AWS-Build\include\aws\cognito-identity\CognitoIdentityRequest.h(41,14): error C2672:         [
1>C:\Users\mambekar\Desktop\WorkSpace\OneMoreTech\AWS\AWS-Build\include\aws\cognito-identity\CognitoIdentityRequest.h(41,14): error C2672:             _Kty=Aws::String,
1>C:\Users\mambekar\Desktop\WorkSpace\OneMoreTech\AWS\AWS-Build\include\aws\cognito-identity\CognitoIdentityRequest.h(41,14): error C2672:             _Ty=Aws::String,
1>C:\Users\mambekar\Desktop\WorkSpace\OneMoreTech\AWS\AWS-Build\include\aws\cognito-identity\CognitoIdentityRequest.h(41,14): error C2672:             _Pr=std::less<Aws::String>,
1>C:\Users\mambekar\Desktop\WorkSpace\OneMoreTech\AWS\AWS-Build\include\aws\cognito-identity\CognitoIdentityRequest.h(41,14): error C2672:             _Alloc=std::allocator<std::pair<const Aws::String,Aws::String>>
1>C:\Users\mambekar\Desktop\WorkSpace\OneMoreTech\AWS\AWS-Build\include\aws\cognito-identity\CognitoIdentityRequest.h(41,14): error C2672:         ]
1>Done building project "AWS-CognitoTest.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

```

**Comment by KaibaLopez** [comment]
Sorry but I can't really do a conference...
But so far, from the logs, I can tell that you're building the sdk correctly, there is just something that you're missing on your project for linking them, so here's the list I usually go through, let's see if something there is missing. 
* Adding the additional include Directories for each of the services: (sdk's directory/aws-cpp-sdk-core/include)
* Preprocessor Definitions.
* Additional Library directories for each of the services: (build directory/aws-cpp-sdk-core/Debug)
* Additional Dependencies (the .libs you mentioned are enough)
* If you didn't install after build, then you also need to bring the .dll's (dependencies of each service's) and put them in your executable folder.
* make sure you're building the project in the same way you built the libraries, (Debug, Release, static, etc.).
I'm sorry I can't be of much more help, but it is really me shooting in the dark since the error is dependent on your project's settings rather than the sdk's not building properly :/

**Comment by jbuttkicker** [comment]
I have just examined the aws-ccp-sdk-core.dll from NuGet package AWSSDKCPP-Core.redist.1.6.25 from build\native\bin\x64\Debug\v140\dynamic using DEPENDS utililty.
https://www.nuget.org/packages/AWSSDKCPP-Core.redist
The following are exported
char const * const Aws::Http::ACCEPT_CHAR_SET_HEADER
char const * const Aws::Http::ACCEPT_ENCODING_HEADER
char const * const Aws::Http::ACCEPT_HEADER
char const * const Aws::Http::AMZ_TARGET_HEADER
char const * const Aws::Http::AUTHORIZATION_HEADER
char const * const Aws::Http::AWS_AUTHORIZATION_HEADER
char const * const Aws::Http::AWS_DATE_HEADER
char const * const Aws::Http::AWS_SECURITY_TOKEN
char const * const Aws::Http::CONTENT_LENGTH_HEADER
char const * const Aws::Http::CONTENT_MD5_HEADER
char const * const Aws::Http::CONTENT_TYPE_HEADER
char const * const Aws::Http::COOKIE_HEADER
char const * const Aws::Http::DATE_HEADER
char const * const Aws::Http::HOST_HEADER
char const * const Aws::Http::SEPARATOR
char const * const Aws::Http::USER_AGENT_HEADER
char const * const Aws::Http::VIA_HEADER
char const * const Aws::Http::X_AMZ_EXPIRES_HEADER

But there is no indication of API_VERSION_HEADER exported from the DLL.

**Comment by jbuttkicker** [comment]
I resolved my problems.  I was using published AWSSDKCPP Core nuget packages from 1.6.x which are incompatible with newly released components like AWS AppConfig which are only in 1.7.x
I had to abandon the published nuget packages to get a core dll with the API_VERSION_HEADER exported.

**Comment by KaibaLopez** [comment]
Great news that you found your issue, sorry I couldn't be of much help, but yea we no longer support the nuget packages, only vcpckg.

**Comment by mambekar** [comment]
Thankyou very much..
I'm finally able to build without linker issues.
