### ISSUE TITLE
Static builds fails to load awssdk package

### ISSUE THREAD

**Issue by kkbachu** [aws/aws-sdk-cpp#1318]
When I build my project statically after editing my cmakelists.txt file to include find_package(AWSSDK REQUIRED COMPONENTS S3), cmake fails with below. I tried passing CMAKE_PREFIX_PATH and CMAKE_INSTALL_PREFIX after looking around but no luck.
If I pass BUILD_SHARED_LIBS=ON to my build, cmake works but its globally applied to my project which we don't want.

I built and installed the SDK in /usr/local/lib by default.
cmake ../aws-sdk-cpp -DBUILD_ONLY=s3

Workaround:
 sudo vi /usr/local/lib/cmake/AWSSDK/AWSSDKConfig.cmake
 set(BUILD_SHARED_LIBS "on")

If I need to follow some steps, I will be happy to try it out.

### What platform/OS are you using?
Ubuntu
### Which version of the SDK?
Found AWS SDK for C++, Version: 1.7.266

### What compiler are you using? what version?
C++ 11
### What are your CMake arguments?
cmake ../aws-sdk-cpp -DBUILD_ONLY=s3

### Can you provide a TRACE level log? (sanitize any sensitive information)

-- Found AWS SDK for C++, Version: 1.7.266, Install Root:/usr/local, Platform Prefix:, Platform Dependent Libraries: pthread;crypto;ssl;z;curl
-- Components specified for AWSSDK: s3, application wll be depending on libs: aws-cpp-sdk-s3;aws-cpp-sdk-core
-- Try finding aws-cpp-sdk-core
CMake Error at /usr/local/lib/aws-c-common/cmake/aws-c-common-config.cmake:7 (include):
  include could not find load file:

    /usr/local/lib/aws-c-common/cmake/static/aws-c-common-targets.cmake
Call Stack (most recent call first):
  /usr/local/share/cmake-3.9/Modules/CMakeFindDependencyMacro.cmake:37 (find_package)
  /usr/local/lib/aws-c-event-stream/cmake/aws-c-event-stream-config.cmake:2 (find_dependency)
  /usr/local/share/cmake-3.9/Modules/CMakeFindDependencyMacro.cmake:37 (find_package)
  /usr/local/lib/cmake/aws-cpp-sdk-core/aws-cpp-sdk-core-config.cmake:2 (find_dependency)
  /usr/local/lib/cmake/AWSSDK/AWSSDKConfig.cmake:303 (find_package)
  dmn/sobject/CMakeLists.txt:161 (find_package)

CMake Error at /usr/local/lib/aws-checksums/cmake/aws-checksums-config.cmake:4 (include):
  include could not find load file:

    /usr/local/lib/aws-checksums/cmake/static/aws-checksums-targets.cmake
Call Stack (most recent call first):
  /usr/local/share/cmake-3.9/Modules/CMakeFindDependencyMacro.cmake:37 (find_package)
  /usr/local/lib/aws-c-event-stream/cmake/aws-c-event-stream-config.cmake:3 (find_dependency)
  /usr/local/share/cmake-3.9/Modules/CMakeFindDependencyMacro.cmake:37 (find_package)
  /usr/local/lib/cmake/aws-cpp-sdk-core/aws-cpp-sdk-core-config.cmake:2 (find_dependency)
  /usr/local/lib/cmake/AWSSDK/AWSSDKConfig.cmake:303 (find_package)
  dmn/sobject/CMakeLists.txt:161 (find_package)

CMake Error at /usr/local/lib/aws-c-event-stream/cmake/aws-c-event-stream-config.cmake:8 (include):
  include could not find load file:

    /usr/local/lib/aws-c-event-stream/cmake/static/aws-c-event-stream-targets.cmake
Call Stack (most recent call first):
  /usr/local/share/cmake-3.9/Modules/CMakeFindDependencyMacro.cmake:37 (find_package)
  /usr/local/lib/cmake/aws-cpp-sdk-core/aws-cpp-sdk-core-config.cmake:2 (find_dependency)
  /usr/local/lib/cmake/AWSSDK/AWSSDKConfig.cmake:303 (find_package)
  dmn/sobject/CMakeLists.txt:161 (find_package)

**Comment by KaibaLopez** [comment]
Hi @kkbachu ,
I'm a bit confused on what you're trying to do, and when you're getting this error. It sounds like the problem is that you are trying to use the sdk as a static library when it by default builds as shared.
 
If you want to build and use the sdk as a static library, then you'd have to add -DBUILD_SHARED=OFF when you build the sdk.
`cmake ../aws-sdk-cpp -DBUILD_ONLY=s3 -DBUILD_SHARED=OFF`

Let me know if this helped or what I'm missing.

**Comment by kkbachu** [comment]
Thanks @KaibaLopez for quick response.

I am building a static binary but it requires few .so libraries via find_package(). For eg.,
-- fuse: /usr/include
-- libfuse: /usr/lib/x86_64-linux-gnu/libfuse.so
When I do the samething for awssdk that is installed in /usr/local/lib, it does find this /usr/local/lib/cmake/AWSSDK/AWSSDKConfig.cmake:303 (find_package) but dependent makefiles it looks in a static directory usr/local/lib/aws-c-common/cmake/static/aws-c-common-targets.cmake.  So, after much looking around, I changed AWSSDKConfig.cmake to set BUILD_SHARED_LIBS=on as workaround, then everything works. 
I understand that I need to build sdk statically but not necessary for what i am doing. Just wondering - how to use sdk that is built with BUILD_SHARED_LIBS=ON but find_package(sdk) is called from a static build of the application that is trying to use the dynamic sdk.

**Comment by KaibaLopez** [comment]
hmm so unless I'm getting your question wrong, in which case sorry in advance, you're having a problem because even though you are able to use the shared libs of the sdk, the shared lib flag is not passed down to the sdk's find_package() and so it looks for static libraries for the sdk's dependencies?
 
I think your "workaround" is a good solution honestly, since you're mixing static and shared builds I don't think you can use find_package() in a simple way, specially in cases like this sdk where it's like a project within a project.

But maybe we could change something in the config file to add this.... Could you share your cmakelists.txt? or a mock one to replicate this behavior?

**Comment by KaibaLopez** [comment]
Hi @kkbachu ,
As an update, after some digging we came to the conclusion this is more of a limitation on cmake with multiple projects and mixing shared and static builds than an error with the sdk, so for now I'm afraid the workaround will have to do.
Thanks for pointing it out and sorry I can't give you better news on that.
