### ISSUE TITLE
cognito credentials provider refresh bug

### ISSUE THREAD

**Issue by mistrmistr** [aws/aws-sdk-cpp#132]
The CognitoCachingCredentialsProvider has logic to refresh your cognito credentials when they are about to expire.  To determine this, the following function is called

bool CognitoCachingCredentialsProvider::IsTimeExpired(double expiry)
{
    using namespace std::chrono;
    //30s grace buffer so requests have time to finish before expiry.
    static const double GRACE_BUFFER = 30.0;   

    return expiry < (Utils::DateTime::ComputeCurrentTimestampInAmazonFormat() - GRACE_BUFFER);
}

Shouldn’t that minus sign be a plus?  We want to start the refresh 30 units of time before they expire, not after, correct?  (Or change the < to > but then you will have to deal with initial expiry of 0.0)

**Comment by bretambrose** [comment]
Logically, what you're saying seems correct; not sure how it wasn't noticed until now since it implies a 30 second dead period every 15 minutes or so where requests should always fail.

**Comment by mistrmistr** [comment]
The default cognito credentials expiration is one hour, so your session would have to last at least that long.  We only noticed it in systems that require frequent heartbeating being starved every hour or so.

**Comment by JonathanHenson** [comment]
We pushed a change for this this morning. Can you have a look and see if this works for you. Reopen if you still have a problem.
