### ISSUE TITLE
Why are the URLEncodes inconsistently applied during MultiPartCopy

### ISSUE THREAD

**Issue by rahul003** [aws/aws-sdk-cpp#1320]
Hello, 

In UploadPartCopyRequest there's a URLEncode for the x-amz-copy-source field. I'm running into issues here. S3 responds saying the object doesn't exist whereas it does. On digging further I found this line.
https://github.com/aws/aws-sdk-cpp/blame/master/aws-cpp-sdk-s3/source/model/UploadPartCopyRequest.cpp#L101

https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPartCopy.html#API_UploadPartCopy_RequestSyntax

Does the S3 documentation says the bucket and object must be separated by /, and the object key name must be URL encoded. Isn't it? How come the other x-amz-copy-source-... fields don't encode the path?

**Comment by rahul003** [comment]
@marcomagdy Could you please take a look

**Comment by KaibaLopez** [comment]
Hi @rahul003 ,
I'm not super sure on what you mean here, could you clarify a bit? Or even better if you could give me some sample code or logs that show the problem you're having?
