### ISSUE TITLE
SIGSEGV in multipart upload

### ISSUE THREAD

**Issue by kreuzerkrieg** [aws/aws-sdk-cpp#1322]
- What platform/OS are you using?
Ubuntu 18.04 x64
- Which version of the SDK?
#define AWS_SDK_VERSION_STRING "1.7.111"
- What compiler are you using? what version?
GCC 9.2.1
- What are your CMake arguments?
CMAKE_ARGS  -G${CMAKE_GENERATOR}
                -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
                -DBUILD_ONLY:String=transfer$<SEMICOLON>s3
                -DBUILD_SHARED_LIBS:BOOL=OFF
                -DENABLE_TESTING:BOOL=OFF
                -DOPENSSL_INCLUDE_DIR=${OPENSSL_INCLUDE_DIR}
                -DOPENSSL_CRYPTO_LIBRARY=${OPENSSL_CRYPTO_LIBRARY_FILE} #For testing only
                -DOPENSSL_SSL_LIBRARY=${OPENSSL_SSL_LIBRARY_FILE} #For testing only
                -DCURL_INCLUDE_DIR=${CMAKE_SOURCE_DIR}/contrib/curl/include/
                -DCURL_LIBRARY=$<TARGET_FILE:libcurl> #For testing only
                -DCUSTOM_MEMORY_MANAGEMENT=ON

The callstack:
#0  std::__future_base::_State_baseV2::wait (this=0x289487273c52f114) at /usr/include/c++/9/future:334
#1  std::__basic_future<Aws::Utils::Outcome<Aws::S3::Model::UploadPartResult, Aws::Client::AWSError<Aws::S3::S3Errors> > >::_M_get_result (this=0x7f3470ee5e20) at /usr/include/c++/9/future:717
#2  std::future<Aws::Utils::Outcome<Aws::S3::Model::UploadPartResult, Aws::Client::AWSError<Aws::S3::S3Errors> > >::get (this=0x7f3470ee5e20) at /usr/include/c++/9/future:796

**Comment by KaibaLopez** [comment]
Hi @kreuzerkrieg,
I'm guessing this error is happening on build, but this description is a bit confusing so let me ask you a few questions:
Have you installed all the requirements for the sdk? (libssl-dev & curl).
Is there a reason why you can't use the latest sdk version? 
Can you upload the full output from the cmake call? (preferably as a .txt file).

**Comment by kreuzerkrieg** [comment]
I think there is a misunderstanding.
No build problem there. Just banal segmentation fault when I'm running the upload to S3, something like once in 10M calls to the SDK. The the call-stack in the initial question

**Comment by KaibaLopez** [comment]
@kreuzerkrieg 
Ah I see, sorry about that, could you provide a sample of the code you're using?
Specifically I want to know how you're calling wait, although unlikely I still would like to see if we can deduce an edge case from it.

**Comment by kreuzerkrieg** [comment]
Will post the code tomorrow, but it is not something special, initialize multi-part upload, upload each part asynchronously, gather `std::feature` or as you call it `UploadPartOutcomeCallable` then call `get` on it. Then, once in a 1M to 10M calls to `get()` we get segmentation. I was hoping there is known issue which is fixed in latest version and the fix will be as easy as upgrading to latest. Alas! :)

**Comment by kreuzerkrieg** [comment]
> @kreuzerkrieg
> Ah I see, sorry about that, could you provide a sample of the code you're using?
> Specifically I want to know how you're calling wait, although unlikely I still would like to see if we can deduce an edge case from it.

[Here you go](https://github.com/kreuzerkrieg/CPPJunk/blob/master/SlowDown/S3MultipartUploader.cpp)

**Comment by kreuzerkrieg** [comment]
@KaibaLopez 
Confirmed, the above tester given enough time uploading stuff leads to segmentation fault. I've launched it on 32 instances in EC2, it took ~3 hours for first two instances to fail.
The complete tester is [here](https://github.com/kreuzerkrieg/CPPJunk/tree/master/SlowDown) 
The core dump from one of instances is [here](https://1drv.ms/u/s!AvKB-sqTwjdHhp9VoYrDspsK5kTGsg?e=6ppNbM)

**Comment by KaibaLopez** [comment]
Hi @kreuzerkrieg ,
Thanks, this is all great info and really appreciate you going through the trouble!

**Comment by kreuzerkrieg** [comment]
Additional input, all external libraries (openssl, curl, aws-sdk) were provided by [vcpkg](https://github.com/microsoft/vcpkg)
