### ISSUE TITLE
Fail to build in Windows 10 using VS 2019 

### ISSUE THREAD

**Issue by miryee** [aws/aws-sdk-cpp#1323]
### What platform/OS are you using?
Windows 10

### Which version of the SDK?
current (Master)

### What compiler are you using? what version?
msbuild 16.3.2.50909 (VS 2019)

### What are your CMake arguments?
cmake d:\Projects\GitHub\aws-sdk-cpp -G "Visual Studio 16 2019" -DSTATIC_LINKING=1 -DBUILD_ONLY="s3" -DFORCE_SHARED_CRT=OFF -DBUILD_SHARED_LIBS=OFF -DCUSTOM_MEMORY_MANAGEMENT=0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_WIN32_EXECUTABLE=TRUE -DCMAKE_INSTALL_PREFIX=D:\Projects\awssdkcpp_build\out

### Can you provide a TRACE level log? (sanitize any sensitive information)
[aws_build_log_202002181704_latest.log](https://github.com/aws/aws-sdk-cpp/files/4222157/aws_build_log_202002181704_latest.log)
`Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:"D:\Projects\awssdkcpp_build\bi
  n\Debug\aws-cpp-sdk-s3-integration-tests.exe" /INCREMENTAL /NOLOGO "..\aws-cpp-sdk-s3\Debug\aws-cpp-sdk-s3.lib" "..\testing-resources\Debug\testing-resources.lib" "..\aws-
  cpp-sdk-core\Debug\aws-cpp-sdk-core.lib" Wininet.lib winhttp.lib Bcrypt.lib "..\out\lib\aws-c-event-stream.lib" "..\out\lib\aws-c-common.lib" BCrypt.lib Kernel32.lib Ws2_3
  2.lib "..\out\lib\aws-checksums.lib" Userenv.lib version.lib ws2_32.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32
  .lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Projects/awssdkcpp_build/bin/Debug/aws-cpp-sdk-s3-integration
  -tests.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Projects/awssdkcpp_build/aws-cpp-sdk-s3-integration-tests/Debug/aws-cpp-sdk-s3-integration-tests
  .lib" /MACHINE:X64  /machine:x64 "aws-cpp-sdk-s3-integration-tests.dir\Debug\BucketAndObjectOperationTest.obj"
  "aws-cpp-sdk-s3-integration-tests.dir\Debug\RunTests.obj"
LIBCMTD.lib(exe_winmain.obj) : error LNK2019: unresolved external symbol WinMain referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ) [D:\Projects\aw
ssdkcpp_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
D:\Projects\awssdkcpp_build\bin\Debug\aws-cpp-sdk-s3-integration-tests.exe : fatal error LNK1120: 1 unresolved externals [D:\Projects\awssdkcpp_build\aws-cpp-sdk-s3-integrat
ion-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
Done Building Project "D:\Projects\awssdkcpp_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj" (default targets) -- FAILED.

Done Building Project "D:\Projects\awssdkcpp_build\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Build FAILED.

"D:\Projects\awssdkcpp_build\ALL_BUILD.vcxproj" (default target) (1) ->
"D:\Projects\awssdkcpp_build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj" (default target) (4) ->
(Link target) ->
  LIBCMTD.lib(exe_winmain.obj) : error LNK2019: unresolved external symbol WinMain referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ) [D:\Projects\
awssdkcpp_build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]
  D:\Projects\awssdkcpp_build\bin\Debug\aws-cpp-sdk-core-tests.exe : fatal error LNK1120: 1 unresolved externals [D:\Projects\awssdkcpp_build\aws-cpp-sdk-core-tests\aws-cpp-
sdk-core-tests.vcxproj]

"D:\Projects\awssdkcpp_build\ALL_BUILD.vcxproj" (default target) (1) ->
"D:\Projects\awssdkcpp_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj" (default target) (7) ->
  LIBCMTD.lib(exe_winmain.obj) : error LNK2019: unresolved external symbol WinMain referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ) [D:\Projects\
awssdkcpp_build\aws-cpp-sdk-s3-integration-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]
  D:\Projects\awssdkcpp_build\bin\Debug\aws-cpp-sdk-s3-integration-tests.exe : fatal error LNK1120: 1 unresolved externals [D:\Projects\awssdkcpp_build\aws-cpp-sdk-s3-integr
ation-tests\aws-cpp-sdk-s3-integration-tests.vcxproj]

    0 Warning(s)
    4 Error(s)`

This is possibly related to issue #1276 or #1254 .  The difference between the cmake command I used for this build and the one in #1276 that I reported back in November, is that I am forcing a build for Win32 (it seems to default to x64 now) with the -DCMAKE_WIN32_EXECUTABLE=TRUE flag.  Disabling testing causes the build to succeed.

**Comment by miryee** [comment]
I found an additional problem trying to build my application with the SDK.  Before forcing win32, I had all 5 modules fail in my app build.  After forcing win32 (and disabling the core and integration tests), I still have 1 of the 5 modules failing to build with the same error:

`aws-cpp-sdk-core.lib(HttpRequest.obj) : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'`

**Comment by dcorderoch-el** [comment]
I thought this was related to the issue I'm currently having, but it isn't, BUT the `CMAKE_WIN32_EXECUTABLE` option is NOT for 32-bit builds, you want the `-A Win32` option, see https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2016%202019.html

**Comment by miryee** [comment]
Thanks but it still has the same errors with the -A Win32.

**Comment by miryee** [comment]
Gotcha.  That solved my issues.  Thanks!

**Comment by miryee** [comment]
FYI even AWS documents that the win32 attribute was not necessary in previous versions.  I suspect this was an AWS change, since I am still using the same version of cmake as when I originally built this SDK.  This was a very time-consuming issue to understand why it suddenly broke, and then find the fix.

> on it as below to create the make files for msbuild to operate on:

> 
> cmake -G "Visual Studio 15 2017 Win64"
> If you remove the Win64 part, it will build 32 bit. You can find more info on build options here: 

> https://cmake.org/cmake/help/v3.7/manual/cmake-generators.7.html

from https://aws.amazon.com/blogs/gametech/how-to-build-and-integrate-the-aws-sdk-for-c-games-on-windows/
