### ISSUE TITLE
Sample AWS C++ code to get Cognito token after server authenticates user 

### ISSUE THREAD

**Issue by mambekar** [aws/aws-sdk-cpp#1325]
### What platform/OS are you using?
Windows 10
### Which version of the SDK?
aws-sdk-cpp-1.7.219

### What compiler are you using? what version?
MS Visual Studio 2019. Version 16.3.1

### What are your CMake arguments?
cmake -G "Visual Studio 16 2019" -DSTATIC_LINKING=1 -DBUILD_ONLY="s3;cognito-identity" -DFORCE_SHARED_CRT=OFF -DBUILD_SHARED_LIBS=OFF -DCUSTOM_MEMORY_MANAGEMENT=0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=

**Comment by mambekar** [comment]
Sample C++ code to get Cognito token.
Context : After Server authenticates the user, Server requests tokens from AWS cognito and issues it to the user.

**Comment by KaibaLopez** [comment]
Hi @mambekar,
I'll be honest, this might take me a bit to get around to but I'll come up with a code sample if you give me some time.
While I do that though, you might want to take a look at aws-cpp-sdk-cognitoidentity-integration-tests/IdentityOperationTests.cpp to get ideas on how it works.
Oh and also, if you're feeling extra nice and get a sample working you might want to do a pull request to the [samples repo](https://github.com/awsdocs/aws-doc-sdk-examples), up to you.
