### ISSUE TITLE
Question: How does SSE-KMS with customer managed CMK works when Get() objects?

### ISSUE THREAD

**Issue by lsong0905** [aws/aws-sdk-cpp#1327]
Hello,

I am testing SSE-KMS with customer managed CMK feature for my application. 
I was able to Put() objects with SSE-KMS with customer managed CMK, and as described in the article (https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingKMSEncryption.html), I did not have to provide any information about encryption when Get() the encrypted objects, and was able to retrieve the object. 
I am wondering how the sdk (and other layers below) handles the validation process without the encryption key when tries to Get() the encrypted objects.

Thanks.

**Comment by KaibaLopez** [comment]
Hi @lsong0905 ,
Just to be clear here, you're not facing any problems when using the service, but you're curious on how it works? Is there anything specific about it that interest you? Like,performance or ?

**Comment by lsong0905** [comment]
@KaibaLopez No. I have not encountered any issue yet. So far, Put() with SSE-KMS (customer managed CMK) and Get() are working ok. I am curious how the validation process works when tries to Get() an encrypted object with SSE-KMS (customer managed CMK).
