### ISSUE TITLE
Are there plans to support the Polly.Presigner (available in JavaScript SDK) in C++?

### ISSUE THREAD

**Issue by dcrogers333** [aws/aws-sdk-cpp#1329]
### What platform/OS are you using?
ReSpeaker Core v2 (based on Rockchip ARM processor)
Debian GNU/Linux 9

### Which version of the SDK?
Latest checkout from github as of 27-Feb-2020

### What compiler are you using? what version?
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

### What are your CMake arguments?
NA

### Can you provide a TRACE level log? (sanitize any sensitive information)
NA

The JavaScript SDK has a "Polly Presigner" that returns a URL rather than audio. Are there plans toexpose this capability in the C++ SDK?

**Comment by KaibaLopez** [comment]
Hi @dcrogers333 ,
well... no. 
But! It does sound like a cool thing to add so we'll take it as a feature request, having this kind of issues asking for it does help too so thanks.
Oh and we also welcome contributions, so if you think you can make it happen feel free to make a pull request.

**Comment by kdjani** [comment]
@KaibaLopez interested in helping. Would like to learn more about the problem and would like to have pointers for setting up the dev environment. I am C++ veteran on Windows and have decent familiarity with Linux. As far as hardware goes, I have a x64 machine running Windows with Ubuntu installed. I have an old Macbook air as well.

**Comment by KaibaLopez** [comment]
Hi @kdjani ,
To contribute you'd have to fork the repo and make a pull request, no requirements really, other than following our contributions guideline at the end of the README.
