### ISSUE TITLE
EC2Client.cpp fails to build on 32bit host

### ISSUE THREAD

**Issue by crawlins** [aws/aws-sdk-cpp#133]
I attempted to build aws-sdk-cpp on a raspberry pi host, (which is 32bit) and regardless of making 10G of swap space available the build fails with an out of memory error.  I am pretty sure this is because the compiler ran out of virtual address space before it ran out of swap space to allocate for itself.  

[ 32%] Built target aws-cpp-sdk-dynamodb
[ 32%] Building CXX object aws-cpp-sdk-ec2/CMakeFiles/aws-cpp-sdk-ec2.dir/source/EC2Client.cpp.o
virtual memory exhausted: Cannot allocate memory
aws-cpp-sdk-ec2/CMakeFiles/aws-cpp-sdk-ec2.dir/build.make:134: recipe for target 'aws-cpp-sdk-ec2/CMakeFiles/aws-cpp-sdk-ec2.dir/source/EC2Client.cpp.o' failed
make[2]: **\* [aws-cpp-sdk-ec2/CMakeFiles/aws-cpp-sdk-ec2.dir/source/EC2Client.cpp.o] Error 1
CMakeFiles/Makefile2:1407: recipe for target 'aws-cpp-sdk-ec2/CMakeFiles/aws-cpp-sdk-ec2.dir/all' failed
make[1]: **\* [aws-cpp-sdk-ec2/CMakeFiles/aws-cpp-sdk-ec2.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

$ ls -lh /var/swap
-rw------- 1 root root 10G Mar 21 15:34 /var/swap

top (after the compiler failed so there is hardly any memory in use, gives an idea of how much total virtual memory is available on the system)
top - 23:32:32 up 2 days, 19:51,  2 users,  load average: 0.00, 0.01, 0.05
Tasks: 120 total,   1 running, 119 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.1 us,  0.0 sy,  0.0 ni, 99.8 id,  0.1 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem:    948012 total,   179608 used,   768404 free,    13744 buffers
KiB Swap: 10485756 total,   117828 used, 10367928 free.    80432 cached Mem

**Comment by Bu11etmagnet** [comment]
Not surprising; this is what /usr/bin/time -v reports:
```
	Command being timed: "/usr/bin/c++ -DAWS_CUSTOM_MEMORY_MANAGEMENT -DAWS_SDK_PLATFORM_LINUX -DENABLE_CURL_CLIENT -DENABLE_OPENSSL_ENCRYPTION -DJSON_USE_EXCEPTION=0 -Daws_cpp_sdk_ec2_EXPORTS -Wall -Werror -pedantic -Wextra -fno-exceptions -fPIC -I ~/workspace/aws-sdk-cpp-awslabs/aws-cpp-sdk-ec2/include -I ~/workspace/aws-sdk-cpp-awslabs/aws-cpp-sdk-core/include -std=c++11 -o CMakeFiles/aws-cpp-sdk-ec2.dir/source/EC2Client.cpp.o -c ~/workspace/aws-sdk-cpp-awslabs/aws-cpp-sdk-ec2/source/EC2Client.cpp"
	User time (seconds): 143.37
	System time (seconds): 2.93
	Percent of CPU this job got: 98%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 2:27.94
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 4871780
```

That's 4.8 GB of memory!

**Comment by JonathanHenson** [comment]
Yes sorry for the inconvenience. The EC2 APi surface is massive. You'll
need at least 4GB of memory to build the EC2 client. You could in theory
build the sdk on a different machine and then deploy the binary to your
rasbery Pi host. Altenernatively, you could trim out the methods and
headers you don't actually need.

On Thu, Mar 24, 2016 at 5:16 AM, Ráduly, Csaba <notifications@github.com>
wrote:

> Not surprising; this is what /usr/bin/time -v reports:
>
>     Command being timed: "/usr/bin/c++ -DAWS_CUSTOM_MEMORY_MANAGEMENT -DAWS_SDK_PLATFORM_LINUX -DENABLE_CURL_CLIENT -DENABLE_OPENSSL_ENCRYPTION -DJSON_USE_EXCEPTION=0 -Daws_cpp_sdk_ec2_EXPORTS -Wall -Werror -pedantic -Wextra -fno-exceptions -fPIC -I ~/workspace/aws-sdk-cpp-awslabs/aws-cpp-sdk-ec2/include -I ~/workspace/aws-sdk-cpp-awslabs/aws-cpp-sdk-core/include -std=c++11 -o CMakeFiles/aws-cpp-sdk-ec2.dir/source/EC2Client.cpp.o -c ~/workspace/aws-sdk-cpp-awslabs/aws-cpp-sdk-ec2/source/EC2Client.cpp"
>     User time (seconds): 143.37
>     System time (seconds): 2.93
>     Percent of CPU this job got: 98%
>     Elapsed (wall clock) time (h:mm:ss or m:ss): 2:27.94
>     Average shared text size (kbytes): 0
>     Average unshared data size (kbytes): 0
>     Average stack size (kbytes): 0
>     Average total size (kbytes): 0
>     Maximum resident set size (kbytes): 4871780
>
> That's 4.8 GB of memory!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-sdk-cpp/issues/133#issuecomment-200807300>
>



-- 
"The poet only asks to get his head into the heavens. It is the logician
who seeks to get the heavens into his head. And it is his head that splits"
--G. K. Chesterton-- "Orthodoxy"

**Comment by crawlins** [comment]
I was able to get the ec2 client to build by splitting it into 8! parts.  (EC2Client{1..8}.cpp)
While I haven't attempted to use it yet I wouldn't expect an issue.

Is splitting large services into multiple files something worth considering?

**Comment by JonathanHenson** [comment]
The EC2 API plane has dependencies between services that are difficult to separate. The best advice I can give at the moment is to cross compile for 32 bit on a 64 bit system. 

Shortly, I will add prebuilt 32 bit binaries to our release for you. I'm assuming this is linux?

**Comment by crawlins** [comment]
linux-armhf

**Comment by crawlins** [comment]
When I mean splinting large services I should have been more clear.
I meant, would modifying the generator code to generate multiple cpp files instead of one large cpp file for services that have very large definitions be something worth considering.  

I imagine (I admit that I am completely unfamiliar with this generation technology) that at least two templates would be necessary for large services.  The first template would be just like or very similar to the existing one, except that it gets gets fed a subset of the service definition to generate from.  This template would emit the include directives, the class constructors and destructors and other class level code along with a subset of methods as passed to it. The second would also emit the include directives but omit the constructor and destructor code then emit the subset of the methods provided to the template.  The second template could be used multiple times to split the target cpp files into as many target files as required to fit inside the 3Gb limit of 32bit processes under linux.

Logically the resulting library would be the same, each method and member in the existing objects would still be methods and members in version with split files.  The main difference would be multiple .o files that are then bundled together into the .so or .a file.  The consequence is that the compiler will have less code to work with to find optimizations within the object file.  I doubt that for the performance bottlenecks that this code base experiences that that would make much difference.

**Comment by crawlins** [comment]
I forked the [aws-sdk-cpp repo](https://github.com/crawlins/aws-sdk-cpp/commit/b3ea6244ab1802bdc25e34afbcd27925e2dff35d) and pushed manual changes to EC2Client.cpp (and other large files that didn't compile on 32bit) for reference.  If the concept has merit I may look into modifying the generators to support splits like this.

**Comment by Warbo** [comment]
Just wanted to point out that this issue also applies to i686 Linux as well. I don't have any 64bit machine to cross compile on. I might try emulating one with Qemu, but I imagine that would be rather slow :(

**Comment by singku** [comment]
There are downloadable prebuilt binaries here: http://sdk.amazonaws.com/cpp/builds/
