### ISSUE TITLE
ProfileConfigFileAWSCredentialsProvider ignores role

### ISSUE THREAD

**Issue by jking777** [aws/aws-sdk-cpp#1330]
I have this profile defined in .aws/credentials:

```
[role_test]
role_arn=arn:aws:iam::xxxxSomeRolexxx
source_profile=default
```

When I set AWS_PROFILE=role_test and run AWS CLI commands then it behaves as expected - I can do `aws s3 ls` (the role has S3 access policy) and I can see my buckets, and `aws configure list` shows reasonable info.

Also with AWS_PROFILE=role_test, when I run this bit of C++:

```
Aws::Auth::DefaultAWSCredentialsProviderChain provider;
auto credentials = provider.GetAWSCredentials();
```

I get empty credentials.  Expected outcome:  temporary credentials obtained via the role.

I can manually get temporary role credentials by making a request using Aws::STS::STSClient, but I would like to be able to use the SDK without worrying about credential setup, like when I use AWS CLI.

### What platform/OS are you using?
Windows 10

### Which version of the SDK?
1.7.261

### What compiler are you using? what version?
Visual Studio 2015

### What are your CMake arguments?
-DBUILD_ONLY="identity-management;s3" -DCUSTOM_MEMORY_MANAGEMENT=OFF -DCMAKE_INSTALL_PREFIX=%BUILD_DIR%/install -DENABLE_TESTING=OFF -G "Visual Studio 14 2015" -A x64

### Can you provide a TRACE level log? (sanitize any sensitive information)
Probably not relevant?  Will provide on request.

**Comment by KaibaLopez** [comment]
Hi @jking777 ,
When you say "manually get temporary role credentials by making a request using Aws::STS::STSClient" , can you give me a bit of sample code on how you do that? 

I think this is related to a known issue that should be fixed in the next mayor version but I'd like to get a bit more info.

**Comment by jking777** [comment]
Hi @KaibaLopez,

This is the snippet that I used to see if my role was configured correctly:

```
  Aws::Auth::DefaultAWSCredentialsProviderChain provider;
  auto credentials = provider.GetAWSCredentials();

  Aws::STS::Model::AssumeRoleRequest request;
  request.SetRoleArn("arn:aws:iam::xxxxSomeRolexxx");
  request.SetRoleSessionName("AssumeRoleSession1");
  request.SetExternalId("012345");

  Aws::STS::STSClient stsClient(credentials);
  auto result = stsClient.AssumeRole(request);
```

The credentials I get back from AssumeRole are good.

fwiw, I also looked into using STSProfileCredentialsProvider, but it seems to completely ignore ~/.aws/credentials; if the source profile credentials are not in ~/.aws/config then STSProfileCredentialsProvider is unable to provide role credentials.

**Comment by KaibaLopez** [comment]
Hi @jking777 ,
Did some digging and long story short, you're right on both the default provider chain and the sts credentials provider.

First, the default credentials provider chain does not include the assume role functionality, so you'd need to assign it "manually" through the identity-manager, or create your own provider chain that includes it, up to you there, but at the moment there is no plans of adding it to the default chain.
Second, the cli is kind of a special case in here, this sdk (and most others) only looks on ~/.aws/config, which coincides with documentation.

So yea, these could be feature requests (and we'd **_love_** contributors' help) but unless STSProfileCredentialsProvider ignores ~/.aws/config too I don't think it'd be a bug. 

Let me know what you think, and thanks for pointing it out to us.

**Comment by surry** [comment]
@KaibaLopez, I am seeing a different issue, but your comment seems related to what I am trying to solve...

I'm trying to find a way to have TensorFlow, which uses this SDK, to write to S3 using an assumed role. It doesn't currently support this, however, following the suggestion here by @singku, I am able to get it to work:

> Implement your own CredentialsProviderChain, just do this as what we do in DefaultCredentialsProviderChain. And add STSProfileCredentialsProvider into the chain. Then, when creating your service client, you specify this provider chain in your code.

https://github.com/aws/aws-sdk-cpp/issues/150#issuecomment-538548438

However, this only works if the AWS credentials are in ~/.aws/config. I see some support for loading credentials from the shared credentials file, e.g.

https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/include/aws/core/auth/AWSCredentialsProvider.h#L144

https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp#L140

But, the call here doesn't seem to include the credentials from ~/.aws/credentials, and the call to CheckProfile() a few lines later says the profile is invalid if the credentials are not the profile specified by AWS_PROFILE:

https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-identity-management/source/auth/STSProfileCredentialsProvider.cpp#L168

Do you know if this is a bug, or a missing feature?

Maybe the call to get the profile in STSProfileCredentialsProvider.cpp needs merge the profile results with the results from the credentials file so the profile doesn't fail this check:

```
    if (!profile.GetCredentials().IsExpiredOrEmpty())
    {
        state += STATIC_CREDENTIALS;
    }
```
?

**Comment by frivard-coveo** [comment]
I made a PR to implement the needed change.
Please Like, Subscribe and Share if you liked 😆
