### ISSUE TITLE
aws sdk compute optimizer , doesn't get pricing

### ISSUE THREAD

**Issue by roquesao** [aws/aws-sdk-cpp#1331]
Just a question , I'm trying to get the pricing of the recommendations, I'm executing

client.get_recommendation_summaries()

I got the recommendations about instance type but not pricing , is there any way to get it?

best regards

**Comment by KaibaLopez** [comment]
Hi @roquesao ,
I'm a bit confused on what you're trying to do here, we do have a cost explorer service, but I don't know how you're trying to relate them.
Can you provide some sample code on what you've got and what you're trying to do?

**Comment by roquesao** [comment]
hi I just want to get the same information via aws cli or aws sdk , that aws-compute-optimizer give when we use the aws console

**Comment by KaibaLopez** [comment]
Right, but I'm honestly a bit lost with this, I'm not super familiar with the compute-optimizer service but I know that we have a separate service for pricing, so I'm trying to figure out a way to do both? See if this would be a feature request we need to take or something that we can do with 2 service calls.

In your initial comment you said you got client.get_recommendation_summaries() to execute and get recommendations for instances, but I'm assuming that's a custom function, what exactly does that do? what kind of kind of client is that? Can you provide sample code on what you're running?
