### ISSUE TITLE
SimpleDB and C++:  access credentials are missing

### ISSUE THREAD

**Issue by chtrading** [aws/aws-sdk-cpp#1332]
I am trying to create a SDB Domain using SDK C++.

My program is:

> 
> #include <aws/core/Aws.h>
> #include <aws/core/utils/Outcome.h> 
> #include <aws/sdb/SimpleDBClient.h>
> #include <aws/sdb/model/CreateDomainRequest.h>
> #include <aws/core/auth/AWSCredentialsProviderChain.h>
> #include <iostream>
> 
> int main(int argc, char** argv)
> {
>     const std::string USAGE = "\n" \
>         "Usage:\n"
>         "    create_domain <domain> <optional:region>\n\n"
>         "Where:\n"
>         "    domain - the domain to create\n"
>         "    region - optional region\n\n"
>         "Example:\n"
>         "    create_domain Hello us-west-2\n";
> 
>     if (argc < 2)
>     {
>         std::cout << USAGE;
>         return 1;
>     }
> 
>     Aws::SDKOptions options;
> 
>     Aws::InitAPI(options);
>     {
>         const Aws::String domain(argv[1]);
>         const Aws::String region(argc > 2 ? argv[2] : "");
> 
>         Aws::Client::ClientConfiguration clientConfig;
> 
>         if (!region.empty())
>             clientConfig.region = region;
>         Aws::SimpleDB::SimpleDBClient simpleClient(clientConfig);
> 
>         std::cout << "Creating domain " << domain << std::endl;
> 
>         Aws::SimpleDB::Model::CreateDomainRequest req;
> 
>         req.SetDomainName(domain);
> 
> 
> 		const Aws::SimpleDB::Model::CreateDomainOutcome& result = simpleClient.CreateDomain(req);
> 		if (result.IsSuccess())
> 		{
> 			std::cout << "Domain created" << std::endl;
> 		}
> 		else
> 		{
> 			std::cout << "Failed to create domain: " << result.GetError().GetMessage();
> 		}
> 
>     }
>     Aws::ShutdownAPI(options);
>     return 0;
> }

But I am getting this output:
[ch@localhost ~]$ ./a.out Hello us-west-2
Creating domain Hello
Failed to create domain: Unable to parse ExceptionName: AuthFailure Message: AWS was not able to authenticate the request: access credentials are missing[ch@localhost ~]$ 

---------------------------------------------------------------------
**### What platform/OS are you using?**

CentOS 7

**### Which version of the SDK?**

ll /usr/local/lib64/libaws-cpp-sdk-sdb.so
-rwxr-xr-x 1 root root 2274272 Nov 15  2018 /usr/local/lib64/libaws-cpp-sdk-sdb.so

**### What compiler are you using? what version?**

[ch@localhost Downloads]$ g++ --version
g++ (GCC) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by KaibaLopez** [comment]
Hi @chtrading, 
sorry but the sdk no longer supports simpleDB. 
Basically the sdk only uses SIGV4 for authentication and simpleDB is not compatible.
