### ISSUE TITLE
Compilation failing with VS 2015

### ISSUE THREAD

**Issue by epot** [aws/aws-sdk-cpp#134]
Hello,
I am trying to compile the SDK with Visual studio 2015 but it fails to compile. I am using the following cmake:
cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_EXE_LINKER_FLAGS_DEBUGOPT="" -DCMAKE_CXX_FLAGS_DEBUGOPT="" -DCMAKE_SHARED_LINKER_FLAGS_DEBUGOPT="" -DSTATIC_LINKING=1 ..

And I get when building:
awscppsdk\sources\aws-sdk-cpp-0.9.6\aws-cpp-sdk-core\source\utils\logging\LogLevel.cpp(24): error C2220: warning treated as error - no 'object' file generated                                   
awscppsdk\sources\aws-sdk-cpp-0.9.6\aws-cpp-sdk-core\source\utils\logging\LogLevel.cpp(24): warning C4592: 'logLevelNameMap': symbol will be dynamically initialized (implementation limitation) 

Any clue ?

Thanks !
Emmanuel

**Comment by bretambrose** [comment]
If you can update to the latest version in GitHub, that map has been removed and it's just a switch statement now.

**Comment by bretambrose** [comment]
I should also add, if you are not able to update due to other dependencies, you could make the same change locally and nothing else should be adversely affected.

**Comment by epot** [comment]
Thanks ! I did take the latest version from github. Are you suggesting to take the head from master ?

**Comment by bretambrose** [comment]
Definitely.  

If you look at the latest version of LogLevel.cpp (https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/utils/logging/LogLevel.cpp) you'll see the map is gone.  I'm guessing what you currently have is the old version which you can see at (https://github.com/aws/aws-sdk-cpp/blob/12bf8269d5a8e380617ad905d06ae76a286bac6b/aws-cpp-sdk-core/source/utils/logging/LogLevel.cpp)

**Comment by epot** [comment]
Excellent, thanks !
