### ISSUE TITLE
Convert String into Payload

### ISSUE THREAD

**Issue by chtrading** [aws/aws-sdk-cpp#1340]
I am using the the 
[Aws::DynamoDB::Model::BatchWriteItemRequest::SerializePayload](https://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_dynamo_d_b_1_1_model_1_1_batch_write_item_request.html#ae7bf019e529e95264a205c124dba01f6)

This method converts Payload into String.

I would like to know how can I easily convert this String to Payload again.

**Comment by KaibaLopez** [comment]
Hi @chtrading ,
it kind of depends on what you want really, we have a way to convert strings to json objects and vice versa... but BatchWriteItemRequest doesn't take a json object so, if that's what you want to do then it'd be a no. 
Can you clarify on what you're trying to do?
