### ISSUE TITLE
Please Warn in the Provided Dockerfile that compilation may require at least 4GB

### ISSUE THREAD

**Issue by alanyee** [aws/aws-sdk-cpp#1341]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I use the following Dockerfile provided at https://github.com/aws/aws-sdk-cpp/blob/master/CI/docker-file/AmazonLinux2/Dockerfile:
```
# Using Amazon Linux 2 docker image
FROM amazonlinux:latest

#Install g++
RUN yum groupinstall "Development Tools" -y

#Install cmake
RUN curl https://cmake.org/files/v3.13/cmake-3.13.3-Linux-x86_64.tar.gz --output cmake-3.13.3-Linux-x86_64.tar.gz && \
    tar -xvzf cmake-3.13.3-Linux-x86_64.tar.gz && \
    mv cmake-3.13.3-Linux-x86_64 /opt && \
    rm cmake-3.13.3-Linux-x86_64.tar.gz && \
    ln -s /opt/cmake-3.13.3-Linux-x86_64/bin/cmake /usr/local/bin/cmake

#Install curl and openssl
RUN yum install curl-devel -y && \
    yum install openssl-devel -y && \
    yum install ninja-build -y

#Install awscli
RUN yum install python-pip -y && \
    pip install awscli

RUN git clone https://github.com/aws/aws-sdk-cpp.git
RUN mkdir sdk_build
WORKDIR sdk_build
RUN cmake ../aws-sdk-cpp/ -D CMAKE_BUILD_TYPE=Release -D BUILD_ONLY="sqs"
RUN make
RUN make install
```

But then:
```
[ 26%] Building CXX object aws-cpp-sdk-iam/CMakeFiles/aws-cpp-sdk-iam.dir/source/IAMClient.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [aws-cpp-sdk-iam/CMakeFiles/aws-cpp-sdk-iam.dir/source/IAMClient.cpp.o] Error 4
make[1]: *** [aws-cpp-sdk-iam/CMakeFiles/aws-cpp-sdk-iam.dir/all] Error 2
make: *** [all] Error 2
The command '/bin/sh -c make' returned a non-zero code: 2
```
Perhaps the SDK is not at fault, but if the Dockerfile cannot compile the SDK, I would remove the Dockerfile, provide a warning, or provide additional steps on avoiding this problem.

**SDK version number**
1.7.294

**Platform/OS/Hardware/Device**
Docker on macOS

**To Reproduce (observed behavior)**
1. Make a Dockerfile based on https://github.com/aws/aws-sdk-cpp/blob/master/CI/docker-file/AmazonLinux2/Dockerfile
2. Run `docker build -t cpp_test .`

**Expected behavior**
I expected
```
Successfully tagged cpp_test:latest
```
When I have
```
RUN cmake ../aws-sdk-cpp/ -D CMAKE_BUILD_TYPE=Release -D BUILD_ONLY="s3"
```
instead of
```
RUN cmake ../aws-sdk-cpp/ -D CMAKE_BUILD_TYPE=Release -D BUILD_ONLY="sqs"
```
the SDK compiles correctly.

**Logs/output**
```
[ 26%] Built target aws-cpp-sdk-sqs
Scanning dependencies of target aws-cpp-sdk-iam
[ 26%] Building CXX object aws-cpp-sdk-iam/CMakeFiles/aws-cpp-sdk-iam.dir/source/IAMClient.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [aws-cpp-sdk-iam/CMakeFiles/aws-cpp-sdk-iam.dir/source/IAMClient.cpp.o] Error 4
make[1]: *** [aws-cpp-sdk-iam/CMakeFiles/aws-cpp-sdk-iam.dir/all] Error 2
make: *** [all] Error 2
The command '/bin/sh -c make' returned a non-zero code: 2
```

To enable logging, set the following system properties:

**Additional context**
It does not have to be `amazonlinux`. Just any Docker image will do.

**Comment by alanyee** [comment]
The warning I would add is to make sure that their Docker has allocated at least 4GB of memory.

**Comment by KaibaLopez** [comment]
Hi @alanyee ,
Thanks for pointing this out, would you mind making a pr with the changes you'd like to see? Do you think a comment would be enough or is putting the warning in the Readme a better idea?

**Comment by alanyee** [comment]
I would go with adding a README.md here https://github.com/aws/aws-sdk-cpp/tree/master/CI/docker-file and adding a comment to each Dockerfile. As far as I know, the main README does not include any mentions of the docker files: https://github.com/aws/aws-sdk-cpp/blob/master/README.md. So I would imagine developers stumble across these Dockerfiles through various means, and having redundancy of information would be helpful for informing them since Docker does not provide a helpful error message when it runs out of memory.

**Comment by wps132230** [comment]
I think the README file has already mentioned the minimum requirements of 4 GB of RAM.
https://github.com/aws/aws-sdk-cpp#minimum-requirements

**Comment by alanyee** [comment]
Yeah that README does mention 4GB requirement, but when a typical developer runs Docker, the amount of memory allocated to an image is set by default and usually out of mind.

Also, the README does not mention the docker files, so I don't think those who would find the docker files necessarily read the README.md.

**Comment by wps132230** [comment]
The docker file is for internal usage to build testing infrastructure, so we haven't mention it in the README.
But it's reasonable to let users make use of these dockerfile to setup environment as well.
If we would like to add it to README, it sounds good to me to mention the 4GB requirement. And thank you for your PR, it will be a good starting point to provide more useful information in README.
