### ISSUE TITLE
 MalformedXML error while using PutBucketLifecycleConfiguration

### ISSUE THREAD

**Issue by mkhan3088** [aws/aws-sdk-cpp#1343]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Linux/Centos7/

**Describe the question**
Creating lifecycle rule using aws-sdk-cpp for bucket gives error. Using the PutBucketLifecycleConfiguration() to set the BucketLifecycleConfiguration.

**Logs/output**
MalformedXML: Unable to parse ExceptionName: MalformedXML Message: The XML you provided was not well-formed or did not validate against our published schema .

   HTTP/1.1 400 Bad Request
   x-amz-id-2: xxx   
   x-amz-request-id: xxx
   Content-Type: application/xml
   Content-Length: 280

     //Code snippet
     LifecycleRule LCR;

    Transition my_transition;
    my_transition.WithDays(30);

    TransitionStorageClass my_transitionstorageclass = TransitionStorageClass::STANDARD_IA ;
    my_transition.WithStorageClass(my_transitionstorageclass);

     // transition vector
     Aws::Vector<Transition> m_transitionvector;
     m_transitionvector.push_back(my_transition);

    LCR.WithTransitions(m_transitionvector);

    // Set status of lifecyclerule
    ExpirationStatus My_expiration = ExpirationStatus::Enabled;
    LCR.WithStatus(My_expiration);

    //Set expiration of lifecyclerule
    LifecycleExpiration my_lifecycleexpiration;
    my_lifecycleexpiration.WithDays(32);
    my_lifecycleexpiration.WithExpiredObjectDeleteMarker(true);

    LCR.SetExpiration(my_lifecycleexpiration);

    LCR.WithID("archive and delete");

    //Set Filter of objects
    LifecycleRuleFilter my_filter;
    my_filter.WithPrefix("my/videos");
    LCR.WithFilter(my_filter);

    // ABort incomplete upload
    AbortIncompleteMultipartUpload my_incmpltupload;
    my_incmpltupload.WithDaysAfterInitiation(7);

    LCR.WithAbortIncompleteMultipartUpload(my_incmpltupload);

    //Nonconcurrent version
    NoncurrentVersionExpiration my_noncurverexpi;
    my_noncurverexpi.WithNoncurrentDays(7);

    LCR.WithNoncurrentVersionExpiration(my_noncurverexpi);

    Aws::Vector<LifecycleRule> My_lcr;
    My_lcr.push_back(LCR);

    Aws::S3::Model::BucketLifecycleConfiguration BLCC;
    BLCC.WithRules(My_lcr);

    Aws::Client::ClientConfiguration config;
    config.region = "us-east-1";
    Aws::S3::S3Client client(config);

    Aws::S3::Model::PutBucketLifecycleConfigurationRequest request;
   
    request.WithBucket("bucket_name");
    request.WithLifecycleConfiguration(BLCC);
    auto outcome = client.PutBucketLifecycleConfiguration(request);

**Comment by KaibaLopez** [comment]
Hi @mkhan3088 ,
I'm able to reproduce this, but I'm not super familiar with using the life cycle configuration, give me some time to investigate what's going on and I'll get back to you as soon as I find something.

**Comment by KaibaLopez** [comment]
@mkhan3088 ,
So, I think I found the problem, you cannot have these 2 as part of your life cycle configurations:
```
    ExpirationStatus My_expiration = ExpirationStatus::Enabled;

    my_lifecycleexpiration.WithExpiredObjectDeleteMarker(true);
```
This is a service limitation, not really something we could add to the sdk's implementation, if you go to the management console, it won't let you do both either.
Let me know if this helps.

**Comment by mkhan3088** [comment]
Thanks it worked i have removed 
my_lifecycleexpiration.WithExpiredObjectDeleteMarker(true);

so , my lifecycle is ready .It is visible on management console.
