### ISSUE TITLE
Multi part upload using TransferManager sometimes upload an empty file of  0 bytes

### ISSUE THREAD

**Issue by xifenghz** [aws/aws-sdk-cpp#1345]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?

**Describe the question**

        auto s3_client_executor = Aws::MakeShared<Aws::Utils::Threading::DefaultExecutor>(AWS_WRITER_TAG);
        TransferManagerConfiguration transfer_config(s3_client_executor.get());
        transfer_config.s3Client = s3_client_;
        transfer_config.bufferSize = MB5 * 24;
        transfer_config.transferBufferMaxHeapSize = MB5 * 24 * 10;
        transfer_config.uploadProgressCallback = [&object_name](const TransferManager*, const std::shared_ptr<const TransferHandle>& transfer_handle) {
    
            LOGSTREAM_INFO("Uploading [" << object_name << "] Process: " << transfer_handle->GetBytesTransferred() << " of " << transfer_handle->GetBytesTotalSize() << " bytes");
   
        };
        LOGSTREAM_INFO("with one part size: " << GetSizeOfOnePart() << " bytes, heap size: " << GetSizeOfHeap() << " bytes");
        auto transfer_manager = TransferManager::Create(transfer_config);
        std::shared_ptr<TransferHandle> transfer_handle = transfer_manager->UploadFile(body, bucket_name, object_name, "bin", Aws::Map<Aws::String, Aws::String>());
        transfer_handle->WaitUntilFinished();
        for (int retries = 0; transfer_handle->GetStatus() == TransferStatus::FAILED && retries < 3; ++retries) {
            LOGSTREAM_INFO("Upload file [" << object_name << "] with multipart upload fail: retry " << retries + 1 << "...");
            transfer_manager->RetryUpload(body, transfer_handle);
            transfer_handle->WaitUntilFinished();
        }
        transfer_handle->SetIsMultipart(true);

        PartStateMap complete_parts = transfer_handle->GetCompletedParts();
        for (const auto& part : complete_parts) {
            LOGSTREAM_INFO("[" << object_name << "] completed parts [" << part.first << "]: "
                                    << part.second->GetETag() << " with " << part.second->GetSizeInBytes() << " bytes");
        }

**Logs/output**
Upload file [xxxxx] with multipart upload ...
with one part size: 125829120 bytes, heap size : 1258291200 bytes
Upload file [xxxxx] with multipart upload fail: retry 1...
**[xxxxxx] completed parts [1]: "d4xxxxxxxxxxxxxxxxxxx" with 0 bytes**
Upload file [xxxxxx] success

**But the file on s3 is an empty file,with 0 byte. I using an old version sdk of 1.2.34. The frequency of this situation is not high, and the memory utilization rate is about 80-90. So will TransferManager.upload() put entire file into the memory or it is smart enough to stream content to s3 without filling up the memory? Thanks for any help.**
*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
Hi @xifenghz ,
Hard to tell if the situation cannot be reproduced consistently, it might be a failed upload that got interrupted in a specific part of the process, for now I'd recommend making sure that there are no "parts" still stored in your s3 to avoid extra charges.
And about the last question, transfermanager will on default do multi part and divide the request in parts of 5MB, now these parts would remain in memory while in use (not the whole file but the part which in your case would be `MB5 * 24` ).
See [TransferManager Code ](https://github.com/aws/aws-sdk-cpp/blob/b7b820def7cf61041585326da3eb159fc1a25cd7/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp#L774) it should be clearer there.
