### ISSUE TITLE
Do you have an example for Sagemaker or Documentation?

### ISSUE THREAD

**Issue by braca51e** [aws/aws-sdk-cpp#1346]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
MacOS Mojave

**Describe the question**
I'm trying to use sagemaker but i'm getting linker errors. You do not provide any examples in examples folder. Is this available in the sdk?

**Logs/output**
[ 83%] Building CXX object CMakeFiles/VideoAnalysis.dir/src/Sagemaker.cpp.o
[100%] Linking CXX executable VideoAnalysis
Undefined symbols for architecture x86_64:
  "Aws::SageMakerRuntime::SageMakerRuntimeClient::SageMakerRuntimeClient(std::__1::shared_ptr<Aws::Auth::AWSCredentialsProvider> const&, Aws::Client::ClientConfiguration const&)", referenced from:
      std::__1::__compressed_pair_elem<Aws::SageMakerRuntime::SageMakerRuntimeClient, 1, false>::__compressed_pair_elem<std::__1::shared_ptr<Aws::Auth::DefaultAWSCredentialsProviderChain>&&, Aws::Client::ClientConfiguration&, 0ul, 1ul>(std::__1::piecewise_construct_t, std::__1::tuple<std::__1::shared_ptr<Aws::Auth::DefaultAWSCredentialsProviderChain>&&, Aws::Client::ClientConfiguration&>, std::__1::__tuple_indices<0ul, 1ul>) in Sagemaker.cpp.o
  "Aws::SageMakerRuntime::SageMakerRuntimeClient::~SageMakerRuntimeClient()", referenced from:
      std::__1::__compressed_pair_elem<Aws::SageMakerRuntime::SageMakerRuntimeClient, 1, false>::~__compressed_pair_elem() in Sagemaker.cpp.o
  "Aws::SageMakerRuntime::Model::InvokeEndpointRequest::InvokeEndpointRequest()", referenced from:
      Sagemaker::infer(std::__1::shared_ptr<Frame>) in Sagemaker.cpp.o
  "Sagemaker::_ALLOCATION_TAG", referenced from:
      Sagemaker::Sagemaker() in Sagemaker.cpp.o
  "vtable for Aws::SageMakerRuntime::Model::InvokeEndpointRequest", referenced from:
      Aws::SageMakerRuntime::Model::InvokeEndpointRequest::~InvokeEndpointRequest() in Sagemaker.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [VideoAnalysis] Error 1
make[1]: *** [CMakeFiles/VideoAnalysis.dir/all] Error 2
make: *** [all] Error 2
10:01:37: The process "/usr/local/Cellar/cmake/3.16.5/bin/cmake" exited with code 2.
Error while building/deploying project Video_Analysis (kit: Desktop Qt 5.12.5 clang 64bit)
When executing step "CMake Build"

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
Hi @braca51e ,
We sadly don't have one ready, but here's a super basic example on how to create a notebook instance in sagemaker : 
```
#include <aws/core/Aws.h>
#include <aws/core/utils/logging/LogLevel.h>
#include <aws/core/client/ClientConfiguration.h>
#include <aws/sagemaker/SageMakerClient.h>
#include <aws/sagemaker/model/CreateNotebookInstanceRequest.h>
#include <aws/sagemaker/model/CreateNotebookInstanceResult.h>

#include <iostream>

using namespace std;
using namespace Aws;

int main(){
    SDKOptions options;
    options.loggingOptions.logLevel = Utils::Logging::LogLevel::Trace;
    InitAPI(options);
    {
        Client::ClientConfiguration sageconfig("default");
        SageMaker::SageMakerClient myClient(sageconfig);
        SageMaker::Model::CreateNotebookInstanceRequest nowork;

        nowork.WithNotebookInstanceName("myInstance");
        nowork.WithInstanceType(SageMaker::Model::InstanceType::ml_t2_medium);
        nowork.WithRoleArn("***Write your own role Arn here***");
        auto outcome = myClient.CreateNotebookInstance(nowork);
        if(outcome.IsSuccess()){
            cout<<"the notebook instance"<< outcome.GetResult().GetNotebookInstanceArn() << "was succesfully created"<<endl;
        }else{
            cout<<"error: " << outcome.GetError() << endl;
        }
        
    }ShutdownAPI(options);
return 0;
}
```
Hope this helps, let me know if there's anything specific you're trying to do too. I might not be able to do complicated samples for you but simple/generic actions like this should be fine.

**Comment by braca51e** [comment]
@KaibaLopez Thanks for the answer this is very helpful. This is very helpful.
I'm trying to call an endpoint that I already deployed in Sagemaker. Having an example for InvokeEndpoint would be great!

**Comment by braca51e** [comment]
@KaibaLopez this is what I'm trying to compile:

```
#include <aws/core/Aws.h>
#include <aws/core/utils/logging/LogLevel.h>
#include <aws/core/utils/Outcome.h>
#include <aws/core/client/ClientConfiguration.h>
#include <aws/sagemaker-runtime/SageMakerRuntimeClient.h>
#include <aws/sagemaker-runtime/model/InvokeEndpointRequest.h>
#include <aws/sagemaker-runtime/model/InvokeEndpointResult.h>

#include <iostream>

using namespace std;
using namespace Aws;

int main(){
    SDKOptions options;
    options.loggingOptions.logLevel = Utils::Logging::LogLevel::Trace;
    InitAPI(options);
    {
        Client::ClientConfiguration sageconfig("default");
        std::shared_ptr<SageMakerRuntime::SageMakerRuntimeClient> _sagemakerClient = MakeShared<SageMakerRuntime::SageMakerRuntimeClient>("_ALLOCATION_TAG",
                                            sageconfig);
        SageMakerRuntime::Model::InvokeEndpointRequest request;
        request.SetEndpointName("test");
        auto payload = Aws::MakeShared<Aws::StringStream>("FrameInference", std::stringstream::in | std::stringstream::out | std::stringstream::binary);
        request.SetBody(payload);
        request.SetContentType("image/jpeg");
        SageMakerRuntime::Model::InvokeEndpointOutcome result = _sagemakerClient->InvokeEndpoint(request);
        std::cout << "Calling sagemaker endpoint success: " << result.IsSuccess() << std::endl;

    }ShutdownAPI(options);
return 0;
}

```

**Comment by braca51e** [comment]
@KaibaLopez Never ind I was not finding the right package in cmake was using sagemaker instead of sagemaker-runtime

**Comment by KaibaLopez** [comment]
glad you were able to find your error. 
I'll be closing this if there isn't any more questions.
