### ISSUE TITLE
Aws::EC2::Model::Snapshot: startTime

### ISSUE THREAD

**Issue by quatmax** [aws/aws-sdk-cpp#135]
Hi!

First of all thanks a lot for this cool C++ toolkit!

I have a problem with `Aws::EC2::Model::Snapshot` in connection with the [DescribeSnapshots-API](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSnapshots.html).
The `startTime` property is parsed as string, trimmed and converted to double. 
On my configuration (Win10, VC2015, German locale) this results in a double containing only the year-part of the `startTime`. 

Wouldn't the raw string of the result be better (or a TimeStamp data type)?
Is this an error or am I missing something?

Thanks for your answer!

ps.: If this is an error, it affects `startTime` properties of all responses and requests.

**Comment by JonathanHenson** [comment]
We've reworked the way date timestamps are handled in the SDK. Have a look at aws-cpp-sdk-core/include/aws/core/utils/DateTime.h. Let me know if you have any questions.
