### ISSUE TITLE
Problem with the NetworkConnection class

### ISSUE THREAD

**Issue by chifaabouguila** [aws/aws-sdk-cpp#1356]
Confirm by changing [ ] to [x] below:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?

**Describe the question**
I'm using the PubSub sample code, IsConnected always return true when connection goes off, plus the reconnect callback and the disconnect callback handler are not being called to re-establish the network connection

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
Hi @chifaabouguila ,
are you maybe looking for the [aws-iot-device-sdk-cpp](https://github.com/aws/aws-iot-device-sdk-cpp) repo? Or what do you mean by the PubSub sample?
