### ISSUE TITLE
Not all regions are supported

### ISSUE THREAD

**Issue by heylaender** [aws/aws-sdk-cpp#1358]
Aws::S3::Model::BucketLocationConstraint doesn't support all regions, e.g.

Asia Pacific (Hong Kong) — ap-east-1
Asia Pacific (Osaka-Local) — ap-northeast-3
EU (Stockholm) — eu-north-1
Middle East (Bahrain) — me-south-1
AWS GovCloud (US-East) — us-gov-east-1

How to create a bucket within this location?

Aws::S3::Model::CreateBucketRequest request;	request.SetCreateBucketConfiguration(Aws::S3::Model::CreateBucketConfiguration().WithLocationConstraint(getBucketLocationContraint()));
request.SetBucket(m_bucket.toLatin1().data());
auto create_bucket_outcome = s3Client()->CreateBucket(request);

**Comment by KaibaLopez** [comment]
Hi @heylaender ,
Most of these regions are restricted for some reason or another and so they are not supported intentionally, from your list: `ap-east-1, ap-northeast-3, eu-north-1, me-south-1 and us-gov-east-1`.
`eu-north-1` is actually missing and I think we can add it, so I'll mark this as a feature request and get to that.
If this is blocking you though, you could manually add the region to the [enum class](https://github.com/aws/aws-sdk-cpp/blob/2a1d72685720b9663df2bfe38d3e69c4cc87c417/aws-cpp-sdk-s3/include/aws/s3/model/BucketLocationConstraint.h). 
Finally `ap-south-1` should work, not sure why it isn't for you.

**Comment by KaibaLopez** [comment]
Hi @heylaender ,
Sorry this took longer than expected, but the regions have been updated on the last release.
I'll be closing this issue, thanks again for pointing this out to us!
