### ISSUE TITLE
AWS doesn't Cmake and  make by MINGW in windows

### ISSUE THREAD

**Issue by kouroshkashi** [aws/aws-sdk-cpp#1362]
I want to use S3 in my QT project so I decided to compile S3 with MINGW in windows 10 but when I want to Cmake S3 with MINGW it has error in third party, after I searched a lot I found that I have to use previous version which it doesn't have third party. I used a previous version and changed some files like Array.h.
Now I can cmake, but now I have error in make like "winhttp_option_secure_protocols tls1_1 was not declared in this scope".

**Comment by KaibaLopez** [comment]
this is a duplicate issue from #1361 ,
So I'll be closing this one and following up there since it has more info to work with.
