### ISSUE TITLE
Single file upload - etag verification fails

### ISSUE THREAD

**Issue by kkbachu** [aws/aws-sdk-cpp#1369]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Ubuntu 18.04

**Describe the question**
I am doing a single file upload of 1mb, it successfully uploads with the contentHash I set. I verified the contents of the file are correct.
However, when i verify the etag with content hash on putobject response, content hash in the outcome and etag does not match.
Am I doing this correctly?

/*
           * TODO: verification from our side.
           * S3 verifies if content hash is set during putobject request.
           *
          Aws::Utils::ByteBuffer digest = Aws::Utils::HashingUtils::CalculateMD5(*request.GetBo  dy());
          Aws::String contentHash = Aws::Utils::HashingUtils::Base64Encode(digest);
          if (outcome.GetResult().GetETag() == contentHash) {
              cout << "Verified uploaded content" << handle->GetKey();
          } else {
              cout << "Verificaton failed" << contentHash << outcome.GetRe  sult().GetETag() << handle->GetKey();
              
          }
*/

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
Hi @kkbachu ,
Haven't tried this but just as a quick look from our tests the way we verify etags is with HexEncode can you try that?
```
Aws::StringStream ss;
ss << "\"" << HashingUtils::HexEncode(HashingUtils::CalculateMD5(*putObjectRequest.GetBody())) << "\"";
ss.str().c_str() == putObjectOutcome.GetResult().GetETag().c_str())
```

**Comment by kkbachu** [comment]
Thank you . Above suggestion worked.
