### ISSUE TITLE
aws api crashes while retrieving data from dynamo db when there is repeated misses

### ISSUE THREAD

**Issue by msinha31** [aws/aws-sdk-cpp#137]
#0  SLL_Next (t=0xf) at src/linked_list.h:44
#1  SLL_Pop (list=<optimized out>) at src/linked_list.h:58
#2  Pop (this=0x1cb4a28) at src/thread_cache.h:215
#3  Allocate (cl=4, size=<error reading variable: Cannot access memory at address 0x20>, this=<optimized out>) at src/thread_cache.h:367
#4  do_malloc_small (size=<error reading variable: Cannot access memory at address 0x20>, heap=<optimized out>) at src/tcmalloc.cc:1088
#5  do_malloc_no_errno (size=46) at src/tcmalloc.cc:1095
#6  do_malloc (size=46) at src/tcmalloc.cc:1104
#7  do_malloc_or_cpp_alloc (size=46) at src/tcmalloc.cc:1024
#8  tc_malloc (size=46) at src/tcmalloc.cc:1563
#9  0x00007f4d885ffd8d in operator new (sz=46) at ../../../../libstdc++-v3/libsupc++/new_op.cc:51
#10 0x00007f4d8865b369 in allocate (this=<optimized out>, __n=<optimized out>)
    at /usr/src/debug/gcc-4.8.3-20140911/obj-x86_64-amazon-linux/x86_64-amazon-linux/libstdc++-v3/include/ext/new_allocator.h:104
#11 std::string::_Rep::_S_create (__capacity=__capacity@entry=21, __old_capacity=__old_capacity@entry=0, __alloc=...)
    at /usr/src/debug/gcc-4.8.3-20140911/obj-x86_64-amazon-linux/x86_64-amazon-linux/libstdc++-v3/include/bits/basic_string.tcc:607
#12 0x00007f4d8865c8f1 in std::string::_S_construct<char*> (
    __beg=0x27f60d8 "%Y-%m-%d %H:%M:%S,53385 [139970802542336] [INFO ] [getScores] [] - wtp b949711a-6e92-4a77-a95f-4b77b4bd430e is not present in table good_wtp\nR == 'UCBrowser' or BROWSER == 'OperaMobi') {W_BROWSER := -"..., __end=<optimized out>, __a=...)

**Comment by bretambrose** [comment]
Your stack trace is cutoff before it reaches SDK code.  Could you add more, at least up to the point where it crosses into your code?  If you could provide more detailed reproduction steps (a small code sample with a description of the dybamodb table being hit for example), that would be very helpful too.

**Comment by JonathanHenson** [comment]
Also, we've made this much easier for use with cmake. Have a look at this blog post:

https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/

**Comment by JonathanHenson** [comment]
Closing pending more info. Reopen if your issue is not resolved.
