### ISSUE TITLE
HOW TO GET LIST OF BUCKETS

### ISSUE THREAD

**Issue by mkhan3088** [aws/aws-sdk-cpp#1372]
How to get list of all buckets in my aws account using API call?

**Comment by KaibaLopez** [comment]
Hi @mkhan3088 ,
You can find sample code for simple api uses in [this repo](https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/cpp/example_code/s3/list_buckets.cpp).
Hope this helps and next time please use the issue templates.
