### ISSUE TITLE
AWS SDK for C++ Version 1.8 Developer Preview

### ISSUE THREAD

**Issue by wps132230** [aws/aws-sdk-cpp#1373]
The AWS SDK for C++ version 1.8 is out for preview under branch [version1.8](https://github.com/aws/aws-sdk-cpp/tree/version1.8) with the following new features (items with a `*` means a breaking change):

1. `ENABLE_CURL_LOGGING` is now `ON` by default in CMake. *
2. `ENABLE_UNITY_BUILD` is now `ON` by default in CMake. *
3. The deprecated version of function `MakeRequest()` was removed. This function takes a reference to an `HttpRequest` object as its argument, which is unsafe. *
4. Client configuration now reads environment variables, configuration file and EC2 metadata to get the default AWS region *
5. Exceptions may include more service and operation specific details now.
6. New pseudo region: `aws-global` to make cross region requests. *
7. S3 client in `us-east-1` now uses regional endpoint by default. *
8. Improvements on the underlying HTTP client override.

You can see more details in this Wiki: https://github.com/aws/aws-sdk-cpp/wiki/What’s-New-in-AWS-SDK-for-CPP-Version-1.8

If you have any questions, concerns, suggestions or ideas to make improvements. Feel free to leave comments in this issue. Your feedback is important to AWS SDK for C++!

**Comment by pavian** [comment]
Hi, when is it scheduled to release? 
I mean, can it be considered stable at this point or should I give it some time to resolve possible issues?

**Comment by singku-china** [comment]
@pavian It's now official.

**Comment by rvernica** [comment]
Are there pre-built libraries available for CentOS and Debian? How are applications using the SDK generally deployed on Linux systems?

**Comment by Sunil-P** [comment]
Need support for Apple M1 Macs (Universal binary)

**Comment by ahmedyarub** [comment]
I made a PR for VCPKG support for Android (and other cross-platform builds). It would be nice if you would accept that.
Other than that, I added SOCK5 and SOCKS5H protocols required for proxying. These are very easy to test and validate.

**Comment by wps132230** [comment]
@rvernica We have some pre-built binaries in https://sdk.amazonaws.com/cpp/builds/. But unfortunately, we don't have that for CentOS or Debian at this moment.

**Comment by wps132230** [comment]
@Sunil-P We are trying to get a machine with M1 chip. The support is coming after that.

**Comment by wps132230** [comment]
@ahmedyarub Thank you for your PR! Is it still in draft or it's ready to be reviewed?

**Comment by ahmedalnuaimi** [comment]
Still draft. I'll finish it this week. I already have it working on my machine but I just want to make it more generic.
