### ISSUE TITLE
Override default http client factory.

### ISSUE THREAD

**Issue by lsong0905** [aws/aws-sdk-cpp#1377]
Hello,

I am trying to write a custom class that overrides http client factory, and, to be precise, I want to change the behavior only when #elif ENABLE_CURL_CLIENT is set. So my initial thought was to write a class that inherits from DefaultHttpClientFactory. And within my custom class, if ENABLE_CURL_CLIENT is set, I do whatever I want to do. For other cases, I call the existing functions defined in DefaultHttpClientFactory. However, I realized that the functions in DefaultHttpClientFactory are all private (also the class is not defined in the header, which my application includes), thus, I am not able to call them from the custom (or derived) class. 

Is there any way to achieve this goal? I want to check with you before I re-write the same code in my custom class.

Thank you in advance.

**Comment by JonathanHenson** [comment]
You could compose your factory with the Default http client factory. If ENABLE_CURL_CLIENT use yours, otherwise, call the default's factory function.

**Comment by lsong0905** [comment]
@JonathanHenson Thanks for the reply. The way I am trying is that I first override "httpClientFactory_create_fn" first and then decide what to call between my custom function or the default's function. Here is what I am trying. 

...
// 
options.httpOptions.httpClientFactory_create_fn = [](){ return Aws::MakeShared<MYCUSTOMFACTORY>("ALLOC_TAG"); };
...
InitAPI(options);
...

class MYCUSTOMFACTORY : public Aws::Http::HttpClientFactory
{
   Aws::Http::DefaultHttpClientFactory *default;
   ...
   std::shared_ptr<Aws::Http::HttpClient> CreateHttpClient(const Aws::Client::ClientConfiguration& clientConfiguration) const override {
   #if ENABLE_CURL_CLIENT
        // TO DO:
    #else
     return default->CreateHttpClient(clientConfiguration);
     #endif
...
}

The problem with calling the CreateHttpClient in the default http client factory is that the function is private. Therefore I am getting the error that I cannot access to the private function.

**Comment by lsong0905** [comment]
Any update on this?

**Comment by wps132230** [comment]
I think with current SDK, and the private `DefaultHttpClientFactory`, you will have to copy paste whatever inside `DefaultHttpClientFactory`, including all its member functions, and change the part of `ENABLE_CURL_CLIENT` to have a custom http client factory. And then override `httpClientFactory_create_fn`.
