### ISSUE TITLE
Looking for Unit Tests and/or other code examples of using Route53Client in C++

### ISSUE THREAD

**Issue by loboviking** [aws/aws-sdk-cpp#1379]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Windows 10
**Describe the question**
I haven't been able to find any examples of usage of the Route53Client in C++. I am particularly interested in using GeoLocation features of the Route53Client.

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
Hi @loboviking ,
Yea our documentation is regrettably lacking at the moment, but here is a quick sample to get you started, let me know if you have any questions or if this is not working for you.
```
#include <aws/route53/Route53Client.h>
#include <aws/route53/model/GetGeoLocationRequest.h>
#include <aws/route53/model/GetGeoLocationResult.h>
Aws::SDKOptions options;
using namespace Aws;

int main()
{
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;
    Aws::InitAPI(options);
    {
        Aws::Client::ClientConfiguration client_config("default");
        auto routClient = MakeShared<Aws::Route53::Route53Client>( "RouteClient");

        Route53::Model::GetGeoLocationRequest myRequest;
        myRequest.WithContinentCode("NA");

        auto outcome = routClient->GetGeoLocation(myRequest);

        if(outcome.IsSuccess()){
            std::cout<< outcome.GetResult().GetGeoLocationDetails().GetContinentName() <<std::endl;
        }else{
            std::cout<< outcome.GetError().GetMessage() << std::endl;
        }

    }
    Aws::ShutdownAPI(options);
}
```
