### ISSUE TITLE
I can not compile aws-c-event-stream, how to solve the problem?

### ISSUE THREAD

**Issue by lml0001** [aws/aws-sdk-cpp#1384]
lumenle@lumenle-virtual-machine:~/aws-c-event-stream/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:36 (include):
  include could not find load file:

    AwsCFlags

CMake Error at CMakeLists.txt:37 (include):
  include could not find load file:

    AwsSharedLibSetup

CMake Error at CMakeLists.txt:38 (include):
  include could not find load file:

    AwsSanitizers

CMake Error at CMakeLists.txt:74 (aws_set_common_properties):
  Unknown CMake command "aws_set_common_properties".

-- Configuring incomplete, errors occurred!
See also "/home/lumenle/aws-c-event-stream/build/CMakeFiles/CMakeOutput.log".

**Comment by KaibaLopez** [comment]
Hi @lml0001 ,
It looks like you're not getting the dependencies for aws-c-event-stream. Have you taken a look at the [build and install third party dependencies](https://github.com/aws/aws-sdk-cpp#to-build-and-install-third-party-dependencies) part of the readme? Unless you modified the CMakeLists.txt, you have to add the cmake arguments for install and path locations.

And just for clarification, does this error show up when you're trying to build the aws-sdk-cpp or only when you're trying to build the dependencies?

**Comment by lml0001** [comment]
> Hi @lml0001 ,
> It looks like you're not getting the dependencies for aws-c-event-stream. Have you taken a look at the build and install third party dependencies part of the readme? Unless you modified the CMakeLists.txt, you have to add the cmake arguments for install and path locations.
> And just for clarification, does this error show up when you're trying to build the aws-sdk-cpp or only when you're trying to build the dependencies?

I see some world in aws-c-event-stream/README.md ,but doesn't help the problem
## AWS C Event Stream

C99 implementation of the vnd.amazon.event-stream content-type.

## License

This library is licensed under the Apache 2.0 License.

**Comment by lml0001** [comment]
> Hi @lml0001 ,
> It looks like you're not getting the dependencies for aws-c-event-stream. Have you taken a look at the build and install third party dependencies part of the readme? Unless you modified the CMakeLists.txt, you have to add the cmake arguments for install and path locations.
> And just for clarification, does this error show up when you're trying to build the aws-sdk-cpp or only when you're trying to build the dependencies?

I see some word in aws-c-event-stream/README.md ，doesn't help the problem:
## AWS C Event Stream

C99 implementation of the vnd.amazon.event-stream content-type.

## License

This library is licensed under the Apache 2.0 License.

**Comment by KaibaLopez** [comment]
Hi @lml0001 ,
My bad,should've been clearer, I meant the [Readme for the aws-sdk-cpp repo](https://github.com/aws/aws-sdk-cpp#to-build-and-install-third-party-dependencies).
Did you follow the instructions I linked and try the cmake arguments for install and path locations for the dependencies?

**Comment by jcourtat** [comment]
Hello, same for me. I'm trying to make rpm packages to ease deployment of my software.

 $ cat aws-c-common.spec
 Summary:            Core c99 package for AWS SDK for C
Name:               aws-c-common
Version:            0.4.42
Release:            0%{?dist}
License:            Apache v2.0
Group:              Development/Tools
Source:             https://github.com/awslabs/aws-c-common/archive/v%{version}.tar.gz
URL:                https://github.com/awslabs/aws-c-common
BuildRequires:      make cmake3 gcc

%description

%package devel
Summary:            Core c99 package for AWS SDK for C, Development files
Group:              Development/Libraries

%description devel
Core c99 package for AWS SDK for C. Includes cross-platform primitives, configuration,
data structures, and error handling.
Development files for the AWS C Common library.

%prep
%autosetup -n aws-c-common-%{version}

%build
mkdir build && cd build
cmake3 -DCMAKE_INSTALL_PREFIX=%{buildroot}/usr ..
make

%install
cd build && make install

%files devel
%{_libdir}/libaws-c-common.a
%{_libdir}/aws-c-common/cmake
%{_libdir}/cmake
%{_includedir}/aws

rpmbuild -ba aws-c-common.spec

$ cat aws-checksums.spec 
Summary:            Cross-Platform HW accelerated CRC32c and CRC32
Name:               aws-checksums
Version:            0.1.7
Release:            0%{?dist}
License:            Apache v2.0
Group:              Development/Tools
Source:             https://github.com/awslabs/aws-checksums/archive/v%{version}.tar.gz
URL:                https://github.com/awslabs/aws-checksums
BuildRequires:      make cmake3 gcc

%description
Cross-Platform HW accelerated CRC32c and CRC32 with fallback to efficient SW implementations.
C interface with language bindings for each of our SDKs

%package devel
Summary:            Cross-Platform HW accelerated CRC32c and CRC32
Group:              Development/Libraries

%description devel
Cross-Platform HW accelerated CRC32c and CRC32 with fallback to efficient SW implementations.
C interface with language bindings for each of our SDKs
Development files for the AWS checksums library.

%prep
%autosetup -n aws-checksums-%{version}

%build
mkdir build && cd build
cmake3 -DCMAKE_INSTALL_PREFIX=%{buildroot}/usr ..
make

%install
cd build && make install

%files devel
%{_libdir}/libaws-checksums.a
%{_libdir}/aws-checksums/cmake
%{_includedir}/aws

rpmbuild -ba aws-checksums.spec

$ sudo rpm -ivh /home/jcourtat/rpmbuild/RPMS/x86_64/aws-c-common-devel-0.4.42-0.el7.x86_64.rpm
$ sudo rpm -ivh /home/jcourtat/rpmbuild/RPMS/x86_64/aws-checksums-devel-0.1.7-0.el7.x86_64.rpm

$ cat aws-c-event-stream.spec 
Summary:            C99 implementation of the vnd.amazon.event-stream content-type.
Name:               aws-c-event-stream
Version:            0.1.5
Release:            0%{?dist}
License:            Apache v2.0
Group:              Development/Tools
Source:             https://github.com/awslabs/aws-c-event-stream/archive/v%{version}.tar.gz
URL:                https://github.com/awslabs/aws-c-event-stream
BuildRequires:      make cmake3 gcc

%description
C99 implementation of the vnd.amazon.event-stream content-type.

%package devel
Summary:            Cross-Platform HW accelerated CRC32c and CRC32
Group:              Development/Libraries

%description devel
C99 implementation of the vnd.amazon.event-stream content-type.
Development files for the AWS c-event-stream library.

%prep
%autosetup -n aws-c-event-stream-%{version}

%build
mkdir build && cd build
cmake3 -DCMAKE_INSTALL_PREFIX=%{buildroot}/usr -DCMAKE_PREFIX_PATH=%{buildroot}/usr  ..
make

%install
cd build

make install
rm `find %{buildroot} -name "*.cmake"`

%files devel
%{_libdir}/libaws-c-event-stream.a
%{_includedir}/aws

rpmbuild -ba aws-c-event-stream.spec
=> same issue as one previously declared.

$ tree /usr/lib64/cmake
/usr/lib64/cmake
├── AwsCFlags.cmake
├── AwsCheckHeaders.cmake
├── AwsFindPackage.cmake
├── AwsLibFuzzer.cmake
├── AwsSanitizers.cmake
├── AwsSharedLibSetup.cmake
├── AwsSIMD.cmake
├── AwsTestHarness.cmake
└── libwebsockets

$ tree /usr/lib64/aws-c*
/usr/lib64/aws-c-common
└── cmake
    ├── aws-c-common-config.cmake
    └── static
        ├── aws-c-common-targets.cmake
        └── aws-c-common-targets-noconfig.cmake
/usr/lib64/aws-checksums
└── cmake
    ├── aws-checksums-config.cmake
    └── static
        ├── aws-checksums-targets.cmake
        └── aws-checksums-targets-noconfig.cmake

**Comment by jcourtat** [comment]
Hello, i added  -DBUILD_SHARED_LIBS=YES in cmake invocation to all spec files, but issue remains exactly the same.
i tryed to change CMAKE_MODULE_PATH to /usr/lib64/cmake, cmake doesn't fails but make didn't find the headers directory

rpmbuild -ba aws-c-event-stream.spec
Exécution_de(%prep) : /bin/sh -e /var/tmp/rpm-tmp.1GdBuJ
+ umask 022
+ cd /home/jcourtat/rpmbuild/BUILD  
+ cd /home/jcourtat/rpmbuild/BUILD  
+ rm -rf aws-c-event-stream-0.1.5   
+ /usr/bin/gzip -dc /home/jcourtat/rpmbuild/SOURCES/v0.1.5.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd aws-c-event-stream-0.1.5
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Exécution_de(%build) : /bin/sh -e /var/tmp/rpm-tmp.bPA2ON
+ umask 022
+ cd /home/jcourtat/rpmbuild/BUILD  
+ cd aws-c-event-stream-0.1.5
+ mkdir build
+ cd build
+ cmake3 -DCMAKE_MODULE_PATH=/usr/lib64/cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/home/jcourtat/rpmbuild/BUILDROOT/aws-c-event-stream-0.1.5-0.el7.x86_64/usr -DCMAKE_PREFIX_PATH=/home/jcourtat/rpmb.
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jcourtat/rpmbuild/BUILD/aws-c-event-stream-0.1.5/build
+ make V=1
Scanning dependencies of target aws-c-event-stream
[  9%] Building C object CMakeFiles/aws-c-event-stream.dir/source/event_stream.c.o
/home/jcourtat/rpmbuild/BUILD/aws-c-event-stream-0.1.5/source/event_stream.c: In function 'aws_event_stream_library_init':
/home/jcourtat/rpmbuild/BUILD/aws-c-event-stream-0.1.5/source/event_stream.c:71:9: error: implicit declaration of function 'aws_common_library_init' [-Werror=implicit-function-declaration]
         aws_common_library_init(allocator);
         ^
/home/jcourtat/rpmbuild/BUILD/aws-c-event-stream-0.1.5/source/event_stream.c: In function 'aws_event_stream_library_clean_up':
/home/jcourtat/rpmbuild/BUILD/aws-c-event-stream-0.1.5/source/event_stream.c:79:9: error: implicit declaration of function 'aws_unregister_error_info' [-Werror=implicit-function-declaration]
         aws_unregister_error_info(&s_list);
         ^
/home/jcourtat/rpmbuild/BUILD/aws-c-event-stream-0.1.5/source/event_stream.c:80:9: error: implicit declaration of function 'aws_common_library_clean_up' [-Werror=implicit-function-declaration]
         aws_common_library_clean_up();
         ^
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/aws-c-event-stream.dir/source/event_stream.c.o] Error 1
make[1]: *** [CMakeFiles/aws-c-event-stream.dir/all] Error 2
make: *** [all] Error 2

[jcourtat@atlantique aws] (master)$ grep -nRs aws_common_library_init /usr/include/
/usr/include/aws/common/common.h:42:void aws_common_library_init(struct aws_allocator *allocator);
i don't know how to tell cmake to add include directory /usr/include/aws

**Comment by KaibaLopez** [comment]
@jcourtat , I honestly can't reproduce this so I'm kind of shooting in the dark here, sorry if this is a bit frustrating.
I think the first thing I'd like you to try is upgrading to a newer GCC version, if you're planning on using the C++ sdk you're going to need to have 4.9+ anyways so that's a good starting point.
Second, make sure that the dependencies were properly installed in the location you specified, and that -DCMAKE_PREFIX_PATH points there (as in there were no errors on them before you tried installing c-event-stream).
You should not need the -DCMAKE_MODULE_PATH btw.
Let me know how it goes

**Comment by ChrisCates** [comment]
@KaibaLopez, honestly, you shouldn't be suggesting him to look at the `README.md` when the `README.md` instructions are clearly wrong.

In order to correctly compile the third party dependencies, you need to specify the flag `CMAKE_INSTALL_LIBDIR`.

An example command that will make this successfully compile is:

```bash
cmake .. -DCMAKE_INSTALL_LIBDIR="/usr/local/lib"
sudo make && make install
```

I am more than happy to send a PR updating the README to have the correct instructions for third party dependencies to compile.
