### ISSUE TITLE
Is Filter Expression possible with DynamoDB?

### ISSUE THREAD

**Issue by DevGarou** [aws/aws-sdk-cpp#1385]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Platform: Windows 10
Target: Windows
Built on Unreal Engine

**Describe the question**
Is it possible to use Filter expression when Scanning data in a table of DynamoDB?
I can retrieve all the data with a simple scan. When I try to add a filter expression it just skips the data it should send back. I'm wondering if filter expressions work with DynamoDB from C++ or if I just forgot something...
Note: I can see it scanned all the elements of the table 

Code to generate the Scan Request:

```
	Aws::DynamoDB::Model::ScanRequest ScanRequest;
	ScanRequest.SetTableName(TCHAR_TO_UTF8(*ConnectedUsersTableName));

	Aws::DynamoDB::Model::AttributeValue FilterValue;
	FilterValue.AddSItem("1");

	ScanRequest.SetFilterExpression("GarouVersion = :version");
	ScanRequest.AddExpressionAttributeValues(":version", FilterValue);

	s_DynamoDBClient->ScanAsync(ScanRequest, Lambda);
```
**Logs/output**
If applicable, add logs or error output.

**Comment by KaibaLopez** [comment]
Hi @DevGarou ,
Can you try changing the `FilterValue.AddSItem("1");` to `FilterValue.SetS("1");` and let me know if that works for you?
