### ISSUE TITLE
GetOjbect size more than 512MB,  then errr!

### ISSUE THREAD

**Issue by hanqingwu** [aws/aws-sdk-cpp#1386]
Hi,

when i try  getobject size  about 4GB,   then  i  get  response error .  from 

aws-sdk-cpp\aws-cpp-sdk-core\source\http\windows\WinSyncHttpClient.cpp

            response->GetResponseBody().write(body, read);  <-------

and  numBytesResponseReceived  reach  about 512MB..

so  can you give dome advices  about  how to getObject  more than 4GB ?

    while (DoReadData(hHttpRequest, body, bodySize, read) && read > 0 && success)
        {
            response->GetResponseBody().write(body, read);
            if (read > 0)
            {
                numBytesResponseReceived += read;
                if (readLimiter != nullptr)
                {
                    readLimiter->ApplyAndPayForCost(read);
                }
                auto& receivedHandler = request.GetDataReceivedEventHandler();
                if (receivedHandler)
                {
                    receivedHandler(&request, response.get(), (long long)read);
                }
            }

            success = success && ContinueRequest(request) && IsRequestProcessingEnabled();
        }

**Comment by KaibaLopez** [comment]
Hi @hanqingwu ,
Sorry the comment is a bit hard to read....
Can you tell me what service you're trying to use? and maybe a more complete code sample that reproduces this issue?
Also please try to clean up the  markdown so that it is easier to read.

**Comment by hanqingwu** [comment]
thanks reply.
i  add a  feature,   when  numBytesResponseReceived  more than 100MB,    i  release  response->GetResponseBody() and renew the  stream ,   so  it works .
