### ISSUE TITLE
ProcessCredentialsProvider not in default provider chain

### ISSUE THREAD

**Issue by sidewinder12s** [aws/aws-sdk-cpp#1388]
**Is your feature request related to a problem? Please describe.**
Is there a reason that the ProcessCredentialsProvider is not included in the default chain? It seems to be in place for at least Boto and Go SDKs, and the slight deviations on this common behavior of AWS SDKs is somewhat annoying when working with multiple language SDKs

**Describe the solution you'd like**
Have Default Credential Provider chain match the behavior of the other language SDKs

**Describe alternatives you've considered**
Alternative is you need to manage your own cred chain, but if you're new to the SDK from another language this seems super easy to overlook. 

**Additional context**
There seem to be a few different tickets floating around this repo that are of similar problems (this SDK behavior not matching the other language SDKs)

**Comment by KaibaLopez** [comment]
Hi @sidewinder12s ,
Hmm, I'll look into that, I'm not sure we have a defined standard on what the default chain should be across sdks.
I'll get back to you on this as soon as I can, ah and thanks for the PR!

**Comment by sidewinder12s** [comment]
Ya, as I've started dealing with more than one SDK the inconsistencies/lack of clear definition of what should be standard behavior is fairly insidious with how far into each SDK the behavior can be. Boto seems to not even really expose the ProcessCredentailsProvider in a similar manner as this (it's just on). And I've only been trying to get AWS SSO working for them 😞

**Comment by KaibaLopez** [comment]
Just as an update, it looks like this should be part of the default provider chain so I'm taking a look at your PR, just need to check with our tests to make sure we are properly testing this, hopefully we'll be able to merge this soon.
