### ISSUE TITLE
CMakeLists.txt not generating vcxproj correctly for static libraries

### ISSUE THREAD

**Issue by mattman71** [aws/aws-sdk-cpp#139]
When I use cmake to specify my desired environment for building, like this:
cmake . -DTARGET_ARCH="WINDOWS" -DSTATIC_LINKING=1 -G "Visual Studio 14 Win64"

I get .vcxproj files that have:
&lt;RuntimeLibrary&gt;MultiThreadedDebugDLL&lt;/RuntimeLibrary&gt;
and
&lt;RuntimeLibrary&gt;MultiThreadedDLL&lt;/RuntimeLibrary&gt;

instead of what they should be:
&lt;RuntimeLibrary&gt;MultiThreadedDebug&lt;/RuntimeLibrary&gt;
&lt;RuntimeLibrary&gt;MultiThreaded&lt;/RuntimeLibrary&gt;

I fixed this on my local copy, but I'm a noob, both to this project as well as to cmake, so I'm not naïve enough to try to push my change back without someone reviewing to either approve or do it in a more proper way.

I've attached a patch file of what I did to fix the problem, so hopefully someone who knows what they're doing can incorporate it into the solution so everyone (who is using Visual Studio, Windows, and wants Static libraries) can benefit.

[CMakeLists.patch.txt](https://github.com/aws/aws-sdk-cpp/files/192001/CMakeLists.patch.txt)

Thanks,
-Matt

**Comment by JonathanHenson** [comment]
Can you submit a pull request?

**Comment by mattman71** [comment]
Sorry, I don't understand. I just did a pull, and there were changes since my last pull, but the problem I mentioned still exists. There were no changes in the CMakeLists.txt that I could see that would effect my patch, thus my confusion about a pull request. Can you clarify? (remember, I already admitted I'm a noob, haha)

**Comment by JonathanHenson** [comment]
Google "github create a pull request"

**Comment by bretambrose** [comment]
Does this issue cause things not to build or run properly?  Or does it just result in a link/run set up that you don't want?

**Comment by mattman71** [comment]
It causes a linker failure with my static project, so I'm unable to build successfully.

**Comment by mattman71** [comment]
@JonathanHenson thanks, how embarrassing! (forgot to mention I'm a github noob as well, coming from subversion land)

**Comment by bretambrose** [comment]
In my opinion, the real issue (and I'm at fault here, this was originally my doing) is that we're using a single flag (STATIC_LINKING) to control two related-but-not-fully-coupled things: what kind of library targets to generate (static vs. shared) vs. how to link in system/standard libraries.  One of these combinations (make shared libraries but link them statically to system/stdlib) doesn't make any sense whatsoever, but I think the other three are all valid.  We've been able to use static AWS libraries that use the DLLs for stdlib/clib without issue, so it seems like maybe we should be making this an option rather than mandatory.  If your patch/pull adds this as an optional setting then that would be perfect (I just skimmed it and didn't actually apply to see the full change).

**Comment by mattman71** [comment]
@bretambrose I'll create a pull request, then let you guys make it fit the way it should. I'm not good enough with cmake to be able to fix the multiple scenario options you mention. I'll defer to those who know more what they're doing. All I care about at this point is if it works. :)

**Comment by mattman71** [comment]
Either I'm an idiot (most likely), or I don't have access to create a new branch or push to it.

If someone else wants to run with this, I fixed some typos in my original attachment, and the corrected patch is here:

[CMakeLists.patch.txt](https://github.com/aws/aws-sdk-cpp/files/192226/CMakeLists.patch.txt)

This is what I did, and what went wrong, so everybody can laugh at whatever noob mistake I may have made along the way:
git clone https://github.com/aws/aws-sdk-cpp.git
cd aws-sdk-cpp
git checkout -b M139
<apply changes>
git commit -a -m "<real comment went in here>"
git push --set-upstream origin master
remote: Permission to aws/aws-sdk-cpp.git denied to mattman71.
fatal: unable to access 'https://github.com/aws/aws-sdk-cpp.git/': The requested URL returned error: 403

**Comment by bretambrose** [comment]
Rather than trying to push to the aws/aws-sdk-cpp repo you can fork aws/aws-sdk-cpp into your account, make the change there, and then have the pull request be from your forked version to the aws main repo.

**Comment by mattman71** [comment]
Thanks for the tip, @bretambrose . I made my attempt to do that, hopefully it's not messed up. My forehead is bloody enough for the day. :) [](https://github.com/aws/aws-sdk-cpp/pull/140)

**Comment by mattman71** [comment]
Hmm, link didn't go through. Trying again... https://github.com/aws/aws-sdk-cpp/pull/140

**Comment by bretambrose** [comment]
I believe this was addressed with the FORCE_SHARED_CRT cmake param

**Comment by mattman71** [comment]
Agree. My latest build with 0.12.15 went OK. Thanks for the fix!
