### ISSUE TITLE
mediastore data streaming putobject

### ISSUE THREAD

**Issue by bongjj77** [aws/aws-sdk-cpp#1390]
I am trying to chunked upload live audio data(.mp4) to the mediastore with PutObjectAsync.
Implement [streambuf] to provide real-time data from other threads.(set duration)

In the 2-second duration setting, Windows/Linux operates normally.
upload Windows/Linux operates normally at a bit rate of 200Kbps or higher.

If I set the duration to 10 seconds below 200Kbps, only the connection to the mediasotre server will be disconnected within 3-4 seconds on Linux (Windows works normally).

The same is true if I change the ClientConfiguration settings to set curl timeout.

How to upload 100~200K real-time streaming data on Linux?

**Comment by KaibaLopez** [comment]
hi @bongjj77 ,
Would you mind giving me some sample code so that I can try and reproduce this ? Or giving me a sanitized version of the logs?

**Comment by bongjj77** [comment]
hi @KaibaLopez This is part of my sample code.

**MyMediaData is streambuf class underflow implement** 

class MyMediaData : public std::streambuf

bool MyMediaData::AppendData(const std::shared_ptr<uint8_t>& data, int size) {
    if (size > 0 && (_appendSize + size) <= MaxStreamBufferSize) {
        std::unique_lock<std::mutex> lock(_dataLock);
        _streamData->insert(_streamData->end(), &(*data), &(*data) + size);
        _appendSize += size;
        lock.unlock();
        _condition.notify_one();
    }
    return false;
}

std::pair<uint32_t, char*> MyMediaData::_ReadBuffer() {
    std::unique_lock<std::mutex> lock(_dataLock);
    while (_isCompleted == false && _streamData->size() == 0) {
        _condition.wait(lock);
    }

    if (_streamData->size() > 0) {
        _bufferData = _streamData;
        _streamData = std::make_shared<std::vector<char>>();
        return {_bufferData->size(), _bufferData->data()};
    }
    return {0, nullptr};
}

int_type MyMediaData::underflow() {
    if (auto [size, buffer] = _ReadBuffer(); size != 0) {
        setg(buffer, buffer, buffer + size);
        return traits_type::to_int_type(*gptr());
    }
    return traits_type::eof();
}

**1. mediastore data client create**

bool MyMediaStore::Create(const std::shared_ptr<MediaStoreParam>& param) {
    SdkInit(static_cast<Aws::Utils::Logging::LogLevel>(param->logLevel));

    auto config = Aws::MakeShared<ClientConfiguration>(AllocTag);
    config->region = param->region;
    config->scheme = Scheme::HTTPS;
    config->connectTimeoutMs = 1000;
    config->requestTimeoutMs = 15000;
    // config->lowSpeedLimit = 1; 
    
    _client = Aws::MakeShared<MediaStoreClient>(AllocTag, Aws::Auth::AWSCredentials{param->accessKeyID.c_str(), param->secretKey.c_str()}, *config);

    // Container Check(get endpoint)
    DescribeContainerRequest request;
    request.SetContainerName(param->container.c_str());
    auto result = _client->DescribeContainer(request);
    if (result.IsSuccess() == false || result.GetResult().GetContainer().GetStatus() != Aws::MediaStore::Model::ContainerStatus::ACTIVE) {        
        _client = nullptr;
        return false;
    }

    // Data client setting
    config->endpointOverride = param->endPoint;  // result.GetResult().GetContainer().GetEndpoint();
    _dataClient = Aws::MakeShared<MediaStoreDataClient>(AllocTag, Aws::Auth::AWSCredentials{param->accessKeyID.c_str(), param->secretKey.c_str()}, *config);

    _folder = param->folder;

    return true;
}

**2. MyMediaData crate and PutObjectAsync call** 

bool MyMediaStore::StartMediaData(const std::string& fileName) {
    if (_dataClient != nullptr && fileName.empty() == false) {
        if (std::lock_guard<std::mutex> lock(_mediaDataLock); _mediaDataList.count(fileName) == 0) {
            auto mediaBuffer = std::make_shared<MyMediaData>(fileName);
            _mediaDataList[fileName] = mediaBuffer;
            
            // Put request
            PutObjectRequest request;
            request.SetPath(_GetMediaPath(fileName).c_str());
            request.SetUploadAvailability(UploadAvailability::STREAMING);
            request.SetBody(Aws::MakeShared<Aws::IOStream>(AllocTag, &(*mediaBuffer)));

            // Put object(async)
            _dataClient->PutObjectAsync(request,
                                        std::bind(&MyMediaStore::_OnMediaDataFinished, shared_from_this(), std::placeholders::_1, std::placeholders::_2,
                                                  std::placeholders::_3, std::placeholders::_4),
                                        Aws::MakeShared<Aws::Client::AsyncCallerContext>(AllocTag, fileName.c_str()));
            return true;
        }
    }
    return false;
}

**3. stream data append function**

bool MyMediaStore::AppendMediaData(const std::string& fileName, const std::shared_ptr<uint8_t>& data, int size) {
    if (_dataClient != nullptr && fileName.empty() == false) {
        if (std::lock_guard<std::mutex> lock(_mediaDataLock); _mediaDataList.count(fileName) > 0 && _mediaDataList[fileName]->IsCompleted() != true) {
            _mediaDataList[fileName]->AppendData(data, size);
            return true;
        }
    }

    return false;
}

aws c++ sdk version is latest 
linnux is centos test
windows is windows10 test

Stream the data to the media store by calling the AppendMediaData function.

If AppendMediaData is added with an average of 200Kbps or more on a periodic basis for 10 seconds, the data will be uploaded.
AppendMediaData function calls 500 bytes of data about 50 times per second (for 10 seconds)


**However, if the data is called with an average of 200Kbps or less (100Kbps), the data cannot be uploaded by calling _OnMediaDataFinished after 3-4 seconds of uploading data in the middle. (Linux only)**
AppendMediaData function calls 200~250 bytes of data about 50 times per second (for 10 seconds)

**Comment by bongjj77** [comment]
I knew the cause above


If there is no data transmitted for more than 3 seconds after connecting, the mediastore server disconnects.
Windows sends data when 8192 data is collected from aws sdk.
(static const uint32_t HTTP_REQUEST_WRITE_BUFFER_LENGTH = 8192;)


Windows sends data when 8192Byte data is collected from aws sdk.
(static const uint32_t HTTP_REQUEST_WRITE_BUFFER_LENGTH = 8192;)


Linux sends data when 65524ByteByte data is collected from aws sdk.
(
CurlHttpClient.cpp file - function ReadBody(char* ptr, size_t size, size_t nmemb, void* userdata) from curl
size value is 65524
)

If you don't want to hang up within 3 seconds
Windows min bitrate 8192Byte*8/3 = About 21kbps up
Linux min bitrate 65524Byte*8/3 = About 175kbps up

The simple solution is
CurlHandleContainer::SetDefaultOptionsOnHandle function
add curl option 
curl_easy_setopt(handle, CURLOPT_UPLOAD_BUFFERSIZE, 8192);
function ReadBody(char* ptr, size_t size, size_t nmemb, void* userdata) 
he size value goes to 16372

Do you have any plans to add configuration options to ClientConfiguration?
Please let me know if there is any other solution

**Comment by KaibaLopez** [comment]
Hi @bongjj77 ,
So I'll take a look into this, but it'll probably take me longer than it would take you, so let me answer your questions first, and I'll update again if I can reproduce your problem and get a solution.

> Do you have any plans to add configuration options to ClientConfiguration?

We already, have options for client configurations, you can see them and their descriptions in the client configuration [section of the ReadMe](https://github.com/aws/aws-sdk-cpp#client-configuration).

> **And is there a way to aws sdk or site settings to prevent disconnection without sending data for more than 3 seconds after connecting to the mediastore server?**

Again, I haven't tested this yet, but I'm pretty sure that can be configured in the [clientConfiguration.requestTimeoutMs](https://github.com/aws/aws-sdk-cpp/blob/a88a6c995c2627f9380a52178a87dfdb3209abed/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp#L55) value. 

Let me know if these help out or if I'm misunderstanding the questions.

**Comment by bongjj77** [comment]
hi @KaibaLopez  ,
I didn't speak English very well, so I put the last question wrong...

If the MediaData Client does not send data for more than 3 seconds after connecting to the MediaStore, the connection is disconnected by sending a fin packet that disconnects from the MediaStore server to the client. (check with wireshark)


If the MediaData Client does not send data for more than 3 seconds after connecting to the MediaStore, the connection is disconnected by sending a fin packet that disconnects from the MediaStore server to the client. (check with wireshark)

**Is there any way to make this time more than 10 seconds?**
