### ISSUE TITLE
S3 Object HEAD Request results in No response body error

### ISSUE THREAD

**Issue by erksch** [aws/aws-sdk-cpp#1391]
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
When using the C++ S3 SDK to read the size of the file, I would perform a head request and read the ContentLength like so:

```C++
Aws::S3::S3Client s3_client;
Aws::S3::Model::HeadObjectRequest request;
request.SetBucket(bucket_name);
request.SetKey(object_name);

Aws::S3::Model::HeadObjectOutcome outcome = s3_client.HeadObject(request);

if (outcome.IsSuccess()) {
    // success!
} else {
    auto error = outcome.GetError();
    std::string errorMessage = "Error: " + error.GetExceptionName() + " - " + error.GetMessage();
    std::cout << errorMessage;
}
```

But this always results in a "No response body" error, which is kind of expected since a head request does not return a response body. However, this error should obviously not occur for head requests.

**SDK version number**
Master @ fe55d84c808243baf48468369e98e09018e959a3

**Platform/OS/Hardware/Device**
Linux Ubuntu 20.04.

**To Reproduce (observed behavior)**
See above.

**Logs/output**
No response body.

**Comment by KaibaLopez** [comment]
Hi @erksch ,
I think I'm missing something here, I've ran your code but I get a successful request, could you maybe show me your logs? (remember to censor out private information there)

**Comment by erksch** [comment]
Hmm, you're right I tried it again with a simpler application than I had before and it works.
Where I experienced the error was when creating a custom c++ runtime for lambda with the same code and running it on AWS.
