### ISSUE TITLE
Nuget stable version is from Oct2018

### ISSUE THREAD

**Issue by drorgy** [aws/aws-sdk-cpp#1393]
Hi, 
I'm looking for the latest stable version - Nuget says it's from Oct2018. Is this correct? 
I see there are frequent releases - are they all considered stable?
Also I'm building cross platform solution and getting windows packages with Nuget while Linux I compile from release (code). So should I get the Oct2018 release for Linux as well or should I somehow get hold of a more recent version for windows?
Thanks,
Dror

**Comment by KaibaLopez** [comment]
Hi @drorgy ,
Sorry, sorry we don't support Nuget packages anymore, so yea the 2018 is the latest one of those, I'd recommend building from source or using vcpkg.

**Comment by drorgy** [comment]
Thanks. 
So which is the latest most stable release (the recommended version to use).

**Comment by drorgy** [comment]
Thanks.
