### ISSUE TITLE
Uncatchable exception Aws exception: RequestLimitExceeded (503) Unable to parse ExceptionName

### ISSUE THREAD

**Issue by keef-cognitiv** [aws/aws-sdk-cpp#1394]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
This was observed on release 1.7.212. Apologies if it's been fixed already since. I have been putting off opening an issue.

We have a service that's using PutObjectAsync to S3 and PutRecordAsync in Kinesis. I'm not sure which of these is triggering the issue. We can get into a condition where it tries to do lots of these across a cluster in a single AZ. I can deal with the error itself. The problem is (and the reason I don't know what's causing it) that when we get rate limited, it crashes the whole process. The error happens in the background worker pool handling the async responses to the calls. And the exception bubbles all the way up, through 100% aws-sdk-cpp code until the process is killed with abort() such that the callback never even sees the response.

```
terminate called after throwing an instance of 'std::logic_error'
  what():  Aws exception: RequestLimitExceeded (503) Unable to parse ExceptionName: RequestLimitExceeded Message: Request limit exceeded. with address : 52.46.150.99
```

I would instead expect this error to be catchable in user code by calling the Async callback with an error response rather than crashing the whole process.

Again, apologies if it's been fixed since .212. I found no similar issues when searching

**SDK version number**
1.7.212

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Linux / EC2 c5 class instances

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
Use one (or both) of those two calls and get rate limited using purely Async versions.

**Expected behavior**
Pass the error to the async callback rather than crash the process.

**Logs/output**
```
terminate called after throwing an instance of 'std::logic_error'
  what():  Aws exception: RequestLimitExceeded (503) Unable to parse ExceptionName: RequestLimitExceeded Message: Request limit exceeded. with address : 52.46.150.99
```

**Additional context**
Just re-iterating that this was last observed on 1.7.212. We are upgrading to 1.7.350 today to see if the issue is resolved but after globbing through issues, I couldn't find other instances of this issue.

**Comment by KaibaLopez** [comment]
Hi @keef-cognitiv ,
Thanks for bringing this up, we're going to be taking a closer look at this see what we can do about this, or figure out if there is a workaround.
In the mean time if you figure out a workaround feel free to comment here, or if you have a solution in mind we also accept PRs

**Comment by keef-cognitiv** [comment]
We still saw this happening initially - but we've since upgraded and no longer see this ever. Newer versions of the library do not have the issue at all as far as we can detect. So I am closing.
