### ISSUE TITLE
C2054/C2085/C2143/C4013 errors when building AWS SDK API C++

### ISSUE THREAD

**Issue by RichDee** [aws/aws-sdk-cpp#1396]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on? Windows 8.1 Professional (x64) (build 9600.19728) / Dell OptiPlex 9020 00

**Describe the question**
I am endeavoring to build the AWS SDK API (CPP) on my Windows 8.1 Professional (x64) (build 9600.19728) development workstation.

I downloaded the latest "aws sdk cpp" / "AWS SDK for C++" master branch from:
https://github.com/aws/aws-sdk-cpp

However, running cmake yields the following errors (n.b., the complete cmake stdout/stderr output is in the attached file):
	...
		crc_sw.c
	E:\Debugging\myfolder\Inventory\AWS SDK API\.deps\build\src\AwsChecksums\source\crc_sw.c(1130): error C2054: expected '(' to follow 'inline' [E:\Debugging\myfolder\Inventory\AWS SDK API\.deps\build\src\AwsChecksums-build\aws-checksums.vcxproj] [E:\Debugging\myfolder\Inventory\AWS SDK API\.deps\AwsChecksums.vcxproj]
	E:\Debugging\myfolder\Inventory\AWS SDK API\.deps\build\src\AwsChecksums\source\crc_sw.c(1134): error C2085: 's_crc_generic_align' : not in formal parameter list [E:\Debugging\myfolder\Inventory\AWS SDK API\.deps\build\src\AwsChecksums-build\aws-checksums.vcxproj] [E:\Debugging\myfolder\Inventory\AWS SDK API\.deps\AwsChecksums.vcxproj]
	E:\Debugging\myfolder\Inventory\AWS SDK API\.deps\build\src\AwsChecksums\source\crc_sw.c(1134): error C2143: syntax error : missing ';' before '{' [E:\Debugging\myfolder\Inventory\AWS SDK API\.deps\build\src\AwsChecksums-build\aws-checksums.vcxproj] [E:\Debugging\myfolder\Inventory\AWS SDK API\.deps\AwsChecksums.vcxproj]
	E:\Debugging\myfolder\Inventory\AWS SDK API\.deps\build\src\AwsChecksums\source\crc_sw.c(1222): warning C4013: 's_crc_generic_align' undefined; assuming extern returning int [E:\Debugging\myfolder\Inventory\AWS SDK API\.deps\build\src\AwsChecksums-build\aws-checksums.vcxproj] [E:\Debugging\myfolder\Inventory\AWS SDK API\.deps\AwsChecksums.vcxproj]
	CMake Error at CMakeLists.txt:235 (message):
	  Failed to build third-party libraries.
[StdoutAndStderr.txt](https://github.com/aws/aws-sdk-cpp/files/4780386/StdoutAndStderr.txt)

	-- Configuring incomplete, errors occurred!

I am using the latest version of cmake:
	$ cmake --version
	cmake version 3.17.3

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
Hi @RichDee ,
These kind of errors are usually related to the compiler you're using, for example C2054 happens because of **inline**.... from [microsoft documentation](https://docs.microsoft.com/en-us/cpp/cpp/inline-functions-cpp?redirectedfrom=MSDN&view=vs-2019#inline-__inline-and-__forceinline):

> The inline keyword is available only in C++. The __inline and __forceinline keywords are available in both C and C++.

So the first thing I'd like to ask while I set up to test this, can you verify that you have visual studio 15 or later installed? and that cmake is trying to use C++ 11?

**Comment by RichDee** [comment]
I am running an earlier version of VS: "Microsoft Visual Studio Professional 2013 with Update 4" -- version 12.0.40629.

There are a lot of C++ distributables on the workstation -- from VS C++ 2005 / v 8.x to VS C++ 2015 / v14.0.x

Is this supported?

**Comment by KaibaLopez** [comment]
While you're at that, I may be wrong but I believe that if you have the distributables installed you should be able to tell cmake to build it for vs 2015 by adding the -G attribute to the command:

`cmake -G "Visual Studio 14 2015" -A x64 `

**Comment by RichDee** [comment]
So I upgraded my VS to VS2019.

Here's my current build environment:
- Windows 8.1 Professional (x64) (build 9600.19728)
- Microsoft Visual Studio Professional 2019 16.6.2
- cmake version 3.17.3

Now when I try to build the AWS SDK, it gets a lot farther but I get errors (see attached file) when compiling 8 of the thousands of src files:
- aws-sdk-cpp-master\aws-cpp-sdk-fsx\source\FSxClient.cpp 
- aws-sdk-cpp-master\aws-cpp-sdk-fsx\source\model\Backup.cpp 
- aws-sdk-cpp-master\aws-cpp-sdk-fsx\source\model\DescribeFileSystemsResult.cpp 
- aws-sdk-cpp-master\aws-cpp-sdk-fsx\source\model\CreateFileSystemFromBackupResult.cpp 
- aws-sdk-cpp-master\aws-cpp-sdk-fsx\source\model\CreateBackupResult.cpp 
- aws-sdk-cpp-master\aws-cpp-sdk-fsx\source\model\UpdateFileSystemResult.cpp 
- aws-sdk-cpp-master\aws-cpp-sdk-fsx\source\model\CreateFileSystemResult.cpp 
- aws-sdk-cpp-master\aws-cpp-sdk-fsx\source\model\DescribeBackupsResult.cpp 

[AWS_SDK_VS2019_COMPILE_ERRORS.txt](https://github.com/aws/aws-sdk-cpp/files/4837015/AWS_SDK_VS2019_COMPILE_ERRORS.txt)

**Comment by KaibaLopez** [comment]
Hi @RichDee ,
Yes we currently have a known problem with the fsx service, you can see #1397 for updates, it should be fixed very soon.

In the mean time I'd recommend building only the service components that you'll be using by adding the BUILD_ONLY parameter, so for example:

```
cmake .. -DBUILD_ONLY="s3;dynamodb"
```
And also, remember you have to set LongPathsEnabled to 1 on windows in order to successfully build tests.

**Comment by RichDee** [comment]
Thanks. 
Two things:
1) yesterday I built just a couple of the services (s3, config, ec2) and that build successfully
2) do I have to set LongPathsEnabled on Windows 8.1 -- or only if there is some sort of error?

**Comment by wps132230** [comment]
Hi @RichDee , the FSX issue should be fixed by: https://github.com/aws/aws-sdk-cpp/commit/8fbba83973bb8b253befad4b06fe252cc1164349

**Comment by KaibaLopez** [comment]
great!
and if your not having errors, don't worry about it, there's a specific test that might fail if you don't but nothing to worry about if you don't see the error
