### ISSUE TITLE
Convert Aws::Map<Aws::String, String> variable to std::map<std::string, std::string> variable

### ISSUE THREAD

**Issue by nitesh-idnani1** [aws/aws-sdk-cpp#1398]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Ubuntu Linux
**Describe the question**
How can I convert map of type Aws::Map<Aws::String, Aws::String> to std::map<std::string, std::string> ?

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
Hi @nitesh-idnani1 ,
I think the copy constructor fails for this, but you can either do it manually or use the insert function.
Here's an example: 
```
    Aws::Map<Aws::String, Aws::String> awsmap;
//fill the map with data.
    awsmap.insert(std::make_pair<Aws::String,Aws::String>("someKey","SomeValue"));
    ...
    awsmap.insert(std::make_pair<Aws::String,Aws::String>("someKeyX","SomeValue"));
//new map.
    std::map<std::string, std::string> stdmap;
    stdmap.insert(awsmap.begin(),awsmap.end());
    for(auto iter: stdmap){
        std::cout<< "key:" << iter.first<<std::endl;
        std::cout<< "value:" << iter.second<<std::endl;
    }
```
There could be other options though, you may not want to create a copy of the map but only to use the values inside as strings, now for most purposes Aws::String can be used as std::string, but you can also use the c_str() function and get a <const char *> too.

```
...
const char * rawVal = iter.first().c_str();
```

Hope this helps you and let me know if you got a more specific case where neither of these would work.

**Comment by nitesh-idnani1** [comment]
Does std::map insert function handle the type conversion from Aws::String to std::string correctly?

**Comment by KaibaLopez** [comment]
Alright I think I know what's happening.
I was running my sample on clang, and assumed it would behave the same way for all other platforms, but after switching to linux I got the same issue you did...

Can you try adding `-DCUSTOM_MEMORY_MANAGER=OFF` to your cmake command? And let me know if that works for you?

**Comment by wps132230** [comment]
You could use
```cpp
for(auto iter: awsmap){
    stdmap[iter.first.c_str()] = iter.second.c_str();
}
```
to convert each element in the for loop.
Or you can use `std::transform` in one line, but it's more complicated.

**Comment by nitesh-idnani1** [comment]
> Alright I think I know what's happening.
> I was running my sample on clang, and assumed it would behave the same way for all other platforms, but after switching to linux I got the same issue you did...
> 
> Can you try adding `-DCUSTOM_MEMORY_MANAGER=OFF` to your cmake command? And let me know if that works for you?

Does this flag turn off the Aws memory manager i.e. allocators used in aws constructs like string, map?

**Comment by KaibaLopez** [comment]
@nitesh-idnani1 ,
Mmm kind of,  if CUSTOM_MEMORY_MANAGENT is set to OFF, then instead of using Aws::Allocator the sdk will use std::allocator<T>, and so for practical uses Aws::String == std::string and so on.

You could also try what @wps132230  suggested,  and convert Aws::String to const char * to std::string, a bit more manual work but then you don't worry too much about the memory management settings.

**Comment by nitesh-idnani1** [comment]
Got it, thanks for your help @wps132230 @KaibaLopez .
