### ISSUE TITLE
No link to GitHub releases

### ISSUE THREAD

**Issue by markus289** [aws/aws-sdk-cpp#1401]
**Short description**: With the new layout of GitHub there does not seem to be an easy way to reach the [releases](https://github.com/aws/aws-sdk-cpp/releases) page.

**Possible solution**: As far as I can tell, you are creating tags, but you also want to [create a release](https://developer.github.com/v3/repos/releases/#create-a-release).

**Elaborate description**: Compare the side-bar of `aws-sdk-cpp` with the side-bar of `aws-c-common`.

![Untitled](https://user-images.githubusercontent.com/66057358/85828517-27ce2000-b778-11ea-8874-64f3abb856ed.png)

As you can see, there is no link to any of the releases for `aws-sdk-cpp` while they are visible for `aws-c-common`. As such, it is difficult to check for new releases.

Also, when watching the repository, i.e., `Watch [button] -> Releases only`, I am newer notified about a new release.

**Comment by markus289** [comment]
As of today, tags are listed as releases. This leaves the problem of receiving notifications about new releases/tags.

**Comment by KaibaLopez** [comment]
Hi @markus289 ,
Hmmm yea I can kind of see the value in starting to do that, will bring it up and update on how we'll approach this.
Thanks for bringing it up to us!
