### ISSUE TITLE
Conflict between native and cross-compiled version

### ISSUE THREAD

**Issue by andre237** [aws/aws-sdk-cpp#1402]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Can't use the SDK when there's a cross-compiled version of it in the same machine

**SDK version number**
1.7.363

**Platform/OS/Hardware/Device**
x86_64 computer

**To Reproduce (observed behavior)**
I've cross-compiled the SDK to arm 32 bits arch and it all went fine. Whenever I had to build an application to arm_32, I pointed it to my toolchain and that was all. Then, I decided to build the SDK for x86_64 (my computer's arch). The build process went fine as well. After that, I had a x86_64 installation at `/usr` and an arm_32 installation at `<my-toolchain-path>`. However, once I had built the x86 version, I couldn't compile any application to arm_32 that would need to include the sdk. This is the cmake error I got: 
```
CMake Error at <my-toolchain-path>/lib/cmake/AWSSDK/AWSSDKConfig.cmake:122 (message):
  AWS SDK for C++ headers found, but we were unable to locate the binaries.
  Have you deleted or moved it?

              Please make sure header files and binaries are located in INSTALL_ROOT_DIR/INCLUDE_DIR/ and INSTALL_ROOT_DIR/LIB_DIR/[PLATFORM_PREFIX]/[Debug|Config|OtherConfigs]
Call Stack (most recent call first):
  CMakeLists.txt:5 (find_package)
```

Than, using two virtual machines with the same operating system as mine, I built the SDK for x86_64 in one of them and cross-compilled to arm_32 in the other, so they would be separated, and both worked perfectly. 
My guess is this is related to some conflict when having two different builds in the same environment 

**Expected behavior**
I expect to use both versions in the same computer without having conflicts or, at least, to know that this is not possible.

**Additional context**
A important note is that, when dealing with the environment where both versions are installed, the only application that would fail to build was the one the had to include the cross-compiled version.

**Comment by singku-china** [comment]
When searching installed sdk files, by default SDK will search `/usr` directory first. That's why the firstly installed SDK (arm_32) was not looked up correctly.

**Comment by andre237** [comment]
Indeed it worked. Just changing this line enabled me to use both sdk versions.
Will be closing the issue as solved
Thanks!
