### ISSUE TITLE
How can I add a custom header value to a create bucket request?

### ISSUE THREAD

**Issue by heylaender** [aws/aws-sdk-cpp#1403]
It is possible to add a custom header to an object like:

Aws::S3::Model::PutObjectRequest object_request;
...
object_request.AddMetadata("x-emc-retention-period", QVariant(QDateTime::currentDateTimeUtc().secsTo(retentionTime)).toString().toLatin1().data());

How is it possible to do this for a CreateBucketRequest as well?

...
Aws::S3::Model::CreateBucketRequest request;	request.SetCreateBucketConfiguration(Aws::S3::Model::CreateBucketConfiguration().WithLocationConstraint(getBucketLocationContraint()));
request.SetBucket(m_bucket.toLatin1().data());
// how to set a custom header like "x-emc-retention-period"
...

**Comment by KaibaLopez** [comment]
Hi @heylaender ,
The s3 buckets don't have "metadata" or custom headers, this is an api limitation and not an sdk one though so it's not something we would be able to change.
That being said, maybe I can help you find a workaround to what you're trying to do, can you give me a bit more context on what you're trying to achieve?

**Comment by heylaender** [comment]
I'm trying to archive on DELL ECS, which has both bucket and object level retention:

http://doc.isilon.com/ECS/3.1/DataAccessGuide/ecs_c_s3_reterntion.html

Object level retention works perfect with Aws::S3::Model::PutObjectRequest::AddMetadata.

But the customer's default is bucket level retention and this is the challenge. I know that in both cases x-emc-retention-period header can be used to send it to the archiving system. But it seems that the SDK doesn't support it for buckets.

**Comment by KaibaLopez** [comment]
@heylaender ,
sorry to say but the answer kind of remains the same, even the documentation you provided states : _"This is an ECS extension and is not available in the standard S3 API. "_
The sdk only supports what the service api supports. This kind of feature must be implemented by the service first... so yea, sorry I can't help you with this one.

**Comment by F-Haun** [comment]
I had a similar problem and added a patchfile to my local build via vcpkg.
With that I could successfully set the retention on buckets and files by setting a custom header for the request objects.

[CustomHeader.txt](https://github.com/aws/aws-sdk-cpp/files/4953091/CustomHeader.txt)

It is in no way pretty, or complete, but it works for me.

**Comment by aesophor** [comment]
```cpp
CreateBucketRequest req;
req.SetBucket("your_bucket_name");
req.SetAdditionalCustomHeaderValue("X-Custom-Header-Key", "your_value");
```
