### ISSUE TITLE
Cannot upload file with accent (é) to S3

### ISSUE THREAD

**Issue by LaMague** [aws/aws-sdk-cpp#1404]
Hi,

I have an issue when trying to upload a file with accent to S3 (for example a file called "Rémi.txt") . I use Aws::S3::Model::CreateMultipartUploadRequest to upload files and never experienced any issue before. I'm using aws-sdk-cpp-1.6.25.
I am getting the following error : "Unable to parse ExceptionName: InvalidURI Message: Couldn't parse the specified URI".
I've tried escaping the special character "é" with "%C3%A9" and in that case the upload works, but the files appears on S3 as "R%C3%A9mi.txt".

Is there a solution for this?

Thanks in advance for your help!

Antoine

**Comment by KaibaLopez** [comment]
Hi @LaMague ,
I'm not able to reproduce this error on my tests or running the integration tests,meaning the objects get uploaded with the "é" character,  would you mind showing me minimal code to reproduce it?
Also, let me know what version of the sdk and what platform you're using the sdk on? (windows/mac/linux).

**Comment by LaMague** [comment]
Hi @KaibaLopez,

Thank for the response! 
So, to provide you with the requested information: I'm using aws-sdk-cpp-1.6.25, on Windows 10.

Here is a snippet of the code:

```
		Aws::Auth::AWSCredentials credentials(publicKey, secretKey);
		Aws::Client::ClientConfiguration clientConfig;
		if (!region.empty()) clientConfig.region = region;
		if (!endPointUrl.empty()) clientConfig.endpointOverride = endPointUrl;
		s3Client_.reset(new Aws::S3::S3Client(credentials, clientConfig, Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Never, true));

		// Create the multipart upload request
		Aws::S3::Model::CreateMultipartUploadRequest multipartUploadRequest;
		multipartUploadRequest.SetBucket(bucket_);
		multipartUploadRequest.SetKey(key_); // HERE my key is for example "Test_Rémi.txt" (the 'é' is encoded as "0xC3 0xA9" if I check the string byte by byte)
		multipartUploadRequest.SetStorageClass(Aws::S3::Model::StorageClassMapper::GetStorageClassForName(storageClass));
		
		Aws::S3::Model::CreateMultipartUploadOutcome multipartUploadOutcome;
		bool res = AmazonS3StoragePlugin::RetriableCommand(S3_NbRetriesBeforeGivingUp(),
			[&](bool& retriable) -> bool
		{
			multipartUploadOutcome = s3Client_->CreateMultipartUpload(multipartUploadRequest);
			retriable = multipartUploadOutcome.GetError().ShouldRetry();
			if (multipartUploadOutcome.IsSuccess() && multipartUploadOutcome.GetResult().GetUploadId().empty())
			{
				DTK_WARNINGF("multipartUploadOutcome is successful but the upload id is empty, let's try again...");
				retriable = true;
				return false;
			}
			return multipartUploadOutcome.IsSuccess(); // This is false in my case
		},
			[&]() -> void
		{
			DTK_WARNINGF("Failed to create %0 because %1. Trying again") << urlFile_ << multipartUploadOutcome.GetError().GetMessage(); // I am getting this warning in our logs with the following error: "Unable to parse ExceptionName: InvalidURI Message: Couldn't parse the specified URI"
		},
			[&]() -> void
		{
			DTK_ERRORF("Failed to create %0 because %1") << urlFile_ << multipartUploadOutcome.GetError().GetMessage();
			code_ = (int)multipartUploadOutcome.GetError().GetErrorType();
			lastErrorMsg_ = Dtk::UConv(multipartUploadOutcome.GetError().GetMessage());
			s3Client_.reset();
		}
		);

		if (!res)
			return false; // --> we end up returning false here
```

Thanks in advance for your help!

**Comment by KaibaLopez** [comment]
Hi @LaMague ,
Sorry for the delayed response, I'm still unable to reproduce your issue though... Here's my simple sample code on creating a multipartUpload request with special characters:
```
       Aws::Client::ClientConfiguration clientConfig("default");
       auto s3Client = Aws::MakeShared<Aws::S3::S3Client>("s3Client",clientConfig);
       Aws::S3::Model::CreateMultipartUploadRequest multipartUploadRequest;
		multipartUploadRequest.SetBucket("myBucketName");
		multipartUploadRequest.SetKey("éñó");
		multipartUploadRequest.SetContentType("text/plain");
        auto outcome = s3Client->CreateMultipartUpload(multipartUploadRequest);
        if(outcome.IsSuccess()){
            std::cout << "we are good" << std::endl;
        }else{
            std::cout << outcome.GetError().GetMessage() << std::endl;
        }
```
I don't know... can you think of any other root cause or way to reproduce this error?

**Comment by LaMague** [comment]
Hi @KaibaLopez ,

Thanks for the response, we've been investigating on our side and have literally just found the issue! It was actually caused by some other DLL being loaded which was calling std::setlocale(), which was creating the bug down the line... So the issue isn't related to the SDK in the end and can be closed. 

Thanks for your help!

Antoine
