### ISSUE TITLE
Vcpkg install aws sdk 1.8

### ISSUE THREAD

**Issue by kenkit** [aws/aws-sdk-cpp#1406]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Cannot set tag specicifacations when creating internet gateway in 1.7 sdk.

**SDK version number**
1.7.333 <-installed by vcpkg
**Platform/OS/Hardware/Device**
Windows 10 VS2019

**To Reproduce (observed behavior)**
Install skd via official

**Comment by KaibaLopez** [comment]
Hi @kenkit ,
A little confused here, the title says that it installs 1.8, but I've checked vcpkg repo and it says 1.7.33...
Is it safe to assume that you are asking us to update the vcpkg version to be 1.8?

**Comment by kenkit** [comment]
yes, sorry for the confusion.

**Comment by KaibaLopez** [comment]
Just as an update, 
I opened a [PR](https://github.com/microsoft/vcpkg/pull/12316) on vcpkg, hopefully it will be resolved pretty soon.

**Comment by KaibaLopez** [comment]
It has been merged and should be available now, thanks.
