### ISSUE TITLE
cmake is unable to locate the binaries, building example dynamodb project

### ISSUE THREAD

**Issue by drempelAT** [aws/aws-sdk-cpp#1407]
Hello everyone,

i want to start developing with the AWS C++ SDK and for the beginning i want to take a look at the dynamoDB example project.

I've already installed the C++ SDK correctly with all components. When i try to build the project with CMake i get the Error: 
_"AWS SDK for C++ headers found, but we were unable to locate the binaries. Have you deleted or moved it? Please make sure header files and binaries are located in INSTALL_ROOT_DIR/INCLUDE_DIR/ and INSTALL_ROOT_DIR/LIB_DIR/[PLATFORM_PREFIX]/ [Debug|Config|OtherConfigs]"_

Header files are located in "C:/Program Files/aws-cpp-sdk-all/include" , also Object File Library -Files are located in "C:/Program Files/aws-cpp-sdk-all/lib". I have tried to add the exact PATHs in the file AWSSDKConfig.cmake 
find_library(AWSSDK_CORE_LIB_FILE aws-cpp-sdk-core) - function because my lib-files are located in the lib/intel64/ directory but that didn't work for me. 
Also i'm wondering why there exists an "intel64" directory, because i dont use any Intel-Hardware. 

I have read many discussion about similiar issues but no solution worked in my case.

I'm working the first time with CMake and because of that i'm not experienced with that, so i'm sorry if i miss simple things.

I appreciate any helpful ideas.

**Comment by KaibaLopez** [comment]
Hi @drempelAT ,
Can you show me the CMakeLists.txt file you're using for you project? 
And also, the platform you're using (windows,mac or linux) and the version of the sdk you installed?

**Comment by drempelAT** [comment]
Hi @KaibaLopez,
i'm using Windows 10 Pro 64bit and the SDK version is 1.8.1 (got this via "git log" command).

This is my [CMakeLists.txt](https://github.com/aws/aws-sdk-cpp/files/4867916/CMakeLists.txt) file.

**Comment by KaibaLopez** [comment]
Hmmm... 
the CMakeLists looks fine, it sounds like it should work and well I've not been able to reproduce this on my side... All I can think at the top of my head is that you may have a discrepancy between either, release-debug mode or shared-static libraries...
Could you walk me through the steps you took to build-install the sdk and build your app?

**Comment by drempelAT** [comment]
For installing the SDK i followed this instruction: https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup.html _"Building the SDK from Source"_. I have reinstalled it today with _CMAKE_BUILD_TYPE=Debug_ to prevent discrepancies between release-debug mode. Last time i installed both, Debug and Release type. 

Its interesting, i didn't changed the installing directory neither this time nor last time and now its located in _"C:/Program Files (x86)/aws-cpp-sdk-all/"_ and not as last time in _"C:/Program Files/aws-cpp-sdk-all/"_ . I don't know if this is important but maybe it helps solving the problem. 

To build the example project i run the command: **_cmake -DAWSSDK_DIR="C:/Program Files (x86)/aws-cpp-sdk-all/lib/cmake/AWSSDK" .._** (my build directory is in the source directory) but it complains about not finding a package configuration file provided by "aws-cpp-sdk-core".

If i use only **_cmake .._** it complains about not finding a package configuration file provided by "AWSSDK" but AWSSDK is located in the default directory.

**Comment by KaibaLopez** [comment]
@drempelAT ,
Sorry, this is probably frustrating and it is a bit of a common thing so It's definitely on us and our documentation. 

But about your error, can't really say what went differently for you  on installations but, regardless which folder it was saved on, the cmake command you want to run on your app is:
```
cmake .. -DCMAKE_PREFIX_PATH="C:/Program Files (x86)/aws-cpp-sdk-all/" -DBUILD_SHARED_LIBS=ON
```
Note: if you don't specify build shared libs then you'll probably get an error about the dependencies (aws-c-common, aws-checksum and aws-c-event-stream), the sdk installs these on the background but they have different defaults, so you have to explicitly tell cmake to look for shared and not static.

Let me know if this doesn't work for you.

**Comment by drempelAT** [comment]
@KaibaLopez 
Yes, that worked! Thanks a lot for your help!
