### ISSUE TITLE
Initialization of the SDK clients takes a long time on PC with empty AWS credentials.

### ISSUE THREAD

**Issue by rhard** [aws/aws-sdk-cpp#1410]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Initialization of the SDK client takes a long time (5s) on PC with empty AWS credentials.

In my environment, I will manually setup the client for using AWS services. No credentials, config files, or environment variables will be used. All credentials will be retrieved from Cognito services during login, etc.

In previous versions of the SDK (~1.7.*) I could normally start the client. In version 1.8.4 it takes about  5 s to execute this simple code:

```cpp
    Aws::SDKOptions options;
    Aws::Utils::Logging::LogLevel logLevel{Aws::Utils::Logging::LogLevel::Warn};
    options.loggingOptions.logLevel = logLevel;
    options.loggingOptions.logger_create_fn = [] { return std::make_shared<Aws::Utils::Logging::ConsoleLogSystem>Aws::Utils::Logging::LogLevel::Warn); };
    Aws::InitAPI(options);

    Aws::Client::ClientConfiguration config;
    AWS_LOGSTREAM_FLUSH();
``` 
This is the log output:
```
[WARN] 2020-07-07 21:38:00.797 ClientConfiguration [10100] Retry Strategy will use the default max attempts.
[WARN] 2020-07-07 21:38:00.801 ClientConfiguration [10100] Retry Strategy will use the default max attempts.
[WARN] 2020-07-07 21:38:00.802 WinHttpSyncHttpClient [10100] Failed setting TCP keep-alive interval with error code: 120
18
[ERROR] 2020-07-07 21:38:00.802 WinHttpSyncHttpClient [10100] Failed to add HTTP request headers with error code: 12150
[WARN] 2020-07-07 21:38:04.803 WinHttpSyncHttpClient [10100] Send request failed: The operation timed out

[ERROR] 2020-07-07 21:38:04.804 EC2MetadataClient [10100] Http request to retrieve credentials failed
[WARN] 2020-07-07 21:38:04.805 EC2MetadataClient [10100] Request failed, now waiting 0 ms before attempting again.
[WARN] 2020-07-07 21:38:04.806 WinHttpSyncHttpClient [10100] Failed setting TCP keep-alive interval with error code: 120
18
[ERROR] 2020-07-07 21:38:04.806 WinHttpSyncHttpClient [10100] Failed to add HTTP request headers with error code: 12150
[WARN] 2020-07-07 21:38:08.803 WinHttpSyncHttpClient [10100] Send request failed: The operation timed out

[ERROR] 2020-07-07 21:38:08.804 EC2MetadataClient [10100] Http request to retrieve credentials failed
[ERROR] 2020-07-07 21:38:08.804 EC2MetadataClient [10100] Can not retrive resource from http://169.254.169.254/latest/me
ta-data/placement/availability-zone
``` 
In the debugger, I see it tries to make a request  to find a region on this line:
![image](https://user-images.githubusercontent.com/8452952/86846877-bbbeb680-c0ab-11ea-8677-e68699dfa732.png)

I know there is an environment variable to disable EC2MetadataClient (`AWS_EC2_METADATA_DISABLED`), but as I said before, I don't have access to the end user PC and can't force him to set needed variable.

Is it possible to setup AWS region without making any requests and disable EC2MetadataClient direct from code?

**SDK version number  - 1.8.4**

**Platform/OS/Hardware/Device**
Win 10, VS2017, x64

**Comment by rhard** [comment]
Update: SDK version 1.7.344 works as expected  immediately returning default `Aws::Client::ClientConfiguration`.

**Comment by KaibaLopez** [comment]
Hi @rhard ,
So, let me first answer the last question: 
> Is it possible to setup AWS region without making any requests and disable EC2MetadataClient direct from code?
Yes, simply set it to the clientConfiguration:
```
Aws::Client::ClientConfiguration config;
config.region = "us-west-1";
```
Then you can also explicitly tell your service client which credentials provider to use, and that way it won't look for any of the other providers:
```
Aws::S3:S3Client(EnvironmentAWSCredentialsProvider,clientConfig); //if you want to read from the enviroment variables for example
```
Or, if you know the credentials, you can also hard code them in and provide that to your client:
```
Aws::Credentials myCreds("YOURaccessKey","YOURsecretKey");
Aws::S3:S3Client(myCreds,clientConfig); 
```

If you don't particularly like hard coding the values, you can also make a custom credentials provider chain based off the default one,though that may more complicated.

And, in case you're interested on why this behaves differently, you can read the changes and reasoning behind them for version 1.8 [here](https://github.com/aws/aws-sdk-cpp/wiki/What%E2%80%99s-New-in-AWS-SDK-for-CPP-Version-1.8).

Let me know if I missed something or misunderstood the question

**Comment by rhard** [comment]
@KaibaLopez Thanks for helping, but
```cpp
Aws::Client::ClientConfiguration config;
config.region = "us-west-1";
```
was the first thing I tried. However it doesn't helped, because if you check ClientConfiguration.h file, it has default constructor:
```cpp
        struct AWS_CORE_API ClientConfiguration
        {
            ClientConfiguration();
```
This constructor tries to retrieve all the data before `config.region = "us-west-1";` actually executes.

**Comment by KaibaLopez** [comment]
ahh, I see what you're saying, sorry I misunderstood your question. We certainly don't have a constructor that only takes the region or that ignores it/hard-code it like we used to.

So this might make for a (old?) feature request, I don't think there is a way to avoid that other than specifically telling clientConfig to get the values from a profile in the `.aws/config ` file.
```Aws::Client::ClientConfiguration config("default");```

It sounds to me like that could work for your case but I want to be sure so, could you show me some sample code? I'm mainly interested on how you're setting up your service client and how cognito is getting your configuration details.

**Comment by rhard** [comment]
The idea of how to use aws-sdk-cpp in my case is very straight forward and has been already working with 1.7.344:
1) For my APP I have a custom API gateway definition which I can export to c2j format and generate custom SDK for it. This is the main reason I select aws-sdk-cpp, as there is not so many C++ REST API generators on the market. 
2) I also want to use the S3 service for my APP.
3) To use both clients from above (custom and S3) I created custom CognitoCredentialProvider which is derived from `Aws::Auth::AWSCredentialsProvider`.  This provider can manage all Cognito requests for user registration, login, etc. It also cares about getting and refreshing needed access keys and tokens. CognitoCredentialProvider has inside `CognitoIdentityClient` and `CognitoIdentityProviderClient` for all operations.
5) I initialize custom and S3 clients with my custom CognitoCredentialProvider.

### Here is the code:
```cpp
Aws::SDKOptions options;
Aws::InitAPI(options);
auto cognitoProvider = Aws::MakeShared<Aws::Auth::NewCognitoCredentialsProvider>(ALLOCATION_TAG, "clientID", "identity-pool-id", "user-pool-id");

auto s3Client = Aws::MakeShared<Aws::S3::S3Client>(ALLOCATION_TAG, cognitoProvider);
// Make operations on S3

auto customClient = Aws::MakeShared<Aws::MyCustomGeneratedClient>(ALLOCATION_TAG, cognitoProvider);
// Make custom API requests
```
Both `CognitoIdentityClient` and `CognitoIdentityProviderClient` inside my custom `NewCognitoCredentialsProvider` are initialized with `AnonymousAWSCredentialsProvider`:

```cpp
NewCognitoCredentialsProvider::NewCognitoCredentialsProvider(const char *appID, const char *identityPoolId, const char *userPoolId) :
        m_cognitoIdentityClient(Aws::MakeShared<CognitoIdentityClient>(MEM_TAG, Aws::MakeShared<AnonymousAWSCredentialsProvider>(MEM_TAG))),
        m_cognitoIdentityProviderClient(Aws::MakeShared<CognitoIdentityProviderClient>(MEM_TAG, Aws::MakeShared<AnonymousAWSCredentialsProvider>(MEM_TAG))), ...
```
In version 1.8.4 it takes 5s to initialize the CognitoIdentityClient and CognitoIdentityProviderClient as it tries to make EC2 metadata request. After it tries to get region data my code is working as before.

The application I develop should not use any AWS default authorization/configuration locations and profiles. In the ideal case, the end-user should even don't know the APP is using AWS services.

Anyway, from my point of view, the `ClientConfiguration` constructor code should have a possibility to bypass all setup possibilities and start with default values immediately.

**Comment by rhard** [comment]
And yes, I tried to explicitly initialize the ClientConfiguration as you suggested above and path it to `NewCognitoCredentialsProvider`, but it doesn't help as mentioned above.

**Comment by wps132230** [comment]
For short term solution, could you try `setenv("AWS_EC2_METADATA_DISABLED", "true", 1);` after `Aws::InitAPI(options);` so as to set the environment variable programmatically?
On windows, it might be `_putenv("AWS_EC2_METADATA_DISABLED=true");`

**Comment by rhard** [comment]
I will try, thanks.

**Comment by rhard** [comment]
The _putenv("AWS_EC2_METADATA_DISABLED=true") solves the issue. I guess I can live with it. Thanks.

**Comment by msheasby** [comment]
I had exactly the same issue 2021 10 06.

using _putenv("AWS_EC2_METADATA_DISABLED=true") removed the 5-second delay during instantiation.
