### ISSUE TITLE
Debug version of AWS SDK Example code (aws-doc-sdk-examples-master\cpp) core dumps

### ISSUE THREAD

**Issue by RichDee** [aws/aws-sdk-cpp#1412]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Running the Debug versions of the cpp examples (e.g., for ec2) dumps core.
Running the Release or the RelWithDebInfo versions works properly.
$ ./describe_instances.exe
Segmentation fault

**SDK version number**

**Platform/OS/Hardware/Device**
Windows 8.1 Professional (x64) (build 9600.19728) on a Dell / OptiPlex 9020
Using Visual Studio 2019

**To Reproduce (observed behavior)**
Build the Debug configuration of the ec2 Example code .exes and run any of them.

**Expected behavior**
I expect the Debug .exes to run just as the Release and the RelWithDebInfo  versions do

**Logs/output**
Debug/describe_instances.exe generates:
     Exception thrown at 0x00007FFB45853D0D (aws-cpp-sdk-core.dll) in describe_instances.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF. occurred

The code location that causes the exception seems to be the "auto factory = " instantiation line listed below -- it is in the InitMonitoring() method in the file aws-sdk-cpp-master\aws-cpp-sdk-core\source\monitoring\MonitoringManager.cpp :
void InitMonitoring(const std::vector<MonitoringFactoryCreateFunction>& monitoringFactoryCreateFunctions)
        {
            if (s_monitors)
            {
                return;
            }
            s_monitors = Aws::MakeUnique<Monitors>(MonitoringTag);
            for (const auto& function: monitoringFactoryCreateFunctions)
            {
                **_auto factory = function();_**

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @RichDee ,
does this happen on every sample or is it specific to the describe instance one?
I'm not able to reproduce the error from my side, my first suspicion is that you've built/installed the SDK on Release and so the sample fails when trying to use it for Debug?

**Comment by RichDee** [comment]
Hi,

So far it happens on every Debug build .exe for ec2 and for s3 -- although I have only run a few of each of those.

ec2 and s3 are the only two example code projects that I built.

And your suspicion is correct: I **_did_** build the SDK on Release configuration -- does that mean I cannot then build the SDK Example code on Debug configuration?

**Comment by KaibaLopez** [comment]
yes you can, you just gotta specify that when you build and install the sdk libraries so, basically go back to building the sdk and when you call cmake add `-DCMAKE_BUILD_TYPE=Debug`, so it'd look something like :
```
cmake <sdk_sourcecode_location> -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -G "Visual Studio 2019"  -DBUILD_ONLY="s3;ec2"
MSBuild ALL_BUILD.vcxprj
```
And then try to run the sample on debug and let me know if that works for you.

**Comment by RichDee** [comment]
I will try that later this weekend and let you know.

**Comment by RichDee** [comment]
Okay, here's what happened:

- I re-ran cmake with the -DCMAKE_BUILD_TYPE=**_Debug_** arguments (instead of -DCMAKE_BUILD_TYPE=Release) from aws-sdk-cpp-master
- I then did a rebuild of the Debug configuration of AWSSDK.sln in VS2019
- Then I built the AWSSDK.sln Install project
- I then re-ran cmake for my ec2 and my s3 example_code folders from aws-doc-sdk-examples-master
- Then I did a rebuild of the Debug configuration of of the ec2 and s3 solution files in VS2019
- Now running the Debug versions of the .exes works without dumping core -- e.g., ec2/describe-instances.exe works, s3/list_buckets.exe works, etc.

Also, the Release versions of these .exes now dump core since the libraries are now build with the Debug configuration.

So the takeaway is as follows -- please correct me if I am wrong:
The AWS SDK "aws-sdk-cpp-master" libraries built/installed to "c:/Program Files (x86)/aws-cpp-sdk-all/bin/" must have the same configuration (i.e., Debug versus Release) as the AWS SDK "aws-doc-sdk-examples-master" example code executables.

**Comment by KaibaLopez** [comment]
Yes, that is correct, by default the builds will get overwritten so you would need to match them up...

If you need to switch back and forth between builds though, you could change the install location so they don't get overwritten, so for example for debug you could do:
```
cmake <source_loc> -DBUILD_ONLY=s3 -DCMAKE_BUILD_TYPe=Debug -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX="c:/program files(x86)/aws-cpp-sdk/debug"
...
cmake <yourapp_loc> -DCMAKE_PREFIX_PATH="c:/program files(x86)/aws-cpp-sdk/debug" 
```

**Comment by RichDee** [comment]
Thank you for your help. That is a good idea to have different install folder for the Debug v Release versions. I will consider doing that going forward.
