### ISSUE TITLE
Build in linux continues to fail

### ISSUE THREAD

**Issue by manning0218** [aws/aws-sdk-cpp#1413]
https://github.com/aws/aws-sdk-cpp/blob/1602b75abbca880b770c12788f6d2bac0c87176a/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp#L679

I am using openssl-1.1.1g and have also tried this with openssl-1.1.1f, when building I am getting the following test failure:
> ~/aws-sdk-cpp/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp:679: Failure
> Value of: *cipherDe
>   Actual: true
> Expected: false

I am not sure what is causing this for openssl-1.1.1f is directly from running sudo apt-get install libssl-dev. For openssl-1.1.1g I am building from source. 
OS: ubuntu and rhel7
Libraries being installed: ssm, servicediscovery, and s3

**Comment by KaibaLopez** [comment]
Hi @manning0218 ,
 I don't think I've ever seen this error and I just tried and couldn't reproduce it.... can you walk me through the steps you followed to build the sdk? Maybe I did something different and just cant think of it now?

**Comment by manning0218** [comment]
The exact steps I took were:

1. git clone https://github.com/aws/aws-sdk-cpp.git
2. cd aws-sdk-cpp; mkdir build; cd build;
3a. cmake -DCPP_STANDARD="17" -DCMAKE_INSTALL_PREFIF:PATH=/opt/aws/1.8.7/debug -DCMAKE_BUILD_TYPE=Debug -DTARGET_ARCH=LINUX ..
3b. cmake -DCPP_STANDARD="17" -DCMAKE_INSTALL_PREFIF:PATH=/opt/aws/1.8.7/debug -DCMAKE_BUILD_TYPE=Debug -DCURL_INCLUDE_DIR=/opt/curl/7.71.1/debug/include -DCURL_LIBRARY=/opt/curl/7.71.1/debug/lib/libcurl.so.4.6.0 -DOPENSSL_ROOT_DIR=/opt/openssl/1.1.1g/debug -DBUILD_ONLY="servicediscovery;ssm;s3"  -DCMAKE_BUILD_TYPE=Debug -DTARGET_ARCH=LINUX ..
4. make && make install

3a is used for installing with ubuntu 20.04 LTS and the curl and openssl libraries installed in the default locations. 3b is used for rhel7 and my own builds of openssl and curl using the latest stable versions of the library. In both cases I am using gcc 9.3.0. The failure occurs after calling make and it is running the unit tests. Everything else is passing so I am not sure what is causing this specific test to fail on the system I am using.

**Comment by isbang** [comment]
I have same error with this Dockerfile
```Dockerfile
FROM alpine

RUN apk add --no-cache build-base cmake git bash curl-dev zlib-dev zip

WORKDIR /usr
RUN git clone https://github.com/aws/aws-sdk-cpp.git && \
    cd aws-sdk-cpp && \
    mkdir build && cd build && \
    cmake .. \
        -DBUILD_ONLY="core;s3" \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_SHARED_LIBS=OFF \
        -DCUSTOM_MEMORY_MANAGEMENT=OFF \
        -DCMAKE_INSTALL_PREFIX=~/install \
        -DENABLE_UNITY_BUILD=ON && \
    make && make install
```

result
```
[ RUN      ] AES_GCM_TEST.AES_GCM_256_KAT_1
/usr/aws-sdk-cpp/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp:679: Failure
Value of: *cipherDe
  Actual: true
Expected: false
```

**Comment by singku** [comment]
It's a problem in Openssl, where it fails to validate AAD for `empty string` during finalize decryption at least in version 1.1.1c. So we made an exception for Openssl in FinalizeDecryption.

Looks like this is fixed for 1.1.1g.

**Comment by manning0218** [comment]
@singku  Thank you! 
I am in the process of updating libraries and then having these placed in Docker for applications to easily be able to update libraries for our pipeline. What would you suggest the best way to work around this in Docker would be?

**Comment by singku** [comment]
I will be doing a customization in SDK to handle this variation.

**Comment by manning0218** [comment]
Great, thank you for getting this taken care of quickly!

**Comment by yisiqiyisiqi** [comment]
Hi @singku @KaibaLopez, I am getting the exact same failed core test using openssl 1.1.1l and 1.1.1u
~/aws-sdk-cpp/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp:679: Failure
Value of: *cipherDe
Actual: true
Expected: false

When I build the sdk with 1.0.2k, all tests pass.

I am only building the s3 and core lib, on rhel7

Can I ask if you have pushed in a fix for this?
