### ISSUE TITLE
aws-cpp-sdk ubuntu18 cmake .. Compile error

### ISSUE THREAD

**Issue by lml0001** [aws/aws-sdk-cpp#1415]
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating linux build config
-- Building project version: 1.7.63
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lumenle/aws-sdk-cpp/build/.deps
[ 33%] Built target AwsChecksums
[ 66%] Built target AwsCCommon
[ 70%] Performing build step for 'AwsCEventStream'
[  9%] Building C object CMakeFiles/aws-c-event-stream.dir/source/event_stream.c.o
/home/lumenle/aws-sdk-cpp/build/.deps/build/src/AwsCEventStream/source/event_stream.c: In function ‘aws_event_stream_library_init’:
/home/lumenle/aws-sdk-cpp/build/.deps/build/src/AwsCEventStream/source/event_stream.c:61:9: error: implicit declaration of function ‘aws_common_library_init’; did you mean ‘aws_event_stream_library_init’? [-Werror=implicit-function-declaration]
         aws_common_library_init(allocator);
         ^~~~~~~~~~~~~~~~~~~~~~~
         aws_event_stream_library_init
/home/lumenle/aws-sdk-cpp/build/.deps/build/src/AwsCEventStream/source/event_stream.c: In function ‘aws_event_stream_library_clean_up’:
/home/lumenle/aws-sdk-cpp/build/.deps/build/src/AwsCEventStream/source/event_stream.c:69:9: error: implicit declaration of function ‘aws_unregister_error_info’; did you mean ‘aws_register_error_info’? [-Werror=implicit-function-declaration]
         aws_unregister_error_info(&s_list);
         ^~~~~~~~~~~~~~~~~~~~~~~~~
         aws_register_error_info
/home/lumenle/aws-sdk-cpp/build/.deps/build/src/AwsCEventStream/source/event_stream.c:70:9: error: implicit declaration of function ‘aws_common_library_clean_up’; did you mean ‘aws_array_list_clean_up’? [-Werror=implicit-function-declaration]
         aws_common_library_clean_up();
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
         aws_array_list_clean_up
/home/lumenle/aws-sdk-cpp/build/.deps/build/src/AwsCEventStream/source/event_stream.c: In function ‘aws_event_stream_message_from_buffer’:
/home/lumenle/aws-sdk-cpp/build/.deps/build/src/AwsCEventStream/source/event_stream.c:314:5: error: implicit declaration of function ‘AWS_ASSERT’; did you mean ‘AWS_OP_ERR’? [-Werror=implicit-function-declaration]
     AWS_ASSERT(buffer);
     ^~~~~~~~~~
     AWS_OP_ERR
cc1: all warnings being treated as errors
CMakeFiles/aws-c-event-stream.dir/build.make:62: recipe for target 'CMakeFiles/aws-c-event-stream.dir/source/event_stream.c.o' failed
make[5]: *** [CMakeFiles/aws-c-event-stream.dir/source/event_stream.c.o] Error 1
CMakeFiles/Makefile2:867: recipe for target 'CMakeFiles/aws-c-event-stream.dir/all' failed
make[4]: *** [CMakeFiles/aws-c-event-stream.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/AwsCEventStream.dir/build.make:111: recipe for target 'build/src/AwsCEventStream-stamp/AwsCEventStream-build' failed
make[2]: *** [build/src/AwsCEventStream-stamp/AwsCEventStream-build] Error 2
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/AwsCEventStream.dir/all' failed
make[1]: *** [CMakeFiles/AwsCEventStream.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at CMakeLists.txt:180 (message):
  Failed to build third-party libraries.

-- Configuring incomplete, errors occurred!

**Comment by KaibaLopez** [comment]
Hi @lml0001 ,
It's hard to say what went wrong from just looking at this error log, can you show me what your cmake command looks like?
