### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by oracleloyall** [aws/aws-sdk-cpp#1416]
In centos ,build project call errors:
/home//aws/aws-sdk/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/client/AWSError.h:60:13: error: unused parameter ‘rhs’ [-Werror=unused-parameter]
             AWSError(const AWSError& rhs) = default;
‘other’ [-Werror=unused-parameter]
         class AWSError
               ^

**Comment by KaibaLopez** [comment]
hi @oracleloyall ,
Can you walk me through how you built the sdk? Did you follow one of our tutorials?
Also, which OS are you using (ubuntu/centos/macOS/windows)? And what version of the sdk are you trying to build?

**Comment by oracleloyall** [comment]
> hi @oracleloyall ,
> Can you walk me through how you built the sdk? Did you follow one of our tutorials?
> Also, which OS are you using (ubuntu/centos/macOS/windows)? And what version of the sdk are you trying to build?

system version :CentOS Linux release 7.5.1804 (Core)
build :
 cmake   -DCMAKE_BUILD_TYPE=Debug
 make 
error:
Scanning dependencies of target aws-cpp-sdk-core
[  1%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/ub_core.cpp.o
In file included from /home/test/zhaoxi/aws-sdk/aws-sdk-cpp-master/aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp:17:0,
                 from /home/test/zhaoxi/aws-sdk/aws-sdk-cpp-master/aws-cpp-sdk-core/ub_core.cpp:14:
/home/test/zhaoxi/aws-sdk/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/client/AWSError.h:60:13: error: unused parameter ‘rhs’ [-Werror=unused-parameter]
             AWSError(const AWSError& rhs) = default;

**Comment by KaibaLopez** [comment]
Hi @oracleloyall ,
Can you verify that the gcc version you're using is 4.9 or greater??
