### ISSUE TITLE
Installation on CentOS 7 errors out on the "make" step at "AWSError(AWSError&& rhs) = default;"

### ISSUE THREAD

**Issue by ilyanyt** [aws/aws-sdk-cpp#1417]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
```
cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)
```

**Describe the question**
Installation dies on the "make" step with the error shown below in the Logs/output section. And I'm following the following set of instructions from README.md:
```
Install CMake and the relevant build tools for your platform. Ensure these are available in your executable path.
 
Create your build directory. Replace <BUILD_DIR> with your build directory name:

Build the project:

For Auto Make build systems:
cd <BUILD_DIR>
cmake <path-to-root-of-this-source-code> -DCMAKE_BUILD_TYPE=Debug
make
sudo make install
```

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```
```
[  5%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/utils/event/EventStreamErrors.cpp.o
In file included from /root/aws-sdk-cpp-master/aws-cpp-sdk-core/source/utils/event/EventStreamErrors.cpp:5:0:
/root/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/client/AWSError.h:59:13: error: unused parameter ‘rhs’ [-Werror=unused-parameter]
             AWSError(AWSError&& rhs) = default;
             ^
/root/aws-sdk-cpp-master/aws-cpp-sdk-core/source/utils/event/EventStreamErrors.cpp: In function ‘Aws::Client::AWSError<Aws::Client::CoreErrors> Aws::Utils::Event::EventStreamErrorsMapper::GetAwsErrorForEventStreamError(Aws::Utils::Event::EventStreamErrors)’:
/root/aws-sdk-cpp-master/aws-cpp-sdk-core/source/utils/event/EventStreamErrors.cpp:61:103: note: synthesized method ‘Aws::Client::AWSError<ERROR_TYPE>::AWSError(Aws::Client::AWSError<ERROR_TYPE>&&) [with ERROR_TYPE = Aws::Client::CoreErrors]’ first required here 
                     return AWSError<CoreErrors>(CoreErrors::UNKNOWN, GetNameForError(error), "", false);
                                                                                                       ^
cc1plus: all warnings being treated as errors
make[2]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/utils/event/EventStreamErrors.cpp.o] Error 1
make[1]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by KaibaLopez** [comment]
Hi @ilyanyt ,
This is a sort of duplicate issue from the latest one but I haven't been able to reproduce it and this one already has more info so, could you help me by telling me the version of the SDK you're trying to install, the gcc version you're using and if you didn't use that exact cmake command, the one you used.

**Comment by ilyanyt** [comment]
Sorry for a duplicate, I didn't see the solution though.

This is from CHANGELOG: `## [1.8.0](https://github.com/aws/aws-sdk-cpp/tree/1.8.0) (2020-06-30)` so I guess it's v1.8.0 and as for GCC:
```gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

And I've used the exact cmake command you guys prescribed: `cmake ../aws-sdk-cpp-master -DCMAKE_BUILD_TYPE=Debug`

**Comment by KaibaLopez** [comment]
@ilyanyt , the sdk has a minimum requirement of gcc 4.9 or higher, could you try upgrading to a newer version of gcc and then try again? 
Also, I'd recommend building only the components you need, otherwise the build can take quite a long time, for example if you're planning to build an application that uses s3 and dynamodb:
```cmake ../aws-cpp-master -DCMAKE_BUILD_TYPE=Debug -DBUILD_ONLY="s3;dynamodb"```

**Comment by ilyanyt** [comment]
Thanks @KaibaLopez , I'll try that.

**Comment by ilyanyt** [comment]
@KaibaLopez , your recommendation worked. I've upgraded gcc:
```
gcc --version
gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
... and limited build to s3 only:
```
cmake ../aws-sdk-cpp-master -DCMAKE_BUILD_TYPE=Debug -DBUILD_ONLY="s3"
```
... and `make` went all the way through with 100% of the tests passed. Closing the case. Thanks!
