### ISSUE TITLE
Can I query number of operations on S3 Bucket using the SDK/API?

### ISSUE THREAD

**Issue by drorgy** [aws/aws-sdk-cpp#1419]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Linux
**Describe the question**

I want to know how many operations (REST requests) I've done on a specific bucket in the last month. Is there a way I can get this information with the SDK/API?
Thanks, 
Dror

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
@drorgy ,
Kind of, s3 buckets have what's called an Access Log which has to be manually enabled, either from the console or the sdk, you can read more about what those are [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/ServerLogs.html). 
Once enabled 

> Amazon S3 periodically collects access log records, consolidates the records in log files, and then uploads log files to your target bucket as log objects.

Not sure if that is exactly what you're looking for though. I also noticed that there is only a sample on how to do it for .NET but if you need that on C++ let me know and I can write a quick similar one for you too.

**Comment by drorgy** [comment]
@KaibaLopez 
Thanks for the information.
You mention that there is a sample of how to do it in .NET (can you please send a link). You wrote that the Access Log is manually enabled (as opposed to programmatically), so what can be done in .NET/C++.
Thanks again,
Dror

**Comment by KaibaLopez** [comment]
Yea, these are the 2 documentation pages on enabling those logs: [manually](https://docs.aws.amazon.com/AmazonS3/latest/dev/enable-logging-programming.html#enabling-logging-general) and [programatically](https://docs.aws.amazon.com/AmazonS3/latest/dev/enable-logging-programming.html).
