### ISSUE TITLE
dynamo client timeout when built with docker

### ISSUE THREAD

**Issue by Lovett1991** [aws/aws-sdk-cpp#1421]
Confirm by changing [ ] to [x] below:
- [ X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
X86/Ubuntu-20.04
X86/Ubuntu-20.04/Docker/Ubuntu-20.04

**Describe the question**
Built a sample app to scan a dynamo table, when building locally on ubuntu with
`mkdir build && cd build && make && make aws-lambda-package-hello` 
followed by
`aws lambda update-function-code --function-name test-build --zip-file fileb://build/hello.zip`
`aws lambda invoke --function-name test-build output.txt`

the lambda runs as expected, however using the docker file in the sample project (which replicates these steps) to build 
`docker run -v {SRC_DIR}:/usr/src/my-src {CONTAINER_HASH}`
everything is fine until actually invoking the lambda whereupon it times out.

Sample project here: https://github.com/Lovett1991/aws-cpp-lambda/tree/aws-cpp-sdk-timeout

In the main branch it does not use the aws-sdk-cpp and is able to run a normal lambda when built in docker.

**Logs/output**
If applicable, add logs or error output.
```
aws lambda invoke --function-name test-build output.txt
{
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "ExecutedVersion": "$LATEST"
}

cat output.txt 
{"errorMessage":"2020-07-22T14:03:44.078Z 23463934-d596-40ea-9770-a7fb425795fa Task timed out after 15.02 seconds"}
```

logging set.
```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by Lovett1991** [comment]
_Bump_

If this needs to go on stackoverflow or the likes I can post there.

**Comment by KaibaLopez** [comment]
Hey @Lovett1991 ,
Sorry for the lack of response here, been trying to reproduce this error on and off, and haven't been able to do so, just wondering if you could give me a bit more specifics on what is it you're trying to do?

**Comment by Lovett1991** [comment]
Hi @KaibaLopez Sorry I've not been working on this for a while and just come back to it.

All I'm trying to do is run a build through jenkins, our jenkins workers runs on docker. I can build locally and upload to aws fine, but when building in docker I have this unusual issue.
