### ISSUE TITLE
AWS S3 C++ SDK failed to connect minio, minio its own other language SDK is OK

### ISSUE THREAD

**Issue by gwnet** [aws/aws-sdk-cpp#1425]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**

```below is my code
#include <iostream>
#include <fstream>
#include <sys/stat.h>
#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>
#include <aws/s3/model/PutObjectRequest.h>
#include <awsdoc/s3/s3_examples.h>
#include <aws/core/auth/AWSCredentialsProvider.h>
//snippet-end:[s3.cpp.put_object.inc]
using namespace Aws::S3;
using namespace Aws::S3::Model;
/* ////////////////////////////////////////////////////////////////////////////
* Purpose: Adds an object to an Amazon S3 bucket.
*
* Prerequisites: An Amazon S3 bucket and the object to be added.
*
* Inputs:
* - bucketName: The name of the bucket.
* - objectName: The name of the object.
* - region: The AWS Region for the bucket.
*
* Outputs: true if the object was added to the bucket; otherwise, false.
* ///////////////////////////////////////////////////////////////////////// */
// snippet-start:[s3.cpp.put_object.code]
bool AwsDoc::S3::PutObject(const Aws::String& bucketName, 
    const Aws::String& objectName,
    const Aws::String& region)
{
    // Verify that the file exists.
    struct stat buffer;
    if (stat(objectName.c_str(), &buffer) == -1)
    {
        std::cout << "Error: PutObject: File '" <<
            objectName << "' does not exist." << std::endl;
        return false;
    }
    Aws::Client::ClientConfiguration config;
    if (!region.empty())
    {
        config.region = region;
    }
    config.endpointOverride = "192.168.1.110:9000";  // S3服务器地址和端口
    config.scheme = Aws::Http::Scheme::HTTP;
    config.verifySSL = false;
    //Aws::Auth::AWSCredentials cred("xxxxxxxxxxxxx", "xxxxxxxx");  // 认证的Key
    //m_client = new S3Client(Aws::Auth::AWSCredentials("test", "xxxxx"), cfg, false, false);
    Aws::S3::S3Client s3_client(Aws::Auth::AWSCredentials("minioadmin", "minioadmin"), config);
    //Aws::S3::S3Client s3_client(config);
    Aws::S3::Model::PutObjectRequest request;
    request.SetBucket(bucketName);
    //request.SetKey(objectName);
    request.SetKey("object1");
    std::shared_ptr<Aws::IOStream> input_data = 
        Aws::MakeShared<Aws::FStream>("SampleAllocationTag", 
            objectName.c_str(), 
            std::ios_base::in | std::ios_base::binary);
    request.SetBody(input_data);
    Aws::S3::Model::PutObjectOutcome outcome = 
        s3_client.PutObject(request);
    if (outcome.IsSuccess()) {
        std::cout << "Added object '" << objectName << "' to bucket '"
            << bucketName << "'.";
        return true;
    }
    else 
    {
        std::cout << "Error: PutObject: " << 
            outcome.GetError().GetMessage() << std::endl;
        return false;
    }
}
int main()
{
    Aws::SDKOptions options;
    Aws::InitAPI(options);
    {
        const Aws::String bucket_name = "test";
        const Aws::String object_name = "C:\\tmp\\1.txt";
        const Aws::String region = "";
        if (!AwsDoc::S3::PutObject(bucket_name, object_name, region)) {
            return 1;
        }
    }
    Aws::ShutdownAPI(options);
    return 0;
}
// snippet-end:[s3.cpp.put_object.code]
```
1:03
then I suffer one network error even it is just local node
1:03
-                             Aws::Client::AWSError<enum Aws::S3::S3Errors>               {m_errorType=NETWORK_CONNECTION (99) m_exceptionName="" m_message="Encountered network error when sending http request" ...}               Aws::Client::AWSError<enum Aws::S3::S3Errors>
                              m_errorType      NETWORK_CONNECTION (99)     Aws::S3::S3Errors
+                            m_exceptionName          ""               std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>
+                            m_message        "Encountered network error when sending http request"               std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>
+                            m_remoteHostIpAddress              ""               std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>
+                            m_requestId       ""               std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>
+                            m_responseHeaders        { size=0 } std::map<std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>,std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>,std::less<std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>>,Aws::Allocator<std::pair<std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>> const ,std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>>>>
                              m_responseCode             REQUEST_NOT_MADE (-1)               Aws::Http::HttpResponseCode
                              m_isRetryable    true        bool
                              m_errorPayloadType       NOT_SET (0)       Aws::Client::ErrorPayloadType
+                            m_xmlPayload   {m_doc=0x0000000000000000 <NULL> }               Aws::Utils::Xml::XmlDocument
+                            m_jsonPayload  {m_value=0x0000000000000000 <NULL> m_wasParseSuccessful=true m_errorMessage="" }           Aws::Utils::Json::JsonValue

**SDK version number**

**Platform/OS/Hardware/Device**
What are you running the sdk on?

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

**Expected behavior**

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @gwnet ,
I can't reproduce the error you're getting from my side.

Network connection can be caused by a number of issues, but your code seems correct, so I think the problem might simply be that you have either bad internet connection or a firewall blocking the ip address and port.
Can you verify that that is not the case? Also, might as well try, use the default values for clientConfiguration, and only change the region.

**Comment by gwnet** [comment]
@KaibaLopez hello buddy, did you try use minio to reproduce the issue. I debug more on root cause. it show me, AWS C++ SDK will use http://bucketname.127.0.0.1:9000. but minio does not have this. 

minio developer follow up with me on this https://github.com/minio/minio/issues/10176


  | Name | Value | Type
-- | -- | -- | --
▶ | std::basic_stringstream<char,std::char_traits,Aws::Allocator >::str returned | "http://test.127.0.0.1:9000" | std::basic_string<char,std::char_traits,Aws::Allocator>



  | Name | Value | Type
-- | -- | -- | --
▶ | std::basic_stringstream<char,std::char_traits,Aws::Allocator >::str returned | "http://test.127.0.0.1:9000" | std::basic_string<char,std::char_traits,Aws::Allocator>

**Comment by gwnet** [comment]
@KaibaLopez minio community suggest useVirtualAddressing, any guidance for me, I am new to S3 SDK. maybe you can share me your example source code. 
my network should be OK, I can use minio .net client to call minio server in local machine well. so just AWS SDK with minio server issue

**Comment by gwnet** [comment]
@KaibaLopez I have found the root cause, it works fine now with my below code, need assign useVirtualaddress=false.

```
 Aws::SDKOptions m_options;
    S3Client* m_client = { NULL };


    Aws::InitAPI(m_options);
    Aws::Client::ClientConfiguration cfg;
    cfg.endpointOverride = "127.0.0.1:9000";  // S3服务器地址和端口
    cfg.scheme = Aws::Http::Scheme::HTTP;
    cfg.verifySSL = false;
    //Aws::Auth::AWSCredentials cred("RPW421T9GSIO4A45Y9ZR", "2owKYy9emSS90Q0pXuyqpX1OxBCyEDYodsiBemcq");  // 认证的Key
    m_client = new S3Client(Aws::Auth::AWSCredentials("minioadmin", "minioadmin"), cfg, 
        Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Never, false);

    PutObjectRequest putObjectRequest;
    putObjectRequest.WithBucket(BucketName.c_str()).WithKey(objectKey.c_str());
    auto input_data = Aws::MakeShared<Aws::FStream>("PutObjectInputStream", pathkey.c_str(), std::ios_base::in | std::ios_base::binary);
    putObjectRequest.SetBody(input_data);
    auto putObjectResult = m_client->PutObject(putObjectRequest);
    if (putObjectResult.IsSuccess())
    {
        std::cout << "Done!" << std::endl;
        return true;
    }
    else
    {
        std::cout << "PutObject error: " <<
            putObjectResult.GetError().GetExceptionName() << " " <<
            putObjectResult.GetError().GetMessage() << std::endl;
        return false;
    }
```

**Comment by KaibaLopez** [comment]
Hi @gwnet ,
Glad to hear you were able to find the answer to your question, sorry about the misunderstanding on what was going on.
