### ISSUE TITLE
How can I build aws-sdk-cpp on Windows 10 using my current tools (CMake, MinGW, gcc, g++)?

### ISSUE THREAD

**Issue by ccssmmww** [aws/aws-sdk-cpp#1426]
I would like to build aws-sdk-cpp on Windows 10.  I am trying to follow the steps in the "For Auto Make build systems" section of aws-sdk-cpp/README.md, to no avail.  Please help with this task.

I have the following tools installed: CMake 3.18.0, gcc  7.3.0, g++ 7.3.0, and MinGW 7.3.0 (the latter three are from Qt Creator 4.11.1).  The path to the folder containing gcc.exe and g++.exe is in in my Path system variable (the path is <path_to_Qt>/Tools/mingw730_64/bin).

I cloned aws-sdk-cpp to C:/Users/<my_user_name>/Downloads/AWS.  I also made the directory C:/Users/<my_user_name>/Downloads/AWS/sdk_build.  From the sdk_build folder, I ran the following command using Git bash 4.4.23 (this command is one of many similar variations that I have tried and failed to successfully use):

```
clear; cmake ../aws-sdk-cpp/ -DCMAKE_BUILD_TYPE=Debug -DBUILD_ONLY="core;s3" -D__USE_MINGW_ANSI_STDIO=1 -DTARGET_ARCH=WINDOWS -G "MinGW Makefiles"
```

Originally, this command failed with several variations of the following error:

```
<path_to_array_list.inl>:109:48: error: unknown conversion type character 'z' in format [-Werror=format=]
```

The __USE_MINGW_ANST_STDIO flag in my cmake command was intended to--but did not--resolve these errors.  I ultimately edited every instance of CMAKE_C_FLAGS:STRING in the sdk_build folder so that CMAKE_C_FLAGS:STRING=-D__USE_MINGW_ANST_STDIO=1, after which the errors disappeared (surely, this is not the suggested manner of preventing such errors, but it appeared to work).  

Rerunning the same cmake command (after editing the CMAKE_C_FLAGS:STRING values) now results in the following error message:

```
<path_to_byte_order.inl>:25:14: fatal error: netinet/in.h: No such file or directory
#include <netinet/in.h>
```

No surprise that Windows can't use netinet/in.h.  Theoretically I could replace every instance of the offending includes and related functions with WIndows anaologues.  However, there appear to already be Windows-specific versions of SDK files that use WinSock2.h instead of netinet/in.h (e.g. there are multiple versions of SimpleUDP.cpp; one version includes netinet/in.h, while the other includes WinSock2.h).  The Windows-specific versions apparently aren't being used.  

How can I build aws-sdk-cpp on Windows 10 using my current tools (CMake, MinGW, gcc, g++)?

**Comment by KaibaLopez** [comment]
Hi @ccssmmww ,
Sadly we don't really support MinGW at the moment... There has been discussions about it and it's just been low on the priority list for now... sorry about that.

**Comment by ihnorton** [comment]
@KaibaLopez @wps132230: we are very interested in mingw-w64 as a supported platform. Several open source language ecosystems (R, Julia, Rust to a lesser degree) rely on mingw-w64 to build the entire package matrix for Windows, and so downstream SDK users/embedders like us (core, S3) have an increasing demand to support this target, to allow simple installation by end-users. I believe several people from the Apache Arrow project would also be interested, cc @nealrichardson.

What can we do to help get #1333 merged (cc @trilader), and possibly add a CI target to avoid regression?
