### ISSUE TITLE
Question About libcurl HTTP Client

### ISSUE THREAD

**Issue by cjhanks** [aws/aws-sdk-cpp#143]
Hi,

I am on a Linux machine using the Curl client.  I am using the HTTP client for non-AWS requests; unfortunately many HTTP servers are not as compliant as AWS.  In one case the server I am contacting does not provide either a Content-Length or a Transfer-Encoding header, this causes the CURL client to exit with error code 18 (CURLE_PARTIAL_FILE).  Consequently the response from the `Client->MakeRequest(...)` is a nulled shared_ptr (it appears any non 0 exit-code is returned null).

Is there any mechanism/hook whereby I might request the client to not abort the response on any or all exit codes from libcurl?

**Comment by JonathanHenson** [comment]
Which http server are you using?

**Comment by cjhanks** [comment]
It's unclear to me, I don't have access to it.  NMAP reports to me:
```
Running (JUST GUESSING): F5 Networks embedded (89%), OpenBSD 4.X|5.X (88%), Apple embedded (87%), FreeBSD 6.X|7.X|8.X (86%), PC-BSD 1.X (85%)
OS CPE: cpe:/o:openbsd:openbsd:4.4 cpe:/o:openbsd:openbsd:5 cpe:/h:apple:airport_extreme cpe:/o:freebsd:freebsd:6 cpe:/o:freebsd:freebsd:7 cpe:/o:freebsd:freebsd:8.1 cpe:/o:pc-bsd:pc_bsd:1
Aggressive OS guesses: F5 BIG-IP 3650 Local Traffic Manager load balancer (89%), OpenBSD 4.4 - 4.5 (88%), OpenBSD 4.6 (88%), OpenBSD 5.0 (88%), OpenBSD 4.0 (87%), Apple AirPort Extreme WAP (87%), OpenBSD 4.2 - 4.4 (87%), F5 BIG-IP load balancer (86%), FreeBSD 6.2-RELEASE-p2 (pf with scrub enabled) (86%), FreeBSD 7.1-PRERELEASE - 7.3-RELEASE (86%)
```

Judging by that, I would have to guess it's an F5 load balancer based on BSD.  From what I am told, it's stripping out response headers programatically.  I am unsure how common that is.

**Comment by JonathanHenson** [comment]
@cjhanks Sorry for your problem and my delayed response.

An http server not sending a content-length header back with a body is not an http server. It is much easier for us to write against http spec compliant servers than attempt to take on the complexity of handling miscreant http server vendors.

**Comment by cjhanks** [comment]
Understood and completely agree.  Unfortunately the endpoint disagrees.  Closing.
