### ISSUE TITLE
Headers not found

### ISSUE THREAD

**Issue by ccssmmww** [aws/aws-sdk-cpp#1431]
.

**Comment by KaibaLopez** [comment]
Hi @ccssmmww ,
How are you building the SDK? What was the cmake command you used and what version of the SDK are you trying to use?

**Comment by ccssmmww** [comment]
@KaibaLopez 

*How are you building the SDK?*
I've followed the steps from the section "For Visual Studio" of "To create an out-of-source build" from the README.md, but the msbuild command fails.

*What was the cmake command you used?*
cmake <path_to_sdk_repo> -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Debug -DBUILD_ONLY="core;s3"
(I'm using cmake 3.18.1)

*What version of the SDK are you trying to use?*
git rev-parse HEAD returns f362eaa4a249dd5724ef014b6a237f3f8d45cba2.  It's a recent pull from the master branch.

**Comment by KaibaLopez** [comment]
hmmm, that is odd.
It looks like you're having problems with the aws dependencies, 
Could you try adding `DBUILD_SHARED_LIBS=ON` to your cmake command and let me know if that fixes it? 
If that does not work, I'd recommend building the dependencies manually, you can see how to [here](https://github.com/aws/aws-sdk-cpp#third-party-dependencies).
And If neither of those work, I'll need to see the full cmake and msbuild output(make sure to clean up any private info).
