### ISSUE TITLE
Issue with transcribe in C++ 

### ISSUE THREAD

**Issue by ktonchev** [aws/aws-sdk-cpp#1432]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
We are trying to use the transcribe service in C++ following the example provided:

https://aws.amazon.com/blogs/developer/real-time-streaming-transcription-with-the-aws-c-sdk/

However, there seems to be compilation error. In the file audio-capture.cpp (part of the example), in function AudioCaptureCallback, the first line is the expression:

auto stream = static_cast<Aws::TranscribeStreamingService::Model::AudioStream>(userData);

However, this is reported as error by the compiler and we have to change the line to (i.e. cast to pointer):

auto stream = static_cast<Aws::TranscribeStreamingService::Model::AudioStream *>(userData);

This fixes the compilation error, but now we are unable to get any transcription in Linux, i.e. the program is working fine, but no transcriptions are returned by the cloud. 

**SDK version number**
SDK version is 1.7.9

Thanks

**Comment by KaibaLopez** [comment]
Hi @ktonchev ,
You're right on the pointer cast, thanks for pointing that out.

As for the lack of transcriptions, that's going to be harder to figure out since the code was only meant to be a sample, and there could be multiple silent failure causes, like bad connection to microphone detection.
I will say though that I am able to make it work on my side on linux, mac and windows. So I'd look into your environment configuration.

**Comment by ktonchev** [comment]
Hi KaibaLopez, 

sorry for the late response, but due to other issues and the holiday season I was unable to reply earliler. If I understand you correctly, you are able to run this example on linux, right ?  If so, I will appreciate if you can give us general guidance on how you did it, only for linux. We will need info about: linux distro, library dependencies, amazon SDK version and compilation flags. We will try to replicate your environment and hopefully your results. 

Thansk, 
Krasimir

**Comment by KaibaLopez** [comment]
Hi @ktonchev ,
sorry for the lack of response here.
Could you verify that you are still seeing this issue?
There was an update regarding eventstream on version: 1.8.179. Which might have fixed it for you.
