### ISSUE TITLE
Add Support for AWS SSO generated credentials

### ISSUE THREAD

**Issue by sidewinder12s** [aws/aws-sdk-cpp#1433]
AWS SSO generated credentials introduce some new semantics around where it stores credentials (first creates an accessToken, which then is used to request IAM Credentials that are stored in a new location `$HOME/.aws/cli/cache`). 

Support for these creds seems to be per SDK, figured I'd get a request in here for them. We're stuck with needing C++, Boto & Go so this has been fairly painful. 

https://github.com/aws/aws-sdk-go/issues/3186
https://github.com/boto/boto3/issues/2091

**Comment by sidewinder12s** [comment]
Any status update on this? 

Looks like Go (and Python) have landed support: https://github.com/aws/aws-sdk-go/pull/3755

**Comment by jmklix** [comment]
This has already been released in version 1.9.0
