### ISSUE TITLE
Test Cases fails during make following SDK componencts :- s3;s3-encryption;sts;transfer

### ISSUE THREAD

**Issue by shiv50084** [aws/aws-sdk-cpp#1434]
[----------] Global test environment tear-down
[==========] 374 tests from 67 test cases ran. (5005 ms total)
[  PASSED  ] 372 tests.
**[  FAILED  ] 2 tests, listed below:
[  FAILED  ] VersionTest.TestMajorMinorPatch
[  FAILED  ] AES_GCM_TEST.AES_GCM_256_KAT_1

 2 FAILED TESTS**
aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/build.make:795: recipe for target 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests' failed
make[2]: *** [aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 1
make[2]: *** Deleting file 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests'
CMakeFiles/Makefile2:744: recipe for target 'aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all' failed
make[1]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

  
**Describe the bug**
compilation bug after cmake when i am running make and after that itself run some test cases .They are failing.

**SDK version number**
Using latest commit ID : -6fa9af26f0d6d453dc5a1aa3ba539cc70952e61c

**Platform/OS/Hardware/Device**
What are you running the sdk on?  i am compiling on Linux 64 bit paltform

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

**Expected behavior**

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

**Comment by shiv50084** [comment]
This is my compilation cmake options

cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_ONLY="s3;s3-encryption;sts;transfer" -DCMAKE_BUILD_TYPE=Release -DMINIMIZE_SIZE=ON -DENABLE_UNITY_BUILD=ON -DAUTORUN_UNIT_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON

**Comment by KaibaLopez** [comment]
Hi @shiv50084,
some of the tests we run involve creating directories and creating files so they require administrator permissions, try adding `sudo` to the make call. 
I should also mention just in case, in a recent version of the sdk we had an error that would cause failures on linux builds, it should be fixed now so just in case I'd recommend getting the latest version of the SDK.

Let me know if these didn't help.

**Comment by shiv50084** [comment]
@KaibaLopez 
With "sudo make" also test case failing .

**Comment by KaibaLopez** [comment]
Hi @shiv50084 ,
I'm still not able to reproduce this error. Just tried on a new linux machine and had no problems with it... Only reason I know of why `VersionTest.TestMajorMinorPatch` might fail is manual changes to `VersionConfig.h`.
Are there any steps you can think of on how to reproduce?
