### ISSUE TITLE
  Compile error

### ISSUE THREAD

**Issue by lml0001** [aws/aws-sdk-cpp#1435]
lumenle@lumenle-PICO-KBU4:~/aws-sdk-cpp/build$ cmake .. -DBUILD_ONLY="s3;core"
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating linux build config
fatal: 没有发现名称，无法描述任何东西。
-- Building project version: 1.7.63
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lumenle/aws-sdk-cpp/build/.deps
Scanning dependencies of target AwsCCommon
[  4%] Creating directories for 'AwsCCommon'
[  8%] Performing download step (git clone) for 'AwsCCommon'
正克隆到 'AwsCCommon'...
Note: checking out 'f5383755e934745811d777a8e6c6866791b4302e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD 目前位于 f538375... Disable backtrace log on Android. (#232)
[ 12%] No patch step for 'AwsCCommon'
[ 16%] No update step for 'AwsCCommon'
[ 20%] Performing configure step for 'AwsCCommon'
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Success
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Success
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Success
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Success
-- Performing Test HAVE_MAY_I_USE
-- Performing Test HAVE_MAY_I_USE - Failed
-- Performing Test HAVE_BUILTIN_CPU_SUPPORTS
-- Performing Test HAVE_BUILTIN_CPU_SUPPORTS - Success
-- Performing Test HAVE_MSVC_CPUIDEX
-- Performing Test HAVE_MSVC_CPUIDEX - Failed
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Building SIMD base64 decoder
-- Packaging currently only supported on Fedora.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lumenle/aws-sdk-cpp/build/.deps/build/src/AwsCCommon-build
[ 25%] Performing build step for 'AwsCCommon'
Scanning dependencies of target aws-c-common
[  1%] Building C object CMakeFiles/aws-c-common.dir/source/array_list.c.o
[  3%] Building C object CMakeFiles/aws-c-common.dir/source/byte_buf.c.o
[  5%] Building C object CMakeFiles/aws-c-common.dir/source/codegen.c.o
[  7%] Building C object CMakeFiles/aws-c-common.dir/source/common.c.o
[  8%] Building C object CMakeFiles/aws-c-common.dir/source/condition_variable.c.o
[ 10%] Building C object CMakeFiles/aws-c-common.dir/source/date_time.c.o
[ 12%] Building C object CMakeFiles/aws-c-common.dir/source/device_random.c.o
[ 14%] Building C object CMakeFiles/aws-c-common.dir/source/encoding.c.o
[ 16%] Building C object CMakeFiles/aws-c-common.dir/source/error.c.o
[ 17%] Building C object CMakeFiles/aws-c-common.dir/source/hash_table.c.o
[ 19%] Building C object CMakeFiles/aws-c-common.dir/source/lru_cache.c.o
[ 21%] Building C object CMakeFiles/aws-c-common.dir/source/priority_queue.c.o
[ 23%] Building C object CMakeFiles/aws-c-common.dir/source/string.c.o
[ 25%] Building C object CMakeFiles/aws-c-common.dir/source/task_scheduler.c.o
[ 26%] Building C object CMakeFiles/aws-c-common.dir/source/uuid.c.o
[ 28%] Building C object CMakeFiles/aws-c-common.dir/source/posix/clock.c.o
[ 30%] Building C object CMakeFiles/aws-c-common.dir/source/posix/condition_variable.c.o
[ 32%] Building C object CMakeFiles/aws-c-common.dir/source/posix/device_random.c.o
[ 33%] Building C object CMakeFiles/aws-c-common.dir/source/posix/mutex.c.o
[ 35%] Building C object CMakeFiles/aws-c-common.dir/source/posix/rw_lock.c.o
[ 37%] Building C object CMakeFiles/aws-c-common.dir/source/posix/system_info.c.o
[ 39%] Building C object CMakeFiles/aws-c-common.dir/source/posix/thread.c.o
[ 41%] Building C object CMakeFiles/aws-c-common.dir/source/posix/time.c.o
[ 42%] Building C object CMakeFiles/aws-c-common.dir/source/arch/cpuid.c.o
[ 44%] Building C object CMakeFiles/aws-c-common.dir/source/arch/encoding_avx2.c.o
[ 46%] Linking C shared library libaws-c-common.so
[ 46%] Built target aws-c-common
Scanning dependencies of target aws-c-common-assert-tests
[ 48%] Building C object tests/CMakeFiles/aws-c-common-assert-tests.dir/assert_test.c.o
[ 50%] Linking C executable /home/lumenle/aws-sdk-cpp/build/bin/aws-c-common-assert-tests
[ 50%] Built target aws-c-common-assert-tests
Scanning dependencies of target aws-c-common-tests
[ 51%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/test_runner.c.o
[ 53%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/array_list_test.c.o
[ 55%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/atomics_test.c.o
[ 57%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/byte_buf_test.c.o
[ 58%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/byte_order_test.c.o
[ 60%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/clock_test.c.o
[ 62%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/condition_variable_test.c.o
[ 64%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/cursor_test.c.o
[ 66%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/date_time_test.c.o
[ 67%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/device_random_test.c.o
[ 69%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/encoding_test.c.o
[ 71%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/error_test.c.o
[ 73%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/hash_table_test.c.o
[ 75%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/linked_list_test.c.o
[ 76%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/lru_cache_test.c.o
[ 78%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/math_test.c.o
[ 80%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/mutex_test.c.o
[ 82%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/priority_queue_test.c.o
[ 83%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/realloc_test.c.o
[ 85%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/rw_lock_test.c.o
[ 87%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/secure_zero_test.c.o
[ 89%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/split_test.c.o
[ 91%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/string_test.c.o
[ 92%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/system_info_tests.c.o
[ 94%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/task_scheduler_test.c.o
[ 96%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/thread_test.c.o
[ 98%] Building C object tests/CMakeFiles/aws-c-common-tests.dir/uuid_test.c.o
[100%] Linking C executable /home/lumenle/aws-sdk-cpp/build/bin/aws-c-common-tests
[100%] Built target aws-c-common-tests
[ 29%] Performing install step for 'AwsCCommon'
[ 46%] Built target aws-c-common
[ 50%] Built target aws-c-common-assert-tests
[100%] Built target aws-c-common-tests
Install the project...
-- Install configuration: "Release"
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/array_list.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/atomics.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/byte_buf.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/byte_order.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/clock.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/common.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/condition_variable.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/date_time.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/device_random.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/encoding.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/error.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/exports.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/hash_table.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/linked_list.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/lru_cache.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/math.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/mutex.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/priority_queue.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/rw_lock.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/string.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/system_info.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/task_scheduler.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/thread.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/time.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/uuid.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/array_list.inl
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/atomics_fallback.inl
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/atomics_gnu.inl
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/atomics_gnu_old.inl
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/atomics_msvc.inl
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/math.fallback.inl
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/math.gcc_overflow.inl
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/math.gcc_x64_asm.inl
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/math.msvc.inl
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/config.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/common/posix/common.inl
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/testing/aws_test_harness.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/lib/libaws-c-common.so.1.0.0
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/lib/libaws-c-common.so.0unstable
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/lib/libaws-c-common.so
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/lib/aws-c-common/cmake/aws-c-common-targets.cmake
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/lib/aws-c-common/cmake/aws-c-common-targets-release.cmake
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/lib/aws-c-common/cmake/aws-c-common-config.cmake
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/lib/cmake/AwsCFlags.cmake
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/lib/cmake/AwsSharedLibSetup.cmake
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/lib/cmake/AwsTestHarness.cmake
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/lib/cmake/AwsLibFuzzer.cmake
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/lib/cmake/AwsSanitizers.cmake
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/lib/cmake/AwsSIMD.cmake
[ 33%] Completed 'AwsCCommon'
[ 33%] Built target AwsCCommon
Scanning dependencies of target AwsChecksums
[ 37%] Creating directories for 'AwsChecksums'
[ 41%] Performing download step (git clone) for 'AwsChecksums'
正克隆到 'AwsChecksums'...
Note: checking out 'v0.1.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD 目前位于 78be31b... Install DLLs to the bin directory on windows (#15)
[ 45%] No patch step for 'AwsChecksums'
[ 50%] No update step for 'AwsChecksums'
[ 54%] Performing configure step for 'AwsChecksums'
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lumenle/aws-sdk-cpp/build/.deps/build/src/AwsChecksums-build
[ 58%] Performing build step for 'AwsChecksums'
Scanning dependencies of target aws-checksums
[  9%] Building C object CMakeFiles/aws-checksums.dir/source/cpuid_generic.c.o
[ 18%] Building C object CMakeFiles/aws-checksums.dir/source/crc.c.o
[ 27%] Building C object CMakeFiles/aws-checksums.dir/source/crc_jni.c.o
[ 36%] Building C object CMakeFiles/aws-checksums.dir/source/crc_sw.c.o
[ 45%] Building C object CMakeFiles/aws-checksums.dir/source/intel/cpuid.c.o
[ 54%] Building C object CMakeFiles/aws-checksums.dir/source/intel/crc32c_sse42_asm.c.o
[ 63%] Building C object CMakeFiles/aws-checksums.dir/source/arm/cpuid_arm.c.o
[ 72%] Linking C shared library libaws-checksums.so
[ 72%] Built target aws-checksums
Scanning dependencies of target aws-checksums-tests
[ 81%] Building C object CMakeFiles/aws-checksums-tests.dir/tests/crc_test.c.o
[ 90%] Building C object CMakeFiles/aws-checksums-tests.dir/tests/run_tests.c.o
[100%] Linking C executable /home/lumenle/aws-sdk-cpp/build/bin/aws-checksums-tests
[100%] Built target aws-checksums-tests
[ 62%] Performing install step for 'AwsChecksums'
[ 72%] Built target aws-checksums
[100%] Built target aws-checksums-tests
Install the project...
-- Install configuration: "Release"
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/checksums/crc.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/checksums/crc_jni.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/include/aws/checksums/exports.h
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/lib/libaws-checksums.so
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/lib/aws-checksums/cmake/aws-checksums-targets.cmake
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/lib/aws-checksums/cmake/aws-checksums-targets-release.cmake
-- Installing: /home/lumenle/aws-sdk-cpp/build/.deps/install/lib/aws-checksums/cmake/aws-checksums-config.cmake
[ 66%] Completed 'AwsChecksums'
[ 66%] Built target AwsChecksums
Scanning dependencies of target AwsCEventStream
[ 70%] Creating directories for 'AwsCEventStream'
[ 75%] Performing download step (git clone) for 'AwsCEventStream'
正克隆到 'AwsCEventStream'...
已经位于 'master'
您的分支与上游分支 'origin/master' 一致。
[ 79%] No patch step for 'AwsCEventStream'
[ 83%] No update step for 'AwsCEventStream'
[ 87%] Performing configure step for 'AwsCEventStream'
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:30 (include):
  include could not find load file:

    AwsFindPackage

-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
CMake Error at CMakeLists.txt:77 (aws_use_package):
  Unknown CMake command "aws_use_package".

-- Configuring incomplete, errors occurred!
See also "/home/lumenle/aws-sdk-cpp/build/.deps/build/src/AwsCEventStream-build/CMakeFiles/CMakeOutput.log".
See also "/home/lumenle/aws-sdk-cpp/build/.deps/build/src/AwsCEventStream-build/CMakeFiles/CMakeError.log".
CMakeFiles/AwsCEventStream.dir/build.make:106: recipe for target 'build/src/AwsCEventStream-stamp/AwsCEventStream-configure' failed
make[2]: *** [build/src/AwsCEventStream-stamp/AwsCEventStream-configure] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/AwsCEventStream.dir/all' failed
make[1]: *** [CMakeFiles/AwsCEventStream.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at CMakeLists.txt:180 (message):
  Failed to build third-party libraries.

-- Configuring incomplete, errors occurred!

**Comment by KaibaLopez** [comment]
Hi @lml0001 ,
can you try running the cmake command like this:
`cmake .. -DBUILD_ONLY="s3" -DBUILD_SHARED_LIBS=ON`

**Comment by lml0001** [comment]
> Hi @lml0001 ,
> can you try running the cmake command like this:
> `sudo cmake .. -DBUILD_ONLY="s3" -DBUILD_SHARED_LIBS=ON`

i try this way,  but the same error occurred

**Comment by KaibaLopez** [comment]
I haven't been able to reproduce this error...
I can't really think on what could be causing it and I'd be shooting in the dark here to know what was going on... I think the best thing I can suggest is for you to try with the latest version of the sdk. 
Another thing you could try is installing the dependencies separately following this [instructions](https://github.com/aws/aws-sdk-cpp#third-party-dependencies). That might give us some more info on where the error is coming from at least.

**Comment by lml0001** [comment]
> I haven't been able to reproduce this error...
> I can't really think on what could be causing it and I'd be shooting in the dark here to know what was going on... I think the best thing I can suggest is for you to try with the latest version of the sdk.
> Another thing you could try is installing the dependencies separately following this [instructions](https://github.com/aws/aws-sdk-cpp#third-party-dependencies). That might give us some more info on where the error is coming from at least.

maybe I because use the 1.7.319 version of the aws-sdk-cpp，

**Comment by KaibaLopez** [comment]
mmm maybe, have you tried newer versions? 
Also, make sure that you meet the minimum requirements for the sdk.

**Comment by lml0001** [comment]
> mmm maybe, have you tried newer versions?
> Also, make sure that you meet the minimum requirements for the sdk.

but i have to use this version ,because my team  are using this version

**Comment by KaibaLopez** [comment]
@lml0001 ,
Sorry but can you walk me through exactly how you tried to build the sdk?
Also, what cmake version are you using?  And if you follow these [instructions](https://github.com/aws/aws-sdk-cpp#third-party-dependencies) what error do you get when building the dependencies? Is it the same? which one fails?
