### ISSUE TITLE
[Guidance] : I need a help for S3 data encryption using AES-CBC encryption

### ISSUE THREAD

**Issue by shiv50084** [aws/aws-sdk-cpp#1438]
**Describe the question**

I need a help (one sample code because i didn't found in SDK samples ) to encrypt my data by using AES-CBC encryption and i want to use my keys for data encryption.

I found one example on URL :
https://aws.amazon.com/blogs/developer/amazon-s3-encryption-client-is-now-available-for-c/

but its using KMS method where user can give its keys.

**Platform/OS/Hardware/Device**
embedded linux

**Comment by KaibaLopez** [comment]
Hi @shiv50084 ,
So I'm not sure what the problem is with using KMS and also only one of the 2 samples there uses it, so not sure what is wrong with the other sample....
I wouldn't want to write code and have that not help you either... So instead I'll say:

if you need more samples you can always take a look at the our [tests here](https://github.com/aws/aws-sdk-cpp/tree/master/aws-cpp-sdk-s3-encryption-tests) for inspiration on how to use the service.

Hope that helps and if not please describe a bit more on what kind of sample you'd want? What is missing from the one you linked?

**Comment by shiv50084** [comment]
@KaibaLopez 

This is my sample code:-

/**

bool KMSWithEncryptionMaterials(const char* bucket, const char* objectKey,const char *File_name,HeaderValueCollection metadata)
{
    ClientConfiguration clientConfig;
    // Put an encrypted object to S3
    PutObjectRequest putObjectRequest;
    String contentType;
    String Objkey;

    String Region((char *)gstArnPermission.acRegion);
    clientConfig.region = Region;
    clientConfig.scheme = Scheme::HTTP;
    clientConfig.verifySSL = 0;
    clientConfig.httpRequestTimeoutMs = 30000;
    clientConfig.connectTimeoutMs = 30000;
    clientConfig.requestTimeoutMs = 30000;

#if 0  // To Get keys from AWS S3 CPP SDK
    Aws::KMS::KMSClient kmsClient(clientConfig);
    Aws::KMS::Model::CreateKeyRequest createKeyRequest;
    auto createKeyOutcome = kmsClient.CreateKey(createKeyRequest);
    if (!createKeyOutcome.IsSuccess())
    {
        std::cout << "Failed to create KMS master key.\n" << createKeyOutcome.GetError() << std::endl;
        return false;
    }
    const Aws::String& masterKeyId = createKeyOutcome.GetResult().GetKeyMetadata().GetKeyId();
#else  // User given Keys
    const Aws::String& masterKeyId= "2659407263E4A797";
#endif /* 0 */
    
    const auto kmsEncryption = MakeShared<Aws::S3Encryption::Materials::KMSWithContextEncryptionMaterials>("s3Encryption",masterKeyId,clientConfig);
    Aws::S3Encryption::CryptoConfigurationV2 cryptoConfig(kmsEncryption);

    Auth::AWSCredentials credentials(ACCESS_KEY_ID, ACCESS_KEY_ID); // user Account Credentials

    S3EncryptionClientV2 s3EncryptionClient(cryptoConfig,credentials,clientConfig);

    putObjectRequest.SetMetadata(metadata);
    putObjectRequest.SetBucket(bucket);
    putObjectRequest.SetKey(Objkey);
    const std::shared_ptr<IOStream> input_data =  MakeShared<FStream>("SampleAllocationTag", 
                                                       File_name, 
                                                       std::ios_base::in | std::ios_base::binary);
    putObjectRequest.SetBody(input_data);
    putObjectRequest.SetContentType("image/jpeg");

    auto putObjectOutcome = s3EncryptionClient.PutObject(putObjectRequest,{});

    if (putObjectOutcome.IsSuccess()) {
        std::cout << "Put object with KMSWithContextEncryptionMaterials succeeded" << std::endl;
    } else {
        std::cout << "Error while putting object with KMSWithContextEncryptionMaterials \n"
                  << putObjectOutcome.GetError() << std::endl;
        return false;
    }
    return true;
}


When i am running this code on my embedded device.I am getting an error :- 
#### This error coming while i am giving user assigned encryption master key.

>> Error while putting object with KMSWithContextEncryptionMaterials
>> HTTP response code: -1
>> Resolved remote host IP address:
>> Request ID:
>> Exception name: GenerateContentEncryptionKeyFailed
>> Error message: Failed to generate content encryption key(CEK)
>> 0 response headers:


##### when i running same code with master key generated by AWS SDK C++
I am getting below error.

Failed to create KMS master key.
HTTP response code: -1
Resolved remote host IP address:
Request ID:
Exception name:
Error message: curlCode: 7, Couldn't connect to server
0 response headers:


############################# 



and full trace log during this testing you can find in attachment (mainly this log related to user input master key )
[aws_sdk_2020-08-20-14.log](https://github.com/aws/aws-sdk-cpp/files/5103746/aws_sdk_2020-08-20-14.log)


Can you please help why this error coming.

**Comment by KaibaLopez** [comment]
Hey @shiv50084 ,
I've tweaked a bit with the sample code you provided and it worked out fine.
The first error tells me that the key you tried to use is not valid and the second error means "Failed to connect to Permission denied” which happens when for any reason curl request is blocked by some firewall or similar thing.
Not sure what your V2 classes changed so I can't say for sure I know the root cause was but I reverted them to the ones the sdk provides, here's what works for me:
```
#include <stdio.h>
#include <aws/core/Aws.h>

#include <aws/core/client/ClientConfiguration.h>
#include <aws/kms/KMSClient.h>
#include <aws/kms/model/GenerateDataKeyRequest.h>
#include <aws/kms/model/GenerateDataKeyResult.h>

#include <aws/s3/S3Client.h>
#include <aws/s3/model/PutObjectRequest.h>
#include <aws/s3/model/PutObjectResult.h>
#include <aws/s3-encryption/S3EncryptionClient.h>
#include <aws/s3-encryption/materials/SimpleEncryptionMaterials.h>
#include <aws/s3-encryption/materials/KMSEncryptionMaterials.h>

using namespace Aws::Client;
using namespace Aws::S3Encryption::Materials;
using namespace Aws::S3Encryption;
using namespace Aws::KMS;
using namespace Aws::KMS::Model;

bool KMSWithEncryptionMaterials(const char* bucket, const char* objectKey)
{
ClientConfiguration clientConfig("default");
// Put an encrypted object to S3
Aws::S3::Model::PutObjectRequest putObjectRequest;
Aws::String contentType;

#if 1 // To Get keys from AWS S3 CPP SDK
auto kms_client = Aws::MakeShared<KMSClient>("Test KMS client", clientConfig);
GenerateDataKeyRequest request;
Aws::Map<Aws::String, Aws::String> enc_context;
request.SetKeyId("KMSkeyId");
request.SetNumberOfBytes(64);
request.SetEncryptionContext(enc_context);

auto generate_datakey_outcome = kms_client->GenerateDataKey(request);

//auto createKeyOutcome = kms_client->CreateKey(req);
if (!generate_datakey_outcome.IsSuccess())
{
std::cout << "Failed to create KMS master key.\n" << generate_datakey_outcome.GetError().GetMessage() << std::endl;
return false;
}
const Aws::String& masterKeyId = generate_datakey_outcome.GetResult().GetKeyId();
#else // User given Keys
const Aws::String& masterKeyId= "ValidKey";
#endif /* 0 */

auto kmsMaterials = Aws::MakeShared<KMSWithContextEncryptionMaterials>("s3Encryption", masterKeyId);
auto cryptoConfig = CryptoConfiguration(StorageMethod::METADATA, CryptoMode::ENCRYPTION_ONLY);

auto s3encClient = Aws::MakeShared<S3EncryptionClient>("Encryption Client",kmsMaterials,cryptoConfig,clientConfig);

putObjectRequest.SetBucket(bucket);
putObjectRequest.SetKey(objectKey);
const std::shared_ptr<Aws::IOStream> input_data =  Aws::MakeShared<Aws::StringStream>("s3KMSEncriptionTest");
putObjectRequest.SetBody(input_data);
putObjectRequest.SetContentType("image/jpeg");

auto putObjectOutcome = s3encClient->PutObject(putObjectRequest);

if (putObjectOutcome.IsSuccess()) {
    std::cout << "Put object with KMSWithContextEncryptionMaterials succeeded" << std::endl;
} else {
    std::cout << "Error while putting object with KMSWithContextEncryptionMaterials \n"
              << putObjectOutcome.GetError().GetMessage() << std::endl;
    return false;
}
return true;

}

int main(){
    Aws::SDKOptions options;
    Aws::InitAPI(options);
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Info;
    if(KMSWithEncryptionMaterials("myBucketName", "myKeyName"))
        std::cout<<"worked"<<std::endl;
    else
    {
        std::cout<<"did not work" << std::endl;
    }
    Aws::ShutdownAPI(options);
}
```
Hope this helps and let me know if you need something else or if I missed something.
