### ISSUE TITLE
Client constructors throw std::out_of_range if region string is less than 5 characters

### ISSUE THREAD

**Issue by Gram-C** [aws/aws-sdk-cpp#1439]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
This is a minor bug in that it only occurs if an invalid region is specified. However the handling of this case is unfriendly as it results in a std::out_of_range exception. Also, users who are migrating from library version 1.7 may well have their region set to an empty string rather than "aws-global".

The problem is in Aws::Region::ComputeSignerRegion in aws-cpp-sdk-core\source\Region.cpp. Line 26 is:

`else if (region.compare(region.size() - 5, 5, "-fips") == 0)`

which will throw a std::out_of_range exception if the region variable is less than 5 characters.

**SDK version number**
1.8.4

**Platform/OS/Hardware/Device**
Not relevant.

**To Reproduce (observed behavior)**
Construct a client such as Aws::IAM::IAMClient with a Aws::Client::ClientConfiguration with its region member set to "".

**Expected behavior**
Return the region unchanged which should then generate are more friendly error later. So change the line to:

`else if ((region.size() >= 5) && (region.compare(region.size() - 5, 5, "-fips") == 0))`

Ideally also detect an empty string region and suggest that "aws-global" is used instead.

**Logs/output**
Not relevant.

**Comment by KaibaLopez** [comment]
Hi @Gram-C ,
Yeah that makes sense... Thanks for pointing this out, we'll take a look at it.

**Comment by wps132230** [comment]
Hi, there.
Thank you for reporting this issue, and it was fixed in commit: https://github.com/aws/aws-sdk-cpp/commit/0c9a6988c8c02b53aa8ecfb75cb5ff1b01f98085#diff-f07f1cd7d3a94b791dd7a16886e77823L22-R26
