### ISSUE TITLE
AWS SQS - How to get SentTimestamp?

### ISSUE THREAD

**Issue by ncoder-1** [aws/aws-sdk-cpp#1447]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Linux-5.8.5, aws-sdk-cpp version 1.8.39

**Describe the question**

I'm trying to get the `SentTimestamp` from a message, I've tried many variations of what I could find in [this issue](https://github.com/aws/aws-sdk-cpp/issues/83) and looked at the [doc](https://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_s_q_s_1_1_model_1_1_message.html) but I'm unable to get the individual message's `SentTimestamp`  attribute.

Below is my simple receive function:

```cpp
void ReceiveMessage(const Aws::SQS::SQSClient& sqs, const Aws::String& queue_url) {
  Aws::SQS::Model::ReceiveMessageRequest rm_req;
  rm_req.SetQueueUrl(queue_url);
  rm_req.AddMessageAttributeNames("All");
  rm_req.SetMaxNumberOfMessages(1);

  auto rm_out = sqs.ReceiveMessage(rm_req);
  if (!rm_out.IsSuccess()) {
    std::cerr << "Error receiving message\n";
    return;
  }

  const auto& messages = rm_out.GetResult().GetMessages();
  if (messages.empty()) {
    std::cout << "No messages received\n";
    return;
  }

  const auto& message = messages[0];

  auto message_mav = message.GetMessageAttributes();
  if (message_mav.find("SentTimestamp") != message_mav.end()) {
    std::cout << "Found SentTimestamp: " << message_mav["SentTimestamp"].GetStringValue() << '\n';
  }

  std::cout << "Received message (" << message.GetBody().length() << " bytes):\n";
  std::cout << message.GetBody() << "\n\n";

  Aws::SQS::Model::DeleteMessageRequest dm_req;
  dm_req.SetQueueUrl(queue_url);
  dm_req.SetReceiptHandle(message.GetReceiptHandle());

  auto dm_out = sqs.DeleteMessage(dm_req);
  if (dm_out.IsSuccess()) {
    std::cout << "Successfully deleted message\n";
  } else {
    std::cerr << "Error deleting message\n";
  }
}
```

I'm currently manually adding my own timestamp inside a `Aws::SQS::Model::MessageAttributeValue` as a string, which I'd like to avoid.  Any suggestions?

**Comment by KaibaLopez** [comment]
Hi @ncoder-1 ,
It is a bit confusing with so many similar names but here's how to get the timestamp in your code sample( keep in mind it is saved in[ Unix time](https://en.wikipedia.org/wiki/Unix_time) ).
```cpp
void ReceiveMessage(const Aws::SQS::SQSClient& sqs, const Aws::String& queue_url) {
    Aws::SQS::Model::ReceiveMessageRequest rm_req;
    rm_req.SetQueueUrl(queue_url);
    rm_req.AddAttributeNames(QueueAttributeName::All); // this is the first change to your code
    rm_req.SetMaxNumberOfMessages(1);
/*rest of the code*/
    const auto& message = messages[0];

    auto message_mav = message.GetAttributes();
    auto iter = message_mav.find( MessageSystemAttributeName::SentTimestamp ); // same idea only different type of data.
    if(iter != message_mav.end()){
        std::cout << "timestamp : " << iter->second <<std::endl; //you'll get an int representing the time.
    }
/*rest of the code*/
...
}
```

**Comment by ncoder-1** [comment]
Hi @KaibaLopez ,

That worked perfectly!  Thanks for the help!

**Comment by ncoder-1** [comment]
I'm getting 3 extra numbers at the end of the timestamp, can you confirm if you are getting the same?  This puts the time some 52,000 years in the future...

**Comment by webbnh** [comment]
The value is in [milliseconds](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html#API_ReceiveMessage_RequestParameters) since the UNIX Epoch.

`1599168535236` [converts](https://www.epochconverter.com) to Thursday, September 3, 2020 9:28:55.236 PM GMT.

**Comment by ncoder-1** [comment]
@webbnh , got it, that makes sense! Thanks!
