### ISSUE TITLE
Build fails on MacOSX 10.15.5 with XCode 11.7

### ISSUE THREAD

**Issue by dhilowitz** [aws/aws-sdk-cpp#1449]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
When I build the library for the first time, the build fails because the `HttpClientTest.TestRandomURL` fails. 

**SDK version number**

**Platform/OS/Hardware/Device**
MacOSX 10.15.5 with XCode 11.7

**To Reproduce (observed behavior)**
Here's my build command:

    cd "~/SDKs"
    git clone --depth=1 https://github.com/aws/aws-sdk-cpp.git 5
    cd aws-sdk-cpp
    mkdir build
    cd build
    
    cmake "~/SDKs/aws-sdk-cpp" -DTARGET_ARCH="APPLE" -DBUILD_ONLY="core;s3"
    sudo make -j 3

**Expected behavior**
I expect the SDK to build and for tests to pass.

**Logs/output**

```
...
[ RUN      ] JsonSerializerTest.TestNullSanity
[       OK ] JsonSerializerTest.TestNullSanity (0 ms)
[ RUN      ] JsonSerializerTest.TestJsonIntegerValue
[       OK ] JsonSerializerTest.TestJsonIntegerValue (0 ms)
[----------] 19 tests from JsonSerializerTest (0 ms total)

[----------] 10 tests from EventStreamDecoderTest
[ RUN      ] EventStreamDecoderTest.EventStreamHeaderValueTest
[       OK ] EventStreamDecoderTest.EventStreamHeaderValueTest (0 ms)
[ RUN      ] EventStreamDecoderTest.ContEventMessageTest
[       OK ] EventStreamDecoderTest.ContEventMessageTest (0 ms)
[ RUN      ] EventStreamDecoderTest.StatsEventMessageTest
[       OK ] EventStreamDecoderTest.StatsEventMessageTest (0 ms)
[ RUN      ] EventStreamDecoderTest.RequestLevelExceptionTest
[       OK ] EventStreamDecoderTest.RequestLevelExceptionTest (0 ms)
[ RUN      ] EventStreamDecoderTest.RequestLevelErrorMessageTest
[       OK ] EventStreamDecoderTest.RequestLevelErrorMessageTest (0 ms)
[ RUN      ] EventStreamDecoderTest.BadInternalPayloadTest
[       OK ] EventStreamDecoderTest.BadInternalPayloadTest (0 ms)
[ RUN      ] EventStreamDecoderTest.EndEventMessageTest
[       OK ] EventStreamDecoderTest.EndEventMessageTest (0 ms)
[ RUN      ] EventStreamDecoderTest.IncompleteAndMultipleMessagesTest
[       OK ] EventStreamDecoderTest.IncompleteAndMultipleMessagesTest (0 ms)
[ RUN      ] EventStreamDecoderTest.RecordsEventMessageTest
[       OK ] EventStreamDecoderTest.RecordsEventMessageTest (0 ms)
[ RUN      ] EventStreamDecoderTest.ProgressEventMessageTest
[       OK ] EventStreamDecoderTest.ProgressEventMessageTest (0 ms)
[----------] 10 tests from EventStreamDecoderTest (1 ms total)

[----------] Global test environment tear-down
[==========] 374 tests from 67 test cases ran. (5194 ms total)
[  PASSED  ] 373 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] HttpClientTest.TestRandomURL

 1 FAILED TEST
make[2]: *** [aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 1
make[2]: *** Deleting file `aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests'
make[1]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
make: *** [all] Error 2

```

**Additional context**

**Comment by dhilowitz** [comment]
I've tried this now on two different Macs running two different OSes (Catalina and High Siera). Both fail.

**Comment by KaibaLopez** [comment]
Hi @dhilowitz ,
I am currently trying the latest version of the sdk on a high sierra mac and I'm not able to reproduce the issue.
 
Looking at the test it tries a get request on the url `"http://some.unknown1234xxx.test.aws"`, see [here](https://github.com/aws/aws-sdk-cpp/blob/a9a5406dcfe30e4113f45d7b055c282bedcb2418/aws-cpp-sdk-core-tests/http/HttpClientTest.cpp#L20).  
It is expected to fail but not get null response, we've also had edge cases on this before (sometimes it goes into a search engine for example). 

Before I dig too deep into this, could you please verify that you are not under some firewall that is blocking the request?
Also, in case you are being blocked by this, you can use the cmake flag `-DENABLE_TESTING= OFF`while we figure it out.

**Comment by dhilowitz** [comment]
Hi. Thanks for your reply. Using `-DENABLE_TESTING= OFF` does seem to solve my issue.

As for a firewall, my ISP is Verizon FIOS and right now I'm using their default DNS. The DNS seems to redirect that fake URL to some crappy "Page not found" FIOS page. Maybe that is causing the issue?

**Comment by KaibaLopez** [comment]
Hmmm, is there a way you could turn that off and test?
If not, could you try and tell me the http response you get from the page? It might be worth it to account for another edge case.
Otherwise the best work around I can think of is to manually turn that test off, or to keep building without the tests.
