### ISSUE TITLE
In 32 bits C++ SDK, TransferManager cannot upload big size file

### ISSUE THREAD

**Issue by Anandkumar-Veritas** [aws/aws-sdk-cpp#1454]
AWS C++ SDK version: 1.6.25

Description:
We are using AWS C++ SDK 1.6.25 in our product & trying to use TransferManager to upload files from on-premise to S3 partition. We are using 32-bit binaries as our product supports 32 bit binaries only.
TransferManager works fine with small size files. 
Recently, we faced challenge while uploading file having size more than 4 GB. It got uploaded partially around 1.6 GB.
We checked the code of TransferManager & found the following piece of code causing the issue. (The code is from TransferManager.cpp) 

fileStream->seekg(0, std::ios_base::end);
size_t length = static_cast<size_t>(fileStream->tellg());

Here, TransferManager calculating the size of the file before uploading it. The data type used is size_it which is internally unsigned int. 
unsigned int has size limitations on 32 bit architecture, where size would be 4 bytes so it cannot calculate the exact size of large files.

Can AWS C++ SDK team please take a look & fix this issue as soon as possible?

**Comment by Anandkumar-Veritas** [comment]
Hi,

Any updates on this issue? 
Could you please confirm, is it possible to get this fix in next AWS C++ SDK release?

Please reply.

**Comment by KaibaLopez** [comment]
Hi @Anandkumar-Veritas ,
Sorry for the late response, this was fixed on version 1.8.53. 
Please update teh SDK and let me know if the error persists.
