### ISSUE TITLE
TransferManager fails to upload big size file > 4 GB

### ISSUE THREAD

**Issue by Anandkumar-Veritas** [aws/aws-sdk-cpp#1455]
I have raised similar issue for AWS C++ SDK 1.6.25 which fails to upload big size file > 4 GB for 32 bit architecture.
But same issue we found on latest AWS C++ SDK 1.8.44. 
In latest version of TransferManager code we can still see same piece of code to calculate size of the file before uploading it to S3.

fileStream->seekg(0, std::ios_base::end);
size_t length = static_cast<size_t>(fileStream->tellg());

The data type used is size_it which is internally unsigned int.
unsigned int has size limitations on 32 bit architecture, where size would be 4 bytes so it cannot calculate the right size of large files.

Can AWS C++ SDK team please take a look & fix this issue for latest SDK?

**Comment by KaibaLopez** [comment]
Hi @Anandkumar-Veritas ,
It seems like this is a duplicate issue from the one you just opened here #1454 , so I'll be closing this one and we'll look into this and respond on the other one, unless there is a difference on the 2 bugs that I'm not seeing?

**Comment by Anandkumar-Veritas** [comment]
Thanks for addressing the issue.
There is no difference in issue, only the version of AWS C++ SDKs is different and we are expecting fix in both versions.
