### ISSUE TITLE
Symbol not found error while running my executable. Building sdk as external project

### ISSUE THREAD

**Issue by disa6302** [aws/aws-sdk-cpp#1457]
Confirm by changing [ ] to [x] below:
- [X ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
MacOS 10.14

**Describe the question**
I am adding CPP SDK as an external project. The configuration is as follows:
```
cmake_minimum_required(VERSION 2.8)

project(libawscpp-download NONE)

include(ExternalProject)

ExternalProject_Add(libawscpp-download
    GIT_REPOSITORY    https://github.com/aws/aws-sdk-cpp.git
    GIT_TAG           1.8.17
    PREFIX            ${CMAKE_CURRENT_BINARY_DIR}/build
    CMAKE_ARGS        -DBUILD_ONLY=monitoring;logs -DENABLE_TESTING=OFF -DCUSTOM_MEMORY_MANAGEMENT=OFF
    BUILD_ALWAYS      TRUE
    TEST_COMMAND      ""
)
```

In my main CMake file, I run `find_package(AWSSDK REQUIRED COMPONENTS monitoring logs)` and while linking, I run I link with `${AWS_SDK_LINK_LIBRARIES}`. Everything builds fine the target executable is generated. However, when I run the executable, I run into this issue:

```
dyld: lazy symbol binding failed: Symbol not found: __ZN3Aws6Region19ComputeSignerRegionERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS_9AllocatorIcEEEE
  Referenced from: /usr/local/lib/libaws-cpp-sdk-logs.dylib
  Expected in: /usr/local/lib/libaws-cpp-sdk-core.dylib

dyld: Symbol not found: __ZN3Aws6Region19ComputeSignerRegionERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS_9AllocatorIcEEEE
  Referenced from: /usr/local/lib/libaws-cpp-sdk-logs.dylib
  Expected in: /usr/local/lib/libaws-cpp-sdk-core.dylib

Abort trap: 6
```

I am unsure if I am messing something up, but does anyone have any experience adding CPP SDK as external project in the past?

**Comment by webbnh** [comment]
>  `Expected in: /usr/local/lib/libaws-cpp-sdk-core.dylib`

Your build isn't finding the core library...

> `    CMAKE_ARGS        -DBUILD_ONLY=monitoring;logs`

...perhaps because your build isn't building the core library?

Try

```
    CMAKE_ARGS        -DBUILD_ONLY=core;monitoring;logs
```
and see if that resolves your issue.

**Comment by disa6302** [comment]
@webbnh , 

I installed core. But it still does not seem to work. These are the contents of `/usr/local/lib`

<img width="876" alt="Screen Shot 2020-09-11 at 9 18 33 AM" src="https://user-images.githubusercontent.com/22107309/92949539-1b20a600-f410-11ea-8654-da8dd084d24d.png">

**Comment by KaibaLopez** [comment]
@disa6302 
hmmm, that's odd, can you try adding `-DCMAKE_PREFIX_PATH="/usr/local/lib"` to the cmake arguments?

**Comment by disa6302** [comment]
@KaibaLopez , 

I added that. But, I still get the same error. One thing I do in my main CMake file is, run this: `find_package(AWSSDK REQUIRED COMPONENTS monitoring core logs)`

I also add a custom path to `CMAKE_MODULE_PATH` to point to the CPP SDK External Project CMake file. Not sure if this helps.

**Comment by KaibaLopez** [comment]
@disa6302 
so, probably not related to the problem, but cmake version 3 is required for the sdk, so i would change the first line. 

Second, I may be wrong but the way I understand it, `CMAKE_MODULE_PATH` is basically used for find_package when those are within the project, which would not be the case for this. the [first answer on this stackoverflow question](https://stackoverflow.com/questions/20746936/what-use-is-find-package-if-you-need-to-specify-cmake-module-path-anyway) explains it better.
I don't think that means that it doesn't look for the install locations though, specially if you explicitly tell where to look I'd expect it to do both but you know, cmake behavior has surprised me before so maybe? 

And finally just to be sure on how to start trying to reproduce this, if you do a simple app like the one on [this tutorial](https://github.com/aws/aws-sdk-cpp/wiki/Building-the-SDK-from-source-on-EC2) (ignore the ec2 part, just building the app). Does that work for you or does it fail the same way?

**Comment by disa6302** [comment]
@KaibaLopez , 

I tried the tutorial. I get the same error: 

dyld: lazy symbol binding failed: Symbol not found: __ZN3Aws6Client15AWSAuthV4SignerC1ERKNSt3__110shared_ptrINS_4Auth22AWSCredentialsProviderEEEPKcRKNS2_12basic_stringIcNS2_11char_traitsIcEENS_9AllocatorIcEEEENS1_20PayloadSigningPolicyEb
  Referenced from: /usr/local/lib/libaws-cpp-sdk-s3.dylib
  Expected in: /usr/local/lib/libaws-cpp-sdk-core.dylib

dyld: Symbol not found: __ZN3Aws6Client15AWSAuthV4SignerC1ERKNSt3__110shared_ptrINS_4Auth22AWSCredentialsProviderEEEPKcRKNS2_12basic_stringIcNS2_11char_traitsIcEENS_9AllocatorIcEEEENS1_20PayloadSigningPolicyEb
  Referenced from: /usr/local/lib/libaws-cpp-sdk-s3.dylib
  Expected in: /usr/local/lib/libaws-cpp-sdk-core.dylib

**Comment by disa6302** [comment]
One thing I noticed: 

` CMAKE_ARGS        -DBUILD_ONLY=core;monitoring;logs` builds only `core` or whatever the first value is. It does not build monitoring and logs. Somehow those arguments are not taken.

**Comment by webbnh** [comment]
Try putting the list in double quotation marks:
```
 -DBUILD_ONLY="core;monitoring;logs"
```
(My apologies:  in my previous reply I copied an modified your code -- in _my_ code, I've got the quotes....)

**Comment by disa6302** [comment]
<img width="603" alt="Screen Shot 2020-09-14 at 9 15 45 AM" src="https://user-images.githubusercontent.com/22107309/93111024-ecead280-f66a-11ea-8707-ee4d61ff9580.png">


I tried that. This is what I get.

**Comment by webbnh** [comment]
Well that's disappointing!

I'm not using `ExternalProject_Add()` in my code -- I'm just using the `-D` on the `cmake` command line.

Perhaps the quotes need to be around the whole option:
```
    CMAKE_ARGS        "-DBUILD_ONLY=core;monitoring;logs" -DENABLE_TESTING=OFF -DCUSTOM_MEMORY_MANAGEMENT=OFF
```
If you omit the quotes, do the other two `-D`'s seem to be having any effect?

(Semicolons, lists, and quoting are tricky in CMake.)

**Comment by disa6302** [comment]
I have actually not checked if the other 2 have any effect. But yes, if I run `-D` on the `cmake` command line, it works perfectly well. I just face issues when I run ExternalProject_Add(). I am trying `"-DBUILD_ONLY=core;monitoring;logs"` now, but, I am not sure how else I can run this in `ExternalProject_Add()`.

**Comment by webbnh** [comment]
The only thing I can think of is to try to create the values that you want in variables and then reference the variables in the `ExternalProject_Add()` invocation...however, that's likely to be tricky to do, because of the interaction between "lists" and "strings" in CMake.

**Comment by disa6302** [comment]
Yeah. `"-DBUILD_ONLY=core;monitoring;logs"` does not work.

**Comment by KaibaLopez** [comment]
@disa6302 ,
core should build by default even if you don't add it to the -DBUILD_ONLY list but it doesn't make a difference if you add it. @webbnh  was right that you need quotes around the list, otherwise it only takes the first one there.
`cmake .. -DBUILD_ONLY="monitoring;logs" `
The fact that you are getting the same error even when building the sample tells me there is something off about your set up, so I doubt the cmake command is the problem. Can you walk me through how you installed the sdk? (did you build the dependencies separately and/or what arguments did you use on your cmake command, that kind of thing).

**Comment by disa6302** [comment]
@KaibaLopez , 

I am trying to install the SDK using External project and execute process. I am not building the dependencies separately. This is my CMake args list: 

```
 CMAKE_ARGS        -DENABLE_TESTING=OFF -DCUSTOM_MEMORY_MANAGEMENT=OFF -DBUILD_DEPS=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_ONLY="monitoring;logs" 
```

When I run `cmake` from command line with -DBUILD_ONLY="monitoring;logs", the installation works fine and I see the assets in `/usr/local/lib` and `/usr/local/include/aws`. However, When I use the same arg in `ExternalProject_Add`, I get the error above about double quotes. 

As mentioned by @webbnh , I do suspect it is a list->string issue. But, I could be wrong. Let me know if you need any other information.

**Comment by disa6302** [comment]
@webbnh @KaibaLopez , 

Thank you for all your assistance. I found a similar issue, and this worked: https://github.com/aws/aws-sdk-cpp/issues/826

I would like to recommend that the team look into adding instructions on how to add the SDK as an external project. I think it will be really helpful since it can be quite a common way to add this project with External add. If the team welcomes contributions, I could add the section in the README.md as well. Let me know.

**Comment by KaibaLopez** [comment]
Hey @disa6302 ,
Yea that does sound like a good idea, and we most definitely take contributions! please make a PR with the instructions that worked for you.
Actually, and just for clarity and visibility, it would help if you could open a new issue as a feature request and then make the PR, that way I can close this issue which is no longer a guidance thing and we can focus on the other one (plus other team members wouldn't need to go through the whole conversation).

**Comment by disa6302** [comment]
Sure! I can do that. 

Let me create a new PR. Thank you for your support!
