### ISSUE TITLE
aws-cpp-sdk-core: No such file or directory issue

### ISSUE THREAD

**Issue by rafayhameed** [aws/aws-sdk-cpp#1458]
**Platform/OS/Hardware/Device**
CentOS

**Describe the question**
I am trying to install aws-cpp-sdk-core and aws-cpp-sdk-kinesis on CentOS. I have already installed aws-c-common, aws-checksums and aws-c-event-stream successfully. 

cmake command : 
cmake <path-to-root-of-this-source-code> -DBUILD_DEPS=OFF -DCMAKE_PREFIX_PATH=<deps-install-dir>
I have already tried without  -DBUILD_DEPS=OFF and other flags but unsuccessful so far.

I am getting the error "No such file or directory" on make stage for KinesisClient and AmazonSerializableWebServiceRequest. 
.h and .cpp Files for KinesisClient and AmazonSerializableWebServiceRequest are present in the source folder but the object files are not created after the cmake command in aws-cpp-sdk-core directory and so I get this error after make.

**Logs/output**
1. on core
#make
Scanning dependencies of target aws-cpp-sdk-core
[  1%] Building CXX object CMakeFiles/aws-cpp-sdk-core.dir/source/AmazonSerializableWebServiceRequest.cpp.o
c++: error: aws-cpp-sdk-core: No such file or directory
make[2]: *** [CMakeFiles/aws-cpp-sdk-core.dir/build.make:63: CMakeFiles/aws-cpp-sdk-core.dir/source/AmazonSerializableWebServiceRequest.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/aws-cpp-sdk-core.dir/all] Error 2

2. on Kinesis

# make
Scanning dependencies of target aws-cpp-sdk-core
[  1%] Building CXX object CMakeFiles/aws-cpp-sdk-core.dir/source/KinesisClient.cpp.o
c++: error: aws-cpp-sdk-core: No such file or directory
make[2]: *** [CMakeFiles/aws-cpp-sdk-core.dir/build.make:63: CMakeFiles/aws-cpp-sdk-core.dir/source/KinesisClient.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/aws-cpp-sdk-core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

**Comment by KaibaLopez** [comment]
Hi @rafayhameed ,
I'm pretty sure this is just a typo kind of problem, I'd recommend going through the [Building From Source - third party dependencies](https://github.com/aws/aws-sdk-cpp#third-party-dependencies) instructions step by step just in case.

If you're still having problems though, the cmake error points to libraries not being found, so for me to reproduce this error I'm going to need the full commands and steps you took to build the sdk... as an example on why this is incomplete when you say you ran `cmake -DBUILD_DEPS=OFF -DCMAKE_PREFIX_PATH=` I assume you're running it from the source folder when usually you'd want to run from a "build" folder and tell cmake where the source is. 


And finally, I'd recommend building only the components you need for your application, the sdk is pretty big and can take a long time to build, try adding the cmake parameter `-DBUILD_ONLY="s3" ` (or kinesis, or whtever component you're thinking of using)
