### ISSUE TITLE
Region does not check for string size in ComputeSignerRegion

### ISSUE THREAD

**Issue by villqrd** [aws/aws-sdk-cpp#1469]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
The size of the region is not checked before doing a string possibly leading to an out of range error (in case of `region.size() < 5`).

**SDK version number**
1.8.50

**Platform/OS/Hardware/Device**
Ubuntu 18.04

**To Reproduce (observed behavior)**
```cpp
#include <aws/s3/S3Client.h>

int main(int argc, char *argv[]) {
    Aws::Region::ComputeSignerRegion("gra");
    return 0;
}
```
This leads to an out of range error.

**Expected behavior**
I expect the sdk to hit the last clause of the if / else and return the string unchanged.

**Logs/output**
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::compare: __pos (which is 18446744073709551614) > this->size() (which is 3)
```

**Additional context**
This is important as I want to use the SDK with S3 buckets hosted on a provider that uses a region string of length 3 ("gra") and this `ComputeSignerRegion` is being called when I instantiate an `Aws::S3::S3Client`.

Happy to be assigned to this issue.

**Comment by KaibaLopez** [comment]
Hi @alexandrevillard ,
Yea, thanks for reporting this but, it is a bit of a known issue and was reported to us previously #1439  
So, yea going to close this issue as a duplicate and we'll keep the older one open, feel free to comment on it.
