### ISSUE TITLE
How to logging into cloud watch using c++ ?

### ISSUE THREAD

**Issue by latapankaj** [aws/aws-sdk-cpp#1470]
**Platform: Window10**
What are you running the sdk on?
VS2017
**Describe the question**
Hi
I am working on a project on which i need to log the data into cloud watch .I have google it but not able to get how to do that and what will be steps to do it from scratch.

Please guide from scratch.

**Comment by KaibaLopez** [comment]
Hi @latapankaj ,
Hmmm, we may not have a step by step guide for cloudwatch but we do have several code samples on how to use it with the c++ SDK, and you can find them [here](https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/cpp/example_code/cloudwatch).
So yea, I don't think I can help you build your specific project unless you have more specific questions, but hope these samples help you to at least get started.

**Comment by latapankaj** [comment]
ok

**Comment by latapankaj** [comment]
I am doing login as a first step . I am using that code to login into account but not getting how to get response back that I login into the account or not ?
`

 int main()
 {
     Aws::SDKOptions options;
    Aws::InitAPI(options); options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Info;
    Aws::InitAPI(options);
    Aws::Client::ClientConfiguration configuration;
    configuration.region = Aws::Region::US_EAST_2;
     Aws::Auth::AWSCredentials creds(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY);
     Aws::ShutdownAPI(options);
     return 0;
     }
`

**Comment by KaibaLopez** [comment]
that code will only do the setup, there is no concept of "login" but to establish a connection you need to create a client, and have it make a request, then you can get a success or failure response.

Here, I've written a quick sample code on adding a log event to cloudwatch. Hope it helps.
```
#include <aws/core/Aws.h>
#include <aws/logs/CloudWatchLogsClient.h>
#include <aws/logs/model/PutLogEventsRequest.h>

using namespace Aws;
using namespace Aws::Http;
using namespace Aws::Client;
using namespace Aws::CloudWatchLogs;
using namespace Aws::CloudWatchLogs::Model;

int main(){
    Aws::SDKOptions options;
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
    Aws::InitAPI(options);
    ClientConfiguration config;
    config.region = Aws::Region::US_EAST_2;
    auto m_client = Aws::MakeUnique<Aws::CloudWatchLogs::CloudWatchLogsClient>("cloudwatch Client", config);
    PutLogEventsRequest putRequest;
    putRequest.WithLogGroupName("someGroupName")
                       .WithLogStreamName("someLogStreamName");
     InputLogEvent e1;
     e1.WithTimestamp(Aws::Utils::DateTime::Now().Millis()).WithMessage("Test Message 1");
     InputLogEvent e2;
     e2.WithTimestamp(Aws::Utils::DateTime::Now().Millis()).WithMessage("Test Message 2");

     putRequest.AddLogEvents(e1).AddLogEvents(e2);
     putRequest.WithSequenceToken("fake");
     auto putOutcome = m_client->PutLogEvents(putRequest);
     if(!putOutcome.IsSuccess()){
         std::cout<< "error on the putOutcome: "<<std::endl;
         std::cout<< putOutcome.GetError().GetMessage()<< std::endl;
    }else{
         std::cout<< "success"<<std::endl;
    }
    Aws::ShutdownAPI(options);
```

**Comment by latapankaj** [comment]
Hi @KaibaLopez
I have tried the code and it is working fine .only the thing i have found that fr a single entry it will take min 15 seconds to log the data into cloud watch .Suggest if can modify this to take minimum time.
Thanks!!

**Comment by KaibaLopez** [comment]
@latapankaj I believe this is a service limitation, I've looked a bit around and it seems like there are different types of logs and events and different timings depending on the services you are getting the logs from.
I'm not super familiar with it but you can find more info on [cloudwatch here](https://docs.aws.amazon.com/cloudwatch/index.html)

**Comment by latapankaj** [comment]
Hi @KaibaLopez 
Thank you for your response. I have resolved the issue by initialize the AWS SDK only once and then log the data into cloud watch.
Thanks !!
