### ISSUE TITLE
Is AWS SDK for C++ supported/stable on RHEL7 / CentOS7?

### ISSUE THREAD

**Issue by actian-sandor** [aws/aws-sdk-cpp#1471]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
RHEL7 / CentOS 7 / Ubuntu 18

**Describe the question**
To build the SDK, the readme clearly states a requirement to use gcc 4.9 or later.
There are no claims regarding supported Linux distributions though.
I am bringing this up as both RH and CentOS 7 come with gcc 4.8 and its libstdc++.so, which does _not_ support cxx11 ABI.
gcc versions >= 4.9 can be installed through devtoolsets.
However, even with the newer gcc versions from those devtoolsets, **use of cxx11 ABI is always forcibly disabled** as RH enforces _GLIBCXX_USE_CXX11_ABI=0 even when set to 1.
See https://bugzilla.redhat.com/show_bug.cgi?id=1546704
And also https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

So my question is whether AWS SDK can be safely compiled and used on RH7 and CentOS7 (using devtoolset 3 or higher) or, whether those platforms are basically deemed 'unusable' for use of the AWS C++ SDK?

Basically, the std::string on RH and CentOS7 would fallback to non-cxx11 compliant copy-on-write implementation for strings.
And I am wondering whether that introduces problems/unsafely for the SDK.

**Logs/output**
Just as an illustration, S3 library built on RH7 gives:

`nm -gDC <RH7PREFIX>/lib64/libaws-cpp-sdk-s3.so | grep GetBucketLocationConstraintForName
0000000000168af0 T Aws::S3::Model::BucketLocationConstraintMapper::GetBucketLocationConstraintForName(**std::basic_string**<char, std::char_traits<char>, Aws::Allocator<char> > const&)`

while compiled on Ubuntu 18 it gives the 'proper' C++11 version:
`nm -gDC <U18PREFIX>/lib/libaws-cpp-sdk-s3.so | grep GetBucketLocationConstraintForName
000000000017b9d0 T Aws::S3::Model::BucketLocationConstraintMapper::GetBucketLocationConstraintForName(**std::__cxx11::basic_string**<char, std::char_traits<char>, Aws::Allocator<char> > const&)`

**Comment by KaibaLopez** [comment]
Hi @actian-sandor ,
Yes, it should be safe to use the sdk on both of those Linux distributions. I've personally tested on both of them and found no problems. 
That being said, there's always a chance something is off so if you do find a problem while using it please open a bug report.

**Comment by actian-sandor** [comment]
Hi @KaibaLopez 

Thanks for your reply, that sounds promising.
Did you use any of the devtoolsets for such testing? Or did you build your own >=gcc4.9 toolchain?

Best, Sandor

**Comment by KaibaLopez** [comment]
@actian-sandor ,
Yea, no devtools, I just built gcc and g++ latest versions manually, plus the rest of the requirements, like cmake 3, openssl 1.1, etc.

**Comment by actian-sandor** [comment]
Hi @KaibaLopez,

Thanks for that confirmation. This is far from ideal though, as it would require shipping libstdc++ along with our software on RHEL7 based systems.
Unless someone on the Amazon side can motivate/validate the minimum gcc requirement of version 4.9.
Does this requirement imply that Amazon considers it safe to use corresponding libstdc++4.9 (which in turn implies C++03 ABI)?

This libstdc++/ABI combination still has a non-conformant string implementation:
https://gcc.gnu.org/onlinedocs/gcc-4.9.0/libstdc++/manual/manual/status.html#status.iso.2011 (search for 'Class template basic_string')

It may very well be that this is not a problem for the SDK though, i.e. if it eliminates scenarios where a dangling pointer could be left due to copy-on-write string model, as described by Jonathan Wakely (libstdc++ maintainer at RedHat) in his answer to this post:
https://stackoverflow.com/questions/12199710/legality-of-cow-stdstring-implementation-in-c11

If someone can confirm whether or not this is a non-issue for the SDK, then simply compiling our code with -D_GLIBCXX_USE_CXX11_ABI=0 might be preferrable over shipping a newer libstdc++.

Any clarification on this would be highly appreciated.

Thanks

Sandor

**Comment by KaibaLopez** [comment]
So, take this with a grain of salt because I wasn't there when the decision was made but, I believe the min gcc version required is 4.9 because of c++11 and although gcc 4.8 was the first to support c++11, it had some errors using the atomic library which 4.9 fixes, so we considered 4.9 the first to "fully" support it and went with it.
That being said, I don't think the string thing is an issue for the sdk, at least it wasn't part of the gcc version decision from 4.8 to 4.9, so you should be able to run that, but keep in mind it would be your responsibility, meaning we wouldn't consider bugs that show up because of this.

**Comment by actian-sandor** [comment]
Thanks for the clarification @KaibaLopez
We'll test/decide in-house which version to move forward with.

Kind regards,

Sandor

**Comment by KaibaLopez** [comment]
alright, I'll be closing this issue then.

Feel free to open a new one if you've got more (or other) questions though.
