### ISSUE TITLE
Expose AWS_SDK_VERSION_MAJOR, AWS_SDK_VERSION_MINOR and AWS_SDK_VERSION_PATCH

### ISSUE THREAD

**Issue by pitrou** [aws/aws-sdk-cpp#1472]
Currently only `AWS_SDK_VERSION_STRING` is exposed to user code (in `aws/core/VersionConfig.h`).
To switch at compile-time between different code paths, it would be more useful to access the numeric version macros. Those seem to exist during the build chain of the SDK itself, but are not exposed in any headers.

**Comment by pitrou** [comment]
Example where this would have helped (setting `Aws::Client::ClientConfiguration::followRedirects` in a compatible way):
https://github.com/apache/arrow/pull/8261/files#diff-e9f354b91b661561b027f4c50dea4d17

**Comment by KaibaLopez** [comment]
Hi @pitrou ,
Is there a reason why you can't use `Aws::Version::GetVersionMajor()` / `Aws::Version::GetVersionMinor()` / `Aws::Version::GetVersionPatch()` from `aws/core/Version.h`?

**Comment by pitrou** [comment]
They wouldn't help me if I want to switch code at compile-time. See the example I linked to.

**Comment by pitrou** [comment]
Basically, ideally I could have written:
```c++

void DisableRedirects(Aws::Client::ClientConfiguration* c) {
#if AWS_SDK_VERSION_MAJOR == 1 && AWS_SDK_VERSION_MINOR <= 7
  c->followRedirects = false;
#else
  c->followRedirects = PolicyEnum::NEVER;
#endif
}
```

**Comment by KaibaLopez** [comment]
Hi, 
This is now merged in the newest version of the SDK. I'll be closing this issue.
