### ISSUE TITLE
Some mind of PutObjectRequest.SetBody

### ISSUE THREAD

**Issue by ToBeMyOwnHero** [aws/aws-sdk-cpp#1478]
Hi,I saw the class _PutObjectReques_ have a method _SetBody_ in S3,it defined as 
**inline void SetBody(const std::shared_ptr<Aws::IOStream>& body) { m_bodyStream = body; }**

What my confusion is that _SetBody_ must input a IOStream.when I use _PutObjectRequestAsync_ to upload a file,but this need me change a file to a stream, I think it spent too much time. I think if do this work that change a file to a stream in exector must be better. Maybe SDK have some other method do it. Could  you help me?

**Comment by KaibaLopez** [comment]
Hi @ToBeMyOwnHero ,
I am sorry but I am not exactly understanding what your problem is with the putobject request... But, I would suggest using the TransferManager for your s3 operations, it is meant to make the operations simpler, as it decides for you whether it does sync/async or single/multi part.

Here's a quick sample on how to do uploads:
```
#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>

#include <aws/transfer/TransferManager.h>
#include <iostream>
#include <fstream>
#include <time.h>
#include <string>

using namespace Aws;
using namespace Aws::Transfer;

Aws::SDKOptions options;
std::mutex semaphoreLock;


int main(){
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;
    Aws::InitAPI(options);

    Aws::String testFileName = "yourfileName.txt";
    Aws::Client::ClientConfiguration client_config("default");
    auto m_s3Client = MakeShared<Aws::S3::S3Client>( "S3Client", client_config);
    
    Aws::Utils::Threading::DefaultExecutor executor; 

    TransferManagerConfiguration transferManagerConfig(&executor);
    transferManagerConfig.s3Client = m_s3Client;
    
    auto transferManager = TransferManager::Create(transferManagerConfig);
        
    std::shared_ptr<TransferHandle> uploadHandle = transferManager->UploadFile(testFileName, "bucketName", "keyValue", "text/plain", Aws::Map<Aws::String, Aws::String>());
    uploadHandle->WaitUntilFinished();
    bool success = uploadHandle->GetStatus() == TransferStatus::COMPLETED;

    if(success){
        std::cout<< "this worked"<<std::endl;
        std::cout<<"handler size: "<<sizeof(*uploadHandle)<<std::endl;
        std::cout<<"object total size: "<< uploadHandle->GetBytesTotalSize()<<std::endl;
    }else
    {
        std::cout<<"it didnt work Because : " << uploadHandle->GetLastError()<<std::endl;
    }

    Aws::ShutdownAPI(options);
}
```

Let me know if this helped you or if I misunderstood your question.
