### ISSUE TITLE
S3 fails to build (Windows 10, VS 2019)

### ISSUE THREAD

**Issue by marcoherrerarendon** [aws/aws-sdk-cpp#1479]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
The msbuild step fails when following these instructions https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup.html (for Windows)

**SDK version number**
Current on master (tag: 1.8.56)

**Platform/OS/Hardware/Device**
Windows 10 
Visual Studio 2019 Version 16.4.4

**To Reproduce (observed behavior)**
I entered these commands based on the documentation from the link above
```
git clone https://github.com/aws/aws-sdk-cpp.git
mkdir sdk_build
cd sdk_build
cmake ../aws-sdk-cpp -D CMAKE_BUILD_TYPE=Release -D BUILD_ONLY="s3"
msbuild ALL_BUILD.vcxproj
```
It fails on the last step. Error in msbuild.log below. 

**Expected behavior**
Expected to build with no failures

**Logs/output**
cmake logs
verbose 
[mycmake-verbose.log](https://github.com/aws/aws-sdk-cpp/files/5295392/mycmake-verbose.log)
default output
[mycmake-default.log](https://github.com/aws/aws-sdk-cpp/files/5295393/mycmake-default.log)

msbuild logs
verbose 
[mymsbuild-verbose.log](https://github.com/aws/aws-sdk-cpp/files/5295396/mymsbuild-verbose.log)
default output
[mymsbuild-default.log](https://github.com/aws/aws-sdk-cpp/files/5295397/mymsbuild-default.log)

**Comment by KaibaLopez** [comment]
Hi @marcoherrerarendon ,
Before I go into this any deeper do you mind trying something for me:
I think there is a disparity between cmake and msbuild, can't remember which is which at the moment but I think cmake on default tries to do release where msbuild tries to do debug so.... could you either try:
`cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE=Debug -DBUILD_ONLY="s3" -DBUILD_SHARED_LIBS=ON` 
or 
`msbuild ALL_BUILD.vcxproj /property:Configuration=Release` or you could also try opening the .sln file and build on VS and just select the build type there.

Let me know if that helps or at least gets you to an error later on the build.

**Comment by marcoherrerarendon** [comment]
Hi @KaibaLopez , 
That was it. Thank you.  =)
