### ISSUE TITLE
CentOS7 build errors due to use of CURLOPT_XFERINFOFUNCTION (requires libcurl 7.32.0+)

### ISSUE THREAD

**Issue by gavllew** [aws/aws-sdk-cpp#1483]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Compile errors for undeclared references to CURLOPT_XFERINFOFUNCTION and CURLOPT_XFERINFODATA, which first appeared in libcurl 7.32.0.  A recent commit introduced these: 8eea6d3ef1bfbbf68ac296d3bab26fd705f494ee

The libcurl documentation suggests that CURLOPT_XFERINFOFUNCTION replaced CURLOPT_PROGRESSFUNCTION.

**SDK version number**
1.8.60

**Platform/OS/Hardware/Device**
CentOS 7.8 x86_64 (libcurl 7.29.0)

**To Reproduce (observed behavior)**
Attempt to compile the SDK on a CentOS 7 VM/container.

**Expected behavior**
Compiles successfully and unit/integration tests pass.

**Logs/output**
```
In file included from /home/rpmbuild/rpmbuild/BUILD/aws-sdk-cpp-1.8.60/aws-cpp-sdk-core/include/aws/core/http/curl/CurlHandleContainer.h:11,
                 from /home/rpmbuild/rpmbuild/BUILD/aws-sdk-cpp-1.8.60/aws-cpp-sdk-core/include/aws/core/http/curl/CurlHttpClient.h:11,
                 from /home/rpmbuild/rpmbuild/BUILD/aws-sdk-cpp-1.8.60/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp:6:
/home/rpmbuild/rpmbuild/BUILD/aws-sdk-cpp-1.8.60/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp: In member function 'virtual std::shared_ptr<Aws::Http::HttpResponse> Aws::Http::CurlHttpClient::MakeRequest(const std::shared_ptr<Aws::Http::HttpRequest>&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const':
/home/rpmbuild/rpmbuild/BUILD/aws-sdk-cpp-1.8.60/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp:659:52: error: 'CURLOPT_XFERINFOFUNCTION' was not declared in this scope; did you mean 'CURLOPT_WRITEFUNCTION'?
  659 |                 curl_easy_setopt(connectionHandle, CURLOPT_XFERINFOFUNCTION, CurlProgressCallback);
      |                                                    ^~~~~~~~~~~~~~~~~~~~~~~~
/home/rpmbuild/rpmbuild/BUILD/aws-sdk-cpp-1.8.60/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp:660:52: error: 'CURLOPT_XFERINFODATA' was not declared in this scope; did you mean 'CURLOPT_WRITEDATA'?
  660 |                 curl_easy_setopt(connectionHandle, CURLOPT_XFERINFODATA, &readContext);
      |                                                    ^~~~~~~~~~~~~~~~~~~~
```

**Additional context**
None

**Comment by KaibaLopez** [comment]
Hi @gavllew ,
I'm not sure if this would be considered a bug.... I guess we could be more specific on which are the required versions for things like curl or openssl.
Just to be sure though, you should only need to run `yum install libcurl-devel ` for the curl and openssl versions to match the sdk requirements. After doing that do you still face this problem?

**Comment by gavllew** [comment]
@KaibaLopez The `libcurl-devel` was installed before the build, but the CentOS7 package is only 7.29.0, which is not new enough for `CURLOPT_XFERINFOFUNCTION`.

You can certainly take the stance that minimum dependency versions are required, as long as those requirements are well documented.  Currently the only requirements mentioned are compiler versions.  I figured breaking the out-of-the-box build on a supported version of a major distro was probably unintentional.

There is already some handling in aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp of libcurl versions using the LIBCURL_VERSION_MAJOR/LIBCURL_VERSION_MINOR preprocessor definitions, so should be straightforward to continue to support older versions if that is indeed desirable.

**Comment by alanwevans** [comment]
**Disclaimer**: Not a CPP developer.

Looking at [CURLOPT_XFERINFOFUNCTION explained](https://curl.haxx.se/libcurl/c/CURLOPT_XFERINFOFUNCTION.html) and [CURLOPT_PROGRESSFUNCTION explained
](https://curl.haxx.se/libcurl/c/CURLOPT_PROGRESSFUNCTION.html) it would appear that while `CURLOPT_PROGRESSFUNCTION` is technically deprecated, that it is still completely valid.

As such I attempted a build simply swapping XFER for PROGRESS and was able to get a successful build where all of the built-in tests passed.  I don't think this is a proper solution though, the callback function signatures seem to be slightly different but I'm not sure if that matters here (not CPP dev).

There is though, an example in the curl source that shows how to support both the old and new APIs. [here](https://github.com/curl/curl/blob/efc696a2e09225bfeab4e7efea61a4e416d66cba/docs/examples/progressfunc.c#L86-L98) [and here](https://github.com/curl/curl/blob/efc696a2e09225bfeab4e7efea61a4e416d66cba/docs/examples/progressfunc.c#L113-L132)
