### ISSUE TITLE
Exhausting Memory on Raspberry Pi

### ISSUE THREAD

**Issue by tnorlund** [aws/aws-sdk-cpp#1484]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Raspberry Pi 4 - 4GB

**Describe the question**
I'd like to `make` this using a Raspberry Pi with 4GB of RAM. Is this possible? I've attempted using a swap file, but I still exhaust the memory while making this. Is there a way to do this? 

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```bash
pi@raspberrypi:~/aws-sdk-cpp/build $ make
...
[ 26%] Building CXX object aws-cpp-sdk-ec2/CMakeFiles/aws-cpp-sdk-ec2.dir/ub_EC2.cpp.o
virtual memory exhausted: Cannot allocate memory
make[2]: *** [aws-cpp-sdk-ec2/CMakeFiles/aws-cpp-sdk-ec2.dir/build.make:64: aws-cpp-sdk-ec2/CMakeFiles/aws-cpp-sdk-ec2.dir/ub_EC2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3863: aws-cpp-sdk-ec2/CMakeFiles/aws-cpp-sdk-ec2.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by KaibaLopez** [comment]
Hi @tnorlund ,
The full SDK might be too big for your raspberry pi, but you can try building only the services you need by adding the cmake flag `-DBUILD_ONLY` so, for example, let's say you want to use s3, dynamodb and transfer manager:
```
cmake <source_dir> -DBUILD_ONLY="s3;dynamodb;transfer"
make
```
Let me know if this helped, or if I misunderstood the question.

**Comment by tnorlund** [comment]
@KaibaLopez Thanks. That works fine.
