### ISSUE TITLE
DyanmoDB Data Type

### ISSUE THREAD

**Issue by tnorlund** [aws/aws-sdk-cpp#1490]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Raspbian / Raspberry Pi

**Describe the question**
I'm trying to use DynamoDB to store results from testing hardware. I've just installed the library, but I'm not sure how to store numbers in DynamoDB. How do I caste the numbers to Ints and Floats? 

```cpp
         /**
         *   Save the results of the test to DynamoDB.
         * 
         *   @param numImages The number of images the test saved to disk
         *   @param timeLength The amount of time to record frames for.
         */
        void saveResultToDynamoDB( int numImages, int timeLength ) {
            Aws::Client::ClientConfiguration clientConfig;
            Aws::DynamoDB::DynamoDBClient dynamoClient(clientConfig);
            Aws::DynamoDB::Model::PutItemRequest pir;
            // Caste strings
            std::string _dateTime = boost::lexical_cast<std::string>(
                getTimeInMiliseconds()
            );
            // Convert to AWS::String
            Aws::String dateTime(_dateTime.c_str(), _dateTime.size());
            Aws::String table_name(tableName.c_str(), tableName.size());
            // Set table name
            pir.SetTableName(table_name);
            // Set the key for the table row
            Aws::DynamoDB::Model::AttributeValue av;
            av.SetS(dateTime);
            pir.AddItem("id", av);
            // Set the different values for the row
            Aws::DynamoDB::Model::AttributeValue val;
            val.SetS(dateTime); pir.AddItem("dateTime", val);
            val.SetS(
                Aws::Number((endTime - startTime)/1000) // What do I do here???
            ); pir.AddItem("runTime", val);

            const Aws::DynamoDB::Model::PutItemOutcome result = dynamoClient.PutItem(pir);
            if (!result.IsSuccess())
            {
                std::cout << "bad result" << std::endl;
                std::cout << result.GetError().GetMessage() << std::endl;
            }
        }
```

**Comment by KaibaLopez** [comment]
Hi @tnorlund ,
So the way dynamodb works with the sdk is a bit complicated because typed variables, but in short, we have different methods to add different value types, for numeric simply change : `val.SetS()` for `val.SetN()`.
And if you want to know a bit more detail on how that works or what type of values it takes, take a look at [AttributeValue.h](https://github.com/aws/aws-sdk-cpp/blob/6d6dcdbfa377393306bf79585f61baea524ac124/aws-cpp-sdk-dynamodb/include/aws/dynamodb/model/AttributeValue.h).

Let me know if this helped you, or if I missed something.

**Comment by tnorlund** [comment]
@KaibaLopez Thanks. That was it!
