### ISSUE TITLE
Get operation on s3://foo/bar failed. curlCode: 77, Problem with the SSL CA cert

### ISSUE THREAD

**Issue by rvernica** [aws/aws-sdk-cpp#1491]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**

I receive the following error during an S3 get operation:
```
Get operation on s3://foo/bar failed. curlCode: 77, Problem with the SSL CA cert (path? access rights?).
```

**SDK version number**

`1.8.3`

**Platform/OS/Hardware/Device**

AWS instance, CentOS 7, cmake3, devtoolset-3, g++ 4.9.2

**To Reproduce (observed behavior)**

I compiled AWS S3 libraries on this system. If I try a simple program that just does a GET requests it works fine. Once I integrate this code in a larger library I get the error listed above. Both use the same AWS configuration and credentials.

The same code works fine on an Ubuntu Xenial distribution as part of the larger library.

The code is compiled and linked like this:
```
/opt/rh/devtoolset-3/root/usr/bin/g++ -DARROW_NO_DEPRECATED_API -DNDEBUG -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -Wall -Wextra -Wno-long-long -Wno-strict-aliasing -Wno-system-headers -Wno-unused -Wno-unused-parameter -Wno-variadic-macros -fPIC -fno-omit-frame-pointer -g -std=c++14 -DAWS_COMMON_USE_IMPORT_EXPORT -DAWS_EVENT_STREAM_USE_IMPORT_EXPORT -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=8 -DAWS_SDK_VERSION_PATCH=3 -DPROJECT_ROOT="/foo/bar" -I. -I"/foo/bar/include" -I"/foo/bar/3rdparty/boost/include" -I/opt/aws/include  -c -o foo.o foo.cpp

/opt/rh/devtoolset-3/root/usr/bin/g++ -DARROW_NO_DEPRECATED_API -DNDEBUG -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -Wall -Wextra -Wno-long-long -Wno-strict-aliasing -Wno-system-headers -Wno-unused -Wno-unused-parameter -Wno-variadic-macros -fPIC -fno-omit-frame-pointer -g -std=c++14 -DAWS_COMMON_USE_IMPORT_EXPORT -DAWS_EVENT_STREAM_USE_IMPORT_EXPORT -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=8 -DAWS_SDK_VERSION_PATCH=3 -DPROJECT_ROOT="/foo/bar" -I. -I"/foo/bar/include" -I"/foo/bar/3rdparty/boost/include" -I/opt/aws/include -o taz.so foo.o etc.o -shared -Wl,-soname,taz.so -L . -L "/foo/bar/3rdparty/boost/lib" -L "/foo/bar/lib" -Wl,-rpath,/foo/bar/lib -lm -larrow -rdynamic /opt/aws/lib64/libaws-cpp-sdk-s3.so -lm -lrt -ldl -Wl,-rpath,/opt/aws/lib64
```

**Comment by rvernica** [comment]
I enabled the AWS logging and got some interesting results. There are two GET requests made by my code, one after another. The first one succeeds while the second one fails. Here are the relevant log entries. The first, the successful, request:
```
[DEBUG] 2020-10-08 16:07:16.352 CURL [140352776283904] (Text) About to connect() to foo.s3.us-east-1.amazonaws.com port 443 (#0)
[DEBUG] 2020-10-08 16:07:16.352 CURL [140352776283904] (Text)   Trying 52.216.142.88...
[DEBUG] 2020-10-08 16:07:16.353 CURL [140352776283904] (Text) Connected to foo.s3.us-east-1.amazonaws.com (52.216.142.88) port 443 (#0)
[DEBUG] 2020-10-08 16:07:16.353 CURL [140352776283904] (Text) Initializing NSS with certpath: sql:/etc/pki/nssdb
[DEBUG] 2020-10-08 16:07:16.466 CURL [140352776283904] (Text)   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
[DEBUG] 2020-10-08 16:07:16.472 CURL [140352776283904] (Text) SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
[DEBUG] 2020-10-08 16:07:16.472 CURL [140352776283904] (Text) Server certificate:
[DEBUG] 2020-10-08 16:07:16.472 CURL [140352776283904] (Text)   subject: CN=s3.amazonaws.com,O="Amazon.com, Inc.",L=Seattle,ST=Washington,C=US
[DEBUG] 2020-10-08 16:07:16.472 CURL [140352776283904] (Text)   start date: Aug 04 00:00:00 2020 GMT
[DEBUG] 2020-10-08 16:07:16.472 CURL [140352776283904] (Text)   expire date: Aug 09 12:00:00 2021 GMT
[DEBUG] 2020-10-08 16:07:16.472 CURL [140352776283904] (Text)   common name: s3.amazonaws.com
[DEBUG] 2020-10-08 16:07:16.472 CURL [140352776283904] (Text)   issuer: CN=DigiCert Baltimore CA-2 G2,OU=www.digicert.com,O=DigiCert Inc,C=US
[DEBUG] 2020-10-08 16:07:16.472 CURL [140352776283904] (HeaderOut) GET /foo/bar HTTP/1.1
```
The second, the failed, request:
```
[DEBUG] 2020-10-08 16:07:16.502 CURL [140352776283904] (Text) About to connect() to foo.s3.us-east-1.amazonaws.com port 443 (#1)
[DEBUG] 2020-10-08 16:07:16.502 CURL [140352776283904] (Text)   Trying 52.216.142.88...
[DEBUG] 2020-10-08 16:07:16.503 CURL [140352776283904] (Text) Connected to foo.s3.us-east-1.amazonaws.com (52.216.142.88) port 443 (#1)
[DEBUG] 2020-10-08 16:07:16.503 CURL [140352776283904] (Text) Initializing NSS with certpath: sql:/etc/pki/nssdb
[DEBUG] 2020-10-08 16:07:16.566 CURL [140352776283904] (Text) Unable to initialize NSS database
[DEBUG] 2020-10-08 16:07:16.566 CURL [140352776283904] (Text) Initializing NSS with certpath: none
[DEBUG] 2020-10-08 16:07:16.569 CURL [140352776283904] (Text) Unable to initialize NSS
[DEBUG] 2020-10-08 16:07:16.569 CURL [140352776283904] (Text) Closing connection 1
[ERROR] 2020-10-08 16:07:16.569 CurlHttpClient [140352776283904] Curl returned error code 77 - Problem with the SSL CA cert (path? access rights?)
[DEBUG] 2020-10-08 16:07:16.569 CurlHandleContainer [140352776283904] Destroy curl handle: 0x7fa6480f79e0 and decrease pool size by 1.
[DEBUG] 2020-10-08 16:07:16.569 AWSClient [140352776283904] Request returned error. Attempting to generate appropriate error codes from response
[ERROR] 2020-10-08 16:07:16.569 AWSClient [140352776283904] HTTP response code: -1
```

**Comment by rvernica** [comment]
On CentOS 7, curl comes with NSS for SSL support:
```
> curl -V
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.44 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
```
I have compiled cURL from source. By default it gets compiled with OpenSSL for SSL support. I dynamically linked by program against the resulting `libcurl.so`. The AWS SDK libraries are still dynamically linked against system `libcurl.so`. Anyhow, my program works as expected now.

**Comment by KaibaLopez** [comment]
Hi @rvernica ,
I'm glad to see you've solved your issue, I'm a bit confused on what ended up being the source from the error though, was it that your initial cURL compilation did not support OpenSSL? Or the cURL/OpenSSL version?
Is there any problem still or is it safe to close this issue then?

**Comment by rvernica** [comment]
The cURL library that comes with CentOS 7 is compiled with NSS (*not* OpenSSL) for SSL. It seems that the AWS SDK does not work with NSS or triggers a bug in NSS.

It would be ideal if the AWS SDK would work with the cURL library that comes with CentOS 7. Otherwise, the **AWS SDK is not compatible with CentOS 7.**

The alternative is for the SDK user to compile the cURL library from source as it get compiled with OpenSSL. That works but now the user needs to manually install the custom-compiled cURL library.

I was not able the make the AWS SDK compile with cURL installed in my `/home` directory. `cmake` picks up the local cURL but does not pick it up correctly and header files and libraries are missing. So, the AWS SDK is still dynamically linked against the unsupported `libcurl`. To fix this, I dynamically linked my program against my custom `libcurl`.

If the AWS SDK is supported in CentOS 7 then this issue needs to be fixed or an work-around needs to be provided and documented.

**Comment by KaibaLopez** [comment]
Hi @rvernica ,
As an update on this, we are not going to make the SDK compatible with NSS, it just too much work and not really on our plans.
The rest of the problems you face are unrelated to the SDK though, it's all about cURL installation, this is a common thing when installing curl manually or when having various curl versions... as a work around you can always tell cmake where to find curl via the cmake flags `-DCURL_LIBRARY=<curl_lib_path> -DCURL_INCLUDE_DIR=<curl_include_path>`, same for openssl `-DOPENSSL_ROOT_DIR=<lib_path> -DOPENSSL_LIBRARIES=<include_path>`
Finally openssl is technically listed in the readme as a requirement [here](https://github.com/aws/aws-sdk-cpp#other-dependencies), but yea we could make that clearer.
I'll close this issue since I don't see any action that would be taken.

**Comment by rvernica** [comment]
Understood. It makes sense. Since CentOS/RHEL installations are fairly common, it would be nice to have an official workaround for this cURL/NSS issue.
