### ISSUE TITLE
Cant Build windows c++ SDK

### ISSUE THREAD

**Issue by POWER-KI** [aws/aws-sdk-cpp#1493]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
CMAKE fail buiding SDK for windows (32) 

**SDK version number**
1.18

**To Reproduce (observed behavior)**
Just try

**Logs/output**
Could NOT find Git (missing: GIT_EXECUTABLE) 
TARGET_ARCH not specified; inferring host OS to be platform compilation target
Building AWS libraries as shared objects
Generating windows build config
Building project version: 1.8.64
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.

-- The C compiler identification is MSVC 19.24.28319.0

-- The CXX compiler identification is MSVC 19.24.28319.0

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x86/cl.exe - skipped

-- Detecting C compile features

-- Detecting C compile features - done

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x86/cl.exe - skipped

-- Detecting CXX compile features

-- Detecting CXX compile features - done

CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/ExternalProject.cmake:2350 (message):

  error: could not find git for clone of AwsCCommon
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/ExternalProject.cmake:3206 (_ep_add_download_command)
  cmake/BuildAwsCCommon.cmake:39 (ExternalProject_Add)
  CMakeLists.txt:19 (include)

-- Configuring incomplete, errors occurred!

See also "C:/AWS/BUILD/.deps/CMakeFiles/CMakeOutput.log".

CMake Error at CMakeLists.txt:218 (message):
  Failed to configure third-party libraries.

Configuring incomplete, errors occurred!

**If I disable BUILD_DEPS I get:**

Could NOT find Git (missing: GIT_EXECUTABLE) 
TARGET_ARCH not specified; inferring host OS to be platform compilation target
Building AWS libraries as shared objects
Generating windows build config
Building project version: 1.8.64
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
The CXX compiler identification is MSVC 19.24.28319.0
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x86/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Encryption: Bcrypt
Http client: WinHttp
The C compiler identification is MSVC 19.24.28319.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x86/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Updating version info to 1.8.64
Custom memory management enabled; stl objects now using custom allocators
CMake Error at aws-cpp-sdk-core/CMakeLists.txt:496 (find_package):
  By not providing "Findaws-c-event-stream.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "aws-c-event-stream", but CMake did not find one.

  Could not find a package configuration file provided by
  "aws-c-event-stream" with any of the following names:

    aws-c-event-streamConfig.cmake
    aws-c-event-stream-config.cmake

  Add the installation prefix of "aws-c-event-stream" to CMAKE_PREFIX_PATH or
  set "aws-c-event-stream_DIR" to a directory containing one of the above
  files.  If "aws-c-event-stream" provides a separate development package or
  SDK, be sure it has been installed.

Configuring incomplete, errors occurred!
See also "C:/AWS/Build/CMakeFiles/CMakeOutput.log".

. . . . . . .
THANK You

**Comment by KaibaLopez** [comment]
Hi @POWER-KI ,
It seems like you don't have Git installed on your computer, can you verify that?

**Comment by POWER-KI** [comment]
Thank You, we did not have Git installed. 
I suggest AWS Team to add this requirement (GIT) as they have done with CMAKE, to the documentation.

**Comment by KaibaLopez** [comment]
Yea, surprisingly it's only come  to our attention very recently that we didn't list git as a requirement. 
Anyways, glad we got your issue figured out, I'll go ahead and close this as solved.
