### ISSUE TITLE
TransferManager DownloadFile with offset does not use the client's seek offset when Multipart download

### ISSUE THREAD

**Issue by lynchpancho** [aws/aws-sdk-cpp#1495]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
TransferManager's DownloadFile with fileOffset non zero has an issue that if the client seeks the stream to an offset, when the download kicks into the multipart mode, it will not stream into the client buffer at the position the client set but will stream into it with 0 offset

**SDK version number**
1.8.65

**Platform/OS/Hardware/Device**
windows

**To Reproduce (observed behavior)**
Download a file using transfer manager, set fileOffset to x
create a stream to file and seekg(x) to receive the data at an offset
works with DoSinglePartDownload
does not work with Multipart

**Expected behavior**

**Logs/output**

Possible fix?

```
        void TransferHandle::WritePartToDownloadStream(Aws::IOStream* partStream, std::size_t writeOffset)
        {
            std::lock_guard<std::mutex> lock(m_downloadStreamLock);

            if(m_downloadStream == nullptr)
            {
                m_downloadStream = m_createDownloadStreamFn();
                assert(m_downloadStream->good());
            }

#if 1 // fix?
            partStream->seekg(0);
            std::size_t pos = m_downloadStream->tellg();
            m_downloadStream->seekp(pos + writeOffset);
            (*m_downloadStream) << partStream->rdbuf();
            m_downloadStream->flush();
            m_downloadStream->seekg(pos);
#else
            partStream->seekg(0);
            m_downloadStream->seekp(writeOffset);
            (*m_downloadStream) << partStream->rdbuf();
            m_downloadStream->flush();
#endif
        }
```

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

**Comment by singku** [comment]
May I ask your use case why would you seek the stream when downloading an object?
SinglePartDownload doesn't have this problem because for single part download, SDK call `write` directly to the stream you provided (no seek)

**Comment by lynchpancho** [comment]
> May I ask your use case why would you seek the stream when downloading an object?
> SinglePartDownload doesn't have this problem because for single part download, SDK call `write` directly to the stream you provided (no seek)

@singku 

Our use case: 
We are downloading media from relatively large files stored in S3 on demand. To support random access in a timely manner for the end user we start downloading with an offset to the relevant content stored in S3 and write to the local file at the same offset.
