### ISSUE TITLE
Multi Arch build (arm64 x86_64) on MacOS to support ARM Mac Devices (Universal Binary)

### ISSUE THREAD

**Issue by Sunil-P** [aws/aws-sdk-cpp#1496]
Confirm by changing [x] to [] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Mac OS 10.15 Catalina, using Xcode12
**Describe the question**
Upcoming ARM Macs have following requirements to build to ensure universal compatibility.
https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary

I use the following command to build aws sdk (As an example, take into account only cognito and kinesis.
```
cmake -DBUILD_ONLY="cognito-identity;kinesis" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -G Xcode
xcodebuild -project AWSSDK.xcodeproj
```

The resulting .dylib files upon running Apple's compatibility checker, I get the following output
```
lipo libaws-cpp-sdk-access-management.dylib -archs
x86_64
```

My expectation was, it should show both x86_64 and arm64. Can anyone tell me why this is occurring. Perhaps apple's implementation is to build these two architectures separately and merge them together using the lipo tool. 

**Logs/output**
If applicable, add logs or error output.
None
To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
Hi @Sunil-P , sorry for the delayed response
I've tested this and you are right the arm64 build fails. It does so silently because cmake is happy to have x86_64 build and just ignores building arm. 
It seems to be related mostly to the sdk's dependencies, but we'll look more into it
thanks fro bringing this up to us.

**Comment by Sunil-P** [comment]
Any update on this, guys ? Anyone working on this

**Comment by Sunil-P** [comment]
Ive managed to build an arm version of my required libs, and managed to combine them using lipo tool.
As of this moment, Cmake is broken with latest version, use Cmake 3.18.4 to build aws. Homebrew can't downgrade, so if uve installed Cmake via home-brew, 
`brew remove Cmake
`
install via pip
`pip install Cmake
`
check Cmake version using 
`Cmake --version`

Rest of the build step

`git clone https://github.com/aws/aws-sdk-cpp
cd aws-sdk-cpp
cmake ../aws-sdk-cpp -G Xcode -DBUILD_ONLY="cognito-identity;kinesis" -DTARGET_ARCH="APPLE" -DCMAKE_OSX_ARCHITECTURES="arm64"
# I only build cognito and kinesis
xcodebuild -project AWSSDK.xcodeproj -target "aws-cpp-sdk-core" -target "aws-cpp-sdk-kinesis" -target "testing-resources" -target "aws-cpp-sdk-iam" -target "aws-cpp-sdk-access-management" -target "aws-cpp-sdk-cognito-identity" 

xcodebuild -project AWSSDK.xcodeproj -target "aws-cpp-sdk-core" -target "aws-cpp-sdk-kinesis" -target "testing-resources" -target "aws-cpp-sdk-iam" -target "aws-cpp-sdk-access-management" -target "aws-cpp-sdk-cognito-identity" -configuration Release
mkdir -p ~/aws-libs/arm/{Debug,Release}
find -f ./**/Debug/** -name "*.dylib" -exec cp {} ~/aws-libs/arm/Debug \;
find -f ./**/Release/** -name "*.dylib" -exec cp {} ~/aws-libs/arm/Release \;

`
