### ISSUE TITLE
How to Create the "Log Group" and Log Stream from AWS SDk using c++ ?

### ISSUE THREAD

**Issue by latapankaj** [aws/aws-sdk-cpp#1500]
**Platform/OS/Hardware/Device**
Windows

**Describe the question**
I want to create  the "Log Group" and Log Stream from AWS SDk using c++  but not getting how to call the function "CreateLogGroup" and "CreateLogStream".

```

**Comment by KaibaLopez** [comment]
Hi @latapankaj ,
So, we are missing samples on this but you can always take a look at the [logs integration tests](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-logs-integration-tests/CloudWatchLogsTests.cpp) for inspiration.
But here is a real quick sample, probably with some typos so feel free to modify it: 
* For the log group it'd look something like
```
void CreateLogsGroup(const Aws::String& groupName){
    Aws::CloudWatchLogs::Model::CreateLogGroupRequest createRequest;
    createRequest.SetLogGroupName(groupName);
    auto createOutcome = m_client->CreateLogGroup(createRequest);
}
```
* For stream it would look something like:
```
void CreateLogStream(const Aws::String& groupName, const Aws::String& streamName){
    Aws::CloudWatchLogs::Model::CreateLogStreamRequest createStreamRequest;
    createStreamRequest.WithLogGroupName(groupName)
                                       .WithLogStreamName(streamName);
    auto createStreamOutcome = m_client->CreateLogStream(createStreamRequest);
}
```
Hope this helps.

**Comment by latapankaj** [comment]
Hi @KaibaLopez 
Your suggestion resolved my issues.
I have used the class   CreateLogGroupRequest and CreateLogStreamRequest to cretae the LogGroup and LogStream  and  it is working fine.

Thanks!!
