### ISSUE TITLE
Sporadic crashes from `InitAPI()` and `ShutdownAPI()`

### ISSUE THREAD

**Issue by mycpuorg** [aws/aws-sdk-cpp#1502]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
**Context:** Issue found deals around `InitAPI` and `ShutdownAPI`, previously reported here https://github.com/aws/aws-sdk-cpp/issues/1050 and other issues allude to this requirement.
However, this issue is not specific to Windows (I am testing on Ubuntu 18.04 DL AMI EC2 instance)
We are using Google Test as a framework to run unit and integration tests for our application which uses AWS SDK for S3 transactions.

The Test Suite for Unit and Integration tests have their own `main()` function.
We would like to reuse a function defined within a common header included across all test suites to perform the `InitAPI()` and `ShutdownAPI()` calls. This causes sporadic segmentation faults in the application while running these test suites.

**SDK version number**
Latest

**Platform/OS/Hardware/Device**
Ubuntu 18.04/20.04 DL AMI instance on EC2

**To Reproduce (observed behavior)**

**Expected behavior**
No crashes.

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

**Comment by singku** [comment]
Can you provide a reproducible code?

**Comment by jweinst1** [comment]
Are you accessing any s3 calls or AWS calls prior to calling `InitAPI` ?

**Comment by mycpuorg** [comment]
@jweinst1 Yes, among other things.

**Comment by jweinst1** [comment]
In my experience you should call InitAPI in a thread safe singleton , such as a `static` lambda, that way it only needs to get called once, or call it at the beginning of `main()`. Then call `ShutdownAPI` at the end of `main()`. Thats how i solved the problems in my code at least.

**Comment by KaibaLopez** [comment]
@mycpuorg, @jweinst1  is correct, InitAPI and ShutdownAPI should be called once and only once, so it would make sense to enforce that by having them called on a singleton or at the main function.
If you're already doing that, we still need the code to reproduce this if we are to continue investigating.
