### ISSUE TITLE
Memory check of Aws::InitAPI

### ISSUE THREAD

**Issue by ToBeMyOwnHero** [aws/aws-sdk-cpp#1503]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
When I use valgrind to check my project, I find got this:
==9378== Memcheck, a memory error detector
==9378== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==9378== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==9378== Command: ./aws
==9378== 
==9378== 
==9378== HEAP SUMMARY:
==9378==     in use at exit: 92,629 bytes in 2,876 blocks
==9378==   total heap usage: 3,088 allocs, 212 frees, 134,052 bytes allocated
==9378== 
==9378== LEAK SUMMARY:
==9378==    definitely lost: 0 bytes in 0 blocks
==9378==    indirectly lost: 0 bytes in 0 blocks
==9378==      possibly lost: 0 bytes in 0 blocks
==9378==    still reachable: 92,629 bytes in 2,876 blocks
==9378==         suppressed: 0 bytes in 0 blocks
==9378== Rerun with --leak-check=full to see details of leaked memory
==9378== 
==9378== For lists of detected and suppressed errors, rerun with: -s
==9378== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

And, I want to know that the result would have serious consequences.

**SDK version number**

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Linux localhost 3.10.0-693.el7.x86_64
CentOS Linux release 7.4.1708 (Core) 

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

This is my project:

#include <aws/core/Aws.h>

int main()

{
    
    Aws::SDKOptions options;
    
    Aws::InitAPI(options);
    
    Aws::ShutdownAPI(options);
    
    return 0;

}

I just use "valgrind ./myproject".

**Expected behavior**
I expected the LEAK SUMMARY is clearly.

==9378== Memcheck, a memory error detector
==9378== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==9378== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==9378== Command: ./aws
==9378== 
==9378== 
==9378== HEAP SUMMARY:
==9378==     in use at exit: 0 bytes in 0 blocks
==9378==   total heap usage: 3,088 allocs, 3088 frees, 134,052 bytes allocated
==9378== 
==9378== LEAK SUMMARY:
==9378==    definitely lost: 0 bytes in 0 blocks
==9378==    indirectly lost: 0 bytes in 0 blocks
==9378==      possibly lost: 0 bytes in 0 blocks
==9378==    still reachable: 0 bytes in 0 blocks
==9378==         suppressed: 0 bytes in 0 blocks
==9378== Rerun with --leak-check=full to see details of leaked memory
==9378== 
==9378== For lists of detected and suppressed errors, rerun with: -s
==9378== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @ToBeMyOwnHero ,
Yea this is not a real problem, "still reachable" while arguably still can be considered a "memory leak" it does not cause any of the potential problems that a more, say, traditional memory leak like "unfreed memory" would. In short, it is safe.

And if you want to read more on this, I liked this [stackoverflow explanation](https://stackoverflow.com/a/3857638) on the difference, or you can also look at the [Valgrind FAQ on the subject](https://www.valgrind.org/docs/manual/faq.html#faq.deflost), also [here](https://www.valgrind.org/docs/manual/faq.html#faq.reports).
Hope this clears things up for you.
