### ISSUE TITLE
transcribestream asserts in EventStreamDecoder. assert(handler->IsMessageCompleted());

### ISSUE THREAD

**Issue by Ri0n** [aws/aws-sdk-cpp#1504]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [+] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [+] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
transcribestream on destruction stops decoding event stream properly

**SDK version number**
1.8.52  (I haven't tried newer versions because they do not pass curl unit test)

**Platform/OS/Hardware/Device**
Ubuntu 20.04 on HP EliteBook 850 G6

**To Reproduce (observed behavior)**
1. Start multiple transcribestreams in parallel (create TranscribeStreamingServiceClient for each).
2. Send some audio to all of them.
3. Start deinitializating the streams one by one with a code similar to
```
    auto stream = request_.GetAudioStream();
    if (stream)
    {
        stream->WriteAudioEvent({});
        stream->flush();
        stream->Close();
    }
```
Then for each stream when response handler callback has triggered, destroy TranscribeStreamingServiceClient instance.

**Expected behavior**
The event message is properly validated no causing any crash.

**Logs/output**
[locals.txt](https://github.com/aws/aws-sdk-cpp/files/5403887/locals.txt)
[stack.txt](https://github.com/aws/aws-sdk-cpp/files/5403888/stack.txt)
```
2020-10-19T20:14:28.029606 [debug] ThreadID=rs0/0x00007f63a53ff700 TYPE:aws_logger AWSAuthEventStreamV4Signer=Event chunk final signature - 992a8ae5b34370371dd740421f2bb7c89b7cbf62d10f41d2827aef455ac24dda
2020-10-19T20:14:28.099484 [debug] ThreadID=0x00007f6399fff700 TYPE:get_message_from_aws text=It looks not so good at explaining from work so I can try and invoke.
mediaserver: /aws-sdk-cpp/aws-cpp-sdk-core/source/utils/event/EventStreamDecoder.cpp:85: static void Aws::Utils::Event::EventStreamDecoder::onPayloadSegment(aws_event_stream_streaming_decoder*, aws_byte_buf*, int8_t, void*): Assertion `handler->IsMessageCompleted()' failed.
```
More logs will be available later (next time I catch it).
It's not 100% reproducible but still quite often.

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @Ri0n ,
I'll take a look at this, but as you can see I'm a bit swamped on issues so, to make things move faster, could you provide minimal working sample code that (even if only sometimes) reproduces this bug?

**Comment by Ri0n** [comment]
@KaibaLopez, I could give you the original src which is pretty much minimal but it's under NDA. (at least it shouldn't be disclosed here).
I'll try to figure out something.
