### ISSUE TITLE
S3 URI parser

### ISSUE THREAD

**Issue by dvirtz** [aws/aws-sdk-cpp#1507]
**Is your feature request related to a problem? Please describe.**
I'd like to parse S3 URI to get region, bucket, etc.

**Describe the solution you'd like**
A parser API like in [.NET](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TS3Uri.html) and [Java](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3URI.html)

**Describe alternatives you've considered**
I can parse it manually but it might break sometime.

**Comment by KaibaLopez** [comment]
Hi @dvirtz ,
This sounds like a reasonable enough feature request, I just don't know when we could get around to making it happen, we do take PRs though, in case you already have an idea on how to implement it.

**Comment by dvirtz** [comment]
My idea is to reuse the parsing from [Http::URI](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/http/URI.cpp) class and copy the other logic from the .NET and Java implementations. Does that sound ok?

**Comment by KaibaLopez** [comment]
sounds good to me, could you try making a pr so we can review it?

**Comment by dvirtz** [comment]
started a PR at https://github.com/aws/aws-sdk-cpp/pull/1523

**Comment by ajaybhargavb** [comment]
@KaibaLopez any update on this? Almost every other language AWS Sdk contains this utility. I don't understand why the cpp sdk is lagging so far behind.

**Comment by jmklix** [comment]
This is not something we plan on adding to the sdk. I would suggest using regex for this
