### ISSUE TITLE
Linking error on Windows (both with VS 2013 and 2015)

### ISSUE THREAD

**Issue by epot** [aws/aws-sdk-cpp#151]
Hello,

I built the awscppsdk with Cmake and Visual Studio (tried with both 2013 and 2015 versions) sucessfully. I am trying to build an executable using it. If I only use methods to upload to S3, it works fine (meaning the putObjectRequest). But as soon as I add this line:

Aws::S3::Model::GetObjectRequest getObjectRequest;

I get a linking error:

bla.obj : error LNK2001: unresolved external symbol "char const * const Aws::Http::CONTENT_TYPE_HEADER" (?CONTENT_TYPE_HEADER@Http@Aws@@3PEBDEB)

My executable is linking against aws-cpp-sdk-s3.lib and aws-cpp-sdk-core.lib.

Any idea ?

Cheers,
Emmanuel

**Comment by dkislov** [comment]
I experienced the same link error in Visual Studio 2013. Still trying to find solution... Could someone input to that issue?

**Comment by epot** [comment]
FYI I am now compiling in static mode and things work fine.

**Comment by JonathanHenson** [comment]
@epot what changed that it started working?

**Comment by epot** [comment]
Sorry for the close and re-open, that was a misclick :-). I am compiling in static mode now and do not have this issue anymore. But it would be good to have the possibility to use the library in dynamic mode on windows !

**Comment by JonathanHenson** [comment]
We don't have this issue on VS 2013 or VS 2015 for our builds, could you show me how you are building and also which version of the SDK you were using?

**Comment by epot** [comment]
I was told to use the head a while ago because of another issue (https://github.com/aws/aws-sdk-cpp/issues/134). I am still using the head of that time, which was starting by b216290. I will try with the latest now to check if my issue has been fixed.

**Comment by epot** [comment]
Argl I misclicked again...

**Comment by epot** [comment]
I still have the same issue with the latest revision of the repository, sorry :-(. I am building with absolutely no parameters with cmake (just  -G "Visual Studio 12 2013 Win64"). And then I have a C++ program trying to link against aws-cpp-sdk-s3.lib and aws-cpp-sdk-core.lib. 
I just noticed that it actually works in Release mode, but not in RelWithDebInfo (coming from a default cmake).

**Comment by dkislov** [comment]
Hello , I solved issue in this way:
Building:
=======
mkdir build
cd build
cmake .. -G "Visual Studio 12 Win64" -DBUILD_ONLY="aws-cpp-sdk-transfer" -DCUSTOM_MEMORY_MANAGEMENT=0 -DSTATIC_LINKING=0
Using:
======
I link aws-cpp-sdk-transfer.dll, aws-cpp-sdk-s3.dll, aws-cpp-sdk-core.dll to my custom DLL project in my VS solutionand setup these preprocessor variables in my DLL project:
AWS_SDK_PLATFORM_WINDOWS
ENABLE_WINDOWS_CLIENT
ENABLE_BCRYPT_ENCRYPTION
USE_IMPORT_EXPORT
AWS_S3_EXPORTS

That's all, issue solved

**Comment by JonathanHenson** [comment]
If you use CMake to configure your application then you can use our targets file and it will make this much less painful. Glad you got it solved.

**Comment by ehosseini** [comment]
I have the same exact problem... recompiled the project using the instructions that **dkislov** posted, and that didn't solve the problem. 

I noticed a weird behavior while trying to instantiate Aws::Route53Domains::Model::GetDomainDetailRequest object using the new operator... the weird behavior is that now the code compiles and runs without any complaint.

I was wondering if anyone knows why? I have copied the two lines of code below.

**The following line of code doesn't run and gives the same error message posted above:**
`Aws::Route53Domains::Model::GetDomainDetailRequest dmreq2;`

> 1>------ Build started: Project: CAPP1, Configuration: Release x64 ------
1>  CAPP1.cpp
1>CAPP1.obj : error LNK2001: unresolved external symbol "char const * const Aws::Http::CONTENT_TYPE_HEADER" (?CONTENT_TYPE_HEADER@Http@Aws@@3PEBDEB)
1>C:\Projects\CAPP1\x64\Release\CAPP1.exe : fatal error LNK1120: 1 unresolved externals
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**This one works though:**
`auto dmreq= Aws::MakeShared<Aws::Route53Domains::Model::GetDomainDetailRequest>(ALLOCATION_TAG);
dmreq->SetDomainName("abc.com");`

**Comment by chebz** [comment]
If anyone still running into this problem, make sure **preprocessor variables are defined** as @dkislov mentioned. Have a look at dynamoDbIntegrationTests project for reference:
WIN32
_WINDOWS
_DEBUG
USE_IMPORT_EXPORT
ENABLE_WINDOWS_CLIENT
ENABLE_BCRYPT_ENCRYPTION
JSON_USE_EXCEPTION=0
GTEST_LINKED_AS_SHARED_LIBRARY=1
CMAKE_INTDIR="Debug"

**Comment by benny515** [comment]
For those who are having the same problem on debug mode, I got it solved with **dkislov**'s solution.
I am using Qt with VS2013, below is how my .pro file looks like.

CONFIG(release, debug|release) {
    #RELEASE
} else {
    #DEBUG
    DEFINES += AWS_SDK_PLATFORM_WINDOWS \
            ENABLE_WINDOWS_CLIENT \
            ENABLE_BCRYPT_ENCRYPTION \
            USE_IMPORT_EXPORT \
            AWS_S3_EXPORTS
}

INCLUDEPATH += "E:\AWS\aws-sdk-cpp-master\aws-cpp-sdk-core\include" \
               "E:\AWS\aws-sdk-cpp-master\aws-cpp-sdk-s3\include"

win32: LIBS += -L$$PWD/../../aws-sdk-cpp-build/aws-cpp-sdk-core/Debug/ -laws-cpp-sdk-core \
               -L$$PWD/../../aws-sdk-cpp-build/aws-cpp-sdk-s3/Debug/ -laws-cpp-sdk-s3 \
               -L$$PWD/../../aws-sdk-cpp-build/aws-cpp-sdk-transfer/Debug/ -laws-cpp-sdk-transfer


Thanks,

Ben

**Comment by dkislov** [comment]
> Even using @dkislov 's solution it promotes other build errors like:
> error LNK2001: unresolved external symbol "__declspec(dllimport) public: class std::basic_istream<char,struct std::char_traits > & __cdecl std::basic_istream<char,struct std::char_traits >::putback(char)" (__imp_?putback@?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAAEAV12@D@Z)
> 1>main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class std::basic_istream<char,struct std::char_traits > & __cdecl std::basic_istream<char,struct std::char_traits >::unget(void)" (__imp_?unget@?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAAEAV12@XZ)

For VS 2017 it is much more easier to get appropriate AWS SDK Nuget package. It takes latest stable version of libraries and setup in right way all VS targets files

**Comment by LazzariPaolo** [comment]
I am using VS 2017 and I am trying to use the latest version of the SDK. I run into the same error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "void __cdecl Aws::InitAPI(struct Aws::SDKOptions const &)" (?InitAPI@Aws@@YAXABUSDKOptions@1@@Z) referenced in function _main	ProjectFinal	C:\Users\paolol\source\repos\ProjectFinal\ProjectFinal\Source.obj	1
