### ISSUE TITLE
Error when calling WriteRecord in Timestream-Write

### ISSUE THREAD

**Issue by Dashing-Nelson** [aws/aws-sdk-cpp#1510]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Hello, when I am trying to call WriteRecordsRequest of Timestream-write, I face an error saying 404. But when I do 

```
        cconfig.endpointOverride = "ingest-cell2.timestream.us-east-1.amazonaws.com";
```
It works fines. I know I can do this, but what if in the future the link changes then? My API will stop working.
**SDK version number**
1.8
**Platform/OS/Hardware/Device**
What are you running the sdk on?
Ubuntu 20.10
**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
Does not work (Returns 404 status code)
```
Aws::Client::ClientConfiguration cconfig;
        clientConfiguration = cconfig;
        TimestreamWriteClient timestreamWriteClient(cconfig);
        WriteRecordsRequest writeRecordsRequest = WriteRecordsRequest();
        writeRecordsRequest.SetDatabaseName(databaseName);
        writeRecordsRequest.SetTableName(tableName);
        writeRecordsRequest.AddRecords(*records);
        Aws::TimestreamWrite::Model::WriteRecordsOutcome writeRecordsOutcome = timestreamWriteClient.WriteRecords(writeRecordsRequest);
```

Works like a charm
```
Aws::Client::ClientConfiguration cconfig;
        clientConfiguration = cconfig;
        cconfig.endpointOverride = "ingest-cell2.timestream.us-east-1.amazonaws.com";
        TimestreamWriteClient timestreamWriteClient(cconfig);
        WriteRecordsRequest writeRecordsRequest = WriteRecordsRequest();
        writeRecordsRequest.SetDatabaseName(databaseName);
        writeRecordsRequest.SetTableName(tableName);
        writeRecordsRequest.AddRecords(*records);
        Aws::TimestreamWrite::Model::WriteRecordsOutcome writeRecordsOutcome = timestreamWriteClient.WriteRecords(writeRecordsRequest);
```

**Expected behavior**
Success (200)

**Logs/output**

[INFO] 2020-11-09 11:23:49.771 Aws_Init_Cleanup [140258397099904] Initiate AWS SDK for C++ with Version:1.8.79
[TRACE] 2020-11-09 11:23:49.771 FileSystemUtils [140258397099904] Checking HOME for the home directory.
[DEBUG] 2020-11-09 11:23:49.771 FileSystemUtils [140258397099904] Environment value for variable HOME is /home/nelson
[DEBUG] 2020-11-09 11:23:49.771 FileSystemUtils [140258397099904] Home directory is missing the final / appending one to normalize
[DEBUG] 2020-11-09 11:23:49.771 FileSystemUtils [140258397099904] Final Home Directory is /home/nelson/
[INFO] 2020-11-09 11:23:49.771 Aws::Config::AWSConfigFileProfileConfigLoader [140258397099904] Initializing config loader against fileName /home/nelson/.aws/credentials and using profilePrefix = 0
[TRACE] 2020-11-09 11:23:49.771 FileSystemUtils [140258397099904] Checking HOME for the home directory.
[DEBUG] 2020-11-09 11:23:49.771 FileSystemUtils [140258397099904] Environment value for variable HOME is /home/nelson
[DEBUG] 2020-11-09 11:23:49.771 FileSystemUtils [140258397099904] Home directory is missing the final / appending one to normalize
[DEBUG] 2020-11-09 11:23:49.771 FileSystemUtils [140258397099904] Final Home Directory is /home/nelson/
[INFO] 2020-11-09 11:23:49.771 Aws::Config::AWSConfigFileProfileConfigLoader [140258397099904] Initializing config loader against fileName /home/nelson/.aws/config and using profilePrefix = 1
[TRACE] 2020-11-09 11:23:49.771 FileSystemUtils [140258397099904] Checking HOME for the home directory.
[DEBUG] 2020-11-09 11:23:49.771 FileSystemUtils [140258397099904] Environment value for variable HOME is /home/nelson
[DEBUG] 2020-11-09 11:23:49.771 FileSystemUtils [140258397099904] Home directory is missing the final / appending one to normalize
[DEBUG] 2020-11-09 11:23:49.771 FileSystemUtils [140258397099904] Final Home Directory is /home/nelson/
[DEBUG] 2020-11-09 11:23:49.771 Aws::Config::ConfigFileProfileFSM [140258397099904] found profile default
[DEBUG] 2020-11-09 11:23:49.771 Aws::Config::ConfigFileProfileFSM [140258397099904] found access key *****************************
[INFO] 2020-11-09 11:23:49.771 Aws::Config::AWSProfileConfigLoader [140258397099904] Successfully reloaded configuration.
[TRACE] 2020-11-09 11:23:49.771 Aws::Config::AWSProfileConfigLoader [140258397099904] reloaded config at 2020-11-09T11:23:49Z
[TRACE] 2020-11-09 11:23:49.771 FileSystemUtils [140258397099904] Checking HOME for the home directory.
[DEBUG] 2020-11-09 11:23:49.772 FileSystemUtils [140258397099904] Environment value for variable HOME is /home/nelson
[DEBUG] 2020-11-09 11:23:49.772 FileSystemUtils [140258397099904] Home directory is missing the final / appending one to normalize
[DEBUG] 2020-11-09 11:23:49.772 FileSystemUtils [140258397099904] Final Home Directory is /home/nelson/
[DEBUG] 2020-11-09 11:23:49.772 Aws::Config::ConfigFileProfileFSM [140258397099904] found profile default
[DEBUG] 2020-11-09 11:23:49.772 Aws::Config::ConfigFileProfileFSM [140258397099904] found region us-east-1
[INFO] 2020-11-09 11:23:49.772 Aws::Config::AWSProfileConfigLoader [140258397099904] Successfully reloaded configuration.
[TRACE] 2020-11-09 11:23:49.772 Aws::Config::AWSProfileConfigLoader [140258397099904] reloaded config at 2020-11-09T11:23:49Z
[INFO] 2020-11-09 11:23:49.773 CurlHttpClient [140258397099904] Initializing Curl library with version: 7.69.1, ssl version: OpenSSL/1.1.1f
[DEBUG] 2020-11-09 11:23:49.773 ClientConfiguration [140258397099904] ClientConfiguration will use SDK Auto Resolved profile: [default] if not specified by users.
[WARN] 2020-11-09 11:23:49.773 ClientConfiguration [140258397099904] Retry Strategy will use the default max attempts.
[INFO] 2020-11-09 11:23:49.773 EC2MetadataClient [140258397099904] Creating AWSHttpResourceClient with max connections 2 and scheme http
[INFO] 2020-11-09 11:23:49.773 CurlHandleContainer [140258397099904] Initializing CurlHandleContainer with size 2
[DEBUG] 2020-11-09 11:23:49.774 ClientConfiguration [140258397099904] ClientConfiguration will use SDK Auto Resolved profile: [default] if not specified by users.
[WARN] 2020-11-09 11:23:49.774 ClientConfiguration [140258397099904] Retry Strategy will use the default max attempts.
[DEBUG] 2020-11-09 11:23:49.774 ClientConfiguration [140258397099904] ClientConfiguration will use SDK Auto Resolved profile: [default] if not specified by users.
[WARN] 2020-11-09 11:23:49.774 ClientConfiguration [140258397099904] Retry Strategy will use the default max attempts.
[DEBUG] 2020-11-09 11:23:49.774 ClientConfiguration [140258397099904] ClientConfiguration will use SDK Auto Resolved profile: [default] if not specified by users.
[WARN] 2020-11-09 11:23:49.774 ClientConfiguration [140258397099904] Retry Strategy will use the default max attempts.
[TRACE] 2020-11-09 11:23:49.774 FileSystemUtils [140258397099904] Checking HOME for the home directory.
[DEBUG] 2020-11-09 11:23:49.774 FileSystemUtils [140258397099904] Environment value for variable HOME is /home/nelson
[DEBUG] 2020-11-09 11:23:49.774 FileSystemUtils [140258397099904] Home directory is missing the final / appending one to normalize
[DEBUG] 2020-11-09 11:23:49.774 FileSystemUtils [140258397099904] Final Home Directory is /home/nelson/
[INFO] 2020-11-09 11:23:49.774 Aws::Config::AWSConfigFileProfileConfigLoader [140258397099904] Initializing config loader against fileName /home/nelson/.aws/credentials and using profilePrefix = 0
[TRACE] 2020-11-09 11:23:49.774 FileSystemUtils [140258397099904] Checking HOME for the home directory.
[DEBUG] 2020-11-09 11:23:49.774 FileSystemUtils [140258397099904] Environment value for variable HOME is /home/nelson
[DEBUG] 2020-11-09 11:23:49.774 FileSystemUtils [140258397099904] Home directory is missing the final / appending one to normalize
[DEBUG] 2020-11-09 11:23:49.774 FileSystemUtils [140258397099904] Final Home Directory is /home/nelson/
[TRACE] 2020-11-09 11:23:49.774 FileSystemUtils [140258397099904] Checking HOME for the home directory.
[DEBUG] 2020-11-09 11:23:49.774 FileSystemUtils [140258397099904] Environment value for variable HOME is /home/nelson
[DEBUG] 2020-11-09 11:23:49.774 FileSystemUtils [140258397099904] Home directory is missing the final / appending one to normalize
[DEBUG] 2020-11-09 11:23:49.774 FileSystemUtils [140258397099904] Final Home Directory is /home/nelson/
[INFO] 2020-11-09 11:23:49.774 ProfileConfigFileAWSCredentialsProvider [140258397099904] Setting provider to read credentials from /home/nelson/.aws/credentials for credentials file and /home/nelson/.aws/config for the config file , for use with profile default
[INFO] 2020-11-09 11:23:49.774 ProcessCredentialsProvider [140258397099904] Setting process credentials provider to read config from default
[WARN] 2020-11-09 11:23:49.774 STSAssumeRoleWithWebIdentityCredentialsProvider [140258397099904] Token file must be specified to use STS AssumeRole web identity creds provider.
[DEBUG] 2020-11-09 11:23:49.774 DefaultAWSCredentialsProviderChain [140258397099904] The environment variable value AWS_CONTAINER_CREDENTIALS_RELATIVE_URI is 
[DEBUG] 2020-11-09 11:23:49.774 DefaultAWSCredentialsProviderChain [140258397099904] The environment variable value AWS_CONTAINER_CREDENTIALS_FULL_URI is 
[DEBUG] 2020-11-09 11:23:49.774 DefaultAWSCredentialsProviderChain [140258397099904] The environment variable value AWS_EC2_METADATA_DISABLED is 
[DEBUG] 2020-11-09 11:23:49.774 ClientConfiguration [140258397099904] ClientConfiguration will use SDK Auto Resolved profile: [default] if not specified by users.
[WARN] 2020-11-09 11:23:49.774 ClientConfiguration [140258397099904] Retry Strategy will use the default max attempts.
[INFO] 2020-11-09 11:23:49.774 EC2MetadataClient [140258397099904] Creating AWSHttpResourceClient with max connections 2 and scheme http
[INFO] 2020-11-09 11:23:49.774 CurlHandleContainer [140258397099904] Initializing CurlHandleContainer with size 2
[INFO] 2020-11-09 11:23:49.774 InstanceProfileCredentialsProvider [140258397099904] Creating Instance with default EC2MetadataClient and refresh rate 300000
[INFO] 2020-11-09 11:23:49.774 DefaultAWSCredentialsProviderChain [140258397099904] Added EC2 metadata service credentials provider to the provider chain.
[DEBUG] 2020-11-09 11:23:49.774 Aws::Config::ConfigFileProfileFSM [140258397099904] found profile default
[DEBUG] 2020-11-09 11:23:49.774 Aws::Config::ConfigFileProfileFSM [140258397099904] found access key *******************
[INFO] 2020-11-09 11:23:49.774 Aws::Config::AWSProfileConfigLoader [140258397099904] Successfully reloaded configuration.
[TRACE] 2020-11-09 11:23:49.774 Aws::Config::AWSProfileConfigLoader [140258397099904] reloaded config at 2020-11-09T11:23:49Z
[INFO] 2020-11-09 11:23:49.774 CurlHandleContainer [140258397099904] Initializing CurlHandleContainer with size 25
[TRACE] 2020-11-09 11:23:49.774 AWSClient [140258397099904] Found body, but content-length has not been set, attempting to compute content-length
[DEBUG] 2020-11-09 11:23:49.774 AWSAuthV4Signer [140258397099904] Calculated sha256 7a9b3d4ae148c7e575f5d935720052da5c06609722f069f14378b30426719564 for payload.
[DEBUG] 2020-11-09 11:23:49.774 AWSAuthV4Signer [140258397099904] Canonical Header String: amz-sdk-invocation-id:184F67F5-0FB1-487F-A818-9F29A72916E9
amz-sdk-request:attempt=1
content-length:344
content-type:application/x-amz-json-1.0
host:ingest.timestream.us-east-1.amazonaws.com
x-amz-api-version:2018-11-01
x-amz-content-sha256:7a9b3d4ae148c7e575f5d935720052da5c06609722f069f14378b30426719564
x-amz-date:20201109T112349Z
x-amz-target:Timestream_20181101.WriteRecords

[DEBUG] 2020-11-09 11:23:49.774 AWSAuthV4Signer [140258397099904] Signed Headers value:amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-api-version;x-amz-content-sha256;x-amz-date;x-amz-target
[DEBUG] 2020-11-09 11:23:49.774 AWSAuthV4Signer [140258397099904] Canonical Request String: POST
/

amz-sdk-invocation-id:184F67F5-0FB1-487F-A818-9F29A72916E9
amz-sdk-request:attempt=1
content-length:344
content-type:application/x-amz-json-1.0
host:ingest.timestream.us-east-1.amazonaws.com
x-amz-api-version:2018-11-01
x-amz-content-sha256:7a9b3d4ae148c7e575f5d935720052da5c06609722f069f14378b30426719564
x-amz-date:20201109T112349Z
x-amz-target:Timestream_20181101.WriteRecords

amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-api-version;x-amz-content-sha256;x-amz-date;x-amz-target
7a9b3d4ae148c7e575f5d935720052da5c06609722f069f14378b30426719564
[DEBUG] 2020-11-09 11:23:49.774 AWSAuthV4Signer [140258397099904] Final String to sign: AWS4-HMAC-SHA256
20201109T112349Z
20201109/us-east-1/timestream/aws4_request
fb11a0f23055875a8a60d5bdf9bc4a7b97c43b46b6347ac102ff6008568d18df
[DEBUG] 2020-11-09 11:23:49.775 AWSAuthV4Signer [140258397099904] Final computed signing hash: bdd9152188bff03ac7f9732360db328794f55e3fd143923bed90e36e4a1fad9b
[DEBUG] 2020-11-09 11:23:49.775 AWSAuthV4Signer [140258397099904] Signing request with: AWS4-HMAC-SHA256 Credential=*******************/20201109/us-east-1/timestream/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-api-version;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=bdd9152188bff03ac7f9732360db328794f55e3fd143923bed90e36e4a1fad9b
[DEBUG] 2020-11-09 11:23:49.775 AWSClient [140258397099904] Request Successfully signed
[TRACE] 2020-11-09 11:23:49.775 CurlHttpClient [140258397099904] Making request to https://ingest.timestream.us-east-1.amazonaws.com
[TRACE] 2020-11-09 11:23:49.775 CurlHttpClient [140258397099904] Including headers:
[TRACE] 2020-11-09 11:23:49.775 CurlHttpClient [140258397099904] amz-sdk-invocation-id: 184F67F5-0FB1-487F-A818-9F29A72916E9
[TRACE] 2020-11-09 11:23:49.775 CurlHttpClient [140258397099904] amz-sdk-request: attempt=1
[TRACE] 2020-11-09 11:23:49.775 CurlHttpClient [140258397099904] authorization: AWS4-HMAC-SHA256 Credential=**********************/20201109/us-east-1/timestream/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-api-version;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=bdd9152188bff03ac7f9732360db328794f55e3fd143923bed90e36e4a1fad9b
[TRACE] 2020-11-09 11:23:49.775 CurlHttpClient [140258397099904] content-length: 344
[TRACE] 2020-11-09 11:23:49.775 CurlHttpClient [140258397099904] content-type: application/x-amz-json-1.0
[TRACE] 2020-11-09 11:23:49.775 CurlHttpClient [140258397099904] host: ingest.timestream.us-east-1.amazonaws.com
[TRACE] 2020-11-09 11:23:49.775 CurlHttpClient [140258397099904] user-agent: aws-sdk-cpp/1.8.79/Timestream Write/Linux/5.8.0-26-generic x86_64 GCC/10.2.0
[TRACE] 2020-11-09 11:23:49.775 CurlHttpClient [140258397099904] x-amz-api-version: 2018-11-01
[TRACE] 2020-11-09 11:23:49.775 CurlHttpClient [140258397099904] x-amz-content-sha256: 7a9b3d4ae148c7e575f5d935720052da5c06609722f069f14378b30426719564
[TRACE] 2020-11-09 11:23:49.775 CurlHttpClient [140258397099904] x-amz-date: 20201109T112349Z
[TRACE] 2020-11-09 11:23:49.775 CurlHttpClient [140258397099904] x-amz-target: Timestream_20181101.WriteRecords
[DEBUG] 2020-11-09 11:23:49.775 CurlHandleContainer [140258397099904] Attempting to acquire curl connection.
[DEBUG] 2020-11-09 11:23:49.775 CurlHandleContainer [140258397099904] No current connections available in pool. Attempting to create new connections.
[DEBUG] 2020-11-09 11:23:49.775 CurlHandleContainer [140258397099904] attempting to grow pool size by 2
[INFO] 2020-11-09 11:23:49.775 CurlHandleContainer [140258397099904] Pool grown by 2
[INFO] 2020-11-09 11:23:49.775 CurlHandleContainer [140258397099904] Connection has been released. Continuing.
[DEBUG] 2020-11-09 11:23:49.775 CurlHandleContainer [140258397099904] Returning connection handle 0x560dbdc267e0
[DEBUG] 2020-11-09 11:23:49.775 CurlHttpClient [140258397099904] Obtained connection handle 0x560dbdc267e0
[DEBUG] 2020-11-09 11:23:49.917 CURL [140258397099904] (Text)   Trying 34.192.75.90:443...

[DEBUG] 2020-11-09 11:23:50.162 CURL [140258397099904] (Text) Connected to ingest.timestream.us-east-1.amazonaws.com (34.192.75.90) port 443 (#0)

[DEBUG] 2020-11-09 11:23:50.164 CURL [140258397099904] (Text) ALPN, offering http/1.1

[DEBUG] 2020-11-09 11:23:50.187 CURL [140258397099904] (Text) successfully set certificate verify locations:

[DEBUG] 2020-11-09 11:23:50.187 CURL [140258397099904] (Text)   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs

[DEBUG] 2020-11-09 11:23:50.187 CURL [140258397099904] (SSLDataOut) 5bytes
[DEBUG] 2020-11-09 11:23:50.187 CURL [140258397099904] (Text) TLSv1.3 (OUT), TLS handshake, Client hello (1):

[DEBUG] 2020-11-09 11:23:50.187 CURL [140258397099904] (SSLDataOut) 512bytes
[DEBUG] 2020-11-09 11:23:50.425 CURL [140258397099904] (SSLDataIn) 5bytes
[DEBUG] 2020-11-09 11:23:50.425 CURL [140258397099904] (Text) TLSv1.3 (IN), TLS handshake, Server hello (2):

[DEBUG] 2020-11-09 11:23:50.425 CURL [140258397099904] (SSLDataIn) 91bytes
[DEBUG] 2020-11-09 11:23:50.426 CURL [140258397099904] (SSLDataIn) 5bytes
[DEBUG] 2020-11-09 11:23:50.429 CURL [140258397099904] (Text) TLSv1.2 (IN), TLS handshake, Certificate (11):

[DEBUG] 2020-11-09 11:23:50.429 CURL [140258397099904] (SSLDataIn) 4951bytes
[DEBUG] 2020-11-09 11:23:50.430 CURL [140258397099904] (SSLDataIn) 5bytes
[DEBUG] 2020-11-09 11:23:50.430 CURL [140258397099904] (Text) TLSv1.2 (IN), TLS handshake, Server key exchange (12):

[DEBUG] 2020-11-09 11:23:50.430 CURL [140258397099904] (SSLDataIn) 333bytes
[DEBUG] 2020-11-09 11:23:50.430 CURL [140258397099904] (SSLDataIn) 5bytes
[DEBUG] 2020-11-09 11:23:50.430 CURL [140258397099904] (Text) TLSv1.2 (IN), TLS handshake, Server finished (14):

[DEBUG] 2020-11-09 11:23:50.430 CURL [140258397099904] (SSLDataIn) 4bytes
[DEBUG] 2020-11-09 11:23:50.431 CURL [140258397099904] (SSLDataOut) 5bytes
[DEBUG] 2020-11-09 11:23:50.431 CURL [140258397099904] (Text) TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

[DEBUG] 2020-11-09 11:23:50.431 CURL [140258397099904] (SSLDataOut) 70bytes
[DEBUG] 2020-11-09 11:23:50.431 CURL [140258397099904] (SSLDataOut) 5bytes
[DEBUG] 2020-11-09 11:23:50.431 CURL [140258397099904] (Text) TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):

[DEBUG] 2020-11-09 11:23:50.431 CURL [140258397099904] (SSLDataOut) 1bytes
[DEBUG] 2020-11-09 11:23:50.431 CURL [140258397099904] (SSLDataOut) 5bytes
[DEBUG] 2020-11-09 11:23:50.431 CURL [140258397099904] (Text) TLSv1.2 (OUT), TLS handshake, Finished (20):

[DEBUG] 2020-11-09 11:23:50.431 CURL [140258397099904] (SSLDataOut) 16bytes
[DEBUG] 2020-11-09 11:23:50.774 CURL [140258397099904] (SSLDataIn) 5bytes
[DEBUG] 2020-11-09 11:23:50.774 CURL [140258397099904] (SSLDataIn) 5bytes
[DEBUG] 2020-11-09 11:23:50.774 CURL [140258397099904] (Text) TLSv1.2 (IN), TLS handshake, Finished (20):

[DEBUG] 2020-11-09 11:23:50.774 CURL [140258397099904] (SSLDataIn) 16bytes
[DEBUG] 2020-11-09 11:23:50.774 CURL [140258397099904] (Text) SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256

[DEBUG] 2020-11-09 11:23:50.774 CURL [140258397099904] (Text) ALPN, server did not agree to a protocol

[DEBUG] 2020-11-09 11:23:50.774 CURL [140258397099904] (Text) Server certificate:

[DEBUG] 2020-11-09 11:23:50.774 CURL [140258397099904] (Text)  subject: CN=timestream.us-east-1.amazonaws.com

[DEBUG] 2020-11-09 11:23:50.775 CURL [140258397099904] (Text)  start date: Mar 10 00:00:00 2020 GMT

[DEBUG] 2020-11-09 11:23:50.775 CURL [140258397099904] (Text)  expire date: Mar 10 12:00:00 2021 GMT

[DEBUG] 2020-11-09 11:23:50.775 CURL [140258397099904] (Text)  subjectAltName: host "ingest.timestream.us-east-1.amazonaws.com" matched cert's "ingest.timestream.us-east-1.amazonaws.com"

[DEBUG] 2020-11-09 11:23:50.775 CURL [140258397099904] (Text)  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon

[DEBUG] 2020-11-09 11:23:50.775 CURL [140258397099904] (Text)  SSL certificate verify ok.

[DEBUG] 2020-11-09 11:23:50.775 CURL [140258397099904] (SSLDataOut) 5bytes
[DEBUG] 2020-11-09 11:23:50.775 CURL [140258397099904] (HeaderOut) POST / HTTP/1.1
Host: ingest.timestream.us-east-1.amazonaws.com
Accept: */*
amz-sdk-invocation-id: 184F67F5-0FB1-487F-A818-9F29A72916E9
amz-sdk-request: attempt=1
authorization: AWS4-HMAC-SHA256 Credential=************************/20201109/us-east-1/timestream/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-api-version;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=bdd9152188bff03ac7f9732360db328794f55e3fd143923bed90e36e4a1fad9b
content-length: 344
content-type: application/x-amz-json-1.0
user-agent: aws-sdk-cpp/1.8.79/Timestream Write/Linux/5.8.0-26-generic x86_64 GCC/10.2.0
x-amz-api-version: 2018-11-01
x-amz-content-sha256: 7a9b3d4ae148c7e575f5d935720052da5c06609722f069f14378b30426719564
x-amz-date: 20201109T112349Z
x-amz-target: Timestream_20181101.WriteRecords
Expect: 100-continue

[DEBUG] 2020-11-09 11:23:51.183 CURL [140258397099904] (SSLDataIn) 5bytes
[DEBUG] 2020-11-09 11:23:51.184 CURL [140258397099904] (Text) Mark bundle as not supporting multiuse

[DEBUG] 2020-11-09 11:23:51.184 CURL [140258397099904] (HeaderIn) HTTP/1.1 100 Continue

[TRACE] 2020-11-09 11:23:51.184 CurlHttpClient [140258397099904] HTTP/1.1 100 Continue

[TRACE] 2020-11-09 11:23:51.184 CurlHttpClient [140258397099904] 

[DEBUG] 2020-11-09 11:23:51.184 CURL [140258397099904] (SSLDataOut) 5bytes
[DEBUG] 2020-11-09 11:23:51.184 CURL [140258397099904] (DataOut) {
        "DatabaseName": "TestDB",
        "TableName":    "TestTable",
        "Records":      [{
                        "Dimensions":   [{
                                        "Name": "device_id",
                                        "Value":        "c82b968aef70",
                                        "DimensionValueType":   "VARCHAR"
                                }],
                        "MeasureName":  "frameNo",
                        "MeasureValue": "1233.230000",
                        "MeasureValueType":     "DOUBLE",
                        "Time": "1604921029",
                        "TimeUnit":     "SECONDS"
                }]
}
[DEBUG] 2020-11-09 11:23:51.446 CURL [140258397099904] (SSLDataIn) 5bytes
[DEBUG] 2020-11-09 11:23:51.446 CURL [140258397099904] (Text) Mark bundle as not supporting multiuse

[DEBUG] 2020-11-09 11:23:51.446 CURL [140258397099904] (HeaderIn) HTTP/1.1 404 Not Found

[TRACE] 2020-11-09 11:23:51.446 CurlHttpClient [140258397099904] HTTP/1.1 404 Not Found

[DEBUG] 2020-11-09 11:23:51.447 CURL [140258397099904] (HeaderIn) x-amzn-RequestId: c0ebd10b-4dfb-4ee5-b703-cca1ed8e0560

[TRACE] 2020-11-09 11:23:51.447 CurlHttpClient [140258397099904] x-amzn-RequestId: c0ebd10b-4dfb-4ee5-b703-cca1ed8e0560

[DEBUG] 2020-11-09 11:23:51.447 CURL [140258397099904] (HeaderIn) Content-Type: application/x-amz-json-1.0

[TRACE] 2020-11-09 11:23:51.447 CurlHttpClient [140258397099904] Content-Type: application/x-amz-json-1.0

[DEBUG] 2020-11-09 11:23:51.447 CURL [140258397099904] (HeaderIn) Content-Length: 63

[TRACE] 2020-11-09 11:23:51.447 CurlHttpClient [140258397099904] Content-Length: 63

[DEBUG] 2020-11-09 11:23:51.447 CURL [140258397099904] (HeaderIn) Date: Mon, 09 Nov 2020 11:23:51 GMT

[TRACE] 2020-11-09 11:23:51.447 CurlHttpClient [140258397099904] Date: Mon, 09 Nov 2020 11:23:51 GMT

[DEBUG] 2020-11-09 11:23:51.447 CURL [140258397099904] (HeaderIn) Connection: close

[TRACE] 2020-11-09 11:23:51.447 CurlHttpClient [140258397099904] Connection: close

[TRACE] 2020-11-09 11:23:51.447 CurlHttpClient [140258397099904] 

[DEBUG] 2020-11-09 11:23:51.447 CURL [140258397099904] (HeaderIn) 

[DEBUG] 2020-11-09 11:23:51.447 CURL [140258397099904] (SSLDataIn) 5bytes
[DEBUG] 2020-11-09 11:23:51.447 CURL [140258397099904] (DataIn) {"__type":"com.amazon.coral.service#UnknownOperationException"}
[TRACE] 2020-11-09 11:23:51.447 CurlHttpClient [140258397099904] 63 bytes written to response.
[DEBUG] 2020-11-09 11:23:51.447 CURL [140258397099904] (Text) Closing connection 0

[DEBUG] 2020-11-09 11:23:51.447 CURL [140258397099904] (SSLDataOut) 5bytes
[DEBUG] 2020-11-09 11:23:51.448 CURL [140258397099904] (Text) TLSv1.2 (OUT), TLS alert, close notify (256):

[DEBUG] 2020-11-09 11:23:51.448 CURL [140258397099904] (SSLDataOut) 2bytes
[DEBUG] 2020-11-09 11:23:51.453 CurlHttpClient [140258397099904] Returned http response code 404
[DEBUG] 2020-11-09 11:23:51.453 CurlHttpClient [140258397099904] Returned content type application/x-amz-json-1.0
[TRACE] 2020-11-09 11:23:51.453 CurlHttpClient [140258397099904] Response content-length header: 63
[TRACE] 2020-11-09 11:23:51.453 CurlHttpClient [140258397099904] Response body length: 63
[DEBUG] 2020-11-09 11:23:51.453 CurlHttpClient [140258397099904] Releasing curl handle 0x560dbdc267e0
[DEBUG] 2020-11-09 11:23:51.453 CurlHandleContainer [140258397099904] Releasing curl handle 0x560dbdc267e0
[DEBUG] 2020-11-09 11:23:51.454 CurlHandleContainer [140258397099904] Notified waiting threads.
[DEBUG] 2020-11-09 11:23:51.454 AWSClient [140258397099904] Request returned error. Attempting to generate appropriate error codes from response
[TRACE] 2020-11-09 11:23:51.454 AWSErrorMarshaller [140258397099904] Error response is {
        "__type":       "com.amazon.coral.service#UnknownOperationException"
}
[WARN] 2020-11-09 11:23:51.454 AWSErrorMarshaller [140258397099904] Encountered Unknown AWSError 'com.amazon.coral.service#UnknownOperationException': 
[ERROR] 2020-11-09 11:23:51.454 AWSClient [140258397099904] HTTP response code: 404
Resolved remote host IP address: 34.192.75.90
Request ID: c0ebd10b-4dfb-4ee5-b703-cca1ed8e0560
Exception name: com.amazon.coral.service#UnknownOperationException
Error message: Unable to parse ExceptionName: com.amazon.coral.service#UnknownOperationException Message: 
5 response headers:
connection : close
content-length : 63
content-type : application/x-amz-json-1.0
date : Mon, 09 Nov 2020 11:23:51 GMT
x-amzn-requestid : c0ebd10b-4dfb-4ee5-b703-cca1ed8e0560
[WARN] 2020-11-09 11:23:51.456 AWSClient [140258397099904] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
[DEBUG] 2020-11-09 11:23:51.456 AWSClient [140258397099904] Server time is Mon, 09 Nov 2020 11:23:51 GMT, while client time is Mon, 09 Nov 2020 11:23:51 GMT
404
Unable to parse ExceptionName: com.amazon.coral.service#UnknownOperationException Message: 
[INFO] 2020-11-09 11:23:51.457 CurlHandleContainer [140258397099904] Cleaning up CurlHandleContainer.
[INFO] 2020-11-09 11:23:51.457 CurlHandleContainer [140258397099904] Cleaning up CurlHandleContainer.
[DEBUG] 2020-11-09 11:23:51.457 CurlHandleContainer [140258397099904] Cleaning up 0x560dbdc21090
[DEBUG] 2020-11-09 11:23:51.457 CurlHandleContainer [140258397099904] Cleaning up 0x560dbdc267e0

To enable logging, set the following system properties:
```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
Hi @Dashing-Nelson ,
Yea, I'm seeing the same error.

We'll look into this and thanks for pointing it out to us!

**Comment by KaibaLopez** [comment]
Hi @Dashing-Nelson ,
This should be fixed and merged, thanks again.

**Comment by Dashing-Nelson** [comment]
this issue still persists in 1.9.3
