### ISSUE TITLE
Performance Degradation because of EC2 Metadata Client

### ISSUE THREAD

**Issue by Benmartin92** [aws/aws-sdk-cpp#1511]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
We were experiencing very slow speeds after upgrading to version v1.8.24. I am aware that the same issue has already been reported in https://github.com/aws/aws-sdk-cpp/issues/1440, however I think this still needs to be addressed somehow.

I can confirm that setting `AWS_EC2_METADATA_DISABLED=true` indeed solves the issue, however we are supporting several authentication methods including EC2 Instance Profile credentials (https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html, method 6) that obtains the credentials through EC2 Metadata Service which is in this case would be blocked. Therefore, we cannot disable this service.

I also understand that setting either `AWS_DEFAULT_REGION` or `AWS_REGION` prevents `ClientConfiguration` constructor from reaching out to the metadata service but these are global settings and for applications that may access multiple buckets in different regions one configuration might not be doable.

Moreover, these are new environment variables introduced in v1.8 so I suppose the region handling are implemented without utilizing these variables in many applications. For me it seems to be a hack to temporarily set `AWS_DEFAULT_REGION` or `AWS_REGION` to some region just to avoid a potentially slow EC2 metadata call.

I think it would be nice to not reaching out to the EC2 metadata client to obtain the region just because EC2 metadata is enabled, maybe make it configurable trough a different environment variable?

Thanks,
Ben

**SDK version number**
1.8.24

**Platform/OS/Hardware/Device**
Windows Server version 1607

**To Reproduce (observed behavior)**
Just create an S3Client with a default-constructed ClientConfiguration instance.

**Comment by KaibaLopez** [comment]
Hi @Benmartin92 ,
Yea... you're right, the ec2 metadata call and the workaround are not ideal and we are planning on changing that. 

I do appreciate you taking the time to open the issue though, while it is a kind of "work in progress" thing that's already in our backlog, it helps to have it explained in a concise manner and I think you did it perfectly.

**Comment by TimLand** [comment]
mark

**Comment by adame11** [comment]
We are implementing the somewhat hacky workaround of setting the environment variable `AWS_EC2_METADATA_DISABLED=true` before instantiating a `ClientConfiguration` and removing it or setting to false afterwards, but we are wondering if another permanent fix is forthcoming? And secondly, is there anything you could think of that would explain why the performance issue happens on some not all **_non-ec2_** instance machines (PCs that are naive to any environment variables or .aws\config files)? 

We stumbled across this issue after experience the performance degradation described above on SOME (but not all) of our machines. Again, any idea on what could explain why just some?

1. All of our machines do not have any AWS_DEFAULT_REGION nor AWS_REGION environment variables nor any .aws\config files anywhere on their file system. 
2. By experiment, the "expensive" ec2 metadata lookup does NOT appear to happen (using sysinternals process monitor app `procmon64` to verify this) on _some_ of our PCs
3. For example, the performance slowdown did _not_ occur on bare metal Windows 10 desktops. You can see the failure to find an .aws\config file but then no attempt to query 169.254.169.254 (the ec2 metadata service)
4. However, the performance slowdown does notably happen on, for example, a bare metal Windows Server 2019 that we tried. Also, the slowdown happens reliably on our Windows 10 and Windows 11 esxi hosted virtual machines: first there is a failed attempt to find an %USERPROFILE%\.aws\config file, next there is a failed attempt to query 169.254.169.254 (the ec2 metadata service), which tries a few times and fails (hence the slowness). Also, although we have no way of verifying whether the ec2 metadata service call is happening or not, the slowdown does not appear to happen on Mac OS nor Ubuntu vms? Is this all just coincidence?

I looked at the `GetCurrentRegion` method after the `GetEC2MetadataClient` but didn't see anything there that could explain why some machines are "fast" and some machines experience the expensive/slow ec2 metadata lookup. Ideas are welcome!

**Suggested Fix**

Would a reasonable fix for this be to offer a new overload of the `ClientConfiguration` constructor that takes a default `region` string as a parameter? In that case, don't bother looking at environment variables nor doing the slow `ec2 metadata` lookup. We have the same needs as the OP here: need to access buckets in potentially different regions from a single machine/application.

**Comment by jmklix** [comment]
We have added an optional cmake flag that will turn off IMDS calls: `DISABLE_INTERNAL_IMDSV1_CALLS`. This should fix your problems but please let me know if you have any more questions. Commit with changes: https://github.com/aws/aws-sdk-cpp/commit/3fefb1ce2cac3bd502018587936f3de42389b010

**Comment by xconverge** [comment]
@jmklix I don't think setting DISABLE_INTERNAL_IMDSV1_CALLS works for my application. I can't find where this is used in https://github.com/aws/aws-sdk-cpp/commit/3fefb1ce2cac3bd502018587936f3de42389b010

I see where the test sets ```clientConfig.disableIMDS = true``` and ensures functionality, but I don't see where the cmake flag, which adds the definition DISABLE_IMDSV1 is then used in the client configuration to set m_disableIMDS = true?

I think I will have to stick with the old way of setting ```AWS_EC2_METADATA_DISABLED=true```

unless I am missing something here...

**Comment by jmklix** [comment]
Sorry for the confusion, but this cmake flag only disables IMDS v1 calls. And it does not disable IMDS v2 calls.

**Comment by xconverge** [comment]
Ok, so without really understanding what IMDS v1 or v2 are, I am still definitely experiencing this issue, and will continue to use the workaround of setting ```AWS_EC2_METADATA_DISABLED=true``` in my code to prevent the long client configuration creation times of 10-20 seconds
