### ISSUE TITLE
Windows 32-bit build of transfer fails

### ISSUE THREAD

**Issue by dougnorton** [aws/aws-sdk-cpp#1512]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
When compiling "transfer" for 32-bit the build fails.

**SDK version number**
1.8 - master

**Platform/OS/Hardware/Device**
Windows 10

**To Reproduce (observed behavior)**
mkdir build
cd build
cmake ..\aws-sdk-cpp -G "Visual Studio 15 2017" -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3;glacier;transfer"
msbuild ALL_BUILD.vcxproj /p:Configuration=Release

**Expected behavior**
I expect it to build without errors. S3 and glacier compile but transfer fails.

**Logs/output**
C:\test\aws-sdk-cpp\aws-cpp-sdk-transfer\source\transfer\TransferManager.cpp(772): error C2220: warning treated as error - no 'object' file generated [C:\test\build\aws-cpp-sdk-transfer\aws-cpp-sdk-transfer.vcxproj]
C:\test\aws-sdk-cpp\aws-cpp-sdk-transfer\source\transfer\TransferManager.cpp(772): warning C4244: 'initializing': conversion from 'const _Ty' to 'size_t', possible loss of data [C:\test\build\aws-cpp-sdk-transfer\aws-cpp-sdk-transfer.vcxproj]
          with
          [
              _Ty=uint64_t
          ]
C:\test\aws-sdk-cpp\aws-cpp-sdk-transfer\source\transfer\TransferManager.cpp(777): warning C4244: 'initializing': conversion from 'uint64_t' to 'size_t', possible loss of data [C:\test\build\aws-cpp-sdk-transfer\aws-cpp-sdk-transfer.vcxproj]
C:\test\aws-sdk-cpp\aws-cpp-sdk-transfer\source\transfer\TransferManager.cpp(927): warning C4244: 'argument': conversion from 'uint64_t' to 'size_t', possible loss of data [C:\test\build\aws-cpp-sdk-transfer\aws-cpp-sdk-transfer.vcxproj]
C:\test\aws-sdk-cpp\aws-cpp-sdk-core\include\aws/core/utils/memory/AWSMemory.h(66): warning C4244: 'argument': conversion from '_Ty' to 'size_t', possible loss of data [C:\test\build\aws-cpp-sdk-transfer\aws-cpp-sdk-transfer.vcxproj]
          with
          [
              _Ty=uint64_t
          ] (compiling source file C:\test\aws-sdk-cpp\aws-cpp-sdk-transfer\source\transfer\TransferManager.cpp)
  C:\test\aws-sdk-cpp\aws-cpp-sdk-core\include\aws/core/utils/memory/AWSMemory.h(258): note: see reference to function template instantiation 'T *Aws::New<T,const _Ty&,unsigned __int64>(const char *,const _Ty &,unsigned __int64 &&)' being compiled
          with
          [
              T=Aws::Utils::Stream::PreallocatedStreamBuf,
              _Ty=unsigned char *
          ] (compiling source file C:\test\aws-sdk-cpp\aws-cpp-sdk-transfer\source\transfer\TransferManager.cpp)
  C:\test\aws-sdk-cpp\aws-cpp-sdk-transfer\source\transfer\TransferManager.cpp(827): note: see reference to function template instantiation 'std::unique_ptr<Aws::Utils::Stream::PreallocatedStreamBuf,Aws::Deleter<Aws::Utils::Stream::PreallocatedStreamBuf>> Aws::MakeUnique<Aws::Utils::Stream::PreallocatedStreamBuf,const RESOURCE_TYPE&,uint64_t>(const char *,const RESOURCE_TYPE &,uint64_t &&)' being compiled
          with
          [
              RESOURCE_TYPE=unsigned char *
          ]

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @dougnorton ,
Thanks for bringing this up for us and yea I can reproduce this as well.

**Comment by KaibaLopez** [comment]
Hi @dougnorton ,
This bug should be fixed now, please update to the newest version.

**Comment by dougnorton** [comment]
Compiles! Great, thanks for addressing this so quickly!
