### ISSUE TITLE
Set Higher Default Connect Time Out For STS in STSCredentialsProvider.cpp

### ISSUE THREAD

**Issue by vinayan3** [aws/aws-sdk-cpp#1514]
When a larger set of processes, on the order of 1000s - 10,0000s , startup on a  EKS cluster they fetch a STS token so they can download data from S3. I've observed that the default connect time out of 1s is too short and what happens is that most processes will fail to get the token.

This is basically a thundering herd and it's possible STS does not like this at the TCP level at least. 

**Describe the solution you'd like**
Increase the default connect timeout to something higher. The errors don't show up on Cloud Trail so I' m not sure what the connection timeout should b. The system was unblocked by using a connection timeout of 30 seconds:
```
STSAssumeRoleWebIdentityCredentialsProvider::STSAssumeRoleWebIdentityCredentials() {
[ . . . ]
 config.connectTimeoutMs = 30000;
[ . . . ]
}
```

**Describe alternatives you've considered**

- Really not much of a workaround here. STS tokens even a highly concurrent container environment need to be fetch-able.

**Additional context**
AWS Support recommended I file a ticket on Github for the C++ SDK as this is not a EKS/STS problem.

**Comment by KaibaLopez** [comment]
Hi @vinayan3 ,

 I think it kind of makes sense but I'm always defensive about changing "defaults" based on issues like this, and honestly, I have no idea what was the process in choosing the current default values... 

I think a better change for this would be something like : 

```
STSAssumeRoleWebIdentityCredentialsProvider::STSAssumeRoleWebIdentityCredentials(Aws::Client::ClientConfiguration& config) 
{
    [ . . . ]
    m_client = Aws::MakeUnique<Aws::Internal::STSCredentialsClient>(STS_ASSUME_ROLE_WEB_IDENTITY_LOG_TAG, config);
    [ . . . ]
}
```
Where the credentials provider could take a client config (which is already exposed to the user). That way you could modify it to fit your needs....

I'll look into this and keep you updated on whether or not this is something we can do without breaking stuff... Also, feel free to suggest other possible solutions.

**Comment by vinayan3** [comment]
> Where the credentials provider could take a client config (which is already exposed to the user). That way you could modify it to fit your needs....
> 
> I'll look into this and keep you updated on whether or not this is something we can do without breaking stuff... Also, feel free to suggest other possible solutions.

That is actually perfect and the only reason why I had to go change `STSCredentialsProvider.cpp` in the first place.

**Comment by vinayan3** [comment]
This is still relevant. I have an in progress diff that I need to clean up and get a PR Going for.
