### ISSUE TITLE
vs2019, when installing this package with NuGet, get the error "you are trying to install this package into a project that targets 'native,Version=v0.0"

### ISSUE THREAD

**Issue by GitZinger** [aws/aws-sdk-cpp#1519]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Hi,

I create an empty project. also now there is no network choice when creating a new project in vs 2019

Could not install package  
```
You are trying to install this package into a project 
that targets 'native,Version=v0.0', 
but the package does not contain any assembly references 
or content files 
that are compatible 
with that framework. For more information, 
contact the package author.		
```		
but I set the

```
project property -> configuration properties-> c++/cli  properties 
->.net target framework version : v.50

```

please help me here!

I really appreciate it!
**SDK version number**
awssdk core; 
awssdk lambda;
**Platform/OS/Hardware/Device**
What are you running the sdk on?
win 10

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

**Expected behavior**

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @GitZinger ,
I'm a bit confused here, you listed: awssdk core and awssdk lambda as SDK versions and the log mentions .net... are you trying to install aws sdk for .net and got here by mistake or am I misunderstanding something?

**Comment by GitZinger** [comment]
> Hi @GitZinger ,
> I'm a bit confused here, you listed: awssdk core and awssdk lambda as SDK versions and the log mentions .net... are you trying to install aws sdk for .net and got here by mistake or am I misunderstanding something?
I am using visual studio. So I want the asw sdk for c++. So in order to load these, I used visual studio NuGet UI to install awssdk core and awssdk lambda these two package for my empty c++ project. 
Then I got this error. Could you tell me how to install the sdk for visual studio  c++ project? ?

**Comment by KaibaLopez** [comment]
@GitZinger , we don't support NuGet for our sdk.
The recommended way of installing the sdk is to do it from source.
The ReadMe has a [quick guide](https://github.com/aws/aws-sdk-cpp#building-the-sdk) on how to do that. 

Alternatively, you could also try installing through vcpkg, we don't have full control on that though, so if you face any problems, it would take a bit longer to fix.

**Comment by GitZinger** [comment]
@KaibaLopez 
Thank you so much!
Here is what I did. I will appreciate it if you could advise me here. I used the Microsoft Visual Studio 2019.
In order to use these release built directories including the .h files and .dll files in the Visual Studio, I need to add the source code .h files path into the ` C/C++ -> Additional Include Directories.` 
and add the corresponding .lib files into` Linker -> Input -> Additional Dependencies.` (after I click the build button in the Visual Studio, the Visual Studio generates the .lib files.
Are there any associated .dll files there? at this point I did not see any dll files in the build directory.
So am I on the right track here?

another question is that:
I am using the C++ at local end. at the cloud end, the lambda function written in Python. Can I pass the argument when invoking the lambda function? I mean is there a limitation about the argument? 
what if I want to use the OpenCV variable type MAT? Can I pass the local MAT data as the argument into the  lambda function? and cloud  lambda function could take in this type variable and return the same type?
if not, what kind of generic variable type I could use to pass as the argument into the  lambda function?
Thank you so much!

**Comment by KaibaLopez** [comment]
@GitZinger ,
For the first question, I think I've seen this before but I can't find the github issue with the instructions on how to add the sdk to visual studio. I did however find [this blog post](https://aws.amazon.com/blogs/gametech/how-to-build-and-integrate-the-aws-sdk-for-c-games-on-windows/) on how to "integrate to games" which basically walks you through the steps. Let me know if you have other problems after doing that. 

As for the second question... that's a bit more complicated so it'll take me a bit more time to be sure but yea wanted to at least respond to the visual studio one first.

**Comment by KaibaLopez** [comment]
I see that you've opened issues for this follow up questions so I will close this one and continue to respond on the other ones.
