### ISSUE TITLE
Please provide a string -> AWS::Region function

### ISSUE THREAD

**Issue by zwass** [aws/aws-sdk-cpp#152]
Our application parses the AWS region from a CLI flag, but there is currently no good way to determine whether the user-provided region is valid. I noticed there is a `const char* GetRegionName(Region region)` function, and it would be great if there were one that went in the opposite direction.

We could add our own `std::map<std::string, Aws::Region>`, but then this would have to be updated every time `Aws::Region` was updated. If the SDK provided a function (or just provided that map), we could just use that and automatically benefit from updates to the SDK.

Thanks.

**Comment by JonathanHenson** [comment]
Good idea, We are considering integrating CLI config support anyways. In the meantime, we can see about exposing that mapping.

**Comment by zwass** [comment]
Cool! We would definitely take advantage of the CLI config support, but would also want access to this information anyway as we might take a region as a flag in our (separate) configuration.

**Comment by JonathanHenson** [comment]
This has been implemented and pushed out as part of the AWSProfileConfigLoader interface. See https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/include/aws/core/config/AWSProfileConfigLoader.h as a result we added the reverse mapping as well.

**Comment by Bu11etmagnet** [comment]
Apart from getting and setting a string, I don't see any operation on regions in AWSProfileConfigLoader. @zwass was asking for a way to get an Aws::Region from a string.

**Comment by JonathanHenson** [comment]
Which there is in the Region file.
