### ISSUE TITLE
ListObjectsV2 returns keys/prefixes with special XML symbols (&'"<>) escaped

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#1521]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
`Aws::S3::S3Client::ListObjectsV2()` returns mangled key names/prefixes. Every symbol XML requires to escape (`& < > ' "`) is represented by their escaped sequence (`&amp;`, etc). I stepped through the code I see that original data gets unmangled (in `XMLNode::Value()`) and then mangled again (in `XMLPrinter::PushText()`). I assume this happens because someone forgot to set `XMLPrinter::_processEntities` to `false` (in `XmlNode::GetText()`).

I've tried setting `EncodingType` to `Aws::S3::Model::EncodingType::url`, but immediately ran into an issue with decoding keys containing whitespace -- for some reason server decided to encode these as `+` instead of `%20`. Which is kinda mentioned in [wiki](https://en.wikipedia.org/wiki/Percent-encoding), but not really and now I am worried my URL decoding logic may not agree with server's in some other ways...

**SDK version number**
1.7.116

**Platform/OS/Hardware/Device**
Win7, Linux

**To Reproduce (observed behavior)**
Create an object with key containing `&`, list it using ListObjectsV2(), then look at returned key name.

**Expected behavior**
I expect it to return object key without special XML symbols being escaped.

**Logs/output**
N/A

**Additional context**

**Notes**
ListObjectV1's "next marker" (returned by GetNextMarker()) requires url-decoding too.

**Comment by crusader-mike** [comment]
Note that using url-encoding is not an adequate workaround. I am lucky that AWS S3 url-encodes symbols like '<>"' -- those symbols are not reserved according to URI-encoding standard and some other S3 service may decide to not encode them. Which in turn will cause XML-escaping to kick in and I'll be back to original issue.

**Comment by KaibaLopez** [comment]
Hi @crusader-mike ,
Just as a quick update before I go diving into this, but I believe this is more of a service API side Issue, all these characters are included in the documentation for "troublesome" or "best to avoid" when using s3... 
I'll update with more useful info as I get around to working on this but yea, keep in mind this might be "expected" even if not great.

**Comment by crusader-mike** [comment]
Well, the way I see it -- AWS S3 handles them just fine (judging from intercepted REST API packets), Storage Grid handles them just fine (judging from the same thing). Only AWS C++ SDK doesn't... ;)

**Comment by crusader-mike** [comment]
An update -- `ListObjectV1`s "next marker" (returned by `GetNextMarker()`) requires url-decoding too.

**Comment by crusader-mike** [comment]
> Note that using url-encoding is not an adequate workaround. I am lucky that AWS S3 url-encodes symbols like `<>"` -- those symbols are not reserved according to URI-encoding standard and some other S3 service may decide to not encode them. Which in turn will cause XML-escaping to kick in and I'll be back to original issue.

Well, guess what? IBM COS (CleverSafe/3.10.0.141) doesn't support url-encoding in ListObject... I ended up manually xml-decode-ing everything this SDK pulls from returned xml (key, etag, continuation-token, prefix, etc).

To fix it you'll need to update everyone of those constructors that take `XXXResult<XmlDocument>` and uses plain `XmlNode::GetText()` without proper decoding.
