### ISSUE TITLE
Facing cmake error

### ISSUE THREAD

**Issue by Pravallika-Vardhani** [aws/aws-sdk-cpp#1524]
Platform/OS/Hardware/Device
Ubuntu 18.04

Describe the question
I tried the build SDK in my ubuntu while running cmake command I am facing errors 

ubuntu@ubuntu-VirtualBox:~/aws-cpp/aws-sdk-cpp-build$ cmake ../aws-sdk-cpp
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating linux build config
-- Building project version: 1.8.94
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/aws-cpp/aws-sdk-cpp-build/.deps
[  4%] Performing download step (git clone) for 'AwsCCommon'
Cloning into 'AwsCCommon'...
fatal: unable to access 'https://github.com/awslabs/aws-c-common.git/': gnutls_handshake() failed: Error in the pull function.
Cloning into 'AwsCCommon'...
fatal: unable to access 'https://github.com/awslabs/aws-c-common.git/': gnutls_handshake() failed: Error in the pull function.
Cloning into 'AwsCCommon'...
fatal: unable to access 'https://github.com/awslabs/aws-c-common.git/': gnutls_handshake() failed: Error in the pull function.
-- Had to git clone more than once:
          3 times.
CMake Error at /home/ubuntu/aws-cpp/aws-sdk-cpp-build/.deps/build/tmp/AwsCCommon-gitclone.cmake:66 (message):
  Failed to clone repository: 'https://github.com/awslabs/aws-c-common.git'

 

make[2]: *** [build/src/AwsCCommon-stamp/AwsCCommon-download] Error 1
make[1]: *** [CMakeFiles/AwsCCommon.dir/all] Error 2
make: *** [all] Error 2
CMakeFiles/AwsCCommon.dir/build.make:89: recipe for target 'build/src/AwsCCommon-stamp/AwsCCommon-download' failed
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/AwsCCommon.dir/all' failed
Makefile:83: recipe for target 'all' failed
CMake Error at CMakeLists.txt:224 (message):
  Failed to build third-party libraries.

 

-- Configuring incomplete, errors occurred!
ubuntu@ubuntu-VirtualBox:~/aws-cpp/aws-sdk-cpp-build$

**Comment by KaibaLopez** [comment]
Hi @Pravallika-Vardhani ,
The error you're getting is kind of generic...
I would recommend installing the dependencies separately, follow [these instructions](https://github.com/aws/aws-sdk-cpp#third-party-dependencies) and let me know when and what error you get that way.

**Comment by Pravallika-Vardhani** [comment]
Still facing issue while installing dependencies separately.

ubuntu@ubuntu-VirtualBox:~$ git clone https://github.com/awslabs/aws-c-common
Cloning into 'aws-c-common'...
fatal: unable to access 'https://github.com/awslabs/aws-c-common/': gnutls_handshake() failed: Error in the pull function.
ubuntu@ubuntu-VirtualBox:~$

ubuntu@ubuntu-VirtualBox:~/aws-cpp$ git clone https://github.com/awslabs/aws-checksums
Cloning into 'aws-checksums'...
fatal: unable to access 'https://github.com/awslabs/aws-checksums/': gnutls_handshake() failed: Error in the pull function.
ubuntu@ubuntu-VirtualBox:~/aws-cpp$

ubuntu@ubuntu-VirtualBox:~/aws-cpp$ git clone https://github.com/awslabs/aws-c-event-stream
Cloning into 'aws-c-event-stream'...
fatal: unable to access 'https://github.com/awslabs/aws-c-event-stream/': gnutls_handshake() failed: Error in the pull function.
ubuntu@ubuntu-VirtualBox:~/aws-cpp$

**Comment by KaibaLopez** [comment]
it doesn't even seem to try to do git clone, so not sure I can help you from the SDK side.

can you verify that this is not an internet connection, firewall or permission problem?
