### ISSUE TITLE
Adding array of float or double to JSONValue

### ISSUE THREAD

**Issue by Dashing-Nelson** [aws/aws-sdk-cpp#1526]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Ubuntu 20.10
**Describe the question**
i wanted to create a JSON using Aws-sdk for C++. this is what i am doing so far.

```
void convertStructToAwsJSON()
{
    Aws::Utils::Json::JsonValue jsonValue = Aws::Utils::Json::JsonValue();
    jsonValue.WithDouble("percentage", 93.6);
    jsonValue.WithInteger("age", 25);
    float grades[3] = {87, 95, 65};
    jsonValue.WithArray("grades", grades);
}
```
but it seems like it throws an error, saying that it is not of the argument type. I checked the documentation and the only thing I can do is add an array of type String.

```
const Aws::Utils::Array<Aws::String> grades;
grades[0] = "87";
grades[1] = "95";
grades[2] = "65";
jsonValue.WithArray("grades", grades);
```
Now it works. How to store it in double or integer instead of string?

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
Hi @Dashing-Nelson ,
The json value is saved as a string, but it can be interpreted as other types...
for examples on how to approach this you can take a look at our [json serializer tests](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/utils/json/JsonSerializer.cpp).
Let me know if this works for you or if I misunderstood the question.

**Comment by Dashing-Nelson** [comment]
I want to store an array of float in an json array. WithArray only allows for aws array based on aws string.

**Comment by KaibaLopez** [comment]
ahh ok yea I see the problem, my bad.
So, the solution is a little convoluted but basically what you want to do for numbers or (non string data types) is something like:
```cpp
    Aws::Utils::Array<Aws::Utils::Json::JsonValue> grades(2);
    Aws::Utils::Json::JsonValue value1;
    Aws::Utils::Json::JsonValue value2;
    grades[0] = value1.AsDouble(3.1416);
    grades[1] = value2.AsDouble(164635242.4134452);
```
There is no float tho, and yea let me know if this helps or if I'm still missing something.

**Comment by Dashing-Nelson** [comment]
yup but this is too complex. Closing this.
