### ISSUE TITLE
TranscribeStreaming send more audio chunks while receiving partial results

### ISSUE THREAD

**Issue by diegonieto** [aws/aws-sdk-cpp#1527]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
ARM STB/ Linux Ubuntu bionic 18.04 LTS

**Describe the question**
Is it possible to receive partial audio transcriptions while still sending more audio chunks?
I've been through the TranscribeTests.cpp test and I realized full stream must be filled before receiving results in StartStreamTranscriptionHandler::SetTranscriptEventCallback.

Is there any way to do both process simultaneously? to continue filling the stream while some previous chunks have already been transcribed?

**Related code**
TranscribeTests.cpp (aws-cpp-sdk-transcribestreaming-integration-tests/aws-cpp-sdk-transcribestreaming-integration-tests)
This callback:
```
    handler.SetTranscriptEventCallback([&transcribedResult](const TranscriptEvent& ev)
    {
        // TODO: only check the result marked as "final"
        const auto& results = ev.GetTranscript().GetResults();
        if (results.empty())
        {
            return;
        }
        const auto& last = results.back();
        const auto& alternatives = last.GetAlternatives();
        if (alternatives.empty())
        {
            return;
        }
        if (!last.GetIsPartial()) {
        }
        if (!kk) {
            std::cout << __PRETTY_FUNCTION__ << " first partial: "  << std::this_thread::get_id() <<  std::endl;
            kk = true;
        }
        transcribedResult = alternatives.back().GetTranscript();
    });
```
is never called before this finishes:
```
    auto OnStreamReady = [](AudioStream& stream)
    {
        std::cout << __PRETTY_FUNCTION__ << " test: " << std::this_thread::get_id() << std::endl;
        Aws::FStream file(TEST_FILE_NAME, std::ios_base::in | std::ios_base::binary);
        ASSERT_TRUE(file);
        char buf[1024];
        while(file)
        {
            file.read(buf, sizeof(buf));
            Aws::Vector<unsigned char> bits{buf, buf + file.gcount()};
            AudioEvent event(std::move(bits));
            if (!stream)
            {
                break;
            }
            if (!stream.WriteAudioEvent(event))
            {
                break;
            }
        }
        stream.WriteAudioEvent({}); // per the spec, we have to send an empty event (i.e. without a payload) at the end.
        stream.flush();
        stream.Close();
    };
```

**Comment by diegonieto** [comment]
I found it is a matter of how fast you write in the stream. In any case, I see a noticeable delay based on the amount of size written in the stream. Does it require a minimum amount of data before sending the request?

**Comment by KaibaLopez** [comment]
Hi @diegonieto ,
Sorry for the lack of response on this, and glad you found an answer for the original question.
As for a minimum amount of data: The service has a hard limit on minimum duration of audio for 500 milliseconds so... yes, kind of.
You can find more info on the service's limits [here](https://docs.aws.amazon.com/transcribe/latest/dg/limits-guidelines.html#limits).
Again, sorry for the slow response and hope this helps.
