### ISSUE TITLE
Create iOS framework

### ISSUE THREAD

**Issue by SeanBottomley** [aws/aws-sdk-cpp#1528]
I am trying to build the C++ SDK for iOS, i note a few postd about it but in one it says formal guidance was being created? I cant find it so has this been created?

**Comment by KaibaLopez** [comment]
Hi @SeanBottomley ,
At some point it was, but apparently this was long enough ago that it was no longer valid so it was removed, we'll work on getting one out, sorry for that.
We do however, have instructions on how to build for xcode in the [readme](https://github.com/aws/aws-sdk-cpp#to-create-an-out-of-source-build). From there you can change the target through xcode, I found [this guide](https://developer.apple.com/library/archive/technotes/tn2339/_index.html) very helpful on how to do that.

Sorry again we don't have a formal guidance or step by step tutorial on how to do that, but yea hope this helps.

**Comment by wansco** [comment]
Is ios no longer supported at all in this library at all? I get that there is a dedicated ios sdk, but I need to call some API's from c++ that's cross-compiled for all platforms. It seems like this library supports everything except ios?
