### ISSUE TITLE
Use Unicode Character Set to build aws-cpp-sdk-core library

### ISSUE THREAD

**Issue by dkislov** [aws/aws-sdk-cpp#153]
When I set in Visual Studio 2013 Use Unicode Character Set for aws-cpp-sdk-core project property I got cast error: C2664: 'BOOL GetVersionExA(LPOSVERSIONINFOA)' : cannot convert argument 1 from 'OSVERSIONINFO *' to 'LPOSVERSIONINFOA'	D:\xxxxx\aws-sdk-cpp\aws-cpp-sdk-core\source\utils\OSVersionInfo.cpp. My solution to solve this error is : 
change line GetVersionExA(&versionInfo); to:
#ifdef _UNICODE
	GetVersionExA(reinterpret_cast<LPOSVERSIONINFOA>(&versionInfo));
#else
	GetVersionExA(&versionInfo);
#endif
Am I right?

**Comment by Bu11etmagnet** [comment]
No.
GetVersionExA is always "ANSI". versioninfo should be always-ANSI too. (OSVERSIONINFOA ?)

**Comment by JonathanHenson** [comment]
We support Unicode the Unix way, and don't want the complexity or mess that comes with window's half baked unicode solution. You can use unicode safely in the SDK by just passing unicode strings as char* or std::string. Unfortunately, this may mean you need to convert wchar* or std::wstring over, but this is less problematic than trying to support wchar formats in general.

I see we have a bug here with the version info struct we are using will update. I'll update this issue once we update it.

**Comment by JonathanHenson** [comment]
Confirmed, we are using OSVersionInfo instead of OSVersionInfoA, this causes people compiling with unicode turned on with TCHAR resolving to WCHAR to have broken builds. 

https://msdn.microsoft.com/en-us/library/windows/desktop/ms724834(v=vs.85).aspx

Will update when bug is fixed.

**Comment by JonathanHenson** [comment]
I've got an update going through CI right now. I'll push out as soon as it's finished.

**Comment by JonathanHenson** [comment]
I pushed the update out, can you verify your build?
