### ISSUE TITLE
error LNK2001: unresolved external symbol "char const * const Aws::Http::CONTENT_TYPE_HEADER" (?CONTENT_TYPE_HEADER@Http@Aws@@3QBDB) Aws::Http::API_VERSION_HEADER" (?API_VERSION_HEADER@Http@Aws@@3QBDB)

### ISSUE THREAD

**Issue by GitZinger** [aws/aws-sdk-cpp#1530]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
when calling the S3 functions, the program raised these error, and there is no aws-http.dll. after taking a glance at all s3 header files, did not find any other aws libraries modules to be needed
No idea how to fix it
**SDK version number**
1.8
**Platform/OS/Hardware/Device**
What are you running the sdk on?
win10
**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

added s3 include/lib/dll files into project,
and tried to connect s3 and called the getobject function

**Expected behavior**
working with aws s3
**Logs/output**
If applicable, add logs or error output.
error LNK2001: unresolved external symbol "char const * const Aws::Http::CONTENT_TYPE_HEADER" (?CONTENT_TYPE_HEADER@Http@Aws@@3QBDB)

error LNK2001: unresolved external symbol "char const * const Aws::Http::API_VERSION_HEADER" (?API_VERSION_HEADER@Http@Aws@@3QBDB)

fatal error LNK1120: 2 unresolved externals
To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

**Comment by KaibaLopez** [comment]
@GitZinger ,
This error usually happens if you have not added the preprocessor definitions:
```
USE_IMPORT_EXPORT
USE_WINDOWS_DLL_SEMANTICS
```
Can you verify that's not the case?

Also, make sure that your project matches the platform you built the SDK for, by default cmake builds on Release x64  and Visual Studio defaults to Debug x86 so there may be a problem there, so to avoid future hard to find errors make sure that when you set the project properties at the top they are the correct ones.

**Comment by GitZinger** [comment]
@KaibaLopez 
Thank you. where and when should I put these?
in the main.cpp code?
or when building from the source???

But the weird thing is Putobject() is totally working.
the getobject() is not.
I mean they are both from the same library dll and header file.
I am using the official example
https://docs.aws.amazon.com/code-samples/latest/catalog/cpp-s3-get_object.cpp.html

How can two functions from the same library be so different?

**Comment by KaibaLopez** [comment]
the preprocessor defines are changed on the project properties:

right click on the project > Properties > Configuration Properties (on the left side menu) > C/C++ > Preprocessor > Preprocessor Definitions.

That is odd, but yea let me know if that fixes it for you.

**Comment by GitZinger** [comment]
Yes! it is working. it got compiled successfully. Thank you

**Comment by JordiGR-TheBreachStudios** [comment]
Hi,

I'm getting the same linker errors, even if USE_IMPORT_EXPORT and USE_WINDOWS_DLL_SEMANTICS preprocessor definitions are set (I tried with compiled SDK 1.9.220 and 1.9.272).
I'm trying to integrate the SDK into an Unreal project. If I use the pre-built SDK downloaded from vcpkg, my project links properly, but at run time I get a crash from the Unreal memory handler when freeing memory doing the following:

1. From my code, call ListAliases SDK method and store the result in a local variable
2. Do some work with the retrieved aliases
3. Exit the scope where the local variable is defined -> Crash when the first std::string (the alias name) is deallocated
