### ISSUE TITLE
TranscribeStreaming partial results IsPartial always return true

### ISSUE THREAD

**Issue by diegonieto** [aws/aws-sdk-cpp#1531]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
PC / ARM64

**Describe the question**
Hi, it seems that
Aws::TranscribeStreamingService::Model::Result::GetIsPartial
always return true. I'm using TranscribeTests.cpp integration test. So, how to know when the transcription is finished from the event callback?

**Comment by diegonieto** [comment]
Hi guys, do you have any update about this?

**Comment by KaibaLopez** [comment]
@diegonieto ,

oh wow very sorry about this one, it totally flew under my radar.
I will take a closer look, but on first impression it does seem like a bug, the whole intention of the call is that it will tell you if it is finished so if it truly always returns true then there's a problem.
Could you show me the test you are running btw?
