### ISSUE TITLE
s3 sdk & grpc cannot coexist in the same application

### ISSUE THREAD

**Issue by squalfof** [aws/aws-sdk-cpp#1533]
Hi, seems both s3-sdk and grpc use SSL/TLS, during startup, my application just crashed with either 
```
@     0x55c8bcb30bd8  (unknown)  bssl::ssl_cert_dup()
```
or 
```
PC: @     0x7fbec111154e  (unknown)  Aws::Utils::Crypto::CreateSha256Implementation()
```
depends on which one initialized first.

Can I disable SSL mech in s3-sdk ? Since SSL/TLS is a built-in mech in Grpc.

Any suggestions on this ? Like editing `Aws::SDKOptions`?

Thanks a lot.

**Comment by squalfof** [comment]
Well, set 
```
Aws::CryptoOptions::initAndCleanupOpenSSL =  false
Aws::Client::ClientConfiguration::schema = Aws::Http::Scheme::HTTP
```
seems resolve my issue. Not quite sure if any side effect ?

**Comment by KaibaLopez** [comment]
Not really, I mean... the side effect is that it's on you (or in your case grpc) to initialize and clean up SSL and well using the http schema is considered less secure, so it's up to you on how you use that? 

Anyways, I'm glad you found a way to make them both work, I'll be marking this issue to closing since I don't think there's any more actions to be taken, but let me know if you have more questions.

**Comment by JonathanHenson** [comment]
You should be able to simply set the flag without using plain text http. Does that work for you?

**Comment by squalfof** [comment]
Thanks. If `without plain text http` means using `Http::Scheme::HTTPS`, then it's error `@     0x55c8bcb30bd8  (unknown)  bssl::ssl_cert_dup()` again.

**Comment by KaibaLopez** [comment]
Hey @squalfof ,
I'm not sure I can help you further with this, is it ok to close it or do you have another specific question regarding this issue?

**Comment by ezillinger** [comment]
For anyone else who finds this issue while Googling the problem:

This problem is caused by linking GRPC and the S3 SDK to two different versions of OpenSSL. It's easy to mess up when you're using OpenSSL 1.1.1x in one library and OpenSSL 3.x in another because you won't get ODR errors.
