### ISSUE TITLE
Error when make building sdk

### ISSUE THREAD

**Issue by Alegruz** [aws/aws-sdk-cpp#1535]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Platform: Linux
OS: Ubuntu 20.04.1
Hardware: Laptop
Device: MSI PS42 Modern 8MO
g++ version: 9.3.0
gcc version: 9.3.0
aws-cli version: 2.1.9

**Describe the question**
I am currently trying to build the sdk according to the [developer guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/aws-sdk-cpp-dg.pdf). However, whenever I try to build the sdk, I get an error regarding `AwsCheckSums`. Below is the terminal log.

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
sudo cmake ../aws-sdk-cpp/ -D CMAKE_BUILD_TYPE=[Debug]
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating linux build config
-- Building project version: 1.8.103
-- Configuring done
-- Generating done
-- Build files have been written to: ~??~/sdk_build/.deps
[ 33%] Built target AwsCCommon
[ 37%] Performing build step for 'AwsChecksums'
[  8%] Building C object CMakeFiles/aws-checksums.dir/source/intel/crc32c_sse42_asm.c.o
~??~/sdk_build/.deps/build/src/AwsChecksums/source/intel/crc32c_sse42_asm.c: In function ‘s_crc32c_sse42_clmul_256’:
~??~/sdk_build/.deps/build/src/AwsChecksums/source/intel/crc32c_sse42_asm.c:61:5: error: ‘asm’ operand has impossible constraints
   61 |     asm volatile("enter_256_%=:"
      |     ^~~
make[5]: *** [CMakeFiles/aws-checksums.dir/build.make:154: CMakeFiles/aws-checksums.dir/source/intel/crc32c_sse42_asm.c.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:592: CMakeFiles/aws-checksums.dir/all] Error 2
make[3]: *** [Makefile:141: all] Error 2
make[2]: *** [CMakeFiles/AwsChecksums.dir/build.make:113: build/src/AwsChecksums-stamp/AwsChecksums-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:108: CMakeFiles/AwsChecksums.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
CMake Error at CMakeLists.txt:224 (message):
  Failed to build third-party libraries.


-- Configuring incomplete, errors occurred!
```

Is there anything I am missing?

**Comment by KaibaLopez** [comment]
Hi @Alegruz ,
so the error code is confusing but that's because the cmake flag -DCMAKE_BUILD_TYPE is getting an unexpected value, simply remove the brackets from the call:
```cmake ../aws-sdk-cpp/ -DCMAKE_BUILD_TYPE=Debug```
I would suggest to also add the -DBUILD_ONLY flag to only build the services you are planning to use for your project, for example:
```cmake ../aws-sdk-cpp/ -DCMAKE_BUILD_TYPE=Debug -DBUILD_ONLY="s3;transfer;dynamodb"```
Hope this helps.

**Comment by Alegruz** [comment]
> Hi @Alegruz ,
> so the error code is confusing but that's because the cmake flag -DCMAKE_BUILD_TYPE is getting an unexpected value, simply remove the brackets from the call:
> `cmake ../aws-sdk-cpp/ -DCMAKE_BUILD_TYPE=Debug`
> I would suggest to also add the -DBUILD_ONLY flag to only build the services you are planning to use for your project, for example:
> `cmake ../aws-sdk-cpp/ -DCMAKE_BUILD_TYPE=Debug -DBUILD_ONLY="s3;transfer;dynamodb"`
> Hope this helps.

THANK YOU! IT WORKED!

but now I am trying to invoke the makefile made, but i am getting deprecation issues from `aws-sdk-cpp/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp`, a file included from `aws-cpp-sdk-core/ub_core.cpp:46:`

the command I used was:
```
~~??~~/sdk_build$ sudo make
```

Should I make another issue ticket?

**Comment by KaibaLopez** [comment]
yea I think it'd be best to close this one and open a new one for that issue, makes it easier to look up for people who might have the same problem. 
Also, I am not getting that error so I'll need at least the full error message.
