### ISSUE TITLE
How do I use EKS or ECS role credentials when running in those contexts?

### ISSUE THREAD

**Issue by nickform-ost** [aws/aws-sdk-cpp#1538]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Amazon Linux on a t3.medium (EKS) or t2.large (ECS).

**Describe the question**
I have built an executable that calls the RegisterUsage API exposed via Aws::MarketplaceMetering::MarketplaceMeteringClient but when I run the executable in EKS or ECS, I see this message:
```
This operation can only be called from within an ECS task or an EKS pod
```
I believe that the call is being made with a role assigned to the underlying EC2 instance as I had to add the RegisterUsage permission to that role in order to get as far as the above message. My question is, what do I need to do to caues the API implementation to use the role assigned to the ECS task or EKS pod?

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by nickform-ost** [comment]
I should add that my client code for calling RegisterUsage has zero explicit handling of credentials at present as the SDK has default credentials providers built in.

**Comment by nickform-ost** [comment]
I closed this by accident yesterday but today I'm happy to close it for good. I was not properly setting the environment for the process which uses the SDK and that was preventing it from seeing the variables it needs to establish the credentials and possibly some other configuration. Sorry for the noise.

**Comment by Phanindra-labs** [comment]
> I closed this by accident yesterday but today I'm happy to close it for good. I was not properly setting the environment for the process which uses the SDK and that was preventing it from seeing the variables it needs to establish the credentials and possibly some other configuration. Sorry for the noise.

Can you help with which ENV variables need to be set to the metering client? I have a RegisterUsage policy attached to instance profile of EKS node. I am getting same error as your's. Thanks!

**Comment by jimdigriz** [comment]
This bit me too.

It seems [EKS Pod Identities](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html) is not suitable for use with `RegisterUsage`, an example with the `aws` CLI is:
```
$ aws --debug meteringmarketplace register-usage --public-key-version 1 --product-code 1234... --nonce 1234
[snipped]
An error occurred (PlatformNotSupportedException) when calling the RegisterUsage operation: This operation can only be called from within an ECS task or an EKS pod
```

If you use [IAM roles for service accounts (IRSA)](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) then it works fine.

My guess is where @nickform-ost stated "was not properly setting the environment for the process" is he was using IRSA but forgot to set those environment variables (eg. `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_ROLE_ARN`) where I am trying to use Pod Identities (`AWS_CONTAINER_CREDENTIALS_FULL_URI` and `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE`).
