### ISSUE TITLE
Getting a warning while running cmake on Windows

### ISSUE THREAD

**Issue by Eliyahu-Machluf** [aws/aws-sdk-cpp#1539]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

I'm trying to build the SDK on Windows from sources. I downloaded the sources as a zip file from https://github.com/aws/aws-sdk-cpp/releases/tag/1.8.106
When I run cmake, I get a warning, stating the sources of the SDK are not under source control of git.
I succeeded to build the SDK, however I wondered if this warning needs my attention or not.

Here is the command I run:
**cmake -G "Visual Studio 16 2019" -DSTATIC_LINKING=1 -DCMAKE_EXE_LINKER_FLAGS_DEBUGOPT="" -DCMAKE_CXX_FLAGS_DEBUGOPT="" -DTARGET_ARCH=WINDOWS** 

And here is the output with the warning message (fatal: not a git repository):

D:\Development\3rdParties\aws_sdk_cpp\1.8.106\aws-sdk-cpp-1.8.106
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.21.0.windows.1")
-- Building AWS libraries as static objects
-- Generating windows build config
**fatal: not a git repository: 'D:/Development/3rdParties/aws_sdk_cpp/1.8.106/aws-sdk-cpp-1.8.106/.git'**
-- Building project version: 1.8.106
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.14393.
-- The C compiler identification is MSVC 19.27.29111.0
....

Is that OK? Should I ignore this warning?

**Comment by KaibaLopez** [comment]
@Eliyahu-Machluf , it is weird that you're getting this message, my best guess is that the sdk is somehow in an unexpected folder structure.
But anyways yea, that is a git warning and not a cmake or msbuild one, so as long as the project is built successfully I wouldn't worry about it.

**Comment by Eliyahu-Machluf** [comment]
@KaibaLopez,
Thanks for the quick response.
It is good to know I can ignore this error and proceed with my work.

BTW, the error is very simple to reproduce, and does not relate to directory structure:

1. simply download the sources as zip file from https://github.com/aws/aws-sdk-cpp/releases/tag/1.8.106
2. extract the sources to SOURCE_PATH.
2. make directory BUILD
3. cd BUILD
4. run the command cmake SOURCE_PATH

And you'll get the "fatal: not a git repository:" warning at the first 10 lines of cmake output.
