### ISSUE TITLE
Documentation: aws-c-event-stream now requires aws-c-io

### ISSUE THREAD

**Issue by mattcwill** [aws/aws-sdk-cpp#1540]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
When installing dependencies manually, need to account for new aws-c-event-stream dependency on aws-c-io by either installing it as an additional dependency or fixing the version number of aws-c-event-stream (as is done in third-party/CMakeLists.txt)

**SDK version number**
1.8.108

**Platform/OS/Hardware/Device**
Ubuntu 18.04.5

**To Reproduce (observed behavior)**
Follow instructions in README file for installing third-party dependencies manually. When you get to the part about installing aws-c-event-stream, I get the following error:

```
CMake Error at /<path>/lib/cmake/AwsFindPackage.cmake:19 (find_package):
  By not providing "Findaws-c-io.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "aws-c-io",
  but CMake did not find one.

  Could not find a package configuration file provided by "aws-c-io" with any
  of the following names:

    aws-c-ioConfig.cmake
    aws-c-io-config.cmake

  Add the installation prefix of "aws-c-io" to CMAKE_PREFIX_PATH or set
  "aws-c-io_DIR" to a directory containing one of the above files.  If
  "aws-c-io" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:75 (aws_use_package)

```
**Expected behavior**
All dependencies should install with no errors.

**Additional context**
I was going down this path since the automated dependency install insn't working for me (same as #1537). It looks like as of v0.2.1, aws-c-event-stream has a dependency on aws-c-io. Need to either amend the third party dependencies to include aws-c-io, or amend the README instructions to clone v0.1.16 or some other release before that dependency was added.

This could be just me, but even after working around this I can't seem to build aws-cpp-sdk with -DBUILD_DEPS=OFF. I get a bunch of "include could not find load file" errors, but maybe I'm doing something else wrong here.

**Comment by Eliyahu-Machluf** [comment]
Hi,

aws-c-io library requires s2n library which requires openssl and maybe other dependencies.
To avoid all this, I checked out V0.1.6 of aws-c-event-stream, and managed to build this library (with the aws-c-common and aws-checksums dependencies).

Should that be OK for me? I mean can I use version 0.1.6 of this library which is not an up-to-date version? I'm in the process of building AWS CPP SDK version 1.8.106 on Linux.

**Comment by KaibaLopez** [comment]
Hi @mattcwill  and @Eliyahu-Machluf ,

I'll be working on this but probably not in the way you expect... 

Our "current" policy is we don't really support building the dependencies individually, and to be fair any problems you'd have with them would belong in the issue queue but that's kind of different thing, so because of that I'll be removing that section from our README.

For the record though, you are correct, aws-c-event-stream does depend on aws-c-io. 

As for that being ok for you @Eliyahu-Machluf , it should be ok yes, but I would still recommend just letting this SDK build them for you, by default it should but just in case you can set it via cmake flag: `-DBUILD_DEPS=ON`.

**Comment by daniel-fudge** [comment]
Hi @KaibaLopez , thank you for the above information. 

I have the same issue and to give a little background, like many users I am building in an enterprise VPC with no internet access. I would love to just let the SDK build them but as it is currently configured, it tries to clone the dependencies from the internet. This is and always will be impossible for me.

Is it possible to manually download the packages and then let the SDK build from the local copies?

**Comment by KaibaLopez** [comment]
Hi @daniel-fudge ,
So... yes it is possible, as @Eliyahu-Machluf says in his comment, you could build the dependencies individually, just make sure you get the right versions:
* aws-c-common : v0.4.42
* aws-checksums: v0.1.5
* aws-c-event-stream: v0.1.5
then when building the sdk add `-DBUILD_DEPS=OFF -CMAKE_PREFIX_PATH=<deps_install_dir>` to your cmake command.
This way the sdk will not try to git clone the dependencies and will not need internet access to install.
Let me know if this doesn't work for you though.
