### ISSUE TITLE
CURL HTTP2 connections does not work when crosscompiling

### ISSUE THREAD

**Issue by diegonieto** [aws/aws-sdk-cpp#1542]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I'm using Amazon TranscribeStreaming in both PC64 and ARM64 machines.

When crosscompiling the SDK there is a check_c_source_runs CMake sentence that forces to run a CURL code in order to enable its functionality. Since the crosscompiled code is not runnable in the host machine, the checker fails when CURL is actually capable to work with both HTTP2 and TLS Proxy connections. This is affecting to the TranscribeStreaming service.

Pull request: https://github.com/aws/aws-sdk-cpp/pull/1541

**SDK version number**
1.8.105

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Linux PC64 and ARM64 

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
Cross-compile AWS TranscribeStreaming for ARM64. CURL_HAS_H2 is not enabled

**Expected behavior**
CURL_HAS_H2 shoule be enabled

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @diegonieto ,
We have merged your PR, thanks and sorry again for the long wait, we're trying to do better on these.
