### ISSUE TITLE
XML parse error when trying to perform CreateBucket() on the S3 client.

### ISSUE THREAD

**Issue by sunbines** [aws/aws-sdk-cpp#1543]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
aws-adk-cpp
**Describe the question**
I keep getting the following XML parse error when trying to perform CreateBucket() on the S3 client.

```
[DEBUG] 2020-12-21 06:35:32.491 CurlHttpClient [139864302418048] Returned http response code 200
[TRACE] 2020-12-21 06:35:32.491 CurlHttpClient [139864302418048] Response content-length header: 875
[TRACE] 2020-12-21 06:35:32.491 CurlHttpClient [139864302418048] Response body length: 875
[DEBUG] 2020-12-21 06:35:32.491 CurlHttpClient [139864302418048] Releasing curl handle 0x958a20
[DEBUG] 2020-12-21 06:35:32.491 CurlHandleContainer [139864302418048] Releasing curl handle 0x958a20
[DEBUG] 2020-12-21 06:35:32.491 CurlHandleContainer [139864302418048] Notified waiting threads.
[DEBUG] 2020-12-21 06:35:32.491 AWSClient [139864302418048] Request returned successful response.
[TRACE] 2020-12-21 06:35:32.491 AWSClient [139864302418048] Request successful returning.
[ERROR] 2020-12-21 06:35:32.491 AWSClient [139864302418048] Xml parsing for error failed with message XML_ERROR_PARSING_TEXT
[INFO] 2020-12-21 06:35:32.492 CurlHandleContainer [139864302418048] Cleaning up CurlHandleContainer.
[DEBUG] 2020-12-21 06:35:32.492 CurlHandleContainer [139864302418048] Cleaning up 0x94fdb0
[DEBUG] 2020-12-21 06:35:32.492 CurlHandleContainer [139864302418048] Cleaning up 0x958a20
"aws_sdk_2020-12-21-06.log" 912L, 75016C                                                     
```

**Comment by KaibaLopez** [comment]
Hi @sunbines ,
Can you verify that you are using valid characters as part of you bucket name? 
You can check s3 bucket limitations [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html).

If that' not the problem, I'm going to need to see some sample code that reproduces this error since I can not see it from just running our tests.
