### ISSUE TITLE
improve http client traces for CURL and add traces for WinHTTP client.

### ISSUE THREAD

**Issue by Eliyahu-Machluf** [aws/aws-sdk-cpp#1544]
I'm about to commit a PR which improve http client traces for CURL client, and add http client traces for WinHTTP client. I saw you requested to first open a feature request for that, so here it is:

The following is needed relating to http client traces:

1. Enable http client traces to be configured as per client configuration and not as per compilation of the library (currently only if ENABLE_CURL_LOGGING is defined when building the library).

2. For curl traces, do not print the data transferred, as it may contain user private data. Current code (before the suggested code change) prints CURLINFO_DATA_[IN|OUT] information, which contains for example content of files uploaded or downloaded to S3. This is not acceptable by our customers as it harms their privacy, and the suggested code change prints the size of the data only and not the content of the data.

3. Print the http client traces at the most verbose mode, which is 'trace', instead of 'debug' mode.

4. For curl trace, when printing size, add a space between the size and the 'bytes' suffix (for example '1024 bytes' instead of '1024bytes' )

5. Add also WinHTTP traces for Windows build (with the same http client trace flag).

6. When WinHTTP request failed, print also the WinHTTP error code to debug trace. This can help with troubleshooting of network issues on Windows.

**Comment by Eliyahu-Machluf** [comment]
The suggested changes for this feature requested are at PR https://github.com/aws/aws-sdk-cpp/pull/1545

**Comment by KaibaLopez** [comment]
Hi @Eliyahu-Machluf ,
Thanks for the contribution!

**Comment by jmklix** [comment]
Merged: https://github.com/aws/aws-sdk-cpp/pull/2676
