### ISSUE TITLE
Can't Build windows c++ SDK (Failed to build third-party libraries.)

### ISSUE THREAD

**Issue by Shortz79** [aws/aws-sdk-cpp#1547]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [o] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [o] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I am trying to build the aws Sdk for c++ on my machine but it generates the error for third party library. By searching for the similar issues, I already reinstall my git and set in the environment variables. However, the issue still happen.

**SDK version number**
_1.8.112_
**Platform/OS/Hardware/Device**
What are you running the sdk on?
_Win10_
**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
mkdir build
cd build
cmake ..\aws-sdk-cpp -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3" -DBUILD_SHARED_LIBS=ON
**Expected behavior**
Expected to build with no failures
**Logs/output**

-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.29.2.windows.3")
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating windows build config
-- Building project version: 1.8.112
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
-- The C compiler identification is MSVC 19.28.29335.0
-- The CXX compiler identification is MSVC 19.28.29335.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/aws/build/.deps
Microsoft (R) Build Engine version 16.8.2+25e4d540b for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Creating directories for 'AwsCCommon'
  Performing download step (git clone) for 'AwsCCommon'
  Cloning into 'AwsCCommon'...
  Note: switching to 'v0.4.42'.

  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.

  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:

    git switch -c <new-branch-name>

  Or undo this operation with:

    git switch -

  Turn off this advice by setting config variable advice.detachedHead to false

  HEAD is now at fa67d3b IO handle ulimit stuff. (#637)
  No update step for 'AwsCCommon'
  No patch step for 'AwsCCommon'
  Performing configure step for 'AwsCCommon'
  -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
  -- The C compiler identification is MSVC 19.28.29335.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
  -- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Failed
  -- Performing Test AWS_HAVE_MSVC_MULX
  -- Performing Test AWS_HAVE_MSVC_MULX - Failed
  -- Performing Test AWS_HAVE_GCC_INLINE_ASM
  -- Performing Test AWS_HAVE_GCC_INLINE_ASM - Failed
  -- Performing Test AWS_HAVE_EXECINFO
  -- Performing Test AWS_HAVE_EXECINFO - Failed
  -- Performing Test HAVE_M_AVX2_FLAG
  -- Performing Test HAVE_M_AVX2_FLAG - Success
  -- Performing Test HAVE_AVX2_INTRINSICS
  -- Performing Test HAVE_AVX2_INTRINSICS - Success
  -- Performing Test HAVE_MM256_EXTRACT_EPI64
  -- Performing Test HAVE_MM256_EXTRACT_EPI64 - Success
  -- Performing Test HAVE_MAY_I_USE
  -- Performing Test HAVE_MAY_I_USE - Failed
  -- Performing Test HAVE_BUILTIN_CPU_SUPPORTS
  -- Performing Test HAVE_BUILTIN_CPU_SUPPORTS - Failed
  -- Performing Test HAVE_MSVC_CPUIDEX
  -- Performing Test HAVE_MSVC_CPUIDEX - Success
  -- Looking for stdint.h
  -- Looking for stdint.h - found
  -- Looking for stdbool.h
  -- Looking for stdbool.h - found
  -- Performing Test HAS_WGNU
  -- Performing Test HAS_WGNU - Failed
  -- Performing Test HAVE_SYSCONF
  -- Performing Test HAVE_SYSCONF - Failed
  -- Performing Test HAS_SANITIZERS
  -- Performing Test HAS_SANITIZERS - Failed
  -- Building SIMD base64 decoder
  -- Packaging is only supported on Linux
  -- Configuring done
CUSTOMBUILD : CMake error : install(EXPORT "aws-c-common-targets" ...) includes target "aws-c-common" more than once in the export set. [C:\aws\build\.deps\AwsCCommon.vcxproj]
  -- Generating done
  CMake Generate step failed.  Build files cannot be regenerated correctly.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: Custom build for 'C:\aws\build\.deps\CMakeFiles\2d61e8da1a13640b5bca65a95c8d6ea8\AwsCCommon-mkdir.rule;C:\aws\build\.deps\CMakeFiles\2d61e8da1a13640b5bca65a95c8d6ea8\AwsCCommon-download.rule;C:\aws\build\.deps\CMakeFiles\2d61e8da1a13640b5bca65a95c8d6ea8\AwsCCommon-update.rule;C:\aws\build\.deps\CMakeFiles\2d61e8da1a13640b5bca65a95c8d6ea8\AwsCCommon-patch.rule;C:\aws\build\.deps\CMakeFiles\2d61e8da1a13640b5bca65a95c8d6ea8\AwsCCommon-configure.rule;C:\aws\build\.deps\CMakeFiles\2d61e8da1a13640b5bca65a95c8d6ea8\AwsCCommon-build.rule;C:\aws\build\.deps\CMakeFiles\2d61e8da1a13640b5bca65a95c8d6ea8\AwsCCommon-install.rule;C:\aws\build\.deps\CMakeFiles\1a66176725b08503af322d5bb7891b72\AwsCCommon-complete.rule;C:\aws\build\.deps\CMakeFiles\a3309a4daa5e09eca74dc6e2ec0c1d08\AwsCCommon.rule' exited with code 1. [C:\aws\build\.deps\AwsCCommon.vcxproj]
  Creating directories for 'AwsChecksums'
  Performing download step (git clone) for 'AwsChecksums'
  Cloning into 'AwsChecksums'...
  Note: switching to 'v0.1.5'.

  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.

  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:

    git switch -c <new-branch-name>

  Or undo this operation with:

    git switch -

  Turn off this advice by setting config variable advice.detachedHead to false

  HEAD is now at 519d6d9 Don't return 0 on arm please (#22)
  No update step for 'AwsChecksums'
  No patch step for 'AwsChecksums'
  Performing configure step for 'AwsChecksums'
  -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
  -- The C compiler identification is MSVC 19.28.29335.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Configuring done
CUSTOMBUILD : CMake error : install(EXPORT "aws-checksums-targets" ...) includes target "aws-checksums" more than once in the export set. [C:\aws\build\.deps\AwsChecksums.vcxproj]
  -- Generating done
  CMake Generate step failed.  Build files cannot be regenerated correctly.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: Custom build for 'C:\aws\build\.deps\CMakeFiles\c287eb571de44408f0ab5b2631988ada\AwsChecksums-mkdir.rule;C:\aws\build\.deps\CMakeFiles\c287eb571de44408f0ab5b2631988ada\AwsChecksums-download.rule;C:\aws\build\.deps\CMakeFiles\c287eb571de44408f0ab5b2631988ada\AwsChecksums-update.rule;C:\aws\build\.deps\CMakeFiles\c287eb571de44408f0ab5b2631988ada\AwsChecksums-patch.rule;C:\aws\build\.deps\CMakeFiles\c287eb571de44408f0ab5b2631988ada\AwsChecksums-configure.rule;C:\aws\build\.deps\CMakeFiles\c287eb571de44408f0ab5b2631988ada\AwsChecksums-build.rule;C:\aws\build\.deps\CMakeFiles\c287eb571de44408f0ab5b2631988ada\AwsChecksums-install.rule;C:\aws\build\.deps\CMakeFiles\1a66176725b08503af322d5bb7891b72\AwsChecksums-complete.rule;C:\aws\build\.deps\CMakeFiles\a3309a4daa5e09eca74dc6e2ec0c1d08\AwsChecksums.rule' exited with code 1. [C:\aws\build\.deps\AwsChecksums.vcxproj]
CMake Error at CMakeLists.txt:224 (message):
  Failed to build third-party libraries.

-- Configuring incomplete, errors occurred!

**Comment by KaibaLopez** [comment]
Hi @Shortz79 ,
This error: 
```
CMake error : install(EXPORT "aws-checksums-targets" ...) includes target "aws-checksums" more than once in the export set. [C:\aws\build.deps\AwsChecksums.vcxproj]
```
Is a known issue on cmake 3.19, can you verify that's the case for you too? If so, try installing cmake 3.18 instead, that should fix it for you.

**Comment by Shortz79** [comment]
Hi @KaibaLopez 
Thanks for hearing that, I successfully built the aws lib by using cmake version 3.18.5.
