### ISSUE TITLE
How to support ipv6 address

### ISSUE THREAD

**Issue by Andy6Loda** [aws/aws-sdk-cpp#1549]
**Is your feature request related to a problem? Please describe.**
1.It can not work when i set Aws::Client::ClientConfiguration cfg.endpointOverride one IPV6 address,  

**Describe the solution you'd like**
I want to use aws-sdk-cpp in IPv6 environment

In IPV4 
cfg.endpointOverride = "http://192.168.32.54:10001";   //is ok

In IPV6 i try :
test-1: minio-mc  is ok
[root@host47 bin]# ./mc config host list
ipv6 
  URL       : http://[2001:da8:2004:1000:202:116:160:44]:17701
  AccessKey : minioadmin
  SecretKey : minioadmin
  API       : s3v4
  Path      : auto

[root@host47 bin]# ./mc ls ipv6
[2020-12-30 18:01:20 CST]     0B test/

test-2:
cfg.endpointOverride = "http://[2001:da8:2004:1000:202:116:160:44]:17701"
>> CreateMultipartUpload error: : curlCode: 6, Couldn't resolve host name

test-3:
cfg.endpointOverride = "http://2001:da8:2004:1000:202:116:160:44:17701"
>>CreateMultipartUpload error: : curlCode: 7, Couldn't connect to server with address : 0.0.7.209 with address : 0.0.7.209

I couldn't sort out the IP decision  =.=||

**Comment by KaibaLopez** [comment]
Hi @Andy6Loda ,
So ipv6 is supported only in certain services in the SDK and s3 is not one of them yet, we are working on it though.

**Comment by Andy6Loda** [comment]
thanks  @KaibaLopez

**Comment by Andy6Loda** [comment]
Hi @KaibaLopez ,
Today i found that we can use the domain name avoid this problem. Just need set DNS-server or /etc/hosts
```
[root@localhost ~]# ping6 aaabbbccc
PING aaabbbccc(aaabbbccc (2001:da8:2004:1000:202:116:160:99)) 56 data bytes
64 bytes from aaabbbccc (2001:da8:2004:1000:202:116:160:99): icmp_seq=1 ttl=64 time=0.189 ms


DXN Run Environment SetUP
[----------] 1 test from SingelTest
[ RUN      ] SingelTest.ListObjects
#######http://aaabbbccc:17702
test  2021-01-28T14:04:04Z
[       OK ] SingelTest.ListObjects (9 ms)
[----------] 1 test from SingelTest (9 ms total)

[----------] Global test environment tear-down
DXN Run Environment TearDown
```

**Comment by Pradnyeshp** [comment]
Is this supported in latest release ?
