### ISSUE TITLE
SegFault on Jemalloc on a Simple use case

### ISSUE THREAD

**Issue by shuzhang1989** [aws/aws-sdk-cpp#155]
Hi, I constructed a very simple getObjectRequest:
`Aws::S3::Model::GetObjectRequest getObjectRequest;
Aws::String bucket = "my-bucket";
getObjectRequest.SetBucket(bucket);`

Then program crashed at the SetBucket() method. gdb tells:
> Program received signal SIGSEGV, Segmentation fault.
> 0x00007ffff6f186f4 in free () at include/jemalloc/internal/arena.h:511
> 511     include/jemalloc/internal/arena.h: No such file or directory.

I built the SDK without local custom memory management flag.

Is there any idea on it? Looks somehow the sdk screws with using jemalloc. (BTW my other part of the program relies on jemalloc, but even i removed jemalloc linking option, it still segfaults)

**Comment by JonathanHenson** [comment]
You built the SDK without Custom memory management, but did you tell your program not to use custom memory management via. -DAWS_CUSTOM_MEMORY_MANAGEMENT=0

**Comment by shuzhang1989** [comment]
@JonathanHenson thanks for the reply. No i didn't, should i add this flag into cmake?

**Comment by JonathanHenson** [comment]
It isn't a cmake flag perse, 

See this blog post:
https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/

This will make your life much easier, and we updated this for this very reason.

If you are manually handling your builds (e.g. invoking gcc directly) you need to pass -DAWS_CUSTOM_MEMORY_MANAGEMENT=0 as a compiler flag to the build of YOUR application.

**Comment by JonathanHenson** [comment]
wait, did you explictly turn custom memory management off? Or did you not specify it? It is on by default, in that case you need to pass -DAWS_CUSTOM_MEMORY_MANAGEMENT=1 to your compiler. As before the blog post I linked will make this problem invisible to you.

**Comment by shuzhang1989** [comment]
I didn't write custom memory management and i hope it can use the default STL based solution. I tried to rebuild using cmake, it showed me:
`Custom memory management enabled; stl objects now using custom allocators`
So the question is how should can i turn it off? -DAWS_CUSTOM_MEMORY_MANAGEMENT=0 doesn't work in cmake case, here is my cmake command:

`cmake -DCMAKE_BUILD_TYPE=Release  -DAWS_CUSTOM_MEMORY_MANAGEMENT=0 .`

**Comment by shuzhang1989** [comment]
Okay, figured out how to turn this off - by passing ` -DCUSTOM_MEMORY_MANAGEMENT` :)
