### ISSUE TITLE
Properly Document Compilation Steps

### ISSUE THREAD

**Issue by ChrisCates** [aws/aws-sdk-cpp#1552]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
### Describe the bug
It seems very clear that hundreds of developers have had a lot of issues dealing with the third party dependencies for this project. Pretty much every single one of them could have still ran:

```bash
sudo cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DBUILD_DEPS=ON
```

And still not get the third party deps to install. Quite frankly, it's a bit disappointing to see the maintainer not properly describe how to resolve these issues with the third party libraries, despite how **frequently** people open issues in regards to them.

### SDK version number
v1.8.117

### Platform/OS/Hardware/Device
Ubuntu 20.04

### To Reproduce (observed behavior)
Compile it on any Linux Debian or RHEL machine... Literally...

### Solution

**Please**, *please* provide proper guidance for developers so they can compile the project on their machine properly. The following script I've made will resolve any and all issues in regards to third party dependencies.

```bash
#!/bin/bash

# AWS C Common Deps
git clone https://github.com/awslabs/aws-c-common
cd aws-c-common

mkdir build
cd build

cmake ..
sudo make
sudo make install

cd ../..
rm -rf aws-c-common

# AWS Checksums Deps
git clone https://github.com/awslabs/aws-checksums
cd aws-checksums

mkdir build
cd build

cmake .. -DCMAKE_INSTALL_LIBDIR="/usr/local/lib"
sudo make && make install

cd ../..
rm -rf aws-checksums

# AWS C Event Stream Deps
git clone https://github.com/awslabs/aws-c-event-stream
cd aws-c-event-stream

git fetch origin v0.1.6
git checkout v0.1.6

mkdir build
cd build

cmake .. -DCMAKE_INSTALL_LIBDIR="/usr/local/lib"
sudo make && make install

cd ../..
rm -rf aws-c-event-stream
```

I've provided this out of my own good will since I've seen several issues closed and hundreds of developers have their issue not resolved in regards to this. And, simply just want to make sure that future developers don't spend hours scratching their head as to why it won't compile.

**Comment by wps132230** [comment]
Thank you for reporting this issue!
We've already known the hard part to build and install third party dependencies are working on a better solution to consume dependencies.
We will let you know when it's available.

**Comment by ChrisCates** [comment]
@wps132230, I encourage you to reach out to me if you need help implementing better documentation for compilation.

This shouldn't be something obtuse, and, maintainers **definitely** should not be closing issues when a developer's compilation fails. We are paying for this product and service.

Thank you.

**Comment by KaibaLopez** [comment]
Hi @ChrisCates ,
I do agree that we could make documentation better,  in our defense though, I guess it is hard to see or really not important to a new user, but there's story on the current state of things, hence related issues being closed and why our priority is a better solution to consuming them rather than documentation fixes. 
But yea I'll be updating the Readme to completely remove building the dependencies since that is not really supported anymore.

**Comment by ChrisCates** [comment]
@KaibaLopez, the most important thing is acknowledgement!

That's all that matters. Hopefully I motivated you guys to have a faster turnaround on the refactor.

Furthermore, simply having this issue exist and the `.sh` script I've provided should be more than enough for any future devs that need to "hack" their way to a compile + install of the SDK.
