### ISSUE TITLE
list all agents with current status and contact state

### ISSUE THREAD

**Issue by rafayhameed** [aws/aws-sdk-cpp#1554]
I am using Kinesis stream to get live events of agent activities. I get the agent status from "CurrentAgentSnapshot"->"AgentStatus".
I am using C++ SDKs for my application. 

On startup of my application, I need the ID and ARN of all logged in agents with their current status(available or offline) and contact state(connecting, connected or ended) against specific routing profile, queue or instance. Is there any API for this? I could not find in connect C++

**Comment by KaibaLopez** [comment]
hi @rafayhameed ,
Not sure i quite follow what you're asking for, could you maybe provide minimal code on what you got and what you're trying to do or what you got so far?

**Comment by rafayhameed** [comment]
Hi @KaibaLopez ,
I have configured amazon connect instance and configured a data stream. I am using aws-sdk-cpp kinesis client to get agent events from configured kinesis stream.
Aws::Kinesis::Model::GetRecordsOutcome getRecordsResult = kinesisClient.GetRecords(getRecordsRequest);


I am using this code for getting the list of users configured in connect :

Aws::Connect::ConnectClient connectClient(clientCred, clientConfig);
Aws::Connect::Model::ListUsersRequest req;	
req.SetInstanceId(instanceID.c_str());
Aws::Connect::Model::ListUsersOutcome usersOutcome = connectClient.ListUsers(req);

It returns only the ID, username and ARN for Users. I need the  current status(available or offline) and contact state(connecting, connected or ended) of all logged in users configured in my connect instance.

**Comment by KaibaLopez** [comment]
Hi @rafayhameed ,
I don't think the connect service api supports such a call, I can't find anything regarding "user status". The closest thing I found would be [GetCurrentMetricData](https://docs.aws.amazon.com/connect/latest/APIReference/API_GetCurrentMetricData.html). 
Which could return the number of available Agents if that's the metric set for it.
