### ISSUE TITLE
Partial results callbacks not triggering with TranscribeStreamingServiceClient

### ISSUE THREAD

**Issue by Tudi** [aws/aws-sdk-cpp#1555]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I tried to follow through this tutorial : https://aws.amazon.com/blogs/developer/real-time-streaming-transcription-with-the-aws-c-sdk/
My expectations are to receive partial results as I use the microphone. I do not get partial results. This code needs modifications in order to get partial results ( maybe even final ones ? ). Please update the code or provide an alternative for live transcribing.
My final goal is to have speaker labels working, but if I close the audio stream, speaker labels seem to reset or get reassigned randomly(speaker 1 becomes speaker 0).

**SDK version number**
1.8.114

**Platform/OS/Hardware/Device**
Windows 10

**To Reproduce (observed behavior)**
Follow the instructions from here :
https://aws.amazon.com/blogs/developer/real-time-streaming-transcription-with-the-aws-c-sdk/
when starting the application, nothing is printed on the console until you close the microphone

**Expected behavior**
When talking into the microphone, periodically, partial(final) results are printed on the console

**Logs/output**
No special setup is required.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**
None

**Comment by Tudi** [comment]
Just to clear up doubt that I'm unable to run the test. Also tested Java, Javascript and python version. All 3 work fine. It's only c++ code that does not work asynchronously.
Right now I'm integrating the python implementation into the c++ application. It's a temporary workaround until a solution is provided for the c++ version.

**Comment by Tudi** [comment]
Attaching 2 logs. Maybe helps debugging as I was told this issue is not present in MAC version. Maybe there is some specific setup I have that makes this behavior exist.  Windows 10 ? Visual studio 2019 ? Windows SDK version ? Any details ? Help ?

[aws_sdk_2021-01-20-20_1.log](https://github.com/aws/aws-sdk-cpp/files/5847734/aws_sdk_2021-01-20-20_1.log)

[aws_sdk_2021-01-20-20.log](https://github.com/aws/aws-sdk-cpp/files/5847733/aws_sdk_2021-01-20-20.log)

**Comment by wps132230** [comment]
Hi there.
That's the limitation of Http libraries (WinHttp, WinINet) we are using on Windows.
Http/2 multiplexing is not fully supported, then you will not get the response until the stream closes.
As the short term workaround, we may test libcurl on Windows to see if it works for this case.
