### ISSUE TITLE
Unmarshaling(converting) DynamoDB JSON outputs to regular JSON.

### ISSUE THREAD

**Issue by dominique120** [aws/aws-sdk-cpp#1556]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Windows 10 x64, Visual Studio Enterprise 2019. Deploys to t4g.nano on AMI2.

**Describe the question**
Is there a way to convert the output of DynamoDBs JSON to regular JSON with my data in it? 

Currently ```SerializeAttribute()``` for ```AttributeValues``` as well as ```WriteReadable()``` and ```WriteReadable()``` on JSON views will write JSON data, however its in Dynamo's own way. Is there a way to convert this JSON(or the result of a GetItemOutcome for example) to regular JSON? I know its possible in the Javascript API with ```AWS.DynamoDB.Converter.unmarshall``` and in Python with ```TypeDeserializer.deserialize```(in boto3).

This is what I mean:
```
{
        "M":    {
                "Active":       {
                        "N":    "1"
                },
                "ClientId_uuid":        {
                        "S":    "uuid"
                },
                "District":     {
                        "S":    "district"
                },
                "FirstName":    {
                        "S":    "fn"
                },
                "Intrest":      {
                        "S":    "intrests"
                },
                "LastNames":    {
                        "S":    "last names"
                },
                "PrimaryAddress":       {
                        "S":    "address"
                },
                "PrimaryPhone": {
                        "S":    "123456"
                }
        }
}
```
Thanks!

**Comment by KaibaLopez** [comment]
Hi @dominique120 ,
So the short answer is no, we don't have a deserializer for jsonvalues or dynamodb objects. We only provide serializing to Json objects.
You'd basically have to build the json as a string from the map generated by the response...

**Comment by dominique120** [comment]
Well thats unfortunate. 

I went ahead and gave it a go for my specific case and here is something a cobbled up. I'm leaving this here for anyone that encounters a similar situation. I have not tested it thoroughly though. It uses nlohmann json library since I'm not familiar with the SDKs json parser. Hopefully it will be of use to someone.

This issue can be closed or can be left open as a feature request.

```c++
nlohmann::json DynamoDB::parse_type(Aws::DynamoDB::Model::AttributeValue attr) {
	if (attr.GetType() == Aws::DynamoDB::Model::ValueType::STRING) {
		return attr.GetS();
	}
	else if (attr.GetType() == Aws::DynamoDB::Model::ValueType::NUMBER) {
		return attr.GetN();
	}
	else if (attr.GetType() == Aws::DynamoDB::Model::ValueType::BOOL) {
		return attr.GetBool();
	}
	else if (attr.GetType() == Aws::DynamoDB::Model::ValueType::ATTRIBUTE_MAP) {
		nlohmann::json json;
		auto type = attr.GetM();
		for (const auto& element : type) {
			json[element.first.c_str()] = parse_type(*element.second);			
		}
		return json;
	}	
	else if (attr.GetType() == Aws::DynamoDB::Model::ValueType::ATTRIBUTE_LIST) {
		nlohmann::json json = nlohmann::json::array();
		auto type = attr.GetL();
		for (const auto& element : type) {
			nlohmann::json obj = parse_type(*element);
			json.push_back(obj);
		}		
		return json;
	}
	else if (attr.GetType() == Aws::DynamoDB::Model::ValueType::NULLVALUE) {
		return nullptr;
	}
	else {
		return nullptr;
	}
}
```
Usage:
```c++
		nlohmann::json result_out;
		const Aws::Map<Aws::String, Aws::DynamoDB::Model::AttributeValue>& item = result.GetResult().GetItem();

		if (!item.empty()) {			
			for (const auto& i : item) {
				result_out[i.first.c_str()] = parse_type(i.second);
			}			
		}
```
nlohmann json has implicit conversion for some types so its possible to create a json object and later assign this a key. For arrays and objects its a bit trickier and for arrays an empty json array is created in which json objects are added.  Note that all DynamoDB types are supported.

**Comment by KaibaLopez** [comment]
Wait, I may have misunderstood your problem... Or I may be still a little confused here but just to be clear, would something like this work for you?
```cpp
        auto obj = result.GetResult().GetItem();
        Aws::Utils::Json::JsonValue jsonObj(obj);
```

**Comment by dominique120** [comment]
What type of object should ```obj``` be?

In my case ```result``` is a ```GetItemOutcome``` and ```result.GetResult().GetItem()``` returns a map of strings and AttributeValues. VS shows me an error telling me there is no such constructor and indeed I dont see a constructor for maps of any type.

This is what I have:
```c++
	const Aws::DynamoDB::Model::GetItemOutcome& result = dynamo_client.GetItem(req);
	Aws::Map<Aws::String, Aws::DynamoDB::Model::AttributeValue> obj = result.GetResult().GetItem();
	Aws::Utils::Json::JsonValue jsonObj(obj);
        //                                            -------^ No constructor matches obj's type                                    
```
I'm using version 1.8.83 of the SDK

**Comment by KaibaLopez** [comment]
Sorry @dominique120 ,
My bad, I had a overloaded constructor left over on my branch from when I tried to implement something similar, but yea it wouldn't work the same way.
Anyways sorry for the confusion, thanks for bringing this up and the workaround you coded up, I'm going to be marking this for closure as I don't think there is anything else to do about it for now.
