### ISSUE TITLE
AWS SDK CPP not working with IAM Roles on windows, kindly help how to do it

### ISSUE THREAD

**Issue by shivanshtech** [aws/aws-sdk-cpp#1557]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
When i print secret details using the code , it is printing if i pass the aws access key and secret key.
But when i want to do without credentials ie with the use of IAM ROLES, it is working with linux but i want to do on windows , but now working.

**Platform/OS/Hardware/Device**
What are you running the sdk on? Visual studio 2017 (Windows)

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

**Expected behavior**
I pass aws access key, secret key in AWSCredentials class and is getting the o/p but not getting o/p with aws iam roles.

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

**Comment by KaibaLopez** [comment]
to be clear here, you are saying the error only happens on Windows machines correct?
Can you show me code on how you're trying to use them? (Don't post any sensitive information like secret keys or such, just the code).
