### ISSUE TITLE
S3 HeadObject(request) gives "No response body" when using AWS_GLOBAL region

### ISSUE THREAD

**Issue by TomateSoft** [aws/aws-sdk-cpp#1558]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Using an existing valid object situated in a S3 bucket (in `eu-central-1`) **AWS_GLOBAL** won't help `HeadObject` requests redirect with the correct region and instead will return the **HTTP** error 400 with the following message "_No response body_." (this is the full message returned by `error.GetMessage()`, so no information about being able to use a different region as you would expect to get from a wrongly configure region for `GetObject` requests).

**SDK version number**
1.8.110

**Platform/OS/Hardware/Device**
CentOS 7, 3.10.0-1160.11.1.el7.x86_64

**To Reproduce (observed behavior)**
Bucket needs to be in a different region than us-east-1 (due to AWS_GLOBAL implementation)
```
ClientConfiguration cc = ClientConfiguration("default");
cc.scheme = Aws::Http::Scheme::HTTP;
cc.maxConnections = 500;
cc.region = Aws::Region::AWS_GLOBAL;
S3Client cli(cc);
HeadObjectRequest request;
request.WithBucket(String(bucket.c_str()));
request.WithKey(String(path.c_str()));
auto head_response = cli.HeadObject(request);
if (!head_response.IsSuccess()) {
    printf("%s\n", head_response.GetError().GetMessage().c_str());
    printf("%d\n",head_response.GetError().GetResponseCode());
}
exit(0)
```

**Expected behavior**
The HeadObject outcome should be successful with AWS_GLOBAL.

**Logs/output**
[aws_sdk_2021-01-07-09_sanitized.log](https://github.com/aws/aws-sdk-cpp/files/5781227/aws_sdk_2021-01-07-09_sanitized.log)

**Comment by KaibaLopez** [comment]
Hi @TomateSoft ,
Hmmm, yea I can see why this is happening, my only issue is that it is kind of in between a bug and feature request... like it's a feature we should be supporting but haven't implemented, guess I'll just label it as both and move on.

For now though, and in case this is blocking you, it seems like pretty much no s3 object operation ( headobject, getobject, etc.) supports` aws-global` as a valid region, so you would have to specify region on the client Configuration whenever you are making one.  Bucket operations seem to work just fine though.

Anyways, thanks for bringing it up to us!

**Comment by TomateSoft** [comment]
Hey @KaibaLopez thank you for your quick answer!

This was blocker for me but I have a solution, I first started doing the region change manually (I have to support cross region s3 operations) and will revert back to that code in the meantime.

I think the biggest issue with the current situation is the error message in this case: I can't recover the right region on a HeadObject when using global and since I'm using a pool of clients with the same configuration I can't branch inside the worker that will do HeadObject and switch its region beforehand.
I have to revert my code and use set regions for all the clients and make sure I dynamically switch my region on error for all the type of s3 operations I might do (for example GetObject).

**Comment by corpoverlords** [comment]
This is still a bug
