### ISSUE TITLE
SQS::Model::ReceiveMessageRequest AttributeNames functions using incorrect enum for attributes list

### ISSUE THREAD

**Issue by marack** [aws/aws-sdk-cpp#1564]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
The API docs for the SQS ReceiveMessage request takes an "AttributeName" parameter which determines the list of attributes that should be returned with each message (such as "MessageGroupId").  See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html.

The C++ SDK model class for this request implements this parameter with the functions `SetAttributeNames`, `WithAttributeNames` etc.  These functions take an argument based on the type `QueueAttributeName`.  See http://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_s_q_s_1_1_model_1_1_receive_message_request.html.

This seems to be the incorrect type since the `QueueAttributeName` enum is a different set of attributes to those listed in both the API and SDK documents ("MessageGroupId" is not available).

**SDK version number**
1.8.126, version1.9, master

**Additional context**
As a temporary workaround the `QueueAttributeName` enum type includes an `All` value, which can be used to generate valid output since this value is present in both lists of names.  This comes at the cost of returning more attributes than desired/needed.

**Comment by KaibaLopez** [comment]
Hi @marack ,
Thanks for bringing this up to us, and yea you're right that the `QueueAttributeName` enum does not match the api reference, we'll look into that.
