### ISSUE TITLE
Aws::S3::S3Client::GetObject Segmentation Fault 

### ISSUE THREAD

**Issue by rvernica** [aws/aws-sdk-cpp#1565]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**

Segmentation fault on `Aws::S3::S3Client::GetObject`. It happens occasionally but not consistently. I large test suite will eventually trigger one. Here is what I could see with `gdb`:

```
Thread 4 "foo" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f231e6fd700 (LWP 39842)]
0x00007f231f4a4430 in Aws::Http::CreateHttpRequest(Aws::Http::URI const&, Aws::Http::HttpMethod, std::function<std::iostream* ()> const&) (uri=..., 
    method=method@entry=Aws::Http::HttpMethod::HTTP_GET, streamFactory=...)
    at /aws-sdk-cpp-1.8.3/aws-cpp-sdk-core/source/http/HttpClientFactory.cpp:200
200	            return GetHttpClientFactory()->CreateHttpRequest(uri, method, streamFactory);

(gdb) p uri
$1 = (const Aws::Http::URI &) @0x7f231e6f6a20: {m_scheme = Aws::Http::Scheme::HTTPS, m_authority = "bar.s3.us-east-1.amazonaws.com", m_port = 443, 
  m_path = "/taz", m_queryString = ""}

(gdb) p method
$2 = Aws::Http::HttpMethod::HTTP_GET

(gdb) p streamFactory
$3 = (const Aws::IOStreamFactory &) @0x7f231e6f7ae8: {<std::_Maybe_unary_or_binary_function<std::basic_iostream<char, std::char_traits<char> >*>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {
        _M_object = 0x7f231f44b430 <Aws::Utils::Stream::DefaultResponseStreamFactoryMethod()>, 
        _M_const_object = 0x7f231f44b430 <Aws::Utils::Stream::DefaultResponseStreamFactoryMethod()>, 
        _M_function_pointer = 0x7f231f44b430 <Aws::Utils::Stream::DefaultResponseStreamFactoryMethod()>, 
        _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x7f231f44b430 <Aws::Utils::Stream::DefaultResponseStreamFactoryMethod()>, this adjustment 139788811205392}, _M_pod_data = "0\264D\037#\177\000\000\020{o\036#\177\000"}, 
    _M_manager = 0x7f231f46ef90 <std::_Function_base::_Base_manager<std::iostream* (*)()>::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)>}, _M_invoker = 0x7f231f46ef80 <std::_Function_handler<std::iostream* (), std::iostream* (*)()>::_M_invoke(std::_Any_data const&)>}
```

**SDK version number**
`1.8.3`

**Platform/OS/Hardware/Device**
Ubuntu Xenial

**To Reproduce (observed behavior)**
Very difficult to reproduce. I have a large test suite for the end goal code which runs a distributed system and eventually triggers it. It does not happen consistently. 2 out of 3 runs of the test suite would trigger it.

**Additional context**
Possibly related to #1368

**Comment by KaibaLopez** [comment]
@rvernica ,
I'm a bit unclear on "I large test suite will eventually trigger one". 
Could you provide minimal sample code to reproduce the bug (even if not consistently)?

**Comment by rvernica** [comment]
Unfortunately, I'm not able to provide a repro at the time. The entire stack is way to complicated to pull a sample out of it.

**Comment by KaibaLopez** [comment]
Hmmm, the 2 out of 3 is worrisome but I don't know how to approach this....
Can you maybe provide logs from when it succeeds and when it fails? 
```
Aws::SDKOptions options;
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
```
That should give me at least a better idea of what the sdk is trying to do.

**Comment by rvernica** [comment]
I will enable logging and try to provide the log. At a high level here is how the SDK is used.
1. SDK is integrated in a plug-in
2. The plug-in is used in a distributed DB
3. When needed the distributed DB calls the plug-in
4. The plug-in runs Aws::InitAPI, makes S3 calls, and, when done, runs Aws::ShutdownAPI
Few questions:
1. Do you seen any issue with running Aws::InitAPI multiple times during the life of a process?
2. If we force Aws::InitAPI to run only once pre-process lifetime, is there a chance that the memory usage will grow with time or that stored state would become stale? The distributed DB process could be running for months.
3. How much work are InitAPI and ShutdownAPI doing? Could a race condition where ShutdownAPI is still running while a new InitAPI starts could cause this Segmentation Fault?

**Comment by KaibaLopez** [comment]
Hi @rvernica ,
Sorry for the delay, I need to investigate more to be able to give you complete answers for these but maybe my kind of quick "first impression" answers are enough? Let me know either way.

1. I guess it kind of depends on how you're calling it, but the idea is that they wouldn't be called multiple times, they should be called once.
2. It should not, but this is the one I need to investigate and test first before I give you a proper answer.
3. Init and Shutdown are not intended to run in parallel at any point, they are definitely not thread safe, so yea such a situation could have all sorts of problems like segmentation fault. 

I'll let you know what I find about the second question, but if you were expecting init and shutdown to be thread safe, then that is not a supported feature and the seg fault would be kind of expected behavior.

**Comment by rvernica** [comment]
Thank you for looking into this. We are using the approach described in question (2) where we only run `InitAPI` once per process. The test suite passes but at times we are seeing `curlCode: 6, Couldn't resolve host name.` from the AWS SDK. The instance we are running the tests from is an EC2 instance. Once we re-try the tests, they work fine. Is this something that could be related to `InitAPI`?
