### ISSUE TITLE
Does `AUTORUN_UNIT_TESTS` and `ENABLE_TESTING` CMake options work?

### ISSUE THREAD

**Issue by disa6302** [aws/aws-sdk-cpp#1567]
Confirm by changing [ ] to [x] below:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on? 
Ubuntu

**Describe the question**
I am trying to use ENABLE_TESTING=OFF to disable testing. I see it is enabled by default. However, I would like to know if running unit tests and other tests can be disabled.

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
Hi @disa6302 ,
Yes, setting the camke parameter `-DENABLE_TESTING=OFF ` should have it so it doesn't run the SDK tests.

**Comment by disa6302** [comment]
@KaibaLopez ,

Thank you for the response. Can you explain what the difference between the 2 options are? I saw the `CMakeLists.txt` File for an explanation, but did not get clarity out of it.

**Comment by KaibaLopez** [comment]
Right, so:
* `-DENABLE_TESTING` decides whether or not to build the services integration-tests.
* `-DAUTORUN_UNIT_TESTS` is whether or not it will run these tests. (This gets ignored if enable testing is set to off btw).

**Comment by disa6302** [comment]
Cool. That makes sense. Thank you! Closing the ticket
