### ISSUE TITLE
Unable to build S3 on macOS with a target version set to 10.12

### ISSUE THREAD

**Issue by loic-ps** [aws/aws-sdk-cpp#1570]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**

**SDK version number**

Since 1.7.365

**Platform/OS/Hardware/Device**
What are you running the sdk on?

macOS. 10.14 (xcode 10.2.1)

**To Reproduce (observed behavior)**

- Build `S3` with cmake options `CMAKE_OSX_DEPLOYMENT_TARGET` set to `10.12`
=> The build fail trying to use unavailable API.

The problem seems to be related to https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/include/aws/core/utils/crypto/commoncrypto/CryptoImpl.h#L13. 

Those tests are based on the maximum supported API, instead of the minimal targeted API (in my case 10.12).

As a result, feature availability tests (e.g. https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/utils/crypto/commoncrypto/CryptoImpl.cpp#L504) have not the good behavior.

**Expected behavior**

The build succeed, using the old macOS Crypto API.

**Logs/output**

Build logs:

```
      newer [-Werror,-Wunguarded-availability-new]
                status |= CCCryptorGCMSetIV(m_encryptorHandle, m_initializationVector.GetUnderlyingData(), m_initializationVector.GetLength());
                          ^~~~~~~~~~~~~~~~~
CommonCryptorSPI.h:217:1: note: 'CCCryptorGCMSetIV' has been marked as being introduced in
      macOS 10.13 here, but the deployment target is macOS 10.12.0
```

**Additional context**

None

**Comment by KaibaLopez** [comment]
Hi @loic-ps ,
Yea I think you're right.... we'll take a look into it, thanks for bringing it up to us!

**Comment by sdavtaker** [comment]
Hi @loic-ps 
The version you mention of OSX is long deprecated by Apple by now, however I found a way to get a build for it from a build in travis:  https://travis-ci.com/github/sdavtaker/aws-sdk-cpp/jobs/481903249 
However, I couldn't reproduce the error you mention in that build. 
I'm using this configuration for it https://github.com/sdavtaker/aws-sdk-cpp/blob/9017ae2d63dc6eccce80e5601c444d09f15ba40c/.travis.yml#L8-L11
Do you have a guess of what could I be missing to reproduce it?
Thanks,
Damian

**Comment by loic-ps** [comment]
Hi @sdavtaker 

You should normally be able to reproduce the error using xcode12.x and the following build command:
`cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12 && cmake --build . --target aws-cpp-sdk-s3`

Thanks,

Loïc

**Comment by trzeciak** [comment]
Hey, i see that issue that still open, for me working workaround is set `MACOSX_DEPLOYMENT_TARGET` before run cmake, and use Xcode toolchain:

```shell
export MACOSX_DEPLOYMENT_TARGET=10.12

cmake \
    -G Xcode \
    -DCMAKE_OSX_DEPLOYMENT_TARGET="$MACOSX_DEPLOYMENT_TARGET" \
    ...
```

**Comment by jmklix** [comment]
Please look at the above solutions if you are having problems building on Mac. You can also open a new issue if you are having problems with a newer MacOS version.
