### ISSUE TITLE
Unable to copy object with specified versionId

### ISSUE THREAD

**Issue by rliaoNutanix** [aws/aws-sdk-cpp#1574]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Unable to copy object with specific version id for CopyObjectRequest.

**SDK version number**
1.7.315

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Centos 7.5

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

Aws::S3::Model::CopyObjectRequest object_request;
object_request.WithBucket("bucket_name").WithKey("dst").WithCopySource("bucket_name/test?versionId=6LfRKv8tGuFvrH.z4WzLq._7s6igA_Qq");
auto copy_object_outcome = s3_client.CopyObject(object_request);

**Expected behavior**
Object with specified version should be copied to destination key. Generated copy source header URL encodes the versionId specifier, so S3 does not find the object.

x-amz-copy-source: bucket_name/test%3FversionId%3D6LfRKv8tGuFvrH.z4WzLq._7s6igA_Qq

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

[DEBUG] 2021-02-22 22:39:06.862 AWSAuthV4Signer [140524309695104] Canonical Request String: PUT
/<bucket_name>/dst

content-length:0
content-type:application/xml
host:52.216.85.237
x-amz-api-version:2006-03-01
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-copy-source:<bucket_name>/test%3FversionId%3D6LfRKv8tGuFvrH.z4WzLq._7s6igA_Qq
x-amz-date:20210222T223906Z

content-length;content-type;host;x-amz-api-version;x-amz-content-sha256;x-amz-copy-source;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

<?xml version="1.0"?>
<Error>
    <Code>NoSuchKey</Code>
    <Message>The specified key does not exist.</Message>
    <Key>test?versionId=6LfRKv8tGuFvrH.z4WzLq._7s6igA_Qq</Key>
    <RequestId>D0D2FE21E36975FE</RequestId>
    <HostId>+TwVxw3r8no+Ci5sFMMqta4as6UaOq5E4t3v50BcVmRA4FLFPwFmkDRxbG0NvJ9V4lATMJxxYNA=</HostId>
</Error>

**Additional context**
Works fine with AWS CLI.
aws s3api copy-object --bucket bucket_name --key dst --copy-source 'bucket_name/test?versionId=6LfRKv8tGuFvrH.z4WzLq._7s6igA_Qq'

Generates x-amz-copy-source: bucket_name/test?versionId=6LfRKv8tGuFvrH.z4WzLq._7s6igA_Qq

**Comment by KaibaLopez** [comment]
Hi @rliaoNutanix,
Sorry for the slow response on this.

I just tested this and it worked for me, can you try using the latest version of the SDK see if you are still seeing the error?

This is my code btw, pretty similar to yours so I doubt that's the problem but just in case.
```cpp
Aws::S3::Model::CopyObjectRequest copyRequest;
    copyRequest.WithBucket("destination_bucket")
            .WithKey("object_key")
            .WithCopySource("sourcebucketwithversioningActive/source_key?versionId=yourobjectversionIdAsseenintheconsole");

        auto copyOutcome = s3_client.CopyObject(copyRequest);
```

**Comment by rliaoNutanix** [comment]
Hi @KaibaLopez ,

Thanks for looking at this. I tried 1.8.182 and your sample code and I still have the same issue. The entire copy source header is URL encoded so that the version field is not interpreted properly. Even in browsing the source code, it seems the entire copy source is URL encoded so that ? is not passed literally. It appears S3 thinks the versionId specification is part of the key itself.

[TRACE] 2021-04-13 18:30:09.147 AWSErrorMarshaller [140229885270656] Error response is <?xml version="1.0"?>
<Error>
    <Code>NoSuchKey</Code>
    <Message>The specified key does not exist.</Message>
    <Key>src?versionId=35W7vDw1sG.VJdbiB9YdYdbqKHv9NO_h</Key>
    <RequestId>MRKXSQAH00C9JCSM</RequestId>
    <HostId>CseljZqOPX3amo2k4LQx79qFs9qDza3jj8ND19yMGv9BaoJZYQp5+N9UNaXe0LU5l2cwgT1VIJY=</HostId>
</Error>

https://github.com/aws/aws-sdk-cpp/blob/1.8.182/aws-cpp-sdk-s3/source/model/CopyObjectRequest.cpp#L147

**Comment by KaibaLopez** [comment]
Hmmm...
But if the encoding thinks "?" is part of the key then I would be able to reproduce on my side right? Like, it would never work. 
I think you're on the right track with the encoding though, you might have hit an edge case... For now, and since I can't seem to reproduce Can you verify that you are not using any of the characters s3 is special about? -Look [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html).
Or if  you have the AWS CLI installed, could you try running the command from there? It'd help me see if this is more of a service behavior problem or the SDK's
`aws s3api copy-object --copy-source bucket-1/test.txt?versionId=version-id  --key test.txt --bucket bucket-2`

**Comment by rliaoNutanix** [comment]
Right, I'm not using any special characters. The snippet in the latest post is the exact copy source string that I passed in: src?versionId=35W7vDw1sG.VJdbiB9YdYdbqKHv9NO_h. src is the object name and I pass in a specific version.

Yes, the AWS SDK works fine for me. It passes the literal ? in x-amz-copy-source. It's a specific issue when using the C++ SDK.
