### ISSUE TITLE
CreateMultipartUploadRequest in a public bucket?

### ISSUE THREAD

**Issue by lsong0905** [aws/aws-sdk-cpp#1575]
Hello,

I am trying to test multipart upload in a public bucket, and it looks like this operation does not work with anonymous user even though I set the bucket policy as following. I keep getting "An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Anonymous users cannot initiate multipart uploads.  Please authenticate.". 

I've tried with "aws s3" and "aws s3api" CLI tools but they all returned the same error. Since I could not find such restriction online, I am reaching out here and want to confirm that multipart upload is NOT allowed with anonymous user. 

Thank you in advance.

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "test",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::MY_BUCKET",
                "arn:aws:s3:::MY_BUCKET/*"
            ]
        }
    ]
}`

**Comment by jmklix** [comment]
@lsong0905 I did find someone on [stack-overflow](https://stackoverflow.com/questions/33600192/aws-s3-cli-anonymous-users-cannot-initiate-multipart-uploads) that successfully did this with `--sse`. They did have some trouble at first, but can you also try this to see if it works for you with the cli?

**Comment by lsong0905** [comment]
@jmklix I don't think the flag "--sse" is helping the case since "--sse" flag is to specify server-side encryption of the object.

```
myVM:/home/ # aws s3 cp --sse my_obj s3://SANITIZED --no-sign-request
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --sse: Invalid choice, valid choices are:
```

**Comment by jmklix** [comment]
Sorry for the misleading info about --sse. It does appear that this was an bug previously, but has been since fixed. Try using the policy [here](https://github.com/aws/aws-cli/issues/1674#issuecomment-406808241) to get this working.

``` JSON
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "VisualEditor0",
      "Effect": "Allow",
      "Action": [
        "s3:PutEncryptionConfiguration",
        "s3:PutObject",
        "s3:ListBucketMultipartUploads",
        "s3:AbortMultipartUpload",
        "s3:ListMultipartUploadParts"
      ],
      "Resource": "*"
    }
  ]
}
```

**Comment by lsong0905** [comment]
@jmklix I've tried using the bucket policy that you suggested above, and it still returned the same error.
I've even tried giving full permission by setting "Action": "*" in the bucket policy, and still no luck.

**Comment by jmklix** [comment]
What is the full error that you are getting when trying to use the CLI?

**Comment by lsong0905** [comment]
@jmklix 
```
myVM:/home/ # aws s3api create-multipart-upload --bucket SANITIZED_BUCKET --key OBJECT --no-sign-request

An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Anonymous users cannot initiate multipart uploads.  Please authenticate.
```
is the full error I got.

**Comment by lsong0905** [comment]
@jmklix Is there any update on the issue?

**Comment by jmklix** [comment]
Sorry for the slow reply, but after inquiring internally we have not supported this for 10 years.

**Comment by nachomezzadra** [comment]
Hi.  Any updates on this? I'm getting the same error.
