### ISSUE TITLE
S3 HeadObjectResult Content Length only supports 32bit file sizes

### ISSUE THREAD

**Issue by kieranthawley** [aws/aws-sdk-cpp#158]
HeadObjectResult m_contentLength is stored as a long, resulting in the value being truncated for files over 2GB.

**Comment by JonathanHenson** [comment]
You are correct. I need to raise this back to the team that maintains the s3 model since this is modeled as a 32 bit integer.

**Comment by JonathanHenson** [comment]
We've updated the model, but need to make sure all of the other SDKs handle backwards compatibility. This change should be out soon.

**Comment by bretambrose** [comment]
This fix has been pushed to live.
