### ISSUE TITLE
Can't get package to attach with CLion 2020.3.2 and Cygwin compiler

### ISSUE THREAD

**Issue by xeru98** [aws/aws-sdk-cpp#1580]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Win10/Cygwin

**Describe the question**
I'm trying to use the sdk with jetbrains CLion 2020.3.2 on my windows machine. However, I need access to the POSIX C++ libraries so I'm using cygwin as my compiler. Steps I took

1) Download from git
2) run cmake to generate VS solution
3) build the BUILD_ALL project
4) build the INSTALL project
5) ensure that the files had been correctly build to C:\aws-cpp-sdk-all (they were)
6) copy the contents of that directory to /usr/local on cygwin
7) try to run CLion
doing this resulted in the following error

```
CMake Error at /usr/local/lib/cmake/AWSSDK/AWSSDKConfig.cmake:111 (message):
  AWS SDK for C++ headers found, but we were unable to locate the binaries.
  Have you deleted or moved it?

              Please make sure header files and binaries are located in INSTALL_ROOT_DIR/INCLUDE_DIR/ and INSTALL_ROOT_DIR/LIB_DIR/[PLATFORM_PREFIX]/[Debug|Config|OtherConfigs]
```

my current directory structure on cygwin is
/usr/local/
    - include
    - bin
    - etc (empty)
    - lib

my cmake
```
cmake_minimum_required(VERSION 3.10)
set(CMAKE_CXX_STANDARD 20)

option(BUILD_SHARED_LIBS "Build shared libraries" ON)

project(proj)

find_package(AWSSDK)

add_executable(proj main.cpp)

# The libraries used by your executable.
target_link_libraries(proj ${AWSSDK_LINK_LIBRARIES})
```

Have I missed a piece of configuration?

**Comment by KaibaLopez** [comment]
Hi @xeru98 ,
Sorry for the late response on this.
Can you verify what your compiler is on Cygwin? 

The way you describe building on windows but running on cygwin is not really how it would work, unless I am missing something.
The easiest way to do this would be to build and run using the same compiler, so in your case, build from cygwin using gcc/g++ (versions 4.9 or higher).
