### ISSUE TITLE
cmake fails to configure

### ISSUE THREAD

**Issue by lrsays** [aws/aws-sdk-cpp#1581]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Followed cmake commands described here -https://github.com/aws/aws-sdk-cpp/tree/version1.9, cmake fails to compile.

**SDK version number**
version1.9

**Platform/OS/Hardware/Device**
Linux X86_64

**To Reproduce (observed behavior)**
1. Download SDK from https://github.com/aws/aws-sdk-cpp/archive/version1.9.zip
2. Unzip SDK
3. mkdir build && cd build
4. cmake ../aws-sdk-cpp-version1.9/ -DCMAKE_BUILD_TYPE=Debug -DBUILD_ONLY="core;meteringmarketplace"

**Expected behavior**
cmake should configure without any issues.

**Logs/output**

CMake Error at CMakeLists.txt:187 (include):
  include could not find load file:

    AwsFindPackage

CMake Error at CMakeLists.txt:197 (add_subdirectory):
  The source directory

    /home/admin/aws/aws-sdk-cpp-version1.9/crt/aws-crt-cpp

  does not contain a CMakeLists.txt file.

-- Add s3-crt:s3 to C2J_SPECIAL_NAME_LIST
-- Considering core
-- Considering meteringmarketplace
-- Updating version info to 1.9-rc1
-- Custom memory management enabled; stl objects now using custom allocators
CMake Error at aws-cpp-sdk-core/CMakeLists.txt:489 (aws_use_package):
  Unknown CMake command "aws_use_package".

-- Configuring incomplete, errors occurred!

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**
README.md for version 1.9 SDK is wrong [https://github.com/aws/aws-sdk-cpp/tree/version1.9], README says following -
Version 1.8 is now Available!
Version 1.8 introduces much asked for new features and changes to the SDK but, because this might also cause compatibility issues with previous versions we've decided to keep it as a seperate branch to make the transition less jarring.

Looks like it's copied from Version 1.8.

**Comment by KaibaLopez** [comment]
Hi @lrsays ,
The version 1.9 is still under development and most of the documentation on it is still being worked on but, one of the biggest changes being implemented is the use of git submodules to handle the third-party dependencies. If you want to try it out, can you try running this git command from the source folder before running cmake?
`git clone -b version1.9 --recurse-submodules https://github.com/aws/aws-sdk-cpp`
Let me know if that worked for you, but keep in mind it is not yet the recommended version.
