### ISSUE TITLE
Consider adding flag to fall back to natural libcurl proxy behavior

### ISSUE THREAD

**Issue by rwolfson** [aws/aws-sdk-cpp#1583]
Hi AWS C++ SDK folks,
I recently hit similar behavior regarding libcurl environment variables as reported in #1049 . Although I understand the desire for certain customers not wanting this automatic behavior, the default behavior is very helpful in many other environments. Specifically, it allows developers to create more deployment-agnostic code that doesn't need to implement boilerplate proxy detection logic or flags.

Would it be possible to consider a CMake flag that skips the block that sets CURLOPT_PROXY to ""?
https://github.com/aws/aws-sdk-cpp/blob/1.8.155/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp#L613-L616

That would hopefully avoid breaking customers that rely on the default behavior, but provide an opportunity for customers that want the default libcurl behavior to have their applications function similarly to other libcurl applications.

An alternative implementation could be an `automaticProxy` flag in `ClientConfiguration` that skips that specific `CURLOPT_PROXY` option from being set. This is a little bit less transparent than the preprocessor option since it would require application code changes to utilize.

Thank you for your consideration. I'm happy to submit a PR if this seems like a worthwhile improvement.

**Comment by sahil1105** [comment]
I agree, using environment variables by default, and providing an option to ignore them for the special case would be ideal.

**Comment by jmklix** [comment]
This was added with this [PR](https://github.com/aws/aws-sdk-cpp/pull/2679). Please update to the latest version of this sdk and let us know if you have any other features that could improve this sdk.
