### ISSUE TITLE
S3Client PutObject fails on some files with : SignatureDoesNotMatch

### ISSUE THREAD

**Issue by fxfire** [aws/aws-sdk-cpp#1584]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I'm using the latest sdk version in a lambda to put png files into an S3 Bucket. One png works, the other returns the error:
PutObject Failed: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method. Here are the two files:
![works](https://user-images.githubusercontent.com/5979321/110075368-00a60480-7d83-11eb-946f-073c169ade38.png)
![breaks](https://user-images.githubusercontent.com/5979321/110075371-00a60480-7d83-11eb-8560-ab3be89fe0c4.png)

code:
```
Aws::InitAPI(m_options);
ClientConfiguration aws_conf;
aws_conf.region = "eu-central-1";
aws_conf.endpointOverride = "s3.eu-central-1.wasabisys.com";
m_options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
auto aws_credentials = AWSCredentials("xxxxxxxxx", "yyyyyyyyyyyyyyyyyyyyyyyy");
m_s3client = std::make_shared<S3Client>(aws_credentials, aws_conf);
...
bool S3Bucket::PutObject(std::string bucketname, std::string& key, std::string& data, Aws::Map< Aws::String, Aws::String>& metadata, std::string& error)
{
  Aws::S3::Model::PutObjectRequest request;
  request.SetBucket(bucketname);
  request.SetKey(key);
  const std::shared_ptr<Aws::IOStream> input_data = Aws::MakeShared<Aws::StringStream>("whatever");
  input_data->write(data.data(), data.size());
  request.SetBody(input_data);

  auto outcome = m_s3client->PutObject(request);
  if (!outcome.IsSuccess())
  {
    auto err = outcome.GetError();
    error = std::string("PutObject Failed: " + std::string(err.GetExceptionName().c_str()) + ": " + std::string(err.GetMessage().c_str()));
    return false;
  }
   return true;
}
...
Aws::Utils::Logging::ShutdownAWSLogging();
Aws::ShutdownAPI(m_options);
```

**SDK version number**
cloned from latest version

**Platform/OS/Hardware/Device**
c++ amazonlinux2, Lambda function

**To Reproduce (observed behavior)**
see above

**Expected behavior**
It obvioulsy should always work...

**Logs/output**
CoudWatch only gives me this:
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method. ( I'm not sure how to get the http request/response logs from inbetween lambda and the S3 http call ... someone ?

Why do I always feel like I'm the first and only one using the sdk and encountering endless problems lol

**Comment by KaibaLopez** [comment]
Hi @fxfire ,
Sorry for the slow response here, and yea that is very weird behavior. 
Could you try running it locally instead of in a lambda function and provide the full log? (remember to censor out credentials and names).
There might be something there that could help me identify the issue.
