### ISSUE TITLE
requestTimeoutMs can't be set to a value higher than 60 seconds

### ISSUE THREAD

**Issue by simonebaracchi** [aws/aws-sdk-cpp#1585]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Aws::Client::ClientConfiguration.requestTimeoutMs should represent the "socket read timeout" according to the docs. It seems to work as expected for values up to 60 seconds. However, even if set to a value higher than 60 seconds, if the server has response times higher than that, the request will fail with a timeout.

**SDK version number**
1.7.177

**Platform/OS/Hardware/Device**
Ubuntu 20.04

**To Reproduce (observed behavior)**
set requestTimeoutMs to a value higher than 60 seconds, then try to perform an operation that takes longer than that to reply

**Expected behavior**
Either the documentation should report a max value for the setting, or the setting should accept any value (which would be preferable)

**Logs/output**

after 60 seconds I get this error:

`[ERROR] 2021-03-11 10:28:33.117 CurlHttpClient [140377922628928] Curl returned error code 28 - Timeout was reached
[ERROR] 2021-03-11 10:28:33.117 AWSClient [140377922628928] HTTP response code: -1
Exception name:
Error message: Unable to connect to endpoint
0 response headers:`

**Comment by KaibaLopez** [comment]
Hi @simonebaracchi ,
Sorry for the lack of response here, can you specify what service call you're trying to use here? 
Different api's have different timeout limits and those are documented on the service limitations...
That being said, depending on what service you are talking about it might still be a bug.

**Comment by simonebaracchi** [comment]
I'm using the S3 read and write APIs.On Jun 4, 2021 21:49, Gilberto Lopez Zayas ***@***.***> wrote:
Hi @simonebaracchi ,
Sorry for the lack of response here, can you specify what service call you're trying to use here?
Different api's have different timeout limits and those are documented on the service limitations...
That being said, depending on what service you are talking about it might still be a bug.
