### ISSUE TITLE
How can I get and show the results of a request to IoTSiteWise

### ISSUE THREAD

**Issue by EliezerMaduro** [aws/aws-sdk-cpp#1587]
Confirm by changing [ ] to [x] below:
- [ ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Windows 10

**Describe the question**
Hi, I am new programming in C++, I was trying to show in the console the outputs of a request to IoTSitiWise, when I build the project all is ok, but I dont know if the code is correct for get what I want, for this time I just want to test de SDK and I want to print in the console the result of the request, but then I would like to use this data, this is the code that I have right now, How can I print the results?

```cpp
#include <iostream>
#include <string>
#include <aws/core/Aws.h>
#include <sstream>
#include <aws/iotsitewise/IoTSiteWiseClient.h>
#include <aws/core/client/AWSError.h>
#include <fstream>
#include <aws/core/client/ClientConfiguration.h>
#include <aws/core/auth/AWSCredentials.h>
#include <aws/iotsitewise/model/GetAssetPropertyValueRequest.h>
#include <aws/iotsitewise/model/GetAssetPropertyValueResult.h>

using namespace Aws::IoTSiteWise; using namespace std;

int main()
{
    Aws::SDKOptions options;
    Aws::InitAPI(options);
    {
        Aws::Client::ClientConfiguration config;
        config.region = Aws::Region::xxx; config.profileName = "xxx";
        config.connectTimeoutMs = 15000;
        config.requestTimeoutMs = 15000;

        Aws::Auth::AWSCredentials crendetials("foo","bar");
        
        IoTSiteWiseClient client(crendetials,config);

        Model::GetAssetPropertyValueRequest request;
        request.SetAssetId("xxx");
        request.SetPropertyId("xxx");
        auto outcome = client.GetAssetPropertyValue(request);
        auto result = outcome.GetResult();
    }

    Aws::ShutdownAPI(options);
    return 0;
}

```

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by jmklix** [comment]
What are you expecting in the result?

You can do this:
```cpp
std::cout << outcome.GetResult().GetPropertyValue().GetValue().GetStringValue() << std::endl;
```
Or for the error message:
```cpp
std::cout << outcome.GetError().GetMessage() << std::endl;
```

**Comment by EliezerMaduro** [comment]
@jmklix I want to be able to see the same message that I get when I do the same request but with the AWS CLI with the following command: 

``aws iotsitewise get-asset-property-value --asset-id foo --property-id bar``

But when I debug the proyect adding to my script:
```cpp
std::cout << outcome.GetResult().GetPropertyValue().GetValue().GetStringValue() << std::endl;
std::cout << outcome.GetError().GetMessage() << std::endl;
```
I am not able to see any message in the console

**Comment by jmklix** [comment]
Are you looking for it to be formatted in JSON like this:
```JSON
{
    "propertyValue": {
        "value": {
            "stringValue": "Renton"
        },
        "timestamp": {
            "timeInSeconds": 1616693522,
            "offsetInNanos": 0
        },
        "quality": "GOOD"
    }
}
```

or are you just looking for specific values? stringValue, timeInSeconds, offsetInNanos, and quality

**Comment by EliezerMaduro** [comment]
I am looking for the specific values such as `TimeInSeconds`, `Quality` and `StringValue` (In my case Value would be a `Double` variable)

**Comment by jmklix** [comment]
Try this:
```cpp
        auto outcome = client.GetAssetPropertyValue(request);
        auto result = outcome.GetResult().GetPropertyValue();

        std::cout << "StringValue: " << result.GetValue().GetStringValue() << std::endl;
        std::cout << "TimeInSeconds: " << result.GetTimestamp().GetTimeInSeconds() << std::endl;
        std::cout << "OffsetInNanos: " << result.GetTimestamp().GetOffsetInNanos() << std::endl;
        std::cout << "Quality: " << Aws::IoTSiteWise::Model::QualityMapper::GetNameForQuality(result.GetQuality()) << std::endl;
```

**Comment by EliezerMaduro** [comment]
Thank you so much, that worked for me
