### ISSUE TITLE
Is AWS_CUSTOM_MEMORY_MANAGEMENT still to be used?

### ISSUE THREAD

**Issue by magnushakansson** [aws/aws-sdk-cpp#1589]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Linux

**Describe the question**
There seems to be some inconsistency in the documentation and unclarity in how to configure custom memory management.

The code example in page https://sdk.amazonaws.com/cpp/api/LATEST/md__docs__memory__management.html refer to the define AWS_CUSTOM_MEMORY_MANAGEMENT but in the latest code the define is USE_AWS_MEMORY_MANAGEMENT (https://sdk.amazonaws.com/cpp/api/LATEST/_a_w_s_allocator_8h_source.html). 

The commit https://github.com/aws/aws-sdk-cpp/commit/80a64072977b7fbc8857fa00f1e1aac9eed8099b changed it in all places in the code except in the file https://github.com/aws/aws-sdk-cpp/blob/c4e89e4f855e60b304c91db472fed650759cca55/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp#L25.

Is the intentional and you are still supposed to set AWS_CUSTOM_MEMORY_MANAGEMENT  when building the SDK (and using it?) as described in the documentation?

**Comment by KaibaLopez** [comment]
Hi @magnushakansson ,
Thanks for pointing this out to us, it seems like this is something we have just overlooked. But to answer your question no it should not be used anymore.
