### ISSUE TITLE
S3 DeleteObject failure error -- Missing required header for this request: Content-MD5 with address

### ISSUE THREAD

**Issue by bryce-shang** [aws/aws-sdk-cpp#1592]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**

The `DeleteObjects` fails with weird error message. This failure may relate to the object does not exist (I am still confirming this assumption).

```cpp
    auto delete_objects_outcome = s3_client->DeleteObjects(delete_objects_request);
    if (!delete_objects_outcome.IsSuccess()) {
        auto delete_objects_error = delete_objects_outcome.GetError();
        cout << "Unable to delete objects in bucket: " << bucket_name << endl;
        cout << "ERROR: " << delete_objects_error.GetMessage() << endl;
```

error
```
Deleted bucket: train-0c9726f5-aa35-4db8-b7c4-3290bfb0a90b-input
--
172 | Unable to delete objects in bucket: train-0c9726f5-aa35-4db8-b7c4-3290bfb0a90b-output
173 | ERROR: Unable to parse ExceptionName: InvalidRequest Message: Missing required header for this request: Content-MD5 with address : 52.218.208.49 with address : 52.218.208.49
```

**SDK version number**

1.7.316

**Platform/OS/Hardware/Device**
What are you running the sdk on?

Ubuntu 20.04

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

See description

**Expected behavior**

No failure

**Logs/output**

See description

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @bryce-shang ,
Sorry for the slow response. 
I think I need a bit more info on this, like what is the rest of the code doing? Or if you can show me the trace log that would also help.
From what you say, it looks like you are trying to delete a bucket and then trying to delete objects in the bucket?

**Comment by crockeea** [comment]
I'm not sure how to consistently reproduce this, but I got the same error today (with an older version of the SDK). Our code creates two S3 buckets and then calls SageMaker with those buckets. Once SageMaker returns, we try to empty the buckets and then delete the buckets. Normally, this works fine. When I got the error today, the SageMaker job had failed. Of course we should still try to clean up the temporary S3 buckets:
```
bool s3_delete_bucket(const string& bucket_name, const shared_ptr<s3::S3Client> &s3_client) {
    // Find objects in bucket to delete
    s3::Model::Delete objects_to_delete;
    s3::Model::ListObjectsRequest list_objects_request = s3::Model::ListObjectsRequest()
            .WithBucket(bucket_name.c_str());

    auto list_objects_outcome = s3_client->ListObjects(list_objects_request);
    if (!list_objects_outcome.IsSuccess()) {
        auto list_objects_error = list_objects_outcome.GetError();
        cout << "Unable to list objects for bucket: " << bucket_name << endl;
        cout << "ERROR: " << list_objects_error.GetMessage() << endl;

        return false;
    }

    Aws::Vector<s3::Model::Object> objects = list_objects_outcome.GetResult().GetContents();

    for (s3::Model::Object object : objects) {
        s3::Model::ObjectIdentifier identifier;
        objects_to_delete.AddObjects(s3::Model::ObjectIdentifier().WithKey(object.GetKey()));
    }

    // Delete objects in bucket
    s3::Model::DeleteObjectsRequest delete_objects_request = s3::Model::DeleteObjectsRequest()
            .WithBucket(bucket_name.c_str())
            .WithDelete(move(objects_to_delete));

    auto delete_objects_outcome = s3_client->DeleteObjects(delete_objects_request);
    if (!delete_objects_outcome.IsSuccess()) {
        auto delete_objects_error = delete_objects_outcome.GetError();
        cout << "Unable to delete objects in bucket: " << bucket_name << endl;
        cout << "ERROR: " << delete_objects_error.GetMessage() << endl;

        return false;
    }


    // Delete bucket now that it is empty
    s3::Model::DeleteBucketRequest delete_bucket_request = s3::Model::DeleteBucketRequest()
            .WithBucket(bucket_name.c_str());

    auto outcome = s3_client->DeleteBucket(delete_bucket_request);
    if (!outcome.IsSuccess()) {
        auto error = outcome.GetError();
        cout << error.GetExceptionName() << ": " << error.GetMessage() << endl;

        return false;
    }

    cout << "Deleted bucket: " << bucket_name << endl;
    return true;
}
```

I got the same error as @bryce-shang:
```
Unable to parse ExceptionName: InvalidRequest Message: Missing required header for this request: Content-MD5 with address : <someIPAddress> with address : <sameIPAddress>
```

So one question is: why is the call to `DeleteObjects` failing? Perhaps SageMaker still has some kind of handle on the bucket/object? The second problem is that the error message unhelpful.

**Comment by crockeea** [comment]
Note: when we try to delete all objects in the bucket, this bucket is empty: we are trying to delete the SageMaker output bucket, but the SageMaker training job failed, so it didn't put anything in this bucket.

This means that `objects_to_delete` is probably empty. I'm not sure why that would cause any sort of error; just pointing it out.

**Comment by KaibaLopez** [comment]
Hi @crockeea ,
Ok so yea I am getting the same error message when trying to delete objects on an empty bucket...
kind of debatable wether or not that should be considered an error, but it for sure needs at least a better message so I'll start there.  
For now, and I'm sure you already do something like this but, as a work around you can do a simple check to verify that the vector isn't empty before trying to delete:
```cpp
Aws::Vector<Model::Object> objects = list_objects_outcome.GetResult().GetContents();
    if(objects.empty()){
        cout << "bucket has no more objects to delete" << endl;
        return false;
    }
```
Let me know if you are still getting that message though since it is a generic error it could be that what I'm hitting is not really all there is.

**Comment by crockeea** [comment]
An empty batch operation should not fail. Moreover, this is not documented [here](http://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_s3_1_1_s3_client.html#ab4836eb38ad26b7402868acd8931a962).
