### ISSUE TITLE
Undefined Error Symbol on Aws::DynamoDB::Model::AttributeValue::GetM()

### ISSUE THREAD

**Issue by alexeimartov** [aws/aws-sdk-cpp#1596]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I'm trying to integrate the aws sdk to my application to be able to execute queries on dynamodb, the issue that I'm having is that my code compiles but when it's linking I find errors on AttributeValue, there are specific methods that  seems not being defined, all of them are related to Aws::Map and Aws::String.

**SDK version number**
1.8
**Platform/OS/Hardware/Device**
Linux-ubuntu20.04
What are you running the sdk on?
**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
I've tried to use 
sudo cmake . -DCMAKE_BUILD_TYPE=Release -DAWS_CUSTOM_MEMORY_MANAGEMENT=0 -DSTATIC_LINKING=0 
sudo make
then build my app using
sudo make
and still not able to make my app link.
**Expected behavior**
The expected behavior is that the app build properly.
**Logs/output**
[1/4] Link (lld) libUE4Editor-DynamoDB.so
ld.lld: error: undefined symbol: Aws::DynamoDB::Model::AttributeValue::SetS(std::__1::basic_string<char, std::__1::char_traits<char>, Aws::Allocator<char> > const&)
>>> referenced by AttributeValue.h:41 (/home/martin/Documents/Unreal Projects/MyProject/Plugins/martov-client-cpp/Source/ThirdParty/AWSDynamoDB/aws/dynamodb/model/AttributeValue.h:41)
>>>               /home/martin/Documents/Unreal Projects/MyProject/Plugins/martov-client-cpp/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/DynamoDB/Module.DynamoDB.cpp.o:(Aws::DynamoDB::Model::AttributeValue::SetS(char const*))

ld.lld: error: undefined symbol: Aws::DynamoDB::Model::AttributeValue::GetS() const
>>> referenced by AttributeValue.h:24 (/home/martin/Documents/Unreal Projects/MyProject/Plugins/martov-client-cpp/Source/DynamoDB/Public/Model/AttributeValue.h:24)
>>>               /home/martin/Documents/Unreal Projects/MyProject/Plugins/martov-client-cpp/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/DynamoDB/Module.DynamoDB.cpp.o:(FAttributeValue::setItemValue(TSharedPtr<FJsonObject, (ESPMode)0>, std::__1::basic_string<char, std::__1::char_traits<char>, Aws::Allocator<char> >, Aws::DynamoDB::Model::AttributeValue))
>>> did you mean: Aws::DynamoDB::Model::AttributeValue::GetB() const
>>> defined in: /home/martin/Documents/Unreal Projects/MyProject/Plugins/martov-client-cpp/Source/ThirdParty/AWSDynamoDB/Linux/x86_64-unknown-linux-gnu/libaws-cpp-sdk-dynamodb.so

ld.lld: error: undefined symbol: Aws::DynamoDB::Model::AttributeValue::GetSS() const
>>> referenced by AttributeValue.h:36 (/home/martin/Documents/Unreal Projects/MyProject/Plugins/martov-client-cpp/Source/DynamoDB/Public/Model/AttributeValue.h:36)
>>>               /home/martin/Documents/Unreal Projects/MyProject/Plugins/martov-client-cpp/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/DynamoDB/Module.DynamoDB.cpp.o:(FAttributeValue::setItemValue(TSharedPtr<FJsonObject, (ESPMode)0>, std::__1::basic_string<char, std::__1::char_traits<char>, Aws::Allocator<char> >, Aws::DynamoDB::Model::AttributeValue))

ld.lld: error: undefined symbol: Aws::DynamoDB::Model::AttributeValue::GetN() const
>>> referenced by AttributeValue.h:27 (/home/martin/Documents/Unreal Projects/MyProject/Plugins/martov-client-cpp/Source/DynamoDB/Public/Model/AttributeValue.h:27)
>>>               /home/martin/Documents/Unreal Projects/MyProject/Plugins/martov-client-cpp/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/DynamoDB/Module.DynamoDB.cpp.o:(FAttributeValue::setItemValue(TSharedPtr<FJsonObject, (ESPMode)0>, std::__1::basic_string<char, std::__1::char_traits<char>, Aws::Allocator<char> >, Aws::DynamoDB::Model::AttributeValue))

ld.lld: error: undefined symbol: Aws::DynamoDB::Model::AttributeValue::GetNS() const
>>> referenced by AttributeValue.h:44 (/home/martin/Documents/Unreal Projects/MyProject/Plugins/martov-client-cpp/Source/DynamoDB/Public/Model/AttributeValue.h:44)
>>>               /home/martin/Documents/Unreal Projects/MyProject/Plugins/martov-client-cpp/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/DynamoDB/Module.DynamoDB.cpp.o:(FAttributeValue::setItemValue(TSharedPtr<FJsonObject, (ESPMode)0>, std::__1::basic_string<char, std::__1::char_traits<char>, Aws::Allocator<char> >, Aws::DynamoDB::Model::AttributeValue))

ld.lld: error: undefined symbol: Aws::DynamoDB::Model::AttributeValue::GetM() const
>>> referenced by AttributeValue.h:51 (/home/martin/Documents/Unreal Projects/MyProject/Plugins/martov-client-cpp/Source/DynamoDB/Public/Model/AttributeValue.h:51)
>>>               /home/martin/Documents/Unreal Projects/MyProject/Plugins/martov-client-cpp/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/DynamoDB/Module.DynamoDB.cpp.o:(FAttributeValue::setItemValue(TSharedPtr<FJsonObject, (ESPMode)0>, std::__1::basic_string<char, std::__1::char_traits<char>, Aws::Allocator<char> >, Aws::DynamoDB::Model::AttributeValue))
>>> referenced by AttributeValue.h:53 (/home/martin/Documents/Unreal Projects/MyProject/Plugins/martov-client-cpp/Source/DynamoDB/Public/Model/AttributeValue.h:53)
>>>               /home/martin/Documents/Unreal Projects/MyProject/Plugins/martov-client-cpp/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/DynamoDB/Module.DynamoDB.cpp.o:(FAttributeValue::setItemValue(TSharedPtr<FJsonObject, (ESPMode)0>, std::__1::basic_string<char, std::__1::char_traits<char>, Aws::Allocator<char> >, Aws::DynamoDB::Model::AttributeValue))
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:1050: UE4Editor] Error 6

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @alexeimartov ,
Sorry for the slow response, can you show me a small code sample that reproduces this?
