### ISSUE TITLE
SSOCredentialsProviderTest.TestParseCredentialsFromConfigCorrectly Segmentation fault on Raspian Buster

### ISSUE THREAD

**Issue by phlantin** [aws/aws-sdk-cpp#1597]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Running the test SSOCredentialsProviderTest.TestParseCredentialsFromConfigCorrectly results in a segmentation fault on a Raspian Buster OS, and the awk sdk build fails.

**SDK version number**
1.8.165

**Platform/OS/Hardware/Device**
Raspbery pi 4 / 4GB / Raspbian Buster (updated to latest)

**To Reproduce (observed behavior)**
git clone --depth 1 --branch 1.8.165 https://github.com/aws/aws-sdk-cpp.git
cd build
cmake ../aws-sdk-cpp -DBUILD_ONLY="lex;cognito-identity;sts;identity-management"

**Expected behavior**
Successful build, such as I get when I execute the same steps on mac laptop.

**Logs/output**
<...>
[----------] 3 tests from SSOCredentialsProviderTest
[ RUN      ] SSOCredentialsProviderTest.TestParseCredentialsFromConfigCorrectly
Segmentation fault
make[2]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/build.make:817: aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 139
make[2]: *** Deleting file 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests'
make[1]: *** [CMakeFiles/Makefile2:634: aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 56%] Linking CXX shared library libaws-cpp-sdk-access-management.so
[ 56%] Built target aws-cpp-sdk-access-management
make: *** [Makefile:149: all] Error 2

**Additional context**
Going back to version 1.8.115 fixes this problem, though I haven't tried to narrow down exactly which version caused this issue to start occurring.

**Comment by sdavtaker** [comment]
Hi, 
Thanks for reporting, this is consistent with other open issue we are looking at right now. 
I will keep updates in https://github.com/aws/aws-sdk-cpp/issues/1601
