### ISSUE TITLE
Improve AWS-SDK-CPP documentation readability

### ISSUE THREAD

**Issue by geraldo-netto** [aws/aws-sdk-cpp#1598]
**Is your feature request related to a problem? Please describe.**
Dear Friends, I'm developing an integration with your SDK and everything is great except one minor detail on documentation: some declarations are too long making it difficult to read

This is what I see now:  
![aws-before](https://user-images.githubusercontent.com/20527108/111785872-72229e80-88bd-11eb-9754-f82f65742550.png)

Would be possible to consider splitting each parameter by line?

That way, it would be readable for everybody :)

Thank You so much,
Geraldo Netto

**Comment by jmklix** [comment]
We will look into removing the unnecessary and useless parts of parameter lines, but this might be limited because it is auto generated.
