### ISSUE TITLE
Websocket support for Transcribe

### ISSUE THREAD

**Issue by dschnabel** [aws/aws-sdk-cpp#1599]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Rasperry PI 4

**Describe the question**
Transcribe has [support for WebSockets](https://aws.amazon.com/blogs/aws/amazon-transcribe-streaming-now-supports-websockets/). However, the C++ SDK only seems to support HTTP/2. Are there any plans to add WebSockets support to the Transcribe API?

I'm asking because right now I'm getting this error message when I use `TranscribeStreamingService`:
```
Exception name: BadRequestException
Error message: A complete signal was sent without the preceding empty frame.
```
This error seems to be related to HTTP/2, so I wanted to give WebSockets a try.

Thanks!

**Comment by KaibaLopez** [comment]
Hi @dschnabel ,
Sorry for the delayed response, could you give me a bit more details on what you're trying to do and how you are trying to accomplish it? 
A code snippet or better yet a quick sample code on the call you are trying to do would help me get a better idea of how this should work.

**Comment by dschnabel** [comment]
Hi @KaibaLopez I'm working on a chatbot and was using `TranscribeStreamingService` to stream the audio data to Transcribe in real-time. However, this was super slow and prone to errors (probably because `TranscribeStreamingService` uses HTTP/2) so I implemented my own methods to talk to the Transcribe API using WebSocket which works great.

Streaming via Websocket is much faster than HTTP/2 but unfortunately the C++ SDK doesn't support websockets. It would be nice if future versions of `TranscribeStreamingService` supported Websocket. Does this make sense?

**Comment by KaibaLopez** [comment]
@dschnabel ,
Yea ok, that does make sense.
It sounds like you got an implementation of websockets working though, could you share how you did that? Or better yet, make a PR on it so we could review the changes.

**Comment by dschnabel** [comment]
I didn't use the C++ SDK but went direcly so you'll have to rewrite the code to fit the SDK infrastructure.

Anyway, here's the code: https://gist.github.com/dschnabel/9b4ca0d6afd510b59e49c5cf1013087a

The file `CRC.h` is found under https://github.com/d-bahr/CRCpp/blob/master/inc/CRC.h

Usage:
```
#include "TranscribeManager.hpp"

// get signed URL
const string url = TranscribeManager::getSignedWebsocketUrl(accessKey_, secretKey_, region_);

// connect to the url using a socket library (e.g. https://github.com/machinezone/IXWebSocket)

// build request string
string request;
TranscribeManager::makeRequest(request, audioData); // audioData is a const vector<uint8_t>

// send request to socket
```

**Comment by dschnabel** [comment]
@jbmcgee Establishing a WSS connection is out of scope for this discussion. I used [IXWebSocket](https://github.com/machinezone/IXWebSocket) which works on Windows as well. You can find sample code on the project page.
