### ISSUE TITLE
Cannot build aws-sdk-cpp source version 1.9 on Windows

### ISSUE THREAD

**Issue by shahidur106** [aws/aws-sdk-cpp#1602]
Confirm by changing [ ] to [x] below:
- [ ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Windows 10 64Bit
cmake version 3.20.0

**Describe the question**
I am trying to build source of branch = version1.9
After downloading the source checked out to that branch and run below command:
`mkdir build`
`cd build`
`"C:\Program Files\CMake\bin\cmake.exe" C:\dev-wa\AWSSDKCPP\aws-sdk-cpp -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:\dev-wa\AWSSDKCPP\build\Debug\ -DBUILD_ONLY="apigatewaymanagementapi;sqs" -DCMAKE_BUILD_TYPE=Debug`

**Logs/output**
Below are the CMD console logs
```
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating windows build config
-- Building project version: 1.9-rc1
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- Encryption: Bcrypt
-- Http client: WinHttp
CMake Error at CMakeLists.txt:187 (include):
  include could not find requested file:

    AwsFindPackage


CMake Error at CMakeLists.txt:197 (add_subdirectory):
  The source directory

    C:/dev-wa/AWSSDKCPP/aws-sdk-cpp/crt/aws-crt-cpp

  does not contain a CMakeLists.txt file.


-- Add s3-crt:s3 to C2J_SPECIAL_NAME_LIST
-- Considering apigatewaymanagementapi
-- Considering sqs
-- Updating version info to 1.9-rc1
-- Custom memory management enabled; stl objects now using custom allocators
CMake Error at aws-cpp-sdk-core/CMakeLists.txt:489 (aws_use_package):
  Unknown CMake command "aws_use_package".


-- Configuring incomplete, errors occurred!
See also "C:/dev-wa/AWSSDKCPP/build/CMakeFiles/CMakeOutput.log".
See also "C:/dev-wa/AWSSDKCPP/build/CMakeFiles/CMakeError.log".
```

**Comment by jmklix** [comment]
There are different build steps needed for 1.9 which have not been published yet, but I will make sure to update here when it is published.

**Comment by shahidur106** [comment]
@jmklix Many thanks for your reply.
I am waiting for your notification.

**Comment by jmklix** [comment]
1.9 Has been released and documentation can be found [here](https://github.com/aws/aws-sdk-cpp#version-19-is-now-available). Please let us know if you have any more build issues
