### ISSUE TITLE
Is it possible to run describe_instances.exe on another box (i.e., one that it was not built on)?

### ISSUE THREAD

**Issue by RichDee** [aws/aws-sdk-cpp#1604]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

Windows 8.1 Professional (x64) (build 9600.19968)

Hello,

It is possible to run an aws sdk executable on a box that is different than the build box?

e.g.,
$ ./describe_instances.exe --usage
describe_instances.exe: error while loading shared libraries: ucrtbased.dll: cannot open shared object file: No such file or directory

**Comment by jmklix** [comment]
Yes, but it's not as simple as that. I think what you are looking for is cross compiling and it can be rather complicated to set up as explained [here](https://stackoverflow.com/questions/25153044/c-cross-platform-compiling). You can find an example of how to set it up using this sdk [here](https://github.com/aws/aws-sdk-cpp/issues/1288).

**Comment by RichDee** [comment]
I was not referring to another box as in another OS / platform; I was referring to another box as in another Windows box.

In other words, build the describe_instances.exe on one Windows box, then run it on another Windows box -- perhaps by statically linking it in Visual Studio?

Is that what you meant?

**Comment by jmklix** [comment]
You only need the DLL files if it's dynamically linked.

Cmake [example](https://github.com/awsdocs/aws-doc-sdk-examples/blob/75f2f0ae95834157cafd9641f11e56af883abd71/cpp/example_code/s3/CMakeLists.txt#L30) showing copying of DLLs to application directory.
