### ISSUE TITLE
Get notified when a transfer has been canceled

### ISSUE THREAD

**Issue by MartinDelille** [aws/aws-sdk-cpp#1605]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
MacOS / Linux

**Describe the question**

I want to be able to pause and restore my download queue where I have several assets.

I have written a piece of code where I start the download then cancel it: https://github.com/martindelille/aws-cancel-test

Is there no other way to be notified than waiting for the handle than using the synchro `TransferHandle::WaitUntilFinished()` ?

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by jmklix** [comment]
You can call TransferStatus which will give you one one the following results:

- EXACT_OBJECT_ALREADY_EXISTS
- NOT_STARTED
- IN_PROGRESS
- CANCELED
- FAILED 
- COMPLETED
- ABORTED

I'm not sure if this would be more useful for your use case. Make sure to check out the [API](http://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_transfer_1_1_transfer_handle.html#a18093b29709e109bda8dd324c8c1693c) if you haven't already

**Comment by MartinDelille** [comment]
My problem is that CANCELED is sent several times (one per part). I finally manage to guess that the asset has been totally cancelled this way:

```cpp
PartStateMap queuedParts,  pendingParts,  failedParts, completedParts;
handle->GetAllPartsTransactional(queuedParts,  pendingParts,  failedParts, completedParts);

if (queuedParts.size() == 0 && pendingParts.size() == 0) {
  if (failedParts.size()) {
    // => Asset canceled
  } else {
    // => Asset ready
  }
}
```

Two question:
- why not having a status telling all part are cancelled?
- why `TransferHandle::GetAllPartsTransactional()` is not `const`?

**Comment by KaibaLopez** [comment]
Hi @MartinDelille, 
I think you may be thinking of transferStatusUpdatedCallback...
```cpp
Aws::Utils::Threading::DefaultExecutor executor;
TransferManagerConfiguration config(&executor);
config.s3Client = m_s3Client; 
config.transferStatusUpdatedCallback =
 [&](const TransferManager* manager, const std::shared_ptr<const TransferHandle>& handle)
        { 
        //Do your check for Canceled here.
        }
 ```
 Let me know if this is what you were looking for.

**Comment by MartinDelille** [comment]
Yes this is where I put my code in with a little different: I had to convert to an non `const` handle since `TransferHandle::GetAllPartsTransactional()` is not const.

**Comment by KaibaLopez** [comment]
Hmmm I see, I'll take a look at the PR...
But at this point I feel like I can close this issue and keep an eye on the PR, specially since this turned into more of a fix than a question. 
Anyways, thanks for the PR!
