### ISSUE TITLE
CMake cannot find aws-c-event-stream while trying to use dynamodb

### ISSUE THREAD

**Issue by stephanecharette** [aws/aws-sdk-cpp#1609]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
While attempting to use this line in my cmake file:  `FIND_PACKAGE (AWSSDK COMPONENTS dynamodb REQUIRED)` I get this error:
```
-- Found AWS SDK for C++, Version: 1.8.174, Install Root:/usr, Platform Prefix:, Platform Dependent Libraries: pthread;crypto;ssl;z;curl
-- Components specified for AWSSDK: dynamodb, application will be depending on libs: aws-cpp-sdk-dynamodb;aws-cpp-sdk-core
-- Try finding aws-cpp-sdk-core
CMake Error at /snap/cmake/847/share/cmake-3.20/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Found package configuration file:

    /usr/lib/aws-c-event-stream/cmake/aws-c-event-stream-config.cmake

  but it set aws-c-event-stream_FOUND to FALSE so package
  "aws-c-event-stream" is considered to be NOT FOUND.  Reason given by
  package:

  The following imported targets are referenced, but are missing:
  AWS::aws-c-io
```

**SDK version number**
1.8.174

**Platform/OS/Hardware/Device**
What are you running the sdk on?
NVIDIA Jetson NX (arm-based)

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
- build and install the AWS SDK C++
- add the line `FIND_PACKAGE (AWSSDK COMPONENTS dynamodb REQUIRED)` to a project's CMakeLists.txt

**Expected behavior**
Packages are found.

**Logs/output**
See output above.

**Comment by KaibaLopez** [comment]
Hi @stephanecharette ,
Hmmm, can you walk me through how you are building and trying to use the SDK?  I don't think I've seen this issue before so I need to know how to reproduce exactly. 
Also, if you could show me the full CMakeLists.txt that might help.

**Comment by stephanecharette** [comment]
I've left the job where we had this issue, so I cannot provide any more details.  It was on a Jetson NX, and the AWS SDK was built from source on the NX itself.  (Took *forever* to compile!)  But if no-one has seen this before and it isn't obvious how to reproduce, I'd say go ahead and close it.

**Comment by KaibaLopez** [comment]
Oh...
Well if you ever see this problem again please open a new issue.
