### ISSUE TITLE
Add SOCKS5 and SOCKS5H schemes

### ISSUE THREAD

**Issue by ahmedyarub** [aws/aws-sdk-cpp#1612]
**Is your feature request related to a problem? Please describe.**
We cannot use SOCKS5H which is especially required for WebAssembly/Emscripten based implementations

**Describe the solution you'd like**
Add proxy protocols that can be used for for proxifying connections to AWS servers

**Describe alternatives you've considered**
Implementing an extension module, but this feature has been requested before by other devs and it's trivial to do.

**Additional context**
PR has been created 3 months ago and so far nobody has done anything to it:
https://github.com/aws/aws-sdk-cpp/pull/1562

**Comment by KaibaLopez** [comment]
Hi, Sorry for the delay on this, but yea I'm taking a look at this. hopefully we'll be merging the PR soon.

**Comment by PaavoHelde** [comment]
Any chance of getting this issue reactivated, or is there any other existing way to get the aws-cpp-sdk S3 traffic going through an SOCKS5 proxy?
