### ISSUE TITLE
Use conan for aws-sdk-cpp dependency

### ISSUE THREAD

**Issue by MartinDelille** [aws/aws-sdk-cpp#1613]
**Is your feature request related to a problem? Please describe.**

I managed to submit aws-sdk-cpp as an official formula for the [Conan center index](https://github.com/conan-io/conan-center-index/pull/4401) making easy to use the SDK for those using Conan as package manager. I'll be happy to have your feedback on this work and see how it could be improved (it is quite resource consuming for the continuous integration for example).

**Describe the solution you'd like**
Advertise the conan dependency option in the readme.

**Describe alternatives you've considered**
The alternative I've considered is that this issue won't be triage nor responded despite the time I invested in making this work. Hopefully having conan in the issue title might help someone interested in using conan to find this issue and use it as-is which would already make me happy! 😜 

**Additional context**
Nope

**Comment by KaibaLopez** [comment]
Hi @MartinDelille ,
So here's the thing, while it's really cool that you manage to submit an official formula, the problem with adding these to our Readme is that then I'd be responsible about maintaining it, and I just don't have the bandwidth... it's kind of the same reason we don't really recommend vcpkg even though the SDK is "available" there. 
Sorry this isn't the answer you were hoping for but I don't think we can take on this kind of requests.
I could maybe pin the issue for a while to make it more visible , that way I could close it but still have it around?

**Comment by MartinDelille** [comment]
I totally understand the low bandwith issue! Let's pin it.
