### ISSUE TITLE
Can't build aws-sdk-cpp 1.9 on Centos 6.10

### ISSUE THREAD

**Issue by Johnparke888** [aws/aws-sdk-cpp#1621]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Trying to build SDK 1.9. 
Getting following error:

CMake Error at /usr/local/lib64/cmake/AwsFindPackage.cmake:29 (find_package):
  By not providing "Findaws-crt-cpp.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "aws-crt-cpp", but CMake did not find one.

  Could not find a package configuration file provided by "aws-crt-cpp" with
  any of the following names:

    aws-crt-cppConfig.cmake
    aws-crt-cpp-config.cmake

**SDK version number**
1.9
**Platform/OS/Hardware/Device**
What are you running the sdk on?
Centos 6.10
**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

1. git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp
2. mkdir aws-sdk-cpp-build
3. cd aws-sdk-cpp-build

4. cmake ../aws-sdk-cpp -D CMAKE_C_COMPILER=/usr/local/gcc-10.2.0-2/bin/gcc -D CMAKE_CXX_COMPILER=/usr/local/gcc-10.2.0-2/bin/g++ -DCMAKE_MODULE_PATH=/usr/local/lib64/cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=OFF -DBUILD_DEPS=OFF -DCMAKE_BUILD_TYPE=Release -DCPP_STANDARD=17 -DBUILD_ONLY="s3;s3-crt;kms;s3-encryption"

**Expected behavior**

**Logs/output**
If applicable, add logs or error output.
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as static objects
-- Generating linux build config
-- Building project version: 1.9.1
--   Zlib library: /usr/lib64/libz.so
-- Encryption: Openssl
--   Openssl include directory: /usr/local/include
--   Openssl library: /usr/local/lib64/libssl.so;/usr/local/lib64/libcrypto.so
-- Http client: Curl
--   Curl include directory: /usr/local/include
--   Curl library: /usr/local/lib/libcurl.so
-- Add s3-crt:s3 to C2J_SPECIAL_NAME_LIST
-- Considering s3
-- Considering s3-crt
-- Considering kms
-- Considering s3-encryption
-- Updating version info to 1.9.1
-- Custom memory management disabled
CMake Error at /usr/local/lib64/cmake/AwsFindPackage.cmake:29 (find_package):
  By not providing "Findaws-crt-cpp.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "aws-crt-cpp", but CMake did not find one.

  Could not find a package configuration file provided by "aws-crt-cpp" with
  any of the following names:

    aws-crt-cppConfig.cmake
    aws-crt-cpp-config.cmake

  Add the installation prefix of "aws-crt-cpp" to CMAKE_PREFIX_PATH or set
  "aws-crt-cpp_DIR" to a directory containing one of the above files.  If
  "aws-crt-cpp" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  aws-cpp-sdk-core/CMakeLists.txt:489 (aws_use_package)

-- Configuring incomplete, errors occurred!
To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

**Comment by wps132230** [comment]
Hi there,
Could you turn ON the `BUILD_DEPS`? Otherwise, you need to build and install `aws-crt-cpp` by yourselves.

**Comment by Johnparke888** [comment]
Your were right. I hadn't noticed that. Thanks...

**Comment by Johnparke888** [comment]
Solution worked. Thanks for your help.
