### ISSUE TITLE
Bug with Cognito-IDP ListUsers API?

### ISSUE THREAD

**Issue by potatowiz69** [aws/aws-sdk-cpp#1622]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Windows 10 x64 C++ SDK Visual Studio 16 2019

**Describe the question/Problem**

Hello,

I'm trying to use the ListUsers from cognito-idp, yet it returns "MissingAuthenticationTokenException" everytime, I checked the documentations, it says that I don't need any token of any kind. I tried passing AccessToken only to be met with **"class "Aws::CognitoIdentityProvider::Model::ListUsersRequest" has no member "SetAccessToken""**. This leads to my listUsersOutcome.IsSuccess() always returning false. I could not find any example of C++ codes of Cognito ListUsers too. Also how do you get attributes and etc of a listUsersResult.GetUsers()? I tried writing GetAttributes()/GetUsername() just to be met with no member again.

I'm not sure if this is a bug or not, can anyone please try it out for me? And if it works could you please reply with some code example that I could study on?

Thank you very much.

**Comment by KaibaLopez** [comment]
Hi @potatowiz69 ,
Here's a quick sample on how to do the ListUsers call:
```cpp
#include <aws/core/Aws.h>
#include <aws/cognito-idp/CognitoIdentityProviderClient.h>
#include <aws/cognito-idp/model/ListUsersRequest.h>
#include <aws/cognito-idp/model/ListUsersResult.h>

int main(){
    Aws::SDKOptions options;
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;
    Aws::InitAPI(options);
    Aws::Client::ClientConfiguration ClientConfiguration("profile_name");
    auto client = Aws::MakeShared<Aws::CognitoIdentityProvider::CognitoIdentityProviderClient>("cognito_thing",ClientConfiguration);
    Aws::String UserPoolId = "the_pool_id_with_the_users";
    Aws::CognitoIdentityProvider::Model::ListUsersRequest request;
    request.WithUserPoolId(UserPoolId);
    auto result = client->ListUsers(request);

    if(!result.IsSuccess()){
        std::cout << result.GetError().GetMessage() << std::endl;
    }else{
        for (auto user: result.GetResult().GetUsers()) 
            std::cout<< user.GetUsername() << std::endl;
    }

    Aws::ShutdownAPI(options);
}
```
Let me know if you have other questions regarding this.

**Comment by potatowiz69** [comment]
> Hi @potatowiz69 ,
> Here's a quick sample on how to do the ListUsers call:
> 
> ```c++
> #include <aws/core/Aws.h>
> #include <aws/cognito-idp/CognitoIdentityProviderClient.h>
> #include <aws/cognito-idp/model/ListUsersRequest.h>
> #include <aws/cognito-idp/model/ListUsersResult.h>
> 
> int main(){
>     Aws::SDKOptions options;
>     options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;
>     Aws::InitAPI(options);
>     Aws::Client::ClientConfiguration ClientConfiguration("profile_name");
>     auto client = Aws::MakeShared<Aws::CognitoIdentityProvider::CognitoIdentityProviderClient>("cognito_thing",ClientConfiguration);
>     Aws::String UserPoolId = "the_pool_id_with_the_users";
>     Aws::CognitoIdentityProvider::Model::ListUsersRequest request;
>     request.WithUserPoolId(UserPoolId);
>     auto result = client->ListUsers(request);
> 
>     if(!result.IsSuccess()){
>         std::cout << result.GetError().GetMessage() << std::endl;
>     }else{
>         for (auto user: result.GetResult().GetUsers()) 
>             std::cout<< user.GetUsername() << std::endl;
>     }
> 
>     Aws::ShutdownAPI(options);
> }
> ```
> 
> Let me know if you have other questions regarding this.

I just tried this code, it returned MissingAuthenticationToken again, is there any settings in Cognito I have to lookout for?

**Comment by KaibaLopez** [comment]
@potatowiz69 ,
ok, it seems like it could be a problem with your credentials set up, let's make sure though.
In the above code, can you change the log level to trace ?
```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
```
And then go through that log file, censor your credentials and keys, and then upload that here? That should give us the info we need.

**Comment by potatowiz69** [comment]
I see, that we require credentials and keys, I got it now, thanks!
