### ISSUE TITLE
Version 1.9 SDK Build Error

### ISSUE THREAD

**Issue by Johnparke888** [aws/aws-sdk-cpp#1623]
Trying to build version 1.9 of SDK, with following cmake invokation:

cmake ../aws-sdk-cpp -D CMAKE_C_COMPILER=/usr/local/gcc-10.3.0/bin/gcc -D CMAKE_CXX_COMPILER=/usr/local/gcc-10.3.0/bin/g++ -DCMAKE_MODULE_PATH=/usr/local/lib64/cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=OFF -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE=Release -DCPP_STANDARD=17 -DBUILD_ONLY="s3;s3-crt;kms;s3-encryption"

I am getting a number of error messages referring to Aws::Crt::ByteCursorFromString invalid initialization of reference type string& from string:

signing_config_override.service = Aws::Crt::ByteCursorFromString(computeEndpointOutcome.GetResult().signerServiceName);
503:103: error: invalid initialization of reference of type 'const String&' {aka
const std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Crt::StlAllocator<char> >&'} from expression of type 'Aws::String' {aka
std::__cxx11::basic_string<char>'}

This shows up repeatedly (showing first few):
 
[ 85%] Linking CXX static library libaws-cpp-sdk-s3.a
[ 85%] Built target aws-cpp-sdk-s3
[ 86%] Building CXX object aws-cpp-sdk-s3-crt/CMakeFiles/aws-cpp-sdk-s3-crt.dir/ub_S3-CRT.cpp.o
[ 85%] Built target aws-cpp-sdk-s3
[ 86%] Building CXX object aws-cpp-sdk-s3-crt/CMakeFiles/aws-cpp-sdk-s3-crt.dir/ub_S3-CRT.cpp.o
In file included from /usr/aws-sdk-cpp-build/aws-cpp-sdk-s3-crt/ub_S3-CRT.cpp:3:
/usr/aws-sdk-cpp/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp: In member function 'void Aws::S3Crt::S3CrtClient::init(const Aws::S3Crt::ClientC
nfiguration&, const Aws::Auth::AWSCredentials*)':
/usr/aws-sdk-cpp/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp:203:62: error: invalid initialization of reference of type 'const String&' {aka '
onst std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Crt::StlAllocator<char> >&'} from expression of type 'const String' {aka
const std::__cxx11::basic_string<char>'}
  203 |   s3CrtConfig.region = Aws::Crt::ByteCursorFromString(config.region);
      |                                                       ~~~~~~~^~~~~~
In file included from /usr/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/io/Bootstrap.h:8,
                 from /usr/aws-sdk-cpp/aws-cpp-sdk-s3-crt/include/aws/s3-crt/ClientConfiguration.h:13,
                 from /usr/aws-sdk-cpp/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h:12,
                 from /usr/aws-sdk-cpp/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp:22,
                 from /usr/aws-sdk-cpp-build/aws-cpp-sdk-s3-crt/ub_S3-CRT.cpp:3:
/usr/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/Types.h:66:76: note: in passing argument 1 of 'Aws::Crt::ByteCursor Aws::Crt::ByteCursorFro
String(const String&)'
   66 |         AWS_CRT_CPP_API ByteCursor ByteCursorFromString(const Crt::String &str) noexcept;
      |                                                         ~~~~~~~~~~~~~~~~~~~^~~
In file included from /usr/aws-sdk-cpp-build/aws-cpp-sdk-s3-crt/ub_S3-CRT.cpp:3:
/usr/aws-sdk-cpp/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp:211:92: error: invalid initialization of reference of type 'const String&' {aka '
onst std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Crt::StlAllocator<char> >&'} from expression of type 'const String' {aka
const std::__cxx11::basic_string<char>'}
  211 |     staticCreds.AccessKeyId = Aws::Crt::ByteCursorFromString(credentials->GetAWSAccessKeyId());
      |                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /usr/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/io/Bootstrap.h:8,
                 from /usr/aws-sdk-cpp/aws-cpp-sdk-s3-crt/include/aws/s3-crt/ClientConfiguration.h:13,
                 from /usr/aws-sdk-cpp/aws-cpp-sdk-s3-crt/include/aws/s3-crt/S3CrtClient.h:12,
                 from /usr/aws-sdk-cpp/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp:22,
                 from /usr/aws-sdk-cpp-build/aws-cpp-sdk-s3-crt/ub_S3-CRT.cpp:3:

Obviously this is caused by trying to pass value by reference. 

I attempted to see if value could be passed by value rather than by reference, but this did not work.

Could use your help with this.

Thanks for your help.

John

**Comment by KaibaLopez** [comment]
Hi @Johnparke888 ,
I am not able to reproduce this issue... but we have been patching this sort of problems this week, could you try the newest version of the SDK (1.9.5) , see if that still gives you problems? 
If it does, I'm going to need more details on your environment like, what linux distribution and version are you using?

**Comment by jweinst1** [comment]
```
-DCPP_STANDARD=17
```

Why use this option ? Try removing it and see if there's an improvement. I have never had to use that when building the sdk for other projects.

**Comment by Johnparke888** [comment]
I retrieved latest release and removed option. This fixed the problem. Thank you very much for your help. John
