### ISSUE TITLE
Leverage HEAD+GET behavior from transfer manager to defer stream creation

### ISSUE THREAD

**Issue by nikki-dong** [aws/aws-sdk-cpp#1624]
**Is your feature request related to a problem? Please describe.**
I have a use case where I need to download objects into a buffer(mmapped to the size of the object, which involves a HEAD request first).  I have been using transfer manager and it's been great. I noticed it also first sends a HEAD request to find out object size to determine the version, and whether multipart download is needed. 

**Describe the solution you'd like**
I'm currently passing a stream creation function to Transfer Manager, which points to the preallocated mmap area. I noticed the Transfer Manager will trigger the handle status to IN_PROGRESS after the size of the object is determined. I wonder if it's possible to defer the creation of the stream, inside the status update callback, so I can essentially get rid of the my own HEAD request, piggybacking on the size information Transfer Manager received.

My previous work flow:  
HEAD (get size) -> mmap -> DownloadFile
Now:
DownloadFile -> Status update to IN_PROGRESS (size known) -> mmap

**Describe alternatives you've considered**
I do not know if there is any other work around.

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @nikki-dong ,
Sorry for the delayed response, it sounds like reasonable request, I'd have to look more into it but the truth is that I can't promise a date for it to happen.
