### ISSUE TITLE
Build error while building source on Windows

### ISSUE THREAD

**Issue by shahidur106** [aws/aws-sdk-cpp#1629]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Env**
Platform/OS/Hardware/Device
Windows 10 64Bit
cmake version 3.20.0

**Describe the question**
I am trying to build the main branch source.
Source download command:
`git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp`

After downloading the source run below command:
```
mkdir build
cd build
"C:\Program Files\CMake\bin\cmake.exe" C:\dev-wa\AWSSDKCPP\aws-sdk-cpp -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:\dev-wa\AWSSDKCPP\build\Debug\ -DBUILD_ONLY="apigatewaymanagementapi;sqs" -DCMAKE_BUILD_TYPE=Debug
"c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" INSTALL.vcxproj /p:Configuration=Debug
```
**Logs/output**
Below are the CMD console logs. (Sorry for logs in Japanese)

```
ビルドに失敗しました。

"C:\dev-wa\AWSSDKCPP\build\INSTALL.vcxproj" (既定のターゲット) (1) ->
"C:\dev-wa\AWSSDKCPP\build\ALL_BUILD.vcxproj" (既定のターゲット) (3) ->
"C:\dev-wa\AWSSDKCPP\build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj" (既定のターゲット) (22) ->
(ClCompile ターゲット) ->
  C:\dev-wa\AWSSDKCPP\aws-sdk-cpp\aws-cpp-sdk-core-tests\utils\StringUtilsTest.cpp(542): warning C4819: ファイルは、現在のコード ページ (932) で表示できない文字を含んでいます。データの損失を防ぐために、ファイルを Unicode 形式で保存してください。 [C:\dev-wa\AWSSDKCPP\build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]


"C:\dev-wa\AWSSDKCPP\build\INSTALL.vcxproj" (既定のターゲット) (1) ->
"C:\dev-wa\AWSSDKCPP\build\ALL_BUILD.vcxproj" (既定のターゲット) (3) ->
"C:\dev-wa\AWSSDKCPP\build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj" (既定のターゲット) (22) ->
(ClCompile ターゲット) ->
  C:\dev-wa\AWSSDKCPP\aws-sdk-cpp\aws-cpp-sdk-core-tests\utils\StringUtilsTest.cpp(542): error C2220: 警告をエラーとして扱いました。'object' ファイルは生成されません。 [C:\dev-wa\AWSSDKCPP\build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]

    1 個の警告
    1 エラー
```
The error saying that the file 'C:\dev-wa\AWSSDKCPP\aws-sdk-cpp\aws-cpp-sdk-core-tests\utils\StringUtilsTest.cpp' has error as below:
`The file contains characters that cannot be displayed in the current code page (932). Save the file in Unicode format to prevent data loss. `

**Resolution**
The encoding of StringUtilsTest.cpp file is UTF-8.
But If change the encoding to UTF-8-BOM
Then build goes fine.

Thanks.

**Comment by KaibaLopez** [comment]
Hi @shahidur106 ,
Thanks for pointing this out to us, we'll try and get it fixed as soon as possible.
