### ISSUE TITLE
SQSClient hardcoded to POST

### ISSUE THREAD

**Issue by Bu11etmagnet** [aws/aws-sdk-cpp#163]
According to the [SQS developer guide](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/MakingRequests_MakingQueryRequestsArticle.html), SQS requests can be made with GET, but SQSClient always calls MakeRequest with method hard-coded to HttpMethod::HTTP_POST.

SQSClient should support the GET method too.

**Comment by JonathanHenson** [comment]
What in particular are you hoping to do with GET that can't be done with POST? They are two different protocols for the same API.

**Comment by Bu11etmagnet** [comment]
Easier to debug. All the info is logged for a GET request (it's all in the URI) ; parameters passed in a POST request are not logged.

**Comment by JonathanHenson** [comment]
Why not use a proxy like burp suite and add it to your client config? Then you can see the whole http layer.
