### ISSUE TITLE
Allow users to select local port or range of port

### ISSUE THREAD

**Issue by lrsays** [aws/aws-sdk-cpp#1630]
Please add a new configuration parameter in InitAPI to allow users select port or range of ports to establish communication with AWS API server. This helps us use CPP SDK on platforms where not all local ports are open to establish TCP connection (by SDK), on such platforms we need to open network ports in advance. Since AWS SDK picks up random port to do DNS followed by request to AWS servers all such requests fail on such restricted platforms as ports selected by AWS SDK are not open and user is not aware which port is used by AWS SDK unless SDK makes the call.
Thanks

**Comment by KaibaLopez** [comment]
Hi @lrsays ,
Is there a reason you cannot use ClientConfiguration's Proxyport on your client? Like:
```cpp
Aws::Client::ClientConfiguration config("profile");
ClientConfiguration.proxyPort = 8080;
auto m_client = Aws::MakeUnique<Aws::S3::S3Client>("S3 Client", config);
```

**Comment by lrsays** [comment]
Documentation says proxyPort can be used if we are using proxy server, my use case is having list of local ports configured so that TCP connections are initiated from those ports. AWS API server doesn't work well with multiple requests coming from same IP and port. Is it possible to give list of local ports API queries can use to establish connections with API server?
I don't want to use any proxy machine in between, my problem is to know which port SDK will use when queries are sent, even if SDK can give me list of ports before making calls is a workable solution. Thanks

unsigned Aws::Client::ClientConfiguration::proxyPort
If you have users going through a proxy, set the port here.

**Comment by KaibaLopez** [comment]
Hi @lrsays ,
Ok yea, we don't have an exposed variable to directly change that in the SDK , but we do allow to use customized http clients and then you can have those customize curl to use the ports or port range you need. 
Try following [this example ](https://github.com/awsdocs/aws-doc-sdk-examples/blob/68fbaa852c2ad8365b2671638a78124688f8f54d/cpp/example_code/s3/list_buckets_disabling_dns_cache.cpp#L45) and change line :
`curl_easy_setopt(connectionHandle, CURLOPT_DNS_CACHE_TIMEOUT, 0L);`
To match the ports you'd like to use... and just in case here's some documentation on the call:
* [curl_easy_setopt](https://curl.se/libcurl/c/curl_easy_setopt.html)
* [CURLOPT_LOCALPORT](https://curl.se/libcurl/c/CURLOPT_LOCALPORT.html)
* [CURLOPT_LOCALPORTRANGE](https://curl.se/libcurl/c/CURLOPT_LOCALPORTRANGE.html)
Let me know if this is what you were looking for or if I misunderstood again.

**Comment by lrsays** [comment]
Thanks a lot @KaibaLopez, I was looking for similar options to customize client code. I'll make changes in my application to have a customized http client with right set of curl options set.
