### ISSUE TITLE
Symbols are not exported on Mac as shared libraries

### ISSUE THREAD

**Issue by shinyanger** [aws/aws-sdk-cpp#1631]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Symbols are not exported on Mac as shared libraries. Then we get link error when building application.

**SDK version number**
1.2

**Platform/OS/Hardware/Device**
What are you running the sdk on?
macOS Big Sur

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

**Expected behavior**
Symbols declared with AWS_*_API should be exported.

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

On Mac, need to explicitly set the visibility attribute for symbols. Here is the patch for aws-sdk-cpp-core:
```
diff -r -u a/aws-sdk-cpp-core/include/aws/core/Core_EXPORTS.h b/aws-sdk-cpp-core/include/aws/core/Core_EXPORTS.h
--- a/aws-sdk-cpp-core/include/aws/core/Core_EXPORTS.h	2021-04-27 16:25:45.000000000 +0800
+++ b/aws-sdk-cpp-core/include/aws/core/Core_EXPORTS.h	2021-04-27 17:14:58.000000000 +0800
@@ -31,6 +31,12 @@
     #else // USE_IMPORT_EXPORT
         #define AWS_CORE_API
     #endif // USE_IMPORT_EXPORT
+#elif defined (__APPLE__)
+    #ifdef USE_IMPORT_EXPORT
+        #define AWS_CORE_API __attribute__((visibility("default")))
+    #else // USE_IMPORT_EXPORT
+        #define AWS_CORE_API
+    #endif // USE_IMPORT_EXPORT
 #else // defined (USE_WINDOWS_DLL_SEMANTICS) || defined (WIN32)
     #define AWS_CORE_API
 #endif // defined (USE_WINDOWS_DLL_SEMANTICS) || defined (WIN32)
diff -r -u a/aws-sdk-cpp-core/include/aws/core/external/json-cpp/json.h b/aws-sdk-cpp-core/include/aws/core/external/json-cpp/json.h
--- a/aws-sdk-cpp-core/include/aws/core/external/json-cpp/json.h	2021-04-27 16:25:45.000000000 +0800
+++ b/aws-sdk-cpp-core/include/aws/core/external/json-cpp/json.h	2021-04-27 17:24:08.000000000 +0800
@@ -178,6 +178,8 @@
             #define AWS_JSON_API __declspec(dllimport)
             #define AWS_JSONCPP_DISABLE_DLL_INTERFACE_WARNING
         #endif // AWS_CORE_EXPORTS
+    #elif defined(__APPLE__)
+        #define AWS_JSON_API __attribute__((visibility("default")))
     #endif // if defined(_MSC_VER)
 #endif // ifdef AWS_JSON_IN_CPPTL
 #if !defined(AWS_JSON_API)
diff -r -u a/aws-sdk-cpp-core/include/aws/core/external/tinyxml2/tinyxml2.h b/aws-sdk-cpp-core/include/aws/core/external/tinyxml2/tinyxml2.h
--- a/aws-sdk-cpp-core/include/aws/core/external/tinyxml2/tinyxml2.h	2021-04-27 16:25:45.000000000 +0800
+++ b/aws-sdk-cpp-core/include/aws/core/external/tinyxml2/tinyxml2.h	2021-04-27 17:24:25.000000000 +0800
@@ -77,6 +77,10 @@
             #define TINYXML2_LIB __declspec(dllimport)
         #endif // AWS_CORE_EXPORTS
     #endif // USE_IMPORT_EXPORT
+#elif defined(__APPLE__)
+    #ifdef USE_IMPORT_EXPORT
+        #define TINYXML2_LIB __attribute__((visibility("default")))
+    #endif
 #endif
 
 #ifndef TINYXML2_LIB
```

**Comment by KaibaLopez** [comment]
Hi @shinyanger ,
I'm going to need information on how you're getting to this error. 
* What steps are you taking to build the SDK?
* What version of the SDK are you running? If it is 1.2, then I'm going to ask you to update it to a newer version, that one is way too old.
* What are the error messages you are seeing? 

I need to be able to reproduce the error before taking the changes you are suggesting.

**Comment by shinyanger** [comment]
Hi @KaibaLopez ,

We use cmake to build the SDK. We force set the host application built as shared libraries:
`set(BUILD_SHARED_LIBS ON CACHE BOOL "Build dylibs?" FORCE)`

Although we use an old version, in the latest version in the export headers, the AWS_*_API part is not changed.

When building host application, we get the link error:
```
[build] Undefined symbols for architecture x86_64:
[build]   "Aws::AmazonWebServiceRequest::AmazonWebServiceRequest()", referenced from:
[build]       Aws::AmazonSerializableWebServiceRequest::AmazonSerializableWebServiceRequest() in CreateDeliveryStreamRequest.cpp.o
[build]       Aws::AmazonSerializableWebServiceRequest::AmazonSerializableWebServiceRequest() in DeleteDeliveryStreamRequest.cpp.o
[build]       Aws::AmazonSerializableWebServiceRequest::AmazonSerializableWebServiceRequest() in DescribeDeliveryStreamRequest.cpp.o
[build]       Aws::AmazonSerializableWebServiceRequest::AmazonSerializableWebServiceRequest() in GetKinesisStreamRequest.cpp.o
[build]       Aws::AmazonSerializableWebServiceRequest::AmazonSerializableWebServiceRequest() in ListDeliveryStreamsRequest.cpp.o
[build]       Aws::AmazonSerializableWebServiceRequest::AmazonSerializableWebServiceRequest() in PutRecordBatchRequest.cpp.o
[build]       Aws::AmazonSerializableWebServiceRequest::AmazonSerializableWebServiceRequest() in PutRecordRequest.cpp.o
[build]       ...
...
```

Then check the symbols of the dylib with:
`nm ./libaws-sdk-cpp-core.dylib | grep AmazonSerializableWebServiceRequest`

The output:
```
0000000000005910 t __ZN3Aws35AmazonSerializableWebServiceRequestD0Ev
0000000000005900 t __ZN3Aws35AmazonSerializableWebServiceRequestD1Ev
00000000000055e0 t __ZNK3Aws35AmazonSerializableWebServiceRequest7GetBodyEv
0000000000420e08 s __ZTIN3Aws35AmazonSerializableWebServiceRequestE
00000000003f0ef0 s __ZTSN3Aws35AmazonSerializableWebServiceRequestE
0000000000420d30 s __ZTVN3Aws35AmazonSerializableWebServiceRequestE
```

Note that the lower case 't' and 's' indicate they are local symbols. They are invisible to linker.

After adding the visibility attribute and check the symbols again:
```
00000000000058b0 t __ZN3Aws35AmazonSerializableWebServiceRequestD0Ev
00000000000058a0 t __ZN3Aws35AmazonSerializableWebServiceRequestD1Ev
0000000000005580 T __ZNK3Aws35AmazonSerializableWebServiceRequest7GetBodyEv
0000000000420ee8 S __ZTIN3Aws35AmazonSerializableWebServiceRequestE
00000000003f0ef0 S __ZTSN3Aws35AmazonSerializableWebServiceRequestE
0000000000420e10 S __ZTVN3Aws35AmazonSerializableWebServiceRequestE
```

Some of them become upper case. Symbols are exported now.

The visibility attribute is referenced from Dynamic Library Design Guidelines:
[https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryDesignGuidelines.html](url)
See Symbol Exporting Strategies section.

**Comment by KaibaLopez** [comment]
I guess my problem is that I am not able to reproduce this... I can build the SDK as shared libraries with no problem, more over, there should be no need to force shared libraries.
Like, the SDK builds shared libraries by default, it can also be set to build shared libraries via the CMake argument `-DBUILD_SHARED_LIBS=ON`.
It seems to me that there is a disconnect in the parameters you're using when building the SDK and your host app.
Unless you can walk me through how to reproduce this issue on the SDK I am afraid I can't really help you with this.

**Comment by shinyanger** [comment]
I will try to create a sample application later.
