### ISSUE TITLE
Documentation for rds-data usage

### ISSUE THREAD

**Issue by justinpchang** [aws/aws-sdk-cpp#1632]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?

Docker/ubuntu:latest

**Describe the question**

Hi, all. I was wondering where I can find documentation or example code for querying an Amazon RDS Postgres database from my C++ application. I couldn't find any through amazon documentation or in Github issues. If I simply want to query this database, is the aws-sdk the best choice, or should I just use SQLAPI++ or some similar API for interfacing with regular PostgreSQL databases?

**Comment by KaibaLopez** [comment]
Hi @justinpchang ,
Yea we don't have that many doc samples for our services... Good news is we do have integration tests on RDS, you could use those to guide you on how to use the service. 
[Look here.](https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-rds-integration-tests/RDSTest.cpp)
Let me know if this helps. Or if you have other more specific questions
