### ISSUE TITLE
[transfer-manager] Add a helper function for querying contiguous downloaded bytes from the beginning of a file

### ISSUE THREAD

**Issue by timtianyang** [aws/aws-sdk-cpp#1636]
**Is your feature request related to a problem? Please describe.**
Currently the transfer manager provides convenient ways to run callbacks, such as during status and progress updates. This gives a way for users to poll if files are ready. One use case is to "stream" files to users, without waiting for the entire file to finish downloading. It is possible for users to query all completed parts and calculate how many bytes are ready for streaming, from the _start_ of the file.

However, multi-part downloads make things a bit complicated since different parts of the file may finish downloading in a none-deterministic order. The following example shows a typical situation one may face for a file with 4 parts:

```
p0   p1   p2   p3
|====|=   |====|=   |
```

Part 0 and part 2 are finished, but because part 1 is not yet completed, only part 0's total byte size is available for users to stream. The accounting users must do involves careful locking and iterating the completed part map.

**Describe the solution you'd like**
Transfer manager already contains stateful information and it should be fairly non-intrusive to cache the number of continuous bytes downloaded from the start of the file, prior to when progress update callback is triggered.

With a single API to query number of bytes available from the start, it alleviates the burden from users.

Reviewers, I'm willing to work on this and please assign it to me if you think it's a good idea.

**Comment by KaibaLopez** [comment]
Hi @timtianyang ,
This sound like a relatively safe change to make, so yea we'd really appreciate your contribution.
