### ISSUE TITLE
Can't build C++ SDK on Ubuntu 20

### ISSUE THREAD

**Issue by mecono** [aws/aws-sdk-cpp#1638]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?  
    Ubuntu 20

**Describe the question** 
   Cannot build SDK

**Logs/output**

dev@dev-Macmini:/usr/local/aws-sdk-cpp-main$ sudo cmake CMakeLists.txt 
CMake Warning (dev) at /snap/cmake/870/share/cmake-3.20/Modules/GNUInstallDirs.cmake:236 (message):
  Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
  target architecture is known.  Please enable at least one language before
  including GNUInstallDirs.
Call Stack (most recent call first):
  CMakeLists.txt:109 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating linux build config
-- Building project version: 1.9.10
-- The CXX compiler identification is GNU 9.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
--   Zlib library: /usr/lib/x86_64-linux-gnu/libz.so
-- Encryption: Openssl
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1f")  
--   Openssl include directory: /usr/include
--   Openssl library: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Http client: Curl
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.68.0")  
--   Curl include directory: /usr/include/x86_64-linux-gnu
--   Curl library: /usr/lib/x86_64-linux-gnu/libcurl.so
-- Performing Test HAVE_ATOMICS_WITHOUT_LIBATOMIC
-- Performing Test HAVE_ATOMICS_WITHOUT_LIBATOMIC - Success
CMake Error at CMakeLists.txt:184 (include):
  include could not find requested file:

    AwsFindPackage

CMake Error at CMakeLists.txt:194 (add_subdirectory):
  The source directory

    /usr/local/aws-sdk-cpp-main/crt/aws-crt-cpp

  does not contain a CMakeLists.txt file.

-- Add s3-crt:s3 to C2J_SPECIAL_NAME_LIST
-- Looking for pathconf
-- Looking for pathconf - found
-- Looking for umask
-- Looking for umask - found
-- The C compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Updating version info to 1.9.10
-- Custom memory management enabled; stl objects now using custom allocators
-- Performing Test CURL_HAS_H2
-- Performing Test CURL_HAS_H2 - Success
-- Performing Test CURL_HAS_TLS_PROXY
-- Performing Test CURL_HAS_TLS_PROXY - Success
CMake Error at aws-cpp-sdk-core/CMakeLists.txt:496 (aws_use_package):
  Unknown CMake command "aws_use_package".

-- Configuring incomplete, errors occurred!
See also "/usr/local/aws-sdk-cpp-main/CMakeFiles/CMakeOutput.log".

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
Hi @mecono ,
Can you verified if you used the recursive option when cloning the repository? It looks like cmake is not finding the crt libraries, and that would the most common scenario.
If you didn't or are not sure, you can just run the instruction in the ReadMe:
```
cd aws-sdk-cpp
git checkout main
git pull origin main
git submodule update --init --recursive
```
Let me know if that's not the case.

**Comment by mecono** [comment]
Hi @KaibaLopez ,

I did not clone the repo from git, I just downloaded the .zip file, then extracted it and attempted to build.  Can you please send me full set of commands to do fresh install / build using git?

Thanks,

Michael

**Comment by mecono** [comment]
Hi @KaibaLopez , can you tell me if these instructions shown below are up-t- date and accurate?  Any missing information I will need?  Thanks

https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup-linux.html

**Comment by KaibaLopez** [comment]
Yea these are correct and up to date, if you have the same issue while following them, then we might have a bug, so I'd need to investigate.
Also, you may have notice in the same guide, but we don't yet guarantee that the sdk will compile correctly with cmake versions newer than 3.18 so you might want to downgrade your cmake version. 
Let me know if you still face the same issue or have other problems.

**Comment by mecono** [comment]
> Yea these are correct and up to date, if you have the same issue while following them, then we might have a bug, so I'd need to investigate.
> Also, you may have notice in the same guide, but we don't yet guarantee that the sdk will compile correctly with cmake versions newer than 3.18 so you might want to downgrade your cmake version.
> Let me know if you still face the same issue or have other problems.

It's working, and I didn't need the downgrade cmake.  The problem only occurred because was trying to build by downloading a .zip of the repo.  But I had to use git clone instead. Not sure why, shouldn't I end up with the same exact code either way?  

Anyway, using git is  fine, thanks again for your help.

-Michael

**Comment by KaibaLopez** [comment]
Yea I think this is a side effect of switching to git submodules for our dependencies. I'll look a bit into it to see if it just won't be supported or if there's something we can do about it, for now though, good to hear you got it to work.
