### ISSUE TITLE
CreateMultipartUpload : curlCode: 6, Couldn't resolve host name

### ISSUE THREAD

**Issue by zxdposter** [aws/aws-sdk-cpp#1639]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Use custom endpoint, make error : **curlCode: 6, Couldn't resolve host name**

**SDK version number**
1.9.8

**Platform/OS/Hardware/Device**
What are you running the sdk on?
ubuntu:14.04

**To Reproduce (observed behavior)**
use custom endpoint:
```cpp
    clientConfiguration.scheme = Aws::Http::Scheme::HTTP;
    clientConfiguration.verifySSL = true;
    clientConfiguration.endpointOverride = "http://mycustomip:port";
    clientConfiguration.region = "cn-north-1";
```

after that,  call CreateMultipartUpload:
```cpp
Aws::String
initMultipart(const Aws::S3::S3Client &s3Client, const Aws::String &bucketName, const Aws::String &objectName) {
    Aws::S3::Model::CreateMultipartUploadRequest createMultipartRequest;
    createMultipartRequest.WithBucket(bucketName).WithKey(objectName);

    //1. init
    auto createMultiPartResult = s3Client.CreateMultipartUpload(createMultipartRequest);
    if (createMultiPartResult.IsSuccess()) {
        std::cout << "createMultipartUpload ok, uploadId = " << createMultiPartResult.GetResult().GetUploadId()
                  << std::endl;
        return createMultiPartResult.GetResult().GetUploadId();
    } else {
        std::cout << "Create MultipartUpload failed" << createMultiPartResult.GetError().GetMessage() << std::endl;
        return "";
    }
}
```

**Expected behavior**
If I don't use custom endpoint, I got normal behavior, return upload id.

**Logs/output**
curlCode: 6, Couldn't resolve host name

I add this code, but no more log have:
```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**
I use custom endpoint, this function have normal behavior:
```cpp
bool findTheBucket(const Aws::S3::S3Client &s3Client,
                   const Aws::String &bucketName) {

    Aws::S3::Model::ListBucketsOutcome outcome = s3Client.ListBuckets();

    if (outcome.IsSuccess()) {
        std::cout << "Looking for a bucket named '" << bucketName << "'..."
                  << std::endl << std::endl;

        Aws::Vector <Aws::S3::Model::Bucket> bucket_list =
                outcome.GetResult().GetBuckets();

        for (Aws::S3::Model::Bucket const &bucket : bucket_list) {
            if (bucket.GetName() == bucketName) {
                std::cout << "Found the bucket." << std::endl << std::endl;
                return true;
            }
        }

        std::cout << "Could not find the bucket." << std::endl << std::endl;
    } else {
        std::cout << "ListBuckets error: "
                  << outcome.GetError().GetMessage() << std::endl;
    }

    return false;
}
```

**Comment by zxdposter** [comment]
I found error log :
>[DEBUG] 2021-05-07 06:59:44.027 CURL [365105342064] (Text) getaddrinfo(3) failed for zxdtest.mycustomip:port
[DEBUG] 2021-05-07 06:59:44.027 CURL [365105342064] (Text) Couldn't resolve host 'zxdtest.mycustomip'
[DEBUG] 2021-05-07 06:59:44.027 CURL [365105342064] (Text) Closing connection 0

How can I solve this ?

**Comment by zxdposter** [comment]
I found solution
```cpp
Aws::S3::S3Client s3_client = Aws::S3::S3Client(Aws::Auth::AWSCredentials("user","user_pswd"), config, Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Never, false);
```

**Comment by wangjunxiao0207** [comment]
Thanks, Bro. I also had this problem, and this solve it.
