### ISSUE TITLE
Why don't libs install directly into the install prefix libs directory?

### ISSUE THREAD

**Issue by zwass** [aws/aws-sdk-cpp#164]
This came up in the discussion on my PR to get the SDK included into Homebrew (https://github.com/Homebrew/homebrew-core/pull/109). Is there a reason why the libraries are installed into `/usr/local/lib/[linux|mac]/Release` rather than just `/usr/local/lib`? As it stands, symlinks need to be created for regular linker flags to pick up the libraries.

**Comment by bretambrose** [comment]
The install setup was configured for our first "real" customer, which needed the binaries for all supported platforms placed side-by-side, hence the additional folder indirection.  It sounds like it would be better if that kind of install was not the default but instead an off-by-default option.  I'll look into what the scope of that would be.

**Comment by zwass** [comment]
Thanks for clarifying @bretambrose. We've just been symlinking the libraries from the nested directory - so it's not a blocker for us - but I do think it would make things simpler for future users if the installation is a bit more standard.

**Comment by JonathanHenson** [comment]
This fix is coming really soon. We are testing the build currently

**Comment by bretambrose** [comment]
A new cmake option is available with the latest version that should resolve this: -DSIMPLE_INSTALL=ON

**Comment by JonathanHenson** [comment]
Any updates on this @zwass? Does the update we provided work for you?

**Comment by zwass** [comment]
@JonathanHenson: I haven't had a chance to test this (particularly since the old behavior + symlinks is working fine), but it sounds like the simple install option will allow us to simplify the Homebrew installation. Thank you.
