### ISSUE TITLE
S3CrtClient doesn't call handler on error

### ISSUE THREAD

**Issue by baarmaley** [aws/aws-sdk-cpp#1640]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**

`S3CrtClient::PutObjectAsync` and `S3CrtClient::GetObjectAsync` never call handler if `aws_s3_client_make_meta_request` return `NULL`

**SDK version number**
1.9

**Platform/OS/Hardware/Device**
Ubuntu 20.04

**To Reproduce (observed behavior)**
```
// Get the Amazon S3 object from the bucket.
Aws::S3Crt::Model::GetObjectRequest request;
request.SetBucket(bucketName);
request.SetKey(objectKey);
request.SetRange("bytes=1-5");

Aws::S3Crt::Model::GetObjectOutcome outcome =  s3CrtClient.GetObject(request); // <-- thread is blocked forever

if (outcome.IsSuccess()) {
    std::cout << "Success!";
}else{
    std::cout << "Fail!";
}

```

or any other example where an error occurs while creating a request

**Expected behavior**

printing "Fail"

**Logs/output**
```
[INFO] 2021-05-07 11:45:57.382 S3Client [140463331858176] id=0x55b13b38df70 Initiating making of meta request
[ERROR] 2021-05-07 11:45:57.382 S3MetaRequest [140463331858176] Could not create auto-ranged-get meta request; handling of ranged header is currently unsupported.
[ERROR] 2021-05-07 11:45:57.382 S3Client [140463331858176] id=0x55b13b38df70: Could not create new meta request.

```

**Comment by KaibaLopez** [comment]
Hi @baarmaley ,
I am not sure I quite follow, the reproduction method here. 
Are you trying to use getObject or getObjectAsync? 
The reproduction code you provide should work, or at least it works for me, is there anything else you're doing that might cause the error?
