### ISSUE TITLE
how could i know if the bucket exists

### ISSUE THREAD

**Issue by ProgrammerZhujinming** [aws/aws-sdk-cpp#1644]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
windows

**Describe the question**
Hi!  
How could i know if the bucket exists? I find the method which is called HeadBucket, but i can't use it's return value, so could you help me and i will be very appreciated if you can answer my questions above. I find if the bucket exists, the response will return 200, but how can i get the response, i can only get the S3Error and it's response code, but it keeps zeor. My aws-sdk-cpp version is 1.0.164, and i can't change it now.

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
HeadBucketRequest headBucketRequest;
headBucketRequest.WithBucket(strBucketName);
auto out = pClient->HeadBucket(headBucketRequest);
```
how can i get the response code

**Comment by KaibaLopez** [comment]
Hi @ProgrammerZhujinming ,
Kind of depends on what the use case you want this to be for.
To give you an example, you could do a ListBuckets request and compare the result, or get the `outcome.GetError().GetMessage()  `. 
Can you maybe provide sample code on your use case?

**Comment by ProgrammerZhujinming** [comment]
Hi.
Actually, i just want to know how can I know if the bucket exists by a head bucket request rather than get bucket list and traverse it. The API reference shows that S3Client has the method which called HeadBucket can do this and return 200 if the request is success, but I don't know how to get the response code.

Could you help me? I will be very appreciated.

**Comment by KaibaLopez** [comment]
So... the headbucket request is a kind of boolean response, it either succeeds or gets you the error... There is no body to the outcome response on the cpp implementation unless it fails. Here's a quick sample:
```cpp
int main()
{
    Aws::SDKOptions options;
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;
    Aws::InitAPI(options);
    {
        Aws::Client::ClientConfiguration clientConfig("default");
        Aws::S3::S3Client clS3Client( clientConfig );
        Aws::S3::Model::HeadBucketRequest headReq;
        headReq.WithBucket("bucket-name");
        auto outcome = clS3Client.HeadBucket(headReq);
        if (!outcome.IsSuccess()) {
            auto error = outcome.GetError();
            Aws::String errorMessage = "Error: " + error.GetExceptionName() + " - " + error.GetMessage();
            std::cout << errorMessage;
        }else{
            std::cout << "success" << std::endl;
        }
    }
    Aws::ShutdownAPI(options);
}
```
Let me know if this helps or if you have other questions about this.

**Comment by ProgrammerZhujinming** [comment]
Thanks for your reply.
I tried this way, but I found that the method always return true no matter whether the bucket exists. At the beginning, I though that it means the request is success rather than the response is 200 ok. By the way, the version of aws-sdk-cpp I am using is 1.0.164. I just want to find a method to replace the way that list buckets and  compare the result becauese I just want to know if the bucket which I need exists. It maybe not a good idea that i store the list now in my program structure. Please help me confirm where the question comes from and I will be very appreciated.

**Comment by KaibaLopez** [comment]
@ProgrammerZhujinming ,
The version you say you're using is VERY old, so I can't really test this out, for the newer versions I tested my code and it does return false if the bucket doesn't exist which is expected behavior, real solution is to update the SDK.
If this is not working for you and you can't udpate the SDK, any other solution is going to be kind of "hacky", like with Listbuckets.

**Comment by ProgrammerZhujinming** [comment]
Well...I got it. Thanks for your reply.

**Comment by HeenaBansal2009** [comment]
@KaibaLopez , The sample code above is very useful. 
I have a quick question:
- I am checking exists() function as like this : DO you think it  has room for improvement in terms of performance ,
```
bool S3ObjectStorage::exists(const StoredObject & object) const
auto client_ptr = client.get();
    client_ptr->HeadBucket()
    Aws::S3::Model::HeadObjectRequest request;
    request.SetBucket(bucket_from);
    request.SetKey(key);
   auto object_head =  client_ptr->HeadObject(request);

bool S3ObjectStorage::exists(const StoredObject & object) const{
if (!object_head.IsSuccess())
    {
        if (object_head.GetError().GetErrorType() == Aws::S3::S3Errors::RESOURCE_NOT_FOUND)
            return false;

        throwIfError(object_head);
    }
    return true;

}
```
And ,  how I can  find the lastrevision to restore metadata.
    currently doing something like this :
    
/// Construct revision number from high to low bits.
```
    String revision;
    revision.reserve(64);
    const auto & object_storage = disk->object_storage;
    for (int bit = 0; bit < 64; ++bit)
    {
        auto revision_prefix = revision + "1";

        LOG_TRACE(disk->log, "Check object exists with revision prefix {}", revision_prefix);
        StoredObject revision_object{disk->object_storage_root_path + "r" + revision_prefix};
        StoredObject revision_operation_object{disk->object_storage_root_path + "operations/r" + revision_prefix};
       
            /// Check file or operation with such revision prefix exists.
        if (object_storage->exists(revision_object) || object_storage->exists(revision_operation_object))
            revision += "1";
        else
            revision += "0";
    }
    revision_counter = static_cast<UInt64>(std::bitset<64>(revision).to_ullong());
    LOG_INFO(disk->log, "Found last revision number {} for disk {}", revision_counter, disk->name);
}


```
- Do we have any API available to find the lastRevision and can avoid above calculations.
- Do you think , checking if versioning is enabled/suspended/not set should be done before calculating lastRevision. If version is NULL , It is not needed to calculate. the last revision to restoreMetadata ? Please correct me If ia m wrong.

I will really appreciate your response on this,
