### ISSUE TITLE
Compilation warning message in aws-crt-cpp

### ISSUE THREAD

**Issue by jerrytfleung** [aws/aws-sdk-cpp#1646]
**Describe the bug**
A compilation warning message is popped up during building aws-crt-cpp with -Wextra and -Werror compiler options.
```
[  5%] Building C object aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/encoding.c.o
/Users/runner/work/timestream-odbc/timestream-odbc/src/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/encoding.c:364:20: error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
       if (result == -1) {
           ~~~~~~ ^  ~~
1 error generated.
```

**SDK version number**
1.9.19

**Platform/OS/Hardware/Device**
macOS Mojave

**To Reproduce (observed behavior)**
1. Add the following line in your cmake project using aws-sdk-cpp 1.9.19
```
add_compile_options(-Wall -Wextra -pedantic -Werror)
```
2. Build the project and look for the warning message

**Expected behavior**
aws-crt-cpp should be able to build without errors and warnings.

**Comment by KaibaLopez** [comment]
Hi @jerrytfleung ,
Thanks for bringing this up to us, we'll take a look, it should be a fairly simple fix. 
I think it's worth mentioning that most compilers will figure it out and behave the expected way though. this is not to say that the warning is invalid, just that you can safely build without worries while we change it.

**Comment by KaibaLopez** [comment]
Hi @jerrytfleung , 
Kind of revisiting this and upon closer inspection, while we could change that one comparison, and it kind of makes sense to do so if only for readability , I don't think we can commit to having the compilation pass the `-pedantic` flag. It would be a much bigger endeavor and we simply don't have the bandwidth for it. 
I've already created the PR on aws-crt-cpp  for the type comparison change, but I think I'll close this issue as I don't think we can get the whole FR in so I don't think it makes sense to keep it, If you disagree though, feel free to add a comment to keep it open to keep track of when the pr is merged.

**Comment by jerrytfleung** [comment]
Understand. It is okay to me.
