### ISSUE TITLE
Aws::S3::Model::Object::GetLastModified( ) returns only the year.

### ISSUE THREAD

**Issue by Jinex2012** [aws/aws-sdk-cpp#165]
GetLastModified only returns the year.

`QStringList APIManager::listFolderItems(QString serverFolder)
{

    Aws::S3::Model::ListObjectsRequest listObjectsRequest;
    listObjectsRequest.SetBucket(this->bucket);
    listObjectsRequest.WithPrefix(serverFolder.toStdString());
    listObjectsRequest.SetDelimiter("/");
    QStringList items;
    auto listObjectsOutcome = this->s3Client->ListObjects(listObjectsRequest);
    if(listObjectsOutcome.IsSuccess())
    {
        auto res = listObjectsOutcome.GetResult();
        auto files = res.GetContents();
        for(unsigned int i=0; i<files.size(); i++)
        {
            Aws::S3::Model::Object o = files.at(i);
            std::cout<<o.GetLastModified(); //returns only year here
            items<< QString::fromStdString(o.GetKey()).replace(serverFolder,"");

        }

        auto prefix = res.GetCommonPrefixes();
        for(unsigned int i=0; i<prefix.size(); i++)
        {
            Aws::S3::Model::CommonPrefix p = prefix.at(i);
            items<< QString::fromStdString(p.GetPrefix()).replace(serverFolder,"");
        }

    }
    else
    {
        this->errorManager("listFolderItems", listObjectsOutcome.GetError().GetMessage());
    }

    return items;

}
`

**Comment by Bu11etmagnet** [comment]
I doubt it returns only the year. Trying to compile your code results in:
```
error: invalid operands to binary expression ('ostream' (aka 'basic_ostream<char>') and 'const Aws::Utils::DateTime')
```

**Comment by JonathanHenson** [comment]
What revision of the SDK are you using? We reworked all of the timestamp stuff a couple of weeks ago. Have you tried the latest revision?

**Comment by Jinex2012** [comment]
Ah, OK. I downloaded the SDK 3 weeks ago. I will try the latest version.

**Comment by Jinex2012** [comment]
OK. Its working on the latest version.
