### ISSUE TITLE
Build error after upgrading to version 1.9

### ISSUE THREAD

**Issue by davehorton** [aws/aws-sdk-cpp#1650]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I have been building a shared library that uses the sdk for transcribestreaming and lexv2-runtime.  Before upgrading to 1.9, I was including all of the aws-c-* libs in my link step, i.e.
```
-laws-cpp-sdk-transcribestreaming -laws-cpp-sdk-core -laws-c-event-stream -laws-checksums -laws-c-common -lpthread -lcurl -lcrypto -lssl -lz
```
and this all worked fine.

Now, I have upgraded to version 1.9.  I followed the instructions to `git update submodules --init --recursive` to get the new crt lbraries, etc and successfully built the sdk (tests at the end of the build step pass).

I changed my link command to this:

```
-laws-cpp-sdk-transcribestreaming -laws-cpp-sdk-core -laws-crt-cpp -lpthread -lcurl -lcrypto -lssl -lz
```
as it was my understanding from the docs that libaws-crt-cpp encompasses the other libs

My problem is that when I try to load my shared library I get an undefined symbol error
```
2021-05-19 18:40:40.934882 [CRIT] switch_loadable_module.c:1785 Error Loading module /usr/local/freeswitch/mod/mod_aws_transcribe.so
**/usr/local/freeswitch/mod/mod_aws_transcribe.so: undefined symbol: aws_tls_ctx_release**
```

Any idea what I am doing wrong?  Are there additional libraries I should link with? Any insight will be much appreciated

Here, by the way, is my cmake command to build the sdk
```
cmake .. -DBUILD_ONLY="lexv2-runtime;transcribestreaming" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS="-Wno-unused-parameter"
```

**SDK version number**
1.9
**Platform/OS/Hardware/Device**
Debian 10

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

**Expected behavior**
My shared library would load successfully and be able to use the sdk apis

**Logs/output**
If applicable, add logs or error output.

**Additional context**

**Comment by davehorton** [comment]
Closing this, as I was able to build after adding all the libraries.  (However, my process now crashes while handling a transcribe request - may open a separate issue on that).

For posterity, I had to fiddle with the link order a bit, this is what worked
```
-laws-cpp-sdk-transcribestreaming -laws-cpp-sdk-core -laws-crt-cpp \
-laws-c-s3 -laws-c-http -laws-c-auth \
-laws-c-mqtt -ls2n -laws-c-compression -laws-c-io -laws-c-cal -laws-c-event-stream \
-laws-checksums -laws-c-common  \
-lpthread -lcurl -lcrypto -lssl -lz
```

**Comment by wangjunxiao0207** [comment]
I have also experienced this problem， but in S3 function。This is my link lib order
```
 -laws-cpp-sdk-s3 -laws-cpp-sdk-core -laws-crt-cpp -laws-c-s3 -laws-c-http \
-laws-c-auth -laws-c-mqtt -laws-c-compression -laws-c-io -ls2n -laws-c-cal \
-laws-c-event-stream -laws-checksums -laws-c-common  -lpthread -lcurl \
-lcrypto -lssl -lz -ldl
```
