### ISSUE TITLE
Silently connecting to metadata service in constructor is dangerous behavior

### ISSUE THREAD

**Issue by jvictor0** [aws/aws-sdk-cpp#1653]
I noticed in 147469373c9fec1037bd2d75d7cd949250c6f7c5, it introduced a behavior where, if the region was not specified, it tried to infer it from the EC2 metadata service.  I think this is dangerous behavior because
1) A user not using S3 probably doesn't care about this field.  A user who additionally isn't using EC2 will incur a several second wait (as this person did https://stackoverflow.com/questions/63725308/awss3s3client-constructor-very-slow).
2) More importantly, if you are using EC2 but not US-EAST-1 and relying on this, and for some reason one day it fails to connect to the metadata service during the constructor, you have accidentally created a cross-region S3Client without knowing about it.  Since cross region traffic is billed by the byte, this could be a very expensive mistake!  

Its easy to work around this by just setting the region explicitly, but it isn't clear that this is a requirement from anything I've seen.

Thanks!

**Comment by KaibaLopez** [comment]
Hi @jvictor0 ,
Yea this is a good point, but it's kind of "known" thing/topic(?) 
This was a conscious decision, and that is not to say your points are not valid... but yea let me kind of justify why that's there.

So the first thing to note is that this is meant to only be "default" behavior, the option is there in case you want to avoid it, I wouldn't even say it's a workaround, it is expected that you are able to customize this in whatever way you prefer, so you can explicitly tell the SDK where to look, or have a custom chain of places to look for that don't include the EC2 metadata... But yea it's not a requirement, it's an option.

The idea was to have the sdk run with as little configuration necessary, so we made the default credentials provider chain check for region in all the expected places.
Dunno if this makes sense but let me know what you think.
