### ISSUE TITLE
c++ dynamodb <UpdateItemRequest.h> compile error

### ISSUE THREAD

**Issue by zhangli-jerry** [aws/aws-sdk-cpp#1656]
When include the <UpdateItemRequest.h> , compile error occurred.

#include <aws/dynamodb/model/UpdateItemRequest.h>    

I think maybe the problem is <aws/dynamodb/model/ComparisonOperator.h> Line21.

change  IN to IN_ can fix the error.

Verson: 1.9
OS: windows

**Comment by KaibaLopez** [comment]
Hi @zhangli-jerry ,
Can you provide the error you are getting and how you are trying to compile this? (the CMakeLists.txt and cmake arguments). 
But yea we are having various issues on windows, and are investigating the case. Thanks for pointing this and a workaround. I'll update once we have a better solution for this.

**Comment by zhangli-jerry** [comment]
[CMakeLists.txt](https://github.com/aws/aws-sdk-cpp/files/6535974/CMakeLists.txt)
[cmake_error.log](https://github.com/aws/aws-sdk-cpp/files/6535985/cmake_error.log)

I build on Windows10 with 
[cmake version 3.18.4]
[Visual Studio 2019 Professional Release - x86_amd64]

**Comment by KaibaLopez** [comment]
alright, thanks @zhangli-jerry ,
I've added this bug to our queue and will take a look at it as soon as possible. On the mean time though it sounds like you have yourself a fix/workaround.

**Comment by wps132230** [comment]
Hi there,
We had a fix for this issue with commit: https://github.com/aws/aws-sdk-cpp/commit/a835ea4e96cbee2d17a9033c7b24b353a3a58bb2
Could you take a look if it works for you?
