### ISSUE TITLE
Aws::DynamoDB::PutItem() calls take around 30ms

### ISSUE THREAD

**Issue by NatxoM** [aws/aws-sdk-cpp#1657]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Aws::DynamoDB::PutItem() calls take around 30ms

**SDK version number**
1.9

**Platform/OS/Hardware/Device**
Ubuntu:18.04 on Docker

**To Reproduce (observed behavior)**

```
Aws::Client::ClientConfiguration client_conf;
client_conf.region = Aws::Environment::GetEnv("AWS_REGION");
client_conf.caFile = "/etc/pki/tls/certs/ca-bundle.crt";
Aws::DynamoDB::DynamoDBClient dynamo_client(client_conf);
Aws::DynamoDB::Model::PutItemRequest request;
request.SetTableName(...);
request.SetItem(...);
auto db_outcome =  dynamo_client.PutItem(request); // This line takes around 30ms with small items

```

**Expected behavior**
PutItem is supposed to take <10ms

I create a new client with each PutItem call. Is this the reason of the latency?

**Comment by KaibaLopez** [comment]
Hi @NatxoM ,
So first to answer, your question _I create a new client with each PutItem call. Is this the reason of the latency?_ maybe? It depends on how you are taking the times, as in do you include the whole process in the 30ms or is it just the putItem call?
The sample isn't very clear on this so let me ask a few questions.
* How are you measuring this times? Can you show me the full sample with these lines?  
* Why 10 ms? Not saying you are wrong but I can't find documentation that specifies a time range, can you point me to some or was this an estimate on how long the operation takes on CLI or the web client? 
* Are you sure this isn't related to you network connection? 
* Is the 30ms constant? or does it vary if you run the command say 10 times?

**Comment by NatxoM** [comment]
Yes, the problem was that I was creating a new client with each *PutItem* call. With a *static* client, the latency is *single-digit millisecond*, as Amazon promises.
