### ISSUE TITLE
Segfault when destructing CloudwatchClient

### ISSUE THREAD

**Issue by harry-unlikelyai** [aws/aws-sdk-cpp#1660]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I have been following the example set up and have code like:

	Aws::SDKOptions options;
	options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;
	// options.cryptoOptions.initAndCleanupOpenSSL = false;
	Aws::InitAPI(options);
	Aws::Client::ClientConfiguration clientConfig;

	Aws::CloudWatch::CloudWatchClient cw(clientConfig);
	Aws::CloudWatch::Model::Dimension dimension;
	dimension.SetName("UNIQUE_PAGES");
	dimension.SetValue("URLS");

	Aws::CloudWatch::Model::MetricDatum datum;
	datum.SetMetricName("PAGES_VISITED");
	datum.SetUnit(Aws::CloudWatch::Model::StandardUnit::None);
	datum.SetValue(100);
	datum.AddDimensions(dimension);

	Aws::CloudWatch::Model::PutMetricDataRequest request;
	request.SetNamespace("SITE/TRAFFIC");
	request.AddMetricData(datum);

	auto outcome = cw.PutMetricData(request);
	if (!outcome.IsSuccess())
	{
		std::cout << "Failed to put sample metric data:" <<
			outcome.GetError().GetMessage() << std::endl;
	}
	else
	{
		std::cout << "Successfully put sample metric data" << std::endl;
	}

	Aws::ShutdownAPI(options);
	return false;

And this code segfaults after the `Aws::ShutdownAPI` call. In GDB I get an error like:

    Thread 1 "cm" received signal SIGSEGV, Segmentation fault.
    0x00007ffff75b0e0f in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1

And using a few breakpoints I tracked down this issue:

    Thread 1 "cm" hit Breakpoint 1, 0x00007ffff6e71f30 in Aws::Client::AWSClient::~AWSClient() () from /usr/local/lib/libaws-cpp- 
    sdk-monitoring.so
    (gdb) c
    Continuing.
    
    Thread 1 "cm" hit Breakpoint 3, 0x00007ffff6b17bd0 in Aws::Internal::AWSHttpResourceClient::~AWSHttpResourceClient() () 
    from /usr/local/lib/libaws-cpp-sdk-core.so
    (gdb) c
    Continuing.
    
    Thread 1 "cm" hit Breakpoint 2, 0x00007ffff6b55fd0 in Aws::Http::CurlHttpClient::~CurlHttpClient() () from /usr/local/lib/libaws- 
    cpp-sdk-core.so
    (gdb) c
    Continuing.
    
    Thread 1 "cm" hit Breakpoint 2, 0x00007ffff6b55fd0 in Aws::Http::CurlHttpClient::~CurlHttpClient() () from /usr/local/lib/libaws- 
    cpp-sdk-core.so
    (gdb) c
    Continuing.
    
    Thread 1 "cm" received signal SIGSEGV, Segmentation fault.
    0x00007ffff75b0e0f in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1

So it seems like the CurlHttpClient destructor gets run twice for the same memory location and then it segfaults right afterwards. I'm not exactly sure how SSL plays into this as well but it seems like SSL can be problematic in multithreaded environments sometimes. The interesting thing is that the rest of the code works well and I can see the metrics reaching my Cloudwatch console.

**SDK version number**
1.9.29

**Platform/OS/Hardware/Device**
What are you running the sdk on?

Windows 10 WSL/Ubuntu 18.04

@PaulBenn-UnlikelyAI

**Comment by KaibaLopez** [comment]
Hi @harry-unlikelyai ,
Hmmm alright, thanks for pointing this out to us. We'll take a closer look, but just out of curiosity, the way you said "this sample" makes me think you got it from somewhere in our docs, was that the case? If so, could you point me to it?

**Comment by harry-unlikelyai** [comment]
Thanks for the response, yes the code is pretty much the same as https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/examples-cloudwatch-publish-custom-metrics.html and https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/cpp/example_code/cloudwatch/put_metric_data.cpp

**Comment by harry-unlikelyai** [comment]
This segfault still occurs when my full program is just

`bool send_metric_data() {
	Aws::SDKOptions options;
	options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;
	Aws::InitAPI(options);
	Aws::Client::ClientConfiguration clientConfig;
	clientConfig.region = "eu-west-2";

	Aws::CloudWatch::CloudWatchClient cw(clientConfig);
	Aws::CloudWatch::Model::Dimension dimension;
	dimension.SetName("UNIQUE_PAGES");
	dimension.SetValue("URLS");

	Aws::CloudWatch::Model::MetricDatum datum;
	datum.SetMetricName("PAGES_VISITED");
	datum.SetUnit(Aws::CloudWatch::Model::StandardUnit::None);
	datum.SetValue(100);
	datum.AddDimensions(dimension);

	Aws::CloudWatch::Model::PutMetricDataRequest request;
	request.SetNamespace("SITE/TRAFFIC");
	request.AddMetricData(datum);

	auto outcome = cw.PutMetricData(request);
	if (!outcome.IsSuccess())
	{
		std::cout << "Failed to put sample metric data:" <<
			outcome.GetError().GetMessage() << std::endl;
	}
	else
	{
		std::cout << "Successfully put sample metric data" << std::endl;
	}

	Aws::ShutdownAPI(options);
	return false;
}

int main()
{
	return send_metric_data();
}`

so I don't think it is to do with multithreading issues. I built the latest version of the SDK at the time from source in the way the documentation says to, I will try again now with the latest version.

**Comment by KaibaLopez** [comment]
yea that works I guess.

**Comment by KaibaLopez** [comment]
So, what's going on in that sample is that the scope is not properly defined.
To be explicit on the scope add brackets to the init and shutdown like this:
```cpp
bool send_metric_data() {
  Aws::SDKOptions options;
  options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;
  Aws::InitAPI(options); {                       //add the '{' to define scope
  //rest of the code
  }Aws::ShutdownAPI(options);             //close the scope
  return false;
}
```
That should get rid of the segfault.

**Comment by harry-unlikelyai** [comment]
Unfortunately not, this way just segfaults at the end of the scope. Again it seems like its an issue with the destructor of the client.

**Comment by KaibaLopez** [comment]
@harry-unlikelyai ,
I'm going to need a new way to reproduce then, when I run the sample with the block scope the segfault doesn't happen. 
And yes it is probably related to some destructor being called at inappropiate times, but that's what shutdownAPI is supposed to handle, so these are not unrelated.

Now, just to test this since it seems like you are seeing different things than I am, do you still see the segfault if you move the init here?
```cpp
int main()
{
   Aws::InitAPI(options); { 
   return send_metric_data();
   }Aws::ShutdownAPI(options);
}
```

**Comment by harry-unlikelyai** [comment]
The example you've given there would never get to the ShutdownAPI call right? I tried it and it still segfaults unfortunately. With the scope added it segfaults on exiting scope so that happens before ShutdownAPI is ever called.

**Comment by KaibaLopez** [comment]
ah bad copy paste, my bad :
```cpp
int main()
{
   Aws::InitAPI(options); { 
   send_metric_data();
   }Aws::ShutdownAPI(options);
   return 0;
}

**Comment by harry-unlikelyai** [comment]
Interestingly, when I try that I get a slightly different issue. I (sometimes) get:

    *** stack smashing detected ***: <unknown> terminated
    Aborted

And other times just a standard segfault. Does this give any more indication of the issue?

**Comment by KaibaLopez** [comment]
Hmmm... not really now I'm more confused, I was trying to make sure we would see the same things so I can get a starting point, but until I can reproduce the error there isn't much I can do to help and the only thing I was able to reproduce was the segfault that happened when the InitAPI->ShutdownAPI block scope was not explicitly defined in the previous sample you provided, but that didn't seem to be the case for you so...
The last thing I can think of is a bit of a shot in the dark... there is a similar issue opened that might be related, could I ask that you try:
```cpp
#include <aws/testing/platform/PlatformTesting.h>

int main()
{
   Aws::InitAPI(options); { 
   Aws::Environment::SetEnv("AWS_EC2_METADATA_DISABLED", "true", 1);
   Aws::Client::ClientConfiguration clientConfig;
   clientConfig.region = "eu-west-2";

   Aws::CloudWatch::CloudWatchClient cw(clientConfig);
   }Aws::ShutdownAPI(options);
   return 0;
}
```
See if adding the env variable does anything for you?

Otherwise I'm going to need to know things like, the gcc/g++ version you're using, are you building the SDK as a static or shared library, did you update to the latest SDK? (There was a change on the default ssl implementation sometime around 1.9.3X that might be related). Any other info about your environment that you may think is related like having a version of openssl other than 1.1.1 or something like that?

**Comment by harry-unlikelyai** [comment]
Updating the sdk to latest master has now fixed this, thank you. Although this was very painful it does seem to work now.
