### ISSUE TITLE
TransferManager relies on non-standardised behavior

### ISSUE THREAD

**Issue by ivanov-wai** [aws/aws-sdk-cpp#1661]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**

When `TransferManager` writes to download stream, it seeks past the end of the stream. [link](https://github.com/aws/aws-sdk-cpp/blob/1.8.166/aws-cpp-sdk-transfer/source/transfer/TransferHandle.cpp#L373-L376)

In POSIX `fseek` will increase the file size and fill the file with zeros up to the requested point if the file is opened in write mode. However, this behaviour is not standardised in C++ for streams. If a different stream implementation is used (e.g. `std::stringstream`), this may result in chunks missing from the download stream with no warnings or errors from `TransferManager`,

**SDK version number**

1.8.186

**Platform/OS/Hardware/Device**

AWS Lambda AL2

**To Reproduce (observed behavior)**

```c++
void testDownload(const char *bucket, const char *key,
                  Aws::Transfer::TransferManager *transferManager) {
  std::stringbuf data;
  auto transferHandle = transferManager->DownloadFile(bucket, key, [&data] {
    return Aws::New<Aws::IOStream>("stream", &data);
  });
  transferHandle->WaitUntilFinished();
  assert(!transferHandle->HasFailedParts());
  assert(transferHandle->GetBytesTransferred() ==
         transferHandle->GetBytesTotalSize());
  assert(data.str().size() == transferHandle->GetBytesTransferred());
}
```

**Expected behavior**

Final stream size should match file size

**Logs/output**

n/a

**Additional context**

n/a

**Comment by KaibaLopez** [comment]
Hi @ivanov-wai ,
Thanks for pointing this out, we are investigating this issue.
