### ISSUE TITLE
Make Aws::Client::AWSClient::MakeHttpRequest public

### ISSUE THREAD

**Issue by malaterre** [aws/aws-sdk-cpp#1663]
**Is your feature request related to a problem? Please describe.**

In the context of s3 object lambda, typical c++ code initialize an s3client, for example:

```
    Client::ClientConfiguration config;
    config.region = Aws::Environment::GetEnv("AWS_REGION");
    config.caFile = "/etc/pki/tls/certs/ca-bundle.crt";

    auto credentialsProvider =
        Aws::MakeShared<Aws::Auth::EnvironmentAWSCredentialsProvider>(TAG);
    S3::S3Client client(credentialsProvider, config);
```

In typical scenario, the first thing developer wants to do is retrieve an s3 object:

```
  std::shared_ptr<Aws::Http::HttpRequest> getRequest =
      CreateHttpRequest(s3url, Http::HttpMethod::HTTP_GET,
                        Aws::Utils::Stream::DefaultResponseStreamFactoryMethod);
  std::shared_ptr<Aws::Http::HttpClient> httpClient =
      Aws::Http::CreateHttpClient(Aws::Client::ClientConfiguration());
  std::shared_ptr<Aws::Http::HttpResponse> getResponse =
      httpClient->MakeRequest(getRequest);
```

**Describe the solution you'd like**

It does not make much sense to create a new `Aws::Http::HttpClient`, since internally `S3::S3Client` already has one. All it would take is to expose the protected function `Aws::Client::AWSClient::MakeHttpRequest`:

* https://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_client_1_1_a_w_s_client.html#ae689edfcb3006b2796d13a520ac58a54

**Describe alternatives you've considered**

As stated above, dev can simply create an httpClient to execte the GET request. This is a feature request to simplify dev work.

**Comment by KaibaLopez** [comment]
Hi @malaterre ,
Hmmm... I mean, the thing here is that the HttpClient is a base class, it is not meant to be used this way....
I am probably missing something in your use case or misunderstanding it but... if you are trying to for example, do s3's getObject then you'd do something like:
```cpp
        Client::ClientConfiguration config;
        config.region = Aws::Environment::GetEnv("AWS_REGION");
        config.caFile = "/etc/pki/tls/certs/ca-bundle.crt";

        auto credentialsProvider =
        Aws::MakeShared<Aws::Auth::EnvironmentAWSCredentialsProvider>(TAG);
        S3::S3Client client(credentialsProvider, config);

        Aws::S3::Model::GetObjectRequest request;
        request.WithBucket("name").WithKey("key");

        auto result = s3Client.GetObject(request);
```
So yea, to me it doesn't make sense that you've created the s3client but then not use it to make the request? Can you clarify why do you want to use the base HttpClient instead of the specialized s3Client for your requests?

**Comment by malaterre** [comment]
@KaibaLopez Thanks much for your time and response. 

One thing that is not clear to me: my use case is within the scope of "s3 object lambda". So my code is rather:

```
  S3::Model::WriteGetObjectResponseRequest request;
  request.WithRequestRoute(route);
  request.WithRequestToken(token);
  request.SetBody(objectStream);
  auto outcome = client.WriteGetObjectResponse(request);
```

In the above code `objectStream` is derived from:

`const Aws::IOStream& responseBody = getResponse->GetResponseBody();`

The input json payload I receive in my s3 object lambda is as follow:

```
{
  "xAmzRequestId": "1a5ed718-5f53-471d-b6fe-5cf62d88d02a",
  "getObjectContext": {
      "inputS3Url": "https://transform-424432388155.s3-accesspoint.us-east-1.amazonaws.com/title.txt?X-Amz-Security-Token=...",
      "outputRoute": "io-iad-cell001",
      "outputToken": "..."
  },
```

ref:

* https://antonputra.com/introduction-to-amazon-s3-object-lambda/

**Comment by malaterre** [comment]
One more comment, even the official documentation for the python binding makes use of an external library to execute the GET.

See:

* https://docs.aws.amazon.com/AmazonS3/latest/userguide/olap-writing-lambda.html#olap-getobject-response

Scroll to "Example 2:", then search for line:

`    image_request = requests.get(s3_url)`

where requests is a third party lib:

`import requests `
