### ISSUE TITLE
WriteGetObjectResponseRequest: Content-Type

### ISSUE THREAD

**Issue by malaterre** [aws/aws-sdk-cpp#1665]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**

I'd like to be able to set the "Content-Type" on `WriteGetObjectResponseRequest`, as specified in the documentation:

* https://docs.aws.amazon.com/AmazonS3/latest/API/API_WriteGetObjectResponse.html

Scroll to:

`x-amz-fwd-header-Content-Type: ContentType`

**SDK version number**

git/master

**Platform/OS/Hardware/Device**

Linux

**To Reproduce (observed behavior)**

Code does not set content-type at all:

* https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-s3/source/model/WriteGetObjectResponseRequest.cpp#L176-L188

**Expected behavior**

I'd like to set the content-type to be something other than just "text/plain"

**Comment by malaterre** [comment]
I should also mentionned that the function `SetContentType `does not change the `content-type` of the output:

`void Aws::AmazonStreamingWebServiceRequest::SetContentType	(	const Aws::String & 	contentType	)	
`

ref:

* http://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_amazon_streaming_web_service_request.html#ab3c257c251ecd26b096a0c3be7dfd69f

**Comment by KaibaLopez** [comment]
Hi @malaterre ,
Sorry for the response delay, I'm still trying to reproduce this but looking at the code it seems you are right, thanks for pointing it out to us.
