### ISSUE TITLE
Where can I clone awsdoc/s3 respository from?

### ISSUE THREAD

**Issue by Baharak12** [aws/aws-sdk-cpp#1666]
Hi there, 
Does anyone know where I can clone the AWSdoc/S3 repository?
To access the following header file, I need access to this repository.
#include <awsdoc/s3/s3_examples.h
Thanks

**Comment by KaibaLopez** [comment]
@Baharak12 ,
I think you are looking for [this](https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/cpp/example_code/s3/include/awsdoc/s3/s3_examples.h).

**Comment by Baharak12** [comment]
Thank you for your response. The cloning repo can be found here:
https://github.com/awsdocs/aws-doc-sdk-examples
