### ISSUE TITLE
AWS C++ SDK conflict with OpenSLL 1.1.1d on Ubuntu.

### ISSUE THREAD

**Issue by stephb9959** [aws/aws-sdk-cpp#1669]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Building SDK on Ubuntu 20 and using as part of an app that uses OpenSSL does not work.

**SDK version number**
Latest main branch as of today.

**Platform/OS/Hardware/Device**
Debian Buster 10, patched, running on AWS. 

**To Reproduce (observed behavior)**
SDK builds without a problem and all tests (394) run. SDK is installed with sudo make install. SDK was built with the following

cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF -DENABLE_TESTING=ON -DCPP_STANDARD=14 -DTARGET_ARCH=LINUX -DBUILD_ONLY="s3" ..

(same problem with shared libs enabled.)

The SDK is being used in an app using the Poco C++ framework. 

Here is the main:
```
int main(int argc, char **argv) {

    Aws::SDKOptions AwsOptions;
    Aws::InitAPI(AwsOptions);

    int ExitCode=0;
    {
        auto App = uCentral::Daemon::instance();
        ExitCode = App->run(argc, argv);
    }

    ShutdownAPI(AwsOptions);
    return ExitCode;
}```

The app has always worked and several of these apps all follow the same pattern and are running. This app is the only one that uses the AWS SDK. There are no global variables. The code that uses the SDK is not using any memory management. Statically declared AWS Objects which are all scoped. 

The behavior is similar on Linux and OS X (aws-cpp-sdk installed with brew on OS X, although we would like to build from source)

- the app will crash at InitAPI(), crash on the first AWS call in the code, will crash on exit always. 
- we also noticed that after installing the SDK on Linux, /usr/local/include/openssl appears and populated with AWS's SSL files. These files conflict with the installed OpenSSL (the versions are not very close it seems) already in /usr/include/openssl.

**Expected behavior**
This may be a problem with building the SDK with the proper flags. Or there are no good examples on how to build an app that uses AWS SDK and also uses OpenSSL. We need to be able to use the SDK inside of the C++ project that uses OpenSLL for serving REST and some mTLS functions. 


**Logs/output**
Attached is a valgrind of one of the failures. They are all very similar. If we remove the AWS SDK and mock the calls, all works. 

[valgrind.ucentralfws.txt](https://github.com/aws/aws-sdk-cpp/files/6596452/valgrind.ucentralfws.txt)

To enable logging, set the following system properties:
The app does not run enough to produce logs. 

**Additional context**
I did notice that at some point, there was a PR to change the included AWS SSL for a 1.1.1.1 version. I no longer see that PR so I do not know if it was merged or deleted.  This has been a very frustrating journey. 

Thanks for looking at this.

**Comment by KaibaLopez** [comment]
Hi @stephb9959 ,
Yea this is a problem with the newest version of the SDK and we are working on it, thanks for bringing it up to us, we should have a fix soon.

**Comment by KaibaLopez** [comment]
By the way, as a workaround, I woudl suggest using an older version (yesterday's should work) and specifying an install location, that way it should not overwrite them.

**Comment by wps132230** [comment]
We are fixing this issue to prevent it populating system openssl.
And another workaround is to turn on `USE_OPENSSL` in CMake command. Then it will not install `libcrypto`, `libssl` for you.

**Comment by stephb9959** [comment]
@wps132230 Thanks!

Can someone update the CMAKE variables document to include the USE_OPENSSL? 

I am very happy to hear this. So we can close this as far as I am concerned. 

Thanks again.

**Comment by wps132230** [comment]
Added CMake variables document: https://github.com/aws/aws-sdk-cpp/blob/main/Docs/CMake_Parameters.md#use_openssl
Please reopen this issue or create another one if you have more concerns.
