### ISSUE TITLE
S3-CRT not working with the AWS Lambda C++ Runtime

### ISSUE THREAD

**Issue by NatxoM** [aws/aws-sdk-cpp#1672]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I use AWS SDK C++ with the AWS Lambda C++ Runtime. Aws:S3 works without problems, but Aws:S3Crt doesn't work.

**SDK version number**
v1.9.34

**Platform/OS/Hardware/Device**
Ubuntu 18.04, AWS Lambda C++ Runtime 0.2.7

**To Reproduce (observed behavior)**
S3 works without problems:

```
Aws::Client::ClientConfiguration config;
config.region = Aws::Environment::GetEnv("AWS_REGION");
config.caFile = "/etc/pki/tls/certs/ca-bundle.crt";
Aws::S3::S3Client s3_client(config);
Aws::S3::Model::GetObjectRequest object_request;
object_request.WithBucket(bucket.c_str()).WithKey(key.c_str());
auto get_object_outcome = s3_client.GetObject(object_request);

```
S3-CRT doesn't work:

```
Aws::S3Crt::ClientConfiguration config;
config.region = Aws::Environment::GetEnv("AWS_REGION");
Aws::S3Crt::S3CrtClient s3_client(config);
Aws::S3Crt::Model::GetObjectRequest object_request;
object_request.WithBucket(bucket.c_str()).WithKey(key.c_str());
auto get_object_outcome = s3_client.GetObject(object_request); // Fails here
```

**Logs/output**
The error I get with S3-CRT:

    Error: Runtime exited with error: signal: segmentation fault (core dumped)

**Comment by NatxoM** [comment]
With branch 1.9.69 it works. However, it fails if I select Aws::Region::AWS_GLOBAL.

**Comment by KaibaLopez** [comment]
Hi @NatxoM ,
Sorry for the lack of response here but what kind of error do you get? and what endpoint are you hitting ? 
Also, if this is the new error you should be able to get logs right? Could you provide those as well?
