### ISSUE TITLE
Cannot compile dynamo Comparison Operator on Windows

### ISSUE THREAD

**Issue by gjasny** [aws/aws-sdk-cpp#1674]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**

The `IN` value in this enum:

https://github.com/aws/aws-sdk-cpp/blob/065ebee98ad5bd6bba49749368adc5fb27b6d5d7/aws-cpp-sdk-dynamodb/include/aws/dynamodb/model/ComparisonOperator.h#L21

clashes with a define that originates from `windows.h` / `minwindef.h` (from `aws/io/event_loop.h`):

```c++
#ifndef IN
#define IN
#endif
```

This leads to the following error:
```
1>D:\Foo\include\aws/dynamodb/model/ComparisonOperator.h(21,7): error C2143: syntax error: missing '}' before ','
1>D:\Foo\include\aws/dynamodb/model/ComparisonOperator.h(21,7): error C2059: syntax error: ','
```

**SDK Version**

`1.9.35`

**Platform/OS/Hardware/Device**
Windows, Visual Studio 2019 / 16.10.0

**Comment**

Maybe you could handle the `IN` value as a special one like the `NULL_` value some lines below.

Thanks,
Gregor

**Comment by KaibaLopez** [comment]
Hi @gjasny ,
Yea this has already been reported, look [here](https://github.com/aws/aws-sdk-cpp/issues/1656).
The easiest workaround for this error is to just change `IN` to `IN_`.
I'll close this one as it is already being tracked, but yea we are working on this.
