### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by disa6302** [aws/aws-sdk-cpp#1676]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on? MacOS Mojave

**Describe the question**

I am adding this SDK as an external project and using monitoring and logs. It was working fine in the past, but not sure why I get a linking error now. I am using v1.8.17. I checked previous issues, however, did not get a resolution.

**Logs/output**

```
Undefined symbols for architecture x86_64:
  "_curl_easy_cleanup", referenced from:
      Aws::Http::CurlHandleContainer::~CurlHandleContainer() in libaws-cpp-sdk-core.a(CurlHandleContainer.cpp.o)

     Aws::Http::CurlHandleContainer::DestroyCurlHandle(void*) in libaws-cpp-sdk-core.a(CurlHandleContainer.cpp.o)
  "_curl_easy_getinfo", referenced from:
      Aws::Http::CurlHttpClient::MakeRequest(std::__1::shared_ptr<Aws::Http::HttpRequest> const&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_easy_init", referenced from:
      Aws::Http::CurlHandleContainer::CheckAndGrowPool() in libaws-cpp-sdk-core.a(CurlHandleContainer.cpp.o)
  "_curl_easy_perform", referenced from:
      Aws::Http::CurlHttpClient::MakeRequest(std::__1::shared_ptr<Aws::Http::HttpRequest> const&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_easy_reset", referenced from:
      Aws::Http::CurlHandleContainer::ReleaseCurlHandle(void*) in libaws-cpp-sdk-core.a(CurlHandleContainer.cpp.o)
  "_curl_easy_setopt", referenced from:
      SetOptCodeForHttpMethod(void*, std::__1::shared_ptr<Aws::Http::HttpRequest> const&) in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
      Aws::Http::CurlHttpClient::MakeRequest(std::__1::shared_ptr<Aws::Http::HttpRequest> const&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
      Aws::Http::CurlHandleContainer::SetDefaultOptionsOnHandle(void*) in libaws-cpp-sdk-core.a(CurlHandleContainer.cpp.o)
  "_curl_easy_strerror", referenced from:
      Aws::Http::CurlHttpClient::MakeRequest(std::__1::shared_ptr<Aws::Http::HttpRequest> const&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_global_cleanup", referenced from:
      Aws::Http::CurlHttpClient::CleanupGlobalState() in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_global_init", referenced from:
      Aws::Http::CurlHttpClient::InitGlobalState() in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_slist_append", referenced from:
      Aws::Http::CurlHttpClient::MakeRequest(std::__1::shared_ptr<Aws::Http::HttpRequest> const&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_slist_free_all", referenced from:
      Aws::Http::CurlHttpClient::MakeRequest(std::__1::shared_ptr<Aws::Http::HttpRequest> const&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_version_info", referenced from:
      Aws::Http::CurlHttpClient::InitGlobalState() in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by disa6302** [comment]
This is my external project file:

```
cmake_minimum_required(VERSION 3.10.2)
project(libawscpp-download NONE)
include(ExternalProject)

ExternalProject_Add(libawscpp-download
    GIT_REPOSITORY    https://github.com/aws/aws-sdk-cpp.git
    GIT_TAG           1.8.17
    PREFIX            ${CMAKE_CURRENT_BINARY_DIR}/build
    LIST_SEPARATOR 	  "|"
    CMAKE_ARGS		-DCUSTOM_MEMORY_MANAGEMENT=OFF 
                    -DENABLE_TESTING=OFF 
                    -DAUTORUN_UNIT_TESTS=OFF 
                    -DBUILD_DEPS=ON 
                    -DBUILD_SHARED_LIBS=OFF 
                    -DBUILD_ONLY=monitoring|logs
                    -DCMAKE_INSTALL_PREFIX=${OPEN_SRC_INSTALL_PREFIX}
    BUILD_ALWAYS      0
    TEST_COMMAND      ""
)
```

**Comment by KaibaLopez** [comment]
@disa6302 ,
Hmmm... can't really reproduce the issue... Though it is hard to say if it is all being correctly linked seeing the CMakeLists separate like that...
couple things, first, make sure you've cleaned previous builds from DCMAKE_INSTALL_PREFIX location and try building the SDK manually and then doing the linking, just to make sure it's not the external project part that is failing.
Second, can you tell me more about the project? Specifically I'd like to know what the structure is like so I can try and reproduce this.

**Comment by disa6302** [comment]
@KaibaLopez , 

I removed the libraries from DCMAKE_INSTALL_PREFIX location and performed a clean build. This is my folder structure:


main-repo
      -> CMakeLists.txt
      -> CMake
            ->Dependencies
                 -> libcppsdk-CMakeLists.txt
                 
                 
To know more about the project, you can check [this](https://github.com/aws-samples/amazon-kinesis-video-streams-demos/tree/master/canary/producer-c) folder in the repo.

I can try building the SDK manually, but wondering how I can link it with the SDK built separately. This is a recent issue and I have not been seeing this in the past and nothing changed. So a little puzzled. 

Can you suggest a way for me to find how the libraries are linked?

**Comment by KaibaLopez** [comment]
Hi @disa6302 ,
so the my first thought would be that the libraries are not being found because they are not being properly built/installed, that's why I would suggest you build it manually first, in theory :
```
find_package(AWSSDK REQUIRED COMPONENTS monitoring logs)
target_link_libraries(lib ${AWSSDK_LINK_LIBRARIES} 
```
should be enough to link the SDK to your project if it has been built and installed.

**Comment by pr0g** [comment]
I stumbled across this issue and I believe it's related to https://github.com/aws/aws-sdk-cpp/issues/2717 (not being able to link Curl against aws-sdk-cpp). This simple change (https://github.com/aws/aws-sdk-cpp/pull/2718/commits/12b09058b251e1e528a98c2dd43d250f8165bebf) got it working for me, but it's just a quick fix and not integrated properly with all possible platforms/configurations. YMMV.
