### ISSUE TITLE
Cross-platform compilation with custom paths doesn't work for version 1.9.34

### ISSUE THREAD

**Issue by mbutkovski** [aws/aws-sdk-cpp#1677]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Host OS**
Ubuntu 20.04.2 LTS

**Target Platform**
aarch64

**Cross-compilation toolchain**
gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu

**SDK Version**
1.9.34

We are building AWS SDK with custom paths to openssl, zlib and curl.

This is the build script :

openssl_path="${build_path}/artifacts/openssl/${TARGET}"
curl_path="${build_path}/artifacts/curl/${TARGET}"
zlib_path="${build_path}/artifacts/zlib/${TARGET}"

${build_path}/artifacts/cmake/${TARGET}/cmake-3.18.2-Linux-x86_64/bin/cmake .. -DBUILD_ONLY="core;s3" -DCMAKE_BUILD_TYPE=Release \
 		-DCMAKE_LIBRARY_ARCHITECTURE="$HOST" \
		-DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
		-DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
		-DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
		-DCMAKE_C_COMPILER="${build_path}/artifacts/toolchain/${TARGET}/${TOOLCHAIN_BIN}/${CC}" \
		-DCMAKE_CXX_COMPILER="${build_path}/artifacts/toolchain/${TARGET}/${TOOLCHAIN_BIN}/${CXX}" \
		-DCMAKE_PREFIX_PATH="$openssl_path;$curl_path;$zlib_path" \
		-DCMAKE_INSTALL_PREFIX="$install_path;" \
		-DENABLE_TESTING=OFF

The artifacts are found in independent folder : '${build_path}/artifacts' (located with aws-sdk-cpp folders).
openssl_path is the path to a folder that has aarch64 lib, include, bin, ssl folders.
curl_path is the path to a folder with aarch64 lib, include, bin folders.
zlib is the path to a folder with aarch64 lib, include, bin folders.

The build script worked for 1.9.9 but stopped working for 1.9.34 , until probably the commit (?) 42b606e24283999cdc69037d73d777f213b3578b 01 Jun 2021 .

AWS cmake finds zlib lib and curl lib / dir , but openssl and crypto are not found:
-- Found ZLIB: /workdir/artifacts/zlib/nvtx2aarch64/lib/libz.so (found version "1.2.11") 
--   Zlib library: /workdir/artifacts/zlib/nvtx2aarch64/lib/libz.so
-- Encryption: Openssl
--   **Using libcrypto and libssl from AWS-LC.**
-- Http client: Curl
-- Found CURL: /workdir/artifacts/curl/nvtx2aarch64/lib/libcurl.so (found version "7.70.0")  
--   Curl include directory: /workdir/artifacts/curl/nvtx2aarch64/include
--   Curl library: /workdir/artifacts/curl/nvtx2aarch64/lib/libcurl.so

**How to tell to cmake to use custom path to openssl library ?** 
I tried different options:
1. export LDFLAGS="-L$openssl_path/lib/"
2. set install_path to the same folder where third party artifacts (openssl , curl, zlib) are found
3. copy all openssl libs into install path
Nothing helped - still cmake doesn't use custom path to openssl.

(The script does work for 1.9.34 amd64.)

I am not so familiar with cmake builds so probably I missed something.

**Logs/output**
`
export PATH=/workdir/artifacts/toolchain/nvtx2aarch64/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin:/usr/local/openjdk-8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ PATH=/workdir/artifacts/toolchain/nvtx2aarch64/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin:/usr/local/openjdk-8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ openssl_path=/workdir/artifacts/openssl/nvtx2aarch64
+ curl_path=/workdir/artifacts/curl/nvtx2aarch64
+ zlib_path=/workdir/artifacts/zlib/nvtx2aarch64
+ rm -rf /workdir/build
+ mkdir -p /workdir/build
+ cd /workdir/build
+ /workdir/artifacts/cmake/nvtx2aarch64/cmake-3.18.2-Linux-x86_64/bin/cmake .. '-DBUILD_ONLY=core;s3' -DCMAKE_BUILD_TYPE=Release -DCMAKE_LIBRARY_ARCHITECTURE=aarch64-linux-gnu -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_C_COMPILER=/workdir/artifacts/toolchain/nvtx2aarch64/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=/workdir/artifacts/toolchain/nvtx2aarch64/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++ '-DCMAKE_PREFIX_PATH=/workdir/artifacts/openssl/nvtx2aarch64;/workdir/artifacts/curl/nvtx2aarch64;/workdir/artifacts/zlib/nvtx2aarch64' '-DCMAKE_INSTALL_PREFIX=/workdir/nvtx2aarch64;' -DENABLE_TESTING=OFF
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating linux build config
-- Building project version: 1.9.34
-- The CXX compiler identification is GNU 7.3.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /workdir/artifacts/toolchain/nvtx2aarch64/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /workdir/artifacts/zlib/nvtx2aarch64/lib/libz.so (found version "1.2.11") 
--   Zlib library: /workdir/artifacts/zlib/nvtx2aarch64/lib/libz.so
-- Encryption: Openssl
**--   Using libcrypto and libssl from AWS-LC.**
-- Http client: Curl
-- Found CURL: /workdir/artifacts/curl/nvtx2aarch64/lib/libcurl.so (found version "7.70.0")  
--   Curl include directory: /workdir/artifacts/curl/nvtx2aarch64/include
--   Curl library: /workdir/artifacts/curl/nvtx2aarch64/lib/libcurl.so
-- Performing Test HAVE_ATOMICS_WITHOUT_LIBATOMIC
-- Performing Test HAVE_ATOMICS_WITHOUT_LIBATOMIC - Success
-- The C compiler identification is GNU 7.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /workdir/artifacts/toolchain/nvtx2aarch64/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- AWS CRT C++ 1.9.34-3-g4a44dd1664
CMake Warning (dev) at crt/aws-crt-cpp/crt/aws-c-common/CMakeLists.txt:5 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'STATIC_CRT'.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- CMake 3.18.2
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Failed
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_HAVE_WINAPI_DESKTOP
-- Performing Test AWS_HAVE_WINAPI_DESKTOP - Failed
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Failed
-- Performing Test AWS_ARCH_ARM64
-- Performing Test AWS_ARCH_ARM64 - Success
-- Performing Test AWS_ARCH_ARM32
-- Performing Test AWS_ARCH_ARM32 - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test AWS_HAVE_AUXV
-- Performing Test AWS_HAVE_AUXV - Success
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Success
-- Performing Test AWS_SHOULD_DISABLE_STRINGOP_OVERFLOW
-- Performing Test AWS_SHOULD_DISABLE_STRINGOP_OVERFLOW - Success
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Failed
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Failed
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test HAS_MOUTLINE_ATOMICS
-- Performing Test HAS_MOUTLINE_ATOMICS - Failed
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Looking for pthread_attr_setaffinity_np
-- Looking for pthread_attr_setaffinity_np - found
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Packaging currently only supported on Fedora.
-- Checking for module 'libunwind-generic'
--   No package 'libunwind-generic' found
libunwind not found. Disabling unwind tests.
-- Go not found. Disabling some code generation and using pre-generated code in generated-src/
-- Perl not found. Disabling some code generation and using pre-generated code in generated-src/
-- Test stdalign_check.c passed, enabling AWS_LC_STDALIGN_AVAILABLE
-- Test builtin_swap_check.c passed, enabling AWS_LC_BUILTIN_SWAP_SUPPORTED
-- The ASM compiler identification is GNU
-- Found assembler: /workdir/artifacts/toolchain/nvtx2aarch64/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc
**Copying platform assembly files from /workdir/crt/aws-crt-cpp/crt/aws-lc/generated-src/linux-x86_64/crypto/ to /workdir/build/crt/aws-crt-cpp/crt/aws-lc/crypto**
-- S2N found target: crypto
-- Using libcrypto from AWS-LC
-- Add s3-crt:s3 to C2J_SPECIAL_NAME_LIST
-- Considering core
-- Considering s3
-- Looking for pathconf
-- Looking for pathconf - found
-- Looking for umask
-- Looking for umask - found
-- Updating version info to 1.9.34
-- Custom memory management disabled
-- Performing Test CURL_HAS_H2
-- Performing Test CURL_HAS_H2 - Failed
-- Performing Test CURL_HAS_TLS_PROXY
-- Performing Test CURL_HAS_TLS_PROXY - Failed
-- Configuring done
-- Generating done
-- Build files have been written to: /workdir/build
+ make
[35m[1mScanning dependencies of target aws-c-common[0m
[  0%] [32mBuilding C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/allocator.c.o[0m
[  0%] [32mBuilding C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/allocator_sba.c.o[0m
[  0%] [32mBuilding C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/arch/arm/asm/cpuid.c.o[0m
...
[ 37%] [32m**Building ASM object crt/aws-crt-cpp/crt/aws-lc/crypto/CMakeFiles/crypto.dir/hrss/asm/poly_rq_mul.S.o[0m
/workdir/crt/aws-crt-cpp/crt/aws-lc/crypto/hrss/asm/poly_rq_mul.S: Assembler messages:
/workdir/crt/aws-crt-cpp/crt/aws-lc/crypto/hrss/asm/poly_rq_mul.S:320: Error: unknown pseudo-op: `.att_syntax'**
/workdir/crt/aws-crt-cpp/crt/aws-lc/crypto/hrss/asm/poly_rq_mul.S:323: Error: unknown mnemonic `push' -- `push %rbp'
/workdir/crt/aws-crt-cpp/crt/aws-lc/crypto/hrss/asm/poly_rq_mul.S:325: Error: bad register expression
/workdir/crt/aws-crt-cpp/crt/aws-lc/crypto/hrss/asm/poly_rq_mul.S:326: Error: unknown mnemonic `movq' -- `movq %rsp,%rbp'
...
/workdir/crt/aws-crt-cpp/crt/aws-lc/crypto/hrss/asm/poly_rq_mul.S:8461: Error: bad register expression
crt/aws-crt-cpp/crt/aws-lc/crypto/CMakeFiles/crypto.dir/build.make:3073: recipe for target 'crt/aws-crt-cpp/crt/aws-lc/crypto/CMakeFiles/crypto.dir/hrss/asm/poly_rq_mul.S.o' failed
`

**Comment by KaibaLopez** [comment]
Hi, we did have a few changes happening these past couple weeks, I would suggest you update to the latest version (1.9.37 was a big fix).

**Comment by mbutkovski** [comment]
Thank you @KaibaLopez  ! 
You are right. I used 1.9.40 and it worked.
