### ISSUE TITLE
TranscribeStreaming streaming short audio data does not work

### ISSUE THREAD

**Issue by diegonieto** [aws/aws-sdk-cpp#1683]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
When trying to recognize short audio I found that the service expect for more data instead of recognize the audio in that moment. I also found that if I write several empty audio events to the service:
------
        for (unsigned int i=0; i<10; i++)
        {
            stream.WriteAudioEvent({}); // per the spec, we have to send an empty event (i.e. without a payload) at the end.
        }
------
the service is able to detect that the audio is finished and starts to recognition process

I'm sending streaming audio on the fly, i.e, I don't know what is total size of the audio data till the user stops pressing the microphone. Then, I am sending several wav headers indicating the chunk size for all of them (the total audio data is splitted in 8192 byte chunks). This is working, however I am wondering if there is another way to specify wav header when the size is unknown at the beginning and if there is way to calculate the number of empty audio events needed for a certain amount of audio data. If there is a way to speedup the recognition process.

It seems that writing empty audio events makes the recognizer to start earlier, does it make sense? Thanks in advance

**SDK version number**
1.9

**Platform/OS/Hardware/Device**
What are you running the sdk on?
ARM and x64

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
Send to the transcribe streaming service short audios

**Expected behavior**
work with short audio data

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
Hi @diegonieto ,
I'm going to need to see sample code to reproduce this.

**Comment by diegonieto** [comment]
Hi @KaibaLopez,

This is example to reproduce the issue: 
[test.zip](https://github.com/aws/aws-sdk-cpp/files/6670980/test.zip) (credentials have been removed)


If you run it without arguments the output is like this:
---------------------------------------
$ ./test
Starting
Initialize SDK
Creating client config
Creating client
Creating client with previous config
Client created
Creating even callback
Creating even error callback
Creating request
Starting Asynch transmission: 139625724659648
1623939315749 Reading file: 139625724659648
1623939315949 Writing 4096 block 
1623939316444 Writing 4096 block 
1623939316650 Writing 4096 block 
1623939316857 Writing 4096 block 
1623939317063 Writing 4096 block 
1623939317269 Writing 4096 block 
1623939317476 Writing 4096 block 
1623939317682 Writing 4096 block 
1623939317889 Writing 4096 block 
1623939318095 Writing 4096 block 
1623939318301 Writing 4096 block 
1623939318508 Writing 4096 block 
1623939318715 Writing 4096 block 
1623939318916 Writing 4096 block 
1623939319122 Writing 4096 block 
1623939319329 Writing 4096 block 
Empty results: 
Empty results: 
1623939319335 Transcript result: But
Empty results: 
1623939319336 Transcript result: But what
1623939319336 Transcript result: But what if
1623939319337 Transcript result: But what if
1623939319337 Transcript result: But what if some
1623939319338 Transcript result: But what if somebody
1623939319338 Transcript result: But what if somebody did?
---------------------------------------

Please, check that from the first writing block (1623939315949 Writing 4096 block ) till the first partial result (1623939319335 Transcript result: But) takes 3386ms.

Now, If we run it with an argument, that means stop filling the data in the block <argument>, we will see that the first partial is returned sooner:
---------------------------------------
$ ./test 3
Starting
Initialize SDK
Creating client config
Creating client
Creating client with previous config
Client created
Creating even callback
Creating even error callback
Creating request
Starting Asynch transmission: 140020746737600
1623939493835 Reading file: 140020746737600
1623939494036 Writing 4096 block 
1623939494658 Writing 4096 block 
1623939494864 Writing EMPTY block 
1623939494868 Total file read: 0
1623939495275 Transcript result: That
1623939495275 Transcript result: That we
1623939495275 Transcript result: That we
1623939495276 Releasing semaphore
API Shudown
-------------------------------------

Now, from the first read till the first partial takes only 1239ms

So, I would like to have the first partial result at 1239ms instead of 3386, no matter how long the audio is. It seems that the service is listening for a while before start processing the data. I know that my audio will be really short (1-3), so it would be nice if the streaming service is able to give me partials at the same time the user is still talking to the microphone .

Thanks in advance for your help

**Comment by diegonieto** [comment]
Hi @KaibaLopez , do you have any update for this?
