### ISSUE TITLE
How can I cross compile it for Nintendo switch?

### ISSUE THREAD

**Issue by wukakuki** [aws/aws-sdk-cpp#1689]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Nintendo switch

**Describe the question**
How can I cross compile it for Nintendo switch? Is there any document about it? 
Thank you very much

**Comment by KaibaLopez** [comment]
Hi @wukakuki ,
So we don't really support Nintendo switch as a platform. 
In theory it should work, but we don't have documentation for that, nor do we test on the platform.

**Comment by wukakuki** [comment]
> Hi @wukakuki ,
> So we don't really support Nintendo switch as a platform.
> In theory it should work, but we don't have documentation for that, nor do we test on the platform.

thanks. I'll try by myself.

**Comment by CrHasher** [comment]
@KaibaLopez Nintendo is really popular nowadays it would be nice if it would get the same level of support as other platforms. I would also need support for aws sdk to work on nintendo. We have a server embedded in the client for testing porpoises that runs on nintendo switch, obviously we need to compile the aws sdk to work on switch for this or disable features that use the aws sdk (very inconvenient).
