### ISSUE TITLE
curl and openssl paths not configurable

### ISSUE THREAD

**Issue by drivehappy** [aws/aws-sdk-cpp#169]
We currently extract and build specific versions of curl and openssl for our existing product that targets Android/Linux/Windows.

I would like to integrate the AWS SDK into our build system, but there doesn't appear to be a way through CMake that allows me to point it to our curl and openssl directories. At least under Linux the CMake scripts appear to require that the curl/openssl libraries are installed on the system.

I would like to have the ability to specify CMake variables that point to a pre-extracted location for curl and openssl.

**Comment by JonathanHenson** [comment]
One thing you can do is add additional include arguments for the include directory you want to search. You can do something similar for the linker. In the meantime, we'll investigate ways we can make this less painful

**Comment by bretambrose** [comment]
This is currently in development and will hopefully available within a week or so

**Comment by bretambrose** [comment]
We now take four command line parameters for custom curl/openssl installations:
CURL_LIB_DIR, CURL_INCLUDE_DIR, OPENSSL_LIB_DIR, OPENSSL_INCLUDE_DIR. Please let us know if this doesn't work for you.  I think a better approach would be for us to use find_package/library on curl and openssl which would let you simply modify CMAKE_PREFIX_PATH with your custom installation directories; I may try and slip this in as part of a larger cmake-cleanup pass.

**Comment by drivehappy** [comment]
That looks like it solved my problem, thanks.
