### ISSUE TITLE
[Regression] S3Client::PutObject removes trailing slash

### ISSUE THREAD

**Issue by pitrou** [aws/aws-sdk-cpp#1690]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**

Recently, `S3Client::PutObject` has started removing the trailing slash on the object name.

With the SDK 1.8.186, `PutObject` with bucket `bucket` and key `somedir/` would generate the following HTTP request:
```http
PUT /bucket/somedir/ HTTP/1.1
Host: 127.0.0.1:41583
Accept: */*
Connection: Upgrade, HTTP2-Settings
Upgrade: h2c
HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA
amz-sdk-invocation-id: 4E54B096-D0B9-45CE-8906-42CFAB0CE190
amz-sdk-request: attempt=1
authorization: AWS4-HMAC-SHA256 Credential=minio/20210621/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-content-sha256;x-amz-date, Signature=302cf010d02d55edefa6b0d7aea893f4a1415caf86388820535f9ab0a1f61d7a
content-length: 0
content-type: binary/octet-stream
user-agent: aws-sdk-cpp/1.8.186 Linux/5.4.0-74-generic x86_64 GCC/9.3.0
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20210621T130019Z
```

With the SDK 1.9.39, the same method calls generates the following HTTP request:
```http
PUT /bucket/somedir HTTP/1.1
Host: 127.0.0.1:47097
Accept: */*
Connection: Upgrade, HTTP2-Settings
Upgrade: h2c
HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA
amz-sdk-invocation-id: 00000000-0000-4000-8000-000000000000
amz-sdk-request: attempt=1
authorization: AWS4-HMAC-SHA256 Credential=minio/20210621/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-content-sha256;x-amz-date, Signature=4eea707adda5a995b6cf4efa5ca35ce8825f3c0d4c45100b94e73bc13ca1150c
content-length: 0
content-type: binary/octet-stream
user-agent: aws-sdk-cpp/1.9.39 Linux/5.4.0-74-generic x86_64 GCC/9.3.0
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20210621T125048Z
```

The trailing slash is significant for some S3 implementations such as Minio, which is a problem here (there's no obvious way to force a trailing slash on the request). Generally, it seems wrong for the AWS SDK to silently modify the user-provided request.

**SDK version number**

1.9.39

**Platform/OS/Hardware/Device**

Ubuntu 20.04.2

**Comment by KaibaLopez** [comment]
Hi @pitrou ,
Yea thanks for pointing this out to us, we'll look more into it.

**Comment by wps132230** [comment]
I am able to reproduce this issue, and we are working on the fix.
The root cause is `URI::AddPathSegments()` removes the trailing slash.

**Comment by wps132230** [comment]
Fixed with https://github.com/aws/aws-sdk-cpp/commit/6dd8d33150346caa458407fca9d67139e11db0f3
Please reopen this issue or create new one if you still see it.

**Comment by pitrou** [comment]
Thank you @wps132230, this did fix the issues we were seeing.
