### ISSUE TITLE
How do I adjust multipart_chunk_size

### ISSUE THREAD

**Issue by witanswer** [aws/aws-sdk-cpp#1693]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
linux/c++

**Describe the question**
when trying to upload a file > 52gb, I get the following error:

Part number must be an integer between 1 and 10000, inclusive

It seems like i need to change the chunk size from reading https://docs.aws.amazon.com/sdkref/latest/guide/setting-s3-multipart_chunk_size.html

but I can't see how to do it in the sdk.

code:

`    auto uploadHandle = m_TransferManager->UploadFile(path, m_Bucket, key, "text/plain", Aws::Map<Aws::String, Aws::String>());
    uploadHandle->WaitUntilFinished();//blocking
    
    //https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-transfer-tests/TransferTests.cpp
    //make sure we don't fail because of failing to download a part for occasional reasons like network problem or s3 eventual consistency.
    size_t retries = 0;
    while (uploadHandle->GetStatus() == Aws::Transfer::TransferStatus::FAILED && retries++ < 5)
    {
        auto last_error = uploadHandle->GetLastError();
        string warning = "error name:";
        warning.append(last_error.GetExceptionName())
                .append(" message:")
                .append(last_error.GetMessage())
                .append(" shouldRetry:")
                .append(last_error.ShouldRetry()?"true":"false");
        ERR_POST(Warning << warning);
        warning = "upload failed (uploaded ";
        warning.append(NStr::NumericToString(uploadHandle->GetBytesTransferred()))
                .append(" bytes vs ")
                .append(NStr::NumericToString(uploadHandle->GetBytesTotalSize()))
                .append(" total), retrying:")
                .append(path);
`

**Logs/output**
error name:InvalidArgument message:Unable to parse ExceptionName: InvalidArgument Message: Part number must be an integer between 1 and 10000, inclusive shouldRetry:false
upload failed (uploaded 52428800000 bytes vs 53738388247 total), retrying:<path>

If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
Hi @witanswer ,
the good news is that you are using transfer manager already which makes this much easier, just change bufferSize in the trasnferManagerConfiguration, like:
```cpp
TransferManagerConfiguration transferManagerConfig(&executor);
transferManagerConfig.bufferSize = //uint64_t value depends on total size, 5mb is default with a max total size of 50gb, in your case 6mb might be enough.
```
Let me know if that is all you need or if I misunderstood the question.

**Comment by witanswer** [comment]
Perfect that's exactly what I need. Tested working.

Really appreciate the help, Thanks
