### ISSUE TITLE
error when making

### ISSUE THREAD

**Issue by DreadRemilia** [aws/aws-sdk-cpp#1696]
when making sdk, the error occurred like this
![Z%PYN2X)E72%_9%PGDA8LN4](https://user-images.githubusercontent.com/54435791/124103948-5de16680-da94-11eb-8578-138a54a95c98.png)

**Comment by KaibaLopez** [comment]
Hi @DreadRemilia ,
Did you run add `--recurse-submodules` to your git clone command? If not try running:
```git submodule update --init --recursive```
Make sure to clear your cmake cache and try again, also make sure to add `-DBUID_SHARED_LIBS=ON` to your cmake command.
If after doing these you are still having this issue, then I'm going to need you to walk me through the steps you took to build the SDK.
