### ISSUE TITLE
 HttpClientTest.TestRandomURLWithProxy test failure on ubuntu 20.04

### ISSUE THREAD

**Issue by n242** [aws/aws-sdk-cpp#1697]
**Describe the bug**
failed tests of HttpClientTest.TestRandomURLWithProxy with message: 
SSL peer certificate or SSH remote key was not OK

**SDK version number**
 1.9.40

**Platform/OS/Hardware/Device**
ubuntu 20.04
host machine: windows 10, docker desktop using WSL 2

**To Reproduce (observed behavior)**
command ran was: docker build -t <image-name> .
docker file: 
RUN git clone --recurse-submodules --branch 1.9.40 https://github.com/aws/aws-sdk-cpp
RUN mkdir sdk_build
RUN cd sdk_build
RUN cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE=Release -D BUILD_ONLY="s3"
RUN make
RUN make install

**Expected behavior**

**Logs/output**
#15 401.7 [----------] 6 tests from HttpClientTest
#15 401.7 [ RUN      ] HttpClientTest.TestRandomURLWithProxy
#15 402.0 /aws-sdk-cpp/aws-cpp-sdk-core-tests/http/HttpClientTest.cpp:64: Failure
#15 402.0 Failed
#15 402.0 The curl error code has to be 28 in [curlCode: 60, SSL peer certificate or SSH remote key was not OK]
#15 402.0 [  FAILED  ] HttpClientTest.TestRandomURLWithProxy (259 ms)
#15 402.0 [ RUN      ] HttpClientTest.TestRandomURLWithProxyAndOtherDeclaredAsNonProxyHost
#15 402.2 /aws-sdk-cpp/aws-cpp-sdk-core-tests/http/HttpClientTest.cpp:64: Failure
#15 402.2 Failed
#15 402.2 The curl error code has to be 28 in [curlCode: 60, SSL peer certificate or SSH remote key was not OK]
#15 402.2 [  FAILED  ] HttpClientTest.TestRandomURLWithProxyAndOtherDeclaredAsNonProxyHost (255 ms)
#15 402.2 [ RUN      ] HttpClientTest.TestRandomURLWithProxyAndDeclaredParentDomainAsNonProxyHost
#15 402.2 [       OK ] HttpClientTest.TestRandomURLWithProxyAndDeclaredParentDomainAsNonProxyHost (25 ms)
#15 402.2 [ RUN      ] HttpClientTest.TestRandomURLMultiThreaded
#15 403.4 /aws-sdk-cpp/aws-cpp-sdk-core-tests/http/HttpClientTest.cpp:64: Failure
#15 403.4 Failed
#15 403.4 The curl error code has to be 6 in [curlCode: 28, Timeout was reached]
#15 403.4 /aws-sdk-cpp/aws-cpp-sdk-core-tests/http/HttpClientTest.cpp:64: Failure
#15 403.4 Failed
#15 403.4 The curl error code has to be 6 in [curlCode: 28, Timeout was reached]
#15 403.4 /aws-sdk-cpp/aws-cpp-sdk-core-tests/http/HttpClientTest.cpp:64: Failure

**Additional context**
used default settings for proxy and network on docker desktop

**Comment by KaibaLopez** [comment]
Hi @n242 ,
This error has been fixed as of versions 1.9.56, could you update and try again? 
Also, as a side note you could also make your build faster and avoid getting blocked by adding the `-DENABLE_TESTING=OFF` argument to your cmake command.
