### ISSUE TITLE
Is there a library that help me calculate password verifier for confirm device of cognito?

### ISSUE THREAD

**Issue by wukakuki** [aws/aws-sdk-cpp#1699]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
macOS

**Describe the question**
Is there a library that help me calculate password verifier for confirm device of cognito?
I read [cognito-user-pool-remembered-devices](https://aws.amazon.com/premiumsupport/knowledge-center/cognito-user-pool-remembered-devices/) and want to implement it into my c++ application.
I found that there is a AuthenticationHelper.js in amplify which help js developer calculating the password verifier. So, I wonder if there is a c++ version library to do so. I do found someone posted [srp_A calculator](https://gist.github.com/manishpin/f7d8e9af84068bd9b0220bb2c7d14a4d). But, password verifier calculator is missing. Thanks.

**Comment by KaibaLopez** [comment]
Hi @wukakuki ,
I am not really sure what you are looking for here, but I don't think we have anything of the sort, we do not really provide helper libraries... The best place to look for something like that would be on the aws-iam service but yea...
Could you show me a code sample? even if it's just pseudo code, just so I get a better idea on what you expect the helper to do. Maybe it can be done with our current tools.

**Comment by wukakuki** [comment]
<img width="1459" alt="Screen Shot 2021-07-07 at 10 55 27 PM" src="https://user-images.githubusercontent.com/7627497/124782050-7bbc3900-df76-11eb-9682-46f599e0d30c.png">

can you see this picture? I want a c++ library to help me calculate the salt and password verifier for confirm device from cognito idp client.

> Hi @wukakuki ,
> I am not really sure what you are looking for here, but I don't think we have anything of the sort, we do not really provide helper libraries... The best place to look for something like that would be on the aws-iam service but yea...
> Could you show me a code sample? even if it's just pseudo code, just so I get a better idea on what you expect the helper to do. Maybe it can be done with our current tools.

**Comment by KaibaLopez** [comment]
Hi @wukakuki sorry for the slow response but no, we don't really provide any such helper.

**Comment by wukakuki** [comment]
Thanks
