### ISSUE TITLE
Use of long causing compile issues for iOS arm64

### ISSUE THREAD

**Issue by BruceSutherland** [aws/aws-sdk-cpp#170]
Hi guys,

The long type is 8 bytes on arm64 builds and this causes a lot of compile errors in the SDK.

I'd recommend moving to explicitly sized types (i.e. int32_t, etc.) to ensure portable code.

https://developer.apple.com/library/ios/documentation/General/Conceptual/CocoaTouch64BitGuide/Major64-BitChanges/Major64-BitChanges.html

Thanks,
Bruce

**Comment by Bu11etmagnet** [comment]
The long type is also 8 bytes on 64-bit Intel CPUs and there are no compilation errors there. What errors are you talking about?

**Comment by BruceSutherland** [comment]
I reverted my changes.

The first error I hit is:

/Users/Bruce/Documents/UnrealProjects/AWS-CPP-SDK/aws-cpp-sdk-core/source/external/json-cpp/jsoncpp.cpp:1672:41: error: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'unsigned int' [-Werror,-Wshorten-64-to-32]
  comment_ = duplicateStringValue(text, len);
             ~~~~~~~~~~~~~~~~~~~~       ^~~
1 error generated.

**Comment by bretambrose** [comment]
Jsoncpp.cpp and tinyxml2.cpp are external open source implementations that we've pulled in in order to stay self-contained.  If at all possible, we'd like to avoid making changes to them (although we've had to a few times).  As a temporary measure, can you disable the warning just on those two files and see what happens?  If we have similar issues in the SDK at large then that's more worrying.  I ran into a similar issue last week targeting Android arm64 with openssl, but I didn't have time to investigate further.

**Comment by BruceSutherland** [comment]
There are definitely more within the SDK code.

I'm only building access-management, core, cognito-identity, iam and identity-management at the moment.

I'll go through the process of working through the errors from scratch again and document all of the errors here.

I like the idea of strict error levels and Werror so I'd rather not relax that.

I've seen other pull requests that have removed Werror. I'm not sure that's a good idea for a cross-platform library such as this.

**Comment by Bu11etmagnet** [comment]
That's odd, on 64-bit Linux also size_t is larger than unsigned int; but I get no warning:

```
g++-530  -DAWS_SDK_PLATFORM_LINUX -DENABLE_CURL_CLIENT -DENABLE_OPENSSL_ENCRYPTION -DJSON_USE_EXCEPTION=0 -Daws_cpp_sdk_core_EXPORTS -Wall -Werror -pedantic -Wextra -fno-exceptions -fPIC -I../aws-cpp-sdk-core/include    -std=c++11 -Wall -Werror -Wno-comment -MMD -MT aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/external/json-cpp/jsoncpp.cpp.o -MF aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/external/json-cpp/jsoncpp.cpp.o.d -o aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/external/json-cpp/jsoncpp.cpp.o -c ../aws-cpp-sdk-core/source/external/json-cpp/jsoncpp.cpp
```
(Werror is there twice, to be extra sure :)

**Comment by BruceSutherland** [comment]
-Wshorten-64-to-32 isn't supported by G++ according to my quick Google searches so you won't get the errors. iOS programs are compiled with Apple LLVM/Clang. I assume if you compiled with Clang on Linux with the same switch you would see the errors.

My preference would be ensuring consistency in using long or int where desired over removing that error case. The standard doesn't guarantee that int and long are the same size so that assumption wouldn't be sound.

Even better would be to use the explicitly sized types from cstdint given this is a library that can be compiled for lots of different platforms and instruction sets.

My local changes altered every case of a long that had a setter or getter passing/returning an int to be an int32_t instead but I haven't had time to grab the patch. I'm using the C++ SDK in my spare time with Unreal and not as part of my day job.

**Comment by Bu11etmagnet** [comment]
"I assume if you compiled with Clang on Linux with the same switch you would see the errors."
You assume correctly :)

It would be nice to add -Wshorten-64-to-32 to CXXFLAGS when the compiler is clang. Then all these inconsistencies would have to be fixed (why can't JsonCPP use size_t for string length???).

**Comment by Bu11etmagnet** [comment]
Here's an example of this:
`Aws::CodePipeline::Model::ActionDeclaration` (aws-cpp-sdk-codepipeline/include/aws/codepipeline/model/ActionDeclaration.h) has a `long m_runOrder` member. However, in `ActionDeclaration::Jsonize` (aws-cpp-sdk-codepipeline/source/model/ActionDeclaration.cpp:136) there's
```
  if(m_runOrderHasBeenSet)
  {
   payload.WithInteger("runOrder", m_runOrder); // line 136
  }

```

`JsonValue::WithInteger` takes an `int` parameter. If `m_runOrder` really has to be long, then this call could be changed to `WithInt64`.

**Comment by bretambrose** [comment]
We want to get this fixed but don't have an immediate ETA; I started on it this weekend but had some other priorities take over.  Within the service clients & models, I would prefer to see long become int32_t rather than int64_t, as all currently-happy platforms would remain the same.

**Comment by bretambrose** [comment]
In more detail, the service clients/models will transform via

int, long -> int32_t
unsigned, unsigned int, unsigned long -> uint32_t
long long -> int64_t
unsigned long long -> uint64_t

Within aws-cpp-sdk-core, I feel like we need to be a bit more careful because of size_t conversions and comparisons and such.  Also we use ints in a lot of places that uints would be preferable and it might be a good time to address that as well.

**Comment by JonathanHenson** [comment]
We decided to explicitly declare long long and long. This has been pushed out. Let us know if issues persist.
