### ISSUE TITLE
when I build static library for Mac or iOS, cJson symbols in aws-sdk-cpp-core, crt and aws-c-auth will be duplicated. How can I hide cJson symbols for crt and aws-c-auth?

### ISSUE THREAD

**Issue by wukakuki** [aws/aws-sdk-cpp#1700]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
MacOS and iOS

**Describe the question**
I'm using 1.9.14
when I build static library for Mac or iOS, cJson symbols in aws-sdk-cpp-core, crt and aws-c-auth will be duplicated. How can I hide cJson symbols for crt and aws-c-auth? Thanks a lot.

**Logs/output**
ld: warning: duplicate symbol '_cJSON_AddStringToObject' in:
libaws-c-auth.a(cJSON.c.o)
libaws-cpp-sdk-core.a(cJSON.cpp.o)

**Comment by KaibaLopez** [comment]
Hi @wukakuki , I am not seeing these warnings,
Could you walk me through how you are building the SDK so that I can reproduce?

**Comment by wukakuki** [comment]
> Hi @wukakuki , I am not seeing these warnings,
> Could you walk me through how you are building the SDK so that I can reproduce?

build ios libraries with `-DBUILD_SHARED_LIBS=OFF` and then add it to an ios project. then build the ios project. then a lot of duplicate symbols warnings appear. they are only warning and I can just ignore them. So, it's not a big problem. I just don't like these warnings showing up. 

```
ld: warning: duplicate symbol '_cJSON_AddStringToObject' in:
libaws-c-auth.a(cJSON.c.o)
libaws-cpp-sdk-core.a(cJSON.cpp.o)
```

**Comment by KaibaLopez** [comment]
@wukakuki ,
Yea it is kind of annoying but for the moment we don't have a workaround for it... we'll try to look into removing the second definition, but it will probably take a while. Sorry

**Comment by wukakuki** [comment]
> @wukakuki ,
> Yea it is kind of annoying but for the moment we don't have a workaround for it... we'll try to look into removing the second definition, but it will probably take a while. Sorry

yep. I can understand. 
it's just some warning. 
and removing the cJson from aws SDK CPP will make code in aws SDK CPP include the header from aws c auth library directly. It doesn't look beautiful. that's alright.
