### ISSUE TITLE
How to decrypt events from Kinesis

### ISSUE THREAD

**Issue by COMEBACKISREAL** [aws/aws-sdk-cpp#1701]
Confirm by changing [ ] to [x] below:
- [+] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [+] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Windows 10

**Describe the question**
Hello, Could you please give an example on c++ how to decrypt messages from 
` Aws::Kinesis::Model::GetRecordsOutcome getRecordsResult = kinesisClient.GetRecords(getRecordsRequest);`
Like how it's done in python example. Should I use aws-encryption-sdk-c or is the aws: kms library sufficient? Is there is in vcpkg
aws-encryption-sdk-c if i should use it? 
Thanks!
![image](https://user-images.githubusercontent.com/18268483/124288524-f392f980-db59-11eb-85e6-cd5c698338c5.png)

```import base64
import json
import zlib
import aws_encryption_sdk
from aws_encryption_sdk import CommitmentPolicy
from aws_encryption_sdk.internal.crypto import WrappingKey
from aws_encryption_sdk.key_providers.raw import RawMasterKeyProvider
from aws_encryption_sdk.identifiers import WrappingAlgorithm, EncryptionKeyType
import boto3

REGION_NAME = '<region>'                    # us-east-1
RESOURCE_ID = '<external-resource-id>'      # cluster-ABCD123456
STREAM_NAME = 'aws-rds-das-' + RESOURCE_ID  # aws-rds-das-cluster-ABCD123456

enc_client = aws_encryption_sdk.EncryptionSDKClient(commitment_policy=CommitmentPolicy.REQUIRE_ENCRYPT_ALLOW_DECRYPT)

class MyRawMasterKeyProvider(RawMasterKeyProvider):
    provider_id = "BC"

    def __new__(cls, *args, **kwargs):
        obj = super(RawMasterKeyProvider, cls).__new__(cls)
        return obj

    def __init__(self, plain_key):
        RawMasterKeyProvider.__init__(self)
        self.wrapping_key = WrappingKey(wrapping_algorithm=WrappingAlgorithm.AES_256_GCM_IV12_TAG16_NO_PADDING,
                                        wrapping_key=plain_key, wrapping_key_type=EncryptionKeyType.SYMMETRIC)

    def _get_raw_key(self, key_id):
        return self.wrapping_key


def decrypt_payload(payload, data_key):
    my_key_provider = MyRawMasterKeyProvider(data_key)
    my_key_provider.add_master_key("DataKey")
    decrypted_plaintext, header = enc_client.decrypt(
        source=payload,
        materials_manager=aws_encryption_sdk.materials_managers.default.DefaultCryptoMaterialsManager(master_key_provider=my_key_provider))
    return decrypted_plaintext


def decrypt_decompress(payload, key):
    decrypted = decrypt_payload(payload, key)
    return zlib.decompress(decrypted, zlib.MAX_WBITS + 16)


def main():
    session = boto3.session.Session()
    kms = session.client('kms', region_name=REGION_NAME)
    kinesis = session.client('kinesis', region_name=REGION_NAME)

    response = kinesis.describe_stream(StreamName=STREAM_NAME)
    shard_iters = []
    for shard in response['StreamDescription']['Shards']:
        shard_iter_response = kinesis.get_shard_iterator(StreamName=STREAM_NAME, ShardId=shard['ShardId'],
                                                         ShardIteratorType='LATEST')
        shard_iters.append(shard_iter_response['ShardIterator'])

    while len(shard_iters) > 0:
        next_shard_iters = []
        for shard_iter in shard_iters:
            response = kinesis.get_records(ShardIterator=shard_iter, Limit=10000)
            for record in response['Records']:
                record_data = record['Data']
                record_data = json.loads(record_data)
                payload_decoded = base64.b64decode(record_data['databaseActivityEvents'])
                data_key_decoded = base64.b64decode(record_data['key'])
                data_key_decrypt_result = kms.decrypt(CiphertextBlob=data_key_decoded,
                                                      EncryptionContext={'aws:rds:dbc-id': RESOURCE_ID})
                print(decrypt_decompress(payload_decoded, data_key_decrypt_result['Plaintext']))
            if 'NextShardIterator' in response:
                next_shard_iters.append(response['NextShardIterator'])
        shard_iters = next_shard_iters


if __name__ == '__main__':
    main()

**Comment by KaibaLopez** [comment]
Hi @COMEBACKISREAL ,
Sorry for the slow response, I am not familiar with aws-encryption-sdk-c  but in theory the KMS library should be enough.
You can take a look at [this sample](https://github.com/awsdocs/aws-doc-sdk-examples/blob/d707945f25589c0b2caea3a1c9a34fb8e2135ce8/cpp/example_code/kinesis/put_get_records.cpp) on how to get records from a stream with encoding disabled.

**Comment by ailtire-JonGrant** [comment]
> Confirm by changing [ ] to [x] below:
> 
>     * [+] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
> 
>     * [+] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
> 
> 
> **Platform/OS/Hardware/Device** Windows 10
> 
> **Describe the question** Hello, Could you please give an example on c++ how to decrypt messages from ` Aws::Kinesis::Model::GetRecordsOutcome getRecordsResult = kinesisClient.GetRecords(getRecordsRequest);` Like how it's done in python example. Should I use aws-encryption-sdk-c or is the aws: kms library sufficient? Is there is in vcpkg aws-encryption-sdk-c if i should use it? Thanks! ![image](https://user-images.githubusercontent.com/18268483/124288524-f392f980-db59-11eb-85e6-cd5c698338c5.png)
> 
> ```
> import json
> import zlib
> import aws_encryption_sdk
> from aws_encryption_sdk import CommitmentPolicy
> from aws_encryption_sdk.internal.crypto import WrappingKey
> from aws_encryption_sdk.key_providers.raw import RawMasterKeyProvider
> from aws_encryption_sdk.identifiers import WrappingAlgorithm, EncryptionKeyType
> import boto3
> 
> REGION_NAME = '<region>'                    # us-east-1
> RESOURCE_ID = '<external-resource-id>'      # cluster-ABCD123456
> STREAM_NAME = 'aws-rds-das-' + RESOURCE_ID  # aws-rds-das-cluster-ABCD123456
> 
> enc_client = aws_encryption_sdk.EncryptionSDKClient(commitment_policy=CommitmentPolicy.REQUIRE_ENCRYPT_ALLOW_DECRYPT)
> 
> class MyRawMasterKeyProvider(RawMasterKeyProvider):
>     provider_id = "BC"
> 
>     def __new__(cls, *args, **kwargs):
>         obj = super(RawMasterKeyProvider, cls).__new__(cls)
>         return obj
> 
>     def __init__(self, plain_key):
>         RawMasterKeyProvider.__init__(self)
>         self.wrapping_key = WrappingKey(wrapping_algorithm=WrappingAlgorithm.AES_256_GCM_IV12_TAG16_NO_PADDING,
>                                         wrapping_key=plain_key, wrapping_key_type=EncryptionKeyType.SYMMETRIC)
> 
>     def _get_raw_key(self, key_id):
>         return self.wrapping_key
> 
> 
> def decrypt_payload(payload, data_key):
>     my_key_provider = MyRawMasterKeyProvider(data_key)
>     my_key_provider.add_master_key("DataKey")
>     decrypted_plaintext, header = enc_client.decrypt(
>         source=payload,
>         materials_manager=aws_encryption_sdk.materials_managers.default.DefaultCryptoMaterialsManager(master_key_provider=my_key_provider))
>     return decrypted_plaintext
> 
> 
> def decrypt_decompress(payload, key):
>     decrypted = decrypt_payload(payload, key)
>     return zlib.decompress(decrypted, zlib.MAX_WBITS + 16)
> 
> 
> def main():
>     session = boto3.session.Session()
>     kms = session.client('kms', region_name=REGION_NAME)
>     kinesis = session.client('kinesis', region_name=REGION_NAME)
> 
>     response = kinesis.describe_stream(StreamName=STREAM_NAME)
>     shard_iters = []
>     for shard in response['StreamDescription']['Shards']:
>         shard_iter_response = kinesis.get_shard_iterator(StreamName=STREAM_NAME, ShardId=shard['ShardId'],
>                                                          ShardIteratorType='LATEST')
>         shard_iters.append(shard_iter_response['ShardIterator'])
> 
>     while len(shard_iters) > 0:
>         next_shard_iters = []
>         for shard_iter in shard_iters:
>             response = kinesis.get_records(ShardIterator=shard_iter, Limit=10000)
>             for record in response['Records']:
>                 record_data = record['Data']
>                 record_data = json.loads(record_data)
>                 payload_decoded = base64.b64decode(record_data['databaseActivityEvents'])
>                 data_key_decoded = base64.b64decode(record_data['key'])
>                 data_key_decrypt_result = kms.decrypt(CiphertextBlob=data_key_decoded,
>                                                       EncryptionContext={'aws:rds:dbc-id': RESOURCE_ID})
>                 print(decrypt_decompress(payload_decoded, data_key_decrypt_result['Plaintext']))
>             if 'NextShardIterator' in response:
>                 next_shard_iters.append(response['NextShardIterator'])
>         shard_iters = next_shard_iters
> 
> 
> if __name__ == '__main__':
>     main()
> ```

This is the correct answer!  FYI you need to add "import base64".  Thx for this!
