### ISSUE TITLE
can't build the sdk source code with steps on README.md

### ISSUE THREAD

**Issue by forhead** [aws/aws-sdk-cpp#1704]
**Describe the bug**
try to compile the source code by the steps in README file , but I failed. after reading this doc https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup-linux.html ,  I can success to compile source code.

can you please update the doc of compiling code?

**Comment by KaibaLopez** [comment]
Hi @forhead ,
Could you point out what was the step missing or the error you were seeing with the instructions from the ReadMe? As it is now the Readme is admittedly confusing but I want to make sure I know what to fix.
