### ISSUE TITLE
Including aws-sdk-cpp in a stand-alone project

### ISSUE THREAD

**Issue by angrdtsk** [aws/aws-sdk-cpp#1705]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Debian Stretch

**Describe the question**
How exactly do I add this library into a cmake project so that both the includes and linking work?

The best possible answer to this question would be a minimal working code example that would:
- include CMakeLists.txt, main.cpp and other files that may be needed
- assume that aws-sdk-cpp has been built and installed at /my-experiments/aws-sdk-cpp-install
- demonstrate itself by calling ListJobs and printing the outcome

**Comment by KaibaLopez** [comment]
Hi @angrdtsk ,
You can find a quick guide [here](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/build-cmake.html).
Let me know if that's not what you are looking for though, or if you have more specific questions.

**Comment by angrdtsk** [comment]
@KaibaLopez I managed to build that example and I dare to assume that once I will get some other issues not related to this fixed, it will all work. Thanks!

One of those issues is that when running the example program, I get an error from cURL which, according to my research, suggests that the cURL in my Debian Stretch may be too old.

Extra question: Excluding the documentation (like the example you linked), is there a place in the library Git tree where I could have checked what exactly to put in my CMakeLists.txt to make includes and linking work?

**Comment by angrdtsk** [comment]
The example program gives me this output, with varying response codes:
Failed with error: HTTP response code: 698850932
Exception name: 
Error message: Unable to connect to endpoint
0 response headers:

Other codes that I got: -1113260428, 186392180 and 1088740980.

What could be causing that?

**Comment by KaibaLopez** [comment]
unable to connect to endpoint could be a number of things...
The best way to know what's going on is to change the log level to Trace :
```
options.loggingOptions.logLevel = Utils::Logging::LogLevel::Trace;
```
After you run the code it should create a log file with the full story of the call, If you want me to take a look at it, you can upload it here, just make sure you censor out any mention of your credentials or secret key.
And no, we don't have a `CMakeLists` sample in the repo.

**Comment by angrdtsk** [comment]
This is working now. I am not absolutely sure of what fixed it, but my best guess is moving from Debian Stretch to Buster which features more recent curl library.
