### ISSUE TITLE
Build Failure: Undefined Symbol undefined symbol: _ZN3Aws6Client9AWSClient20SetServiceClientNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by jplflyer** [aws/aws-sdk-cpp#1707]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
A build failure. Fuller notes below.

[ 92%] Linking CXX executable aws-cpp-sdk-core-tests
./aws-cpp-sdk-core-tests: symbol lookup error: ./aws-cpp-sdk-core-tests: undefined symbol: _ZN3Aws6Client9AWSClient20SetServiceClientNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/build.make:1300: recipe for target 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests' failed
make[2]: *** [aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 127
make[2]: *** Deleting file 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests'
CMakeFiles/Makefile2:1252: recipe for target 'aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all' failed
make[1]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**SDK version number**
Master branch as of July 7, 2021

**Platform/OS/Hardware/Device**
Inside a docker container with Ubuntu 18.04 LTS.

**To Reproduce (observed behavior)**
git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp.git
cd aws-sdk-cpp/
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="ecr;s3"
make

This gets 92% done and then produces the dump listed earlier.

**Expected behavior**
A clean build.

Let me know if you need a docker container to work from.

**Comment by KaibaLopez** [comment]
@jplflyer ,
First and just in case this is blocking you, add `-DENABLE_TESTING=OFF` to your cmake command so it doesn't run the tests.

Do you know which test specifically is failing? And just to verify this is what I think it is, does it succeed after you run the make command a couple times?

**Comment by jplflyer** [comment]
@KaibaLopez Thanks for the reply.

Repeated makes produce the same error. I've tried going back to previous versions with something like:

     git checkout 1.9.40

I tried several parts and got the same error. If I go back to 1.9.1, I got a different build error. When I went to 1.8.186, I got yet another build error.

    Linking CXX executable aws-cpp-sdk-core-tests
    ./aws-cpp-sdk-core-tests: symbol lookup error: ./aws-cpp-sdk-core-tests: undefined symbol: 

However, the -DENABLE_TESTING=OFF you recommended got me a clean build.

I'm not sure which test is causing it -- I've included the build failure way at the top. I'm happy to use that as a workaround.

**Comment by KaibaLopez** [comment]
Ok, so if you are happy with the workaround feel free to close the issue, since it's going to be hard for me to pinpoint what is going on without knowing which test case is failing it would be a bunch of shooting in the dark for me so yea...
If you want to give it a few more tries to find the problem, can I ask which version of gcc/g++ and cmake are you using? 
Also, try using 'sudo make', the tests do try to create files and read folders that might need admin permissions.

**Comment by jplflyer** [comment]
It's a build problem, not a run problem.

I'll make a Dockerfile that hits the error. That's what I did last time I had build problems with the SDK.

**Comment by KaibaLopez** [comment]
yea that works

**Comment by jplflyer** [comment]
Okay, I managed to dig further and make a docker container that highlights the problem. See this:

https://github.com/jplflyer/FailingAWS.git

The reason it took time was that the build succeeds under Ubuntu 18.04 and fails under 20.04 (which uses a newer version of GCC.

There's a README.md with directions on how to make the build fail.
