### ISSUE TITLE
Kinesis video stream - GetMedia example

### ISSUE THREAD

**Issue by gellerilan** [aws/aws-sdk-cpp#1708]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Ubuntu 18.04
**Describe the question**
Hello,
We are trying to build a steam parser/consumer using the aws-sdk-cpp, and can't make the code working. The best that I've managed is to actually call GetMedia without exceptions, but the code just wait endlessly on that call. The code finally stops after I close the from the producer (gstreamer) side.
Can you supply any working example of a stream parser in C++ for a reference?

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
@gellerilan ,
So we don't really have a sample ready and I don't think I have the bandwidth to come up with one... But, I could maybe give you pointers on errors you face along the way on your attempts. 
Could you show me your code?

**Comment by gellerilan** [comment]
Sure, I'll post it here as soon as I'll get back in the office.

**Comment by gellerilan** [comment]
Hi,

This is the main() method that I've come up with:
`int main()
{
    //The Aws::SDKOptions struct contains SDK configuration options.
    //An instance of Aws::SDKOptions is passed to the Aws::InitAPI and 
    //Aws::ShutdownAPI methods.  The same instance should be sent to both methods.
    SDKOptions options;
    options.loggingOptions.logLevel = Utils::Logging::LogLevel::Debug;
    
    //The AWS SDK for C++ must be initialized by calling Aws::InitAPI.
    InitAPI(options); 
    {
        KinesisVideo::KinesisVideoClient client;
        KinesisVideo::Model::GetDataEndpointRequest request;
        request.SetStreamARN("arn:aws:kinesisvideo:us-east-1:##accountid##:stream/##streamname###/1622222222222");
        request.SetAPIName(KinesisVideo::Model::APIName::GET_MEDIA);
        KinesisVideo::Model::GetDataEndpointOutcome res = client.GetDataEndpoint(request);

        cout << "result succesful: " << res.IsSuccess() << endl;
        
        KinesisVideoMedia::Model::GetMediaRequest getMediaRequest;
        getMediaRequest.SetStreamARN("arn:aws:kinesisvideo:us-east-1:##accountid##:stream/##streamname###/1622222222222");
        KinesisVideoMedia::Model::StartSelector selector;
        selector.WithStartSelectorType(KinesisVideoMedia::Model::StartSelectorType::NOW);
        getMediaRequest.SetStartSelector(selector);
        KinesisVideoMedia::KinesisVideoMediaClient videoMediaClient;
        Aws::String endpoint = res.GetResult().GetDataEndpoint();
        videoMediaClient.OverrideEndpoint(endpoint);
        videoMediaClient.EnableRequestProcessing();
        KinesisVideoMedia::Model::GetMediaOutcome media = videoMediaClient.GetMedia(getMediaRequest);
        
        cout << "GetMedia succesful: " << media.IsSuccess() << endl;
    }

    //Before the application terminates, the SDK must be shut down. 
    ShutdownAPI(options);
    return 0;
}
`

I can't figure out how to access the media from any of the examples. 
Also, the GetMedia call keeps running until I stop the stream in the producer.

**Comment by KaibaLopez** [comment]
Hi @gellerilan ,
Ok I was able to setup the kinesis video producer and stream and use your sample, with no real problem. So, regarding your questions:
>I can't figure out how to access the media from any of the examples.

Not sure what you mean here, kind of sounds like the call was a failure but the second question makes me think otherwise....
>Also, the GetMedia call keeps running until I stop the stream in the producer.

Yea this is expected, the payload is a sequence of chunks from the specified stream. While you could send media _offline_ it seems like you are using the producer to send a live stream, so get media will continue to get these chunks until the stream ends or it is somehow interrupted, see [here for more info](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_dataplane_GetMedia.html)

**Comment by gellerilan** [comment]
Hi @KaibaLopez ,

Thanks, but I'm still missing something. How do I consume the stream data? I don't see any documentation of a hock or an interface to get the stream.
In java there is something like _StreamingMkvParser_, but I don't see anything similar for C++.

**Comment by KaibaLopez** [comment]
yea... ok I'll try looking into making a sample for that.

**Comment by zhordev** [comment]
I have an issue with parsing data obtained from GetMedia.GetPayload(). How should I parse MKV data? Is there anything like StreamingMkvReader for C++?
