### ISSUE TITLE
Lambda Lockup on calling Dynamo

### ISSUE THREAD

**Issue by Lovett1991** [aws/aws-sdk-cpp#1709]
Confirm by changing [ ] to [x] below:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
aws-lambda

**Describe the question**
When creating a lambda to scan dynamodb the lambda times out. I've got a sample project here: https://github.com/Lovett1991/aws-cpp-lambda/tree/aws-cpp-sdk-timeout

The project can build fine, but when called the code locks up on the following line:
```
const Aws::DynamoDB::Model::ScanOutcome &scanResult = client.Scan(scanRequest); // Time out here
```

In the sample app I've included a vagrantfile to show how the environment is set up. But here's the commands I've run:

```
    apt-get update
    # apt-get install -y git gcc g++ cmake libcurl4-openssl-dev zlib1g zlib1g-dev libssl-dev zip
    apt-get install -y git gcc g++ cmake libcurl4-openssl-dev libssl-dev uuid-dev zlib1g-dev libpulse-dev zip

    cd /usr/src
    git clone https://github.com/awslabs/aws-lambda-cpp.git
    mkdir aws-lambda-cpp/build
    cd aws-lambda-cpp/build
    cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
    make && sudo make install
    
    cd /usr/src
    git clone --branch 1.7.364 --recurse-submodules https://github.com/aws/aws-sdk-cpp.git
    mkdir aws-sdk-cpp/build
    cd aws-sdk-cpp/build
    cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_ONLY="dynamodb" -DENABLE_TESTING=OFF
    make && sudo make install
    
    cd /usr/src
    git clone https://github.com/open-source-parsers/jsoncpp.git
    mkdir jsoncpp/build
    cd jsoncpp/build
    cmake .. -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF
    make && sudo make install
```

Have I missed something out from setting up the sdk?

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
Hi @Lovett1991 ,
> Have I missed something out from setting up the sdk?

I don't think so, your set up looks fine to me.
The timeout error could be a number of things though... If the timeout is happening directly on the Scan call, you could try playing with the client config's request timeout value? It would only help if the problem is that the request is actually taking a long time and it's not stuck in some sort of loop, but it's a starting point.
Also, could you show me the trace logs? There might be more info there, only make sure to first remove any mention of credentials and such.

**Comment by Lovett1991** [comment]
It's odd because I don't get any trace logs I just get the cout statements I've put in.


|timestamp|message|
|---|---|
|1626082192073 | START RequestId: fd926558-3754-4e3f-a77a-a78818457336 Version: $LATEST|
|1626082192105 | about to scan|
|1626082202085 | END RequestId: fd926558-3754-4e3f-a77a-a78818457336|
|1626082202085 | REPORT RequestId: fd926558-3754-4e3f-a77a-a78818457336Duration: 10010.52 msBilled Duration: 10198 msMemory Size: 128 MBMax Memory Used: 52 MBInit Duration: 186.94 ms|
|1626082202085 | 2021-07-12T09:30:02.084Z fd926558-3754-4e3f-a77a-a78818457336 Task timed out after 10.01 seconds|

**Comment by KaibaLopez** [comment]
Hmm I haven't been able to reproduce this so far but something I noticed, is there a reason why you are using version 1.7 ?
Also, could you try running the call locally, as in not by lambda, I want to know if it is related to the lambda-runtime or the cpp SDK, plus that way you'll for sure get the logs if it is on the SDK side.

**Comment by Lovett1991** [comment]
Ok I created a new branch so the code would run locally [here](https://github.com/Lovett1991/aws-cpp-lambda/blob/runLocal/src/main.cpp).

This did run as expected, although I didn't get any trace logs from the sdk. I don't understand why this doesn't work as a lambda :/ Have you been able to successfully run the code as a lambda then?

**Comment by Lovett1991** [comment]
Ah thought I'd add to answer your question about why 1.7; When I originally wrote the code (about a year ago) on an install of ubuntu this worked as a lambda, and the version I had then was 1.7.364, I'm now trying to build this and I figured I'd use the same version of the library to eliminate any differences, I originally just pulled the latest version but thought I'd pin it to the same version I was using when originally developed to see if that's where the problem was.

**Comment by KaibaLopez** [comment]
Hi @Lovett1991 ,
Sorry for the radio silence there, finally was able to reproduce and run your code
I just increased the timeout limit though (In my case 2 minutes was enough), does that work for you? 
In case you are not sure how to you can either do it from the console or the [update-function-configuration](https://docs.aws.amazon.com/cli/latest/reference/lambda/update-function-configuration.html) command on the aws cli:
```
aws lambda update-function-configuration --function-name demo-db --timeout 120 
```
