### ISSUE TITLE
Unable to connect to endpoint

### ISSUE THREAD

**Issue by shuzhang1989** [aws/aws-sdk-cpp#171]
hi, 

I am using S3Client to GetObject() from S3 but I randomly get "Unable to connect to endpoint" exception. I wonder if there is a way to investigate this? The ClientConfiguration is using default values.

**Comment by wroluk** [comment]
Hi, I have the same problem. Additionally the data received callback shows that it is downloading 2-3 times more than the actual file size. Like you said it happens randomly - sometimes the download works.
Could you tell me how you solved the problem?

**Comment by shuzhang1989** [comment]
@wroluk sure, I set the timeout to be 60 seconds and looks the issue is gone

**Comment by wroluk** [comment]
Unfortunately this does not work for me.
