### ISSUE TITLE
How can I respond to the PASSWORD_VERIFIER challenge?

### ISSUE THREAD

**Issue by wukakuki** [aws/aws-sdk-cpp#1715]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Linux

**Describe the question**
How can I respond to the PASSWORD_VERIFIER challenge? 
I use initial Auth from cognito idp with USER_SRP_AUTH to log in users. and initial Auth replies with PASSWORD_VERIFIER Challenge. I can't find any doc about the PASSWORD_VERIFIER challenge. (I can only find DEVICE_PASSWORD_VERIFIER)
Thanks

**Logs/output**
nullptr

**Comment by KaibaLopez** [comment]
@wukakuki ,
I'm going to need to see a small code snippet that reproduces this, and the logs generated (remember to sanitize those before uploading them).
