### ISSUE TITLE
AWS CPP SDK will not build 

### ISSUE THREAD

**Issue by MarkhailAW** [aws/aws-sdk-cpp#1717]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?

Windows 10

**Describe the question**

The build of the AWS SDK as described in the doc fails repetitively.   

I attempt to use

.\vcpkg\vcpkg install "aws-sdk-cpp[*]":x64-windows --recurse

it also fails with the same error when using

.\vcpkg\vcpkg install "aws-sdk-cpp[*]" --recurse

The reputed error is 

CMake Error at cmake/sdks.cmake:147 (message):
  applicationcostprofiler is required for build, but
  aws-cpp-sdk-applicationcostprofiler directory is missing!
Call Stack (most recent call first):
  CMakeLists.txt:253 (include)

I installed and pathed CMake 3.21 as the same error occurred with 3.20.2  .

**Logs/output**

attached

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
[build_attempt_for_aws_cpp_sdk.txt](https://github.com/aws/aws-sdk-cpp/files/6855808/build_attempt_for_aws_cpp_sdk.txt)

**Comment by KaibaLopez** [comment]
@MarkhailAW ,
So first... yea what's happening here is that vcpkg is installing only up to version 1.8.126, which did not have the `application cost profiler` service, so when it tries to find it, it isn't there. Updating the version vcpkg uses is a bit of a problem at the moment so I can't promise it changing any time soon.
Having said that there are a few things you can do here:
1. specify the services you are planning to use by adding them to the install command (assuming you are not planning on using the application cost profiler ), for example:
```
.\vcpkg\vcpkg install "aws-sdk-cpp[s3,dynamodb,lambda,ec2]" --recurse
```
2. You could build from source, it is our recommended way and the one we have more control over so we can support you better with errors that happen this way.

**Comment by MarkhailAW** [comment]
YES !   (and no, but that's later...)

This worked :
.\vcpkg\vcpkg install "aws-sdk-cpp[s3,dynamodb,lambda,ec2,rds,rds-data]"
--recurse

Thanks!  Now I can go get into other trouble by trying to make my code
work..... <g>

As for the build from source...there is no joy there.  I guess this is
another incident, but the ugly short details are:

cmake c:\aws-sdk-cpp-main -G "Visual Studio 16 2019"
-DCMAKE_BUILD_TYPE=Release
....
CMake Error at CMakeLists.txt:179 (include):
  include could not find requested file:

    AwsFindPackage


CMake Error at CMakeLists.txt:191 (add_subdirectory):
  The source directory

    C:/aws-sdk-cpp-main/crt/aws-crt-cpp

  does not contain a CMakeLists.txt file.


-- Add s3-crt:s3 to C2J_SPECIAL_NAME_LIST
-- Updating version info to 1.9.64
-- Custom memory management disabled
CMake Error at aws-cpp-sdk-core/CMakeLists.txt:504 (aws_use_package):
  Unknown CMake command "aws_use_package".

**Comment by KaibaLopez** [comment]
Cool and good luck!

About the source build though, It looks like you didn't include the sub-modules when cloning , try running these on the repo source folder: 
```
git pull origin main
git submodule update --init --recursive
```

**Comment by MarkhailAW** [comment]
Thanks, I'll check it out later this evening.

One last little thing.... Is there a reputable writeup for once I get this
compiled, how to get it all to link ?   I can RTFM but it seems like there
are a maze of twisty little passages, all different when it comes to doing
this successfully.   LNK-2001 is a swear word right now.

**Comment by KaibaLopez** [comment]
I mean kind of, depends on what you are planning on using to linking, we do have a sort of guide/sample [here](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/build-vcpkg.html) for using cmake.
For Visual Studio it gets a little weird, we don't have a guide on how to link but the short version is :
* Build the SDK (take note of the build type like, debug or release).
* Create your project and do the usual: Properties ->C/C++->General-> Additional Include libraries & Properties ->Linker->General->Additional library directories & Properties->Linker->Input->Additional Dependencies,
* Move dlls to the directory the executable is in, usually the Debug or Release folder.
* Make sure your project is building in the same type you build the SDK. I think defaults are flipped for cmake and visual studio.
