### ISSUE TITLE
AWS S3 CRT client configuration features

### ISSUE THREAD

**Issue by lordgamez** [aws/aws-sdk-cpp#1721]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Ubuntu 20.04

**Describe the question**
I currently upgraded the AWS SDK to version 1.9.65 version and I was considering using the new S3 CRT client instead of the old S3 client. I managed to upgrade most of the codebase, but I encountered a problem with the `Aws::S3Crt::ClientConfiguration` class. Previously I was using the `connectTimeoutMs` and the proxy fields of the `Aws::Client::ClientConfiguration` class which seem to be currently unavailable in the `Aws::S3Crt::ClientConfiguration` class. Are these features planned to be implemented later or is there another way to set these parameters in the S3 CRT client?

**Logs/output**
N/A

**Comment by KaibaLopez** [comment]
Hi @lordgamez ,
The plan is to eventually add those but no, they are not available at the moment and we don't have a set date either.

**Comment by lordgamez** [comment]
> Hi @lordgamez ,
> The plan is to eventually add those but no, they are not available at the moment and we don't have a set date either.

Thanks for the information!
