### ISSUE TITLE
Cancelling Downloads Initiated By TransferManager::DownloadToDirectory

### ISSUE THREAD

**Issue by MissingAFew** [aws/aws-sdk-cpp#1727]
### Discussed in https://github.com/aws/aws-sdk-cpp/discussions/1726

<div type='discussions-op-text'>

<sup>Originally posted by **MissingAFew** August  3, 2021</sup>
Direct quote from comments of the TransferManager class:

> The key interface for controlling and knowing the status of your upload is the TransferHandle. An instance of TransferHandle is returned from each of the public functions in this interface.

However, DownloadToDirectory function does not return a TransferHandle, which is needed to Cancel downloads.  In the comments for this function, it states:

> You will receive notifications that a download has started via the transferInitiatedCallback callback function in your configuration. If you do not set this callback, then you will not be able to handle the file transfers.

That's great, I can get TransferHandle via callbacks... however, the callback's TransferHandle is pointing to a const, and the Cancel function isn't const, so I can't Cancel the download from the callback.

Maybe Im missing an alternative way to Cancel the download, but I can't find it.</div>

**Comment by KaibaLopez** [comment]
Hi @MissingAFew ,
Hmmm.. I think I am misunderstanding your problem...
Could you maybe show me a code sample on what you're trying to do? It'll make things a lot easier for me to figure out for me.

On a side note, just in case this saves us time, you can look into the `aws-cpp-sdk-transfer-tests\TransferTests.cpp` for examples on how to use the transferHandle callbacks. There is no "cancel download" test in those, but it'll give you more info on how the transfermanager expects the callbacks to be set.

**Comment by MissingAFew** [comment]
For example with:

`CurrentTransferHandle = S3TransferManager->DownloadFile(BucketNameStr, S3FilePathStr, DownloadFilePathStr) // Returns Handle, I can now Cancel();
CurrentTransferHandle->Cancel();
S3TransferManager->DownloadToDirectory(S3DownloadPath, S3BucketName);  // Returns void, can't use Handle`

Like we both mentioned, we have the callbacks. That's fine. But they all have the function signature as follows:

`TransferInitiated(const Aws::Transfer::TransferManager* TransferManager, const std::shared_ptr<const Aws::Transfer::TransferHandle>& TransferHandle)`

Notice the TransferHandle is const. The callback is called, and I have the transfer handle, but the function Cancel() is not const so I can't call it. Here's the function declaration of Cancel.

`void Cancel();`

My question is, how do I Cancel a download when I call DownloadToDirectory, considering it doesnt return a Handle and every callback returns a const, which makes it impossible to call the non-const Cancel function?

**Comment by MissingAFew** [comment]
Any updates on this? I don't really see the purpose of DownloadToDirectory as a utility function if we have absolutely no way to manage what is being downloaded. Is there some roundabout way to deal with the downloads that are occurring? Pausing, cancelling, etc.?

**Comment by KaibaLopez** [comment]
Sorry, kind of all over the place this week, but anyways the short answer is yes, the way is to const cast the handle, like :
```cpp
    Aws::Vector<std::shared_ptr<TransferHandle>> directoryDownloads;
    std::condition_variable directoryDownloadSignal;
    auto transferInitCallback = [&](const TransferManager*, const std::shared_ptr<const TransferHandle>& handle){
        if(handle->GetTransferDirection() == TransferDirection::DOWNLOAD)
        {
            directoryDownloads.push_back(std::const_pointer_cast<TransferHandle>(handle));
            directoryDownloadSignal.notify_one();
        }
    };
    config.transferInitiatedCallback = transferInitCallback;
```
Then you can just do something like:
```cpp
    auto transfer_manager = TransferManager::Create(config);
    transfer_manager->DownloadToDirectory("absolute/path/to/folder","bucketname","prefix"); 
    {
        std::unique_lock<std::mutex> locker(semaphoreLock);
        directoryDownloadSignal.wait(locker);
    }
    for (auto handle : directoryDownloads)
    {
        handle->Cancel(); 
        handle->WaitUntilFinished(); 
    }
```
Now, if you want an answer on the why is it this way.... That's harder to answer, I think it was responded some time back in another issue.... but let me know, I wasn't there so it'll take a while to ask around.

**Comment by MissingAFew** [comment]
Great! Thank you, I believe this answers my question.
