### ISSUE TITLE
TransferManager::DoSinglePartDownload() should flush the stream before marking the transfer completed

### ISSUE THREAD

**Issue by igorcanadi** [aws/aws-sdk-cpp#1732]
`TransferManager::DoSinglePartDownload()` marks the transfer as completed here: https://github.com/rockset/rocksdb-cloud/blob/8c0ff476d77c0df0af92b1466269404bdfb8e89e/cloud/aws/aws_s3.cc#L196

This happens before the underlying response stream is flushed. The response stream's ownership is tied to local variable `getObjectOutcome` and the stream is flushed only in `getObjectOutcome`'s destructor when it out of scope (here: https://github.com/aws/aws-sdk-cpp/blob/5543842bdd1bd0a318295a6f2247909883054b0e/aws-cpp-sdk-core/source/utils/stream/ResponseStream.cpp#L61).

This means that a code that uses `std::fstream` to download S3 object to a local file and does:
```
handle->WaitUntilFinished();
// do something with the file
```
is incorrect, because the file might not be flushed when `WaitUntilFinished()` returns.

This is similar to this 6 year old bug: https://github.com/aws/aws-sdk-cpp/issues/58

**Comment by KaibaLopez** [comment]
Hi @igorcanadi ,
Yea thanks for bringing attention to this,and you're right, this is an ongoing issue with the SDK, I'll try to make it a priority for the team.

**Comment by igorcanadi** [comment]
Hi @KaibaLopez any news on this issue? Thanks!

**Comment by SergeyRyabinin** [comment]
Hi,
I think it should be fixed now by https://github.com/aws/aws-sdk-cpp/pull/2351
At least a flush() is called before a task completion notification.
Closing the issue, please submit a new one or re-open should you see more issues.

Best regards,
Sergey
