### ISSUE TITLE
Error while installing the sdk

### ISSUE THREAD

**Issue by MohammadArik** [aws/aws-sdk-cpp#1733]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I was installing aws-sdk for c++ in kubuntu 21.04(ubuntu 21.04 with kde plasma). After running 
`cmake -DBUILD_ONLY="sesv2" -DCMAKE_BUILD_TYPE=Debug  ..`
I got the following error just before the `make` command ends,
```
[100%] Linking CXX executable aws-cpp-sdk-core-tests
/usr/bin/ld: ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `curl_easy_reset'
/usr/bin/ld: ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `curl_slist_append'
/usr/bin/ld: ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `curl_easy_perform'
/usr/bin/ld: ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `curl_easy_init'
/usr/bin/ld: ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `curl_global_init'
/usr/bin/ld: ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `curl_easy_cleanup'
/usr/bin/ld: ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `curl_global_cleanup'
/usr/bin/ld: ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `curl_easy_pause'
/usr/bin/ld: ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `curl_easy_setopt'
/usr/bin/ld: ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `curl_easy_getinfo'
/usr/bin/ld: ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `curl_slist_free_all'
/usr/bin/ld: ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `curl_version_info'
/usr/bin/ld: ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `curl_easy_strerror'
collect2: error: ld returned 1 exit status
make[2]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/build.make:864: aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 1
make[1]: *** [CMakeFiles/Makefile2:912: aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**SDK version number**
The latest one rolling now..

**Platform/OS/Hardware/Device**
What are you running the sdk on?
I am running it in Kubuntu 21.04 with intel-i5 1035g1 and 16gb ram.

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
```
git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp
cd ./aws-sdk-cpp
mkdir build; cd build
cmake -DBUILD_ONLY="sesv2" -DCMAKE_BUILD_TYPE=Debug  ..
make
```

**Expected behavior**
I wanted it to be installed successfully.

**Logs/output**
If applicable, add logs or error output.
Given above...

**Comment by KaibaLopez** [comment]
Hi @MohammadArik,
I just ran this on Ubuntu 21.04 and didn't have any issues, could you give me more info on your enviroment? Did you get all the dependencies installed?
` zlib1g-dev libssl-dev libcurl4-openssl-dev`
Also, what gcc and cmake versions are you using?

**Comment by MohammadArik** [comment]
Yeah I have them installed.. Ok let me try in a virtual machine. But I wanted it on my regular machine...

**Comment by MohammadArik** [comment]
Yeah it worked on my ubuntu server too. Maybe there is an issue in my main machine. Any suggestions???
