### ISSUE TITLE
Build failure: Error in `./aws-cpp-sdk-core-tests': free(): invalid next size (fast)

### ISSUE THREAD

**Issue by DennisHeimbigner** [aws/aws-sdk-cpp#1736]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

Failure during build:

aws-s3-sdk: branch version1.9
[afail.txt](https://github.com/aws/aws-sdk-cpp/files/6984962/afail.txt)

os: linux ubuntu 16
gcc: 5.4.0
openssl: version 1.0.2g
libcurl: 7.47.0
cmake version: 3.15.3

CMAKE flags: -DBUILD_ONLY=s3

During the tests, a failure occurs:
````
[ RUN      ] AWSClientTestSuite.TestClockChangesAfterSkewHasBeenSet
*** [afail.zip](https://github.com/aws/aws-sdk-cpp/files/6984980/afail.zip): 0x0000000000e91630 ***
````
Complete cmake output attached.

**Comment by KaibaLopez** [comment]
Hi @DennisHeimbigner ,
Hmmm, I'll try to reproduce this but it's a bit slow for me to set up an enviroment with these specific versions.
Is there a chance for you to update to at least openssl 1.1+ ? 
On the mean time you might want to add `-DENABLE_TESTING=OFF` to your cmake command, to skip these.

**Comment by DennisHeimbigner** [comment]
This problem also shows up when I use the library. So ignoring the tests
will not help.
I will see if I can install a later version of openssl.

**Comment by DennisHeimbigner** [comment]
Switched to openssl 1.1.1 stable and problem is still the same.

**Comment by DennisHeimbigner** [comment]
Can you tell me the versions of various subsidiary libraries that you use?
I had hoped to get it from you github actions, but I see they are private.

**Comment by KaibaLopez** [comment]
Sorry @DennisHeimbigner , I just can't seem to reproduce your error, I just tried the versions you specified and the SDK builds for me. Is there anything else you can think that's special about your set up that might help me reproduce this?

**Comment by DennisHeimbigner** [comment]
Clearly something is different. But I do not know what.
I was told that conda had an install that worked, so I am experimenting with that.
Thanks.
