### ISSUE TITLE
Presigning Request URLs is not Generating Valid Requests

### ISSUE THREAD

**Issue by ahmedyarub** [aws/aws-sdk-cpp#1737]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Presigning a URL to submit requests to the Kubernetes clusters returns access denied. Using tokens generated either by aws eks get-token or a script like this https://github.com/kubernetes-sigs/aws-iam-authenticator work perfectly. The tokens look very similar but the one I generated are not accepted.

**SDK version number**
1.8.126 from VCPKG
**Platform/OS/Hardware/Device**
Windows 64bit with the latest preview of Visual Studio 2019

What are you running the sdk on?

**To Reproduce (observed behavior)**
Sample code:
QList<PodInfo> getEksPods() {
    Aws::Client::ClientConfiguration client_config;

    client_config.region = "us-west-2";
    client_config.verifySSL = false;

    Aws::STS::STSClient stsClient(AuthUtils::getCredentialsProvider("STSClient"), client_config);

    Aws::Http::URI uri("https://sts.us-west-2.amazonaws.com/");
    uri.AddQueryStringParameter("Action", "GetCallerIdentity");
    uri.AddQueryStringParameter("Version", "2011-06-15");

    Aws::Http::HeaderValueCollection headers;
    headers.insert(Aws::Http::HeaderValuePair("x-k8s-aws-id", "something"));

    auto presignedUrl = stsClient.GeneratePresignedUrl(uri, Aws::Http::HttpMethod::HTTP_GET, "us-west-2", headers, 60);

    qDebug() << presignedUrl.c_str();

    std::string token("k8s-aws-v1." +
                      Aws::Utils::HashingUtils::Base64Encode(
                              Aws::Utils::ByteBuffer((unsigned char *) presignedUrl.c_str(), presignedUrl.length())));

    std::replace(token.begin(), token.end(), '=', '\0');

    return getPods(token.c_str());
}

**Expected behavior**
Token accepted.

**Logs/output**
Kubernetes returns Unauthorized

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**
I can provide samples of the tokens but not publicly

**Comment by ahmedyarub** [comment]
OK so the problem was that the presigned URL does not have a slash after the host name!! I fixed it like this:
`presignedUrl.insert(presignedUrl.find('?'),"/");`

**Comment by KaibaLopez** [comment]
Hi @ahmedyarub ,
Thanks for pointing this out to us but here's the problem.... vcpkg is not really supported at this time, and what I mean is that we are not currently updating the SDK version in it... It is something we are working on but not available at the moment.
For now I suggest you either continue with your workaround or that you install the SDK from source, and see if the problem persists on the newest version.

**Comment by ahmedalnuaimi** [comment]
I have just tested by building the latest main branch commit and still has the same problem

**Comment by ahmedyarub** [comment]
I have just tested by building the latest main branch commit and still has the same problem

**Comment by KaibaLopez** [comment]
Ok, I think I can reproduce your problem but just for curiosity's sake, is there any reason why you're not using `ConvertRequestToPresignedUrl`? Or do you get the same result if you try this for example:
```cpp
Aws::STS::Model::GetCallerIdentityRequest request;
auto presignedURL = stsClient.ConvertRequestToPresignedUrl(request,"us-west-2");
```

**Comment by ahmedyarub** [comment]
> ```c++
> ConvertRequestToPresignedUrl
> ```

Looking at the code, it doesn't seem that it serializes the headers, right?
https://github.com/aws/aws-sdk-cpp/blob/b24dc7bcf286078083bad68f7a13f27457fb0073/aws-cpp-sdk-sts/source/STSClient.cpp#L106
