### ISSUE TITLE
Does StartConversationRequest (Lex v2) for C++ even work?

### ISSUE THREAD

**Issue by TelephonyMan** [aws/aws-sdk-cpp#1746]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Windows 10 64-bit (on my home PC)

I can connect to Lex V1 bot using Aws::LexRuntimeService::Model::PostContentRequest from the same PC using the same credentials. I can also connect to Lex V2 bot using AWS CLI (aws lexv2-runtime recognize-text) same credentials. So there is no permission issue. But StartConversationRequest using C++ doesn't work.

I have already posted this question on AWS forum and stackoverflow. There isn't a single sample/example anywhere on Internet on how StartConversationRequest is supposed to work in C++. 

I have also logged this as a ticket under AWS Business Support Plan. They are simply pointing me to links I have already googled myself.

Let me just point to the [stackoverflow question](https://stackoverflow.com/questions/68853083/using-aws-lex-v2-streaming-with-c-signature-does-not-match) instead of repeating it all over again.

**Comment by TelephonyMan** [comment]
Well, turns out it had nothing do with my code. I forced use of CURL instead of WinHTTP/WinINet, problem was solved. Turns out WinHTTP/WinINet doesn't have Http/2 multiplexing support.

Can this be documented somewhere? DON'T USE streaming lex/transcribe with WinHTTP or WinINet. Use CURL.

**Comment by KaibaLopez** [comment]
oh, thanks for clearing it out, and yea I'll see about where to document this.
