### ISSUE TITLE
StartStreamTranscription fails with "A complete signal was sent without the preceding empty frame"

### ISSUE THREAD

**Issue by bsbontchev** [aws/aws-sdk-cpp#1747]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
Related to "Websocket support for Transcribe #1599" issue.  

**Describe the bug**
Using your test example (aws-sdk-cpp-1.9.82\aws-cpp-sdk-transcribestreaming-integration-tests\TranscribeTests.cpp) as a base when executed fails with an exception "A complete signal was sent without the preceding empty frame".

**SDK version number**
aws-sdk-cpp-1.9.82

**Platform/OS/Hardware/Device**
CentOS 7.0, curl 7.29.0, OpenSSL 1.0.2k-fips  26 Jan 2017

**To Reproduce (observed behavior)**
Unzip 
[aws_sdk_transcribe_stream.zip](https://github.com/aws/aws-sdk-cpp/files/7383209/aws_sdk_transcribe_stream.zip)
Run "make clean; make"
Run "build/test "your_aws_key_id" "your_aws_key" "your_codec_linear_rate_8_size_16.pcm"

**Expected behavior**
Receive the transcription event

**Logs/output**
[aws_sdk_2021-08-20-17.log](https://github.com/aws/aws-sdk-cpp/files/7023341/aws_sdk_2021-08-20-17.log)

**Comment by KaibaLopez** [comment]
Hi @bsbontchev ,
This error seems to have been caused by a problem on the Service, it has recently been fixed though, would you mind retrying and telling me if you are still seeing the issue?

**Comment by bsbontchev** [comment]
Yes, it is still there.
The provided aws_sdk_transcribe_stream.zip has all it is necessary to reproduce the issue.

**Comment by bsbontchev** [comment]
The service is still not working. Is anybody looking into this issue?
Today tests results;
arg_initialize() result: 1
sdk_initialize()
transcribe_stream_initiailaize() result: 1
request_initiailaize >>
OnStreamReady >>
handler.SetOnErrorCallback >>
handler.SetOnErrorCallback error: HTTP response code: -1
Resolved remote host IP address:
Request ID:
Exception name: BadRequestException
Error message: A complete signal was sent without the preceding empty frame.
0 response headers:
handler.SetOnErrorCallback <<
handler.SetOnErrorCallback >>
handler.SetOnErrorCallback error: HTTP response code: -1
Resolved remote host IP address:
Request ID:
Exception name: BadRequestException
Error message: A complete signal was sent without the preceding empty frame.
0 response headers:

[aws_sdk_2021-09-07-13.log](https://github.com/aws/aws-sdk-cpp/files/7122367/aws_sdk_2021-09-07-13.log)

**Comment by floswitch** [comment]
I'm facing the same issue.  I even went so far as to make a custom HttpClientFactory to make 100% certain the HTTP/2 option was set on the CURL* handle, to no avail.  The connection keeps ending with the BadRequestException: A complete signal was sent without the preceding empty frame.

**Comment by floswitch** [comment]
Oddly, the windows version generated actual partial / final transcribe results at the end of the audio stream, though that was two weeks ago, and that was using WININET  on Windows.  I suspected HTTP/2 was the culprit, so spent the time converting it to use CURL.  It using CURL, but now I get a series of " A complete signal was sent without the preceding empty frame." followed by a reconnection attempt.

**Comment by blundercode** [comment]
Was able to resolve this issue with using a specific version of curl.

After playing around with different curl versions I was able to get it to work fine.
