### ISSUE TITLE
With WinHttp make the send timeout configurable

### ISSUE THREAD

**Issue by sbailey476** [aws/aws-sdk-cpp#1749]
**Describe the bug**
When communicating with a S3 compatible storage location with the AWS SDK we have observed a issue whereby when sending the data neither side has timed out when the data transfer is going extremely slow (8MB in one hour and 43 minutes) other requests running parallel went really quick so it's probably a networking issue causing the slow connection. The client side AWS SDK didn't timeout because the AWS SDK sets the send timeout to be -1 or infinite in the WinHttpSyncHttpClient. 

`if (!WinHttpSetTimeouts(GetOpenHandle(), config.connectTimeoutMs, config.connectTimeoutMs, -1, config.requestTimeoutMs))`

**SDK version number**
1.6.25

**Platform/OS/Hardware/Device**
Windows 10

**Expected behavior**
It would be useful if the send timeout could be configured via the client configuration the default can continue to be infinite however clients would be able to change the timeout if they require.

**Comment by KaibaLopez** [comment]
Hi @sbailey476 ,
Hmmm, I can see what you mean but I'm not sure if I consider this a bug, more like a feature request right?

**Comment by sbailey476** [comment]
Yeh I can see this is more of a new feature to the SDK rather than a bug
