### ISSUE TITLE
Cant find any examples with aws-sdk-cpp and DynamoDb

### ISSUE THREAD

**Issue by manafGadgeon** [aws/aws-sdk-cpp#175]
iam new in C language. i need to communicate with DynamoDb using c++. i dowloaded the aws-sdk-cpp codebase from git. and successfully maked and installed. but what is next?. i can't find any examples with c++ and dynamoDb(i need to create a table, put items to table, and fetch data from table).

**Comment by JonathanHenson** [comment]
Have you read the Readme.md file or looked at aws-cpp-sdk-dynamodb-integration-tests?

**Comment by JonathanHenson** [comment]
we you able to find the samples you needed? Closing for lack of correspondence. Please reopen if you need more information.
