### ISSUE TITLE
InitAPI not being run?

### ISSUE THREAD

**Issue by HavenRemix** [aws/aws-sdk-cpp#1756]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?

Windows 10

**Describe the question**

I think InitAPI is not being called. Basically, any Aws related call after InitAPI results in an Access Violation.

This is the code:

```
Aws::InitAPI(options);

Aws::Utils::Logging::InitializeAWSLogging(Aws::MakeShared<Aws::Utils::Logging::DefaultLogSystem>("AwsLogTemp", Aws::Utils::Logging::LogLevel::Trace, "aws_sdk_"));
Aws::Utils::Logging::LogSystemInterface* LogSystem = Aws::Utils::Logging::GetLogSystem();

Aws::Client::ClientConfiguration clientConfiguration;
clientConfiguration.region = "us-west-2";
```

**Logs/output**
If applicable, add logs or error output.

```
Exception thrown at 0x00007FFB246EC8BD (aws-cpp-sdk-core.dll) in main-launcher.exe: 0xC0000005: Access violation reading location 0x0000000100000000.
Unhandled exception at 0x00007FFB246EC8BD (aws-cpp-sdk-core.dll) in main-launcher.exe: 0xC0000005: Access violation reading location 0x0000000100000000.
```

Thats from the VS debugger output. No log file is being generated.

I also occasionally get this while building:

```
C:\Program Files (x86)\aws-cpp-sdk-all\include\aws\core\utils\stream\ResponseStream.h(61,13): warning C4275: non dll-interface class 'std::ios_base' used as base for dll-interface class 'std::basic_ios<char,std::char_traits<char>>'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30037\include\xiosbase(172): message : see declaration of 'std::ios_base'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30037\include\iosfwd(222): message : see declaration of 'std::basic_ios<char,std::char_traits<char>>'
```

**Comment by KaibaLopez** [comment]
hey, sorry I didn't get a chance to get to this but it seems you got it to work, could you share what you did to solve the problem?
