### ISSUE TITLE
Xml Parse Error XML_ERROR_MISMATCHED_ELEMENT

### ISSUE THREAD

**Issue by DoruBirtley** [aws/aws-sdk-cpp#1758]
Aws::InitAPI(m_options);
    Aws::Client::ClientConfiguration cfg;
    cfg.endpointOverride = "11.11.11.11:11111";  // S3服务器地址和端口
    cfg.scheme = Aws::Http::Scheme::HTTP;
    cfg.verifySSL = false;
    cfg.connectTimeoutMs = 30000;
    //Aws::Auth::AWSCredentials cred("XXXXXXXXXX", "XXXXXXXX");  // 认证的Key
    m_client = new S3Client(Aws::Auth::AWSCredentials("admin", "123456"), cfg, 
    Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Never, false);
    PutObjectRequest putObjectRequest;
    putObjectRequest.WithBucket(BucketName.c_str()).WithKey(objectKey.c_str());
    auto input_data = Aws::MakeShared<Aws::FStream>("PutObjectInputStream", pathkey.c_str(), std::ios_base::in | std::ios_base::binary);
    putObjectRequest.SetBody(input_data);
    auto putObjectResult = m_client->PutObject(putObjectRequest);
    if (putObjectResult.IsSuccess())
    {
        std::cout << "Done!" << std::endl;
        return true;
    }
    else
    {
        std::cout << "PutObject error: " <<
        putObjectResult.GetError().GetExceptionName() << " " <<
        putObjectResult.GetError().GetMessage() << std::endl;
        return false;
    }

result ：                  PutObject error: Xml Parse Error XML_ERROR_MISMATCHED_ELEMENT

What is this？  help please

**Comment by KaibaLopez** [comment]
Hi @DoruBirtley ,
I can't reproduce this as it is, could you tell me what version of the SDK, the operating system and the compiler you are using?

**Comment by DoruBirtley** [comment]
commit   b0204a7b6a33211f533a175e987a755f714bf7f3   

Linux ubuntu 5.4.0-1042-raspi

gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

**Comment by DoruBirtley** [comment]
@KaibaLopez

**Comment by KaibaLopez** [comment]
Sorry @DoruBirtley I was on a holiday, but I've tested this and am not seeing the same issue....
Can you upload the trace logs of the request? Remember to remove any credentials in them.

To have them generated add this to your code:
```cpp
    Aws::SDKOptions m_options;
    options.loggingOptions.logLevel = Utils::Logging::LogLevel::Trace;
    Aws::InitAPI(m_options);
```
Also, not the root cause of the issue but, the code you uploaded will have some memory errors because you are returning without calling `Aws::ShutdownAPI(m_options);` first. So make sure to fix that too.

**Comment by DoruBirtley** [comment]
[Uploading aws_sdk_2021-09-12-06.log…]()
The file is what what you need.

**Comment by KaibaLopez** [comment]
Hi @DoruBirtley ,
That is not a link to a log file... Could you upload the log file generated ?

**Comment by DoruBirtley** [comment]
[aws_sdk_2021-09-12-06.log](https://github.com/aws/aws-sdk-cpp/files/7192008/aws_sdk_2021-09-12-06.log)
