### ISSUE TITLE
ListObjectsRequest - fetch more results?

### ISSUE THREAD

**Issue by logidelic** [aws/aws-sdk-cpp#176]
I'm playing with the AWS C++ SDK and I have run into the following. You can list objects simply enough doing something like:

```
  ListObjectsRequest lst;
  lst.SetBucket("some_bucket");
  ListObjectsOutcome r = client->ListObjects(lst);
  //if(!r.IsSuccess()) ...
  for(const auto& obj: r.GetResult().GetContents()) {
    //...
  }
```

Great, this works, however the results are limited to (at most) 1000 objects. If there are more than 1000 objects in your bucket, you'll need to fetch again. I've previously used the Javascript AWS SDK and there is indeed a function to fetch more objects. I see the same in the Java SDK. However, I can't figure out how to do this in the C++ SDK.

How do you fetch more objects in the AWS C++ SDK?

**Comment by bretambrose** [comment]
The ListObjectsResult object has two values that will help you: GetIsTruncated and GetNextMarker.  GetIsTruncated tells you if you've reached the end of the result set.  If you haven't reached the end, you fetch the next set of results by setting the marker on the request (ListObjectsRequest::SetMarker) to be the value of ListObjectsResult::GetNextMarker from the result of the previous request.  So rough pseudo-code would be:

```
bool isDone = false;
ListObjectsRequest request;
... // fill in request

while(!isDone)
{
    listObjectsOutcome = client->ListObjects(request);
    ... // process results
    isDone = !listObjectsOutcome.GetResult().GetIsTruncated();
    if(!isDone)
        request.SetMarker(listObjectsOutcome.GetResult().GetNextMarker());
}

```

Obiviously it would be nice if we provided higher-level clients that did these cursor-like queries for you, but that's something we haven't gotten to yet.

**Comment by logidelic** [comment]
Thanks for that. The weird thing is that these are exactly what I was looking for and convinced myself did not exist. Nevertheless, there they are in the ListObjectsResult docs. Not sure how I missed it.

**Comment by logidelic** [comment]
I know that this issue is closed. Just want to mention for anyone who comes across: Be careful with using GetNextMarker() in the way mentioned above. Specifically, it might return an empty string if delimit isn't specified in the ListObjects request. The docs state:

> Note: This element is returned only if you have delimiter request parameter specified. If response does not include the NextMaker and it is truncated, you can use the value of the last Key in the response as the marker in the subsequent request to get the next set of object keys.

**Comment by SubmarineX** [comment]
```
bool all_objects_listed = false;
Aws::S3::Model::ListObjectsV2Request list_objects_request;
list_objects_request.WithBucket(aws_container_name);
while (!all_objects_listed) {
    auto list_objects_outcome = client->ListObjectsV2(list_objects_request);
    if (list_objects_outcome.IsSuccess()) {
      all_objects_listed = list_objects_result.GetIsTruncated();
      if(!all_objects_listed) {
        list_objects_request.SetContinuationToken(list_objects_result.GetNextContinuationToken());
     }
  }
}
```

> Version: 1.1.42.

There are 1001 objects in bucket, but list_objects_result.GetIsTruncated() is true after call firstly ListObjectsV2.  Why GetIsTruncated() is true? My code is incorrect?

**Comment by CrammingLearning** [comment]
@SubmarineX 
the code should be
```
all_objects_listed = !list_objects_result.GetIsTruncated();
```
As far as I understand, since when the object is not all listed, the state is `truncate`, so `GetIsTruncated()` return `true`, that means `all_objects_listed` should be `false`

**Comment by SubmarineX** [comment]
Sorry, I made a silly mistake at that time.

**Comment by SubmarineX** [comment]
> 

Sorry, I made a silly mistake at that time.

**Comment by SubmarineX** [comment]
@q-wind 

Sorry, I made a silly mistake at that time.

**Comment by q-wind** [comment]
@SubmarineX 
I just started learning this, thanks for your example
