### ISSUE TITLE
How to make the streaming transcribe run in real-time

### ISSUE THREAD

**Issue by alanee1996** [aws/aws-sdk-cpp#1760]
I run the streaming transcribe example code from [here](https://aws.amazon.com/blogs/developer/real-time-streaming-transcription-with-the-aws-c-sdk/) but it did not run as real-time. It need to click cltr + c then only will get the result. I read the code basically it will only make request when after AudioStream is close. Any idea how to make it stream real time (wish TranscriptEventCallback can be invoke every time when each request send out and get response)

**Comment by KaibaLopez** [comment]
Hi @alanee1996 
What version of the SDK and what OS are you using?

**Comment by alanee1996** [comment]
> Hi @alanee1996
> What version of the SDK and what OS are you using?

I was installing the sdk using vcpkg with version 1.8.126#10 (this is the latest version I can get via vcpkg). My OS is windows 10 x64. I also have one more question is about the streaming transcribe results did not contained accuracy percentage (confidence). this version 1.8.126#10 also cannot set the partialStability option.

**Comment by KaibaLopez** [comment]
Hi @alanee1996 ,
Sorry for the lack of response here, the realtime repsonse on the command line is a windows limitation, not much we can do on that front.
About the confidence part: it's there, just kind of hard to get to, You would need to get a result -> get alternatives -> get specific alternative -> get Items -> specific item ->   and de-jsonify the item to get the confidence of that alternative.
Again, sorry for the late response.

**Comment by alanee1996** [comment]
> Hi @alanee1996 , Sorry for the lack of response here, the realtime repsonse on the command line is a windows limitation, not much we can do on that front. About the confidence part: it's there, just kind of hard to get to, You would need to get a result -> get alternatives -> get specific alternative -> get Items -> specific item -> and de-jsonify the item to get the confidence of that alternative. Again, sorry for the late response.

After I updated to the latest sdk, it have the confidence attribute can get from item model. So do you mean like other than command line project such as windows desktop application, it would be able to run in parallel?

**Comment by KaibaLopez** [comment]
I am not sure which windows applications would and which wouldn't have this problem but in theory yes.
