### ISSUE TITLE
TranscribeStreaming Receive partial results while continuing to send chunks.

### ISSUE THREAD

**Issue by jbmcgee** [aws/aws-sdk-cpp#1761]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Using 1.9 on Intel x86 / Window 10

**Describe the question**
I'm trying to receive partial audio transcriptions while still sending more audio chunks. I found a similar [issue #1527](https://github.com/aws/aws-sdk-cpp/issues/1527) mentioning the issue but it's unclear to me in how to achieve this. I'm sure I'm sending at least 500 millisecond chunks, but I don't receive results until the stream completely finishes. How do you receive partial results while continuing to send chunks in a stream?

**Comment by jbmcgee** [comment]
I probably should mention I'm using http/2, `TranscribeStreamingServiceClient::StartStreamTranscriptionAsync`

**Comment by KaibaLopez** [comment]
Hi @jbmcgee ,
Yea there seems to be something going on with the windows implementation, we'll update when we have more info.

**Comment by jbmcgee** [comment]
Is there any updates regarding the issue? Thanks.

**Comment by KaibaLopez** [comment]
sorry, 
Yea there was an recent update on the transcribestreaming service, I just haven't had the chance to test if the issue was fixed, but if you could try getting the latest SDK version and trying it might be faster than me setting up the test on a windows machine. 
I will still try and update by eod and see if anything's changed.

**Comment by KaibaLopez** [comment]
Alright, as an update I was able to run the sample on Windows.
The only "issue" I have is that the windows console does not really work for this sample, as it doesn't work in real time, so you won't get the transcribe results printed on the console until you close the application.
This is not really a "problem" with the SDK though, and the sample is only meant to be an example on how to call the service so I am not sure  it's a bug either?
Idk, let me know what you think and/or if you are still having issues with it.

**Comment by jbmcgee** [comment]
Thanks for the update. I'm still seeing the same behavior with the latest SDK. The request's `TranscriptEventCallback` isn't call until the stream finishes. Maybe my expectations of the SDK API is incorrect. I assumed `TranscribeStreamingServiceClient::StartStreamTranscriptionAsync` would call the `StartStreamTranscriptionStreamReadyHandler` on one thread and call the request's `TranscriptEventCallback` on another. After looking at the source, it seems the request and response are made on the same thread. Looking at `WinSyncHttpClient.cpp`,:

```
        if (DoSendRequest(hHttpRequest) && StreamPayloadToRequest(request, hHttpRequest, writeLimiter))
        {
            success = BuildSuccessResponse(request, response, hHttpRequest, readLimiter);
        }
```

How do I stream payloads on one thread while receiving responses on another in parallel? Do I have to turn my stream into separate request?

**Comment by jbmcgee** [comment]
Thanks for the help. I was able to achieve my goal with websockets api.
