### ISSUE TITLE
TransferManager not exhibitng RAII behavior

### ISSUE THREAD

**Issue by kartikarcot** [aws/aws-sdk-cpp#1764]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I use the transfer manager and have written a wrapper around it for my use. I end up using the transfer status callback, which captures some member variables of the wrapper class. The transfer manager does not seem to gracefully shut down if I the wrapper object (which contains an instantiation of the transfer manager) gets destroyed. The callback is still called and leads to a segmentation fault.

**SDK version number**
1.9.56

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Linux

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
* Launch a transfer manager with a large download
* Have a call back that captures variables that are not in its own scope but in the parent scope
* Kill the transfer manager abruptly

**Expected behavior**

Should lead to segmentation fault since the callback refers to variables that are not available anymore

**Logs/output**
If applicable, add logs or error output.
Tried trace level logging but could not get any useful aws logs

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

There has been a related issue which also does not seem to have been resolved but was closed.
https://github.com/aws/aws-sdk-cpp/issues/651

**Comment by KaibaLopez** [comment]
Hi @kartikarcot ,
could you show me sample code that reproduces this?
