### ISSUE TITLE
Compile error: 'SigV4A' is not a member of 'Aws::Crt::Auth::SigningAlgorithm'

### ISSUE THREAD

**Issue by rvernica** [aws/aws-sdk-cpp#1769]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**

Compilation error during `make`.

**SDK version number**

1.9.97

**Platform/OS/Hardware/Device**

CentOS 7

**To Reproduce (observed behavior)**

1. Download `.tar.gz` from GitHub Releases https://github.com/aws/aws-sdk-cpp/releases
1. Run `./prefetch_crt_dependency.sh `
1. Run cmake:

        build> scl enable devtoolset-3                                                          \
          "cmake3 ..                                                          \
                 -DBUILD_ONLY=s3                                                \
                 -DBUILD_SHARED_LIBS=ON                                         \
                 -DENABLE_TESTING=OFF                                           \
                 -DCMAKE_BUILD_TYPE=Release                                     \
                 -DCMAKE_CXX_COMPILER=/opt/rh/devtoolset-3/root/usr/bin/g++     \
                 -DCMAKE_C_COMPILER=/opt/rh/devtoolset-3/root/usr/bin/gcc       \
                 -DCMAKE_INSTALL_PREFIX=/opt/aws-sdk-cpp \
                 -DCMAKE_PREFIX_PATH=/opt/curl"

1. Run make:

        build> make
        ...
        Scanning dependencies of target aws-cpp-sdk-core
        [ 88%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/AmazonSerializableWebServiceRequest.cpp.o
        In file included from /aws-sdk-cpp-1.9.97/aws-cpp-sdk-core/include/aws/core/AmazonWebServiceRequest.h:16:0,
                 from /aws-sdk-cpp-1.9.97/aws-cpp-sdk-core/include/aws/core/AmazonSerializableWebServiceRequest.h:9,
                 from /aws-sdk-cpp-1.9.97/aws-cpp-sdk-core/source/AmazonSerializableWebServiceRequest.cpp:6:
        /aws-sdk-cpp-1.9.97/aws-cpp-sdk-core/include/aws/core/auth/AWSAuthSigner.h:48:49: error: 'SigV4A' is not a member of 'Aws::Crt::Auth::SigningAlgorithm'
        ASYMMETRIC_SIGV4 = static_cast<int>(Aws::Crt::Auth::SigningAlgorithm::SigV4A),
                                                 ^
        make[2]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/AmazonSerializableWebServiceRequest.cpp.o] Error 1
        make[1]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/all] Error 2
        make: *** [all] Error 2

**Comment by chubin** [comment]
I have this error too; 1.9.145

**Comment by hardikmdev** [comment]
Facing this with v 1.9.146 as well.
