### ISSUE TITLE
When build aws-sdk-cpp, got "Unknown CMake command "aws_use_package""

### ISSUE THREAD

**Issue by Jasonqian1** [aws/aws-sdk-cpp#1770]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
OS windows 10 
cmake C:\tools\aws-sdk-cpp-main -G "Visual Studio 15 Win64" -DCMAKE_BUILD_TYPE=Debug

-- Detecting C compile features
-- Detecting C compile features - done
-- Updating version info to 1.9.99
-- Custom memory management disabled
-- Performing Test WINHTTP_HAS_H2
-- Performing Test WINHTTP_HAS_H2 - Success
-- Performing Test WININET_HAS_H2
-- Performing Test WININET_HAS_H2 - Success
CMake Error at aws-cpp-sdk-core/CMakeLists.txt:504 (aws_use_package):
  Unknown CMake command "aws_use_package".

-- Configuring incomplete, errors occurred!
See also "C:/GServer/tools/aws-sdk-cpp-build/CM

**Comment by rvernica** [comment]
Sounds similar to #1766, you might be missing the sub-modules.

**Comment by KaibaLopez** [comment]
@Jasonqian1 ,
can you try running 
```
cd aws-sdk-cpp
git checkout main
git pull origin main
git submodule update --init --recursive
```
and see if that works for you?
