### ISSUE TITLE
Non standard locale causes 400 errors for every S3 query

### ISSUE THREAD

**Issue by edouarda** [aws/aws-sdk-cpp#1772]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
S3 queries will return 400 bad request when locale is set.

**SDK version number**
1.9.95

**Platform/OS/Hardware/Device**
Windows 64

**To Reproduce (observed behavior)**
Set locale to en US UTF-9 for example, you will get bad request when max keys (or any numerical parameter) is more than 1,000

**Expected behavior**
Queries should return 200 OK

**Additional context**

The bug is caused because you guys use std:stringstream (not the best choice if you ask me). std::stringstream will use the locale and may thus add thousand separators, thus the query sent to S3 is "max-keys=2,000" instead of "max-keys=2000" (for example).

The bug can be fixed by adding the following line in

aws-sdk-cpp/aws-cpp-sdk-s3/source/model/ListObjectsRequest.cpp

```cpp
void ListObjectsRequest::AddQueryStringParameters(URI& uri) const
{
    Aws::StringStream ss;
    ss.imbue(std::locale("C")); // add this line

    if(m_delimiterHasBeenSet)
    {
      ss << m_delimiter;
```

Or stop using std::stringstream. Maybe give fmtlib a try?

**Comment by KaibaLopez** [comment]
Hi @edouarda ,
Yea we had a similar issue come up a while ago, and I think this is a known issue for us but just to be sure they are the same thing, could you show me sample code that reproduces this? I'm curious on your use case and it would also help me prioritize this bug.

**Comment by edouarda** [comment]
Howdy! Thanks for the quick reply, just add this in your program then do a S3 directory listing

```cpp
const auto loc = "en-US"; // if Linux do "en_US.UTF-8"
const auto res = std::setlocale(LC_ALL, loc);
if (res)
{
    std::locale::global(std::locale(loc));
}
```

**Comment by edouarda** [comment]
The bug is present in multiple area, it's also present here in AWSClient.cpp

```cpp
        body->seekg(0, body->beg);
        Aws::StringStream ss;
        ss << streamSize;
        httpRequest->SetContentLength(ss.str());
```

With locale on the number may be stored as "1,234" instead of 1234.

The real fix is to get rid of Aws::StringStream 🤠 

Or just do this

```cpp
typedef std::basic_stringstream< char, std::char_traits< char >, Aws::Allocator< char > > StringStreamImpl;

class StringStream : public StringStreamImpl
{
   StringStream() : StringStreamImpl{} {     imbue(std::locale("C")); }
};

```
