### ISSUE TITLE
S3 SDK hangs on multiple requests

### ISSUE THREAD

**Issue by rvernica** [aws/aws-sdk-cpp#1775]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
SDK hungs with multiple parallel requests.

**SDK version number**
1.9.97

**Platform/OS/Hardware/Device**
CentOS 7

**To Reproduce (observed behavior)**
I have 36 ~threads~ processes making the a `list` request to the same S3 path. Most of the clients succeed but a few hang in the AWS SDK.

If I decrease the number of ~threads~ processes to 35 it works fine.

**Comment by jmklix** [comment]
Can you include a code snippet of how you are creating 36 threads?

**Comment by KaibaLopez** [comment]
Hmm I would still like to see code on how to reproduce this, not much I can help with otherwise.

**Comment by rvernica** [comment]
I agree, but getting the code together is quite a feat. The SDK is currently embedded in a parallel DB.

This issue only appears if I use the S3 CRT API. If I use the S3 non-CRT API everything works fine. We tried with up to 48 processes.

Are there any tests in the S3 CRT API doing something similar?

**Comment by KaibaLopez** [comment]
Ok, I guess my confusion is, what do you mean by processes and how are you testing this ? 
Like, can you make 36 processes of one of our samples so we can try that?

**Comment by rvernica** [comment]
I'm not sure about your second question but I'll answer the first. The SDK is used in a parallel DB. The DB has between 2-48 instances/processed running concurrently - there are Linux processes with their own PID - not threads. At one point they all do a `list` request on an S3 URL. Some succeed while others fail, retry and hang. This issue appears only if we are using the S3 CRT libraries. If we are using the cURL S3 libraries it works fine. As you can see the setup is pretty complex and can't be replicated here.

**Comment by rvernica** [comment]
@jmklix @KaibaLopez see [this PR](https://github.com/awsdocs/aws-doc-sdk-examples/pull/2137) for an example on how to repro this.

**Comment by rvernica** [comment]
@jmklix @KaibaLopez were you able to confirm this? On our side, this issue is blocking us from upgrading the SDK and taking advantage to the S3 improvements in 1.9.97

**Comment by rvernica** [comment]
@jmklix @KaibaLopez or anyone else, were you have a look at this?
