### ISSUE TITLE
S3 crt does not recognise AWS_GLOBAL region

### ISSUE THREAD

**Issue by NatxoM** [aws/aws-sdk-cpp#1777]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
S3 crt does not recognise AWS_GLOBAL region

**SDK version number**
v1.9.105

**Platform/OS/Hardware/Device**
Ubuntu 18.04

**To Reproduce (observed behavior)**
Create a S3 crt client with global region:

		Aws::S3Crt::ClientConfiguration client_conf;
		client_conf.region = Aws::Region::AWS_GLOBAL;
		static std::shared_ptr<Aws::S3Crt::S3CrtClient> AWS_S3_CLIENT = Aws::MakeShared<Aws::S3Crt::S3CrtClient>("S3CrtClient", client_conf);

**Expected behavior**
The global region is not recognised. It defaults to 'us-east-1'

**Comment by KaibaLopez** [comment]
Hi @NatxoM ,
I am not able to reproduce this, for me the AWS_GLOBAL works just fine, could you try activating the trace logs and (after sanitizing them off any credentials info) post them here? There might be something else going on.

**Comment by NatxoM** [comment]
This is the error I get when using the code shown above:

`AuthorizationHeaderMalformedUnable to parse ExceptionName: AuthorizationHeaderMalformed Message: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'"`

**Comment by KaibaLopez** [comment]
Hi @NatxoM ,
Sorry for the lack of response here... It kind of went over my head honestly, but regarding your problem.

The short answer is: `aws-global` is a bit of a hacky value for the SDK and the response you are getting is kind of expected.

Basically, the region `aws-global` is only valid for requests where the region is not really required, think s3's `ListBuckets()`. But as you can see it will not be accepted for things that do required the region, like `GetObject()`. 
I know it is not super intuitive but yea, `aws-global` is not meant to be an "all regions" or "detect and use the correct region" but more of a token value to get past the region requirement of certain api models where it shouldn't matter.
Hope that makes sense and sorry again for the slow response.
