### ISSUE TITLE
How can I get AWS credentials through Cognito identity pool?

### ISSUE THREAD

**Issue by jeffwang512021** [aws/aws-sdk-cpp#1783]
Hello! I'd like to know how I can get temporary AWS credentials through Amazon Cognito Identity pool (in C/C++)?

From the link (https://docs.aws.amazon.com/cognito/latest/developerguide/authentication-flow.html), it seems we could get the credentials by only providing the Identity Pool ID and the region to the application, but after some checking of the aws-sdk-cpp SDK (https://github.com/aws/aws-sdk-cpp), it seems no direct way&example to do this.

So I'd like to know if anyone here knows about this and give me some guidance? Thanks in advance! :)

**Comment by KaibaLopez** [comment]
Hi @jeffwang512021 ,
I think you are looking for a sample on how to use `GetCredentialsForIdentity` so I'll respond with that assumption, let me know if I'm wrong though...
So yea we don't have a "sample" ready but we do have tests that show what the expected usage is, for this specific call you can look [here](https://github.com/aws/aws-sdk-cpp/blob/bb1fdce01cc7e8ae2fe7162f24c8836e9d3ab0a2/aws-cpp-sdk-cognitoidentity-integration-tests/IdentityPoolOperationTest.cpp#L233)
But basically it goes something like
```cpp
Aws::Client::ClientConfiguration clientConfig("default"); // this will look for that profile in your .aws/config and .aws/credentials files
auto client = Aws::MakeShared<Aws::CognitoIdentity::CognitoIdentityClient>("cognito_client",clientConfig);
auto iamClient = Aws::MakeShared<Aws::IAM::IAMClient>("iam_client", clientConfig);
        
Aws::CognitoIdentity::Model::GetCredentialsForIdentityRequest request;
request.WithIdentityId(<your_identityId>);
        

auto getIdOutcome = client->GetCredentialsForIdentity(request);
if(getIdOutcome.IsSuccess()){
    std::cout<< "success! the Id is: " << getIdOutcome.GetResult().GetCredentials().GetAccessKeyId() << std::endl;
    std::cout<< "Secret Key: " << getIdOutcome.GetResult().GetCredentials().GetSecretKey()<< std::endl;
}else{
    std::cout<< "failed : " << getIdOutcome.GetError().GetMessage()<< std::endl;
}
```
Let me know if this helps or if I misunderstood the question.

**Comment by jeffwang512021** [comment]
@KaibaLopez Thanks a lot for your info! I could now get the AWS credentials with identity pool id and region as input. 
But when I try to use the credentials to establish Mqtt connections (see my below code), it popped with below error message:

_Connection failed with error aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed_

The Mqtt related code is attached below, which is based on the basic_pub_sub example. Here I used CreateCredentialsProviderStatic as the credential provider with the access_key/secret_key/session_token got through the cognito identity pool. Could you please enlighten me about this error? thanks a lot! :)

    Aws::Crt::Auth::CredentialsProviderStaticConfig defaultConfig;
    std::shared_ptr<Aws::Crt::Auth::ICredentialsProvider> provider = nullptr;

    defaultConfig.AccessKeyId = Aws::Crt::ByteCursorFromCString(access_key.c_str());
    defaultConfig.SecretAccessKey = Aws::Crt::ByteCursorFromCString(secret_key.c_str());
    defaultConfig.SessionToken = Aws::Crt::ByteCursorFromCString(session_token.c_str());
 
    provider = Aws::Crt::Auth::CredentialsProvider::CreateCredentialsProviderStatic(defaultConfig);
 
    Aws::Iot::MqttClientConnectionConfigBuilder builder;
    Aws::Iot::WebsocketConfig config("us-east-1", provider);
    builder = Aws::Iot::MqttClientConnectionConfigBuilder(config);

    /********************** Now Setup an Mqtt Client ******************/
    /*
     * You need an event loop group to process IO events.
     * If you only have a few connections, 1 thread is ideal
     */
    Aws::Crt::Io::EventLoopGroup eventLoopGroup(1);
    if (!eventLoopGroup)
    {
        printf("Event Loop Group Creation failed with error %s\n", ErrorDebugString(eventLoopGroup.LastError()));
    }
 
    Aws::Crt::Io::DefaultHostResolver defaultHostResolver(eventLoopGroup, 1, 5);
    Aws::Crt::Io::ClientBootstrap bootstrap(eventLoopGroup, defaultHostResolver);
 
    if (!bootstrap)
    {
        printf("ClientBootstrap failed with error %s\n", ErrorDebugString(bootstrap.LastError()));
    }

    Aws::Crt::String endpoint = "xxxxxxxxxxxxx-ats.iot.us-east-1.amazonaws.com";
    builder.WithEndpoint(endpoint);
 
    auto clientConfig1 = builder.Build();
 
    if (!clientConfig1)
    {
        printf("Client Configuration initialization failed with error %s\n", ErrorDebugString(clientConfig1.LastError()));
    }
 
    Aws::Iot::MqttClient mqttClient(bootstrap);
    /*
     * Since no exceptions are used, always check the bool operator
     * when an error could have occurred.
     */
    if (!mqttClient)
    {
        printf("MQTT Client Creation failed with error %s\n", ErrorDebugString(mqttClient.LastError()));
    }
 
    /*
     * Now create a connection object. Note: This type is move only
     * and its underlying memory is managed by the client.
     */
    auto connection = mqttClient.NewConnection(clientConfig1);
 
    if (!connection)
    {
        printf("MQTT Connection Creation failed with error %s\n", ErrorDebugString(mqttClient.LastError()));
    }

    /*
     * In a real world application you probably don't want to enforce synchronous behavior
     * but this is a sample console application, so we'll just do that with a condition variable.
     */
    std::promise<bool> connectionCompletedPromise;
    std::promise<void> connectionClosedPromise;
 
    /*
     * This will execute when an mqtt connect has completed or failed.
     */
    auto onConnectionCompleted = [&](Mqtt::MqttConnection &, int errorCode, Mqtt::ReturnCode returnCode, bool) {
        if (errorCode)
        {
            **_printf("Connection failed with error %s\n", ErrorDebugString(errorCode));_**
            connectionCompletedPromise.set_value(false);
        }
        else
        {
            if (returnCode != AWS_MQTT_CONNECT_ACCEPTED)
            {
                printf("Connection failed with mqtt return code %d\n", (int)returnCode);
                connectionCompletedPromise.set_value(false);
            }
            else
            {
                printf("Connection completed successfully.");
                connectionCompletedPromise.set_value(true);
            }
        }
    };
 
    auto onInterrupted = [&](Mqtt::MqttConnection &, int error) {
        printf("Connection interrupted with error %s\n", ErrorDebugString(error));
    };
 
    auto onResumed = [&](Mqtt::MqttConnection &, Mqtt::ReturnCode, bool) { printf("Connection resumed\n"); };
 
    /*
     * Invoked when a disconnect message has completed.
     */
    auto onDisconnect = [&](Mqtt::MqttConnection &) {
        {
            printf("Disconnect completed\n");
            connectionClosedPromise.set_value();
        }
    };
 
    connection->OnConnectionCompleted = std::move(onConnectionCompleted);
    connection->OnDisconnect = std::move(onDisconnect);
    connection->OnConnectionInterrupted = std::move(onInterrupted);
    connection->OnConnectionResumed = std::move(onResumed);
 
    /*
     * Actually perform the connect dance.
     * This will use default ping behavior of 1 hour and 3 second timeouts.
     * If you want different behavior, those arguments go into slots 3 & 4.
     */
    fprintf(stdout, "Connecting...\n");
    if (!connection->Connect("test1", false, 1000))
    {
        printf("MQTT Connection failed with error %s\n", ErrorDebugString(connection->LastError()));
    }

**Comment by jeffwang512021** [comment]
I just realize that the 2nd question is not quite related to the topic, so maybe I need to launch a new issue. But any guidance&comments are welcomed here as well! :)

**Comment by KaibaLopez** [comment]
Hi @jeffwang512021 ,
Yea, opening a new one is a good idea, if it's ok with you though I'll close this one, just makes it cleaner and easier to keep track of for us.

**Comment by jeffwang512021** [comment]
@KaibaLopez Yea, sounds good. Let's close it. Thanks a lot. :)
