### ISSUE TITLE
TLS negotiation failure when establishing MQTT connections with Cognito identity credentials

### ISSUE THREAD

**Issue by jeffwang512021** [aws/aws-sdk-cpp#1785]
Hello! When I try to use the credentials got through the identity pool, plus the endpoint, to establish Mqtt connections (see my below code), it popped with below error message:

_Connection failed with error aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed_

The Mqtt related code is attached below, which is based on the basic_pub_sub example. Here I used CreateCredentialsProviderStatic as the credential provider (only for the prototype) with the access_key/secret_key/session_token got through the cognito identity pool. Could you please enlighten me about this error? Thanks in advance! :)

Aws::Crt::Auth::CredentialsProviderStaticConfig defaultConfig;
std::shared_ptr<Aws::Crt::Auth::ICredentialsProvider> provider = nullptr;

defaultConfig.AccessKeyId = Aws::Crt::ByteCursorFromCString(access_key.c_str());
defaultConfig.SecretAccessKey = Aws::Crt::ByteCursorFromCString(secret_key.c_str());
defaultConfig.SessionToken = Aws::Crt::ByteCursorFromCString(session_token.c_str());

provider = Aws::Crt::Auth::CredentialsProvider::CreateCredentialsProviderStatic(defaultConfig);

Aws::Iot::MqttClientConnectionConfigBuilder builder;
Aws::Iot::WebsocketConfig config("us-east-1", provider);
builder = Aws::Iot::MqttClientConnectionConfigBuilder(config);

/********************** Now Setup an Mqtt Client ******************/
/*
 * You need an event loop group to process IO events.
 * If you only have a few connections, 1 thread is ideal
 */
Aws::Crt::Io::EventLoopGroup eventLoopGroup(1);
if (!eventLoopGroup)
{
    printf("Event Loop Group Creation failed with error %s\n", ErrorDebugString(eventLoopGroup.LastError()));
}

Aws::Crt::Io::DefaultHostResolver defaultHostResolver(eventLoopGroup, 1, 5);
Aws::Crt::Io::ClientBootstrap bootstrap(eventLoopGroup, defaultHostResolver);

if (!bootstrap)
{
    printf("ClientBootstrap failed with error %s\n", ErrorDebugString(bootstrap.LastError()));
}

Aws::Crt::String endpoint = "xxxxxxxxxxxxx-ats.iot.us-east-1.amazonaws.com";
builder.WithEndpoint(endpoint);

auto clientConfig1 = builder.Build();

if (!clientConfig1)
{
    printf("Client Configuration initialization failed with error %s\n", ErrorDebugString(clientConfig1.LastError()));
}

Aws::Iot::MqttClient mqttClient(bootstrap);
/*
 * Since no exceptions are used, always check the bool operator
 * when an error could have occurred.
 */
if (!mqttClient)
{
    printf("MQTT Client Creation failed with error %s\n", ErrorDebugString(mqttClient.LastError()));
}

/*
 * Now create a connection object. Note: This type is move only
 * and its underlying memory is managed by the client.
 */
auto connection = mqttClient.NewConnection(clientConfig1);

if (!connection)
{
    printf("MQTT Connection Creation failed with error %s\n", ErrorDebugString(mqttClient.LastError()));
}

/*
 * In a real world application you probably don't want to enforce synchronous behavior
 * but this is a sample console application, so we'll just do that with a condition variable.
 */
std::promise<bool> connectionCompletedPromise;
std::promise<void> connectionClosedPromise;

/*
 * This will execute when an mqtt connect has completed or failed.
 */
auto onConnectionCompleted = [&](Mqtt::MqttConnection &, int errorCode, Mqtt::ReturnCode returnCode, bool) {
    if (errorCode)
    {
        **_printf("Connection failed with error %s\n", ErrorDebugString(errorCode));_**
        connectionCompletedPromise.set_value(false);
    }
    else
    {
        if (returnCode != AWS_MQTT_CONNECT_ACCEPTED)
        {
            printf("Connection failed with mqtt return code %d\n", (int)returnCode);
            connectionCompletedPromise.set_value(false);
        }
        else
        {
            printf("Connection completed successfully.");
            connectionCompletedPromise.set_value(true);
        }
    }
};

auto onInterrupted = [&](Mqtt::MqttConnection &, int error) {
    printf("Connection interrupted with error %s\n", ErrorDebugString(error));
};

auto onResumed = [&](Mqtt::MqttConnection &, Mqtt::ReturnCode, bool) { printf("Connection resumed\n"); };

/*
 * Invoked when a disconnect message has completed.
 */
auto onDisconnect = [&](Mqtt::MqttConnection &) {
    {
        printf("Disconnect completed\n");
        connectionClosedPromise.set_value();
    }
};

connection->OnConnectionCompleted = std::move(onConnectionCompleted);
connection->OnDisconnect = std::move(onDisconnect);
connection->OnConnectionInterrupted = std::move(onInterrupted);
connection->OnConnectionResumed = std::move(onResumed);

/*
 * Actually perform the connect dance.
 * This will use default ping behavior of 1 hour and 3 second timeouts.
 * If you want different behavior, those arguments go into slots 3 & 4.
 */
fprintf(stdout, "Connecting...\n");
if (!connection->Connect("test1", false, 1000))
{
    printf("MQTT Connection failed with error %s\n", ErrorDebugString(connection->LastError()));
}

**Comment by KaibaLopez** [comment]
Hi @jeffwang512021 ,
So this error is a sort of "Catch all" for the IoT service which makes it really hard to pinpoint what's wrong.... Could you post the trace logs generated here? Just make sure that you censor any mention of your keys and credentials. 
That might help me identify what went wrong.

**Comment by jeffwang512021** [comment]
@KaibaLopez I think I've missed to instantiate the ApiHandle first to perform the onetime static initialization of the library, and now the mqtt connection is working now! Anyway, thanks a lot for your strong support! :)

**Comment by KaibaLopez** [comment]
great!
