### ISSUE TITLE
Cancelling SubscribeToShard method of KinesisClient

### ISSUE THREAD

**Issue by Galdoren** [aws/aws-sdk-cpp#1787]
### Discussed in https://github.com/aws/aws-sdk-cpp/discussions/1786

<div type='discussions-op-text'>

<sup>Originally posted by **Galdoren** October  1, 2021</sup>
Hi,

I'm trying to delete a ```KinesisClient``` instance, but the problem is the method ```SubscribeToShard``` blocks the code for 5 minutes and I'm unable to delete the client unless 5 minutes passes.

I hope someone can show me the correct way to cancel this call.

Thanks in advance.</div>

**Comment by jmklix** [comment]
Are you still blocked for 5 minutes if you use `SubscribeToShardAsync`?
