### ISSUE TITLE
AWS SDK C++ not freeing memory of nlohmann::json or jsoncpp objects

### ISSUE THREAD

**Issue by NatxoM** [aws/aws-sdk-cpp#1790]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I have an AWS Lambda built with the C++ runtime and using AWS SDK C++. I use large Json objects and the memory they used is not freed after each Lambda execution. Actually, it seems to leakage slowly. I have the same problem either using Jsoncpp or the Nlohmann/json library.

**SDK version number**
1.9.116

**Platform/OS/Hardware/Device**
Ubuntu:18.04

**To Reproduce (observed behavior)**
Create a large json object (Jsoncpp or the Nlohmann/json). Observe how the memory grows with repeated lambda calls. To obtain the memory used, I call this function: 

```
std::string process_mem_usage(void) {
    double vm_usage = 0.0;
    double resident_set = 0.0;
    unsigned long vsize;
    long rss;
    {
        std::string ignore;
        std::ifstream ifs("/proc/self/stat", std::ios_base::in);
        ifs >> ignore >> ignore >> ignore >> ignore >> ignore >> ignore >> ignore >> ignore >> ignore >> ignore
                >> ignore >> ignore >> ignore >> ignore >> ignore >> ignore >> ignore >> ignore >> ignore >> ignore
                >> ignore >> ignore >> vsize >> rss;
    }
    long page_size_kb = sysconf(_SC_PAGE_SIZE) / 1024; // in case x86-64 is configured to use 2MB pages
    vm_usage = vsize / 1024.0;
    resident_set = rss * page_size_kb;
    std::stringstream ss;
	ss << "VM: " << vm_usage << "; RSS: " << resident_set;
    return ss.str();
};
```

At the beginning of the first call to the lambda handler, RSS = 11 MB, at the end is RSS = 600 MB. At the beginning of the second call, it is RSS = 600 MB again, at the end of the second call it is around 600 MB, probably a bit larger. After extensive testing, I am sure that the memory not being freed comes from the json object.

**Comment by KaibaLopez** [comment]
Hi @NatxoM ,
I'm not super familiar with the c++ Lambda sdk so it might take me a bit to get a testing setup for this but before I do, do you know if there is a memory leak or is it just increased memory usage? We do have a known issue on the way the sdk uses global variables that might be related but not sure, which does not cause a memory leak but has the memory usage problem.

**Comment by jmklix** [comment]
This is an old issue and we have fixed a few memory leaks sense it was open. Can you confirm if this is still an issue with this sdk?
