### ISSUE TITLE
Is it possible to use AWS Lambda runtime CPP with AWS SDK CPP on Ubuntu 20.04?

### ISSUE THREAD

**Issue by NatxoM** [aws/aws-sdk-cpp#1794]
Confirm by changing [ ] to [x] below:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Ubuntu 20.04

**Describe the question**
I've tried several times to use AWS Lambda runtime CPP with AWS SDK CPP on Ubuntu 20.04 and always had to back up to Ubuntu 18.04 because I encountered  major issues when running my lambdas. Compilation was ok, but then I had segmentation faults, memory corruption problems, etc. Everything works as expected on Ubuntu 18.04.

Is it possible to use AWS Lambda runtime CPP with AWS SDK CPP on Ubuntu 20.04?

**Comment by NatxoM** [comment]
I use the Docker image of Ubuntu 20.04. This image has GCC 9 and Cmake 3.16. My program is implemented with C++11.

If I launch one time my lambda (which uses AWS Lambda C++ runtime) it works fine. But if I launch it again, I get this error:

`Error: Runtime exited with error: signal: broken pipe`

**Comment by KaibaLopez** [comment]
Hi @NatxoM ,
Sorry for the late response, could you activate and provide the trace logs for the SDK ? 
Also, I have a feeling this is mostly on the AWS Lambda C++ runtime and not the c++ SDK though, the logs should clarify that by giving a more complete story though.
Make sure to remove any mention of your credentials from the logs before posting them.

**Comment by technic** [comment]
I have same issue:

 Runtime exited with error: signal: broken pipe

**Comment by yasminetalby** [comment]
Hello @technic ,

Thank you very much for reaching out.
This issue submission was closed due to missing information.
Could you please open a new issue with detailed information about your use case, reproduction steps as well as trace logs so we can further investigate the behavior you are experiencing?
You can do so [here](https://github.com/aws/aws-sdk-cpp/issues/new/choose) under reporting bug.

Thank you very much for your time and collaboration.

Sincerely,

Yasmine

**Comment by technic** [comment]
It happens randomly, hard to reproduce.

**Comment by technic** [comment]
@yasminetalby Oh, I didn't! Thanks for pointing this out :)

**Comment by yasminetalby** [comment]
@technic of course! Let me know if you have any further questions

Best regards,

Yasmine
