### ISSUE TITLE
Segmentation fault when downloading with DownloadToDirectory

### ISSUE THREAD

**Issue by alexminnaar** [aws/aws-sdk-cpp#1796]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Getting a segmentation fault error in the following code.  Some files do get successfully downloaded.  The code is mostly copied from TransferTests.

```
    using namespace Aws::S3;
    using namespace Aws::S3::Model;
    using namespace Aws::Transfer;
    using namespace Aws::Client;
    using namespace Aws::Http;
    using namespace Aws::Utils;

    Aws::SDKOptions options;
    Aws::InitAPI(options);
    auto  m_executor = Aws::MakeShared<Aws::Utils::Threading::PooledThreadExecutor>("DirectoryDownloadTag", 4);

    Aws::Vector<std::shared_ptr<TransferHandle>> directoryUploads;
    Aws::Vector<std::shared_ptr<TransferHandle>> directoryDownloads;
    std::condition_variable directoryUploadSignal;
    std::condition_variable directoryDownloadSignal;
    std::mutex semaphoreLock;

    auto transferInitCallback = [&](const TransferManager*, const std::shared_ptr<const TransferHandle>& handle)
        {
            std::lock_guard<std::mutex> m(semaphoreLock);

            if(handle->GetTransferDirection() == TransferDirection::UPLOAD)
            {
                directoryUploads.push_back(std::const_pointer_cast<TransferHandle>(handle));

                if (directoryUploads.size() == 4)
                {
                    directoryUploadSignal.notify_one();
                }
            }
            else
            {
                directoryDownloads.push_back(std::const_pointer_cast<TransferHandle>(handle));

                if (directoryDownloads.size() == 4)
                {
                    directoryDownloadSignal.notify_one();
                }
            }
        };

    Aws::Client::ClientConfiguration clientConfiguration;
    clientConfiguration.endpointOverride = endpoint;
    auto s3Client = Aws::MakeShared<Aws::S3::S3Client>("DirectoryDownloadTag", clientConfiguration);

    TransferManagerConfiguration transferManagerConfig(m_executor.get());
    transferManagerConfig.s3Client = s3Client;
    transferManagerConfig.transferInitiatedCallback = transferInitCallback;
    auto transferManager = TransferManager::Create(transferManagerConfig);

     transferManager->DownloadToDirectory(downloadDir, bucket, prefix);

    {
        std::unique_lock<std::mutex> locker(semaphoreLock);
        if (directoryDownloads.size() < 4)
        {
            directoryDownloadSignal.wait(locker);
        }
    }


    for (auto handle : directoryDownloads)
    {
        handle->WaitUntilFinished();
    }
    Aws::ShutdownAPI(options);

```
**SDK version number**
1.8.186-0
**Platform/OS/Hardware/Device**
What are you running the sdk on?

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
See code above
**Expected behavior**

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @alexminnaar ,
Before I go into trying to reproduce this error, can you give me the complete code snippet that reproduces it? On you code I don't see the calls to`Aws::InitAPI()` and `Aws::ShutdownAPI();` which might be the problem.

**Comment by KaibaLopez** [comment]
Hi @alexminnaar ,
Sorry for the lack of response here. 
Kind of hard to pinpoint since I can no longer reproduce but ... I think that the root of your problem are the size comparisons, can you remove those ifs? Or make sure that the number is matches the number of files, (in your case there should be only 4 objects in the bucket). 
```cpp
if (directoryDownloads.size() < 4)
```
```cpp
if (directoryDownloads.size() == 4)
```
