### ISSUE TITLE
Compile fails with dependency on aws-c-auth private headers

### ISSUE THREAD

**Issue by greghogan** [aws/aws-sdk-cpp#1797]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Error when compiling.

**SDK version number**
1.9.95 and later.

**Platform/OS/Hardware/Device**
Amazon Linux 2. GNU Guix.

**To Reproduce (observed behavior)**
When building aws-sdk-cpp with `"-DBUILD_DEPS=OFF"` (having installed the dependent AWS libraries separately) the build fails due to a dependency on the aws-c-auth private libraries which are not installed to the system.

The compile error is:
`/tmp/guix-build-aws-sdk-cpp-1.9.121.drv-0/aws-sdk-cpp-1.9.121-checkout/aws-cpp-sdk-core-tests/aws/auth/AWSAuthSignerTest.cpp:17:10: fatal error: aws/auth/private/aws_signing.h: No such file or directory
 #include <aws/auth/private/aws_signing.h>`

The change was made on 2021-06-04 in commit 23cca02c2df.

**Expected behavior**
Clean build.

**Comment by KaibaLopez** [comment]
Hi @greghogan ,
Can you walk me through how you installed the dependencies separately so I can better reproduce this issue?

**Comment by KaibaLopez** [comment]
@daniloegea ,
Hey and thanks for the workaround! I never got an answer from op but could you tell me how you installed the deps ? Like, can you walk me through your process step by step so I can repro and maybe push this as a change if necessary?

**Comment by daniloegea** [comment]
Hi @KaibaLopez, I didn't do anything special really.

I simply built all the aws-sdk-cpp dependencies (these ones https://github.com/awslabs/aws-crt-cpp/blob/main/.gitmodules) and installed at /usr/local.

Then I built aws-sdk-cpp with -DBUILD_DEPS=OFF so it will look for dependencies installed in the system. The compilation failed due to the error described above. The solution was to patch [aws-c-auth](https://cgit.freebsd.org/ports/tree/security/aws-c-auth) to install the private headers.

It was part of the work to update the aws-sdk-cpp in the FreeBSD ports tree https://cgit.freebsd.org/ports/tree/devel/aws-sdk-cpp/Makefile

I built everything on FreeBSD.

**Comment by ajishna** [comment]
Ran into this issue today. I'm building with aws-sdk-cpp (at 1.9.220 tag), for a custom api gateway client build, with "-DBUILD_DEPS=OFF" and using an exported vcpkg nuget for static libs from aws-sdk-cpp[transfer] which has version 1.9.220
Output:
Build FAILED.

"C:\PROG\hp-surerecover-warrantyauthgateway\src\aws-sdk-cpp\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\PROG\hp-surerecover-warrantyauthgateway\src\aws-sdk-cpp\build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj
" (default target) (5) ->
(ClCompile target) ->
  C:\PROG\hp-surerecover-warrantyauthgateway\src\aws-sdk-cpp\aws-cpp-sdk-core-tests\aws\auth\AWSAuthSignerTest.cpp(17,1
0): fatal error C1083: Cannot open include file: 'aws/auth/private/aws_signing.h': No such file or directory [C:\PROG\h
p-surerecover-warrantyauthgateway\src\aws-sdk-cpp\build\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]

**Comment by jmklix** [comment]
We have recently updated the [build process](https://github.com/aws/aws-sdk-cpp/issues/1888), please let me know if you are still having problems with trying to compile.
