### ISSUE TITLE
Enable gzip/deflate Response Decoding

### ISSUE THREAD

**Issue by jarruda** [aws/aws-sdk-cpp#180]
Introduce an option into ClientConfiguration which will control whether automatic decoding of compressed response bodies is enabled.

WinHTTP must have an option set in order to enable decoding of gzip or deflate-encoded response bodies (https://msdn.microsoft.com/en-us/library/windows/desktop/aa383955%28v=vs.85%29.aspx).

cURL can be controlled by setting the CURLOPT_ACCEPT_ENCODING option (https://curl.haxx.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html).

**Comment by JonathanHenson** [comment]
This is a good idea. I'll keep you posted.

**Comment by JonathanHenson** [comment]
@jarruda Can you give me more of a use case? Apparently this isn't a widely used portion of the Http spec for AWS, and we don't use it except for large Dynamodb payloads.

**Comment by jarruda** [comment]
(sorry for the response 2y later; just noticed it going through my issue inbox)

I don't have a use case relating to current AWS services.  In monitoring my browsers requests via proxy, it seems almost all of them are gzip encoded to most websites, so for the service I was implementing at the time I desired to also use gzip in the response to speed up download speeds of a sizeable JSON file.

As an aside, I try to pull in as few dependencies as possible for most small projects.  Since the HTTP client is exposed in the SDK, I prefer to use that as the only HTTP client my program will use in addition to AWS requestss, so this feature is desirable in those circumstances as well.

**Comment by marcomagdy** [comment]
You can add the HTTP header "Content-Encoding" to the http request object via its AddHeader API.
