### ISSUE TITLE
Error get cognito identity ID on AARCH64 platform

### ISSUE THREAD

**Issue by jeffwang512021** [aws/aws-sdk-cpp#1800]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
ARM Aarch64

**Describe the question**
Hello,

I've cross-compiled aws-sdk-cpp on arm aarch64 platform following the link [https://github.com/aws/aws-sdk-cpp/issues/1288](url), but when I tried to get AWS cognito identity ID with the below test code, an error was reported as:
_GetId failed: curlCode: 1, Unsupported protocol_

The curl, openssl, zlib were built also with the same cross-compiling toolchain as to build the aws-sdk-cpp following the above link [https://github.com/aws/aws-sdk-cpp/issues/1288](url). 
But if I build aws-sdk-cpp and the test code with the standard Ubuntu gcc toolchain (without building curl, openssl and zlib separately, but use the stuff from the standard toolchain or through "sudo apt install"), the test code could run correctly.
So any idea what's going wrong? many thanks!

The test code piece is:

    GetIdRequest getIdRequest;
    getIdRequest.WithIdentityPoolId("us-east-1:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx");

    ClientConfiguration clientConfig;
    clientConfig.region = Aws::Region::US_EAST_1;

    auto client = Aws::MakeShared<Aws::CognitoIdentity::CognitoIdentityClient>("cognito_client", clientConfig);
    //auto iamClient = Aws::MakeShared<Aws::IAM::IAMClient>("iam_client", clientConfig);
    //Aws::AccessManagement::AccessManagementClient accessManagementClient(iamClient, client);

    GetIdOutcome getIdOutcome = client->GetId(getIdRequest);
    if (getIdOutcome.IsSuccess()) {
    	GetCredentialsForIdentityRequest getCredentialsRequest;
    	getCredentialsRequest.WithIdentityId(getIdOutcome.GetResult().GetIdentityId());
    	std::cout << "Identity ID: " << getIdOutcome.GetResult().GetIdentityId() << std::endl;
    } else {
    	std::cout<< " GetId failed : " << getIdOutcome.GetError().GetMessage()<< std::endl;
    }

**Comment by KaibaLopez** [comment]
Hi @jeffwang512021 ,
I think I am missing something, but did you end up making it work it's just that the guide might be outdated on it's version instructions or were you unable to have it cross compile but it worked when just building ?

**Comment by jeffwang512021** [comment]
@KaibaLopez,
So sorry I forgot to update this thread...
It's been fixed already, and the cause is with the openssl library which may be lack of support of https. 
But it's fixed already. Thanks a lot for your help on this anyway! :)
