### ISSUE TITLE
vague error report from windows usage of aws-sdk-core

### ISSUE THREAD

**Issue by dhoke4tdb** [aws/aws-sdk-cpp#1803]
**Is your feature request related to a problem? Please describe.**
on github actions runners windows-2019/windows-2016, communicating with minio
Error "Encountered network error when sending http request" reported,
apparently generated in aws-sdk-core, WinSyncHttpClient.cpp, 
```
std::shared_ptr<HttpResponse> WinSyncHttpClient::MakeRequest(const std::shared_ptr<HttpRequest>& request,
        Aws::Utils::RateLimits::RateLimiterInterface* readLimiter,
        Aws::Utils::RateLimits::RateLimiterInterface* writeLimiter) const
```
the only place I found that exact text.

**Describe the solution you'd like**
Have the SDK return more exact information including any native environment error information and the more specific path where the error occurred.  
This error seems like it could have been caused by failures in either of 
```
bool WinHttpSyncHttpClient::DoSendRequest(void* hHttpRequest) const
```
where a failure of 
```
    auto rval = WinHttpSendRequest(hHttpRequest, NULL, NULL, 0, 0, 0, NULL);
```
should have resulted in a native environment error that could be retrieved by windows API GetLastError(),
OR a failure in 
```
bool WinSyncHttpClient::StreamPayloadToRequest(const std::shared_ptr<HttpRequest>& request, void* hHttpRequest, Aws::Utils::RateLimits::RateLimiterInterface* writeLimiter) const
```
which appears to have multiple locations where a failure may have occurred.
Currently it is not possible to even tell in which of those routines the failure may have occurred, much less what the exact nature of the failure is.

**Describe alternatives you've considered**
Making local mods to the SDK version used to more specifically identify path and nature of error occurring so that SDK clients can report more detail as to possible errors occurring, generating patches from those changes to patch the version of SDK we currently use for our application's build process.

**Additional context**
We are currently using 1.8.84, but an examination of branch "main" around oct 21, 2021 (probably equivalent to tag 1.9.128) found the error reporting to be similar in nature.

**Comment by dhoke4tdb** [comment]
FWIW, a branch, "tag.1.8.84" in fork https://github.com/dhoke4tdb/aws-sdk-cpp, 
shows via individual added patches, the various incremental diagnostic changes I made hunting the cause of failure (in the sdk codebase using an API [WinHttp], lacking any knowledge of either, prior to starting the hunt).
(The current state of the branch has all of those patches applied, might be a few other changes not reflected in the individual patches.)

Thought it might help with showing areas where more specific reports of source points of failure and specific (native) errors could be helpful to others chasing any encountered problems currently obscured by the rather nebulous "Encountered network error when sending http request".

The current immediate problem was found to simply be a too low timeout value (for Aws::Client::ClientConfiguration::requestTimeoutMs) which had been set by the client application using the aws core sdk, (resulting in fairly frequent windows WinHttp error of 12002, ERROR_HTTP_TIMEOUT communicating with minio in a github actions CI windows runner.  FWIW, this same timeout value does not seem to be a problem for *nix application version in the related sibling *nix environments.  Whether the lowered timeout is a problem communicating with actual S3 is yet to be determined, but suspecting it might given the current scenario is an entirely on-node situation where live environment will generally involve off-node communications.)

**Comment by KaibaLopez** [comment]
Hi @dhoke4tdb ,
Thanks for bringing this up to us and sorry for the slow response, I'll bring it up to the team and see how possible it'd be to implement this. 
I will say that the easiest way to get this going is to have a sample that showcases where the SDK is lacking. I would wait for that though as I am afraid we won't have the bandwidth to implement this and I don't want to ask you to put more time into it and it not going anywhere.
