### ISSUE TITLE
Any example how to upload files to s3?

### ISSUE THREAD

**Issue by chebz** [aws/aws-sdk-cpp#181]
In particular I was trying to upload a png file. There is a  putObjectRequest.SetBody(); function but it only accepts string stream. How can I upload an image file?

**Comment by JonathanHenson** [comment]
SetBody accepts any arbitrary iostream.

**Comment by chebz** [comment]
Well I can't just put IFStream/FStream there, And I am not sure how to do it otherwise.

**Comment by JonathanHenson** [comment]
You can put fstream. See the Readme which has a sample. Also have a look at the s3 integration tests which also do this.

**Comment by chebz** [comment]
yeah figured it out, like I've said in the email, I've tried using ifstream whereas I should have been using fstream. Thanks!

**Comment by frank51212** [comment]
Can I please have some sample code as well as I am trying to the exactly same thing? In particular, how am I suppose to open a local png file and then make iostream that is acceptable by putObjectRequest.SetBody() ?

**Comment by gopi77** [comment]
Hi

As per this link, https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/
I made a project and able to upload the string example.

Then i tried to upload a jpeg file as per this link, https://forums.aws.amazon.com/thread.jspa?messageID=712685

But the putObjectOutcome is failure.
The error is >> Error while putting Object BadRequest Unable to parse ExceptionName: BadRequest Message: An error occurred when parsing the HTTP request.


My code is below.

int main()
{
    Aws::SDKOptions options;
    Aws::InitAPI(options);
    S3Client client;
    
    //first put an object into s3
    PutObjectRequest putObjectRequest;
    putObjectRequest.WithKey(KEY)
           .WithBucket(BUCKET);
#if 0
    //this can be any arbitrary stream (e.g. fstream, stringstream etc...)
    auto requestStream = Aws::MakeShared<Aws::StringStream>("s3-sample");
    *requestStream << "Emoji s3 upload test";

    //set the stream that will be put to s3
    putObjectRequest.SetBody(requestStream);
#else
	string filePATH = "planets.jpg";

	//PutObjectRequest putObjectRequest;
	//putObjectRequest.SetBucket(S3_BUCKET);
	std::shared_ptr<Aws::FStream> fileToUpload = Aws::MakeShared<Aws::FStream>("OCRFile", filePATH, ios::in | ios::binary | ios::trunc);
	putObjectRequest.SetBody(fileToUpload);
	putObjectRequest.SetContentType("image/jpeg");
	putObjectRequest.SetContentLength(static_cast<long>(putObjectRequest.GetBody()->tellg()));
	//putObjectRequest.SetContentMD5(HashingUtils::Base64Encode(HashingUtils::CalculateMD5(*putObjectRequest.GetBody())));
	//PutObjectOutcome putObjectOutcome = s3Client.PutObject(putObjectRequest);

#endif
    auto putObjectOutcome = client.PutObject(putObjectRequest);

    if(putObjectOutcome.IsSuccess())
    {
        std::cout << "Put object succeeded" << std::endl;
    }
    else
    {
        std::cout << "Error while putting Object " << putObjectOutcome.GetError().GetExceptionName() << 
               " " << putObjectOutcome.GetError().GetMessage() << std::endl;
    }
.....
.....

Please let me know if anyone fixed it.

Thanks
Gopi. J
