### ISSUE TITLE
When build aws-sdk-cpp, got "Unknown CMake command "aws_use_package"

### ISSUE THREAD

**Issue by chubin** [aws/aws-sdk-cpp#1811]
Confirm by changing [ ] to [x] below to ensure that it's a bug:

I've gone though Developer Guide and API reference

    I've searched for previous similar issues and didn't find any solution

The same problem as #1770, but I have Linux, and now Windows.

That's how I build it:

```
cmake ../ \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DCMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES=$PREFIX/include \
    -DCMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES=$PREFIX/include \
    -DCMAKE_BUILD_TYPE=Release \
    -DCUSTOM_MEMORY_MANAGEMENT=OFF \
    -DBUILD_ONLY="s3"
```

I use this: github.com/aws/aws-sdk-cpp/archive/1.9.144.tar.gz as the source code.

I've read the comment about the submodule, but I wuld like to build it from the source code archive

**Comment by KaibaLopez** [comment]
@chubin,
So, because of the way we are consuming our dependencies with github submodules, the recommended way is to use `git clone --recursive` to get the SDK and it's dependencies.
Not being able to build directly from the zip file is a known issue for us and something we are working on fixing, but on the mean time we do have a sort of workaround in the form of a building script: `prefetch_crt_dependency.sh` , try running it before building the SDK, and let me know if it works for you.

**Comment by chubin** [comment]
In my environment, I don't have Internet access during the build time, and so it is not really an option to me.
In general, it is a good approach to have everything in the "input" archive/directory/whatever, just to be able
to reproduce the build anytime. Maybe you have some other archive, where you have all the submodules inside?

**Comment by chubin** [comment]
Do not use `prefetch_crt_dependency.sh` to fetch the dependencies!
This script seems to fetch outdated dependencies, and the whole project does not compile.

If you fetch the actual dependencies with `git clone --recurive`, everything works

**Comment by KaibaLopez** [comment]
@chubin, can you specify which dependencies you had a problem with? Like what error did you get when running the `prefetch_crt_dependency.sh` script?

**Comment by chubin** [comment]
When I use the script, I have exactly the problems as in #1795.
When I don't use the script, and checkout with `git --recursive`, everything just works.

**Comment by KaibaLopez** [comment]
@chubin , and are you using gcc 11 as well?

**Comment by chubin** [comment]
Yes, I am using GCC 11.2

**Comment by KaibaLopez** [comment]
oh then yea the script is probably out of date, I'll see about getting that fixed, thanks.

**Comment by hardikmdev** [comment]
Please have a look for updated `prefetch_crt_dependency.sh` at PR [https://github.com/aws/aws-sdk-cpp/pull/1814](https://github.com/aws/aws-sdk-cpp/pull/1814)
