### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by rkoo19** [aws/aws-sdk-cpp#1813]
Confirm by changing [ ] to [x] below:
- [ x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?

MacOS (on Docker)

**Describe the question**

Hi, I'm trying to install aws-sdk-cpp to a Docker container image on my Mac. I am installing aws-sdk-cpp because I need to download the [AWS S3 PyTorch plug-in](https://aws.amazon.com/blogs/machine-learning/announcing-the-amazon-s3-plugin-for-pytorch/) and aws-sdk-cpp is required for the plug-in's install.

This is the script I am running in my Docker container image CLI to install everything I need:

![Screen Shot 2021-11-15 at 9 51 03 PM](https://user-images.githubusercontent.com/24364976/141887129-0323fc24-bb5a-45cb-88ef-ec1a3d6d0c22.png)

However, I am getting this error when running the _make install_:

![Screen Shot 2021-11-15 at 7 02 46 PM](https://user-images.githubusercontent.com/24364976/141886927-45e70438-6b5e-4f5f-83a3-fd12d74a39c2.png)

I haven't been able to find anything on the issue and I was looking to get some help. Thank you!

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by jmklix** [comment]
What openssl version do you have?
You can get this with: `openssl version`

Also make sure to run `make` before you run `make install`
