### ISSUE TITLE
CRTLogSystem.cpp:60:13: too many initializers for ‘aws_logger_vtable’

### ISSUE THREAD

**Issue by ferdiko** [aws/aws-sdk-cpp#1818]
Confirm by changing [ ] to [x] below:
- [X ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Ubuntu 18.04

**Describe the question**
When building `core`  from source, I get the following error. For building I use ```cmake .. -DBUILD_ONLY="core" -DCMAKE_BUILD_TYPE=Release``` (inside `build` directory) and the error occurs when then calling `make -j16`.

**Logs/output**
```
[ 90%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/ub_core.cpp.o
In file included from XXX/aws-sdk-cpp/build/aws-cpp-sdk-core/ub_core.cpp:28:0:
XXX/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/logging/CRTLogSystem.cpp:60:13: error: too many initializers for ‘aws_logger_vtable’
             };
             ^
aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/build.make:866: recipe for target 'aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/ub_core.cpp.o' failed
make[2]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/ub_core.cpp.o] Error 1
CMakeFiles/Makefile2:804: recipe for target 'aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/all' failed
make[1]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by ferdiko** [comment]
I tried using both `cmake 3.18.2` and `cmake 3.19.6`. My OpenSSL version is `1.1.1l`

**Comment by jmklix** [comment]
Can you make sure that you are downloading the submodules before you try to build this sdk?

If you’ve already downloaded source code for SDK for C++, e.g. in directory aws-sdk-cpp, you can update the git submodule by:
```sh
cd aws-sdk-cpp
git checkout main
git pull origin main
git submodule update --init --recursive
```
