### ISSUE TITLE
A temporary credentials from STS service expires during a request?

### ISSUE THREAD

**Issue by lsong0905** [aws/aws-sdk-cpp#1828]
Hello,

I am wondering what would happen if 
1. User gets a valid temporary credentials (keyID, secret and sessionToken) from STS service via assumeRole request
2. Let's say the temp credentials only lasts for 15 mins. 
3. User creates a S3 client with the temp credentials and initiates a GET request that will take 30 min to finish

This is a one single GET request that will take 30 mins to finish, and the temp credentials in the S3 client is only
valid for the first 15 mins. In this case, is the user getting a failure in the middle of the request, say after 15 mins after
the initiation of the GET request? Or, is the request expected to finish without error?

If it is the formal case, what would be the suggestion to resolve such issue?

Thank you in advance!

**Comment by KaibaLopez** [comment]
Hi @lsong0905 ,
In short, the credentials are verified per request and not per Client creation, once that request is sent and the credentials are marked as valid for the operation then it wouldn't matter if they became invalid during the time it took to complete.

In your example you are using big time frames and those are kind of hard to imagine, so let's instead imagine you try a getObject request in the last second for which your credentials are valid:
In this scenario, the SDK sends the getObject request and the s3 service api does the validation, it decides they are and the download goes through and completes even after the credentials expire, there is no "for each byte" or "check again at the end of the request" validations.
Now, if the single operation takes 30ish minutes then there might be more going on in the background. 
For example, it could be that you are trying to get a HUGE file and so you'd have to use a multipart download, and those are really a lot of requests, as soon as one of those start after the credentials expire then it would fail. 
Hope that makes sense, let me know if something is unclear
