### ISSUE TITLE
Invoking lambdas : double free or corruption (!prev)

### ISSUE THREAD

**Issue by rahulbhalerao001** [aws/aws-sdk-cpp#183]
When invoking a large number of lambdas - > 500 to 1000, I am getting the following exception.
```
*** Error in `./s3-sample': double free or corruption (!prev): 0x00000000018ce630 ***
Aborted (core dumped)

```
My code is :
```
    std::vector<Aws::Lambda::Model::InvokeOutcomeCallable> futures;
    Aws::Lambda::Model::InvokeRequest invoke request
    invokerequest.WithFunctionName("testLam");
    Aws::Lambda::LambdaClient lambdaClient{config};
    for(int i =0; i < 1000; i++)
        futures.push_back(lambdaClient.InvokeCallable(invoke request))
    int success = 0, failures = 0;
    for(auto &e : futures){
        auto invokeOutcome = e.get();
        if(invokeOutcome.IsSuccess())
                success += 1;
        else
                failures += 1;
        }
    }
```

**Comment by bretambrose** [comment]
Hi,

I spent a little time investigating your issue this morning.  I can't say for certain that I know what's going wrong in your run, but I was able to use your code and "successfully" crash.  In my runs, the process crashes due to excessive thread creation.  With a standard ClientConfiguration, each request goes through the default executor, which drops the request into a new thread.  When you spawn 1000 requests in short order, you end up spawning 1000 threads as well.

If this is a use case that you need to support, we recommend you use the new PooledThreadExecutor that was added a few weeks back.  For information on how to use it, see https://aws.amazon.com/blogs/developer/using-a-thread-pool-with-the-aws-sdk-for-c/ .  This executor puts a controllable limit on the number of allocated threads, and your example should end up behaving.

**Comment by JonathanHenson** [comment]
std::async goes through the default c++ behavior. To utilize the thread executor implementation you need to use the *Async functions instead of the *Callable functions.

**Comment by rahulbhalerao001** [comment]
Thank you @bretambrose  and @JonathanHenson. Thank you for your suggestion about using the thread pool executor.

However, I feel the issue for my crash was a multithreading issue in the open ssl and thus the curl module.
Openssl recommends setting up 2 callbacks when using their code in multithreading. So I used the 2 callbacks from http://stackoverflow.com/a/27567259, and that solved my issue. 

But I am still getting a lot of valgrind errors, but they are not causing a crash even after 10's of invocations.

**Comment by JonathanHenson** [comment]
I'm pushing out a change later today that will automatically handle this
for you (symmetric ciphers for crypto that install thread safety callbacks
into openssl by default). I didn't see in problems in our valgrind run
though. What version of OpenSSL are you running?

On Mon, May 23, 2016 at 11:30 AM, Rahul Bhalerao <notifications@github.com>
wrote:

> Thank you @bretambrose <https://github.com/bretambrose> and
> @JonathanHenson <https://github.com/JonathanHenson>. Thank you for your
> suggestion about using the thread pool executor.
>
> However, I feel the issue for my crash was a multithreading issue in the
> open ssl and thus the curl module.
> Openssl recommends setting up 2 callbacks when using their code in
> multithreading. So I used the 2 callbacks from
> http://stackoverflow.com/a/27567259, and that solved my issue.
>
> But I am still getting a lot of valgrind errors, but they are not causing
> a crash even after 10's of invocations.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-sdk-cpp/issues/183#issuecomment-221048597>
>



-- 
"The poet only asks to get his head into the heavens. It is the logician
who seeks to get the heavens into his head. And it is his head that splits"
--G. K. Chesterton-- "Orthodoxy"

**Comment by rahulbhalerao001** [comment]
I get the valgrind dump as attached for the parallel lambda launch.[valgrind_parallel_lambda_.txt](https://github.com/aws/aws-sdk-cpp/files/278129/valgrind_parallel_lambda_.txt)

But this might be a valgrind bug, as running 100-300 parallel lambda does not show an error and we get this for the 1000 case:

> vg_alloc_ThreadState: no free slots available
> Increase VG_N_THREADS, rebuild and try again.
> 
> valgrind: the 'impossible' happened:
>    VG_N_THREADS is too low

Also for the sample S3 code :
```
void download_file(const char *bucket_name, const char *key, const char *path){
        Aws::Client::ClientConfiguration config;
        config.region = Aws::Region::EU_WEST_1;
        static const char* ALLOCATION_TAG = "BucketAndObjectOperationTest";
        S3Client s3Client{config};
        GetObjectRequest getObjectRequest2;
        getObjectRequest2.SetBucket(bucket_name);
        getObjectRequest2.SetKey(key);
        getObjectRequest2.SetResponseStreamFactory(
            [=](){
                return Aws::New<Aws::FStream>(ALLOCATION_TAG, path, std::ios_base::out | std::ios_base::in | std::ios_base::trunc);
            }
        );
        GetObjectOutcome getObjectOutcome2 = s3Client.GetObject(getObjectRequest2);
        if(getObjectOutcome2.IsSuccess()){
                std::cout << "Download Successful" << std::endl;
        }else{
                std::cout << "Download Failed" << std::endl;
                exit(1);
        }
}
```
I get a huge valgrind dump [valgrind_s3_dump.txt](https://github.com/aws/aws-sdk-cpp/files/278127/valgrind_s3_dump.txt)

It will be great if you could have a look once, as this is almost the same code from the tests.

**Comment by JonathanHenson** [comment]
vg_alloc_ThreadState: no free slots available
Increase VG_N_THREADS, rebuild and try again.

valgrind: the 'impossible' happened:
VG_N_THREADS is too low


means you are out of threads. That's why we are recommending you use the
thread pool with the *Async api.


The issues in the s3 dump are mostly innocuous libcurl issues.



On Mon, May 23, 2016 at 12:47 PM, Rahul Bhalerao <notifications@github.com>
wrote:

> I get the valgrind dump as attached for the parallel lambda launch.
> valgrind_parallel_lambda_.txt
> <https://github.com/aws/aws-sdk-cpp/files/278129/valgrind_parallel_lambda_.txt>
>
> But this might be a valgrind bug, as running 100-300 parallel lambda does
> not show an error and we get this for the 1000 case:
>
> vg_alloc_ThreadState: no free slots available
> Increase VG_N_THREADS, rebuild and try again.
>
> valgrind: the 'impossible' happened:
> VG_N_THREADS is too low
>
> Also for the sample S3 code :
>
> void download_file(const char *bucket_name, const char *key, const char *path){
>         Aws::Client::ClientConfiguration config;
>         config.region = Aws::Region::EU_WEST_1;
>         static const char* ALLOCATION_TAG = "BucketAndObjectOperationTest";
>         S3Client s3Client{config};
>         GetObjectRequest getObjectRequest2;
>         getObjectRequest2.SetBucket(bucket_name);
>         getObjectRequest2.SetKey(key);
>         getObjectRequest2.SetResponseStreamFactory(
>             [=](){
>                 return Aws::New<Aws::FStream>(ALLOCATION_TAG, path, std::ios_base::out | std::ios_base::in | std::ios_base::trunc);
>             }
>         );
>         GetObjectOutcome getObjectOutcome2 = s3Client.GetObject(getObjectRequest2);
>         if(getObjectOutcome2.IsSuccess()){
>                 std::cout << "Download Successful" << std::endl;
>         }else{
>                 std::cout << "Download Failed" << std::endl;
>                 exit(1);
>         }
> }
>
> I get a huge valgrind dump valgrind_s3_dump.txt
> <https://github.com/aws/aws-sdk-cpp/files/278127/valgrind_s3_dump.txt>
>
> It will be great if you could have a look once, as this is almost the same
> code from the tests.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-sdk-cpp/issues/183#issuecomment-221075354>
>



-- 
"The poet only asks to get his head into the heavens. It is the logician
who seeks to get the heavens into his head. And it is his head that splits"
--G. K. Chesterton-- "Orthodoxy"

**Comment by rahulbhalerao001** [comment]
Ok yes agreed with both the statements. S3 issues seem innocuous as they don't cause a crash. Thank you for your prompt replies.
