### ISSUE TITLE
AWS SDK tests cannot be built with GCC 11 for version 1.9.165

### ISSUE THREAD

**Issue by ravindra-wagh** [aws/aws-sdk-cpp#1831]
Getting following compilation error:

> aws-cpp-sdk-identity-management-tests/CMakeFiles/aws-cpp-sdk-identity-management-tests.dir/auth/STSProfileCredentialsProviderTest.cpp.o
> /AWS/aws-sdk-cpp/aws-cpp-sdk-identity-management-tests/auth/STSAssumeRoleCredentialsProviderTest.cpp: In member function 'virtual void {anonymous}::STSAssumeRoleCredentialsProviderTest_TestCredentialsCacheExpiry_Test::TestBody()':
> /AWS/aws-sdk-cpp/aws-cpp-sdk-identity-management-tests/auth/STSAssumeRoleCredentialsProviderTest.cpp:145:23: error: 'sleep_for' is not a member of 'std::this_thread'
>   145 |     **std::this_thread::sleep_for(std::chrono::seconds(1));**
>       |                       ^~~~~~~~~
> make[3]: *** [aws-cpp-sdk-identity-management-tests/CMakeFiles/aws-cpp-sdk-identity-management-tests.dir/auth/STSAssumeRoleCredentialsProviderTest.cpp.o] Error 1
> make[3]: *** Waiting for unfinished jobs....
> [       OK ] AWSClientTestSuite.TestStandardRetryStrategy (4993 ms)

This is issue needs to apply the same fix as in https://github.com/aws/aws-sdk-cpp/issues/1826.

**Comment by KaibaLopez** [comment]
oh.. ok thanks for pointing this out to us!

**Comment by KaibaLopez** [comment]
This fix has been merged, and it will be part of the next release.
Thanks!
