### ISSUE TITLE
Easy to use, header only DynamoDB

### ISSUE THREAD

**Issue by OptimisticMonkey** [aws/aws-sdk-cpp#1835]
Would be great to have a single header only include just for DynamoDB instead of having to deal with the entire AWS SDK.

Just an idea.

**Comment by KaibaLopez** [comment]
Hi @OptimisticMonkey ,
So depending on what you mean by this, it is already a feature?
`cmake -DBUILD_ONLY=dynamodb` 
Should only build dynamodb and core, so you could just inlcude that to your app.
Is that what you mean though?

**Comment by OptimisticMonkey** [comment]
Thanks @KaibaLopez - That is pretty much what I was looking for :-)    I did just stumble onto aws API Gateway.  Going to use that with aws lambda to query DynamoDB table instead.  So turns out my game doesnt need the SDK at all anyway.

**Comment by KaibaLopez** [comment]
alright, I'll go ahead and close this issue then.
