### ISSUE TITLE
Mingw-w64 compilation support

### ISSUE THREAD

**Issue by slonm** [aws/aws-sdk-cpp#1836]
I would like contribute Mingw-w64 compilation support. It requires:

- Changed case of Windows headers to lower case
- Added undefine WinAPI defines for "interface", "GetObject", "ERROR" when names clash appear
- removed -fPIC compiler option for Windows
- Replace _WIN32 to _MSC_VER or viceversa when needed

Changes affect to aws-sdk-cpp project and crt dependent projects. 

Changes to aws-sdk-cpp provided in PR https://github.com/aws/aws-sdk-cpp/pull/1832

Can anybody help me make contribution correctly?

**Comment by KaibaLopez** [comment]
Hi @slonm ,
Thanks for the feature request and the PRs!

**Comment by jmklix** [comment]
Thanks for taking the time to create the PR, but we have decided to not accept it right now. It can be difficult to support any additional complexities that may arise because of this so I will be closing this feature request and the related PR
