### ISSUE TITLE
project compilation crashes at ub_EC2.cpp

### ISSUE THREAD

**Issue by anatol** [aws/aws-sdk-cpp#1838]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I am trying to compile the project at Arch Linux with following compilation steps:
```
 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCUSTOM_MEMORY_MANAGEMENT=OFF -DENABLE_TESTING=OFF -DBUILD_DEPS=OFF \
      -DCMAKE_MODULE_PATH=/usr/lib/cmake \
      -S . -B build -G Ninja
  ninja -C build -j 2
```

I have a relatively powerful machine with 8 cores and 16G. Never had compilation issues with other heavy projects. But starting with recent aws-sdk-cpp releases I see following compilation crash, always at the same place:

```
[101/688] Building CXX object aws-cpp-sdk-elasticmapreduce/CMakeFiles/aws-cpp-sdk-elasticmapreduce.dir/ub_ELASTICMAPREDUCE.cpp.o
[102/688] Building CXX object aws-cpp-sdk-elastictranscoder/CMakeFiles/aws-cpp-sdk-elastictranscoder.dir/ub_ELASTICTRANSCODER.cpp.o
[103/688] Building CXX object aws-cpp-sdk-email/CMakeFiles/aws-cpp-sdk-email.dir/ub_EMAIL.cpp.o
[104/688] Building CXX object aws-cpp-sdk-emr-containers/CMakeFiles/aws-cpp-sdk-emr-containers.dir/ub_EMR-CONTAINERS.cpp.o
[105/688] Building CXX object aws-cpp-sdk-marketplace-entitlement/CMakeFiles/aws-cpp-sdk-marketplace-entitlement.dir/ub_MARKETPLACE-ENTITLEMENT.cpp.o
[106/688] Building CXX object aws-cpp-sdk-es/CMakeFiles/aws-cpp-sdk-es.dir/ub_ES.cpp.o
[107/688] Building CXX object aws-cpp-sdk-eventbridge/CMakeFiles/aws-cpp-sdk-eventbridge.dir/ub_EVENTBRIDGE.cpp.o
[108/688] Building CXX object aws-cpp-sdk-ec2/CMakeFiles/aws-cpp-sdk-ec2.dir/ub_EC2.cpp.o
FAILED: aws-cpp-sdk-ec2/CMakeFiles/aws-cpp-sdk-ec2.dir/ub_EC2.cpp.o 
/usr/bin/c++ -DAWS_AUTH_USE_IMPORT_EXPORT -DAWS_CAL_USE_IMPORT_EXPORT -DAWS_CHECKSUMS_USE_IMPORT_EXPORT -DAWS_COMMON_USE_IMPORT_EXPORT -DAWS_COMPRESSION_USE_IMPORT_EXPORT -DAWS_CRT_CPP_USE_IMPORT_EXPORT -DAWS_EVENT_STREAM_USE_IMPORT_EXPORT -DAWS_HTTP_USE_IMPORT_EXPORT -DAWS_IO_USE_IMPORT_EXPORT -DAWS_MQTT_USE_IMPORT_EXPORT -DAWS_MQTT_WITH_WEBSOCKETS -DAWS_S3_USE_IMPORT_EXPORT -DAWS_SDKUTILS_USE_IMPORT_EXPORT -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=9 -DAWS_SDK_VERSION_PATCH=167 -DAWS_USE_EPOLL -DENABLE_CURL_CLIENT -DENABLE_OPENSSL_ENCRYPTION -DHAS_PATHCONF -DHAS_UMASK -DPLATFORM_LINUX -Daws_cpp_sdk_ec2_EXPORTS -I/build/aws-sdk-cpp/src/aws-sdk-cpp-1.9.167/aws-cpp-sdk-ec2/include -I/build/aws-sdk-cpp/src/aws-sdk-cpp-1.9.167/aws-cpp-sdk-core/include -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto -O3 -DNDEBUG -fPIC -fno-exceptions -std=c++11 -Wall -Werror -pedantic -Wextra -DS2N_SIKE_P434_R3_ASM -DS2N_BIKE_R3_AVX2 -DS2N_BIKE_R3_AVX512 -DS2N_BIKE_R3_PCLMUL -DS2N_BIKE_R3_VPCLMUL -DS2N_KYBER512R3_AVX2_BMI2 -DS2N_ADX -DS2N_HAVE_EXECINFO -DS2N_CPUID_AVAILABLE -fPIC -DS2N_FALL_THROUGH_SUPPORTED -DS2N___RESTRICT__SUPPORTED -DS2N_LIBCRYPTO_SUPPORTS_EVP_MD5_SHA1_HASH -pthread -MD -MT aws-cpp-sdk-ec2/CMakeFiles/aws-cpp-sdk-ec2.dir/ub_EC2.cpp.o -MF aws-cpp-sdk-ec2/CMakeFiles/aws-cpp-sdk-ec2.dir/ub_EC2.cpp.o.d -o aws-cpp-sdk-ec2/CMakeFiles/aws-cpp-sdk-ec2.dir/ub_EC2.cpp.o -c /build/aws-sdk-cpp/src/aws-sdk-cpp-1.9.167/build/aws-cpp-sdk-ec2/ub_EC2.cpp
{standard input}: Assembler messages:
{standard input}:1625555: Warning: end of file in string; '"' inserted
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[109/688] Building CXX object aws-cpp-sdk-events/CMakeFiles/aws-cpp-sdk-events.dir/ub_EVENTS.cpp.o
ninja: build stopped: subcommand failed.
```

I do not know whether it is a compile issue or the project issue. Please let me know if you need additional information.

**SDK version number**
1.9.167

** Compiler **
```
/usr/bin/c++ --version
c++ (GCC) 11.1.0
```

**Platform/OS/Hardware/Device**
Arch Linux

**Comment by KaibaLopez** [comment]
Hi @anatol ,
Hmmm I'll try and take a closer look to this but in the mean time, and just as a general thing to maybe help, I would suggest adding the specific services you plan on using to the cmake command via `-DBUILD_ONLY`, hopefully this could unblock you even if just a bit, but most importantly you don't have to build the whole SDK when you are not planning to use all of the aws services on your project, for example if you are planning on using s3 and dynamodb :
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCUSTOM_MEMORY_MANAGEMENT=OFF -DENABLE_TESTING=OFF -DBUILD_DEPS=OFF \
      -DCMAKE_MODULE_PATH=/usr/lib/cmake -DBUILD_ONLY="s3;dynamodb" \
      -S . -B build -G Ninja
```
Anyways, yea I'll update as soon as I find something.

**Comment by anatol** [comment]
Thanks for the response @KaibaLopez. I am actually trying to update the [official Arch Linux package](https://github.com/archlinux/svntogit-community/blob/packages/aws-sdk-cpp/trunk/PKGBUILD) for this SDK and want to include as many components as possible to add more flexibility to the users.

I wonder if it is some bug caused by GCC11 + large ub_EC2.cpp file.

**Comment by jmklix** [comment]
@anatol can you successfully build a few of the services at all?

**Comment by colintoal** [comment]
Experiencing the same problem building AWS SDK. Many of the services build - but it consistently fails on ub_EC2.cpp.

**Comment by anatol** [comment]
@jmklix I was able to "fix" the issue by updating all `aws-*` dependencies to its latest versions. I still don't really know what happened with the compiler and `ub_EC2.cpp`.
