### ISSUE TITLE
Use latest aws-sdk-cpp lib that supported Toolset 120 (VS2013)

### ISSUE THREAD

**Issue by euser153** [aws/aws-sdk-cpp#1841]
### Describe the issue

Hi
We want to upgrade our current aws-cpp-sdk library version which is 1.6.25.
We have a limitation as we can support only VS 2013 (toolset 120).

I have tried to build newer versions with our toolset, the latest ive succeed was 1.6.53.

When trying above this version, for example 1.7.43 (which states its supported VS 2013 and above), it failed in the submodules (aws-c-common, aws-checksums..) with errors related to C++ 11 .

This is one example of the commands im running :
cmake.exe aws-sdk-cpp -G "Visual Studio 12 Win64" -T v120 -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY=core

C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe ..\aws-cpp-sdk-core\ALL_BUILD.vcxproj -p:Configuration=Release

As mentioned, for 1.6.53 it succeed, for 1.7.43 it failed at the cmake stage.
Example for one error of many:
AwsCCommon\include\aws/common/array_list.inl(199): error C2143: syntax error : missing ';' before '{'

What is the highest version that should be supported for VS 2013?
Am i missing something related to the cmake stage?

Thanks!

### Steps to Reproduce

building via this commands, new versions

cmake.exe aws-sdk-cpp -G "Visual Studio 12 Win64" -T v120 -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY=core

C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe ..\aws-cpp-sdk-core\ALL_BUILD.vcxproj -p:Configuration=Release

### AWS CPP SDK version used

1.6.25.

### compiler and version used

Visual Studio

### Operating System and version

Windows

**Comment by jmklix** [comment]
This sdk has never and will not support VS 2013.

I am sorry to inform you that you will not be able to use this sdk if you have to use VS 2013. You are not missing anything related to cmake. This was decided during the initial development of this sdk.
