### ISSUE TITLE
Expire token error code?

### ISSUE THREAD

**Issue by lsong0905** [aws/aws-sdk-cpp#1843]
### Describe the issue

Hello,

When I issue a S3 request(PUT, GET, etc) with an expire credentials (generated by STS service), the S3 SDK seems returning  UNKNOWN = 100 error code from S3Errors.h. The error message "ExpiredToken:Unable to parse ExceptionName: ExpiredToken Message: The provided token has expired." , on the other hand, seems containing some hint that indicates why the request failed. 

Other than parsing the error message, is there any better way to verify the request failed due to "ExpiredToken"? I expected to receive an error code that maps to "ExpiredToken" in S3Errors.h, but it is returning UNKNOWN = 100 error code. I am not certain if this is intentional. 

Thank you in advance!

### AWS CPP SDK version used

1.7.29

### compiler and version used

na

### Operating System and version

na

**Comment by KaibaLopez** [comment]
Hi @lsong0905 ,
Short answer is no.
Error handling is always somewhat problematic for the SDK as it is heavily limited to what the service APIs models provide. We have to keep parity with them and so there is a limit to what we can change there, and the api sends error 100 (which can mean anything really) and the message with the description. Admittedly, it could be "catched" by reading the error but making those kinds of checks is a rabbit hole we are just not looking to get into.

Let me know if that answers your question.
