### ISSUE TITLE
Need a proper cpp code to download the large file from S3 bucket

### ISSUE THREAD

**Issue by AkshayGawande1994** [aws/aws-sdk-cpp#1849]
Hi,

I have tried the getobject.cpp code but in that i am not able to download the file. It just copy the contents from the file and display it on the terminal. 
I have tried the demo code of transfer manager but its download is failing.

Please guide me in this how to proceed to download the any file from AWS S3 bucket using only cpp code.

Thanks in advance.

**Comment by KaibaLopez** [comment]
Hi @AkshayGawande1994 ,
So I'm closing this as it is not really SDK related but rather a C++ question of "how to save a stream as a file"... but basically you'd want to do something like:
```cpp
Aws::String filename = "something.txt"
auto &retrieved_file = outcome.GetResult().GetBody();                                                                                                                                                                          
    std::ofstream output_file(filename.c_str(), std::ios::out |std::ios::binary);
    output_file << retrieved_file.rdbuf();
```
