### ISSUE TITLE
Attempting to replace file in S3 results in "No response body"

### ISSUE THREAD

**Issue by LorenDB** [aws/aws-sdk-cpp#1855]
### Describe the bug

In my project, I have a function that boils down to something like this:

```
void replaceFile(const std::string &key, const std::string &filePathToUpload, std::function<void (const Aws::S3::Model::PutObjectOutcome &)> successCallback, std::function<void (const Aws::S3::Model::PutObjectOutcome &)> failureCallback)
{
	Aws::S3::S3Client client;
	Aws::S3::Model::PutObjectRequest req;
	req.SetBucket("name of my bucket");
	req.SetBody(std::make_shared<std::fstream>(filePathToUpload));
	req.SetACL(Aws::S3::Model::ObjectCannedACL::public_read);
	req.SetKey(key);
	if (auto outcome = client.PutObject(req); outcome.IsSuccess())
		successCallback(outcome);
	else
		failureCallback(outcome);
}
```

Basically, I want to replace files that I have already uploaded. (I suppose I could really just re-upload the file; I hadn't thought about that till now. However, my upload function has the same problem.) Unfortunately, this function won't work. It sends data to AWS but ends up with an error "No response body." This error is HTTP 400 and has the internal error code 100 for Aws::S3::S3Errors::UNKNOWN. I [checked the issue list for issues involving this error message](https://github.com/aws/aws-sdk-cpp/issues?q=is%3Aissue+no+response+body) and found a few that looked similar, but they all involved HEAD, not PUT. Is the SDK doing a HEAD request behind my back? Am I missing something? What is wrong?

### Expected behavior

  The file should upload without complaining or erroring. I should be able to verify that the file contents have changed.

### Current behavior

AWS fails with HTTP error 400 and the error message 'No response body.'

### Steps to Reproduce

After changing everything here that needs changed for your bucket, run this snippet of code:

``` cpp
Aws::S3::S3Client client;
Aws::S3::Model::PutObjectRequest req;
req.SetBucket("name of a bucket that you don't mind overwriting an object in");
req.SetBody(std::make_shared<std::fstream>("/dev/urandom")); // PLEASE DON'T ACTUALLY USE /dev/urandom, YOU WILL PROBABLY BORK YOUR PC AND/OR YOUR BUCKET
req.SetACL(Aws::S3::Model::ObjectCannedACL::public_read);
req.SetKey("/path/to/existing/object");
if (auto outcome = client.PutObject(req); outcome.IsSuccess())
	std::cout << "Something worked right for you; what did you do to fix it?!\n";
else
	std::cout << "Yup, failed for you too: " << outcome.GetError().GetMessage() << '\n';
```

### AWS CPP SDK version used

1.9.180 (OK, OK, I'm using ~~master~~ main, but that's the same thing)

### Compiler and Version used

Clang 13.0.0

### Operating System and version

openSUSE Tumbleweed, more or less up to date

**Comment by KaibaLopez** [comment]
Hi @LorenDB ,
So I can run the putobject code no problem, and it is kind of hard to tell what could be going on with just this info... Could you try turning the on the trace logs and uploading them here? Just make sure that you censor private things like credentials before you post them.

```
Aws::SDKOptions options;
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;
Aws::InitAPI(options);
```

Kind of a shot in the dark but, can you also verify that you are using the correct bucket region in your client configuration?

**Comment by LorenDB** [comment]
I've got the trace logs here: [pertinent-log.log](https://github.com/aws/aws-sdk-cpp/files/7981915/pertinent-log.log). The most pertinent information is very near the end of the log. I did redact a few things as suggested.

As far as bucket region, that didn't fix anything, although setting it suddenly sped up SDK requests a whole lot.

**Comment by KaibaLopez** [comment]
@LorenDB I'm confused, this logs show only successful calls, did it still not work? 
Can you share the full sample maybe there is something else off there?

**Comment by LorenDB** [comment]
That *is* the full log, and yes, it still doesn't work.

**Comment by KaibaLopez** [comment]
My bad, I meant the full code sample, not sure if it will show anything different but I can't really help without a way to reproduce the error... kind of shooting in the dark at this point.

**Comment by LorenDB** [comment]
OK, I'm feeling really stupid now. It turns out there is an elaborate bug in my code that meant that I actually wasn't uploading any data at all. I'll fix it myself. :facepalm:
