### ISSUE TITLE
IPv6 address support in S3

### ISSUE THREAD

**Issue by drake127** [aws/aws-sdk-cpp#1857]
### Describe the bug

The commit https://github.com/aws/aws-sdk-cpp/commit/cb67425a8ec081ad948e638baedf5cabf3e72a15 introduced IPv6 address support in AWS core but it's still failing in `AWSClient.cpp` and function `Aws::Utils::IsValidHost()`

### Expected behavior

Connection to `http://[::1]:8000` should work.

### Current behavior

Currently, the request fails with `Invalid DNS Label found in URI host` error

### Steps to Reproduce

Create an S3 bucket using bracketed IPv6 address with explicit port, e.g. `http://[::1]:8000`

### Possible Solution

It appears that half-work is already done and `Aws::Utils::IsValidHost` needs to understand bracketed GetAuthority, or rather IPs.

### AWS CPP SDK version used

1.9.185

### Compiler and Version used

gcc-9

### Operating System and version

Ubuntu 20.04

**Comment by KaibaLopez** [comment]
Hi @drake127 ,
Hmmm... So you are right about it not working, but I am pretty sure this is something we don't support for s3 yet... just a matter of syntax but I think this is a feature in the works rather than a bug.

**Comment by DmitriyMusatkin** [comment]
This should now be supported in 1.11 with the rule based endpoint resolution which does understand ipv6 endpoint overrides.
