### ISSUE TITLE
Compile Error with VS2022 and C++ 20

### ISSUE THREAD

**Issue by bspfp** [aws/aws-sdk-cpp#1858]
### Describe the issue

I generated with the following command.
cmake -G "Visual Studio 17 2022" -A x64 -DTARGET_ARCH=WINDOWS -DCMAKE_BUILD_TYPE=Release -DCPP_STANDARD=20 -DCMAKE_CXX_STANDARD=20 -DBUILD_ONLY="dynamodb" -DCMAKE_PREFIX_PATH=../sdk-vs2022 -DCMAKE_INSTALL_PREFIX=../sdk-vs2022 ../aws-sdk-cpp

And, build
msbuild ALL_BUILD.vcxproj -p:Configuration=Release

1. C7527: Missing "#include &lt;string&gt;"
Error message: aws-sdk-cpp\crt\aws-crt-cpp\include\aws/crt/StringView.h(856,45): error C7527: 'Traits': template parameter name cannot be redeclared.
- Solution:
Add "#include &lt;string&gt;"

2. C2280: Reference a deleted function
Error message: aws-sdk-cpp\aws-cpp-sdk-core\source\utils\crypto\bcrypt\CryptoImpl.cpp(129,21): error C2280: 'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const wchar_t *)': attempting to reference a deleted function
- Solution:
Add "#include <aws/core/utils/StringUtils.h>"
Change
AWS_LOGSTREAM_ERROR(logTag, "Failed initializing BCryptOpenAlgorithmProvider for " << algorithmName);
to
AWS_LOGSTREAM_ERROR(logTag, "Failed initializing BCryptOpenAlgorithmProvider for " << Aws::Utils::StringUtils::FromWString(algorithmName));

3. C2593: 'operator <<' is ambiguous
Error message: aws-sdk-cpp\testing-resources\include\aws/external/gtest.h(10356,1): error C2593: 'operator <<' is ambiguous
- Solution:
Add function in gtest.h
#if GTEST_LANG_CXX11
inline void PrintTo(std::nullptr_t, ::std::ostream* os) { *os << "(nullptr)"; }
#endif  // GTEST_LANG_CXX11
- Reference: https://github.com/google/googletest/pull/1620/commits/f66ab00704cd47e4e63ef6d425ca14b9192aaebb

### AWS CPP SDK version used

1.9.187

### compiler and version used

Visual Studio 2022, C++ 20

### Operating System and version

Windows 10 21H2 x64

**Comment by KaibaLopez** [comment]
Hi @bspfp ,
Short answer here is, C++20 does introduce some compatibility issues with the SDK, we are working on it but yea for now (if possible) use C++17 or lower.

**Comment by QuellaZhang** [comment]
I have this issue too, waiting for the fix. :)

**Comment by sbiscigl** [comment]
[merged the fix](https://github.com/aws/aws-sdk-cpp/commit/fd2f50f859b129e62b447a109e6fe9e39d386dfe) to fix the described use case. If it is reproduce-able under other circumstances, please let us know.

**Comment by webmaster0407** [comment]
I am struggling with these issues too.
Plz help me someone to fix that.
Thanks !
