### ISSUE TITLE
USE_PROXY_FOR_TESTS missing from Transfertests.cpp

### ISSUE THREAD

**Issue by mmustafa-hp** [aws/aws-sdk-cpp#186]
The proxyconfig.h includes a definition for the proxy configuration. There is no corresponding code in the TransferTests.cpp to use it.

Need to add 
  
#ifdef USE_PROXY_FOR_TESTS
		config.proxyHost = PROXY_HOST;
		config.proxyPort = PROXY_PORT;

#endif // USE_Proxy_FOR_TESTS

to  
static void SetUpTestCase()
in TransferTests.cpp

**Comment by JonathanHenson** [comment]
That's mainly for internal usage and largely for debugging our tests. Is this impacting you in some way?

**Comment by mmustafa-hp** [comment]
It impacted me when I tired the run the tests and got failures until I added the proxy configuration.
But I only use this for understanding and learning the SDK and not development.
