### ISSUE TITLE
`cmake --install` on Windows seems to install badly

### ISSUE THREAD

**Issue by LorenDB** [aws/aws-sdk-cpp#1862]
### Describe the issue

After building the SDK on Windows (in release mode (in debug mode, `cmake --install` won't find debug builds of the crt library)) and installing it via `cmake --install`, I tried to build an app that has `find_package(AWSSDK REQUIRED COMPONENTS s3)` in its CMakeLists.txt. However, the CMake command fails with:

```
CMake Error at CMakeLists.txt:12 (find_package):
  By not providing "FindAWSSDK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "AWSSDK", but
  CMake did not find one.

  Could not find a package configuration file provided by "AWSSDK" with any
  of the following names:

    AWSSDKConfig.cmake
    awssdk-config.cmake

  Add the installation prefix of "AWSSDK" to CMAKE_PREFIX_PATH or set
  "AWSSDK_DIR" to a directory containing one of the above files.  If "AWSSDK"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```

After changing the install directory (`C:\Program Files\aws-sdk-cpp-all`) to `C:\Program Files\AWSSDK`,  the error message becomes:

```
CMake Error at C:/Program Files/AWSSDK/lib/cmake/AWSSDK/AWSSDKConfig.cmake:307 (find_package):
  By not providing "Findaws-cpp-sdk-core.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "aws-cpp-sdk-core", but CMake did not find one.

  Could not find a package configuration file provided by "aws-cpp-sdk-core"
  with any of the following names:

    aws-cpp-sdk-coreConfig.cmake
    aws-cpp-sdk-core-config.cmake

  Add the installation prefix of "aws-cpp-sdk-core" to CMAKE_PREFIX_PATH or
  set "aws-cpp-sdk-core_DIR" to a directory containing one of the above
  files.  If "aws-cpp-sdk-core" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:12 (find_package)


-- Configuring incomplete, errors occurred!
```

(Apologies for the walls of text! Maybe I should have gistified them...)

Apparently, CMake is installing the SDK into directories that do not follow the standard for CMake library searching on Windows.

### AWS CPP SDK version used

1.9.194

### compiler and version used

Visual Studio 2022

### Operating System and version

Windows 10 Pro (10.0.19043 Build 19043) (straight from `msinfo32`!)

**Comment by LorenDB** [comment]
For the SDK:

```powershell
rem Don't forget to run this as administrator.
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="core;s3"
msbuild ALL_BUILD.vcxproj /p:Configuration=Release
cmake --install .
rem Don't forget to run this as administrator.
```

For my app:

```
mkdir build
cd build
cmake ..
```

I don't know of anything special going on in my CMakeLists.txt.

And yes, there is nothing bad going on during install. The only actual failure is when I run CMake on my app.

**Comment by KaibaLopez** [comment]
hmmm ok, so the first thing I want you to try is:
Can you try adding the `-DCMAKE_INSTALL_PREFIX` to the app's cmake command and see if that fixes it?
so in your case it could look like:
```
cmake .. -DCMAKE_INSTALL_PREFIX="C:\Program Files\AWSSDK"
```
Or
```
cmake .. -DCMAKE_INSTALL_PREFIX="C:\Program Files\aws-sdk-cpp-all"
```

**Comment by LorenDB** [comment]
That results in second error output from my first post. In other words, CMake has found the AWSSDK files but doesn't seem to know where to look for aws-sdk-cpp-core.

**Comment by KaibaLopez** [comment]
hmm how about you add `-DCMAKE_BUILD_TYPE=Release` to the same command, like:
```
cmake .. -DCMAKE_INSTALL_PREFIX="C:\Program Files\aws-sdk-cpp-all" -DCMAKE_BUILD_TYPE=Release
```
And just to be clear, this is the app's cmake (not the sdk's).

**Comment by KaibaLopez** [comment]
weird, my issue here is that the error message is clear in what the problem is: it is not finding the installed libraries.
We have explicitly told cmake where they should be and what type to look for so the only thing I can think could be wrong now is that they are just not being installed.
check the folder `C:\Program Files\aws-sdk-cpp-all\bin` and see that `aws-cpp-sdk-core.lib` is actually there.

**Comment by KaibaLopez** [comment]
@LorenDB,
If the files are not there that tells me that they were not installed correctly... Hard for me to say which part failed so I'm just going to list the steps I'd take, and sorry if this seems repetitive but honestly I can't really do much else without seeing it myself.

1. Clear the previous cmake Cache. I would just delete the whole build folder:
```
rm -rf build
```
2. Just to be sure, pull the latest version of the SDK and it's dependencies:
```
git pull origin main
git submodule update --init --recursive
```
2. Run a simple cmake and build command:
```
cmake -S .  -B build -DBUILD_ONLY=s3 -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release
```
3. Make sure you run install as administrator.
```
cmake --install build
```

Since we didn't specify any install directory, the libs should by default be in `C:\Program Files\aws-sdk-cpp-all\bin` , if they are not, I'll need you to share the logs on each of those calls.

The next part shouldn't change, just make sure to also delete the cmake cache before retrying:
```
cmake -S . -B build -DCMAKE_INSTALL_PREFIX="C:\Program Files\aws-sdk-cpp-all" -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release
```

**Comment by LorenDB** [comment]
Still not working. I'm putting the logs up [here](https://gist.github.com/LorenDB/98cb3cad4280e779f0de8a673c263c08). I also included a tree of the install dir so that you can verify that it looks OK as compared to your end.

**Comment by KaibaLopez** [comment]
For the app-build command I see you typed :
```
cmake .. -DCMAKE_INSTALL_PREFIX="C:\Program Files\aws-sdk-cpp-all" -DCMAKE_BUILD_TYPE=Release
```
but on the install logs I see `C:/Program Files (x86)/aws-cpp-sdk-all/....`
Try changing the install prefix on your cmake command to the correct location:
```
cmake .. -DCMAKE_INSTALL_PREFIX="C:/Program Files (x86)/aws-cpp-sdk-all/" -DCMAKE_BUILD_TYPE=Release
```
Let me know if that works.

**Comment by LorenDB** [comment]
Changing the install prefix doesn't help.

**Comment by LorenDB** [comment]
Actually, it does help. I just needed the trailing slash, which I had been omitting. Grr.
