### ISSUE TITLE
Build failed on make

### ISSUE THREAD

**Issue by tfsrgged** [aws/aws-sdk-cpp#1864]
### Describe the issue

 cmake  -DCMAKE_BUILD_TYPE=Debug  ~/aws/aws-sdk-cpp
make

[ 35%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/AmazonSerializableWebServiceRequest.cpp.o
In file included from /root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/Types.h:10:0,
                 from /root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/DateTime.h:8,
                 from /root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/auth/Sigv4Signing.h:9,
                 from /root/aws/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/auth/AWSAuthSigner.h:18,
                 from /root/aws/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/AmazonWebServiceRequest.h:16,
                 from /root/aws/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/AmazonSerializableWebServiceRequest.h:9,
                 from /root/aws/aws-sdk-cpp/aws-cpp-sdk-core/source/AmazonSerializableWebServiceRequest.cpp:6:
/root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/StringView.h: In constructor ‘constexpr Aws::Crt::basic_string_view<CharT, Traits>::basic_string_view(const CharT*, Aws::Crt::basic_string_view<CharT, Traits>::size_type)’:
/root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/StringView.h:52:84: error: declaration of ‘length’ shadows a member of 'this' [-Werror=shadow]
             constexpr basic_string_view(const CharT *s, size_type length) noexcept : m_size{length}, m_data{s} {}
                                                                                    ^
/root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/StringView.h: In instantiation of ‘constexpr Aws::Crt::basic_string_view<CharT, Traits>::basic_string_view(const CharT*, Aws::Crt::basic_string_view<CharT, Traits>::size_type) [with CharT = char; Traits = std::char_traits<char>; Aws::Crt::basic_string_view<CharT, Traits>::size_type = long unsigned int]’:
/root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/StringView.h:819:61:   required from here
/root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/StringView.h:52:23: error: declaration of ‘length’ shadows a member of 'this' [-Werror=shadow]
             constexpr basic_string_view(const CharT *s, size_type length) noexcept : m_size{length}, m_data{s} {}
                       ^
/root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/StringView.h: In instantiation of ‘constexpr Aws::Crt::basic_string_view<CharT, Traits>::basic_string_view(const CharT*, Aws::Crt::basic_string_view<CharT, Traits>::size_type) [with CharT = wchar_t; Traits = std::char_traits<wchar_t>; Aws::Crt::basic_string_view<CharT, Traits>::size_type = long unsigned int]’:
/root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/StringView.h:824:64:   required from here
/root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/StringView.h:52:23: error: declaration of ‘length’ shadows a member of 'this' [-Werror=shadow]
/root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/StringView.h: In instantiation of ‘constexpr Aws::Crt::basic_string_view<CharT, Traits>::basic_string_view(const CharT*, Aws::Crt::basic_string_view<CharT, Traits>::size_type) [with CharT = char16_t; Traits = std::char_traits<char16_t>; Aws::Crt::basic_string_view<CharT, Traits>::size_type = long unsigned int]’:
/root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/StringView.h:829:65:   required from here
/root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/StringView.h:52:23: error: declaration of ‘length’ shadows a member of 'this' [-Werror=shadow]
/root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/StringView.h: In instantiation of ‘constexpr Aws::Crt::basic_string_view<CharT, Traits>::basic_string_view(const CharT*, Aws::Crt::basic_string_view<CharT, Traits>::size_type) [with CharT = char32_t; Traits = std::char_traits<char32_t>; Aws::Crt::basic_string_view<CharT, Traits>::size_type = long unsigned int]’:
/root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/StringView.h:834:65:   required from here
/root/aws/aws-sdk-cpp/crt/aws-crt-cpp/include/aws/crt/StringView.h:52:23: error: declaration of ‘length’ shadows a member of 'this' [-Werror=shadow]
cc1plus: all warnings being treated as errors
make[2]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/AmazonSerializableWebServiceRequest.cpp.o] Error 1make[1]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/all] Error 2
make: *** [all] Error 2

### AWS CPP SDK version used

latest

### compiler and version used

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

### Operating System and version

Red Hat 4.8.5-44

**Comment by KaibaLopez** [comment]
Hi @tfsrgged ,
A couple things here, first you are going to need to upgrade your gcc, version 4.9 is the minimum requirement.
Second, I suggest you only build the services you are planning to use, otherwise the build process will take too long, for example:
```
cmake -DCMAKE_BUILD_TYPE=Debug ~/aws/aws-sdk-cpp -DBUILD_ONLY="s3;dynamodb;ec2" 
```

**Comment by tfsrgged** [comment]
@KaibaLopez
well thanks, I update my gcc to version 11.2.0,but another promble was thrown
[ 25%] Building C object crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/pq-crypto/bike_r3/sampling_avx512.c.o
/tmp/cc3kElZi.s: Assembler messages:
/tmp/cc3kElZi.s:85: Error: operand type mismatch for `vpclmulqdq'
/tmp/cc3kElZi.s:90: Error: operand type mismatch for `vpclmulqdq'
/tmp/cc3kElZi.s:98: Error: operand type mismatch for `vpclmulqdq'
/tmp/cc3kElZi.s:1193: Error: operand type mismatch for `vpclmulqdq'
/tmp/cc3kElZi.s:1198: Error: operand type mismatch for `vpclmulqdq'
make[2]: *** [crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/pq-crypto/bike_r3/gf2x_mul_base_vpclmul.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/all] Error 2
make: *** [all] Error 2

**Comment by tfsrgged** [comment]
this may be similar to https://github.com/aws/aws-sdk-cpp/issues/1795
but it seems to still exist

**Comment by tfsrgged** [comment]
@KaibaLopez 
well thanks, I update my gcc to version 11.2.0,but another promble was thrown 
[ 25%] Building C object crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/pq-crypto/bike_r3/sampling_avx512.c.o 
/tmp/cc3kElZi. s: Assembler messages: 
/tmp/cc3kElZi. s:85: Error: operand type mismatch for vpclmulqdq' /tmp/cc3kElZi. s:90: Error: operand type mismatch for vpclmulqdq' 
/tmp/cc3kElZi. s:98: Error: operand type mismatch for vpclmulqdq' /tmp/cc3kElZi. s:1193: Error: operand type mismatch for vpclmulqdq' 
/tmp/cc3kElZi. s:1198: Error: operand type mismatch for `vpclmulqdq' 
make[2]: *** [crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/pq-crypto/bike_r3/gf2x_mul_base_vpclmul.c. o] Error 1 
make[2]: *** Waiting for unfinished jobs.... 
make[1]: *** [crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n. dir/all] Error 2 
make: *** [all] Error 2

**Comment by tfsrgged** [comment]
this is similar to https://github.com/aws/aws-sdk-cpp/issues/1795
maybe the glibc problem?
my glibc is 2.17

**Comment by KaibaLopez** [comment]
hmmm Honestly this is the first time I've encounter this particular error, but I know that latest versions of gcc can cause these kind of mismatch type errors.... But if it turns out to be a newer gcc version thing, then I can push for a fix.

In the meant time, couple things for you to try:
1. (Just in case) update the crt submodules, since this is probably a "newer gcc version triggers new warnings" thing, an update might have fixed this:
```
git submodule update --init --recursive
```
2. I am sure that gcc/g++ versions 7,8,9 and 10(*) work so, sorry to have you bouncing on gcc versions but could you try with one of those and tell me what you get?
 *_10 can be iffy if using aws-lc, but by default the sdk doesn't use that so unless you explicitly are building with aws-lc it should work._
