### ISSUE TITLE
 Consult http connection and receive timeout

### ISSUE THREAD

**Issue by Hsuehnj** [aws/aws-sdk-cpp#1866]
### Describe the issue

When I trigger http requests, sometimes request send failed with response code -1.
I haven't set the connection and receive timeout, the default WINHTTP_OPTION_CONNECT_TIMEOUT is 60 seconds and WINHTTP_OPTION_RECEIVE_TIMEOUT is 30 seconds.
While the TCP timeout in 3 or 6 seconds, 
[Time since previous frame in this TCP stream: 2.979262000 seconds]
[Time since previous frame in this TCP stream: 6.044147000 seconds]

Aws::String url = Aws::String(requestUrl.c_str(), requestUrl.length());
Aws::Client::ClientConfiguration config;
config.enableTcpKeepAlive = true;
std::shared_ptr<Aws::Http::HttpClient> httpClient = Aws::Http::CreateHttpClient(config);
auto httpRequest(Aws::Http::CreateHttpRequest(url, (Aws::Http::HttpMethod)httpMethod,
            Aws::Utils::Stream::DefaultResponseStreamFactoryMethod));
auto httpResponse = httpClient->MakeRequest(httpRequest);

### AWS CPP SDK version used

AWSNativeSDK-1.9.50-rev2-windows

### compiler and version used

Visual Studio 2019

### Operating System and version

Windows 10

**Comment by KaibaLopez** [comment]
Hey @Hsuehnj ,
I need a bit more context here, can you maybe give me a sample I can just copy-paste and run on my side to reproduce this ? That'd make things a lot faster.

**Comment by Hsuehnj** [comment]
I want to confirm the default value of requestTimeoutMs, is it 3000ms? I fount it in function 
void setLegacyClientConfigurationParameters(ClientConfiguration& clientConfig)
clientConfig.requestTimeoutMs = 3000;

**Comment by KaibaLopez** [comment]
Yes, the default value is 3000ms [defined here](https://github.com/aws/aws-sdk-cpp/blob/ea5a4d61a26c1eac41443fb9829e969ebac6e09b/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp#L46).

**Comment by Hsuehnj** [comment]
thanks, the issue has been solved.
