### ISSUE TITLE
Link to API SKD for version 1.8

### ISSUE THREAD

**Issue by rvernica** [aws/aws-sdk-cpp#1873]
### Describe the issue

https://sdk.amazonaws.com/cpp/api/LATEST/index.html is for 1.9 Were is the SDK for 1.8?

### AWS CPP SDK version used

1.8

### compiler and version used

N/A

### Operating System and version

N/A

**Comment by jmklix** [comment]
You can access previous versions by editing the url. Example for 1.8.1
     http://sdk.amazonaws.com/cpp/api/1.8.1/index.html
