### ISSUE TITLE
 How to implement asynchronous http request

### ISSUE THREAD

**Issue by Hsuehnj** [aws/aws-sdk-cpp#1877]
### Describe the issue

Does the SDK use WinHttp's synchronous mode by default (see in WinHttpSyncHttpClient.cpp)? 
If i want to implement an asynchronous Http request, is there an example reference,  or which APIs should be used?

### AWS CPP SDK version used

AWSNativeSDK-1.9.50-rev2-windows

### compiler and version used

Visual Studio 2019

### Operating System and version

Windows 10

**Comment by jmklix** [comment]
Yes, this sdk uses WinHttp synchronous mode. As a general rule the sdk with specify when functions are [async](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/async-methods.html). There currently isn't an async function for this yet
