### ISSUE TITLE
Incorrect AthenaError in Aws::Utils::Outcome<T, AthenaError> Template

### ISSUE THREAD

**Issue by livioso** [aws/aws-sdk-cpp#1878]
### Describe the bug

`AthenaError` exists twice: [First one here](https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-athena/include/aws/athena/AthenaErrors.h#L56) and [second time here](https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-athena/include/aws/athena/model/AthenaError.h#L34).

Due to a namespace problem, the `Outcome` template uses the incorrect `AthenaError` (second one), same problem exists for all [these methods](https://github.com/aws/aws-sdk-cpp/blob/bb1fdce01cc7e8ae2fe7162f24c8836e9d3ab0a2/aws-cpp-sdk-athena/include/aws/athena/AthenaClient.h#L122-L155) as well.

This causes the following code not to compile:
```
auto outcome = client.ListNamedQueries(request);

// this should & used to work, now fails :(
outcome.GetError().GetExceptionName(); 
```

### Expected behavior

```
auto outcome = client.ListNamedQueries(request);
outcome.GetError().GetExceptionName(); 
```

Should work and  probably use [this class](https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-athena/include/aws/athena/AthenaErrors.h#L56).

### Current behavior

[`Aws::Utils::Outcome<T, AthenaError>`](https://github.com/aws/aws-sdk-cpp/blob/bb1fdce01cc7e8ae2fe7162f24c8836e9d3ab0a2/aws-cpp-sdk-athena/include/aws/athena/AthenaClient.h#L122-L155) template uses the [incorrect AthenaError](https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-athena/include/aws/athena/model/AthenaError.h#L34) causing a compile error.

### Steps to Reproduce

```
auto outcome = client.ListNamedQueries(request);
outcome.GetError().GetExceptionName(); 
```

### AWS CPP SDK version used

`main` / `e5dc51c`

### Compiler and Version used

Clang 13.0.0

### Operating System and version

MacOS 11.6.1

**Comment by sbiscigl** [comment]
Looks like this was fixed in [pull/1988](https://github.com/aws/aws-sdk-cpp/pull/1988) and has been available since version `1.9.295`
