### ISSUE TITLE
Export Aws::Transfer::PartState class

### ISSUE THREAD

**Issue by camarois** [aws/aws-sdk-cpp#1879]
### Describe the issue

I have a special case were I need to tweak the TransferManager class so that each read chunk of a stream is compressed before being sent to s3. 

I end up needing to create new Aws::Transfer::PartState, however the class is not exported in dlls. Is this something that could be easily done?

### Steps to Reproduce

Creating a Aws::Transfer::PartState outside of currently exported classes.

### Current behavior

error LNK2019: unresolved external symbol "public: __cdecl Aws::Transfer::PartState::PartState(int,unsigned __int64,unsigned __int64,bool)"

### AWS CPP SDK version used

1.9.160

### compiler and version used

9.4.0

### Operating System and version

x64-windows

**Comment by vudh1** [comment]
Hi @camarois thanks for bringing this out. Can you send a sample of reproducible code for exporting the class that you used?

**Comment by camarois** [comment]
I can't send all of my code, but the general idea is that the TransferManager class when doing a multipart upload creates all parts beforehand according to stream size passed to the TransferHandle. 

In my case however, I need to compress my data on each read to limit upload size. I created a custom buffer/stream class to do this, but because of compression ratio, the total number of parts can vary and don't equal the total number of initial parts. 

So I end up creating my own parts:
`            Aws::Transfer::PartPointer part =
                Aws::MakeShared<Aws::Transfer::PartState>(CLASS_TAG, static_cast<int>(sentBytes / m_TransferConfig.bufferSize + 1), 0, partSize, false);
auto lengthToWrite = part->GetSizeInBytes();

p_spStream->read(reinterpret_cast<char*>(buffer), lengthToWrite);`

In Linux, this works well because all classes are exported by default, but in windows these classes/methods are undefined.
`Aws::PartState::PartState
Aws::PartState::Reset 
Aws::PartState::OnDataTransferred`

All I'm asking is to export PartState, so that it can be used individually.

**Comment by camarois** [comment]
@jmklix why was this closed?

**Comment by jmklix** [comment]
The PR you made was merged and the change should be live. Did you need anything else?

**Comment by camarois** [comment]
No, that's all. Sorry, it wasn't clear to me that my changes were merged. Thanks a lot!
