### ISSUE TITLE
BUILD_ONLY flag fails

### ISSUE THREAD

**Issue by rabinnh** [aws/aws-sdk-cpp#188]
Without BUILD_ONLY flag:
user@rab-sprt:~/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master$ cmake -DCMAKE_BUILD_TYPE=Release  .
-- Found Git: /usr/bin/git (found version "1.9.1") 
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Generating linux build config
-- Building AWS libraries as shared objects
-- Http client: Curl
-- Encryption: Openssl
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Install binary prefix: linux/intel64
etc

With BUILD_ONLY flag:
user@rab-sprt:~/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master$ cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="aws-cpp-sdk-s3" .
-- Found Git: /usr/bin/git (found version "1.9.1") 
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Generating linux build config
-- Building AWS libraries as shared objects
-- Http client: Curl
-- Encryption: Openssl
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Install binary prefix: linux/intel64
-- Considering aws-cpp-sdk-s3
FATALaws-cpp-sdk-s3 is required for build, but aws-cpp-sdk-aws-cpp-sdk-s3 directory is missing!
fatal: No names found, cannot describe anything.
Not able to compute versioning string, not updating.
-- Custom memory management enabled; stl objects now using custom allocators
CMake Error at CMakeLists.txt:930 (add_subdirectory):
  add_subdirectory given source "aws-cpp-sdk-aws-cpp-sdk-s3" which is not an
  existing directory.

CMake Error at CMakeLists.txt:982 (export):
  export given target "aws-cpp-sdk-aws-cpp-sdk-s3" which is not built by this
  project.

-- Configuring incomplete, errors occurred!
See also "/home/user/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/CMakeFiles/CMakeOutput.log".

OS is Ubuntu 14.04.4 LTS amd64.

**Comment by rabinnh** [comment]
Solved - the README is incorrect.  Instead of 

cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="aws-cpp-sdk-s3" .

you use

cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3" .

**Comment by JonathanHenson** [comment]
Thanks for pointing this out, we will update the readme

**Comment by JoyIfBam5** [comment]
There are couple pull requests to fix this #187 and #178

**Comment by JonathanHenson** [comment]
Readme updated. It will be pushed out to this repo shortly.
