### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by Daoudia** [aws/aws-sdk-cpp#1880]
### Describe the bug

Ich habe bemerkt das sich fremde in meinen Konten Zugang verschafft haben und versuchen meinen Daten umzulenken und sich klare Vorteile damit zu bewirken...

### Expected behavior

Hoffe ihr könnt helfen und doppelt drauf achten wer oder was hier versucht wird.... Also ich bin eine eizel Person bin männlich und 36 Jahre alt und keine Frau und habe auch keiner Familie erlaubt in meinem Konten zu sein....! 

### Current behavior

Ich werde mit permanenten fishing und scimming oder wie man das jetzt nennt.... Aber ich habe überhaupt keine Ahnung wie ich mich verhalten soll und wenn ich mal abschalten will unrdie Geräte ausschalte.. Sind am Tag mehrer Geräte bei mir angemeldet

### Steps to Reproduce

![Screenshot_20220316_164601_com android chrome](https://user-images.githubusercontent.com/85792632/158797504-7becc309-648b-4268-ab82-02d085423ee9.jpg)
![Screenshot_20220316_164557_com android chrome](https://user-images.githubusercontent.com/85792632/158797507-c361e09d-36cb-4785-83d1-70e791d17f29.jpg)
![Screenshot_20220315_135104_com android chrome](https://user-images.githubusercontent.com/85792632/158797510-6b658dd0-1d9a-413b-8aef-29f3f17aef85.jpg)
![Screenshot_20220315_135107_com android chrome](https://user-images.githubusercontent.com/85792632/158797513-747f7fd3-6422-4417-a2cf-f40b5292b226.jpg)
![Screenshot_20220315_074437_com android chrome](https://user-images.githubusercontent.com/85792632/158797515-0c15fb3f-cb43-47be-b7d3-098df33612c6.jpg)
![Uploading Screenshot_20220314_144711_com.android.chrome.jpg…]()

### Possible Solution

Das sind Screenshots von meinem kompromitierten Konten..... Wer könnte mir helfen 

### AWS CPP SDK version used

.... 

### Compiler and Version used

..... 

### Operating System and version

....

**Comment by Daoudia** [comment]
![1594531765318](https://user-images.githubusercontent.com/85792632/158797927-3dd3c32f-eb2b-4929-b8a7-7c929e823f2f.jpg)
![1594548383816](https://user-images.githubusercontent.com/85792632/158797931-c514b1d7-9b19-4cae-8b7b-c3526dbe4691.jpg)
![1594531890389](https://user-images.githubusercontent.com/85792632/158797934-48ca27de-db2d-406b-b611-cbdd7dd6f196.jpg)
![1594532222599](https://user-images.githubusercontent.com/85792632/158797936-1dd2e087-0314-41a7-ba2d-1553d0656479.jpg)
![1594532151667](https://user-images.githubusercontent.com/85792632/158797937-2942cfa2-07b1-4c89-873c-0d90d7efd89f.jpg)
![1594531655110](https://user-images.githubusercontent.com/85792632/158797943-2e6c6d5d-17db-4d81-9897-515edcce6db8.jpg)

Diese Bilder habe ich in meine cloud die nicht von mir sind und wiederhergestellt

**Comment by Daoudia** [comment]
Eins noch dazu ich habe diese Leute in meinem Konten und die machen sich penetrant breit in meinem Eigentum und bekommen wohl seit längerer Zeit meinen Kreditrahmen in den USA Venezuela Japan blabla aber ich Weiss das wird nur genommen so wie die werbe Oberfläche um zu betrügen

**Comment by vudh1** [comment]
Hi @Daoudia thanks for opening an issue. Can you follow the template and provide us the information in English?

**Comment by serzhick** [comment]
Sorry, this issue does not seem to be related to aws sdk cpp. Closing it.
