### ISSUE TITLE
S3CrtClient: regression due to missing AwsClient fields in  Aws::S3Crt::ClientConfiguration

### ISSUE THREAD

**Issue by grrtrr** [aws/aws-sdk-cpp#1882]
### Describe the bug

The `S3CrtClient` still uses the parent class `MakeRequest` for the majority of its operations.

The S3Client allows to configure the behaviour of the `Aws::Client::AWSXMLClient` via `ClientConfiguration` options.

These are not exposed via the `S3CrtClient` constructor, hence defaults are used.

This means that people wishing to upgrade to the new `S3CrtClient` suffer a regression: for the majority of requests, the S3CrtClient will use default behaviour, with the user unable to influence this.

Please see list of minimally required configuration parameters. The defaults are not sufficient for production use.

### Expected behavior

Minimally the following `Aws::Client::ClientConfiguration` parameters should be included in the `Aws::S3Crt::ClientConfiguration`:
- `maxConnections`,
- `httpRequestTimeoutMs` (Linux),
- `requestTimeoutMs`,
- `connectTimeoutMs`,
- `enableTcpKeepAlive`,
- `tcpKeepAliveIntervalMs`,
- `lowSpeedLimit`,
- `retryStrategy`
- `caPath` / `caFile`.

### Current behavior

The above parameters are not configurable, and so the S3CrtClient falls back to defaults via `operator Aws::Client::ClientConfiguration()`.

### Steps to Reproduce

Reproducible with any S3CrtClient as of today's master.

### Possible Solution

Above.

### AWS CPP SDK version used

1.9

### Compiler and Version used

gcc / clang

### Operating System and version

Linux, ubuntu 18.04

**Comment by vudh1** [comment]
Hi @grrtrr thanks for letting us know about this. I can reproduce this and will let the team know.
