### ISSUE TITLE
Build broken on OS X 10.9

### ISSUE THREAD

**Issue by Jerzerak** [aws/aws-sdk-cpp#190]
I just PR'ed the latest aws-sdk-cpp version (0.12.3) to Homebrew [here](https://github.com/Homebrew/homebrew-core/pull/1485) and the build is failing on OS X 10.9 Mavericks.

The proposed fix is to add `typedef int32_t CCStatus;` to `CryptoImpl.cpp` which wasn't part of the public API until 10.10 but existed in 10.9 under the hood

10.11: public
http://opensource.apple.com/source/CommonCrypto/CommonCrypto-60075.20.1
http://opensource.apple.com/source/CommonCrypto/CommonCrypto-60075.20.1/include/CommonCryptoError.h

10.9: private
http://opensource.apple.com/source/CommonCrypto/CommonCrypto-60049
http://opensource.apple.com/source/CommonCrypto/CommonCrypto-60049/include/CommonBigNum.h
http://opensource.apple.com/source/CommonCrypto/CommonCrypto-60049/include/CommonCryptoPriv.h

**Comment by ilovezfs** [comment]
@JonathanHenson Any chance of getting this patched?

**Comment by JonathanHenson** [comment]
Yes, we will fix this shortly

**Comment by ilovezfs** [comment]
@JonathanHenson Great, thank you. By the way, is it your project's intent that Mavericks is "officially" supported? I wanted to check in with you to make sure that Homebrew isn't "pressuring" you into supporting 10.9 if that's not the decision you'd otherwise make.
