### ISSUE TITLE
rtti should not be turned off in linux builds

### ISSUE THREAD

**Issue by jmccl** [aws/aws-sdk-cpp#191]
This stack-overflow question has the gist of the problem; if rtti is off you can buld the sdk on linux, but you can't use aws clients when linking to the library. (I'm static linking, fwiw. I'm not sure what the stack-overflow OP was doing.)

http://stackoverflow.com/questions/37183254/basic-program-using-aws-c-sdk-wont-compile

The comment at the bottom about rtti worked for me, i.e., the following patch fixes linking.

--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -697,7 +697,7 @@ elseif(PLATFORM_LINUX OR PLATFORM_ANDROID OR PLATFORM_APPLE)
 endif()
 
 if(NOT PLATFORM_WINDOWS)
-    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-exceptions -fno-rtti")
+    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-exceptions")
     if(MINIMIZE_SIZE)
         set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -s")
     endif()

I don't know whether the patch is over-broad or not since I don't understand why rtti would be turned off (other than on windows) to begin with.

**Comment by theopolis** [comment]
I concur: https://github.com/facebook/osquery/issues/2107

Can we revert this change, which came from the `0.10.11` commit?

**Comment by JonathanHenson** [comment]
-fno-rtti, This should have been part of optional flags to be passed in. We will remove.

As far as documenting which flags you should be using when linking against the build library, we added cmake export targets to fix this entire question. https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/

**Comment by theopolis** [comment]
Rock on! Thanks a ton Jonathan!
