### ISSUE TITLE
Successful S3 DeleteObjects returns 0 deleted and 0 errors

### ISSUE THREAD

**Issue by rvernica** [aws/aws-sdk-cpp#1911]
### Describe the bug

I'm submitting DeleteObjects requests in parallel from the same EC2 instance with a list of 1,000 requests each. I verify that the request is successful and check the count of the deleted objects and the count of errors. They are both 0.
```
Aws::S3::Model::DeleteObjectsRequest deleteReq;
deleteReq.SetBucket(_bucket);
deleteReq.SetDelete(Aws::S3::Model::Delete().WithObjects(objList));
if (outcome.IsSuccess()) {
    const auto &result = outcome.GetResult();
    result.GetErrors().size();  // is 0
    result.GetDeleted().size(); // is 0
}
```

### Expected Behavior

`GetDeleted().size() + GetErrors.size()` should equal the `objList.size()`

### Current Behavior

```
GetDeleted().size() = 0
GetErrors.size() = 0
objList.size() = 1000
```

### Reproduction Steps

```
Aws::S3::Model::DeleteObjectsRequest deleteReq;
deleteReq.SetBucket(_bucket);
deleteReq.SetDelete(Aws::S3::Model::Delete().WithObjects(objList));
if (outcome.IsSuccess()) {
    const auto &result = outcome.GetResult();
    result.GetErrors().size();  // is 0
    result.GetDeleted().size(); // is 0
}
```

### AWS CPP SDK version used

1.8.3

### Compiler and Version used

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

### Operating System and version

CentOS Linux release 7.7.1908 (Core)

**Comment by jmklix** [comment]
Do you have the correct policy permissions that would allow you to delete those objects?

**Comment by jmklix** [comment]
Can you include the logs from when this request is returning 0 deleted?
