### ISSUE TITLE
build fails on windows 10 using vs 2019 toolchain 

### ISSUE THREAD

**Issue by mekinesis** [aws/aws-sdk-cpp#1914]
### Describe the bug

Building from source fails.

Microsoft Windows [Version 10.0.19044.1645]
cmake version 3.23.1
Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework  16.7.0.37604

git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp
cd aws-sdk-cpp
git checkout main
git pull origin main
git submodule update --init --recursive

git log

> >commit 940e5f066a06be316cb61a63839d841a9922bf2a (HEAD -> main, tag: 1.9.242, origin/master, origin/main, origin/HEAD)

mkdir build
mkdir debug
cd build
cmake .. -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=../debug

> CMake Deprecation Warning at CMakeLists.txt:13 (cmake_policy):
>   The OLD behavior for policy CMP0077 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.
> 
> 
> -- TARGET_ARCH not specified; inferring host OS to be platform compilation target
> -- Building AWS libraries as shared objects
> -- Generating windows build config
> -- Building project version: 1.9.242
> -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19044.
> -- The CXX compiler identification is MSVC 19.27.29112.0
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Encryption: Bcrypt
> -- Http client: WinHttp
> -- The C compiler identification is MSVC 19.27.29112.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- AWS CRT C++ 1.9.242
> CMake Warning (dev) at crt/aws-crt-cpp/crt/aws-c-common/CMakeLists.txt:5 (option):
>   Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
>   --help-policy CMP0077" for policy details.  Use the cmake_policy command to
>   set the policy and suppress this warning.
> 
>   For compatibility with older versions of CMake, option is clearing the
>   normal variable 'STATIC_CRT'.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- CMake 3.23.1
> CMake Deprecation Warning at crt/aws-crt-cpp/crt/aws-c-common/CMakeLists.txt:17 (cmake_policy):
>   The OLD behavior for policy CMP0077 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.
> 
> 
> -- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
> -- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Failed
> -- Performing Test AWS_HAVE_MSVC_MULX
> -- Performing Test AWS_HAVE_MSVC_MULX - Failed
> -- Performing Test AWS_HAVE_WINAPI_DESKTOP
> -- Performing Test AWS_HAVE_WINAPI_DESKTOP - Success
> -- Performing Test AWS_ARCH_INTEL
> -- Performing Test AWS_ARCH_INTEL - Success
> -- Performing Test AWS_ARCH_ARM64
> -- Performing Test AWS_ARCH_ARM64 - Failed
> -- Performing Test AWS_ARCH_ARM32
> -- Performing Test AWS_ARCH_ARM32 - Failed
> -- Performing Test AWS_HAVE_GCC_INLINE_ASM
> -- Performing Test AWS_HAVE_GCC_INLINE_ASM - Failed
> -- Performing Test AWS_HAVE_AUXV
> -- Performing Test AWS_HAVE_AUXV - Failed
> -- Performing Test AWS_HAVE_EXECINFO
> -- Performing Test AWS_HAVE_EXECINFO - Failed
> -- Performing Test HAVE_M_AVX2_FLAG
> -- Performing Test HAVE_M_AVX2_FLAG - Success
> -- Performing Test HAVE_AVX2_INTRINSICS
> -- Performing Test HAVE_AVX2_INTRINSICS - Success
> -- Performing Test HAVE_MM256_EXTRACT_EPI64
> -- Performing Test HAVE_MM256_EXTRACT_EPI64 - Success
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Looking for stdbool.h
> -- Looking for stdbool.h - found
> -- Performing Test HAS_WGNU
> -- Performing Test HAS_WGNU - Failed
> -- Performing Test HAVE_SYSCONF
> -- Performing Test HAVE_SYSCONF - Failed
> -- Performing Test HAS_SANITIZERS
> -- Performing Test HAS_SANITIZERS - Failed
> -- Building SIMD base64 decoder
> -- Packaging is only supported on Linux
> -- Add s3-crt:s3 to C2J_SPECIAL_NAME_LIST
> -- Looking for pathconf
> -- Looking for pathconf - not found
> -- Looking for umask
> -- Looking for umask - not found
> -- Updating version info to 1.9.242
> -- Custom memory management disabled
> -- Performing Test WINHTTP_HAS_H2
> -- Performing Test WINHTTP_HAS_H2 - Success
> -- Performing Test WININET_HAS_H2
> -- Performing Test WININET_HAS_H2 - Success
> -- Looking for include file pulse/simple.h
> -- Looking for include file pulse/simple.h - not found
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/Users/me/aws-sdk-cpp/build

msbuild ALL_BUILD.vcxproj /p:Configuration=Debug

> 
> Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Build started 4/24/2022 8:19:54 AM.
> Project "c:\Users\me\gitrepos\aws-sdk-cpp\build\ALL_BUILD.vcxproj" on node 1 (default targets).
> Project "c:\Users\me\gitrepos\aws-sdk-cpp\build\ALL_BUILD.vcxproj" (1) is building "C:\Users\me\gitrepos\aws-sdk-cpp\build\ZERO_CHECK.vcxproj" (2) on node 1 (default
> targets).
> InitializeBuildStatus:
>   Creating "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
> CustomBuild:
>   Checking Build System
> C:rogram Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: Custom build for item "C:\Users\me\gitrepos
> \aws-sdk-cpp\build\CMakeFiles\f60bae2ccd847ff73f8ebd3168da1bed\generate.stamp.rule" succeeded, but specified dependency "c:\users\me\gitrepos\aws-sdk-cpp\build\cmakefiles\f
> 60bae2ccd847ff73f8ebd3168da1bed\generate.stamp.rule" does not exist. This may cause incremental build to work incorrectly. [C:\Users\me\gitrepos\aws-sdk-cpp\build\ZERO_CHECK.vcxp
> roj]
> C:rogram Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: Custom build for item "C:\Users\me\gitrepos
> \aws-sdk-cpp\build\CMakeFiles\f60bae2ccd847ff73f8ebd3168da1bed\generate.stamp.rule" succeeded, but specified dependency "c:\users\me\gitrepos\aws-sdk-cpp\cmakelists.txt" do
> es not exist. This may cause incremental build to work incorrectly. [C:\Users\me\gitrepos\aws-sdk-cpp\build\ZERO_CHECK.vcxproj]
> C:rogram Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: Custom build for item "C:\Users\me\gitrepos
> \aws-sdk-cpp\build\CMakeFiles\f60bae2ccd847ff73f8ebd3168da1bed\generate.stamp.rule" succeeded, but specified dependency "c:\users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-awsmig
> rationhub\cmakelists.txt" does not exist. This may cause incremental build to work incorrectly. [C:\Users\me\gitrepos\aws-sdk-cpp\build\ZERO_CHECK.vcxproj]
> C:rogram Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: Custom build for item "C:\Users\me\gitrepos
> \aws-sdk-cpp\build\CMakeFiles\f60bae2ccd847ff73f8ebd3168da1bed\generate.stamp.rule" succeeded, but specified dependency "c:\users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-access
> -management\cmakelists.txt" does not exist. This may cause incremental build to work incorrectly. [C:\Users\me\gitrepos\aws-sdk-cpp\build\ZERO_CHECK.vcxproj]
> C:rogram Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: Custom build for item "C:\Users\me\gitrepos
> \aws-sdk-cpp\build\CMakeFiles\f60bae2ccd847ff73f8ebd3168da1bed\generate.stamp.rule" succeeded, but specified dependency "c:\users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-access
> analyzer\cmakelists.txt" does not exist. This may cause incremental build to work incorrectly. [C:\Users\me\gitrepos\aws-sdk-cpp\build\ZERO_CHECK.vcxproj]
> C:rogram Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: Custom build for item "C:\Users\me\gitrepos
> \aws-sdk-cpp\build\CMakeFiles\f60bae2ccd847ff73f8ebd3168da1bed\generate.stamp.rule" succeeded, but specified dependency "c:\users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-accoun
> t\cmakelists.txt" does not exist. This may cause incremental build to work incorrectly. [C:\Users\me\gitrepos\aws-sdk-cpp\build\ZERO_CHECK.vcxproj]
> C:rogram Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: Custom build for item "C:\Users\me\gitrepos
> \aws-sdk-cpp\build\CMakeFiles\f60bae2ccd847ff73f8ebd3168da1bed\generate.stamp.rule" succeeded, but specified dependency "c:\users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-acm-pc
> a\cmakelists.txt" does not exist. This may cause incremental build to work incorrectly. [C:\Users\me\gitrepos\aws-sdk-cpp\build\ZERO_CHECK.vcxproj]
> C:rogram Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: Custom build for item "C:\Users\me\gitrepos
> \aws-sdk-cpp\build\CMakeFiles\f60bae2ccd847ff73f8ebd3168da1bed\generate.stamp.rule" succeeded, but specified dependency "c:\users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-acm\cm
> akelists.txt" does not exist. This may cause incremental build to work incorrectly. [C:\Users\me\gitrepos\aws-sdk-cpp\build\ZERO_CHECK.vcxproj]
> 
> .... 
> 
> "c:\Users\me\gitrepos\aws-sdk-cpp\build\ALL_BUILD.vcxproj" (default target) (1) ->
> "C:\Users\me\gitrepos\aws-sdk-cpp\build\aws-cpp-sdk-AWSMigrationHub\aws-cpp-sdk-AWSMigrationHub.vcxproj" (default target) (14) ->
> "C:\Users\me\gitrepos\aws-sdk-cpp\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj" (default target) (15) ->
>   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: Custom build for item "C:\Users\me\gitrepos
> \aws-sdk-cpp\aws-cpp-sdk-core\CMakeLists.txt" succeeded, but specified dependency "c:\users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-core\cmakelists.txt" does not exist. This
> may cause incremental build to work incorrectly. [C:\Users\me\gitrepos\aws-sdk-cpp\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
>   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: Custom build for item "C:\Users\me\gitrepos
> \aws-sdk-cpp\aws-cpp-sdk-core\CMakeLists.txt" succeeded, but specified dependency "c:\users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-core\include\aws\core\sdkconfig.h.in" does
>  not exist. This may cause incremental build to work incorrectly. [C:\Users\me\gitrepos\aws-sdk-cpp\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
>   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: Custom build for item "C:\Users\me\gitrepos
> \aws-sdk-cpp\aws-cpp-sdk-core\CMakeLists.txt" succeeded, but specified dependency "c:\users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-core\include\aws\core\versionconfig.h.in"
> does not exist. This may cause incremental build to work incorrectly. [C:\Users\me\gitrepos\aws-sdk-cpp\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
>   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: Custom build for item "C:\Users\me\gitrepos
> \aws-sdk-cpp\aws-cpp-sdk-core\CMakeLists.txt" succeeded, but specified dependency "c:\users\me\gitrepos\aws-sdk-cpp\build\cmakefiles\3.23.1\cmakeccompiler.cmake" does not
>  exist. This may cause incremental build to work incorrectly. [C:\Users\me\gitrepos\aws-sdk-cpp\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
>   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: Custom build for item "C:\Users\me\gitrepos
> \aws-sdk-cpp\aws-cpp-sdk-core\CMakeLists.txt" succeeded, but specified dependency "c:\users\me\gitrepos\aws-sdk-cpp\toolchains\core-config.cmake" does not exist. This may
>  cause incremental build to work incorrectly. [C:\Users\me\gitrepos\aws-sdk-cpp\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
>   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8064: Custom build for item "C:\Users\me\gitrepos
> \aws-sdk-cpp\aws-cpp-sdk-core\CMakeLists.txt" succeeded, but specified dependency "c:\users\me\gitrepos\aws-sdk-cpp\toolchains\pkg-config.pc.in" does not exist. This may
> cause incremental build to work incorrectly. [C:\Users\me\gitrepos\aws-sdk-cpp\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
>   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): warning MSB8065: Custom build for item "C:\Users\me\gitrepos
> \aws-sdk-cpp\aws-cpp-sdk-core\CMakeLists.txt" succeeded, but specified output "c:\users\me\gitrepos\aws-sdk-cpp\build\aws-cpp-sdk-core\cmakefiles\generate.stamp" has not
> been created. This may cause incremental build to work incorrectly. [C:\Users\me\gitrepos\aws-sdk-cpp\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
> 
> 
> "c:\Users\me\gitrepos\aws-sdk-cpp\build\ALL_BUILD.vcxproj" (default target) (1) ->
> "C:\Users\me\gitrepos\aws-sdk-cpp\build\aws-cpp-sdk-AWSMigrationHub\aws-cpp-sdk-AWSMigrationHub.vcxproj" (default target) (14) ->
> "C:\Users\me\gitrepos\aws-sdk-cpp\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj" (default target) (15) ->
> (ClCompile target) ->
>   C:\Users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-core\include\aws/core/http/windows/WinSyncHttpClient.h(10,10): fatal error C1083: Cannot open include file: 'aws/core/utils/memory/
> stl/AwsStringStream.h': No such file or directory (compiling source file C:\Users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-core\source\http\HttpClientFactory.cpp) [C:\Users\me\git
> repos\aws-sdk-cpp\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
>   C:\Users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-core\include\aws/core/http/windows/WinSyncHttpClient.h(10,10): fatal error C1083: Cannot open include file: 'aws/core/utils/memory/
> stl/AwsStringStream.h': No such file or directory (compiling source file C:\Users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-core\source\http\windows\WinHttpSyncHttpClient.cpp) [C:\User
> s\me\gitrepos\aws-sdk-cpp\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
>   C:\Users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-core\include\aws/core/http/windows/WinSyncHttpClient.h(10,10): fatal error C1083: Cannot open include file: 'aws/core/utils/memory/
> stl/AwsStringStream.h': No such file or directory (compiling source file C:\Users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-core\source\http\windows\WinINetSyncHttpClient.cpp) [C:\User
> s\me\gitrepos\aws-sdk-cpp\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
>   C:\Users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-core\include\aws/core/http/windows/WinSyncHttpClient.h(10,10): fatal error C1083: Cannot open include file: 'aws/core/utils/memory/
> stl/AwsStringStream.h': No such file or directory (compiling source file C:\Users\me\gitrepos\aws-sdk-cpp\aws-cpp-sdk-core\source\http\windows\WinSyncHttpClient.cpp) [C:\Users\me
> \gitrepos\aws-sdk-cpp\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
> 
>     853 Warning(s)
>     4 Error(s)

### Expected Behavior

 a successful build of aws cpp sdk

### Current Behavior

build fails with errors and warnings

### Reproduction Steps

see bug description

### AWS CPP SDK version used

commit 940e5f066a06be316cb61a63839d841a9922bf2a (HEAD -> main, tag: 1.9.242, origin/master, origin/main, origin/HEAD)

### Compiler and Version used

Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework Copyright (C) Microsoft Corporation. All rights reserved.  16.7.0.37604

### Operating System and version

Microsoft Windows [Version 10.0.19044.1645]

**Comment by jmklix** [comment]
P63991765

**Comment by jmklix** [comment]
We have changed the build process so this failure should no longer be occurring.
