### ISSUE TITLE
'tmpnam' linker warning

### ISSUE THREAD

**Issue by jmccl** [aws/aws-sdk-cpp#192]
When I linke a program statically linked with the sdk (linux, gcc) I get the following warning.

//usr/local/lib/libaws-cpp-sdk-core.a(FileSystemUtils.cpp.o): In function `Aws::Utils::FileSystemUtils::CreateTempFilePath()':
FileSystemUtils.cpp:(.text+0x21dc): warning: the use of `tmpnam' is dangerous, better use `mkstemp'

This is using gcc 5.3.0.

**Comment by JonathanHenson** [comment]
We are aware of this. It doesn't break the builds as far as I know, and the tempnam is only being used for unit tests. mkstemp actually makes a file, which isn't what we want. As soon as we have a suitable work around, will remove.

**Comment by zwass** [comment]
@JonathanHenson Over on the osquery project (https://github.com/facebook/osquery) this is going to cause failures in our weekly static analysis runs. We would very much appreciate a workaround.

**Comment by JonathanHenson** [comment]
For those platforms, I'll just make it generate a hash off of the current timestamp.

Also, if you have data from your static analysis related to the SDK, I'd love to see it.

Shoot me an email, and I'll give you my amazon email address.

Jonathan.michael.henson@gmail.com

**Comment by zwass** [comment]
Thank you. As far as I know we are just turning on all warnings, ASAN and TSAN, and I don't think we've found anything interesting in relation to the SDK. @theopolis could confirm.

**Comment by theopolis** [comment]
Nothing to report from the `kenesis` and `firehose` usage, our weekly sanitization runs just turn on clang's sanitization frameworks that @zwass mentioned, fail the compile if clang's [static analysis](https://github.com/facebook/osquery/blob/master/tools/analysis/clang-analyze.sh) has results, cpp-checks for performance recommendations, and sets strict warnings to errors.

We do *not* build + test all of the AWS SDK and its unit tests. Running the whole set after a TSAN, ASAN, and UBSAN would be cool but is too much for our build hosts right now.

**Comment by JonathanHenson** [comment]
This has been fixed. See https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/platform/linux-shared/FileSystem.cpp
