### ISSUE TITLE
MultiplePartGetRequests

### ISSUE THREAD

**Issue by TechBeings** [aws/aws-sdk-cpp#193]
Hi
I need to do multiple part downloads from S3, but this seems not to be implemented in the TransferClient class.
Is there a specific reason for this or is it even possible with the cpp SDK?
thanks a lot.

**Comment by JonathanHenson** [comment]
This is not yet in the transfer client. You can do it directly with the S3 client for now. Also, we are more than happy to take a pull request if you beat us to it.

**Comment by mmustafa-hp** [comment]
This would be a really good addition to the SDK. I deal with large files and having multipart capability will enable us to offer a much better downloader for our application

**Comment by singku** [comment]
@mmustafa-hp The MultipartDownload in S3 is actually done with GetObjectRangeRequest. And transferManager DownloadFile is using this way.
