### ISSUE TITLE
Partial multipart download attempts to retrieve incorrect number of bytes

### ISSUE THREAD

**Issue by peteboothroyd** [aws/aws-sdk-cpp#1932]
### Describe the bug

This is not a contribution.

When using the DownloadFile operation on TransferManager to download a subset of a file from s3 using the fileOffset & downloadBytes options ([link](https://github.com/aws/aws-sdk-cpp/blob/79f94bcc32d255df5a57fc2a5b93812b5ec5b5dc/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp#L111-L118)) only the part of the file from bytes [fileOffset: fileOffset +downloadBytes) should be downloaded. However due to a bug in the use of a head object request the downloadBytes is set to the total size of the file.

### Expected Behavior

Exactly bytes [fileOffset: fileOffset + downloadBytes) should be downloaded

### Current Behavior

Bytes [fileOffset: fileOffset + fileLength] are attempted to be downloaded. As far as I can tell the fileOffset is set correctly, so I'm not sure what happens when fileOffset > 0 as the upper bound then moves beyond the end of the file.

### Reproduction Steps

I hit this through the tensorflow integration so the [following lines](https://github.com/tensorflow/io/blob/60b6338eaa3381a60609aade4605dffef6b2d9b4/tensorflow_io/core/filesystems/s3/s3_filesystem.cc#L291-L299) are sufficient to reproduce.

### Possible Solution

I believe the root cause are these [two lines](https://github.com/aws/aws-sdk-cpp/blob/79f94bcc32d255df5a57fc2a5b93812b5ec5b5dc/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp#L758-L759) where the `m_bytesTotalSize` is set using the content length of the head object call. From the [headobject docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.head_object) content length is the total length of the file. It appears that the implementation expects it to be the size of the [desired range](https://github.com/aws/aws-sdk-cpp/blob/79f94bcc32d255df5a57fc2a5b93812b5ec5b5dc/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp#L734-L741), but the docs say that this parameter is ignored:

> Range (string) -- Because HeadObject returns only the metadata for an object, this parameter has no effect.

I believe that this could be fixed by changing

```
handle->SetBytesTotalSize(downloadSize);
```

to 

```
if (handle->GetBytesTotalSize() == 0) {
  handle->SetBytesTotalSize(downloadSize);
}
```

### AWS CPP SDK version used

1.9.260

### Compiler and Version used

N/A

### Operating System and version

N/A

**Comment by peteboothroyd** [comment]
Actually looking more into this, there are also issues when configuring the download parts as the offset is not taken into account when [setting the rangeBegin](https://github.com/aws/aws-sdk-cpp/blob/79f94bcc32d255df5a57fc2a5b93812b5ec5b5dc/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp#L780).

**Comment by jmklix** [comment]
Do you have logs from when this is happening?

**Comment by peteboothroyd** [comment]
I do not have any logs, sorry.

**Comment by jmklix** [comment]
There have been some recent changes to transfer manager to fix `m_bytesTotalSize`. Can you update to the latest version is see if you are still getting the incorrect number of bytes?
