### ISSUE TITLE
Compile error  error: 'AWS_IO_INVALID_FILE_HANDLE' undeclared 

### ISSUE THREAD

**Issue by SebTV** [aws/aws-sdk-cpp#1939]
### Describe the bug

Building SDK 1.9.268 under Linux/gcc leads to the error above.
It looks like the symbol is renamed to `DEPRECATED_AWS_IO_INVALID_FILE_HANDLE` in `aws-c-io/include/aws/io/io.h`, but still in use in `aws-c-io/source/windows/file_utils.c `and `aws-c-io/source/posix/file_utils.c`

### Expected Behavior

The code should compile

### Current Behavior

Compilation stops with an error

### Reproduction Steps

git-clone (with submodules) from gitlab on the tag 1.9.268
Configure with cmake 3.20.5 (I am using s3 and meteringmarketplace only)

### Possible Solution

If the symbol is deprecated, stop using it in `source/windows/file_utils.c` or "fix" it by renaming as in `source/io.c`

### AWS CPP SDK version used

1.9.268

### Compiler and Version used

gcc 7.4.0

### Operating System and version

CentOS 7

**Comment by SebTV** [comment]
Also the include of `aws/common/file.h` (by file_utils.h) causes a conflicting definition for `aws_path_exists()`.
Reverting the `DEPRECATE_` marker and changing include `aws/common/file.h` to `aws/io/io.h` at least fixes the compilation.

**Comment by jmklix** [comment]
Can you list the exact cmake command that you are using after git clone?

Also I don't see the `file_utils.c` that you mentioned in either location:
https://github.com/awslabs/aws-c-io/tree/main/source/windows
https://github.com/awslabs/aws-c-io/tree/main/source/posix
