### ISSUE TITLE
Unable to build for Android

### ISSUE THREAD

**Issue by jmklix** [aws/aws-sdk-cpp#1946]
### Discussed in https://github.com/aws/aws-sdk-cpp/discussions/1944

<div type='discussions-op-text'>

<sup>Originally posted by **IIAwesomeII** June  6, 2022</sup>
Hello,
I am trying to build for android using this code on windows:

> cmake -G "NMake Makefiles" `-DTARGET_ARCH=ANDROID` -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3" 
But, it is giving me this error:

> NMake : fatal error U1065: invalid option 'j'

Am i doing something wrong?
I am following the instructions mentioned here on github.
</div>

**Comment by jmklix** [comment]
@IIAwesomeII there seams to be something wrong with the dependencies that NMAKE is trying to build. I'm getting the same error with the current version of this sdk:
```
NMAKE : fatal error U1065: invalid option 'j'
Stop.
CMake Error at cmake/build_external.cmake:148 (message):
  Failed to build dependency libraries.
Call Stack (most recent call first):
  CMakeLists.txt:166 (include)
```

For now please use the last version of 1.8 of this sdk when building for android. I tested this on windows, so it should work for you. 

I created this bug from the discussions so we can let you know when it gets fixed

**Comment by jmklix** [comment]
P65507276

**Comment by Sam-Slater97** [comment]
Hey, Is there a release date for this bug? Still happening when trying to build form android on windows.

**Comment by Kiptoo-Deus** [comment]
Did anyone find a solution to "NMAKE : fatal error U1065: invalid option 'j' "

**Comment by jmklix** [comment]
Sorry for the delay, but we have fixed, then broke, and then fixed again the builds on android. Here is the recent [issue](https://github.com/aws/aws-sdk-cpp/issues/3014) and latest [fix](https://github.com/aws/aws-sdk-cpp/pull/3023) for building on Android. Please let us know if you still have any problems with building this sdk for Android
