### ISSUE TITLE
Access denied to SSM parameter (via GetParameter), although policy in place

### ISSUE THREAD

**Issue by euser153** [aws/aws-sdk-cpp#1947]
### Describe the bug

for this flow:
1) We are adding a new parameter to the parameter store
2) we updating policy via ansible task with IAM_policy.
3) try to retrieve password via aws-sdk-cpp  ssm:GetParamter

We get for around 2 minutes 
 'AccessDeniedException': User: ... is not authorized to perform: ssm:GetParameter on resource: ... because no identity-based policy allows the ssm:GetParameter action

After a 2 minute of retries, it succeed (with no additional action).

### Expected Behavior

When Policy updated correctly, GetParameter should succeed

### Current Behavior

AccessDeniedException, although policy is correct (it succeed eventually) 

### Reproduction Steps

1) We are adding a new parameter to the parameter store
2) we updating policy via ansible task with IAM_policy.
3) try to retrieve password via aws-sdk-cpp  ssm:GetParamter

### Possible Solution

Sleep for 2.5 minutes

### Additional Information/Context

our policy:

 {
            "Action": "ssm:GetParameters","ssm:GetParameter","ssm:GetParametersByPath"
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ssm:eu-central-1:905361737089:parameter/MasterPassword",
                "arn:aws:ssm:eu-central-1:905361737089:parameter/AdministratorPassword",
                "arn:aws:ssm:eu-central-1:905361737089:parameter/DBPassword"
            ]
        }

### AWS CPP SDK version used

1922

### Compiler and Version used

Visual Studio 2019

### Operating System and version

Windows

**Comment by jmklix** [comment]
Do you have a minimal code sample that reproduces this?

**Comment by mathix420** [comment]
I had the same issue, here is the managed policy used on a EC2 instance role
 ```
arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
```

Then I was running this command (fetching cw-agent config):
```bash
sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c ssm:CloudWatchAgentConfig-neo4j-dev-stack2 -s
```

Generated this output:
```
****** processing amazon-cloudwatch-agent ******
2023/12/08 17:54:21 E! Fail to fetch/remove json config: AccessDeniedException: User: arn:aws:sts::REDACTED:assumed-role/neo4j-dev-stack2-Neo4jRole-t35E3Ct6Vn6Z/i-REDACTED is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:REDACTED:parameter/CloudWatchAgentConfig-neo4j-dev-stack2 because no identity-based policy allows the ssm:GetParameter action
	status code: 400, request id: REDACTED
```

Seems to not be the only one, have a look there https://stackoverflow.com/questions/65653103/aws-system-manager-getparameters-permission-being-implicitly-denied

I tried the most liked response, will update this post with feedback about it.
