### ISSUE TITLE
-DCUSTOM_MEMORY_MANAGEMENT=0  flag doesn't work

### ISSUE THREAD

**Issue by rabinnh** [aws/aws-sdk-cpp#195]
When this flag is set, I don't expect to get a link error:

/projects/unroadmap/adns/adnsedgepackager/../aws-sdk-libs/include/aws/core/utils/memory/stl/AWSAllocator.h:74: undefined reference to `Aws::Free(void*)'

This is because of:

        void deallocate(typename Base::pointer p, size_type n)
        {
            AWS_UNREFERENCED_PARAM(n);

            Free(p);
        }

Apparently, in the same class, somewhere "Malloc" has been defined, but "Free" has not.

This is on Ubuntu 14.04.4

**Comment by bretambrose** [comment]
Can you add your full cmake command line and what compiler you're using to this issue?

**Comment by rabinnh** [comment]
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3"  -DCUSTOM_MEMORY_MANAGEMENT=0 -DSTATIC_LINKING=1

~$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


The STATIC_LINKING flag is not relevant other than the readme says that with STATIC_LINKING customer memory management is turned off.  I tried without and with ('so' libs and 'a' libs).

I also realize that what should be happening is that Free and Malloc should are found in AWSMemory.cpp.  Is it possible that using BUILD_ONLY prevented some required modules to be left out?

**Comment by JonathanHenson** [comment]
BUILD_ONLY only affects the service-level clients, it should have nothing to do with aws-cpp-sdk-core where this module resides.

**Comment by bretambrose** [comment]
I will try to recreate this on my local machine, but it's an earlier version of Ubuntu.  If that doesn't work we'll need to wait until I get home tonight to try it on Ubuntu 14.

**Comment by bretambrose** [comment]
My initial test on Ubuntu 12 did not have any problems; I'll try on 14 later tonight.  Do you have a file called SDKConfig.h in your .../aws-cpp-sdk-core/include/aws/core/  directory?  If so, what's in it?  If not, what commit are you building off of?

**Comment by rabinnh** [comment]
I do.  All that is in it is below (SDKConfig.h).  I assume the "#undef" should not be commented.

/*
  * Copyright 2010-2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  *
  * Licensed under the Apache License, Version 2.0 (the "License").
  * You may not use this file except in compliance with the License.
  * A copy of the License is located at
  *
  *  http://aws.amazon.com/apache2.0
  *
  * or in the "license" file accompanying this file. This file is distributed
  * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
  * express or implied. See the License for the specific language governing
  * permissions and limitations under the License.
  */

/* #undef USE_AWS_MEMORY_MANAGEMENT */

**Comment by bretambrose** [comment]
Your SDKConfig.h looks correct given your cmake configuration.  It seems like USE_AWS_MEMORY_MANAGEMENT is getting defined somewhere else in your build process because your link error is from code that is only active if that is defined.

Do you get the link error building aws-cpp-sdk-core or when linking your own target against it?  Can you check the build and link flags  for aws-cpp-sdk-core (from your build directory -> aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/flags.make && link.txt) as well as your own target?

**Comment by rabinnh** [comment]
The link error is when building my own target (I don't define any of the SDK flags).

I want to note that I also get the "CryptoBuffer" build error mentioned in #194, with the difference that the build continues and the libraries are created successfully.  This seems a bit odd to me, but it looks like a build of a unit test is failing so the primary target continues.  A copy/paste of the section of the build I am referring to is at the bottom of this post.

flags.make and link.txt attached.
[link_files.tar.gz](https://github.com/aws/aws-sdk-cpp/files/293302/link_files.tar.gz)

[ 50%] Building CXX object aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/source/model/IndexDocument.cpp.o
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp: In function ‘void TestGCMMultipleBuffers(const String&, const String&, const String&, const String&, const String&)’:
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp:498:70: error: call of overloaded ‘CryptoBuffer(<brace-enclosed initializer list>)’ is ambiguous
     auto decryptResult = CryptoBuffer({ std::move(decryptedStreams) });
                                                                      ^
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp:498:70: note: candidates are:
In file included from /home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/utils/crypto/Factories.h:19:0,
                 from /home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp:17:
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/utils/Array.h:246:13: note: Aws::Utils::CryptoBuffer::CryptoBuffer(Aws::Utils::CryptoBuffer&&)
             CryptoBuffer(CryptoBuffer&& other) : ByteBuffer(std::move(other)) {}
             ^
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/utils/Array.h:245:13: note: Aws::Utils::CryptoBuffer::CryptoBuffer(const Aws::Utils::CryptoBuffer&)
             CryptoBuffer(const CryptoBuffer& other) : ByteBuffer(other) {}
             ^
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/utils/Array.h:244:13: note: Aws::Utils::CryptoBuffer::CryptoBuffer(const ByteBuffer&)
             CryptoBuffer(const ByteBuffer& other) : ByteBuffer(other) {}
             ^
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/utils/Array.h:243:13: note: Aws::Utils::CryptoBuffer::CryptoBuffer(Aws::Vector<Aws::Utils::Array<unsigned char>*>&&)
             CryptoBuffer(Aws::Vector<ByteBuffer*>&& toMerge) : ByteBuffer(std::move(toMerge)) {}
             ^
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp: In function ‘void TestCBCMultipleBlockBuffers(const String&, const String&, const String&, const String&)’:
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp:567:70: error: call of overloaded ‘CryptoBuffer(<brace-enclosed initializer list>)’ is ambiguous
     auto decryptResult = CryptoBuffer({ std::move(decryptedStreams) });
                                                                      ^
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp:567:70: note: candidates are:
In file included from /home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/utils/crypto/Factories.h:19:0,
                 from /home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp:17:
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/utils/Array.h:246:13: note: Aws::Utils::CryptoBuffer::CryptoBuffer(Aws::Utils::CryptoBuffer&&)
             CryptoBuffer(CryptoBuffer&& other) : ByteBuffer(std::move(other)) {}
             ^
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/utils/Array.h:245:13: note: Aws::Utils::CryptoBuffer::CryptoBuffer(const Aws::Utils::CryptoBuffer&)
             CryptoBuffer(const CryptoBuffer& other) : ByteBuffer(other) {}
             ^
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/utils/Array.h:244:13: note: Aws::Utils::CryptoBuffer::CryptoBuffer(const ByteBuffer&)
             CryptoBuffer(const ByteBuffer& other) : ByteBuffer(other) {}
             ^
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/utils/Array.h:243:13: note: Aws::Utils::CryptoBuffer::CryptoBuffer(Aws::Vector<Aws::Utils::Array<unsigned char>*>&&)
             CryptoBuffer(Aws::Vector<ByteBuffer*>&& toMerge) : ByteBuffer(std::move(toMerge)) {}
             ^
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp: In function ‘void TestCTRMultipleBlockBuffers(const String&, const String&, const String&, const String&)’:
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp:629:70: error: call of overloaded ‘CryptoBuffer(<brace-enclosed initializer list>)’ is ambiguous
     auto decryptResult = CryptoBuffer({ std::move(decryptedStreams) });
                                                                      ^
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp:629:70: note: candidates are:
In file included from /home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/utils/crypto/Factories.h:19:0,
                 from /home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core-tests/utils/crypto/SymmetricCiphersTest.cpp:17:
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/utils/Array.h:246:13: note: Aws::Utils::CryptoBuffer::CryptoBuffer(Aws::Utils::CryptoBuffer&&)
             CryptoBuffer(CryptoBuffer&& other) : ByteBuffer(std::move(other)) {}
             ^
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/utils/Array.h:245:13: note: Aws::Utils::CryptoBuffer::CryptoBuffer(const Aws::Utils::CryptoBuffer&)
             CryptoBuffer(const CryptoBuffer& other) : ByteBuffer(other) {}
             ^
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/utils/Array.h:244:13: note: Aws::Utils::CryptoBuffer::CryptoBuffer(const ByteBuffer&)
             CryptoBuffer(const ByteBuffer& other) : ByteBuffer(other) {}
             ^
/home/rbross/Dyn/projects/unroadmap/adns/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/utils/Array.h:243:13: note: Aws::Utils::CryptoBuffer::CryptoBuffer(Aws::Vector<Aws::Utils::Array<unsigned char>*>&&)
             CryptoBuffer(Aws::Vector<ByteBuffer*>&& toMerge) : ByteBuffer(std::move(toMerge)) {}
             ^
make[2]: *** [aws-cpp-sdk-core-tests/CMakeFiles/runCoreUnitTests.dir/utils/crypto/SymmetricCiphersTest.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 50%] Building CXX object aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/source/model/ObjectIdentifier.cpp.o

**Comment by bretambrose** [comment]
Can you attach the flags and link text for your target that doesn't link?  In particular, anything that provides the full compile command line for the .o file that is generating the bad reference as well as the full link command line for your target.

Also, a few more dumb questions:

In a previous message you said "I downloaded the zip from the repo on Friday"  Is "zip" just a typo?  I'm not aware of an archived release.

Have you been using the SDK for a while or is the Friday download the first time you've used it?

If you've been using the SDK previous to the last download, have you cleared your cmake build directory recently (for both the SDK and your target, if they are separate)?

**Comment by rabinnh** [comment]
The "Clone or Download" button on github has a "Download zip" link.

As far as compile flags;  unfortunately I'm on to another project with a deadline, so I might not get back to it for a few days.  I have *no* AWS C++ SDK flags defined.  I simply add the libraries to my linker list and cut and pasted the following from the README in main.cpp:

   SDKOptions options;
   Aws::InitAPI(options);
   Aws::ShutdownAPI(options);

But I did a grep anyway so I could confirm for you; no hits.

rab-sprt:~/projects/unroadmap/adns/adnsedgepackager$ grep -r USE_CUSTOM_MEMORY_MANAGEMENT *
rab-sprt:~/projects/unroadmap/adns/adnsedgepackager$

**Comment by JonathanHenson** [comment]
If you are using cmake, I don't recommend manually specifying flags, we provide export targets that will do all of this for you.

**Comment by JonathanHenson** [comment]
Any updates on this?

**Comment by JonathanHenson** [comment]
closing per no updates. Feel free to reopen if issues persist
