### ISSUE TITLE
SendEmailRequest results in malformed post body

### ISSUE THREAD

**Issue by jmccl** [aws/aws-sdk-cpp#197]
This is related to a question I asked on the forums.

https://forums.aws.amazon.com/thread.jspa?threadID=232576&tstart=0

The problem seems to be that extra periods are being inserted into the post body. So pre-patch the post body looks something like this. Note the '..' in the keys.

> Action=SendEmail&Source=foo%40foo.com&Destination..ToAddresses.member.1=success%40simulator.amazonses.com&Message..Subject.Data=fooMessage..Body.Text.Data=foo

This patch 'fixes' that and allows mail to be sent.

```
--- a/aws-cpp-sdk-email/source/model/SendEmailRequest.cpp
+++ b/aws-cpp-sdk-email/source/model/SendEmailRequest.cpp
@@ -40,11 +40,11 @@ Aws::String SendEmailRequest::SerializePayload() const
   }
   if(m_destinationHasBeenSet)
   {
-    m_destination.OutputToStream(ss, "Destination.");
+    m_destination.OutputToStream(ss, "Destination");
   }
   if(m_messageHasBeenSet)
   {
-    m_message.OutputToStream(ss, "Message.");
+    m_message.OutputToStream(ss, "Message");
   }
   if(m_replyToAddressesHasBeenSet)
   {
```
I'm not sure if this is the right way to fix this or whether the other period somewhere in the code should be removed.

**Comment by JonathanHenson** [comment]
what version of the SDK are you using?

**Comment by jmccl** [comment]
Built from head of a few days ago.

commit db75e727a4101d3485143c9b69a65e2717fc71e6

**Comment by JonathanHenson** [comment]
Fixed. It will be a few hours before this makes it out to NuGet, so be aware of that if you use it.

**Comment by jmccl** [comment]
Thanks for the fix.
