### ISSUE TITLE
Content-Length for CreateMultipartUploadRequest

### ISSUE THREAD

**Issue by stas2** [aws/aws-sdk-cpp#198]
When doing a CreateMultipartUploadRequest the SDK sends a POST request with no Content-Length header. I work with a Mono-based third-party S3-compatible server and it rejects the request:
```
POST /automated-test-local/testbigfile.txt?uploads HTTP/1.1
authorization: ...
user-agent: aws-sdk-cpp/0.12.3 Linux/4.5.4-1-ARCH x86_64
x-amz-content-sha256: ...
x-amz-date: 20160531T202446Z

HTTP/1.1 411 Length Required
Content-Type: text/html; charset=utf-8
Server: Mono-HTTPAPI/1.0
Date: Tue, 31 May 2016 20:24:46 GMT
Content-Length: 24
Connection: close
 
<h1>Length Required</h1>
```
It seems the server legitimately rejects the request since according to RFC the server may require Content-Length specified for POST requests: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4 . Unfortunately I cannot implement a workaround in the server to ignore the missing header since the behaviour is implemented in a core class, System.Net.HttpListener. Relevant explanation here, https://bugzilla.novell.com/show_bug.cgi?id=323215#c1 .

AWS SDK for .NET does send the Content-Length header in this case.

Would you accept a pull request that fixes this issue? See relevant commit here: https://github.com/stas2/aws-sdk-cpp/commit/c0d6f19bb19e674eccf475189dc290e5a1c03932

**Comment by JonathanHenson** [comment]
Unfortunately, it isn't possible to fill in content-length for you without seeking the stream (which has the potential to be extremely costly), it is up to the user  to set the content-length, since it is much more likely that the user has a more cost-effective mechanism to know the content length, we leave that task to the user.

AWS SDK for .NET or Java or any other language binding, aren't trying to accommodate high-performance use cases and it makes more sense for them to set it for you than it does for C++.

**Comment by JonathanHenson** [comment]
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/client/AWSClient.cpp

Line 272. 

Could I see the logs?

**Comment by JonathanHenson** [comment]
Ah... I see. The problem is if you are POSTing an empty body. We'll submit an update for this shortly.

**Comment by stas2** [comment]
Yes, the question is about when there is no body. At present the SDK does not sent Content-Length in header. A relevant line from log is like this,
`
[TRACE] 2016-05-27 17:36:10 AWSClient [139821993359168] No content body, removing content-type and content-length headers
`

**Comment by stas2** [comment]
Jonathan, thank you for the prompt action.
I have tested it today. The SDK now sets the Content-Length to 0 as expected.

But  curl attempts to send upload data since it is a POST request. 

See https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp#L400 , request.GetContentBody() returns NULL so CURLOPT_READFUNCTION remains at default and reads from stdin. The client application will now be waiting for user input and pressing Ctrl-D resumes it.

I have already had the same issue and solved it by modifying CurlHttpClient.cpp/SetOptCodeForHttpMethod so it works similarly to when there is no Content-Length header and uses CURLOPT_CUSTOMREQUEST, "POST" :
https://github.com/stas2/aws-sdk-cpp/commit/c0d6f19bb19e674eccf475189dc290e5a1c03932#diff-e9fe81d4c79594b967aa545ec1fdd3c0R170

but you have not included it in the fix for some reason? Is there something I am missing here? 

Also in your commit please can you revisit [AWSClient.cpp#L278](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/client/AWSClient.cpp#L278) , this looks redundant.

**Comment by JonathanHenson** [comment]
Yes, sorry about the mistake, I forgot about curl and custom request stuff. 

Also, I must have copy and pasted something on accident on L278. Thanks for pointing that out. Updated, I'll push it out shortly.

**Comment by JonathanHenson** [comment]
Ok just updated again. Give it a go and let me know if you have any more trouble.
