### ISSUE TITLE
Transfer Client Bails out on download with successful status 

### ISSUE THREAD

**Issue by mmustafa-hp** [aws/aws-sdk-cpp#202]
When downloading a ~4 GB file from S3 using the transfer client, it intermittently exits the download with all successful return codes from isDone and CompletedSuccessfully and no reported failure. However it only downloaded a part of the file.
The content length = 5292737876
Progress stopped at  385695744

Excerpts from the log file:
Date: Tue, 17 May 2016 00:20:37 GMT

**Content-Length:** 5292737876**

Content-Type: application/octet-stream

Last-Modified: Thu, 28 Apr 2016 20:46:24 GMT

Accept-Ranges: bytes

ETag: "b67f4187d540c26d12649110adce0d02-79"

Server: AmazonS3

x-amz-id-2: EqVtzfl8012Gneq3kV2mAosTGjsyNCSwJjeBGOTCEbPcjz0nYZJBJgJ3c3UMp73R+kTarUx8t74=

x-amz-request-id: D20C7BC36BD2A1FE

x-amz-version-id: 8u3lpyw2iKnzUiSVglg74KjG7DnpoAMR

[DEBUG] 2016-05-17 08:20:36 WinHttpSyncHttpClient [6880] Closing http request handle 00000273362B4620
[DEBUG] 2016-05-17 08:20:36 WinHttpSyncHttpClient [6880] Releasing connection handle 0000027331EC4A90
[DEBUG] 2016-05-17 08:20:36 WinHttpConnectionPoolMgr [6880] Releasing connection to endpoint s3.amazonaws.com:443.
[DEBUG] 2016-05-17 08:20:36 AWSClient [6880] Request returned successful response.
[TRACE] 2016-05-17 08:20:36 AWSClient [6880] Request was either successful, or we are now out of retries.
[DEBUG] 2016-05-17 08:20:37 DownloadManagerAWS [6656] Progress update - 16384
[DEBUG] 2016-05-17 08:20:38 DownloadManagerAWS [6656] Progress update - 155648
many progress updates later ....
[DEBUG] 2016-05-17 08:23:20 DownloadManagerAWS [6656] Progress update - 378150912
[DEBUG] 2016-05-17 08:23:21 DownloadManagerAWS [6656] Progress update - 381820928
[DEBUG] 2016-05-17 08:23:22 DownloadManagerAWS [6656] Progress update - 385695744
[DEBUG] 2016-05-17 08:23:23 WinHttpSyncHttpClient [200] Closing http request handle 0000027331E95240
[DEBUG] 2016-05-17 08:23:23 WinHttpSyncHttpClient [200] Releasing connection handle 00000273362B0840
[DEBUG] 2016-05-17 08:23:23 WinHttpConnectionPoolMgr [200] Releasing connection to endpoint s3.amazonaws.com:443.
[DEBUG] 2016-05-17 08:23:23 AWSClient [200] Request returned successful response.
[TRACE] 2016-05-17 08:23:23 AWSClient [200] Request was either successful, or we are now out of retries.
[DEBUG] 2016-05-17 08:23:23 DownloadManagerAWS [6656] Done - Progress at 100
[TRACE] 2016-05-17 08:23:23 DownloadManagerAWS [6656] <<< WaitForDownloadAndUpdate
[TRACE] 2016-05-17 08:23:23 DownloadManagerAWS [6656] <<< TransferObject - 1 - 
[TRACE] 2016-05-17 08:23:23 DownloadManagerAWS [6656] >>> TransferObject
[TRACE] 2016-05-17 08:23:23 AWSClient [5104] No content body, removing content-type and content-length headers
[DEBUG] 2016-05-17 08:23:23 AWSAuthV4Signer [5104] Calculated sha256 e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 for payload.
[TRACE] 2016-05-17 08:23:23 DownloadManagerAWS [6656] >>> WaitForDownloadAndUpdate
[DEBUG] 2016-05-17 08:23:23 DownloadManagerAWS [6656] Initial Download progress - 0
[DEBUG] 2016-05-17 08:23:23 AWSAuthV4Signer [5104] Canonical Header String: host:s3.amazonaws.com
user-agent:aws-sdk-cpp/0.9.6-76-gb216290 Windows/6.2.9200- AMD64
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20160517T002323Z

**Comment by mmustafa-hp** [comment]
Is there any update? this issue is causing may users to experience failed downloads.
we update the sdk to 0.12.6 and still encounter the failure.

Some of the failed logs have this entry:
[WARN] 2016-06-22 21:42:23 EnumParseOverflowContainer [9760] Encountered enum member COMPLETED which is not modeled in your clients. You should update your clients when you get a chance.

**Comment by JonathanHenson** [comment]
Ok, the latest comment is a bug that you just uncovered in our S3 api definition. I'm submitting a CR right now to get that fixed in the next release.

Unless you are using Replication Status that should affect you though.

I'm still looking in to your actual problem.

**Comment by mmustafa-hp** [comment]
We are not currently using replication status.

**Comment by JonathanHenson** [comment]
What's the timeout on your client configuration?

**Comment by JonathanHenson** [comment]
[DEBUG] 2016-05-17 08:23:23 AWSClient [200] Request returned successful response.
[TRACE] 2016-05-17 08:23:23 AWSClient [200] Request was either successful, or we are now out of retries.

These lines show that at the least winhttp thinks it wrote the whole body out to the stream.

**Comment by JonathanHenson** [comment]
Can you check the size of the file on disk? I suspect the progress update may just be wrong.

**Comment by mmustafa-hp** [comment]
We have hit this issue multiple times. The file on disk is a partial download. This happens early or sometime late in the download.
I filed the progress update accuracy issue as well.

**Comment by mmustafa-hp** [comment]
the connectTimeoutMS and requestTimeoutMS are set to 90000

**Comment by JonathanHenson** [comment]
If you do a GetObject using the S3Client directly on that object, what happens? does it succeed?

**Comment by mmustafa-hp** [comment]
don't know. The issue is intermittent. We would need to instrument the code to catch the failure condition and switch to an S3Client.
A casual observation of the failures, it seems to be worst when downloading from singapore and sydney and the source bucket is in Virginia

**Comment by JonathanHenson** [comment]
One more thing, there should be a line in that log that says:

"Received response code "   something

Can you find it during the failure and post it?

**Comment by mmustafa-hp** [comment]
The last response code entry from a small file grab before starting on the big file. There are none after this point. 

[DEBUG] 2016-06-23 20:33:35 WinHttpSyncHttpClient [8880] Received response code 200
[DEBUG] 2016-06-23 20:33:35 WinHttpSyncHttpClient [8880] Received content type application/octet-stream
[DEBUG] 2016-06-23 20:33:35 WinHttpSyncHttpClient [8880] Received headers:
[DEBUG] 2016-06-23 20:33:35 WinHttpSyncHttpClient [8880] HTTP/1.1 200 OK

Date: Thu, 23 Jun 2016 12:33:45 GMT

Content-Length: 4006362650

Content-Type: application/octet-stream

Last-Modified: Fri, 27 May 2016 18:13:02 GMT

Accept-Ranges: bytes

ETag: "e073c0e87565d5b136005953f987f19d-60"

Server: AmazonS3

x-amz-id-2: vnxSED5tek26JC9ns6JFRHYjZhP+a3bnkxyE/Ff55zUc5IsHLnJfXSkYUlBDEzWj

x-amz-request-id: D7670C9918E7574E

x-amz-replication-status: COMPLETED

x-amz-version-id: XISP0T9FPAUKqZ_nqVkyaJY2tiK4NQ1z




[DEBUG] 2016-06-23 20:33:36 DownloadManagerAWS [8932] Progress update - 0.00238419
[DEBUG] 2016-06-23 20:33:37 DownloadManagerAWS [8932] Progress update - 0.00724792
[DEBUG] 2016-06-23 20:33:38 DownloadManagerAWS [8932] Progress update - 0.0194073
[DEBUG] 2016-06-23 20:33:39 DownloadManagerAWS [8932] Progress update - 0.0526428
[DEBUG] 2016-06-23 20:33:40 DownloadManagerAWS [8932] Progress update - 0.107765
[DEBUG] 2016-06-23 20:33:41 DownloadManagerAWS [8932] Progress update - 0.15316
[DEBUG] 2016-06-23 20:33:42 DownloadManagerAWS [8932] Progress update - 0.319099
[DEBUG] 2016-06-23 20:33:43 DownloadManagerAWS [8932] Progress update - 0.437355
[DEBUG] 2016-06-23 20:33:44 DownloadManagerAWS [8932] Progress update - 0.554085
[DEBUG] 2016-06-23 20:33:45 DownloadManagerAWS [8932] Progress update - 0.673103
[DEBUG] 2016-06-23 20:33:46 DownloadManagerAWS [8932] Progress update - 0.790596
[DEBUG] 2016-06-23 20:33:47 DownloadManagerAWS [8932] Progress update - 0.908852
[DEBUG] 2016-06-23 20:33:48 DownloadManagerAWS [8932] Progress update - 1.02711
[DEBUG] 2016-06-23 20:33:49 DownloadManagerAWS [8932] Progress update - 1.08433
[DEBUG] 2016-06-23 20:33:50 DownloadManagerAWS [8932] Progress update - 1.26209
[DEBUG] 2016-06-23 20:33:51 DownloadManagerAWS [8932] Progress update - 1.38111
[DEBUG] 2016-06-23 20:33:52 DownloadManagerAWS [8932] Progress update - 1.49784
[DEBUG] 2016-06-23 20:33:53 DownloadManagerAWS [8932] Progress update - 1.60084
[DEBUG] 2016-06-23 20:33:54 DownloadManagerAWS [8932] Progress update - 1.70689
[DEBUG] 2016-06-23 20:33:55 DownloadManagerAWS [8932] Progress update - 1.81522
[DEBUG] 2016-06-23 20:33:56 DownloadManagerAWS [8932] Progress update - 1.92356
[DEBUG] 2016-06-23 20:33:57 DownloadManagerAWS [8932] Progress update - 2.03648
[DEBUG] 2016-06-23 20:33:58 DownloadManagerAWS [8932] Progress update - 2.15092
[DEBUG] 2016-06-23 20:33:59 DownloadManagerAWS [8932] Progress update - 2.26765
[DEBUG] 2016-06-23 20:34:00 DownloadManagerAWS [8932] Progress update - 2.38285
[DEBUG] 2016-06-23 20:34:01 DownloadManagerAWS [8932] Progress update - 2.49882
[DEBUG] 2016-06-23 20:34:02 DownloadManagerAWS [8932] Progress update - 2.61555
[DEBUG] 2016-06-23 20:34:03 DownloadManagerAWS [8932] Progress update - 2.72923
[DEBUG] 2016-06-23 20:34:04 DownloadManagerAWS [8932] Progress update - 2.84519
[DEBUG] 2016-06-23 20:34:05 DownloadManagerAWS [8932] Progress update - 2.96268
[DEBUG] 2016-06-23 20:34:06 DownloadManagerAWS [8932] Progress update - 3.07941
[DEBUG] 2016-06-23 20:34:07 DownloadManagerAWS [8932] Progress update - 3.09696
[DEBUG] 2016-06-23 20:34:08 DownloadManagerAWS [8932] Progress update - 3.14274
[DEBUG] 2016-06-23 20:34:09 DownloadManagerAWS [8932] Progress update - 3.15113
[DEBUG] 2016-06-23 20:34:10 DownloadManagerAWS [8932] Progress update - 3.1702
[DEBUG] 2016-06-23 20:34:12 DownloadManagerAWS [8932] Progress update - 3.20148
[DEBUG] 2016-06-23 20:34:13 DownloadManagerAWS [8932] Progress update - 3.20301
[DEBUG] 2016-06-23 20:34:15 DownloadManagerAWS [8932] Progress update - 3.20606
[DEBUG] 2016-06-23 20:34:16 DownloadManagerAWS [8932] Progress update - 3.20759
[DEBUG] 2016-06-23 20:34:17 DownloadManagerAWS [8932] Progress update - 3.21064
[DEBUG] 2016-06-23 20:34:18 DownloadManagerAWS [8932] Progress update - 3.21445
[DEBUG] 2016-06-23 20:34:19 DownloadManagerAWS [8932] Progress update - 3.22056
[DEBUG] 2016-06-23 20:34:20 DownloadManagerAWS [8932] Progress update - 3.23887
[DEBUG] 2016-06-23 20:34:21 DownloadManagerAWS [8932] Progress update - 3.26099
[DEBUG] 2016-06-23 20:34:22 DownloadManagerAWS [8932] Progress update - 3.29227
[DEBUG] 2016-06-23 20:34:23 DownloadManagerAWS [8932] Progress update - 3.3289
[DEBUG] 2016-06-23 20:34:24 DownloadManagerAWS [8932] Progress update - 3.35789
[DEBUG] 2016-06-23 20:34:25 DownloadManagerAWS [8932] Progress update - 3.41053
[DEBUG] 2016-06-23 20:34:26 DownloadManagerAWS [8932] Progress update - 3.45249
[DEBUG] 2016-06-23 20:34:27 DownloadManagerAWS [8932] Progress update - 3.45783
[DEBUG] 2016-06-23 20:34:28 DownloadManagerAWS [8932] Progress update - 3.46699
[DEBUG] 2016-06-23 20:34:29 DownloadManagerAWS [8932] Progress update - 3.47462
[DEBUG] 2016-06-23 20:34:30 DownloadManagerAWS [8932] Progress update - 3.50666
[DEBUG] 2016-06-23 20:34:31 DownloadManagerAWS [8932] Progress update - 3.50742
[DEBUG] 2016-06-23 20:34:32 DownloadManagerAWS [8932] Progress update - 3.512
[DEBUG] 2016-06-23 20:34:36 DownloadManagerAWS [8932] Progress update - 3.51658
[DEBUG] 2016-06-23 20:34:38 DownloadManagerAWS [8932] Progress update - 3.5181
[DEBUG] 2016-06-23 20:34:40 DownloadManagerAWS [8932] Progress update - 3.51887
[DEBUG] 2016-06-23 20:34:41 DownloadManagerAWS [8932] Progress update - 3.51963
[DEBUG] 2016-06-23 20:34:43 DownloadManagerAWS [8932] Progress update - 3.52039
[DEBUG] 2016-06-23 20:34:57 DownloadManagerAWS [8932] Progress update - 3.52116
[DEBUG] 2016-06-23 20:35:03 DownloadManagerAWS [8932] Progress update - 3.52268
[DEBUG] 2016-06-23 20:35:08 DownloadManagerAWS [8932] Progress update - 3.52345
[DEBUG] 2016-06-23 20:36:49 WinHttpSyncHttpClient [8880] Closing http request handle 00000250EFBA5600
[DEBUG] 2016-06-23 20:36:49 WinHttpSyncHttpClient [8880] Releasing connection handle 00000250EFBA4BE0
[DEBUG] 2016-06-23 20:36:49 WinHttpConnectionPoolMgr [8880] Releasing connection to endpoint s3.amazonaws.com:443.
[DEBUG] 2016-06-23 20:36:49 AWSClient [8880] Request returned successful response.
[TRACE] 2016-06-23 20:36:49 AWSClient [8880] Request was either successful, or we are now out of retries.
[WARN] 2016-06-23 20:36:49 EnumParseOverflowContainer [8880] Encountered enum member COMPLETED which is not modeled in your clients. You should update your clients when you get a chance.
[DEBUG] 2016-06-23 20:36:49 DownloadManagerAWS [8932] Done - Progress at 100
[TRACE] 2016-06-23 20:36:50 DownloadManagerAWS [8932] <<< WaitForDownloadAndUpdate
[TRACE] 2016-06-23 20:36:50 DownloadManagerAWS [8932] <<< TransferObject - 1 - 
[ERROR] 2016-06-23 20:36:50 AppLogicManager [8932] Failed to open WIM -- 650434-376.wim
[TRACE] 2016-06-23 20:36:50 AppLogicManager [8932] <<< AwsFormatDownloadApply - 0

**Comment by JonathanHenson** [comment]
Ok, I talked to the other SDK teams and it looks like S3 is prematurely closing the socket, and it causes the client end to exit the request normally.

 We have a few options: 

I will add a length check and compare it to the content-length header. I'll fail the request when this happens and it will retry the request. At least then we will report failures back to your stack.

We need to add partial downloads to the transfer client anyways, so we'll go ahead and queue that work up.

**Comment by mmustafa-hp** [comment]
thank you. I look forward to working with the changes when they become available.

**Comment by JonathanHenson** [comment]
Update has been pushed. Please feel free to reopen if issues persist.

**Comment by mmustafa-hp** [comment]
thank you. We integrated this release of sdk into our application and have started testing

**Comment by mmustafa-hp** [comment]
The issue is still occurring.

**Comment by mmustafa-hp** [comment]
Yes, sorry. HTTP code is 200 and only partial content is delivered. This is with release 0.12.17 and we are using the transfer client.

**Comment by mmustafa-hp** [comment]
Yes, sorry. HTTP code is 200 and only partial content is delivered. This is with release 0.12.17 and we are using the transfer client.

**Comment by mmustafa-hp** [comment]
We are observing a 30-40% occurrence of this issue. Where does it stand? Is the bug reopened?

**Comment by mmustafa-hp** [comment]
Analysis of more data shows that the failure rate increased with 0.12.17. Also, the failure correlates to the trasfer rate. Slow transfer rates have a very high failure rate.
