### ISSUE TITLE
aws-sdk-cpp-core ENABLE_UNITY_BUILD=OFF fails to compile

### ISSUE THREAD

**Issue by kwach** [aws/aws-sdk-cpp#2021]
### Describe the bug

Build failes with: 

aws-sdk-cpp/aws-cpp-sdk-core/source/config/EC2InstanceProfileConfigLoader.cpp:21:34: error: unused variable 'CONFIG_LOADER_TAG' [-Werror,-Wunused-const-variable]
        static const char* const CONFIG_LOADER_TAG = "Aws::Config::AWSProfileConfigLoader";
                                 ^
1 error generated.

### Expected Behavior

Built target aws-sdk-cpp

Build finished

### Current Behavior

Build failes with: 

aws-sdk-cpp/aws-cpp-sdk-core/source/config/EC2InstanceProfileConfigLoader.cpp:21:34: error: unused variable 'CONFIG_LOADER_TAG' [-Werror,-Wunused-const-variable]
        static const char* const CONFIG_LOADER_TAG = "Aws::Config::AWSProfileConfigLoader";
                                 ^
1 error generated.

### Reproduction Steps

compile with disabled unity build like this:
cmake ..
-DCMAKE_BUILD_TYPE=Debug
-DCMAKE_CXX_COMPILER=/usr/bin/clang++-12
-DCMAKE_C_COMPILER=/usr/bin/clang-12
-DBUILD_SHARED_LIBS=OFF
-DBUILD_ONLY=transfer;s3;sts
-DENABLE_UNITY_BUILD=OFF

### Possible Solution

remove the line: 
21:        static const char* const CONFIG_LOADER_TAG = "Aws::Config::AWSProfileConfigLoader";
from EC2InstanceProfileConfigLoader.cpp

### AWS CPP SDK version used

main aka 1.9.314

### Compiler and Version used

clang 12

### Operating System and version

ubuntu 22.04

**Comment by jmklix** [comment]
I can get the same error that you are seeing. Looking into if possible solution you made is the correct solution
