### ISSUE TITLE
FIPS connection using sdk

### ISSUE THREAD

**Issue by benshriki** [aws/aws-sdk-cpp#2023]
### Describe the bug

Hi,
I'm using S3Client and wish to support FIPS,
I've sent to the client constructor the region "us-west-1-fips" and I expect that your client will build the following URI:
"https://<bucket>.s3-fips.us-west-1.amazonaws.com"
but instead I'm getting the following URI:
"https://[bucket].s3.us-west-1-fips.amazonaws.com"

I've take a look at your code and it seem that the [S3Endpoint::ForRegion](https://github.com/aws/aws-sdk-cpp/blob/3e68aeac3771ee7ad3935d9765f5885c38a71966/aws-cpp-sdk-s3/source/S3Endpoint.cpp#L110) function will create the correct URI only when the service name is not empty and equals to s3. The [S3Client::init](https://github.com/aws/aws-sdk-cpp/blob/3e68aeac3771ee7ad3935d9765f5885c38a71966/aws-cpp-sdk-s3/source/S3Client.cpp#L166) function call the ForRegion function with empty service name always.

To sum up I'm not sure what is the correct way to create proper FIPS connection using the s3Client is there a different way to create the correct URI or create FIPS compliant connection using the s3client?

ps
same goes to kinesis client

Thank for your help

### Expected Behavior

I expect the client will build a proper fips uri such as 
"https://[bucket].s3-fips.[fips region].amazonaws.com"

### Current Behavior

the client build wrong uri for example when i'm passing "us-west-1-fips" i get:
"https://[bucket].s3.us-west-1-fips.amazonaws.com"

### Reproduction Steps

using the s3 client pass to the constructor the config with "us-west-1-fips" region.

### Possible Solution

fix [S3Endpoint::ForRegion](https://github.com/aws/aws-sdk-cpp/blob/3e68aeac3771ee7ad3935d9765f5885c38a71966/aws-cpp-sdk-s3/source/S3Endpoint.cpp#L110) logic to check if region contains "-fips" or "fips-" not only if the service name is not empty.

### AWS CPP SDK version used

1.9.262

### Compiler and Version used

gcc 4.9

### Operating System and version

window 10

**Comment by jmklix** [comment]
Looking into added a fix for this use case.

**Comment by jmklix** [comment]
Still working on finding and creating a fix for this, but I don't know when it will be completed as it is not a high priority

**Comment by DmitriyMusatkin** [comment]
Fips should work correctly in 1.11.x versions after endpoint resolution rewrite.

**Comment by ohookins** [comment]
Hi, did the endpoint resolution rewrite happen? Is the SDK considered FIPS-compliant now?
