### ISSUE TITLE
SendRawEmail Exception: Malformed RawMessage (with extra periods being inserted)

### ISSUE THREAD

**Issue by triton3** [aws/aws-sdk-cpp#204]
This is related to issue #197  .
The same problem of extra periods occurring in the raw message key. See example below (RawMessage Data is truncated):

    Action=SendRawEmail&RawMessage..Data=FBhaVbE1WVl***WTIxCg%3D%3D&Version=2010-12-01

The patch suggested in referenced post fixes the problem and allows emails to go through.

File: /aws-cpp-sdk-email/source/model/SendRawEmailRequest.cpp
Method: Aws::String SendRawEmailRequest::SerializePayload() const, line 52

    - m_rawMessage.OutputToStream(ss, "RawMessage.");
    + m_rawMessage.OutputToStream(ss, "RawMessage");

Output after fix (RawMessage Data is truncated):

    Action=SendRawEmail&RawMessage.Data=FBhaVbE1WVl***WTIxCg%3D%3D&Version=2010-12-01

**Comment by JonathanHenson** [comment]
Wow, good find! This actually occurs erroniously in 65 other places as well. I've fixed the problem in the generator and will push it out shortly

**Comment by JonathanHenson** [comment]
I just pushed the change out. It will be a few ours before the change makes it out to NuGet, so be aware of that if you are using NuGet.
