### ISSUE TITLE
Compile Error aws-cpp-sdk-core utils include of Array.h

### ISSUE THREAD

**Issue by micelic** [aws/aws-sdk-cpp#205]
Downloaded the lastest aws-sdk-cpp..  Now getting the following error during compile

[  2%] Building CXX object aws-cpp-sdk-core-tests/CMakeFiles/runCoreUnitTests.dir/utils/crypto/CryptoStreamsTest.cpp.o
In file included from /home/labuser/Oculi/kcp/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/crypto/Cipher.h:19:0,
                 from /home/labuser/Oculi/kcp/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/crypto/CryptoBuf.h:17,
                 from /home/labuser/Oculi/kcp/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/crypto/CryptoStream.h:17,
                 from /home/labuser/Oculi/kcp/aws-sdk-cpp/aws-cpp-sdk-core-tests/utils/crypto/CryptoStreamsTest.cpp:16:
/home/labuser/Oculi/kcp/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/Array.h:238:28: error: unused parameter \u2018other\u2019 [-Werror=unused-parameter]
         class AWS_CORE_API CryptoBuffer : public ByteBuffer
                            ^
/home/labuser/Oculi/kcp/aws-sdk-cpp/aws-cpp-sdk-core-tests/utils/crypto/CryptoStreamsTest.cpp: In member function \u2018void MockSymmetricCipher::SetFinalResponse(const Aws::Utils::CryptoBuffer&)\u2019:
/home/labuser/Oculi/kcp/aws-sdk-cpp/aws-cpp-sdk-core-tests/utils/crypto/CryptoStreamsTest.cpp:73:25: note: synthesized method \u2018Aws::Utils::CryptoBuffer& Aws::Utils::CryptoBuffer::operator=(const Aws::Utils::CryptoBuffer&)\u2019 first required here 
         m_finalResponse = finalResponse;
                         ^
cc1plus: all warnings being treated as errors
make[2]: *** [aws-cpp-sdk-core-tests/CMakeFiles/runCoreUnitTests.dir/utils/crypto/CryptoStreamsTest.cpp.o] Error 1
make[1]: *** [aws-cpp-sdk-core-tests/CMakeFiles/runCoreUnitTests.dir/all] Error 2

**Comment by JoyIfBam5** [comment]
There is a pull request #196 to fix this issue.

**Comment by micelic** [comment]
Thank you

**Comment by JonathanHenson** [comment]
I just pushed this internally, it should be out later tonight.
