### ISSUE TITLE
Intermittent SIGSEGV in Aws::S3::S3Client::PutBucketAcl()

### ISSUE THREAD

**Issue by kailascohesity** [aws/aws-sdk-cpp#2055]
### Describe the bug

I am intermittently seeing segmentation fault while calling Aws::S3::S3Client::PutBucketAcl().
The issue was consistent/very frequent when using slightly older release [aws-sdk-cpp-1.9.319].
The issue has become intermittent since I moved to release [aws-sdk-cpp-1.9.328].

Here's the stack trace (trimmed few initial calls as it's part of proprietary code) -
```
210660 *** Aborted at 1661395837 (unix time) try "date -d @1661395837" if you are using GNU date ***
210661 PC: @     0x7ffb1da49aa0 (unknown)                                              
210662 *** SIGSEGV (@0x0) received by PID 31 (TID 0x7ffb1b821280) from PID 0; stack trace: ***
210663     @     0x7ffb1db383fd google::(anonymous namespace)::FailureSignalHandler()  
210664     @     0x7ffb27ef0240 (unknown)                                              
210665     @     0x7ffb1da49aa0 (unknown)                                              
210666     @     0x7ffb1da4ae8a std::istream::tellg()                                  
210667     @          0x1d766e4 Aws::Utils::Crypto::MD5OpenSSLImpl::Calculate()        
210668     @          0x1d5f1f5 Aws::Utils::Crypto::MD5::Calculate()                   
210669     @          0x1d59fde Aws::Utils::HashingUtils::CalculateMD5()               
210670     @          0x1d87ee4 Aws::Client::AWSClient::AddChecksumToRequest()         
210671     @          0x1d8812c Aws::Client::AWSClient::BuildHttpRequest()             
210672     @          0x1d9295f Aws::Client::AWSClient::AttemptOneRequest()            
210673     @          0x1d93649 Aws::Client::AWSClient::AttemptExhaustively()          
210674     @          0x1d94fd7 Aws::Client::AWSXMLClient::MakeRequest()               
210675     @          0x1ce0120 Aws::S3::S3Client::PutBucketAcl()                      
```

### Expected Behavior

The API should complete consistently, without any crash/faults.

### Current Behavior

The SDK is crashing with segmentation fault.

### Reproduction Steps

Calling the same API PutBucketAcl() may reproduce the issue.
I am seeing the issue with two independent binaries.

### AWS CPP SDK version used

1.9.328

### Compiler and Version used

7.4.0

### Operating System and version

Linux u18-101104-01 5.4.0-80-generic #90~18.04.1-Ubuntu SMP Tue Jul 13 19:40:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jmklix** [comment]
Can you please include a minimal code snippet that reproduces this seg fault? and include sanitized logs from the sdk?

**Comment by win32asm** [comment]
DEAR PEOPLE FROM THE FUTURE: we have encountered a similar (same starting with ::AttemptExhaustively()) trace when deleting an empty object list.
Could it be that you were putting an empty object?
