### ISSUE TITLE
Using VS2019 to Build AWS-SDK-CPP files and libraries, Failing

### ISSUE THREAD

**Issue by inlandchris** [aws/aws-sdk-cpp#2059]
### Describe the bug

I am using VS2019 to make the libraries and its failing with the error msg:  Building Custom Rule D:/Projects/Sdks/aws-sdk-cpp-Source/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-cal/CMakeLists.txt
cl : command line error D8016: '/O2' and '/RTC1' command-line options are incompatible.
Whether its on the command line or inside VS2019, cannot build.
VS2019 is different than VS2015 and /RTC1 cannot operate with /O2 together. In the properties of each file is the "Optimization" where /O2 is specified. On the "Code Generation" property under "Basic Runtime Checks" is where AWS has put the switch "/RTC1". I have to change that to default although I have not tested it yet. There are a lot of files. 
What is the workaround?
<img width="2160" alt="Screenshot 2022-08-26 23 25 04" src="https://user-images.githubusercontent.com/71764733/186954931-fad6e2d8-ce98-4ef0-9ffb-569d9472c845.png">

### Expected Behavior

Expect no errors

### Current Behavior

I have to open each file separately and set the RTC1 to default, every FILE!

### Reproduction Steps

each file is modified for no /RTC1 if /O2 is set under Optimization

<img width="2160" alt="Screenshot 2022-08-27 00 11 16" src="https://user-images.githubusercontent.com/71764733/186957399-1ea6bae9-9d24-4c3f-be9e-4b6aae4b6d07.png">
<img width="2160" alt="Screenshot 2022-08-27 00 11 10" src="https://user-images.githubusercontent.com/71764733/186957416-07d85c84-fce1-4109-80f0-96e33eb77bc1.png">

### Possible Solution

Edit each individual code in VS2019 and change the Code Generation to default 

### AWS CPP SDK version used

latest clone from Github Aug 26, 2022

### Compiler and Version used

gcc== 12.1.0 , VS2019

### Operating System and version

windows 11, Version	10.0.22000 Build 22000

**Comment by jmklix** [comment]
Sorry for the slow reply. The building process of this sdk has changed since this issue was opened. I'm not able to reproduce this with the current version. Can you update and try again with the latest version
