### ISSUE TITLE
Error when linking the s3 library

### ISSUE THREAD

**Issue by cebukin** [aws/aws-sdk-cpp#206]
Hi, I keep getting an error when linking the s3 lib.

The code that's causing the problem is:
```  
client = Aws::MakeShared<S3Client>(ALLOCATION_TAG, Aws::Auth::AWSCredentials(accessKey, secretKey), config, true);
```

And I'm getting the following message from the linker:
```
Undefined symbols for architecture x86_64:
  "Aws::S3::S3Client::S3Client(Aws::Auth::AWSCredentials const&, Aws::Client::ClientConfiguration const&, bool)", referenced from:
      std::__1::shared_ptr<Aws::S3::S3Client> std::__1::shared_ptr<Aws::S3::S3Client>::allocate_shared<Aws::Allocator<Aws::S3::S3Client>, Aws::Auth::AWSCredentials, Aws::Client::ClientConfiguration&>(Aws::Allocator<Aws::S3::S3Client> const&, Aws::Auth::AWSCredentials&&, Aws::Client::ClientConfiguration&&&) in PersistenceManager.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Do you what is causing the problem? I got that line of code from snippets posted by the sdk developers. I'm also using the sdks latest version on a Mac.

**Comment by JonathanHenson** [comment]
It looks like you have pulled the latest source code but not rebuilt. We
added a flag to S3 to turn off payload hashing in the signing process. We
added a default argument to keep it on unless you specify it. However the
symbols probably mismatch because you have the new header file but not the
latest binary. Can you try cleaning and rebuilding?

On Wed, Jun 8, 2016 at 3:12 PM, Bruno Cebukin <notifications@github.com>
wrote:

> Hi, I keep getting an error when linking the s3 lib.
>
> The code that's causing the problem is:
> client = Aws::MakeShared<S3Client>(ALLOCATION_TAG,
> Aws::Auth::AWSCredentials(accessKey, secretKey), config);
>
> And im getting the following message from the linker:
> Undefined symbols for architecture x86_64:
> "Aws::S3::S3Client::S3Client(Aws::Auth::AWSCredentials const&,
> Aws::Client::ClientConfiguration const&, bool)", referenced from:
> std::__1::shared_ptr<Aws::S3::S3Client>
> std::__1::shared_ptr<Aws::S3::S3Client>::allocate_shared<Aws::Allocator<Aws::S3::S3Client>,
> Aws::Auth::AWSCredentials,
> Aws::Client::ClientConfiguration&>(Aws::Allocator<Aws::S3::S3Client>
> const&, Aws::Auth::AWSCredentials&&, Aws::Client::ClientConfiguration&&&)
> in PersistenceManager.cpp.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see
> invocation)
>
> Do you what is causing the problem? I got that line of code from snippets
> posted by the sdk developers. I'm also using the sdks latest version o a
> Mac.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/aws/aws-sdk-cpp/issues/206>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADvpxewikZhQADmqdwNS_4SHxmjwEJUMks5qJz43gaJpZM4IxdKw>
> .
>



-- 
"The poet only asks to get his head into the heavens. It is the logician
who seeks to get the heavens into his head. And it is his head that splits"
--G. K. Chesterton-- "Orthodoxy"

**Comment by cebukin** [comment]
Thanks, I got it to link now.
