### ISSUE TITLE
Enhance Memory Allocator to support allocator for just i/o(data) memory #927

### ISSUE THREAD

**Issue by leodotcloud** [aws/aws-sdk-cpp#2072]
### Describe the feature

Currently, the SDK provides the ability to specify a custom memory allocator. The same allocator is used for generic data structure allocations as well as for actual data transfers. This feature request is for adding another allocator which can be used for allocating memory for actual data transfers. For example, let's when using S3, memory for the file transfers uses this new allocator.

### Use Case

Data Privacy

### Proposed Solution

Add additional allocator support which is used to allocate memory when doing I/O.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by leodotcloud** [comment]
Initially created this [issue](https://github.com/awslabs/aws-c-common/issues/927), wasn't sure if that repo is being monitored by anyone.

**Comment by graebm** [comment]
Responded on the aws-c-common issue. Closing this one
