### ISSUE TITLE
Aws::InitAPI(options)

### ISSUE THREAD

**Issue by Cassiel1987** [aws/aws-sdk-cpp#2079]
### Describe the bug

aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-io/source/s2n/s2n_tls_channel_handler.c:195: 0 && "s2n_init() failed"

### Expected Behavior

I want to initialze Aws API success.

### Current Behavior

When I use Aws::InitAPI(options), s2n_init() failed: 402653236 (Error initializing trust store)

### Reproduction Steps

I use aws-sdk-cpp-s3 library and openssl librarys

### AWS CPP SDK version used

1.9.339

### Compiler and Version used

4.8.5

### Operating System and version

centos 7.6

**Comment by jmklix** [comment]
Are you making sure to set it up correctly as shown [here](https://github.com/aws/aws-sdk-cpp/blob/main/Docs/SDK_usage_guide.md#initialization-and-shutdown)?

```c++
#include <aws/core/Aws.h>
...

Aws::SDKOptions options;
Aws::InitAPI(options);

//use the sdk

Aws::ShutdownAPI(options);
```
