### ISSUE TITLE
AWS S3Client and DynamoDBClient segfault

### ISSUE THREAD

**Issue by ylc265** [aws/aws-sdk-cpp#208]
Hey, I pulled from the repo today and rebuild it. Now, I am getting segfault when I declare S3Client or DynamoDBClient. I only get a segfault message which makes it hard for me to debug. The most recent version of the library that I built and got it working was from 10 days ago. Any ideas why this is the case? Here's how I find the aws_sdk_cpp package in my make file:

`set(AWS_CPP_SDK_INCLUDE_DIRS /path-to-sdk/build_dir/ CACHE STRING "aws-cpp-sdk include directories")`
`set(AWS_CORE_LIB "/path-to-sdk/build_dir/aws-cpp-sdk-core/libaws-cpp-sdk-core.dylib" CACHE STRING "aws-cpp-sdk link core lib")`
`set(AWS_CPP_SDK_DYNAMO_LIB "/path-to-sdk/aws-sdk-cpp/build_dir/aws-cpp-sdk-dynamodb/libaws-cpp-sdk-dynamodb.dylib" CACHE STRING "aws-cpp-sdk link Dynamo lib")`
`set(AWS_CPP_SDK_S3_LIB "/path-to-sdk/build_dir/aws-cpp-sdk-s3/libaws-cpp-sdk-s3.dylib" CACHE STRING "aws-cpp-sdk link S3 lib")`

**Comment by bretambrose** [comment]
What fixed your issue?

**Comment by ylc265** [comment]
Nothing. I figured that I probably did something wrong linking the library since no one complained about this so I decided it's probably a problem on my end. Will update when I find a solution.

**Comment by ylc265** [comment]
So what happened was I forgot to read and the newest stable release version requires InitApi().
