### ISSUE TITLE
Compilation error in `ub_S3-CRT.cpp` while constructing `Aws::Crt::Auth::Credentials`

### ISSUE THREAD

**Issue by fosterbrereton** [aws/aws-sdk-cpp#2097]
### Describe the bug

When limiting the compilation to `s3-crt`, I get the following error while compiling `ub_S3-CRT.cpp`:

```shell
/path/to/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/memory:2627:37: error: no matching constructor for initialization of 'Aws::Crt::Auth::Credentials'
        ::new ((void*)__get_elem()) _Tp(_VSTD::forward<_Args>(__args)...);
                                    ^
/path/to/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/memory:3385:55: note: in instantiation of function template specialization 'std::__shared_ptr_emplace<Aws::Crt::Auth::Credentials, std::allocator<Aws::Crt::Auth::Credentials>>::__shared_ptr_emplace<>' requested here
    ::new ((void*)_VSTD::addressof(*__guard.__get())) _ControlBlock(__a, _VSTD::forward<_Args>(__args)...);
                                                      ^
/path/to/aws-sdk-cpp-1.9.347/aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSAllocator.h:51:21: note: in instantiation of function template specialization 'std::allocate_shared<Aws::Crt::Auth::Credentials, std::allocator<Aws::Crt::Auth::Credentials>, void>' requested here
        return std::allocate_shared<T, Aws::Allocator<T>>(Aws::Allocator<T>(), std::forward<ArgTypes>(args)...);
                    ^
/path/to/aws-sdk-cpp-1.9.347/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp:211:26: note: in instantiation of function template specialization 'Aws::MakeShared<Aws::Crt::Auth::Credentials>' requested here
             return Aws::MakeShared<Aws::Crt::Auth::Credentials>(ALLOCATION_TAG);
                         ^
/path/to/aws-sdk-cpp-1.9.347/crt/aws-crt-cpp/include/aws/crt/auth/Credentials.h:40:17: note: candidate constructor not viable: requires single argument 'credentials', but no arguments were provided
                Credentials(const aws_credentials *credentials) noexcept;
                ^
/path/to/aws-sdk-cpp-1.9.347/crt/aws-crt-cpp/include/aws/crt/auth/Credentials.h:50:17: note: candidate constructor not viable: requires 1 argument, but 0 were provided
                Credentials(const Credentials &) = delete;
                ^
/path/to/aws-sdk-cpp-1.9.347/crt/aws-crt-cpp/include/aws/crt/auth/Credentials.h:51:17: note: candidate constructor not viable: requires 1 argument, but 0 were provided
                Credentials(Credentials &&) = delete;
                ^
/path/to/aws-sdk-cpp-1.9.347/crt/aws-crt-cpp/include/aws/crt/auth/Credentials.h:41:17: note: candidate constructor not viable: requires at least 4 arguments, but 0 were provided
                Credentials(
                ^
1 error generated.
```

### Expected Behavior

Compilation success

### Current Behavior

Compilation failure

### Reproduction Steps

- Download the AWS C++ SDK release
- Run `prefetch_crt_dependency.sh` to grab dependencies
- From the top level directory, run:
- `cmake -Bbuild -DBUILD_ONLY="s3-crt" -DBUILD_SHARED_LIBS=OFF -DCPP_STANDARD=17 -DFORCE_SHARED_CRT=OFF`
- `cmake --build build -j`

### AWS CPP SDK version used

1.9.347

### Compiler and Version used

Apple clang version 13.0.0 (clang-1300.0.29.30)

### Operating System and version

macOS 12.0.1

**Comment by jmklix** [comment]
Can you try running the following command to update the submodules?
```sh
git submodule update --init --recursive
```

I was getting the same error the other day and I think that is what fixed it for me. I tried running the reproduction steps you provided and it build successfully for me.

**Comment by rgardner** [comment]
@jmklix, I hit the same issue and your suggestion of `git submodule update --init --recursive` then re-running CMake resolved it for me.

I followed the `git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp` guidance, so I'm not sure what I did to cause the submodules to get out of sync.

**Comment by SergeyRyabinin** [comment]
hi @rgardner,
> I followed the git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp guidance, so I'm not sure what I did to cause the submodules to get out of sync.

Most probably your git config is not enabled to pull with recurse submodule. I have following in my gitconfig:
```
[submodule]
        recurse = true
```
However, I cannot recommend or not recommend it, it depends on your preferences how you would like to use git.

**Comment by jmklix** [comment]
@rgardner I'm glad that you where able to get it working. @fosterbrereton are you still having problems?

**Comment by fosterbrereton** [comment]
@jmklix Let me reach out to @rgardner directly, thank you for letting me know.
