### ISSUE TITLE
Empty version and delete marker lists when listing object versions

### ISSUE THREAD

**Issue by marianobarrios** [aws/aws-sdk-cpp#211]
When issuing the ListObjectVersions request, the lists returned ListObjectVersionsResult::GetVersions and ListObjectVersionsResult::GetDeleteMarkers are always empty, even though the AWS API returns a valid response with non-empty lists.

The errors seems to be caused by some incorrect pluralizations in ListObjectVersionsResult.cpp.

Pull request supplied: https://github.com/aws/aws-sdk-cpp/pull/210

**Comment by JonathanHenson** [comment]
I've updated the code generator and pushed out these changes. Feel free to reopen if issues persist.
