### ISSUE TITLE
AWSClient::AttemptOneRequest nullptr access

### ISSUE THREAD

**Issue by pdc-tstream** [aws/aws-sdk-cpp#2138]
I've run into the closed issue #2109

[Segmentation fault with Transcribe Streaming](https://github.com/aws/aws-sdk-cpp/issues/2109#top) #2109

As I cannot re-open I think the correct thing to do is create a new issue.

Sorry if that's not the way...

Anyway:

Crash due to nullptr access in AWSClient::AttemptOneRequest
    auto signer = GetSignerByName(signerName);
returns nullptr.

I looked over the new example and it seems to be the same structure i'm using.

OK, I believe I've tracked it back.  

It works on 1.9.334, and fails on 1.9.335

I think this is the change that causes the problem:
Looking at TranscribeStreamingServiceClient::TranscribeStreamingServiceClient:

The old version had 

`   Aws::MakeShared<Aws::Auth::DefaultAuthSignerProvider>(...)
`

The new version has

`  Aws::MakeShared<AWSAuthV4Signer>(...)
`

The same for all 3 CTORs

So as part of re-formatting the CTORs, they were changed slightly.

I am going to run with 1.9.334 for my current work.

Let me know if you have any questions.

Cheers

_Originally posted by @pdc-tstream in https://github.com/aws/aws-sdk-cpp/issues/2109#issuecomment-1276240544_

**Comment by jmklix** [comment]
You said that you seem to using the same structure as the new [transcribe streaming example](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/cpp/example_code/transcribe). Can you confirm that you see this error when running the exact same sample or can you provide a minimal code sample that does reproduce it?

**Comment by pdc-tstream** [comment]
I have reproduced with the transcribe streaming example.

I am building against aws static libs if that makes a difference.

I am enclosing a zip file containing the various bits to build a docker container (which builds aws into /musl) and then CMakeLists.txt etc to build the example file.

[aws-debug.zip](https://github.com/aws/aws-sdk-cpp/files/9785837/aws-debug.zip)

**Comment by pdc-tstream** [comment]
If you change the docker file to do --branch 1.9.334 instead of --branch 1.9.335 then it will work (if you install credentials)

**Comment by jmklix** [comment]
Can you update to the latest version of this sdk and see if you are still running into a nullptr access? We have updated the transcribe streaming since this issue was opened.
