### ISSUE TITLE
JsonCpp namespace collision issue

### ISSUE THREAD

**Issue by jimmyt857** [aws/aws-sdk-cpp#214]
When adding `#include <aws/logs/CloudWatchLogsClient.h>` to my code, I get the following compile errors:

In file included from /usr/local/include/aws/logs/CloudWatchLogsClient.h:22:0,
/usr/local/include/aws/core/utils/json/JsonSerializer.h:332:17: error: ‘External’ in namespace ‘Aws’ does not name a type
                 Aws::External::Json::Value& ModifyRawValue() { return m_value; }
                 ^
/usr/local/include/aws/core/utils/json/JsonSerializer.h:335:33: error: ‘External’ in namespace ‘Aws’ does not name a type
                 JsonValue(const Aws::External::Json::Value& value);
                                 ^
/usr/local/include/aws/core/utils/json/JsonSerializer.h:335:59: error: expected unqualified-id before ‘&’ token
                 JsonValue(const Aws::External::Json::Value& value);
                                                           ^
/usr/local/include/aws/core/utils/json/JsonSerializer.h:335:59: error: expected ‘)’ before ‘&’ token
/usr/local/include/aws/core/utils/json/JsonSerializer.h:335:59: error: constructors may not be ref-qualified
/usr/local/include/aws/core/utils/json/JsonSerializer.h:335:59: error: expected ‘;’ at end of member declaration
/usr/local/include/aws/core/utils/json/JsonSerializer.h:335:61: error: ‘value’ does not name a type
                 JsonValue(const Aws::External::Json::Value& value);
                                                             ^
/usr/local/include/aws/core/utils/json/JsonSerializer.h:337:43: error: declaration of ‘operator=’ as non-function
                 JsonValue& operator=(Aws::External::Json::Value& other);
                                           ^
/usr/local/include/aws/core/utils/json/JsonSerializer.h:337:36: error: expected ‘;’ at end of member declaration
                 JsonValue& operator=(Aws::External::Json::Value& other);
                                    ^
/usr/local/include/aws/core/utils/json/JsonSerializer.h:337:43: error: ‘Aws::External’ has not been declared
                 JsonValue& operator=(Aws::External::Json::Value& other);
                                           ^
/usr/local/include/aws/core/utils/json/JsonSerializer.h:337:64: error: expected ‘)’ before ‘&’ token
                 JsonValue& operator=(Aws::External::Json::Value& other);
                                                                ^
/usr/local/include/aws/core/utils/json/JsonSerializer.h:339:25: error: ‘External’ in namespace ‘Aws’ does not name a type
                 mutable Aws::External::Json::Value m_value;
                         ^
In file included from /usr/local/include/aws/logs/CloudWatchLogsClient.h:22:0,
/usr/local/include/aws/core/utils/json/JsonSerializer.h: In member function ‘bool Aws::Utils::Json::JsonValue::operator!=(const Aws::Utils::Json::JsonValue&)’:
/usr/local/include/aws/core/utils/json/JsonSerializer.h:71:28: error: ‘m_value’ was not declared in this scope
                     return m_value != other.m_value;
                            ^
/usr/local/include/aws/core/utils/json/JsonSerializer.h:71:45: error: ‘const class Aws::Utils::Json::JsonValue’ has no member named ‘m_value’
                     return m_value != other.m_value;
                                             ^
/usr/local/include/aws/core/utils/json/JsonSerializer.h: In member function ‘bool Aws::Utils::Json::JsonValue::operator==(const Aws::Utils::Json::JsonValue&)’:
/usr/local/include/aws/core/utils/json/JsonSerializer.h:76:28: error: ‘m_value’ was not declared in this scope
                     return m_value == other.m_value;
                            ^
/usr/local/include/aws/core/utils/json/JsonSerializer.h:76:45: error: ‘const class Aws::Utils::Json::JsonValue’ has no member named ‘m_value’
                     return m_value == other.m_value;

If it matters, I'm only building a subset of the clients, and I'm building as a static library. My code already uses S3Client, EC2Client, ElasticLoadBalancingClient, RDSClient, and Route53Client just fine, but for some reason simply including the cwl client causes issues.

**Comment by jimmyt857** [comment]
Whoops, this is actually caused by a previous inclusion of the JsonCpp header file (the regular JsonCpp, not yours). I'm not using any `using namespace` commands, though. Is there a simple way to get these two to play nicely?

**Comment by bretambrose** [comment]
We added the namespaces in the hopes that it would prevent a situation like this, but completely forgot about the defined symbols staying the same.  My fear is that it will require a complete rename/mangle for every #defined symbol, which will be a bit of a pain, but we'll need to take a close look to determine that for sure.  It's definitely something that we will try to get to in the near term.

**Comment by jimmyt857** [comment]
Alright, thanks! I can make do with a workaround for now.

**Comment by bretambrose** [comment]
I've added a new branch, FB-JsonCPPInsulation, with the #define name changes.  It worked in my test case, but I'd feel safer merging it in if you were able to give it a try and a thumbs-up/thumbs-down first.

**Comment by jimmyt857** [comment]
Works great! Thanks for the quick turnaround on this.
