### ISSUE TITLE
Consistency Control Headers

### ISSUE THREAD

**Issue by adhitya97** [aws/aws-sdk-cpp#2142]
### Describe the feature

Hi,

Is there a plan to add support to send consistency control headers as part of S3 Put operations?

I need to be able to send the following consistency control header values - all, strong-global, strong-sit, read-after-new-write, available.

Thank you

### Use Case

Some metadata headers are unavailable to be set using the S3 CPP SDK.

Using the AddMetadata adds a "x-amz-meta" prefix, which doesn't solve this issue.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by SergeyRyabinin** [comment]
Hi Adhitya,

AWS S3 is strong read-after-write consistent:

https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-s3-now-delivers-strong-read-after-write-consistency-automatically-for-all-applications/

https://aws.amazon.com/s3/consistency/

I suggest to inquiry S3 customer support if you would like to check for a different or additional consistency control.


If you want to send a custom header with a request, you should be able to overwrite virtual function of a base request class, i.e. [GetRequestSpecificHeaders](https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-core/include/aws/core/AmazonStreamingWebServiceRequest.h#L75) or [GetRequestSpecificHeaders](https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-s3/include/aws/s3/S3Request.h#L37)(for non-streaming requests), to be more specific:
1. Inherit from a request class, for example [PutObjectRequest](https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-s3/include/aws/s3/model/PutObjectRequest.h#L35)
2. Implement/override a GetRequestSpecificHeaders function that will return additional headers you want.
3. Pass your an object of your inherited request class to the regular SDK's operation API, a slicing will happen, but thanks to the virtual inheritance, your overwritten method will be still called and custom headers inserted into the request.


Best regards
