### ISSUE TITLE
FileName with unicode charcter CPP AWS SDK

### ISSUE THREAD

**Issue by abhiDev199** [aws/aws-sdk-cpp#2144]
I have a requirement where I download the file from S3 bucket to client with a filename which consists of unicode character. 
Example: 
```cpp
transfer_manager->DownloadFile(bucket_name, object_name, fileName)
```
, where filename is `filePath/–test--aws––store__–Status%28th–Aug_2022–.txt`. After successful execution of DownloadFile the unicode character in filename gets replaced with ?(question mark) and it's saved as `�test--aws��store__�Status%28th�Aug_2022�`. I am using windows as a client. Using sdk https://github.com/aws/aws-sdk-cpp. Please let me know if I am missing something.

**Comment by jmklix** [comment]
I think this will be fixed with this [PR](https://github.com/aws/aws-sdk-cpp/pull/2113). It looks like the sdk is encoding the filename when it shouldn't be which is fixed in the PR

**Comment by jmklix** [comment]
We don't want to change how we handle some characters by introducing the PR I made above. You can find a list of safe and unsafe characters for s3 object keys [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html). Please let me know if you have any questions about this.
