### ISSUE TITLE
Single threaded interface

### ISSUE THREAD

**Issue by jimmyt857** [aws/aws-sdk-cpp#215]
In my application, I use libuv so that I can take advantage of the async style while avoiding the overhead of threads and eliminating the need for locking/worrying about race conditions. How will this interect with asynchronous calls in this library? My first guess is that my callbacks are called from a separate thread. If that is the case, is there any way to have the callbacks run on the same thread that called the function? Or, even better, is there a way for me to configure the library to run on the same libuv event loop that I am already using?

**Comment by JonathanHenson** [comment]
You can create your own executor implementation that does whatever you want.

**Comment by JonathanHenson** [comment]
Here's an example of one I wrote a while back. all you have to do is implement the executor interface.

https://aws.amazon.com/blogs/developer/using-a-thread-pool-with-the-aws-sdk-for-c/

**Comment by jimmyt857** [comment]
If I understand this correctly, the Executor::SubmitToThread function that I am to override takes a function which performs the entire request, i.e. sends the HTTP message and waits for the response. This is why separate threads are needed in the first place, because the HTTP calls are blocking. I was hoping that I could take control of the actual sending and receiving of the HTTP request itself. This way I could send off the HTTP request, and then have libuv poll the file descriptor and run the response callback when data arrives.

I can instead have the Aws callback register my own callback to be performed on my main thread, so this isn't an important feature for me. It would just be nice to have my whole system run on a single thread while simultaneously having non-blocking calls.

**Comment by JonathanHenson** [comment]
You can write executor to run on same thread and handle the run loop and an http implementation to perform whatever you like.

**Comment by jimmyt857** [comment]
But isn't the function parameter that I get passed going to block on the http call?

**Comment by JonathanHenson** [comment]
You can control the http call by overriding the http stack. 

Granted the sdk is not architected for an async io style, but you can use a run loop in the executor to make it behave properly using async io. 

A better design would have been for us to design for async io and then fit the synchronous APIs on top of that, but alas, hindsight is always 20/20.

**Comment by jimmyt857** [comment]
I think this works for me, thanks!
