### ISSUE TITLE
How do i configure and provide credentials?

### ISSUE THREAD

**Issue by arunvasist1996** [aws/aws-sdk-cpp#216]
If we use python , we configure by giving `aws configure` command and then inputting the credentials such as Access key and Secret access key.How do i achieve the same while using c++?

**Comment by prestomation** [comment]
'aws configure' sets up your credentials file at ~/.aws/credentials.
The C++ SDK uses this file the same way, so if you are already setup for Boto, than the C++ SDK will work exactly the same .
