### ISSUE TITLE
Lambda Integration Test Error

### ISSUE THREAD

**Issue by cisse21** [aws/aws-sdk-cpp#217]
After using cmake -DBUILD_ONLY="lambda" <path of the folder> , while running the executables of Lambda Integration tests, the 10 tests in functions.cpp failed. Please Help

**Comment by JonathanHenson** [comment]
Have you set up a credentials file?

**Comment by cisse21** [comment]
Yes the credentials have been set up in Home/.aws/credentials folder

**Comment by JonathanHenson** [comment]
We have several IAM permissions that are setup to make those work internally. I don't recommend that you worry with running these tests. They are mainly for us to verify the build before we push changes out publicly. 

If you are truly concerned about this, you could upload your log file and I'll have a look.
