### ISSUE TITLE
The library is too big to run on our OS with less RAM(128MB)

### ISSUE THREAD

**Issue by sridevi-m** [aws/aws-sdk-cpp#218]
I just want to have functionality to invoke LAMBDA, how does the request look like (curl request ) .
How do I get the authentication token?

I get this error when I type this url 
[https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/<functionname>/invocations]

```
<MissingAuthenticationTokenException>
  <Message>Missing Authentication Token</Message>
</MissingAuthenticationTokenException>
```

Any help would be greatly appreciated.

**Comment by prestomation** [comment]
AWS uses a  process we call AWS Signature Version 4 signing for security. This involves taking parts of the request and signing it using a secret key you have from AWS and sending the resulting signature in the Authorization: header.

The official documentation of this process is here: http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

I would highly recommend you use an AWS SDK to handle this and other concerns for you if possible. Have you tried to run a stripped down version of that SDK that is just the -core and -lambda libraries to see if it will work?

**Comment by JonathanHenson** [comment]
If you are in an environment with memory that constrained, C++ is probably not a good decision, I would go with C and have a look at the AWS IOT SDK. 

You can possibly strip down the lambda client to only have the invoke method, and see if you can get your application to load.
