### ISSUE TITLE
1.10.x build not working when using prefetch_crt_dependency.sh

### ISSUE THREAD

**Issue by gavllew** [aws/aws-sdk-cpp#2188]
### Describe the bug

The README describes how to use this script to download the source code without using git:
> Alternatively, if you downloaded the code bundle from GitHub website and have no installation of git, you can download all the dependencies running the prefetch_crt_dependency.sh script from the root of the repository. It will download bundles of all dependencies from github website using curl and expand them in the right locations.

When following these instructions, the compile fails.

### Expected Behavior

The project builds successfully.

### Current Behavior

Compiler error about a missing header file:

```
aws-sdk-cpp-1.10.2/aws-cpp-sdk-core/include/aws/core/endpoint/DefaultEndpointProvider.h:16:10: fatal error: aws/crt/endpoints/RuleEngine.h: No such file or directory
   16 | #include <aws/crt/endpoints/RuleEngine.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Reproduction Steps

Follow the build instructions for a tarball build without git.

### Possible Solution

Update commit IDs in `prefetch_crt_dependency.sh`

### AWS CPP SDK version used

1.10.2

### Compiler and Version used

gcc (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2)

### Operating System and version

Amazon Linux 2022

**Comment by SergeyRyabinin** [comment]
Hi Gavin,

Thanks a lot for reporting this issue.
This is definitely a miss on our side, will follow up on this shortly.
