### ISSUE TITLE
Add custom headers to AmazonWebServiceRequest: pass x-amz-request-payer header to SelectObjectContentRequest

### ISSUE THREAD

**Issue by raman-aro** [aws/aws-sdk-cpp#2192]
### Describe the feature

SelectObjectContentRequest does not support the RequestPayer option. Also, it doesn't seem possible to inject a custom header per the solution suggested for the [python SDK](
https://github.com/boto/boto3/issues/3074) or the [Java SDK](https://github.com/aws/aws-sdk-java/issues/1219)

Please suggest any workarounds 

### Use Case

Use SelectObjectContent to run S3Select queries on a cross-account bucket which has Requester Pays enabled. This isn't possible without the passing the 'x-amz-request-payer':'requester' header.

### Proposed Solution

Modify the AmazonWebServiceRequest class to accept customRequestHeaders, similar to the Java SDK. 

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/AmazonWebServiceRequest.java

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jmklix** [comment]
You should be able to add custom headers. Please take a look at [this answer](https://github.com/aws/aws-sdk-cpp/issues/2142#issuecomment-1292448231):

> Hi Adhitya,
> 
> AWS S3 is strong read-after-write consistent:
> 
> https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-s3-now-delivers-strong-read-after-write-consistency-automatically-for-all-applications/
> 
> https://aws.amazon.com/s3/consistency/
> 
> I suggest to inquiry S3 customer support if you would like to check for a different or additional consistency control.
> 
> 
> If you want to send a custom header with a request, you should be able to overwrite virtual function of a base request class, i.e. [GetRequestSpecificHeaders](https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-core/include/aws/core/AmazonStreamingWebServiceRequest.h#L75) or [GetRequestSpecificHeaders](https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-s3/include/aws/s3/S3Request.h#L37)(for non-streaming requests), to be more specific:
> 1. Inherit from a request class, for example [PutObjectRequest](https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-s3/include/aws/s3/model/PutObjectRequest.h#L35)
> 2. Implement/override a GetRequestSpecificHeaders function that will return additional headers you want.
> 3. Pass your an object of your inherited request class to the regular SDK's operation API, a slicing will happen, but thanks to the virtual inheritance, your overwritten method will be still called and custom headers inserted into the request.
> 
> *I hope the information I have provided answers your question.
> *Please feel free to re-open the issue should you have any additional questions.
> 
> Best regards
