### ISSUE TITLE
compile failure on MacOS Ventura

### ISSUE THREAD

**Issue by nrgiii** [aws/aws-sdk-cpp#2195]
### Describe the bug

Builds fail on MacOS Ventura due to cJSON using deprecated function sprintf() and AWS building with -Werror.

`/Users/normg/gs370ssl3/externals/aws/crt/aws-crt-cpp/source/external/cJSON.cpp:146:5: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
    sprintf(version, "%i.%i.%i", CJSON_VERSION_MAJOR, CJSON_VERSION_MINOR, CJSON_VERSION_PATCH);
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
`

### Expected Behavior

Builds should work on MacOS Ventura

### Current Behavior

Compile failure when building cJSON.cpp due to use of sprintf(), which is explicitly deprecated on MacOS Ventura.

### Reproduction Steps

Build AWS on MacOS Ventura.

### Possible Solution

Do not use -Werror when building cJSON until this is fixed in the cJSON repo.

### Additional Information/Context

Tracked in the cJSON repo as: 

[cJSON_Version](https://github.com/DaveGamble/cJSON/issues/716) is not thread-safe #716

### AWS CPP SDK version used

1.9.362

### Compiler and Version used

Apple clang version 14.0.0 (clang-1400.0.29.202)

### Operating System and version

MacOS Ventura, Darwin Kernel Version 22.1.0

**Comment by jmklix** [comment]
This was fixed in this [PR](https://github.com/aws/aws-sdk-cpp/pull/2175). You can fix the compile error by using the latest version of this sdk.

**Comment by jmklix** [comment]
Correction, the PR fixed a similar error in this repo. You are running into the same error with `aws-crt-cpp`. I'm working on getting this fixed there as well.

**Comment by sbiscigl** [comment]
Should be fixed with [2206](https://github.com/aws/aws-sdk-cpp/pull/2206), let us know if you see any more issues!
