### ISSUE TITLE
make[2]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/build.make:890: aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 1

### ISSUE THREAD

**Issue by AlexanderBurdenko** [aws/aws-sdk-cpp#2198]
### Describe the bug

I have a Dockerfile with part of lines:
```
FROM ubuntu:focal

RUN git clone -b 1.9.379 --recurse-submodules --depth 1 https://github.com/aws/aws-sdk-cpp.git && cd aws-sdk-cpp && mkdir build && cd build \
	&& cmake .. -DBUILD_ONLY=s3 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SHARED_LIBS=ON \
	&& make -j4 && make install && make clean
```

### Expected Behavior

Must make without error

### Current Behavior

```
[  PASSED  ] 487 tests.
[  SKIPPED ] 1 test, listed below:
[  SKIPPED ] AWSMemory.StaticUniquePtrDtorOrder
make[2]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/build.make:890: aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 1
make[2]: *** Deleting file 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests'
make[1]: *** [CMakeFiles/Makefile2:1044: aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
```

### Reproduction Steps

build docker image

### AWS CPP SDK version used

1.9.379

### Compiler and Version used

CMake 3.16.3

### Operating System and version

Ubuntu 20.04

**Comment by AlexanderBurdenko** [comment]
> You don't have to build it with the tests. Adding `-DENABLE_TESTING=OFF` will turn the tests off and will prevent the build from failing from a test. Please let me know if you are still running into problems after this.

But as i understand Tests is important ?

**Comment by jmklix** [comment]
We run the tests on various environments before we make changes to the sdk, so that you don't have to. They can be helpful, but they can also fail for various reasons in your environment. Can you let me know if disabling the tests for the sdk allows you to build the sdk successfully?
