### ISSUE TITLE
SQS->SendMessageBatchRequest is losing messageAttributes

### ISSUE THREAD

**Issue by ggallego** [aws/aws-sdk-cpp#220]
When sending sqs messages using SendMessageBatch with MessageAttributes attached, these MessageAttributes are lost and cannot be received from ReceiveMessage.

This behavior only happens on SendMessageBatch (the SendMessage method is fine).

There is a test case showing this behavior (SendMessageBatch:NOK; SendMessage:OK) on https://github.com/ggallego/aws-sdk-cpp-sqs-messages-with-message-attributes-test.

**Comment by asylvest** [comment]
Yes, I ran into this too and reported it under #39.  The issue got closed out I believe by accident...

**Comment by JonathanHenson** [comment]
OK, I just updated the generator and pushed out the changes. Feel free to reopen if issues persist.

**Comment by ggallego** [comment]
Perfect! The SendMessageBatchRequest is now working. Thank you!
