### ISSUE TITLE
Nuget package support for Visual Studio 2022

### ISSUE THREAD

**Issue by SameerOmar** [aws/aws-sdk-cpp#2207]
### Describe the feature

The Nuget package currently supports up to Visual Studio platform toolset v141 but the latest toolset released with Visual Studio 2022 is v143

### Use Case

To use the Nuget package with Visual Studio 2022 without downgrading the build toolset to old version

### Proposed Solution

Push a new Nuget packages version

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jmklix** [comment]
We don't distribute via Nuget and have never done so in the past. Github is currently the only way we distribute this sdk, but was are interested in adding Nuget package support in the future. Please upvote the original post is this is something that you would like.

**Comment by SameerOmar** [comment]
I found https://www.nuget.org/packages/AWSSDKCPP-Core and I thought it is an official distribution.

**Comment by SameerOmar** [comment]
check here as well https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/sdk-from-pm.html it says "deprecated" so it was an official distribution

**Comment by jmklix** [comment]
Sorry for the confusion, but that was provided by a third party and was just linked on our developer guide. As you noticed the nuget package was for a very old version of this sdk. We don't have any plans to distribute via Nuget currently.
