### ISSUE TITLE
Building SDK fails with failed/flaky test

### ISSUE THREAD

**Issue by bearrito** [aws/aws-sdk-cpp#2214]
### Describe the bug

I'm building the library in a Dockerfile. I'm getting the following

```
#8 207.1 Value of: hasPendingTasks
#8 207.1   Actual: true
#8 207.1 Expected: false
#8 209.8 [  FAILED  ] HttpClientTest.TestRandomURLMultiThreaded (8734 ms)
#8 209.8 [==========] 488 tests from 76 test suites ran. (18946 ms total)
#8 209.8 [  PASSED  ] 486 tests.
#8 209.8 [  SKIPPED ] 1 test.
#8 215.8 1.10.12
#8 216.7 /root/aws-sdk-cpp/aws-cpp-sdk-core-tests/utils/memory/AWSMemoryTest.cpp:101: Skipped
#8 216.7 Skipping the repeat of StaticUniquePtrDtorOrder test as it cannot be repeated.
#8 226.0 [==========] 488 tests from 76 test suites ran. (16224 ms total)
#8 226.0 [  PASSED  ] 487 tests.
#8 226.0 [  SKIPPED ] 1 test.
```

@KaibaLopez  This is clearly a duplicate of https://github.com/aws/aws-sdk-cpp/issues/1486 but that issue was closed and you said create a new issue.

I get that confounding issues, can make fuzz tests like this non-deterministic,however I feel like this should work provided this on Amazon Linux docker file.  My network is fine in all other regards.

Edit: 

If I run the tests enough time, it passes. So I'd mark this as flaky

### Expected Behavior

The tests to pass.

### Current Behavior

The tests failed

### Reproduction Steps

My Dockerfile preamble looks like

```
FROM amazonlinux:latest
RUN yum -y install make git gcc-c++ nano zip clang gcc-c++RUN yum -y install libcurl-devel cmake3 zlib-devel openssl-devel
```

Skipping irrelevant parts
```

RUN export CC=gcc && \
    export CXX=g++ && \
    cd ~  && \
    git clone https://github.com/aws/aws-sdk-cpp.git && \
    cd ~ && cd aws-sdk-cpp && \
    git submodule update --init --recursive


RUN cd ~ && cd aws-sdk-cpp && ls -lah && \
    mkdir build && \
    cd build && \
    cmake3 .. -DBUILD_ONLY=s3  -DBUILD_SHARED_LIBS=OFF -DENABLE_UNITY_BUILD=ON -DCMAKE_BUILD_TYPE=Release && -DCMAKE_INSTALL_PREFIX=~/out  && make && make install
```

### Possible Solution

The test should either decrease the threadcount given the number of cores, or increase the timeout. 
I could submit a patch along these lines if there is interest.

### AWS CPP SDK version used

master

### Compiler and Version used

gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15) 

### Operating System and version

amazonlinux:latest

**Comment by jmklix** [comment]
Thanks for opening this issue and providing a detailed description. We are looking into improving the flaky tests, but for now the workaround is to disable the tests. You can do [this](https://github.com/aws/aws-sdk-cpp/blob/main/Docs/CMake_Parameters.md#enable_testing) with `-DENABLE_TESTING=OFF`

**Comment by jmklix** [comment]
Are you still running into any test failures? I'm not seeing any when I run this dockerfile:

```dockerfile
FROM amazonlinux:latest

#Install required dependencies
RUN yum -y install make git gcc-c++ nano zip clang gcc-c++
RUN yum -y install libcurl-devel cmake3 zlib-devel openssl-devel

RUN git clone --depth 1 --recurse-submodules https://github.com/aws/aws-sdk-cpp && \
    cd aws-sdk-cpp && \
    mkdir build && \
    cd build && \
    cmake .. -DBUILD_ONLY=s3  -DBUILD_SHARED_LIBS=OFF -DENABLE_UNITY_BUILD=ON -DCMAKE_BUILD_TYPE=Release && \
    cmake --build . && \
    cmake --install .
```
