### ISSUE TITLE
build error [  FAILED  ] AWSAuthSignerTest.PayloadSigningPolicyAlways (2 ms)

### ISSUE THREAD

**Issue by wuhongsheng** [aws/aws-sdk-cpp#2238]
### Describe the bug

cmake -DBUILD_ONLY="s3" -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF ..
make && make install

### Expected Behavior

cmake -DBUILD_ONLY="s3" -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF ..
make && make install

### Current Behavior

cmake -DBUILD_ONLY="s3" -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF ..
make && make install

### Reproduction Steps

cmake -DBUILD_ONLY="s3" -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF ..
make && make install

### AWS CPP SDK version used

 1.10.27

### Compiler and Version used

Apple clang version 11.0.3 (clang-1103.0.32.59) Target: x86_64-apple-darwin22.1.0

### Operating System and version

macOS 13.0.1 (22A400)

**Comment by jmklix** [comment]
Can you make sure you are using the latest versions of the dependencies? You can do this with:
```
git submodule update --init --recursive
```

If that doesn't work can you provide more detailed logs? I am able to use the exact build command you have listed above to build without any problems on mac

**Comment by zzq996** [comment]
> @wuhongsheng
> 
> Any news? Have you solved this problem? I have the same problem on linux

i  soulved same problem by add -DENABLE_TESTING=OFF in cmake command options

**Comment by jmklix** [comment]
Thanks zq996 for the suggested work around. Turning off the tests with `-DENABLE_TESTING=OFF` will allow you to avoid this build error. 

I have been unable to reproduce this same error. If you could please provide a docker container that fails the same test that would help us address this issue.
