### ISSUE TITLE
MP4 download using GetObjectRequest results in a corrupted file

### ISSUE THREAD

**Issue by ofirlessel** [aws/aws-sdk-cpp#225]
Hi,
I'm using the following code for downloading a public MP4 video file from an S3 bucket to my local disk.
The downloaded file size looks OK but the file is corrupted for some reason.
What am I doing wrong?

    Aws::Client::ClientConfiguration config;
    config.scheme = SCHEME;
    config.connectTimeoutMs = TIMEOUT_MILLIS;
    config.requestTimeoutMs = TIMEOUT_MILLIS;
    config.region = REGION;
    std::shared_ptr<Aws::S3::S3Client> s3Client = Aws::MakeShared<Aws::S3::S3Client>(ALLOCATION_TAG, config);

    Aws::S3::Model::GetObjectRequest getObjectRequest;
    getObjectRequest.SetBucket(BUCKET_NAME);
    getObjectRequest.SetKey(MP4_FILE_NAME);
    getObjectRequest.SetResponseStreamFactory(
    	[]() {
    	return Aws::New<Aws::FStream>(ALLOCATION_TAG, LOCAL_MP4_PATH, std::ios_base::out | std::ios_base::in | std::ios_base::trunc);
    });
    auto getObjectOutcome = s3Client->GetObject(getObjectRequest);

**Comment by JonathanHenson** [comment]
I think you forgot the std::ios_base::binary flag

**Comment by ofirlessel** [comment]
I did! Thanks!
