### ISSUE TITLE
InstanceProfileCredentialsProvider deadlock

### ISSUE THREAD

**Issue by 1-Olivier** [aws/aws-sdk-cpp#2251]
### Describe the bug

The `InstanceProfileCredentialsProvider` class deadlocks when used from multiple threads. `GetAWSCredentials()` calls `RefreshIfExpired()` which can call `ExpiresSoon()` at [this location](https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-core/source/auth/AWSCredentialsProvider.cpp#L302) with the writer lock held. `ExpiresSoon()` attempts to acquire the reader lock and gets stuck permanently. The entire object is then unusable.

This looks like it could trivially happen with a single thread but it does not because `ExpiresSoon()` does not actually work. It always returns false because `EC2InstanceProfileConfigLoader::LoadInternal()` discards the expiration time of the credentials (see [here](https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-core/source/config/EC2InstanceProfileConfigLoader.cpp#L96)). I don't know if that part is a bug or intentional. Regardless, this means a single thread will either return the first time the condition is tested or not call `ExpiresSoon()` the second time.

With two threads the deadlock can happen as follows:
- Both threads enter `RefreshIfExpired()` and see `IsTimeToRefresh()` returning true.
- Both threads attempt to acquire the writer lock. Thread 1 succeeds while thread 2 waits.
- Thread 1 proceeds to refresh the credentials and release the writer lock.
- Thread 2 acquires the writer lock.
- Thread 2 evaluates the condition: `if (!credentials.IsEmpty() && !IsTimeToRefresh(m_loadFrequencyMs) && !ExpiresSoon())` and will reach the last term because `IsTimeToRefresh()` now returns false.
- Thread 2 hangs in `ExpiresSoon()`, trying to acquire the reader lock.

See reproduction code for how to make this happen easily.

This appears to have been introduced with bd29beab895397285cce3004cfbde32c41e5cfd5 and going back to 1.10.1 fixes the problem here.

### Expected Behavior

I expect it not to get stuck.

### Current Behavior

The `InstanceProfileCredentialsProvider` object becomes unusable and stalls all the threads using it.

### Reproduction Steps

```
#include <aws/core/Aws.h>
#include <aws/core/auth/AWSCredentialsProvider.h>
#include <memory>
#include <thread>

/*
    This should run at 200% CPU indefinitely. But it nearly always gets stuck
    on the first refresh, after about 10 seconds. It then remains at 0% CPU and
    no progress is ever made.
*/
int main()
{
    Aws::SDKOptions options;
    Aws::InitAPI(options);

    Aws::Auth::InstanceProfileCredentialsProvider credentials_provider(10 * 1000);
    std::unique_ptr<std::thread> threads[2];
    auto tf = [&credentials_provider]()
    {
        while( true )
        {
            credentials_provider.GetAWSCredentials();
        }
    };
    for( auto &t : threads )
    {
        t.reset(new std::thread(tf));
    }
    for( auto &t : threads )
    {
        t->join();
    }
}
```

### Possible Solution

Don't lock the mutex in `InstanceProfileCredentialsProvider::ExpiresSoon()`. The method is private and all callers already lock the mutex, as far as I can see.

### AWS CPP SDK version used

1.10.23

### Compiler and Version used

clang 13.0.0

### Operating System and version

latest amazon linux on a t3.micro ec2 instance

**Comment by jmklix** [comment]
Thanks for the repro sample, looking into repro-ing and fixing this

**Comment by jkamp-aws** [comment]
This is appalling. How is this still open? It's super trivial to reproduce. The lock in the provider is used not reentrant, but it is being used as such. Code displaying that statement:

```
#include <iostream>
#include <aws/core/Aws.h>
#include <aws/core/utils/threading/Semaphore.h>
#include <aws/core/utils/threading/ReaderWriterLock.h>

using namespace Aws::Utils::Threading;

ReaderWriterLock rwLock;
void check(const char* info) {
    ReaderLockGuard guard(rwLock);
    std::cout << info << ": still locked\n";
}

int main() {
    ReaderLockGuard guard(rwLock);
    std::cout << info << ": read only\n";
    check(info);
    std::cout << info << ": upgrading\n";
    guard.UpgradeToWriterLock();
    std::cout << info << ": writer" << "\n";

    // invalid! can't grab a reader on a write-lock
    check(info);
}
```

The fix mentioned (removing the lock guard from ExpiresSoon is the fix.
