### ISSUE TITLE
fatal error: aws/core/Aws.h: No such file or directory

### ISSUE THREAD

**Issue by noopta** [aws/aws-sdk-cpp#2254]
### Describe the bug

I have followed this documentation here for setting up the AWS SDK with C++:
https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html

However, when I try to compile a cpp file and run the command "gcc -o something test.cpp", I get the error:
fatal error: aws/core/Aws.h: No such file or directory
 #include <aws/core/Aws.h>

What's strange is that if I `ctrl + select` the line  #include <aws/core/Aws.h> in my cpp file, the actual Aws.h file appears, showing that it does exist on my system.

### Expected Behavior

I expected the code to compile and locate the header files associated with  the AWS SDK.

### Current Behavior

I am getting the error message mentioned before.

### Reproduction Steps

https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html

I am following these steps for the Windows setup.

I also have my test.cpp file located in sdk_build. 

After installing Dynamo DB and Core, I run gcc -o something test.cpp

### AWS CPP SDK version used

The latest version

### Compiler and Version used

6.3.0 for gcc, 15.0.6 for clang

### Operating System and version

Windows 10

**Comment by jmklix** [comment]
Are use using cmake to also build your project. This sdk was developed with this in mind and there is even sample for how to do this on the developer guide: https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/build-cmake.html

This makes sure that everything is setup correctly for your program, but it is not required. I think this might be why your seeing the above error. I would recommend trying to follow that sample first. If that doesn't work please list out the commands that you are running to build the sdk and your program.

**Comment by noopta** [comment]
I appreciate the response, I will try building the project with CMake. One thing I am trying to figure out is where is the executable? I don't have a DEBUG folder. I'll try to setup up the SDK again and see if there is a a DEBUG folder, however, if you know why this may occur then please let me know :)

**Comment by noopta** [comment]
I am still getting an error message. Here is what I have done so far:

1) Followed the AWS SDK setup for C++ (https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup-linux.html)

2) Got to step 2 of part 2 of the HelloS3 example, where we run `cmake ..` (/https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/build-cmake.html)

3) Received the following error message:
 Could not find a package configuration file provided by "aws-cpp-sdk-s3"
  with any of the following names:

    aws-cpp-sdk-s3Config.cmake
    aws-cpp-sdk-s3-config.cmake

  Add the installation prefix of "aws-cpp-sdk-s3" to CMAKE_PREFIX_PATH or set
  "aws-cpp-sdk-s3_DIR" to a directory containing one of the above files.  If
  "aws-cpp-sdk-s3" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:16 (find_package)

**Comment by noopta** [comment]
Hi I have not heard an update regarding this. The documentation is somewhat unclear for the AWS C++ SDK. I am building the AWS SDK on a Ubuntu system for EC2. 

Could you please give me a list of steps from the beginning to install the SDK, set up an example S3, and then compile the sample S3 with the relative locations of the s3 example directory. 

When I try to build the program currently, I do not even see the executable which the makefile is supposed to create.

**Comment by jmklix** [comment]
Sorry for the slow reply. You can find the documentation for how to do this on the official docs website:
- [build sdk on linux](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup-linux.html)
- [build sample s3 application](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/build-cmake.html) (includes sample cmake)
Please let me know if you have any questions or problems with running the sample application

**Comment by Zxisam** [comment]
I am currently working on the same problem, in the latest release.

**Comment by jmklix** [comment]
@Zxisam can you provide detailed steps for how you are building, your CMakeLists.txt file, and the full error messages that you're seeing?
