### ISSUE TITLE
Uploaded image become gabled

### ISSUE THREAD

**Issue by luohaibiao** [aws/aws-sdk-cpp#226]
Successfully using examples from /aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp to upload txt file to a bucket, and successfully uploading image file to a bucket but that uploaded image file becomes garbled and cannot be read. Here is part of the code to upload an image file to S3, which is the same as the original code to upload a txt file except that "text/plain" was changed to 'image/jpeg". Is there anything else I need to change?
putObjectRequest.SetContentType("image/jpeg");

Aws::String fullBucketName = CalculateBucketName(PUT_OBJECTS_BUCKET_NAME);

        CreateBucketRequest createBucketRequest;
        createBucketRequest.SetBucket(fullBucketName);
        createBucketRequest.SetACL(BucketCannedACL::private_);

        CreateBucketOutcome createBucketOutcome = Client->CreateBucket(createBucketRequest);
        ASSERT_TRUE(createBucketOutcome.IsSuccess());
        const CreateBucketResult& createBucketResult = createBucketOutcome.GetResult();
        ASSERT_TRUE(!createBucketResult.GetLocation().empty());

        WaitForBucketToPropagate(fullBucketName);

        PutObjectRequest putObjectRequest;
        putObjectRequest.SetBucket(fullBucketName);

        std::shared_ptr<Aws::IOStream> objectStream = Aws::MakeShared<Aws::StringStream>("BucketAndObjectOperationTest");
        *objectStream << "Test Object";
        objectStream->flush();
        putObjectRequest.SetBody(objectStream);
        putObjectRequest.SetContentLength(static_cast<long>(putObjectRequest.GetBody()->tellp()));
        putObjectRequest.SetContentMD5(HashingUtils::Base64Encode(HashingUtils::CalculateMD5(*putObjectRequest.GetBody())));
        putObjectRequest.SetContentType("image/jpeg");
        putObjectRequest.SetKey(TEST_OBJ_KEY);

        PutObjectOutcome putObjectOutcome = Client->PutObject(putObjectRequest);
        ASSERT_TRUE(putObjectOutcome.IsSuccess());

**Comment by bretambrose** [comment]
Does the answer here (https://github.com/aws/aws-sdk-cpp/issues/225) help?

**Comment by JonathanHenson** [comment]
I don't see here where you are uploading an actual image. It appears you are uploading the text "Test Object" with a content type of image/jpeg (which would certainly be garbled).

Be sure you use the std::ios_base::binary when you are actually uploading binary data.

Please reopen if you still have problems after addressing the above concerns.
