### ISSUE TITLE
Forum or Mailing List? 

### ISSUE THREAD

**Issue by InikOfDoom** [aws/aws-sdk-cpp#227]
Hi. 

Is there something like a forum or a mailing list for the AWS C++ SDK? I'm currently migrating a platform independent Qt application (Win, iOS, Android) from a cloud service that is about to shut down to AWS and I have many questions, but I'm a bit reluctant to file an issue here on GitHub everytime I'm lost. My question here https://forums.aws.amazon.com/thread.jspa?threadID=234436&tstart=0 remained unanswered. 
If there's no forum / list (yet), is it ok to summarize multiple issues in one post here or do you insist on having one question / issue per post? 

Thanks and kind regards,
Dominik

**Comment by JonathanHenson** [comment]
I'm really sorry, we didn't respond to your forum question. I never saw it.
If you encounter a bug, please file a github issue for each one. Otherwise,
feel free to just send me an email.

On Tue, Jul 5, 2016 at 7:53 AM, InikOfDoom <notifications@github.com> wrote:

> Hi.
>
> Is there something like a forum or a mailing list for the AWS C++ SDK? I'm
> currently migrating a platform independent Qt application (Win, iOS,
> Android) from a cloud service that is about to shut down to AWS and I have
> many questions, but I'm a bit reluctant to file an issue here on GitHub
> everytime I'm lost. My question here
> https://forums.aws.amazon.com/thread.jspa?threadID=234436&tstart=0
> remained unanswered.
> If there's no forum / list (yet), is it ok to summarize multiple issues in
> one post here or do you insist on having one question / issue per post?
>
> Thanks and kind regards,
> Dominik
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/aws/aws-sdk-cpp/issues/227>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADvpxZRNykT-3NOha_n2TtR6uRGuChYvks5qSm_QgaJpZM4JFM6S>
> .
>



-- 
"The poet only asks to get his head into the heavens. It is the logician
who seeks to get the heavens into his head. And it is his head that splits"
--G. K. Chesterton-- "Orthodoxy"

**Comment by InikOfDoom** [comment]
Hi Jonathan, 
thanks. I'll add some issues I encountered here. My first questions were mostly about building the beast for iOS but I managed to get it up and running myself. 

Nevertheless, I think a forum / wiki for general questions and best practices would be really helpful. 

Kind regards, 
Dominik
