### ISSUE TITLE
Error parsing ~/.aws/config containing CRLF characters

### ISSUE THREAD

**Issue by scottmcnab** [aws/aws-sdk-cpp#2270]
### Describe the bug

Applications that use S3 with sso silently fail to load credentials if the `~/.aws/config file` is saved with DOS (CR/LF) line endings.
The same application works as expected if the config file is saved using Unix (LF) line endings.

This is particularly problematic on Windows machines where the config file may be shared between Windows and WSL, as Windows text editors are likely to save the config file in CR/LF format, but cause Linux applications to fail.

Inspecting the aws_sdk.log file shows the reason for the failure:
```
[ERROR] 2023-01-05 02:03:06.269 Aws::Config::ConfigFileProfileFSM [140265209610304] Found unexpected characters after closing bracket of Section Identifier [profile dev]
[ERROR] 2023-01-05 02:03:06.269 Aws::Config::ConfigFileProfileFSM [140265209610304] Found unexpected characters after closing bracket of Section Identifier [profile prod]
[INFO] 2023-01-05 02:03:06.270 Aws::Config::AWSProfileConfigLoaderBase [140265209610304] Failed to reload configuration.
````

This can be observed using the basic "Hello S3" app from https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/build-vcpkg.html

The failure is present in AWS CPP SDK version 1.9.347, however if the application is rebuilt using 1.9.220 then it works with both types of line ending. This suggests the bug was introduced sometime between these two versions.

### Expected Behavior

First, login using `aws sso login`. Then running the "Hello S3" application should show the number of S3 buckets. For example, this is the app compiled with AWS CPP SDK version 1.9.220:

```
$ unix2dos ~/.aws/config
unix2dos: converting file /home/scott/.aws/config to DOS format...
$ ./app | head -n 2
AWS SDK version:1.9.220
Found 118 buckets
$ dos2unix ~/.aws/config
dos2unix: converting file /home/scott/.aws/config to Unix format...
$ ./app | head -n 2
AWS SDK version:1.9.220
Found 118 buckets
```

### Current Behavior

When compiled with 1.9.347, the application shows zero buckets if `~/.aws/config` is saved with CR/LF newlines:

```
$ unix2dos ~/.aws/config
unix2dos: converting file /home/scott/.aws/config to DOS format...
$ ./app | head -n 2
AWS SDK version:1.9.347
Found 0 buckets
$ dos2unix ~/.aws/config
dos2unix: converting file /home/scott/.aws/config to Unix format...
$ ./app | head -n 2
AWS SDK version:1.9.347
Found 118 buckets
```

### Reproduction Steps

- Build the "Hello S3" application from https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/build-vcpkg.html against AWS CPP SDK version 1.9.347
- Setup a SSO profile using `aws configure sso`
- Observe that the application can list available buckets
- Save the `~/.aws/config` file again using DOS line endings (or use `unix2dos` command to convert the file)
- Observe that the application cannot list available buckets

### Possible Solution

Review the config file parsing code to ensure it can handle both CR/LF and LF line endings.

### AWS CPP SDK version used

1.9.347

### Compiler and Version used

gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

### Operating System and version

Ubunto-20.04

**Comment by DmitriyMusatkin** [comment]
Should be fixed by https://github.com/aws/aws-sdk-cpp/commit/69227fbdbffc86cef22395f4c433742fcd90e235.
