### ISSUE TITLE
DynamoDB: AttributeValue::GetM() missing const

### ISSUE THREAD

**Issue by InikOfDoom** [aws/aws-sdk-cpp#228]
I noticed that DynamoDB::Model::AtrributeValue::GetM() is not const (in contrast to all other GetX accessors). Since it returns a const ref to a map with const shared pointers, I don't see a reason for this other that it slipped through. I'd be glad if I could get rid of that horrible const cast I introduced in my code for this one. 

Kind regards,
Dominik

**Comment by JonathanHenson** [comment]
I believe this one was fixed a few days ago.

**Comment by JonathanHenson** [comment]
this was fixed here: 

a40e1e77adfff2856fed0f2d51d779c1f758757a
