### ISSUE TITLE
Difficulty setting up AWS SDK?

### ISSUE THREAD

**Issue by KevinWSteele** [aws/aws-sdk-cpp#229]
I am trying both Xcode and Visual Studio, but I can't get the SDK running correctly.
First, my IDE is having difficulty finding the header files. The instructions say to do this:
cd BUILD_DIR
cmake <path-to-root-of-this-source-code>
In Visual studio, I am replacing BUILD_DIR with the folder that contains my cpp file for the project. 
After entering that into command prompt, is there anything else I should be doing so that my IDE can find the header files without having to enter in the full path names?

In Xcode, I get the following error after just manually entering in the full path names for the header files:
Undefined symbols for architecture x86_64:
  "Aws::ShutdownAPI(Aws::SDKOptions const&)", referenced from:
      _main in main.o
  "Aws::InitAPI(Aws::SDKOptions const&)", referenced from:
      _main in main.o

Any suggestions?
Thanks,
Kevin

**Comment by JonathanHenson** [comment]
Have you tried using this? https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/

**Comment by KevinWSteele** [comment]
When I write: cmake –Daws-sdk-cpp_DIR=usr/local/aws-sdk-cpp /Users/kevinsteele/Desktop/aws-sdk-cpp 

I got the following error:  MACOSX_RPATH is not specified for the following targets:

   aws-cpp-sdk-access-management
   aws-cpp-sdk-acm
   aws-cpp-sdk-apigateway
   aws-cpp-sdk-application-autoscaling

   ........ and it lists a bunch of other targets.

**Comment by JonathanHenson** [comment]
That warning isn't a problem. Is that the only problem you are encountering.

**Comment by KevinWSteele** [comment]
When I try to run the program in XCode, the program still doesn't run. I'm getting the same error message:
Undefined symbols for architecture x86_64:
  "Aws::ShutdownAPI(Aws::SDKOptions const&)", referenced from:
      _main in main.o
  "Aws::InitAPI(Aws::SDKOptions const&)", referenced from:
      _main in main.o

The steps I did to build the SDK:
Opened up the terminal window
I cloned the code from github into my desktop folder
cd into that folder
cmake ./
make
sudo make install 

Then I did the command: make –Daws-sdk-cpp_DIR=usr/local/aws-sdk-cpp /Users/kevinsteele/Desktop/aws-sdk-cpp

**Comment by JonathanHenson** [comment]
Cmake with no generator argument typically uses make. When you want to work with another IDE that isn't purely cmake/make based, you need to tell cmake what type of build artifacts to create (Visual Studio, NMake, XCode, etc...). Any time you want to use cmake with Xcode you need to specify -G Xcode for your cmake call.

**Comment by KevinWSteele** [comment]
I tried adding -G Xcode to my cmake command. I then executed this command: xcodebuild install

When I write the following in my main.cpp file: #include <aws/core/Aws.h>

XCode cannot find the library/header file? Any ideas? thanks

**Comment by JonathanHenson** [comment]
So let me make sure I understand. 

you are running 
mkdir aws-sdk-cpp-build
cd aws-sdk-cpp-build
cmake -G Xcode ../aws-sdk-cpp
xcodebuild

Then when that finishes
cd <build for your project>
cmake -G Xcode –Daws-sdk-cpp_DIR=usr/local/aws-sdk-cpp-build ../<your project source dir>

When that finishes, there will be an .xcodeproj file in your build directory. When you open that, you can now build in XCode against the SDK.

**Comment by KevinWSteele** [comment]
thanks, I noticed an xcodeproj file called aws-sdk-cpp-all and opened that. I still cannot quite get my code running, but I'm still playing around with things and will probably post a more specific question in a little while.

**Comment by JonathanHenson** [comment]
You shouldn't be using the aws-sdk-cpp-all xcode project file. You should use the XCode project file for your application. When you run cmake -G Xcode –Daws-sdk-cpp_DIR=usr/local/aws-sdk-cpp-build <your project source>
It will set everything up for your project. Then you just open the xcode project up for your application.

**Comment by KevinWSteele** [comment]
Sorry, I am still quite confused. Alas, I have switched over to Ubuntu and I am now just trying to run my main.cpp file from the terminal.

The steps i did to build the SDK:
Git cloned the repository
Put the repository in my Downloads folder in a folder named 'aws-sdk-cpp'
Created a folder for my build in my Documents folder named 'aws-sdk-cpp'
I then executed the following commands:
cd Documents
cd aws-sdk-cpp
cmake '/home/kevin/Downloads/aws-sdk-cpp'
make
sudo make install
cd
cmake –Daws-sdk-cpp_DIR=usr/local/aws-sdk-cpp '/home/kevin/Documents/aws-sdk-cpp'

I do not know what to do next to run my code that uses the SDK.

In the blog post, it sounds like you are supposed to make a CMakeLists.txt with the following: 
"cmake_minimum_required(VERSION 2.8)
project(s3-sample)

#this will locate the aws sdk for c++ package so that we can use its targets
find_package(aws-sdk-cpp)

add_executable(s3-sample main.cpp)

#since we called find_package(), this will resolve all dependencies, header files, and cflags necessary
#to build and link your executable. 
target_link_libraries(s3-sample aws-cpp-sdk-s3)"

I do not know where to put that CMakeLists.txt file or where to put my main.cpp file or which commands to write to execute my main.cpp file from the command line so that it can use the functions from the SDK?

**Comment by KevinWSteele** [comment]
I am still having a lot of trouble. I executed the following command:
cmake –Daws-sdk-cpp_DIR=/home/kevin/Documents/aws-sdk-cpp-build /home/kevin/Documents/s3-sample

s3-sample is a folder that contains the CMakeLists.txt from the blog: https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/
It also contains my main.cpp file with code that tries to use simple functions from the SDK.

I get the following error message even though aws-sdk-cpp-build contains a configuration file with a name listed:

Could not find a package configuration file provided by "aws-sdk-cpp" with
  any of the following names:

    aws-sdk-cppConfig.cmake
    aws-sdk-cpp-config.cmake

  Add the installation prefix of "aws-sdk-cpp" to CMAKE_PREFIX_PATH or set
  "aws-sdk-cpp_DIR" to a directory containing one of the above files.  If
  "aws-sdk-cpp" provides a separate development package or SDK, be sure it
  has been installed.

**Comment by KevinWSteele** [comment]
I had to do something differently what the instructions say on your README,, but I finally got the library to link up. I added the following line at the bottom of the CMakeLists.txt file from Github:
add_subdirectory(s3-sample)

Then, I created a s3-folder in the folder I got from GitHub and in that new folder, I put my main.cpp file and the CMakeLists.txt  file from the blog. However, I could not get the following line to work: find_package(aws-sdk-cpp)

I had to instead write something like this: 
set(AWS_CPP_SDK_INCLUDE_DIRS /usr/local/include/aws CACHE STRING 
"aws-cpp-sdk include directories")
set(AWS_CPP_SDK_CORE_LIB "-l:/usr/local/lib/libaws-cpp-sdk-core.so" 
CACHE STRING "aws-cpp-sdk link core lib")
set(AWS_CPP_SDK_S3_LIB "-l:/usr/local/lib/libaws-cpp-sdk-s3.so" CACHE 
STRING "aws-cpp-sdk link S3 lib"
