### ISSUE TITLE
Error building for Android

### ISSUE THREAD

**Issue by eagene** [aws/aws-sdk-cpp#230]
I'm running the following command in a VS2013 developer prompt on Windows which I started as administrator:

cmake -G "NMake Makefiles" -DTARGET_ARCH=ANDROID -DBUILD_ONLY="cognito-identity,lambda" -DCMAKE_BUILD_TYPE=Release -DNDK_DIR=C:/Android/android-ndk-r12b -DANDROID_NDK=C:/Android/android-ndk-r12b -DANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-4.9 C:/Android/Aws/aws-sdk-cpp 

I get the below output.  The first error is about the C++ STL library. I've looked at the scripts and can't see how this is supposed to work. 

Any help?

Thanks,
Elizabeth

-- Generating android build config
-- Android ABI: none specified, defaulting to armeabi-v7a
-- Android std lib: libc++_shared
-- Android API level: android-21
-- Could not find an appropriate standalone toolchain.  Generating one into C:/A
ndroid/Aws/aws-sdk-cpp/toolchains/android/armeabi-v7a-arm-linux-androideabi-4.9-
android-21-libc++_shared
-- standalone toolchain name: arm-linux-androideabi-clang
WARNING: make-standalone-toolchain.sh will be removed in r13. Please try make_st
andalone_toolchain.py now to make sure it works for your needs.
HOST_OS=cygwin
HOST_EXE=.exe
HOST_ARCH=x86_64
HOST_TAG=windows-x86_64
HOST_NUM_CPUS=4
BUILD_NUM_CPUS=8
-nThe system cannot find the file specified.
Auto-config: --arch=arm
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying c++ runtime headers and libraries (with libc++abi)...
Copying files to: C:/Android/Aws/aws-sdk-cpp/toolchains/android/armeabi-v7a-arm-
linux-androideabi-4.9-android-21-libc++_shared
Cleaning up...
Done.
-- Building AWS libraries as shared objects
-- Http client: Curl
-- Encryption: Openssl
CMake Error at toolchains/android.toolchain.cmake:1054 (message):
  **Unknown runtime: libc++_shared**
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:98 (
include)
  CMakeLists.txt:366 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by bretambrose** [comment]
Just a guess, but I think libc++ may only be usable by clang.  So there are a couple of things you could try:
    (1) Add "-DANDROID_STL=gnustl" to your cmake command line
or (2) Remove "-DANDROID_TOOLCHAIN_NAME=..." from the command line 

If both work, I would suggest (2) because Android is deprecating gcc support and also because gnustl does not work well with the AWS libraries on Android.

Outside of these workarounds, it's an error on our part to default to libc++ if you manually specify gcc as the toolchain, so let's keep this issue open as a reminder to myself.

**Comment by eagene** [comment]
I use clang with c++_static (llvm) for compiling my native code, so I need to be compatible. I tried that first without success - see below (please excuse the Windows line breaks).

gnustl won't work for my project. 

Also, I couldn't get it to build with NDK r10d (what I'm currently using in my product) because of the "-llvm" argument. I upgraded to r12b to see if I could get this to build, but would prefer to not upgrade my NDK at this point if not necessary.

Thanks,
Elizabeth


cmake -G "NMake Makefiles" -DTARGET_ARCH=ANDROID -DBUILD_ON
LY="cognito-identity,lambda" -DCMAKE_BUILD_TYPE=Release -DNDK_DIR=C:/Android/and
roid-ndk-r12b -DANDROID_NDK=C:/Android/android-ndk-r12b  C:/Android/Aws/aws-sdk-
cpp
-- Found Git: C:/Program Files (x86)/Git/cmd/git.exe (found version "1.9.5.msysg
it.0")
-- Generating android build config
-- Android ABI: none specified, defaulting to armeabi-v7a
-- Android toolchain unspecified, defaulting to standalone-clang
-- Libc++ requires setting API level to at least 21
-- Android std lib: libc++_shared
-- Android API level: android-21
-- Could not find an appropriate standalone toolchain.  Generating one into C:/A
ndroid/Aws/aws-sdk-cpp/toolchains/android/armeabi-v7a-standalone-clang-android-2
1-libc++_shared
-- standalone toolchain name: arm-linux-androideabi-clang
WARNING: make-standalone-toolchain.sh will be removed in r13. Please try make_st
andalone_toolchain.py now to make sure it works for your needs.
HOST_OS=cygwin
HOST_EXE=.exe
HOST_ARCH=x86_64
HOST_TAG=windows-x86_64
HOST_NUM_CPUS=4
BUILD_NUM_CPUS=8
-nThe system cannot find the file specified.
Auto-config: --arch=arm
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying c++ runtime headers and libraries (with libc++abi)...
Copying files to: C:/Android/Aws/aws-sdk-cpp/toolchains/android/armeabi-v7a-stan
dalone-clang-android-21-libc++_shared
Cleaning up...
Done.
-- Building AWS libraries as shared objects
-- Http client: Curl
-- Encryption: Openssl
CMake Error at toolchains/android.toolchain.cmake:743 (message):
  Specified toolchain "standalone-clang" is missing in your NDK or broken.
  Please verify that your NDK is working or select another compiler
  toolchain.

  To configure the toolchain set CMake variable ANDROID_TOOLCHAIN_NAME to one
  of the following values:

    * aarch64-linux-android-4.9
    * arm-linux-androideabi-4.9
    * mips64el-linux-android-4.9
    * mipsel-linux-android-4.9
    * x86-4.9
    * x86_64-4.9

Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:98 (
include)
  CMakeLists.txt:366 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by eagene** [comment]
I'm getting farther - I ran this:

cmake -G "NMake Makefiles" -DTARGET_ARCH=ANDROID -DBUILD_ONLY="cognito-identity;lambda" -DCMAKE_BUILD_TYPE=Release -DNDK_DIR=C:/Android/android-ndk-r12b  C:/Android/Aws/aws-sdk-cpp

Then manually did a chmod -R +rw on the toolchain directory, then ran it again and it completed.

Now I need to figure out what's next...

**Comment by eagene** [comment]
OK, I ran nmake and it ran for a while, eventually failing with this error:

ce/external/json-cpp/jsoncpp.cpp.o
[ 16%] Linking CXX shared library libaws-cpp-sdk-core.so
C:\Android\Aws\aws-sdk-cpp\toolchains\android\armeabi-v7a-standalone-clang-andro
id-21-libc++_shared\bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-l
inux-androideabi/bin\ld: error: cannot find -landroid_support
clang38++.exe: error: linker command failed with exit code 1 (use -v to see invo
cation)
NMAKE : fatal error U1077: 'C:\Android\Aws\aws-sdk-cpp\toolchains\android\armeab
i-v7a-standalone-clang-android-21-libc++_shared\bin\clang++.cmd' : return code '
0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\BIN\nmake.exe"' : return code '0x2'
Stop.

How can I fix this?

Thanks,
Elizabeth

**Comment by bretambrose** [comment]
It looks like the core problem is that the NDK's make_standalone_toolchain script, which we're using to simplify our build assumptions, actually changes a lot between NDK versions.  During development, I only used 11c.  I found some tweaks that will make things work with your current 10d installation.  I'll need to look into what we need to make things work for 12 and then do the right thing in the cmake script depending on the NDK version.

In the meantime, try the following:  switch back to using 10d and then starting at line 197 of the top-level CMakeLists.txt file, add "3.5" at the end of all of the set(__TOOLCHAIN "blablah-clang") commands.  Also change the --use-llvm to --llvm-version=3.5.

That section of the CMakeLists.txt should then look like:

            if(ANDROID_ABI MATCHES "armeabi")
                set(__TOOLCHAIN "arm-linux-androideabi-clang3.5")
            elseif(ANDROID_ABI MATCHES "arm64")
                set(__TOOLCHAIN "aarch64-linux-android-clang3.5")
            elseif(ANDROID_ABI MATCHES "x86_64")
                set(__TOOLCHAIN "x86_64-clang3.5")
            elseif(ANDROID_ABI MATCHES "x86")
                set(__TOOLCHAIN "x86-clang3.5")
            elseif(ANDROID_ABI MATCHES "mips64")
                set(__TOOLCHAIN "mips64el-linux-android-clang3.5")
            elseif(ANDROID_ABI MATCHES "mips")
                set(__TOOLCHAIN "mipsel-linux-android-clang3.5")
            else()
                message(FATAL, "Unable to map ANDROID_ABI value ${ANDROID_ABI} to a valid architecture for make-standalone-toolchain")
            endif()

            message(STATUS "standalone toolchain name: ${__TOOLCHAIN}")

            execute_process(
                COMMAND ${SH_VAR} ${NDK_DIR}/build/tools/make-standalone-toolchain.sh --ndk-dir=${NDK_DIR} --toolchain=${__TOOLCHAIN} --llvm-version=3.5 --stl=${STANDALONE_TOOLCHAIN_STL} --platform=${ANDROID_NATIVE_API_LEVEL} --install-dir=${STANDALONE_TOOLCHAIN_DIR}
                WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
            )

**Comment by eagene** [comment]
nmake is running - thanks for the help. I'll let you know if it completes. I had to make an additional tweak (see below).

BTW, building on my mac for iOS took 10 minutes with no errors. I haven't tried linking the resulting library in xcode yet, but I'm sure it'll be straightforward.

==============================================
Attempt 1:
==============================================
SET ANDROID_NDK=C:\Android\android-ndk-r10d
C:\Android\Aws\build>cmake -G "NMake Makefiles" -DTARGET_ARCH=ANDROID -DBUILD_ON
LY="cognito-identity;lambda" -DCMAKE_BUILD_TYPE=Release -DNDK_DIR=C:/Android/and
roid-ndk-r10d C:/Android/Aws/aws-sdk-cpp
-- Found Git: C:/Program Files (x86)/Git/cmd/git.exe (found version "1.9.5.msysg
it.0")
-- Generating android build config
-- Android ABI: none specified, defaulting to armeabi-v7a
-- Android toolchain unspecified, defaulting to standalone-clang
-- Libc++ requires setting API level to at least 21
-- Android std lib: libc++_shared
-- Android API level: android-21
-- Could not find an appropriate standalone toolchain.  Generating one into C:/A
ndroid/Aws/aws-sdk-cpp/toolchains/android/armeabi-v7a-standalone-clang-android-2
1-libc++_shared
-- standalone toolchain name: arm-linux-androideabi-clang3.5
**Host system 'cygwin-x86' is not supported by the source NDK!
Try --system=<name> with one of:  windows-x86_64**
-- Building AWS libraries as shared objects
-- Http client: Curl
-- Encryption: Openssl
CMake Error at toolchains/android.toolchain.cmake:308 (file):
  file STRINGS file
  "C:/Android/Aws/aws-sdk-cpp/toolchains/android/armeabi-v7a-standalone-clang-an
droid-21-libc++_shared/sysroot/usr/include/android/api-level.h"
  cannot be read.
Call Stack (most recent call first):
  toolchains/android.toolchain.cmake:507 (__DETECT_NATIVE_API_LEVEL)
  C:/Program Files/CMake/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:98 (
include)
  CMakeLists.txt:366 (project)

  
==============================================
Attempt 2:
==============================================
  Edited CMakeLists.txt as follows:
                  COMMAND ${SH_VAR} ${NDK_DIR}/build/tools/make-standalone-toolchain.sh --ndk-dir=${NDK_DIR} --toolchain=${__TOOLCHAIN} --llvm-version=3.5 --stl=${STANDALONE_TOOLCHAIN_STL} --platform=${ANDROID_NATIVE_API_LEVEL} --install-dir=${STANDALONE_TOOLCHAIN_DIR} **--system=windows-x86_64**
				  
C:\Android\Aws\build>cmake -G "NMake Makefiles" -DTARGET_ARCH=ANDROID -DBUILD_ON
LY="cognito-identity;lambda" -DCMAKE_BUILD_TYPE=Release -DNDK_DIR=C:/Android/and
roid-ndk-r10d C:/Android/Aws/aws-sdk-cpp
-- Generating android build config
-- Android ABI: none specified, defaulting to armeabi-v7a
-- Android toolchain unspecified, defaulting to standalone-clang
-- Android std lib: libc++_shared
-- Android API level: android-21
-- Could not find an appropriate standalone toolchain.  Generating one into C:/A
ndroid/Aws/aws-sdk-cpp/toolchains/android/armeabi-v7a-standalone-clang-android-2
1-libc++_shared
-- standalone toolchain name: arm-linux-androideabi-clang3.5
Copying prebuilt binaries...
FIND: Invalid switch
Copying sysroot headers and libraries...
Copying c++ runtime headers and libraries (with libc++abi)...
Copying files to: C:/Android/Aws/aws-sdk-cpp/toolchains/android/armeabi-v7a-stan
dalone-clang-android-21-libc++_shared
Cleaning up...
Done.
-- Building AWS libraries as shared objects
-- Http client: Curl
-- Encryption: Openssl
CMake Error at toolchains/android.toolchain.cmake:308 (file):
  file STRINGS file
  **"C:/Android/Aws/aws-sdk-cpp/toolchains/android/armeabi-v7a-standalone-clang-an
droid-21-libc++_shared/sysroot/usr/include/android/api-level.h"
  cannot be read.**
Call Stack (most recent call first):
  toolchains/android.toolchain.cmake:507 (__DETECT_NATIVE_API_LEVEL)
  C:/Program Files/CMake/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:98 (
include)
  CMakeLists.txt:366 (project)


CMake Warning at toolchains/android.toolchain.cmake:323 (message):
  Could not determine machine name for compiler from
  C:/Android/Aws/aws-sdk-cpp/toolchains/android/armeabi-v7a-standalone-clang-and
roid-21-libc++_shared
Call Stack (most recent call first):
  toolchains/android.toolchain.cmake:510 (__DETECT_TOOLCHAIN_MACHINE_NAME)
  C:/Program Files/CMake/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:98 (
include)
  CMakeLists.txt:366 (project)


CMake Error at toolchains/android.toolchain.cmake:512 (message):
  Could not determine machine name of your toolchain.  Probably your Android
  standalone toolchain is broken.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:98 (
include)
  CMakeLists.txt:366 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!


==============================================
Attempt 3:
==============================================
After doing a recursive chmod +rx on the toolchain directory

C:\Android\Aws\build>cmake -G "NMake Makefiles" -DTARGET_ARCH=ANDROID -DBUILD_ON
LY="cognito-identity;lambda" -DCMAKE_BUILD_TYPE=Release -DNDK_DIR=C:/Android/and
roid-ndk-r10d C:/Android/Aws/aws-sdk-cpp
-- Generating android build config
-- Android ABI: none specified, defaulting to armeabi-v7a
-- Android toolchain unspecified, defaulting to standalone-clang
-- Android std lib: libc++_shared
-- Android API level: android-21
-- Standalone toolchain disabled; this is not a well-supported option
-- Building AWS libraries as shared objects
-- Http client: Curl
-- Encryption: Openssl
CMake Deprecation Warning at C:/Program Files/CMake/share/cmake-3.6/Modules/CMak
eForceCompiler.cmake:79 (message):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  toolchains/android.toolchain.cmake:1146 (CMAKE_FORCE_C_COMPILER)
  C:/Program Files/CMake/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:98 (
include)
  CMakeLists.txt:366 (project)


CMake Deprecation Warning at C:/Program Files/CMake/share/cmake-3.6/Modules/CMak
eForceCompiler.cmake:93 (message):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  toolchains/android.toolchain.cmake:1158 (CMAKE_FORCE_CXX_COMPILER)
  C:/Program Files/CMake/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:98 (
include)
  CMakeLists.txt:366 (project)


-- Install binary prefix: android/armeabi-v7a
-- Considering cognito-identity
-- Considering lambda
Updating version info to 0.12.17
-- Custom memory management enabled; stl objects now using custom allocators
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Android/Aws/build

**Comment by bretambrose** [comment]
Good to hear that you've been able to make progress.  Here are a few more things that I ran into or thought of while looking into this:

If you run into a "command line too big" error while building aws-cpp-sdk-iam, add the following to CMakeLists.txt, just above the "project(aws-sdk-cpp-all)" line (this will go into a future release, but might take a while to reach the public):

SET(CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS 1)
SET(CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES 1)
SET(CMAKE_CXX_RESPONSE_FILE_LINK_FLAG "@")


Some of the libraries, like iam (which you end up building because the cognito and lambda tests depend on it) and ec2, are so large that their link line exceeds the windows command line maximum (30kish).  This gets around that by tweaking cmake to use response files rather than the command line.

Another suggestion: if you find yourself rebuilding SDK a lot for whatever reasons, consider using "-DENABLE_UNITY_BUILD=ON" as part of your cmake command line.  It should speed up compilation of the service APIs quite a bit (curl/openssl remain slow though).  If things are still too slow, consider installing QT and putting Jom on your command line.  If you use -G "NMake Makefiles JOM" rather than -G "NMake Makefiles" you should also see a large speedup; by itself nmake does not have a way to do parallel builds, but jom does.

**Comment by eagene** [comment]
Thanks for that. I did hit that error and made the change you suggested and I was able to get it to compile.

Was I clear about the additional two issues I needed to work around?
1. File permissions in the standalone toolchain directory
2. The --system argument to make-standalone-toolchain.sh

I have it built now so I'll start prototyping my code. I had it working in Java, but my code is cross platform, so it'll be much easier if I can put it in the C++ portion.

How close do you think you are to GA of this? I'm trying to gauge how much stability I should expect.

Thanks for all your help,
Elizabeth

**Comment by bretambrose** [comment]
I think both of those issues are coming from Cygwin.  I can add the workarounds if it's detected, but you might end up being a guinea pig for testing purposes, as I don't have easy access to that kind of setup.

I'm guessing GA is still a couple of months out.  Android-wise, the only major thing I'm planning before then is reworking our Openssl build to not use a flimsy CMake wrapper, but instead use the standard build method (right now, it doesn't work on a few less-common architectures).  At this point, I think we're mostly trying to close the feature parity gap between us and the other language-specific SDKs.  I'll check with Jonathan to see if he can think of any other potential compatibility issues coming up before then.

**Comment by bretambrose** [comment]
One other thing, apologies if this is a dumb question, but have you tried building for Android on the Mac without using Cygwin?

**Comment by eagene** [comment]
No, I haven't, but I will when I get a chance. I've been slowly moving all my development over to the mac.

**Comment by singku** [comment]
@bretambrose @eagene Looks like you guys have solved the problem and just left some ongoing discussion here right?
