### ISSUE TITLE
cmake version and target_compile_options

### ISSUE THREAD

**Issue by yiown** [aws/aws-sdk-cpp#231]
The CMakeLists.txt file from core contains the instruction:
target_compile_options(aws-cpp-sdk-core PUBLIC -std=c++11)
And even thou the header says:
cmake_minimum_required(VERSION 2.8.5)
The instruction is only available since version 3.0:
https://cmake.org/cmake/help/v3.0/command/target_compile_options.html

**Comment by JonathanHenson** [comment]
This was added in 2.8.12. We've updated the cmake versions in each file as well as the generator.
