### ISSUE TITLE
CMake Parameters Page in Developer guide should specify where to make these changes

### ISSUE THREAD

**Issue by jkaplan55** [aws/aws-sdk-cpp#2316]
### Describe the issue

There should be a note that these parameters are handled in the cmakelists.txt of the original SourceRepo.

I lost a lot of time trying to specify these parameters when building my actual project.  Eventually I figured out that I need to set these parameters when doing the initial code generation from the Source repo.

That might be obvious to experienced developers, but a call out here would definitely help people who are a bit less experienced.

### Links

https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/cmake-params.html

**Comment by jmklix** [comment]
Thanks for sharing your frustration and helping us improve the clarity for other. We will looking into adding additional notes to make sure it's clear where you need to change the CMake Parameters.

**Comment by jmklix** [comment]
Changes have been make. Please let us know if you would like any more clarifications on the docs
