### ISSUE TITLE
Multipart Fatal error condition occurred allocator != ((void *)0) AWS S3 CPP SDK

### ISSUE THREAD

**Issue by asod1999** [aws/aws-sdk-cpp#2325]
### Describe the bug

I'm trying to send files using multipart sender provided by the SDK AWS for CPP.

The idea is to create a client to send files to Minio Server using TransferManager.

The code has been created inspired by AWS Examples:

[https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/examples-s3-transfermanager.html](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/examples-s3-transfermanager.html)

But it throws this error:

>File upload finished. 
>Fatal error condition occurred in /aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/allocator.c:209: allocator != ((void *)0) 
>Exiting Application No call stack information available Aborted (core dumped)

The program is as follows:

```c++

#include <iostream>
#include <fstream>
#include <string.h>
#include <chrono>
#include <thread>
#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>
#include <aws/core/utils/threading/Executor.h>
#include <aws/transfer/TransferManager.h>
#include <aws/transfer/TransferHandle.h>
#include <aws/core/auth/AWSCredentials.h>

using Sign_Payload =  Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy;

struct config_client{
    std::string user_id = "REDACTED";
    std::string password = "REDACTED" ;
    std::string ip = "127.0.0.1:9000";
    std::string region = "eu-west-3"; 
    Aws::Http::Scheme scheme = Aws::Http::Scheme::HTTP;
    bool verifySSL = false;
}; 

//auto start_server(const char* path_filename, std::string bucket,config_client config_params){
auto start_server(config_client configuration){

    Aws::SDKOptions options;

    //Debug Logging
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;

    //Set environment for efficiency
    setenv("AWS_EC2_METADATA_DISABLED", "true", 1);
    
    //Variables

    const uint64_t buffer_size = 5 * 1024 * 1024;

    //Init API

    Aws::InitAPI(options);
    {
        Aws::Client::ClientConfiguration config;
        config.region = configuration.region; 
        config.endpointOverride = configuration.ip;
        config.scheme = configuration.scheme;
        config.verifySSL = configuration.verifySSL;

        auto credentials = Aws::Auth::AWSCredentials{configuration.user_id,configuration.password};
        
        auto executor = Aws::MakeShared<Aws::Utils::Threading::PooledThreadExecutor>("executor", 1);
        
        Aws::Transfer::TransferManagerConfiguration transfer_config(executor.get());

        transfer_config.s3Client = Aws::MakeShared<Aws::S3::S3Client>("S3Client",credentials,config,Sign_Payload::Never, false);

        transfer_config.bufferSize = buffer_size;

        auto transfer_manager = Aws::Transfer::TransferManager::Create(transfer_config);

        auto uploadHandle = transfer_manager->UploadFile("/s3_sdp/build/my-file1.txt", "sdp", "my-file1.txt", "text/plain", Aws::Map<Aws::String, Aws::String>());

        uploadHandle->WaitUntilFinished();

        bool success = uploadHandle->GetStatus() == Aws::Transfer::TransferStatus::COMPLETED; 

        if (!success)
        {
            auto err = uploadHandle->GetLastError();           
            std::cout << "File upload failed:  "<< err.GetMessage() << std::endl;
        }
        else
        {
            std::cout << "File upload finished." << std::endl;
        }
        
    
    Aws::ShutdownAPI(options);
    }
    

}
```

### Expected Behavior

I've tried to modify:

-> auto executor = Aws::MakeSharedAws::Utils::Threading::PooledThreadExecutor("executor", 1);

With:

-> auto executor = Aws::MakeSharedAws::Utils::Threading::PooledThreadExecutor("executor", 25);

And using defaultExecutor instead as follows:

-->auto executor = Aws::MakeSharedAws::Utils::Threading::DefaultExecutor("executor", 1);

### Current Behavior

I think the problem is in that line:

transfer_config.s3Client = Aws::MakeSharedAws::S3::S3Client("S3Client",credentials,config,Sign_Payload::Never, false);

But i don't know how can i omit or solve the problem, althought the program is working and the server is recieving the data divided in multiparts.

In addition, without TranferManager program is working and error is not throw.

### Reproduction Steps

Install SDK: 

>git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp
>mkdir sdk_build
>cd sdk_build
>cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=/usr/local/ -DCMAKE_INSTALL_PREFIX=/usr/local/ -DBUILD_ONLY="s3"
>cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=/usr/local/ -DCMAKE_INSTALL_PREFIX=/usr/local/ -DBUILD_ONLY="crt"
>make
>make install

Compile the program to send a Minio Server.

### AWS CPP SDK version used

1.11.5

### Compiler and Version used

Cmake 3.22

### Operating System and version

CentOS 7

**Comment by SergeyRyabinin** [comment]
Hi @asod1999 ,

I have edited your message to exclude some personal information.

For the issue,
please update
```
    Aws::ShutdownAPI(options);
    }
```
to
```
    }
    Aws::ShutdownAPI(options);
```
because otherwise SDK objects destruction would happen after ShutdownAPI leading to memory issues.

I also suggest to use new api method of transfer manager `WaitUntilAllFinished` (because TransferManager self-prolong it's lifetime until all tasks finished), so update to
```
       transfer_manager->WaitUntilAllFinished();
    }
    Aws::ShutdownAPI(options);
```

Best regards,
Sergey

**Comment by asod1999** [comment]
Thank you very much!
It works!
