### ISSUE TITLE
Unable to link library generated on Mac M1 (arm64)

### ISSUE THREAD

**Issue by sampath441** [aws/aws-sdk-cpp#2345]
### Describe the bug

I'm trying to use c++ aws s3 api's in our code its not working in one of the mac ( MAC M10 which is arm64 based). we get the below error;

iterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
"_curl_version_info", referenced from:
Aws::Http::CurlHttpClient::InitGlobalState() in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
ld: symbol(s) not found for architecture arm64

Does aws-sdk-cpp support Mac arm64 architecture? If so any special arguments to be passed for cmake to generate library having arm64 symbols?

### Expected Behavior

Linking should be success

### Current Behavior

iterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
"_curl_version_info", referenced from:
Aws::Http::CurlHttpClient::InitGlobalState() in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
ld: symbol(s) not found for architecture arm64

### Reproduction Steps

1. Follow the intallation steps mentioned in README on MAC M1 ( ARM 64)
2.  Write  a sample program to list buckets on s3 
3. Link either static / dynamic library to the program using g++

### AWS CPP SDK version used

1.11

### Compiler and Version used

Apple clang version 12.0.5 (clang-1205.0.22.11) Target: arm64-apple-darwin20.6.0 Thread model: posix

### Operating System and version

Mac M1

**Comment by jmklix** [comment]
How exactly are you building this and which cmake commands are you using?

**Comment by sampath441** [comment]
Resolved issue by generating static library
