### ISSUE TITLE
Source file encoding as UTF-8

### ISSUE THREAD

**Issue by zeliard** [aws/aws-sdk-cpp#235]
Can you change the encoding types to UTF-8 and reupload all source code files?

It's somewhat annoying whenever compiling this SDK in Visual Studio.
In my case, whenever pulling & merging from the origin repo, I used to run a powershell script as follows:

Function  SaveAsUtf8([string] $path)
{
  [String[]] $files = Get-ChildItem $path -Recurse -Include *.h, *.cpp;
  foreach ($file  in $files)
    {
      "Saving As $file...";
       [String]$s = [IO.File]::ReadAllText($file);
       [IO.File]::WriteAllText($file, $s, [Text.Encoding]::UTF8);
     }
}

**Comment by JonathanHenson** [comment]
We've fixed this here 22b769689e5eaa7bb5e02f2443cd5442e863cf99
