### ISSUE TITLE
Compile gamelift on linux for unreal，libcrypto so did not match

### ISSUE THREAD

**Issue by hexun80149128** [aws/aws-sdk-cpp#2359]
### Describe the bug

Compile gamelift on linux for unreal，for the success，i did the the flowing steps：

1. https://docs.aws.amazon.com/zh_cn/sdk-for-cpp/v1/developer-guide/setup-linux-vcpkg.html  
 i follow the guide，use vcpkg to compile
for success and in linux.cmake I add
 set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_FLAGS "-std=c++11 -stdlib=libc++")
set(CMAKE_EXE_LINKER_FLAGS "-stdlib=libc++ -lc++abi")
set(CMAKE_C_COMPILER "/usr/bin/clang-13")
set(CMAKE_CXX_COMPILER "/usr/bin/clang++-13")
2.i copy installed/x64-linux-dynamic-release/lib all lib file to unreal5
and start the unreal，finally occuer the error

s2n_init() failed: 402653266 (The libcrypto major version number seen at compile-time is different from the major version number seen at run-time)
Fatal error condition occurred in /home/genius/code/vcpkg/buildtrees/aws-c-io/src/v0.13.14-9c542d2ee9.clean/source/s2n/s2n_tls_channel_handler.c:197: 0 && "s2n_init() failed"

### Expected Behavior

i wish unreal can success

### Current Behavior

s2n_init() failed: 402653266 (The libcrypto major version number seen at compile-time is different from the major version number seen at run-time)
Fatal error condition occurred in /home/genius/code/vcpkg/buildtrees/aws-c-io/src/v0.13.14-9c542d2ee9.clean/source/s2n/s2n_tls_channel_handler.c:197: 0 && "s2n_init() failed"

### Reproduction Steps

1. https://docs.aws.amazon.com/zh_cn/sdk-for-cpp/v1/developer-guide/setup-linux-vcpkg.html  
 i follow the guide，use vcpkg to compile
for success and in linux.cmake I add
 set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_FLAGS "-std=c++11 -stdlib=libc++")
set(CMAKE_EXE_LINKER_FLAGS "-stdlib=libc++ -lc++abi")
set(CMAKE_C_COMPILER "/usr/bin/clang-13")
set(CMAKE_CXX_COMPILER "/usr/bin/clang++-13")
2.i copy installed/x64-linux-dynamic-release/lib all lib file to unreal5
and start the unreal，finally occuer the error

### Possible Solution

![92b131f05cf3846fa03f171ecda3b07](https://user-images.githubusercontent.com/16658848/220809747-cb306d80-1321-42b4-b4fc-30c36780b639.png)
i replace the libcrypto.so with two versions,and it did not work

### AWS CPP SDK version used

1.11.4

### Compiler and Version used

gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)/VS 1.75.1/clang-13

### Operating System and version

Ubuntu22.04

**Comment by jmklix** [comment]
We don't currently support building this sdk with unreal. But this is something that we would like to add. Closing this issue for now, but please let us know if you are still running into any problems after support is added
