### ISSUE TITLE
Conan 2.0 support

### ISSUE THREAD

**Issue by BoilerTom90** [aws/aws-sdk-cpp#2360]
### Describe the feature

Conan 2.0 just came out, and attempting to install aws-sdk-cpp with it fails indicating 2.0 is not supported.  Is there a feature in the works to upgrade the recipes to work with Conan 2.0?

many other c++ packages have already been updated to work with 2.0:

https://github.com/conan-io/conan-center-index/discussions/16196

### Use Case

Conan 2.0 is a necessity to successfully use Conanlock files.  Conan 1.x lock files fail for a variety of reasons.

### Proposed Solution

I believe the recipes need to be updated per the 2.0 guidelines.

https://docs.conan.io/1/conan_v2.html

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by abhijith96** [comment]
Is there a rough estimate on the date for the new Conan 2.0 compatible recipe to be released.

**Comment by jmklix** [comment]
After reconsideration this is not something we are planning on doing. We have no plans to release this sdk on any package managers and recommend that you consume it from source and compile it on your own. Please let us know if you have any questions/concerns with compiling this sdk
