### ISSUE TITLE
R53 ChangeResourceRecordSets error

### ISSUE THREAD

**Issue by jimmyt857** [aws/aws-sdk-cpp#237]
I am getting an "Unable to connect to endpoint" error when calling ChangeResourceRecordSetsAsync. I am making the call as with the following setup (sorry about the tabbing):

```c++
const Aws::Auth::AWSCredentials localCredentials(accessKey, secretKey);

Aws::Client::ClientConfiguration clientConfig;
clientConfig.scheme = Aws::Http::Scheme::HTTPS;
clientConfig.connectTimeoutMs = 30000;
clientConfig.requestTimeoutMs = 30000;
clientConfig.region = Aws::Region::US_WEST_2;

std::string recordName = "something";
std::string dnsName = "somethingElse";
Aws::Route53::Route53Client r53Client(localCredentials, clientConfig);
            auto request = Aws::Route53::Model::ChangeResourceRecordSetsRequest()
            .WithHostedZoneId(domainHostedZoneId)
            .WithChangeBatch(Aws::Route53::Model::ChangeBatch().WithChanges({
                Aws::Route53::Model::Change()
                .WithAction(changeAction)
                .WithResourceRecordSet(Aws::Route53::Model::ResourceRecordSet()
                    .WithName(recordName.c_str())
                    .WithType(Aws::Route53::Model::RRType::CNAME)
                    .WithTTL(300)
                    .WithResourceRecords({
                        Aws::Route53::Model::ResourceRecord()
                        .WithValue(dnsName.c_str())
                    })
                )
            }));

r53Client.ChangeResourceRecordSetsAsync(request, callback);
```

I am successfully making many other Aws calls to EC2, S3, and ElasticLoadBalancer with analogous setups, so I don't understand what it wrong, although I'm sure it is something silly. I turned on trace logging and it is reporting a curl error code of 6 (couldn't resolve host), which makes it sound like the Aws library is not contacting the correct endpoint.

**Comment by JonathanHenson** [comment]
Route 53 is only available in us-east-1

**Comment by jimmyt857** [comment]
Haha, well that is pretty silly. Is there documentation anywhere that covers things like this?

**Comment by JonathanHenson** [comment]
http://docs.aws.amazon.com/general/latest/gr/rande.html#r53_region

**Comment by jimmyt857** [comment]
Sorry to bother you again, but I just tried this and I am getting the same error. The log says "Making request to https://route53.us-east-1.amazonaws.com/2013-04-01/hostedzone", but it looks like I'm supposed to be hitting route53.amazonaws.com, without the us-east-1. The documentation on this github page says not to use the endpointOverride field. What is the intended way for me to make this request?

**Comment by JonathanHenson** [comment]
You can certainly use endpoint override and signing region, but I think you just found a bug. I'll fix it this week and let you know when we Push it out.

**Comment by jimmyt857** [comment]
Haha ok great, thanks!

**Comment by JonathanHenson** [comment]
I just pushed the update for this out. It will be a little while before it makes out to NuGet.
