### ISSUE TITLE
kms sometimes crashes after invoking encrypt & decrypt

### ISSUE THREAD

**Issue by devtoolset** [aws/aws-sdk-cpp#2395]
### Describe the bug

Describe the bug
When call KMSClient::Encrypt() and KMSClient::Decrypt(), it sometimes crashes the app. No core dump generated, no error logs found in aws logs.

Expected Behavior
Want to know why this happened randomly

Current Behavior
No error found in logs.

Reproduction Steps
It happens randomly, no specific steps to reproduce it.

Possible Solution
No response

Additional Information/Context
No response

AWS CPP SDK version used
1.9.313

Compiler and Version used
gcc 5.4.0

Operating System and version
Ubuntu 16.04.7

### Expected Behavior

No crash happens.

### Current Behavior

Randomly crash.

### Reproduction Steps

.

### AWS CPP SDK version used

1.9.313, 1.10.10

### Compiler and Version used

gcc 5.4.0

### Operating System and version

Ubuntu 16.04.7

**Comment by devtoolset** [comment]
This issue happens randomly, sometimes it can run well for a long time without crash, but sometimes when we do encryption or decryption, it crash. We need several tries to make it.

1. This is the code to init AWS:
```
std::shared_ptr<Aws::OFStream> _sptrOfs
    = Aws::MakeShared<Aws::OFStream>(serviceName.c_str(), _logFilePath.c_str(), Aws::OFStream::out | Aws::OFStream::app);
awsCrendtials.awsSdkOptions.loggingOptions.logger_create_fn = [&]() {
    return Aws::MakeShared<Aws::Utils::Logging::DefaultLogSystem>(serviceName.c_str(), Aws::Utils::Logging::LogLevel::Warn,
                                                                  _sptrOfs);
};

awsCrendtials.awsSdkOptions.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Warn;

Aws::InitAPI(awsCrendtials.awsSdkOptions);
Aws::Auth::AWSCredentials _awsCredentials(awsCrendtials.awsAccessId, awsCrendtials.awsSecretKey);
Aws::Client::ClientConfiguration _clientConfig;
...
awsCrendtials.kwsClient = new Aws::KMS::KMSClient(_awsCredentials, _clientConfig);
if (awsCrendtials.kwsClient == nullptr) {
    return false;
}
return true;
```
2. This is the code for encryption
```
Aws::KMS::Model::EncryptRequest _encryptRequest;
_encryptRequest.SetKeyId(awsCrendtials.awsArn);
_encryptRequest.SetPlaintext(_data2Encrypt);
Aws::KMS::Model::EncryptOutcome _encryptOutcome = awsCrendtials.kwsClient->Encrypt(_encryptRequest);            
if (_encryptOutcome.IsSuccess()) {
    Aws::KMS::Model::EncryptResult _encryptResult = _encryptOutcome.GetResult();
    Aws::Utils::ByteBuffer _cippherText = _encryptResult.GetCiphertextBlob();                
    unsigned int _strLen = 0;
    memset(base64Str, 0x00, BUFFER_SIZE);
    CBase64::Base64Encode(base64Str, &_strLen, (const unsigned char*)_cippherText.GetUnderlyingData(),
                          _cippherText.GetLength());
    encryptRst = std::string(base64Str, _strLen);
    return 0;
} else {
    Aws::KMS::KMSError _error = _encryptOutcome.GetError();
    Aws::KMS::KMSErrors _errType = _error.GetErrorType();
    Aws::String _errMsg = _error.GetMessage();
	return 1;
}
```

**Comment by jmklix** [comment]
https://github.com/aws/aws-sdk-cpp/issues/2096

**Comment by devtoolset** [comment]
![image](https://user-images.githubusercontent.com/72804892/226856899-ba4e48d5-c030-478a-8f07-d21ca722c5f5.png)

**Comment by devtoolset** [comment]
I checked that Broken pipe sometimes happened to curl_easy_perform()

**Comment by jmklix** [comment]
It looks like you are using the sdk before you are calling `InitAPI`. Can you make sure you are making any sdk calls inside the curly brackets:

```cpp
#include <aws/core/Aws.h>
int main(int argc, char** argv)
{
   Aws::SDKOptions options;
   Aws::InitAPI(options);
   {
      // make your SDK calls here.
   }
   Aws::ShutdownAPI(options);
   return 0;
}
```

**Comment by devtoolset** [comment]
Thanks @jmklix. I think I called Aws::InitAPI() before using AWS SDK.  Our service will stop if initialization fails and I call   Aws::InitAPI() in the initialization.
Also the above case may occur after our service that uses AWS KMS gets started and runs well for a uncertain period of time.

**Comment by devtoolset** [comment]
All the initialization works for my program and aws sdk are done only once.

**Comment by jmklix** [comment]
I haven't been able to reproduce this. Can you provide logs from when it is crashing? I know you said no errors are generated, but they might tell us what is happening right before the crash
