### ISSUE TITLE
SQS Unable to connect to endpoint

### ISSUE THREAD

**Issue by Alien2150** [aws/aws-sdk-cpp#241]
Hey, 

i am getting an "Unable to connect to endpoint" call. My Code simplified looks like this: 
https://gist.github.com/Alien2150/99e64b309f35e4b390baff06bea07b3a

I also tried accessing the queue using the queue-name and/or <id>/queue-name only

**Comment by Alien2150** [comment]
Nevermind. Found out that the error was caused when 0 messages are available in the queue. As soon as there are messages the return value will be different

**Comment by JonathanHenson** [comment]
If you are doing long polling, "Unable to connect to endpoint is most likely caused by a socket timeout. Can you try setting the socket timeouts on the client configuration to longer than 20 seconds?
