### ISSUE TITLE
Project README's Getting Help section links to a forum that no longer exists

### ISSUE THREAD

**Issue by laurie71** [aws/aws-sdk-cpp#2412]
### Describe the issue

The Getting Help section of the readme links to [AWS Discussion Forum for CPP](https://forums.aws.amazon.com/forum.jspa?forumID=245) which has been archived, and re-directs to re:Post. I couldn't find a suitable topic / discussion space there to suggest as an alternative link (or to use). The dead link should be removed or replaced with something appropriate.

### Links

https://github.com/aws/aws-sdk-cpp/blob/main/README.md

**Comment by jmklix** [comment]
Thanks for pointing this out. Created a PR to remove the old link.
