### ISSUE TITLE
Build error on Windows with zlib installed

### ISSUE THREAD

**Issue by alinaliBQ** [aws/aws-sdk-cpp#2425]
### Describe the bug

Cannot build with [zlib](https://gnuwin32.sourceforge.net/install.html) installed on Windows. The aws sdk finds the zlib and tries to build with it, but then it looks for `unistd.h` file which is a UNIX file and not available on Windows. aws sdk 1.9.220 does not have this issue. 

### Expected Behavior

Expect build successfully. 

### Current Behavior

Fail to build with error below. This is all the logs I have. Since I have uninstalled [zlib](https://gnuwin32.sourceforge.net/install.html), I'm unable to get more logs. 
```
    14>C:\Program Files (x86)\GnuWin32\include\zconf.h(289,12): fatal  error C1083: Cannot open include file: 'unistd.h
       ': No such file or directory (compiling source file C:\<path-to-repo>\build\aws-sdk\build\src\aws-cpp-sdk-core\ub_core.cpp) [C:\<path-to-repo>\build\aws-sdk\build\src\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
```

### Reproduction Steps

1. Install [zlib ](https://gnuwin32.sourceforge.net/install.html)on Windows
2. Build the aws sdk 1.11.48.
 - aws sdk finds ZLIB 
 ```
Found ZLIB: C:/Program Files (x86)/GnuWin32/lib/zlib.lib (found version "1.2.3")
```
4. Fail with error
```
    14>C:\Program Files (x86)\GnuWin32\include\zconf.h(289,12): fatal  error C1083: Cannot open include file: 'unistd.h
       ': No such file or directory (compiling source file C:\<path-to-repo>\build\aws-sdk\build\src\aws-cpp-sdk-core\ub_core.cpp) [C:\<path-to-repo>\build\aws-sdk\build\src\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
```

### Possible Solution

Only include `unistd.h` on UNIX platform and not Windows. 
```
#if !defined(OPENSSL_WINDOWS)
#include <unistd.h>
#endif
```

### AWS CPP SDK version used

1.11.48

### Compiler and Version used

3.23.22060601-MSVC_2

### Operating System and version

Windows 10

**Comment by TyrasNistru** [comment]
AFAIK, you can't use libraries from GnuWin with MSVC builds. They are not compatible with MSVC, since they will require libraries that are from a unix environment (such as GnuWin, MinGW, etc).

You need to use a MSVC-built version of zlib. I recommend trying VCPKG to get one

**Comment by jzakrzewski** [comment]
The error clearly states that it's the `zconf.h` from zlib that includes the `unistd.h`.

**Comment by alinaliBQ** [comment]
Okay, understood. Closing this ticket, thanks both for looking into this.
