### ISSUE TITLE
S3CrtClient fails when requesting a specific part number

### ISSUE THREAD

**Issue by neon64** [aws/aws-sdk-cpp#2428]
### Describe the bug

I believe that there's an issue where when requesting a specific part number, we don't want to use `AWS_S3_META_REQUEST_TYPE_GET_OBJECT` since there is only 1 request to make (i.e.: don't want to split the 1 request into multiple parallel requests).

In addition I think any range GetObject request returns HTTP 206 partial content, not HTTP 200 OK, so need to update the response handler to avoid spammy logs.

### Expected Behavior

Would expect that setting partNumber on the request should just work

### Current Behavior

Unfortunately I don't have the exact error message on hand right now, I can try and find it (& reproduce with latest SDK version) tomorrow.

Also get error-level logs even though no error really occurred:

```
S3CrtClient received error response for s3_meta_request with response code: 206
```

### Reproduction Steps

1. set part number on `GetObjectRequest` struct
2. call GetObjectAsync()

### Possible Solution

I had a local fork where the following changes sufficed to fix this:

https://github.com/aws/aws-sdk-cpp/compare/main...neon64:aws-sdk-cpp:s3-crt-individual-parts

I haven't put up a PR yet as I need to verify that this indeed works, and also would need to write tests etc.. for it.

### AWS CPP SDK version used

1.10

### Compiler and Version used

clang 13

### Operating System and version

CentOS 7

**Comment by jmklix** [comment]
> Unfortunately I don't have the exact error message on hand right now, I can try and find it (& reproduce with latest SDK version) tomorrow.

Did you have the exact error message? and can you include a minimal code sample?
