### ISSUE TITLE
GetLogLevelName does not support `Aws::Utils::Logging::LogLevel::Off` as parameter

### ISSUE THREAD

**Issue by alinaliBQ** [aws/aws-sdk-cpp#2436]
### Describe the bug

When calling `Aws::Utils::Logging::GetLogLevelName(Aws::Utils::Logging::LogLevel::Off)`, AWS SDK crashes and `abort()` is called because of `assert(0);`. 
Current implementation of `GetLogLevelName` can be found in [src/aws-cpp-sdk-core/source/utils/logging/LogLevel.cpp#L137](https://github.com/aws/aws-sdk-cpp/blob/e25d722/src/aws-cpp-sdk-core/source/utils/logging/LogLevel.cpp#L37). 

### Expected Behavior

Expect `Aws::Utils::Logging::GetLogLevelName(Aws::Utils::Logging::LogLevel::Off)` to return "OFF". 

### Current Behavior

With function call `Aws::Utils::Logging::GetLogLevelName(Aws::Utils::Logging::LogLevel::Off)`, the program crashes.

### Reproduction Steps

1. Call `Aws::Utils::Logging::GetLogLevelName(Aws::Utils::Logging::LogLevel::Off)`. 
- `#include <aws/core/utils/logging/LogLevel.h>` needs to be included as header.
2. The program crashes. 

### Possible Solution

Handle log level `Off`: Current implementation of `GetLogLevelName` can be found [here](https://github.com/aws/aws-sdk-cpp/blob/e25d722/src/aws-cpp-sdk-core/source/utils/logging/LogLevel.cpp#L37). 
```
Aws::String GetLogLevelName(LogLevel logLevel) 
{ 
	switch (logLevel)
	{
	case LogLevel::Fatal:
		return "FATAL";
	case LogLevel::Error:
		return "ERROR";
	case LogLevel::Warn:
		return "WARN";
	case LogLevel::Info:
		return "INFO";
	case LogLevel::Debug:
		return "DEBUG";
	case LogLevel::Trace:
		return "TRACE";
	case LogLevel::Off:
		return "OFF";
	default:
		assert(0);
		return "";
	}   
}
```

### Additional Information/Context

none

### AWS CPP SDK version used

1.11.48

### Compiler and Version used

3.23.22060601-MSVC_2

### Operating System and version

Windows 10

**Comment by jmklix** [comment]
Thanks for pointing this out. Pending PR merge

**Comment by alinaliBQ** [comment]
Thanks for merging this!
