### ISSUE TITLE
segfault in s3client constructor

### ISSUE THREAD

**Issue by sh22tan** [aws/aws-sdk-cpp#245]
I tried to use the s3 interface. Segfault presented when initialized an s3-client instance.

PC: @     0x7fb15599ed63 Aws::Utils::Crypto::CreateSha256Implementation()
*** SIGSEGV (@0x0) received by PID 28513 (TID 0x7fb0d2d33700) from PID 0; stack trace: ***
    @     0x7fb155e4c340 (unknown)
    @     0x7fb15599ed63 Aws::Utils::Crypto::CreateSha256Implementation()
    @     0x7fb15598381e Aws::Utils::Crypto::Sha256::Sha256()
    @     0x7fb155961be7 Aws::New<>()
    @     0x7fb15596136f _ZN3Aws10MakeUniqueINS_5Utils6Crypto6Sha256EJEEESt10unique_ptrIT_NS_7DeleterIS5_EEEPKcDpOT0_
    @     0x7fb15595de57 Aws::Client::AWSAuthV4Signer::AWSAuthV4Signer()
    @     0x7fb14d9848b7 __gnu_cxx::new_allocator<>::construct<>()
    @     0x7fb14d97e598 std::allocator_traits<>::_S_construct<>()
    @     0x7fb14d97a120 _ZNSt16allocator_traitsISaIN3Aws6Client15AWSAuthV4SignerEEE9constructIS2_JSt10shared_ptrINS0_4Auth28SimpleAWSCredentialsProviderEERPKcKSsRbbEEEDTcl12_S_constructfp_fp0_spcl7forwardIT0_Efp1_EEERS3_PT_DpOSF_
    @     0x7fb14d974266 std::_Sp_counted_ptr_inplace<>::_Sp_counted_ptr_inplace<>()
    @     0x7fb14d96dbd6 _ZN9__gnu_cxx13new_allocatorISt23_Sp_counted_ptr_inplaceIN3Aws6Client15AWSAuthV4SignerESaIS4_ELNS_12_Lock_policyE2EEE9constructIS7_JKS5_St10shared_ptrINS2_4Auth28SimpleAWSCredentialsProviderEERPKcKSsRbbEEEvPT_DpOT0_
    @     0x7fb14d9684f0 _ZNSt16allocator_traitsISaISt23_Sp_counted_ptr_inplaceIN3Aws6Client15AWSAuthV4SignerESaIS3_ELN9__gnu_cxx12_Lock_policyE2EEEE12_S_constructIS7_JKS4_St10shared_ptrINS1_4Auth28SimpleAWSCredentialsProviderEERPKcKSsRbbEEENSt9enable_ifIXsrNS9_18__construct_helperIT_JDpT0_EEE5valueEvE4typeERS8_PSN_DpOSO_
    @     0x7fb14d95ec64 _ZNSt16allocator_traitsISaISt23_Sp_counted_ptr_inplaceIN3Aws6Client15AWSAuthV4SignerESaIS3_ELN9__gnu_cxx12_Lock_policyE2EEEE9constructIS7_JKS4_St10shared_ptrINS1_4Auth28SimpleAWSCredentialsProviderEERPKcKSsRbbEEEDTcl12_S_constructfp_fp0_spcl7forwardIT0_Efp1_EEERS8_PT_DpOSL_
    @     0x7fb14d9527b8 _ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC2IN3Aws6Client15AWSAuthV4SignerESaIS6_EJSt10shared_ptrINS4_4Auth28SimpleAWSCredentialsProviderEERPKcKSsRbbEEESt19_Sp_make_shared_tagPT_RKT0_DpOT1_
    @     0x7fb14d93af05 _ZNSt12__shared_ptrIN3Aws6Client15AWSAuthV4SignerELN9__gnu_cxx12_Lock_policyE2EEC1ISaIS2_EJSt10shared_ptrINS0_4Auth28SimpleAWSCredentialsProviderEERPKcKSsRbbEEESt19_Sp_make_shared_tagRKT_DpOT0_
    @     0x7fb14d91943e std::shared_ptr<>::shared_ptr<>()
    @     0x7fb14d8f400c std::allocate_shared<>()
    @     0x7fb14d8d71bc Aws::MakeShared<>()
    @     0x7fb14d8c8cd6 Aws::S3::S3Client::S3Client()

Can anyone help to point out the issue ? Many thanks.

**Comment by sh22tan** [comment]
Solved by adding the global initialization.

Aws::SDKOptions options;
    Aws::InitAPI(options);

**Comment by projenix** [comment]
This does not solve it in my case on version 1.0.9
