### ISSUE TITLE
can't build on os x 10.9.5

### ISSUE THREAD

**Issue by pathcl** [aws/aws-sdk-cpp#246]
/usr/local/Library/Homebrew/shims/super/clang++ -std=c++11 -fno-exceptions -fPIC -Wall -Werror -pedantic -Wextra -Wno-unused-private-field -fno-exceptions -DNDEBUG -s -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/runCoreUnitTests.dir/RunTests.cpp.o CMakeFiles/runCoreUnitTests.dir/aws/RegionMapperTest.cpp.o CMakeFiles/runCoreUnitTests.dir/aws/auth/AWSCredentialsProviderTest.cpp.o CMakeFiles/runCoreUnitTests.dir/aws/client/AWSClientTest.cpp.o CMakeFiles/runCoreUnitTests.dir/aws/client/AWSErrorMashallerTest.cpp.o CMakeFiles/runCoreUnitTests.dir/aws/client/HttpSchemeMapperTest.cpp.o CMakeFiles/runCoreUnitTests.dir/http/HttpTypesMapperTest.cpp.o CMakeFiles/runCoreUnitTests.dir/http/URITest.cpp.o CMakeFiles/runCoreUnitTests.dir/utils/DateTimeTest.cpp.o CMakeFiles/runCoreUnitTests.dir/utils/EnumOverflowTest.cpp.o CMakeFiles/runCoreUnitTests.dir/utils/FileSystemUtilsTest.cpp.o CMakeFiles/runCoreUnitTests.dir/utils/GetTheLightsTest.cpp.o CMakeFiles/runCoreUnitTests.dir/utils/HashingUtilsTest.cpp.o CMakeFiles/runCoreUnitTests.dir/utils/OSVersionInfoTest.cpp.o CMakeFiles/runCoreUnitTests.dir/utils/StringUtilsTest.cpp.o CMakeFiles/runCoreUnitTests.dir/utils/crypto/CryptoStreamsTest.cpp.o CMakeFiles/runCoreUnitTests.dir/utils/crypto/SymmetricCiphersTest.cpp.o CMakeFiles/runCoreUnitTests.dir/utils/json/JsonSerializerTest.cpp.o CMakeFiles/runCoreUnitTests.dir/utils/xml/XmlSerializerTest.cpp.o CMakeFiles/runCoreUnitTests.dir/utils/logging/LoggingTest.cpp.o CMakeFiles/runCoreUnitTests.dir/utils/memory/MemoryTests.cpp.o CMakeFiles/runCoreUnitTests.dir/utils/ratelimiter/RateLimiterTests.cpp.o -o runCoreUnitTests ../aws-cpp-sdk-core/libaws-cpp-sdk-core.a ../testing-resources/libtesting-resources.a ../aws-cpp-sdk-core/libaws-cpp-sdk-core.a -lpthread
ld: internal error: atom not found in symbolIndex(__ZN7testing8internal10scoped_ptrINSt3__118basic_stringstreamIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEE5resetEPS8_) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [aws-cpp-sdk-core-tests/runCoreUnitTests] Error 1
make[2]: *** [aws-cpp-sdk-core-tests/CMakeFiles/runCoreUnitTests.dir/all] Error 2
make[1]: *** [all] Error 2

**Comment by bretambrose** [comment]
The referenced issue appears to be closed, so I'm guessing this is not an issue any longer.  Please reopen if you're still having trouble.
