### ISSUE TITLE
cmake: Clang 3.6 and USE_GCC_FLAGS sets invalid CXX flag -s

### ISSUE THREAD

**Issue by theopolis** [aws/aws-sdk-cpp#247]
`-s` is not available for Clang: https://github.com/aws/aws-sdk-cpp/blob/master/CMakeLists.txt#L880

**Comment by theopolis** [comment]
This is gated to `MINIMIZE_SIZE` too!

**Comment by bretambrose** [comment]
We should probably just remove that completely and let users pass in symbol strip cflags if they want.

**Comment by bretambrose** [comment]
This flag should no longer be present on clang-based builds.
