### ISSUE TITLE
[aws-cpp-sdk-s3-crt]: please expose existing aws-c-s3 CopyObject

### ISSUE THREAD

**Issue by grrtrr** [aws/aws-sdk-cpp#2477]
### Problem Description

The C++ SDK provides the `CopyObject[Async]` request for `s3` copy operations.
Despite the support for `CopyObject` in `aws-c-s3` since https://github.com/awslabs/aws-c-s3/pull/166, the `S3CrtClient` [is still using](https://github.com/aws/aws-sdk-cpp/blob/main/generated/src/aws-cpp-sdk-s3-crt/source/S3CrtClient.cpp#L708-L730) the `AWSXMLClient` for launching `CopyObject` requests.

This has the following problems:
1. The `AWSXMLClient` `CopyObject` request only supports copying of objects [< 5GB](https://docs.aws.amazon.com/AmazonS3/latest/userguide/copy-object.html).
2. Users thus have to re-implement most of the `aws-c-s3` `CopyObject` code (initial `HeadObject`, determine chunk size, parallel `UploadPartCopy` requests, and handling completion or abort of the multipart upload).
3. There is an existing issue #2103 with `AWSXMLClient` `CopyObject`, which [also affects](https://github.com/aws/aws-sdk-cpp/pull/2113/files) the CRT code.

### Proposed Solution

Please make the [existing `aws-c-s3` support for `CopyObject`](https://github.com/awslabs/aws-c-s3/blob/main/source/s3_copy_object.c) available as `CopyObjectAsync` and `CopyObject` in the `S3CrtClient`.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jmklix** [comment]
Looking into if we want to re-enable this.

**Comment by sbiscigl** [comment]
merged your change + our changes for code generation, it should be going out today! thanks for working with us on this
