### ISSUE TITLE
Access Violation aws-cpp-sdk-core.dll

### ISSUE THREAD

**Issue by kronus-lx** [aws/aws-sdk-cpp#2493]
### Describe the bug

Attempting to run a simple exe using the aws--sdk. Got a project in Visual Studio with .libs referenced in the linker and DLL present in the exe folder. The build is for x86 machines.

Exception is being thrown when attempting to initialize the API lined to aws-cpp-sdk-core.dll

### Expected Behavior

Successful build given minimal code and linked dependencies

### Current Behavior

Unhandled exception at 0x607FEF92 (aws-cpp-sdk-core.dll) in s3_store.exe: 0xC0000005: Access violation reading location 0xFFFFFFFF

### Reproduction Steps
```cpp
#include <iostream>
#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>

int main(int argc, char* argv[])
{
    Aws::SDKOptions options;

    Aws::InitAPI(options);
    {
        
    }
    Aws::ShutdownAPI(options);

    return 0;
}
```

### AWS CPP SDK version used

1.11.65

### Compiler and Version used

MSVC

### Operating System and version

Windows 10 64bit

**Comment by jmklix** [comment]
How did you install the c++ sdk? Did you possibly install it somewhere where you don't have permissions? Please include the steps you used to build this sdk

**Comment by kronus-lx** [comment]
> How did you install the c++ sdk? Did you possibly install it somewhere where you don't have permissions? Please include the steps you used to build this sdk

Thank you for your response.
I used the vcpkg package manager and installed the files in the default Windows x86 location on the PC's C:\ Drive.
I then copied the files to the default packages directory of my VS project and linked from there.

**Comment by jmklix** [comment]
Can you try compiling this sdk from the source rather than using vcpkg? You can do this with the following:

```cmake 
cmake .. -DBUILD_ONLY="s3crt" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="<path-to-install-sdk>" -DENABLE_TESTING=OFF
cmake --build . --config=Debug
cmake --install . --config=Debug
```
If you are still getting this error can you post your call stack?
