### ISSUE TITLE
C++14 support?

### ISSUE THREAD

**Issue by vinnyspb** [aws/aws-sdk-cpp#250]
Thanks for [adding ability to build SDK inside a project](https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/). The problem now is that it always adds `-std=c++11` flag (OSX) though my project uses C++14.

This flag is added after all others, so I can't override it with `add_definitions()` or `target_compile_options()`.

Any chance to make this flag optional or configurable?

**Comment by JonathanHenson** [comment]
Yes, we'll push out an update soon.

**Comment by JonathanHenson** [comment]
Updated in latest commit. We've added a new argument CPP_STANDARD. this defaults to 11, but you can set it to 14 or 17 if you like.
