### ISSUE TITLE
Invalid CRT Rule Engine state, CRT Endpoint rule engine is not initialized

### ISSUE THREAD

**Issue by aphage** [aws/aws-sdk-cpp#2508]
### Describe the bug

I encountered an error 'CRT Endpoint rule engine is not initialized' when using PutObject.

The environment is on a Linux embedded system, and the program will eventually load openssl 1.0 and openssl 1.1, I am not sure if this will have any impact.
[aws_sdk_2023-05-24-09.log](https://github.com/aws/aws-sdk-cpp/files/11550159/aws_sdk_2023-05-24-09.log)

### Expected Behavior

Successfully uploaded object.

### Current Behavior

Failed to upload object. Error message: 'CRT Endpoint rule engine is not initialized'

### Reproduction Steps

```c++

bool PutObject(const Aws::String &bucketName,
                           const Aws::String &keyName,
                           const Aws::String &fileName,
                           const Aws::Client::ClientConfiguration &clientConfig) {
    Aws::S3::S3Client s3_client(clientConfig);

    Aws::S3::Model::PutObjectRequest request;
    request.SetBucket(bucketName);
    //We are using the name of the file as the key for the object in the bucket.
    //However, this is just a string and can be set according to your retrieval needs.
    request.SetKey(keyName);

    std::shared_ptr<Aws::IOStream> inputData =
            Aws::MakeShared<Aws::FStream>("SampleAllocationTag",
                                          fileName.c_str(),
                                          std::ios_base::in | std::ios_base::binary);

    if (!*inputData) {
        std::cerr << "Error unable to read file " << fileName << std::endl;
        return false;
    }

    request.SetBody(inputData);

    Aws::S3::Model::PutObjectOutcome outcome =
            s3_client.PutObject(request);

    if (!outcome.IsSuccess()) {
        std::cerr << "Error: PutObject: " <<
                  outcome.GetError().GetMessage() << std::endl;
    }
    else {
        std::cout << "Added object '" << fileName << "' to bucket '"
                  << bucketName << "'.";
    }

    return outcome.IsSuccess();
}

int main(int argc, char** argv)
{
    setenv("AWS_ACCESS_KEY_ID", "MY_KEY_ID", 1);
    setenv("AWS_SECRET_ACCESS_KEY", "MY_KEY", 1);
    
    Aws::SDKOptions options;

    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
    Aws::InitAPI(options);
    {
        Aws::Client::ClientConfiguration clientConfig;
        clientConfig.verifySSL = false;
        clientConfig.endpointOverride = "https://";

        PutObject("ajm", "test.txt", "./test.txt", clientConfig);
    }
    Aws::ShutdownAPI(options);

    return 0;
}
```

### AWS CPP SDK version used

1.11.82

### Compiler and Version used

aarch64-buildroot-linux-gnu-gcc.br_real (Buildroot 2018.02-rc3-g4f000a0) 6.4.0

### Operating System and version

Linux/4.4.154

**Comment by yasminetalby** [comment]
Hello @aphage ,

Thank you very much for your submission.
Could you please let me know how you have installed the C++ SDK?

Would it be possible that you are using different versions of the SDK concurrently?

Best,

Yasmine

**Comment by yasminetalby** [comment]
Hello @aphage ,

A few additional points:
1. Is this the actual syntax `clientConfig.endpointOverride = "https://";` or did you redact out the endpoint? If you have redacted out the endpoint could you give an example a little more complete of the syntax being used?
2. From the log, it seems that you are not specifying the region which is a requirement when using the c++ sdk. You can do so in your code sample by adding  `clientConfig.region = "us-east-1";`  (note: us-east-1 is an example and can be replaced by the region of your choice).

Thank you very much for your time and collaboration.

Sincerely,

Yasmine

**Comment by aphage** [comment]
> 

No, I only compiled one version.

**Comment by aphage** [comment]
> Hello @aphage ,
> 
> A few additional points:
> 
> 1. Is this the actual syntax `clientConfig.endpointOverride = "https://";` or did you redact out the endpoint? If you have redacted out the endpoint could you give an example a little more complete of the syntax being used?
> 2. From the log, it seems that you are not specifying the region which is a requirement when using the c++ sdk. You can do so in your code sample by adding  `clientConfig.region = "us-east-1";`  (note: us-east-1 is an example and can be replaced by the region of your choice).
> 
> Thank you very much for your time and collaboration.
> 
> Sincerely,
> 
> Yasmine

Yes, I modified the endpoint and used the default region. Strangely, it runs without any issues on the X86 host, and the CRT Rule Engine initialization failure does not occur. I would like to know the conditions for initializing the CRT Rule Engine so that I can investigate where the issue may lie.

**Comment by aphage** [comment]
> Hello @aphage ,
> 
> Thank you very much for your submission. Could you please let me know how you have installed the C++ SDK?
> 
> Would it be possible that you are using different versions of the SDK concurrently?
> 
> Best,
> 
> Yasmine

No, I only compiled one version.

**Comment by yasminetalby** [comment]
Hello @aphage ,

Thank you very much for your answer.

If you are properly Initializing and Shutting Down the SDK and are using the same SDK version you shouldn't encounter any issue initializing the CRT Rule Engine. 

Based on the behavior you are describing, the issue seems to be dependent on your installation of the SDK. 

Best,

Yasmine
