### ISSUE TITLE
Cannot connect to S3 endpoint using HTTPS on Android (Curl error code 60)

### ISSUE THREAD

**Issue by renatoaf** [aws/aws-sdk-cpp#251]
Hello,

I'm trying to integrate aws-sdk (most recent version) with a cocos2d-x based-game and I'm having some trouble on Android (haven't tried it on iOS yet).

I've managed to successfully build it with the following settings (android STL, ABI and API Level are the same I use for my application). Android NDK is android-ndk-r11c.

_cmake -G "Unix Makefiles" -DTARGET_ARCH=ANDROID -DSTATIC_LINKING=1 -DANDROID_NATIVE_API_LEVEL=android-21 -DANDROID_STL=gnustl_static -DBUILD_ONLY="s3" -DANDROID_ABI=armeabi-v7a -DENABLE_TESTING=OFF -DBUILD_SHARED_LIBS=OFF -DFORCE_SHARED_CRT=OFF_

However, when I try to use HTTPS as http scheme, I cannot connect to the server. Here is the trace from AWS SDK:

D/cocos2d-x debug info(29924): #### [DEBUG] 2016-08-01 13:42:30 CurlHandleContainer [-1346033664] Attempting to acquire curl connection.
D/cocos2d-x debug info(29924): 
D/cocos2d-x debug info(29924): #### [DEBUG] 2016-08-01 13:42:30 CurlHandleContainer [-1346033664] Returning connection handle 0x9d9d4000
D/cocos2d-x debug info(29924): 
D/cocos2d-x debug info(29924): #### [DEBUG] 2016-08-01 13:42:30 CurlHttpClient [-1346033664] Obtained connection handle 0x9d9d4000
D/cocos2d-x debug info(29924): 
**D/cocos2d-x debug info(29924): #### [ERROR] 2016-08-01 13:42:31 CurlHttpClient [-1346033664] Curl returned error code 60**
D/cocos2d-x debug info(29924): 
D/cocos2d-x debug info(29924): #### [DEBUG] 2016-08-01 13:42:31 CurlHandleContainer [-1346033664] Releasing curl handle 0x9d9d4000

(After some retries, it results in a "Unable to connect to endpoint" error)

If I use HTTP or set **verifySSL** to _false_, everything works as expected.

As it appears to be a problem with SSL certificates, I also tried forcing "cacert.pem" into my app and setting **caPath** on ClientConfiguration, but it seems this is not so simple for Android since libcurl requires an absolute path for the directory.

Am I missing something here? Should I install any AWS certificates separately?

Thanks.

PS: this is the piece of code I'm using to debug the problem.

```
    Aws::Client::ClientConfiguration config;
    config.region = Aws::Region::US_EAST_1;
    config.scheme = Aws::Http::Scheme::HTTPS;
    config.connectTimeoutMs = 60000;
    config.requestTimeoutMs = 60000;

    Aws::S3::Model::GetObjectRequest request;
    request.WithBucket(<BUCKET>).WithKey(<KEY>);

    auto client = Aws::MakeShared<Aws::S3::S3Client>(ALLOCATION_TAG, Aws::Auth::AWSCredentials(<ACCESS_KEY>, <SECRET_KEY>), config);

    auto outcome = client->GetObject(request);    
    if (outcome.IsSuccess())
    {
        CCLOG("### :):)");
    } else {
        CCLOG("### :(:( outcome: %d %s %s", outcome.GetError().GetErrorType(), outcome.GetError().GetExceptionName().c_str(), outcome.GetError().GetMessage().c_str());
    }
```

**Comment by bretambrose** [comment]
The emulator is missing certs to validate SSL connections to AWS services (no idea whether actual devices suffer from the same problem).  Internally, we get around this by uploading a known good cert set underneath the app; if it's of any help, take a look at  BuildAndInstallCertSet in android-build/build_and_test_android.py.  If you do something similar, you should get working TLS-enabled calls.  You will need to use the caPath option of course.  

We hard-code an absolute path for the tests and it doesn't sound like you have that luxury on a real device.  There are ways of getting your app's base directory (see InitCacheDirectory for an example, I believe) so perhaps you could base your solution on that.

**Comment by renatoaf** [comment]
Thanks, I will check it out asap.

The same problem occurs on iOS version of the game. Is there any chance the problem is related with the build process? Any libcurl configuration during cmake that may have failed?

**Comment by bretambrose** [comment]
Curl and cmake aren't well-supported together as far as I know, but I haven't seen other problems.  We can look into providing a certset hook (probably just forward to curl config's --with-ca-bundle) when the curl build gets configured.

**Comment by renatoaf** [comment]
I've lost a few hours trying to use "caPath" property with no result. Not sure why, but I kept receiving curl 60 error with debugging messages indicating that it was unable to get local issuer certificate. I tried setting different directory paths, each of them with [AWS cacert.pem](https://github.com/amazonwebservices/aws-sdk-for-php/blob/master/lib/requestcore/cacert.pem), rehashed by c_rehash tool or not, but none of the combinations I tried worked for Android or iOS.

I only managed to solve the problem by modifying the SDK to include CURLOPT_CAINFO  (--cacert option) support. By pointing CURLOPT_CAINFO to cacert.pem it worked instantly for iOS and Android. Can you consider adding support to a "caFile" on Aws::Client::ClientConfiguration (besides CURLOPT_CAPATH)? I think it's much more straightforward than CURLOPT_CAPATH, especially for Android that we have to embed the certificates and copy it to a directory with appropriate permissions during runtime.

p.s. I've sent a merge request with minor changes to support --cacert option. Not sure if it will be included in the SDK, but in case anyone faces the same problem, here it is: https://github.com/aws/aws-sdk-cpp/pull/274

**Comment by JonathanHenson** [comment]
we need to just go ahead and add the caFile to the client config. I'm prioritizing this fix and we'll get it out as soon as possible.
