### ISSUE TITLE
aws-cpp-sdk does not support IPv6 type address for S3 endpoint

### ISSUE THREAD

**Issue by kv83821-yb** [aws/aws-sdk-cpp#2525]
### Describe the bug

Background: I am using MinIO( S3 compatible storage ). The address for endpoint is in IPv6 format:
`https://[[240b:c0e0:102:553e:b4c2:2::]]:3000` 
This does not work. Error message: `Invalid DNS Label found in URI host`
 However when I use the DNS name for it: `uhn7klr2crbct001.rmnkiba.local` the functionality works as expected.

### Expected Behavior

The sdk should work with IPv6 type addresses.

### Current Behavior

Using IPv6 address for S3 endpoint, like:
`https://[[240b:c0e0:102:553e:b4c2:2::]]:3000` 
Throws error message:
`Invalid DNS Label found in URI host`

### Reproduction Steps

Any IPv6 address used as S3 endpoint.

### AWS CPP SDK version used

1.9.220

### Compiler and Version used

gcc (GCC) 4.8.5 20150623

### Operating System and version

Linux 3.10.0-1160.31.1.el7.x86_64

**Comment by yasminetalby** [comment]
Hello @kv83821-yb ,

Thank you very much for your submission.
Unfortunately the behavior you are experiencing is expected as the aws-cpp-sdk does not offer support for IPv6 address in S3. 
There is a feature-request open here for [IPv6 address support in S3](https://github.com/aws/aws-sdk-cpp/issues/1857). You can add a thumbs up or a comment to it to showcase your interest in this feature which will help us with feature-request prioritization.

I will also bring this up for discussion with the team.

If that is ok with you, I will close this issue as a duplicate and invite you to follow status update for this feature in #1857 to prevent duplicate submission.

Thank you very much again for your submission, your feedback is extremely valuable to our team.

Best regards,

Yasmine
