### ISSUE TITLE
cmake on ubuntu 20.04 fails to find include files resolve_platform and initialize_project_version

### ISSUE THREAD

**Issue by carl** [aws/aws-sdk-cpp#2550]
### Describe the bug

I am following the directions in the README for Auto Make build systems on ubuntu 20.04 on tag 1.11.105, and get errors running cmake

### Expected Behavior

cmake should work

### Current Behavior

Errors when running cmake:

```
CMake Error at CMakeLists.txt:126 (include):
  include could not find requested file:

    resolve_platform

CMake Error at CMakeLists.txt:144 (include):
  include could not find requested file:

    initialize_project_version

-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:156 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
CMake Error at cmake/build_external.cmake:139 (message):
  Failed to configure dependency libraries.
Call Stack (most recent call first):
  CMakeLists.txt:198 (include)
  ```
  
It can't find the files to include `resolve_platform` and `initialize_project_version` and I can't find them in the repo either, are they missing or is some external dependency?

### Reproduction Steps

cmake <path-to-root-of-this-source-code> -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=<path-to-install>

### Additional Information/Context

cmake version 3.26.4

### AWS CPP SDK version used

1.11.105

### Compiler and Version used

gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

### Operating System and version

Ubuntu 20.04

**Comment by yasminetalby** [comment]
Hello @carl ,

Thank you very much for your message. 

You can find the file [resolve_platform.cmake](https://github.com/aws/aws-sdk-cpp/blob/main/cmake/resolve_platform.cmake) and [initialize_project_version.cmake](https://github.com/aws/aws-sdk-cpp/blob/main/cmake/initialize_project_version.cmake) in [aws-sdk-cpp
/cmake/](https://github.com/aws/aws-sdk-cpp/tree/main/cmake).

Could double check if these files are present within your directory?

Best,

Yasmine

**Comment by carl** [comment]
Yes the files are present. Why can't it find them when running cmake is the question?

**Comment by carl** [comment]
Ok I got past that, but now getting this:

```
-- Encryption: LibCrypto
CMake Error at /usr/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find crypto (missing: crypto_LIBRARY crypto_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/Findcrypto.cmake:71 (find_package_handle_standard_args)
  cmake/external_dependencies.cmake:50 (find_package)
  CMakeLists.txt:197 (include)


-- Configuring incomplete, errors occurred!
CMake Error at cmake/build_external.cmake:139 (message):
  Failed to configure dependency libraries.
Call Stack (most recent call first):
  CMakeLists.txt:198 (include)
  ```
  I've tried adding ` -Dcrypto_INCLUDE_DIR=/usr/include/openssl` to the command line, and ` -DOPENSSL_ROOT_DIR=/usr/include/openssl` or  `-DOPENSSL_ROOT_DIR=/usr/lib/ssl`

**Comment by yasminetalby** [comment]
Hello @carl ,

Did you complete the Additional Requirements for Linux Systems prior to attempting to build the SDK? ([see](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup-linux.html))

Best,

Yasmine
