### ISSUE TITLE
Comprehensive option to disable -Werror or respect CXXFLAGS

### ISSUE THREAD

**Issue by ihnorton** [aws/aws-sdk-cpp#2555]
### Describe the bug

As far as I can tell, aws-sdk-cpp does not currently provide a way to disable [setting `-Werror`](https://github.com/aws/aws-sdk-cpp/blob/4880fa91f67a8ca55b1c126efe02b8a2facefe55/cmake/compiler_settings.cmake#L56), although some dependencies do (https://github.com/awslabs/aws-c-common/blob/1778c799be82fde844a02e27d59c5a30a1489e90/cmake/AwsCFlags.cmake#L12).

Please introduce a similar option to either disable `-Werror`, or to force cmake to respect `CXXFLAGS` and `CFLAGS` by not post-pending `-Werror`.

### Expected Behavior

Don't set `-Werror` unconditionally.

### Current Behavior

Builds fail when new compiler versions are released with different safety checks. There are many examples in the issue tracker. It takes time to get these fixed _and released_ across all downstream packages, so an escape-hatch is necessary.

### Reproduction Steps

n/a please see many prior issues in this repo

### AWS CPP SDK version used

n/a

### Compiler and Version used

gcc 12, but happens with other compilers

### Operating System and version

Debian 12

**Comment by sbiscigl** [comment]
Added `AWS_SDK_WARNINGS_ARE_ERRORS` as a cmake arg that defaults to on that you can escape hatch out of it if desired. give a shout if you have any questions or suggestions, thanks for the feedback!
