### ISSUE TITLE
Aws::ShutdownAPI() now SEGVs when called twice

### ISSUE THREAD

**Issue by hunjmes** [aws/aws-sdk-cpp#2568]
### Describe the bug

After https://github.com/aws/aws-sdk-cpp/pull/2515 , calling `Aws::ShutdownAPI()` twice, within the same process causes a SEGV. This is because the function calls function `Aws::Utils::ComponentRegistry::TerminateAllComponents()`, which dereferences pointer field `s_registry`; and then calls function `Aws::Utils::ComponentRegistry::ShutdownComponentRegistry()`, which `delete`s that field and sets it to `nullptr`.

### Expected Behavior

Good C coding practice is that calling a shutdown / cleanup / etc. API should be idempotent, so that calling the same API twice results in a no-op, the second time -- rather than crashing.

### Current Behavior

The `Aws::ShutdownAPI()` function crashes on the second call.

### Reproduction Steps

Sample code like:
```
Aws::SDKOptions options;
Aws::InitAPI(options);

Aws::ShutdownAPI(options);
Aws::ShutdownAPI(options); // will crash with SEGV
```

### Possible Solution

Rewrite function `ComponentRegistry::TerminateAllComponents()` as:
```
void TerminateAllComponents()
{
    std::unique_lock<std::mutex> lock(s_registryMutex);

    // BEGIN BUG FIX.
    if (!s_registry) {
        // Registry already shut down -- nothing to do.
        return;
    }
    // END BUG FIX.

    for(const auto it : *s_registry)
    {
        if (it.second.TerminateFn) {
            it.second.TerminateFn(it.first, -1);
        }
    }
    s_registry->clear();
}
```

### AWS CPP SDK version used

`main`

### Compiler and Version used

n/a

### Operating System and version

n/a

**Comment by jmklix** [comment]
Thanks for pointing this out and taking the time to make the PR. The PR is being review/tested internally and will be merged once everything looks good.
