### ISSUE TITLE
How am I supposed to use this thing ?

### ISSUE THREAD

**Issue by ghost** [aws/aws-sdk-cpp#257]
Hello, does this library come wtih any hidden documentation for human users ?

The examples are quite vague and they force me to crawl thought the library to figure out what namespace things use, finding out.

E.g.:

Aws::S3::S3Client s3Client;
GetObjectRequest getObjectRequest;

Includes the namespace for S3Client put doesn't tell you GetObjectRequest is found in:

Aws::S3::Model::

.... I'm still unable to figure out what a "Scheme::HTTP" is or where can I find one.

Is there any full features examples with all the includes and code instead of "..." ?

I just want to download some files and due to a twist of fate I can't use s3cmd.... but using this library seems quite impossible.

**Comment by DraconPern** [comment]
Look in aws-cpp-sdk-transfer-tests to see how to do all kinds calls.

**Comment by toneill818** [comment]
@FlavouredGeorge  The transfer client makes it easy to download and upload files using S3. [Here](https://gist.github.com/toneill818/d90c85a453d935e7e9aed6eab1d75f8a) is an example of downloading and uploading files to S3. As @DraconPern mentioned more examples can be found in the test files.

**Comment by JonathanHenson** [comment]
You may feel me the developer blog to be helpful. 
https://aws.amazon.com/blogs/developer/category/cpp/
Also, the autogenerated docs can be found at
http://sdk.amazonaws.com/cpp/api

**Comment by FlavouredGeorge** [comment]
Currently I am getting an error called:

"NoSuchBucket
The specified bucket does not exist:"

despite being able to list and access the exact same bucket with s3cmd... 
It might be from missing configurations (e.g. I don't give the client the region anywhere)

Should i add extra configurations in ~/.aws/credentials ? Is there a different config files aws looks up ?

Also thank you @toneill818 for the example, much better and more concise then the "test" ones

**Comment by JonathanHenson** [comment]
If you are on Windows, have you tried using NuGet? We just discovered this morning that we broke the CMake export functionality in a recent refactor and will be pushing an update for that later today or this week.

**Comment by FlavouredGeorge** [comment]
I am not... 

Can a 'broken' CMake export functionality result in run-time download "errors" ? I assumed they just came from not having a properly configured .aws/credentials or .aws/config... since I can find no guidelines on how to actually configure them in order to properly work with this library.

**Comment by JonathanHenson** [comment]
Are you still having issues configuring your credentials file? It follows the same format as all of the other SDKs. This blog post may be helpful: https://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs
