### ISSUE TITLE
Apparent inability to use library with Windows GUI applications

### ISSUE THREAD

**Issue by hthompson6** [aws/aws-sdk-cpp#2573]
### Describe the bug

Due to the decision made in this thread https://github.com/aws/aws-sdk-cpp/issues/402, this line https://github.com/aws/aws-sdk-cpp/blob/main/src/aws-cpp-sdk-core/include/aws/core/client/AWSError.h#L16 was added.

The addition of this line means that one ostensibly cannot use this SDK with Windows GUI applications as it not only breaks the main GetMessage found in most apps but also others invoked in the ATL libraries.

### Expected Behavior

I'd expect that both libraries were compatible.

### Current Behavior

They are not compatible.

### Reproduction Steps

Use the AWS SDK and Windows GUI.

### Possible Solution

Rename the AWSError.h method

### Additional Information/Context

I'd love a work around for this if anyone has one.

### AWS CPP SDK version used

1.11.117

### Compiler and Version used

Visual Studio

### Operating System and version

Windows 11 Pro

**Comment by jmklix** [comment]
Looking into possible work arounds for this that will allow compatibility of Windows GUI applications and this sdk

**Comment by jmklix** [comment]
I have made a PR with a possible fix for this issue. Testing it to make sure it works without breaking anything else

**Comment by hthompson6** [comment]
Awesome thank you!
