### ISSUE TITLE
AWS SDK appears to clobber libcurl when used with libcurl 

### ISSUE THREAD

**Issue by dhudson1** [aws/aws-sdk-cpp#2574]
### Describe the bug

Running `libcurl` in the same executable as an `aws-sdk-cpp` library is called causes the `libcurl` request to fail with the following error message (when `libcurl` is set to the verbose logging with `curl_easy_setopt(_curl, CURLOPT_VERBOSE, 1L);`):
```
* STATE: INIT => CONNECT handle 0x556823ce86f8; line 1789 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => RESOLVING handle 0x556823ce86f8; line 1835 (connection #0)
* family0 == v4, family1 == v6
*   Trying ***.***.***.***:443...
* STATE: RESOLVING => CONNECTING handle 0x556823ce86f8; line 1917 (connection #0)
* Connected to ************** (***.***.***.***) port 443 (#0)
* STATE: CONNECTING => PROTOCONNECT handle 0x556823ce86f8; line 1980 (connection #0)
* SSL: couldn't create a context: error:0A0C0100:SSL routines::malloc failure
* multi_done
* The cache now contains 0 members
* Closing connection 0
* Expire cleared (transfer 0x556823ce86f8)
*
```

I am using `aws-sdk-cpp` library to get SSM parameters and Secrets Manager Secrets for a cognito instance, and then using the `libcurl` to directly acquire the access tokens for the service principal.

When hard-coding these credentials to test, `libcurl` proceeds as expected and returns the credentials.

**Note**: Attempted to build on `vcpkg` with latest 1.11 `aws-sdk-cpp` version, but the `CMake` build fails.

### Expected Behavior

I expected the `libcurl` request to proceed without issue from creating an SSL Context, and if it were to fail, for it to be related to the usual REST failure modes (incorrect URL, bad parameters, etc.) or for it to succeed. 

### Current Behavior

`libcurl` outright fails, and complains that the program is out of memory, because the SSL context failed to create.

### Reproduction Steps

Set up `curl_global_setup`, run any aws-sdk-cpp library SSM or Secrets Manager code (including the `Aws::InitAPI` and `Aws::ShutdownAPI`), then run a curl request with `curl_easy_perform` (and required setup).

An example repository that builds using `cmake` and `vcpkg`, which includes a `README.md` to help with building and demonstrating the issue. 

### Possible Solution

This could be a result of multiple `curl_global_cleanup` commands that are not desirable, as indicated in [this ticket](https://github.com/aws/aws-sdk-cpp/issues/2538).

### Additional Information/Context

This package (`aws-sdk-cpp`), as are `libcurl`, `openssl`, and the other packages in this larger project, are all built and installed by using [vcpkg](https://github.com/microsoft/vcpkg).

### AWS CPP SDK version used

1.9.220#2

### Compiler and Version used

gcc (Debian 10.2.1-6) 10.2.1 20210110

### Operating System and version

6.1.0-0.deb11.7-cloud-amd64

**Comment by jmklix** [comment]
Can you provide slightly more detailed repro steps? How are you setting up `curl_global_setup`? and a code snippet for how you make the curl request?
