### ISSUE TITLE
TransferClient.GetFailure() returns blank string if region is not correct.

### ISSUE THREAD

**Issue by DraconPern** [aws/aws-sdk-cpp#258]
I had a bucket that was in the west coast.  Using the default region of US_EAST_1, even though the operation failed (IsDone == true, CompletedSuccessfully == false), the function GetFailure returned a blank error string. Other errors such as invalid credentials returned relevant error messages.  If I change the bucket to something in US_EAST_1, code works correctly.  This is on VS2013 aka 12

**Comment by singku** [comment]
@DraconPern Are you still facing this problem? Our code updated a lot since you were asking.

**Comment by DraconPern** [comment]
Thanks for the follow up!  I worked around the issue by manually specifying the bucket region, I am using KMS now anyways so I need to specify the region regardless.  I am not sure if this bug is still present however.
