### ISSUE TITLE
Compilation Failure on macOS Catalina

### ISSUE THREAD

**Issue by mdavis-coder** [aws/aws-sdk-cpp#2581]
### Describe the bug

The SDK doesn't build out of the box on Catalina.

The source file, aws-sdk-cpp/src/aws-cpp-sdk-core/source/utils/component-registry/ComponentRegistry.cpp, fails to compile.

### Expected Behavior

The compilation should not fail with:

cmake -DBUILD_ONLY="s3" -DBUILD_SHARED_LIBS=OFF

### Current Behavior
```

[ 66%] Building CXX object src/aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/ub_core.cpp.o
In file included from /Users/mdavis/workspace/aws/aws-sdk-cpp/src/aws-cpp-sdk-core/ub_core.cpp:55:
/Users/mdavis/workspace/aws/aws-sdk-cpp/src/aws-cpp-sdk-core/source/utils/component-registry/ComponentRegistry.cpp:88:32: error: 
      loop variable 'it' of type 'const std::__1::pair<void *const,
      Aws::Utils::ComponentRegistry::ComponentDescriptor>' creates a copy from type 'const std::__1::pair<void
      *const, Aws::Utils::ComponentRegistry::ComponentDescriptor>' [-Werror,-Wrange-loop-analysis]
                for(const auto it : *s_registry)
                               ^
/Users/mdavis/workspace/aws/aws-sdk-cpp/src/aws-cpp-sdk-core/source/utils/component-registry/ComponentRegistry.cpp:88:21: note: 
      use reference type 'const std::__1::pair<void *const, Aws::Utils::ComponentRegistry::ComponentDescriptor> &'
      to prevent copying
                for(const auto it : *s_registry)
                    ^~~~~~~~~~~~~~~
                               &
1 error generated.
make[2]: *** [src/aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/ub_core.cpp.o] Error 1
make[1]: *** [src/aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/all] Error 2
make: *** [all] Error 2
```

### Reproduction Steps

macOS 10.15.7 (Intel)

Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

### Possible Solution

The value of the for loop should use a reference and not make a copy:

                for(const auto& it : *s_registry)
                {
                    if (it.second.TerminateFn) {
                        it.second.TerminateFn(it.first, -1);
                    }
                }

### AWS CPP SDK version used

a4fccfa1924403f077c5281585f3afa88acbca94

### Compiler and Version used

Apple clang version 12.0.0 (clang-1200.0.32.29)

### Operating System and version

macOS 10.15.7

**Comment by yasminetalby** [comment]
Hello @mdavis-coder ,

Thank you very much for your submission. I am unable to reproduce this behavior but from a first glance, this seems to be an issue with your environment. Could you please provide all your set up and building steps?

As a side note, as documented in the readme if you would like to build with macOS - Xcode:
```
cmake <path-to-root-of-this-source-code> -G Xcode -DTARGET_ARCH="APPLE" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=<path-to-install>
xcodebuild -target ALL_BUILD

```

Thank you very much for your time and collaboration.

Sincerely,

Yasmine

**Comment by sbiscigl** [comment]
This should be release, give a shout if you see anymore errors
