### ISSUE TITLE
smithy/tracing/TraceSpan.h conflicts with wingdi.h

### ISSUE THREAD

**Issue by ShimYama** [aws/aws-sdk-cpp#2590]
### Describe the bug

The enum value `smithy::components::tracing::TraceSpanStatus::ERROR` conflicts with `ERROR` macro in wingdi.h

### Expected Behavior

No conflict occurs.

### Current Behavior

C2059, C3805 error occurs.

### Reproduction Steps

Make a project with wingdi.h header file and build it, the you will find the error.

### Possible Solution

Adding these lines in TraceSpan.h may help but I'm not sure there's any subeffects.
``` c++
#ifdef _WIN32
#ifdef ERROR
#undef ERROR
#endif
#endif
```

### AWS CPP SDK version used

1.11.123

### Compiler and Version used

Visual Studio 2015 Community / Build Engine version 14.0.25420.1

### Operating System and version

Windows 10 Pro 22H2

**Comment by yasminetalby** [comment]
This should be fixed in [1.11.152](https://github.com/aws/aws-sdk-cpp/releases/tag/1.11.152)!

Thank you very much for reporting this issue.

Best,

Yasmine
