### ISSUE TITLE
Aws::Client::AWSAuthV4Signer::GenerateSignature declared but not defined

### ISSUE THREAD

**Issue by vaci** [aws/aws-sdk-cpp#2599]
### Describe the bug

Class Aws::Client::AWSAuthV4Signer declares a public method:

https://github.com/aws/aws-sdk-cpp/blob/main/src/aws-cpp-sdk-core/include/aws/core/auth/signer/AWSAuthV4Signer.h#L168
```
Aws::String GenerateSignature(const Aws::Auth::AWSCredentials& credentials,
  const Aws::String& stringToSign, const Aws::String& simpleDate) const;
```
... but this method is not defined

The only overloads of GenerateSignature that are defined in the source code are both private methods of AWSAuthV4Signer:

https://github.com/aws/aws-sdk-cpp/blob/main/src/aws-cpp-sdk-core/source/auth/signer/AWSAuthV4Signer.cpp#L469C1-L477C1
```
Aws::String AWSAuthV4Signer::GenerateSignature(const AWSCredentials& credentials, const Aws::String& stringToSign,
        const Aws::String& simpleDate, const Aws::String& region, const Aws::String& serviceName) const;

Aws::String AWSAuthV4Signer::GenerateSignature(const Aws::String& stringToSign, const ByteBuffer& key) const;
```

### Expected Behavior

I expect to be able to link against the public method.

### Current Behavior

Program fails to link against missing symbol.

```
s3-test.o: in function `S3Test_ListBuckets_Test::TestBody()':
    s3-test.cpp:307: undefined reference to `Aws::Client::AWSAuthV4Signer::GenerateSignature(Aws::Auth::AWSCredentials const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
    collect2: error: ld returned 1 exit status
```

### Reproduction Steps

int main() {    
  Aws::SDKOptions awsOptions{};
  Aws::InitAPI(awsOptions);

  auto credsProvider = std::make_shared<Aws::Auth::DefaultAWSCredentialsProviderChain>();
  auto creds = credsProvider->GetAWSCredentials();
  auto signer = Aws::Client::AWSAuthV4Signer{credsProvider, "s3", "us-east-1"};
  signer.GenerateSignature(creds, "", "");
}

### AWS CPP SDK version used

1.11.37

### Compiler and Version used

gcc (GCC) 12.2.0

### Operating System and version

Linux 5.15.0-75

**Comment by sbiscigl** [comment]
took a look this and was able to reproduce, will look into pushing out a fix asap

**Comment by sbiscigl** [comment]
merged, is available from HEAD and will be tagged in a release tomorrow. Resolving, give a shout if you have any questions.
