### ISSUE TITLE
Compilation failure on RHEL8.6

### ISSUE THREAD

**Issue by kavitha123408** [aws/aws-sdk-cpp#2620]
### Describe the bug

In latest AWS CPP SDK, we are getting compilation error for  utils/Array.h ..  error states that "call of overloaded unique_ptr(int) is ambiguous "

Whether this SDK is compatible with RHEL8.6 version?  We are compiling SDK on RHEL8.6 OS. Current version downloaded is 1.11.132

If not what is compatible SDK version for RHEL8.6 OS?

### Expected Behavior

There should not be any compilation issues.

### Current Behavior

Compilation is failing with errors.

### Reproduction Steps

compile latest CPP SDK on RHEL8.6 OS.

### AWS CPP SDK version used

1.11.132

### Compiler and Version used

GCC 8.5.0

### Operating System and version

RHEL8.6

**Comment by yasminetalby** [comment]
Hello @kavitha123408 ,

Thank you very much for your submission. 
Could you please provide the full error message received? 

Best regards,

Yasmine

**Comment by kavitha123408** [comment]
Error message 
aws/core/utils/Array.h:61:31 call of overloaded 'unique_ptr(int)' is ambiguous m_data(nullptr)

this compilation went fine in RHEL7.9 , It is throwing error in RHEL8.6

**Comment by yasminetalby** [comment]
Hello @kavitha123408 ,

Thank you very much for your answer. 
Could you please provide some more information:
- From which cpp is the utils/Array.h file included from?
- Have you made any changes in how you are compiling the code/could you provide detailed repro steps so we can attempt to reproduce your use case and see if we can see a similar change in behavior between the 2 OS versions?

Thank you very much for your time and collaboration.

Sincerely,

Yasmine

**Comment by kavitha123408** [comment]
Hello,

Array.h has called from <crypto/Factories.h>

It happens at instantiating of "AWS::Utils::Array<T>Array(const T*,size_t) [ with T= unsgned char;size_t= long unsigned int]

Error is throwing exactly at create new array and initialize it to a raw array. We tried to comment out //m_data(nullptr) and used m_data.reset(nullptr) inside the constructor instead of constructor default variable, This fix went fine .

**Comment by jmklix** [comment]
Are you still running into this build error? I can't seem to reproduce it while trying to build on RHEL with the latest version of the sdk. Here is how I built the sdk:
```sh
git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp
cd aws-sdk-cpp
mkdir build
cd build
cmake .. -DBUILD_ONLY="s3" -DCMAKE_BUILD_TYPE=Debug
cmake --build . --config=Debug
cmake --install . --config=Debug
```

Please let me know if you are still running into the above error when building this sdk.
