### ISSUE TITLE
OSX doesn't have kCCAlgorithmAES but kCCAlgorithmAES128

### ISSUE THREAD

**Issue by zhoub** [aws/aws-sdk-cpp#263]
As the source code of Apple here.

http://opensource.apple.com//source/CommonCrypto/CommonCrypto-36064/CommonCrypto/CommonCryptor.h

**Comment by JonathanHenson** [comment]
That source code is out of date. Is this breaking your build. 128 bit cryptographic keys isn't something we're willing to support or encourage people to use.

If it is breaking your build, what version of OSX are you using?

**Comment by zhoub** [comment]
Okay seems that I'm using a too old MacOSX 10.8 SDK, switch to 10.9 it works now. Thank you very much.
