### ISSUE TITLE
Is S3Client thread safe?

### ISSUE THREAD

**Issue by newpoo** [aws/aws-sdk-cpp#266]
Or should I create one for each thread?

If I use one S3Client object to send multiple requests, will we reuse the tcp connection underlying?

Thanks,

**Comment by JonathanHenson** [comment]
Yes it's thread safe.
Yes it uses a connection pool per client.

**Comment by aditya300899** [comment]
Is the instance of AmazonS3 thread safe here:

AmazonS3ClientBuilder
                .standard()
                .withEndpointConfiguration(new AmazonS3 s3Client = AwsClientBuilder.EndpointConfiguration(s3Config.getEndpoint(), s3Config.getRegion()))
                .withPathStyleAccessEnabled(true)
                .withClientConfiguration(clientConfiguration)
                .withCredentials(new AWSStaticCredentialsProvider(credentials))
                .build();
