### ISSUE TITLE
cmake options USE_TLS_V1_2 and USE_TLS_V1_3 have no effect

### ISSUE THREAD

**Issue by tmajkowski-ot** [aws/aws-sdk-cpp#2662]
### Describe the bug

The recently added cmake configure options USE_TLS_V1_2 and USE_TLS_V1_3 have no effect
https://github.com/aws/aws-sdk-cpp/pull/2604

There are three issues:
1. cmake -L lists USE_TLS_V1_2 and USE_TLS_V1_3 options, which have no effect as CMakeLists.txt checks for USE_TLS_V2 and USE_TLS_V3
2. the conditionally compiled code in CurlHttpClient.cpp has no effect with current versions of curl 8 since LIBCURL_VERSION_MINOR would be <34.  For curl version range checks LIBCURL_VERSION_NUM might be a better choice https://curl.se/docs/versions.html
3. CURL_SSLVERSION_TLSv1_3 is available as of curl 7.52 according to curl documentation https://curl.se/libcurl/c/CURLOPT_SSLVERSION.html

### Expected Behavior

using the cmake options should enforce the desired TLS version for the selected client

### Current Behavior

cmake options USE_TLS_V1_2 and USE_TLS_V1_3 have no effect

### Reproduction Steps

cmake <path_to_sdk_source> -DCMAKE_INSTALL_PREFIX=<install_dir> -DBUILD_ONLY=core -DENABLE_TESTING=OFF -DBUILD_SHARED_LIBS=ON -DFORCE_CURL=ON -DCURL_LIBRARY=<path_to_curl_lib> -DCURL_INCLUDE_DIR=<path_to_curl_include> -DUSE_TLS_V1_3=ON
cmake --build . --config=Debug

void UploadFile(const std::string& access_key_id, const std::string& secret_key, const std::string bucket_name, const std::string key_name, std::shared_ptr<std::fstream> file_stream)
{
  Aws::S3::S3ClientConfiguration config;
  config.scheme = Aws::Http::Scheme::HTTPS;
  config.region = "us-east-2";

  Aws::S3::S3Client client(Aws::Auth::AWSCredentials(access_key_id, secret_key), config, Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::RequestDependent, false);
  
  Aws::S3::Model::PutObjectRequest put_object_request;
  put_object_request.SetBucket(bucket_name);
  put_object_request.SetKey(key_name);
  put_object_request.SetBody(file_stream);
  auto outcome(client.PutObject(put_object_request));

  std::cout << "Put " << (outcome.IsSuccess() ? "succeeded" : "failed") << std::endl;
}

put brake point before #if defined(ENFORCE_TLS_V1_3) in CurlHttpClient.cpp and see that CURL_SSLVERSION_TLSv1_3 option is not set.  Repeat the same for V1_2.

### AWS CPP SDK version used

1.11.159

### Compiler and Version used

Visual Studio 2022

### Operating System and version

windows 10

**Comment by sbiscigl** [comment]
Hey sorry about that, pushing out a change that should address your problems

**Comment by sbiscigl** [comment]
closing issue ad it was released and tagged give a shout if you have anymore questions
