### ISSUE TITLE
Comment error for TransferManager::DownloadToDirectory()

### ISSUE THREAD

**Issue by BofeiCHEN** [aws/aws-sdk-cpp#2665]
### Describe the issue

In the comment for `TransferManager::DownloadToDirectory()`, 

> bucketName: the name of the S3 bucket to upload to

which is an error, it should be:

> bucketName: the name of the S3 bucket to download from

### Links

https://github.com/aws/aws-sdk-cpp/blame/53ea0c45ce2bfe2ee5c28a2d9d2211795d4ccc20/src/aws-cpp-sdk-transfer/include/aws/transfer/TransferManager.h#L257

**Comment by yasminetalby** [comment]
Hello @BofeiCHEN ,

Thank you very much for bringing this up to our attention.

I will update the documentation to accurately describe the SDK behavior.

We appreciate your feedback and time helping us to improve the SDK documentation.

Best regards,

Yasmine

**Comment by yasminetalby** [comment]
Hello @BofeiCHEN ,

This has been fixed in v[1.11.162](https://github.com/aws/aws-sdk-cpp/releases/tag/1.11.162) of the SDK.

Thank you very much for your collaboration.

Best regards,

Yasmine
