### ISSUE TITLE
Add support to Json Utils to get values as Double,Int,String array 

### ISSUE THREAD

**Issue by shah-nirmit** [aws/aws-sdk-cpp#2678]
### Describe the feature

As a user I would like to parse json object that could have values like double arrays,int arrays or string arrays for a specific key
Take for an example a JSON object from
```
{
"embedding":[0.432442,-0.234342,.....]
"co-ordinates":[10.2423,4.432]
}
```

### Use Case

This would be useful for consider a machine learning applications calling sagemaker endpoints. Which could return an inference which could contain embedding or other outputs in which a value can be an array.

### Proposed Solution

One simple solution that comes to my mind is a method like this for `JsonView` Class
```
Array<double> JsonView::GetDoubleArray(const Aws::String& key) const
{
    assert(m_value);
    auto array = cJSON_AS4CPP_GetObjectItemCaseSensitive(m_value, key.c_str());
    assert(cJSON_AS4CPP_IsArray(array));
    Array<double> returnArray(cJSON_AS4CPP_GetArraySize(array));

    auto element = array->child;
    for (unsigned i = 0; element && i < returnArray.GetLength(); ++i, element = element->next)
    {
        returnArray[i] = element->valuedouble;
    }

    return returnArray;
}
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jmklix** [comment]
Looking into if we want to add this feature
