### ISSUE TITLE
Error Initializing hash

### ISSUE THREAD

**Issue by atharvapaladin** [aws/aws-sdk-cpp#2683]
### Describe the bug

While initializing AWS API in C++ code I get this error 
"s2n_init() failed: 335544335 (error initializing hash)
Fatal error condition occurred in /home/ubuntu/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-io/source/s2n/s2n_tls_channel_handler.c:203: 0 && "s2n_init() failed"
Exiting Application
################################################################################
Stack trace:
################################################################################
"

### Expected Behavior

Initialize AWS API and start S3 bucket upload

### Current Behavior

<img width="980" alt="Screenshot 2023-09-25 at 5 03 49 PM" src="https://github.com/aws/aws-sdk-cpp/assets/143420952/f92668b3-d685-4f06-8363-6d13b37cb3a9">

### Reproduction Steps

Initailize AWSAPI for uploading to S3 bucket

### AWS CPP SDK version used

1.11

### Compiler and Version used

gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

### Operating System and version

Ubuntu 20.04

**Comment by yasminetalby** [comment]
Hello @atharvapaladin ,

Thank you very much for your submission.

[error initializing hash](https://github.com/aws/s2n-tls/blob/2c8f025c5d59ba385ea80c202c2fbfebaceaeb3f/error/s2n_errno.c#L73) error you are encountering is thrown [here](https://github.com/awslabs/aws-c-io/blob/f7d9318fded44b64939f2139482706fb04324a8c/source/s2n/s2n_tls_channel_handler.c#L203) by the s2n_tls_channel_handler in the aws-c-io sdk. 

This error is the result of the call to [s2n_init](https://github.com/aws/s2n-tls/blob/main/utils/s2n_init.c). I am looking into potential root causes.

As a quick check, which version of TLS are you using?

Best regards,

Yasmine

**Comment by yasminetalby** [comment]
Hello @atharvapaladin ,

Thank you very much for your rapid response, I wanted to double check if you were using a supported version of TLS which you do.
Do you think you could share the stacktrace associated with this init failure. Here is some guidance documentation on how to enable stack trace for s2n-tls : https://github.com/aws/s2n-tls/blob/main/docs/USAGE-GUIDE.md#stacktraces 
This would help us to get more information regarding the s2n_init() failure.

Thank you very much for your time and collaboration.

Best regards,

Yasmine

**Comment by atharvapaladin** [comment]
Hi Yasmine,
I'm looping in my colleague @khapaladin , he would be able to answer the TLS questions better than me. 
Thanks

**Comment by khapaladin** [comment]
This is the code I use to activate the stack trace, but it outputs an empty file.
![s2nStackEnableCode](https://github.com/aws/aws-sdk-cpp/assets/111612958/60c65400-842a-4b6b-b39e-a6be8b3b64ee)
![EmptyFile](https://github.com/aws/aws-sdk-cpp/assets/111612958/585e91ae-f1e1-4982-a10d-5535055c8f58)

**Comment by atharvapaladin** [comment]
Hi Yasmine, 
I am still facing the same issue while initializing AWS, @khapaladin  tried running the stack trace but to no avail.

**Comment by khapaladin** [comment]
Hello,
Any updates on this issue?

**Comment by sbiscigl** [comment]
Hey sorry for taking a while to respond, this issue is an extremely environment dependent issue, can you please provide the full instructions to replicate it in the from of a dockerfile? I can help you get started using the following docker file and commands.

so far  we cannot reproduce your issue and will not be able to without a detailed reproduction example.

Dockerfile
```
FROM public.ecr.aws/amazonlinux/amazonlinux:2023

#Install g++
RUN yum groupinstall "Development Tools" -y

#Install required dependencies
RUN yum install -y curl-devel openssl-devel ninja-build cmake3 graphviz

# Clone repo
RUN git clone --depth 1 --recurse-submodules https://github.com/aws/aws-sdk-cpp && \
    cd aws-sdk-cpp && \
    mkdir build && \
    cd build && \
    cmake -DAUTORUN_UNIT_TESTS=OFF -DBUILD_ONLY="core" .. && \
    cmake --build . && \
    cmake --install .

# Copy Code Over \
RUN mkdir sdk-example
COPY CMakeLists.txt sdk-example/CMakeLists.txt
COPY main.cpp sdk-example/main.cpp
RUN cd sdk-example && \
    mkdir build && \
    cd build && \
    cmake .. && \
    cmake --build . \
```

main.cpp
```
#include <aws/core/Aws.h>

using namespace Aws;
using namespace Aws::Utils;

auto main() -> int {
  SDKOptions options;
  options.loggingOptions.logLevel = Logging::LogLevel::Trace;
  InitAPI(options);
  {
    std::cout << "From the SDK closure\n";
  }
  ShutdownAPI(options);
  return 0;
}
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.22)
project(sdk_usage_workspace)
set(CMAKE_CXX_STANDARD 20)
find_package(ZLIB)
find_package(AWSSDK REQUIRED COMPONENTS core)
add_executable(${PROJECT_NAME} "main.cpp")
target_link_libraries(${PROJECT_NAME} ${AWSSDK_LINK_LIBRARIES})
```

You can build with
```
docker build -t basic-use-image .
```

And run with
```
docker run --name basic-use-image basic-use-image /sdk-example/build/sdk_usage_workspace
```

we can see 
```
From the SDK closure
```

can you please update the above example to replicate your issue so that we can replicated it

**Comment by pythonking6** [comment]
Hello, I am also seeing this!
