### ISSUE TITLE
Listing directories in a bucket

### ISSUE THREAD

**Issue by DisgruntledBadger** [aws/aws-sdk-cpp#269]
Hello, I've been looking for a way to do something with the sdk and I can't quite figure out how to do it.

I have a bucket, for the sake of this question call it "b" and I can list all file held within all of its directories using a ListObjectRequest.

However, I am only working on a specific directory from said bucket, lets call it "d" and I wish to collect all files from a subset of the directories within d.

So basically I have to download from "b/d/{regex to find wanted directories}/files"

In order to do this I, presumably need an object that can help me list all subdirectories of  "d" (keep in mind, d is not a buckets, its a directory in itself) so i can then filter the given list and obtain the directories which I need.

Is it possible to do this kind of listing with the sdk ? if so what classes should I be looking at ? (note,: currently my projects uses the transfer client in order to download files)

**Comment by DisgruntledBadger** [comment]
To be more clear, I know of the methods alike "WithPrefix()" that I can set a prefix like b/d/ with, but I can't find a way to make them use a regex string

**Comment by JonathanHenson** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

You can do something like this based on delimiter now, but we unfortunately do not yet support a standard regex matcher.
