### ISSUE TITLE
Cannot specify Beijing regions

### ISSUE THREAD

**Issue by tomghuang** [aws/aws-sdk-cpp#270]
I can't find any constant in Aws::Region for Beijing regions (CN_NORTH_1 and CN_NORTH_2). Is there any way to specify Beijing regions in the AWS SDK for CPP? Thanks.

**Comment by JonathanHenson** [comment]
We just reworked the way regions work. On the latest revision, region is simply a string. We have some predefined constants, but they are only for convenience.

**Comment by tomghuang** [comment]
Hi @JonathanHenson 

I've tried to set the region to the string, "cn-north-1". I've also correctly set the config and credentials files. However, the log keeps telling me that, "Unable to connect to endpoint".
