### ISSUE TITLE
S3Crt fails when downloading exactly 5242881 bytes from s3 bucket

### ISSUE THREAD

**Issue by aschuess** [aws/aws-sdk-cpp#2704]
### Describe the bug

When using the `Aws::S3Crt::Model::GetObjectRequest` and `GetObject` API

on an object that is precisely ((5 * 1024 * 1024) + 1 bytes - only (5 * 1024 * 1024) bytes are returned.

When I download the same object through the AWS Web Console I get the full file.

 

Even when specifying a range of the last, say, 100 bytes, I am missing the final byte.

 

There was an identical bug report in the ruby sdk: https://github.com/aws/aws-sdk-ruby/issues/2561

 

### Expected Behavior

I expect to receive all 5242881 bytes of the s3 object

### Current Behavior

Only 5242880 bytes of the s3 object is returned

### Reproduction Steps

1. create a file that is 5MB + 1 byte (5242881 bytes)

2. Upload to s3

3. Download the object using `Aws::S3Crt::S3CrtClient` tooling

### Possible Solution

Off-by-one bug likely around the chunk size threshold is probably the issue

### AWS CPP SDK version used

1.9.359

### Compiler and Version used

Gcc 9

### Operating System and version

EL8

**Comment by aschuess** [comment]
I confirmed that changing the `partSize` of the `ClientConfiguration` makes the download of the 5M file work. (Of course files that are at the now different value will no longer work)

**Comment by jmklix** [comment]
Can you try updating to the latest version of this sdk. There was an update in [aws-c-s3](https://github.com/awslabs/aws-c-s3/commit/51df51a5cf94ec12f58c07af8d816015b976300e) to fix this exact issue. Please let me know if you run into any problems or still run into this off by one error.
