### ISSUE TITLE
Build fails due to warnings C4267: '=': conversion from 'size_t' to 'uInt', possible loss of data

### ISSUE THREAD

**Issue by ajishna** [aws/aws-sdk-cpp#2711]
### Describe the bug

strm.avail_in aws-sdk-cpp/src/aws-cpp-sdk-core/source/client/RequestCompression.cpp
has improper conversions at 2 locations:
Line 159:
 strm.avail_in = (flush == Z_FINISH)?toRead-1:toRead; //skip EOF if included
and Line 280:
 strm.avail_in = toRead;

Found when building custom client.
Worked around with adding #pragma warning(suppress: 4267) on the source.

### Expected Behavior

Build should not fail

### Current Behavior

Build fails when building custom clients with warning treated as error:
C4267: '=': conversion from 'size_t' to 'uInt', possible loss of data

### Reproduction Steps

Build custom client with cmake ( flag -DLEGACY_BUILD=ON and -DADD_CUSTOM_CLIENTS=<your_service_name>)

### Possible Solution

Fix the conversion issue

### AWS CPP SDK version used

1.11.169

### Compiler and Version used

Visual Studio 2022

### Operating System and version

Windows 10

**Comment by jmklix** [comment]
Can you try turning off warning as errors? You can do this with [this cmake flag](https://github.com/aws/aws-sdk-cpp/blob/main/docs/CMake_Parameters.md#aws_sdk_warnings_are_errors):
```cmake
-DAWS_SDK_WARNINGS_ARE_ERRORS=OFF
```

**Comment by ajishna** [comment]
Yes, turning off warning as errors works, but ideally one shouldn't.

**Comment by jmklix** [comment]
Should be fixed with the above PR. closing issue
