### ISSUE TITLE
Build fails for Legacy mode ON for custom clients, KeyError: 'serviceName'

### ISSUE THREAD

**Issue by ajishna** [aws/aws-sdk-cpp#2712]
### Describe the bug

When building the script for generate_sdks fail with:

Generating <my_service_name> api version <my_service_version>.
Traceback (most recent call last):
```
  File "aws-sdk-cpp\tools\scripts\legacy\generate_sdks.py", line 164, in <module>
    main()
  File "aws-sdk-cpp\tools\scripts\legacy\generate_sdks.py", line 153, in main
    generate_sdk(arguments['pathToGenerator'], sdks[key], arguments['outputLocation'], arguments['namespace'],
  File "aws-sdk-cpp\tools\scripts\legacy\generate_sdks.py", line 98, in generate_sdk
    process = Popen(['java', '-jar', jar_path, '--service', sdk['serviceName'], '--version', sdk['apiVersion'],
KeyError: 'serviceName'
```

The issue is because the key is defined as service_name and used as serviceName.
In tools/scripts/legacy/generate_sdks.py,

Line 76 :
```python
sdk = {'service_name': service_name, 'apiVersion': match.group(2), 'filePath': join(discovery_path, file)}
```

Issue is in Line 98:
```python
 process = Popen(['java', '-jar', jar_path, '--service', sdk['serviceName'], '--version', sdk['apiVersion'],
```

where the key is called using serviceName instead of service_name.

### Expected Behavior

Build should not fail

### Current Behavior

Build fails with KeyError

### Reproduction Steps

Build custom client with -DLEGACY_BUILD=ON

### Possible Solution

Rename serviceName to service_name at Line 98
or make the key names consistent (following naming/casing guidelines)

### AWS CPP SDK version used

1.11.169

### Compiler and Version used

Visual Studio 2022

### Operating System and version

Windows 10

**Comment by jmklix** [comment]
Does this [PR](https://github.com/aws/aws-sdk-cpp/pull/2720) fix the error you are getting when generating this sdk?

**Comment by jmklix** [comment]
Merge PR. closing this issue
