### ISSUE TITLE
Build fails with error generate_sdks.py: error: unrecognized arguments: --enable-virtual-operations

### ISSUE THREAD

**Issue by ajishna** [aws/aws-sdk-cpp#2713]
### Describe the bug

When building custom clients, Build fails with error 
Generating client for <my_service_name> version <my_service_version>
usage: generate_sdks.py [-h] [--outputLocation OUTPUTLOCATION]
                        [--serviceName SERVICENAME]
                        [--clientConfigDefaults CLIENTCONFIGDEFAULTS]
                        [--apiVersion APIVERSION] [--namespace NAMESPACE]
                        [--licenseText LICENSETEXT]
                        [--pathToApiDefinitions PATHTOAPIDEFINITIONS]
                        [--pathToGenerator PATHTOGENERATOR] [--prepareTools]
                        [--standalone] [--listAll] [--enableVirtualOperations]
generate_sdks.py: error: unrecognized arguments: --enable-virtual-operations

Reason:
Mismatch in argument names in sdks.cmake and generate_sdks.py

generate_sdks.py takes argument as "--enableVirtualOperations"
can be seen in Line 47 and used in Line 101 in 
aws-sdk-cpp/tools/scripts/legacy/generate_sdks.py

However, in aws-sdk-cpp/cmake/sdks.cmake, when it calls generate_sdks.py, at Line 80:

if(ENABLE_VIRTUAL_OPERATIONS) # it could be set to 0/1 or ON/OFF
    set(ENABLE_VIRTUAL_OPERATIONS_ARG "--enable-virtual-operations")
else()
    set(ENABLE_VIRTUAL_OPERATIONS_ARG "")
endif()

it created argument as "--enable-virtual-operations" instead of "--enableVirtualOperations"
and used it at Line 145, as:
 COMMAND ${PYTHON3_CMD} tools/scripts/legacy/generate_sdks.py --serviceName ${C_SERVICE_NAME} --apiVersion ${C_VERSION} ${ENABLE_VIRTUAL_OPERATIONS_ARG} --outputLocation ./generated/

### Expected Behavior

Build should not fail

### Current Behavior

Build fails

### Reproduction Steps

Build custom client with Legacy build ON

### Possible Solution

Change argument for generate_sdks.py to  "--enable-virtual-operations" instead of "--enableVirtualOperations"

### AWS CPP SDK version used

1.11.169

### Compiler and Version used

Visual Studio 2022

### Operating System and version

Windows 10

**Comment by jmklix** [comment]
Does this [pr](https://github.com/aws/aws-sdk-cpp/pull/2720) fix the error you see while generating the sdk?

**Comment by ajishna** [comment]
No it doesn't. That PR is for a different issue  #2712
<https://github.com/aws/aws-sdk-cpp/issues/2712>  that was reported.

**Comment by jmklix** [comment]
I added documentation for how to generate custom clients [here](https://github.com/aws/aws-sdk-cpp/pull/2748/files). Can you try following those steps and let me know if you have any problems?

**Comment by ajishna** [comment]
In added documentation, you mention placing the api-defintion in
Place your new model files in the correct folders:
  - c2j model (looks like this: `mycustomservice-2020-08-01.normal.json`)
    - In this path:
`aws-sdk-cpp/tree/main/tools/code-generation/api-descriptions`

I have been placing it here:
aws-sdk-cpp\code-generation\api-descriptions

There is no such path starting with aws-sdk-cpp/tree/..

**Comment by jmklix** [comment]
Sorry for not noticing this initially, but it should be `aws-sdk-cpp/tools/code-generation/api-descriptions` not `aws-sdk-cpp/tree/main/tools/code-generation/api-descriptions`. I have updated the PR to include this change. 
Does this work for you, or are you still running into errors building the sdk?

**Comment by ajishna** [comment]
Thanks. I'm still running into issues building the sdk.
The next error thrown by the build was a java error:
"Unable to access jarfile ./code-generation/generator\
target/aws-client-generator-1.0-SNAPSHOT-jar-with-dependencies.jar
Generating MyServiceName api version 2020-06-10"
MyServiceName - my service name
2020-06-10 - my service version

I'm currently stuck at this stage as there is no indication as to what
could be causing this next issue.
There are no error logs/outputs.

**Comment by ajishna** [comment]
I’m using:

>java -version

java version "1.8.0_202"

Java(TM) SE Runtime Environment (build 1.8.0_202-b08)

Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)



> python.exe --version

Python 3.10.11

**Comment by jmklix** [comment]
Are you using [this](https://github.com/aws/aws-sdk-cpp/blob/main/tools/scripts/run_code_generation.py) code generation script? Rather than the legacy one?
