### ISSUE TITLE
CognitoIdentityProvider::Model::DeliveryMediumType not getting set correctly

### ISSUE THREAD

**Issue by dturka** [aws/aws-sdk-cpp#273]
The <code>CognitoIdentityProvider::Model::DeliveryMediumType</code> never seems to be set correctly (i.e., it doesn’t match any of the enum types it should have). For examples, see <code>ForgotPasswordOutcome::GetResult().GetCodeDeliveryDetails().GetDeliveryMedium()</code> or <code>UpdateUserAttributesOutcome::GetResult().GetCodeDeliveryDetailsList()[0].GetDeliveryMedium()</code>.
Running a few quick tests, the integer value (which should be 2, for <code>EMAIL</code>) is consistently 67066748 (0x3FF5B7C) for both functions.

**Comment by bretambrose** [comment]
Are you able to send test code and steps to reproduce this?

**Comment by dturka** [comment]
Model::ForgotPasswordRequest request;
    request.SetClientId(m_clientId);
    request.SetSecretHash(GenerateSecretHash(username));
    request.SetUsername(username);

    Aws::CognitoIdentityProvider::CognitoIdentityProviderClient cognitoIdProviderClient;
    auto outcome = cognitoIdProviderClient.ForgotPassword(request);
    
    if (outcome.IsSuccess())
    {
        auto& deliveryDetails = outcome.GetResult().GetCodeDeliveryDetails();
        Model::DeliveryMediumType rawDeliveryMedium = deliveryDetails.GetDeliveryMedium();
        cout << "DeliveryMediumType value as int: " << (int)rawDeliveryMedium << endl;
    }

**Comment by bretambrose** [comment]
Is m_deliveryMediumHasBeenSet false?  The default constructor is not initializing m_deliveryMedium and so if the response processing doesn't set it, you'll likely get garbage in there.  Unfortunately there's no way to access the HasBeenSet either.  I'd like to get ride of *HasBeenSet and instead wrap all data in a simple, generalized option type, but I'm not sure we have time to safely do that before GA.  As a simpler, less risky change, we can add a way to access the HasBeenSet flag.  I'll try to get one of these done sometime this week.

**Comment by JonathanHenson** [comment]
we have had a NOT_SET enum value for a long time, and we forgot to add that to the initialization list. This is a bug on our side. Adding to our backlog.

**Comment by marcomagdy** [comment]
Fixed in v 1.0.26
