### ISSUE TITLE
Support for setting CURLSSLOPT_NATIVE_CA on Windows

### ISSUE THREAD

**Issue by pr0g** [aws/aws-sdk-cpp#2733]
### Describe the feature

(moved from discussion https://github.com/aws/aws-sdk-cpp/discussions/2724)

Pass `CURLSSLOPT_NATIVE_CA` to aws-sdk-cpp

### Use Case

This might be an issue but it's also very likely this is possible and I just don't know how to do it.

I am using aws-sdk-cpp on Windows and have a custom build of OpenSSL and Curl. When I try to make an `https` request using Curl directly, I get the error:

```
 SSL peer certificate or SSH remote key was not OK
```

I can fix this by either setting a certificate with:

```c++
curl_easy_setopt(curl, CURLOPT_CAINFO, "cacert.pem");
```

(_Where `"cacert.pem"` is one I grabbed from [here](https://curl.se/docs/caextract.html)_).

Or I can use:

```c++
curl_easy_setopt(curl, CURLOPT_SSL_OPTIONS, CURLSSLOPT_NATIVE_CA);
```

Where `CURLSSLOPT_NATIVE_CA` states "_Tell libcurl to use the operating system's native CA store for certificate verification_" (see [here](https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html) for more info).

The problem with this option is I don't see a way to pass that through to AWS SDK. I can get things to work if I use:

```c++
Aws::Client::ClientConfiguration client_config;
client_config.region = "<my-region>";
client_config.caFile = "cacert.pem";
```

But it would be nice if I could just use the operating system's native CA store.

Is there a way to do this that I'm not seeing? I initialize Curl outside of aws-sdk-cpp and I've tried setting the property right after `curl_global_init(CURL_GLOBAL_ALL);`.

Something like...

```
curl_global_init(CURL_GLOBAL_ALL);

if (CURL* curl = curl_easy_init()) {
  curl_easy_setopt(curl, CURLOPT_SSL_OPTIONS, CURLSSLOPT_NATIVE_CA);
}

Aws::SDKOptions options;
options.httpOptions.initAndCleanupCurl = false;
Aws::InitAPI(options);

...

Aws::ShutdownAPI(options);
curl_global_cleanup();
```

But that unfortunately does not seem to work. If there's a way to do this I'd be really curious to know. Thank you!

### Proposed Solution

Pass Curl option to aws-sdk-cpp at initialization time to use the operating system's native CA store.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by SergeyRyabinin** [comment]
Hi @pr0g ,

There is a an abstract method on the [Curl HTTP Client wrapper](https://github.com/aws/aws-sdk-cpp/blob/67ed6a2d342803345a21b9953929f81f0d9d2c4d/src/aws-cpp-sdk-core/include/aws/core/http/curl/CurlHttpClient.h#L48):
```
virtual void OverrideOptionsOnConnectionHandle(CURL*) const {}
```

You should be able to inherit the built-in Curl HTTP Client and then provide your implementation in this method. Please also refer to "Override the default HTTP client factory" in [our documentation](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/basic-use.html) in order to make SDK to use your new customized client.

Best regards,
Sergey

**Comment by pr0g** [comment]
Hi @SergeyRyabinin,

Thank you very much for getting back to me about this. This sounds like exactly what I was after! 🥳 Apologies I didn't spot this before.

I'll test this out soon and report back with how it went.

Thanks again very much for your help!

**Comment by pr0g** [comment]
Closing for now, will reopen if needed, thanks again 👍

**Comment by pr0g** [comment]
Just for completeness in case anyone else stumbles across this trying to do the same thing, this is what I used:

```c++
class CustomCurlHttpClient : public Aws::Http::CurlHttpClient
{
public:
  CustomCurlHttpClient(const Aws::Client::ClientConfiguration& client_config)
    : Aws::Http::CurlHttpClient(client_config) {}
private:
  void OverrideOptionsOnConnectionHandle(CURL* curl) const override {
    curl_easy_setopt(curl, CURLOPT_SSL_OPTIONS, CURLSSLOPT_NATIVE_CA);
  }
};

class CustomHttpClientFactory : public Aws::Http::HttpClientFactory
{
public:
  std::shared_ptr<Aws::Http::HttpClient> CreateHttpClient(
    const Aws::Client::ClientConfiguration& client_configuration) const override {
    return std::make_shared<CustomCurlHttpClient>(client_configuration);
  }
  virtual std::shared_ptr<Aws::Http::HttpRequest> CreateHttpRequest(
    const Aws::String& uri, Aws::Http::HttpMethod method,
    const Aws::IOStreamFactory& streamFactory) const override {
    return CreateHttpRequest(Aws::Http::URI(uri), method, streamFactory);
  }
  virtual std::shared_ptr<Aws::Http::HttpRequest> CreateHttpRequest(
    const Aws::Http::URI& uri, Aws::Http::HttpMethod method,
    const Aws::IOStreamFactory& streamFactory) const override {
    auto request =
      std::make_shared<Aws::Http::Standard::StandardHttpRequest>(uri, method);
    request->SetResponseStreamFactory(streamFactory);
    return request;
  }
};

...

// init time
Aws::SDKOptions options;
options.httpOptions.initAndCleanupCurl = false; // I call curl_global_init/curl_global_cleanup
options.httpOptions.httpClientFactory_create_fn = []() {
  return std::make_shared<CustomHttpClientFactory>();
};
```
