### ISSUE TITLE
Unresolved External Symbols when using Static Libraries

### ISSUE THREAD

**Issue by jasonabuzzell** [aws/aws-sdk-cpp#2734]
### Describe the bug

Hi there! I'm currently trying to build static, release libraries for C++ code, and I'm running into linker errors. I provided the sample code and reproduction steps below (the basic AWS initialization, and how I make the libraries).

Unsure what I'm missing here, but I'm guessing I need to fill another field with where the static libraries are. Thank you for the help!

### Expected Behavior

I expect the code to build and run without linker errors.

### Current Behavior

I am getting linker errors for my libraries, as shown below: 
```
main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl Aws::ShutdownAPI(struct Aws::SDKOptions const &)" (_imp?ShutdownAPI@Aws@@YAXAEBUSDKOptions@1@@z)
main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl Aws::InitAPI(struct Aws::SDKOptions const &)" (_imp?InitAPI@Aws@@YAXAEBUSDKOptions@1@@z)
```

### Reproduction Steps

```
#define USE_IMPORT_EXPORT
#define USE_WINDOWS_DLL_SEMANTICS

#include <aws/core/Aws.h>
int main(int argc, char** argv)
{
    Aws::SDKOptions options;
    Aws::InitAPI(options);
    {
        // make your SDK calls here.
    }
    Aws::ShutdownAPI(options);
    return 0;
}
```

To get the static libraries needed for this, I did the following steps:

Get CMake 3.21.7 and add to PATH
C:\Users\Jason > git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp
2.5 C:\Users\Jason > git submodule update --init --recursive
C:\Users\Jason > mkdir sdk_build
C:\Users\Jason > cd sdk_build
C:\Users\Jason\sdk_build > cmake "..\aws-sdk-cpp" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="C:/Program Files (x86)/aws-cpp-sdk-all" DFORCE_SHARED_CRT=OFF -DBUILD_SHARED_LIBS=OFF
C:\Users\Jason\sdk_build > cmake --build . --config=Release
C:\Users\Jason\sdk_build > cmake --install . --config=Release
In Visual Studio, add "C:\Program Files (x86)\aws-cpp-sdk-all\include" to Release Configuration: Additional Include Directories
In Visual Studio, add "aws-cpp-sdk-core.lib;aws-cpp-sdk-s3.lib;aws-c-auth.lib;aws-c-cal.lib;aws-c-common.lib;aws-c-compression.lib;aws-c-event-stream.lib;aws-checksums.lib;aws-c-http.lib;aws-c-io.lib;aws-c-mqtt.lib;aws-crt-cpp.lib;aws-c-s3.lib;aws-c-sdkutils.lib;aws-cpp-sdk-lambda.lib;%(AdditionalDependencies)" to Release Configuration: Additional Dependencies
Add the project folder under Release Configuration: Additional Library Directories to get static libraries.
Copy above libs and corresponding dependencies and add them to the project folder (next to main.cpp)
Build and run in Release mode.

### AWS CPP SDK version used

Latest (1.11.162)

### Compiler and Version used

Visual Studio 17 2022

### Operating System and version

Windows 10, Version 22H2

**Comment by jmklix** [comment]
Not sure if this is your problem, but it looks like you're missing a `-` before `DFORCE_SHARED_CRT=OFF`
It should be this:
```sh
cmake "..\aws-sdk-cpp" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="C:/Program Files (x86)/aws-cpp-sdk-all" -DFORCE_SHARED_CRT=OFF -DBUILD_SHARED_LIBS=OFF
```

**Comment by jmklix** [comment]
What does the CMakeLists.txt look like?

**Comment by jasonabuzzell** [comment]
Hi jmklix! Thank you for catching that missing hyphen. I made sure to run through the steps again from the beginning, making sure the hyphen was in there and I was only building S3, but I still am seeing the prior linker errors. I also do briefly see an error pop up when I cmake the "..\aws-sdk-cpp" folder, not sure what is happening there: 
![image](https://github.com/aws/aws-sdk-cpp/assets/98709108/0143bbcd-ae48-4343-8b8a-1d2120628be5)


As to what my CMakeLists.txt looks like (and I assume you aren't referring to the ones in "sdk_build"), I was hoping to do this all through a Visual Studio project without a CMakeLists.txt. Part of this is because I am using a framework to on top of C++ (JUCE), but also because I don't know what the CMakeLists.txt should look like. If you do figure out a way to solve this with .vcxproj arguments, that would be awesome, but with CMakeLists.txt I would need some guidance on how it should look.

Thank you for your time!

**Comment by jmklix** [comment]
If you are looking to do this in visual studio you might want to try using the vcpkg. You can find the steps for how to do this with this sdk [here](https://github.com/aws/aws-sdk-cpp#building-aws-sdk-cpp---using-vcpkg). For further questions about using vcpkg look [here](https://github.com/Microsoft/vcpkg#getting-started).

To use this sdk with JUCE I would check out using the forms [here](https://forum.juce.com/t/adding-the-amazon-sdk-to-my-project/32582/4) to see how others have done it

Or you can try to build the sdk and your project with cmake. This is what I have the most experience with and want I can help you the most with. I noticed another error in my previous comment which I forgot to correct. Make sure you are using `-DCMAKE_INSTALL_PREFIX` while you build the sdk and `-DCMAKE_PREFIX_PATH` while you are building your sample application. The error you are seeing at the end is that it can't find the core library at the default install location. Can you try fixing that, building the sample according to the steps [here](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/build-cmake.html), and see if that works for you?

**Comment by jasonabuzzell** [comment]
Thank you jmklix! I got the Release configuration working with the vcpkg method; looks like I call everything from C++ with no problem now. Thank you for also finding a JUCE-friendly resource, I really appreciate you going the extra mile!

There is something strange though that I should probably mention if anyone else is following this route; Aws.h requires that the `AWS_SDK_VERSION_MAJOR / MINOR / PATCH` be specified, which it isn't using the vcpkg method. I defined some bogus numbers prior to including that header (shown below), but I was wondering if there was a way I should be doing this.
![image](https://github.com/aws/aws-sdk-cpp/assets/98709108/ae13ceb7-1025-4997-b268-cb48cb64b01e)


Thank you again for all of the help! I'll keep the thread open in case, but the actual issue has been resolved!

**Comment by jmklix** [comment]
I'm glad I was able to help you. If you run into any other problems it's better if you open a new issue/discussion. Closing this issue for now, but please let me know if you have any other problems

**Comment by SerrgeiL** [comment]
I had same problem with link functions from static libraries.
Just not define USE_IMPORT_EXPORT when you want to use static libraries. Remove any definition in code before includes of AWS SDK headers.

USE_IMPORT_EXPORT need only for dynamic libraries https://github.com/aws/aws-sdk-cpp/blob/main/docs/SDK_usage_guide.md#build-defines.
