### ISSUE TITLE
How to  Specify TCP socket buffer size hints

### ISSUE THREAD

**Issue by yangsmith** [aws/aws-sdk-cpp#2740]
### Describe the issue

I read the documentation (https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/client-config.html) and  it says that I can specify the TCP socket buffer size hint, but I didn't find the related function in the SDK code

### Links

https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/client-config.html

**Comment by jmklix** [comment]
I think that might be incorrectly documented/outdated. Looking into getting that corrected

Why are you trying to change the buffer size? I would like to understand your use case so I can find the best solution for you.

**Comment by yangsmith** [comment]
1, I look at the java sdk documentation（https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html） there are related functions （setSocketBufferSizeHints），But the test program is written in c++.                                                                                                                                              
2、I don't want to rely on Linux to automatically adjust the TCP BUFFER SZIE, I want to manually adjust the buffer size without changing the system environment to test the program performance.

**Comment by jmklix** [comment]
Thanks for this suggestion, but this is not currently supported in the crt dependency. It's also not something that we plan on adding anytime in the near future, so I'm closing this issue.
