### ISSUE TITLE
Update CMakeLists to use GNUInstallDirs

### ISSUE THREAD

**Issue by ambasta** [aws/aws-sdk-cpp#276]
Currently, installation targets are hardcoded to bin/lib etc... On PLATFORM_LINUX=1, GNUInstallDirs should be used instead.

**Comment by bretambrose** [comment]
I've merged your changes (with some refactoring in) internally, but my refactoring (mostly pushing all the repetitive changes in per-project CMakeLists.txt files into macros) has broken something and I haven't had a chance to dig further into it yet.  It may be a few weeks before I finish it up.

**Comment by JonathanHenson** [comment]
This has been merged in and it is working it's way through our CI.
