### ISSUE TITLE
Set up S3 bucket to allow downloads without access keys?

### ISSUE THREAD

**Issue by KevinWSteele** [aws/aws-sdk-cpp#278]
Is there some way to use the SDK to set up a bucket to let someone download files from your S3 bucket without using your own private access keys? 
I know you can do this:  createBucketRequest.SetACL(BucketCannedACL::public_read);
However, how would someone download those files using the SDK?

**Comment by JonathanHenson** [comment]
You can generate a presigned url using your keys via the sdk if you have security concerns, or just generate a link using endpoint/bucket/key and give that to users if you want public reads. The users can then use that link to make an http get using whatever method they wish.

**Comment by KevinWSteele** [comment]
ok thanks!
