### ISSUE TITLE
aws-sdk-cpp failed to build on vcpkg

### ISSUE THREAD

**Issue by vertual-hb** [aws/aws-sdk-cpp#2780]
### Describe the bug

I added aws-sdk-cpp with override version 1.1.125 to vcpkg.json manifest.
During build with Visual Studio 2022, I recieved a build failed message.

### Expected Behavior

aws sdk installed as normal on vcpkg and project.

### Current Behavior

Project build with Visual Studio 2022 results in a build failed message.
This is the error from "install-x64-windows-dbg-out.log"

C:\vcpkg\buildtrees\aws-sdk-cpp\x64-windows-dbg\src\aws-cpp-sdk-core\ub_core.cpp
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(107): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(125): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(250): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(251): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(413): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(435): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(842): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(843): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(861): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(862): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(926): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(948): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(959): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(972): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(987): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(1004): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(1015): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(2061): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(2074): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(2721): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(2729): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(2740): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(2751): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(2760): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(2771): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(2808): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(2809): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(2818): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(2825): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(2826): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(2834): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(2842): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(3021): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(3043): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(3055): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(3087): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(3198): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(3213): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdcep.h(74): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdcep.h(76): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdcep.h(260): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdcep.h(757): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdcep.h(778): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdcep.h(1051): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdcep.h(1052): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdcep.h(1103): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdcep.h(1105): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdcep.h(1115): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdcep.h(1308): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdcep.h(1315): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\rpcnsi.h(128): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\rpcnsi.h(140): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\rpcnsi.h(368): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\rpcnsi.h(475): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\rpcnsi.h(486): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcasync.h(541): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcasync.h(563): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcasync.h(587): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcasync.h(611): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winscard.h(1255): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winscard.h(1263): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winscard.h(1277): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winscard.h(1285): error C2872: 'UUID': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\rpcdce.h(83): note: could be 'GUID UUID'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/utils/UUID.h(21): note: or       'Aws::Utils::UUID'
C:/vcpkg/buildtrees/aws-sdk-cpp/src/1.11.215-217520a113.clean/src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp(48): error C2589: '(': illegal token on right side of '::'
C:/vcpkg/buildtrees/aws-sdk-cpp/src/1.11.215-217520a113.clean/src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp(48): error C2062: type 'unknown-type' unexpected
C:/vcpkg/buildtrees/aws-sdk-cpp/src/1.11.215-217520a113.clean/src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp(48): error C2059: syntax error: ')'
C:/vcpkg/buildtrees/aws-sdk-cpp/src/1.11.215-217520a113.clean/src/aws-cpp-sdk-core/source/client/RequestCompression.cpp(142): error C2589: '(': illegal token on right side of '::'
C:/vcpkg/buildtrees/aws-sdk-cpp/src/1.11.215-217520a113.clean/src/aws-cpp-sdk-core/source/client/RequestCompression.cpp(142): error C2062: type 'unknown-type' unexpected
C:/vcpkg/buildtrees/aws-sdk-cpp/src/1.11.215-217520a113.clean/src/aws-cpp-sdk-core/source/client/RequestCompression.cpp(142): error C2059: syntax error: ')'
C:\vcpkg\buildtrees\aws-sdk-cpp\src\1.11.215-217520a113.clean\src\aws-cpp-sdk-core\include\aws/core/endpoint/DefaultEndpointProvider.h(16): fatal error C1083: Cannot open include file: 'aws/crt/endpoints/RuleEngine.h': No such file or directory
ninja: build stopped: subcommand failed.

### Reproduction Steps

add aws-sdk-cpp on vcpkg.json manifest as a project depenency with override version 1.1.125.

### Additional Information/Context

https://github.com/aws/aws-sdk-cpp/issues/2656 has similar error message

### AWS CPP SDK version used

1.11.215

### Compiler and Version used

Visual Studio 2022

### Operating System and version

Windows 11

**Comment by jmklix** [comment]
As noted in our documentation vcpkg is supported by [external contributors](https://github.com/Microsoft/vcpkg). I can help you if you run into any problems while building this [sdk from source](https://github.com/aws/aws-sdk-cpp#building-from-source). You can still build this from source and use it with visual studio, so please let me know if you have any questions
