### ISSUE TITLE
MFAOptions: Email delivery?

### ISSUE THREAD

**Issue by dturka** [aws/aws-sdk-cpp#279]
<code>Aws::CognitoIdentityProvider::Model::MFAOptionType</code> has a <code>GetDeliveryMedium()</code> method (with corresponding Set and With methods), which returns a DeliveryMediumType value of NOT_SET, SMS, or EMAIL. 
Won't the delivery medium always be SMS, and won't EMAIL always be an invalid setting? 
Is there any reason this setting exists?

**Comment by bretambrose** [comment]
Looking over the CIP documentation, both values appear to be valid (http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUserAttributeVerificationCode.html for example).  Why do you think email is potentially invalid?

**Comment by dturka** [comment]
It's my understanding that MFA codes are only delivered by SMS. 

"When MFA is required on a user pool, the phone number attribute is automatically required, and phone number verification is automatically turned on."

https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-email-phone-verification.html?icmpid=docs_cognito_console#user-pool-settings-mfa

**Comment by bretambrose** [comment]
The next section seems to indicate that both SMS and email are supported as options.  It sounds like SMS is just the default once enabled.

**Comment by bretambrose** [comment]
Closing for now.  Please reopen if you have further questions or issues.
