### ISSUE TITLE
Have to build with non-standard libuuid and zlib

### ISSUE THREAD

**Issue by necro351** [aws/aws-sdk-cpp#280]
Hi all, I have to build the sdk with a non-standard libuuid location (it is not in /usr/include) but there are only options to build the SDK with non-standard curl and openssl locations (which I happen to also be using). Can we add an option for a non-standard libuuid similar to the non-standard curl and openssl CMake options?

Also, to add to this, I also need to point to an external libz as well. This is the change I made to my version of the CMakeLists.txt file to allow this:

```
if(PLATFORM_LINUX)
    if(UUID_INCLUDE_DIR AND UUID_LIB_DIR)
        include_directories(${UUID_INCLUDE_DIR})
        link_directories(${UUID_LIB_DIR})
    endif()
    if(Z_INCLUDE_DIR AND Z_LIB_DIR)
        include_directories(${Z_INCLUDE_DIR})
        link_directories(${Z_LIB_DIR})
    endif()
endif()
```

**Comment by necro351** [comment]
Also, to add to this, I also need to point to an external libz as well. This is the change I made to my version of the CMakeLists.txt file to allow this:
`if(PLATFORM_LINUX)
    if(UUID_INCLUDE_DIR AND UUID_LIB_DIR)
        include_directories(${UUID_INCLUDE_DIR})
        link_directories(${UUID_LIB_DIR})
    endif()
    if(Z_INCLUDE_DIR AND Z_LIB_DIR)
        include_directories(${Z_INCLUDE_DIR})
        link_directories(${Z_LIB_DIR})
    endif()
endif()`

**Comment by bretambrose** [comment]
Hello,

In the next version of the SDK we have switched over to using CMake's find_* for curl, openssl, uuid, and zlib.  This means you should be able to use -DCMAKE_PREFIX_PATH="<your special builds of various libraries>" for any of those dependencies and have it taken over the default system ones.  This should be released on 8/30.

**Comment by JonathanHenson** [comment]
This has been fixed. Feel free to reopen if you have further issues or questions.
