### ISSUE TITLE
The aws sdk and libtorch build failed

### ISSUE THREAD

**Issue by cl1218** [aws/aws-sdk-cpp#2808]
### Describe the bug

The bug manifests as undefined references to specific functions in the AWS SDK during the linking stage of your project build.

### Expected Behavior

I expect the project to be built successfully.

### Current Behavior
```
[ 50%] Building CXX object CMakeFiles/http_predict.dir/downLoad.cpp.o
[100%] Linking CXX executable http_predict
CMakeFiles/http_predict.dir/downLoad.cpp.o:(.data.rel.ro._ZTVN3Aws2S39S3RequestE[_ZTVN3Aws2S39S3RequestE]+0x30): undefined reference to `Aws::AmazonWebServiceRequest::GetAdditionalCustomHeaders() const'
CMakeFiles/http_predict.dir/downLoad.cpp.o:(.data.rel.ro._ZTVN3Aws2S39S3RequestE[_ZTVN3Aws2S39S3RequestE]+0x38): undefined reference to `Aws::AmazonWebServiceRequest::SetAdditionalCustomHeaderValue(std::string const&, std::string const&)'
CMakeFiles/http_predict.dir/downLoad.cpp.o:(.data.rel.ro._ZTVN3Aws2S38Endpoint18S3EndpointProviderE[_ZTVN3Aws2S38Endpoint18S3EndpointProviderE]+0x28): undefined reference to `Aws::Endpoint::DefaultEndpointProvider<Aws::S3::S3ClientConfiguration, Aws::S3::Endpoint::S3BuiltInParameters, Aws::S3::Endpoint::S3ClientContextParameters>::OverrideEndpoint(std::string const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [http_predict] Error 1
make[1]: *** [CMakeFiles/http_predict.dir/all] Error 2
make: *** [all] Error 2
```

### Reproduction Steps

CMakeLists.txt :
```cmake
cmake_minimum_required(VERSION 3.13)
project(http_predict)
find_package(AWSSDK REQUIRED COMPONENTS s3)
message(STATUS "AWS SDK version: ${AWSSDK_LIBRARIES}")
# Set the C++ compiler based on the build target
if(BUILD_FOR_ARM)
    set(CMAKE_CXX_COMPILER aarch64-linux-gnu-gcc)
else()
    set(CMAKE_CXX_COMPILER gcc)
endif()
# Set additional library and include directories
set(EXTRA_LIB_DIR -L../lib)
set(EXTRA_INCLUDE_DIR -I../include)
file(GLOB AWSDOC_S3_HEADERS
    "include/s3download.h"
)
set(VTK_DIR "/usr/local/lib64/cmake/vtk-8.2")
set(Torch_DIR "/home/ec2-user/libtorch/share/cmake/Torch")

find_package(VTK REQUIRED)
find_package(Torch REQUIRED)
find_package(X11 REQUIRED)
# Set source files
set(SRC_DEMO downLoad.cpp)

# Set library dependencies
set(LIB -lsecurec -lstdc++)

# Add executable target
add_executable(http_predict ${SRC_DEMO})

# Set additional compile options
#target_compile_options(http_predict PRIVATE -g -fstack-protector --param ssp-buffer-size=4 -Wstack-protector)
target_link_libraries(http_predict PRIVATE ${VTK_LIBRARIES} ${TORCH_LIBRARIES}   ${X11_LIBRARIES} ${EXTRA_LIB_DIR} ${LIB} pthread aws-cpp-sdk-s3 aws-cpp-sdk-core)

# Set linking options
target_link_options(http_predict PRIVATE -Wl,--disable-new-dtags,--rpath ../lib -Wl,-z,relro,-z,now -Wl,-z,noexecstack -fPIC)
```

### Additional Information/Context

Only aws getobject is used in the actual source code.There is no problem when aws and libtorch build projects separately,This problem arises when the combination comes together.libtorch is available in version 1.7.0

### AWS CPP SDK version used

AWS CPP SDK-1.11.237

### Compiler and Version used

gcc-7.3.1 

### Operating System and version

centos

**Comment by sbiscigl** [comment]
> find_package(AWSSDK REQUIRED COMPONENTS s3)

how are installing the SDK? this error to me indicates that you have drift in your installation where you are including a header that expects these functions to be present but are using a binary where they are not present. Those specific functions were added in a [1.10 version](https://github.com/aws/aws-sdk-cpp/commit/cd22de13474d8f56d75243c613be11957c47164f#diff-73907f9213a794f8194dfef8f82f4ad081ee4766e1f637c92b157e1fa4684ca6) a while ago. My guess if you clean installed the SDK install to a specific directory, you would not see this problem

**Comment by cl1218** [comment]
Build S3 part of aws-sdk-cpp:
git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp
cd aws-ask-cpp
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/ -DCMAKE_INSTALL_PREFIX=/usr/local/ -DBUILD_ONLY="s3"
make -j4
make install

http_predict/downLoad.cpp example code:

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

#include "torch/torch.h"
#include "torch/script.h"
#include <iostream>
#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>
#include <aws/s3/model/GetObjectRequest.h>
#include <fstream>
#include "s3download.h"

/**
 * Before running this C++ code example, set up your development environment, including your credentials.
 *
 * For more information, see the following documentation topic:
 *
 * https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/getting-started.html
 *
 * Purpose
 *
 * Demonstrates using the AWS SDK for C++ to getting an object in an S3 bucket.
 *
 */

//! Routine which demonstrates getting an object in an S3 bucket.
/*!
  \sa GetObject()
  \param objectKey Name of an object in a bucket.
  \param toBucket: Name of a bucket.
  \param clientConfig: Aws client configuration.
*/

// snippet-start:[s3.cpp.get_object.code]
bool AwsDoc::S3::GetObject(const Aws::String &objectKey,
                           const Aws::String &fromBucket,
                           const Aws::Client::ClientConfiguration &clientConfig) {
    Aws::S3::S3Client client(clientConfig);

    Aws::S3::Model::GetObjectRequest request;
    request.SetBucket(fromBucket);
    request.SetKey(objectKey);

    Aws::S3::Model::GetObjectOutcome outcome =
            client.GetObject(request);

    if (!outcome.IsSuccess()) {
        const Aws::S3::S3Error &err = outcome.GetError();
        std::cerr << "Error: GetObject: " <<
                  err.GetExceptionName() << ": " << err.GetMessage() << std::endl;
    }
    else {
        std::cout << "Successfully retrieved '" << objectKey << "' from '"
                  << fromBucket << "'." << std::endl;
    }

    return outcome.IsSuccess();
}
// snippet-end:[s3.cpp.get_object.code]

/*
 *
 * main function
 *
 * Prerequisites: The bucket with an object to be retrieved.
 *
 * TODO(user): items: Set the following variable
 * - bucketName: The name of the bucket.
 * - objectName: The name of an object in the bucket.
*
*/

#ifndef TESTING_BUILD

int main() {
    Aws::SDKOptions options;
    Aws::InitAPI(options);
    {
        //TODO(user): Change bucketName to the name of a bucket in your account.
        const Aws::String bucketName = "<Enter bucket name>";

        //TODO(user): Change objectName to the name of an object in the bucket.
        //See create_bucket.cpp and put_object.cpp to create a bucket and load an object into that bucket.
        const Aws::String objectName = "<Enter object name>";

        Aws::Client::ClientConfiguration clientConfig;
        // Optional: Set to the AWS Region in which the bucket was created (overrides config file).
        // clientConfig.region = "us-east-1";

        AwsDoc::S3::GetObject(objectName, bucketName, clientConfig);
    }
    Aws::ShutdownAPI(options);

    return 0;
}

#endif // TESTING_BUILD



s3download.h:

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0 

#pragma once

#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>
#include <aws/s3/model/BucketLocationConstraint.h>

namespace AwsDoc {
    namespace S3 {

        bool GetObject(const Aws::String &objectKey,
                       const Aws::String &fromBucket,
                       const Aws::Client::ClientConfiguration &clientConfig);


        extern std::mutex upload_mutex;

        extern std::condition_variable upload_variable;
    } // namespace S3
} // namespace AwsDoc

**Comment by jmklix** [comment]
Can you please try to clean you build and install folders and then try rebuilding this sdk?

**Comment by DavidEnriqueNieves** [comment]
I also get the same error with a fresh install of the AWS C++ SDK using S3 only instead of S3-CRT as done previously.

**Comment by DavidEnriqueNieves** [comment]
@cl1218 Did you ever resolve this?

**Comment by DavidEnriqueNieves** [comment]
I also just tried it out with an older version of the AWS C++ SDK, namely tag 1.11.234. I unfortunately still run into the same issue.

**Comment by SergeyRyabinin** [comment]
Hi @DavidEnriqueNieves 
thank you for listing your cmake script.
```
# Set the path to the AWS SDK and other libraries
# set(AWS_SDK_PATH "/home/davidn/aws-sdk-cpp/build/AWSSDK")
set(AWS_SDK_PATH "/home/davidn/ml-c++/libs/aws-sdk-cpp-out-debug")
set(LIBTORCH_PATH "$ENV{HOME}/ml-c++/libs/libtorch-debug")

# Set CMAKE_MODULE_PATH to help find the custom AWS SDK
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${AWS_SDK_PATH}/lib/cmake/AWSSDK")
set(CMAKE_PREFIX_PATH ${AWS_SDK_PATH} ${LIBTORCH_PATH})

# Ensure CMake uses the custom path for AWS SDK
set(AWSSDK_ROOT_DIR ${AWS_SDK_PATH})
set(AWSSDK_INCLUDE_DIR ${AWS_SDK_PATH}/include)
set(AWSSDK_LIB_DIR ${AWS_SDK_PATH}/lib)

# Find AWS SDK
find_package(AWSSDK REQUIRED COMPONENTS s3-crt HINTS ${AWS_SDK_PATH} NO_DEFAULT_PATH)
```

I can see it quite deviates from our example app [cmake script](https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/cpp/example_code/s3-crt/CMakeLists.txt) and our [local test app](https://github.com/aws/aws-sdk-cpp/blob/main/tools/CI/install-test/CMakeLists.txt) within the main repo.
Your application is compiled successfully, but fails to be linked (because sdk libraries are not added to the linker input (or wrong libs added).

I'm not entirely sure why you are manually setting certain cmake variables (such as AWSSDK_ROOT_DIR, AWSSDK_INCLUDE_DIR, AWSSDK_LIB_DIR). I can also see that both CMAKE_PREFIX_PATH and CMAKE_MODULE_PATH are set with the SDK install path.

Typically we recommend setting only the CMAKE_PREFIX_PATH to contain an install path of the SDK, and then calling
```
find_package(AWSSDK REQUIRED COMPONENTS s3-crt)
```
I'm not sure what will happen if the SDK install path is pushed into different cmake package/library search variables, as well as manually set AWSSDK_LIB_DIR. Please let us know if there is a specific reason for your approach and you would have any suggestion what to update in our cmake script.

**Comment by DavidEnriqueNieves** [comment]
> Hi @DavidEnriqueNieves thank you for listing your cmake script.
> 
> ```
> # Set the path to the AWS SDK and other libraries
> # set(AWS_SDK_PATH "/home/davidn/aws-sdk-cpp/build/AWSSDK")
> set(AWS_SDK_PATH "/home/davidn/ml-c++/libs/aws-sdk-cpp-out-debug")
> set(LIBTORCH_PATH "$ENV{HOME}/ml-c++/libs/libtorch-debug")
> 
> # Set CMAKE_MODULE_PATH to help find the custom AWS SDK
> set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${AWS_SDK_PATH}/lib/cmake/AWSSDK")
> set(CMAKE_PREFIX_PATH ${AWS_SDK_PATH} ${LIBTORCH_PATH})
> 
> # Ensure CMake uses the custom path for AWS SDK
> set(AWSSDK_ROOT_DIR ${AWS_SDK_PATH})
> set(AWSSDK_INCLUDE_DIR ${AWS_SDK_PATH}/include)
> set(AWSSDK_LIB_DIR ${AWS_SDK_PATH}/lib)
> 
> # Find AWS SDK
> find_package(AWSSDK REQUIRED COMPONENTS s3-crt HINTS ${AWS_SDK_PATH} NO_DEFAULT_PATH)
> ```
> 
> I can see it quite deviates from our example app [cmake script](https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/cpp/example_code/s3-crt/CMakeLists.txt) and our [local test app](https://github.com/aws/aws-sdk-cpp/blob/main/tools/CI/install-test/CMakeLists.txt) within the main repo. Your application is compiled successfully, but fails to be linked (because sdk libraries are not added to the linker input (or wrong libs added).
> 
> I'm not entirely sure why you are manually setting certain cmake variables (such as AWSSDK_ROOT_DIR, AWSSDK_INCLUDE_DIR, AWSSDK_LIB_DIR). I can also see that both CMAKE_PREFIX_PATH and CMAKE_MODULE_PATH are set with the SDK install path.
> 
> Typically we recommend setting only the CMAKE_PREFIX_PATH to contain an install path of the SDK, and then calling
> 
> ```
> find_package(AWSSDK REQUIRED COMPONENTS s3-crt)
> ```
> 
> I'm not sure what will happen if the SDK install path is pushed into different cmake package/library search variables, as well as manually set AWSSDK_LIB_DIR. Please let us know if there is a specific reason for your approach and you would have any suggestion what to update in our cmake script.

Well,  I tried this out with the example CMakeLists.txt file that you linked from [here](https://github.com/aws/aws-sdk-cpp/blob/main/tools/CI/install-test/CMakeLists.txt). My reasoning for manually setting the directories was to isolate and ensure that only the directories that I was pointing it to were used for linking the libraries. However, it seems that this approach was flawed due to some unforeseen details. I still don't fully understand everything that's going on under the hood with CMake, but I suppose that's for me to find out. 

For anyone who needs reference, this CMakeLists.txt file worked for me:

```
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.13)
# -- Preamble --
project("sample_app"
        LANGUAGES CXX
        VERSION 1.0
        DESCRIPTION "A testing app using AWS SDK for C++"
        )

# -- Project wide setup --
# Setting C++ minimum requirements
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(LIBTORCH_PATH "$ENV{HOME}/autolabel-anything-c++/libs/libtorch-debug")
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "/home/davidn/autolabel-anything-c++/libs/aws-sdk-cpp-1.11.234_out_debug")
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} ${LIBTORCH_PATH})

# Setting build to hide symbols in targets by default
set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN YES)

# Preventing writes to package registry by default
set(CMAKE_EXPORT_NO_PACKAGE_REGISTRY YES)

# Validating config type and setting default if needed
get_property(is_multi_conf_build GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
if (NOT is_multi_conf_build)
    set(allowed_build_types Debug Release RelWithDebInfo MinSizeRel)
    # cmake-gui helper
    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "${allowed_build_types}")
    if (NOT CMAKE_BUILD_TYPE)
        message(STATUS "Setting build type to 'RelWithDebInfo' as none was specified.")
        set(CMAKE_BUILD_TYPE "RelWithDebInfo" CACHE STRING "Choose the type of build." FORCE)
    elseif (NOT CMAKE_BUILD_TYPE IN_LIST allowed_build_types)
        message(FATAL_ERROR "Unknown build type: ${CMAKE_BUILD_TYPE}")
    endif ()
endif ()

# -- Dependencies --
find_package(AWSSDK REQUIRED COMPONENTS s3)
find_package(Torch)

# -- main build target --
add_executable(app "aws-s3-fetch.cpp")
target_link_libraries(app ${AWSSDK_LINK_LIBRARIES} ${TORCH_LIBRARIES})
target_include_directories(app PRIVATE ${AWSSDK_INCLUDE_DIRS} "/home/davidn/autolabel-anything-c++/aws-lambda-cpp-hello/include")

# -- install target --
include(GNUInstallDirs)
set(CMAKE_INSTALL_DOCDIR ${CMAKE_INSTALL_DATAROOTDIR}/doc/${PROJECT_NAME})

install(TARGETS app
        RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
        )
```

Thank you for your suggestion.

**Comment by jmklix** [comment]
@DavidEnriqueNieves I glade that you were able to get it working. Closing this issue as there is a working solution. Please let me know if you run into more problems when using this sdk with libtorch.
