### ISSUE TITLE
Add SDKOption for default Credentials Provider Chain

### ISSUE THREAD

**Issue by MitchellKagerKodiak** [aws/aws-sdk-cpp#2814]
### Describe the feature

Every service client accepts an `AwsCredentialsProviderChain` that determines how credentials are resolved. It should be possible to configure a default during SDK initialization.

### Use Case

`STSProfileCredentialsProvider` does not exist in default chain [[150](https://github.com/aws/aws-sdk-cpp/issues/150)]. In certain codebases, it would be much more code-efficient to configure the credentials provider chain during initialization as opposed to passing a chain to construction of every client object.

### Proposed Solution

* Add a new `CredentialsProviderChainOptions` struct to `Aws.h`'s SDKOptions
* During `InitSDK`, check for presence of this struct's closure. If it is present, call some `SetDefaultCredentialsProviderChain` with the result of the closure. If it is not present, call `Set...Chain` method with `DefaultAWSCredentialsProviderChain` (current default)
* Update all occurrences of `DefaultAWSCredentialsProviderChain` across clients with `GetDefaultCredentialsProviderChain` (to resolve to configured value or pre-existing `DefaultAWSCredentialsProviderChain`).

### Other Information

posting a PR right now

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jmklix** [comment]
Thanks for opening this feature request and creating a PR to add this option. We are reviewing your PR to see if we would like to accept this changes and change how the credentials work.

**Comment by jmklix** [comment]
Thanks for taking the time and effort to make this PR. But we don't want to accept these changes, as we have plans to rework the Credentials Provider.

**Comment by MitchellKagerKodiak** [comment]
hey @jmklix , have you had a chance to rework the credentials provider? I still have a use case where I want to be able to easily reconfigure the default credentials provider against dozens of processes and I don't want to have to manually modify every single place I am constructing SDK clients. my processes generally construct SDK clients indirectly via wrappers and it would be incredibly tedious to modify the signature of every wrapper to pass a credentials provider through. it would be much more convenient to have each client configure this when they SDK::InitApi.
