### ISSUE TITLE
RequestTimeTooSkewed Error in CPP

### ISSUE THREAD

**Issue by kranthikusumuru** [aws/aws-sdk-cpp#282]
hi,
I am developing an application in mfc c++. I have stored my data in S3 bucket and am trying to pull that using aws cpp sdk . When skew time is more than 15 minutes I get generic error "Unable to connect to endpoint " or "403 forbidden" . I would like to get more specific error saying there is "time skew". Is there any function in cpp that can give me.

please let me know if there is any function like that or try to implement in next release.

**Comment by bretambrose** [comment]
Hello,

Can you give me any more details (platform, OS version, SDK version) how you are developing?  When I do an S3 Get with a bad value for my system clock, I get "RequestTimeTooSkewed" as the exception name.

**Comment by kranthikusumuru** [comment]
hi,

I am developing an application in MFC C++ where I use S3 to get content of
storage. I am using Windows 7. I am using latest sdk.

When am trying to download an .xml file from S3 with clock skew greater
than 15 mins. I get error description in .xml file and sdk writes
RequestTimeTooSkewed error into log file but in cpp code I didn't find any
function which gives detailed description instead it says "unable to
connect to end point".

In simple words, If there is time skew then I want a function which is
gives error description as "RequestTimeTooSkewed" instead of generalized
error description.

Thanks & Regards,
Kusumuru.

**Comment by renatoaf** [comment]
I'm experiencing similar problems (Android/iOS). Not sure if it is the same issue, but I'm always receiving an UNKNOWN error type (100). Tested with 403 errors (such as RequestTimeTooSkewed) and 404 errors (trying to download non-existing resources).

Debug log shows (same for 404 errors):

[DEBUG] 2016-09-02 20:44:50 AWSClient [0x16e3eb000] Request returned error. Attempting to generate appropriate error codes from response

[ERROR] 2016-09-02 20:44:50 AWSClient [0x16e3eb000] No response body.  Response code: 403

[DEBUG] 2016-09-02 20:44:50 CurlHttpClient [0x16e84b000] Returned http response code 403

[DEBUG] 2016-09-02 20:44:50 CurlHttpClient [0x16e84b000] Returned content type application/xml

[DEBUG] 2016-09-02 20:44:50 CurlHttpClient [0x16e84b000] Releasing curl handle 0x112598000

[DEBUG] 2016-09-02 20:44:50 CurlHandleContainer [0x16e84b000] Releasing curl handle 0x112598000

[DEBUG] 2016-09-02 20:44:50 CurlHandleContainer [0x16e84b000] Notifying waiting threads.

[DEBUG] 2016-09-02 20:44:50 AWSClient [0x16e84b000] Request returned error. Attempting to generate appropriate error codes from response

[WARN] 2016-09-02 20:44:50 AWSErrorMarshaller [0x16e84b000] Encountered Unknown AWSError
XML_ERROR_EMPTY_DOCUMENT
Unable to generate a proper httpResponse from the response stream.   Response code: 403:

**Comment by kranthikusumuru** [comment]
hi ,
I am using Windows platform,  Os is windows 7, Aws cpp Sdk Version is 0.14.4 . It would be great if I display "RequestTimeTooSkewed" Error to my customer instead of displaying generalized error "Unable to connect to end point" when the connection failed due to time skew.
 
I hope it get fixed in next release and let me know if you have any queries.

Thanks & Regards,
Kusumuru.

**Comment by JonathanHenson** [comment]
I just pushed a fix for this. The way it works is as follows. If we recieve a signing error, we check the date header returned from the server. If it's off, we automatically adjust the clock skew and retry the request. Once it is adjusted the first time, the client will have the correct timestamp. This should happen invisibly to the user without any errors surfacing.

Feel free to reopen if you still have problems or have any further questions.
