### ISSUE TITLE
Downloading large file from S3

### ISSUE THREAD

**Issue by shuzhang1989** [aws/aws-sdk-cpp#286]
Hi,

I am using the GetObjectRequest / Result to get some large objects (300M+) from S3. Is there a way to stream the object into disk? If we keep putting it into memory, we saw there are a large number of mem swaps and slowing down other io heavy applications.

**Comment by bretambrose** [comment]
Hello.

To download directly to disk, you can set a stream factory function in the GetObjectRequest that creates an appropriate file stream.  See https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp#L789  for an example.  We use a function to delay file creation until we know the request is successful and returning data.
