### ISSUE TITLE
how to set bucket policy, not ACL?

### ISSUE THREAD

**Issue by KevinWSteele** [aws/aws-sdk-cpp#287]
I can see how to set the ACL (access control list) for a bucket using the sdk. However, how do you set the bucket policy using this sdk?

**Comment by bretambrose** [comment]
PutBucketPolicyRequest is probably what you want.  I believe SetContentMD5 maps to the JSON policy string.

**Comment by JonathanHenson** [comment]
Does this solve your issue? Let us know if you still have a problem and reopen the issue.
