### ISSUE TITLE
Mandatory meta data for PUT S3 presigned url unlike javascript sdk

### ISSUE THREAD

**Issue by mamidisatya** [aws/aws-sdk-cpp#2878]
### Describe the bug

Generating PUT S3 presigned url with meta data and same has to provide manually for to hit the presigned url.
This is not the case with javascript sdk, where meta values will be added automatically (with key value). I am using aws sdk version 1.8.121.

### Expected Behavior

should be like javascript sdk when meta dta is populated as part of the url with values

### Current Behavior

Not populating meta data values. user has to provide manually

### Reproduction Steps

generated presgined url for S3 using PUT having some meta-data
try generating GET presinged url, meta values not populated only keys are populated

### AWS CPP SDK version used

1.8.121

### Compiler and Version used

gcc

### Operating System and version

linux

**Comment by jmklix** [comment]
Can you try updating to the latest version of the sdk? 1.8 is rather old and there have been many updates since then that. 

If this still doesn't work can you provide a minimal code sample for what you have to do currently and what you would like it to look like?

**Comment by mamidisatya** [comment]
Sure, thanks @jmklix will try once.
