### ISSUE TITLE
The following imported targets are referenced, but are missing:   AWS::aws-c-sdkutils

### ISSUE THREAD

**Issue by srinivasab3** [aws/aws-sdk-cpp#2896]
### Describe the bug

I am getting the following errors when I am trying to update the SDK for my application from 1.8.x to 1.11.X

CMake Error at /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Found package configuration file:

    /ros_ws/src/install/tools/lib/aws-c-auth/cmake/aws-c-auth-config.cmake

  but it set aws-c-auth_FOUND to FALSE so package "aws-c-auth" is considered 
  to be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  AWS::aws-c-sdkutils

Call Stack (most recent call first):
  /ros_ws/src/install/tools/lib/aws-crt-cpp/cmake/aws-crt-cpp-config.cmake:6 (find_dependency)
  /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /ros_ws/src/install/tools/lib/cmake/aws-cpp-sdk-core/aws-cpp-sdk-core-config.cmake:13 (find_depende
ncy)
  /ros_ws/src/install/tools/lib/cmake/AWSSDK/AWSSDKConfig.cmake:310 (find_package)
  CMakeLists.txt:133 (find_package)

===============================================================================
 CMakeLists.txt:133 has find_package(AWSSDK REQUIRED COMPONENTS kinesis s3 secretsmanager ssm lambda iot)

### Expected Behavior

Build should be completed without any errors

### Current Behavior

    /ros_ws/src/install/tools/lib/aws-c-auth/cmake/aws-c-auth-config.cmake

  but it set aws-c-auth_FOUND to FALSE so package "aws-c-auth" is considered 
  to be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  AWS::aws-c-sdkutils

### Reproduction Steps

NA

### AWS CPP SDK version used

1.11.285

### Compiler and Version used

set(CMAKE_CXX_STANDARD 14)

### Operating System and version

Linux

**Comment by jmklix** [comment]
Have you made sure that you have cloned the submodules needed? You can do that with this command:
```
git submodule update --init --recursive
```

If that doesn't work can you include the build steps that you are using that reproduces the error that you're seeing above?
