### ISSUE TITLE
Does the RateLimiting feature work?

### ISSUE THREAD

**Issue by piponazo** [aws/aws-sdk-cpp#290]
Hi!

I have been playing for a day with the library and I am very happy with it :+1: . The unique issue I am having at this moment is with the RateLimiting feature. I am writing a small test application for testing the different features of the library (sync putObject, async putObject, transfer manager with only 1 image, transfer manager with several images, etc). If I do not specify the RateLimiter the application works as expected but it does take all the available bandwidth. The moment I set the RateLimiter, the application does not upload anything ... 

This is an example of the code. I hope you can help me.

```
    auto limiter = Aws::MakeShared<Aws::Utils::RateLimits::DefaultRateLimiter<>>("test_s3", 200000);

    ClientConfiguration config;
    config.scheme =  Aws::Http::Scheme::HTTPS;
    config.connectTimeoutMs = 3000;
    config.requestTimeoutMs = 10000;
    config.writeRateLimiter = limiter;
    config.readRateLimiter = limiter;

    auto client = Aws::MakeShared<S3Client>("test_s3", creds2, config);

    // ...

    TransferManagerConfiguration transferManagerConfig;
    transferManagerConfig.s3Client = client;
    transferManagerConfig.uploadProgressCallback = uploadProgressCallback;

    TransferManager transferManager(transferManagerConfig);

    // Test with default behavior of using file name as key
    std::shared_ptr<TransferHandle> handle = transferManager.UploadFile(inputImage.c_str(),
        "myBucket", "myString", "application/octet-stream", Aws::Map<Aws::String, Aws::String>());

    handle->WaitUntilFinished();
```

Am I missing something?

**Comment by bretambrose** [comment]
I'll look into this when I get some time.  It seems possible that the sleep throttle is causing a timeout.

**Comment by piponazo** [comment]
Thanks for the answer. I'm looking forward to hearing from you ;)

**Comment by bretambrose** [comment]
How large a file are you uploading?  Your settings include a 10s timeout and a 200k/s rate limit.

**Comment by bretambrose** [comment]
There was a bug that made rate limiters and the transfer client crash when used together.  We'll have a fix out this week.

**Comment by AnAkkk** [comment]
Anything new about the fix? I just had the same issue.
I have tried to use PutObjectRequest instead, but the DefaultRateLimiter seems to have no effect at all on the upload speed. I have tried all kind of different values.

**Comment by bretambrose** [comment]
The fix did not get reviewed in time to make it out last week.  We will try again this week.

**Comment by JonathanHenson** [comment]
We just pushed out this change. Reopen if you still have issues or questions.
