### ISSUE TITLE
Duplicate definitions for AWS_CREDENTIAL_PROVIDER_EXPIRATION_GRACE_PERIOD

### ISSUE THREAD

**Issue by bcsgh** [aws/aws-sdk-cpp#2906]
### Describe the bug

The unqualified symbol `AWS_CREDENTIAL_PROVIDER_EXPIRATION_GRACE_PERIOD` is defined in two different namespaces (with the same type and value).

https://github.com/search?q=repo%3Aaws%2Faws-sdk-cpp%20AWS_CREDENTIAL_PROVIDER_EXPIRATION_GRACE_PERIOD&type=code

While this isn't likely an issue *now* (due to them being identical and only one of them actually being used) it could become an issue.

### Expected Behavior

Constant names always resolved to the same symbol.

### Current Behavior

two different constants with the same name in different namespaces.

### Reproduction Steps

Build under clang with `-Werror -Wunused-const-variable`.

### Possible Solution

Delete this line: https://github.com/aws/aws-sdk-cpp/blob/832ce62c18b7d5effd8299250283a939b64f1e14/src/aws-cpp-sdk-core/source/auth/GeneralHTTPCredentialsProvider.cpp#L17

### AWS CPP SDK version used

head

### Compiler and Version used

clang version 10.0.0-4ubuntu1

### Operating System and version

Linux

**Comment by jmklix** [comment]
Thanks for pointing this out. Testing the change to make sure it doesn't break anything
