### ISSUE TITLE
When we support China region?

### ISSUE THREAD

**Issue by zorrofox** [aws/aws-sdk-cpp#291]
Hi,

I have serval cases involve the CPP SDK for BJS region, and we just modify the source code and compile it ourself. So my question is when we can support BJS region and next China region Ningxia? If needed I can have a pull request for BJS region, thanks!

**Comment by tomghuang** [comment]
I have the same issue when I tried to access the Beijing data center.

I've tried to set the region to the string, "cn-north-1". I've also correctly set the config and credentials files. However, the log keeps telling me that, "Unable to connect to endpoint".

But when I switch the region to "us-west-2", everything works great. There must be some differences between the Beijing data center and the other data centers outside China, which haven't been considered in the CPP SDK.

**Comment by JonathanHenson** [comment]
Can you try this with http instead of https? If that works can you turn TLS back on and turn curl verbosity on and then upload the output?

**Comment by tomghuang** [comment]
I've changed to `config.scheme = Aws::Http::Scheme::HTTP`. However, it still doesn't work. The log still shows "Unable to connect to endpoint".

**Comment by JonathanHenson** [comment]
What service is this for?

**Comment by tomghuang** [comment]
I use this SDK to access S3 in the Beijing region.

**Comment by zorrofox** [comment]
Hi @tomghuang ,

  We have some products use this CPP SDK before and add BJS region endpoint separately in the codes, but recently the SDK source code has change a lot. I need some time the change original to include recently changed.

**Comment by zorrofox** [comment]
Hi @tomghuang ,

I have folk the latest version and add the S3 BJS support, you can clone it and build it for testing. Please following bellow detail:

You MUST use the BJS account to create a IAM user access key and setup to the default Credentials in your $HOME/.aws/credentials file.

I have created a new S3 integration testing CPP programs and you need make it first:
```
$ cmake -DBUILD_ONLY="s3"
$ make
```

Please use the gtest filter to only test for China region or you will failed for Access Key errors for Global region:
```
$ aws-cpp-sdk-s3-integration-tests/runS3IntegrationTests --gtest_filter=ChinaBucketAndObjectOperationTest.*
```
   
![image](https://cloud.githubusercontent.com/assets/1528417/18502827/23097ce0-7a8c-11e6-98b1-91ba84ec093d.png)

[FORK URL](https://github.com/zorrofox/aws-sdk-cpp)

**Comment by tomghuang** [comment]
@zorrofox, thank you so much for the fix. It works!!! Now I can access the S3 in the Beijing region.

**Comment by JonathanHenson** [comment]
Is the only change the endpoint change to append .cn to the bjs url? If so I can fix that today.

**Comment by tomghuang** [comment]
Yes, @JonathanHenson, the URL of the S3 endpoint in the Beijing region is different from the others.
Normal URL pattern is `s3-<region>.amazonaws.com`, but the URL of S3 in Beijing is `s3.<region>.amazonaws.com.cn`.

In other words, not only you have to add `.cn`, but also have to notice that `s3` is followed by a dot, not a dash.

**Comment by JonathanHenson** [comment]
I'll update our generators and get an update out today.

**Comment by zorrofox** [comment]
My version is only for work around to use the S3 services, all the other services should be modified accordingly. And we also need think more to totally support BJS region, such as BJS no dualstack endpoint, no default S3 bucket location etc.

**Comment by JonathanHenson** [comment]
My generator changes will handle all services and dual stack. 

The default location, is a whole different matter. That comes from the s3 service model. I can work with them to get that updated.

**Comment by zorrofox** [comment]
Hi @JonathanHenson 

I am SA base on China, if you want to get any help for BJS and maybe other China region you can reach me internally.

**Comment by bretambrose** [comment]
With the 10/12 release, we should now support the cn-north-1 region.  Please reopen if  there's a problem or remaining work to do.

**Comment by pshrivas** [comment]
Can someone summerize what is the difference between China SDK and standard AWS SDK?

**Comment by JonathanHenson** [comment]
there isn't one. The china endpoints are calculated from the region string just like every other region. The only slight difference is that the endpoint dns name is slightly different from the convention for other regions.
