### ISSUE TITLE
Header from the aws-sdk-transfer are gone

### ISSUE THREAD

**Issue by FlavouredGeorge** [aws/aws-sdk-cpp#292]
I recently made a pull request and noticed that programs previously working were lacking all there Transfer dependencies in this version, where have the TransferClient.h UploadFileRequest.h and DownloadFileRequest.h gone ? Why were they removed ?

**Comment by JonathanHenson** [comment]
Because they were broken, too complex and we didn't want to support it after going General Availability. The functionality has been moved to TransferManager.h

Since we are now at version 1.0 nothing else will be removed.
