### ISSUE TITLE
Build error: CURLINFO_APPCONNECT_TIME_T available only after v. 7.61.0

### ISSUE THREAD

**Issue by heriberto-delgado** [aws/aws-sdk-cpp#2931]
### Describe the bug

Building the SDK for Ubuntu 18.04, as of 4 / 18/ 2024, fails on CurlHttpClient.cpp:909, because of an incorrect version check for libcurl.

CURLINFO_APPCONNECT_TIME_T is available for libcurl 7.61.0 and later. The code, however, checks for v. 7.55.0. 

The documentation reference can be found here: https://curl.se/libcurl/c/CURLINFO_APPCONNECT_TIME_T.html

### Expected Behavior

Code compiles.

### Current Behavior

Code does not compile.

### Reproduction Steps

Perform a build following the instructions in the main repo page.

### AWS CPP SDK version used

Latest (3 hours after `tags/1.11.310` )

### Compiler and Version used

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

### Operating System and version

Ubuntu 18.04

**Comment by jmklix** [comment]
The fix for this was merged. Closing this issue
