### ISSUE TITLE
Cannot get mutable response stream from S3 async handler

### ISSUE THREAD

**Issue by 0x1997** [aws/aws-sdk-cpp#294]
e.g. Inside a GetObjectResponseReceivedHandler, the Model::GetObjectOutcome is passed in as a const reference, but to get the response content with `outcome.GetResult().GetBody().rdbuf()`, `GetBody()` requires a mutable `this`

**Comment by JonathanHenson** [comment]
Yes, this is the lesser of several evils. You'll have to do a const cast in this case since reading the stream alters its state.

**Comment by 0x1997** [comment]
@JonathanHenson Thanks.
