### ISSUE TITLE
S3: UploadPartCopy returns empty ETag

### ISSUE THREAD

**Issue by allspace** [aws/aws-sdk-cpp#295]
version 1.0.5

UploadPartCopyOutcome.IsSuccess() // is true, but

UploadPartCopyOutcome.GetResult().GetCopyPartResult().GetETag().c_str() //is empty

response trace is like below:

_[TRACE] 2016-09-19 00:40:54 CurlHttpClient [139771015977088] HTTP/1.1 200 OK^M

[TRACE] 2016-09-19 00:40:54 CurlHttpClient [139771015977088] x-amz-id-2: 17xx0lYEeN8JrXesoR0pwsVbrjTfSLKJFS3R/w2mh5D6rEuKcgcdrY6gI6b3FhDi7iMKP5gE4iE=^M

[TRACE] 2016-09-19 00:40:54 CurlHttpClient [139771015977088] x-amz-request-id: 94835C69A185CD58^M

[TRACE] 2016-09-19 00:40:54 CurlHttpClient [139771015977088] Date: Mon, 19 Sep 2016 04:40:48 GMT^M

[TRACE] 2016-09-19 00:40:54 CurlHttpClient [139771015977088] Content-Type: application/xml^M

[TRACE] 2016-09-19 00:40:54 CurlHttpClient [139771015977088] Content-Length: 230^M

[TRACE] 2016-09-19 00:40:54 CurlHttpClient [139771015977088] Server: AmazonS3^M

[TRACE] 2016-09-19 00:40:54 CurlHttpClient [139771015977088] ^M

[TRACE] 2016-09-19 00:40:54 CurlHttpClient [139771015977088] 230 bytes written to response.
[DEBUG] 2016-09-19 00:40:54 CurlHttpClient [139771015977088] Returned http response code 200
[DEBUG] 2016-09-19 00:40:54 CurlHttpClient [139771015977088] Returned content type application/xml
[TRACE] 2016-09-19 00:40:54 CurlHttpClient [139771015977088] Response content-length header: 230
[TRACE] 2016-09-19 00:40:54 CurlHttpClient [139771015977088] Response body length: 230__

**Comment by allspace** [comment]
tcpdump shows that S3 server response correct. It's the library fails to parse the response:

Response body looks like below:

<?xml version="1.0" encoding="UTF-8"?>
<CopyPartResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LastModified>2016-09-19T08:25:49.000Z</LastModified><ETag>&quot;2db0c8febc53ec3f01e740dfac41da8a&quot;</ETag></CopyPartResult>

**Comment by allspace** [comment]
The bug is here: "CopyPartResult" is exactly the root element of the XML document, instead of a child node under root.

UploadPartCopyResult& UploadPartCopyResult::operator =(const AmazonWebServiceResult<XmlDocument>& result)
{
  const XmlDocument& xmlDocument = result.GetPayload();
  XmlNode resultNode = xmlDocument.GetRootElement();

  if(!resultNode.IsNull())
  {
    XmlNode copyPartResultNode = resultNode.FirstChild("CopyPartResult");
    if(!copyPartResultNode.IsNull())
    {
      m_copyPartResult = copyPartResultNode;
    }
  }

**Comment by singku** [comment]
@allspace Do you still have this bug in your project?

**Comment by singku** [comment]
I can see the Etag in current log, reopen if the issue remains
