### ISSUE TITLE
No support for caFile?

### ISSUE THREAD

**Issue by necro351** [aws/aws-sdk-cpp#296]
So the Aws::Client::ClientConfiguration object has a caPath, where you can set the path. However, on CentOS and RHEL the CAs are not in a directory (like on Debian/Ubuntu) but all bundled together in a single file. OpenSSL lets you specify either file or path, but the AWS sdk only lets you specify a path, so it is unclear to me how to tell the AWS sdk where to get my CA certificates on CentOS/RHEL if they aren't in the standard place.

Shouldn't we have both a caDirPath and caFilePath option?

**Comment by JonathanHenson** [comment]
Yes, we should.

**Comment by JonathanHenson** [comment]
128
