### ISSUE TITLE
Unable to compile SDK with older windows SDK

### ISSUE THREAD

**Issue by ShimYama** [aws/aws-sdk-cpp#2964]
### Describe the bug

I tried to build the latest SDK (1.11.329) but [this line](https://github.com/aws/aws-sdk-cpp/blob/4740960c00f5390ff32eed71c54ab2e931f41a27/src/aws-cpp-sdk-core/source/http/windows/WinHttpSyncHttpClient.cpp#L95) cause error and I can't build it.
I changed SDK version to 1.11.296 that the version before the line added, I can compile SDK.

### Expected Behavior

Compile SDK

### Current Behavior

Error occurs that tells me "WINHTTP_OPTION_ENABLE_HTTP_PROTOCOL" is not defined.
I checked the source and found that there's no such variable in my winhttp.h source.
I think I'm using Visual Studio 2017 and my windows sdk is too old.

### Reproduction Steps

I used command prompt with this command.
```
cmake [AWS SDK Git Directory] -G "Visual Studio 14 Win64" -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="S3;S3-crt;sts" -DENABLE_TESTING=OFF -DCMAKE_INSTALL_PREFIX=[Install Directory] -DBUILD_SHARED_LIBS=OFF -DFORCE_SHARED_CRT=OFF -DAWS_SDK_WARNINGS_ARE_ERRORS=OFF
msbuild INSTALL.vcxproj /p:Configuration=Release /t:Rebuild /m /nologo
```

### AWS CPP SDK version used

1.11.329

### Compiler and Version used

Visual Studio 2017

### Operating System and version

Windows 10 Pro 22H2

**Comment by ShimYama** [comment]
I tested latest but another error occurred.
'ERROR_WINHTTP_CLIENT_AUTH_CERT_NEEDED_PROXY' and 'ERROR_WINHTTP_SECURE_FAILURE_PROXY' used in [WinHttpSyncHttpClient.cpp](https://github.com/aws/aws-sdk-cpp/blob/ed6fa2839659e8a1e99b2be5fc25bc1a62644226/src/aws-cpp-sdk-core/source/http/windows/WinHttpSyncHttpClient.cpp#L157-L158) are not defined.
However, it seems that these lines are added a few days ago, so should I report as another issue?

**Comment by jmklix** [comment]
Sorry the first PR didn't fix it for you. @SergeyRyabinin most recent [PR](https://github.com/aws/aws-sdk-cpp/pull/2985) should get it working for you. Please let us know if you still have any problems compiling this sdk

**Comment by ShimYama** [comment]
I tested latest and confirm it is okay.  Thank you.
