### ISSUE TITLE
Missing std::move

### ISSUE THREAD

**Issue by 0x1997** [aws/aws-sdk-cpp#297]
e.g. in implementation of [Aws::S3::Model::PutObjectRequest](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-s3/include/aws/s3/model/PutObjectRequest.h)

``` cpp
inline void SetContentMD5(Aws::String&& value) { m_contentMD5HasBeenSet = true; m_contentMD5 = value; }
inline PutObjectRequest& WithContentMD5(Aws::String&& value) { SetContentMD5(value); return *this;}
```

These rvalue references are used incorrectly. Without `std::move`, `value` will be not be moved from, and will generate an extra copy. These should be changed to

``` cpp
inline void SetContentMD5(Aws::String&& value) { m_contentMD5HasBeenSet = true; m_contentMD5 = std::move(value); }
inline PutObjectRequest& WithContentMD5(Aws::String&& value) { SetContentMD5(std::move(value)); return *this;}
```

**Comment by JonathanHenson** [comment]
Thanks for pointing this out. We'll get a fix out for this.

**Comment by crusader-mike** [comment]
should use std::forward() -- same effect, but semantically more correct.

**Comment by 0x1997** [comment]
@crusader-mike `std::forward` is for forwarding values, i.e. it returns a lvalue when passed a lvalue, or an rvalue when passed an rvalue. Inside these method bodys, `std::forward` will always return a lvalue and cause a copy because the value category of a named variable is always lvalue.
A better ways to do this will be like this
```cpp
inline void SetContentMD5(const Aws::String& value) { m_contentMD5HasBeenSet = true; m_contentMD5 = value }
inline void SetContentMD5(Aws::String&& value) { m_contentMD5HasBeenSet = true; m_contentMD5 = std::move(value); }
inline PutObjectRequest& WithContentMD5(const Aws::String& value) { SetContentMD5(value); return *this;}
inline PutObjectRequest& WithContentMD5(Aws::String&& value) { SetContentMD5(std::move(value)); return *this;}
```

**Comment by crusader-mike** [comment]
@0x1997 what std::forward<T> returns depends only on T (which is normally deduced depending on context as described [here](http://en.cppreference.com/w/cpp/utility/forward)). In the function above T isn't deduced -- you'll have to specify it.

In any case, effect will be the same and std::move is less typing. I retract my suggestion.
