### ISSUE TITLE
S3 client ignores http configuration

### ISSUE THREAD

**Issue by kiwaa** [aws/aws-sdk-cpp#2972]
### Describe the bug

`S3Client::operator=` was introduced in [the commit](https://github.com/aws/aws-sdk-cpp/commit/1a4150c6b17b6da970cdc6d538899aee1ac95415) which does not properly reinitialise base class. m_httpclient uses default timeouts in this case

### Expected Behavior

Configuration (and timeouts) are respected. Code below outputs 30000

### Current Behavior

Timeouts are not respected as inner m_httpclient is initialised with default configuration. Code below prints ~150

### Reproduction Steps

```cpp
Aws::SDKOptions options;
Aws::InitAPI(options);
{
    Aws::Client::ClientConfiguration clientConfig;
    clientConfig.connectTimeoutMs = 30'000;
    clientConfig.httpRequestTimeoutMs = 30'000;
    clientConfig.requestTimeoutMs = 30'000;
    clientConfig.proxyHost = "localhost";
    clientConfig.proxyPort = 1234;

    // ok
    // Aws::S3::S3Client client = Aws::S3::S3Client(clientConfig);

    // not ok since 1.11.212
    Aws::S3::S3Client client;
    client = Aws::S3::S3Client(clientConfig);

    Aws::S3::Model::GetObjectRequest request;
    request.SetBucket("test_bucket");
    request.SetKey("test_key");

    auto start = std::chrono::system_clock::now();
    auto outcome = client.GetObject(request);
    auto end = std::chrono::system_clock::now();

    auto now_ms = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);

    std::cout << now_ms.count() << std::endl;
}
Aws::ShutdownAPI(options);

```

### AWS CPP SDK version used

1.11.212

### Compiler and Version used

Visual Studio

### Operating System and version

Windows 11

**Comment by kiwaa** [comment]
sorry,  I should have been more specific. It was tested on 1.11.331 and I just tried on the latest master - still doesn't work.
From the commit that you provided, I don't see changes around m_httpclient (in AWSClient or S3Client)

**Comment by jmklix** [comment]
This should be fixed with this PR: https://github.com/aws/aws-sdk-cpp/pull/2977
Please update to the latest version of this sdk and let us know if you run into any problems

**Comment by kiwaa** [comment]
Confirmed, it is fixed now. thanks!
