### ISSUE TITLE
Cannot include Windows.h

### ISSUE THREAD

**Issue by bvhoang91** [aws/aws-sdk-cpp#299]
Hi,

I have a issue when try to add aws-cpp-sdk-core/aws-cpp-sdk-s3/aws-cpp-sdk-transfer project to my project (mfc project).
It seem there is a conflict with GetObject function in windows.h.

error LNK2001: unresolved external symbol "public: virtual class Aws::Utils::Outcome<class Aws::S3::Model::GetObjectResult,class Aws::Client::AWSError<enum Aws::S3::S3Errors> > __thiscall Aws::S3::S3Client::GetObjectW(class Aws::S3::Model::GetObjectRequest const &)const " (?GetObjectW@S3Client@S3@Aws@@UBE?AV?$Outcome@VGetObjectResult@Model@S3@Aws@@V?$AWSError@W4S3Errors@S3@Aws@@@Client@4@@Utils@3@ABVGetObjectRequest@Model@23@@Z)

Can someone please help?

**Comment by JonathanHenson** [comment]
Unfortunately, you'll have to undef GetObject.

**Comment by bvhoang91** [comment]
Hi Jonathan Henson,

Can you explain your idea.
I'm writing a test upload function (copy and modify code from upload function in aws-cpp-sdk-transfer-tests), so I think I can't undef GetObject in aws project, I also can't remove include"windows.h".
Would you like check my project? I can send to you via e-mail.

**Comment by JonathanHenson** [comment]
Sure
