### ISSUE TITLE
Cancel progress when uploading large file

### ISSUE THREAD

**Issue by bvhoang91** [aws/aws-sdk-cpp#300]
When I upload a small file (<5MB), progress callback function is triggered consecutive (after sending data success). I can cancel progress immediately.
But when upload a large file (multi upload),  callback func is triggered after sending one part (5MB) success, so it take a long time for cancel progress .
How can I solve this problem? Thanks.

**Comment by JonathanHenson** [comment]
You can hold on to the handle returned by UploadFile() and cancel it at any time. We currently don't trigger the callback for each packet sent for a.) performance considerations, b.) the complexity involved in backing out a failed part upload is high and it is less error prone to just trigger the callback when each part completes successfully. Please reopen if you have further questions.

**Comment by bvhoang91** [comment]
But, It mean we can not update percent immediately, too. (I don't create new issue because I think this is the same problem).
