### ISSUE TITLE
Code generation API Gateway

### ISSUE THREAD

**Issue by MaxGriot** [aws/aws-sdk-cpp#301]
Hello,

I am trying to generate the cpp code for my custom API, I can download the APi for java/ios etc but not for C++, where can I find/create the c2j for my API ?

Thanks,
Max

**Comment by JonathanHenson** [comment]
As of now, API Gateway hasn't added automated generation of C++ SDKs. You can take the C2j file from the Java Client and use it to generate a custom client in the C++ SDK using the ADD_CUSTOM_CLIENTS cmake arg. If you don't have access to the c2j file API Gateway generated, one option is to look at the c2j file for lambda (code-generation/api-definitions/) and use that as a template (the format/protocol is basically identitical) for your API Gateway definition.

**Comment by MaxGriot** [comment]
So after some research I just couldn't find the C2J files, I ended up writing a python script to codegen from the swagger json files that gateway exposes, I will see if my employer agrees to make it opensource, it's probably incomplete but it works fine for the subset of gateway features I am currently using.

**Comment by csimmons0** [comment]
Should I, as an API Gateway user, be able to access this c2j file? I don't see anything about it in the API Gateway console.

**Comment by MaxGriot** [comment]
No sadly you can only download the swagger file... It contains everything you need to generate the SDK but you will have to write scripts for it yourself...

**Comment by csimmons0** [comment]
I generated this JSON and put it in a file named "vitalservices.normal.json" in the api-descriptions folder. I then ran cmake with '"-DADD_CUSTOM_CLIENTS="serviceName=VitalServices; version=2016-11-23T04:16:29Z"' (no single quotes) as one of the arguments. Maven ran, but, when I look at the contents of the generated build folder, the only sign of the client generator's running on my API is one line in CMakeCache.txt, and it's just echoing the argument that I passed to CMake. What might I be doing wrong?
```
{
    "metadata": {
        "serviceFullName": "VitalServices",
        "endpointPrefix": "h6wguq9ghl.execute-api.us-east-1.amazonaws.com/prod",
        "protocol": "rest-json",
        "apiVersion": "2016-11-23T04:16:29Z"
    },
    "version": 2.0,
    "operations": {
        "get-logged-in-user": {
            "output": {
                "shape": "ClientUser"
            },
            "input": {
                "shape": "VitalServicesRequest"
            },
            "name": "get-logged-in-user",
            "http": {
                "method": "POST",
                "responseCode": 200,
                "requestUri": "/get-logged-in-user"
            }
        }
    },
    "shapes": {
        "VitalServicesRequest": {
            "title": "VitalServicesRequest",
            "type": "object",
            "properties": {
                "doctorId": {
                    "type": "string"
                },
                "operation": {
                    "type": "string"
                },
                "pictureUrl": {
                    "type": "string"
                },
                "getPatients": {
                    "type": "boolean"
                },
                "unavailableTimeSlots": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "priceDollars": {
                    "type": "string"
                },
                "sourceId": {
                    "type": "string"
                },
                "appointmentId": {
                    "type": "string"
                },
                "patientIds": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "cardToken": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "bankAccountToken": {
                    "type": "string"
                },
                "doctorIds": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "officeNumber": {
                    "type": "string"
                },
                "appointmentIds": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "lastName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "availableTimeSlots": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "lastTime": {
                    "type": "string"
                },
                "mobileNumber": {
                    "type": "string"
                },
                "streetNumberAndName": {
                    "type": "string"
                },
                "httpMethod": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "file": {
                    "type": "string"
                },
                "birthdateMonth": {
                    "type": "string"
                },
                "serviceIds": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "suite": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "firstTime": {
                    "type": "string"
                },
                "lateCancellation": {
                    "type": "boolean"
                },
                "latitude": {
                    "type": "number"
                },
                "patientId": {
                    "type": "string"
                },
                "billVersion": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "employerIdentificationNumber": {
                    "type": "string"
                },
                "durationMinutes": {
                    "type": "string"
                },
                "string4": {
                    "type": "string"
                },
                "string2": {
                    "type": "string"
                },
                "string3": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "birthdateDay": {
                    "type": "string"
                },
                "string1": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "birthdateYear": {
                    "type": "string"
                },
                "businessName": {
                    "type": "string"
                },
                "serviceId": {
                    "type": "string"
                },
                "ssnLast4": {
                    "type": "string"
                },
                "specialtyId": {
                    "type": "string"
                },
                "getDoctors": {
                    "type": "boolean"
                }
            }
        },
        "ClientUser": {
            "title": "ClientUser",
            "type": "object",
            "properties": {
                "doctorId": {
                    "type": "string"
                },
                "profilePhotoUrl": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "mobileNumber": {
                    "type": "string"
                }
            },
            "required": [
                "email",
                "firstName",
                "id",
                "lastName"
            ]
        }
    }
}
```

**Comment by JonathanHenson** [comment]
I think there's a typo in the readme, there should be a comma separating service name and API version. Also the versioning date goes in the file name following the convention of the other services.

**Comment by csimmons0** [comment]
I appear to have things close to working now, but my attempt to invoke my API fails at runtime with an, "Unable to connect to endpoint," error message.  What should the "endpointPrefix" in the  api-description file look like? I suspect that's where the problem is--there or somewhere else in the metadata section. This is what I presently have:

    "metadata": {
        "apiVersion": "2016-11-23",
        "endpointPrefix": "h6wguq9ghl.execute-api.us-east-1.amazonaws.com/prod",
        "protocol": "rest-json",
        "serviceFullName": "VitalServices"
    },

**Comment by MaxGriot** [comment]
Could you paste the content of the Aws::String ForRegion(Region region) function that was generated?

**Comment by csimmons0** [comment]
```
  static const int CN_REGION_HASH = Aws::Utils::HashingUtils::HashString("cn-north-1");
  

  Aws::String ForRegion(const Aws::String& regionName, bool useDualStack)
  {
    auto hash = Aws::Utils::HashingUtils::HashString(regionName.c_str());
    
    Aws::StringStream ss;
    ss << "h6wguq9ghl.execute-api.us-east-1.amazonaws.com/prod" << ".";

    if(useDualStack)
    {
      ss << "dualstack.";
    }

    ss << regionName << ".amazonaws.com";
    
    if(hash == CN_REGION_HASH)
    {
      ss << ".cn"; 
    }
    
    return ss.str();
  }
```

**Comment by JonathanHenson** [comment]
you want h6wguq9ghl.execute-api as your endpoint prefix

**Comment by csimmons0** [comment]
Thanks. Is there a way to make my generated client send requests with the application/json content type? I looked at the CORAL_TO_CONTENT_TYPE_MAPPINGs, but I didn't see an option for normal application/json. I think that using the application/x-amz-json-1.1 content type is what's presently causing an "Unsupported Media Type" error.

Also, using h6wguq9ghl.execute-api as the endpoint prefix didn't quite work because the AWSAuthV4Signer then used the entire "h6wguq9ghl.execute-api" string as the scope of the credential. I would get back an error saying, "Credential should be scoped to correct service 'execute-api'." I got past this issue by using "execute-api" as the endpoint prefix and setting the ClientConfiguration's endpointOverride to "h6wguq9ghl.execute-api.us-east-1.amazonaws.com."

**Comment by JonathanHenson** [comment]
for the moment, you can change the value in your base request object in the generated sdk. im going to make some generator changes to make this whole process easier for you but that will take a few days.

**Comment by csimmons0** [comment]
Is there any way I could get access to this C2J file or some other means of generating a C++ client that appears the way it's meant to? The swagger-to-api-description script that I've been using as a stopgap measure results in a C++ client that is becoming increasingly difficult to use, much more difficult to use than a client generated with the proper tools would be.

**Comment by jarruda** [comment]
Hello! Is this still the current state of getting a C++ SDK generated for API Gateway?

**Comment by singku** [comment]
We are at the last stage to integrate this auto gen sdk into Api Gateway

**Comment by wps132230** [comment]
You can generate the C2J file with aws cli:
```sh
aws --region <region> --profile <your profile> apigateway get-export --rest-api-id <api id> --stage-name <stage name> --export-type c2j ./c2j.zip && unzip c2j.zip && vim service-2.json
```
Then use the code-generation to generate the custom cpp SDK for you API manually. We've already made some changes on the generator to work with custom API.

And hopefully, you can do that with only one click in the AWS console in the future. The code is under tests and reviews.

**Comment by jkoutavas** [comment]
Has anyone succeeded in generating a c2j file?

**Comment by mattman71** [comment]
That part, yes. See [issue thread 858](https://github.com/aws/aws-sdk-cpp/issues/858)
