### ISSUE TITLE
Transfer Client lacks multi-part download support

### ISSUE THREAD

**Issue by mmustafa-hp** [aws/aws-sdk-cpp#302]
Downloading large files of 4GB plus is currently problematic with the transfer client. A retry on the entire file is not efficient or economical. We really multi-part download capability added. 
This issue has been mentioned before but I think it deserves its own entry on the issues list.

**Comment by JonathanHenson** [comment]
I'm going to add it using range gets but there is one big caveat, you need to make sure you use the same buffer size for the download as you did when you uploaded it, or the disk will thrash on s3's side and it will be very slow. Is the uploaded part size something you would know at download time?

**Comment by mmustafa-hp** [comment]
Todate, we have been using the AWS web interface to perform the uploads. We are in the process of automating and switching to the AWS CLI for performing the uploads. So we can make the download part the same.

**Comment by mmustafa-hp** [comment]
Is there an update for this issue? Our solution continues to struggle due to the lack of this capability.

**Comment by bretambrose** [comment]
We don't have an ETA right now, but I wouldn't be surprised if it mysteriously gets done over the holiday break.

**Comment by mmustafa-hp** [comment]
I saw a comment on closed issue #426 that looked promising. We're still eagerly awaiting this feature.

**Comment by JonathanHenson** [comment]
its in cr right now. We had to update it to respect part boundaries.

**Comment by bretambrose** [comment]
1.0.83 contains a preliminary implementation of multi-part download (parts go to the in-memory buffers only).  In the future, we'd like to also support downloading parts to files and serializing the download state to a file, which would allow downloads to resume across runs of a program (think of an online game patcher downloading multi-gigabyte updates in the background, for example).  We don't have an ETA on that feature though.

**Comment by mmustafa-hp** [comment]
thank you very much. We will certainly work with this release. Is there a blog post or documentation that we can review?

**Comment by bretambrose** [comment]
No blog post unless Jonathan wants to write one (I'm on another project right now).  DownloadFile on TransferManager will automatically split between single part and multi-part based on the size of the object (relative to the internal buffer size).
