### ISSUE TITLE
Need AWS C++ libraries for RaspberryPi 3-B Linux (Raspbian) on ARM Processor

### ISSUE THREAD

**Issue by scotthbradley** [aws/aws-sdk-cpp#304]
I was attempting to write a C++ appliance for AWS on a little Linux box (a Raspberry Pi !!)  I have found references to Windows 32bit and 64bit libraries... but I cannot seem to find references to non-64bit Linux distros.... Is it possible to port these to a 1.2 GHz 64-bit quad-core ARM Cortex-A53 which is running a **32bit** Raspbian OS??? If you want to ask questions about what I need, please feel free to contact me...  Thanks!

**Comment by JonathanHenson** [comment]
Are you asking if you can build from source for your target? The answer is yes. It's just standard cmake to specify the target.

**Comment by scotthbradley** [comment]
I was under the assumption that you provided binary libraries for each OS... 
Seeing that you provide DLLs for 32bit Windows and 64bit Windows each is
what brought me to that conclusion.  Are you saying that I can build AWS
for my box?  if so, what I am attempting to do, is replace a Java program
which already runs on the box with something FASTER!!!

It seems that we are using the following AWS (again) libraries for Java
import com.amazonaws.AmazonClientException;
import com.amazonaws.AmazonServiceException;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.regions.Region;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.kinesis.AmazonKinesisClient;
import com.amazonaws.services.kinesis.model.CreateStreamRequest;
import com.amazonaws.services.kinesis.model.DescribeStreamRequest;
import com.amazonaws.services.kinesis.model.DescribeStreamResult;
import com.amazonaws.services.kinesis.model.PutRecordRequest;
import com.amazonaws.services.kinesis.model.PutRecordResult;
import com.amazonaws.services.kinesis.model.PutRecordsRequest;
import com.amazonaws.services.kinesis.model.PutRecordsRequestEntry;
import com.amazonaws.services.kinesis.model.PutRecordsResult;
import com.amazonaws.services.kinesis.model.PutRecordsResultEntry;
import com.amazonaws.services.kinesis.model.ResourceNotFoundException;
import com.amazonaws.services.kinesis.model.StreamDescription;

Does any of that make sense?  Can I build from source what I need in C++ 
from those libraries above???

Thanks,
Scott.

**Comment by scotthbradley** [comment]
Ok, so.. some developers attempted to build the AWS libraries on the RaspberryPi 3 before without success... Unfortunately, looking at the README.MD in the source directory, it states clearly that the builds may fail if built on a system with less than 4GB of ram.  The RaspberryPi has only 1GB of ram, so ... does that mean I will have problems building many parts of the system with that small amount of ram???  Also, there is no way to increase the ram on a RaspberryPi for any reason (I've checked that out already...)  What do you suggest???

**Comment by JonathanHenson** [comment]
Cross compilation. Also ec2 on GCC is likely the only sdk you would have trouble with. If you use clang it will be fine. Also use the BUILD_ONLY cmake arg to build only the services you need.

**Comment by JonathanHenson** [comment]
were you able to resolve this?

**Comment by scotthbradley** [comment]
hey, thanks for thinking of me.

i have not resolved this yet because I was interrupted from the project to
work on several other things. I plan to get back to it at some point, but
not quite yet.

**Comment by singku** [comment]
Hello, were you able to build your own binary on Raspberry PI? We have successfully built it on our own, but we haven't had a plan to supply downloadable binary officially yet.

**Comment by singku** [comment]
Closing since no further response from user.
