### ISSUE TITLE
Android Runtime Crash (Assembly Callstack)

### ISSUE THREAD

**Issue by AMZN-Gene** [aws/aws-sdk-cpp#3047]
### Describe the bug

Android runtime crash on startup migrating from 1.11.288 to 1.11.361

### Expected Behavior

No runtime crash

### Current Behavior

Unfortunately, the stack trace is in assembly. I've only narrowed down the change to just my AWS SDK version. So it could be that I incorrectly built the SDK.
```
art_sigsegv_fault 0x0000007129512544
art::FaultManager::HandleFault(int, siginfo*, void*) 0x0000007129512aa4
art::SignalChain::Handler(int, siginfo*, void*) 0x000000741caa0340
__kernel_rt_sigreturn 0x0000007443d4d668
<unknown> 0x0000000000000008
``` 

### Reproduction Steps

1) Build 1.11.361 AWS SDK
```
cmake -S %SRC_PATH% -B %BLD_PATH%\%BUILD_TYPE%_%LIB_TYPE% ^
           -G Ninja ^
           -DNDK_DIR="%ANDROID_NDK_ROOT%" ^
           -DBUILD_SHARED_LIBS=%BUILD_SHARED% ^
           -DCMAKE_BUILD_TYPE="%BUILD_TYPE%" ^
           -DTARGET_ARCH=ANDROID ^
           -DANDROID_NATIVE_API_LEVEL=21 ^
           -DANDROID_ABI=arm64-v8a ^
           -DCPP_STANDARD=17 ^
           -DCMAKE_C_FLAGS="-fPIC" ^
           -DCMAKE_CXX_FLAGS="-fPIC" ^
           -DBUILD_ONLY="access-management;bedrock-runtime;cognito-identity;cognito-idp;core;devicefarm;dynamodb;gamelift;identity-management;kinesis;lambda;queues;s3;sns;sqs;sts;transfer" ^
           -DENABLE_TESTING=OFF ^
           -DENABLE_RTTI=ON ^
           -DCUSTOM_MEMORY_MANAGEMENT=ON^
           -DCMAKE_INSTALL_BINDIR="bin/%BUILD_TYPE%_%LIB_TYPE%" ^
           -DCMAKE_INSTALL_LIBDIR="lib/%BUILD_TYPE%_%LIB_TYPE%" ^
           -DCMAKE_INSTALL_PREFIX="%BLD_PATH%/%BUILD_TYPE%_%LIB_TYPE%" ^
           -DANDROID_BUILD_OPENSSL=ON ^
           -DANDROID_BUILD_ZLIB=OFF ^
           -DANDROID_BUILD_CURL=ON ^
           -DCMAKE_MODULE_PATH="%DOWNLOADED_PACKAGE_FOLDERS%" 
2) Deploy to Android app using AWS SDK and make a simple call to AWS, for example CurlHTTPClient
3) See crash

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### AWS CPP SDK version used

1.11.361

### Compiler and Version used

Android NDK 25.2.9519653

### Operating System and version

Android Pixel 3

**Comment by sbiscigl** [comment]
> I've only narrowed down the change to just my AWS SDK version. 
> Deploy to Android app using AWS SDK and make a simple call to AWS, for example CurlHTTPClient

I see you say "any SDK call", and "Pixel 3". if that is the case i need to know the exact reproducible source you are using to call as well as how you are creating your environment. There is just not a lot to go off of here. can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). The error you are seeing is a seg fault, but i dont know what you are trying to run and where you are trying to run it. Please include minimal source that can be used to reproduce this error, and how to create the runtime environment you are seeing it in.
