### ISSUE TITLE
Where is InvalidAccessKeyId error code (and others)?

### ISSUE THREAD

**Issue by SebastianSikora** [aws/aws-sdk-cpp#305]
Hi!

I'm trying to properly handle S3Client errors. I am invoking S3Client::ListBuckets method with incorrect access key by purpose. I was expecting to get some meaningfull error code, but ListBuckerOutcome::GetError().GetErrorType() returns only S3Errors::UNKNOWN while ListBuckerOutcome::GetError().GetExceptionName() returns "InvalidAccessKeyId".

Same thing when I put incorrect secret key, but then I will get exception name: "SignatureDoeanNotMatch" and S3Errors::UNKNOWN error code.

Why S3Errors.h does not contain all error codes ?

Thanks in advance.

**Comment by JonathanHenson** [comment]
Because some of these errors, unfortunately, aren't documented and we don't know about them until we encounter them. I'll get these added to the generator ASAP.

**Comment by SebastianSikora** [comment]
Thank you for response.

**Comment by JonathanHenson** [comment]
I pushed out SignatureDoesNotMatch a while back when I added clock skew detection. But forgot about InvalidAccessKeyId. I went ahead and added that one as well. The change is currently running through our CI. I'll push it out today.
