### ISSUE TITLE
Support for ipv6 address in s3 ClientConfiguration

### ISSUE THREAD

**Issue by Pradnyeshp** [aws/aws-sdk-cpp#3054]
### Describe the feature

I want to use ipv6 address while setting Aws::Client::ClientConfiguration endpointOverride

Similar old post: https://github.com/aws/aws-sdk-cpp/issues/1549

Is this supported in latest release ? Can you provide related documentation.

### Use Case

I can't use direct ip address in endpoint override, i need to depend on DNS lookup.
I want to remove DNS dependency 

### Proposed Solution

I should be able to provide ipv6 address directly in ClientConfiguration endpointOverride

### Other Information

I am accessing S3 through a private endpoint

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jmklix** [comment]
S3 now supports IPv6. [Here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ipv6-access.html) is a documentation page for how to make requests s3 requests over IPv6. Please let us know if you run into any problems when trying this.

**Comment by Pradnyeshp** [comment]
The above documentation suggests using `dualstack` param with clientConfig.
But when i try to use `dualstack` with endpointOverride i get error saying you can't use dualStack and endpointOverride together.

**Comment by DmitriyMusatkin** [comment]
Are you getting any error? It should just work if you set endpointOverride to the ipv6 address you are trying to connect to. 
Note: the typical caveat of connecting using the pure ip is that san on the cert might not match the ip, so you might have to disable peer validation to get it to work. 

you dont need to set dual stack in this case. that setting is only use to indicate to sdk that it should prefer the ipv6 endpoint when it resolves the service endpoint. overriding endpoint achieves the same goal
