### ISSUE TITLE
DescribeSpotFleetRequests fails with "The action DescribeSpotFleets is not valid for this web service"

### ISSUE THREAD

**Issue by yasushi-saito** [aws/aws-sdk-cpp#306]
Aws::Client::ClientConfiguration config;
  config.scheme = Aws::Http::Scheme::HTTPS;
  config.region = Aws::Region::US_WEST_2;
  auto ec2 = Aws::MakeSharedAws::EC2::EC2Client("ec2", config);
    Aws::EC2::Model::DescribeSpotFleetRequestsOutcome response =
        ec2->DescribeSpotFleetRequests(
            Aws::EC2::Model::DescribeSpotFleetRequestsRequest());
    if (!response.IsSuccess()) {
      LOG(ERROR) << "Failed: " << response.GetError().GetExceptionName() << "/"
                 << response.GetError().GetMessage();
  }

This program fails with:

[DEBUG] 2016-10-12 09:23:07 CurlHttpClient [139850741016512] Returned http response code 400
[DEBUG] 2016-10-12 09:23:07 CurlHttpClient [139850741016512] Releasing curl handle 0x2de2000
[DEBUG] 2016-10-12 09:23:07 CurlHandleContainer [139850741016512] Releasing curl handle 0x2de2000
[DEBUG] 2016-10-12 09:23:07 CurlHandleContainer [139850741016512] Notified waiting threads.
[DEBUG] 2016-10-12 09:23:07 AWSClient [139850741016512] Request returned error. Attempting to generate appropriate error codes from response
[TRACE] 2016-10-12 09:23:07 AWSClient [139850741016512] Error response is <?xml version="1.0"?>
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Errors>
        <Error>
            <Code>InvalidAction</Code>
            <Message>The action DescribeSpotFleets is not valid for this web service.</Message>
        </Error>
    </Errors>
    <RequestID>95a05126-5426-4050-b918-0127eaae436f</RequestID>
</Response>

I'm guessing this is a typo of DescribeSpotFleetRequests.

**Comment by JonathanHenson** [comment]
This is a bug in our generator, will add this to our backlog and get it updated ASAP.

**Comment by yasushi-saito** [comment]
Any update on this? It's still broken as of 1.0.34.

**Comment by bretambrose** [comment]
This will be fixed in a release next week.

**Comment by bretambrose** [comment]
Fixed in yesterday's release.
