### ISSUE TITLE
AWS transcribe aws-sdk-cpp above  1.11.283 version CPU spikes more then 100%

### ISSUE THREAD

**Issue by vdharashive** [aws/aws-sdk-cpp#3079]
### Describe the bug

Reported issue in below thread is not resolved 

https://github.com/aws/aws-sdk-cpp/issues/2779

### Expected Behavior

Performance issue with asr aws transcribe

### Current Behavior

CPU usage for each connection goes avg 80%

### Reproduction Steps

yes its reproducible 

### AWS CPP SDK version used

1.11.283

### Compiler and Version used

gcc (Debian 12.2.0-14) 12.2.0

### Operating System and version

Debian GNU/Linux 12 (bookworm)

**Comment by vdharashive** [comment]
https://github.com/jambonz/freeswitch-modules/tree/main/mod_aws_transcribe
 
is code implementation  

@davehorton

**Comment by jmklix** [comment]
We are currently looking into this.

**Comment by jmklix** [comment]
We added an [additional configuration](https://github.com/aws/aws-sdk-cpp/commit/8aa531312ae30f05ee7fbf20a67aa2af075f088a) to help avoid cpu spikes when using transcribe. Please update to the latest version of this sdk and let us know if you have any other questions/concerns when using this sdk.

**Comment by vdharashive** [comment]
@jmklix will test and let you know thank you very much

**Comment by vdharashive** [comment]
@jmklix having LOW_LATENCY and REGULAR is not ideal solution , since for real-time transcript with REGUALR does not respond quick enough and gets stuck, i dont think is right way to address the issue 

does using websocket api will solve this problem ?

**Comment by jmklix** [comment]
Can you elaborate on what you exactly mean with "REGUALR does not respond quick enough and gets stuck"? How quickly are you expecting this sdk to respond? 

What are your thoughts/suggestions on the correct way to fix this issue? How would you have websocket api to improve this?
