### ISSUE TITLE
sigfault on Aws::InitAPI(Aws::SDKOptions const&) with clang36

### ISSUE THREAD

**Issue by vsakharuk** [aws/aws-sdk-cpp#308]
Following code works with icc 16 and gcc 5.4 but cores with clang36
    Aws::SDKOptions m_options;
    m_options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Info;
    Aws::InitAPI(m_options);

Core dump is:
#0  0x0000000000000000 in ?? ()
#1  0x00007fffe0fa9f23 in Aws::InitAPI(Aws::SDKOptions const&) () from  (...)/aws-sdk-cpp/1.0.5/lib/libaws-cpp-sdk-core.so
...

Help appreciated

p m_options
$3 = {loggingOptions = {logLevel = Aws::Utils::Logging::LogLevel::Info, defaultLogPrefix = 0x7fffe4e4841b "aws_sdk_", 
    logger_create_fn = {<std::__1::__function::__maybe_derive_from_unary_function<std::__1::shared_ptr<Aws::Utils::Logging::LogSystemInterface> ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<std::__1::shared_ptr<Aws::Utils::Logging::LogSystemInterface> ()>> = {<No data fields>}, __buf_ = {
        __lx = '\000' <repeats 23 times>}, __f_ = 0x0}}, memoryManagementOptions = {memoryManager = 0x0}, httpOptions = {
    httpClientFactory_create_fn = {<std::__1::__function::__maybe_derive_from_unary_function<std::__1::shared_ptr<Aws::Http::HttpClientFactory> ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<std::__1::shared_ptr<Aws::Http::HttpClientFactory> ()>> = {<No data fields>}, __buf_ = {
        __lx = '\000' <repeats 23 times>}, __f_ = 0x0}, initAndCleanupCurl = true}, cryptoOptions = {
    md5Factory_create_fn = {<std::__1::__function::__maybe_derive_from_unary_function<std::__1::shared_ptr<Aws::Utils::Crypto::HashFactory> ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<std::__1::shared_ptr<Aws::Utils::Crypto::HashFactory> ()>> = {<No data fields>}, __buf_ = {
        __lx = "\006=\241د*\301\354`\211R\001\000\000\000\000Њb\002\000\000\000"}, __f_ = 0x0}, 
    sha256Factory_create_fn = {<std::__1::__function::__maybe_derive_from_unary_function<std::__1::shared_ptr<Aws::Utils::Crypto::HashFactory> ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<std::__1::shared_ptr<Aws::Utils::Crypto::HashFactory> ()>> = {<No data fields>}, __buf_ = {
        __lx = "h\263\327!\023\353_.\020^\230\001\000\000\000\000\210\064w\002\000\000\000"}, __f_ = 0x0}, 
    sha256HMACFactory_create_fn = {<std::__1::__function::__maybe_derive_from_unary_function<std::__1::shared_ptr<Aws::Utils::Crypto::HMACFactory> ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<std::__1::shared_ptr<Aws::Utils::Crypto::HMACFactory> ()>> = {<No data fields>}, __buf_ = {
        __lx = '\000' <repeats 23 times>}, __f_ = 0x0}, 
    aes_CBCFactory_create_fn = {<std::__1::__function::__maybe_derive_from_unary_function<std::__1::shared_ptr<Aws::Utils::Crypto::SymmetricCipherFactory> ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<std::__1::shared_ptr<Aws::Utils::Crypto::SymmetricCipherFactory> ()>> = {<No data fields>}, __buf_ = {
        __lx = '\000' <repeats 23 times>}, __f_ = 0x0}, 
    aes_CTRFactory_create_fn = {<std::__1::__function::__maybe_derive_from_unary_function<std::__1::shared_ptr<Aws::Utils::Crypto::SymmetricCipherFactory> ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<std::__1::shared_ptr<Aws::Utils::Crypto::SymmetricCipherFactory> ()>> = {<No data fields>}, __buf_ = {
        __lx = '\000' <repeats 23 times>}, __f_ = 0x0}, 
    aes_GCMFactory_create_fn = {<std::__1::__function::__maybe_derive_from_unary_function<std::__1::shared_ptr<Aws::Utils::Crypto::SymmetricCipherFactory> ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<std::__1::shared_ptr<Aws::Utils::Crypto::SymmetricCipherFactory> ()>> = {<No data fields>}, __buf_ = {
        __lx = '\000' <repeats 23 times>}, __f_ = 0x0}, 
    aes_KeyWrapFactory_create_fn = {<std::__1::__function::__maybe_derive_from_unary_function<std::__1::shared_ptr<Aws::Utils::Crypto::SymmetricCipherFactory> ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<std::__1::shared_ptr<Aws::Utils::Crypto::SymmetricCipherFactory> ()>> = {<No data fields>}, 
      __buf_ = {__lx = '\000' <repeats 23 times>}, __f_ = 0x0}, 
    secureRandomFactory_create_fn = {<std::__1::__function::__maybe_derive_from_unary_function<std::__1::shared_ptr<Aws::Utils::Crypto::SecureRandomFactory> ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<std::__1::shared_ptr<Aws::Utils::Crypto::SecureRandomFactory> ()>> = {<No data fields>}, __buf_ = {
        __lx = '\000' <repeats 23 times>}, __f_ = 0x0}, initAndCleanupOpenSSL = true}

**Comment by vsakharuk** [comment]
I suspect that problem is following:
1) library was compiled with gcc
2) binary was compiled with clang.
clang stl is not compartible with gcc in above use.

**Comment by JonathanHenson** [comment]
That seems a likely suspect. We have similar problems building for android. Best to keep everything to the same toolchain for the time being.

**Comment by bretambrose** [comment]
Closing for now.  Feel free to reopen if you encounter additional issues.
