### ISSUE TITLE
AWS SDK CPP. Transcribe streaming doesn't work

### ISSUE THREAD

**Issue by sem32** [aws/aws-sdk-cpp#3086]
### Describe the bug

Hi!

The issue: transcribe streaming doesn't work with CRTHttpClient for SDK's version more than 1.11.252. For 1.11.252 it's ok.

Why we are using CRT HTTP CLIENT?
We are using it because we have a performance issue when we use lib CURL.

With the version of CURL 7.87 the quality of the transcribe was good, but CPU usage was too high (every 3-5 sec spike of CPU usage to 100%). For one transcribing process is more or less OK, but for 30 is not).
With the version of CURL 7.88 we faced an issue with the quality of the transcribe (it looks like the CURL library does some optimization), but we had no performance issue.
We have no issue with the quality and performance with the CRT http client, so we have to use it.

After we've update the SDK to newest version, the SDK stopped to work.

After this logs, the connection is closing:
```
Message received, the expected length of the message is: 188 bytes, and the expected length of the header is: 97 bytes
```

I found the similar issue but it was in 2021
https://github.com/aws/aws-sdk-cpp/issues/1806

[logs.txt](https://github.com/user-attachments/files/16736647/aws_transcribe_issue_1.11.390.txt)

### Expected Behavior

I can use CRTHttpClient for new versions of SDK with no issue for realtime transcribe.

### Current Behavior

No way use CRTHttpClient for new versions of SDK. The session is closing, can write audio event.

### Reproduction Steps

```
git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp.git
cd aws-sdk-cpp
git checkout --recurse-submodules 1.11.390
mkdir sdk_build && cd sdk_build
cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/ -DCMAKE_INSTALL_PREFIX=/usr/local/ -DBUILD_ONLY="transcribestreaming;polly" -DUSE_CRT_HTTP_CLIENT=1
make && sudo make install
```
Use libs for realtime transcribe. Can't WriteAudioEvent, got an error.

### AWS CPP SDK version used

1.11.390

### Compiler and Version used

gcc 12.2.0 

### Operating System and version

Debian 12

**Comment by jmklix** [comment]
We are working on some PR's to fix this: https://github.com/awslabs/aws-crt-cpp/pull/658, https://github.com/aws/aws-sdk-cpp/pull/3097

**Comment by jmklix** [comment]
The PR has been merged and is now in the latest release. Please update and let us know if you have any other problems with this sdk
