### ISSUE TITLE
s3 file upload error

### ISSUE THREAD

**Issue by gopi77** [aws/aws-sdk-cpp#310]
Hi

As per this link, https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/
I made a project and able to upload the string example.

Then i tried to upload a jpeg file as per this link, https://forums.aws.amazon.com/thread.jspa?messageID=712685

But the putObjectOutcome is failure.
The error is >> Error while putting Object BadRequest Unable to parse ExceptionName: BadRequest Message: An error occurred when parsing the HTTP request.

My code (main.cpp) below.

#include <aws/s3/S3Client.h>
#include <aws/s3/model/PutObjectRequest.h>
#include <aws/s3/model/GetObjectRequest.h>
#include <aws/core/Aws.h>
#include <aws/core/utils/memory/stl/AwsStringStream.h> 

#include <iostream>
#include <fstream>
#include <ctime>

using namespace std;

// IMPORTANT:
// Set belew environment values before running code
// 1. AWS_ACCESS_KEY_ID <get this value from aws s3>
// 2. AWS_SECRET_ACCESS_KEY <get this value from aws s3>

using namespace Aws::S3;
using namespace Aws::S3::Model;

static const char* KEY = "aws_cpp_sdk_upload_test"; // "s3_cpp_sample_key";
static const char* BUCKET = "emojiface-photobooth"; // "s3-cpp-sample-bucket";

int main()
{
	Aws::SDKOptions options;
	Aws::InitAPI(options);
	S3Client client;

	//first put an object into s3
	PutObjectRequest putObjectRequest;
	putObjectRequest.WithKey(KEY)
		.WithBucket(BUCKET);

	string filePATH = "planets.jpg";

	std::ifstream  src3(filePATH, std::ios::binary);
	std::ofstream  dst3("out_" + filePATH, std::ios::binary);

	dst3 << src3.rdbuf();

	std::shared_ptr<Aws::FStream> fileToUpload = Aws::MakeShared<Aws::FStream>("OCRFile", filePATH, ios::in | ios::binary | ios::trunc);
	putObjectRequest.SetBody(fileToUpload);
	putObjectRequest.SetContentType("image/jpeg");
	putObjectRequest.SetContentLength(static_cast<long>(putObjectRequest.GetBody()->tellg()));

	auto putObjectOutcome = client.PutObject(putObjectRequest);

	if (putObjectOutcome.IsSuccess())
	{
		std::cout << "Put object succeeded" << std::endl;
	}
	else
	{
		std::cout << "Error while putting Object " << putObjectOutcome.GetError().GetExceptionName() <<
			" " << putObjectOutcome.GetError().GetMessage() << std::endl;
	}

	//now get the object back out of s3. The response stream can be overridden here if you want it to go directly to 
	// a file. In this case the default string buf is exactly what we want.
	GetObjectRequest getObjectRequest;
	getObjectRequest.WithBucket(BUCKET)
		.WithKey(KEY);

	auto getObjectOutcome = client.GetObject(getObjectRequest);

	if (getObjectOutcome.IsSuccess())
	{
		std::cout << "Successfully retrieved object from s3 with value: " << std::endl;
		std::cout << getObjectOutcome.GetResult().GetBody().rdbuf() << std::endl << std::endl;;
	}
	else
	{
		std::cout << "Error while getting object " << getObjectOutcome.GetError().GetExceptionName() <<
			" " << getObjectOutcome.GetError().GetMessage() << std::endl;
	}

	Aws::ShutdownAPI(options);
	return 0;
}

**Comment by JonathanHenson** [comment]
Tellg() returns the current input position, which is zero when you set the content length. You can either seek to the end first then call tellg then seek it back or just let the sdk do it for you. Since content-length is 0 the server doesn't know what to do with your request body.

**Comment by gopi77** [comment]
Thanks, this helped to move ahead.
Some other issue now (Error while putting Object  Unable to connect to endpoint), will raise separate issue for this.
