### ISSUE TITLE
s3 file upload Error while putting Object  Unable to connect to endpoint

### ISSUE THREAD

**Issue by gopi77** [aws/aws-sdk-cpp#311]
Hi
I am getting this error while uploading a file.
Error: s3 file upload Error while putting Object  Unable to connect to endpoint
My jpeg file size was 294 KB.

I tried the solution in this link but no improvement,
http://stackoverflow.com/questions/38647444/aws-c-s3-sdk-putobjectrequest-unable-to-connect-to-endpoint.

Please help me to fix this one.
My code below.

static const char* KEY = "aws_cpp_sdk_upload_test"; // "s3_cpp_sample_key";
static const char* BUCKET = "emojiface-photobooth"; // "s3-cpp-sample-bucket";

int main()
{
	Aws::Client::ClientConfiguration clientConfig;
	clientConfig.scheme = Aws::Http::Scheme::HTTPS;
	clientConfig.region = Aws::Region::US_EAST_1;
	clientConfig.connectTimeoutMs = 30000;

	Aws::SDKOptions options;
	Aws::InitAPI(options);
	S3Client client(clientConfig);

	//first put an object into s3
	PutObjectRequest putObjectRequest;
	putObjectRequest.WithKey(KEY)
		.WithBucket(BUCKET);

	string filePATH = "planets.jpg";

	std::shared_ptr<Aws::FStream> fileToUpload = Aws::MakeShared<Aws::FStream>("OCRFile", filePATH, ios::in | ios::binary | ios::trunc);
	
	std::streampos fsize = 0;
	std::ifstream file(filePATH, std::ios::binary);

	fsize = file.tellg();
	file.seekg(0, std::ios::end);
	fsize = file.tellg() - fsize;
	file.close();

	putObjectRequest.SetBody(fileToUpload);

	putObjectRequest.GetBody()->seekg(0, std::ios::end);

	putObjectRequest.SetContentType("image/jpeg");
	putObjectRequest.SetContentLength(static_cast<long>(fsize));

	std::cout << "Entering into PutObject\n" << std::endl;

	auto putObjectOutcome = client.PutObject(putObjectRequest);

	if (putObjectOutcome.IsSuccess())
	{
		std::cout << "Put object succeeded" << std::endl;
	}
	else
	{
		std::cout << "Error while putting Object " << putObjectOutcome.GetError().GetExceptionName() <<
			" " << putObjectOutcome.GetError().GetMessage() << std::endl;
	}

	//now get the object back out of s3. The response stream can be overridden here if you want it to go directly to 
	// a file. In this case the default string buf is exactly what we want.
	GetObjectRequest getObjectRequest;
	getObjectRequest.WithBucket(BUCKET)
		.WithKey(KEY);

	auto getObjectOutcome = client.GetObject(getObjectRequest);

	if (getObjectOutcome.IsSuccess())
	{
		std::cout << "Successfully retrieved object from s3 with value: " << std::endl;
		//std::cout << getObjectOutcome.GetResult().GetBody().rdbuf() << std::endl << std::endl;;
	}
	else
	{
		std::cout << "Error while getting object " << getObjectOutcome.GetError().GetExceptionName() <<
			" " << getObjectOutcome.GetError().GetMessage() << std::endl;
	}

	Aws::ShutdownAPI(options);
	return 0;
}

**Comment by emojiface** [comment]
I'm having the same problem. I can upload a string but not an image. Has anyone else had issues uploading images to S3?

**Comment by buildmaster** [comment]
I'm getting the same issue just trying to do a HEAD request on an object. Debug log has this repeatedly as it retries (#REDACTED# is me replacing hashes and info)
```
[DEBUG] 2016-10-18 07:06:51 AWSAuthV4Signer [140700699002688] Note: Http payloads are not being signed. signPayloads=0 http scheme=https
[DEBUG] 2016-10-18 07:06:51 AWSAuthV4Signer [140700699002688] Canonical Header String: content-type:application/xml
host:s3.amazonaws.com
user-agent:aws-sdk-cpp/1.0.7 Linux/4.4.24-moby x86_64
x-amz-content-sha256:UNSIGNED-PAYLOAD
x-amz-date:20161018T070651Z

[DEBUG] 2016-10-18 07:06:51 AWSAuthV4Signer [140700699002688] Signed Headers value:content-type;host;user-agent;x-amz-content-sha256;x-amz-date
[DEBUG] 2016-10-18 07:06:51 AWSAuthV4Signer [140700699002688] Canonical Request String: HEAD
#REDACTED#

content-type:application/xml
host:s3.amazonaws.com
user-agent:aws-sdk-cpp/1.0.7 Linux/4.4.24-moby x86_64
x-amz-content-sha256:UNSIGNED-PAYLOAD
x-amz-date:20161018T070651Z

content-type;host;user-agent;x-amz-content-sha256;x-amz-date
UNSIGNED-PAYLOAD
[DEBUG] 2016-10-18 07:06:51 AWSAuthV4Signer [140700699002688] Final String to sign: AWS4-HMAC-SHA256
20161018T070651Z
20161018/us-east-1/s3/aws4_request
#REDACTED#
[DEBUG] 2016-10-18 07:06:51 AWSAuthV4Signer [140700699002688] Final computed signing hash: #REDACTED#
[DEBUG] 2016-10-18 07:06:51 AWSAuthV4Signer [140700699002688] Signing request with: AWS4-HMAC-SHA256 Credential=#REDACTED#/20161018/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=#REDACTED#
[DEBUG] 2016-10-18 07:06:51 AWSClient [140700699002688] Request Successfully signed
[DEBUG] 2016-10-18 07:06:51 CurlHandleContainer [140700699002688] Attempting to acquire curl connection.
[INFO] 2016-10-18 07:06:51 CurlHandleContainer [140700699002688] Connection has been released. Continuing.
[DEBUG] 2016-10-18 07:06:51 CurlHandleContainer [140700699002688] Returning connection handle 0x242bf10
[DEBUG] 2016-10-18 07:06:51 CurlHttpClient [140700699002688] Obtained connection handle 0x242bf10
[ERROR] 2016-10-18 07:06:52 CurlHttpClient [140700699002688] Curl returned error code 28
[DEBUG] 2016-10-18 07:06:52 CurlHandleContainer [140700699002688] Releasing curl handle 0x242bf10
[DEBUG] 2016-10-18 07:06:52 CurlHandleContainer [140700699002688] Notified waiting threads.
[DEBUG] 2016-10-18 07:06:52 AWSClient [140700699002688] Request returned error. Attempting to generate appropriate error codes from response
[WARN] 2016-10-18 07:06:52 AWSClient [140700699002688] Request failed, now waiting 400 ms before attempting again.
```

**Comment by bretambrose** [comment]
To the original poster, can you post your log of a failing request?

**Comment by gopi77** [comment]
Hi

From my previous code i did two changes
1. clientConfig.requestTimeoutMs = 30000;
2. tried uploading a Readme.txt file instead of jpg
3. added 	options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;

Logs below:

[aws_sdk_2016-10-18-19_txt.log.txt](https://github.com/aws/aws-sdk-cpp/files/536490/aws_sdk_2016-10-18-19_txt.log.txt)

**Comment by bretambrose** [comment]
Reading through the code, you seek to the end of the body stream and then never reset it.  Rather than two streams, you should just be able to use one.  For a working example, see BucketAndObjectOperationTest.cpp:450 (the TestObjectOperations test in the s3 integration tests).

**Comment by gopi77** [comment]
Hi

Please refer this one, i changed the computation as per this suggestion.
Also BucketAndObjectOperationTest.cpp:450 has only string upload, not the file upload

**Comment by bretambrose** [comment]
Can you make a new issue that includes the full code sample as well as the resulting log?  Cross referencing across issues for logs and (possibly modified) code is too confusing to reason with certainty about.

**Comment by gopi77** [comment]
just to clarify

        std::shared_ptr<Aws::IOStream> objectStream = Aws::MakeShared<Aws::StringStream>("BucketAndObjectOperationTest");
        *objectStream << "Test Object";
        objectStream->flush();
        putObjectRequest.SetBody(objectStream);
        putObjectRequest.SetContentLength(static_cast<long>(putObjectRequest.GetBody()->tellp()));

the putObjectRequest.GetBody()->tellp() returned wrong number, #310 helped to fix it, but stuck with #311 now

**Comment by gopi77** [comment]
my present code (cleaned one)

int main()
{
	Aws::Client::ClientConfiguration clientConfig;
	clientConfig.scheme = Aws::Http::Scheme::HTTPS;
	clientConfig.region = Aws::Region::US_EAST_1;
	clientConfig.requestTimeoutMs = 30000;
	clientConfig.connectTimeoutMs = 30000;

	Aws::SDKOptions options;
	options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;

	Aws::InitAPI(options);
	S3Client client(clientConfig);

	//first put an object into s3
	PutObjectRequest putObjectRequest;
	putObjectRequest.WithKey(KEY)
		.WithBucket(BUCKET);

	string filePATH = "Readme.txt";

	std::ifstream file(filePATH, std::ios::binary);
	std::streampos fsize = file.tellg();

	file.seekg(0, std::ios::end);
	fsize = file.tellg() - fsize;

	file.close();
	std::cout << "file size = " << fsize << "\n" << std::endl;

	std::shared_ptr<Aws::FStream> fileToUpload = Aws::MakeShared<Aws::FStream>("OCRFile", filePATH, ios::in | ios::binary | ios::trunc);
	putObjectRequest.SetBody(fileToUpload);

	putObjectRequest.SetContentType("text/plain");
	putObjectRequest.SetContentLength(static_cast<long>(fsize));

	std::cout << "Entering into PutObject\n" << std::endl;

	auto putObjectOutcome = client.PutObject(putObjectRequest);

	if (putObjectOutcome.IsSuccess())
	{
		std::cout << "Put object succeeded" << std::endl;
	}
	else
	{
		std::cout << "Error while putting Object " << putObjectOutcome.GetError().GetExceptionName() <<
			" " << putObjectOutcome.GetError().GetMessage() << std::endl;
	}
....

***************************************
My Readme.txt has the below contents
aws s3 file transfer test

***************************************
The command window contents below:

file size = 25

Entering into PutObject

Error while putting Object RequestTimeout Unable to parse ExceptionName: RequestTimeout Message: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.

Also attached the logs.
[aws_sdk_2016-10-18-22.log.txt](https://github.com/aws/aws-sdk-cpp/files/536871/aws_sdk_2016-10-18-22.log.txt)

**Comment by JonathanHenson** [comment]
After seeking to the end you need to seek back to the beginning. You also can just not set content length manually and we will handle it for you.

**Comment by gopi77** [comment]
Is it possible to modify my code & show the example ? (few important lines are enough)

**Comment by JonathanHenson** [comment]
I'm on my way into the office at the moment, will respond when I arrive.

**Comment by bretambrose** [comment]
What happens when you drop std::ios::binary | std::ios::trunc from fileToUpload?

**Comment by gopi77** [comment]
dropping std::ios::binary | std::ios::trunc from fileToUpload helps in successful upload of Readme.txt file. Thanks.

But still fails to upload jpeg files.
Code below.

	string filePATH = "planets.jpg";

	std::shared_ptr<Aws::FStream> fileToUpload = Aws::MakeShared<Aws::FStream>("OCRFile", filePATH, ios::in);
	putObjectRequest.SetBody(fileToUpload);

	putObjectRequest.SetContentType("image/jpeg");

![planets](https://cloud.githubusercontent.com/assets/12639784/19489094/5fe607e4-9587-11e6-9b4a-1caf001e09bb.jpg)

**Comment by gopi77** [comment]
ok added binary word & works now.

std::shared_ptr<Aws::FStream> fileToUpload = Aws::MakeShared<Aws::FStream>("OCRFile", filePATH, ios::in | std::ios::binary);

**Comment by bretambrose** [comment]
Sounds like everything's working now, so I'll go ahead and close this.

**Comment by gopi77** [comment]
Thanks a lot for your support, yes good to close it :)
