### ISSUE TITLE
ERROR: Unable to connect to endpoint

### ISSUE THREAD

**Issue by Vleena1** [aws/aws-sdk-cpp#3114]
we are trying the access the AWS bucket from the Linux server using the utility call ssadrv as shown below

ssadrv -a aws_sdk://<bucket_name>/<aws_url_along with bucketname>

Eg: ssadrv -a aws_sdk://PER/https://s3.us-east-1.aws.amazon.com/infagcs/PER

bucket was not accessible from Linux server, hence we have added the following library "libaws-cpp-sdk-core.so" to the Linux server and issue got resolved, now we are try to delete the data from the AWS bucket file from the Linux server, but it is failing with the following error message
"ERROR: ERROR: Exception Name:, Error Message:Unable to connect to endpoint".

Please let us the answers for below queries:
1: Which scenario the endpoint error will trigger, Is there any configuration missing?
2: How we can find the aws sdk version from RHEL 8 Linux server ? 
3: Is this library "libaws-cpp-sdk-core.so" is compatible with RHEL 8 server?

**Comment by sbiscigl** [comment]
> using the utility call ssadrv 

what is this utility? where is it defined? how do the call the aws sdk?

> hence we have added the following library "libaws-cpp-sdk-core.so" to the Linux server and issue got resolved

why did adding the library fix it? how are you actually using the SDK?

> We are using AWS C++ SDK version 1.4.50.

That commit is 6 years old, why are you using that old of a version?

Overall I'm not following what you are asking. This sounds like a third party tool that is using a very old version of the SDK. I would suggest contacting the owner of this tool.

If you can provide code using the SDK to replicate your issue we can help
