### ISSUE TITLE
Route53 ListHostedZones doesn't work for regions other than us-east-1.

### ISSUE THREAD

**Issue by yasushi-saito** [aws/aws-sdk-cpp#313]
If I set Aws::Client::ClientConfiguration::region to "us-west-2" (that's where we have all our data), 
Aws::Route53::ListHostedZones tries to connect to route53.us-west-2.amazonaws.com, which doesn't exist. Reverse engineering the aws cli, it looks like we need to always talk to route53.amazonaws.com  to list zones.

**Comment by JonathanHenson** [comment]
I'd recommend a separate client config instance per client.

**Comment by JonathanHenson** [comment]
ROUTE 53 is always us-east-1 (or a global endpoint).
