### ISSUE TITLE
Assertion thrown while using aws-cpp-sdk-cognito-identity.dll

### ISSUE THREAD

**Issue by pmanish77** [aws/aws-sdk-cpp#314]
Hi,

I am using AWS CPP SDK to write an application to authenticate the users.  Linked the application to cognito-identity package through NuGet. 
On running the application I am getting the assertion as seen in the attached screenshot.  Not sure what could be causing this issue.
Also wanted to know if there are any samples in C++ for authenticating user credentials. Basically I want to check if the user is valid or not.

Below is the code snippet written by me
# define MY_ACCOUNT_ID   "my-account-id"
# define MY_POOL_ID  "my-pool-id"

```
Aws::SDKOptions options;
Aws::InitAPI(options);

std::shared_ptr<Aws::Auth::AnonymousAWSCredentialsProvider> cred;
Aws::Client::ClientConfiguration clientConfig;
clientConfig.region = "RegionEndpoint.USEast1";

Aws::CognitoIdentity::CognitoIdentityClient cognitoClient;
Aws::CognitoIdentity::Model::GetIdRequest idRequest;
idRequest = Aws::CognitoIdentity::Model::GetIdRequest();

idRequest.SetAccountId(MY_ACCOUNT_ID);
idRequest.SetIdentityPoolId(MY_POOL_ID);

Aws::CognitoIdentity::Model::GetIdOutcome idResp = cognitoClient.GetId(idRequest);

    if (idResp.IsSuccess())
    {
        Aws::CognitoIdentity::Model::GetOpenIdTokenRequest openIdReq;
        Aws::CognitoIdentity::Model::GetIdResult  idResult = idResp.GetResult();
        openIdReq.SetIdentityId(idResult.GetIdentityId());

        Aws::CognitoIdentity::Model::GetOpenIdTokenOutcome openIdResp =  cognitoClient.GetOpenIdToken(openIdReq);

        if (openIdResp.IsSuccess())
        {
            Aws::CognitoIdentity::Model::GetOpenIdTokenResult idToken = openIdResp.GetResult();
        }

    }   

Aws::ShutdownAPI(options);
```

with rgds,
Manish
<img width="348" alt="capture" src="https://cloud.githubusercontent.com/assets/22979109/19595307/ea3b782c-97a6-11e6-8d24-0dc74c68d74d.PNG">

**Comment by JonathanHenson** [comment]
You have a version mismatch. Can you upgrade all of your packages?

Also, the AWSCPPSDK-identity-management provides a cognitive identity credentials provider implementation.

**Comment by pmanish77** [comment]
Hello Jonathan,

Thanks for your reply.
I updated the packages and the version are as below
AWSSDKCPP-CognitoIdentity.1.0.20140630.22
AWSSDKCPP-Core.1.0.4
AWSSDKCPP-IdentityManagement.1.0.1

Even after updating the packages I am getting the assertion which I reported earlier. This is seen especially when I try to include header file GetIdRequest.h in  aws/cognito-identity/model
I am building a CPP application in VS2015.

I looked into AWSCPPSDK-identity-management.  But looks like it is not what I am looking for.
I will try to explain again.  Below is a javascript code written to validate a user.  I want to do the same in C++. But I am  not able to get the relevant function calls.  It will be great if you can point me to the correct calls in C++.

    service.login = function (params) {
        var authenticationData = {
            Username: params.cognito.username,
            Password: params.cognito.password
        };
        var authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData);
        service.getCognitoUser(params.cognito.username);

        service.cognitoUser.authenticateUser(authenticationDetails, {
            onSuccess: function (result) {
                service.cognitoUser.getSession(function (err, session) {
                    if (result) {
                        var credentials = {
                            IdentityPoolId: config.identityPoolId, // your identity pool id here
                            Logins: {}
                        };
                        credentials.Logins['cognito-idp.' + config.region + '.amazonaws.com/' + config.userPoolId] = session.getIdToken().getJwtToken();

                        AWS.config.credentials.clearCachedId();
                        AWS.config.credentials = new AWS.CognitoIdentityCredentials(credentials);

                        AWS.config.credentials.get(function (error) {
                            if (error) {
                                console.error(error);
                                return;
                            } else {
                                console.log("Successfully authenticated user with Cognito.");
                                if (params.cbSuccess) params.cbSuccess(session);
                            }
                        });
                    }
                });
            },
            onFailure: function (err) {
                console.log("Error: Could not authenticate user with Cognito.");
                if (params.cbError) params.cbError(err);
            },
        });
    };

with rgds,
Manish

**Comment by JonathanHenson** [comment]
On the first note, you have a version mismatch. With AWSSDKCPP-CognitoIdentity.1.0.20140630.22 you need AWSSDKCPP-Core.1.0.22. 

On the second topic, identity-management has a CognitoIdentityCredentialsProvider that will do this for you.

**Comment by gkhanacer** [comment]
@pmanish77  I'm also try to write a code to apply cretential operations (login, etc.). But, I couldn't find any sample for this. Only I found out your code for c++. But, It has an error: "2 validation error detected:". 
Can you share your code with me for credential operation?
