### ISSUE TITLE
ListObjectsV2Result shows wrong value when object's size is more than 2GB

### ISSUE THREAD

**Issue by mikewang2016** [aws/aws-sdk-cpp#315]
In file aws-sdk-cpp/aws-cpp-sdk-s3/include/aws/s3/model/Object.h:

There are the following code:

```
    inline int GetSize() const{ return m_size; }
    inline void SetSize(int value) { m_sizeHasBeenSet = true; m_size = value; }
    inline Object& WithSize(int value) { SetSize(value); return *this;}
```

It's used by ListObjectsV2Result

it will have problem when object's size is more than 2 GB.

**Comment by bretambrose** [comment]
This has been a long-standing bug in the service model.  I don't know what the current status is for getting it changed, but I will check and get back to you with more information.

**Comment by mikewang2016** [comment]
Any update on this ticket?

**Comment by JonathanHenson** [comment]
I'm going to go ahead an override this in our generator, I've been trying to get the model updated for months now and it hasn't happened. Adding to the backlog now.

**Comment by mikewang2016** [comment]
Thank you!

**Comment by JonathanHenson** [comment]
Yeah sorry for the delayed response this has been fixed across our whole S3 API. It's a customization in the generator, so size should always be long long now.
