### ISSUE TITLE
Alpine Linux environment throws error on S3 getObject

### ISSUE THREAD

**Issue by itseramin** [aws/aws-sdk-cpp#3158]
### Describe the bug

When calling the S3 getObject function the following error is shown: `Error: getObject: CoreErrors::ENDPOINT_RESOLUTION_FAILURE: Unexpected nullptr: m_endpointProvider`.

### Expected Behavior

For it to work properly like the same way in works in my development MacOS environment that has the `aws-sdk-cpp` library installed with `Homebrew`.

### Current Behavior

When calling the S3 getObject function the following error is shown: `Error: getObject: CoreErrors::ENDPOINT_RESOLUTION_FAILURE: Unexpected nullptr: m_endpointProvider`.

### Reproduction Steps

I have the following Dockerfile:

```Dockerfile
FROM alpine:latest

RUN apk add -U --no-cache \
    build-base=0.5-r3 \
    cmake=3.29.3-r0 \
    openssl-dev=3.3.2-r1 \
    git=2.45.2-r0 \
    linux-headers=6.6-r0 \
    libpq-dev=16.3-r0 \
    libsrt-dev=1.5.3-r0 \
    aws-sdk-cpp-dev=1.11.205-r1 \
    aws-crt-cpp-dev=0.26.1-r0 \
    tzdata=2024b-r0

WORKDIR /home

WORKDIR /

COPY / /app

RUN cmake -DCMAKE_BUILD_TYPE:STRING=Release --no-warn-unused-cli -S/app -B/app/build -G "Unix Makefiles"

RUN cmake --build /app/build --config Release --target StreamServer -j 12 --

ENTRYPOINT [ "/app/build/StreamServer" ]

EXPOSE 1234/UDP
```

And a code snippet for how I setup my AWS SDK:

```c++
    Aws::SDKOptions options;

    Aws::InitAPI(options);
    {

        Aws::Auth::AWSCredentials awsCredentials(Aws::String(config.getAWSAccessKey()), Aws::String(config.getAWSSecretKey()));

        Aws::Client::ClientConfiguration clientConfig;
        clientConfig.endpointOverride = Aws::String(config.getAWSEndpoint());
        clientConfig.region = Aws::String(config.getAWSRegion());
        clientConfig.scheme = Aws::Http::Scheme::HTTPS;

        Aws::S3::S3Client s3Client(awsCredentials, nullptr, clientConfig);

        AwsMediaStore awsMediaStore(config.getAWSBucket(), config.getAWSRootPath(), s3Client);
    }
    Aws::ShutdownAPI(options);
```

### Possible Solution

I saw that the `Aws::S3::S3Client` class's constructor takes a `std::shared_ptr<S3EndpointProviderBase>` as a second parameter which is defaulted to `nullptr`, should I create this object pointer, but then why isn't it needed for my MacOS environment?

Setting the clientConfig's `endpointOverride` property works fine:

```c++
Aws::Client::ClientConfiguration clientConfig;
clientConfig.endpointOverride = Aws::String(config.getAWSEndpoint());
...
```

I also tried setting:

```c++
clientConfig.enableEndpointDiscovery = true;
```

but had no effect.

### Additional Information/Context

We are trying to deploy our audio streaming application to a Kubernetes cluster, hence the Dockerfile. Testing the Docker image locally produces the same error in the K8 cluster too.

### AWS CPP SDK version used

1.11.205-r1

### Compiler and Version used

GNU 13.2.1

### Operating System and version

Alpine Linux 3.20.3

**Comment by sbiscigl** [comment]
Hey @itseramin thanks for the detailed issue, we really appreciate reproducible docker files. That being said for this case we cannot reproduce the issue. for my workspace and test:

```
~/sdk-usage-workspace ❯❯❯ tree -L 1
.
├── CMakeLists.txt
├── Dockerfile
├── main.cpp
└── replicate.sh
```

CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.13)
project(sdk_usage_workspace)
set(CMAKE_CXX_STANDARD 20)
find_package(AWSSDK REQUIRED COMPONENTS s3)
add_executable(${PROJECT_NAME} "main.cpp")
target_link_libraries(${PROJECT_NAME} PRIVATE ${AWSSDK_LINK_LIBRARIES})
```

Dockerfile
```dockerfile
FROM alpine:latest

RUN apk add -U --no-cache \
    build-base=0.5-r3 \
    cmake=3.29.3-r0 \
    openssl-dev=3.3.2-r1 \
    git=2.45.2-r0 \
    aws-sdk-cpp-dev=1.11.205-r1 \
    aws-crt-cpp-dev=0.26.1-r0

## Copy over and build
RUN mkdir sdk-example
COPY CMakeLists.txt /sdk-example/CMakeLists.txt
COPY main.cpp /sdk-example/main.cpp
RUN cd sdk-example &&\
    mkdir build &&\
    cd build &&\
    cmake .. && \
    cmake --build .

```

main.cpp
```cpp
#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>

using namespace Aws;
using namespace Aws::S3;

auto main() -> int {
  SDKOptions options;
  InitAPI(options);
  {
    S3Client client{};
    const auto buckets_result = client.ListBuckets();
    assert(buckets_result.IsSuccess());
    for (const auto& bucket : buckets_result.GetResult().GetBuckets()) {
      std::cout << bucket.GetName() << "\n";
    }
  }
  ShutdownAPI(options);
  return 0;
}
```

replicate.sh
```shell
#!/bin/zsh

set -u

# build image
docker build -t test-image .

# run example
docker run \
    -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
    -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
    -e AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN} \
    --name test-image test-image /sdk-example/build/sdk_usage_workspace\
```

when i run `./replicate.sh` given that i have `AWS_ACCESS_KEY_ID`/`AWS_SECRET_ACCESS_KEY`/`AWS_SESSION_TOKEN` set in the current shell i will see it execute successfully and list the buckets.

So from this snippet it looks like its working. if you can update this snippet to fail, would be happy to take a look into it.

all of that being said i am suspect of incorrect installation in your dockerfile even though its working for me from a clean install. I would suggest building and installing from source. that will likely work for you i.e. an adapted dockerfile from the example above.

```dockerfile
FROM alpine:latest

RUN apk add -U --no-cache \
    build-base=0.5-r3 \
    cmake=3.29.3-r0 \
    openssl-dev=3.3.2-r1 \
    git=2.45.2-r0

RUN git clone --depth 1 --recurse-submodules https://github.com/aws/aws-sdk-cpp && \
    cd aws-sdk-cpp && \
    mkdir build && \
    cd build && \
    cmake -DBUILD_ONLY="s3" \
      -DAUTORUN_UNIT_TESTS=OFF \
      -DCMAKE_INSTALL_PREFIX=/sdk-install .. && \
    cmake --build . && \
    cmake --install .

## Copy over and build
RUN mkdir sdk-example
COPY CMakeLists.txt /sdk-example/CMakeLists.txt
COPY main.cpp /sdk-example/main.cpp
RUN cd sdk-example &&\
    mkdir build &&\
    cd build &&\
    cmake -DCMAKE_PREFIX_PATH=/sdk-install .. && \
    cmake --build .
```

that should remove any chances of incorrectly mix and matching installations entirely by finding it purely on the `CMAKE_PREFIX_PATH`.

Give that a shot a let me know if you can update my example to fail/if installing and using from source works for you.

**Comment by SergeyRyabinin** [comment]
Hi @itseramin ,

I see you are using a bit old version of the AWS CPP SDK,
The version 1.11.205 was requiring the endpointProvider pointer to be initialized and passed to the client constructor (there was a default argument set in the API definition in headers as well).

In the https://github.com/aws/aws-sdk-cpp/pull/2849, I had to refactor the API to satisfy the condition of the MSVS delay load dll flag, as a result, passing a nullptr became a valid usecase, and a default provider will be initialized (anyway you need one and anyway there are only few users requiring a non-default one).

So it is either
```
Aws::S3::S3Client s3Client(awsCredentials, Aws::MakeShared<S3EndpointProvider>("ALLOC_TAG"), clientConfig);
```
or update to a latest version (to a version at least [#1.11.262](https://github.com/aws/aws-sdk-cpp/releases/tag/1.11.262)).

Just in case, `enableEndpointDiscovery` should do / does nothing for S3, it is a functionality of DynamoDB and Timestream services (however, this flag was added to a generic ClientConfig class for some reason)

Please let us know if you still see the issue after the update or you experience other issues. Please refer to the repro template brought by @sbiscigl .

Best regards,

**Comment by itseramin** [comment]
Huge thanks to @sbiscigl and @SergeyRyabinin for your detailed responses! Passing `Aws::MakeShared<S3EndpointProvider>("ALLOC_TAG")` as the second argument to the `Aws::S3:: S3Client` constructor finally solved the problem for me.

Unfortunately, I’m stuck on Alpine’s package version. The latest version (v1.11.400-r0) has dependency issues, and the highest stable version I can use from the non-edge branch is v1.11.205-r1. (I’m probably just new to Alpine and haven’t figured out how to access versions between those.)

I realise the ideal solution would be building the library from scratch, but we’ve already spent way too much time fiddling with `CMakeLists` and `Dockerfile` to get it working in our CI/CD. We’re still fairly new to the C++ ecosystem and learning as we go…
