### ISSUE TITLE
Saving records locally in case of network failure while submitting records to the firehose client

### ISSUE THREAD

**Issue by umangmehta12** [aws/aws-sdk-cpp#318]
I was wondering do we have a method for saving records to local disk in case of network failures?
Something like [saveRecord](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/mobileconnectors/kinesis/kinesisrecorder/KinesisFirehoseRecorder.html#saveRecord-byte:A-java.lang.String-) in Android?
I am using PutRecordBatch, PutRecordAsync and PutRecord at some places. I am mainly concerned of losing the records when the user would be offline.

**Comment by bretambrose** [comment]
There is not any functionality to do this at the moment, but I think it's a good idea.  We could either build a higher-level kinesis client with this as a configurable option, or perhaps we could provide an additional ClientConfiguration parameter for an implementation of a serialize-somewhere-on-total-failure interface, as well as provide ways to reconstruct serialized requests from a data source.

**Comment by JonathanHenson** [comment]
A general request batched would be a cool feature--especially for cloud watch and kinesis

**Comment by umangmehta12** [comment]
@JonathanHenson and @bretambrose  so currently the way I handle it is by binding the client to the PutRecordOutcome object and then retry twice until I get success to put the record. Can you think of any other possibility of handling this without having to write the additional function to handle the storage of records?

**Comment by JonathanHenson** [comment]
By the time saveRecord fails back to the user, it has already been retried multiple times via the retry strategy. We just need an offline batcher/metrics pipeline. Will add this to our back log.

**Comment by singku** [comment]
@umangmehta12 We are working on cleaning up some of the staled issues. Do you still need this feature?

**Comment by umangmehta12** [comment]
No not at this moment. @singku Thanks for checking in.
