### ISSUE TITLE
Async and Client lifetime

### ISSUE THREAD

**Issue by MaxGriot** [aws/aws-sdk-cpp#319]
Hello,

Due to the token expiration, I am forced to recreate my clients everytime I get new tokens, my question being: who is responsible for the lifetime of the Client objects ? Does the executor keep a ref count of the object or should I use the lambda capture operator to ref count my shared_ptr ?

Max

**Comment by bretambrose** [comment]
Could you go into more detail about your use-case and token usage?  Would implementing your own auto-refreshing credentials provider be a possible solution (similar to what we've provided with cognito in the identity-management sdk)?

**Comment by MaxGriot** [comment]
Hey Bret, it's been a while!

The way I do things right is that I need to assume a role through STS, but the tokens I get are valid for at most 1h. I use the tokens to create a Aws::Auth::AWSCredentials that I use to create the Clients.

For example:
`auto pClient = std::make_shared<Aws::DynamoDB::DynamoDBClient>(Aws::Auth::AWSCredentials(pIdentity->AccessKeyId, pIdentity->SecretAccessKey, pIdentity->SessionToken), config);`

To get new tokens I create a task that waits for 30 minutes, calls AssumeRole and notifies listeners that new tokens are available and then I recreate all the clients as seen above. But at this time it is possible that an Async call is happening, right now I capture the shared_ptr in my lambda callback to ref count Async tasks but it doesn't seem efficient.

I will take a look at the credentials provider and see if that works for me.

Thanks,
Max

**Comment by bretambrose** [comment]
Hey Max,

Still crushing noobs at Dota I'm hoping?  Jonathan mentioned that he'd like to add a refreshing STS-based credentials provider in the aws-cpp-sdk-identity-management library.  If you want to take a crack at it, feel free, otherwise he'll probably crank it out one of these days.

**Comment by JonathanHenson** [comment]
I'll be adding this to the identity-management package. Feel free to write one and submit a PR, it will probably be a week until I get to it. Otherwise, I'll let you know when it's done.

**Comment by MaxGriot** [comment]
I went ahead and implemented an STS provider and so far everything works perfectly, sadly I doubt I will be able to contribute to the repository, I tried to get the company to approve the release of parts of what I work on opensource and the answer is clear: no...

@bretambrose Always, feel free to join me anytime!

**Comment by JonathanHenson** [comment]
We're hiring....

**Comment by yamashi** [comment]
I know you are, sadly I am not a US citizen :/

**Comment by JonathanHenson** [comment]
We pay for visas.

**Comment by JonathanHenson** [comment]
we'll add an STS Credentials provider to the identity-management project story to our backlog

**Comment by JonathanHenson** [comment]
I just pushed this out. It's in the identity-management project.
