### ISSUE TITLE
Compiling AccessManagement fails. Compiler option `--std=c++11` dropped.

### ISSUE THREAD

**Issue by tinkyholloway** [aws/aws-sdk-cpp#320]
I am trying to build minimized static libraries. Here are the relevant lines from docker:

    RUN git clone --branch 1.0.22 https://github.com/aws/aws-sdk-cpp.git --depth 1
    RUN cd aws-sdk-cpp && mkdir build && cd build && cmake -DBUILD_SHARED_LIBS=OFF -DENABLE_RTTI=ON -DMINIMIZE_SIZE=ON -DENABLE_TESTING=OFF     -DENABLE_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON .. && make install

Everything is fine until I hit AccessManagement. Then I notice two things:

1. Unity Build (via `MINIMIZE_SIZE=ON`) seems to be ignored.
2. The default `-std=c++11` compile option seems to be lost.

Here is the relevant output from the build:

    [ 94%] Building CXX object aws-cpp-sdk-access-management/CMakeFiles/aws-cpp-sdk-access-management.dir/source/AccessManagementClient.cpp.o
    cd /var/task/aws-sdk-cpp/build/aws-cpp-sdk-access-management && /usr/bin/c++ -DENABLE_CURL_CLIENT -DENABLE_OPENSSL_ENCRYPTION -DPLATFORM_LINUX -Wall -Werror -pedantic -Wextra -fno-exceptions -fPIC -O3 -DNDEBUG -s @CMakeFiles/aws-cpp-sdk-access-management.dir/includes_CXX.rsp   -o CMakeFiles/aws-cpp-sdk-access-management.dir/source/AccessManagementClient.cpp.o -c /var/task/aws-sdk-cpp/aws-cpp-sdk-access-management/source/AccessManagementClient.cpp
    ^[[91mIn file included from /var/task/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/memory/AWSMemory.h:20:0,
                      from /var/task/aws-sdk-cpp/aws-cpp-sdk-access-management/include/aws/access-management/AccessManagementClient.h:19,
                      from /var/task/aws-sdk-cpp/aws-cpp-sdk-access-management/source/AccessManagementClient.cpp:16:
     /var/task/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/memory/MemorySystemInterface.h:50:17: error: identifier ‘nullptr’ is a keyword in C++11 [-Werror=c++0x-compat]
                      virtual void* AllocateMemory(std::size_t blockSize, std::size_t alignment, const char *allocationTag = nullptr) = 0;
    
    ...plus a whole lot more
 
Compiler options have disappeared. In other lines of build output there is a `-std=c++11` compiler option in the place similar to between `-s @CMakeFiles/aws-cpp-sdk-access-management.dir/includes_CXX.rsp` and `-o CMakeFiles/aws-cpp-sdk-access-management.dir/source/AccessManagementClient.cpp.o`

**Comment by bretambrose** [comment]
None of the higher-level clients use the unity build since they don't consist of more than a handful of source files.  I see -s in your compile arguments (which comes from MINIMIZE_SIZE), so that hasn't disappeared.  When I follow your steps, my access management builds without error and includes -std=c++11 so I'm not sure what's going wrong for you.

What version of cmake are you using?
Can you try running cmake with verbose output (--trace maybe) and compare what gets outputted when constructing the makefile for a working service client vs. what gets output for access-management?

**Comment by tinkyholloway** [comment]
@bretambrose Thank you so much for your help.

The full output from the build is here: https://gist.github.com/tinkyholloway/9e54a312d147648b3ff1a05a483e5aa2

Here is the docker file that I am using. The base image is available on docker hub.

    FROM lambci/lambda:build
    # 
    RUN cmake --version
    #
    RUN git clone --branch curl-7_50_3 https://github.com/curl/curl.git --depth 1
    RUN cd curl && ./buildconf && ./configure --enable-shared=no --enable-static=yes --enable-libgcc --with-pic --with-ca-bundle=/etc/pki/tls/certs/ca-bundle.crt && make install
    #
    RUN curl -s -L http://downloads.sourceforge.net/project/libuuid/libuuid-1.0.3.tar.gz --output libuuid-1.0.3.tar.gz
    RUN tar xf libuuid-1.0.3.tar.gz && cd libuuid-1.0.3 && ./configure --enable-shared=no && make install
    #
    RUN git clone --branch 1.0.22 https://github.com/aws/aws-sdk-cpp.git --depth 1
    RUN cd aws-sdk-cpp && mkdir build && cd build && cmake --trace -DBUILD_SHARED_LIBS=OFF -DENABLE_RTTI=ON -DMINIMIZE_SIZE=ON -DENABLE_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON .. && make install VERBOSE=1

Which reports that the `cmake` version is 2.8.12.

**Comment by bretambrose** [comment]
Despite what our top-level CMakeLists.txt says (2.8.12) you actually need a higher version of cmake to properly build the SDK these days.  I'd recommend 3.6 if possible, but 3.0 is probably sufficient.  We haven't updated the minimum yet because we're not sure how it will impact our existing users.  What we've found is that compile and link options are not being properly propagated transitively on 2.8.12

**Comment by tinkyholloway** [comment]
@bretambrose Thanks for this. I've added `cmake-3.6.2` to the build and everything builds nicely.

For completeness here is the docker file used:

    FROM lambci/lambda:build
    #
    RUN git clone --branch curl-7_50_3 https://github.com/curl/curl.git --depth 1
    RUN cd curl && ./buildconf && ./configure --enable-shared=no --enable-static=yes --enable-libgcc --with-pic --with-ca-bundle=/etc/pki/tls/certs/ca-bundle.crt && make install
    #
    RUN curl -s -L http://downloads.sourceforge.net/project/libuuid/libuuid-1.0.3.tar.gz --output libuuid-1.0.3.tar.gz
    RUN tar xf libuuid-1.0.3.tar.gz && cd libuuid-1.0.3 && ./configure --enable-shared=no && make install
    #
    RUN curl -s -L https://cmake.org/files/v3.6/cmake-3.6.2.tar.gz --output cmake-3.6.2.tar.gz
    RUN tar xf cmake-3.6.2.tar.gz && cd cmake-3.6.2 && cmake . && make install
    #
    RUN git clone --branch 1.0.22 https://github.com/aws/aws-sdk-cpp.git --depth 1
    RUN cd aws-sdk-cpp && mkdir build && cd build && cmake -DBUILD_SHARED_LIBS=OFF -DENABLE_RTTI=ON -DMINIMIZE_SIZE=ON -DENABLE_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=OFF .. && make install
