### ISSUE TITLE
LNK2001	About Aws::Http::CONTENT_TYPE_HEADER and Aws::Http::CONTENT TYPE HEADER

### ISSUE THREAD

**Issue by guoyuanchao94** [aws/aws-sdk-cpp#3209]
### Describe the bug

-  When I used the built library file, using the official example, there were two link errors

-  Severity Code Description Item File line Does not display status details Error LNK2001 cannot resolve external symbols "char const * const Aws::Http::CONTENT TYPE HEADER" (? CONTENT TYPE HEADER@Http@Aws@@3QBDB) AWSTest D:\C++\AWSTest\main.obj 1

- Severity Code Description Item File line Prohibited from displaying status details Error LNK2001 failed to parse external symbols "char const * const Aws::Http::API VERSION HEADER" (? API VERSION HEADER@Http@Aws@@3QBDB) AWSTest D:\C++\AWSTest\main.obj 1

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

No Error

### Current Behavior

Error LNK2001	External symbols that cannot be resolved "char const * const Aws::Http::CONTENT_TYPE_HEADER" (?CONTENT_TYPE_HEADER@Http@Aws@@3QBDB)	AWSTest	D:\C++\AWSTest\main.obj	1

Error LNK2001	External symbols that cannot be resolved "char const * const Aws::Http::API_VERSION_HEADER" (?API_VERSION_HEADER@Http@Aws@@3QBDB)	AWSTest	D:\C++\AWSTest\main.obj	1		
		

### Reproduction Steps

```cpp
#include <aws/core/Aws.h>
#include <aws/autoscaling/AutoScalingClient.h>
#include <aws/autoscaling/model/DescribeAutoScalingGroupsRequest.h>
#include <iostream>

/*
 *  A "Hello Autoscaling" starter application which initializes an Amazon EC2 Auto Scaling client and describes the
 *  Amazon EC2 Auto Scaling groups.
 *
 *  main function
 *
 *  Usage: 'hello_autoscaling'
 *
 */

int main(int argc, char** argv) 
{
    Aws::SDKOptions options;
    // Optionally change the log level for debugging.
   options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;
    Aws::InitAPI(options); // Should only be called once.
    int result = 0;
    {
        Aws::Client::ClientConfiguration clientConfig;
         //Optional: Set to the AWS Region (overrides config file).
         clientConfig.region = "us-east-1";

        Aws::AutoScaling::AutoScalingClient autoscalingClient(clientConfig);

        std::vector<Aws::String> groupNames;
        Aws::String nextToken; // Used for pagination.

        do {

            Aws::AutoScaling::Model::DescribeAutoScalingGroupsRequest request;
            if (!nextToken.empty()) 
            {
                request.SetNextToken(nextToken);
            }

            Aws::AutoScaling::Model::DescribeAutoScalingGroupsOutcome outcome =
                autoscalingClient.DescribeAutoScalingGroups(request);

            if (outcome.IsSuccess()) 
            {
                const Aws::Vector<Aws::AutoScaling::Model::AutoScalingGroup>& autoScalingGroups =
                    outcome.GetResult().GetAutoScalingGroups();
                for (auto& group : autoScalingGroups) {
                    groupNames.push_back(group.GetAutoScalingGroupName());
                }
                nextToken = outcome.GetResult().GetNextToken();
            }
            else 
            {
                std::cerr << "Error with AutoScaling::DescribeAutoScalingGroups. "
                    << outcome.GetError().GetMessage()
                    << std::endl;
                result = 1;
                break;
            }
        } while (!nextToken.empty());

        std::cout << "Found " << groupNames.size() << " AutoScaling groups." << std::endl;
        for (auto& groupName : groupNames) 
        {
            std::cout << "AutoScaling group: " << groupName << std::endl;
        }

    }
    Aws::ShutdownAPI(options); // Should only be called once.
    //return result;
}

```

### AWS CPP SDK version used

1.11.455

### Compiler and Version used

Visual Studio

### Operating System and version

Windows 11 22631.4460

**Comment by guoyuanchao94** [comment]
![image](https://github.com/user-attachments/assets/f1671ded-0ca9-4861-92df-efc75b461156)
i add this before all  include, and it slove this problem

**Comment by jmklix** [comment]
Are you still running into the above errors? 

It looks like you temporarily closed this issue and also provided an answer. Please let us know if you need any help with using this sdk.

**Comment by guoyuanchao94** [comment]
@jmklix Now I have solved this problem by #define USE_IMPORT_EXPORT in front of all header files. I don't need any help at the moment, thank you for your reply. if i need help,i will create issue again;
