### ISSUE TITLE
AwsClient and thread safety

### ISSUE THREAD

**Issue by logidelic** [aws/aws-sdk-cpp#321]
Is it safe to make use of a single instance of `AwsClient` accross multiple threads, (without synchronizing usage)?

For example, assuming an `AwsClient` instance named aws, may two seperate threads safely call `aws.client->ListObjects()` in parallel?

Thanks.

**Comment by bretambrose** [comment]
Yes it is safe.

**Comment by bretambrose** [comment]
Closing.  Feel free to reopen if you have any further questions.

**Comment by Bu11etmagnet** [comment]
All methods marked `const` are thread-safe.

**Comment by JonathanHenson** [comment]
In general in c++, const should mean both logically not mutating, and thread safe. In addition, most non-const functions not on plain data objects are also thread-safe (executors, rate limiters etc...)
