### ISSUE TITLE
Case insensitive Map?

### ISSUE THREAD

**Issue by mattman71** [aws/aws-sdk-cpp#322]
How do I achieve case insensitive Map? I want find, count, [], etc. to "hit" even if the case is wrong.

For example, I want this:
Aws::Map<Aws::String, Aws::String> theMap = GetTheMap();
// theMap contains, among others, { "KEY", "this is the value" }
Aws::String value = theMap["key"];
// I want this to match and return the value

for std::, I would do it this way:
    struct comp {
        bool operator() (const Aws::String& lhs, const Aws::String& rhs) const {
            return _stricmp(lhs.c_str(), rhs.c_str()) < 0;
        }
    };
    std::map<Aws::String, Aws::String, comp> theMap;

But the 3rd template parameter isn't there in Aws::Map.

**Comment by bretambrose** [comment]
Other than overriding the global < operator for that type (against itself), not a recommend practice, I don't think there's anything you can do to achieve that with the Aws::Map type.  Even if we did expose the comparison template parameter, you still couldn't seemlessly transition (you'd need to copy/reconstruct) between case-insensitive maps and what's in our interfaces.

**Comment by bretambrose** [comment]
Closing for now.  If you have further questions or concerns, please reopen.

**Comment by mattman71** [comment]
OK, thanks. I ended up just using std::map with the comparison template, and Aws::String key & value pairs.
