### ISSUE TITLE
Repo can't be cloned on Windows

### ISSUE THREAD

**Issue by meyertst-aws** [aws/aws-sdk-cpp#3223]
### Describe the bug

When cloning the repo on Windows, the following error causes the clone to fail with the following error.

> error: unable to create file tools/code-generation/smithy/codegen/.gradle/8.10.2/dependencies-accessors/ff89fa8742c5e83b2b9d65507e208fccb62ee814/classes/org/gradle/accessors/dm/LibrariesForCodegenInPluginsBlock$SmokeTestLibraryAccessors.class: Filename too long

### Regression Issue

- [X] Select this option if this issue appears to be a regression.

### Expected Behavior

This repo clones successfully on Windows.

### Current Behavior

Cloning fails on a Windows machine.

### Reproduction Steps

`git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp` on a Windows machine without long file names enabled.

### AWS CPP SDK version used

1.11.467

### Compiler and Version used

Visual Studio

### Operating System and version

Windows Server 2022 Datacenter - version - 21H2

**Comment by sbera87** [comment]
The exact error message:

```
Cloning into 'aws-sdk-cpp'...
remote: Enumerating objects: 1076598, done.
remote: Counting objects: 100% (37065/37065), done.
remote: Compressing objects: 100% (7456/7456), done.
remote: Total 1076598 (delta 26247), reused 36338 (delta 25862), pack-reused 1039533 (from 1)
Receiving objects: 100% (1076598/1076598), 611.66 MiB | 18.26 MiB/s, done.

Resolving deltas: 100% (852143/852143), done.
error: unable to create file tools/code-generation/smithy/codegen/.gradle/8.10.2/dependencies-accessors/ff89fa8742c5e83b2b9d65507e208fccb62ee814/classes/org/gradle/accessors/dm/LibrariesForCodegenInPluginsBlock$AwsCloudformationLibraryAccessors.class: Filename too long
error: unable to create file tools/code-generation/smithy/codegen/.gradle/8.10.2/dependencies-accessors/ff89fa8742c5e83b2b9d65507e208fccb62ee814/classes/org/gradle/accessors/dm/LibrariesForCodegenInPluginsBlock$AwsSmokeTestLibraryAccessors.class: Filename too long
Updating files: 100% (135462/135462), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by jmklix** [comment]
This is fixed with this PR: https://github.com/aws/aws-sdk-cpp/pull/3224
