### ISSUE TITLE
AWSAuthSigner is not proxy friendly

### ISSUE THREAD

**Issue by Capstan** [aws/aws-sdk-cpp#323]
According to [Guidelines for Web Content Transformation Proxies 1.0](https://www.w3.org/TR/2010/NOTE-ct-guidelines-20101026/#sec-altering-header-values), a transforming web proxy is allowed to update the [`User-Agent`](https://tools.ietf.org/html/rfc7231#section-5.5.3) header to indicate additional product compatibility information. The current mode of the signer is to sign _every_ header, including the `User-Agent`, which means any proxy so adding its product to the agent will invalidate the signature.

In addition, since the signature also includes the hash of the payload and said payload is allowed to be [transformed](https://tools.ietf.org/html/rfc7230#section-5.7.2), I would think that it'd be the signer's responsibility to ensure a [`Cache-Control: no-transform`](https://www.w3.org/TR/2010/NOTE-ct-guidelines-20101026/#sec-request-no-transform) directive in the request, adding it if necessary to any existing `Cache-Control` directives. This would ensure any transforming proxy would not transform the body, which would render the signature invalid.

**Comment by Capstan** [comment]
The [generic v4 documentation for Canonical Request generation](http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html) states that `Host` is required and standard headers, e.g., `Content-Type` are optional, but then states that individual services may require other headers. The [S3-specific documentation](http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html#canonical-request) makes `Content-Type` required if present, makes any existing `x-amz-`* headers required.

Neither seem to require `User-Agent` to be provided as one of the signed headers.

**Comment by JonathanHenson** [comment]
Is this a theoretical bug, or has it actually broken something for you?

**Comment by Capstan** [comment]
The `User-Agent` part is actually broken for one of my partners. We have a workaround for the proxy we control, but it's not generalizable.

**Comment by JonathanHenson** [comment]
I've fixed the user-agent portion of this (and added some nice optimizations to the signer), it should be released shortly. As for the other headers (unfortunately they are modeled by other services so they need to be signed) If a proxy simply adds headers, it shouldn't be an issue however.

**Comment by Capstan** [comment]
Thanks for the quick fix!

For your latter point, are you saying that `Cache-Control` is required to be signed by some services?

**Comment by JonathanHenson** [comment]
Yes

**Comment by Capstan** [comment]
That's… unfortunate. I guess then I hope that the services would, if they provided `Cache-Control`, that they'd provide it pre-filled with `no-transform` to avoid such problems.

**Comment by JonathanHenson** [comment]
Only s3 uses that header, and only then if you set it. If it gets added by the proxy, it won't affect anything.

**Comment by JonathanHenson** [comment]
Ah... it's a metadata field, so there shouldn't be any issues. Only fields that get set by the sdk are signed so the user agent header is probably the only one that needed to be excluded.

**Comment by JonathanHenson** [comment]
We've fixed this and pushed it out. Feel free to reopen if you still have issues.
