### ISSUE TITLE
How to build complete static SDK library?

### ISSUE THREAD

**Issue by cosmosb** [aws/aws-sdk-cpp#324]
I'm trying to build SDK (v1.0.22) as a standalone static library for Windows and Linux. I'm using following:

Windows:

`cmake -G "Visual Studio 14 2015 Win64" -DBUILD_ONLY="s3" -DENABLE_UNITY_BUILD=ON -DFORCE_SHARED_CRT=OFF -DBUILD_SHARED_LIBS=OFF -DSIMPLE_INSTALL=OFF <aws-sdk-cpp-source-dir>`

Linux:

`cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3" -DENABLE_UNITY_BUILD=ON -DFORCE_SHARED_CRT=OFF -DBUILD_SHARED_LIBS=OFF -DSIMPLE_INSTALL=OFF <aws-sdk-cpp-source-dir>`

When I try to use SDK library in my project, I still need to link few libraries. For exa. on Windows: wininet.lib, winhttp.lib, bcrypt.lib, userenv.lib, rpcrt4.lib.

The reason to build isolated static library for SDK is to have it built only once (with all dependencies included) and put it in our source code repository for everyone else.

How would you build complete isolated static library?

**Comment by bretambrose** [comment]
I don't think this is possible on Windows at least; all of the listed examples are system libraries which do not exist statically (I think, not 100% sure).  Beyond that, see the replies in http://reverseengineering.stackexchange.com/questions/2070/can-i-statically-link-not-import-the-windows-system-dlls 

Ultimately, though, I don't understand the premise.  If you're checking in static libraries to source control, then that means your developers are using them as part of building their own targets.  Why is linking the appropriate system libraries when building those targets a problem?

**Comment by cosmosb** [comment]
@bretambrose, Windows probably wasn't good example.

I need to build 64-bit and 32-bit version of libraries: **libaws-cpp-sdk-core.a** and **libaws-cpp-sdk-s3.a** for Linux.  I'm using Ubuntu 16.04.

Premise is that I create libraries once, put them in my project source code repository as pre-built third party library. This way everybody on the team doesn't have to go through all steps of building AWS SDK. 

Another reason to go for this route is that, AWS SDK on Linux depends on **libcurl-dev**, **libssl-dev** and **uuid-dev**.  Installing 64-bit and 32-bit of **libssl-dev** and **uuid-dev** at the same time works.

But I cannot install 64-bit and 32-bit of **libcurl-dev** (I picked libcurl4-openssl-dev) at the same time. Installing one removes other. I don't know if this is a bug or by design.

**Comment by bretambrose** [comment]
One possibility is that you could build curl from source and use install-prefix at configure-time to put the 32 and 64 bit versions in different spots.  Then use CMAKE_PREFIX_PATH to point to the appropriate curl when building the aws cpp sdk.  As you've probably noticed, at cmake time we print out the path to openssl/curl/uuid, making it easy to verify that the right install is getting picked up.

**Comment by cosmosb** [comment]
Thanks for suggestion. Will check it out.

**Comment by bretambrose** [comment]
Did this work out for you?  Please reopen if you have further questions/concerns.
