### ISSUE TITLE
Error in EC2::CreateSecurityGroup

### ISSUE THREAD

**Issue by jimmyt857** [aws/aws-sdk-cpp#327]
When I try to run this function, I get the following error:

```
<Response>
    <Errors>
        <Error>
            <Code>UnknownParameter</Code>
            <Message>The parameter Description is not recognized</Message>
        </Error>
    </Errors>
    <RequestID>246c5761-1f79-4f24-8ab0-00df07bbfb68</RequestID>
</Response>
```

**Comment by jimmyt857** [comment]
Also, if I try to instead just omit the .WithDescription() call, I get a different error telling me that the description is required.

**Comment by JonathanHenson** [comment]
we'll add this to the backlog. Thanks for reporting.

**Comment by bretambrose** [comment]
This will be fixed in a release next week.

**Comment by bretambrose** [comment]
Should be fixed in yesterday's release.
