### ISSUE TITLE
Aws::Transfer::TransferManager::UploadFile() blocks forever and uses all the computer RAM

### ISSUE THREAD

**Issue by yvanix** [aws/aws-sdk-cpp#328]
I'm working on a multiplatform (Windows/Linux) C++ application that uploads files to Amazon S3. To upload the files I use the Aws::Transfer::TransferManager::UploadFile() function.
```
std::shared_ptr<TransferHandle> UploadFile(const Aws::String& fileName, const Aws::String& bucketName, const Aws::String& keyName, const Aws::String& contentType, 
                                                            const Aws::Map<Aws::String, Aws::String>& metadata);
```

Unfortunately this function fails for each key that contains an accent, e.g. "abcdé" and apparently for every key that contains a non-ascii character. In this case the function blocks and consumes all RAM until the computer runs out of RAM or until the process is killed. I read that the aws-sdk-cpp library accepts Unicode strings if the proper method is used to convert them to std::string. My application is written in Qt, to pass the strings to the Aws library I convert them using:
```
Aws::String toAwsString(const QString& s)
{
    return s.toUtf8().constData();
}
```

Both my application and the aws-sdk-cpp are compiled using _UNICODE/UNICODE.
Note that the same code works perfectly on Linux.

Any help would greatly appreciated.

**Comment by bretambrose** [comment]
We have several reports of bad transfer/s3 behavior when filenames contain unusual characters.  There's an entry in our backlog to investigate and fix in the near term; we will try and get to this as soon as possible

**Comment by yvanix** [comment]
I think that the problem is that is that the UploadFunction() uses std::fstream internally.
` auto fileStream = Aws::MakeShared<Aws::FStream>(CLASS_TAG, fileName.c_str(), std::ios_base::in | std::ios_base::binary);`
Unfortunately in order to open utf-8 path one must use std::wfstream() on Windows. On Linux a std::string can contain (the bytes) of a 8TF-8 string so we don't have this problem on Linux.

**Comment by bretambrose** [comment]
This should no longer hang but the upload will now immediately fail (if you use the filename interface).  If you use the fstream interface and pass in a stream that was created with a valid wstring path, it should work.  Meanwhile, as mentioned in #303 we will try and come up with a simple, transparent solution so that the filename interface works even in the presence of unusual characters.

**Comment by marcomagdy** [comment]
We've fixed a couple of deadlock bugs in TransferManager in the latest version.
If you're still experiencing this problem, please re-open.
