### ISSUE TITLE
CurlHttpClient::MakeRequest throws bad_function_call

### ISSUE THREAD

**Issue by tawhirimatea** [aws/aws-sdk-cpp#329]
I'm sorry if this is not the correct place to post this, but I could not find any support on SO and the AWS Dev Forums don't have a place for CPP.

I'm issuing a request like:

    Aws::Client::ClientConfiguration clientConfiguration;
    clientConfiguration.scheme = Aws::Http::Scheme::HTTPS;
    clientConfiguration.region = Aws::Region::US_EAST_1;
                      
    Aws::Http::CurlHttpClient client(clientConfiguration);
                      
    Aws::Http::URI uri;
    uri.SetScheme(Aws::Http::Scheme::HTTPS);
    uri.SetAuthority(ELASTIC_SEARCH_DOMAIN);
    uri.SetPath(r.parameters.path);
                      
    Aws::Http::Standard::StandardHttpRequest req(uri, r.parameters.verb);
    req.AddContentBody(r.parameters.body);
                      
    auto res = client.MakeRequest(req);    //     <----- FAILS HERE                                                                             
                      
    Aws::Http::HttpResponseCode resCode = res->GetResponseCode();
                      
    if (resCode == Aws::Http::HttpResponseCode::OK) {
      // etc.. 

When `CurlHttpClient::MakeRequest` tries to create a response, `bad_function_call` is thrown:

    #0  0x00007ffff6bdb5f7 in raise () from /lib64/libc.so.6
    #1  0x00007ffff6bdcce8 in abort () from /lib64/libc.so.6
    #2  0x00007ffff74e0b3d in __gnu_cxx::__verbose_terminate_handler() () from /usr/local/lib64/node-v4.3.x/lib/libstdc++.so.6
    #3  0x00007ffff74dead6 in __cxxabiv1::__terminate(void (*)()) () from /usr/local/lib64/node-v4.3.x/lib/libstdc++.so.6
    #4  0x00007ffff74deb21 in std::terminate() () from /usr/local/lib64/node-v4.3.x/lib/libstdc++.so.6
    #5  0x00007ffff74ded68 in __cxa_throw () from /usr/local/lib64/node-v4.3.x/lib/libstdc++.so.6
    #6  0x00007ffff7543222 in std::__throw_bad_function_call() () from /usr/local/lib64/node-v4.3.x/lib/libstdc++.so.6
    #7  0x00007fffeb74d18f in std::function<std::iostream* ()>::operator()() const (this=0x7fffffffcd88) at /usr/include/c++/4.8.3/functional:2470
    #8  0x00007fffeb739e7e in Aws::Utils::Stream::ResponseStream::ResponseStream(std::function<std::iostream* ()> const&) (this=0x55555666ed50, factory=...) at /var/task/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/stream/ResponseStream.cpp:27
    #9  0x00007fffeb7459ef in Aws::Http::Standard::StandardHttpResponse::StandardHttpResponse (this=0x55555666ed08,   originatingRequest=...) at /var/task/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/http/standard/StandardHttpResponse.h:44
    #10 0x00007fffeb767f41 in __gnu_cxx::new_allocator<Aws::Http::Standard::StandardHttpResponse>::construct<Aws::Http::Standard::StandardHttpResponse<Aws::Http::HttpRequest&> > (this=0x7fffffffc43f, __p=0x55555666ed08) at /usr/include/c++/4.8.3/ext/new_allocator.h:120
    #11 0x00007fffeb76784e in std::allocator_traits<std::allocator<Aws::Http::Standard::StandardHttpResponse> >::_S_construct<Aws::Http::Standard::StandardHttpResponse<Aws::Http::HttpRequest&> >(std::allocator<Aws::Http::Standard::StandardHttpResponse>&, std::allocator_traits<std::allocator<Aws::Http::Standard::StandardHttpResponse> >::__construct_helper*, (Aws::Http::Standard::StandardHttpResponse<Aws::Http::HttpRequest&>&&)...) (__a=...,  __p=0x55555666ed08) at /usr/include/c++/4.8.3/bits/alloc_traits.h:254
    #12 0x00007fffeb7670be in std::allocator_traits<std::allocator<Aws::Http::Standard::StandardHttpResponse> >::construct<Aws::Http::Standard::StandardHttpResponse<Aws::Http::HttpRequest&> >(std::allocator<Aws::Http::Standard::StandardHttpResponse>&, Aws::Http::Standard::StandardHttpResponse<Aws::Http::HttpRequest&>*, (Aws::Http::Standard::StandardHttpResponse<Aws::Http::HttpRequest&>&&)...) (__a=..., __p=0x55555666ed08) at /usr/include/c++/4.8.3/bits/alloc_traits.h:393
    #13 0x00007fffeb766616 in std::_Sp_counted_ptr_inplace<Aws::Http::Standard::StandardHttpResponse, std::allocator<Aws::Http::Standard::StandardHttpResponse>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<Aws::Http::HttpRequest&> (this=0x55555666ecf0, __a=...) at /usr/include/c++/4.8.3/bits/shared_ptr_base.h:399
    #14 0x00007fffeb764ed0 in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<Aws::Http::Standard::StandardHttpResponse, std::allocator<Aws::Http::Standard::StandardHttpResponse>, (__gnu_cxx::_Lock_policy)2> >::construct<std::_Sp_counted_ptr_inplace<Aws::Http::Standard::StandardHttpResponse, std::allocator<Aws::Http::Standard::StandardHttpResponse>, (__gnu_cxx::_Lock_policy)2><std::allocator<Aws::Http::Standard::StandardHttpResponse> const, Aws::Http::HttpRequest&> > (this=0x7fffffffc507, __p=0x55555666ecf0) at /usr/include/c++/4.8.3/ext/new_allocator.h:120
    #15 0x00007fffeb763da0 in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<Aws::Http::Standard::StandardHttpResponse, std::allocator<Aws::Http::Standard::StandardHttpResponse>, (__gnu_cxx::_Lock_policy)2> > >::_S_construct<std::_Sp_counted_ptr_inplace<Aws::Http::Standard::StandardHttpResponse, std::allocator<Aws::Http::Standard::StandardHttpResponse>, (__gnu_cxx::_Lock_policy)2><std::allocator<Aws::Http::Standard::StandardHttpResponse> const, Aws::Http::HttpRequest&> >(std::allocator<std::_Sp_counted_ptr_inplace<Aws::Http::Standard::StandardHttpResponse, std::allocator<Aws::Http::Standard::StandardHttpResponse>, (__gnu_cxx::_Lock_policy)2> >&, std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<Aws::Http::Standard::StandardHttpResponse, std::allocator<Aws::Http::Standard::StandardHttpResponse>, (__gnu_cxx::_Lock_policy)2> > >::__construct_helper*, (std::_Sp_counted_ptr_inplace<Aws::Http::Standard::StandardHttpResponse, std::allocator<Aws::Http::Standard::StandardHttpResponse>, (__gnu_cxx::_Lock_policy)2><std::allocator<Aws::Http::Standard::StandardHttpResponse> const, Aws::Http::HttpRequest&>&&)...) (__a=..., __p=0x55555666ecf0) at /usr/include/c++/4.8.3/bits/alloc_traits.h:254
    #16 0x00007fffeb76255e in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<Aws::Http::Standard::StandardHttpResponse, std::allocator<Aws::Http::Standard::StandardHttpResponse>, (__gnu_cxx::_Lock_policy)2> > >::construct<std::_Sp_counted_ptr_inplace<Aws::Http::Standard::StandardHttpResponse, std::allocator<Aws::Http::Standard::StandardHttpResponse>, (__gnu_cxx::_Lock_policy)2><std::allocator<Aws::Http::Standard::StandardHttpResponse> const, Aws::Http::HttpRequest&> >(std::allocator<std::_Sp_counted_ptr_inplace<Aws::Http::Standard::StandardHttpResponse, std::allocator<Aws::Http::Standard::StandardHttpResponse>, (__gnu_cxx::_Lock_policy)2> >&, std::_Sp_counted_ptr_inplace<Aws::Http::Standard::StandardHttpResponse, std::allocator<Aws::Http::Standard::StandardHttpResponse>, (__gnu_cxx::_Lock_policy)2><std::allocator<Aws::Http::Standard::StandardHttpResponse> const, Aws::Http::HttpRequest&>*, (std::_Sp_counted_ptr_inplace<Aws::Http::Standard::StandardHttpResponse, std::allocator<Aws::Http::Standard::StandardHttpResponse>, (__gnu_cxx::_Lock_policy)2><std::allocator<Aws::Http::Standard::StandardHttpResponse> const, Aws::Http::HttpRequest&>&&)...) (__a=..., __p=0x55555666ecf0)  at /usr/include/c++/4.8.3/bits/alloc_traits.h:393
    #17 0x00007fffeb760abd in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<Aws::Http::Standard::StandardHttpResponse, std::allocator<Aws::Http::Standard::StandardHttpResponse>, Aws::Http::HttpRequest&> ( this=0x7fffffffca78, __a=...) at /usr/include/c++/4.8.3/bits/shared_ptr_base.h:502
    #18 0x00007fffeb75ec18 in std::__shared_ptr<Aws::Http::Standard::StandardHttpResponse, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<Aws::Http::Standard::StandardHttpResponse>, Aws::Http::HttpRequest&> (  this=0x7fffffffca70, __tag=..., __a=...) at /usr/include/c++/4.8.3/bits/shared_ptr_base.h:957
    #19 0x00007fffeb75b07e in std::shared_ptr<Aws::Http::Standard::StandardHttpResponse>::shared_ptr<std::allocator<Aws::Http::Standard::StandardHttpResponse>, Aws::Http::HttpRequest&> (this=0x7fffffffca70, __tag=..., __a=...) at /usr/include/c++/4.8.3/bits/shared_ptr.h:316
    #20 0x00007fffeb754d54 in std::allocate_shared<Aws::Http::Standard::StandardHttpResponse, std::allocator<Aws::Http::Standard::StandardHttpResponse>, Aws::Http::HttpRequest&> (__a=...) at /usr/include/c++/4.8.3/bits/shared_ptr.h:598
    #21 0x00007fffeb74dfce in Aws::MakeShared<Aws::Http::Standard::StandardHttpResponse, Aws::Http::HttpRequest&> ( allocationTag=0x7fffeb9211e7 "CurlHttpClient") at /var/task/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSAllocator.h:106
    #22 0x00007fffeb73cbe2 in Aws::Http::CurlHttpClient::MakeRequest (this=0x7fffffffcdb0, request=..., readLimiter=0x0, writeLimiter=0x0) at /var/task/aws-sdk-cpp/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp:342

I realise that I am probably just using `CurlHttpClient` incorrectly, and would really appreciate some guidance as I can't see what else I should be doing here and I am unable to find relevant examples anywhere.

**Comment by JonathanHenson** [comment]
You need to go through the http client factory to create the request. That binds the closure for creating the response stream to the request.

**Comment by tawhirimatea** [comment]
Thanks for the nudge in the right direction. I have this working well now.
