### ISSUE TITLE
In S3, calling `SetIfNoneMatch` with a blank string causes a segfault

### ISSUE THREAD

**Issue by evorw** [aws/aws-sdk-cpp#331]
If you run:
```
Aws::S3::Model::GetObjectRequest getObjectRequest;
getObjectRequest.WithKey(src.key).WithBucket(src.bucket);
std::cout << "Set the desired ETag value (" << targetMD5 << ")\n";
getObjectRequest.SetIfNoneMatch(targetMD5); //sets a header in the request that tells S3 to check the MD5 we send, and return 200 + file if the MD5s are different, or 304 otherwise
std::cout << "Make the GET request...";
auto getObjectOutcome = client.GetObject(getObjectRequest);
std::cout << "...done\n";
```
with `targetMD5` set to a blank string, the program has a segmentation fault when we call `SetIfNoneMatch`. The output is:
```
Set the desired ETag value ()
Segmentation fault
```
Logs are:
```
[INFO] 2016-11-08 22:35:43 CurlHttpClient [3069894656] Initializing Curl library
[INFO] 2016-11-08 22:35:44 CurlHandleContainer [3069894656] Initializing CurlHandleContainer with size 25
[TRACE] 2016-11-08 22:35:44 AWSClient [3069894656] No content body, content-length headers
[DEBUG] 2016-11-08 22:35:44 AWSAuthV4Signer [3069894656] Calculated sha256 e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 for payload.
```

**Comment by JonathanHenson** [comment]
it looks like targetMD5 is a const char* that is nullptr. Is this the case?

**Comment by evorw** [comment]
No, it's a `const std::string("")`. At the moment I work around this by ensuring `(!targetmd5.empty())`.

**Comment by bretambrose** [comment]
How does that compile?  std::string is incompatible with Aws::String

**Comment by bretambrose** [comment]
Can we get your system/platform information, cmake command line , cmake output, crash call stack, and a complete (simplified) main.cpp?  All that happens in that function is string assignment and we don't get that crash locally.

**Comment by evorw** [comment]
I'm running on am embedded target without `gdb` or core dumps, so I can't give you a crash call stack.

I cross-compile on a 32-bit Ubuntu 12.04.5 host to ARM. The gcc version is:
```
$ /usr/local/linaro-armv6k-2013.10-gcc4.8/bin/arm-linux-gnueabi-gcc --version
arm-linux-gnueabi-gcc (crosstool-NG - Ambarella Linaro GCC ARMv6k 2013.10) 4.8.2 20131014 (prerelease)
```

My `cmake` command line is:
`cmake -DCMAKE_TOOLCHAIN_FILE=[my_path]/[my_cmake_toolchain_file] -DBUILD_ONLY="s3" -DCUSTOM_MEMORY_MANAGEMENT=0 -DENABLE_TESTING=OFF ~/aws-sdk-cpp/`

`my_cmake_toolchain_file` referenced above looks like:
```
# this one is important
SET(CMAKE_SYSTEM_NAME Linux)
#this one not so much
SET(CMAKE_SYSTEM_VERSION 1)

SET(CMAKE_TARGET_ARCH Linux)

# specify the cross compiler
SET(CMAKE_C_COMPILER   /usr/local/linaro-armv6k-2013.10-gcc4.8/bin/arm-linux-gnueabi-gcc)
#CMake should figure out CXX etc based on value of C_COMPILER

SET(CMAKE_C_COMPILER_TARGET arm-linux-gnueabi)

# where is the target environment 
SET(CMAKE_FIND_ROOT_PATH [my_path]/zlib [my_path]/openssl [my_path]/libcurl [my_path]/util-linux)

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

The generated `CMakeCache.txt`, `Makefile`, `aws-sdk-cpp-config.cmake`, and `cmake_install.cmake` are in the attached  [cmakeoutputs.zip](https://github.com/aws/aws-sdk-cpp/files/584750/cmakeoutputs.zip).

See the CPP file [aws-s3-sample.cpp.zip](https://github.com/aws/aws-sdk-cpp/files/584797/aws-s3-sample.cpp.zip) for my program. I pass the credentials to `Aws::S3::S3Client` as an `Aws::Auth::AWSCredentials`, and set the `caPath` in the `Aws::Client::ClientConfiguration`. I guess both of these are probably unusual?

**Comment by bretambrose** [comment]
None of those settings should really make a difference.  What happens if you set other string members of S3 requests to an empty string?  Do they crash too?  It seems like a possible STL empty string optimization issue (we struggled with gnu stl's empty string optimization on android for a while and ending up switching to libc++ as a default to get around it).  Is _GLIBCXX_FULLY_DYNAMIC_STRING defined on your platform?

**Comment by evorw** [comment]
I can no longer duplicate this error. I'm running `aws-sdk-cpp/1.0.2` which I believe is what I was running before, and pretty sure I'm running the same code. But it behaves now. I'll keep an eye out but closing this issue now.

By the way _GLIBCXX_FULLY_DYNAMIC_STRING is defined.
