### ISSUE TITLE
Use of strlen 

### ISSUE THREAD

**Issue by chadbrewbaker** [aws/aws-sdk-cpp#337]
I noticed strlen was being used instead of strnlen in a number of routines. Unbounded loops are problematic.

What is the max size we want URIs? One megabyte should be more than enough: http://stackoverflow.com/questions/2659952/maximum-length-of-http-get-request

What is the max size we want most XML/JSON files? Can we infer this from the JSON/XML parser being used?

**Comment by bretambrose** [comment]
Do you have any specific instances in mind?  Glancing over the source, most uses are either (1) tests, (2) generic utilities, or (3) json-cpp/tinyxml2 (which we only want to modify if absolutely necessary), none of which feel like compelling targets.  I love logical invariants in code, but I'm not seeing where this would be appropriate.

**Comment by JonathanHenson** [comment]
Closing, please reopen if you have further questions.
