### ISSUE TITLE
aws-sdk-cpp-config.cmake references .cmake files that don't exist

### ISSUE THREAD

**Issue by csimmons0** [aws/aws-sdk-cpp#339]
I get this error when I try to build my Android project:
```
CMake Error at /Users/christophersimmons/Documents/repos/DoclilyAndroid/build-aws-cpp-sdk/aws-sdk-cpp-config.cmake:1 (include):
include could not find load file:
/Users/christophersimmons/Documents/repos/DoclilyAndroid/build-aws-cpp-sdk/aws-cpp-sdk-core/aws-cpp-sdk-core-config.cmake
```
When I look at aws-sdk-cpp-config.cmake, I see that it references .cmake files that don't exist.
```
~/Documents/repos/DoclilyAndroid/build-aws-cpp-sdk$ cat ./aws-sdk-cpp-config.cmake 
include("${CMAKE_CURRENT_LIST_DIR}/aws-cpp-sdk-core/aws-cpp-sdk-core-config.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/aws-cpp-sdk-cognito-identity/aws-cpp-sdk-cognito-identity-config.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/aws-cpp-sdk-iam/aws-cpp-sdk-iam-config.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/aws-cpp-sdk-access-management/aws-cpp-sdk-access-management-config.cmake")
~/Documents/repos/DoclilyAndroid/build-aws-cpp-sdk$ ls -1 aws-cpp-sdk-core
CMakeFiles
Makefile
cmake_install.cmake
libaws-cpp-sdk-core.so
```
The other three folders look similar. How can I fix this problem? In case it matters, I originally created the sdk's build folder by running the following:
```
cmake -DTARGET_ARCH=ANDROID -DNDK_RELEASE=r13b -DANDROID_NATIVE_API_LEVEL=21 -DBUILD_ONLY="cognito-identity;access-management" -DANDROID_ABI=mips64 -Wno-dev ../deps/aws-sdk-cpp/
```

**Comment by bretambrose** [comment]
What happens when you clear your build directory and add 'core' to the BUILD_ONLY list?

**Comment by csimmons0** [comment]
Same issue when I ran
`cmake -DTARGET_ARCH=ANDROID -DNDK_RELEASE=r13b -DANDROID_NATIVE_API_LEVEL=21 -DBUILD_ONLY="core;cognito-identity;access-management" -DANDROID_ABI=mips64 -Wno-dev ../deps/aws-sdk-cpp/`

**Comment by bretambrose** [comment]
What version of cmake are you using?

**Comment by csimmons0** [comment]
```
~/Documents/repos/DoclilyAndroid/build-aws-cpp-sdk$ cmake --version
cmake version 3.6.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by bretambrose** [comment]
Oh wait, the packaging and config generation is not enabled for android I think.  We should be able to fix this fairly quickly.

**Comment by bretambrose** [comment]
I have a potential fix pushed to the FB-ConfigFix branch.  Can you give it a try?  If it works out, we will probably have it pushed to mainline after some more extensive testing tomorrow.

**Comment by csimmons0** [comment]
I'll try it now.

**Comment by csimmons0** [comment]
I'm hitting a different issue that's due to an error on my part, but I think that the CMake issue is fixed now.
```
~/Documents/repos/DoclilyAndroid/build-aws-cpp-sdk$ ls -1 ./aws-cpp-sdk-core
CMakeFiles
Makefile
aws-cpp-sdk-core-config-version.cmake
aws-cpp-sdk-core-config.cmake
aws-cpp-sdk-core-targets.cmake
aws-cpp-sdk-core.pc
cmake_install.cmake
libaws-cpp-sdk-core.so
```
