### ISSUE TITLE
S3Client::HeadObject bug.

### ISSUE THREAD

**Issue by AlienTechLAB** [aws/aws-sdk-cpp#345]
Hi.

I called S3Client::HeadObject for non-existent file in bucket. Outcome::IsSuccess() returns, of course, false.

The problem is:
HeadObjectOutcome::GetError().GetErrorType() returns only 100 (S3Errors::UNKNOWN).
HeadObjectOutcome::GetError().GetExceptionName() returns empty string.

I was expecting to get proper error code and proper exception name. For now, the only way to check if file exists or not is to check if HeadObjectOutcome::GetError().GetMessage() returns: "No response body. Response code: 404".

Thank you in advance.

**Comment by bretambrose** [comment]
The response from a failed HeadObject request does not actually have a body which is what we normally use to construct error messages.  I'll check with Jonathan to determine if we want to add some hand-written empty-response handling into the S3 client (translating 404s appropriately into Bucket/Key/Object Not Found errors, for example).

**Comment by JonathanHenson** [comment]
I just sent out a CR for this. We will now always resolve 404 -> RESOURCE_NOT_FOUND, 401 and 403 ->ACCESS_DENIED

If there is no body. It should be pushed out shortly

**Comment by JonathanHenson** [comment]
I just pushed the fix. Should be fixed now.
