### ISSUE TITLE
S3: question about RequestTimeout 

### ISSUE THREAD

**Issue by mikewang2016** [aws/aws-sdk-cpp#346]
When internet network is slow, it's quite common to see error message below during data upload.

_RequestTimeout Message: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed_

Sometimes, retry can work, but for most of the time, it does not work even after retries several times.

What can cause this problem? And what's "timeout period"?

**Comment by JonathanHenson** [comment]
See the ClientConfiguration, there are two parameters you may be interested in. RequestTimeout and ConnectTimeout. They both default to 3 seconds. You probably want to increase the request timeout.

**Comment by mikewang2016** [comment]
Yes, I have set ConnectTimeout=10s, RequestTimeout=200s, but can still see this error message.

I can see that a request may hang for 40s, and then report this error.

**Comment by mikewang2016** [comment]
By the way, I am using multiparts upload, every part is about 10MB.

**Comment by mikewang2016** [comment]
more information:

After tested over several networks, I found that this problem only occurs in a network which has packet lost.

It has nothing to do with network latency: a high latency network can work perfect as long as there is no packet lost.

If there are packet lost sometimes (not really always), then there is high chance this problem can occur. 

BTW: I am using "Aws::StringStream" to feed "SetBody()" of "UploadPartRequest", if I get RequestTimeout exception from "UploadPart", and want to retry the upload, do I need first rewind by calling "seekg (0, is.beg)" of "Aws::StringStream"?

**Comment by mikewang2016** [comment]
Can I have an update on this query?

**Comment by JonathanHenson** [comment]
Request timeout is supposed to automatically trigger a retry using an exponential backoff strategy. The retry will automatically rewind your stream. If you manually retry, you do need to rewind the stream manually. Though, I would recommend simply injecting a retry strategy into the client configuration to do what you need it to do.

**Comment by JonathanHenson** [comment]
I just reworked the timeouts for curl implementations to behave more like a socket read timeout. You should be able to set this back to something reasonable (like 3 seconds)  and everything will work as it does on windows.

**Comment by lavikonm** [comment]
hi 

How did this story end ? I am facing same problem as described on top ( RequestTimeout Message: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed )

I have been trying to test S3 with AWS SDK wiht c++ .. but this putobject sample is the one that I can not get working 

So this one is the problematic one now:
**aws-doc-sdk-examples/cpp/example_code/s3/put_object.cpp**

I tried putting object into bucket created by me .. 

Sample apps for "creating bucket" , "listing of bucket content" and e.g "deleting buckets" are working well

Credentials for S3 are set properly I have compiled AWS sdk, latest from master branch with Windows 10 and VIsual Studio 2013
