### ISSUE TITLE
S3: question about multiple files upload in one process

### ISSUE THREAD

**Issue by mikewang2016** [aws/aws-sdk-cpp#348]
Hello,

I have an application which is single process but contains multiple threads. every thread tries upload a separate file using multiparts upload method.

In such case, can I just create S3Client in main thread, and then share this S3Client across all threads? Will that cause performance bottleneck?

Thanks
Mike

**Comment by JonathanHenson** [comment]
Always use only one client per configuration.

On another note, have you tried the TransferManager, it will handle this for you.

The trouble with doing multiple files in parallel is hard drive thrash--unless you are using solid state.

**Comment by mikewang2016** [comment]
Thank you. So I can create S3Client in main thread, and then use it in multiple child thread.

My application is a producer/consumer model. So, it actually upload data from memory to S3. That's why I need best upload performance in multithread environment.
