### ISSUE TITLE
UUID::RandomUUID() is broken on Android

### ISSUE THREAD

**Issue by csimmons0** [aws/aws-sdk-cpp#351]
The code in the Android version of UUID_Impl.cpp has at least one bug in it that causes a read past the end of a buffer, and I think that it has some other issues as well.

        UUID UUID::RandomUUID()
        {
            char uuid[UUID_STR_SIZE];
            memset(uuid, 0, sizeof(uuid));

            FILE* fd = fopen("/proc/sys/kernel/random/uuid", "r");

            if(fd)
            {
                fread(uuid, sizeof(uuid), sizeof(uuid), fd);
                fclose(fd);
            }
            Aws::String uuidStr(uuid);
            return UUID(uuidStr);
        }

"char uuid[UUID_STR_SIZE]" has room for a UUID string's characters but not room for a null-terminator, which the constructor that's invoked to create uuidStr must require. When this code runs on my test device, uuidStr is initialized as a string that has a UUID plus a few more characters, and an assertion inside the UUID constructor fails because uuidStr is too long.

I also believe that the call to fread is reading sizeof(uuid) * sizeof(uuid) bytes. The third argument should just be "1".

Lastly, this function will fail silently if fopen or fread fails. Even if the other bugs were fixed, there might not be a good way to get around this problem as long as this function is trying to get a UUID by reading /proc/sys/kernel/random/uuid. I think that there are better ways to get a UUID on Android.

One way is to use boost's UUID implementation. I haven't tried building with it yet, but I believe that it's a header-only implementation that we could just drop into the code. http://www.boost.org/doc/libs/1_62_0/libs/uuid/uuid.html

Another way is to define a "UUIDFactory" interface and add a corresponding option to the SDK's CryptoOptions. Users could then Implement UUID generation however they wanted to--possibly by calling from C++ back to Java code to access the Java library's UUID functions.

**Comment by JonathanHenson** [comment]
boost isn't an option. this is the only non java way of grabbing a uuid on android. if you know of a c way of doing this I'm open to it.

I'll fix the buffer overrun issue.

**Comment by csimmons0** [comment]
What do you think of extending the SDK's options to allow a user-supplied UUID generator? I'm willing to do that work, and it would allow users to eliminate the unhandled failure points that fopen and fread create. I'm using Djinni, and my generator would be a C++ class that calls some Java code to get a UUID.

**Comment by bretambrose** [comment]
I fixed this last week but it's not pushed to live yet.

**Comment by JonathanHenson** [comment]
we already have that essentially with the secure random implementations. Im actually wanting to delete the platform based uuid stuff and have everything use secure random.

**Comment by JonathanHenson** [comment]
I've just removed this entirely and implemented version 4 of the spec as this:

UUID UUID::RandomUUID()
        {
            auto secureRandom = Crypto::CreateSecureRandomBytesImplementation();
            assert(secureRandom);

            unsigned char randomBytes[UUID_BINARY_SIZE];
            memset(randomBytes, 0, UUID_BINARY_SIZE);
            secureRandom->GetBytes(randomBytes, UUID_BINARY_SIZE);
            //Set version bits to 0100
            //https://tools.ietf.org/html/rfc4122#section-4.1.3
            randomBytes[VERSION_LOCATION] = (randomBytes[VERSION_LOCATION] & VERSION_MASK) | VERSION;
            //set variant bits to 10
            //https://tools.ietf.org/html/rfc4122#section-4.1.1
            randomBytes[VARIANT_LOCATION] = (randomBytes[VARIANT_LOCATION] & VARIANT_MASK) | VARIANT;

            return UUID(randomBytes);
        }

It's running through CI right now, it should be available in the next few hours.
