### ISSUE TITLE
Android: build error with -DNO_HTTP_CLIENT=ON

### ISSUE THREAD

**Issue by antoinelefebvre** [aws/aws-sdk-cpp#352]
I am able to build successfully for Android with the standard options. When compiling with -DNO_HTTP_CLIENT=ON, the build fails with the following error:

In file included from [...]/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:18:
[...]/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/crypto/openssl/CryptoImpl.h:22:10: fatal error: 'openssl/ossl_typ.h' file not found
#include <openssl/ossl_typ.h>

That same file compiles fine when the NO_HTTP_CLIENT is OFF. The openssl files are definitely present in external/openssl, 

There must be a bug in the cmake files somewhere. Looking for the problem. Anyone can help here?

**Comment by bretambrose** [comment]
I'll take a look at this today.

What version are you building from?

**Comment by antoinelefebvre** [comment]
I am on commit 28e7a087ef3b780be8899240ec6a1535a5dcfca7.

I found a workaround. In aws-cpp-sdk-core/CMakeLists.txt, there is a section if (PLATFORM_ANDROID) with 
 set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CURL_CXX_FLAGS} -I${CURL_INCLUDE_DIR}" )
 set( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${CURL_C_FLAGS} -I${CURL_INCLUDE_DIR}" )

I removed the curl entries and added OPENSSL ones. Looks like the proper conditional based on the options is missing.

Thanks.

**Comment by antoinelefebvre** [comment]
Full cmake command line:

cmake ../aws-sdk-cpp -DBUILD_SHARED_LIBS=OFF -DENABLE_TESTING=OFF -DBUILD_ONLY="s3;dynamodb;cognito-identity;access-management;identity-management;cognito-idp" -DNO_HTTP_CLIENT=ON -DTARGET_ARCH=ANDROID -DCMAKE_INSTALL_PREFIX:PATH=my/path -DNDK_DIR=../android-ndk-r10e

**Comment by bretambrose** [comment]
Yeah that's it; I'll try and clean it up.  Just out of curiosity, what's your use case for not using curl?  Do you have your own native http client?

**Comment by antoinelefebvre** [comment]
Yes, we are using the AWS SDK in a Qt 5 app and we use the Qt Networking classes. I wrote a custom http client.

**Comment by JonathanHenson** [comment]
id love to offer qt out of the box. would you care to make a pull request?

**Comment by bretambrose** [comment]
We're in the middle of reinvent so the Android updates I've been doing may not make it out for a few days (depends on how much Jonathan wants to review some test refactors) but the actual change we'll apply to fix your issue will be to replace the if(PLATFORM_ANDROID) block with:

if(BUILD_CURL)
  set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I${CURL_INCLUDE_DIR}" )
endif()

if(BUILD_OPENSSL)
  set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I${OPENSSL_INCLUDE_DIR}" )
endif()

if(BUILD_ZLIB)
  set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I${ZLIB_INCLUDE_DIR}" )
endif()

We only want this in core, so we don't push out globally back in build_external.cmake

**Comment by antoinelefebvre** [comment]
> id love to offer qt out of the box. would you care to make a pull request?

This is something I am doing for Realtime Music Solutions (http://rms.biz). I'll see if they agree to share the code and at what conditions.

**Comment by bretambrose** [comment]
This should be fixed in yesterday's release.
