### ISSUE TITLE
Compile error on VS 2015 using NuGet Packages

### ISSUE THREAD

**Issue by MattyBoy4444** [aws/aws-sdk-cpp#353]
When I include S3Client.h I get the following.   I am new to this lib, BTW.

`\build\native\include\aws\s3\model\getbucketpolicyresult.h(54): error C2440: '<function-style-cast>': cannot convert from 'Aws::IOStream *' to 'Aws::Utils::Stream::ResponseStream'
\build\native\include\aws\s3\model\getbucketpolicyresult.h(54): note: No constructor could take the source type, or constructor overload resolution was ambiguous
\build\native\include\aws\s3\model\getobjectresult.h(61): error C2440: '<function-style-cast>': cannot convert from 'Aws::IOStream *' to 'Aws::Utils::Stream::ResponseStream'
\build\native\include\aws\s3\model\getobjectresult.h(61): note: No constructor could take the source type, or constructor overload resolution was ambiguous
\build\native\include\aws\s3\model\getobjecttorrentresult.h(51): error C2440: '<function-style-cast>': cannot convert from 'Aws::IOStream *' to 'Aws::Utils::Stream::ResponseStream'
\build\native\include\aws\s3\model\getobjecttorrentresult.h(51): note: No constructor could take the source type, or constructor overload resolution was ambiguous
`

Any Ideas?

**Comment by bretambrose** [comment]
We think there may be some versioning issues when using nuget packages (aws-cpp-sdk-core version vs. all other services version).  Could this be the case here?  Have you tried clearing your nuget cache and re-getting everything?  Jonathan is the nuget expert so he probably has a better explanation/idea as to what's going on.

**Comment by JonathanHenson** [comment]
We currently have a problem with NuGet where if we change the stack size of anything in the core runtime, it is no longer compatible with a version of the low-level client that expected a different stack size (in either direction). The way nuget currently works with native code, we can't set an upper bound on the version range. Can you try wiping out your package cache and making sure you use the latest version of all packages?

I have a fix for this in mind where we just always force the latest core version for each sdk update.
