### ISSUE TITLE
Non-default regions get hostnames that AWS confuses with buckets

### ISSUE THREAD

**Issue by eczeek** [aws/aws-sdk-cpp#354]
The hostname that the ForRegion creates looks like a vitual host rather than a path access to AWS, and subsequent uses will cause non-existent bucket errors. The following patch fixed it for me.

```diff
diff --git a/aws-cpp-sdk-s3/source/S3Endpoint.cpp b/aws-cpp-sdk-s3/source/S3Endpoint.cpp
index d054438..96e2579 100644
--- a/aws-cpp-sdk-s3/source/S3Endpoint.cpp
+++ b/aws-cpp-sdk-s3/source/S3Endpoint.cpp
@@ -76,7 +76,7 @@ namespace S3Endpoint
       }
     }
     Aws::StringStream ss;
-    ss << "s3" << ".";
+    ss << "s3" << "-";
 
     if(useDualStack)
     {
```

**Comment by JonathanHenson** [comment]
- is legacy, and you'll notice those are explicitly cased out. "." is how all new endpoints should be addressed.

**Comment by eczeek** [comment]
The documentation seems to say otherwise:
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro

**Comment by JonathanHenson** [comment]
Here is a list of the regions and endpoints for S3:

http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by JonathanHenson** [comment]
The regions called out as needing '-' instead of '.' are explicitly white listed and given the '-' prefix. The others use '.'. This is the recommendation from S3 for our SDKs.

**Comment by eczeek** [comment]
Sorry for not replying to this sooner, but your list is missing an endpoint, s3-us-gov-west-1.amazonaws.com.

http://docs.aws.amazon.com/de_de/govcloud-us/latest/UserGuide/using-govcloud-endpoints.html

**Comment by singku** [comment]
That endpoint has been added already.
