### ISSUE TITLE
SQSClient throws access violation when created

### ISSUE THREAD

**Issue by yishais** [aws/aws-sdk-cpp#357]
Trying to create an SQS queue.

```
Aws::SDKOptions options; 
Aws::InitAPI(options); 
Aws::Client::ClientConfiguration configuration; 
configuration.region = Aws::Region::US_WEST_2; 
Aws::SQS::SQSClient sqs = new Aws::SQS::SQSClient(Aws::Auth::AWSCredentials("abc", "def"), configuration);

```
Running on Windows, 64 bit, VC++.

When I run I will get an access violation:
Exception thrown at 0x000007FEE4E9C83C (aws-cpp-sdk-core.dll) in TestDB.exe: 0xC0000005: Access violation reading location 0x0000000000000000.  Latest SDK version. (.35)

This will happen deep in the call chain of the sdk. There are no parameters I can pass as null pointers, so i'm not sure what it can be. I'm able to run against S3 with no issues, just SQS.

-Yishai

**Comment by bretambrose** [comment]
Are you building the library from source or using a nuget release?

**Comment by yishais** [comment]
nuget release

**Comment by JonathanHenson** [comment]
Sorry for the delay. We currently have a problem with NuGet where if we change the stack size of anything in the core runtime, it is no longer compatible with a version of the low-level client that expected a different stack size (in either direction). The way nuget currently works with native code, we can't set an upper bound on the version range. Can you try wiping out your package cache and making sure you use the latest version of all packages?

I have a fix for this in mind where we just always force the latest core version for each sdk update.

**Comment by yishais** [comment]
Unfortunately, I don't think this is it. I cleared all the packages and reinstalled them. Also used the latest packages (ends with .38). Verified all packages are of the last (and same) version, and made sure there is not old package in the packages folder (or being downloaded at runtime). Unfortunately, its the same behavior and the same crash.

**Comment by JonathanHenson** [comment]
could you send me your project so I can see better whats going on?

**Comment by yishais** [comment]
A little large as I wanted it to include the packages. It¹s really divided
into one solution in VC with two sub projects. You start with the TessDB
that has one file that does test calls, and all the actual calls happen in
the other library project. If you look at the code it will take you less
than 20 lines to get there.

https://s3-us-west-2.amazonaws.com/preview.sendtoprint.net/preview/SMIStorag
e.zip

Thanks

Yishai

From:  "Jonathan M. Henson" <notifications@github.com>
Reply-To:  aws/aws-sdk-cpp
<reply+0173c67758ac5e59b304118991a46db9805e02eb6909563f92cf000000011461d7849
2a169ce0b85ff6e@reply.github.com>
Date:  Thursday, December 8, 2016 at 6:23 PM
To:  aws/aws-sdk-cpp <aws-sdk-cpp@noreply.github.com>
Cc:  Yishai <yishai@digi-labs.net>, Author <author@noreply.github.com>
Subject:  Re: [aws/aws-sdk-cpp] SQSClient throws access violation when
created (#357)

> could you send me your project so I can see better whats going on?
> 
> Sent from my iPhone
>

**Comment by JonathanHenson** [comment]
Sorry for the delay, one thing I immediately notice is that TestDB has SQS being linked dynamically while everythine else is configured as static. Can you try setting it as Static and try again?

**Comment by yishais** [comment]
That was it. Now I feel really embarrassed. (note to myself to always check project setting) ;-)
Thanks.
