### ISSUE TITLE
Regarding AWS-C++ Kinesis

### ISSUE THREAD

**Issue by acsdkquery** [aws/aws-sdk-cpp#360]
Hi, Am using AWS-C++ SDK. And am only using Kinesis service and developing a kinesis client program. I want to know what and all the relevant source files required/port from AWS SDK, so that my Kinesis client program will run successfully. 

Am not at all using other services like SQS,etc...

So want to make sure the required files (.h and .cpp) from SDK for my kinesis client program

Thanks,

**Comment by bretambrose** [comment]
In that case, it sounds like all you need is core and kinesis, so something like:

cmake -DBUILD_ONLY="core;kinesis" <path-to-sdk>

And if shipping shared libraries, you'll only need aws-cpp-sdk-core.so/dll and aws-cpp-sdk-kinesis.so/dll

**Comment by acsdkquery** [comment]
Thanks. when i tried cmake (cmake ../aws-sdk-cpp/aws-cpp-sdk-core ../aws-sdk-cpp/aws-cpp-sdk-kinesis), am getting the following error. 

But if i tried cmake ../aws-sdk-cpp (full sdk source, then working)
 
building in linux ;

arunc@arunc-VirtualBox:~/openwrt/SDK_build_onlyKinesis$ cmake ../aws-sdk-cpp/aws-cpp-sdk-core ../aws-sdk-cpp/aws-cpp-sdk-kinesis
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:1 (add_project):
  Unknown CMake command "add_project".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.5)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/arunc/openwrt/SDK_build_onlyKinesis/CMakeFiles/CMakeOutput.log".
arunc@arunc-VirtualBox:~/openwrt/SDK_build_onlyKinesis$

**Comment by Bu11etmagnet** [comment]
You should always point cmake at the root of the AWS SDK project. The CMakeLists.txt there has the ability to select and build a subset of the SDK:

    cmake -DBUILD_ONLY="core;kinesis"  ../aws-sdk-cpp

There **is** a `cmake_minimum_required (VERSION 2.8.12)` in the top-level CMakeLists.txt

**Comment by acsdkquery** [comment]
Thank you..its working.....i have a quick question,
i plan to create a new application (outside of root:aws-sdk-cpp), lets say, Application Directory: Kinesis_Client

So, if i copy only aws-cpp-sdk-core & aws-cpp-sdk-kinesis, and required shared libraries (aws-cpp-sdk-core.so and aws-cpp-sdk-kinesis.so) with my New_kinesis_client.cpp , that should be fine? 
 
Kindly suggest, Thanks.

**Comment by bretambrose** [comment]
You shouldn't really need to copy anything.  If you're using cmake, you can follow the steps here (https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/) to have your other project reference the SDK build.  If you're not using cmake, you could always do an install of the SDK at either the system level or within your project to a common dependencies location.

But yes, all that you technically will need are the headers from core & kinesis, as well as the two shared libraries.

**Comment by acsdkquery** [comment]
Thanks much bretambrose....my client program is working as per the link which u provided,

full AWS-SDK-->cmake -DBUILD_ONLY="core;kinesis"--> CMakeLists.txt (New_kinesis_client.cpp)->make

its working fine in my local linux machine.

Suppose i want to port this client program to some device running linux platform. Since its compiling with cmake, whether i have to port 'full AWS-SDK' also?

or something like below will work?

**(only kinesis/core source from)** AWS-SDK-->cmake -DBUILD_ONLY="core;kinesis"--> CMakeLists.txt (New_kinesis_client.cpp)->make

because i am using only kinesis service, i don't want to port complete AWS-SDK source code to my device.

**Comment by bretambrose** [comment]
Given the SDK's minimal dependencies, it's likely to be easy-to-trivial (ie, just build) to port to common Linux flavors.  Either way, you won't need to do the whole SDK, you can continue to just build and use the subset you want.

**Comment by acsdkquery** [comment]
That really helped. Thanks,
