### ISSUE TITLE
Failed to build AmazonSerializableWebServiceRequest.cpp.o with ANDROID_TOOLCHAIN_NAME = standalone 

### ISSUE THREAD

**Issue by DeepakArora76** [aws/aws-sdk-cpp#363]
> cmake -G "NMake Makefiles" -DTARGET_ARCH=ANDROID -DANDROID_TOOLCHAIN_NAME=standalone -DBUILD_ONLY="cognito-identity;lambda;dynamodb;s3;cognito-sync;cognito-idp" -DCMAKE_BUILD

Scanning dependencies of target aws-cpp-sdk-core
[  2%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/AmazonSerializableWebServiceRequest.cpp.o
In file included from d:\aws\aws-sdk-cpp\toolchains\android\armeabi-v7a-standalone-android-21-libc++_shared-13002\include\c++\4.9.x\type_traits:387:0,
                 from d:\aws\aws-sdk-cpp\toolchains\android\armeabi-v7a-standalone-android-21-libc++_shared-13002\include\c++\4.9.x\memory:599,
                 from D:/AWS/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/memory/AWSMemory.h:22,
                 from D:/AWS/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSAllocator.h:21,
                 from D:/AWS/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSFunction.h:20,
                 from D:/AWS/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/AmazonWebServiceRequest.h:20,
                 from D:/AWS/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/AmazonSerializableWebServiceRequest.h:19,
                 from D:\AWS\aws-sdk-cpp\aws-cpp-sdk-core\source\AmazonSerializableWebServiceRequest.cpp:16:
d:\aws\aws-sdk-cpp\toolchains\android\armeabi-v7a-standalone-android-21-libc++_shared-13002\include\c++\4.9.x\cstddef:43:25: error: no include path in which to search for stddef.h
 #include_next <stddef.h>
                         ^
cc1plus.exe: error: unrecognized command line option "-Wno-unused-private-field" [-Werror]
cc1plus.exe: all warnings being treated as errors
NMAKE : fatal error U1077: 'D:\AWS\aws-sdk-cpp\toolchains\android\armeabi-v7a-standalone-android-21-libc++_shared-13002\bin\arm-linux-androideabi-g++.exe' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.

**Comment by DeepakArora76** [comment]
Is it okay to have the below change in the file cstddef in the folder aws-sdk-cpp\toolchains\android\armeabi-v7a-standalone-android-21-libc++_shared-13002\include\c++\4.9.x> ?

> #include_next <stddef.h> to #include_next <stddef.h>

**Comment by bretambrose** [comment]
Your cmake command line is cut off.

**Comment by DeepakArora76** [comment]
Sorry for that.

> cmake -G "NMake Makefiles" -DTARGET_ARCH=ANDROID -DANDROID_TOOLCHAIN_NAME=standalone -DBUILD_ONLY="cognito-identity;lambda;dynamodb;s3;cognito-sync;cognito-idp" -DCMAKE_BUILD_TYPE=Release -DNDK_DIR=C:/Android/android-ndk-r13b D:/AWS/aws-sdk-cpp

**Comment by DeepakArora76** [comment]
It built nicely after I made below change to cstddef file:
> #include_next <stddef.h> to #include <stddef.h>

I believe that the change what I made may not be right for the reason that the file contains a comment which says:
> // Don't include our own <stddef.h>; we don't want to declare ::nullptr_t.
> #include_next <stddef.h>

**Comment by bretambrose** [comment]
Any way you could change to clang (ANDROID_TOOLCHAIN_NAME=standalong-clang)?  Gcc was deprecated back in r12 and you may have stumbled upon an incompatibility between libc++ and gcc.

**Comment by DeepakArora76** [comment]
I would really like to use CLANG, but unfortunately QT SDK (which I am using) is not available With CLANG. QT team believes that CLANG produces Heavy Object code / Library.  There is no instructions or guidelines either from QT team on building their SDK using CLANG.

Having said that, one of the easy solution would be AWS SDK compiled using GCC, or I a take difficult journey which would be building QT using CLANG. Or, I switch to using r10 or r11 :) which supports GCC.

I know that GCC was deprecated in r12, but that does not prevent developers to use it. I believe that developers around the world are still using GCC.

Could it be possible for AWS team to make their sdk compatible for both the toolchains? 

Is there a problem if I change the line "#include_next <stddef.h> to #include <stddef.h>" in cstddef?

**Comment by bretambrose** [comment]
Well, it really isn't an issue in the AWS SDK itself.  Everything under toolchains/android is generated by the NDK's standalone toolchain script (see the .gitignore).  While you can modify something under there, it's a brittle solution since anyone else building the same repo won't have those changes; essentially you're modifying the C library headers at that point.  You could add some patching logic to the cmake scripts (after the toolchain generation in android.cmake, which you've looked at before since it's where the python dependency was missing).

I should have generated the toolchain under the build directory to avoid confusion.

I'll investigate a few workarounds.

For reference, this is a known issue with the ndk r13:

https://www.bountysource.com/issues/38341727-stddef-h-no-such-file-or-directory

**Comment by bretambrose** [comment]
This should be fixed in yesterday's release.  Please reopen if you still are having problems with it.
