### ISSUE TITLE
Distinguish between the Release and Debug libraries 

### ISSUE THREAD

**Issue by DeepakArora76** [aws/aws-sdk-cpp#364]
What I found that 

> msbuild` INSTALL.vcxproj /p:Configuration=**DEBUG**

and 

> msbuild INSTALL.vcxproj /p:Configuration=**RELEASE**

produces binaries having same name.

As an example building **aws-cpp-sdk-cognito-idp** in debug and release produces lib/dll with same name. This would leads to accidental overwriting / replacing of previously installed version.

**Comment by bretambrose** [comment]
We'll add an optional Windows-only suffix (empty by default to maintain current behavior) for debug libraries.

**Comment by bretambrose** [comment]
Yesterday I added an option to the CMake setup that, on Windows only, lets you specify a suffix to be appended to the library name on Debug builds ('D' being the obvious choice).  Would this be a satisfactory solution for you?

**Comment by JonathanHenson** [comment]
yes, id do it on linux too though.

**Comment by bretambrose** [comment]
Do people expect that on Linux though?  My (admittedly cursory) research suggested that debug libraries just get installed to a different spot and name mangling isn't common.  Allowing it on all platforms is easy, I just worry about little oversights slipping through (for example, the CopyDlls macro breaks once you change the target's output name; easily fixed but it makes me paranoid that other scripts and rarely-used pathways might be making name assumptions).

**Comment by JonathanHenson** [comment]
run apt-get install on a debug symbols package and see what it does.

**Comment by Bu11etmagnet** [comment]
A debug symbols package contains only debug symbols that got stripped from the binaries. It doesn't contain binaries with different names.

If the build produces a libaws-cpp-sdk-cognito-idpD.so or a libaws-cpp-sdk-cognito-idpR.so, then linking with `-laws-cpp-sdk-cognito-idp` will not work. All the build systems would have to be configured with the ability to flip the `-l` switches between debug and release.

**Comment by DeepakArora76** [comment]
@bretambrose:
> Yesterday I added an option to the CMake setup that, on Windows only, lets you specify a suffix to be appended to the library name on Debug builds ('D' being the obvious choice). Would this be a satisfactory solution for you?

which flag is that produces lib suffixed With 'D'?  Is 'D' is default for DEBUG?
