### ISSUE TITLE
GetObject with range cause SignatureDoesNotMatch

### ISSUE THREAD

**Issue by hailbird** [aws/aws-sdk-cpp#366]
With the following code, getObjectOutcome reports SignatureDoesNotMatch.  If the WithRange is comment out, everything is fine.
```
        Aws::StringStream range;
        range << "bytes=" << off << "-" << off + len - 1;
        GetObjectRequest getObjectRequest;
        getObjectRequest
                .WithRange(range.str())    // range is "0-5242879". Good if comment out this line.
                .WithBucket(bucketName)
                .WithKey(oid);             // the size of the object is 12M
        GetObjectOutcome getObjectOutcome = client->GetObject(getObjectRequest);
```

The corresponding logs are attached.
[aws_sdk_2016-12-06-15-without-range.log.txt](https://github.com/aws/aws-sdk-cpp/files/634230/aws_sdk_2016-12-06-15-without-range.log.txt)
[aws_sdk_2016-12-06-15-with-range.log.txt](https://github.com/aws/aws-sdk-cpp/files/634229/aws_sdk_2016-12-06-15-with-range.log.txt)

**Comment by hailbird** [comment]
The problem is due to setting Schem as HTTP by mistake.  The interesting point is it worked well without "range:bytes=....".

**Comment by chvink** [comment]
Does anyone know why this can't with HTTP and how to work around it? I'm trying to do a threaded multi-part download through an HTTP proxy using `GetObjectRequest::SetRange()` but I can't download the first ~36 megabytes from the S3 key because of the signature error.

**Comment by hailbird** [comment]
As I tried, you can only use HTTPS.

**Comment by chvink** [comment]
I've confirmed that HTTPS does make the error go away, but the odd thing with that is that I don't see the failed signature check with HTTP if I'm in a setup where I don't need my proxy. I have yet to test this with the latest build so I don't know if how the new `proxyScheme` field will affect this, but this still seems like a bug so I'm tempted to open up a fresh issue for it.
