### ISSUE TITLE
Unable to parse ExceptionName: InternalError (Aws::S3::S3Client::ListObjects)

### ISSUE THREAD

**Issue by logidelic** [aws/aws-sdk-cpp#367]
I have some code which has been working perfectly for a while now, but today I saw the following error, seemingly randomly:

Calling `Aws::S3::S3Client::ListObjects` resulted in `IsSuccess() == false`. The message associated with the error (`r.GetError().GetMessage()`) was:

> Unable to parse ExceptionName: InternalError Message: We encountered an internal error. Please try again.

I guess this indicates some sort of internal unexpected error... Should I be "expecting" such cases and retrying? Is there anything I can check to try to figure out what is tickling this?

I haven't been able to repro again. I'm using AWS in multiple threads (in a supposedly safe way as far as I understand), so perhaps it is just a matter of timing...

**Comment by JonathanHenson** [comment]
internal error means something went wrong on s3's end. nothing you can do to handle it except for retrying the request.

**Comment by logidelic** [comment]
Ah, so this is not an an error in the library but on the server side. That was my misunderstanding. Thanks much for the response.
