### ISSUE TITLE
Fetch more than 1000 keys with ListObjectsRequest

### ISSUE THREAD

**Issue by giuseros** [aws/aws-sdk-cpp#369]
Hi all, 
I have a large dataset uploaded on s3, like 1e6 files. 

When I list them, I would like to gather all the keys at once. Indeed, listing them in batch of 1000 is killing the performance of my application. 

I tried to set WithMaxKeys(10000000), but this didn't work out.

Is there any way to retrieve all the keys in one shot?

Thank you in advance,
Giuseppe

**Comment by bretambrose** [comment]
AWS services, by design, try and avoid unbounded operations (preferring a paginated interface instead).  1000 is the service-side limit of ListObjects (see http://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html).

**Comment by giuseros** [comment]
Thanks for the prompt answer. I understand not having unbounded operations, but why not giving to the user the possibility to set the page size?

In my case I have 1e6 files, and this means going back and forth 1000 times. 

Also, I don't see ways to parallelize, since since I don't know how many files are stored until I actually list them (or is there a way to retrieve this info?). 

All in all, with a latency of 0.2 secs, this is taking me about 200 seconds, i.e., almost 4 minutes. 

I think changing the page size would be an handy feature to add, especially for applications with lots of data.

Thanks again,
Giuseppe

**Comment by Bu11etmagnet** [comment]
It is already possible to change the page size. 

    max-keys	

    Sets the maximum number of keys returned in the response body. If you want to retrieve fewer than the default 1,000 keys, you can add this to your request.

Unfortunately for you @giuseros , it can only be changed downwards.

**Comment by bretambrose** [comment]
Given the limit, it seems like it would be best to explore ways of transforming the root problem.  Can the service that generates the files do some aggregation to reduce their numbers?  What about partitioning the files into buckets?  You could then list each bucket concurrently for example.

As an example, one thing I'm familiar with is how Mobile Analytics exports to S3.  Each file ends up being several minutes of aggregated event data.  These files are placed into a bucket hierarchicy arranged by date and then hour.  Despite there being a lot of data involved, ultimately the bucket sizes stay small.

**Comment by giuseros** [comment]
My use-case is more like a file system, where the user specifies  bucket+path and I need to list the files. 

If the user specifies the root of the bucket, since in S3 there is no hierarchy, I get a flat list of all the files (which I then parse in a hierarchy). 

And here comes the problem: if a user is asking to list the root of a large dataset (e.g., million of images) it takes few minutes before I can even know which files are in the dataset. But apparently I have to  stick with that :/

Thanks anyway for the suggestions, I really appreciate that!

Giuseppe

**Comment by JonathanHenson** [comment]
I know I'm late to the party, but I implemented this exact scenario recently using Listv2:

https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp#L218

Follow that through to see how to use it the ListV2API. If the added transfer manager functionality works for you, you could also just use that.

**Comment by JonathanHenson** [comment]
Please reopen if you have further questions.
