### ISSUE TITLE
How to abort an async upload?

### ISSUE THREAD

**Issue by YourRatzon** [aws/aws-sdk-cpp#370]
I am using the Amazon AWS SDK for C++ to upload files to S3. My program makes a series of many 
s3_client.PutObjectAsync(request) calls all at once. At some point later, I want abort the upload of all files that haven't been uploaded yet. How can I do this?

**Comment by bretambrose** [comment]
Calling DisableRequestProcessing() on the S3Client object should abort everything.

**Comment by YourRatzon** [comment]
Seems like DisableRequestProcessing() prevents requests from being sent to HTTP, but it doesn't free the memory (release the file handles) of the files contained in each request. Is there a way to do this?

**Comment by bretambrose** [comment]
Short of guaranteeing the client gets destroyed, there may not be right now.  That is very undesirable behavior though, so we will look into it.

**Comment by bretambrose** [comment]
Are you able to provide a short code example that illustrates this?

**Comment by JonathanHenson** [comment]
"Calling DisableRequestProcessing() on the S3Client object should abort everything."

No it shouldn't, that's for pausing the transfer. Imagine the following scenario. I'm writing a file transfer portion of a video game. In the background, it's downloading a texture pack for a level that the user isn't currently using. In the meantime, the user starts a new multiplayer session. The game may want to pause the transfer temporarily until network conditions can return to a sustainable level for both the multiplayer session and the transfer. To abort a request, you should use:  The continuation handler:

here's an example:
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp#L303

**Comment by YourRatzon** [comment]
JonathanHenson,
Can you give a code snippet to do the following:
Launch a PutObject request async
Abort it at a later time while it's still running.

Thanks

**Comment by JonathanHenson** [comment]
the code sample I just gave you does this. Follow UploadFile() in TransferManager

**Comment by JonathanHenson** [comment]
Were you able to solve your problem? Please reopen if you still need help.

**Comment by pitrou** [comment]
Not the OP, but it doesn't seem there's a way to cancel an in-progress part upload. Or does `AbortMultipartUpload` cancel all in-process parts?
