### ISSUE TITLE
S3: how to get upload progress?

### ISSUE THREAD

**Issue by mikewang2016** [aws/aws-sdk-cpp#371]
I upload file blocks to S3. Every block could be 10MB - 100MB. It's not big but if network is slow, it can still take 10 seconds to 1 minutes. My question is: how can I get progress data during uploading.
(multiparts upload is not an option as it's minimum block size is 5MB)

**Comment by JonathanHenson** [comment]
transfer manager will expose this for you. Your other option is to register a callback on the base class AmazonWebServiceRequest.

**Comment by mikewang2016** [comment]
Yes. "SetDataSentEventHandler" works for me. This is a good design.

Thank you and you can close this issue now.
