### ISSUE TITLE
2 majors issues with SDB: credentials, us-east-1

### ISSUE THREAD

**Issue by gilles3** [aws/aws-sdk-cpp#372]
Hi, 

I have been using SDB for 5 or 6 years, mostly the PHP SDK and the iOS SDK.
This morning, I tried to use the C++ SDK but I had 2 blocking issues.

**Problem #1: Credential issue**

```
        Aws::SDKOptions options;
        options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
        Aws::InitAPI(options);
        
        Client::ClientConfiguration config;
        config.region = Region::US_WEST_1;
        auto credentials = Aws::MakeShared<Aws::Auth::DefaultAWSCredentialsProviderChain>("default");
        auto sdb = Aws::MakeShared<SimpleDB::SimpleDBClient>("myAllocTag", credentials, config);
        
        SimpleDB::Model::ListDomainsRequest sdbRequest;
        auto sdbResult = sdb->ListDomains(sdbRequest);
        if (sdbResult.IsSuccess())
            std::cout << "SDB: success" << std::endl;
        else
            std::cerr << "SDB: failure" << std::endl << sdbResult.GetError().GetMessage() << std::endl;

        Aws::ShutdownAPI(options);
```

SDB: failure
Unable to parse ExceptionName: AuthFailure Message: AWS was not able to authenticate the request: access credentials are missing

Note that the dynamo implementation works:

```
        DynamoDB::Model::ListTablesRequest dynamoRequest;
        auto dynamoResult = dynamo->ListTables(dynamoRequest);
        if (dynamoResult.IsSuccess())
            std::cout << "Dynamo: success" << std::endl;
        else
            std::cerr << "Dynamo: failure" << std::endl << dynamoResult.GetError().GetMessage() << std::endl;
```

Dynamo: success

I also tried to hardcode the keys (Auth::AWSCredentials credentials("MY_ACCESS_KEY", "MY_SECRET_KEY");), but I still get the same error.
NB: I am 100% sure that the key is correct (I use it successfully with SDB-PHP).

**Problem #2: US-EAST-1 does not work!**

In my previous example, if I replace: Region::US_WEST_1 by Region::US_EAST_1, I get another error:
Unable to connect to endpoint

It seems that the URI is wrong: sdb->m_uri is "https://sdb.us-east-1.amazonaws.com" instead of "https://sdb.amazonaws.com".

Any help would be appreciated.

-Gilles

**Comment by bretambrose** [comment]
I will look into this today.

**Comment by bretambrose** [comment]
SimpleDB requires a v2 signer and the SDK is only providing a v4 implementation.  We used to provide v2 and v3 a while back; I can look into bringing back the v2 signer just for SDB.

**Comment by gilles3** [comment]
That would be awesome. Thank you.

**Comment by JonathanHenson** [comment]
@gilles3 we're adding this to our backlog, but I can't promise that it is at the top of the priority queue. If you'd like to take a stab at implementing a sigv2 signer, I'd be happy to merge it in.

It needs to inherit from AuthSigner. The code can live next to the Authv4Signer. The generator needs to be updated for SDB to use the sig v2 signer instead of sigv4.

Otherwise, I'll keep you posted as to the progress.

**Comment by hkleynhans** [comment]
Has there been any movement on this?

**Comment by hkleynhans** [comment]
I have a patch for AuthSigner to support Sig V2 in my application.  If there is still interest in that, please let me know and I can send a pull request.

**Comment by JonathanHenson** [comment]
sure send a PR and I'll work on getting it merged.

**Comment by hkleynhans** [comment]
Apologies.  I am still waiting on approval from my employer to contribute the work.  The process is well under way, but does take some time.

**Comment by hkleynhans** [comment]
Proposal for adding AuthV2Sig support for the S3 client: https://github.com/aws/aws-sdk-cpp/pull/481

**Comment by singku** [comment]
We will add use-east-1 soon.

**Comment by singku** [comment]
@hkleynhans We don't support S3 sigV2 because it's not secure. Check this [thread](https://stackoverflow.com/questions/44325418/how-can-i-set-signature-to-v2-by-using-aws-s3-c-sdk)

**Comment by L-Dinosaur** [comment]
So is sdb just not usable right now?
