### ISSUE TITLE
Including JsonSerializer.h Disables Warnings in Visual Studio

### ISSUE THREAD

**Issue by tvdijk** [aws/aws-sdk-cpp#373]
Including `<aws/core/utils/json/JsonSerializer.h>`, which in turn includes `<aws/core/external/json-cpp/json.h>`, causes warnings 4267 and 4512 to be disabled on Visual Studio 2008 and newer. Perhaps this should be wrapped in a `#pragma warning(push/pop)` pair?

**Comment by bretambrose** [comment]
We should be able to fix this fairly easily.  I believe there is another related issue outstanding, much older; let me go dig it up and perhaps we can get both knocked out.

**Comment by bretambrose** [comment]
This should be fixed in the latest release

**Comment by tvdijk** [comment]
Thanks!
