### ISSUE TITLE
Linking error CONTENT_TYPE_HEADER@Http@Aws@@3PEBDEB on Visual C++ 2015, Release, x64

### ISSUE THREAD

**Issue by DeepakArora76** [aws/aws-sdk-cpp#374]
Microsoft Visual C++ 2015, Release Build, x64 

#ERROR
error LNK2001: unresolved external symbol "char const * const Aws::Http::CONTENT_TYPE_HEADER" (?CONTENT_TYPE_HEADER@Http@Aws@@3PEBDEB)

#SDK BUILD INSTRUCTIONS:
cmake D:/AWS/AWS-SDK-CPP -G "Visual Studio 14 Win64"
msbuild INSTALL.vcxproj /p:Configuration=RELEASE

#PROJECT SETTINGS:

> <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
>   <ClCompile>
>     <WarningLevel>Level3</WarningLevel>
>     <PrecompiledHeader>Use</PrecompiledHeader>
>     <Optimization>MaxSpeed</Optimization>
>     <FunctionLevelLinking>true</FunctionLevelLinking>
>     <IntrinsicFunctions>true</IntrinsicFunctions>
>   <PreprocessorDefinitions>AWS_SDK_PLATFORM_WINDOWS;ENABLE_WINDOWS_CLIENT;USE_IMPORT_EXPORT;NDEBUG;_CONSOLE</PreprocessorDefinitions>
>     <SDLCheck>true</SDLCheck>
>     <AdditionalIncludeDirectories>$(AWS_x64)\include;$(QT_x64)\include</AdditionalIncludeDirectories>
>     <RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>
>   </ClCompile>
>   <Link>
>     <SubSystem>Console</SubSystem>
>     <EnableCOMDATFolding>true</EnableCOMDATFolding>
>     <OptimizeReferences>true</OptimizeReferences>
>     <GenerateDebugInformation>true</GenerateDebugInformation>
>     <AdditionalLibraryDirectories>$(AWS_x64)\BIN;$(QT_x64)\lib</AdditionalLibraryDirectories>	  
>     <AdditionalDependencies>aws-cpp-sdk-cognito-idp.lib;aws-cpp-sdk-core.lib;Qt5Core.lib</AdditionalDependencies>
>   </Link>
> </ItemDefinitionGroup>

**Comment by DeepakArora76** [comment]
The file Core_EXPORTS.h contains:

> #if defined (USE_WINDOWS_DLL_SEMANTICS) || defined (WIN32)
>     #ifdef _MSC_VER
>         #pragma warning(disable : 4251)
>     #endif // _MSC_VER
>     #ifdef USE_IMPORT_EXPORT
>         #ifdef AWS_CORE_EXPORTS
>             #define  AWS_CORE_API __declspec(dllexport)
>         #else // AWS_CORE_EXPORTS
>             #define  AWS_CORE_API __declspec(dllimport)
>         #endif // AWS_CORE_EXPORTS
>     #else // USE_IMPORT_EXPORT
>         #define AWS_CORE_API
>     #endif // USE_IMPORT_EXPORT
> #else // defined (USE_WINDOWS_DLL_SEMANTICS) || defined (WIN32)
>     #define AWS_CORE_API
> #endif // defined (USE_WINDOWS_DLL_SEMANTICS) || defined (WIN32)


To fix it I used "USE_WINDOWS_DLL_SEMANTICS" define and all looks good.

**Comment by DeepakArora76** [comment]
Two defines USE_IMPORT_EXPORT & USE_IMPORT_EXPORT have solved the problem.

**Comment by bretambrose** [comment]
If at all possible, try to use the cmake export file that gets generated as part of building the SDK, as that will set up all the compiler settings (including things like USE_IMPORT_EXPORT) you need to properly build & link.  See https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/ for details.
