### ISSUE TITLE
How to build sdk for x86 on Windows 64 Bit Platform?

### ISSUE THREAD

**Issue by DeepakArora76** [aws/aws-sdk-cpp#375]
The guidelines for Windows looks like.

> For Visual Studio:
> cmake <path-to-root-of-this-source-code> -G "Visual Studio 12 Win64"
> msbuild INSTALL.vcxproj /p:Configuration=Release

I believe these command produce SDK for Windows 64 bit.

What command-line options I should use to build SDK for x86(Win32)? I have Windows 10 Pro 64 Bit. Visual Studio 2015. 

Appreciate you help on this.

**Comment by DeepakArora76** [comment]
I tried below command to 

`cmake -G "NMake Makefiles" -DTARGET_ARCH=WINDOWS -DANDROID_TOOLCHAIN_NAME=standalone -DANDROID_ABI=x86 -DCMAKE_BUILD_TYPE=Release -DNDK_DIR=C:/Android/android-ndk-r13b D:/AWS/aws-sdk-cpp`

`nmake intall`

which seems to work.

**Comment by bretambrose** [comment]
For a visual studio build:

cmake -G "Visual Studio 12 2013" <path-to-source>

For an nmake build:

cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release <path-to-source>

All of the android options are not necessary and when building for the local platform (not cross-compiling), you don't need the TARGET_ARCH option either.

**Comment by DeepakArora76** [comment]
Thanks.
