### ISSUE TITLE
use c++ SDK for ec2 service.

### ISSUE THREAD

**Issue by saeedghafar** [aws/aws-sdk-cpp#376]
hi 
i am new in AWS.i want to use c++ sdk for mange ec2 service like create,run and etc actions.
can i use c++ sdk for it?

**Comment by JonathanHenson** [comment]
yes. however the ec2 api is very large and if you are using GCC you'll need at least 4gb of ram to build it.

cmake -DBUILD_ONLY="ec2" <pathToSource>

**Comment by JonathanHenson** [comment]
Please reopen if you are still having issues.
