### ISSUE TITLE
Cannot Add Conditions to Permissions for SQS

### ISSUE THREAD

**Issue by BCribbs** [aws/aws-sdk-cpp#377]
I was writing a test app to create an SQS  Queue and then set permissions allowing SNS to publish to the queue via subscribe.  With much testing, I have yet to have a successful test.  

Upon looking at the SQS Documentation, permissions with arnEquals arn:aws:sns:....:mytopic needs to be applied as a condition.  There does not appear to be any functionality to set conditions from the SDK.

I attempted to generate a manual process via JsonValue and build up a policy however haver gotten several core dumps.  Hence, I would prefer an AddCondition member for Aws::SQS::Model::AddPermissionRequest.  Am I missing something?

Here's how I am adding the Permission, which does appear in the console after executing:
        // Add Permission to Queue to allow SNS to Write
        Aws::SQS::Model::AddPermissionRequest addPermReq;
        Aws::SQS::Model::AddPermissionOutcome addPermOut;
        addPermReq.WithQueueUrl( QueueUrlList[q-1] )
                  .WithLabel( "SNS_Permission_Policy" )
                  .AddActions( "*" )
                  .AddAWSAccountIds( accountId );
        
        addPermOut = sqsClient.AddPermission( addPermReq );
    
        if( addPermOut.IsSuccess()) {
            std::cout << "Permission Added To Queue" << std::endl;
        } else {
            std::cerr << "SQS Add Permission Failed:" 
                      << addPermOut.GetError().GetExceptionName() << std::endl;
            exit(-1);
        }

**Comment by JonathanHenson** [comment]
theres an integration test doing this. Have you had a look at that?

**Comment by BCribbs** [comment]
I’m looking at the QueueOperationTest.cpp now … I will let you know.

Thanks,
Brown Cribbs

**Comment by BCribbs** [comment]
I’ve looked in detail and while the AddPermissions tests look like what I’ve done, there is now direct way to add conditions that I can see, which the AWS Documentation suggests is needed.  

I can see the following in the console:
1) my topics getting generated
2) my queues being created
3) permissions being set
4) Subscriptions occurring to tie the topic to the queue

When I push a message either raw or JSON using the Publish to Topic my code does not receive, and the cloud watch metrics on the SQS Queues show my application making ReceiveMessage calls with no returned messages.  Hence, I believe SNS is not correctly connected.

I know there is a ConfirmSubscription step that an be called, but no Token is accessible to do a confirm. 

AWS Documentation again suggests that Confirmation is not needed for Publishers and Queues using the same AccountId.

At this point I am at a loss, my application needs to be able to configure SNS subscriptions and queues automatically not by hand in the console.
Brown Cribbs

**Comment by BCribbs** [comment]
BTW,  are there plans for integration tests on SNS, the other integration tests are quite useful, but SNS does not have tests. I was able to get a test app to publish to a topic I create and from the console I can do an email confirmation and receive the message via email so SNS works, just attaching/connecting SNS to SQS in an automatic fashion appears to be somewhat difficult and not really documented in a way I can easily figure this out.

Brown Cribbs

**Comment by BCribbs** [comment]
Thanks for the pointers, ultimately, you have to write a custom policy with the conditinals, which was about a dozen lines, maybe two dozen lines of code that the Other SDKs (Java and C#) have built in with the “WithCondition” member function which is absent in the SQS C++ SDK.  The right combination was difficult to diagnose, and I ended up doing a JSON file with the CLI to apply first, then, replicate that JSON structure using nested JsonValue objects.

You can close the issue or move it into the “Suggested Enhancement / Feature Request” category.

Thanks again,
Brown Cribbs
