### ISSUE TITLE
S3 Bug in TopicConfiguration.cpp Wrong or Incorrect XML Node Name

### ISSUE THREAD

**Issue by BCribbs** [aws/aws-sdk-cpp#380]
Upon attempting to setup an S3 Event Notification I kept getting Malformed XML.  After much diagnosis and consultation of the S3 Developer API Guide 2006-03-06, I have found that the culprit is the node name <TopicArn> which is incorrect according to both the API Guide and the schema (xsd) for S3. 

In TopicConfiguration.cpp on line 101, I changed CreateChildElement("TopicArn") to CreateChildElement("Topic").  

This change allows PutBucketNotificationConfiguration() to properly work and allow events to Publish to SNS Topics.

**Comment by bretambrose** [comment]
Related to #327  Another instance where locationName is not being used

**Comment by bretambrose** [comment]
This should be fixed as of yesterday's release
