### ISSUE TITLE
Can't find AccessManagementClient.h when making cognito-identity

### ISSUE THREAD

**Issue by Nomadjackalope** [aws/aws-sdk-cpp#381]
I am getting the following error

```
Building CXX object aws-cpp-sdk-cognitoidentity-integration-tests/CMakeFiles/aws-cpp-sdk-cognitoidentity-integration-tests.dir/IdentityPoolOperationTest.cpp.o
/home/benjamin/Documents/aws-sdk-cpp/aws-cpp-sdk-cognitoidentity-integration-tests/IdentityPoolOperationTest.cpp:34:58: fatal error: aws/access-management/AccessManagementClient.h: No such file or directory
 #include <aws/access-management/AccessManagementClient.h>
```

when doing `make` after `cmake -DBUILD_ONLY="cognito-identity" ../aws-sdk-cpp`

**Comment by bretambrose** [comment]
The cognito identity integration tests have an unmodeled dependency on access-management and iam.  We will fix this in a release in the near future.  In the meantime, you should be able to work around this by adding the following at line 122 in cmake/sdks.cmake:

list(APPEND TEST_DEPENDENCY_LIST "cognito-identity:access-management,iam,core")

**Comment by Nomadjackalope** [comment]
Thank you!

**Comment by bretambrose** [comment]
This should be fixed in the latest release.
