### ISSUE TITLE
AWS SDK- CMake error ("VERSION "v15.05.1" format invalid.")

### ISSUE THREAD

**Issue by acsdkquery** [aws/aws-sdk-cpp#383]
Hi, While building AWS-CMake in openwrt, am getting the following error, "VERSION "v15.05.1" format invalid."

if i build it in local Linux host machine , its working fine.

Kindly help on this issue.

VirtualBox:~/openwrt/package/kinesis_openwrt/src/aws-sdk-cpp/bld$ cmake ../
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating linux build config
-- Building project version: v15.05.1
CMake Error at CMakeLists.txt:90 (project):
  VERSION "v15.05.1" format invalid.

-- Configuring incomplete, errors occurred!
VirtualBox:~/openwrt/package/kinesis_openwrt/src/aws-sdk-cpp/bld$

**Comment by JonathanHenson** [comment]
I don't know where that version setring came from but it wasn't us. Where is the version coming from?

**Comment by acsdkquery** [comment]
I am building in Openwrt platform. here the branch version is 15.05....I think Cmake automatically take this version, and saying VERSION  format invalid.

**Comment by acsdkquery** [comment]
if its a new version, where i have to add some code checks in cmake, so that this new version get it validated correctly ??

**Comment by bretambrose** [comment]
We will need your help to diagnosis this.  As a first step, can you do the following:

(1) Take the text below and use it to replace your local cmake/initialize_project_version.cmake
(2) Clear your build directory
(3) Rerun cmake
(4) Reply here with (a) cmake command line used, (b) cmake output, (c) contents of your aws-cpp-sdk-core/include/aws/core/VersionConfig.h file

and we will try and go from there.

Debug version of initialize_project_version.cmake:


message(STATUS "ipv start: pv = ${VERSION_STRING}")
if(GIT_FOUND)
    execute_process(COMMAND ${GIT_EXECUTABLE} describe --abbrev=0 --tags
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE VERSION_STRING
    OUTPUT_STRIP_TRAILING_WHITESPACE)
    message(STATUS "ipv git describe: pv = ${VERSION_STRING}")
endif()

if(NOT VERSION_STRING)
    # extract it from the existing generated header file
    file(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/aws-cpp-sdk-core/include/aws/core/VersionConfig.h" __SDK_VERSION_LINE LIMIT_COUNT 1 REGEX "AWS_SDK_VERSION_STRING.*[0-9]+\\.[0-9]+\\.[0-9]+" )
    string( REGEX MATCH "([0-9]+\\.[0-9]+\\.[0-9]+)" VERSION_STRING "${__SDK_VERSION_LINE}" )
    message(STATUS "ipv header re: pv = ${VERSION_STRING}")
endif()

set(PROJECT_VERSION "${VERSION_STRING}")

message(STATUS "Building project version: ${PROJECT_VERSION}")

macro(add_project name description)
    set(PROJECT_NAME "${name}")
    set(PROJECT_STRING    "${name}_${PROJECT_VERSION}")
    set(PROJECT_TARNAME   "${name}-${PROJECT_VERSION}")
    set(PROJECT_BUGREPORT "https://github.com/aws/aws-sdk-cpp/issues/")
    set(PROJECT_DESCRIPTION "${description}")
    set(PROJECT_LIBS "")
    foreach(library_var ${ARGN})
        list(APPEND PROJECT_LIBS "${library_var}")
    endforeach()
    cmake_policy(SET CMP0028 NEW)
    cmake_policy(SET CMP0048 NEW)
    cmake_policy(SET CMP0054 NEW)
    cmake_policy(SET CMP0056 NEW)
    project(${name} VERSION "${PROJECT_VERSION}" LANGUAGES CXX)
endmacro()

**Comment by acsdkquery** [comment]
Thanks @bretambrose ,Please find the details as requested

AWS-SDK Source: (Only kinesis client with core)
VirtualBox:~/Open1/openwrt/package/libs/libaws-cpp-sdk-core/src$ ls
aws-cpp-sdk-core        aws-cpp-sdk-kinesis  cmake           code-generation  scripts            toolchains
aws-cpp-sdk-core-tests  bld                  CMakeLists.txt  doxygen          testing-resources

(a) cmake command line used
VirtualBox:~/Open1/openwrt/package/libs/libaws-cpp-sdk-core/src/bld$ cmake ../

(b) cmake output
VirtualBox:~/Open1/openwrt/package/libs/libaws-cpp-sdk-core/src/bld$ cmake ../
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating linux build config
-- ipv start: pv = 
-- ipv git describe: pv = v15.05.1
-- Building project version: v15.05.1
CMake Error at CMakeLists.txt:90 (project):
  VERSION "v15.05.1" format invalid.

-- Configuring incomplete, errors occurred!


(c) contents of your aws-cpp-sdk-core/include/aws/core/VersionConfig.h file

/*
  * Copyright 2010-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  *
  * Licensed under the Apache License, Version 2.0 (the "License").
  * You may not use this file except in compliance with the License.
  * A copy of the License is located at
  *
  *  http://aws.amazon.com/apache2.0
  *
  * or in the "license" file accompanying this file. This file is distributed
  * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
  * express or implied. See the License for the specific language governing
  * permissions and limitations under the License.
  */

#define AWS_SDK_VERSION_STRING "1.0.41"
~

**Comment by bretambrose** [comment]
When you are at the root of the AWS SDK source, what is the output when you run:

git describe --abbrev=0 --tags

You are building from a cloned git repo right?

**Comment by acsdkquery** [comment]
VirtualBox:~/Open1/openwrt/package/libs/libaws-cpp-sdk-core/src$ git describe --abbrev=0 --tags
v15.05.1

**Comment by bretambrose** [comment]
Well, git describe is not going to work as expected if you're not using a source tree that's under git's control.  We can harden the process to be more forgiving, but you are going to have better results if you build directly from a git-rooted tree rather than hand-building a source tree based on what you think is needed.  If you don't want to build the whole sdk (understandable given its size), you can use the BUILD_ONLY option to restrict the build to the components you want:

cmake -DBUILD_ONLY=kinesis;s3 ..

for example.

As for your current situation, you can also fix it by also copying the .git directory from the authoritative clone over into your hand-built source tree.

**Comment by acsdkquery** [comment]
Ok..got it...Thank you @bretambrose

**Comment by acsdkquery** [comment]
For the above, i have just hard-coded the version as of now,

vi cmake/initialize_project_version.cmake
......
set(VERSION_STRING "1.0.41")
set(PROJECT_VERSION "${VERSION_STRING}")
......

**Comment by edenzik** [comment]
I ran into the same issue. https://github.com/aws/aws-sdk-cpp/pull/425 should address it.

**Comment by halayli** [comment]
One approach to fix this without patching your code is to set export GIT_DIR=/tmp/ or some non-git directory
