### ISSUE TITLE
PutObject error: EntityTooLarge Unable to parse ExceptionName: EntityTooLarge Message: Your proposed upload exceeds the maximum allowed size

### ISSUE THREAD

**Issue by abhiguru** [aws/aws-sdk-cpp#386]
Following the example for S3 upload, I am trying to upload a file few max MBs in size and I get EntityTooLarge exception code below, I tested an upload to the same bucket using aws s3 cp file.txt s3://bucket-name/ and it works okay, Some threads seems to suggest multipart upload but I could not find anything about it in the example : 

 std::cout << "Uploading " << filename << " to S3 bucket: " << s3_bucket_name << std::endl;
    Aws::S3::Model::PutObjectRequest object_request;
    object_request.WithBucket(s3_bucket_name.c_str()).WithKey(filename.c_str());
    auto input_data = Aws::MakeShared<Aws::FStream>(filename.c_str(), dir_name.c_str(), std::ios_base::in);
    object_request.SetBody(input_data);
    auto put_object_outcome = s3_client->PutObject(object_request);

**Comment by JonathanHenson** [comment]
auto input_data = Aws::MakeSharedAws::FStream(filename.c_str(), dir_name.c_str(), std::ios_base::in);

This line is not doing what you think it is doing. The first argument of MakeShared is a memory allocation tag. The second argument on is what get's passed to the constructor. Are you intentionally passing you filename as the memory allocation tag?

**Comment by JonathanHenson** [comment]
Also, The transfer manager will handle all of this for you. See aws-cpp-sdk-transfer.

**Comment by JonathanHenson** [comment]
Did transfer manager solve your problem? Please reopen this issue if you are still having problems.

**Comment by abhiguru** [comment]
sorry didn't get a chance to check had a work around will update if required.

**Comment by vsreekanti** [comment]
I'm running into this same issue. I copied the code from the AWS SDK doc examples [here](https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/cpp/example_code/s3/put_object.cpp) and get the same error when trying to upload a 128KB file as well an empty file. What should be passed in as the memory allocation tag?
