### ISSUE TITLE
Inconsistency between Aws::S3::Model::BucketLocationConstraint and Aws::Region

### ISSUE THREAD

**Issue by AlienTechLAB** [aws/aws-sdk-cpp#387]
Hi.

I have found inconsistency between Aws::S3::Model::BucketLocationConstraint and Aws::Region.
For instance, Aws::Region::US_EAST_1 has not it's counterpart in BucketLocationConstraint.

1. To avoid "PermanentRedirect" error when S3Client has different region than request object I have to set the same region in both objects. I don't know how to deal with case when there is no counterpart for one object.

2. Is there a reason for haveing two different ways of describing region? I saw that DynamoDB takes ClientConfiguration (that has region) and I don't see any way to set region again in any request object. And it works just fine.

Did I misunderstood something?

Thank you,
Sebastian

**Comment by JonathanHenson** [comment]
So, with the addition of Sigv4 for S3, the client you use has to be configured for the region your bucket is in. The Bucket location constraint is mainly for creating buckets and reading which region a bucket is in. So, for example, you could have a client configured for us-east-1, call GetBucket, determine the region, then create a client that can communicate with that bucket. Make sense?

**Comment by AlienTechLAB** [comment]
Not yet. But, let's simplify it and focus on particular example:

I want to create bucket in "ap-northeast-2" region (Seoul).
Region Table says that Seoul is available for S3. - OK
Aws::Region contains AP_NORTHEAST_2 ("ap-northeast-2") - OK

but, ...

BucketLocationConstraint does not have "ap_northeast_2".  - Now what?

**Comment by JonathanHenson** [comment]
For now, you can trust that the String conversion from BucketLocationConstraintMapper::GetNameForBucketLocationConstraint() will just work. If you are really interested in why see this:

https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/client/AWSClient.cpp#L63
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/client/AWSClient.cpp#L63
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-s3/source/model/BucketLocationConstraint.cpp#L95

There is a catch with this particular enum though. 
1st, NOT_SET maps to us-east-1
2nd, EU maps to eu-west-1

The others are one-to-one mappings. You can take the direct result of the string conversion, assuming you checked those two values first, and feed it directly to your client config.

**Comment by JonathanHenson** [comment]
As far as creating of a bucket goes. One really disgusting option is for you to do the following:

auto constraint = BucketLocationConstraintMapper::GetBucketLocationConstraintForName("ap-northeast-2");

When you pass constraint to the CreateBucketRequest, it will serialize back into the original string.
In the meantime, I'll work with S3 to get their service model updated.

**Comment by AlienTechLAB** [comment]
Ok, thanks for advice. It did helped. I can create bucket in "ap-northeast-2", but still for 4 regions ("us-east-1", "us-west-2", "cn-north-1", "us-gov-west-1") I'm getting error:

Error code: UNKNOWN (100)

Message:"Unable to parse ExceptionName: InvalidLocationConstraint Message: The specified location-constraint is not valid"

Exception name: "InvalidLocationConstraint"

**Comment by JonathanHenson** [comment]
Can you send me a log for these errors so I can see exactly what is going across the wire?

**Comment by AlienTechLAB** [comment]
Sure. In attached zip file you will find source code for demo, compiling script and log file. In source, just uncomment lines with regionName = *** to be able to create bucket for that region. For some reason "us-west-2" works now. Source code contains exact error messages and codes.

Thank you.
[aws-region-issue.zip](https://github.com/aws/aws-sdk-cpp/files/691577/aws-region-issue.zip)

**Comment by gdochev** [comment]
Same problem here, GetBucketLocationConstraintForName doesn't always work, so there is currently no way as far as I can tell to create buckets in certain regions.
