### ISSUE TITLE
Will AWS-SDK-CPP will run on 32bit machine?

### ISSUE THREAD

**Issue by acsdkquery** [aws/aws-sdk-cpp#388]
Hi I am working on a 32bit platform, While compiling AWS code am getting the following error,

openwrt/staging_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/usr/include/curl/curlrules.h:143:41: error: size of array 'curl_rule_01' is negative
[CurlchkszEQ(long, CURL_SIZEOF_LONG)];

Will AWS-SDK-CPP will run on 32bit machine? Or to do so what changes i have to made in AWS??

Thanks in advance!

**Comment by bretambrose** [comment]
Yes.  We build 32 bit windows binaries regularly.  All of our Android testing is done against an armeabi-v7a target which is also 32 bit.  I have also built Android binaries for both mips and mips64 targets, but do not do so regularly.

**Comment by acsdkquery** [comment]
Thank you...i am getting this error,
openwrt/staging_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/usr/include/curl/curlrules.h:143:41: error: size of array 'curl_rule_01' is negative
[CurlchkszEQ(long, CURL_SIZEOF_LONG)];

So, inAWS_SDK where will be the deification for 'Long' variable ? file-name?

**Comment by acsdkquery** [comment]
in this, [CurlchkszEQ(long, CURL_SIZEOF_LONG)];
==> CURL_SIZEOF_LONG is 4 (as excepted- 32 bit machine) 
==> But long is getting updated as 8 (so the error)

if i made  CURL_SIZEOF_LONG =8 manually,  then AWS is compiling

**Comment by acsdkquery** [comment]
Any help on the above request??

**Comment by JonathanHenson** [comment]
ill look into this tonight, Im working on getting a nee feature out at the moment.

**Comment by acsdkquery** [comment]
Sure and Thanks JonathanHenson.

**Comment by acsdkquery** [comment]
i am having 64ubuntu linux machine, if i want to compile aws-cpp-sdk to 32bit, what changes/options i have to give??

**Comment by acsdkquery** [comment]
I have found the following,

**AWS-SDK not compiling in 32-bit mode properly in openwrt-Mipsel**

Curl build in 32-bit;
/staging_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/usr/lib$ file libcurl.so.4.4.0
libcurl.so.4.4.0: **ELF 32-bit LSB shared object, MIPS, MIPS32 rel2** version 1 (SYSV), dynamically linked, not stripped
==> CURL_SIZEOF_LONG is 4 (as excepted- 32 bit machine)

While compiling aws-sdk in 32-bit, Long size defined to 8, so the error comes

**make -C** build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/libaws-cpp-sdk-core-1.1 AR="mipsel-openwrt-linux-uclibc-gcc-ar" AS="mipsel-openwrt-linux-uclibc-gcc -c -Os -pipe -mmt **-mips32r2** -mtune=1004kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float" LD=mipsel-openwrt-linux-uclibc-ld NM="mipsel-openwrt-linux-uclibc-gcc-nm" CC="mipsel-openwrt-linux-uclibc-gcc" GCC="mipsel-openwrt-linux-uclibc-gcc" CXX="mipsel-openwrt-linux-uclibc-g++" RANLIB="mipsel-openwrt-linux-uclibc-gcc-ranlib" STRIP=mipsel-openwrt-linux-uclibc-strip OBJCOPY=mipsel-openwrt-linux-uclibc-objcopy OBJDUMP=mipsel-openwrt-linux-uclibc-objdump SIZE=mipsel-openwrt-linux-uclibc-size CFLAGS="-Os -pipe -mmt -mips32r2 -mtune=1004kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -Wall" ARCH="mipsel" DESTDIR="/home/arunc/openwrt/build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/libaws-cpp-sdk-core-1.1/ipkg-install" install


[ 33%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/http/curl/CurlHttpClient.cpp.o
taging_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/usr/include/curl/curl.h:35:0,
build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/libaws-cpp-sdk-core-1.1/aws-cpp-sdk-core/include/aws/core/http/curl/CurlHandleContainer.h:21,
 build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/libaws-cpp-sdk-core-1.1/aws-cpp-sdk-core/include/aws/core/http/curl/CurlHttpClient.h:21,
build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/libaws-cpp-sdk-core-1.1/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp:16:
taging_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/usr/include/curl/curlrules.h:143:41: error: size of array '__curl_rule_01__' is negative
     [CurlchkszEQ(long, CURL_SIZEOF_LONG)];


[CurlchkszEQ(long, CURL_SIZEOF_LONG)]; === CurlchkszEQ (8,4) == error


so,it seems, AWS-SDK not compiling in 32-bit mode properly in openwrt-Mipsel

Kindly provide your thoughts

**Comment by acsdkquery** [comment]
JonathanHenson, kindly share your thoughts,

**Comment by acsdkquery** [comment]
and also, if i want to compile aws-sdk in 32-bit linux-mipsel, what changes i have to do in sdk??(cmake files or so.)

**Comment by acsdkquery** [comment]
@JonathanHenson , need to do any update on compiler.cmake w.r.t openwrt? to specifically update for 32bit??

**Comment by JonathanHenson** [comment]
I'm still looking into it. I'll update you asap

**Comment by acsdkquery** [comment]
updated the compiler setting properly and aws-client compiling fine

**Comment by PoundKey** [comment]
Hello acsdkquery and Jonathan,

I am running into similar issue as well.
Could you please share some thoughts on this issue?
For instance, what compiler setting do I need to set in order to compile the aws-client?

Thanks a lot!
