### ISSUE TITLE
S3 client crash on libcurl

### ISSUE THREAD

**Issue by shuzhang1989** [aws/aws-sdk-cpp#391]
Hi, when I am using GetObjects(), but the program will randomly crash (the chance is not very high, but does exist). Is it a known problem? can it be fixed via upgrading the aws-sdk lib?

`#0 0x00007f612cebf556 in ?? () from /mnt/realpin/bin/libcrypto.so.1.0.0
#1 0xca62c1d6ca62c1d6 in ?? ()
#2 0xca62c1d6ca62c1d6 in ?? ()
#3 0xca62c1d6ca62c1d6 in ?? ()
#4 0xca62c1d6ca62c1d6 in ?? ()
#5 0xca62c1d6ca62c1d6 in ?? ()
#6 0xca62c1d6ca62c1d6 in ?? ()
#7 0xca62c1d6ca62c1d6 in ?? ()
#8 0xca62c1d6ca62c1d6 in ?? ()
#9 0x00007f612d22b920 in ?? () from /mnt/realpin/bin/libcrypto.so.1.0.0
#10 0x00007f610a0a7c50 in ?? ()
#11 0x000000000000001f in ?? ()
#12 0x00007f612cebb980 in SHA1_Update () from /mnt/realpin/bin/libcrypto.so.1.0.0
#13 0x00007f612cf3ea4f in ?? () from /mnt/realpin/bin/libcrypto.so.1.0.0
#14 0x00007f6129eed46a in SSL_CTX_new () from /mnt/realpin/bin/libssl.so.1.0.0
#15 0x00007f612cc1db2e in ?? () from /mnt/realpin/bin/libcurl.so.4
#16 0x00007f612cc1f085 in Curl_ossl_connect () from /mnt/realpin/bin/libcurl.so.4
#17 0x00007f612cc32719 in Curl_ssl_connect () from /mnt/realpin/bin/libcurl.so.4
#18 0x00007f612cc09150 in Curl_http_connect () from /mnt/realpin/bin/libcurl.so.4
#19 0x00007f612cc1a01a in Curl_protocol_connect () from /mnt/realpin/bin/libcurl.so.4
#20 0x00007f612cc1a2ca in Curl_setup_conn () from /mnt/realpin/bin/libcurl.so.4
#21 0x00007f612cc1a374 in Curl_connect () from /mnt/realpin/bin/libcurl.so.4
#22 0x00007f612cc25871 in ?? () from /mnt/realpin/bin/libcurl.so.4
#23 0x00007f613264eea9 in Aws::Http::CurlHttpClient::MakeRequest(Aws::Http::HttpRequest&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const ()
from /mnt/realpin/bin/libaws-cpp-sdk-core.so
#24 0x00007f613262e50a in Aws::Client::AWSClient::AttemptOneRequest(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const () from /mnt/realpin/bin/libaws-cpp-sdk-core.so
#25 0x00007f613262e87b in Aws::Client::AWSClient::AttemptExhaustively(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const () from /mnt/realpin/bin/libaws-cpp-sdk-core.so
#26 0x00007f6132631bc1 in Aws::Client::AWSXMLClient::MakeRequest(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const () from /mnt/realpin/bin/libaws-cpp-sdk-core.so
#27 0x00007f61322c27cd in Aws::S3::S3Client::ListObjects(Aws::S3::Model::ListObjectsRequest const&) const () from /mnt/realpin/bin/libaws-cpp-sdk-s3.so
#28 0x000000000091e85a in common::S3Util::listObjects (this=this@entry=0x7f60c38cb0d0, prefix=...) at third_party/rocksplicator/rocksplicator/common/s3util.cpp:81`

**Comment by JonathanHenson** [comment]
What version of the SDK is this?

**Comment by shuzhang1989** [comment]
@JonathanHenson my s3 build is till : https://github.com/aws/aws-sdk-cpp/commit/aa15fabd189d333e1e9b535e225c2ac1945ba1be

**Comment by JonathanHenson** [comment]
It looks like this build was from back in April? If so, please upgrade to the GA version (which we actively support). 

There was a bug a while back with come handles not having the right options set on them when they were returned to the pool. I'm not sure however when we fixed it. It is likely you don't have that fix.

**Comment by JonathanHenson** [comment]
Were you able to fix the issue by upgrading? Please reopen if you still have issues.
