### ISSUE TITLE
Buildfixes (FreeBSD)

### ISSUE THREAD

**Issue by arvedarved** [aws/aws-sdk-cpp#398]
[patch-jsoncpp.cpp.txt](https://github.com/aws/aws-sdk-cpp/files/682011/patch-jsoncpp.cpp.txt)
[patch-Security.cpp.txt](https://github.com/aws/aws-sdk-cpp/files/682012/patch-Security.cpp.txt)

Two patches to fix build on FreeBSD

jsoncpp.cpp Include cmath, which is needed for isfinite
Security.cpp There is no memset_s in FreeBSD (11.0/amd64). Instead of the ifdef maze there should probably be a cmake test to check for presence of memset_s

**Comment by bretambrose** [comment]
I will try and get this integrated in the next week or so.

related: #384

**Comment by bretambrose** [comment]
This is hopefully fixed in the latest version (have nothing to test on unfortunately).

**Comment by arvedarved** [comment]
Hi Bret, thanks for working on this. The first patch has been fixed, as far as i understood, the second patch regarding memset_s hasn't been handled. Please Reopen

**Comment by arvedarved** [comment]
Also the missing include hasn't been handled in 1.0.59

<pre>
/usr/home/arved/ports/aws-sdk-cpp/work/aws-sdk-cpp-1.0.59/aws-cpp-sdk-core/source/external/json-cpp/jsoncpp.cpp:3105:19: note: expanded from macro 'IS_FINITE'
#define IS_FINITE isfinite
                  ^
/usr/include/math.h:115:21: note: expanded from macro 'isfinite'
#define isfinite(x) __fp_type_select(x, __isfinitef, __isfinite, __isfinitel)
                    ^
/usr/include/math.h:86:39: note: expanded from macro '__fp_type_select'
#define __fp_type_select(x, f, d, ld) _Generic((x),                     \
                                      ^
1 error generated.

</pre>
