### ISSUE TITLE
Access violation unhandled exception thrown when creating KinesisClient

### ISSUE THREAD

**Issue by dkarantonis** [aws/aws-sdk-cpp#399]
Hi all,

we are currently developing a project in Windows 7x64, VC++, VS Studio 2015. AWS is installed via nuget.
AWSSDKCPP-Core: v1.0.44
AWSSDKCPP-Core.redist: v1.0.44
AWSSDKCPP-Kinesis: v1.0.20131202.44
AWSSDKCPP-Core.redist: v1.0.20131202.44

All libraries are build for Windows x86 architecture.

When running the following code:
```
//AWS credentials are succesfully fetched from online rest API.	
auto creds = Aws::Auth::AWSCredentials(accessToken, sk, skt);

Aws::Client::ClientConfiguration conf;
conf.verifySSL = false;
conf.region = Aws::Region::US_EAST_1;

auto client = Aws::Kinesis::KinesisClient(creds, conf);
```

an unhandled exception is thrown with the following message:
**Exception thrown at 0x0F2364F2 (aws-cpp-sdk-core.dll) in my_app.exe: 0xC0000005: Access violation reading location 0x00000000.**

Could you pleaase advice on error? 
Moreover, is there any way to further debug this error? The try/catch wrapper does not catch the exception, only a popup is displayed. 

thanks,
Dimitris

**Comment by bretambrose** [comment]
It looks like there's a potential version mismatch between core and kinesis, similar to what's seen in #353.  Are you able to wipe your package cache completely and try again from scratch?

**Comment by dkarantonis** [comment]
Hi,

i have latest versions  installs for all packages.

I tried clearing the package cache via command "nuget locals all -clear" but it didn't work. I even uninstalled and reinstalled all packages, but the same error appears.

Could you please advice for the next steps?

thanks!

**Comment by JonathanHenson** [comment]
Did you call

Aws::InitAPI() before this code?

**Comment by dkarantonis** [comment]
Hi Jonathan,

yes, this was missing. 

thanks!

**Comment by JonathanHenson** [comment]
It should be called before any calls to the sdk and ShutdownAPI() should be called once you are finished with the sdk.

**Comment by dkarantonis** [comment]
for sure, thanks a lot!
