### ISSUE TITLE
UpdateThing timeout on Mac OS for PATCH http curl request

### ISSUE THREAD

**Issue by rjeans** [aws/aws-sdk-cpp#400]
I am seeing a 504 gateway timeout error on Mac OS using curl version 7.52.1. This is the for not client request UpdateThing.

The CurlHttpClient is expecting the body of the request to be sent using the ReadBody callback. However this is not invoked for the PATCH option.

The problem is solved by setting these options in `SetOptCodeForHttpMethod`

      case HttpMethod::HTTP_PATCH:
           curl_easy_setopt(requestHandle, CURLOPT_POST, 1L);
           curl_easy_setopt(requestHandle, CURLOPT_CUSTOMREQUEST, "PATCH");

Setting the CURLOPT_POST option forces the client to call the ReadBody callback.

**Comment by JonathanHenson** [comment]
thanks for this, I'll review and possibly merge it as soon as possible.

**Comment by rjeans** [comment]
Thanks - I also submitted a pull request for the change

**Comment by singku** [comment]
Already fixed.
