### ISSUE TITLE
Question concerning data serialization before streaming to AWS Kinesis streamer

### ISSUE THREAD

**Issue by dkarantonis** [aws/aws-sdk-cpp#403]
Hi,

i currently use a library named avro to serialize my data from json to binary before sending to Kinesis streamer. Does Amazon provides its own serialization library to do the same work and remove the dependency with additional libraries? 

Could i use for example JsonSerializer? Is there any example i could follow?

thanks,
Dimtiris

**Comment by JonathanHenson** [comment]
I think I probably need more information about what you are trying to do. Do you have a json doc that you are wanting to send to a kinesis stream?

If you already have the json doc then you can simply use Aws::Utils::HashingUtils::Base64Encode() on the c_str() of your json string. 

If you have a data structure that you want to serialize, then send to kinesis, you can use JsonSerializer manually, and then base64 encode it.

**Comment by JonathanHenson** [comment]
Here's an example for how to use the Json utilities included in the SDK:

https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-identity-management/source/auth/PersistentCognitoIdentityProvider_JsonFileImpl.cpp#L93

**Comment by dkarantonis** [comment]
Hi Jonathan,

actually we have both a json file and a data struct. The json file is needed to validate schema and then we fill the structure with data and serialize them.

Sending over part of the code to have look on waht we do and comment if you wish:
 `		
//validate schema
ifstream in("myFile.json");
avro::ValidSchema mySchema;
avro::compileJsonSchema(in, mySchema);

//create input file stream
ifstream ifs("myFile.json");
string json((istreambuf_iterator<char>(ifs)), (istreambuf_iterator<char>()));

//create writer
avro::DataFileWriter<myDataStruct> writer("dataFile", mySchema, syncInterval, Codec::DEFLATE_CODEC);
writer.write(*_data);
writer.flush();

vector<unsigned char> buffer;
ifstream dataFile("dataFile", ios_base::in | ios_base::binary);
unsigned char ch = dataFile.get();
	while (dataFile.good()) {
		buffer.push_back(ch);
		}
`
and then send to Kinesis streamer.

thanks

**Comment by dkarantonis** [comment]
we finally built the library.

thanks anyway
