### ISSUE TITLE
CMake errors with older version

### ISSUE THREAD

**Issue by uroni** [aws/aws-sdk-cpp#405]
E.g. this line causes a CMake error with older versions (e.g. 3.0.2):

cmake_policy(SET CMP0054 NEW)

**CMake Error at cmake/initialize_project_version.cmake:31 (cmake_policy):
  Policy "CMP0054" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-s3/CMakeLists.txt:1 (add_project)**

You need to either increase the required CMake version or put it into a IF(POLICY CMP0056).

**Comment by bretambrose** [comment]
Thanks for bringing this to our attention; I'll try and get this fixed this week.

**Comment by bretambrose** [comment]
This should be fixed in the latest release.
