### ISSUE TITLE
Method to extract stream/region from ARN

### ISSUE THREAD

**Issue by acsdkquery** [aws/aws-sdk-cpp#407]
Hi, 
In my AWS-SDK-CPP client code i am having the full ARN value, like
arn:aws:kinesis:us-east-1:528719264515:stream/atream

from this i need to extract stream/region and need to update in kinesis client.
 
is there a method already available in AWS-SDK-CPP?

**Comment by bretambrose** [comment]
There isn't anything available specific to kinesis, but it should be straightforward to write one yourself using regular expressions.  For an example, see AccessManagementClient::ExtractAccountIdFromArn, which pulls out an account id from the IAM User arn.  The kinesis stream arn looks to have a different format (no '::' to easily key off) but that shouldn't make things significantly harder.

**Comment by acsdkquery** [comment]
Thank You. I tried this code and it works for region,
   char karn[256];
    char region[10];
    strcpy(karn, ShmPTR->kiarn);
    char* kregion = strtok(karn, ":");
    for(int Rcount = 0; kregion && Rcount <3; Rcount ++) {
	    std::cout<<kregion<<std::endl;
	    kregion = strtok(NULL, ":");
    }
strcpy(region,kregion);
