### ISSUE TITLE
Help, how do I SPEC this library

### ISSUE THREAD

**Issue by josefernandez91** [aws/aws-sdk-cpp#408]
I need if someone please help me to create a spec of this library, then the creation of an RPM

Thank you very much.

**Comment by bretambrose** [comment]
Unix package support is something we want to get done but haven't had time to finish.  Until we get around to it, any contributions towards that end would be fantastic.

**Comment by josefernandez91** [comment]
Or, but also create a configuration, so you can do something like this ./configure --prefix =%{PREFIX_EXTERNAL_DEPS}
