### ISSUE TITLE
Library crashes when a remote API returns an unexpected JSON response

### ISSUE THREAD

**Issue by csimmons0** [aws/aws-sdk-cpp#409]
My mobile app is using this library to connect to my API gateway. My API and its Lambda backend are still in development, and sometimes the JSON output of the Lambda function doesn't match the models in the API gateway and the generated C++ client. The Lambda's output is well-formed JSON, but it's not what the client expects. I'm finding that this library's code crashes when that happens. Is this behavior by design? I would have expected this library to give me an Aws::Utils::Outcome with an error along the lines of "failed to parse response"; I wouldn't have expected it to crash.

**Comment by Bu11etmagnet** [comment]
Your report is not very useful for diagnosing the problem. 
How did it crash? exit(0)? std::terminate? abort() ? Access violation?

**Comment by csimmons0** [comment]
I'm not asking anyone to diagnose the problem. I'm asking the owners of this project whether there is a problem in the first place. I'm asking whether the library is meant to handle unexpected JSON gracefully.

**Comment by JonathanHenson** [comment]
its not supposed to attempt to touch a missing member. I need to see the code that crashes.

**Comment by csimmons0** [comment]
I was using an older version of the library. I updated it today and then tried to repro the bug. This issue appears to have been fixed at some point.
