### ISSUE TITLE
SNS GetNextToken

### ISSUE THREAD

**Issue by jhonatanpiffer** [aws/aws-sdk-cpp#410]
Hi all,

I Had some  difficulties to iterate over all subscriptions.
When i get a next token from ListSubscriptionsResult this is always set.
and i get a next token from ListSubscriptionsRequest this is never set.

I understand if i have a token from response i need to do a new request with this token, until no received any more tokens. Right ? 

Below is my code : 

#include <stdio.h>
#include <aws/core/Aws.h>
#include <aws/sns/SNSClient.h>
#include <aws/core/client/ClientConfiguration.h>
#include <aws/core/http/Scheme.h>
#include <aws/core/utils/ratelimiter/DefaultRateLimiter.h>
#include <aws/core/auth/AWSCredentialsProvider.h>
#include <aws/sns/model/CreateTopicRequest.h>
#include <aws/sns/model/ListSubscriptionsRequest.h>
#include <aws/sns/model/ListSubscriptionsResult.h>

using namespace Aws::Client;
using namespace Aws::Http;
using namespace Aws::Utils;
using namespace Aws::SNS;
using namespace Aws::Auth;
using namespace Aws::SNS::Model;
using namespace Aws::Region;

const Aws::Map< Aws::String, Aws::String > & getSubscriptions(SNSClient & client);

int main () {
    static const char* ALLOCATION_TAG = "AWS-CPP-SDK-SNS-EXAMPLE";
    static const char* ACCESS_KEY = "";
    static const char* SECRET_KEY = "";

    auto limiter = Aws::MakeShared<Aws::Utils::RateLimits::DefaultRateLimiter<>>(ALLOCATION_TAG, 200000);

    Aws::SDKOptions options;
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
    Aws::InitAPI(options);
    // Create a client
    ClientConfiguration config;
    config.scheme = Scheme::HTTPS;
    config.connectTimeoutMs = 30000;
    config.requestTimeoutMs = 30000;
    config.readRateLimiter = limiter;
    config.writeRateLimiter = limiter;
    config.region = SA_EAST_1;

    auto client = Aws::MakeShared<SNSClient> (ALLOCATION_TAG, AWSCredentials(ACCESS_KEY, SECRET_KEY), config);
 ListSubscriptionsResult listsubscriptionsresult;
    Model::ListSubscriptionsRequest request;
    Model::ListSubscriptionsOutcome listsubscriptionsoutcome;

    int i = 0;
    do {
        request = Model::ListSubscriptionsRequest();
        listsubscriptionsoutcome = client->ListSubscriptions(request);

        if (listsubscriptionsoutcome.IsSuccess()) {
            listsubscriptionsresult = listsubscriptionsoutcome.GetResult();

            std::cout << "GetNextToken: " << listsubscriptionsresult.GetNextToken() << std::endl;
            std::cout << "GetNextToken request: " << request.GetNextToken() << std::endl;
            std::cout << "SerializePayload: " << request.SerializePayload() << std::endl;

            Aws::Vector<Subscription> list_subscriptions = listsubscriptionsresult.GetSubscriptions();

            for(Aws::Vector<Subscription>::iterator it = list_subscriptions.begin(); it != list_subscriptions.end(); ++it, i++) {
                    //std::cout << "GetSubscriptionArn: "   << it->GetSubscriptionArn() << std::endl; 
                    //std::cout << "GetOwner: "             << it->GetOwner() << std::endl; 
                    //std::cout << "GetProtocol: "          << it->GetProtocol() << std::endl; 
                    //std::cout << "GetEndpoint: "          << it->GetEndpoint() << std::endl; 
                    //std::cout << "GetTopicArn: "          << it->GetTopicArn() << std::endl; 
            }
        } else {
            Aws::Client::AWSError<SNSErrors> snserrors = listsubscriptionsoutcome.GetError();

            std::cout << "SNSErrors::GetMessage: " << snserrors.GetMessage() << std::endl;
        }

    //} while( request.GetNextToken().size() > 0);
    } while( request.GetNextToken().size() > 0);

    std::cout << "Total subscriptions: " << i << std::endl;

    Aws::ShutdownAPI(options);
}

const Aws::Map< Aws::String, Aws::String > & getSubscriptions(SNSClient & client) {

}

**Comment by bretambrose** [comment]
request is not modified by the call to client->ListSubscriptions(...)

After the response comes back, you need to call SetNextToken() on the request yourself:

request.SetNextToken(listsubscriptionsresult.GetNextToken());

You would also need to drop the line at the top of the loop where you essentially erase the request by assigning it to a default-constructed object.

**Comment by jhonatanpiffer** [comment]
thanks man

**Comment by bretambrose** [comment]
Closing.  Feel free to reopen if necessary.
