### ISSUE TITLE
Add Travis / Jenkins PR checks

### ISSUE THREAD

**Issue by Skarlso** [aws/aws-sdk-cpp#413]
Hi. 

I can't help but notice that there are no Travis / Jenkins PR checks for Pull Requests. It would be awesome to have some to see if a pr is conflicting with anything. 

Travis is a bit tricky as EC2 requires a huge amount of memory to build, but it can be done if you have a pre-built docker container which you always publish with the latest master on a push / merge to master so that it has the latest packages. And travis than works off of that container binding in the downloaded source as a mounted volume.

But I'm sure you guys have the resources to setup a Jenkins server somewhere which spits out the tests results. :) 

This would a nice-to-have.

Cheers,
Gergely.

**Comment by chadbrewbaker** [comment]
There is an AWS CodeBuild script: .buildscrupt.yaml 

Submit a PR with a bash script to run the checks. I can look into the GitHub hooks and a codebuild setup JSON for the maintainers to trigger it on a PR.

**Comment by Skarlso** [comment]
@chadbrewbaker Sure. :) Happy to help. 👍

**Comment by chadbrewbaker** [comment]
Looks we need a Lambda function triggered by github API. Lambda kicks off codebuild. Should work the same off a fork. Just need repo path, and your aws creds.

**Comment by Skarlso** [comment]
So... There is no `.buildscript.yaml` anywhere... Something else, I'll ought to look out for? :) Did you mean `buildspec.yml`? :)

**Comment by chadbrewbaker** [comment]
Yes. I need to rewrite it anyway now that I understand the execution model. Need to refactor it into bash scripts.

**Comment by Skarlso** [comment]
Hey Chad. 

So sorry, but what is now in that case you would me like to do? Create a bash script from that yml? 

Cheers.
