### ISSUE TITLE
Android: GetObject doesn't work for "big" files

### ISSUE THREAD

**Issue by durkmurder** [aws/aws-sdk-cpp#415]
I am using SDK with arm-linux-androideabi-4.9 toolchain and I have problems with GetObject, it doesn't work for relatively small objects, for instance, I am able to GetObject for a file which size is 3k but for a file which is 250kb it's impossible. I always get a timeout error. I have enabled AWS logs and I see constantly the same output in loop: 

> 21:49:59.437 EET - Content-Length: 253749
> 21:49:59.437 EET - Server: AmazonS3
> 21:49:59.438 EET -
> 21:50:00.439 EET - 12888 bytes written to response.
> 21:50:03.922 EET - 16384 bytes written to response.
> 21:50:09.258 EET - 16384 bytes written to response.
> 21:50:16.352 EET - 16384 bytes written to response.
> 21:50:25.257 EET - 16384 bytes written to response.
> 21:50:35.943 EET - 16384 bytes written to response.
> 21:50:48.605 EET - 16384 bytes written to response.
> 21:51:02.955 EET - 16384 bytes written to response.
> 21:51:02.957 EET - Curl returned error code 28
> 21:51:02.959 EET - Releasing curl handle 0xcdb8ee80
> 21:51:02.962 EET - Request failed, now waiting 0 ms before attempting again.`

It never gets finished, always an timeout error. For me it looks like an issue with some timers or condition variables, but who knows. 

I will attach a small example to reproduce a problem, as well I will describe my environment. 

Environment: 
- Android NDK 10e
- arm-linux-androideabi-4.9 toolchain
- HTC Nexus 9 with Android 7.0 as target device 

I have used next command to build AWS SDK: 

`cmake -DTARGET_ARCH=ANDROID`
`-DCMAKE_BUILD_TYPE=Release `
`-DBUILD_SHARED_LIBS=OFF `
`-DANDROID_STL=gnustl_shared `
`-DANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-4.9 `
`-DANDROID_NATIVE_API_LEVEL=android-16 `
`-DDISABLE_ANDROID_STANDALONE_BUILD=ON `
`-DBUILD_ONLY="s3" `
`-DENABLE_TESTING=OFF ../`

Code for minimum example:(it uses Qt, but you can easily remove it) 
[android-aws-issue.txt](https://github.com/aws/aws-sdk-cpp/files/712197/android-aws-issue.txt)

I will be grateful for any kind of help

**Comment by bretambrose** [comment]
This is a known issue when using the SDK against gnu stl and downloading to a stringstream; we have no workaround at the moment.  If you can switch to clang/libc++ rather than gnustl (which you won't be able to if api 16 is a requirement) the problem goes away.

There is a possibility that implementing and using your own "stringlike" stream (that does not use std::string under the hood) would fix this problem but it's not an avenue we have investigated yet.  

If you download to a file this will also not be a problem.

For more details, see include/aws/core/utils/memory/stl/AWSString.h

We may revisit this in the future and we welcome any solutions to the problem as pull requests.

**Comment by yuraolex** [comment]
I have seen this code, but for me it doesn't explain why I get huge timeouts between writing to response,(you can see at the log that I have sent). Maybe you can explain this? 
How can I download to file without GetObject?

**Comment by bretambrose** [comment]
When gnustl is used we use an alternative string definition (in that file) which disables certain constructors and operators that will crash the SDK if allowed.  Disabling those operators in turn causes every character push into a stringstream to do 4 full copies of the existing string value, so anything above a few thousand characters is going to blow up quadratically (but at least the SDK does not crash).

**Comment by durkmurder** [comment]
And how about downloading to file?
How that can be done?

**Comment by bretambrose** [comment]
Call SetResponseStreamFactory on the GetObjectRequest with a function that creates an Aws::FStream.  See  https://github.com/awslabs/aws-sdk-cpp-staging/blob/master/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp#L794 for an example.

**Comment by durkmurder** [comment]
I was able to workaround the issue by providing a custom stream buffer and using Aws::IOStream instead of Aws::StringStream. Stream buffer is built on top of QByteArray + std::vector<char>.(vector as internal one, and QByteArray as external). So now I got a working library on Android with arm-gcc-4.9 toolchain + gnu_stl. Thanks for your advice. Hope it will help somebody.

**Comment by bretambrose** [comment]
Would you be willing to supply a pull request?  Obviously we can't take anything involving Qt types, but I would probably be able to tweak your solution into a built-in default that works for gnustl, which would be tremendously helpful.

**Comment by durkmurder** [comment]
Sorry, for long reply. I will prepare a pull request this week, I will try to remove Qt stuff, to leave you minimum amount of work.

**Comment by bretambrose** [comment]
Yesterday's release included a string buffer and string stream replacement which is used by default on Android builds that use gnustl; from this point we will consider gnustl fully supported.
