### ISSUE TITLE
CMake errors CMP0056 with CMake version 3.1.3

### ISSUE THREAD

**Issue by josefernandez91** [aws/aws-sdk-cpp#418]
cmake -DCMAKE_BUILD_TYPE=Release /root/packages/BUILD/aws-sdk-cpp-1.0.51
-- Found Git: /usr/bin/git (found version "1.7.1") 
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating linux build config
-- Building project version: 1.0.51
CMake Error at CMakeLists.txt:88 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.

-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.3") 
--   Zlib include directory: /usr/include
--   Zlib library: /usr/lib64/libz.so
-- Encryption: Openssl
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.1e") 
--   Openssl include directory: /usr/include
--   Openssl library: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so
-- Http client: Curl
-- Found CURL: /usr/lib64/libcurl.so (found version "7.19.7") 
--   Curl include directory: /usr/include
--   Curl library: /usr/lib64/libcurl.so
CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-acm/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-apigateway/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-autoscaling/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-appstream/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-budgets/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-cloudformation/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-cloudfront/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-cloudhsm/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-cloudsearch/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-cloudsearchdomain/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-cloudtrail/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-codebuild/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-codecommit/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-codedeploy/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-codepipeline/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-cognito-identity/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-cognito-sync/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-config/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-datapipeline/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-devicefarm/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-directconnect/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-dms/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-ds/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-dynamodb/CMakeLists.txt:1 (add_project)

CMake Error at cmake/initialize_project_version.cmake:32 (cmake_policy):
  Policy "CMP0056" is not known to this version of CMake.
Call Stack (most recent call first):
  aws-cpp-sdk-ec2/CMakeLists.txt:1 (add_project)

**Comment by bretambrose** [comment]
#405

**Comment by bretambrose** [comment]
This should be fixed in the latest release.

**Comment by josefernandez91** [comment]
Sorry for loading the issue I did a git clone of the master branch, which version do I have to download?

**Comment by bretambrose** [comment]
1.0.55
aka
3d9c2bde0f470090b2b9ac9d091bf89b3b1e0be6

**Comment by josefernandez91** [comment]
I downloaded the latest version but now I throw this error

[  0%] [  0%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/AmazonStreamingWebServiceRequest.cpp.o
Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/AmazonSerializableWebServiceRequest.cpp.o
cc1plus: error: unrecognized command line option "-std=c++11"cc1plus: error: unrecognized command line option "-std=c++11"

make[3]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/AmazonStreamingWebServiceRequest.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/AmazonSerializableWebServiceRequest.cpp.o] Error 1

**Comment by bretambrose** [comment]
What compiler are you using?

**Comment by josefernandez91** [comment]
make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-redhat-linux-gnu

**Comment by josefernandez91** [comment]
gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)

**Comment by JonathanHenson** [comment]
minimum of 4.9 is required.
