### ISSUE TITLE
KinesisRecoder class request

### ISSUE THREAD

**Issue by kouellet** [aws/aws-sdk-cpp#419]
Is there any plan to add something similar as KinesisRecorder class (available on Android and iOS SDK)?

Like this : http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/mobileconnectors/kinesis/kinesisrecorder/KinesisRecorder.html

It can be really usefull for us...

Regards,

**Comment by JonathanHenson** [comment]
we're working on that very soon. we'll keep you posted.

**Comment by KaibaLopez** [comment]
Hi @kouellet , 
First, sorry for the lack of responses.
While going through old issues I came across yours and wanted to ask, would this still be a feature you'd be interested in?
