### ISSUE TITLE
Aws::Transfer::TransferManager::UploadFile()  fails immediately for files bigger then 5 MB

### ISSUE THREAD

**Issue by RPCPP** [aws/aws-sdk-cpp#423]
Hi,

I am able to upload a  5Mb file with "TransferManager::UploadFile()" successfully. But if I try to upload file bigger then 5 MB for ex, (7 MB) then the function immediately shows Transfer status fail.

Thanks.

**Comment by JonathanHenson** [comment]
is this on linux? if so, what is your request timeout set to?

Also, can you verify you have permissions to the uploadPart api call in iam?

**Comment by RPCPP** [comment]
Thanks for the quick reply. I am using Windows.  I need to ask my administrator for the permission part. So permission is needed because SDK is using multipart?

**Comment by JonathanHenson** [comment]
anything over 5mb is done via multipart.

**Comment by RPCPP** [comment]
Hi Jonathan,

I have all the following permissions but still it doesn't work. 

"s3:AbortMultipartUpload",
                "s3:CreateBucket",
                "s3:DeleteBucket",
                "s3:DeleteBucketPolicy",
                "s3:DeleteBucketWebsite",
                "s3:DeleteObject",
                "s3:DeleteObjectVersion",
                "s3:GetAccelerateConfiguration",
                "s3:GetBucketAcl",
                "s3:GetBucketCORS",
                "s3:GetBucketLocation",
                "s3:GetBucketLogging",
                "s3:GetBucketNotification",
                "s3:GetBucketPolicy",
                "s3:GetBucketRequestPayment",
                "s3:GetBucketTagging",
                "s3:GetBucketVersioning",
                "s3:GetBucketWebsite",
                "s3:GetLifecycleConfiguration",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:GetObjectTagging",
                "s3:GetObjectTorrent",
                "s3:GetObjectVersion",
                "s3:GetObjectVersionAcl",
                "s3:GetObjectVersionTagging",
                "s3:GetObjectVersionTorrent",
                "s3:GetReplicationConfiguration",
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads",
                "s3:ListBucketVersions",
                "s3:ListMultipartUploadParts",
                "s3:PutAccelerateConfiguration",
                "s3:PutBucketAcl",
                "s3:PutBucketCORS",
                "s3:PutBucketLogging",
                "s3:PutBucketNotification",
                "s3:PutBucketPolicy",
                "s3:PutBucketRequestPayment",
                "s3:PutBucketTagging",
                "s3:PutBucketVersioning",
                "s3:PutBucketWebsite",
                "s3:PutLifecycleConfiguration",
                "s3:PutReplicationConfiguration",
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:PutObjectTagging",
                "s3:PutObjectVersionAcl",
                "s3:PutObjectVersionTagging",
                "s3:ReplicateDelete",
                "s3:ReplicateObject",
                "s3:RestoreObject"

In the amazon log it shows content-length = 0 and also following

[WARN] 2017-01-23 15:34:34 AWSErrorMarshaller [126084] Encountered Unknown AWSError
XML_ERROR_MISMATCHED_ELEMENT
Unable to generate a proper httpResponse from the response stream.   Response code: 503:
[TRACE] 2017-01-23 15:34:34 AWSClient [126084] Request was either successful, or we are now out of retries.

Thanks.

**Comment by JonathanHenson** [comment]
503 is a slow down response, how many of these files are you uploading in parallel?

**Comment by RPCPP** [comment]
only one. 

    On Monday, January 30, 2017 2:48 PM, Jonathan M. Henson <notifications@github.com> wrote:
 

 503 is a slow down response, how many of these files are you uploading in parallel?—

**Comment by RPCPP** [comment]
I am able to upload bigger files now.
