### ISSUE TITLE
Download streaming of big files 

### ISSUE THREAD

**Issue by Karim-go** [aws/aws-sdk-cpp#426]
Hi all. 
It seems that streaming down large files is not doable with getobject or getobjectasync
Is there a way to do it that I'm not aware of?
Did I miss something?
Can you provide a sample code example? 
That would be really helpful. I can't read the files I have in s3... 
Thanks.

**Comment by bretambrose** [comment]
Have you looked at aws-cpp-sdk-transfer-tests?

**Comment by Karim-go** [comment]
Yes. 
TransferManager uses GetObject() 
So it doesn't work either.
It seems that the sdk allows us to upload big files but not to stream download.

**Comment by bretambrose** [comment]
What's wrong with GetObject?

**Comment by Karim-go** [comment]
Getobject blocks when called on big files. And finally end up sending curl error 28 for timeout. 
Same with GetobjectASync. 
I'm trying to do this with setRange() . But that would mean sending a lot of requests for just one file. 
I prefer just one request to get a stream of the whole file.

**Comment by bretambrose** [comment]
What is your request timeout set at?  If you're timing out and only want to make one call then there's really no choice other than increase the timeout.

We have a multi-part download implementation for the transfer client in-progress that I'd like to get out in the next week or so.  The initial implementation would bring things down in chunks to memory and then assemble into the final stream.  A later option will allow for the chunks to go to files and add the ability to restart the download across process runs (ie, useful for patchers for example).

**Comment by Karim-go** [comment]
I tried increasing my timeout, to 30seconds or more. But for files > 2go
it's still not long enough.
I have to set a really smaller byte range.
So it takes a lot of requests to get just one file in stream .
I'm really interested by your multipart download! I'll be waiting for it :)
For now,  I can't use the sdk to stream huge files

Le jeu. 26 janv. 2017 15:29, Bret Ambrose <notifications@github.com> a
écrit :

**Comment by JonathanHenson** [comment]
TransferManager calls GetObject in a background thread in order to protect the io (its complicated). Anyways, the timeout can be adjusted via your clientConfiguration.

**Comment by hnaik** [comment]
Hello, I am currently trying to use Aws::Transfer to download files that are over 5 GB. Is this still the best way to do it? What I am noticing is that my process downloads about 32MB and then some how resets, truncates the file and starts downloading again. It does this about 10 times and then finally quits with TransferHandle::GetStatus() == FAILED().

**Comment by JonathanHenson** [comment]
this sounds like a platform using libcurl. You need to set the read timeout to something reasonable, since that will timeout the download if it is set too short.

**Comment by hnaik** [comment]
Ah got it. So I set ClientConfiguration::requestTimeoutMs = 0 (never timeout according to: https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT.html) and that seems to work. Are there potential downsides to doing this?

**Comment by JonathanHenson** [comment]
I just fixed this, requestTimeoutMs will now behave more like a socket read timeout. So you can set this back to something reasonable like 3 seconds.
