### ISSUE TITLE
AWS C++ application Link error with windows header files

### ISSUE THREAD

**Issue by N1N** [aws/aws-sdk-cpp#427]
Hi,

I have compiled aws c++ SDK successfuly. 

I have an application which will access the s3 storage creating bucket,getobject etc., compiled and working well n fine.

But when i add any windows header (#include<Windows.h>/ #include <winsock2.h>), Its showing the
following Link error,

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: virtual class Aws::Utils::Outcome<class Aws::S3::Model::GetObjectResult,class Aws::Client::AWSError<enum Aws::S3::S3Errors> > __cdecl Aws::S3::S3Client::GetObjectW(class Aws::S3::Model::GetObjectRequest const &)const " (?GetObjectW@S3Client@S3@Aws@@UEBA?AV?$Outcome@VGetObjectResult@Model@S3@Aws@@V?$AWSError@W4S3Errors@S3@Aws@@@Client@4@@Utils@3@AEBVGetObjectRequest@Model@23@@Z)	aws2	C:\Users\nandang\Documents\Visual Studio 2015\Projects\aws2\aws2\aws2.obj	1	

Note: If i remove the windows headers, it builds successfully.
I need to use CreateThread and socket API's in my application.

Please suggest!!

**Comment by JonathanHenson** [comment]
windows header has some #define entries such as GetObject that need to be #undef d. As for CreateThread, why not just use std::thread?

**Comment by bretambrose** [comment]
I would also advise partitioning your platform-specific code from the platform-agnostic code if possible.

**Comment by N1N** [comment]
@JonathanHenson @bretambrose Thank you! It worked!! Also i'll try with std::thread.
