### ISSUE TITLE
make install generates pkconfig that ignores CMAKE_INSTALL_LIBDIR

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#428]
On x64 libraries are supposed to go to lib64 (i.e. /usr/local/lib64). Typically they get installed into /*/lib by default, but user has option to override this. With cmake it is typically -DCMAKE_INSTALL_LIBDIR=lib64.

make install for this SDK also generates pkgconfig file(s) with always point to /*/lib (ignoring override made by user).

**Comment by singku** [comment]
This only works as you expected if SIMPLE_INSTALL option is on and on linux. I am not sure it is a bug or not.

**Comment by singku** [comment]
fixed in version #be63d2f8343325660632ae9d579606c5c13368e9

**Comment by ptomato** [comment]
I don't think this is fixed. With my install (Linux, SIMPLE_INSTALL) I have the libraries installed in /app/lib64. But the pkgconfig file says otherwise:
```
$ pkg-config --libs aws-cpp-sdk-core
-L/app/lib -laws-cpp-sdk-core
```

**Comment by crusader-mike** [comment]
@ptomato For some reason I cannot reopen this bug. Care to submit a new issue?

**Comment by ptomato** [comment]
I'm not sure of the exact cmake arguments I had, and that information is on my work computer. I'll submit a new issue after the weekend.

**Comment by singku** [comment]
Will merge the fix soon, thank you for reporting this bug.

**Comment by ptomato** [comment]
Here is my cmake configuration in case you need it: https://gist.github.com/ptomato/f03c393cb6f09313d8aceaf3a8088ed4

**Comment by ptomato** [comment]
I just realized that configuration is no good to you, because in that build I worked around the bug by manually setting `CMAKE_INSTALL_LIBDIR`. I've updated the gist. With this configuration (libdir is set to `lib64`), I get the following contents of `aws-cpp-sdk-core.pc`:
```
prefix=/app
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib

Name: aws-cpp-sdk-core
Description: Core http and utility library for the AWS C++ SDK
Version: 1.5.2
Cflags: -I${includedir} -fno-exceptions -std=c++11 -s
Libs: -L${libdir} -laws-cpp-sdk-core 
Libs.private: -lpthread -lcurl -lcrypto -lssl -lz
Requires: 
```

**Comment by singku** [comment]
This should have been fixed. Please update the repo and check again. Thanks.

**Comment by ptomato** [comment]
I'm afraid that actually made it worse; now code won't compile using the pkg-config file, since the given includedir and libdir aren't absolute.

Here's the contents of `aws-cpp-sdk-core.pc`:
```
includedir=include
libdir=lib64

Name: aws-cpp-sdk-core
Description: Core http and utility library for the AWS C++ SDK
Version: 1.5.11
Cflags: -I${includedir} -fno-exceptions -std=c++11 -s
Libs: -L${libdir} -laws-cpp-sdk-core 
Libs.private: -lpthread -lcurl -lcrypto -lssl -lz
Requires:
```
It leads to the following compilation error:
```
ccache c++  (...my files...) -L/app/lib -Wl,--no-undefined -Wl,--as-needed -shared -fPIC -Wl,--start-group /usr/lib/x86_64-linux-gnu/libglib-2.0.so /usr/lib/x86_64-linux-gnu/libgobject-2.0.so /usr/lib/x86_64-linux-gnu/libgio-2.0.so -Llib64 -laws-cpp-sdk-core -Wl,--end-group -Llib64 -laws-cpp-sdk-cognito-idp -laws-cpp-sdk-core  
/usr/lib/gcc/x86_64-unknown-linux-gnu/8.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -laws-cpp-sdk-core
collect2: error: ld returned 1 exit status
```

**Comment by singku** [comment]
Damn, I have already tested it. Let me do a clean build again. Will update you soon.

**Comment by singku** [comment]
Okay, found the reason and fixed it internally first. If you need the fix now, you can make the following change locally. We will push the commit soon. Thanks for reporting this.
```
-includedir=@INCLUDE_DIRECTORY@
+includedir=@CMAKE_INSTALL_PREFIX@/@INCLUDE_DIRECTORY@

-libdir=@LIBRARY_DIRECTORY@	
+libdir=@CMAKE_INSTALL_PREFIX@/@LIBRARY_DIRECTORY@
```
