### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by josefernandez91** [aws/aws-sdk-cpp#430]
If I just want to use the part of S3, that I can remove so that it does not weigh so much the library, since I want to do static?

**Comment by JonathanHenson** [comment]
delete the operations you dont want out of the api-definition file, and regenerate.

**Comment by josefernandez91** [comment]
To use S3 achieve with buildear this alone? -DBUILD_ONLY = "s3; core"

**Comment by JonathanHenson** [comment]
-DBUILD_ONLY="s3" -DREGENERATE_CLIENTS="1"

**Comment by josefernandez91** [comment]
Thank you
