### ISSUE TITLE
GetInstanceIds() returns an empty Vector

### ISSUE THREAD

**Issue by jubinsanghvi16** [aws/aws-sdk-cpp#432]
I am working with AutoScaling APIs and basically what I am trying to do is get a count of the running instances in the auto-scaling group.

But I am facing multiple issues:

- Aws::AutoScaling::Model::DescribeAutoScalingInstancesRequest::GetInstanceIds() is giving me an empty vector even though I have an instance running in an auto-scaling group.

`
#include <aws/core/Aws.h>
#include <aws/core/utils/logging/DefaultLogSystem.h>
#include <aws/core/utils/logging/AWSLogging.h>

#include <aws/autoscaling/AutoScalingClient.h>
#include <aws/autoscaling/model/DescribeAutoScalingInstancesRequest.h>

using namespace Aws;
using namespace std;

int main() {

	SDKOptions options;
	InitAPI(options);

	Utils::Logging::InitializeAWSLogging(MakeShared<Utils::Logging::DefaultLogSystem>("RunUnitTests", Utils::Logging::LogLevel::Debug, "aws_sdk_"));

	AutoScaling::AutoScalingClient client;
	AutoScaling::Model::DescribeAutoScalingInstancesRequest request;
	
	auto outcome = client.DescribeAutoScalingInstances(request);
	int count = -1;

	if(outcome.IsSuccess()) {

		auto instances = outcome.GetResult().GetAutoScalingInstances();
		count = instances.size();

		for(auto const& each: instances) {
			cout << "ID: " << each.GetInstanceId() << " | Scaling Group: " << each.GetAutoScalingGroupName() << " | Health: " << each.GetHealthStatus() <<endl;
		}
	}
	else {
		cout << "Error: " << outcome.GetError().GetExceptionName() << endl << outcome.GetError().GetMessage() << endl;
	}
	
	ShutdownAPI(options);

	cout << "Count: " << count << endl;
	return count;

}
`

- I get a "Segmentation fault (core dumped)" error after the above program ends. So it gives me the count that I want but throws "Segmentation fault (core dumped)" after it ends.

The gdb results are:
`
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff1259700 (LWP 16896)]
[New Thread 0x7ffff0a58700 (LWP 16897)]
[Thread 0x7ffff0a58700 (LWP 16897) exited]
ID: i-03640a23766c5cfa8 | Scaling Group: rtbkit-demo-group | Health: HEALTHY
Count: -1

Thread 1 "getScalingNodes" received signal SIGSEGV, Segmentation fault.
__GI___pthread_mutex_lock (mutex=0x2d0) at ../nptl/pthread_mutex_lock.c:67
67	../nptl/pthread_mutex_lock.c: No such file or directory.
`

**Comment by JonathanHenson** [comment]
Just FYI, don't do this:

``
Utils::Logging::InitializeAWSLogging(MakeShared<Utils::Logging::DefaultLogSystem>("RunUnitTests", Utils::Logging::LogLevel::Debug, "aws_sdk_"));
````

Put your logging options into SDKOptions. You are currently overwriting some global state and possibly causing some memory problems due to the way the logging thread works.

**Comment by jubinsanghvi16** [comment]
Thanks for pointing that out. It was actually my hasty way to get some answers out. I actually added this after I started getting the "Segmentation fault" error. I made the correction but I still have the same issues.

**Comment by JonathanHenson** [comment]
Your current segfault is liking coming from the fact that your InitAPI and ShutdownAPI is in the same stack frame as the actual code using the SDK. ShutdownAPI() will be executed before the stack allocated objects go out of scope, which is bad since this will cleanup curl and openssl, and possibly a memory manager before the destructors on the client and model objects are called. A simple work around would be to put scoping around your code:

Aws::InitAPI()
{
    //do your code here.
}
Aws::ShutdownAPI()

**Comment by JonathanHenson** [comment]
As for the empty result, unless you are using the latest version of the SDK (we've fixed a lot of query/ec2 protocol stuff lately), we have a bug.

**Comment by jubinsanghvi16** [comment]
Yup, I am using the latest one. I just started working on this yesterday. Were you able to replicate the issue?
I think I might have to switch to the python SDK for now.

**Comment by JonathanHenson** [comment]
were toy at least able to fix the segfault? we can usually get a fix out for this stuff within a few days.

**Comment by jubinsanghvi16** [comment]
No, I wasn't. I am still trying to find out what is going wrong there using this trace.

`Thread 1 "getScalingNodes" received signal SIGSEGV, Segmentation fault.
__GI___pthread_mutex_lock (mutex=0x2d0) at ../nptl/pthread_mutex_lock.c:67
67	../nptl/pthread_mutex_lock.c: No such file or directory.`

**Comment by JonathanHenson** [comment]
this is after adding the scoping brackets?

**Comment by jubinsanghvi16** [comment]
Hey Jonathan, I am really sorry. The scoping brackets resolved the segfault issue. Thanks a ton for that!

**Comment by jubinsanghvi16** [comment]
Hey Jonathan,

Any update on the GetInstanceIds() issue?

Also, I have a query which is not related to any of this but I wasn't sure where to put it as its not an issue. Once the sdk is built, installed and all the .so files go into the usr/local/lib folder why is there a need for the sdk_build folder? I went through this post [https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/](url) but couldn't understand the reason.

I was hoping if you could shed some light on it.

**Comment by jubinsanghvi16** [comment]
Hey Jonathan, I am facing the segmentation fault issue again. So basically I am using an aws c++ sdk script that gives me the number of instances (the one posted above in my main question). I have to call this script multiple times and for some reason I get a seg fault issue after the first call. The first call seems to be working fine.

Here's the trace:
`#0  __GI___pthread_mutex_lock (mutex=0x50) at ../nptl/pthread_mutex_lock.c:67
#1  0x00007ffff78729e2 in __gthread_mutex_lock(pthread_mutex_t*) () from /usr/local/lib/libaws-cpp-sdk-core.so
#2  0x00007ffff7876ab2 in std::mutex::lock() () from /usr/local/lib/libaws-cpp-sdk-core.so
#3  0x00007ffff78b2ba8 in Aws::Utils::Crypto::OpenSSL::locking_fn(int, int, char const*, int) () from /usr/local/lib/libaws-cpp-sdk-core.so
#4  0x00007ffff5bdc10f in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#5  0x00007ffff5bdc6ff in CRYPTO_new_ex_data () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#6  0x00007ffff5c833db in ENGINE_new () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#7  0x00007ffff5c88106 in ENGINE_load_rdrand () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#8  0x00007ffff5c85a4e in ENGINE_load_builtin_engines () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#9  0x00007ffff7bbb1ee in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#10 0x00007ffff7b954d5 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#11 0x000000000040ecbb in main ()`

**Comment by bretambrose** [comment]
Can you post a full code sample that demonstrates the crash?

**Comment by JonathanHenson** [comment]
Sorry it's taken me so long to get back to this one. It looks like the deserialization is right for DescribeAutoScalingInstances. Is the issue just the segfault, or that the Instance collection is empty?

We just pushed out an update on the OpenSSL cleanup that I think clears this up.

Please reopen if you still have issues.
