### ISSUE TITLE
CMakeLists.txt:   Imported target "aws-cpp-sdk-s3" includes non-existent path

### ISSUE THREAD

**Issue by josefernandez91** [aws/aws-sdk-cpp#433]
I am having a problem to compile including libraries from CMakelist.txt

Error: CMake Error in CMakeLists.txt:
  Imported target "aws-cpp-sdk-s3" includes non-existent path
    "/opt/iway/deps/aws-sdk-cpp/aws-cpp-sdk-s3/include"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not
  provide.
--------------------------------------------------------
CMakelist.txt: I only show what represents aws

 if (DEFINED ENV{AWS_SDK_PATH})
     set(AWS_SDK_PATH "$ENV{AWS_SDK_PATH}/build")
 else()
    set(AWS_SDK_PATH "${CMAKE_CURRENT_SOURCE_DIR}/aws-sdk-cpp/build")
   endif()
 
 set(aws-sdk-cpp_DIR "${AWS_SDK_PATH}")
 find_package(aws-sdk-cpp)

target_link_libraries( myproyect
    aws-cpp-sdk-s3
)

----------------------------------

ENV:   AWS_SDK_PATH=/opt/iway/deps/aws-sdk-cpp

------------------------------------

Screenshot Path:
![aws](https://cloud.githubusercontent.com/assets/14926548/22519980/4cdf6174-e891-11e6-9f1c-26e851562529.png)
![aws2](https://cloud.githubusercontent.com/assets/14926548/22520070/9ad8b84e-e891-11e6-8bff-71abe1dd7976.png)

that could be happening?

**Comment by JonathanHenson** [comment]
Compiler version, OS version, SDK version, any other relevant information would be helpful.

I'd like to see your CMake command as well.

**Comment by josefernandez91** [comment]
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
cmake version 3.1.3
OS centos6 and ubuntu
SDK version: I made git clone today

CMake: I made a script

 #!/usr/bin/env bash
 
 cd /opt/iway/deps
 
 LIBS_WE_NEED="core;s3"
 
 if [ ! -d aws-sdk-cpp ]; then
   echo "AWS SDK Source: Not found"
   git clone --depth 1 https://github.com/aws/aws-sdk-cpp aws-sdk-cpp
 else
   echo "AWS SDK Source: Found"
 fi
 
 pushd aws-sdk-cpp
 
 if [ ! -d build ]; then mkdir build; fi
 
 pushd build
 
 cmake \
   -DBUILD_ONLY="${LIBS_WE_NEED}" \
   -DCMAKE_BUILD_TYPE=Release \
   -DENABLE_TESTING=OFF \
   -Wno-dev \
   ..
 
 make -j2

**Comment by JonathanHenson** [comment]
can you upload the output of this script?

**Comment by josefernandez91** [comment]
Sorry I did not understand what you need, if you want the log of the script or the compiled folder that you weapon?

**Comment by josefernandez91** [comment]
By the doubts I raise the two

https://drive.google.com/file/d/0BxCNpdIwzL9zM2NMdGRacTY1Z2c/view?usp=sharing

[log.txt](https://github.com/aws/aws-sdk-cpp/files/747834/log.txt)

**Comment by JonathanHenson** [comment]
did you run make install?

**Comment by JonathanHenson** [comment]
nevermind you are doing this via cmake export targets.

**Comment by JonathanHenson** [comment]
Can you upload the generated aws-sdk-cpp exports file?

**Comment by josefernandez91** [comment]
This is the aws file that was generated
https://drive.google.com/file/d/0BxCNpdIwzL9zM2NMdGRacTY1Z2c/view?usp=sharing

Yes, make install was executed.

**Comment by josefernandez91** [comment]
There are news of this topic?

**Comment by singku** [comment]
This problem should have been fixed, reopen if you still have.
