### ISSUE TITLE
Can we avoid generating different types for requests, results, and sub-objects?

### ISSUE THREAD

**Issue by csimmons0** [aws/aws-sdk-cpp#434]
The swagger-to-api-description script that I wrote used to generate different shapes for each operation, even if two operations involved the same schema in the swagger file.  As a result, there were places in my CPP code where I had to convert between two Model classes that were exactly the same except in name. I went back and improved the script to generate a single shape for each schema in the swagger file because this code to convert between classes was becoming unmaintainable. Much to my chagrin, I learned that the code-generator would still create multiple Model classes for the same shape--a class for when the shape was a request, a class for when the shape was a result, and a class for when the shape was inside another shape.

Is there a way that we can eliminate these separate classes and generate only one class per shape? Alternatively, could we merge just the result and sub-shape classes? (Having separate classes for requests hasn't actually caused any problems.) The only notable difference that I see between JsonResultHeader.vm and JsonSubObjectHeader.vm is what they do with "useRequiredField." I see that this switch controls whether the class includes "HasBeenSet" functions. Does it do anything else? If not, I imagine that we could simply include those functions in the merged class.

An alternative solution to merging the classes might be to give all of them methods that allow conversion to/from JSON. Presently, only the sub-shape class includes the Jsonize() function and the from-JSON constructor. If All of the classes had these methods, then conversions between the classes would be maintainable.

**Comment by JonathanHenson** [comment]
yes, use composition. It will only generate one shape. see aws-cpp-sdk-dynamodb TableDescription and AttributeValue.

Define the structure then put a reference to the structure in your request and result shapes.

**Comment by csimmons0** [comment]
I see. I could make that work, but it's not ideal. What's the cause for separate classes for requests and results? I know that an ObjC library generated from an API Gateway doesn't have this quirk.
