### ISSUE TITLE
Could not load aws-sdk using node.js

### ISSUE THREAD

**Issue by N1N** [aws/aws-sdk-cpp#435]
Hi,

I installed node.js in my PC, and installed aws-sdk successfuly with the below command.
_**npm install aws-sdk -g package.json**_

I have a html file, in which i am trying to ling aws-sdk. But it is failing.
Code looks like this,

var s3;
function inits3()
{
alert("alert1");
//var AWS = require('C:/Program Files/nodejs/node_modules/aws-sdk');
var AWS = require('aws-sdk');

alert("alert2");
s3 = new AWS.S3({ params: { Bucket: 'test' }});
}

**Note : I am getting the alert box message alert1 but not alert2.**

Please suggest!!

Regards.

**Comment by JonathanHenson** [comment]
I think you intended the aws-sdk-js repositiory?

https://github.com/aws/aws-sdk-js/issues
