### ISSUE TITLE
segfaults only when an object is written to or read from s3

### ISSUE THREAD

**Issue by sanafrasu20** [aws/aws-sdk-cpp#437]
Hi
 
I am using this example: [s3client](https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/)
It uploads and downloads the 'Hello world' text, but segfaults while exiting the code. After the `Aws::ShutdownAPI(options);` call at the end (couts confirmed it).

If I comment out the upload and download code, then there is no segfault. 
Help please.

thanks in advance

**Comment by JonathanHenson** [comment]
You need scoping brackets between InitAPI and ShutdownAPI. The Client is getting cleaned up after shutdown. On linux this will cause problems.

**Comment by JonathanHenson** [comment]
Did following my suggestion fix your issue? Please reopen if this is still a problem after trying my suggestion.

**Comment by sanafrasu20** [comment]
Thank you it worked.
