### ISSUE TITLE
Kinesis Application Fails to Compile with error incomplete type instantiation

### ISSUE THREAD

**Issue by BCribbs** [aws/aws-sdk-cpp#441]
When using Kinesis, you have to include "#include <aws/core/utils/Outcome.h>" prior to including any "request" type because the "outcome" types are not fully defined in the typedef due to forward declarations.  

Recommend, including Outcome.h in KinesisClient.h, where the typedefs are for the various "outcomes."  This avoids the compile time issue.

Issue seen both on Mac OSX with clang 3.3 and on Linux with g++ (version unsure) but other applications work.

**Comment by bretambrose** [comment]
My personal approach here is that the only includes that should appear in a header file are those necessary to declare instances of the types defined, where forward declarations are insufficient.  There are certainly situations where the service clients might be used, but there is no need to know Outcome's definition, thus why it's not included in the header.  

It would be nice if the error message you get when missing Outcome's definition were more obvious, but that isn't something we have control over.

**Comment by BCribbs** [comment]
The issue is the forward declaration which does not allow compilation unless Outcome.h is explicitly included **before** the inclusion of the client, otherwise the code where you'd like to do something like 

auto createStreamOut = kClient.CreateStream( createStreamRequest );

will not compile because the CreateStreamOutcome defined by auto has not been fully specified without the developer explicitly including Outcome.h which is a base type, and not directly used, it merely gets used on the typedef of CreateStreamOutcome in the definition of the client in KinesisClient.h

Hence, the compiler complains and it takes a lot of debugging to realize what dependency was not defined and its buried in a typedef of a template datatype.

**Comment by bretambrose** [comment]
I have recreated this and did not observe any order dependency between header includes.  Are you able to provide a code sample where switching include ordering causes a compilation break?

**Comment by BCribbs** [comment]
This breaks if you comment Outcome.h out.  This breaks on both clang and g++, I have not tried MS VC++. I did not init the SDK in this example so forgive the absent Init and Shutdown calls, this strictly illustrates the compile issue.  The error wording between clang and c++ are slightly different but both hint at the forward declaration issue.  This as shown compiles not issues, remove or comment out the top line and it breaks.

#include <aws/core/utils/Outcome.h>
#include <aws/kinesis/model/CreateStreamRequest.h>
#include <aws/kinesis/KinesisClient.h>
#include <aws/core/client/ClientConfiguration.h>
#include <aws/core/Aws.h>

int main() {

        Aws::Client::ClientConfiguration kconfig;
        Aws::Kinesis::KinesisClient kClient(kconfig);

        Aws::Kinesis::Model::CreateStreamRequest createStreamReq;
        createStreamReq.WithStreamName("aws-kinesis-test-stream").WithShardCount(4);
        auto createStreamOut = kClient.CreateStream( createStreamReq );

        exit(0);
}

**Comment by bretambrose** [comment]
I must have misinterpreted what you were saying in your followup.  I thought you meant that you had code that failed or succeeded to compile depending on include order, but this looks like the original issue.

I'm sure you can find unnecessary includes throughout the SDK codebase, but this is an area I always try (don't always succeed though) to be very careful and absolutely minimal with.  I've worked with C++ codebases that took multiple hours to compile and the combinatorial explosion from unnecessary header includes (which could have been replaced by forward declarations) was a significant portion of that.

Given that Outcome.h doesn't look to have much of an include cost, I think it's probably ok to add to the client headers.

**Comment by singku** [comment]
This issue is similar to #679
