### ISSUE TITLE
Partial File Download Between File Offsets

### ISSUE THREAD

**Issue by hnaik** [aws/aws-sdk-cpp#443]
Hi,

I am currently using Aws::TransferManager::DownloadFile() for downloading large files (> 5GB). Sometimes we know certain file offsets (of the data of interest) ahead of time. In these cases we'd like to download contents between these offsets only. I looked at TransferManager and I couldn't find an obvious way to do that. Is this supported by the API?

Thanks,
Harish

**Comment by JonathanHenson** [comment]
You can use the Aws::S3::S3Client with Aws::S3::Model::GetObjectRequest using the range specifier.

**Comment by hnaik** [comment]
Can I get a 500MB chunk using this? I was of the opinion that for anything greater than 5MB we were to use aws-cpp-sdk-transfer and not the low-level aws-cpp-sdk-s3.

**Comment by JonathanHenson** [comment]
transfer manager just makes it easier. But transfer manager is built around the use case of lots of file transfers and directory synchronization. You can do what you need to do using the s3 client directly.
