### ISSUE TITLE
S3 PutObjectRequest class has no method to set ContentType

### ISSUE THREAD

**Issue by edolstra** [aws/aws-sdk-cpp#444]
As of a8d7208df27b577cd4d522f27d1bb899e40f35b6, `PutObjectRequest` has no methods to set the `Content-Type` of the uploaded object, despite being part of the API description:
```
        "ContentType":{
          "shape":"ContentType",
          "documentation":"A standard MIME type describing the format of the object data.",
          "location":"header",
          "locationName":"Content-Type"
        },
```

The `HttpRequest` class does have a `SetContentType` method, but it's not clear how to use it when using `S3Client::PutObject()`.

**Comment by JonathanHenson** [comment]
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/include/aws/core/AmazonStreamingWebServiceRequest.h#L74

use it as follows:

Aws;:S3::Model::PutObjectRequest request;
request.SetContentType("your content type");
