### ISSUE TITLE
unit tests for text-to-speech get stuck

### ISSUE THREAD

**Issue by ilovezfs** [aws/aws-sdk-cpp#446]
The build of 1.0.66 is failing on Homebrew CI because the text-to-speech tests are getting stuck. Specifically, I'm having to comment out TestSynthResponseAndOutput and TestSynthRequestFailedAndNoOutput otherwise the build never completes.

**Comment by JonathanHenson** [comment]
Sorry about that. Fixed:

000a17c9f1f92d90c9216d27efd6175a5d08c204

**Comment by ilovezfs** [comment]
Thanks @JonathanHenson
