### ISSUE TITLE
aws-sdk-cpp release 1.0.68 build fails.

### ISSUE THREAD

**Issue by sagariiit** [aws/aws-sdk-cpp#447]
Build fails with 'memcpy' not declared in SimpleStreamBuf.cpp

Logs:
/source/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/stream/SimpleStreamBuf.cpp:55:49: error: 'memcpy' was not declared in this scope
     memcpy(m_buffer, value.c_str(), value.size());
                                                 ^
/source/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/stream/SimpleStreamBuf.cpp: In member function 'bool Aws::Utils::Stream::SimpleStreamBuf::GrowBuffer()':
/source/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/stream/SimpleStreamBuf.cpp:135:48: error: 'memcpy' was not declared in this scope
         memcpy(newBuffer, m_buffer, currentSize);
                                                ^
/source/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/stream/SimpleStreamBuf.cpp: In member function 'virtual std::streamsize Aws::Utils::Stream::SimpleStreamBuf::xsputn(const char*, std::streamsize)':
/source/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/stream/SimpleStreamBuf.cpp:195:58: error: 'memcpy' was not declared in this scope
             memcpy(current_pptr, s + writeCount, copySize);
                                                          ^

**Comment by wiredwizardsCoach** [comment]
This broke my nightly build but a quick `sed` will fix the compilation issue.. adjust your path accordingly. This only fixes the broken build at least under my scenario of using gcc 4.9. If this error slipped through, who knows what other issues are lurking as a result.

`sed -i "21i #include <cstring>" aws-cpp-sdk-core/source/utils/stream/SimpleStreamBuf.cpp`
`sed -i -e "s/memcpy/std::memcpy/g" aws-cpp-sdk-core/source/utils/stream/SimpleStreamBuf.cpp`

In "English", edit `SimpleStreamBuf.cpp` and:

1) Add an `#include <cstring>` to the top, I put it on line 21.
2) Change `memcpy` to `std::memcpy`

**Comment by bretambrose** [comment]
This should be fixed in the latest release.
