### ISSUE TITLE
Inconsistent use of WIN32, _WIN32, __WIN32__ macros in source

### ISSUE THREAD

**Issue by kdekker** [aws/aws-sdk-cpp#449]
Hi,

I saw that I had to define WIN32 to get correct exported symbols of the aws-sdk-cpp-master stuff. This is caused because not the _WIN32 (note the leading underscore) macro is used. Visual Studio at default sets _WIN32 (see https://msdn.microsoft.com/en-us/library/b0084kay.aspx) but not WIN32 (in the very old days, this was done by Visual Studio 6, and new projects MAY still add WIN32, but it is not guaranteed that this macro is set).

I would request to change all occurances of WIN32-kind macros to _WIN32.

I found in the following files (I'm not sure which SDK version this is, how can I check?) some inconsistent usage of WIN32 defines, see below. It would be great if these can be fixed by consistently using _WIN32.

```
aws-sdk-cpp-master\aws-cpp-sdk-core\include\aws\core\Core_EXPORTS.h:20:#if defined (USE_WINDOWS_DLL_SEMANTICS) || defined (WIN32)
aws-sdk-cpp-master\aws-cpp-sdk-core\include\aws\core\Core_EXPORTS.h:34:#else // defined (USE_WINDOWS_DLL_SEMANTICS) || defined (WIN32)
aws-sdk-cpp-master\aws-cpp-sdk-core\include\aws\core\Core_EXPORTS.h:36:#endif // defined (USE_WINDOWS_DLL_SEMANTICS) || defined (WIN32)
aws-sdk-cpp-master\aws-cpp-sdk-core\include\aws\core\utils\crypto\bcrypt\CryptoImpl.h:28:#define WIN32_NO_STATUS
aws-sdk-cpp-master\aws-cpp-sdk-core\include\aws\core\utils\crypto\bcrypt\CryptoImpl.h:33:#undef WIN32_NO_STATUS
aws-sdk-cpp-master\aws-cpp-sdk-core\source\utils\logging\FormattedLogSystem.cpp:85:    #ifdef WIN32
aws-sdk-cpp-master\aws-cpp-sdk-core\source\utils\logging\FormattedLogSystem.cpp:93:    #ifdef WIN32
aws-sdk-cpp-master\aws-cpp-sdk-core\source\utils\logging\FormattedLogSystem.cpp:97:    #endif // WIN32
aws-sdk-cpp-master\aws-cpp-sdk-kms\include\aws\kms\KMS_EXPORTS.h:22:#if defined (USE_WINDOWS_DLL_SEMANTICS) || defined (WIN32)
aws-sdk-cpp-master\aws-cpp-sdk-kms\include\aws\kms\KMS_EXPORTS.h:36:#else // defined (USE_WINDOWS_DLL_SEMANTICS) || defined (WIN32)
aws-sdk-cpp-master\aws-cpp-sdk-kms\include\aws\kms\KMS_EXPORTS.h:38:#endif // defined (USE_WINDOWS_DLL_SEMANTICS) || defined (WIN32)

```

**Comment by KaibaLopez** [comment]
Hi @kdekker , sorry for the late response This has been fixed in commit 84a5f670f50
