### ISSUE TITLE
InvalidParameterException Missing required parameter SRP_A

### ISSUE THREAD

**Issue by gkhanacer** [aws/aws-sdk-cpp#452]
Hi, 

I want to apply [that](http://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-integrating-user-pools-javascript.html#tutorial-integrating-user-pools-userpool-object-javascript) statement for cpp: 

I tried to adopt it cpp.  I could sign-up operation. When I tried to sign-in, I encountered that exception:
**"InvalidParameterException :  Missing required parameter SRP_A"**

This is part of my code:

```
    Aws::Map<Aws::String, Aws::String> authParameters;

   Aws::Map<Aws::String, Aws::String> authParameters;
    authParameters.insert(
        std::pair<Aws::String, Aws::String>("USERNAME", "xxxxx"));
    authParameters.insert(
        std::pair<Aws::String, Aws::String>("PASSWORD", "xxxxx"));

    InitiateAuthRequest initiateAuthRequest;
    initiateAuthRequest.SetAuthFlow(
        Aws::CognitoIdentityProvider::Model::AuthFlowType::USER_SRP_AUTH);
    initiateAuthRequest.SetClientId(TEST_APP_CLIENT_ID);
    initiateAuthRequest.SetAuthParameters(authParameters);

    InitiateAuthOutcome initiateAuthOutcome =
        client.InitiateAuth(initiateAuthRequest);
    if (initiateAuthOutcome.IsSuccess()) {
        qDebug() << "Initiate auth: " << initiateAuthOutcome.IsSuccess();
    } else {
        qDebug() << initiateAuthOutcome.GetError().GetExceptionName().c_str()
                 << ": " << initiateAuthOutcome.GetError().GetMessage().c_str();
    }
```

How can I add SRP_A attribute to InitiateAuthRequest? For other platforms (android, ios and js), their sdk has SRP_A generator like [there](https://forums.aws.amazon.com/message.jspa?messageID=733601). 

How can I solve this problem. Thanks.

**Comment by bretambrose** [comment]
I don't know this API, but from what I can gather from the docs, you need to populate your authParameters map with key-value pairs that correspond to the requirements of the authentication type you are attempting.  See http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html#API_InitiateAuth_RequestSyntax

**Comment by gkhanacer** [comment]
I have already filled key-value pairs, but a pair that is SRP_A is necessary.

**Comment by JonathanHenson** [comment]
We haven't added SRP support yet. We are currently researching cross-platform ways of handling it.

**Comment by SahilRanjan05** [comment]
I am using PHP sdk for aws cognito. I am facing problem in suppressing mfa. How to remember device in aws cognito using php sdk. Thanks...
