### ISSUE TITLE
WinHttpSyncHttpClient [16236] Send request failed: A certificate is required to complete client authentication

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#453]
This happens when endpoint is configured to request client certificate during TLS handshake. Basically, server can still let you through, if you set related flag:
`WinHttpSetOption(res, WINHTTP_OPTION_CLIENT_CERT_CONTEXT, WINHTTP_NO_CLIENT_CERT_CONTEXT, 0);`

Problem is that right now there is no good way to do it -- I can intercept creation of Aws::Http::WinHttpSyncHttpClient and provide better implementation of OpenRequest(), but this method is private -- I can override it, but I can't call it from derived class. So, I have to either copy entire WinHttpSyncHttpClient implementation into my codebase or rely on extremely dirty hack like this one:

```
#include <aws/core/http/HttpClient.h>
#include <aws/core/http/windows/WinSyncHttpClient.h>
// this is a very bad way to hack AWS SDK, I am gonna burn in hell for this (ODR violation)
struct MyHttpClient;
#define private friend struct MyHttpClient; private
#include <aws/core/http/windows/WinHttpSyncHttpClient.h>
#undef private
```

We need a decent way to be able to specify this option (or at the very minimum -- change 'private' to 'protected' in WinHttpSyncHttpClient).

Also, it would be nice to be able to specify client certificate, in case if server insists.

Note: Happens only on Windows (looks like curl-based logic handles this properly).

**Comment by crusader-mike** [comment]
To clarify -- this doesn't happen with AWS S3 (because the way it's servers are configured), but it happens with other S3 (-compatible?) services like webscale.

**Comment by JonathanHenson** [comment]
Thanks for the callout, I'll look into this and see what we can do.

**Comment by crusader-mike** [comment]
Any progress with this one? I am still violating ODR in my code because of this. If you simply replace `private` with `protected` in WinHttpSyncHttpClient -- it will be enough...

**Comment by KaibaLopez** [comment]
Sorry, We have no plan to fix this at the moment.
