### ISSUE TITLE
GetObject resolves to GetObjectA/GetObjectW in Windows world

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#454]
If windows.h was included before related SDK header GetObject gets substituted (via define) to GetObjectA (or GetObjectW, if UNICODE is defined). This leads to curious linker errors, frustration and time spent chasing this down.

I understand this is not really SDK problem, but it would be real nice if every GetObject declaration was surrounded by something like this:
```
#pragma push_macro("GetObject")
#undef GetObject        // damn you, Bill Gates!
...
#pragma pop_macro("GetObject")
```

**Comment by JonathanHenson** [comment]
I agree. Unfortunately, that won't solve the problem since this often surfaces when you try to use GetObject in your own code. Do you have further recommendations on how to address that as well?

**Comment by crusader-mike** [comment]
Yes, but with this change I'll know exactly what is wrong and where. (it will fail at compile time and will show me the line). Without -- need to hunt down chains of includes.

Best solution -- rename GetObject to smth else.

**Comment by JonathanHenson** [comment]
Im not renaming GetObject just because MSFT couldn't figure out how to use unicode. The least they could have done was namespace their function name. Anyways, I'll look into your suggestion.

Thanks,

**Comment by crusader-mike** [comment]
if this SDK has common prologue/epilogue in every header -- undefs can go there. Slightly better solution, but yeah -- MS dropped the ball on this one.

**Comment by JonathanHenson** [comment]
every header has our dll export macros, we can probably drop it in there since that only gets defined for windows anyways.
