### ISSUE TITLE
SpotInstanceState is missing the "disabled" state.

### ISSUE THREAD

**Issue by yasushi-saito** [aws/aws-sdk-cpp#457]
I'm not sure this is a cpp issue or something deeper, but "aws ec2 describe-spot-instance-requests" returns a SIR with state "disabled". And that state is not defined in ec2/model/SpotInstanceState.h. It's value comes back as 270940796 from SpotFleetRequest::GetState().

**Comment by JonathanHenson** [comment]
Looks like the service changed without a model update. I'll reach out to the EC2 Team.

https://github.com/aws/aws-sdk-cpp/blob/master/code-generation/api-descriptions/ec2-2016-09-15.normal.json#L16255

Thanks!

**Comment by JonathanHenson** [comment]
I've made the change. It's working it's way through our pipeline. I've also notified Ec2 to update their model, it should update the other SDKs as well once that change is made.
