### ISSUE TITLE
S3Client::HeadObject: Wrong error type returned when request time is skewed

### ISSUE THREAD

**Issue by stavros-vagionitis** [aws/aws-sdk-cpp#458]
Making a request to download a file from a S3 bucket using the S3Client::HeadObject, when the request time is skewed, returns a wrong error type.

In detail, the error returned is the following:
* HeadObjectOutcome::GetError().GetErrorType() returns 100, CoreErrors::UNKNOWN.
* HeadObjectOutcome::GetError().GetExceptionName() returns an empty string
* HeadObjectOutcome::GetError().GetMessage() returns `No response body.  Response code: 403`
which makes a little difficult to debug the problem.

I would expect an error type 20, CoreErrors::REQUEST_TIME_TOO_SKEWED and the message would have more details about the error.

I am using the v1.0.24, but I believe you will get the same behavior with the current version.

Thanks in advance.

**Comment by JonathanHenson** [comment]
What's more annoying about this is that we have mechanisms to handle clock skew automatically. We need a mapping of S3 Http error codes to more meaningful errors. I'll see if I can figure something out. Thanks for reporting this!

**Comment by JonathanHenson** [comment]
I've got a CR out for this. The basic idea, is we are just going to quit checking the error codes before handling clock skew. It's cheap enough given errors aren't a frequent path and we don't have to worry with services having different error codes to represent clock skew.

**Comment by JonathanHenson** [comment]
I just pushed this out. Two new changes. First, we will correctly resolve response-less errors that are 401,403, or 404. Second, we will always check clock skew and adjust if needed instead of only on a few errors that we expect to trigger from clock skew.
