### ISSUE TITLE
S3: All file sizes exceed upload limit

### ISSUE THREAD

**Issue by vsreekanti** [aws/aws-sdk-cpp#460]
This is a duplicate of #386, but the issue was closed, so I decided to open another one. 

I copied the code from the AWS SDK doc examples [here](https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/cpp/example_code/s3/put_object.cpp) and get the following error when trying to upload a 128KB file as well an empty file:

> PutObject error: EntityTooLarge Unable to parse ExceptionName: EntityTooLarge Message: Your proposed upload exceeds the maximum allowed size

The feedback from the other issue says:
> This line is not doing what you think it is doing. The first argument of MakeShared is a memory allocation tag. The second argument on is what get's passed to the constructor. Are you intentionally passing you filename as the memory allocation tag?

I couldn't find any documentation about the memory allocation tag and would appreciate any feedback. 

I also couldn't find any example code for the transfer manager and would appreciate any pointers about how to use that as well.

Thanks!

**Comment by bretambrose** [comment]
The memory allocation tag is just an arbitrary string so that you can classify or track your allocations.  Make it anything you want.

You can look at the tests in aws-cpp-sdk-transfer-tests for examples of how to use the transfer SDK.

**Comment by vsreekanti** [comment]
Thanks, Bret. Still would love to get some feedback on how to avoid the PutObjectError.

**Comment by bretambrose** [comment]
My best guess is the PutObject error likely comes from the fact that either the stream was invalid or did not have a binary flag set (if the file was binary).  Can you step through the http client request stream upload logic and check the state of the stream?

**Comment by JonathanHenson** [comment]
Are you still having problems with this? Please reopen if you still have problems.
