### ISSUE TITLE
Download Landsat from us-gov-west-1

### ISSUE THREAD

**Issue by KeithBlonquist** [aws/aws-sdk-cpp#464]
I'm trying to download Landsat imagery from us-west-2. When I run the attached code on my local machine, it works fine. When I run from AWS (us-gov-west-1) I get an "InvalidAccessKeyId" error. What am I missing? Can Landsat imagery on us-west-2 be accessed from us-gov-west-2 through the S3Client?

**Comment by KeithBlonquist** [comment]
This is probably related to issue #365

**Comment by JonathanHenson** [comment]
I suspect this is because gov cloud is a separate account pool from us-west-2 and the access key is actually invalid. Where are the credentials you are using from the gov-cloud instance coming from?

**Comment by KeithBlonquist** [comment]
Thanks for the reply. The credentials are coming from an IAM Role. I do not have access to edit or view the IAM Role, I would have to talk to our IT manager. I do know that the IAM Role has been configured to access specific S3 buckets within us-gov-west-1.

**Comment by JonathanHenson** [comment]
I suspect those are actually two separate accounts and the credentials for us-gov-west-2 are invalid for calls to us-west-2. But you'll need to check with your IT manager.

**Comment by KeithBlonquist** [comment]
Thanks again. I'll touch base with him and let you know if/when this is resolved.

**Comment by KeithBlonquist** [comment]
I updated to the latest after the fix for issue #365. I also found that there was an old credential file being used rather than the IAM Role. Now that the credential file has been removed, and the IAM Role is being used, I am getting an "InvalidToken" error. I have attached the log output. I am still missing something...

[aws_sdk_2017-03-07-15.txt](https://github.com/aws/aws-sdk-cpp/files/824893/aws_sdk_2017-03-07-15.txt)

**Comment by KeithBlonquist** [comment]
Update and Clarification: After confirming that the IAM Role is being used (and not an old credential file) I am no longer getting an "InvalidAccessKeyId" error, but an "InvalidToken" error when trying to download Landsat imagery from us-west-2 to us-gov-west-1. The file downloads just fine from my local machine. I have attached the source code, the output log from AWS, and the output log from my local machine.

Looking at the difference between the two logs, there is no x-amz-security-token in the local log. Is the token even necessary for this request?

[aws_sdk_2017-04-20-10_local.txt](https://github.com/aws/aws-sdk-cpp/files/944577/aws_sdk_2017-04-20-10_local.txt)
[aws_sdk_2017-04-20-16_aws.txt](https://github.com/aws/aws-sdk-cpp/files/944578/aws_sdk_2017-04-20-16_aws.txt)

[S3_Test_cpp.txt](https://github.com/aws/aws-sdk-cpp/files/944584/S3_Test_cpp.txt)

**Comment by KeithBlonquist** [comment]
If authorization is the issue, here, is there a way to send a request with the CPP SDK without authorization?

**Comment by JonathanHenson** [comment]
If the creds are from an STS Assume Role call, then the token is necessary.

How are you acquiring these credentials?

**Comment by KeithBlonquist** [comment]
When requesting from the EC2 instance on AWS, I believe the credentials are from an IAM Role. See the aws_sdk_2017-04-20-16_aws.txt above (this is the TRACE level log).

When requesting from my local computer, I don't believe it is getting credentials from anywhere. See the aws_sdk_2017-04-20-16_local.txt above.

**Comment by JonathanHenson** [comment]
You can make the call without creds just by using an AnonymousCredentialsProvider instead of the default. I'm not sure why the IAM role being vended by Ec2 is failing. 

One weird thing though. It looks like there is data in your $HOME/.aws/config file? That may be causing some sort of collision.

**Comment by KeithBlonquist** [comment]
I deleted the config file, but the issue remains. Can you point me to instructions on using an AnonymousCredentialsProvider. Right now I'm just allowing the default chain...

**Comment by KeithBlonquist** [comment]
It works with an AnonymousCredentialsProvider. Thank you!
