### ISSUE TITLE
MetricDatum should have a getter for m_xyHasBeenSet.

### ISSUE THREAD

**Issue by TmsKtel** [aws/aws-sdk-cpp#465]
I'm working with CloudWatch::Model::MetricDatums of the monitoring library and at a certain point it would be very useful for me if I could decide if StatisticSet or the Value has been set in a certain object.
There are already m_statisticValuesHasBeenSet and m_VeluHasBeenSet, but they're private. :(
Most probably this would be helpful in other classes as well, but this is where I have encountered it.

**Comment by TmsKtel** [comment]
It would be more elegant if these bool flags were protected and OutPutToStream was virtual.

**Comment by singku** [comment]
Has been supported
