### ISSUE TITLE
How to completely remove aws-sdk-cpp libraries and headers from ubuntu

### ISSUE THREAD

**Issue by dk1301** [aws/aws-sdk-cpp#466]
Hi all,
I have installed on a Ubuntu 16.04 Vm the 1.0.24  version c++ aws-cpp-sdk-core , aws-cpp-sdk-config, aws-cpp-sdk-kinesis. I'd like to completely remove them in order to install the latest version 1.0.76. I tried the command make uninstall but I got the following error message :
make: *** No rule to make target 'uninstall'.  Stop.
I there any other safe way to remove the libraries or can I install the new version on top of the old one?

**Comment by JonathanHenson** [comment]
we need to add an uninstall target.  In the meantime rm -r /usr/include/aws
and rm /usr/lib/libaws-cpp-*

should do the trick.

**Comment by dk1301** [comment]
Thanks a lot.

**Comment by Bu11etmagnet** [comment]
Also, rm -rf  /usr/lib/cmake/aws-cpp-* (see #455)
