### ISSUE TITLE
Unresolved external symbol when upgrading project from MS VS Studio 2015 to 2017

### ISSUE THREAD

**Issue by dkarantonis** [aws/aws-sdk-cpp#467]
Hi,

just upgraded my project from MS VS Studio 2015 to 2017. I have installed aws libraries via nuget and when compiling code i get unresolved external symbol error messages to all code that aws is used.

Could you please advice? Is this aws or VS Studio 2017 issue? 

Please note that i have installed latest aws version 1.0.81 and that when compiling from MS VS Studio 2015 it works.

thanks in advance

**Comment by OlafvdSpek** [comment]
Have you tried vcpkg?

**Comment by dkarantonis** [comment]
No, 

I would like to keep up with nuget installation. 

Is this an AWS issue or VS Studio 2017?

**Comment by bretambrose** [comment]
The nuget packages are linked against the c runtime of the corresponding version of Visual Studio.  Microsoft tends to make breaking changes to this library with new Visual Studio releases, so the existing packages will probably not work with VS 2017.  Your best bet would be to build the SDK yourself using VS 2017.

**Comment by JonathanHenson** [comment]
we have nuget support for vs 2017 on our roadmap, I just haven't done it yet.

**Comment by OlafvdSpek** [comment]
2017 is supposed to be binary compatible with 2015.

**Comment by dkarantonis** [comment]
So, i understand that installing is not working via nuget on VS 2017 for the moment. I guess vcpkg is the alternative to install aws in VS 2017 for the moment?

thanks
