### ISSUE TITLE
Build S3 for Android (API 19) and use static linking

### ISSUE THREAD

**Issue by kiril-kirov** [aws/aws-sdk-cpp#472]
Hi, 

I'm trying to build S3 for Android, targeting API 19, and use static linking. So, as far as I understand from the documentation, I need to use **gnustl_static**. 

On the other hand, the documentation clearly states the following:
> If static linking is enabled, custom memory management defaults to off. If dynamic linking is enabled, custom memory management defaults to on and avoids cross-DLL allocation and deallocation.

but this appears to be different from my observations. Even explicitly disabling the custom memory management, using `-DCUSTOM_MEMORY_MANAGEMENT=0`, does not seem to work.

My whole `cmake` command is:
```
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF \
  -DFORCE_SHARED_CRT=OFF -DTARGET_ARCH=ANDROID -DANDROID_ABI=x86 \
  -DENABLE_TESTING=OFF -DANDROID_STL=gnustl_static \
  -DCUSTOM_MEMORY_MANAGEMENT=0 ../../../Source/
```
Running `cmake`, I see the following:
> Custom memory management enabled; stl objects now using custom allocators

which is printed by the S3's `CMakeLists.txt`. Digging a bit deeper, I found the following in `android.cmake`:  
```
# android-specific required overrrides  
set(CUSTOM_MEMORY_MANAGEMENT "1")
```

which clearly overrides the passed `-D` argument to `cmake`.

So, if I understand correctly, if I need static linking, I should disable custom memory management, but the Android build does not allow this.

Any advises?

Thanks in advance and best regards, 
Kiril

P.S.
Checking the `SDKConfig.h` file confirms the usage of custom memory management, as it contains: `#define USE_AWS_MEMORY_MANAGEMENT`

**Comment by bretambrose** [comment]
I can't think of a reason we should force custom memory management on Android these days.  Can you just delete that forced set and verify that you don't get any problems with static linking and standard memory management?  If everything seems good, we'll remove it.

**Comment by kiril-kirov** [comment]
Unfortunately, I had to postpone the Android development for the project, so I can't test this (because of other issues, which I can't tell if they are related to this one or not). 
Thanks for the reply, it was really helpful.
