### ISSUE TITLE
Is there a way to build my API without rebuilding core?

### ISSUE THREAD

**Issue by csimmons0** [aws/aws-sdk-cpp#476]
I'm trying to decrease build times by building libraries that don't change ahead of time and checking them into source control. I've done so with the following libraries, and that's working fine.
```
libaws-cpp-sdk-access-management.a
libaws-cpp-sdk-cognito-identity.a
libaws-cpp-sdk-core.a
libaws-cpp-sdk-iam.a
```
The problem is that when I try to build the library for my API, vitalservices, the build fails unless I also build the core library along with it. I want to pass "-DBUILD_ONLY=vitalservices" to the build, but I have to use "-DBUILD_ONLY=core;vitalservices" instead. Considering that I have already built libaws-cpp-sdk-core.a, is there a way to avoid building it again? I've attached the entire output of the failing build for reference.
[nocore.txt](https://github.com/aws/aws-sdk-cpp/files/852644/nocore.txt)

**Comment by JonathanHenson** [comment]
As currently designed, Core is always included in the build, though it shouldn't be building across the same build directory unless the source has changed. As far as the high-level libs go, I'd be careful. We don't guarantee ABI compatibility (object sizes always changing) between any two versions of the service specific libraries, which would potentially cause libaws-cpp-sdk-transfer (for example) to explode when it is linked to libaws-cpp-sdk-s3 different than the one it was compiled against.
