### ISSUE TITLE
PutMetricDataRequest fails to move

### ISSUE THREAD

**Issue by Bu11etmagnet** [aws/aws-sdk-cpp#483]
Although `SetMetricData(Aws::Vector<MetricDatum>&& value)` appears to have been written with the intent to move-assign the parameter to its member, it fails to achieve this:
 https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-monitoring/include/aws/monitoring/model/PutMetricDataRequest.h#L104

(`value` is an lvalue, because it has a name, so the copy assignment of `Aws::Vector` is called, not the move assignment).

`m_metricData = value;` should have been `m_metricData = std::move(value);`

`SetNamespace(Aws::String&& value)` suffers from the same problem (and I suspect many other API methods in other classes throughout the library):

```
$ find aws-cpp-sdk-* -name '*.h' | xargs grep --color -nP '\b(Set|With|Add).*\w+\s*&&\s*(\w+)\s*\)\s*{' | grep -vw move | wc -l
37800
```

**Comment by JonathanHenson** [comment]
Good callout, I'll add a story to our backlog to update.

**Comment by Bu11etmagnet** [comment]
Are these functions generated? Then changing the generator might fix most if not all 37000+ instances.

**Comment by JonathanHenson** [comment]
it's a trivial fix. It will be done very soon
