### ISSUE TITLE
Log to console in examples

### ISSUE THREAD

**Issue by OlafvdSpek** [aws/aws-sdk-cpp#484]
Logging to console would demonstrate the log options and it makes it easier to stop things that go wrong.

**Comment by JonathanHenson** [comment]
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/include/aws/core/utils/logging/ConsoleLogSystem.h

**Comment by OlafvdSpek** [comment]
It should log to clog or cerr rather then cout and it should be the default in the example projects.

**Comment by JonathanHenson** [comment]
I could probably make it the default for all debug builds.

**Comment by JonathanHenson** [comment]
I've added this to our backlog. Thanks for the idea!
