### ISSUE TITLE
Runtime error using DynamoDB

### ISSUE THREAD

**Issue by marcblank** [aws/aws-sdk-cpp#485]
Hi.  My tiny app using DynamoDB (a test, basically) fails before running any of my code with this error:

"Entry Point Not Found"

The procedure entry point ?GetSigningTimestamp@AWSAuthSigner@Client@Aws@@UBE?AVDateTime@Utils@3@XZ could not be located in the dynamic link library ... aws-cpp-sdk-dynamodb.dll

First time trying to use the SDK; so far, it's been very painful.  Any idea what this means?  

Marc

Using Visual Studio 2015, C++, got packages from NuGet

Also, this happens when this is the only source file...

#include "stdafx.h"

#include <aws/dynamodb/DynamoDBClient.h>
int main()
{
	Aws::DynamoDB::DynamoDBClient dynamoDbClient;
    return 0;
}

**Comment by JonathanHenson** [comment]
For some reason, NuGet hasn't been pulling down the latest version of Awssdkcpp-core. Go into NuGet manager, navigate to Awssdkcpp-core, and click upgrade.

**Comment by JonathanHenson** [comment]
Did this resolve your issue? Please reopen if you still have a problem.
