### ISSUE TITLE
Pulse Audio / cmake change causes iOS build to fail with missing CRT

### ISSUE THREAD

**Issue by csimmons0** [aws/aws-sdk-cpp#486]
I recently tried to merge the latest version of this repository into my fork, and I found that I couldn't build for iOS and armv7 or armv7s any more. The C compiler test at the start of the build fails and gives the error, "ld: library not found for -lcrt1.3.1.o". I tracked the cause to change 21d35a55d1061598b6e63a2a57312d2dc0cb1c00 using git bisect. I suspect that this diff, in particular, has something to do with the error:
```
diff --git a/cmake/initialize_project_version.cmake b/cmake/initialize_project_version.cmake
index 6aaa5b23a..3479cde51 100644
--- a/cmake/initialize_project_version.cmake
+++ b/cmake/initialize_project_version.cmake
@@ -31,6 +31,6 @@ macro(add_project name description)
     cmake_policy(SET CMP0054 NEW)
     cmake_policy(SET CMP0056 NEW)
 
-    project(${name} VERSION "${PROJECT_VERSION}" LANGUAGES CXX)
+    project(${name} VERSION "${PROJECT_VERSION}" LANGUAGES CXX C)
 
 endmacro()
```
I don't get the error when building for arm64, i386, or x86_64. The full output of the build is attached.
[build_output.txt](https://github.com/aws/aws-sdk-cpp/files/880110/build_output.txt)

**Comment by csimmons0** [comment]
I've found that changing that line in the cmake file back to
```
project(${name} VERSION "${PROJECT_VERSION}" LANGUAGES CXX)
```
allows me to build the libraries that I need to, but I doubt that doing so is a proper solution to the problem.

**Comment by neland** [comment]
I met the similar error with you. Do you have any progress on it except the workaround?

**Comment by singku** [comment]
Hello, is this still a problem for you guys @csimmons0 @neland

**Comment by singku** [comment]
Closing since no response.
