### ISSUE TITLE
Having a problem with new multipart TransferManager.DownloadFile()

### ISSUE THREAD

**Issue by mattman71** [aws/aws-sdk-cpp#488]
Since the new changes for (internal) support of multipart download of large files, I've been encountering a strange error than I cannot account for in my client code (which hasn't changed). This happens with 1.0.84 and 1.0.92, but not with 1.0.76.

I'm using TransferManager.DownloadFile() (using a filename parameter, not my own stream) and then WaitUntilFinished. I'm getting Aws::Transfer::TransferStatus::COMPLETED correctly, so I continue with my code.

The file I'm downloading is a 25MB file. Files that are small enough to not engage the multipart logic do not have a problem. I'm not sure where the size limit is to engage the new code, but 25MB is enough to do it. After the download, when I attempt to open the file, I get an error similar to "The process cannot access the file because it is being used by another process."

After I close my client app, the access works fine and the validation works to prove that nothing is corrupt.

It seems like the multipart download is not properly closing the stream, or keeping some kind of lock on it. I'm not sure what I can do differently to check for that or to force it closed. Other than my failed attempt to open the file, I have nothing else that touches the file in my code.

Any ideas how to pinpoint the problem or prove who is doing it wrong (probably me, but I can't figure out how yet)?

**Comment by bretambrose** [comment]
It looks like the m_downloadStream member of TransferHandle doesn't get cleaned up properly.  We should be able to get a fix out quickly.

**Comment by mattman71** [comment]
Great! I tried to find the source of the problem before submitting the issue, but wasn't able to do so quickly enough; then I figured one of you would be more familiar with the code and would be able to spot it if I described the behavior well enough. :)

**Comment by JonathanHenson** [comment]
The fix for this will be out within a minute or so. Please reopen if issue persists.
