### ISSUE TITLE
How can I make the SDK use std::string on Android?

### ISSUE THREAD

**Issue by csimmons0** [aws/aws-sdk-cpp#489]
How can I make the SDK use std::string on Android? It is my understanding from the comments in AWSString.h that all I should have to do is build with libc++. I have tried specifying libc++ in the cmake arguments as well as explicitly setting CUSTOM_MEMORY_MANAGEMENT=0, but I still get build errors when I try to mix std::string with Aws::String without resorting to calls to c_str(). This is my build script:
```
#!/usr/bin/env bash

set -e

ABIS=("x86" "armeabi-v7a")
WORKING_DIR=$(git rev-parse --show-toplevel)/client
BUILD_DIR=$WORKING_DIR/build-aws-cpp-sdk

$WORKING_DIR/helpers/GenerateVitalClient.sh

mkdir -p $BUILD_DIR
cd $BUILD_DIR
for ABI in "${ABIS[@]}"
do
    mkdir -p $ABI
    pushd .
    cd $ABI
    cmake -DTARGET_ARCH=ANDROID \
          -DNDK_DIR="${ANDROID_NDK_HOME}" \
          -DNDK_RELEASE=r13b \
          -DANDROID_NATIVE_API_LEVEL=21 \
          -DBUILD_ONLY="cognito-identity;access-management;vitalservices" \
          -DADD_CUSTOM_CLIENTS="serviceName=vitalservices,version=2016-11-23" \
          -DANDROID_STL=libc++_static \
          -DANDROID_ABI=$ABI \
          -DCUSTOM_MEMORY_MANAGEMENT=0 \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCPP_STANDARD=14 \
          -Wno-dev \
          $WORKING_DIR/deps/aws-sdk-cpp/

    make -j3
    popd
done
```

**Comment by bretambrose** [comment]
In android.cmake we force CUSTOM_MEMORY_MANAGEMENT to true unconditionally.  We could relax this and instead default it to 1 if not set.

**Comment by chris-doclily** [comment]
Ok. This sounds like a change I may be able to implement myself.

**Comment by chris-doclily** [comment]
See pull request #497.
