### ISSUE TITLE
Publish libraries to apt repo

### ISSUE THREAD

**Issue by pauldraper** [aws/aws-sdk-cpp#490]
It would be nice to published the compiled libraries, just like the Ruby, Python, PHP, JavaScript, and Java AWS SDKs are published as installable packages.

I've published debs to an apt repo here: https://github.com/lucidsoftware/aws-sdk-cpp-deb

**Comment by JonathanHenson** [comment]
Would you care to share the code for generating the deb files? I'd be happy to incorporate it into our build. We've been planning on this for a while, but haven't gotten around to it.

Also, it's not THAT useful, since we can't guarantee ABI compatibility between releases. 

I suppose we could only provide the static libs?

**Comment by pauldraper** [comment]
@JonathanHenson the repo I linked has all the code. Makefile is less than 100 lines. Debian has a bunch of fancy packaging tools, but mine is pretty bare bones.

I build two packages for each library: the binary package with the static binary, and the source package (`-dev`) with the headers.

> Also, it's not THAT useful, since we can't guarantee ABI compatibility between releases.

Sure, but that's for the consumers to figure out. E.g. I can consume 1.0.90 to 1.0.96. Debian actually has some tools to help downstream packages determine when symbols in shared libraries change. (https://www.debian.org/doc/debian-policy/ch-sharedlibs.html) But those don't really apply to C++ libs, which export pretty much everything.

There are some CMake tools (https://cmake.org/cmake/help/v3.0/module/CPackDeb.html), but I am no CMake expert.

**Comment by jmklix** [comment]
https://github.com/aws/aws-sdk-cpp/issues/1888

**Comment by jmklix** [comment]
Closing this issue as we currently don't have any plans to publish binaries and recommend consuming this sdk from source
