### ISSUE TITLE
Fail to override endpoint

### ISSUE THREAD

**Issue by lepsiloon** [aws/aws-sdk-cpp#491]
I am trying to override endpoint by using ClientConfiguration but got "InternalError Unable to parse ExceptionName" and "InternalError Message: We encountered an internal error. Please try again.".
Could anyone please explain it is a bug or something wrong in my code ? thanks a lot !
/////////////////////////////
{
	Aws::SDKOptions options;
	options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Info;
	Aws::InitAPI(options);
	Aws::Client::ClientConfiguration clientCfg;
	clientCfg.scheme = Aws::Http::Scheme::HTTP;
	clientCfg.connectTimeoutMs = 1000;
	clientCfg.requestTimeoutMs = 1000;
	**clientCfg.endpointOverride = "192.168.19.10.:9070";    //storage service address compatible with s3**
	Aws::S3::S3Client* s3client = new Aws::S3::S3Client(Aws::Auth::AWSCredentials("mykey",
		"mysecret"), clientCfg);
	auto list_buckets_outcome = s3client->ListBuckets();
        if (list_buckets_outcome.IsSuccess()) {
            std::cout << "OK" << std::endl;
        }
        else
        {
	    std::cout << "ListBuckets error: " <<
			list_buckets_outcome.GetError().GetExceptionName() << " " <<
			list_buckets_outcome.GetError().GetMessage() << std::endl;
        }
	Aws::ShutdownAPI(options);
}

**Comment by JonathanHenson** [comment]
"InternalError Message: We encountered an internal error. Please try again."

You'll probably have to ask the team that owns the storage service.

**Comment by crusader-mike** [comment]
Try specifying authRegion. Also, check source code to see if empty "bucket name" variable could lead to problems.

**Comment by Bu11etmagnet** [comment]
"192.168.19.10   .     :9070"
Are you sure about that dot between "10" and ":9070" ?

**Comment by crusader-mike** [comment]
lol

**Comment by lepsiloon** [comment]
@Bu11etmagnet  Thanks for indicating that typo. Unfortunately the error still happens after correct the wrong address.
@crusader-mike I was trying to modify "authenticationRegion" but it looks the filed is not defined in the struct ClientConfiguration. I am using vs2015 and AWSSDKCPP-Core version is v1.0.97, and AWSSDKCPP-S3 version is v1.0.20060301.97.

**Comment by crusader-mike** [comment]
debugger and wireshark are your best friends. No idea where did authenticationRegion go. Only @JonathanHenson knows. I remember having to use it (with some older version of SDK) when connecting to Webscale.

**Comment by JonathanHenson** [comment]
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h

I actually have no idea where it went. It wasn't purposefully removed. Ill add it back tonight. Sorry for the confusion.

**Comment by crusader-mike** [comment]
Huh... I checked old code to refreshed my memory on authenticationRegion. Basically:

- if seems that at some point authenticationRegion was removed and 'region' was used for authentication. Probably to prevent people from using authentication token produced in another region?

- for Webscale I ended up using empty region and empty bucket -- bucket was encoded in endpoint override url anyway, like this:   <server>/blah1/blah2 . I confess -- it is cheating... But I verified that it works in SDK source code. In my case endpoint URL is given from outside and I have not a single clue what is the target bucket name (which, by the way, may not show up on URL at all).

Btw, @lepsiloon -- where is the bucket name in your code? I don't see you setting clientCfg.bucket variable, nor it is present in endpoint override...

**Comment by JonathanHenson** [comment]
oh I remember now... lol... thanks for the refresher.

**Comment by francoisbailly** [comment]
bucket is prepended to url due to virtual addressing.
It is loosely document here: https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html
However, S3Client documentation itself never mentions the impact of the final constructor argument, which always defaults to true:
https://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_s3_1_1_s3_client.html#aec09aaff1ecfba34054c5e44b155ec48
