### ISSUE TITLE
HowTo authenticate a user that is in a UserPool using AWS C++ SDK.

### ISSUE THREAD

**Issue by paulkelly2000** [aws/aws-sdk-cpp#495]
I am trying to authenticate a user that is in a UserPool using the AWS C++ SDK.  I have written a small program to try to do this.  There are no examples on the AWS web site that are C++ based.  I tried looking at this JavaScript sample, http://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-javascript-examples.html in the Authenticate a User section, and translate to C++ hoping that there would be a 1-to-1 correspondence between the two languages.

Here is the code that I wrote:
#include <aws\cognito-identity\model\GetOpenIdTokenForDeveloperIdentityRequest.h>
#include <aws\cognito-identity\CognitoIdentityClient.h>
#include <aws\cognito-identity\CognitoIdentityRequest.h>
#include <aws\core\Aws.h>
#include <aws\core\auth\AWSCredentialsProvider.h>
#include <string>

using namespace Aws::CognitoIdentity;
using namespace Aws::CognitoIdentity::Model;
using namespace Aws::Auth;

void main()
{
    Aws::SDKOptions options;
    Aws::InitAPI(options);

    CognitoIdentityClient* identityClient = new CognitoIdentityClient(AWSCredentials("my access key -
 not included for privacy reasons","my secret access key - not included for privacy reasons"));

    AdminGetUserRequest objRequest;

    objRequest.SetIdentityPoolId("my pool id - not included for privacy reasons");

    objRequest.SetUsername("my id - not included for privacy reasons");

    auto objUserInfo = identityClient->AdminGetUser(objRequest);
 
   Aws::ShutdownAPI(options);
}

The objUserInfo has a success field.  It seems to be being set correctly whether the user is in the UserPool or not.  But, I don't use the users password.  I was wondering how I include the password for authentication?  Do I need to use a different request type?

**Comment by JonathanHenson** [comment]
AdminGetUser is not for authentication, and there is no place for a password in this call. It runs on top of the developer credentials.

http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminGetUser.html

Your next step is to call AdminitInitiateAuth or InitiateAuth

http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminInitiateAuth.html

**Comment by jkoutavas** [comment]
You want to use an SDK library extension that handles SRP (Server Remote Password) authentication. Here's a library I've had some success with: https://github.com/drozhkov/aws-cpp-cognito-auth

**Comment by KaibaLopez** [comment]
I'm marking this issue for closing as it seems to have been resolved, if there's any other doubts please comment, and we'll bring it back.
