### ISSUE TITLE
Building the package on various platforms

### ISSUE THREAD

**Issue by jace-bevo** [aws/aws-sdk-cpp#498]
I try to build the aws-sdk-cpp on Linux, MacOSX, and Windows and encounter the following issues:

1. How to build only certain modules, e.g. s3, dynamodb, cognito from the source code.  I pass various settings of -DBUILD_ONLY to cmake command line but none works. If I use a series of -DBUILD_ONLY like "-DBUILD_ONLY=s3 -DBUILD_ONLY=dynamodb -DBUILD_ONLY=cognito", only the last one gets built.
The syntax "-DBUILD_ONLY=s3,dynamodb,cognito" is not recognized at all.

2. It has dependency of libcurl, OpenSSL, and zlib.  These packages are available on Linux and MacOSX, they are not on Windows. And if I want to use newer version of libcurl, OpenSSL, how to I tell cmake to look for the libraries from different paths?

**Comment by JonathanHenson** [comment]
none of these things are true actually

BUILD_ONLY isnt workingn because that isn't the syntax for lists in cmake.

you want DBUILD_ONLY="s3;dynamodb;cognito-identity" 

There is no hard dependency on openssl on osx. Also zlib should no longer be required.

Apple builds use ComminCrypto.

**Comment by jace-bevo** [comment]
Thanks for the clarification Jon. 
 It seems the TARGET_ARCH macro is 'Apple' for MacOS, 'Linux' for Linux and 'Windows' for MS Window (case insensitive ?)
What should I set for Windows build so cmake can pick OpenSSL, zlib and libcurl from the path I specify?
(I have built these for Windows myself.)

**Comment by JonathanHenson** [comment]
is there a particular reason you arent using the platform defaults? Openssl and libcurl are unnecessary and less efficient than the win32 apis we use by default on windows. Windows has no dependencies.

If you wish to use libcurl on windows, you can use the -DFORCE_CURL argument. You'll also need to pass the path to your build libcurl to CMAKE_PREFIX_CONFIG

**Comment by jace-bevo** [comment]
Thanks for the info.
