### ISSUE TITLE
Unresolved symbol 'pa_strerror@@PULSE_0' 

### ISSUE THREAD

**Issue by jace-bevo** [aws/aws-sdk-cpp#499]
I try to build the whole package on Linux with the default setting.
**cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-m64 -fPIC -g -O3" -DSTATIC_LINKING=1 -DTARGET_ARCH=Linux -DCMAKE_INSTALL_PREFIX:PATH=/opt/AWS**

Everything seems to build correctly until the very end.
**[100%] Built target aws-cpp-sdk-core-tests
[100%] Linking CXX executable aws-cpp-sdk-text-to-speech-tests
/opt/rh/devtoolset-6/root/bin/ld: ../aws-cpp-sdk-text-to-speech/libaws-cpp-sdk-text-to-speech.a(PulseAudioPCMOutputDriver.cpp.o): undefined reference to symbol 'pa_strerror@@PULSE_0'
//lib64/libpulse.so.0: error adding symbols: DSO missing from command line
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)**
make[2]: *** [aws-cpp-sdk-text-to-speech-tests/aws-cpp-sdk-text-to-speech-tests] Error 1
make[1]: *** [aws-cpp-sdk-text-to-speech-tests/CMakeFiles/aws-cpp-sdk-text-to-speech-tests.dir/all] Error 2
make: *** [all] Error 2

Did I miss some setting?  It builds fine on MacOS though.

**Comment by jace-bevo** [comment]
I am using 1.0.101 release on CentOS 7.3. It has 'pulseaudio', 'pulseaudio-libs', and 'pulseaudio-libs-devel' installed.

**Comment by JonathanHenson** [comment]
I'm actually not sure what is going on. Looking in to it.

**Comment by jace-bevo** [comment]
I uninstalled pulse related packages and reran cmake so that it did not detect pulse (thus removed the dependency).  The build was successful this time.  Apparently somewhere in AWS code that uses pulse does not link with pulse library.

**Comment by jace-bevo** [comment]
Only need to un-install pulseaudio-libs-devel to remove the header files so that 'cmake' does not try to build modules that use pulseaudio.

**Comment by singku** [comment]
I guess library pulse was dynamically linked to text-to-speech.a and some of the symbols in it were unresolved, during test, we tried to link the test target with text-to-speech.a without linking with libpulse, so symbols in it still unresolved. Let me dive deep with this.

**Comment by singku** [comment]
Well, pa_strerror is a symbol from pluse instead of pluse simple, I will fix this
