### ISSUE TITLE
Building aws-sdk-cpp on Windows

### ISSUE THREAD

**Issue by jace-bevo** [aws/aws-sdk-cpp#500]
I want to build the package on Windows for both 32-bit and 64-bit. According to README, I can do it with
**cmake <path-to-root-of-this-source-code> -G "Visual Studio 12 Win64"**
**msbuild INSTALL.vcxproj /p:Configuration=Release**
I assume it means use either 'cmake' or 'msbuild'? 
I cannot find a MS project file called INSTALL.vcxproj under the source tree.  If I am to use cmake to build 32-bit version on Visual Studio 2015, what should I use in place of the **-G "Visual Studio 12 Win64"** flag?  Is it **-G "Visual Studio 14 Win32"** ?

**Comment by JonathanHenson** [comment]
Visual Studio 12 2013 Win64 ->Visual Studio 2013 64 bit configuration
Visual Stuidio 14 2015 Win32 -> Visual Studio 2015 32 bit configuration

etc....

**Comment by jace-bevo** [comment]
I am using CMake 3.8 and it seems to support only Win64 or ARM.  I ran cmake --help and got the following message.  I tried both 32-bit and 64-bit CMake and got the same message.  'Win32' is not an accepted architecture.

**The following generators are available on this platform:
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 8 2005 [arch]  = Generates Visual Studio 2005 project files.
                                 Optional [arch] can be "Win64".
  Visual Studio 7 .NET 2003    = Deprecated.  Generates Visual Studio .NET
                                 2003 project files.**

**Comment by jace-bevo** [comment]
It turns out that -G "Visual Studio 14 2015 Win64" is for 64-bit and -G "Visual Studio 14 2015" is 32-bit.
However, the resulting libraries are located under each module.  The CMAKE_INSTALL_PREFIX does not work. ( I guess it is for 'make install', which does not apply to Visual Studio).
Is there a way I can make it to put all 'include' and libraries in certain location?
