### ISSUE TITLE
Problem with glacier InitiateJob

### ISSUE THREAD

**Issue by Floaf** [aws/aws-sdk-cpp#501]
I am having trouble with downloading my vault inventory (and probably archives to).
My guess (since I cannot find any example anywhere how this is done) is that I should do it like:
```
Aws::Glacier::Model::JobParameters jobParameters;
jobParameters.SetType("inventory-retrieval");
jobParameters.SetDescription("Get vault inventory");
jobParameters.SetFormat("CSV");

Aws::Glacier::Model::InitiateJobRequest initiateJobRequest;
initiateJobRequest.SetAccountId("-");
initiateJobRequest.SetVaultName("Backup1");
initiateJobRequest.SetJobParameters(jobParameters);

auto initiateJobResult = glacierClient.InitiateJob(initiateJobRequest);
```
The problem is that initiateJobResult receives error message "Required parameter missing: type".
I do call jobParameters.SetType("inventory-retrieval"); but I am not sure that this error is refering to that parameter. 

I have no problem calling ListVaults and ListJobs so my credentials do work.

I'm am using Visual studio 2015 and just downloaded the SDK via NuGet (AWSSDKCPP-Glacier 1.0.20120601.103 and dependencies)

Any help is appreciated!

**Comment by JonathanHenson** [comment]
can you send me a trace log output?

**Comment by Floaf** [comment]
Thanks, fast response :-)

If I use:
````
Aws::Utils::Logging::InitializeAWSLogging(
	Aws::MakeShared<Aws::Utils::Logging::DefaultLogSystem>(
		"RunUnitTests", Aws::Utils::Logging::LogLevel::Trace, "aws_sdk_"));
````
I get:
[aws_sdk_2017-04-17-20.txt](https://github.com/aws/aws-sdk-cpp/files/926353/aws_sdk_2017-04-17-20.txt)

I don't se any payload data there at all.

**Comment by JonathanHenson** [comment]
Hmmmm.... their api description file does not match their documentation. Let me check with the glacier team and see what is going on.

**Comment by JonathanHenson** [comment]
hmmm.... I wonder if this is broken for everyone. Have you been able to make this work with the other SDKs?

**Comment by Floaf** [comment]
No, I have only tried it with Glacier. 
It feels like the payload data from JobParameters is not added to the POST call or something.

Maybe there is some kind of function call to "compile" the final payload data or something?

**Comment by JonathanHenson** [comment]
It is, what isn't happening is the flattening of the object into the request. 

We serialize it as { job-parameters : {...} } It should be { <the parameters here>}. 

Unfortunately, we don't even have this documented internally. I'll get a fix out asap (probably today).

**Comment by Floaf** [comment]
That is appreciated, thanks!

I'm I the first one using this SDK? :-)

**Comment by JonathanHenson** [comment]
The first one using the CPP SDK to call InitiateJob on Glacier... yes. 

I've made the change to our generator, it is now working its way through our CI and will be out shortly.

**Comment by JonathanHenson** [comment]
The change has been pushed out now. Let me know if you have any more trouble.

**Comment by Floaf** [comment]
Just updated the SDK and it works perfectly!

Thanks for your help.
