### ISSUE TITLE
Direct Disk IO for s3 download

### ISSUE THREAD

**Issue by shuzhang1989** [aws/aws-sdk-cpp#502]
Hi - 

do we support direct disk IO for data downloading from s3 in the S3Client? 
We want to download some big data from s3, and don't want them to stream through memory during download.

**Comment by JonathanHenson** [comment]
see GetObjectRequest::SetOutputStreamFactory()

https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/include/aws/core/AmazonWebServiceRequest.h#L80


You just pass a std:;function that returns a new Instance of std::iostream. So, something like

GetObjectRequest getObjectReq;
getObjectReq.SetOutputStreamFactory([]() { return new Aws::FStream("filename", std::ios_base::out | std::ios_base::binary); });

**Comment by shuzhang1989** [comment]
Yes, this is how we set it up:
`if (local_path != "") {
    getObjectRequest.SetResponseStreamFactory(
      [=]() {
        // "T" is just a place holder for ALLOCATION_TAG.
        return Aws::New<Aws::FStream>(
                "T", local_path.c_str(),
                std::ios_base::out | std::ios_base::in | std::ios_base::trunc);
      }
    );
  }`
we didn't set std::ios_base::binary though.

Using it, we still see huge page out during download, so we assume the content still stream into buffer. is there possibility to let the content stream into disk directly?

**Comment by JonathanHenson** [comment]
It's going to do whatever std::fstream does. Can you send me some metrics? If the performance of fstream is that bad, I'm going to rewrite this. The whole point of using iostream was based on the assumption that the stdlib would do sane things. I'd rather just have a callback spewing bytes back to you.

My guess is because we aren't calling flush after each write?

**Comment by JonathanHenson** [comment]
Alternatively, we could write a more performant implementation of fstream.

**Comment by JonathanHenson** [comment]
also what compiler tool chain are you using?

**Comment by shuzhang1989** [comment]
thanks, we observe the page out metrics when doing data downloading, it spikes to around 100x given our data size and memory size (we are memory bound, and we don't want downloading data to use memory).

I am not sure whether we can achieve direct io at aws sdk level. the idea is to achieve something like https://github.com/facebook/rocksdb/wiki/Direct-IO

we are using gcc5 for building the binaries. didn't write customized memory management for aws sdk.

**Comment by JonathanHenson** [comment]
For starters, you can provide any std::iostream implementation you want in that factory fn (that's the whole point).

Another option is for you to use transfer manager, which will honor your memory constraints (that's a key design tenant), and it also forces a flush after each chunk is downloading. I suspect the problem is the write cache implementation for your OS.

**Comment by shuzhang1989** [comment]
@JonathanHenson sounds good. We actually found the spike is during other operations. if s3 client's streaming factory that really become a performance penalty, we will try your suggestion definitely, thanks!

**Comment by shuzhang1989** [comment]
@JonathanHenson our idea is to integrate O_DIRECT with the fstream if possible.

**Comment by JonathanHenson** [comment]
No, you can just write your own implementation of fstream, using O_DIRECT.

**Comment by shuzhang1989** [comment]
sure, we did in that way and works, thanks!

**Comment by qqwangxiaow** [comment]
> sure, we did in that way and works, thanks!

Can you share the relevant implementation? We are also encountering this issue

**Comment by chasingegg** [comment]
@shuzhang1989 @qqwangxiaow  do you guys solve the issue, can you share the way to do direct io? thanks!

**Comment by qqwangxiaow** [comment]
> [@shuzhang1989](https://github.com/shuzhang1989) [@qqwangxiaow](https://github.com/qqwangxiaow) do you guys solve the issue, can you share the way to do direct io? thanks!
Download to your own buffer, then write to the file using direct I/O. You can refer to the implementation in Doris.
