### ISSUE TITLE
Getting S3 request IDs from SDK?

### ISSUE THREAD

**Issue by asylvest** [aws/aws-sdk-cpp#503]
Is it possible to get the S3 request id after doing, for example, a put object command?  I don't see this anywhere in the PutObjectResult unless I'm just missing it (but I see the ability to do something similar in the Java SDK).  I know I can turn logging on to get this but I don't want the overhead of logging... for the rare occasions when some S3 flakiness occurs, Amazon support usually asks for the request ids so I'd like to add that to my error message when it happens.  I was hoping it would be right in the PutObjectResult.

Thanks.

**Comment by JonathanHenson** [comment]
We don't put it into the PutObjectResult at the moment. 

However... AWSError has all of the headers from the response it which contains the request id.

**Comment by JonathanHenson** [comment]
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/include/aws/core/client/AWSError.h#L84

**Comment by asylvest** [comment]
Oh - ok perfect.  I will grab them from there for the time being.
