### ISSUE TITLE
How do I build this for Apple's iOS?

### ISSUE THREAD

**Issue by jace-bevo** [aws/aws-sdk-cpp#504]
I want to build this SDK for the iOS.  Since the 'TARGET_ARCH' only has 'Apple', how do I tell it to build for iOS?  Or I just set up the CXX path to use the ARM compiler?

**Comment by jace-bevo** [comment]
How do I tell cmake to user specified library path, i.e. OpenSSL, libcur, and zlib libraries I built for iOS, since the ones on the system will definitely not work for ARM architecture.

**Comment by JonathanHenson** [comment]
You never need OpenSSL or ZLib on iOS. 

To tell the build to use a custom path you can use CMAKE_PREFIX_PATH. 

Also, you're more than welcome to these:
http://sdk.amazonaws.com/cpp/builds/?prefix=cpp/builds/1.0.99/

and these:
http://sdk.amazonaws.com/cpp/builds/?prefix=cpp/builds/apple_mobile_libcurl/

**Comment by jace-bevo** [comment]
Thanks for your answer Jon.  I check the dynamic libraries generated for MacOS and it has reference to /usr/lib/libcurl.4.dylib but no references to OpenSSL or Zlib.  Does this mean the SDK only dependency of libcurl?

**Comment by JonathanHenson** [comment]
on apple we only have a dependency on libcurl.

**Comment by jace-bevo** [comment]
Jon
To build on iOS, I set the CC and CXX as the following: 
  export CC="$(xcrun -sdk iphoneos --find clang) -arch arm64"
  export CXX="$(xcrun -sdk $iphoneos --find clang++) -arch arm64"
When I run cmake as 
**/Applications/CMake.app/Contents/bin/cmake -Wno-dev -DBUILD_ONLY=s3;s3-encryption -DSTATIC_LINKING=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-O3 -DTARGET_ARCH=Apple -DCMAKE_INSTALL_PREFIX=/Workspace/AWS/CppSDK/1.0.101/iPhoneOS/arm64/Release /Workspace/AWS/CppSDK/aws-sdk-cpp-1.0.101**

I get the following error.  It seems the SDK is trying to build an executable for the iOS (for testing?)
Apparently this will not work since an ARM executable can only run on a real iOS device (not even an simulator because the code is compiled for ARM, not x84_64)
Can you tell me what was the 'cmake' command invoked to compile for iOS?

====== Error messages ========
-- Found Git: /usr/bin/git (found version "2.11.0 (Apple Git-81)") 
-- Building AWS libraries as static objects
fatal: Not a git repository (or any parent up to mount point /Volumes/Workspace)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Building project version: 1.0.101
-- The CXX compiler identification is AppleClang 8.1.0.8020041
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- broken
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.8/Modules/CMakeTestCXXCompiler.cmake:44 (message):
  The C++ compiler
  "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++"
  is not able to compile a simple test program.

  It fails with the following output:
   Change Dir: /Workspace/AWS/CppSDK/1.0.101/iPhoneOS/arm64/Build/Release/CMakeFiles/CMakeTmp
  Run Build Command:"/usr/bin/make" "cmTC_547b9/fast"

  /Applications/Xcode.app/Contents/Developer/usr/bin/make -f
  CMakeFiles/cmTC_547b9.dir/build.make CMakeFiles/cmTC_547b9.dir/build

  Building CXX object CMakeFiles/cmTC_547b9.dir/testCXXCompiler.cxx.o
 
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
  -arch arm64 -O3 -isysroot
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
  -o CMakeFiles/cmTC_547b9.dir/testCXXCompiler.cxx.o -c
  /Workspace/AWS/CppSDK/1.0.101/iPhoneOS/arm64/Build/Release/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
  Linking CXX executable cmTC_547b9

  /Applications/CMake.app/Contents/bin/cmake -E cmake_link_script
  CMakeFiles/cmTC_547b9.dir/link.txt --verbose=1
  **/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
  -arch arm64 -O3 -isysroot
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
  -Wl,-search_paths_first -Wl,-headerpad_max_install_names
  CMakeFiles/cmTC_547b9.dir/testCXXCompiler.cxx.o -o cmTC_547b9

  ld: warning: ignoring file
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.1.0/lib/darwin/libclang_rt.osx.a,
  missing required architecture arm64 in file
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.1.0/lib/darwin/libclang_rt.osx.a
  (3 slices)

  ld: warning: ignoring file
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib/libSystem.tbd,
  missing required architecture arm64 in file
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib/libSystem.tbd
  (2 slices)

  ld: warning: ignoring file
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib/libc++.tbd,
  missing required architecture arm64 in file
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib/libc++.tbd
  (2 slices)

  ld: dynamic main executables must link with libSystem.dylib for
  architecture arm64

  clang: error: linker command failed with exit code 1 (use -v to see
  invocation)**

  make[1]: *** [cmTC_547b9] Error 1

  make: *** [cmTC_547b9/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:99 (project)

**Comment by jace-bevo** [comment]
I found some answers from issue #340 and made some progress.  Now I am able to compile the library but it still fails at link time because it cannot find the iOS version of libcurl.
How to I tell it to look for libcurl at a particular path?

**The command line invocation of cmake is**

/CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64, CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64
/Applications/CMake.app/Contents/bin/cmake -Wno-dev -DBUILD_ONLY=s3;s3-encryption -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_SYSTEM_NAME=Darwin -DCMAKE_SHARED_LINKER_FLAGS=-framework Foundation -framework Security -DCMAKE_EXE_LINKER_FLAGS=-framework Foundation -framework Security -DCMAKE_PREFIX_PATH=/Volumes/Workspace/Prebuilt/Release-iphoneos/libcurl -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-O3 -DCMAKE_INSTALL_PREFIX=/Volumes/Workspace/AWS/CppSDK/1.0.101/iPhoneOS/arm64/Release -DBUILD_SHARED_LIBS=off -DCPP_STANDARD=14 -DCURL_INCLUDE_DIR=/Volumes/Workspace/Prebuilt/Release-iphoneos/libcurl/include64 -DCURL_LIBRARIES=libcurl_draco -DSTATIC_LINKING=1 -DTARGET_ARCH=Apple /Volumes/Workspace/AWS/CppSDK/aws-sdk-cpp-1.0.101

But CMake does not seem to be finding curl library

-- Found Git: /usr/bin/git (found version "2.11.0 (Apple Git-81)")
-- Building AWS libraries as static objects
fatal: Not a git repository (or any parent up to mount point /Volumes/Workspace)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Building project version: 1.0.101
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.8")
--   Zlib include directory: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include
--   Zlib library: /usr/lib/libz.dylib
-- Encryption: CommonCrypto
-- Http client: Curl
-- Found CURL: /usr/lib/libcurl.dylib (found version "7.51.0")
--   Curl include directory: /Volumes/Workspace/Prebuilt/Release-iphoneos/libcurl/include64
**--   Curl library: /usr/lib/libcurl.dylib**
-- Considering s3
-- Considering s3-encryption


The error I get is

[ 92%] Linking CXX executable aws-cpp-sdk-s3-integration-tests
ld: warning: ignoring file /usr/lib/libcurl.dylib, missing required architecture arm64 in file /usr/lib/libcurl.dylib (2 slices)
Undefined symbols for architecture arm64:
  "_curl_easy_cleanup", referenced from:
      Aws::Http::CurlHandleContainer::~CurlHandleContainer() in libaws-cpp-sdk-core.a(CurlHandleContainer.cpp.o)
  "_curl_easy_getinfo", referenced from:
      Aws::Http::CurlHttpClient::MakeRequest(Aws::Http::HttpRequest&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_easy_init", referenced from:
      Aws::Http::CurlHandleContainer::CheckAndGrowPool() in libaws-cpp-sdk-core.a(CurlHandleContainer.cpp.o)
  "_curl_easy_perform", referenced from:
      Aws::Http::CurlHttpClient::MakeRequest(Aws::Http::HttpRequest&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_easy_reset", referenced from:
      Aws::Http::CurlHandleContainer::ReleaseCurlHandle(void*) in libaws-cpp-sdk-core.a(CurlHandleContainer.cpp.o)
  "_curl_easy_setopt", referenced from:
      SetOptCodeForHttpMethod(void*, Aws::Http::HttpRequest const&) in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
      Aws::Http::CurlHttpClient::MakeRequest(Aws::Http::HttpRequest&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
      Aws::Http::CurlHandleContainer::CheckAndGrowPool() in libaws-cpp-sdk-core.a(CurlHandleContainer.cpp.o)
      Aws::Http::CurlHandleContainer::ReleaseCurlHandle(void*) in libaws-cpp-sdk-core.a(CurlHandleContainer.cpp.o)
      Aws::Http::CurlHandleContainer::SetDefaultOptionsOnHandle(void*) in libaws-cpp-sdk-core.a(CurlHandleContainer.cpp.o)
  "_curl_global_cleanup", referenced from:
      Aws::Http::CurlHttpClient::CleanupGlobalState() in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_global_init", referenced from:
      Aws::Http::CurlHttpClient::InitGlobalState() in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_slist_append", referenced from:
      Aws::Http::CurlHttpClient::MakeRequest(Aws::Http::HttpRequest&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
  "_curl_slist_free_all", referenced from:
      Aws::Http::CurlHttpClient::MakeRequest(Aws::Http::HttpRequest&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const in libaws-cpp-sdk-core.a(CurlHttpClient.cpp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [aws-cpp-sdk-s3-integration-tests/aws-cpp-sdk-s3-integration-tests] Error 1
make[1]: *** [aws-cpp-sdk-s3-integration-tests/CMakeFiles/aws-cpp-sdk-s3-integration-tests.dir/all] Error 2
make: *** [all] Error 2

**Comment by triton3** [comment]
I created the following script that works for me. You can try it and see if it helps.
This script currently builds for armv7, armv7s, and arm64, assuming libcurl is built from source for these architectures. I haven't been able to build for i386, x86_64 yet though.

See the readme part, since some parameters will need to be configured as per requirement. I provided a link to a github project for building libcurl for iOS. If you want to use the pre-built libcurl arm64 binary that Jon provided, you will need to disable bitcode flag, and comment out build for armv7 and armv7s (see readme).

	#!/bin/bash
    
    # Based on build scripts from the following:
    # https://github.com/aws/aws-sdk-cpp/issues/340 
    # https://github.com/mologie/libtomcrypt-ios
    # http://stackoverflow.com/a/27161949/5148626
    
    # ------------------------------
    #           README FIRST
    # ------------------------------
    #           DEPENDENCY
    # - Need to build libcurl for iOS
    # -- see project: https://github.com/gcesarmza/curl-android-ios
    # -- Update to latest release of curl if necessary (run git clone https://github.com/curl/curl.git from inside this project)
    # -- Before running the build script located in "curl-compile-scripts/build_iOS.h",
    #    - Go to line containing .configure command
    #      - add option "--without-zlib" to .configure command,
    #      - make sure it has option "--with-darwinssl",
    #      - and then run the build script
    #
    # ------------------------------
    # Create DIR structure as follows
    # ------------------------------
    #
    #  Workspace_dir    // name this whatever you like
    #  |
    #   -- aws-sdk-cpp  // Source dir
    #  |
    #   -- build
    #  |   |
    #  |    -- build.sh
    #  |
    #  |-- buildOutput      // Automatically created. Will contain output
    #  |
    #  |-- aggregatedOutput // Automatically created. Will contain aggregated output (if last line is un-commented)
    #  |
    #   -- libcurl
    #      |
    #       -- lib/libcurl.a      // Note: This should contain a fatlib to support building arm64, armv7, armv7s
    #      |
    #       -- include/..         // libcurl headers
    #
    # ------------------------------
    # Usage: Once libcurl is built/available,
    #        1. Update following parameters in the script below as required:
    #           - WORKSPACE - path to "Workspace_dir" mentioned above
    #           - SDK_VERSION - Currently Set to 10.3
    #           - MIN_VERSION - Currently Set to 10.0
    #           - AWS cmake arguments as necessary in build_AWSRelease_bitcode() function.
    #             Note: To disable bitcode, remove "-fembed-bitcode" from CMAKE_CXX_FLAGS
    #
    #           - If you want to aggregate build outputs into a fat lib, see function aggregate_libs()
    #               - Add the necessary libraries in the components array
    #               - uncomment last line: aggregate_libs "${WORKSPACE}/aggregatedOutput"
    #
    #        2. Place the build script in "Workspace_dir/build"
    #
    #        3. Run the following in terminal:
    #               cd Workspace_dir/build
    #               ./build.sh
    #
    # Output should be in Workspace_dir/buildOutput, if everything went well
    # Aggregated lib should be in Workspace_dir/aggregatedOutput, if everything went well
    # ------------------------------
    
    set -x
    
    # SDK Version
    SDK_VERSION="10.3"
    MIN_VERSION="10.0"
    
    # Setup paths
    WORKSPACE="path/to/workspace/dir"
    
    # XCode paths
    DEVELOPER="/Applications/Xcode.app/Contents/Developer"
    IPHONEOS_PLATFORM="${DEVELOPER}/Platforms/iPhoneOS.platform"
    IPHONEOS_SDK="${IPHONEOS_PLATFORM}/Developer/SDKs/iPhoneOS${SDK_VERSION}.sdk"
    
    IPHONESIMULATOR_PLATFORM="${DEVELOPER}/Platforms/iPhoneSimulator.platform"
    IPHONESIMULATOR_SDK="${IPHONESIMULATOR_PLATFORM}/Developer/SDKs/iPhoneSimulator${SDK_VERSION}.sdk"
    
    # Make sure things actually exist
    if [ ! -d "$IPHONEOS_PLATFORM" ]; then
      echo "Cannot find $IPHONEOS_PLATFORM"
      exit 1
    fi
    
    if [ ! -d "$IPHONEOS_SDK" ]; then
      echo "Cannot find $IPHONEOS_SDK"
      exit 1
    fi
    
    
    if [ ! -d "$IPHONESIMULATOR_PLATFORM" ]; then
      echo "Cannot find $IPHONESIMULATOR_PLATFORM"
      exit 1
    fi
    
    if [ ! -d "$IPHONESIMULATOR_SDK" ]; then
      echo "Cannot find $IPHONESIMULATOR_SDK"
      exit 1
    fi
    
    
    pwd=`pwd`
    
    # ----------------------------------
    # To build arm64, armv7, armv7s
    # ----------------------------------
    build_AWSRelease_bitcode()
    {
    	export ARCH=$1
    
        # Build intermediates dir
        mkdir -p $ARCH
        cd $ARCH
    
        # Cleanup
        rm -r ./*
    
    	export SDK=$2
    
        export CC="$(xcrun -sdk iphoneos -find clang)"
        export CPP="$CC -E"
        export CFLAGS="-arch ${ARCH} -isysroot $SDK -miphoneos-version-min=$MIN_VERSION"
        export AR=$(xcrun -sdk iphoneos -find ar)
        export RANLIB=$(xcrun -sdk iphoneos -find ranlib)
        export CPPFLAGS="-arch ${ARCH} -isysroot $SDK -miphoneos-version-min=$MIN_VERSION"
        export LDFLAGS="-arch ${ARCH} -isysroot $SDK"
    
        BUILD_OUTPUT="${WORKSPACE}/buildOutput/${ARCH}"
        mkdir -p $BUILD_OUTPUT
    
        echo $CMAKE_CXX_FLAGS
    
        /Applications/CMake.app/Contents/bin/cmake -Wno-dev \
            -DCMAKE_OSX_SYSROOT=$IPHONEOS_SDK \
            -DCMAKE_OSX_ARCHITECTURES=$ARCH \
            -DCMAKE_SYSTEM_NAME="Darwin" \
            -DCMAKE_SHARED_LINKER_FLAGS="-framework Foundation -lz -framework Security" \
            -DCMAKE_EXE_LINKER_FLAGS="-framework Foundation -framework Security" \
            -DCMAKE_PREFIX_PATH="$WORKSPACE/libcurl/" \
            -DBUILD_SHARED_LIBS=OFF \
            -DCUSTOM_MEMORY_MANAGEMENT=0 \
            -DCMAKE_BUILD_TYPE="Release" \
            -DCMAKE_INSTALL_PREFIX="$BUILD_OUTPUT" \
            -DCMAKE_CXX_FLAGS="-std=c++11 -stdlib=libc++ -fembed-bitcode -miphoneos-version-min=$MIN_VERSION" \
            $WORKSPACE/aws-sdk-cpp
        make -j 8
        make install
    
        # Go back
        cd ..
    }
    
    
    # ----------------------------------
    # To build i386, x86_64 (fails currently)
    # ----------------------------------
    build_AWSRelease_Simulator_bitcode()
    {
        export ARCH=$1
    
        # Build intermediates dir
        mkdir -p $ARCH
        cd $ARCH
    
        # Cleanup
        rm -r ./*
    
        export SDK=$2
    
        export CC="$(xcrun -sdk iphonesimulator -find clang)"
        export CPP="$CC -E"
        export CFLAGS="-arch ${ARCH} -isysroot $SDK -miphoneos-version-min=$MIN_VERSION"
        export AR=$(xcrun -sdk iphonesimulator -find ar)
        export RANLIB=$(xcrun -sdk iphonesimulator -find ranlib)
        export CPPFLAGS="-arch ${ARCH} -isysroot $SDK -miphoneos-version-min=$MIN_VERSION"
        export LDFLAGS="-arch ${ARCH} -isysroot $SDK"
    
        BUILD_OUTPUT="${WORKSPACE}/buildOutput/${ARCH}"
        mkdir -p $BUILD_OUTPUT
    
        echo $CMAKE_CXX_FLAGS
    
        /Applications/CMake.app/Contents/bin/cmake -Wno-dev \
        -DCMAKE_OSX_SYSROOT=$IPHONEOS_SDK \
        -DCMAKE_OSX_ARCHITECTURES=$ARCH \
        -DCMAKE_SYSTEM_NAME="Darwin" \
        -DCMAKE_SHARED_LINKER_FLAGS="-framework Foundation -lz -framework Security" \
        -DCMAKE_EXE_LINKER_FLAGS="-framework Foundation -framework Security" \
        -DCMAKE_PREFIX_PATH="$WORKSPACE/libcurl/" \
        -DBUILD_SHARED_LIBS=OFF \
        -DCUSTOM_MEMORY_MANAGEMENT=0 \
        -DCMAKE_BUILD_TYPE="Release" \
        -DCMAKE_INSTALL_PREFIX="$BUILD_OUTPUT" \
        -DCMAKE_CXX_FLAGS="-std=c++11 -stdlib=libc++ -fembed-bitcode -miphoneos-version-min=$MIN_VERSION" \
        $WORKSPACE/aws-sdk-cpp
        make -j 8
        make install
    
        # Go back
        cd ..
    }
    
    # ---------------------------------------------------
    # Function to aggregate build outputs into a fat lib
    # ---------------------------------------------------
    aggregate_libs() {
        set +x
        AGG_OUTPUT_DIR=$1
        # Aggregate library and include files
        mkdir -p ${AGG_OUTPUT_DIR}/include
        mkdir -p ${AGG_OUTPUT_DIR}/lib
    
        cp -r ${WORKSPACE}/buildOutput/arm64/include/* ${AGG_OUTPUT_DIR}/include/
    
        ## declare an array variable with required aws components
        ## This is an example. Change as required
        declare -a components=( "core"
                                "access-management"
                                "sts"
                                "lambda"
                                "dynamodb"
                                "cognito-identity"
                                "email"
                                )
    
        ## now loop through the above array
        for component in "${components[@]}"
        do
            LIBNAME="libaws-cpp-sdk-${component}.a"
            echo "--------- Aggregating $LIBNAME ---------"
            xcrun -sdk iphoneos lipo \
            "${WORKSPACE}/buildOutput/arm64/lib/${LIBNAME}" \
            "${WORKSPACE}/buildOutput/armv7/lib/${LIBNAME}" \
            "${WORKSPACE}/buildOutput/armv7s/lib/${LIBNAME}" \
            -create -output ${AGG_OUTPUT_DIR}/lib/${LIBNAME}
    
            #"${WORKSPACE}/buildOutput/i386/lib/${LIBNAME}" \
            #"${WORKSPACE}/buildOutput/x86_64/lib/${LIBNAME}" \
    
            # verify arch
            echo "- Running lipo info for $LIBNAME:"
            lipo -info ${AGG_OUTPUT_DIR}/lib/${LIBNAME}
            echo "--------------------------------------------------"
        done
    
        echo "--------------------------------------------------"
        echo "Aggregated output location: ${AGG_OUTPUT_DIR}"
        echo "--------------------------------------------------"
    }
    
    ## Build release configuration
    build_AWSRelease_bitcode "arm64" "${IPHONEOS_SDK}"
    ## Comment the following if not required
    build_AWSRelease_bitcode "armv7" "${IPHONEOS_SDK}"
    build_AWSRelease_bitcode "armv7s" "${IPHONEOS_SDK}"
    
    ## Note: The following do not work currently
    #build_AWSRelease_Simulator_bitcode "i386" "${IPHONESIMULATOR_SDK}"
    #build_AWSRelease_Simulator_bitcode "x86_64" "${IPHONESIMULATOR_SDK}"
    
    ## Aggregate into a fat lib. Argument provided here is the output directory
    ## (OPTIONAL) Uncomment below to create a fat lib
    #aggregate_libs "${WORKSPACE}/aggregatedOutput"

**Comment by jace-bevo** [comment]
Thanks for the information.  Actually I have finally gotten it working last week.
My script looks very much like yours and I have it working for both armv7, arrm64 (iOS)), i386 and x86_64 (iPhoneSimulator).  This is a snippet of the script.  It does require linking with OpenSSL because the static libcurl library we built for iOS was linked with it.  Now I just need to combine them into a fat binary.

================
                     case $arch in
                                armv7)
                                        platform=iPhoneOS
                                        ;;
                                arm64)
                                        platform=iPhoneOS
                                        ;;
                                i386 )
                                        platform=iPhoneSimulator
                                        ;;
                                x86_64)
                                        platform=iPhoneSimulator
                                        ;;
                        esac

local ios_sdk=$(echo $platform | tr "[:upper:]" "[:lower:]")
local sysroot=$(xcrun --sdk $ios_sdk --show-sdk-path)

/Applications/CMake.app/Contents/bin/cmake -Wno-dev -DBUILD_ONLY=ss3;ss3-encryption     \
                -DCMAKE_OSX_SYSROOT=$sysroot                                                    \
                -DCMAKE_OSX_ARCHITECTURES=$arch                                                 \
                -DCMAKE_SYSTEM_NAME=$(uname)                                                    \
                 -DCMAKE_PREFIX_PATH="$HOME/Prebuilt/Release-iphoneos"         \
                 -DCMAKE_SHARED_LINKER_FLAGS="-framework Foundation -framework Security -L$prebuiltSource/${config}-iphoneos/lib -lssl -lcrypto -lcurl -lz"              \
                 -DCMAKE_EXE_LINKER_FLAGS="-framework Foundation -framework Security -L$HOME/Prebuilt/Release-iphoneos/lib -lssl -lcrypto -lcurl -lz" \
                  -DCMAKE_BUILD_TYPE=Release    \
                  -DCMAKE_CXX_FLAGS="-O3"    \
                   -DCMAKE_INSTALL_PREFIX=$HOME/aws-sdk-cpp-1.0.101/iPhone/Release   \
                   -DBUILD_SHARED_LIBS=no      \
                   -DCPP_STANDARD=14       \
                   -DCURL_INCLUDE_DIR=$HOME/Prebuilt/Release-iphoneos/include     \
                   -DSTATIC_LINKING=1   \
                   -DTARGET_ARCH=Apple  

num_cpu=$(sysctl -n hw.ncpu)
VERBOSE=1 make -j $num_cpu

**Comment by luisgrimaldo** [comment]
How can we get this work for the iPhone simulator? It seems like the third party dependencies aren't building correctly

**Comment by mohammadjalalis** [comment]
> 
Hi,
Unfortunately this script doesn't work for me and error is : 

` [93%] Linking CXX executable aws-cpp-sdk-core-tests
Undefined symbols for architecture arm64:
  "___aarch64_ldadd8_acq_rel", referenced from:
      _aws_ecc_key_pair_acquire in libaws-c-cal.a(ecc.c.o)
      _aws_ecc_key_pair_release in libaws-c-cal.a(ecc.c.o)
      _aws_credentials_new in libaws-c-auth.a(credentials.c.o)
      _aws_credentials_release in libaws-c-auth.a(credentials.c.o)
      _aws_credentials_acquire in libaws-c-auth.a(credentials.c.o)
      _aws_credentials_provider_release in libaws-c-auth.a(credentials.c.o)
      _aws_credentials_provider_acquire in libaws-c-auth.a(credentials.c.o)
      ...
  "___aarch64_ldadd8_relax", referenced from:
      _aws_retry_strategy_acquire in libaws-c-io.a(retry_strategy.c.o)
      _aws_retry_token_acquire in libaws-c-io.a(retry_strategy.c.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 1
make[1]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 94%] Linking CXX static library libaws-cpp-sdk-kms.a
[ 94%] Built target aws-cpp-sdk-kms`

**Comment by mohammadjalalis** [comment]
I found it.
[Fix iOS build error due to -moutline-atomics](https://github.com/awslabs/aws-c-common/pull/909/commits/15f9ef7dd5a02ba8f5752b2abeb8d45b29fe608e)
