### ISSUE TITLE
endpointOverride usage

### ISSUE THREAD

**Issue by volkancetinvcount** [aws/aws-sdk-cpp#505]
I am using s3-eu-west-1.amazonaws.com as endpoint. However my network sometimes cannot resolve the url beacause of the DNS issues. So I pinged the s3-eu-west-1.amazonaws.com and got it IP address which is: 52.218.48.36. Then I changed my configuration as:

Aws::Client::ClientConfiguration clientConfig;
clientConfig.scheme = Aws::Http::Scheme::HTTP;
clientConfig.region = Aws::Region::EU_WEST_1;
clientConfig.connectTimeoutMs = 10000;
clientConfig.requestTimeoutMs = 3000000;	
clientConfig.endpointOverride = "52.218.48.36"; //it works when it is "s3-eu-west-1.amazonaws.com"
clientConfig.verifySSL = false;

However, I cannot upload files to bucket. What am I doing wrong? Any suggestions?

**Comment by JonathanHenson** [comment]
For one, I would recommend against not using DNS for S3. S3 does load balancing dynamically across VIPS and depends on dns to do so.

As for what is wrong with your code, I'd need more details. Do you have a log file I can see?

**Comment by volkancetinvcount** [comment]
[INFO] 2017-04-25 11:03:19 CurlHttpClient [1793061472] Initializing Curl library
[INFO] 2017-04-25 11:03:19 CurlHandleContainer [1793061472] Initializing CurlHandleContainer with size 25
[INFO] 2017-04-25 11:03:19 CurlHandleContainer [1793061472] Pool successfully grown by 2
[INFO] 2017-04-25 11:03:19 CurlHandleContainer [1793061472] Connection has been released. Continuing.
[INFO] 2017-04-25 11:03:19 CurlHandleContainer [1574568544] Connection has been released. Continuing.
[WARN] 2017-04-25 11:03:19 AWSErrorMarshaller [1574568544] Encountered Unknown AWSError
PermanentRedirect
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.:
__

By the way I can list folders under my bucket using IPv4 instead of url, however I cannot upload files.

**Comment by singku** [comment]
Hello, have you figured out the problem?

**Comment by volkancetinvcount** [comment]
I added aws ip to /etc/hosts as:
52.218.48.36   s3-eu-west-1.amazonaws.com

**Comment by singku** [comment]
I remember we have fixed the http redirect problem. You can update sdk and try thay again.
