### ISSUE TITLE
Problem uploading file to glacier

### ISSUE THREAD

**Issue by Floaf** [aws/aws-sdk-cpp#508]
I found this part in the documentation:
"If you are using an AWS SDK to program against Amazon Glacier, the tree hash calculation is done for you and you only need to provide the file reference. " so I was hoping to find a help class somewhere in the source code that you internally use, but I cannot find any. 

Is there an existing method/function for it or should i write my own?

**Comment by Floaf** [comment]
After further investigating the source code I still did not find any tree hashing algorithm so i ended writing my own (based on your C# example). 
Now i have another problem, I get some kind of timeout when I try to upload a file.

````
std::shared_ptr<Aws::FStream> fileStream(new Aws::FStream("ThisIsMyTestFile.txt", std::ios_base::in));

Aws::Glacier::Model::UploadArchiveRequest uploadArchiveRequest;
uploadArchiveRequest.SetAccountId("-");
uploadArchiveRequest.SetVaultName("Backup2");
uploadArchiveRequest.SetArchiveDescription("This is a test description");
uploadArchiveRequest.SetBody(fileStream);

auto uploadArchiveResult = glacierClient.UploadArchive(uploadArchiveRequest);
````
This is the log from the call:

[aws_sdk_2017-04-23-12.txt](https://github.com/aws/aws-sdk-cpp/files/949631/aws_sdk_2017-04-23-12.txt)

1. It seem to trigger some kind of 4 second timeout and then retrying to send but with the same result. 
2. It does not look like it is calculation and adding a tree hash for me (if I add it manually it is sent in the request though)

Am I missing something here?

**Comment by JonathanHenson** [comment]
You can use 

UploadArchiveRequest::SetChecksum

With:

https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/include/aws/core/utils/HashingUtils.h#L68

**Comment by Floaf** [comment]
If you are refering to Aws::Utils::HashingUtils::CalculateSHA256(), that method do not seem to calculate a tree hash. It calculate a regular sha256 hash of the whole file.

**Comment by Floaf** [comment]
This bug is still here :-(
Just to recap, when I try to upload a file to glacier, I get connection timeout all the time.

This is the logfile:
[aws_sdk_2017-07-30-13.txt](https://github.com/aws/aws-sdk-cpp/files/1185662/aws_sdk_2017-07-30-13.txt)

The error is on row 57: [WARN] 2017-07-30 13:37:56 WinHttpSyncHttpClient [540664] Send request failed: Åtgärden tog för lång tid

**Comment by singku** [comment]
We currently do not have Sha256 Tree Hash implementation for Glacier, added it to our backlog and will implement it soon.
Bye the way, based on the warn message,  it took too long to send the request, I am not sure it's the missing tree hashing or the file size is too large. What's the file size you uploaded?

**Comment by singku** [comment]
Hi I saw that from you log the tree-hash header field has been set. But that field need to be set up explicitly from user side by call WithCheckSum(). Whereas I didn't see that part of code from you example code above. Where did you set that checksum?

**Comment by Floaf** [comment]
I wrote my own tree hash calculator based on your C# example and i verified the result against the hash calculated by another client (Fast glacier) so I am pretty sure the tree hash is correct. Ether way, wouldn't an incorrect hash produce some other kind of error than a timeout?

The file i am trying to upload is 5 565 334 bytes large (5.3 MB) so it shouldn't be to big.

Sorry for not update the code example, this is what I am trying with right now:


	Aws::FStream file = Aws::FStream("ThisIsMyTestFile.txt", std::ios_base::in | std::ios_base::binary);
	auto hashBuffer = MyTreeHash::ComputeSHA256TreeHash(file); // This is my version of the tree hash calculator
	Aws::String hashString = Aws::Utils::HashingUtils::HexEncode(hashBuffer);

	std::shared_ptr<Aws::FStream> fileStream(new Aws::FStream("ThisIsMyTestFile.txt", std::ios_base::in));

	Aws::Glacier::Model::UploadArchiveRequest uploadArchiveRequest;
	uploadArchiveRequest.SetAccountId("-");
	uploadArchiveRequest.SetVaultName("Backup2");
	uploadArchiveRequest.SetChecksum(hashString);
	uploadArchiveRequest.SetArchiveDescription("This is a test description");
	uploadArchiveRequest.SetBody(fileStream);

	auto uploadArchiveResult = glacierClient.UploadArchive(uploadArchiveRequest);

**Comment by Floaf** [comment]
Gah, I found the problem.

If I open the file with std::ios_base::binary too, it works.

It should be: 
`std::shared_ptr<Aws::FStream> fileStream(new Aws::FStream("ThisIsMyTestFile.txt", std::ios_base::in | std::ios_base::binary));`

Not helping that I got a socket timeout as error message :-)
