### ISSUE TITLE
aws-sdk-ios

### ISSUE THREAD

**Issue by jace-bevo** [aws/aws-sdk-cpp#512]
There is an AWS SDK for iOS at https://github.com/aws/aws-sdk-ios and https://aws.amazon.com/mobile/sdk/.
It seems to offer similar API as aws-sdk-cpp.  What is the difference between the two SDK.
Are the two in sync?

**Comment by JonathanHenson** [comment]
They are managed differently, but the C++ SDK is inherently cross-platform. So you only need to write your code once and you can build it for most platforms. For example, you could write the same exact code for Windows, Linux, Android, iOS, and OSX without any changes to the code.

The ios SDK is targeted at Apple platforms, and is an objective-c interface.

It all depends on your use-case.

**Comment by jace-bevo** [comment]
Thanks for the information
