### ISSUE TITLE
AWSProfileConfigLoader.h is not getting installed 

### ISSUE THREAD

**Issue by slseed1969** [aws/aws-sdk-cpp#514]
It appears as if the header file /usr/include/aws/core/config/AWSProfileConfigLoader.h in not getting installed. If this is not intentional, then it may be traced back to fact that aws-cpp-sdk-core/CMakeLists.txt is missing an entry to install the header:

install (FILES ${CONFIG_HEADERS} DESTINATION ${INCLUDE_DIRECTORY}

**Comment by JonathanHenson** [comment]
Thanks for reporting this!

**Comment by singku** [comment]
Should be pushed out shortly after merging of https://github.com/awslabs/aws-sdk-cpp-staging/pull/90
