### ISSUE TITLE
Visual Studio Test Example using Nuget with AWS SDK does not link

### ISSUE THREAD

**Issue by genifycom** [aws/aws-sdk-cpp#517]
I worked though the example at https://aws.amazon.com/blogs/developer/aws-sdk-for-c-now-available-via-nuget/

Brought in Nuget as per this document, Core is now v1.0.108, S3 is now 1.0.20060301.108

Just tried this main:

#include "stdafx.h"
#include <iostream>
#include <aws/s3/model/PutObjectRequest.h>
#include <aws/s3/S3Client.h>
#include <aws/core/Aws.h>

int main()
{
	Aws::SDKOptions options;
	Aws::InitAPI(options);
	Aws::ShutdownAPI(options);
    return 0;
}

Linker is unable to resolve InitAPI and ShutdownAPI

I understood from this document that the linker should already be set up to resolve to the dynamic libs?

What is wrong here?
P.S. I tried adding the preprocessor symbol USE_IMPORT_EXPORT

Thanks,
Dave

**Comment by singku** [comment]
Do you have the dependent dlls inside you build directory? (aws-cpp-sdk-core.dll aws-cpp-sdk-s3.dll)

**Comment by JonathanHenson** [comment]
could you send us a zipped up solution to have a look at?

**Comment by singku** [comment]
No longer valid
