### ISSUE TITLE
How to pass credentials explicitly to SQSClient

### ISSUE THREAD

**Issue by genifycom** [aws/aws-sdk-cpp#518]
So there is this example in the C++ PDF

auto client = Aws::MakeShared<DynamoDBClient>(ALLOCATION_TAG, AWSCredentials("access_key_id", "secret_key"), config);

I was looking to do the same for SQS:

Aws::SQS::SQSClient sqs1(Aws::Auth::AWSCredentials("access_key_id", "secret_key"), config);

but the compiler complains "Incomplete type is not allowed".

The ctor is satisfied for SQSClient.

What is wrong here?

Thanks,
Dave

**Comment by genifycom** [comment]
Ok looks like it must be a shared pointer. So the answer appears to be

auto auth = Aws::MakeShared<Aws::Auth::SimpleAWSCredentialsProvider>(aws_secret_key, aws_secret_key);
Aws::Client::ClientConfiguration client_cfg;
Aws::SQS::SQSClient sqs(auth, client_cfg);

Could the documentation be updated please.

**Comment by JonathanHenson** [comment]
your original code looks fine. "incomplete type" usually means you are missing a header file. AWSCredentials is forward declared in SQSClient.h

Are you including aws/core/auth/AWSCredentialsProvider.h when you compile your original sample?

**Comment by genifycom** [comment]
Thank you so much for responding. You are correct, I was missing this header.
