### ISSUE TITLE
Unable to build AWS C++ SDK

### ISSUE THREAD

**Issue by aricop** [aws/aws-sdk-cpp#521]
I am not able to build AWS SDK for C++, i followed these instruccions: 
https://github.com/aws/aws-sdk-cpp/blob/master/README.md.
and i have a problem with commando cmake.

I want to work with Amazon s3, so inside the SDK i work in this route: 
     aws-sdk-cpp-master/aws-cpp-sdk-s3.
Inside this directory i have created a build directory so i have that: 
     build CMakeLists.txt include nuget source

Now inside “build” i try “cmake ..” command and then i got the message error:

	CMake Error at CMakeLists.txt:68 (setup_install):
	Unknown CMake command "setup_install".

	-- Configuring incomplete, errors occurred

the software used:
	Ubuntu 16.04.2 LTS
	cmake version 3.5.1
	gcc version 5.4.0

i don't have experience with cmake so i don’t know why occur this problem, what can i do?

Thanks for help!!

**Comment by Bu11etmagnet** [comment]
You didn't post the full output from cmake, so we have no chance to identify the problem.

My psychic powers suggest that you're missing either g++, or the development libraries for zlib, openssl or libcurl.

**Comment by singku** [comment]
CMakeLists.txt inside aws-cpp-sdk-s3 is part of the entire build process. We need to setup the environment by running CMakeList.txt in the main directory. So create a build dir inside the main directory, go in there and run cmake .. make, make install. If you just want to build s3 only, you need set up cmake option by change line 53 of CMakeList.txt in main directory to "SET(BUILD_ONLY "s3" CACHE STRING "....")"

**Comment by bretambrose** [comment]
You don't need to change CMakeList.txt in order to build a subset of services; you can just specify BUILD_ONLY on the cmake command line ala:

cmake -DBUILD_ONLY=s3 ..

**Comment by singku** [comment]
Yes, as Bret mentioned, specify from command line is a better option. Once set up from command line, BUILD_ONLY exists in cache, line 55 will read from cache and get the desired value.

**Comment by aricop** [comment]
I followed instructions of “singku”, created a buil dir in the main directory and inside directory ran “cmake -DBUILD_ONLY=s3 ..” but i got other error message:

-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating linux build config
fatal: Not a git repository (or any of the parent directories): .git
-- Building project version: 1.0.107
--   Zlib include directory: /usr/include
--   Zlib library: /usr/lib/x86_64-linux-gnu/libz.so
-- Encryption: Openssl
--   Openssl include directory: /usr/include
--   Openssl library: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Http client: Curl
--   Curl include directory: /usr/include
--   Curl library: /usr/lib/x86_64-linux-gnu/libcurl.so
-- Considering s3
-- Updating version info to 1.0.107
-- Custom memory management enabled; stl objects now using custom allocators
CMake Error at cmake/dependencies.cmake:15 (get_property):
  get_property could not find TARGET aws-cpp-sdk-s3.  Perhaps it has not yet
  been created.
Call Stack (most recent call first):
  cmake/dependencies.cmake:59 (compute_links)
  cmake/sdks.cmake:413 (sort_links)
  CMakeLists.txt:142 (add_sdks)


CMake Warning (dev) at cmake/dependencies.cmake:70 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target "aws-cpp-sdk-s3".
Call Stack (most recent call first):
  cmake/sdks.cmake:413 (sort_links)
  CMakeLists.txt:142 (add_sdks)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/ricop/aws-sdk-cpp-master/build/CMakeFiles/CMakeOutput.log".

**Comment by singku** [comment]
@aricop Could you update to the latest version and try again?

**Comment by aricop** [comment]
I updated to the latest version, the current version of cmake is 3.8.0.
But I got the same error message

**Comment by singku** [comment]
@aricop I mean update the SDK to the latest version. It seems your current version is 1.0.107, the latest is 1.0.117. My guess is that you ran CMake before and some variables have been cached.
So update to the latest SDK version, clear the build directory start a clean build

If error still exist:
The error came out of undefined target aws-cpp-sdk-s3, which should be created by macro call add_sdks in line 170 of CMakeLists.txt. Could you debug a little yourself by simply printing message using format:
`Message(STATUS "something or some ${var}")`
show content of variable BUILD_ONLY, SDK_BUILD_LIST after line 170.

**Comment by aricop** [comment]
it worked, thank you very much for all
