### ISSUE TITLE
Getting linker error for S3 Client GeneratePresignedUrl

### ISSUE THREAD

**Issue by MyCADDev** [aws/aws-sdk-cpp#522]
Hi,
I'm getting a linker error in my Application for the function GeneratePresignedUrl on Windows / Visual Studio 2015

Here is how I build the SDK
cmake -DCMAKE_BUILD_TYPE=Release Path_To_aws-sdk-cpp -DBUILD_ONLY="s3" -DCUSTOM_MEMORY_MANAGEMENT=1 -G "Visual Studio 14 Win64" 

msbuild INSTALL.vcxproj /p:Configuration=Release

What am I doing wrong? Error is below

thanks

error LNK2019: unresolved external symbol "public: class std::basic_string<char,struct std::char_traits<char>,class Aws::Allocator<char> > __cdecl Aws::S3::S3Client::GeneratePresignedUrl(class std::basic_string<char,struct std::char_traits<char>,class Aws::Allocator<char>
 > const &,class std::basic_string<char,struct std::char_traits<char>,class Aws::Allocator<char> > const &,enum Aws::Http::HttpMethod,__int64)" (?GeneratePresignedUrl@S3Client@S3@Aws@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$Allocator@D@Aws@@@std@@AEBV45@0W4HttpMethod@Http@3@_J@Z) referenced

**Comment by MyCADDev** [comment]
Additional Info - I am able to link with other functions on the S3Client object. Its only the GeneratePresignedUrl which is causing the linker error.

**Comment by singku** [comment]
@MyCADDev Could you paste your CMakeList.txt here?

**Comment by MyCADDev** [comment]
@singku Here it is ...

# This is the CMakeCache file.
# For build in directory: e:/Projects/aws-sdk-cpp/dist
# It was generated by CMake: E:/Installs/CMake/bin/cmake.exe
# You can edit this file to change values found and used by cmake.
# If you do not want to change any of the values, simply exit the editor.
# If you do want to change a value, simply edit, save, and exit the editor.
# The syntax for the file is as follows:
# KEY:TYPE=VALUE
# KEY is the name of a variable in the cache.
# TYPE is a hint to GUIs for the type of VALUE, DO NOT EDIT TYPE!.
# VALUE is the current value for the KEY.

########################
# EXTERNAL cache entries
########################

//When building for Android, should curl be built as well
ANDROID_BUILD_CURL:BOOL=ON

//When building for Android, should Openssl be built as well
ANDROID_BUILD_OPENSSL:BOOL=ON

//When building for Android, should Zlib be built as well
ANDROID_BUILD_ZLIB:BOOL=ON

//Value Computed by CMake
AWSSDK_BINARY_DIR:STATIC=E:/Projects/aws-sdk-cpp/dist

//Value Computed by CMake
AWSSDK_SOURCE_DIR:STATIC=E:/Projects/aws-sdk-cpp

//A semi-colon delimited list of the projects to build
BUILD_ONLY:STRING=s3

//If enabled, all aws sdk libraries will be build as shared objects;
// otherwise all Aws libraries will be built as static objects
BUILD_SHARED_LIBS:BOOL=ON

//No help, variable specified on the command line.
CMAKE_BUILD_TYPE:UNINITIALIZED=Release

//Semicolon separated list of supported configuration types, only
// supports Debug, Release, MinSizeRel, and RelWithDebInfo, anything
// else will be ignored.
CMAKE_CONFIGURATION_TYPES:STRING=Debug;Release;MinSizeRel;RelWithDebInfo

//Flags used by the compiler during all build types.
CMAKE_CXX_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3 /GR /EHsc

//Flags used by the compiler during debug builds.
CMAKE_CXX_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1

//Flags used by the compiler during release builds for minimum
// size.
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG

//Flags used by the compiler during release builds.
CMAKE_CXX_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG

//Flags used by the compiler during release builds with debug info.
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG

//Libraries linked by default with all C++ applications.
CMAKE_CXX_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib

//Flags used by the compiler during all build types.
CMAKE_C_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3

//Flags used by the compiler during debug builds.
CMAKE_C_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1

//Flags used by the compiler during release builds for minimum
// size.
CMAKE_C_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG

//Flags used by the compiler during release builds.
CMAKE_C_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG

//Flags used by the compiler during release builds with debug info.
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG

//Libraries linked by default with all C applications.
CMAKE_C_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib

//Flags used by the linker.
CMAKE_EXE_LINKER_FLAGS:STRING=/machine:x64

//Flags used by the linker during debug builds.
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL

//Flags used by the linker during release minsize builds.
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO

//Flags used by the linker during release builds.
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO

//Flags used by the linker during Release with Debug Info builds.
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL

//Install path prefix, prepended onto install directories.
CMAKE_INSTALL_PREFIX:PATH=C:/Program Files/aws-cpp-sdk-all

//Path to a program.
CMAKE_LINKER:FILEPATH=C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/link.exe

//Flags used by the linker during the creation of modules.
CMAKE_MODULE_LINKER_FLAGS:STRING=/machine:x64

//Flags used by the linker during debug builds.
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL

//Flags used by the linker during release minsize builds.
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO

//Flags used by the linker during release builds.
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO

//Flags used by the linker during Release with Debug Info builds.
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL

//Value Computed by CMake
CMAKE_PROJECT_NAME:STATIC=AWSSDK

//RC compiler
CMAKE_RC_COMPILER:FILEPATH=rc

//Flags for Windows Resource Compiler.
CMAKE_RC_FLAGS:STRING=/DWIN32

//Flags for Windows Resource Compiler during debug builds.
CMAKE_RC_FLAGS_DEBUG:STRING=/D_DEBUG

//Flags for Windows Resource Compiler during release builds for
// minimum size.
CMAKE_RC_FLAGS_MINSIZEREL:STRING=

//Flags for Windows Resource Compiler during release builds.
CMAKE_RC_FLAGS_RELEASE:STRING=

//Flags for Windows Resource Compiler during release builds with
// debug info.
CMAKE_RC_FLAGS_RELWITHDEBINFO:STRING=

//Flags used by the linker during the creation of dll's.
CMAKE_SHARED_LINKER_FLAGS:STRING=/machine:x64

//Flags used by the linker during debug builds.
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL

//Flags used by the linker during release minsize builds.
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO

//Flags used by the linker during release builds.
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO

//Flags used by the linker during Release with Debug Info builds.
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL

//If set, runtime paths are not added when installing shared libraries,
// but are added when building.
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO

//If set, runtime paths are not added when using shared libraries.
CMAKE_SKIP_RPATH:BOOL=NO

//Flags used by the linker during the creation of static libraries.
CMAKE_STATIC_LINKER_FLAGS:STRING=/machine:x64

//Flags used by the linker during debug builds.
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during release minsize builds.
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during release builds.
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during Release with Debug Info builds.
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//If this value is on, makefiles will be generated without the
// .SILENT directive, and all commands will be echoed to the console
// during the make.  This is useful for debugging only. With Visual
// Studio IDE projects all commands are done without /nologo.
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE

//Flag to upgrade the C++ standard used. The default is 11. The
// minimum is 11.
CPP_STANDARD:STRING=11

//No help, variable specified on the command line.
CUSTOM_MEMORY_MANAGEMENT:UNINITIALIZED=1

//If enabled, the android build will not attempt to generate a
// standalone toolchain and instead rely on externally passed cmake
// parameters to specify the complete build environment.  The included
// toolchain file is still used.
DISABLE_ANDROID_STANDALONE_BUILD:BOOL=OFF

//Flag to enable/disable rtti within the library
ENABLE_RTTI:BOOL=ON

//Flag to enable/disable building unit and integration tests
ENABLE_TESTING:BOOL=ON

//If enabled, the SDK will be built using a single unified .cpp
// file for each service library.  Reduces the size of static library
// binaries on Windows and Linux
ENABLE_UNITY_BUILD:BOOL=OFF

//Forces usage of the Curl client rather than the default OS-specific
// api
FORCE_CURL:BOOL=OFF

//If enabled, will unconditionally link the standard libraries
// in dynamically, otherwise the standard library will be linked
// in based on the BUILD_SHARED_LIBS setting
FORCE_SHARED_CRT:BOOL=ON

//Git command line client
GIT_EXECUTABLE:FILEPATH=GIT_EXECUTABLE-NOTFOUND

//If enabled, the SDK will be built via a unity aggregation process
// that results in smaller static libraries; additionally, release
// binaries will favor size optimizations over speed
MINIMIZE_SIZE:BOOL=OFF

//If enabled, no platform-default encryption will be included in
// the library.  For the library to be used you will need to provide
// your own platform-specific implementations
NO_ENCRYPTION:BOOL=OFF

//If enabled, no platform-default http client will be included
// in the library.  For the library to be used you will need to
// provide your own platform-specific implementation
NO_HTTP_CLIENT:BOOL=OFF

//If enabled, removes all the additional indirection (platform/cpu/config)
// in the bin and lib directories on the install step
SIMPLE_INSTALL:BOOL=ON

//If enabled on windows, the com object IXmlHttpRequest2 will be
// used for the http stack
USE_IXML_HTTP_REQUEST_2:BOOL=OFF

//Value Computed by CMake
aws-cpp-sdk-all_BINARY_DIR:STATIC=E:/Projects/aws-sdk-cpp/dist

//Value Computed by CMake
aws-cpp-sdk-all_SOURCE_DIR:STATIC=E:/Projects/aws-sdk-cpp

//Value Computed by CMake
aws-cpp-sdk-core-tests_BINARY_DIR:STATIC=E:/Projects/aws-sdk-cpp/dist/aws-cpp-sdk-core-tests

//Value Computed by CMake
aws-cpp-sdk-core-tests_SOURCE_DIR:STATIC=E:/Projects/aws-sdk-cpp/aws-cpp-sdk-core-tests

//Value Computed by CMake
aws-cpp-sdk-core_BINARY_DIR:STATIC=E:/Projects/aws-sdk-cpp/dist/aws-cpp-sdk-core

//Dependencies for the target
aws-cpp-sdk-core_LIB_DEPENDS:STATIC=general;Userenv;general;version;general;Wininet;general;winhttp;general;Bcrypt;

//Value Computed by CMake
aws-cpp-sdk-core_SOURCE_DIR:STATIC=E:/Projects/aws-sdk-cpp/aws-cpp-sdk-core

//Value Computed by CMake
aws-cpp-sdk-s3-integration-tests_BINARY_DIR:STATIC=E:/Projects/aws-sdk-cpp/dist/aws-cpp-sdk-s3-integration-tests

//Value Computed by CMake
aws-cpp-sdk-s3-integration-tests_SOURCE_DIR:STATIC=E:/Projects/aws-sdk-cpp/aws-cpp-sdk-s3-integration-tests

//Value Computed by CMake
aws-cpp-sdk-s3_BINARY_DIR:STATIC=E:/Projects/aws-sdk-cpp/dist/aws-cpp-sdk-s3

//Dependencies for the target
aws-cpp-sdk-s3_LIB_DEPENDS:STATIC=general;aws-cpp-sdk-core;

//Value Computed by CMake
aws-cpp-sdk-s3_SOURCE_DIR:STATIC=E:/Projects/aws-sdk-cpp/aws-cpp-sdk-s3

//Value Computed by CMake
testing-resources_BINARY_DIR:STATIC=E:/Projects/aws-sdk-cpp/dist/testing-resources

//Dependencies for the target
testing-resources_LIB_DEPENDS:STATIC=general;aws-cpp-sdk-core;

//Value Computed by CMake
testing-resources_SOURCE_DIR:STATIC=E:/Projects/aws-sdk-cpp/testing-resources


########################
# INTERNAL cache entries
########################

//This is the directory where this CMakeCache.txt was created
CMAKE_CACHEFILE_DIR:INTERNAL=e:/Projects/aws-sdk-cpp/dist
//Major version of cmake used to create the current loaded cache
CMAKE_CACHE_MAJOR_VERSION:INTERNAL=3
//Minor version of cmake used to create the current loaded cache
CMAKE_CACHE_MINOR_VERSION:INTERNAL=8
//Patch version of cmake used to create the current loaded cache
CMAKE_CACHE_PATCH_VERSION:INTERNAL=0
//Path to CMake executable.
CMAKE_COMMAND:INTERNAL=E:/Installs/CMake/bin/cmake.exe
//Path to cpack program executable.
CMAKE_CPACK_COMMAND:INTERNAL=E:/Installs/CMake/bin/cpack.exe
//Path to ctest program executable.
CMAKE_CTEST_COMMAND:INTERNAL=E:/Installs/CMake/bin/ctest.exe
//ADVANCED property for variable: CMAKE_CXX_FLAGS
CMAKE_CXX_FLAGS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_FLAGS_DEBUG
CMAKE_CXX_FLAGS_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_FLAGS_MINSIZEREL
CMAKE_CXX_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_FLAGS_RELEASE
CMAKE_CXX_FLAGS_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_FLAGS_RELWITHDEBINFO
CMAKE_CXX_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_STANDARD_LIBRARIES
CMAKE_CXX_STANDARD_LIBRARIES-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_FLAGS
CMAKE_C_FLAGS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_FLAGS_DEBUG
CMAKE_C_FLAGS_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_FLAGS_MINSIZEREL
CMAKE_C_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_FLAGS_RELEASE
CMAKE_C_FLAGS_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_FLAGS_RELWITHDEBINFO
CMAKE_C_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_STANDARD_LIBRARIES
CMAKE_C_STANDARD_LIBRARIES-ADVANCED:INTERNAL=1
//Executable file format
CMAKE_EXECUTABLE_FORMAT:INTERNAL=Unknown
//ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS
CMAKE_EXE_LINKER_FLAGS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS_DEBUG
CMAKE_EXE_LINKER_FLAGS_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS_MINSIZEREL
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS_RELEASE
CMAKE_EXE_LINKER_FLAGS_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
//Name of external makefile project generator.
CMAKE_EXTRA_GENERATOR:INTERNAL=
//Name of generator.
CMAKE_GENERATOR:INTERNAL=Visual Studio 14 2015 Win64
//Name of generator platform.
CMAKE_GENERATOR_PLATFORM:INTERNAL=
//Name of generator toolset.
CMAKE_GENERATOR_TOOLSET:INTERNAL=
//Source directory with the top level CMakeLists.txt file for this
// project
CMAKE_HOME_DIRECTORY:INTERNAL=E:/Projects/aws-sdk-cpp
//ADVANCED property for variable: CMAKE_LINKER
CMAKE_LINKER-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS
CMAKE_MODULE_LINKER_FLAGS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS_DEBUG
CMAKE_MODULE_LINKER_FLAGS_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS_RELEASE
CMAKE_MODULE_LINKER_FLAGS_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
//number of local generators
CMAKE_NUMBER_OF_MAKEFILES:INTERNAL=6
//Platform information initialized
CMAKE_PLATFORM_INFO_INITIALIZED:INTERNAL=1
//ADVANCED property for variable: CMAKE_RC_COMPILER
CMAKE_RC_COMPILER-ADVANCED:INTERNAL=1
CMAKE_RC_COMPILER_WORKS:INTERNAL=1
//ADVANCED property for variable: CMAKE_RC_FLAGS
CMAKE_RC_FLAGS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_RC_FLAGS_DEBUG
CMAKE_RC_FLAGS_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_RC_FLAGS_MINSIZEREL
CMAKE_RC_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_RC_FLAGS_RELEASE
CMAKE_RC_FLAGS_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_RC_FLAGS_RELWITHDEBINFO
CMAKE_RC_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
//Path to CMake installation.
CMAKE_ROOT:INTERNAL=E:/Installs/CMake/share/cmake-3.8
//ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS
CMAKE_SHARED_LINKER_FLAGS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS_DEBUG
CMAKE_SHARED_LINKER_FLAGS_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS_RELEASE
CMAKE_SHARED_LINKER_FLAGS_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_SKIP_INSTALL_RPATH
CMAKE_SKIP_INSTALL_RPATH-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_SKIP_RPATH
CMAKE_SKIP_RPATH-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS
CMAKE_STATIC_LINKER_FLAGS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS_DEBUG
CMAKE_STATIC_LINKER_FLAGS_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS_RELEASE
CMAKE_STATIC_LINKER_FLAGS_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_VERBOSE_MAKEFILE
CMAKE_VERBOSE_MAKEFILE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: GIT_EXECUTABLE
GIT_EXECUTABLE-ADVANCED:INTERNAL=1

**Comment by singku** [comment]
@MyCADDev I mean the CMakeList.txt not CMakeCache.txt. Also have you specified USE_IMPORT_EXPORT to your compiler and copied all the dependent libs to build dir such as https://github.com/singku/aws-sdk-cpp-test/blob/master/CMakeLists.txt did ?

**Comment by MyCADDev** [comment]
We use a custom build system based on make so I cannot send CMakeLists.txt 
But I added USE_IMPORT_EXPORT and AWS_CUSTOM_MEMORY_MANAGEMENT.

The aws-cpp-sdk-s3 and aws-cpp-sdk-core is the only dependent libs i have specified in my targets.

As I mentioned before I can link with and call other functions on S3Client like  PutObject. Its only the GeneratePresignedUrl which is giving the linker error.

**Comment by MyCADDev** [comment]
I just took the latest source from this repo and recompiled and linked with my app and it worked.
Please close this issue.

Thanks for your support @singku
