### ISSUE TITLE
S3Client doesn't grow it's pool beyond 3~4 connections

### ISSUE THREAD

**Issue by gdochev** [aws/aws-sdk-cpp#523]
We simultaneously issue many GetObjectAsync requests, say 512, yet we never see S3Client growing its connection pool beyond 3~4 connections. How can we tweak the S3Client or our code to increase the concurrent connections being used, which would hopefully increase the aggregate download throughput?

**Comment by marcomagdy** [comment]
Can you post the ``ClientConfiguration`` settings that you instantiate S3Client with?
Specifically, the values for ``ClientConfiguration::maxConnections`` and ``ClientConfiguration::executor``

**Comment by gdochev** [comment]
Sure,
    
We use the following values:

config.executor = make_shared<PooledThreadExecutor>(4);
config.maxConnections = 128;

Your question prompted me to increase the number of threads and sure enough the connections grew proportionally. I haven't studied your code in detail but my quick experiments imply that you don't do any HTTP pipelining (multiple outstanding gets/connection) and further you need one thread per connection. Could you confirm this is the case?

**Comment by marcomagdy** [comment]
No, we don't do http pipelining.
We use one thread per **request** and pool the connections.

**Comment by gdochev** [comment]
Thanks for the clarification, I think we can close this.
