### ISSUE TITLE
GNUInstallDirs.cmake included() too early

### ISSUE THREAD

**Issue by andred** [aws/aws-sdk-cpp#527]
Because GNUInstallDirs is included before the call to project(), it doesn't actually work (except when using the CMake binaries from Ubuntu).

GNUInstallDirs uses CMAKE_SYSTEM_NAME, which is defined only after project().

It works in Ubuntu, because they add a local hack which ends up bypassing the relevant bits of GNUInstallDirs.cmake, but when using CMake from source, or when using any other distribution, the way GNUInstallDirs is used in the AWS C++ SDK doesn't work.

**Comment by singku** [comment]
Could you please elaborate which purpose you want to achieve by using CMAKE_SYSTEM_NAME? If it is empty, cmake script just go into different branch after if condition

**Comment by andred** [comment]
If you look at GNUInstallDirs.cmake (the original version, not Ubuntu's modified version), it uses CMAKE_SYSTEM_NAME to determine if it is compiling for Linux at all https://github.com/Kitware/CMake/blob/master/Modules/GNUInstallDirs.cmake#L220 . After that, it determines the OS, debian and derivates https://github.com/Kitware/CMake/blob/master/Modules/GNUInstallDirs.cmake#L222 or something else https://github.com/Kitware/CMake/blob/master/Modules/GNUInstallDirs.cmake#L232

Given CMAKE_SYSTEM_NAME is empty if GNUInstallDirs is included before project(), the AWS C++ SDK is installed into the wrong location.
