### ISSUE TITLE
Need to pass additional compiler options down to SDK compilation cmdline

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#531]
Is there an easy way to pass "-ffunction-sections -fdata-sections" down to gcc during AWS SDK compilation?

I want to try it to see if it'll have any effect on my binary size (which is linking SDK statically as of now).

Is there any way to do it for "--gc-sections" linker option?

**Comment by marcomagdy** [comment]
Have you tried passing -DCMAKE_CXX_FLAGS="-ffunction-sections" to cmake?
We append our flags to the values defined in that variable.

**Comment by singku** [comment]
Checkout the file: cmake/compiler_settings.cmake, search CMAKE_CXX_FLAGS, see how we manipulate gcc flags, or simply specify the value from command line as Marco pointed out.

**Comment by crusader-mike** [comment]
Thank you. It works. Shaves ~800kb off my binary (SDK is linked statically). It is still definitely not idea -- even though I use only very few elements of SDK (PuObject, basically), linking SDK adds 3Mb to my binary size. Probably because GCC can't discard unused virtual functions, I guess :-\

**Comment by singku** [comment]
Have you tried gcc -O and `strip` of your binary to further reduce the size?

**Comment by crusader-mike** [comment]
Yes, I strip debug info when compiling my binary. Didn't pass "-s" to AWS SDK cmdline. Will try tomorrow.

**Comment by marcomagdy** [comment]
Please reopen if you need further help.

**Comment by crusader-mike** [comment]
Ok.

Btw, tried passing "-s" down the chain today -- no significant effect on final binary size.

**Comment by singku** [comment]
What's the current module you included and what's the size?

**Comment by crusader-mike** [comment]
s3 and core. I only used necessary minimum for PutObject/DeleteObject/Multiupload(Ini/Commit/Abort). At some point I stripped my program from all dependencies but AWS SDK -- it was slightly larger than 3Mb (x86_64, CentOS7, gcc 6.2).

Strange that "-s" had very little effect -- typically C++ symbols are quite large.

**Comment by singku** [comment]
Did you also link zlib, ssl and curl statically?

**Comment by marcomagdy** [comment]
make sure exceptions are disabled for your executable. And try defining 
extern "C" void __cxa_pure_virtual() { std::abort(); }

**Comment by crusader-mike** [comment]
> make sure exceptions are disabled for your executable

Why would I want to do that? O_o


> Did you also link zlib, ssl and curl statically?

I ran couple of tests today, results are below:

**linker cmdline:**
-lnsl -lstdc++ -lrt -lcrypt  -lxerces-c -lxalan-c -laws-cpp-sdk-s3 -laws-cpp-sdk-core -l:libcurl.a -lssl -lz -lcrypto

**case 1:**
`cmake -DCUSTOM_MEMORY_MANAGEMENT=0 -DMINIMIZE_SIZE=1 -DBUILD_ONLY="core;s3" -DENABLE_TESTING=OFF -DCMAKE_INSTALL_LIBDIR=lib64  ~/aws-sdk-cpp`

binary size: 1533224 (1.46Mb)

aws-*, libcurl, libz, libssl are on list produced by ldd


**case 2:**
`cmake -DCUSTOM_MEMORY_MANAGEMENT=0 -DBUILD_SHARED_LIBS=0 -DMINIMIZE_SIZE=1 -DBUILD_ONLY="core;s3" -DENABLE_TESTING=OFF -DCMAKE_INSTALL_LIBDIR=lib64 ~/aws-sdk-cpp`

binary size: 12818801 (12.22Mb)

libz, libssl are on list produced by ldd


**case 3:**
`cmake -DCUSTOM_MEMORY_MANAGEMENT=0 -DBUILD_SHARED_LIBS=0 -DMINIMIZE_SIZE=1 -DBUILD_ONLY="core;s3" -DENABLE_TESTING=OFF -DCMAKE_INSTALL_LIBDIR=lib64 -DCMAKE_CXX_FLAGS="-ffunction-sections -fdata-sections" ~/aws-sdk-cpp`

binary size: 11857342 (11.31Mb)

libz, libssl are on list produced by ldd


**case 4:**
`cmake -DCUSTOM_MEMORY_MANAGEMENT=0 -DBUILD_SHARED_LIBS=0 -DMINIMIZE_SIZE=1 -DBUILD_ONLY="core;s3" -DENABLE_TESTING=OFF -DCMAKE_INSTALL_LIBDIR=lib64 -DCMAKE_CXX_FLAGS="-ffunction-sections -fdata-sections -s" ~/aws-sdk-cpp`

binary size: 11857342 (11.31Mb)

libz, libssl are on list produced by ldd


**now the same with `-s` on main app:**

case 1: 1222704 (1.17Mb)
case 2: 4686096 (4.47Mb)
case 3: 4218480 (4.02Mb)
case 4: 4218480 (4.02Mb)

**linking curl dynamically:**
case 4: 3815168 (3.64Mb)

i.e. 2.47Mb of code to submit few HTTP requests -- seems quite excessive. I imagine there are some global variables in AWS SDK that cause this. Plus the fact that gcc can't discard unused virtual functions.

**Comment by marcomagdy** [comment]
I don't have visibility into your application. I suggested to turn off exceptions as a general guideline to reduce binary size.

Anyways, it seems that you're not passing `-DCMAKE_BUILD_TYPE` in your examples above. I'd recommend that you ensure one of the 'release' options is being passed. Either `RelWithDebInfo`, `Release` or `MinSizeRel`.

**Comment by crusader-mike** [comment]
> I suggested to turn off exceptions as a general guideline to reduce binary size.

Got it. No, cutting out everything exception-related isn't an option for me.

> you're not passing -DCMAKE_BUILD_TYPE ...  ensure one of the 'release' options is being passed. Either RelWithDebInfo, Release or MinSizeRel.

Thank you. I wasn't aware of this option. I'll check on Monday if it makes any difference,

**Comment by crusader-mike** [comment]
`-DCMAKE_BUILD_TYPE=Release` reduced size to 1.97Mb (best case with libcurl linked dynamically). I.e. ~0.8Mb for functionality I used. Not ideal, but much better. Thank you. :-)

It is time for me to learn CMake... :-/
