### ISSUE TITLE
Aws::S3::Model::BucketLocationConstraint does not list us-east-2 region

### ISSUE THREAD

**Issue by igorcanadi** [aws/aws-sdk-cpp#532]
See: https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-s3/include/aws/s3/model/BucketLocationConstraint.h#L26

**Comment by marcomagdy** [comment]
Will fix shortly. Thanks for reporting it.

**Comment by igorcanadi** [comment]
Thanks @marcomagdy !

**Comment by singku** [comment]
@igorcanadi This has been fixed.

**Comment by singku** [comment]
Hi @igorcanadi, since there are some intertwined release procedures, we have to wait until July 1st to get this fix released. For now, you could override the endpoint from user project if you have to use use-east-2. Apologize for this inconvenience, will update this thread once we fixed it.

**Comment by igorcanadi** [comment]
Thank @singku , that's great!

**Comment by singku** [comment]
@igorcanadi We added it earlier today.
