### ISSUE TITLE
request: static libs compiled with dynamic CRT in SDK nugets

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#536]
I tried to link AWS SDK statically on windows. It didn't work because static libs were compiled with "static CRT" (and all my projects use dynamic CRT). It would be really nice if you add these to nugets published on nuget.org.

Thank you.

**Comment by singku** [comment]
Nuget is not supported anymore, since you have switched to vcpckg, I am closing it now.

**Comment by crusader-mike** [comment]
lol... I was about to close it. Thank you, Andrew.
