### ISSUE TITLE
enabling exceptions

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#537]
I noticed that on Linux SDK is compiled with `-fno-exceptions`. I assume similar option was used in Windows build.

1. Is there any easy way to compile SDK with exceptions?

2. Is it ok to compile SDK with exceptions? (i.e. is it going to break smth?)

**Comment by crusader-mike** [comment]
In case if someone stumbles upon this:

- as of now Linux build is compiled with `-fno-exceptions` and there is no easy way to remove it

- Windows build (nuget package distributed via nuget.org) is built with exceptions support, but there could be a problem: if your iostream object doesn't mask exceptions and they escape while in some sort of callback (e.g. libcurl callback, if you use curl) -- it may end up propagating through portion of stack owned by C code. This can cause problems.

- it is ok to compile SDK with exceptions

**Comment by mramato** [comment]
@crusader-mike were you able to build with exceptions without having to hand-modify the CMake files?  It doesn't look like there is a way to get it to build with exceptions otherwise.

**Comment by crusader-mike** [comment]
No, waiting for SDK team to provide CMake option and explain what is going to happen to exception that escapes related iostream. See #542.
