### ISSUE TITLE
What are the steps to compile AWS CPP SDK nugets on Windows?

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#540]
I need to customize SDK build on Windows and not lose nuget's convenience.

**Comment by singku** [comment]
I am confused. Nuget is just package and dependency manager. Build the SDK itself doesn't need nuget.

**Comment by crusader-mike** [comment]
In our company for windows builds we use private nuget repository (to avoid putting 3rd-party libs into source code repository). So, we use AWS SDK by referencing related nuget (taken from [here](http://www.nuget.org/packages/AWSSDKCPP-Core/)).

I wanted to customize SDK build (link CRT statically/etc) and make my own package (and put it into our repository). It seems that Jonathan builds these packages -- if he has instructions written anywhere, I'd really appreciate if they get published.

**Comment by crusader-mike** [comment]
Thank you, Jonathan.

**Comment by JonathanHenson** [comment]
Using this commandlet:  http://coapp.org/reference/write-nugetpackage.html

After running Debug/Release/X86/x64 for VS2013 and VS2015 and then running the install target:

cd <install_dir>/nuget
powershell.exe -NonInteractive -ExecutionPolicy RemoteSigned "gci *.autopkg | ForEach-object { Write-NuGetPackage $_.FullName }"


#Then to publish
nuget.exe setApiKey <your api key here>
powershell.exe -NonInteractive -ExecutionPolicy RemoteSigned "gci *.nupkg -exclude *.redist*,*symbols* | ForEach-object { Publish-NuGetPackage -Packages $_.FullName   -Repository https://www.nuget.org/api/v2/package -SymbolRepository https://nuget.smbsrc.net -ApiKey <your api key here> -Verbose }"
