### ISSUE TITLE
Recent GetBucketLocation behaviour or authorisation change?

### ISSUE THREAD

**Issue by ferrouswheel** [aws/aws-sdk-cpp#541]
I'm not sure this is a bug, but I'd like to understand the behaviour change we've noticed when upgrading from the latest version at April 21 to May 18:

https://github.com/aws/aws-sdk-cpp/compare/fbd9dfbc6015ad86ed1dceafb6a1bad8555cae41...144980695078eb0707752d47b129abb896875bae

What I've noticed is that `Aws::S3::S3Client::GetBucketLocation` used to work fine when the client's region is not explicitly set. I assume this defaults to `us-east-1`, and if I explicitly set to `us-east-1` I get the same problem I'm currently experiencing.

The problem is that the object `Aws::S3::Model::GetBucketLocationOutcome` returned from `m_client->GetBucketLocation(request);` now contains an error:

ExceptionName = "AuthorizationHeaderMalformed"
Message = "Unable to parse ExceptionName: AuthorizationHeaderMalformed Message: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'"

This points to authorization having changed somehow, but trying to diff between those two commits is difficult due to all the copyright header changes! I'm hoping the reason for this different behaviour will be obvious to someone actively working on aws-sdk-cpp :-)

While I can work around it, I want to know why I have to use `us-west-2` instead now, if that will always be a valid region, and if the region is related to the account of the API keys I'm using.

Thanks!

**Comment by JonathanHenson** [comment]
it's probably the bucket addressing change. Can you turn virtual bucket addressing off and see what happens?

**Comment by ferrouswheel** [comment]
Yup - this resolves the problem! Thanks.

**Comment by SubmarineX** [comment]
@JonathanHenson Hi, how to turn virtual bucket addressing off?

**Comment by JonathanHenson** [comment]
have a look at the s3 client constructor, its a bool argument that defaults to true.

**Comment by SubmarineX** [comment]
@JonathanHenson Thank you, I find it.
