### ISSUE TITLE
Problem linking with Visual Studio 2017

### ISSUE THREAD

**Issue by prgtrdr** [aws/aws-sdk-cpp#544]
I'm a new AWS developer so I may be doing something wrong, but I've done lots of searching and can't seem to find a solution to this problem.

I'm using VS 2017 Community Edition, Version 15.1 (26403.7) Release, trying to build just a simple AWS S3 Test program.  I followed [the instructions](https://aws.amazon.com/blogs/developer/aws-sdk-for-c-now-available-via-nuget/) from the Developers Blog to install (using NuGet) AWSSDKCPP-S3 v1.0.20060301.128 (which installs AWSSDKCPP-Core v1.0.128.)  The two packages show up in the Project Property pages under "Referenced Packages" as Linkage: Dynamic Library (DLL).  My target environment is Windows x64 Debug (for now.)

The include files and paths seem to have been installed okay, and compiles complete without error.  But when VS gets to the link stage, it can't seem to find the library functions.  For a simple program:
```
int main()
{
	Aws::SDKOptions options;
	Aws::InitAPI(options);

	std::cout << "Hello, AWS World!" << std::endl;
}
```
VS gives the error:
`error LNK2019: unresolved external symbol "void __cdecl Aws::InitAPI(struct Aws::SDKOptions const &)" (?InitAPI@Aws@@YAXAEBUSDKOptions@1@@Z) referenced in function main`

Is this behavior happening because I'm using VS 2017 and the NuGet packages are for an earlier version of VS?  If so, is there a temporary alternative until the NuGet Packages are updated, i.e., specifying libraries directly in the VS Properties?  Or do I have to go through the entire library build process?

(As a workaround, I tried specifying actual library names as input to the linker and that almost worked--but I'm still getting an unresolved external on Aws::Http::CONTENT_TYPE_HEADER.  But that may be due to not having the correct libraries included or something.)

**Comment by JonathanHenson** [comment]
you are missing the USE_IMPORT_EXPORT definition. Nuget package is supposed to define this for you, but if you do it manually, you'll need to specify it.

**Comment by prgtrdr** [comment]
Thanks Jonathan.  I have now been able to get the program to run.  

I found that in addition to USE_IMPORT_EXPORT, I also needed to define USE_WINDOWS_DLL_SEMANTICS to fix the CONTENT_TYPE_HEADER error.

For future updates, I hope you can get the NuGet distributions work better.

**Comment by JonathanHenson** [comment]
the nuget distributions usually work. Could you send me your project before your changes so I can have a look?

**Comment by prgtrdr** [comment]
I wasn't sure how to upload the whole project so I created a GitHub repo for it [here](https://github.com/prgtrdr/ConsoleApplication1).

**Comment by bawejakunal** [comment]
I am trying to statically link the aws sdk to my project. Do I still need to use USE_IMPORT_EXPORT variable ? I guess just switching `Referenced Packages > AWSSDKCPP-* > Linkage` to `Static` should have been enough right ?

**Comment by prgtrdr** [comment]
@bawejakunal I found that in addition to USE_IMPORT_EXPORT, I also needed to define USE_WINDOWS_DLL_SEMANTICS to fix the CONTENT_TYPE_HEADER error.  That said, @JonathanHenson believes the NuGet package should install and set everything up correctly without extra work.  Let us know if doing so works for you. If not, please be explicit about what you're doing and what errors you're receiving.

**Comment by bawejakunal** [comment]
The errors are exactly what you mentioned in the first post of this issue. The only difference is that I am trying to statically link the awssdk to my project in which case USE_IMPORT_EXPORT and USE_WINDOWS_DLL_SEMANTICS do not help as these are meant for dynamic linking. 

I am trying out the sample code from this post: https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/

**Comment by prgtrdr** [comment]
Understood.  Unfortunately, I have not tried the static libraries.  Maybe the moderator has experience with that…

**Comment by bawejakunal** [comment]
Works absolutely fine on vs 2015, so I am using that for now. Thanks

**Comment by prgtrdr** [comment]
I'm not surprised,  there is probably some incompatibility with VS 2017 and the NuGet pkg.




On Thu, Jun 15, 2017 at 8:46 AM -0400, "Kunal Baweja" <notifications@github.com> wrote:












Works absolutely fine on vs 2015, so I am using that for now. Thanks

**Comment by diablodale** [comment]
I didn't see above that you set your project to use the v140 toolchain. The Nuget packages are only distributed for the v120 and v140 toolchain. You can change this on your project/properties/general the setting "Platform Toolset".  You have to specific customize your VS2017 install so that it installs the v140 toolchain.

Is this contributing to your issue?

**Comment by jason4tw** [comment]
The NuGet package should be updated for v141.

**Comment by prgtrdr** [comment]
@jason4tw I agree, the Nuget package should be updated for the v141 toolchain.

**Comment by MattyBoy4444** [comment]
Any progress?

**Comment by singku** [comment]
Will be out this week.

**Comment by hanaa-abdelgawad** [comment]
Thank you you helped me 
yes, it works fine with Vs2015 and i face problems with vs2017

**Comment by singku** [comment]
Guys, the nuget packages for VS2017(V141) have been updated and now accessible in Nuget package manage tools.
