### ISSUE TITLE
Process deadlock while waiting for s3 file transfer

### ISSUE THREAD

**Issue by ferrouswheel** [aws/aws-sdk-cpp#545]
Despite updating our aws-sdk-cpp libs recently to ensure we had fixes #511 and #520 - we are still seeing infrequent deadlocks when transferring to s3. Presumedly it's still related to `TransferHandle::WaitUntilFinished()` being called and `m_waitUntilFinishedSignal` never receiving a signal, but I am unable to see how.

We only have a single thread interacting with the AWS libraries, so we are reasonably confident it's not anything specific to our implementation.

It is difficult to debug as we only see this on EC2 instances (whether this is because we only run things at scale on EC2 or because of the reduced latency I don't know). Debugging requires some setup to remote attach and catch it before we terminate the process. If we encounter it again I will try update with the exact location it blocks.

For now I just wanted to document the issue in case others have seen it or have ideas where the trouble might be occurring.

**Comment by singku** [comment]
@ferrouswheel Hi, if possible, could you please describe the scenario of your use case, so that for us to better debugging this problem?

**Comment by singku** [comment]
@ferrouswheel Looking at [transferHandle.cpp](https://github.com/aws/aws-sdk-cpp/blob/da682606e2b693d444c1ed87b40ac23ff3fb7d7a/aws-cpp-sdk-transfer/source/transfer/TransferHandle.cpp#L228). There is a potential that currentStatus changed after acquisition, then [If test actually do a wrong test](https://github.com/aws/aws-sdk-cpp/blob/da682606e2b693d444c1ed87b40ac23ff3fb7d7a/aws-cpp-sdk-transfer/source/transfer/TransferHandle.cpp#L230). Will this affect your logic?

**Comment by ferrouswheel** [comment]
@singku The only place `m_status.store` is called is within that if statement, [here](https://github.com/aws/aws-sdk-cpp/blob/da682606e2b693d444c1ed87b40ac23ff3fb7d7a/aws-cpp-sdk-transfer/source/transfer/TransferHandle.cpp#L233) - so I'm not sure that the cause of the deadlock.

**Comment by ferrouswheel** [comment]
Our use case is:
- we have many ec2 instances accessing s3
- the instances run multiple jobs, and they are reading hundreds of megabytes and writing hundreds of megabytes.
- for a single job. it will: read many small files, read and seeking to random positions in a large file, and usually write one single large file at the end. often we have seen the deadlock when writing the large file.

I'll try to provide further information as we can.

**Comment by singku** [comment]
Yes, but since your service write large file at the end. Multipart upload is applied, there are multiple executors(threads) help uploading file. it's possible some thread acquired m_status but it was changed(updateStatus call) by other thread before it go into if condition.

**Comment by marcomagdy** [comment]
One thing you could do, that could help us pin the problem down, is hook up the `TransferStatusUpdatedCallback`.

Something like:
```cpp
    auto statusUpdatedCallback = [](const TransferManager* manager, const TransferHandle& 
    handle) 
    {
        // log sequence of events here
    }
    TransferManagerConfiguration tmConfig;
    tmConfig.s3Client = <your s3 client>;
    tmConfig.TransferStatusUpdatedCallback = statusUpdatedCallback;
    TransferManager transferManager(tmConfig);
```

**Comment by singku** [comment]
@ferrouswheel Hi, we have pushed out another fix for this bug. Could you please verify it? If the problem has been solved. Could you please close this issue?

**Comment by ferrouswheel** [comment]
I will integrate this in our next release. Unfortunately due to the nature of these bugs I won't be able to confirm if it has been solved until we've been running without deadlocks for a few weeks, but if it occurs again I'll reopen this issue.

Thank you for investigating and applying a fix!
