### ISSUE TITLE
On Android, OpenSSL-1.0.2d is not available anymore

### ISSUE THREAD

**Issue by kouellet** [aws/aws-sdk-cpp#55]
The current version of OpenSSL is now 1.0.2e (as of 3 December 2015). This cause an error when building for Android (cmake can't find the URL for OpenSSL-1.0.2d).

**Comment by triton3** [comment]
Hi,

I was wondering, is there any fix for this? 

I tried updating **CMakeLists.txt** with openssl URL pointing to to 1.0.2e with relevant url hash, but the build fails (see output below). Any suggestions?

    .... 
    Scanning dependencies of target OPENSSL    
    [  0%] Creating directories for 'OPENSSL'    
    [  0%] Performing download step (download, verify and extract) for 'OPENSSL'    
    -- downloading...    
         src='http://www.openssl.org/source/openssl-1.0.2e.tar.gz'    
         dst='~/AWS-CPP-ANDROID-BUILD/OPENSSL-prefix/src/openssl-1.0.2e.tar.gz'    
         timeout='none'     
    -- downloading... done     
    -- verifying file... done    
    -- extracting...       
    -- extracting... done    
    [  0%] No patch step for 'OPENSSL'    
    [  0%] Performing update step for 'OPENSSL'    
    [  0%] Performing configure step for 'OPENSSL'    
    -- Configuring done    
    -- Generating done    
    -- Build files have been written to: ~/AWS-CPP-ANDROID-BUILD/OPENSSL-prefix/src/OPENSSL-build    
    [  0%] Performing build step for 'OPENSSL'    
    Scanning dependencies of target crypto    
    [  0%] Building C object crypto/CMakeFiles/crypto.dir/cryptlib.c.o    
    In file included from ~/aws-sdk-cpp-master-Android/openssl/crypto/cryptlib.h:65:0,    
                     from ~/aws-sdk-cpp-master-Android/openssl/crypto/cryptlib.c:117:    
    ~/aws-sdk-cpp-master-Android/openssl/crypto/../e_os.h:64:28: fatal error: openssl/e_os2.h: No such file or directory    
     # include <openssl/e_os2.h>    
                                ^    
    compilation terminated.    
    make[5]: *** [crypto/CMakeFiles/crypto.dir/cryptlib.c.o] Error 1    
    make[4]: *** [crypto/CMakeFiles/crypto.dir/all] Error 2    
    make[3]: *** [all] Error 2    
    make[2]: *** [OPENSSL-prefix/src/OPENSSL-stamp/OPENSSL-build] Error 2    
    make[1]: *** [CMakeFiles/OPENSSL.dir/all] Error 2    
    make: *** [all] Error 2

**Comment by bretambrose** [comment]
I will try and take at look this today or tomorrow

**Comment by bretambrose** [comment]
The best fix for this would involve switching to a direct git clone at a version tag of openssl, but there are substantial structural differences between what's in git at the 1.0.2d tag and what is in the release tarball on their website.  Since the build process was done from the perspective of the archive, this is a non-trivial amount of work.  Until that gets fixed, you can at least bypass the problem by switching the URL in the ExternalProject_Add to:

URL https://www.openssl.org/source/old/1.0.2/openssl-1.0.2d.tar.gz

**Comment by triton3** [comment]
Yes, I did that for the time being. Thanks.

**Comment by JonathanHenson** [comment]
I think Bret fixed this in the HEAD of mainline. Can you check that the value is correct for you?

**Comment by JonathanHenson** [comment]
This has been updated and pushed out. Closing. If you still have an issue let feel free to reopen issue and let us know.

**Comment by bolunfeng** [comment]
MinGW + Cmake on win7 :

D:\software\OpenSSL-CMake\build>make
Scanning dependencies of target crypto
[  0%] Building C object crypto/CMakeFiles/crypto.dir/cryptlib.c.obj
In file included from D:\software\OpenSSL-CMake\crypto\cryptlib.h:65:0,
                 from D:\software\OpenSSL-CMake\crypto\cryptlib.c:117:
D:/software/OpenSSL-CMake/e_os.h:64:28: fatal error: openssl/e_os2.h: No such file or directory
 # include <openssl/e_os2.h>
                            ^
compilation terminated.
crypto\CMakeFiles\crypto.dir\build.make:62: recipe for target 'crypto/CMakeFiles/crypto.dir/cryptlib.c.obj' failed
make[2]: *** [crypto/CMakeFiles/crypto.dir/cryptlib.c.obj] Error 1
CMakeFiles\Makefile2:84: recipe for target 'crypto/CMakeFiles/crypto.dir/all' failed
make[1]: *** [crypto/CMakeFiles/crypto.dir/all] Error 2
Makefile:82: recipe for target 'all' failed
make: *** [all] Error 2


How can I fix it?
