### ISSUE TITLE
does aws-cpp-sdk-transfer supports transfer acceleration

### ISSUE THREAD

**Issue by Eliyahu-Machluf** [aws/aws-sdk-cpp#552]
Hi,

Following http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html I have a question:
 does the aws-cpp-sdk-transfer module supports accelerated transfer to s3?

Thanks. 

Eliyahu

**Comment by singku** [comment]
[Currently we don't](https://stackoverflow.com/questions/44054456/does-aws-cpp-s3-sdk-support-transfer-acceleration)

**Comment by JonathanHenson** [comment]
It does "support" it, you need to use clientConfiguration.endpointoverride and clientConfiguration.region manually to your acceleration end-point. Please reopen if you have further problems.

**Comment by holopekochan** [comment]
I have a question for the clientConfiguration.endpointoverride and clientConfiguration.region 
My bucket is actually in region 'us-west-2', however, after I changed the endpointoverride to the accelerated enpoint 
It gives me an Error "ExceptionName: AuthorizationHeaderMalformed Message: The authorization header is malformed; the region 'us-west-2' is wrong; expecting 'us-east-1'
If I change to us-esst-1, it would become Error aws NoSuchBucket The specified bucket does not exist
