### ISSUE TITLE
S3 GetObjectRequest RequestId

### ISSUE THREAD

**Issue by amaneureka** [aws/aws-sdk-cpp#554]
Is there a way to get response requested id for S3 GetObjectRequest ?

**Comment by amaneureka** [comment]
From S3 documentations I can see that requests can be uniquely identified by ```x-amz-request-id``` (and ```x-amz-id-2```) [Docs](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html)

I looked at current SDK code and found there is no way to get this fields from Response Payload.
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-s3/source/model/GetObjectRequest.cpp

Can I add the required field ```x-amz-request-id``` and send a pull request for the same ?

**Comment by singku** [comment]
Will be provided after next release.
