### ISSUE TITLE
How to set signature to v2

### ISSUE THREAD

**Issue by trustyboy** [aws/aws-sdk-cpp#555]
Is there any way to set  signature to v2?thx

**Comment by singku** [comment]
@trevorrowe Hi, Jonathan has answered the same question on stackoverflow, thread can be found [here](https://stackoverflow.com/questions/44325418/how-can-i-set-signature-to-v2-by-using-aws-s3-c-sdk/44341051#44341051)

**Comment by singku** [comment]
@trustyboy Hi, Jonathan has answered the same question on stackoverflow, you can find the thread [here](https://stackoverflow.com/questions/44325418/how-can-i-set-signature-to-v2-by-using-aws-s3-c-sdk/44341051#44341051)
