### ISSUE TITLE
3 tests failing on master, OS X

### ISSUE THREAD

**Issue by DraconPern** [aws/aws-sdk-cpp#557]
15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64

OS X 10.11.6

[  FAILED  ] 3 tests, listed below:
[  FAILED  ] ProfileConfigFileAWSCredentialsProviderTest.TestDefaultConfig
[  FAILED  ] EnvironmentModifyingTest.ProfileConfigTestWithEnvVars
[  FAILED  ] EnvironmentModifyingTest.ProfileConfigTestWithEnvVarsButSpecifiedProfile

Let me know what info you need to reproduce.

**Comment by DraconPern** [comment]
My cmake command is 

cmake .. -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Debug -DBUILD_ONLY="s3;transfer" -DCMAKE_INSTALL_PREFIX=$DEVSPACE/aws-sdk-cpp/Debug

**Comment by JonathanHenson** [comment]
can you provide us with a trace log output from your test run?

**Comment by DraconPern** [comment]
Unfortunately I have already upgraded to 16.6.0 and can't reproduce the issue anymore.  A bit more information about the build environment in case someone else comes across this.  I was targeting export MACOSX_DEPLOYMENT_TARGET=10.9  

I'll close this bug now.
