### ISSUE TITLE
"Unable to parse" error

### ISSUE THREAD

**Issue by prgtrdr** [aws/aws-sdk-cpp#558]
I see this has been discussed before, and was addressed in an earlier code version.  But I just received this error ("Unable to parse ExceptionName: InternalError Message: We encountered an internal error. Please try again.") using v1.0.133 of AWSSDKCPP with an Ubuntu EC2 image.  
![image](https://cloud.githubusercontent.com/assets/619043/26550850/af7bacb2-444d-11e7-81f7-4c4165095e20.png)

My code looks like this:
```
		Aws::S3::S3Client s3_client;

		Aws::S3::Model::GetObjectRequest object_request;
		object_request.WithBucket(bucketName.c_str()).WithKey(fileName.c_str());

		auto get_object_outcome = s3_client.GetObject(object_request);
		
		if (!get_object_outcome.IsSuccess()) {
			std::cout << "GetObject error: " <<
			get_object_outcome.GetError().GetExceptionName() << " " <<
			get_object_outcome.GetError().GetMessage() << " " <<
			bucketName << ":" << fileName << std::endl;
			return (-1);
		}

		std::istream file(get_object_outcome.GetResult().GetBody().rdbuf());
		in.push(boost::iostreams::gzip_decompressor());
		in.push(file);

		while (getline(in, line )) {
    .
    .
    .

```
It happens randomly about once in every 2,000 or so passes through this code.

I've looked at the comments/issues here and some have said this error emanates from the S3 side.  Is there something I should do in my code to retry?  Is there a way to have the AWSSDKCPP automatically retry (or increase an existing retry count?)  What are the recommended steps to gracefully recover?

**Comment by JonathanHenson** [comment]
Internal Error should always retry up to the retry count threshold, we'll look into why it is not. In the meantime, it is safe for you to retry in that case.

If we are exceeding the threshold, then it will (and should) fail. Could you send us a trace log excerpt of this happening?

**Comment by KaibaLopez** [comment]
I'm marking this issue for closing, if there's anything that needs more discussion on the topic, feel free to comment and we'll take another look at it.
