### ISSUE TITLE
Missing DNS.h in AWSSDKCPP-Core NuGet package?

### ISSUE THREAD

**Issue by zapproved** [aws/aws-sdk-cpp#559]
I noticed the NuGet packages in Visual Studio 2015 and perhaps naively thought it would be as simple a "New Console Project" and add the S3 package to be in business.  But after doing so and adding the include for the S3 client, I immediately have compilation errors (aws\core\util\DNS.h is missing).  I verified the file isn't on disk.  Here is my packages.config content:

```<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AWSSDKCPP-Core" version="1.0.4" targetFramework="native" />
  <package id="AWSSDKCPP-Core.redist" version="1.0.4" targetFramework="native" />
  <package id="AWSSDKCPP-S3" version="1.0.20060301.128" targetFramework="native" />
  <package id="AWSSDKCPP-S3.redist" version="1.0.20060301.128" targetFramework="native" />
</packages>
```

And my code:

```#include "stdafx.h"

#include <aws\core\Aws.h>
#include <aws\s3\S3Client.h>

int main()
{
	Aws::SDKOptions config;
	Aws::InitAPI(config);

	Aws::ShutdownAPI(config);
    return 0;
}
```
And the error:

 ...\packages\AWSSDKCPP-S3.1.0.20060301.128\build\native\include\aws\s3\S3Client.h(24): fatal error C1083: Cannot open include file: 'aws/core/utils/DNS.h': No such file or directory

Thanks!

**Comment by JonathanHenson** [comment]
we recently added dns verification for s3, but probably forgot to add the file to the install output.

What version of core is your project using? Is it the latest version? If not can you try updating the dependency to the latest version and trying again?

**Comment by zapproved** [comment]
Updated core to 1.0.128 and it's working now.  Thanks.
