### ISSUE TITLE
Clock skew is wrong

### ISSUE THREAD

**Issue by aee11** [aws/aws-sdk-cpp#560]
I have a long-running process on a VM that has an instantiated AWS client. I'm not sure how the client got to the state where the clock skew went wild but the logs seem to indicate a bug in the diff calculations:

```
[WARN] 2017-06-06 10:24:20 AWSErrorMarshaller [23524] Encountered AWSError
SignatureDoesNotMatch
Signature expired: 20170606T095435Z is now earlier than 20170606T101920Z (20170606T102420Z - 5 min.):
[WARN] 2017-06-06 10:24:20 AWSClient [23524] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
[DEBUG] 2017-06-06 10:24:20 AWSClient [23524] Server time is Tue, 06 Jun 2017 10:24:20 GMT, while client time is Tue, 06 Jun 2017 10:24:20 GMT
[INFO] 2017-06-06 10:24:20 AWSClient [23524] Computed time difference as 1784448 milliseconds. This is more than 4 minutes. Adjusting signer with the skew.
```

Server and client time are the same but the time difference is 30 minutes. The [debug message](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/client/AWSClient.cpp#L184) uses `DateTime::Now()` but the diff calculation uses `GetSigningTimestamp` from the signer.

SDK versions:
* Core: Nuget 1.0.98.1
* Route53: 1.0.20130401.99

**Comment by singku** [comment]
I think the debug message is to show you current server's time and client's time. Whereas the diff is to compute the difference between your last signing time and current server's time, which indicates the possible expiration of the signature.

**Comment by JonathanHenson** [comment]
We updated this a while back to be more robust:

https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/client/AWSClient.cpp

In general the process is as follows:

Detect signing error.
Get server host timestamp from the response
Compute the diff between what time the signer thinks it is -vs- the server (including an offset from previous detections)
If diff is greater than or less than abs(4 minutes), apply a new offset then retry the request

My guess is that somewhere in here, we detected a clock skew and adjusted, then your machine performed an NTP sync and put it back to the correct value. Did your application recover or did it remain in a bad state?

**Comment by aee11** [comment]
Yeah, I think your guess is correct. Clock skew got detected and adjusted but it seems that the adjustment is no longer valid after the NTP sync. The new offset always includes the old clock skew as a part of `GetSigningTimestamp`. The application did not recover and all calls through the client resulted in this error. Of course, restarting the application fixes the issue but is there any way I can reset the clock skew after catching this error?

**Comment by JonathanHenson** [comment]
I'll check it. We should just always take the new clock skew as gospel truth. Not sure why it isn't doing that actually.

**Comment by marcomagdy** [comment]
@aee11 we just pushed an update to that code section. [v1.0.159](https://github.com/aws/aws-sdk-cpp/releases/tag/1.0.159). I'm not entirely sure if it fixes the exact problem you're having (hard to tell without trace logs) but it might be worth a shot.
Reopen this issue if you're still seeing problems.
