### ISSUE TITLE
HTML entities in SQS messages

### ISSUE THREAD

**Issue by KeithBlonquist** [aws/aws-sdk-cpp#562]
This is probably a newbie question, but I am sending an SQS message with the following:

"&lt;tag&gt;text&lt;/tag&gt;"

When I receive the message with the SDK, (e.g. ReceiveMessageRequest GetResult().GetMessages()) the message is as follows:

"&amp;lt;tag&amp;gt;text&amp;lt;/tag&amp;gt;"

Does the SDK have functionality to convert the HTML (&lt; &gt;) back to the proper characters (< >)?

**Comment by KeithBlonquist** [comment]
My question wasn't posted properly, the SQS message that is sent is:

"&lt;tag&gt;text&lt;/tag&gt;"

The message as received is:

&amp;lt;tag&amp;gt;text&amp;lt;/tag&amp;gt;

**Comment by JonathanHenson** [comment]
A long time ago, I put utilities for that in our xml parser. Have a look at the XMLSerializer header file and see if you find something helpful there.

**Comment by KeithBlonquist** [comment]
Thanks for the quick response.

#include "aws/core/utils/xml/XmlSerializer.h"
...
auto decodedMessage = Aws::Utils::Xml::DecodeEscapedXmlText(originalMessage);
