### ISSUE TITLE
msbuild ALL_BUILD fails on aws-cpp-sdk-transfer

### ISSUE THREAD

**Issue by kreivi** [aws/aws-sdk-cpp#563]
I followed the instructions on the README.md where I first cloned the repo. Then I run the `cmake` for the sources. After that I tried to build for Visual Studio as instructed in README with the `msbuild ALL_BUILD.vcxproj` command (on the root where I ran `cmake` command) and it failed on the `aws-cpp-sdk-transfer` build. After that I separately tried to run `ALL_BUILD.vcxproj` only for `aws-cpp-sdk-transfer` and it failed with the similar warning & error.

Here is what the console printed out about it:
> Build FAILED.
>
>"E:\Developer\aws-sdk-build\ALL_BUILD.vcxproj" (default target) (1) ->
>"E:\Developer\aws-sdk-build\aws-cpp-sdk-transfer\aws-cpp-sdk-transfer.vcxproj"
>(default target) (107) ->
>(ClCompile target) ->
>  E:\Developer\aws-sdk\aws-cpp-sdk-transfer\source\transfer\TransferManager.cpp
>(133): warning C4244: 'argument': conversion from 'uint64_t' to '::size_t', pos
>sible loss of data [E:\Developer\aws-sdk-build\aws-cpp-sdk-transfer\aws-cpp-sdk
>-transfer.vcxproj]
>
>
>"E:\Developer\aws-sdk-build\ALL_BUILD.vcxproj" (default target) (1) ->
>"E:\Developer\aws-sdk-build\aws-cpp-sdk-transfer\aws-cpp-sdk-transfer.vcxproj"
>(default target) (107) ->
>(ClCompile target) ->
>  E:\Developer\aws-sdk\aws-cpp-sdk-transfer\source\transfer\TransferManager.cpp
>(133): error C2220: warning treated as error - no 'object' file generated [E:\D
>eveloper\aws-sdk-build\aws-cpp-sdk-transfer\aws-cpp-sdk-transfer.vcxproj]
>
>   1 Warning(s)
>   1 Error(s)

**Comment by JonathanHenson** [comment]
This is a bug on our end for 32 bit builds. We're fixing it now. In the meantime, if it works for you, you can build for 64 bit cmake -G "Visual Studio <version> Win64"

**Comment by JonathanHenson** [comment]
we just pushed out the fix for this, reopen if you still have problems.
