### ISSUE TITLE
uploadProgressCallback using TransferManager for multi-part uploads

### ISSUE THREAD

**Issue by jt70471** [aws/aws-sdk-cpp#566]
Hi, the uploadProgressCallback of TransferManager seems to work as expected for non-multipart uploads, however, for files that are multipart, the callback is only called once or twice for 9MB and 14GB files I'm testing with.

I have attached the output, it seems that for multipart files, the progress callback is only called when each part has completed uploading perhaps? Is that the way it's designed?

Thanks

[a.txt](https://github.com/aws/aws-sdk-cpp/files/1066800/a.txt)

**Comment by JonathanHenson** [comment]
We updated this somewhat recently to not be per-part based. Which version of the SDK are you using?

**Comment by bretambrose** [comment]
I don't think the continuous updates invoke the callback after each update.  They just write to a monotonically increasing atomic integer.

**Comment by jt70471** [comment]
I just did a git pull and rebuild, I'm now using 1.0.147.

**Comment by jt70471** [comment]
Thanks for merging the PR.
