### ISSUE TITLE
aws-cpp-sdk-transfer TransferManager::UploadFile fails if file name has unicode non ascii characters

### ISSUE THREAD

**Issue by Eliyahu-Machluf** [aws/aws-sdk-cpp#567]
Hi,

I'm calling TransferManager::UploadFile method, giving it a filename in hebrew. I give the filename as utf8 encoded as char *, and method fails stating it failed to open file, no such file. I see internally it calls FStream for opening the file, and I think the solution is changing it to use wfstream instead, in order to support non ascii file names.
I tried also giving the filename at machine code page (Windows-1255), and it worked. However my application shall not work with machine code page, it shall use unicode (UTF-16 or UTF-8).

Please add/change the method to enable unicode support for input filename.

Thanks for your assistance.

Eliyahu

**Comment by JonathanHenson** [comment]
UploadFile also has an overload to take a const std::shared_ptr<Aws::IOStream>&, is there a reason you can't use that instead? Then you can use std::wfstream if you would like.

**Comment by Eliyahu-Machluf** [comment]
Hi,

Thanks for the comment. I missed this overloaded function.
I now used it with fstream with the constructor getting wstring as filename, and it worked fine with unicode filename.

Thanks.

Eliyahu

**Comment by AlizaReishtein** [comment]
Eliyahu,
Can you send an example of how you did this?  Does this work only on windows or also on mac os?
I am having trouble converting from fstream to Aws::IOStream.
Thanks a lot,
Aliza

**Comment by Eliyahu-Machluf** [comment]
Hi Aliza,

Sorry for the delayed response. here is a code snippet which contains support for utf8. I tested it on windows (windows 10) and it worked fine. I don't know how it behaves on Mac:

Eliyahu

#ifdef ENABLE_WIN32_FILE_STREAM_FOR_UTF8_SUPPORT
	ANW_LOGGER_CLASS::ANW_LOG_TRACE( FL, "going to upload file using file stream with utf8 converter" );
	std::wstring_convert<std::codecvt_utf8<wchar_t>> UTF8Converter;
	std::shared_ptr<Aws::IOStream> fileStream;
	fstream *fs = new std::fstream;
	fileStream.reset(fs);
	try
	{		
		fs->exceptions(std::fstream::failbit | std::fstream::badbit);
		fs->open(UTF8Converter.from_bytes(source_file_path), std::ios_base::in | std::ios_base::binary);
	}
	catch ( std::fstream::failure f )
	{	
		ANW_LOGGER_CLASS::ANW_LOG_TRACE( FL, 
										 "got 'std::fstream::failure exception': failed to open file stream for '%s':"
										 " what='%s' code = %d, message = '%s'", 
										 source_file_path, 
										 f.what(), 
										 f.code().value(), 
										 f.code().message().c_str() );
		ANW_LOGGER_CLASS::ANW_SET_ERROR( FL, 
										 S_AWS_FAILED_TO_UPLOAD_FILE,  
										 "failed to open file stream for '%s'", 
										 source_file_path );
		return ANW_FAILED;
	}
	catch(std::exception e)
	{
		ANW_LOGGER_CLASS::ANW_LOG_TRACE( FL, 
										 "got 'std::exception': failed to open file stream for '%s': %s", 
										 source_file_path, 
										 e.what() );
		ANW_LOGGER_CLASS::ANW_SET_ERROR( FL, 
										 S_AWS_FAILED_TO_UPLOAD_FILE,  
										 "failed to open file stream for '%s'", 
										 source_file_path );
		return ANW_FAILED;
	}
	//clear fs exceptions, as TransferManager::UploadFile does not expect IOStream to throw exceptions
	fs->exceptions(std::fstream::goodbit);

	std::shared_ptr<TransferHandle> requestPtr = transferClient->UploadFile( fileStream,
		                                                                     target_bucket, 
																			 target_object_name,
																			 transferClientIntern->GetUploadContentType(),
	
																			 Aws::Map<Aws::String, Aws::String>() );
#else 
	std::shared_ptr<TransferHandle> requestPtr = transferClient->UploadFile( source_file_path,
		                                                                     target_bucket, 
																			 target_object_name,
																			 transferClientIntern->GetUploadContentType(),
	 //aws tests project used "text/plain" as content type, however I think octet-stream is right type here
																			 Aws::Map<Aws::String, Aws::String>() );
#endif
