### ISSUE TITLE
core/CMakeLists.txt missing core/config directory and file

### ISSUE THREAD

**Issue by tiberiuvs** [aws/aws-sdk-cpp#568]
When building, aws/core/config/AWSProfileConfigLoader.h is never copied, so `#include <aws/core/config/AWSProfileConfigLoader.h>` fails and I am unable to override `Aws::Config::AWSProfileConfigLoader`.

`install (FILES ${CONFIG_HEADERS} DESTINATION ${INCLUDE_DIRECTORY}/aws/core/config)`
should be added to the file.

**Comment by JonathanHenson** [comment]
What version are you using?

In HEAD, I see this:

https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/CMakeLists.txt#L428

**Comment by JonathanHenson** [comment]
Please reopen if you still have issues.

**Comment by tiberiuvs** [comment]
I had an old version and did not see that it was fixed. My apologies.

https://github.com/aws/aws-sdk-cpp/issues/514
