### ISSUE TITLE
Overriding AWSCredentialsProvider::GetConfigProfileFilename() causes inconsistencies/issues

### ISSUE THREAD

**Issue by tiberiuvs** [aws/aws-sdk-cpp#569]
When trying to use a custom AWSCredentialsProvider, a custom GetConfigProfileFilename() is used to specify a different configuration filepath.

However the constructor of base class ProfileConfigFileAWSCredentialsProvider uses GetCredentialsProfileFilename before it is overridden, using the original/default filepath. Later, when GetProfileDirectory() is called, it uses the new overridden function, returning a directory that is inconsistent with what was actually used.

`core/auth/AWSCredentialsProvider.cpp`

```
Aws::String ProfileConfigFileAWSCredentialsProvider::GetProfileDirectory()
{
    Aws::String profileFileName = GetCredentialsProfileFilename();
    auto lastSeparator = profileFileName.find_last_of(DIRECTORY_JOIN);
    if (lastSeparator != std::string::npos)
    {
        return profileFileName.substr(0, lastSeparator);
    }
    else
    {
        return "";
    }
}


ProfileConfigFileAWSCredentialsProvider::ProfileConfigFileAWSCredentialsProvider(long refreshRateMs) :
        m_configFileLoader(Aws::MakeShared<Aws::Config::AWSConfigFileProfileConfigLoader>(PROFILE_LOG_TAG, GetConfigProfileFilename(), true)),
        m_credentialsFileLoader(Aws::MakeShared<Aws::Config::AWSConfigFileProfileConfigLoader>(PROFILE_LOG_TAG, GetCredentialsProfileFilename())),
        m_loadFrequencyMs(refreshRateMs)
{
    auto profileFromVar = Aws::Environment::GetEnv(AWS_PROFILE_ENVIRONMENT_VARIABLE);
    if (!profileFromVar.empty())
    {
        m_profileToUse = profileFromVar;
    }
    else
    {
        m_profileToUse = DEFAULT_PROFILE;
    }

    AWS_LOGSTREAM_INFO(PROFILE_LOG_TAG, "Setting provider to read credentials from " <<  GetCredentialsProfileFilename() << " for credentials file"
                                      << " and " <<  GetConfigProfileFilename() << " for the config file "
                                      << ", for use with profile " << m_profileToUse);
}
```

**Comment by JonathanHenson** [comment]
thanks for reporting, we'll get a fix out for this shortly.

**Comment by JonathanHenson** [comment]
I'm confused about your use case, nothing in the ProfileConfigFileAWSCredentialsProvider is extendable (or virtual). If you simply want to use a different file, you can set the AWS_SHARED_CREDENTIALS_FILE environment variable. 

If you want to write your own provider, I suggest implementing the AWSCredentialsProvider interface directly.

**Comment by singku** [comment]
This is no longer a valid problem because the function has been updated.
