### ISSUE TITLE
Gateway get rest apis output is not same as aws cli

### ISSUE THREAD

**Issue by santoshsahu** [aws/aws-sdk-cpp#573]
I reported the original issue in [https://github.com/aws/aws-sdk-cpp/issues/565](#565). But it is not completely resolved. I am not allowed to reopen the issue so creating new one. After the fix pushed  to "inclulde accept header in API  gateway" request,  I do see the response coming like this

`{"item":[{"createdDate":1496048628,"id":"xxxxxxx","name":"My API"}]}`

but the field name should have been **items** instead of **item**, since in GetRestApisResult class, only GetItems() function is available. Below is the output from  aws cli result

```
~# aws apigateway get-rest-apis
{
    "items": [
        {
            "createdDate": 1496048628,
            "id": "xxxxxx",
            "name": "My API"
        }
    ]
}
```

**Comment by JonathanHenson** [comment]
Okay, I dug into this a bit deeper, looks like this is the problem:

"RestApis":{
      "type":"structure",
      "members":{
        "position":{"shape":"String"},
        "items":{
          "shape":"ListOfRestApi",
          "documentation":"<p>An array of links to the current page of <a>RestApi</a> resources.</p>",
          "locationName":"item"
        }
      },
      "documentation":"<p>Contains references to your APIs and links that guide you in how to interact with your collection. A collection offers a paginated view of your APIs.</p> <div class=\"seeAlso\"> <a href=\"http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-create-api.html\">Create an API</a> </div>"
    },

The SDK is generating this correctly, since locationName always overrides the default member name. I'll reach out to the model owner to update the model. Thanks!

**Comment by JonathanHenson** [comment]
I'll also note, this is wrong in all of our static language SDKs. It works in the CLI because of dynamic typing goodness.

**Comment by JonathanHenson** [comment]
Nevermind, I misunderstood your question. I'l get a fix out shortly.

**Comment by JonathanHenson** [comment]
fix pushed out. let us know if you have any other issues.
