### ISSUE TITLE
Segmentation fault while uploading a file using TransferManager

### ISSUE THREAD

**Issue by danny-sade** [aws/aws-sdk-cpp#574]
I’m uploading files by calling TransferManager::UploadFile() and waiting on TransferHandle::WaitUntilFinished() to complete.  File size is 100MB to 200MB.
 About once a day the system crashes at TransferManager::TriggerTransferStatusUpdatedCallback(), called by TransferManager::HandleUploadPartResponse().  Please note that m_transferConfig.transferStatusUpdatedCallback is not set.

I added some debug messages and found two race conditions that end with segmentation fault.

Case 1:
Whenever TransferManager::HandleUploadPartResponse () is “simultaneously” called for the last two parts  (by two different threads), we get the following race condition:
Thread 1 calls TransferHandle::ChangePartToCompleted() for the before-last part.
Thread 2 calls TransferHandle::ChangePartToCompleted() for the last part
Thread 1 calls TransferHandle::GetAllPartsTransactional()
Thread 2 calls TransferHandle::GetAllPartsTransactional()
Both threads evaluate (pendingParts.size() == 0 && queuedParts.size() == 0) as true and therefore both threads send completeMultipartUploadRequest and call TransferHandle::UpdateStatus().
The first thread that calls TransferHandle::UpdateStatus() notifies the m_waitUntilFinishedSignal and causes TransferHandle::WaitUntilFinished() to return. 
At this point the TransferManager object is destroyed, however the second thread keeps running and potentially accesses class members which are not valid any more, such as m_transferConfig, causing the segmentation fault.

Case 2:
Much simpler one (but much rarer):
Thread 1 calls TransferHandle::ChangePartToCompleted() for the last part
Thread 1 calls TransferHandle::UpdateStatus(), which eventually causes TransferHandle::WaitUntilFinished() to return and the TransferManager object is destroyed.  If the system is very busy, then the object is destroyed before thread 1 calls TriggerTransferStatusUpdatedCallback().  Whenever this happens thread 1 gets segmentation fault since m_transferConfig is not valid any more.

SDK version: 1.0.147
Host OS: Amazon Linux AMI 2017.03

Thanks
Danny

**Comment by singku** [comment]
@danny-sade Thank you for reporting this, we will fixed it shortly. Meanwhile, you are very welcome to submit a pull request to patch it. Customers' contribution is highly valued and appreciated.

**Comment by marcomagdy** [comment]
@danny-sade I can see the race condition. We'll get that fixed.
> At this point the TransferManager object is destroyed

You mean in your code, you delete TransferManager? I'm not 100% clear on what destroys TransferManager.

**Comment by danny-sade** [comment]
@marcomagdy Yes, my code destroys `TransferManager` after upload is finished

**Comment by marcomagdy** [comment]
Fixed in v1.1.1

**Comment by danny-sade** [comment]
@marcomagdy Although the `shared_ptr` keeps the `TransferManager `object alive, please note that there is still a race condition at `TransferManager::HandleUploadPartResponse().`
Whenever `TransferManager::HandleUploadPartResponse () `is “simultaneously” called for the last two parts (by two different threads), we get the following race condition:

Thread 1 calls `TransferHandle::ChangePartToCompleted()` for the before-last part.
Thread 2 calls `TransferHandle::ChangePartToCompleted()` for the last part
Thread 1 calls `TransferHandle::GetAllPartsTransactional()`
Thread 2 calls `TransferHandle::GetAllPartsTransactional()`

Both threads evaluate` (pendingParts.size() == 0 && queuedParts.size() == 0) `as true and therefore `completeMultipartUploadRequest` is sent _twice_ by the two threads.

The update of the parts (i.e. `ChangePartToCompleted()` and `ChangePartToFailed()` ) and the testing of completion (i.e. `pendingParts.size() == 0 && queuedParts.size() == 0 `) should be atomic.  This will guarantee that only one thread detects upload completion.

This can be implemented by adding additional boolean argument to `ChangePartToCompleted()` and `ChangePartToFailed()`.  This argument will be set to true while processing the last part and the atomicity will be ensured by the `m_partsLock` mutex.
The `completeMultipartUploadRequest` will be sent only if this boolean is true.

Thanks
Danny

**Comment by marcomagdy** [comment]
v 1.1.1 addresses the segfault. Will address the race condition next.

**Comment by marcomagdy** [comment]
@danny-sade the race-condition is fixed in v1.1.11. See https://github.com/aws/aws-sdk-cpp/commit/440e60c669721921e95776be6a36bdf82d6664e4 for details.
