### ISSUE TITLE
Why is that error?

### ISSUE THREAD

**Issue by hlherrera** [aws/aws-sdk-cpp#575]
I am trying to send a record using firehose client, 
here is a piece of code:

Aws::SDKOptions options;
Aws::InitAPI(options);
{
        QByteArray data("{\"id\":12345}");
        QByteArray encoded = data.toBase64();
        Firehose::Model::PutRecordRequest request;
        Firehose::Model::Record rec;
        rec.SetData(Aws::Utils::ByteBuffer((const unsigned char*)encoded.constData(), encoded.length()));
        request.SetRecord(rec);
        request.SetDeliveryStreamName("delivery-firehose");
        Firehose::FirehoseClient firehose;
        firehose.PutRecord(request);
}
Aws::ShutdownAPI(options);

but I had an error: 
invalid use of incomplete type 'Aws::Firehose::Model::PutRecordOutcome {aka class Aws::Utils::Outcome<Aws::Firehose::Model::PutRecordResult, Aws::Client::AWSError<Aws::Firehose::FirehoseErrors> >}'
         firehose.PutRecord(request);
when I comment the line  firehose.PutRecord(request);  everything works ok.

Do you have an example of using firehose client to send a record?

thanks.

**Comment by JonathanHenson** [comment]
have you tried \#include &lt;aws/core/utils/Outcome.h&gt;

**Comment by hlherrera** [comment]
Thanks, that fix my error!
