### ISSUE TITLE
False detection of time skew at AWSClient::AttemptExhaustively

### ISSUE THREAD

**Issue by danny-sade** [aws/aws-sdk-cpp#577]
While uploading a file using TransferManager, I saw the following scenario:

The S3 server responded with “503 Service Unavailable” (line 32 at the attached log).

While processing the response by AWSClient::AttemptExhaustively(), serverTime was evaluated as 0 (Epoch), although the “Date” header was valid (lines 34 and 58).

As a result, a time skew was detected and the m_signer->SetClockSkew() was, setting the m_clockSkew to -47 years (line 59).

While retrying, the request was sent with a time stamp of January 1970 (line 77).

The server responded with “403 Forbidden” (line 101).

While processing the 403 response by AWSClient::AttemptExhaustively(), serverTime was evaluated correctly to the “Date” header value (line 141), but now a time skew of +47 years was detected and m_clockSkew was set to +47 years (line 142).

While retrying, the request was sent with a time stamp of December 2064 (line 150), causing another 403 error.

All further requests failed with error 403, with the time stamp toggling between 1970 and 2064.

I have no idea why the processing of the 503 response failed to get the value from the “Date” header.  However, I believe that the m_clockSkew should be set with the difference between serverTime and now(), and not the difference between serverTime and m_signer->GetSigningTimestamp().

SDK version: 1.0.147
Host OS: Amazon Linux AMI 2017.03

Attached log: [sdk_2017-06-18-19.txt](https://github.com/aws/aws-sdk-cpp/files/1088684/sdk_2017-06-18-19.txt)

Thanks

Danny

**Comment by marcomagdy** [comment]
Thanks for reporting. This is a bug. Will get it fixed shortly.

**Comment by marcomagdy** [comment]
Our DateTime parser didn't handle the date format that uses the 2 digit year and we weren't checking if the parsing was successful.
Both issues have been fixed in the latest release [v1.0.159](https://github.com/aws/aws-sdk-cpp/releases/tag/1.0.159).
The trace logs you uploaded were quite helpful. Thank you.

**Comment by danny-sade** [comment]
@marcomagdy I’m afraid the issue is not closed yet.
Please note that the signing timestamp was toggling between 1970 to 2064 while processing the 403 responses, although the Date field of those responses was correctly parsed.
I think `m_signer->SetClockSkew()` should be called with the difference between `serverTime `and `now()`.

Consider the hypothetical case in which the client clock has a glitch and it skews one hour backward (e.g. from 02:00:00 to 01:00:00) and after some HTTP transactions it skews again to the correct time.  In this scenario we will get the following:

Before first skew
Server time == 02:00:00, `now()` == 02:00:00, `m_ClockSkew` == 00:00:00, SigningTimestamp == 02:00:00

The first request after the first skew is sent with the following:
Server time == 02:01:00, `now()` == 01:01:00, `m_ClockSkew` == 00:00:00, SigningTimestamp == 01:01:00

After processing the response:
Server time == 02:01:00, `now()` == 01:01:00, `m_ClockSkew` == 01:00:00, SigningTimestamp == 01:01:00
From this point the request are sent with correct SigningTimestamp. 

However the first request after the second skew is sent with the following:
Server time == 02:02:00, `now()` == 02:02:00, `m_ClockSkew` == 01:00:00, SigningTimestamp == 03:02:00

And after processing the response
Server time == 02:02:00, `now()` == 02:02:00, `m_ClockSkew `== -01:00:00, SigningTimestamp == 01:02:00

And from this point `m_ClockSkew `toggles between +01:00:00 to -01:00:00 forever.

Thanks

Danny

**Comment by marcomagdy** [comment]
Looking into it

**Comment by marcomagdy** [comment]
I see the problem. We don't reset the skew offset if the system clock is corrected. Will fix it and close this issue when released.
Thank you.

**Comment by marcomagdy** [comment]
Fixed in v1.1.1

**Comment by danny-sade** [comment]
@marcomagdy I’m afraid that this does not cover the following case:
The client clock skews one hour backwards.  This results with` m_ClockSkew` == 01:00:00.
Now the client clock skews by additional hour backwards (total of two hours). While processing the response, `diff ` == 01:00:00 and `clientDiff ` == 02:00:00.  Since `clientDiff `is out of the range, `m_ClockSkew  `is set to `diff`.
I believe `m_ClockSkew  `should always be set to `clientDiff`, regardless the value of `clientDiff`.  `clientDiff `is the difference between the server time and the client time, which is actually the skew.
Thanks
Danny

**Comment by marcomagdy** [comment]
I adjusted the test suite to reflect that case. Pushing a patch shortly.

**Comment by marcomagdy** [comment]
@danny-sade  checking in, are you still experiencing this problem with the latest version?

**Comment by danny-sade** [comment]
@marcomagdy I do not experience any time skew, so the code never gets into the relevant part...
