### ISSUE TITLE
Windows executable crashes with TransferManager (NuGet AWSSDKCPP-Transfer v1.1.1)

### ISSUE THREAD

**Issue by bawejakunal** [aws/aws-sdk-cpp#590]
**Environment**: `VS2015 | AWSSDKCPP-Transfer v1.1.1 | AWSSDKCPP-S3 v1.0.20060301.162 | AWSSDKCPP-Core v1.0.162`

I have the following simple code to download the file from an `aws s3 bucket` which I compile into an executable which keeps crashing.

```
// download a single file from aws s3 bucket
// use transfer manager
// assume Aws::InitAPI() has already been called
int downloadFile(const Aws::String &bucketName, const Aws::String &objectKey,
	const Aws::String &localFile) {

	auto s3Client = Aws::MakeShared<Aws::S3::S3Client>(S3_CLIENT_TAG);
	TransferManagerConfiguration transferConfig;
	transferConfig.s3Client = s3Client;
	transferConfig.maxParallelTransfers = 10;

	// lambda for download progress callback
	transferConfig.downloadProgressCallback =
		[](const TransferManager* transferManager, const TransferHandle& handle)
	{ std::cout << handle.IsMultipart() << std::endl; };

	// the fabled transfer manager
	TransferManager transferManager(transferConfig);
	auto transferHandle = transferManager.DownloadFile(bucketName, objectKey, localFile);
	transferHandle->WaitUntilFinished();	// block calling thread until download complete
	return 0;
}
```

Can I get some help on this ?

**Comment by singku** [comment]
We have a version error on nuget for high level services as transfer-manager. We will get that fixed soon. For now, the latest version of transfer manager is 1.0.162 instead of 1.1.1.

**Comment by bawejakunal** [comment]
Does that version support multipart downloads ?

**Comment by singku** [comment]
It does.

**Comment by bawejakunal** [comment]
is there some place where I can find the sdk reference for 1.0.1.162. The latest I can find is for 1.0.127 here: http://sdk.amazonaws.com/cpp/api/LATEST/index.html

**Comment by singku** [comment]
The document are almost the same. Since we have some internal delay to push the document out, the latest version hasn't been updated. We will fix that soon.

**Comment by singku** [comment]
Reopen if you have further questions.
