### ISSUE TITLE
Intermittent SignatureDoesNotMatch error

### ISSUE THREAD

**Issue by hkleynhans** [aws/aws-sdk-cpp#592]
Hi everyone,

We are intermittently experiencing SignatureDoesNotMatch errors (around 10% of the time on a specific set of machines).  When we increase the logging, the error disappears.  This makes it rather hard to reproduce the error.  It only happens with smallish files (~500k) 

It feels like it could be a timing issue; but hard to prove/disprove.  Anybody else seeing this?  Any ideas of alternative ways to try reproduce this error?

**Comment by singku** [comment]
Is there time skew on your client machine? We have pushed out a fix on time skew problem. Hopefully it can fix your problem.

**Comment by hkleynhans** [comment]
This version works for us: https://github.com/aws/aws-sdk-cpp/commit/7925eaf573f7f0f7cb138d0a88803f5b1ec5a1dd

It fails on this version: https://github.com/aws/aws-sdk-cpp/commit/167bbc164448e3b82c766eba8a9f6e133a606cbe

Will have to try narrow it down a bit more.

**Comment by marcomagdy** [comment]
Please reopen if you're still getting those errors with the latest release.
