### ISSUE TITLE
AWSTransfer Download to std::stringstream instead of file

### ISSUE THREAD

**Issue by AcidLeroy** [aws/aws-sdk-cpp#595]
I am having problems with the AwsTransfer library, particularly on the "DownloadFile" function. Ideally, I do not want to write to a file and then have to read the contents back into memory. Your integration tests here: https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-transfer-tests/TransferTests.cpp#L194-L235 check the uploaded file by downloading to an FStream. I am able to successfully do this; however, I have not been able to successfully implement the this to an `std::stringstream`. For small transfers (less than 20MB) I don't seem to have problems, but when I increase the size to 21MB, I no longer get the entire file. Here is my attempt: 

```

std::shared_ptr<std::stringstream> AwsTransfer::SyncDownload(const std::string& bucket, const std::string& key) {
    std::shared_ptr<std::stringstream> contents = std::make_shared<std::stringstream>();
    std::shared_ptr<TransferHandle> request = m_transfer->DownloadFile(bucket, key, [&contents]() {
        std::iostream* out = Aws::New<std::iostream>(allocationTag, contents->rdbuf());
        return out;
    });

    request->WaitUntilFinished();

    return contents;
}
```

Do I need to preallocate the size of the stringstream before passing?

**Comment by JonathanHenson** [comment]
does the file contain text only or also binary data? If binary data you need to tell stringstream to not pay attention to null characters. Have you tried with std::stringstream::binary?

**Comment by AcidLeroy** [comment]
@JonathanHenson Thanks for the reply. I am almost always pulling down binary data (images etc), I'll give binary a try and see if that resolves the issue.

**Comment by AcidLeroy** [comment]
@JonathanHenson Just revisited the code and it looks like the test file we are sending and then downloading doesn't contain null characters and we still having the issue. The file  contains "0123456789".... repeated over and over to meet the desired upload and download test size. Like I mentioned in the original post, we don't notice any problems with the tests until we get about ~20MB. I verified that the AWSTransfer upload works great by pulling the image down with the AWS CLI. But when trying to use the AWSTransfer download function, I don't get the entire file size. I'll go ahead and make the change with the binary safety as well.

**Comment by kwach** [comment]
If I'm not mistaken the ~20MB is being downloaded in one thread and therefore is written to your stream from its very begging. I observed that for bigger files there is good chance of writing to the stream in just about random sequence (as the parts come).

In `TransferHandle.cpp:358`, there is:
```
            partStream->seekg(0);
            m_downloadStream->seekp(writeOffset);
            (*m_downloadStream) << partStream->rdbuf();
            m_downloadStream->flush();
```
Tell me if I'm wrong here, but no standard in-memory-stream is able to seek beyond already written memory. I mean it's ok to seek through the stream when it's full of data. You can't seek past it in attempt to write data further. That is OK for files though.

**Comment by singku** [comment]
An example could be found here
https://github.com/awsdocs/aws-doc-sdk-examples/pull/885
