### ISSUE TITLE
NuGet  v1.1.4 fails to construct TransferManager from TransferManagerConfiguration

### ISSUE THREAD

**Issue by bawejakunal** [aws/aws-sdk-cpp#598]
I am noticing the following compile time error on upgrading to v1.1.4 via NuGet package manager.

```
error C2248: 'Aws::Transfer::TransferManager::TransferManager': cannot access private member declared in class 'Aws::Transfer::TransferManager'
```

**Comment by JonathanHenson** [comment]
yes for safety reasons we had to move everything to shared_ptr. You need to call the Create() function
