### ISSUE TITLE
Bug in XmlSerializer:: DecodeEscapedXmlText()

### ISSUE THREAD

**Issue by patilarpith** [aws/aws-sdk-cpp#599]
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/utils/xml/XmlSerializer.cpp#L35
There is an extra semicolon after ```&amp;```

**Comment by singku** [comment]
Thanks for fixing this. Will merge in short.

**Comment by patilarpith** [comment]
Thanks @singku & @JonathanHenson  for the quick turnaround
