### ISSUE TITLE
Thread safety of Aws::S3::S3Client?

### ISSUE THREAD

**Issue by RolefH** [aws/aws-sdk-cpp#601]
Can I call the methods like GetObject, DeleteObject, HeadObject, and the like, concurrently in different threads at the same instance of Aws::S3::S3Client, or do I have to care about thread safety in my user code? In other words, can I share one Aws::S3::S3Client instance with different threads without worrying about thread safety?

**Comment by Bu11etmagnet** [comment]
You should always care about thread safety.
`const` methods should be callable on the same object from different threads.

**Comment by JonathanHenson** [comment]
It's thread-safe to call the client from multiple threads assuming you are only calling const methods.
