### ISSUE TITLE
pkgconfig (.pc) file should not include all C and C++ flags

### ISSUE THREAD

**Issue by hkleynhans** [aws/aws-sdk-cpp#603]
https://github.com/aws/aws-sdk-cpp/blob/a98228f75a28f406ff0f736c22e15e6ff373640f/toolchains/pkg-config.pc.in

Contains `Cflags: -I${includedir} @CMAKE_C_FLAGS@ @CMAKE_CXX_FLAGS@` which pulls in all of the flags used to compile aws-sdk-cpp.  That may not be the flags that a client wishes to use.

Could we limit what gets placed into the .pc file to the absolute minimum required?

**Comment by JonathanHenson** [comment]
We've added this to our backlog. We've been transitioning from older cmake style to using more modern targets. This particular piece is caught in the middle of us still using CMAKE_CXX_FLAGS.

**Comment by Ericson2314** [comment]
https://github.com/aws/aws-sdk-cpp/blob/a98228f75a28f406ff0f736c22e15e6ff373640f/toolchains/pkg-config.pc.in It doesn't look this this was ever done?

**Comment by Ericson2314** [comment]
I still get
```bash
$ pkg-config --cflags aws-cpp-sdk-s3
-fno-exceptions -std=c++11 -fno-exceptions -std=c++11 -I/nix/store/k91i8i4j6fnr07n0z7c2d2bf20hzm4bi-aws-sdk-cpp-1.11.318-dev/include
```
The `-fno-exceptions -std=c++11 -fno-exceptions -std=c++11` isn't very ideal.
