### ISSUE TITLE
How to get metrics from S3 logfiles when TransferManager is used for multipart downloads? 

### ISSUE THREAD

**Issue by mchrist152** [aws/aws-sdk-cpp#609]
We are using the TransferManager to download multipart downloads of large files.  It works well, but how do we get metrics from the S3 log files?  In our testing we have seen very little difference between a successful and unsuccessful download log file.  Also, the only way we know of to tie all of the logfiles together is using the key and the ip address.  But that will not always be accurate (for example, what if the user retries 20 minutes after his first failure).  We would love to be able to pass custom parameters to the Request-URL to tie these together and to give us some feedback to go on but we are not sure how to do that with the TransferManager.  Is anybody else running into similar issues?  We are using ELK and are very capable of analyzing these types of S3 logfiles.  They just don't appear to contain enough information to work with.  Any ideas?

**Comment by marcomagdy** [comment]
> We would love to be able to pass custom parameters to the Request-URL to tie these together and to give us some feedback

Are you able to do that *without* TransferManager, for example using S3Client directly?
I'm asking because I'm not sure S3 supports such a feature.

**Comment by mchrist152** [comment]
We didn't need to previously because we had a single logfile per download.  No need to tie a bunch of logfiles together.  It was a much simpler problem.  But I assumed it was possible based on the S3 documentation I saw on the AWS site.  Here is an excerpt:

**Custom Access Log Information**
You can include custom information to be stored in the access log record for a request by adding a custom query-string parameter to the URL for the request. Amazon S3 will ignore query-string parameters that begin with "x-", but will include those parameters in the access log record for the request, as part of the Request-URI field of the log record. For example, a GET request for "s3.amazonaws.com/mybucket/photos/2014/08/puppy.jpg?x-user=johndoe" will work the same as the same request for "s3.amazonaws.com/mybucket/photos/2014/08/puppy.jpg", except that the "x-user=johndoe" string will be included in the Request-URI field for the associated log record. This functionality is available in the REST interface only.

If we could do the above then we could compile metrics on these downloads; otherwise, it's going to be really difficult.  BTW, thanks for responding.

**Comment by marcomagdy** [comment]
Will add it to the backlog. Thanks.

**Comment by mchrist152** [comment]
Hello Marcomagdy, I'm wondering about the current status of this backlog item. We still need it and I'm wondering if it has been included in any release? If not, is it scheduled to release any time in the future?

Thanks

**Comment by mchrist152** [comment]
Thanks, that would be great

**Comment by mchrist152** [comment]
Hi marcomagdy,

I've heard this feature has been implemented. That is great news if true. Do you have any idea of when it will be released?

Thanks again for all of your help and work on this.

**Comment by singku** [comment]
@mchrist152 This feature has been released in commit: https://github.com/aws/aws-sdk-cpp/commit/e81ec4178e29fcd8c5f650128d0c66ecbe6d3cad.

Basic usage:
If you use S3 directly, you can add customized access log tag in any request that support access log, such as
```
Aws::S3::GetObjectRequest getRequeset;
getRequest.AddCustomizedAccessLogTag("x-key", "val"); //Add one by one
getRequest.SetCustomizedAccessLogTag(<key, val> map); //Reset all tags.
```
Right now, the only request doesn't support this method is ListBucketsRequest.
If the log tag key is not started with "x-", it will be ignored. Currently we don't support identical log tag keys.
```
getRequest.AddCustomizedAccessLogTag("x-key", "val1");
getRequest.AddCustomizedAccessLogTag("x-key", "val2");
```
The first one will be overridden.

If you access S3 via `TrasferManager`, you can assign your intended tags map to `customizedAccessLogTag` of `TransferManagerConfiguration`, that used to initiate a `TransferManager` instance. Then these tags will be passed to S3 requests used inside `TransferManager`.


Reopen and let us know if you have any further question.
