### ISSUE TITLE
Why does the SDK hash short strings before comparing?

### ISSUE THREAD

**Issue by jmsundar** [aws/aws-sdk-cpp#610]
For example [here](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-s3/source/model/MetadataDirective.cpp#L39):
```
static const int COPY_HASH = HashingUtils::HashString("COPY");
static const int REPLACE_HASH = HashingUtils::HashString("REPLACE");

MetadataDirective GetMetadataDirectiveForName(const Aws::String& name)
{
    int hashCode = HashingUtils::HashString(name.c_str());
    if (hashCode == COPY_HASH)
    {
        return MetadataDirective::COPY;
    }
    else if (hashCode == REPLACE_HASH)
    {
        return MetadataDirective::REPLACE;
    }
    EnumParseOverflowContainer* overflowContainer = Aws::GetEnumOverflowContainer();
    if(overflowContainer)
    {
        overflowContainer->StoreOverflow(hashCode, name);
        return static_cast<MetadataDirective>(hashCode);
    }

    return MetadataDirective::NOT_SET;
}
```
The function compares the hash of a four character string literal against that of a `Aws::String`. Would it not be better to compare against `"COPY"` and `"REPLACE"` and compute the hash only (in the worst case) when the Directive is neither of these?

**Comment by marcomagdy** [comment]
If I had to guess, probably because comparing hash values (integers) is much faster than comparing strings.
In this particular case, however, it might be an overkill. Not because the strings are short though, but because there're only two enum values that we compare against.

Are you experiencing a problem with this code?

**Comment by singku** [comment]
Closing because question was answered and no further response from user.
