### ISSUE TITLE
How to get ec2 instance self public IP address?

### ISSUE THREAD

**Issue by caoyangjiang** [aws/aws-sdk-cpp#611]
I am using aws-sdk directly on an ec2 instance.  I want to write a simple program that runs on an ec2 instance and print its public IP address. What is the proper way to do it through aws sdk? Thanks!

**Comment by singku** [comment]
EC2Client has a function named DescribeAddresses, the public ips sit in the response class.
You can basically look at the documentation of each service to find out what you need.

**Comment by caoyangjiang** [comment]
Thanks for your quick response. I have just tried what you said. It does return public addresses. However it returns all public IP addresses for all instances. How could I find out which one is associated with the instance that is running the program?

**Comment by singku** [comment]
http://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_e_c2_1_1_model_1_1_describe_addresses_request.html#a806ee126eda52e7e3d5642f5acb6a23c

**Comment by singku** [comment]
@caoyangjiang Are you able to achieve what you want?

**Comment by caoyangjiang** [comment]
Hi Singku,

I can't see how it can be used for what I need. The filters requires filter name such as instance-id, etc. When I am on an instance, unless there is a way to return instance id, I can't use the filter to find its address.

I did it in a none-native way but I think it is not bullet-proof. I first find out the local address of the instance which is the private address. Then I get all the addresses using DescribeAddress. Since it gets both private and public address for all instances, I can  search through the private addresses of all instances. Once a match is found, the instance public address is returned.

If there is a better way, please let me know

Thanks,

Caoyang

**Comment by singku** [comment]
@caoyangjiang Glad to here you find a way out. Most of the operations of each service is not supplied by SDK itself, they are translated from service model of each service. And you can find the detailed description of operation from the documentation of specific service. Such as [AssociatedAddress](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateAddress.html) of EC2. At the bottom page there is a link linked to CPP implementation of the API.

Reopen if you have further question.
