### ISSUE TITLE
Client side monitoring

### ISSUE THREAD

**Issue by mchatt** [aws/aws-sdk-cpp#618]
Hello,
We are starting to use the S3 cpp sdk and we are looking for a way to have client side metrics. This feature exists on the java sdk as explained here : [https://aws.amazon.com/fr/blogs/developer/enabling-metrics-with-the-aws-sdk-for-java](url)

Is it possible to have similar metrics with the cpp sdk ? If not, do you plan to implement it and in what timeframe?

Thank you in advance.

**Comment by bretambrose** [comment]
That could be an interesting feature.  What kind of metrics would you like to see in a C++ solution?

**Comment by mchatt** [comment]
For NoSQL datastores, we implemented some monitoring collection that give us a a per minute view of : latency histograms, max&min latency, throughput, error rates and retries. Those metrics are aggregated per operations ( get, set, delete ... ).
We want to setup similar monitoring for S3 and since the java sdk is already providing this feature, I hoped to have them directly with the aws cpp sdk.
We would be happy to discuss further and contribute.

**Comment by jwustrack-amadeus** [comment]
Hello,

I am a colleague of @mchatt and would like to give some additional details on what we had in mind.
To collect the metrics we are interested in (mainly latency, throughput, errors and retries on S3 operations), we would like to add an interface to the sdk on which different metrics aggregators can be plugged.
Every operation would trigger a callback on this interface containing the raw metrics specific to the operation (type of operation, result, payload, latency, retries...). Any plugged collector can then compute the aggregated metrics it's interested in (sum, histograms, min, max, average, ...).

If you agree we will share a PR with a design proposal to have something concrete to discuss.

Cheers,
Jonas

**Comment by singku** [comment]
Client Side monitoring has been supported.
Please take a look at https://github.com/aws/aws-sdk-cpp/tree/master/aws-cpp-sdk-core/include/aws/core/monitoring

You could also follow this set up in Java sdk with default metrics mechanism. It's the same setting for C++ SDK
