### ISSUE TITLE
Problems using SDK AWS CPP on QtCreator in Windows

### ISSUE THREAD

**Issue by francoatmega** [aws/aws-sdk-cpp#621]
Hi, i'am having troubles to compile a project with aws sdk in QtCreator. 
I follow the steps on #436 but didn't'work well.

Here's the code that i'am trying to compile:

`#include <QApplication>
#include <QSplashScreen>
#include <QThread>
#include <windows.h>
#include <aws/core/SDKConfig.h>
#include <aws/core/Aws.h>

#include "wanconfig.h"

bool isConfigured(){

    HANDLE file;
    char Buffer[2048];
    DWORD bytesRead = 0,bytesMaxRead= 2047;
    WIN32_FIND_DATA x;

    if(INVALID_HANDLE_VALUE == FindFirstFile((LPCWSTR)"wanglacier.cfg",&x)){

        //SEM ARQUIVO DE CONFIGURAÇÃO
        return false;

    }else{

        //COM ARQUIVO DE CONFIGURAÇÃO
        return true;
    }

}

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    QSplashScreen *splash = new QSplashScreen;
    splash->setPixmap(QPixmap("splash.png"));
    splash->show();

    Aws::SDKOptions options;
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Info;
    Aws::InitAPI(options);

    Aws::ShutdownAPI(options);

    QThread::sleep(2);
    splash->close();

    WanConfig w;

    if(isConfigured()){

    }else{

        w.show();

    }

    return a.exec();
}`

If I only use this:

`Aws::SDKOptions options;
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Info;`

The linker works well.
But using InitAPI and ShutdownAPI the linker retrieves:

12:13:46: Running steps for project WanGlacier2...
12:13:46: Configuration unchanged, skipping qmake step.
12:13:47: Starting: "C:\Qt\Tools\mingw530_32\bin\mingw32-make.exe" 
C:/Qt/5.9.1/mingw53_32/bin/qmake.exe -o Makefile ../WanGlacier2/WanGlacier2.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug
C:/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile.Debug
mingw32-make[1]: Entering directory 'C:/Users/francoatmega/Documents/build-WanGlacier2-Desktop_Qt_5_9_1_MinGW_32bit-Debug'
g++ -Wl,-subsystem,windows -mthreads -o debug/WanGlacier2.exe debug/main.o debug/wanconfig.o debug/wanconfigbd.o debug/wanconfigaws.o debug/waninicial.o debug/moc_wanconfig.o debug/moc_wanconfigbd.o debug/moc_wanconfigaws.o debug/moc_waninicial.o  -lmingw32 -LC:/Qt/5.9.1/mingw53_32/lib C:/Qt/5.9.1/mingw53_32/lib/libqtmaind.a -LC:/utils/my_sql/my_sql/lib -LC:/utils/postgresql/pgsql/lib -lshell32 C:/Qt/5.9.1/mingw53_32/lib/libQt5Cored.a -LD:/libs -laws-cpp-sdk-core C:/Qt/5.9.1/mingw53_32/lib/libQt5Widgetsd.a C:/Qt/5.9.1/mingw53_32/lib/libQt5Guid.a C:/Qt/5.9.1/mingw53_32/lib/libQt5Cored.a 
debug/main.o: In function `Z5qMainiPPc':
C:\Users\francoatmega\Documents\build-WanGlacier2-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../WanGlacier2/main.cpp:41: undefined reference to `Aws::InitAPI(Aws::SDKOptions const&)'
C:\Users\francoatmega\Documents\build-WanGlacier2-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../WanGlacier2/main.cpp:43: undefined reference to `Aws::ShutdownAPI(Aws::SDKOptions const&)'
collect2.exe: error: ld returned 1 exit status
Makefile.Debug:85: recipe for target 'debug/WanGlacier2.exe' failed
mingw32-make[1]: Leaving directory 'C:/Users/francoatmega/Documents/build-WanGlacier2-Desktop_Qt_5_9_1_MinGW_32bit-Debug'
Makefile:36: recipe for target 'debug' failed
mingw32-make[1]: *** [debug/WanGlacier2.exe] Error 1
mingw32-make: *** [debug] Error 2
12:13:57: The process "C:\Qt\Tools\mingw530_32\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project WanGlacier2 (kit: Desktop Qt 5.9.1 MinGW 32bit)
When executing step "Make"
12:13:57: Elapsed time: 00:10.

As can  we see unsolved reference erros, the aws-cpp-sdk-core.lib is in D:/libs directory.

I have tested a similar code on Visual Studio and works like a charm:

`#include "stdafx.h"
#include <stdio.h>
#include <aws/core/Aws.h>

#pragma comment(lib, "aws-cpp-sdk-core.lib")

int main()
{
	Aws::SDKOptions options;
	Aws::InitAPI(options);

	printf("AWS inicializado...");

	Aws::ShutdownAPI(options);
    return 0;
}`

Anyone can help me to solve this?

**Comment by JonathanHenson** [comment]
what happens if you set an absolute path for this:

 -laws-cpp-sdk-core

**Comment by francoatmega** [comment]
Bro, I think the problem is I have compiled the aws SDK cpp with Visual Studio, and I'am using with another compiler.
But due to #45 I was thinking in use the aws python sdk...

**Comment by singku** [comment]
It's better to attach your build script here. What do you mean by using with another compiler? Were you building the library as dlls with Visual studio, and you want to utilize it in MinGw for your Qt project?

**Comment by francoatmega** [comment]
Yes, i compiled the AWS SDK lib in Visual Studio, but when I will use in QT Creator who uses MinGW the compiler cannot find the functions.

The .pro file:

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = WanGlacier2
TEMPLATE = app

# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

INCLUDEPATH += \
    D:\3include \

LIBS += \
    -LD:\1libs \
    -laws-cpp-sdk-core

SOURCES += \
        main.cpp \
    wanconfig.cpp \
    wanconfigbd.cpp \
    wanconfigaws.cpp \
    waninicial.cpp

HEADERS += \
    wanconfig.h \
    wanconfigbd.h \
    wanconfigaws.h \
    waninicial.h

FORMS += \
    wanconfig.ui \
    wanconfigbd.ui \
    wanconfigaws.ui \
    waninicial.ui

**Comment by TyrasNistru** [comment]
AFAIK, you can't use Visual Studio-compiled libraries with MinGW.

**Comment by francoatmega** [comment]
This issue can be closed, in the end  I stared the project in python, boto3 works like I charm!
