### ISSUE TITLE
Get Multipart Upload File Etag

### ISSUE THREAD

**Issue by bawejakunal** [aws/aws-sdk-cpp#623]
For multipart uploads using `TransferManager`, is there a way to get the final `ETag` of file without making an extra `HeadObject` request ?

**Comment by JonathanHenson** [comment]
Transfer Handle contains the metadata.

**Comment by bawejakunal** [comment]
https://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_transfer_1_1_transfer_handle.html#a712dbb13626b689281a11ea805ee22a4 mentions that this specifically returns the metadata placed during upload which doesn't includes the `etag`. I tried `ETag`, `etag` and `Etag` in the map returned from `GetMetadata` and no such key was found in the metadata map.

**Comment by tnguyen-Alta** [comment]
How do I get off this mailing list? 

Tim Yost - VP Business Development 
p :: (800) 676-1281 x8317 
m:: (949) 478-1112 
a :: 3191 Red Hill Avenue, Suite 100 - Costa Mesa, California 92626

**Comment by singku** [comment]
You can either **Unsubscribe** this conversation from left side bar or **Unwatch** the entire conversations from top menu.

**Comment by JonathanHenson** [comment]
We'll add it. Thanks for letting us know.

**Comment by singku** [comment]
Now available, will be pushed out later today
