### ISSUE TITLE
Duplicate calls to Aws::InitAPI() with different options

### ISSUE THREAD

**Issue by shuzhang1989** [aws/aws-sdk-cpp#624]
What will be the behavior of I call Aws::InitAPI() with different options multiple times (without calling ShutdownAPI() for previous InitApi() calls), and in multiple threads?

Will the later one simply overwrite the previous setup, or there will be potentially some issues?

**Comment by shuzhang1989** [comment]
@JonathanHenson

**Comment by singku** [comment]
I would say it's depend on your usage of the SDK. When you call InitAPI(), you basically initialize your  memory management system's state if used customized mem management system. You also initialize network and crypto libraries' status, such as for curl and openssl. In most scenarios, you will be fine. But if your code relies on these status or function addresses, you will have problem.

**Comment by JonathanHenson** [comment]
This would be bad. What's your use case, maybe we can figure out a good way forward.

**Comment by shuzhang1989** [comment]
@JonathanHenson yes, i actually found that we cannot initailize twice with difference options, it will cause segfault. i enforced my code to make sure init and finish always appear in pairs.

**Comment by JonathanHenson** [comment]
yes, initializing it twice period, even without the different options would be unsafe. I assume your issue is solved?

**Comment by shuzhang1989** [comment]
it's solved :)
