### ISSUE TITLE
CurlHttpClient missing cookie when followRedirects is enabled

### ISSUE THREAD

**Issue by PoundKey** [aws/aws-sdk-cpp#627]
Hello AWS C++ SDK Team,

When we use CurlHttpClient to send HTTP request to some server, we might get a 301 status code and by setting followRedirects to true, it should automatically follow the redirect and complete the entire request.

This is set through:
```cpp
curl_easy_setopt(connectionHandle, CURLOPT_FOLLOWLOCATION, 1L);
```

However, some servers might require client side cookie to be sent back to the server to proceed the request and response cycle.

This is not set in the CurlHttpClient, and can be set through:
```cpp
curl_easy_setopt(m_connectionHandle, CURLOPT_COOKIEFILE, "");
```

I tried adding this line of code to the CurlHttpClient.cpp #Line 428. However it still does not work.

I wrote my own curl http client and with this option being set, the request - redirect - response cycle works properly.

Thanks,

**Comment by singku** [comment]
Have you set clientConfig.followRedirects to be true?

**Comment by singku** [comment]
Then I don't understand why it's not working. Are you sure you linked against the newly compiled core library?

**Comment by singku** [comment]
Can you please attach the corresponding trace level log so we can further inspect?

**Comment by PoundKey** [comment]
1. I am with SDK 1.0.103
2. [CURLOPT_COOKIEFILE](https://curl.haxx.se/libcurl/c/CURLOPT_COOKIEFILE.html) need to be set in order for the cookie to take effect when re-directing. Without this being set LibCurl will not send cookie along with the following requests.
3. Even after I set this option and re-compile sdk-core, still did not work. (Maybe I had done something wrong)
4. Will see if I can generate the trace level log.

Thanks
