### ISSUE TITLE
AWSProfileConfigLoader can only read predefined profile attribute

### ISSUE THREAD

**Issue by PoundKey** [aws/aws-sdk-cpp#628]
Hello AWS C++ SDK Team,

We are trying using AWSProfileConfigLoader.cpp to read some customized profile attributes, and realized that it's restricted to read only a small set of predefined attributes:
```cpp
        static const char* const REGION_KEY = "region";
        static const char* const ACCESS_KEY_ID_KEY = "aws_access_key_id";
        static const char* const SECRET_KEY_KEY = "aws_secret_access_key";
        static const char* const SESSION_TOKEN_KEY = "aws_session_token";
        static const char* const ROLE_ARN_KEY = "role_arn";
        static const char* const SOURCE_PROFILE_KEY = "source_profile";
```
 It's possible to add a GetAttributeValue(Aws::String in_attrName) method to this class so that we can get some customized profile attribute values? For instance, plugin_name, idp_host, etc

```
[adfs-profile]
plugin_name = ADFS
idp_host = server.adfs.internal
ssl_insecure = true

```

Thanks,

**Comment by PoundKey** [comment]
Java SDK already have this feature implemented.

**Comment by singku** [comment]
Profile is in format of:
```
[profile1]
key11=val11
key12=val12
..

[profile2]
key21=val21
key22=val22
..

[..]
```
Do you want the attr to be the name of profile or key's name?

**Comment by PoundKey** [comment]
It's actually the key's name.

[BasicProfile.java](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/profile/internal/BasicProfile.java) Line # 64 from AWS JAVA SDK



Thanks.

**Comment by singku** [comment]
ConfigLoader will load multiple profiles for you, so that expected function maybe sit in Profile instead of ConfigLoader? Otherwise you would have to pass another identifier to avoid key's name collision in multiple profiles.

**Comment by PoundKey** [comment]
Yes you are correct.
The problems are:
1.  ConfigLoader only read those predefined keys from a profile file e.g., role_arn 
2. And each individual profile only saves and has  access to those predefined keys as well.

For instance, this is the Profile class:
```cpp
       class Profile
        {
        public:
            inline const Aws::String& GetName() const { return m_name; }
            inline void SetName(const Aws::String& value) { m_name = value; }
            inline const Aws::Auth::AWSCredentials& GetCredentials() const { return m_credentials; }
            inline void SetCredentials(const Aws::Auth::AWSCredentials& value) { m_credentials = value; }
            inline const Aws::String& GetRegion() const { return m_region; }
            inline void SetRegion(const Aws::String& value) { m_region = value; }
            inline const Aws::String& GetRoleArn() const { return m_roleArn; }
            inline void SetRoleArn(const Aws::String& value) { m_roleArn = value; }
            inline const Aws::String& GetSourceProfile() const { return m_sourceProfile; }
            inline void SetSourceProfile(const Aws::String& value ) { m_sourceProfile = value; }

        private:
            Aws::String m_name;
            Aws::String m_region;
            Aws::Auth::AWSCredentials m_credentials;
            Aws::String m_roleArn;
            Aws::String m_sourceProfile;
        };

```

**Comment by singku** [comment]
I understand this portion, the fields are restricted to certain names. We will discuss later about possible expansion.

**Comment by singku** [comment]
Supported
