### ISSUE TITLE
Aws::InitAPI() Crashes

### ISSUE THREAD

**Issue by TyrasNistru** [aws/aws-sdk-cpp#634]
I'm using AWS SDK compiled with Visual Studio 2015.

This code used to work when using VS2013, but now, it crashes when I call InitAPI. The debugger points an Access Violation in the following line in Aws.cpp:

```
if(options.cryptoOptions.aes_CBCFactory_create_fn)
{
>    Aws::Utils::Crypto::SetAES_CBCFactory(options.cryptoOptions.aes_CBCFactory_create_fn());
}
```

I'm calling InitAPI() with an default-constructed Aws::SDKOptions.

Already tried to rebuild the libraries... What could be happening?

**Comment by singku** [comment]
aes_CBCFactory_create_fn is a member of cryptoOptions and the type is std::function<type>. by default ctor, it will be set to nullptr. If you call InitAPI with a default option, this line of code will not be executed.

You can write a simplest test code within the same environment to see what might happen.

```
int main()
{
    Aws::SDKOptions options;
    Aws::InitAPI(options);
    Aws::ShutdownAPI(options);
    return 0;
}
```

**Comment by TyrasNistru** [comment]
I'm sorry for wasting your time. I was mixing MSVC versions (linking a VS2013-built app against a VS2015-built AWS API library) And looks like that was the reason.

But now, I'm having the problem reported in Issue #613 ...
