### ISSUE TITLE
NuGet and Visual Studio 2017 bins - v141

### ISSUE THREAD

**Issue by MattyBoy4444** [aws/aws-sdk-cpp#635]
Can we get the NuGet package updated with v141 bins?

**Comment by JonathanHenson** [comment]
yes, we were planning on just adding the VS2015 binaries to the nuget release, since the ABI matches.

**Comment by JonathanHenson** [comment]
would this work for you?

**Comment by MattyBoy4444** [comment]
Need the VS 2017 bins.  v141.  Thanks

**Comment by MattyBoy4444** [comment]
Please fix!

**Comment by singku** [comment]
@MattyBoy4444 Thanks for your patience. Now v141 is available on Nuget.
