### ISSUE TITLE
Assertion `s_HttpClientFactory' failed

### ISSUE THREAD

**Issue by jugg1024** [aws/aws-sdk-cpp#639]
this is the exception stack trace:

search_server: /data01/home/jugg1024/workspace/video_search/third_party/packages/aws-sdk-cpp/aws-cpp-sdk-core/source/http/HttpClientFactory.cpp:184: std::shared_ptr<Aws::Http::HttpRequest> Aws::Http::CreateHttpRequest(const Aws::Http::URI&, Aws::Http::HttpMethod, const IOStreamFactory&): Assertion `s_HttpClientFactory' failed.
*** Aborted at 1503295429 (unix time) try "date -d @1503295429" if you are using GNU date ***
PC: @     0x7f0ad4aa4067 (unknown)
*** SIGABRT (@0x3e800004cca) received by PID 19658 (TID 0x7f0ac39eb700) from PID 19658; stack trace: ***
    @     0x7f0ad577e890 (unknown)
    @     0x7f0ad4aa4067 (unknown)
    @     0x7f0ad4aa5448 (unknown)
    @     0x7f0ad4a9d266 (unknown)
    @     0x7f0ad4a9d312 (unknown)
    @     0x7f0ad78b4806 Aws::Http::CreateHttpRequest()
    @     0x7f0ad7835919 Aws::Client::AWSClient::AttemptOneRequest()
    @     0x7f0ad783493e Aws::Client::AWSClient::AttemptExhaustively()
    @     0x7f0ad78362f6 Aws::Client::AWSClient::MakeRequestWithUnparsedResponse()
    @     0x7f0ad6e4106c Aws::S3::S3Client::GetObject()
    @           0x548491 video_search::CurlDownloader::S3_Download()

this exception happens randomly, for some times, GetObject() is OK, but other times, it core dumped.

this is how i build it:
   cmake -DCMAKE_INSTALL_PREFIX=$PREFIX_DIR \
       -DBUILD_ONLY="s3" \
       -DCMAKE_INCLUDE_PATH=$CURL_INCLUDE_DIR \
       -DAWS_CUSTOM_MEMORY_MANAGEMENT=1 \
       -DCURL_LIBRARY=$CURL_LIB_DIR ..

this is the code:
 89 void CurlDownloader::S3_Download(const std::string key, const std::string save_path) {
 90   if (headers_.size() < 3) {
 91     throw DownloadException("headers should contain [AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY bucket_name]");
 92   }
 93   Aws::SDKOptions options;
 94   Aws::InitAPI(options);
 95
 96   const char* AWS_ACCESS_KEY_ID = headers_[0].c_str();
 97   const char* AWS_SECRET_ACCESS_KEY = headers_[1].c_str();
 98   const Aws::String bucket_name = headers_[2].c_str();
 99   Aws::Client::ClientConfiguration configuration;
100   if (headers_.size() == 4) {
101     configuration.region = headers_[3].c_str();
102   } else {
103     configuration.region = "us-east-1";
104   }
105   configuration.scheme = Aws::Http::Scheme::HTTPS;
106   configuration.connectTimeoutMs = 30000;
107   configuration.requestTimeoutMs = 60000;
108   const Aws::String key_name = key.c_str();
109   LOG(INFO) << "Downloading " << key_name << " from S3 bucket: " << bucket_name << " to " << save_path;
110
111   try {
112     Aws::Auth::AWSCredentials credentials(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY);
113     Aws::S3::S3Client s3_client(credentials, configuration);
114     Aws::S3::Model::GetObjectRequest object_request;
115     object_request.WithBucket(bucket_name).WithKey(key_name);
116     LOG(INFO) << "start to get";
117     auto get_object_outcome = s3_client.GetObject(object_request);
118     LOG(INFO) << "get done";
119     if (get_object_outcome.IsSuccess()) {
120       LOG(INFO) << "get suc";
121       Aws::OFStream local_file;
122       local_file.open(save_path.c_str(), std::ios::out | std::ios::binary);
123       LOG(INFO) << "start to right";
124       local_file << get_object_outcome.GetResult().GetBody().rdbuf();
125       LOG(INFO) << "Downloading " << key_name << " Success";
126     } else {
127       std::stringstream err;
128       err << "GetObject error: " <<
129         get_object_outcome.GetError().GetExceptionName() << " " <<
130         get_object_outcome.GetError().GetMessage();
131       LOG(ERROR) << "s3 download [" << key << "] exception " << get_object_outcome.GetError().GetMessage();
132       throw DownloadException(err.str());
133     }
134   } catch (const std::exception& ex) {
135     std::stringstream err_ss;
136     err_ss << "s3 download [" << key << "] exception "
137         << ex.what();
138     LOG(ERROR) << "s3 download [" << key << "] exception " << ex.what();
139     throw DownloadException(err_ss.str());
140   }
141   Aws::ShutdownAPI(options);
142 }

any ideas ?

**Comment by jugg1024** [comment]
problem solved

**Comment by iceboundflame** [comment]
what was the solution?

**Comment by weipihui** [comment]
Can you please share how you solved the problem? Thanks!

**Comment by subramanianm-sacumen** [comment]
When Aws::ShutdownAPI() is interleaved with Aws::InitAPI() calls, these kind of connection related issues may be found, especially in threaded sources.
