### ISSUE TITLE
DynamoDB multiple conditional UpdateItemRequests return "conditional request failed" errors

### ISSUE THREAD

**Issue by caoyangjiang** [aws/aws-sdk-cpp#640]
I am trying to make two UpdateItemRequests back to back. One will have deliberate false condition and the other one will have true condition. If the UpdateItemRequest with false condition runs before the UpdateItemRequest wth true condition, both returns "conditional request failed". This is not right because the second request should successfully update the item and returns success. In fact, when I check the table content through aws console, the item does get updated.  I also noticed this is kind random. It seems to solve the problem if I insert a sleep function between the two calls. If I reverse the order of the two requests, everything is correct. Did I do something wrong?

**Comment by caoyangjiang** [comment]
Additional quest: If I want to update an item, should I use PutItemRequest or UpdateItemRequest? From their APIs, it feels like both objects will do the job. What are the most important differences between these two?

**Comment by singku** [comment]
Can you test with sleeping a little bit at client side between these two requests? I am assuming there is some kind of protection at DDB server side that prevent you from doing that.

**Comment by singku** [comment]
Closing without response. Reopen if you still have question.
