### ISSUE TITLE
compile fails on Windows due to AWSMemory.h not considering max() macro in windows.h

### ISSUE THREAD

**Issue by diablodale** [aws/aws-sdk-cpp#641]
## Setup

* Visual Studio 2017 running on Windows 10 x64
* Project configured to use v140 (aka VS 2015) toolchain and Windows 8.1 as target platform
* Project target is a DLL, using the multithreaded debug DLL runtime (aka /MDd)
* used VS2017 and its integrated nuget to install the v140 toolchain package for AWS SDK C++ for S3 v1.1.26

Header file has:
```cpp
#include <windows.h>
#include <aws/core/Aws.h>
```

cpp file has no AWS code

## Repro

1. Compile

## Result
Compile fails. Dozens of syntax and template errors in the AWS SDK codebase. For example:
```
...\packages\awssdkcpp-core.1.1.26\build\native\include\aws\core\utils\memory\awsmemory.h(120): error C2589: '(': illegal token on right side of '::'
...\packages\awssdkcpp-core.1.1.26\build\native\include\aws\core\utils\memory\awsmemory.h(177): error C2589: '(': illegal token on right side of '::'
```

## Expected
No errors. Good compile. 

## Cause and solutions
`windows.h` defines a macro `max` which the AWS SDK codebase didn't consider when it uses `std::max`. You can `#define NOMINMAX` before including `windows.h` to prevent it from defining those macros, or you can prevent macro invocation by using an extra set of parentheses around `(std::max)`

I recommend the SDK be adjusted to consider this. Or to clearly document this `NOMINMAX` requirement for compiling on the Windows platform.

**Comment by marcomagdy** [comment]
We'll fix our build script to pass -DNOMINMAX.
Thank you

**Comment by marcomagdy** [comment]
Oops, sorry, this actually won't help you. We need to use the (std::mix) trick in the headers.

**Comment by diablodale** [comment]
@singku , where is the commit, code, pull request, etc. for this?
Or if you are closing this with another reason (e.g. won't fix), please note that here.

**Comment by singku** [comment]
er...it has already been merged to internal repo, build passed and integ passed, will be pushed out to public repo shortly (within 30 mins), waiting for the agent.

**Comment by diablodale** [comment]
Hello. I do not see a push request, links from this issue to a commit or other means to track and confirm a fix. Would you please add those and/or tell me how to see fixes for issues in commits?

**Comment by marcomagdy** [comment]
@diablodale sorry about that. Here's the commit https://github.com/aws/aws-sdk-cpp/commit/c3f540eec7bb6710b2c280d8f9c9e9819951eb4d
