### ISSUE TITLE
[Question] Nuget package deployment cycle?

### ISSUE THREAD

**Issue by zeliard** [aws/aws-sdk-cpp#642]
When a new AWS feature was released, there was a cpp sdk release. However, this sdk does not come with every release on Nuget.org. I want to know the distribution cycle.

**Comment by singku** [comment]
Unless there are some internal problems, currently Nuget packages release have about 10 hours delay than code release.

**Comment by zeliard** [comment]
https://www.nuget.org/packages?q=awssdkcpp
as you can see, there is about more than 2 weeks delay currently.

**Comment by singku** [comment]
Thanks for reporting that. We will push it out shortly.

**Comment by wps132230** [comment]
The publish of Nuget package was delayed by some inner problems. And you can see the latest update on (www.nuget.org)[https://www.nuget.org/packages?q=awssdkcpp] now.
