### ISSUE TITLE
EC2MetadataClient should have a one-parameter GetResource

### ISSUE THREAD

**Issue by Bu11etmagnet** [aws/aws-sdk-cpp#645]
`EC2MetadataClient` is now derived from `AWSHttpResourceClient` and inherits its `Aws::String GetResource(const char* endpoint, const char* resourcePath) const;` method.
The `EC2MetadataClient` constructor takes a (defaulted) `endpoint` parameter, but this value has to be repeated when calling `GetResource`.

```
EC2MetadataClient client("endpoint");
client.GetResource("endpoint", "resource");
```

`EC2MetadataClient` should have a one-parameter `GetResource` overload which passes `m_endpoint` to `AWSHttpResourceClient::GetResource`

**Comment by wps132230** [comment]
Thank you for reporting this. Currently, in CPP SDK, `EC2MetadataClient` uses `GetResource` to get access to `EC2` metadata or provide credentials and seems to be transparent to developers typically. Are you using `EC2MetadataClient::GetResource` directly in your code and feel redundant to pass two parameters, or just point out a way to improve the CPP SDK?

**Comment by Bu11etmagnet** [comment]
Yes, I use `EC2MetadataClient::GetResource` directly, and it feels redundant to pass the same value to the metadata client, which already accepted and stored the endpoint. Worse, the metadata client makes this value unavailable, so I can't even write `mdclient.GetResource(mdclient.endpoint(), resourcePath)`.

Also, it would be nice if `AWSHttpResourceClient::GetResource` could be made `virtual` so it could be mocked with Google Mock.

**Comment by wps132230** [comment]
Thank you for your suggestion, we made some changes based on your requirements, including:
- One-parameter `Aws::Internal::EC2MetadataClient::GetResource`.
- Make `Aws::Internal::AWSHttpResourceClient::GetResource` virtual.

You can use that with the latest version of aws cpp sdk and you can view [this commit](https://github.com/aws/aws-sdk-cpp/commit/01f60615c17c68ff2f82c49758c53472df96709c) if you want to know more details about how we change the code.

**Comment by Bu11etmagnet** [comment]
Awesome!
