### ISSUE TITLE
AWSClientTestSuite.TestClockSkewOutsideAcceptableRange run during build leads to alignment trap error 

### ISSUE THREAD

**Issue by dk1301** [aws/aws-sdk-cpp#650]
Linux:

gcc 4.9.2
cmake 3.8.2
Armbian_5.20_Cubietruck_Debian_jessie_3.4.112
kernel 3.4.112.sun7i
curl : 7.38
SDK version (1.1.46)

cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="config;core;kinesis"

The build fails at AWSClienttestSuite tests and specifically when running AWSClientTestSuite.TestClockSkewOutsideAcceptableRange

alignment trap: not handling instruction e8de677f at [<b6e509be>]
Unhandled fault :alignment exception (0x001) at 0x00bb674c
Bus error

Is there something that I can do to avoid this error

**Comment by kai5z** [comment]
Did you manage to solve this?

**Comment by dk1301** [comment]
No I haven't manage to solve. Since the build fails I don't know what else to try. That's why I asked the question in the first place. 
For the time being I just upgrade to Armbian_5.20_Cubietruck_Debian_jessie_3.4.113, it worked but it's only half measure because I need it to work under the Armbian_5.20_Cubietruck_Debian_jessie_3.4.112 version if possible.

**Comment by kai5z** [comment]
Alright, that's a shame. I'm getting the exact same problem (alignment exception / bus error) at the same test on Raspian 4.9.35-v7+.

**Comment by gv1dev** [comment]
Hi, I had the same issue in Armbian_5.31_Cubieetruck_Debian_Jessie_next_4.11.5.7
... :(

**Comment by kai5z** [comment]
Having the same problem with Raspbian Stretch, installed everything from scratch.

**Comment by singku** [comment]
@kai5z @gv1dev @dk1301  It's been a while.  Did you guys manage to solve this problem? I remember we had this similar problem in test and fixed it in https://github.com/aws/aws-sdk-cpp/commit/47030e94869586f4b9d29bba8fd0f3315f1c2f58. Appreciate if you guys can try it again with latest SDK.
