### ISSUE TITLE
C++17 removed std::function allocator support, used by AWSFunction.h

### ISSUE THREAD

**Issue by StephanTLavavej** [aws/aws-sdk-cpp#652]
[AWSFunction.h line 38](https://github.com/aws/aws-sdk-cpp/blob/498851b0e9cb18fbb184ef2352e30c94a0ddaa7a/aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSFunction.h#L38) says:

    return std::function< F >( std::allocator_arg_t(), Aws::Allocator<void>(), f );

This uses `std::function` allocator support, which was removed in C++17 by [P0302R1](https://wg21.link/p0302r1). (There are a few other occurrences on surrounding lines.)

Visual Studio 2017 will implement this feature removal in the near future, under `/std:c++17` and `/std:c++latest` (I'm an STL maintainer and I've already checked this in for VS 2017's second toolset update, version 15.5). To be compatible, the AWS SDK should stop attempting to use `std::function` allocator support, which never really worked in the first place. Quoting the P0302R1 paper:

> The GCC standard library has never provided those constructors at all. The libc++ implementation declares the constructors but ignores the allocator arguments. The MSVC implementation uses the allocator on construction, but does not reuse the allocator if the target is replaced by assignment, which means allocator propagation is not supported.

**Comment by JonathanHenson** [comment]
How would you recommend we hook the memory allocations for std::function into a custom allocator? 

I'm not sure we use this much anymore anyways, we began moving everything to lambdas a while back.

**Comment by StephanTLavavej** [comment]
You could store a small wrapper, which dynamically allocates memory using your preferred allocator (for large function objects). If your wrapper is the size of two pointers or smaller, and if `is_nothrow_move_constructible` is true, I think you'll get a de facto guarantee from all STL implementations that the Small Functor Optimization will be activated (this is certainly true for MSVC).

**Comment by marcomagdy** [comment]
@StephanTLavavej I've written a wrapper that utilizes our allocator, however, as far as I can tell, there's no easy way to know if a given `std::function` is utilizing the Small Functor Optimization? (so that I wouldn't wrap it in that case).
We can't use `std::function::target() `or `std::function::target_type()` because we support platforms where RTTI is disabled.

I've written our own `Aws::Function` (with support for SFO), but I'm shying from committing it to our source tree before confirming that I'm not missing an easy opportunity to leverage `std::function`.

**Comment by StephanTLavavej** [comment]
`target()` and `target_type()` don’t interact with the SFO anyways. There’s no official way to determine when the SFO will be activated, but you can empirically determine when it will activate (depending on stdlib, version, architecture, and debug mode; I know the behavior of MSVC’s STL because I retuned this optimization), and you can then detect such scenarios by inspecting the `sizeof` and `is_nothrow_move_constructible` of your function objects. For sufficiently small sizes (plus nothrow), all implementations will (de facto) activate their SFO.

**Comment by crusader-mike** [comment]
Thank you. Though, I think I'll have to call this migration off -- too many problems, especially with `/permissive-`.

**Comment by marcomagdy** [comment]
Fixed in v1.4.55

**Comment by crusader-mike** [comment]
Many thanks! This problem was the only show stopper for us (that we had no good way of working around) during C++17 migration.
