### ISSUE TITLE
GetTargetFilePath() is empty within transferStatusUpdatedCallback and downloadProgressCallback

### ISSUE THREAD

**Issue by diablodale** [aws/aws-sdk-cpp#653]
Calling `hTransfer.GetTargetFilePath()` within `transferConfig.transferStatusUpdatedCallback` is empty when handling a `FAILED` download due to the source S3 key not existing.

### Setup
Windows 10 x64
VS2017 15.3.3
AWS SDK 1.1.49

### Repro
When setting up transferManager and its transferConfig, create a lambda on the config's `transferStatusUpdatedCallback`. In that lambda, when `hTransfer.GetStatus() == FAILED`, display the output of `hTransfer.GetTargetFilePath().c_str()`

Then with a valid transferManager, do
```cpp
transferManager->DownloadFile("mybucket", "myKeyThatDoesNotExist, "c:\\mylocalfile.txt");
```

### Result
The display of `hTransfer.GetTargetFilePath().c_str()` in the callback is empty. It is `""`.

### Expected
The display to be `"c:\\mylocalfile.txt"`

### Note
There may be many other combinations of errors and down/uploads. In all cases, I believe `GetTargetFilePath()` should always have the local path that was given in the `Up/DownloadFile()` api call.

**Comment by singku** [comment]
Thanks for reporting that. TargetFilePath for download is currently not stored in handler. FAILED or not, it's empty. When downloading, handler cares more about the fstream associated with the file. We will add it later.

**Comment by diablodale** [comment]
I am experiencing that the targetFilePath is also not stored in the TransferHandle that is passed to the callback `downloadProgressCallback`.

These two callbacks `downloadProgressCallback` and `transferStatusUpdatedCallback` need valid and complete TransferHandles. Without such, it is difficult to react to a progress callback when I can't determine on what thing progress is occurring. Yes, it is possible to create parallel shadow data structures to track what the sdk is not validly storing.
