### ISSUE TITLE
aws cp - (copy via stdin)

### ISSUE THREAD

**Issue by haisamido** [aws/aws-sdk-cpp#656]
Is there a STDIN interface in the c++ sdk similar to the cli one:

`aws cp - s3://bucket/object
`

**Comment by JonathanHenson** [comment]
there is not, there is a programatic interface on transfer manager that will do this for you though.

**Comment by JonathanHenson** [comment]
Whats your use case where you can't use the aws cli?

This seems like, at the least it would be an interesting demo application for us to show users how to use transfer manager.
