### ISSUE TITLE
transferManager DownloadToDirectory() silently fails when source key prefix does not exist

### ISSUE THREAD

**Issue by diablodale** [aws/aws-sdk-cpp#657]
When calling `TransferManager::DownloadToDirectory()` for s3 key prefix that doesn't exist, the sdk silently fails with no results or callbacks indicating a failure.

### Setup
Windows 10 x64
VS2017 15.3.3
AWS SDK 1.1.49

### Repro
When setting up transferManager and its transferConfig, create all four lambda callbacks on the config. In those lambdas, display some simple debug text.

Then with a valid transferManager, do
```cpp
transferManager->DownloadToDirectory("C:\\mydir\\", "myBucket", "myKeyPrefixThatDoesNotExist");
```

### Result
Nothing. Anywhere.
> Bueller?... Bueller?... Bueller?
> -- Ferris Bueller's Day Off (1986)

### Expected
Something somewhere that reports there is an error, failure, exception, etc.

### Notes

* I am able to workaround this lack-of-feature by calling low-level S3 apis to initially check if the source S3 url prefix exists with code similar to the following
  ```cpp
  ListObjectsV2Request objectsRequest;
  objectsRequest.WithBucket(bucket).WithPrefix(key).WithMaxKeys(1);
  auto listObjectsOutcome = s3Client->ListObjectsV2(objectsRequest);
  if (!listObjectsOutcome.IsSuccess() || (listObjectsOutcome.GetResult().GetKeyCount() == 0)) {
      // s3 prefix doesn't exist
  }
  ```
* Possible enhancement of the SDK is to create a new callback `transferFailedCallback` which has a signature similar to
  ```cpp
  (const TransferManager*,
   const Aws::String &targetPath,
   const Aws::String &bucket,
   const Aws::String &key,
   const Aws::Transfer::TransferDirection&direction)
  ```

**Comment by singku** [comment]
The keyPrefix is a filter. If there is no file prefixed with this prefix, it should download nothing for you, correct? I think that's an expected behavior.

**Comment by diablodale** [comment]
As a customer, the generally expected behavior of any API is to do the work requested and to provide status/results.
This API does not provide status/results for the errant case at the top.

As per SDK documentation...
> Downloads entire contents of an Amazon S3 bucket starting at prefix stores them in a directory (not including the prefix). This is an asynchronous method. You will receive notifications that a download has started via the transferInitiatedCallback callback function in your configuration. If you do not set this callback, then you will not be able to handle the file transfers. **If an error occurs prior to the transfer being initiated (e.g. list objects fails, then an error will be passed through the errorCallback**).

The API need to provide results of successes and/or failures. In this case of nothing to download due to no found objects via the prefix, then some status/result of (finished, finished with null, finished with null set, null error, file not found error, no work to do error, etc.) needs to be provided. Otherwise, the customer (like me) is left digging around in lowerlevel APIs rather than using TransferManager.

This is additionally problematic because it is an async operation. Without status/results in this case, there is no way to know if the API is still working on a loooong operation or no objects were found.

This is the API form of the social behavior called "ghosting". This is like being on a first date with someone, they get up to go to the bathroom, and then they are gone for a loong time. What happened? Are they in the bathroom? Did they have an accident? Did they sneak out the side door and leave you? How long do you want for them to return from the bathroom before leaving yourself?

Customer:  Hi, API.
API: Hello
Customer: I want you to do some work for me.
API: OK. Please provide me the parameters of the work.
Customer: Please download all files that start with "xyz/123" into this folder
(...time passes...)
(...time passes...)

This customer doesn't know what is occurring as there is no immediately API errors, no reported network error, no progress updates, no finished report, ...nothing
This is "ghosting". And it is poor behavior of an API.

**Comment by singku** [comment]
Now I got what you have said. I thought there should be something like handle that you can WaitUntilFinish() and inspect after downloading. We will improve this experience soon. Thanks for your feedback.
