### ISSUE TITLE
S3Client::CompleteMultipartUpload returns success for failed requests

### ISSUE THREAD

**Issue by dyfrgi** [aws/aws-sdk-cpp#658]
Complete Multipart Upload is a bit weird in the REST API. Rather than return a failed HTTP code for a failure, it returns 200 OK immediately and then may later, at its leisure, send back an error. This is described in the API docs here:
http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadComplete.html

However, if an error is received for a Complete Multipart Upload along with a 200 OK, as described in the example given in the doc there, the CompleteMultipartUploadOutcome returned by S3Client::CompleteMultipartUpload will have have IsSuccess()==true.

We are specifically receiving 200 OK SlowDown errors, but I expect other errors may occur as there's one given as an example in the API doc.

**Comment by JonathanHenson** [comment]
Thanks for reporting will get it queued up for fix.

**Comment by marcomagdy** [comment]
This has been fixed in v1.3.30

**Comment by marcomagdy** [comment]
We'll have to revert this change f5c0f797e8267 See https://github.com/aws/aws-sdk-cpp/issues/781 for more details.

**Comment by andriy-bulynko** [comment]
Hi! We're hitting this bug as well. Do you have any idea when you might post a fix? Thanks!

**Comment by pitrou** [comment]
Why isn't this still fixed? This sounds like a critical bug. We just got word that our users can be hit by it: https://issues.apache.org/jira/browse/ARROW-14523

**Comment by pitrou** [comment]
@wps132230 @sdavtaker @KaibaLopez

**Comment by pitrou** [comment]
I'll also note that the docstring, while stating the problem, is unhelpful as to how to solve it:

> Processing of a Complete Multipart Upload request could take several minutes to complete. After Amazon S3 begins processing the request, it sends an HTTP response header that specifies a 200 OK response. While processing is in progress, Amazon S3 periodically sends white space characters to keep the connection from timing out. Because a request could fail after the initial 200 OK response has been sent, it is important that you check the response body to determine whether the request succeeded.

**Comment by pitrou** [comment]
Our own [workaround](https://github.com/apache/arrow/pull/11594/files) is to intercept XML error response using a DataReceivedHandler. Unfortunately, we can't really test it (those errors seem quite sporadic), but it should theoretically work.

**Comment by sdavtaker** [comment]
It seems like the Bug in TinyXML2 was resolved and we recently and we should be able to merge this fix again.

**Comment by pitrou** [comment]
As a sidenote, the original fix seems costly if it blindly parses any HTTP response (even a huge binary payload) as XML.

**Comment by pitrou** [comment]
So, here is an example of how this could be fixed in the AWS SDK, IMHO:

- add a method `virtual bool HasEmbeddedError(Aws::IOStream& body, Aws::Client::AWSError<Aws::Client::CoreErrors>* error)` in `AmazonWebServiceRequest`; default implementation returns `false` and leaves `error` unchanged
- override that method in `CompleteMultipartUploadRequest` and make it parse the XML payload for embedded errors
- in [`AttemptOneRequest`](https://github.com/aws/aws-sdk-cpp/blob/2f90f9fd6c56460bd382243aa215fcddcb5883c8/aws-cpp-sdk-core/source/client/AWSClient.cpp#L484-L489), call `HasBodyError` for successfull HTTP responses

**Comment by sdavtaker** [comment]
Thanks @pitrou for the proposed solution, it sounds like a good approach.

**Comment by jvictor0** [comment]
I agree with @pitrou  that this is a critial issue.  Our customers seem to have hit it as well.

**Comment by sbiscigl** [comment]
[the fix has been merged](https://github.com/aws/aws-sdk-cpp/commit/1614bce979a201ada1e3436358edb7bd1834b5d6) and will be released with 1.9.333
