### ISSUE TITLE
BuildAWSError doesn't account for XML responses with no root element

### ISSUE THREAD

**Issue by allexk** [aws/aws-sdk-cpp#660]
In case the XML in the response body doesn't contain a root element, the response will be parsed successfully, but the `AWSError<CoreErrors> XmlErrorMarshaller::Marshall(const Aws::Http::HttpResponse& httpResponse)` will SIGSEGV, since it doesn't check if the root element is null: 

    XmlNode errorNode = doc.GetRootElement();
    if (errorNode.GetName() != "Error")

This can happen if, for instance, a `ContinueRequestHandler` callback interrupts the processing and the body contains a single XML directive `<? xml ... ?>`. We observed this on an older version of the SDK, but it doesn't seem to be fixed, unless XML parsing was reworked at some point. Checking for `errorNode.isNull()` seems to be a good practice in any case.

**Comment by jmklix** [comment]
We have made a lot of build changes since this issue was opened. Are you still running into this?

**Comment by allexk** [comment]
@jmklix The commit in the history looks like a proper fix for that issue. Would be hard to confirm 100%, since we obviously patched the SDK on our side back then, and there's no desire to retest this. I think closing is the right thing to do.
