### ISSUE TITLE
cygwin - won't compile - missing flags and core dump on test drivers

### ISSUE THREAD

**Issue by garyschneir** [aws/aws-sdk-cpp#661]
I am trying to use the SDK with project written for Linux and porting the application to window using cygwin.  

I am only building CORE and S3, so I don't know how widespread the issue is but at the minimum, I need to add gnu++11 compatibility since c++11 isn't sufficient.  I am able to
set (CMAKE_CPP_STANDARD_11)
set(CMAKE_CXX_EXTENSIONS 1)

There is also a compile problem with S3Client so I have to add -Wa,-mbig-obj to the flags for the aws-cpp-sdk-s3.

The aws-cpp-sdk-core-tests test driver runs fine but when I try the aws-cpp-sdk-s3-integration-tests, it core dumps.  It looks like the core dump is associated with the destructor of the ClientConfiguration object.  The core-tests also uses the ClientConfiguration object but it uses a custom memory model which seems to avoid the issue.  

If I copy the code for the custom memory model to the s3-integration-tests, it goes further but still ends with a core dump. 

I haven't been able to trace it down to a specific line but are there additional flags / memory alignment options that can help the aws-sdk-cpp compile under cygwin?

**Comment by JonathanHenson** [comment]
can you post the code surrounding your InitAPI() call?

**Comment by garyschneir** [comment]
I'm just trying to use the standard aws test drivers.

I don't have code in front of me but, I just check out the source, make the
extensions change to cmake, and compile.  The core-tests runs okay but the
s3-integration tests fail.

**Comment by JonathanHenson** [comment]
what about a trace level log file perhaps?

**Comment by garyschneir** [comment]
Here are my steps to build - 
clone

Add the following lines to CMakeList.txt
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_EXTENSIONS 1)

execute following cmake
cmake -H. -DCMAKE_BUILD_TYPE=Debug -DBUILD_ONLY="core;s3" .

Update ./aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/flags.make
Update the CXX_FLAGS to 
CXX_FLAGS = -g   -fno-exceptions -std=c++11 -Wall -Werror -pedantic -Wextra -std=gnu++11 -Wa,-mbig-obj

run make
aws-cpp-sdk-core-tests runs fine but s3-integration-tests does run during make process
cd aws-cpp-sdk-s3-integration-tests
make
./aws-cpp-sdk-s3-integration-tests.exe

$ ./aws-cpp-sdk-s3-integration-tests
[==========] Running 10 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 10 tests from BucketAndObjectOperationTest
Aborted (core dumped)

The log shows checking for .aws/config and .aws/credentials but here is the tail [TRACE] 2017-09-12 20:09:42 FileSystemUtils [0x600000060] Checking HOME for the home directory.
[DEBUG] 2017-09-12 20:09:42 FileSystemUtils [0x600000060] Environment value for variable HOME is /home/Gary
[DEBUG] 2017-09-12 20:09:42 FileSystemUtils [0x600000060] Home directory is missing the final / appending one to normalize
[DEBUG] 2017-09-12 20:09:42 FileSystemUtils [0x600000060] Final Home Directory is /home/Gary/
[TRACE] 2017-09-12 20:09:42 FileSystemUtils [0x600000060] Checking HOME for the home directory.
[DEBUG] 2017-09-12 20:09:42 FileSystemUtils [0x600000060] Environment value for variable HOME is /home/Gary
[DEBUG] 2017-09-12 20:09:42 FileSystemUtils [0x600000060] Home directory is missing the final / appending one to normalize
[DEBUG] 2017-09-12 20:09:42 FileSystemUtils [0x600000060] Final Home Directory is /home/Gary/
[INFO] 2017-09-12 20:09:42 ProfileConfigFileAWSCredentialsProvider [0x600000060] Setting provider to read credentials from /home/Gary//.aws/credentials for credentials file and /home/Gary//.aws/config for the config file , for use with profile default
[INFO] 2017-09-12 20:09:42 EC2MetadataClient [0x600000060] Creating HttpClient with max connections2 and scheme http
[INFO] 2017-09-12 20:09:42 CurlHandleContainer [0x600000060] Initializing CurlHandleContainer with size 2
[INFO] 2017-09-12 20:09:42 InstanceProfileCredentialsProvider [0x600000060] Creating Instance with default EC2MetadataClient and refresh rate 900000
[DEBUG] 2017-09-12 20:09:42 Aws::Config::ConfigFileProfileFSM [0x600000060] found profile default
[DEBUG] 2017-09-12 20:09:42 Aws::Config::ConfigFileProfileFSM [0x600000060] found access key <removed>
[DEBUG] 2017-09-12 20:09:42 Aws::Config::ConfigFileProfileFSM [0x600000060] found profile default2
[DEBUG] 2017-09-12 20:09:42 Aws::Config::ConfigFileProfileFSM [0x600000060] found access key <removed>
[INFO] 2017-09-12 20:09:42 Aws::Config::AWSProfileConfigLoader [0x600000060] Successfully reloaded configuration.
[TRACE] 2017-09-12 20:09:42 Aws::Config::AWSProfileConfigLoader [0x600000060] reloaded config at 2017-09-13T03:09:42Z
[INFO] 2017-09-12 20:09:42 CurlHandleContainer [0x600000060] Initializing CurlHandleContainer with size 25


For convenience, here is the RunTests.cpp
int main(int argc, char** argv)
{
    Aws::SDKOptions options;
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
    Aws::Testing::InitPlatformTest(options);
    if(argc > 1)
    {
        Aws::Testing::SetAwsResourcePrefix(argv[1]);
    }

    Aws::InitAPI(options);
    ::testing::InitGoogleTest(&argc, argv);
    int exitCode = RUN_ALL_TESTS();
    Aws::ShutdownAPI(options);

    Aws::Testing::ShutdownPlatformTest(options);
    return exitCode;
}

**Comment by garyschneir** [comment]
Execution produces a stackdump file

$ more aws-cpp-sdk-s3-integration-tests.exe.stackdump
Stack trace:
Frame        Function    Args
000FFFFBCF0  0018005CF8C (000FFFFE3F4, 0000000006B, 00000000084, 000FFFFDE50)
000FFFFBD90  0018005E56B (00000000064, 00000000000, 00000000000, 00000000000)
000FFFFBFE0  00180120810 (004D671B6E0, 000FFFFC130, 004D66BA34F, 0060009995C)
000FFFFC2D0  0018011D3DE (004D66BBA0F, 00000000000, 00000000000, 000FFFFC23D)
000FFFFC470  0018011D879 (000FFFFC5C0, 000FFFFC2F0, 004D66D80B6, 00000000006)
000FFFFC470  0018011DA4A (00000000000, 000FFFFC5C0, 00000000000, 000FFFFC3D0)
000FFFFC470  0018011DD0F (00000000000, 000FFFFC460, 004D671B6E0, 004D671B6E0)
000FFFFC470  00180156695 (000FFFFC70F, 000FFFFC70E, 00600099870, 000FFFFC470)
000FFFFC470  001800BAF83 (000FFFFC7C0, 000FFFFC4FF, 000FFFFC5C0, 000FFFFC490)
000FFFFC470  00180118FEB (000FFFFC7C0, 000FFFFC4FF, 000FFFFC5C0, 000FFFFC490)
000FFFFC470  004D6670DC4 (000FFFFC5C0, 000FFFFC4C0, 0010041EE01, 000FFFFC4E0)
000FFFFC4A0  001004136A0 (004D671B6E0, 00000000019, 001FFFFFFFF, 00600082520)
000FFFFC4E0  00100419107 (000FFFFC54F, 000FFFFC660, 000FFFFC7E0, 000FFFFC550)
000FFFFC510  00100419177 (000FFFFC54F, 000FFFFC658, 000FFFFC5C0, 00000000000)
000FFFFC550  0010041A524 (000FFFFC720, 000FFFFC5C0, 00597016D00, 000FFFFC610)
000FFFFC580  00100412A82 (000FFFFC720, 000FFFFC710, 000FFFFC5C0, 000FFFFC70F)
End of stack trace (more stack frames may be present)

**Comment by garyschneir** [comment]
I have found that adding the -DCUSTOM_MEMORY_MANAGEMENT=0 to the cmake
command above will resolve the issue with the test drivers.  I think there
are still the other issues with using this package in the CYGWIN
environment but this seems to solve my issue for now.
