### ISSUE TITLE
aws-cpp-sdk-iot vs aws-cpp-sdk-iot-data vs aws-iot-device-sdk-cpp

### ISSUE THREAD

**Issue by samikhawaja** [aws/aws-sdk-cpp#663]
Hi,

What is the difference between the aws-iot-device-sdk-cpp and aws-cpp-sdk-iot?

I am trying to upload a file from an IOT device to S3 and do some processing on it. For the IOT device I am using aws-iot-device-sdk.

As the aws-iot-device-sdk does not have any api or functionality to upload a file on S3, can I use aws-cpp-sdk for both S3 and IOT?

I noticed that aws-cpp-sdk-iot does not have functionality to publish messages to a topic. Also the aws-cpp-sdk-iot-data has that functionality present.

. Which one should I be using? aws-cpp-sdk-iot or aws-cpp-sdk-iot-data?
. Is IOT-DATA a different service than IOT?
. Is the aws-cpp-sdk-iot (-data) functionally complete as compared to aws-iot-device-sdk?

**Comment by JonathanHenson** [comment]
iot-data is the "data plane" for the iot service. That's the one you want for actually doing device things. 

You can use the aws-cpp-sdk-s3 api to upload to s3

**Comment by samikhawaja** [comment]
Thanks for the reply.

I am using S3 to upload file and it works fine. Also I am using the iot-data APIs in aws-cpp-sdk to publish on the IOT topic.

I want to subscribe to another topic to get anything that is published on it. But I couldn't find any API in iot-data or iot for that purpose. I am trying to do following,

1. upload a file on S3.
2. publish a request on a topic from IOT device.
3. execute a lambda (and processes the uploaded file) based on the rules, and work on the request.
4. publish back the response on a different topic from lambda.
5. Subscribe to the response topic and get/handle response.

I have been able to do 1-4. But for 5 I need a way to subscribe to the topic. Can you suggest anything in this regard?
