### ISSUE TITLE
Compile error for "aws-cpp-sdk-ssm/source/model/CommandStatus.cpp"

### ISSUE THREAD

**Issue by caishaoping** [aws/aws-sdk-cpp#664]
Checked out master branch and tried to build the SDK on my Mac, it has following compile error, after removing the extra ":", the compile success. 

 /aws_sdk_repos/aws-sdk-cpp/aws-cpp-sdk-ssm/source/model/CommandStatus.cpp:27:4: error: expected unqualified-id
  {:
   ^
1 error generated.
make[2]: *** [aws-cpp-sdk-ssm/CMakeFiles/aws-cpp-sdk-ssm.dir/source/model/CommandStatus.cpp.o] Error 1
make[1]: *** [aws-cpp-sdk-ssm/CMakeFiles/aws-cpp-sdk-ssm.dir/all] Error 2
make: *** [all] Error 2

**Comment by marcomagdy** [comment]
Hi, I don't see that ':' in our source tree, and our internal builds are all passing.
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-ssm/source/model/CommandStatus.cpp

**Comment by caishaoping** [comment]
Thanks for the response, I also checked on the repos master branch, it has no extra ":",  let me look my checkout on 9/12, and figure out why. 
Thanks for checking.
Shao

**Comment by marcomagdy** [comment]
Please reopen if you're still having this problem.
