### ISSUE TITLE
s3Client->DeleteObject() outcome is the same (key present, key not present)

### ISSUE THREAD

**Issue by diablodale** [aws/aws-sdk-cpp#667]
When `s3Client->DeleteObject()` used on a bucket+key that exists -or- not exists, the outcome is the same.

```cpp
DeleteObjectRequest objectsRequest;
objectsRequest.WithBucket(bucket).WithKey(key);
auto outcome = s3Client->DeleteObject(objectsRequest);
if (outcome.IsSuccess()) {...
```

### Repro 1

Bucket exists and key exists. Credentials are valid. No versioning.

Result via Outcome 
```
result	{m_deleteMarker=false m_versionId="" m_requestCharged=NOT_SET (0) }	Aws::S3::Model::DeleteObjectResult
m_deleteMarker	false	bool
m_versionId	""	std::basic_string<char,std::char_traits<char>,std::allocator<char> >
m_requestCharged	NOT_SET (0)	Aws::S3::Model::RequestCharged
error	{m_errorType=INCOMPLETE_SIGNATURE (0) m_exceptionName="" m_message="" ...}	Aws::Client::AWSError<enum Aws::S3::S3Errors>
success	true	bool
```

Expected
This is expected result.

### Repro 2

Bucket exists and key **_does not_** exists. Credentials are valid. No versioning.

Result via Outcome
```
result	{m_deleteMarker=false m_versionId="" m_requestCharged=NOT_SET (0) }	Aws::S3::Model::DeleteObjectResult
m_deleteMarker	false	bool
m_versionId	""	std::basic_string<char,std::char_traits<char>,std::allocator<char> >
m_requestCharged	NOT_SET (0)	Aws::S3::Model::RequestCharged
error	{m_errorType=INCOMPLETE_SIGNATURE (0) m_exceptionName="" m_message="" ...}	Aws::Client::AWSError<enum Aws::S3::S3Errors>
success	true	bool
```

Expected
Expected `success = false` and `error` to contain fields consistent with a 404 not found.

### Notes

* http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectDELETE.html has no mention about deletes of keys that do not exist. Therefore, I would assume common behavior that operations on a resource that is not found results in a 404 not found error.
* http://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html has an explicit rule that "if the object specified in the request is not found, Amazon S3 returns the result as deleted". Personally, I think this is very odd behavior, but at least the rules are clear.
* http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html is in _contrast_. It will return 403 or 404 when a key does not exist.
* I suspect this is an upstream design/issue. If so, is there doc/direction/logic on why this is intended?
* It is likely possible to do a head or stat on the key-not-yet-deleted to see if it exists. This potentially doubles the network traffic -- undesired.

**Comment by marcomagdy** [comment]
> I suspect this is an upstream design/issue. 

Yes. This is how S3 is designed to work. You'd get the same response if you hit the endpoint using curl from the cli.
>is there doc/direction/logic on why this is intended?

If DELETE would fail with a 404 for non-existing keys, then it gets tricky on what the outcome should be for a batch delete. Imagine if 1 out of 10 keys does not exist. Do you fail the whole operation?
It's simpler to consider it a success, since the observed state of the bucket is the same after that operation regardless of whether that key existed or not.

Hope that helps.

**Comment by diablodale** [comment]
Got it. Thank you.
