### ISSUE TITLE
[CMake] -DBUILD_ONLY="cloudfront;text-to-speech" only builds the first token

### ISSUE THREAD

**Issue by INRIX-joel-winarske** [aws/aws-sdk-cpp#668]
Specifying multiple values for "BUILD_ONLY" results in only the first parameter having an affect.

So in the case below, it will only build cloudfront, whereas it should should build cloudfront and text-to-speech.

### What platform/OS are you using?
Ubuntu 16.04 LTS

### What compiler are you using? what version?
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

### What's your CMake arguments?
ExternalProject_Add(aws_sdk
    SOURCE_DIR ${CMAKE_SOURCE_DIR}/aws-sdk-cpp
    DOWNLOAD_COMMAND ""
    BUILD_IN_SOURCE 0
    CMAKE_ARGS
      -DZLIB_LIBRARY=${CMAKE_INSTALL_PREFIX}/lib/libz.so
      -DZLIB_INCLUDE_DIR=${CMAKE_INSTALL_PREFIX}/include
      -DCURL_LIBRARY=${CMAKE_INSTALL_PREFIX}/lib/libcurl.so
      -DCURL_INCLUDE_DIR=${CMAKE_INSTALL_PREFIX}/include
      -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
      -DBUILD_ONLY=cloudfront;text-to-speech
)

**Comment by marcomagdy** [comment]
you might need to surround the values with double quotes.
```
ExternalProject_Add(aws_sdk
SOURCE_DIR ${CMAKE_SOURCE_DIR}/aws-sdk-cpp
DOWNLOAD_COMMAND ""
BUILD_IN_SOURCE 0
CMAKE_ARGS
-DZLIB_LIBRARY=${CMAKE_INSTALL_PREFIX}/lib/libz.so
-DZLIB_INCLUDE_DIR=${CMAKE_INSTALL_PREFIX}/include
-DCURL_LIBRARY=${CMAKE_INSTALL_PREFIX}/lib/libcurl.so
-DCURL_INCLUDE_DIR=${CMAKE_INSTALL_PREFIX}/include
-DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
-DBUILD_ONLY="cloudfront;text-to-speech"
)
```

**Comment by INRIX-joel-winarske** [comment]
When you surround it with double quotes, it generates an error...  The error goes away without the quotes, but only builds the first occurring one.

    [ 83%] Performing configure step for 'aws_sdk'
    -- TARGET_ARCH not specified; inferring host OS to be platform compilation target
    -- Building AWS libraries as shared objects
    -- Generating linux build config
    -- Building project version: 1.1.53
    --   Zlib include directory: /home/joel/git/uXeno/build/out/include
    --   Zlib library: /home/joel/git/uXeno/build/out/lib/libz.so
    -- Encryption: Openssl
    --   Openssl include directory: /home/joel/git/uXeno/build/out/include
    --   Openssl library: /home/joel/git/uXeno/build/out/lib/libssl.so;/home/joel/git/uXeno/build/out/lib/libcrypto.so
    -- Http client: Curl
    --   Curl include directory: /home/joel/git/uXeno/build/out/include
    --   Curl library: /home/joel/git/uXeno/build/out/lib/libcurl.so
    -- Considering "cloudfront
    CMake Error at cmake/sdks.cmake:154 (message):
      "cloudfront is required for build, but aws-cpp-sdk-"cloudfront directory is missing!
    Call Stack (most recent call first):
      CMakeLists.txt:125 (include)

**Comment by JonathanHenson** [comment]
you might need to escape them \"

**Comment by INRIX-joel-winarske** [comment]
@JonathanHenson 

    -DBUILD_ONLY=\"cloudfront;text-to-speech\"

Same error

    -- Considering "cloudfront
    CMake Error at cmake/sdks.cmake:154 (message):
      "cloudfront is required for build, but aws-cpp-sdk-"cloudfront directory is missing!
    Call Stack (most recent call first):
      CMakeLists.txt:125 (include)

**Comment by pinglin** [comment]
Due to some internal manner of ExternalProject_Add confusing the list arguments, you need to modify the list delimiter other than `;`. This can be done by adding `LIST_SEPARATOR |` and `-DBUILD_ONLY=cloudfront|text-to-speech` in ExternalProject_Add.

**Comment by singku** [comment]
@pinglin Thank you, that works for me. @INRIX-joel-winarske could you please try this if you still have the problem?

**Comment by singku** [comment]
Closing this issue because above answer solved it. Please reopen if you still have the problem.
