### ISSUE TITLE
Handling "ServiceUnavailable - Please reduce your request rate" errors

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#672]
Occasionally I get `ServiceUnavailable` errors -- i.e. device received my request and discarded it because it is too busy. This is quite unexpected -- now I need to repeat my request at some time later, resending all data over the wire again... without any guarantee of success.

I kind of expected it to slow down reading from related TCP connections -- thus naturally throttling down incoming requests rate. This would also make my life easier -- I wouldn't need to care about `ServiceUnavailable` errors and the only problem I'd have to deal with is timeout (when device is severely overloaded for prolonged  time).

Questions:

- What would be the best way to handle this situation? Should I simply retry in a loop with ever-increasing pause between attempts?

- Does AWS SDK have any tools to help me to handle 'ServiceUnavailable' class of errors?

- Why S3 is using 'receive-and-discard' approach instead of 'slowdown-receive'?

**Comment by JonathanHenson** [comment]
hmmm, the SDK should already be retying this automatically, which means it's already gone through a loop with exponential backoff.

The real problem I suspect is that the winhttp code doesn't handle 100 continue properly.

This isn't something that can be handled through tcp back pressure (if thats what you mean), since the parallelism is running over multiple tcp connections connected to different VIPs that are connected to different hosts.

**Comment by crusader-mike** [comment]
> hmmm, the SDK should already be retying this automatically, which means it's already gone through a loop with exponential backoff.

Not if I used DefaultRetryStrategy with value 0. I never suspected I'll have to deal with 'ServiceUnavailable' and retrying on any error is not a good thing anyways.

> ... tcp back pressure

Uhmm.... I spent some time looking for a good explanation of "what tcp back pressure is?" and tbh I failed. Only found some whitepapers on mechanism used on router level. Can you clarify or point me to an explanation, pls?

I was referring to TCP mechanism that blocks sender as described [here](http://www.rhyshaden.com/tcp.htm) (see chapters 6.1 and 6.2). In particular:
> The receiver specifies the current Receive Window size in every packet sent to the sender. The sender can send up to this amount of data before it has to wait for an update on the Receive Window size from the receiver. 
> ...
> If the receiver has a full buffer, then the window size is reduced to zero. In this state, the window is said to be Frozen and the sender cannot send any more bytes until it receives a datagram from the receiver with a window size greater than zero.

i.e. it is a natural throttling mechanism that exists on TCP level and makes my life (as developer) simple -- I just send data and get blocked when receiver gets overwhelmed. 


> This isn't something that can be handled through tcp back pressure (if thats what you mean), since the parallelism is running over multiple tcp connections connected to different VIPs that are connected to different hosts.

Why? ultimately all these pipes lead to a number of devices that perform actual writing -- and pressure should propagate from them through pipes to original source of request.

---------------------------------------------------------------------------------------

In any case, all philosophy aside:
- is 'retry with exponential backoff' considered to be expected way to handle ServiceUnavailable?
- do I have sufficiently fine-grained control over request retries in AWS SDK?

**Comment by JonathanHenson** [comment]
you can easily implement your own retry strategy... thats the point of it being injectable. 

In general, http error code >= 500 should be retried with an increasing delay between retries.

400s are considered an error from the client so those should never be retried. 

We put a hint in the error class to tell you if that error should be retried.

**Comment by JonathanHenson** [comment]
the point on back pressure is that the throttling/slow down decision is usually made across multiple hosts asynchronously, so tcp back pressure is not a suitable mechanism.

**Comment by crusader-mike** [comment]
Thank you, Jonathan.
