### ISSUE TITLE
How to build with _USE_32_BIT_TIME_T flag set

### ISSUE THREAD

**Issue by gayoso** [aws/aws-sdk-cpp#673]
Hi, I am trying to build aws core + aws s3 to be used with a program that requires 32 bit time_t. MSVC default is 64 bit without this flag set. I tried specifying this define in the CMAKE command, but the flag wasn't set in the solutions generated. I set it manually in the preprocessor defines inside each solution, but when running "msbuild INSTALL.vcproj" I get an error when compiling "DateTimeCommon.cpp", about a possible loss of data when converting from 64 bit time_t to 32 bit time_t. Why could this be happening, if I've set the flag in all solutions? Shouldn't everything be working with 32 bit time_t ?

**Comment by singku** [comment]
Thanks for reporting this, could you please point out the line that generated that compile error?

**Comment by gayoso** [comment]
Yes, this is the exact error message:

```
Build FAILED.

"C:\Users\Gabriel\Desktop\aws-sdk-cpp-master\aws-sdk-cpp-master\build\INSTALL.vcxproj" (default target) (1) ->
"C:\Users\Gabriel\Desktop\aws-sdk-cpp-master\aws-sdk-cpp-master\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\Users\Gabriel\Desktop\aws-sdk-cpp-master\aws-sdk-cpp-master\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj" (defau
lt target) (4) ->
(ClCompile target) ->
  C:\Users\Gabriel\Desktop\aws-sdk-cpp-master\aws-sdk-cpp-master\aws-cpp-sdk-core\source\utils\DateTimeCommon.cpp(1183)
: warning C4244: 'initializing': conversion from '__time64_t' to 'time_t', possible loss of data [C:\Users\Gabriel\Desk
top\aws-sdk-cpp-master\aws-sdk-cpp-master\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
  C:\Users\Gabriel\Desktop\aws-sdk-cpp-master\aws-sdk-cpp-master\aws-cpp-sdk-core\source\utils\DateTimeCommon.cpp(1193)
: warning C4244: 'initializing': conversion from '__time64_t' to 'time_t', possible loss of data [C:\Users\Gabriel\Desk
top\aws-sdk-cpp-master\aws-sdk-cpp-master\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]


"C:\Users\Gabriel\Desktop\aws-sdk-cpp-master\aws-sdk-cpp-master\build\INSTALL.vcxproj" (default target) (1) ->
"C:\Users\Gabriel\Desktop\aws-sdk-cpp-master\aws-sdk-cpp-master\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\Users\Gabriel\Desktop\aws-sdk-cpp-master\aws-sdk-cpp-master\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj" (defau
lt target) (4) ->
(ClCompile target) ->
  C:\Users\Gabriel\Desktop\aws-sdk-cpp-master\aws-sdk-cpp-master\aws-cpp-sdk-core\source\utils\DateTimeCommon.cpp(1183)
: error C2220: warning treated as error - no 'object' file generated [C:\Users\Gabriel\Desktop\aws-sdk-cpp-master\aws-s
dk-cpp-master\build\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]

    2 Warning(s)
    1 Error(s)
```

Looking at the code of DateTimeCommon.cpp, this is the line that fails:
`std::time_t time = std::chrono::system_clock::to_time_t(m_time);`

Just to clarify the steps I just did to reproduce the error again:

cmake ../ -DBUILD_ONLY="s3"
open the generated AWSSDK.sln
select items "aws-cpp-sdk-core", "aws-cpp-sdk-core-tests", "aws-cpp-sdk-s3", "aws-cpp-sdk-s3-integration-tests", "testing-resources" from the solution explorer
go to Properties->Preprocessor Definitions and add "_USE_32BIT_TIME_T"
exit and save
msbuild INSTALL.vcxproj

Hope this helps!
