### ISSUE TITLE
CMake target unrecognized for downstream project in Windows Visual Studio

### ISSUE THREAD

**Issue by jasjuang** [aws/aws-sdk-cpp#675]
### What platform/OS are you using? 

Windows 10.

### What compiler are you using? what version?

Visual Studio 2015

### Step by Step of installing aws sdk

``````
git clone https://github.com/aws/aws-sdk-cpp
cd aws-sdk-cpp && mkdir build && cd build
cmake -A x64 ..
msbuild AWSSDK.sln /p:Configuration=Release
msbuild INSTALL.vcxproj /p:Configuration=Release
``````

and then aws sdk got installed to `C:\Program Files (x86)\aws-sdk-cpp-all`, I had to rename it manually to `C:\Program Files (x86)\AWSSDK` because according to https://cmake.org/cmake/help/v3.9/command/find_package.html , this is the proper path for `find_package` to work in config mode for aws sdk.

### Minimal code to reproduce the problem

CMakeLists.txt

``````
cmake_minimum_required(VERSION 3.5)

project(Example)

find_package(AWSSDK REQUIRED)

set(PROJECT_SRCS ${PROJECT_SOURCE_DIR}/main.cpp)

add_executable(${PROJECT_NAME} ${PROJECT_SRCS})

target_link_libraries(${PROJECT_NAME} aws-cpp-sdk-core)
``````

main.cpp

``````
int main(){
  return 0;
}
``````

and then the step to compile this is

``````
mkdir build && cd build
cmake -A x64 ..
msbuild Example.sln /p:Configuration=Release
``````

but then the compilation error 

``````
LINK : fatal error LNK1181: cannot open input file 'aws-cpp-sdk-core.lib'
``````

and then I look into the solution file and realized, the directory that has the aws headers are not in the include directories, and the linker only shows aws-cpp-sdk-core.lib instead of the full path, that means in cmake it didn't recognize aws-cpp-sdk-core as a cmake target and it treats aws-cpp-sdk-core as if it's the library name. Can someone please fix this?

Note that the exact same minimal code works without a problem on Ubuntu.

**Comment by singku** [comment]
Hi on Unix like system, the default search path for Cmake is /usr/lib(64) or /usr/local/lib(64). On Windows, you have to specify in your cmake script where to search .cmake files for CMake.
set(AWSSDK_ROOT_DIR "/your/aws-sdk-cpp/cmakefile/dir/") will do the work.

**Comment by jasjuang** [comment]
@singku It was able to locate AWSSDKConfig.cmake without a problem via `find_package` config mode because I rename `C:\Program Files (x86)\aws-sdk-cpp-all` to `C:\Program Files (x86)\AWSSDK`.

The problem is not it can't locate the cmake search path, it is able to locate it but unable resolve the target. After `cmake -A x64 ..` in the downstream project, it shows AWSSDK found in the console.

**Comment by singku** [comment]
I mean you don't have to rename the default install dir if you specify the search root. For "unable to resolve the target", try following:
```
link_directories("${AWSSDK_LIB_DIR}")
target_include_directories(TARGET PRIVATE ${AWSSDK_INCLUDE_DIR})
```

**Comment by jasjuang** [comment]
Specifying the search root in my downstream project cmake file is a bad idea, cmake is meant to be cross platform and this line `set(AWSSDK_ROOT_DIR "/your/aws-sdk-cpp/cmakefile/dir/")` is windows only and it only works on a single computer because of the specified path. I tried `set(AWSSDK_ROOT_DIR "/your/aws-sdk-cpp/cmakefile/dir/")` and it still can't locate the cmake config file if I don't do the manual rename. Are you able to get it to find the cmake config without the rename?

I also tried `link_directories("${AWSSDK_LIB_DIR}")` and `target_include_directories(TARGET PRIVATE ${AWSSDK_INCLUDE_DIR})` and it doesn't work. No aws libraries are linked to my downstream project.

**Comment by singku** [comment]
Changing the default install directory "aws-sdk-cpp-all" to AWSSDK on Windows is a breaking change for users. And aws-sdk-cpp-all is not a CMAKE aware location. Without breaking user experience, we have to specify the location. Sorry, the correct variable is AWSSDK_DIR
so basically follow this receipt:
```
project(testProject)
set(AWSSDK_DIR "C:\Program Files (x86)\aws-cpp-sdk-all\lib\cmake\AWSSDK")
find_package(AWSSDK REQUIRED)
set(SERVICE s3)
AWSSDK_DETERMINE_LIBS_TO_LINK(SERVICE OUTPUT)
link_directories("${AWSSDK_LIB_DIR}")
add_executable(testProject test.cpp)
target_link_libraries(testProject ${OUTPUT})
target_include_directories(testProject PRIVATE ${AWSSDK_INCLUDE_DIR})
```

**Comment by jasjuang** [comment]
I tried your cmakelist and here is what I got

``````
CMake Error at CMakeLists.txt:8 (find_package):
  By not providing "FindAWSSDK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "AWSSDK", but
  CMake did not find one.

  Could not find a package configuration file provided by "AWSSDK" with any
  of the following names:

    AWSSDKConfig.cmake
    awssdk-config.cmake
``````

Did you verify and make sure it works?

**Comment by singku** [comment]
I have verified that. I think the problem here is CMake can't find the location of that AWSSDKConfig.cmake. Cant you try to use "C:\\" instead of "C:\" in your CMake scripts?

**Comment by singku** [comment]
But if you have already change the name and is able to find the cmake file, then I think add target_link_directory will help you locate the lib.

**Comment by jasjuang** [comment]
`link_directories` does make it compile but it is still treating `aws-cpp-sdk-core` as if it's the library name and not the target. Non of the `INTERFACE_COMPILE_DEFINITIONS`, `INTERFACE_INCLUDE_DIRECTORIES` and `INTERFACE_LINK_LIBRARIES` as shown in `aws-cpp-sdk-core-targets.cmake` are picked up by the downstream project.

However, I somehow figured out a way that work, but it's very ugly. First rename `C:\Program Files (x86)\aws-sdk-cpp-all` to `C:\Program Files (x86)\aws-sdk-cpp-core`, change my CMakeLists to 

``````
cmake_minimum_required(VERSION 3.5)

project(Example)

find_package(aws-cpp-sdk-core REQUIRED)

set(PROJECT_SRCS ${PROJECT_SOURCE_DIR}/main.cpp)

add_executable(${PROJECT_NAME} ${PROJECT_SRCS})

target_link_libraries(${PROJECT_NAME} aws-cpp-sdk-core)
``````

this is the only way I can make my downstream project treating `aws-cpp-sdk-core` as a target and therefore picking up all the `INTERFACE_COMPILE_DEFINITIONS`, `INTERFACE_INCLUDE_DIRECTORIES` and `INTERFACE_LINK_LIBRARIES` in `aws-cpp-sdk-core-targets.cmake`.

Additionally `link_directories` is an obsolete functionality as mentioned in  https://cmake.org/cmake/help/v3.9/command/link_directories.html hence should be avoided.

**Comment by singku** [comment]
I guess what you want is actually find_package(aws-cpp-sdk) as we did [in the past](https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/cpp/example_code/s3/CMakeLists.txt)

find_package(AWSSDK) is added recently for dependencies resolution and libraries locating.

**Comment by singku** [comment]
@jasjuang Do you still need help on this issue?

**Comment by jasjuang** [comment]
@singku Yes I do. I am still doing the workaround I mentioned in the last reply for the moment. It will be great to see `find_package(AWSSDK)` working as intended.

**Comment by singku** [comment]
I see the problems now. Instead of treating them as targets and pick up the attributes from targets, the purpose of find_package(AWSSDK REQUIRED) is to give customers an easy way to locate and decide which libraries you want to link against. AWSSDK itself is not a target like aws-cpp-sdk-core.

**Comment by singku** [comment]
@jasjuang  This should fix your problem now. https://github.com/aws/aws-sdk-cpp/wiki/Example-CMake-Scripts-to-Build-Your-Project-Against-CPP-SDK

**Comment by demeenta** [comment]
Hello guys, 
I have the same problem with AWSSDK. 

I follow the cpp-encoder- example in this page: 
https://aws.amazon.com/es/blogs/compute/introducing-the-c-lambda-runtime/

And, when I like compile the project with:
` cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=~/out`

I receive the following error:

`By not providing "FindAWSSDK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "AWSSDK", but
  CMake did not find one.

  Could not find a package configuration file provided by "AWSSDK" with any
  of the following names:

    AWSSDKConfig.cmake
    awssdk-config.cmake
`

I tried with the solution of @jasjuang but I could not fix it

**Comment by singku** [comment]
You need to install AWS SDK for C++

**Comment by wuchih-amazon** [comment]
@singku, I clearly saw my sdk's cmake files installed in "C:\Program Files (x86)\aws-cpp-sdk-all\lib\cmake" Nonetheless, my script still having trouble located them. I have also tried to tweak around package path like @jasjuang, but still having issue located the SDK.



`-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
set win32
CMake Error at CMakeLists.txt:25 (find_package):
  By not providing "Findaws-sdk-cpp-all.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "aws-sdk-cpp-all", but CMake did not find one.

  Could not find a package configuration file provided by "aws-sdk-cpp-all"
  with any of the following names:

    aws-sdk-cpp-allConfig.cmake
    aws-sdk-cpp-all-config.cmake

  Add the installation prefix of "aws-sdk-cpp-all" to CMAKE_PREFIX_PATH or
  set "aws-sdk-cpp-all_DIR" to a directory containing one of the above files.
  If "aws-sdk-cpp-all" provides a separate development package or SDK, be
  sure it has been installed.


-- Configuring incomplete, errors occurred!`

**Comment by francoamato** [comment]
Hi I have the same problem.
I have the asw sdk installed here: C:\Program Files(x86)\aws-cpp-ask-all
When I try to build my project I set this variable: -DAWSSDK_DIR="C:\\Program Files (x86)\\aws-cpp-sdk\\lib\\cmake\\AWSSDK" but I get this error:

 Could not find a package configuration file provided by "aws-cpp-sdk-core"
  with any of the following names:

    aws-cpp-sdk-coreConfig.cmake
    aws-cpp-sdk-core-config.cmake

So what's the solution?

**Comment by jmklix** [comment]
@francoamato, can you make sure that you're following all of the steps [here](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup-windows.html), and then open an issue/discussion if you are still running into any build problems?
