### ISSUE TITLE
How to specify sdk installation root dir

### ISSUE THREAD

**Issue by SubmarineX** [aws/aws-sdk-cpp#677]
I want to specify the installation root dir to "/usr/", there are other methods except add line `set(AWSSDK_ROOT_DIR, "<path/to/dir>")` in [AWSSDKConfig.cmake](https://github.com/aws/aws-sdk-cpp/blob/master/cmake/AWSSDKConfig.cmake), for example specify argument for cmake command.

**Comment by jliang1010** [comment]
cmake with -DCMAKE_INSTALL_PATH option should do

**Comment by SubmarineX** [comment]
Execute this command
`cmake  -DCMAKE_INSTALL_PATH=/usr`
Got this message:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_INSTALL_PATH
```

**Comment by jliang1010** [comment]
Sorry, 
-DCMAKE_INSTALL_PREFIX

**Comment by SubmarineX** [comment]
It works. Thank you!
