### ISSUE TITLE
TextToSpeechManager throws exception due to lifetime/destruction management

### ISSUE THREAD

**Issue by diablodale** [aws/aws-sdk-cpp#680]
TTSManager does not cleanup/end the work, threads, or callbacks it has created before it is destroyed. Later, the async work will complete and attempt to access the now destroyed TTSManager. This will cause crashes/exceptions. This is similar to the lifecycle problem of the 1.1.x version of TransferManager.

### Repro

Create a function and put all the following code steps in it

1. create a TTSManager and configure it with a driver, device, and voice.
2. create an empty SendTextCompletedHandler `SendTextCompletedHandler myhandler;`
3. call `ttsManager->SendTextToOutputDevice(textToSay.c_str(), myhandler);`

Now, call that function due to some input.

### Result

Crash via exception.
```
Exception thrown: read access violation.
this->m_activeDriver._Ptr->**** was 0xFFFFFFFFFFFFFFD7.
   this is inside TextToSpeechManager::OnPollySynthSpeechOutcomeRecieved()
   on line 148:   m_activeDriver->Prime();
```

### Expected

No crash or exception. To hear the speech.

### Reason for crash

1. ttsManager will start an async speech request to the AWS polly servers.
2. The function you wrote above that contains ttsManager ends. Therefore ttsManager falls out of scope and is destroyed.
3. AWS polly server creates the PCM data and returns it to the waiting thread
4. Thread receives the data and runs the code in OnPollySynthSpeechOutcomeRecieved()
5. Line 148 runs. This attempts to access a member variable of the already destroyed ttsManager. Therefore, this is an access violation and the program is terminated.

### Workaround

The user of the SDK *must* control the lifetime of ttsManager. The code must not allow ttsManager to destruct before all the work is complete. This can be difficult because there are no handles, ids, or other ways to track the work being done by ttsManager.

### What platform/OS are you using?
Windows 10 x64

### What compiler are you using? what version?
VS 2017 v15.3.5 Community
Compiling my solution with the v140 toolchain

### Can you provide a TRACE level log? (sanitize any sensitive information)

Not at this time.

### What's your CMake arguments?

Problem reproduces both with the NuGet packages (v1.1.60) and with local compile (v1.2.4) of the SDK.
I use VS2017 built-in cmake, therefore my cmake args are in json

```json
{
    "configurations": [
      {
        "name": "x64-Debug",
        "generator": "Visual Studio 15 2017 Win64",
        "configurationType": "Debug",
        "inheritEnvironments": [ "msvc_x64" ],
        "buildRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\build\\${name}",
        "cmakeCommandArgs": "-T v140",
        "buildCommandArgs": "-v:normal",
        "ctestCommandArgs": "",
        "variables": [
          {
            "name": "TARGET_ARCH",
            "value": "WINDOWS"
          },
          {
            "name": "CMAKE_INSTALL_BINDIR",
            "value": "${projectDir}/bin/"
          },
          {
            "name": "CMAKE_INSTALL_LIBDIR",
            "value": "${projectDir}/bin/"
          },
          {
            "name": "CMAKE_INSTALL_INCLUDEDIR",
            "value": "${projectDir}/bin/"
          },
          {
            "name": "BUILD_ONLY",
            "value": "s3;transfer;polly;text-to-speech"
          },
          {
            "name": "CUSTOM_MEMORY_MANAGEMENT",
            "value": "0"
          },
          {
            "name": "BUILD_SHARED_LIBS",
            "value": "0"
          },
          {
            "name": "FORCE_SHARED_CRT",
            "value": "1"
          },
          {
            "name": "ENABLE_TESTING",
            "value": "0"
          }
        ]
      }
    ]
}
```

**Comment by singku** [comment]
Thank you again for reporting this bug, we will have a look at it.

**Comment by marcomagdy** [comment]
Fixed in https://github.com/aws/aws-sdk-cpp/commit/0f417aa2aea11d47005411c8cc8b79a1abb82b11
It's available in the latest release.

Thanks
