### ISSUE TITLE
override the endpoint url

### ISSUE THREAD

**Issue by yandreiy** [aws/aws-sdk-cpp#686]
I am looking to write a test with the aws-sdk-cpp so that it connects to localstack.
From cli I can do:
`aws --endpoint-url=http://localhost:4576 sqs list-queues`

How to achieve this with aws-sdk-cpp ?

I have tried to override the url in config, but this way the client times out:
  ``` Aws::Client::ClientConfiguration config;
   clientConfiguration.endpointOverride = "http://localhost:4576";
   sqsClient = Aws::SQS::SQSClient( credentialsProvider, clientConfiguration );
```

### What platform/OS are you using? 
Ubuntu 16.04

### What compiler are you using? what version?
gcc 6.3

**Comment by marcomagdy** [comment]
Try this:

```cpp
clientConfiguration.endpointOverride = "localhost:4576"; // remove the http:// part
clientConfiguration.scheme = Aws::Http::Scheme::HTTP; // the default is HTTPS, which will cause signature-v4 to sign with localhost, and it won't match
```

**Comment by yandreiy** [comment]
@marcomagdy Thanks a lot, that works
