### ISSUE TITLE
UploadToKinesisFirehose- Put Record giving me Segmentation Fault.

### ISSUE THREAD

**Issue by sakthisg** [aws/aws-sdk-cpp#687]
### What platform/OS are you using?
Linux OS
### What compiler are you using? what version?
gcc-linaro-arm-linux-gnueabihf-4.9.2
### What's your CMake arguments?
cmake -DCMAKE_TOOLCHAIN_FILE=../../../prebuilts/toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="firehose" ..

### Can you provide a TRACE level log? (sanitize any sensitive information)
seems the it is not returning from the Makerequest..i dont see any return..
INFO] 2017-10-05 05:00:34 Aws_Init_Cleanup [3061256720] Initiate AWS SDK for C++ with Version:1.1.46
[INFO] 2017-10-05 05:00:34 CurlHttpClient [3061256720] GSS Initializing Curl library
[INFO] 2017-10-05 05:00:52 CurlHandleContainer [3034575952] Initializing CurlHandleContainer with size 25
[TRACE] 2017-10-05 05:00:52 FirehoseClient [3034575952] GSS  Enter PutRecord
[TRACE] 2017-10-05 05:00:52 FirehoseClient [3034575952] GSS  Calling Make Request
[ERROR] 2017-10-05 05:00:52 AWSClient [3034575952] GSS AWS CLIENT Calling http Outcome
[ERROR] 2017-10-05 05:00:52 AWSClient [3034575952] GSS AWS CLIENT Enter AttemptExhaustively

BackTrace:

Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in ?? ()
#0  0x00000000 in ?? ()
#1  0x00037c1c in Aws::Firehose::FirehoseRequest::GetHeaders (this=<optimized out>)
    at include/aws/firehose/FirehoseRequest.h:36
#2  0xb66d0e12 in Aws::Client::AWSClient::BuildHttpRequest (this=0xb3e266c4, request=..., httpRequest=...)
    at /aws/aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSClient.cpp:431
#3  0xb66d0036 in Aws::Client::AWSClient::AttemptOneRequest (this=0xb3e266c4, uri=..., request=..., method=Aws::Http::HTTP_POST,
    signerName=0xb6744ed0 <Aws::Auth::SIGV4_SIGNER> "SignatureV4")
    at /aws/aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSClient.cpp:293
#4  0xb66cf41c in Aws::Client::AWSClient::AttemptExhaustively (this=0xb3e266c4, uri=..., request=..., method=Aws::Http::HTTP_POST,
    signerName=0xb6744ed0 <Aws::Auth::SIGV4_SIGNER> "SignatureV4")
    at /aws/aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSClient.cpp:186
#5  0xb66d158e in Aws::Client::AWSJsonClient::MakeRequest (this=0xb3e266c4, uri=..., request=..., method=Aws::Http::HTTP_POST,
    signerName=0xb6744ed0 <Aws::Auth::SIGV4_SIGNER> "SignatureV4")
    at /aws/aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSClient.cpp:562
#6  0xb646f920 in Aws::Firehose::FirehoseClient::PutRecord (this=0xb3e266c4, request=...)
    at /aws/aws-sdk-cpp/aws-cpp-sdk-firehose/source/FirehoseClient.cpp:289
#7  0x00034aa6 in AwsWrapperImpl::UploadToKinesisFirehose (this=this@entry=0xc0190, objstring=...) at src/AwsWrapper.cpp:462
#8  0x000350b0 in UploadToKinesisFirehose (objstring=..., this=0xb47fecc0) at src/AwsWrapper.h:110
#9  AwsWrapper::EventsPacket::Send (this=this@entry=0xb47fed08) at src/AwsWrapper.cpp:178
#10 0x0008c4ce in UploadImpl::uploadEvents (this=0xc00a8) at src/Upload.cpp:201
#11 0x0008c94e in UploadImpl::handleMsg (this=this@entry=0xc00a8, id=<optimized out>, data=<optimized out>) at src/Upload.cpp:453
#12 0x0008ca1e in UploadImpl::uploadThread (this=0xc00a8) at src/Upload.cpp:491
#13 0x0008cb9e in operator()<, void> (__object=<optimized out>, this=<optimized out>)
    at /ntktool/SDK/gcc-linaro-arm-linux-gnueabihf-4.9-2014.08_linux/gcc-linaro-arm-linux-gnueabihf-4.9-2014.08_linux/arm-linux-gnueabihf/include/c++/4.9.2/functional:569
#14 _M_invoke<0u> (this=<optimized out>)
    at /ntktool/SDK/gcc-linaro-arm-linux-gnueabihf-4.9-2014.08_linux/gcc-linaro-arm-linux-gnueabihf-4.9-2014.08_linux/arm-linux-gnueabihf/include/c++/4.9.2/functional:1700
#15 operator() (this=<optimized out>)
    at /ntktool/SDK/gcc-linaro-arm-linux-gnueabihf-4.9-2014.08_linux/gcc-linaro-arm-linux-gnueabihf-4.9-2014.08_linux/arm-linux-gnueabihf/include/c++/4.9.2/functional:1688
#16 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (UploadImpl::*)()> (UploadImpl*)> >::_M_run() (this=<optimized out>)
    at /ntktool/SDK/gcc-linaro-arm-linux-gnueabihf-4.9-2014.08_linux/gcc-linaro-arm-linux-gnueabihf-4.9-2014.08_linux/arm-linux-gnueabihf/include/c++/4.9.2/thread:115
#17 0xb5ba649c in ?? ()
#18 0xb5ba649c in ?? ()

if i comment the putrecord call i dont see the segmentation fault. (OfCourse upload will not be down )
Also i see one of the mail thread https://github.com/aws/aws-sdk-cpp/issues/221 , stack size to be increased. Let me know how much minimum stack size we need?

**Comment by marcomagdy** [comment]
Hey, can you provide a sample code to repro this problem?

**Comment by sakthisg** [comment]
Hi , Thanks for the response! the issue was because of the mismatch of header files used for the library creation(release 1.1.42) and linking the application(master branch). Once i have taken the same header files for both(1.1.42), i did not see the crash. Thanks for help.
