### ISSUE TITLE
broken log statement when using proxy on windows

### ISSUE THREAD

**Issue by cedral** [aws/aws-sdk-cpp#688]
This is very straightforward. You are passing a string instead of a const char * to a %s format identifier on line 59 of aws-cpp-sdk-core\source\http\windows\WinINetSyncHttpClient.cpp. 

```c++
if (isUsingProxy)
    {
        AWS_LOG_INFO(GetLogTag(), "Http Client is using a proxy. Setting up proxy with settings host %s, port %d, username %s.",
-            config.proxyHost, config.proxyPort, config.proxyUserName);
+            config.proxyHost.c_str(), config.proxyPort, config.proxyUserName.c_str());

        inetFlags = INTERNET_OPEN_TYPE_PROXY;
        Aws::StringStream ss;
```

**Comment by wps132230** [comment]
Hi, how about update your c++ SDK to the latest version?
I think this problem has already been fixed. We use `operator<<` instead in the log statement now.
https://github.com/aws/aws-sdk-cpp/blob/6aad4c229dad66c4e76b66d37e01939a0f0bbf13/aws-cpp-sdk-core/source/http/windows/WinINetSyncHttpClient.cpp#L58
And here is the commit we made this change:
https://github.com/aws/aws-sdk-cpp/commit/fc0ffbc55a244e5385b26249e9f761e002419807#diff-19cbb4cc1742f5d0ab86717da1ad20b1

**Comment by cedral** [comment]
yeah that is fine. Ignore this I am having a git problem. I did a pull in master yesterday and didn't get this change. I am not sure what happened. But I'll figure that out myself.
