### ISSUE TITLE
s3 low download speed after migrating to ubuntu 14.04

### ISSUE THREAD

**Issue by hrjaco** [aws/aws-sdk-cpp#694]
### What platform/OS are you using?
14.04

### What compiler are you using? what version?
gcc 5.4.1

### Can you provide a TRACE level log? (sanitize any sensitive information)

Our instance is on aws ec2. We used to see 1Gb/sec download speed from s3(on c3.8xl instance) when running the same code on ubuntu 12. After migrating to ubuntu 14, with the same code, we only saw 100Mb/sec download speed from s3. If we directly use s3cmd for example, the download speed is still as high as before, so we are wondering could there be any change inside aws-sdk that could potentially cause this issue?

**Comment by wps132230** [comment]
We made some changes in `TransferManager` recently, but not sure if that's the reason slowing down the speed. Thank you for your questions, we will take a look.

**Comment by hrjaco** [comment]
thanks! I was using https://github.com/aws/aws-sdk-cpp/commit/39a03136ef8525bc94d82669432491e653154677 and tried to upgrade to latest master code yesterday. Both showed decreased downloading speed when migrating to ubuntu 14.

**Comment by marcomagdy** [comment]
You said using the same code. But I wonder if you also mean the same SDK code.
I'm only asking because it seems like we have a regression reported here https://github.com/aws/aws-sdk-cpp/issues/711

**Comment by hrjaco** [comment]
Yes, it's both same SDK code and same our code to use the SDK. We just saw difference downloading speed by using ubuntu 12 vs ubuntu 14.

**Comment by marcomagdy** [comment]
The regression affects uploads only. My bad.

**Comment by KaibaLopez** [comment]
Hi @hrjaco, I'm trying to go clear up the repo and I'd like to ask, are you still facing this issue?

**Comment by hrjaco** [comment]
Yes, we can close this one. IIRC it turned out to be an issue on our end, where we has been misusing one param.
