### ISSUE TITLE
S3 Multipart Copy API Error

### ISSUE THREAD

**Issue by pcaswell** [aws/aws-sdk-cpp#701]
### What platform/OS are you using?
Window 7 Professional 64bit
### What compiler are you using? what version?
Visual Studio 2017
### What's your CMake arguments?
cmake ../aws-sdk-cpp-1.1.56 -G "Visual Studio 15 2017 Win64" -DSIMPLE_INSTALL=OFF \
	-DCMAKE_INSTALL_PREFIX="../MyLibs/aws-sdk-cpp-1.1.56"
### Can you provide a TRACE level log? (sanitize any sensitive information)
[aws_sdk_2017-10-20-09.log](https://github.com/aws/aws-sdk-cpp/files/1401338/aws_sdk_2017-10-20-09.log)

### Problem Details
Hello Forum,
I am struggling with the multi-part copy mechanism of the SDK S3Client.  I have large objects (5GB and 100MB) in one of my buckets and I'm trying to use them as the source of a multi-part copy.  My test program doesn't want to work and I cannot see why so any help would be appreciated.  Here's my simple test program (sanitized)....

[test_multipartcopy.cpp.txt](https://github.com/aws/aws-sdk-cpp/files/1401105/test_multipartcopy.cpp.txt)

The 'pS3Client->CreateMultipartUpload(oCMPURequest)' call succeeds.
The 'pS3Client->UploadPartCopy(oUPCRequest)' call fails with an error - it's none of the S3Errors.  There is no ETag in set in the response.

I also have the AWS CLI installed on the same machine (with Python 3.6) and I can make the multi-part copy work using that.  Here's the CLI commands.

[test_multipartcopy.using_cli.txt](https://github.com/aws/aws-sdk-cpp/files/1401130/test_multipartcopy.using_cli.txt)

So the questions are :
1) Is there something missing in my test program - if so what?
2) Is this a know bug in SDK version 1.1.56 and is it fixed? If so what version?

Regards,
Paul

**Comment by wps132230** [comment]
Hi, if you want to upload large files, how about using the high level API `TransferManager`? I find it in your header files, but is never used. And it's also recommended to use the latest version, since we made some modification in `TransferManager`, including some API changes since 1.1.56.

**Comment by pcaswell** [comment]
Thanks for the reply wps132230.  I am aware of the TransferManager (hence the header in the test file) but I need the multipart copy to work (it does in the AWS CLI).    Can you look again at my initial questions as I they've not been answered by your response.  I'll get the latest SDK and try it out but obviously that's time consuming so it would be good to know whether the latest version incorporates any fixes that might address the MPU.

**Comment by pcaswell** [comment]
I think this is a bug but can't quite see what the problem is at present. Any help appreciated.

I have traced the call through to:
WinSyncHttpClient::BuildSuccessResponse(...) in WinSyncHttpClient.cpp (line 174)
At Line 218 of this file we call DoReadData(...)
The 1024 byte body buffer at this point contains the response I expect: i.e.:
 
 <?xml version="1.0" encoding="UTF-8"?>
  <CopyPartResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <LastModified>2017-10-22T14:39:10.000Z</LastModified>
  <ETag>&quot;b8fc857a25e7958868c2f003d5e0952d&quot;</ETag>
  </CopyPartResult>
  
Therefore AWS is returning the expected response but for some reason that response is not appearing in UploadPartCopy () result.
 
In the same file (Line 229) we call request.GetDataReceivedEventHandler(), this returns null
so 'receivedHandler(...) is not called - should it be ???  Should it have been set if so where?

Keep tracing back up through the stack ..
AWSClient.cpp Line 685 in AWSXMLClient::MakeRequest(...)
The httpOutcome | result | bodyStream | m_underlyingStream | contains the above result...

Trace this through into XmlSerializer.cpp XmlDocument::CreateFromXmlStream( ... ) Line 208
As this point the 'xmlString' contain the expected response :-)
The XML is parsed correctly by the look of it.

Up again to AWSXMLClient::MakeRequest(...) xmlDoc (line 687) is parsed correctly
and from this we create an XmlOutcome at line 695.  Note the XML at this point contains the values we expect.  At this point the original data seems to be lost - cant see why at present ???

**Comment by marcomagdy** [comment]
Thanks for reporting the problem. Looking into it.

**Comment by pcaswell** [comment]
No problem.
Thanks.

**Comment by marcomagdy** [comment]
Fixed the bug, will merge it soon.

**Comment by marcomagdy** [comment]
Latest version should have the fix.
Please let us know if you're still having problems.
Thanks
