### ISSUE TITLE
No version for cmake in list

### ISSUE THREAD

**Issue by krisgoku2** [aws/aws-sdk-cpp#705]
No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.9)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by singku** [comment]
It's not at the top of the list file, but you can find it right after the license description from
[here](https://github.com/aws/aws-sdk-cpp/blob/bacce5952061503537fca2ee96bb5cb4f2e41a74/CMakeLists.txt#L16).

**Comment by singku** [comment]
@krisgoku2 Do you still need help on this issue?
