### ISSUE TITLE
AWSSDK_DETERMINE_LIBS_TO_LINK output should be ordered properly

### ISSUE THREAD

**Issue by paresy** [aws/aws-sdk-cpp#709]
### What platform/OS are you using?
Linux

### What compiler are you using? what version?
GCC 6.4

### What's your CMake arguments?
-DBUILD_ONLY="core;s3;transfer" -DBUILD_SHARED_LIBS="OFF" -DMINIMIZE_SIZE="ON" -DENABLE_TESTING="Off"

### CMakeLists.txt snippet
```
find_package(AWSSDK REQUIRED)
set(SERVICE transfer)
AWSSDK_DETERMINE_LIBS_TO_LINK(SERVICE AWS_LIBRARIES)
include_directories(${AWSSDK_INCLUDE_DIR})
link_directories("${AWSSDK_LIB_DIR}")

message(${AWS_LIBRARIES})
```

### Actual Output
-- Found AWS SDK for C++, Version: 1.2.20, Install Root:/usr/local, Platform Prefix:, Platform Dependent Libraries: pthread;curl

**aws-cpp-sdk-core**aws-cpp-sdk-transferaws-cpp-sdk-s3

### Expected output 
-- Found AWS SDK for C++, Version: 1.2.20, Install Root:/usr/local, Platform Prefix:, Platform Dependent Libraries: pthread;curl

aws-cpp-sdk-transferaws-cpp-sdk-s3**aws-cpp-sdk-core**

### What should be fixed?
aws-cpp-sdk-core should be listed last, to ensure proper linking order for static linking. 

PS: I love the new AWSSDK_DETERMINE_LIBS_TO_LINK macro :)

**Comment by singku** [comment]
Hi, this issue has been fixed at https://github.com/aws/aws-sdk-cpp/commit/e42fbd9d0f2240ac4735a4d46a07e2a44015538f
Please reopen if you have further problem.
