### ISSUE TITLE
CMake target imposing no exceptions and -Werror on my code

### ISSUE THREAD

**Issue by psalvaggio** [aws/aws-sdk-cpp#710]
### What platform/OS are you using?
Fedora 25

### What compiler are you using? what version?
G++ 6.4.1

### What's your CMake arguments?
-CMAKE_INSTALL_PREFIX=$HOME -CMAKE_BUILD_TYPE=Release

### Can you provide a TRACE level log? (sanitize any sensitive information)

I was trying to use the AWS SDK in my code, however, any target that links to one of the targets seem to have exceptions disabled and also get the -Werror flag on them, both of which are causing my code to not build in unrepairable ways. Is there any way to build the AWS SDK to not attach these public properties to the installed targets?

**Comment by Bu11etmagnet** [comment]
How did you try to use the AWS SDK? Linking has no effect on exception handling. Did you make your code part of the AWS SDK build system?

**Comment by psalvaggio** [comment]
I installed the AWS SDK to my system using the install target made by CMake then put a
```
find_package(aws-cpp-sdk-core)
find_package(aws-cpp-sdk-s3)
```
into my code and linked my target with
```
target_link_libraries(my-target PUBLIC aws-cpp-sdk-s3)
```
so, my target inherits all of the PUBLIC properties of aws-cpp-sdk-s3, which seem to include -fno-exceptions and -Werror.

**Comment by psalvaggio** [comment]
The source of these flags appears to be ${CMAKE_INSTALL_PREFIX}/lib64/cmake/AWSSDK/compiler_settings.cmake in the set_gcc_flags() and set_gcc_warnings() and are set in set_compiler_flags() where they are all made PUBLIC.

**Comment by singku** [comment]
-fno-expections, -Werror together with other compiler settings are set up in core as PUBLIC and inherited by service sdks, as well as by customer applications, so that we can make the compiler settings consistent across service SDKs and customer applications, which gives customers a much better experience.

**Comment by psalvaggio** [comment]
That makes a lot of sense in the build environment. Would it be possible to use the $<BUILD_INTERFACE:> and $<INSTALL_INTERFACE:> generator expressions to leave those flags off for the install interface? That would make it a lot easier to integrate this library with existing legacy codebases.

**Comment by marascio** [comment]
Infecting applications that use the SDK with your compile flags is bad form. Surprised this is labeled as an enhancement.

**Comment by singku** [comment]
This issue has been fixed at https://github.com/aws/aws-sdk-cpp/commit/b8cefc0b3c33eb2ce12a8f610ac305edfbba3194. Reopen if you still has this kind of problem. Thanks.
