### ISSUE TITLE
Potential hang in `CurlHandleContainer` and `WinConnectionPoolMgr` on getting new connection

### ISSUE THREAD

**Issue by oliora** [aws/aws-sdk-cpp#713]
I suspect that both `CurlHandleContainer::AcquireCurlHandle()` and `WinConnectionPoolMgr::AquireConnectionForHost()` can hang when they not supposed to.

I'll describe the scenario for `CurlHandleContainer`. `WinConnectionPoolMgr` has absolutely the same behavior.

```
CURL* CurlHandleContainer::AcquireCurlHandle()
{
    AWS_LOGSTREAM_DEBUG(CURL_HANDLE_CONTAINER_TAG, "Attempting to acquire curl connection.");

    if(!m_handleContainer.HasResourcesAvailable())  // [1]
    {
        AWS_LOGSTREAM_DEBUG(CURL_HANDLE_CONTAINER_TAG, "No current connections available in pool. Attempting to create new connections.");
        CheckAndGrowPool();  // [2]
    }

    CURL* handle = m_handleContainer.Acquire();  // [3]
    AWS_LOGSTREAM_INFO(CURL_HANDLE_CONTAINER_TAG, "Connection has been released. Continuing.");
    AWS_LOGSTREAM_DEBUG(CURL_HANDLE_CONTAINER_TAG, "Returning connection handle " << handle);
    return handle;
}
```

Scenario:
- There is a `CurlHandleContainer` object with empty`m_handleContainer`.
- Two threads call this object's `CurlHandleContainer::AcquireCurlHandle()`
- *Thread A* calls `m_handleContainer.HasResourcesAvailable()` [1] and get `false`
- *Thread A* calls `CurlHandleContainer::CheckAndGrowPool()` [2], which creates a new CURL handle and puts it into `m_handleContainer`
- *Thread B* calls `m_handleContainer.HasResourcesAvailable()` [1] and get `true`
- *Thread B* calls `m_handleContainer.Acquire()` [3] and get handle created by *Thread A*. `m_handleContainer` is empty again.
- *Thread A* calls `m_handleContainer.Acquire()` [3] assuming there is a CURL handle available for him (which is not true anymore) and hangs there until someone has released a CURL handle.

The issue exist in mainline.

**Comment by oliora** [comment]
The simplest fix would be to return a newly created handle (if any) from `CurlHandleContainer::CheckAndGrowPool()` [2] thus call to `m_handleContainer.Acquire()` [3] will happen only when the max pool size is reached thus thread has to wait until a CURL handle is released anyway.

**Comment by singku** [comment]
Thank you for reporting this bug. We thought this has been solved in `9e001f60ada3be7cf471dc4b79ce275b4919874c`, but obviously, this is another scenario we missed. We will fix it ASAP.

**Comment by oliora** [comment]
Sure. You welcome!

**Comment by singku** [comment]
After discussing with team, we came up with following ideas:
First, threads will not be hang but block. Second, when we grow the pool, we don't grow it by 1, we have a multiplier, so at least we grow by two. Third, technically, if you have 3 threads, you can still get into that situation, in which we grow the pool from 0 to 2, and now 1 thread waits, but that's a rare scenario and is not worth complicating the code over. Because it doesn't produce wrong results, it's just not as optimal as it can be.

**Comment by oliora** [comment]
It's sad to hear this. I completely disagree that the issue is minor. Just because it needs three threads to be in a particular state. In my experience, in heavily multithread applications any possible data race will happen. And please note that it will happen in the client application possibly the low latency one. And then the client will spend hours and days trying to figure out why he has latency spikes on p99.99...

I also found another (more likely) scenario when `CurlHandleContainer::AcquireCurlHandle()` may hang:
- There is a `CurlHandleContainer` object with `m_handleContainer` with one available handle in it.
- Two threads call this object's `CurlHandleContainer::AcquireCurlHandle()`
- *Thread A* calls `m_handleContainer.HasResourcesAvailable()` [1] and get `true`
- *Thread B* calls `m_handleContainer.HasResourcesAvailable()` [1] and get `true`
- *Thread B* calls `m_handleContainer.Acquire()` [3] and get the available handle. `m_handleContainer` is now empty.
- *Thread A* calls `m_handleContainer.Acquire()` [3] assuming there is a CURL handle available for it (which is not true anymore) and blocks until someone has released a CURL handle.

This scenario seems more likely to occur because it requires only two threads and it can happen any time `m_handleContainer` has only one handle available regardless the pool size.

**Comment by crusader-mike** [comment]
I agree with @oliora -- there is no good reason to have race conditions in the code.

But, as a some sort of workaround -- what about giving user ability to pre-populate that connection cache? In my code I know that I'll have exactly N parallel requests -- I could let SDK know, it'll preallocate required number of curl handles.

**Comment by marcomagdy** [comment]
> there is no good reason to have race conditions in the code.

Just to be clear, this is not a race condition in the sense that it produces undefined behavior, incorrect results, deadlocks, etc.

Depending on the order of thread execution you could potentially over-optimize by growing the pool too much (calling `Grow` more than once), or pessimize when one thread blocks when it shouldn't.

Also, the two scenarios that @oliora mentioned are almost identical. It has nothing to do with three threads or two threads. It was just an example. You could get into the same situation having 8 handles in the pool, 7 of them are in use, and one is free.

My point is, in practice, this undesired thread blocking is amortized over the life of the application. So, if your application runs only for a few seconds and it happens to use the async API versions, then yeah sure, this might be a problem for you. But if your application runs for longer than that, and makes many async calls, then the cost (if that situation happened) will be amortized over the life of the application.

Finally, the plan for the SDK is to eventually move to event-based async IO and completely do away with the current threaded-model.

**Comment by oliora** [comment]
@marcomagdy why do you mention async API version? Isn't CurlHandleContainer used everywhere, including sync APIs?

**Comment by marcomagdy** [comment]
Yes, curl is used everywhere. But if your application is only using the synchronous APIs (in a single thread) then you will only use one curl handle at most.

**Comment by oliora** [comment]
This means that the issue may happen in any application that calls the SDK from more than one thread, regardless of API.
I agree that latency introduced by the issue is amortized over the application lifetime, but it’s still extra latency introduced for no good reason. Switching to new IO approach for the SDK might bring a solution for the issue but it's not here yet.
As a developer of heavily multithread applications that rely on the SDK (Amazon Workmail) I’d like this issue to be fixed. Are you OK if I send a PR for the fix?

**Comment by marcomagdy** [comment]
By all means, please do.

**Comment by oliora** [comment]
@marcomagdy I have few questions about the implementation:
- Do I need to keep ABI for `CurlHandleContainer` and `WinConnectionPoolMgr`? It seems that they're only used in `HttpClient` child classes which aren't exposed to the user except thru the base interface thus it should not matter, but still...
- How important is to have pools with double size grow strategy? I understand this for vector (because of copying/moving all the elements) but why was it introduced for the SDK network connection pools?

**Comment by crusader-mike** [comment]
last time I checked it was 3x growing strategy :)

**Comment by marcomagdy** [comment]
@oliora 
1- You can change the API (different from ABI) of CurlContainer. 
2- doubling the size of the pool is a good heuristic. I don’t understand your reasoning for why it’s ok for standard containers but not for the handles. Memory is a resource and so are curl handles.

**Comment by oliora** [comment]
@crusader-mike, yep, I didn’t put it correctly enough. It grows by adding 2x of current size so yes, 3x grow each time :)

@marcomagdy not standard containers but vector. The reason for its growing strategy is the unefficiency of single element growth when the elements contiguously need to be maintained.
But I don’t understand why the SDK connection pool has 3x grow strategy. Why is it here and how is it better than just grow by one connection at the time?

**Comment by marcomagdy** [comment]
>not standard containers but vector

`std::unordered_set`, `std::unordered_map` and `std::deque` use a 2x growth strategy in libc++ and they do _not_ store their elements contiguously. But anyways, I think I understand your question now.

>But I don’t understand why the SDK connection pool has 3x grow strategy

This is a silly bug. Pretty sure the intent was to simply double the size.

>Why is it here and how is it better than just grow by one connection at the time?

I think the idea was to make one thread pay for the cost of growing the pool instead of spreading the work across multiple threads. Feel free to change that though.

**Comment by oliora** [comment]
> `std::unordered_set`, `std::unordered_map` and `std::deque` use a 2x growth strategy in libc++ and they do not store their elements contiguously.
That's not entirely correct. `std::deque` has 2x grows strategy only for chunks map which stores its elements contiguously (it's like a vector but with capacity available both at the front and back of the container) but not for chunks itself. Chunks are allocated when they're needed rather than along with the chunks map growth. I haven't check unordered containers implementation (it's quite complex to spend time on it) but it's growth strategy is probably dictated by the internal hash algorithm (hash=>bucket_index), cost of rehashing and maintaining the `max_load_factor` rather than elements contiguously (although the buckets can be stored stored in the vector thus there is still some contiguously :)
Anyway, I don't see a reason to use 2x growth for connection pool since the amount of work that need to be done is the same and latency and memory-wise it's more optimal to have the exact number of connections the user wants (with the exception of the case when user can preallocate the expected number of connections at startup but this has nothing with pool growth strategy).

**Comment by singku** [comment]
@oliora What's the status of your PR?

**Comment by oliora** [comment]
@singku almost ready. Will submit it before Monday

**Comment by singku** [comment]
After replay all the discussions above. I think @marcomagdy and @JonathanHenson are actually correct. SDK will not hang but block (wait for other threads to release handles). @oliora it's correct that thread A grows the handle but thread B takes it, A returns and no handle is available. This is block, not hang. The http request will finish and thread B will release handle, then A will get the handle eventually.  

First of all, this is HTTP request, threads will not hold handles forever. And even if it will, we have a max limitation for total handles and if that max hits and if no thread is going to release HTTP handle, the waiting thread will still block. That's the same issue, just different amount.

Based on this, I think this is not a problem in SDK. And It seems your PR has a new resource management implementation, which is complicating the code base over and test is missing.

I am going to close this issue and the PR for now. If you have any concerns and better solution for this problem, please reopen and we are pleased to discuss further.

**Comment by crusader-mike** [comment]
amazing...

**Comment by JonathanHenson** [comment]
Adding to @singku’s response curl is going away in the somewhat near future in favor of async event driven implementations so we’ll address the blocky nature of it there.

**Comment by crusader-mike** [comment]
that is better... :-) 
Andrew's arguments couldn't stand to any sort of scrutiny, imho

**Comment by JonathanHenson** [comment]
@crusader-mike


https://github.com/awslabs/aws-c-common/

Feel free to follow progress/ contribute here.

Work is in progress.

**Comment by singku** [comment]
@JonathanHenson Isn't awslabs a private org?

**Comment by JonathanHenson** [comment]
@crusader-mike yes libcurl "supports" an async mode. There's more in play in the long term as far as application protocols go. The threading model in the current version of the SDK makes a lot of this hard to use. 

But mainly, we want to eliminate shared memory across threads, while maintaining the minimal dependencies approach.

**Comment by JonathanHenson** [comment]
@crusader-mike I discussed this briefly in my cppcon talk from 2017 if you're interested.

**Comment by crusader-mike** [comment]
@JonathanHenson Thanks, I'll find and watch your cppcon talk and will check out aws-c-common. I see you followed up on your original "it is much simpler to write it in C" threat :D

> But mainly, we want to eliminate shared memory across threads, take advantage of the best PKI/TLS implementation we can (which libcurl doesn't allow us to control without requiring customers to manually rebuild the libcurl on their system), use the correct IO implementation for each platform (Edge Triggered Epoll, KQueue, IOCP, /dev/poll etc...) while maintaining the minimal dependencies approach.

If it isn't covered in your talk -- can you direct me to some document that describes approach taken on a high level? Do you aim for smth like "Symmetric Multi-Process EDSM" or you have some other architecture in mind?

I certainly wouldn't mind using an AWS library that works with `libuv`-like event loop and can be used with coroutines... and fully asynchronous (including DNS lookups). :)

**Comment by oliora** [comment]
@singku I would disagree that my change makes code more complex. It's other way around because it splits responsibilities between classes more clearly and makes each class simpler. I can buy your argument about tests (although there was no tests for this part before as well, probably because it's anyway tested via all other tests) but then the solution would be to ask me to add tests rather than close my PR and the issue. But after all it's up to you to decide what's important for the project and what's not. I'm fine with closing the issue if you guys are rewriting the networking layer anyway.

**Comment by oliora** [comment]
@JonathanHenson it sounds interesting what you're going to implement. I have few related questions:
1. Is there ETA for the new networking layer?
2. Currently we hold SDK clients as members in our objects that are stored in TLS. It would be a big change for us (and probably less effective as well) if we have to query the SDK for TLS-bound clients instead of just storing them as members. With the new networking layer will be there possibility to manually manage the SDK clients as it's possible now?
3. We use `boost::asio` for all IO except related to the SDK. `boost::asio` is not far from becoming  a standard IO implementation in C++ (see Networking TS). Will it be possible to integrate the SDK's new networking layer with `boost::asio`?

**Comment by JonathanHenson** [comment]
1. Not one that I’d be willing to commit to publicly.

2. It appears you are taking TLS to mean thread local storage? If so, I mean transport layer security (ssl). The api won’t change, and we’re building mechanisms to take requests on the client and move them into the event loop thread (without a mutex too)

3.  The C SDK will expose an event loop abstraction that you can plug in a custom impl via c style runtime polymorphism.

**Comment by crusader-mike** [comment]
@JonathanHenson Just watched your [presentation](https://www.youtube.com/watch?v=JPdohAomZD8&list=PLHTh1InhhwT6bwIpRk0ZbCA0N2p1taxd6&index=71) -- it was quite amusing, especially when someone mentioned Java at the end ;-). I swear that guy wasn't me!

About library design in general -- you could also consider approach where majority of functionality is confined to templates and inline functions (potentially) backed by a minimal library (.so/.a/.dll/.lib) with (probably) pure-C API. Just like STL.

Also, it was worth to mention few extra things, like:
- virtual functions block compiler/linker ability to remove unused code
- there are few programmers out there that can write a correct `std::streambuf` implementation
