### ISSUE TITLE
feature request: timeout on inactivity

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#716]
SDK uses "request timeout" for timing out logic. There are few problems with this:
1. it doesn't work very well with curl (which uses it's own timeouts in dns resolution logic)
2. it seems that 'upload requests' (e.g. PutObject) needs to complete within `request timeout` or it fails, but it is not so for 'download requests' -- yesterday (Win7,x64) I observed GetObject request that wasn't failing at all even though it took a minute to complete (it was retrieving ~0.5Gb) and timeout was set to 3 seconds. And yet occasionally it was failing in the middle sometimes with log message indicating timeout, sometimes with message complaining about content-length being not same as body length. 
3. and most importantly -- this approach breaks down if you deal with low-bandwidth connection or relatively large objects. To transfer such objects you need to set timeout to very large value (could be hours), which means that if something went wrong (network went down) -- your program can be blocked for long period of time before getting failure from SDK.

One workaround is to split everything into smaller chunks -- multipart upload and download (and use relatively small "request timeout" with each request that deals with each chunk). It seem to work with everything but very large files (where part size becomes too big due to hard limit on part count). It also hurts transfer performance.

What we need is 'activity timeout': if in last N seconds we transferred less than X bytes -- cancel transfer. Make X = 0 by default, N = 20 or some other common sense values.

**Comment by singku** [comment]
The scenarios for different users varies, it's hard to use a specific logic to conciliate these differences. Maybe a possible solution is to give user the ability to instrument a timeout strategy, like what we have done for retry.

**Comment by crusader-mike** [comment]
I think the biggest problem is to coerce libcurl to behave, but I'll take anything that will allow me to achieve what I've described.

**Comment by marcomagdy** [comment]
>SDK uses "request timeout" for timing out logic.

We don't. timing out logic is based on the transfer speed.
```cpp
 curl_easy_setopt(handle, CURLOPT_LOW_SPEED_TIME, m_requestTimeout / 1000);  
```

I realize this is a 2.5 years old issue, and we possible fixed it in reaction to this. But regardless, this does not apply anymore if I understand it correctly.
