### ISSUE TITLE
unused parameter error

### ISSUE THREAD

**Issue by RobertHerreraEECS** [aws/aws-sdk-cpp#717]
### What platform/OS are you using?
OSX 10.12.3
### What compiler are you using? what version?
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.4.0

GNU Make 3.81
### What's your CMake arguments?
cmake -Daws-sdk-cpp_DIR=~/Desktop/aws-sdk-cpp/ ../s3

### Can you provide a TRACE level log? (sanitize any sensitive information)
Scanning dependencies of target set_acl
[ 44%] Building CXX object CMakeFiles/set_acl.dir/set_acl.cpp.o
/Users/Robert/Desktop/aws-examples/aws-doc-sdk-examples/cpp/example_code/s3/set_acl.cpp:40:17: error: unused parameter 'access' [-Werror,-Wunused-parameter]
    Aws::String access, Aws::String user_region)
                ^
/Users/Robert/Desktop/aws-examples/aws-doc-sdk-examples/cpp/example_code/s3/set_acl.cpp:70:36: error: unused parameter 'access' [-Werror,-Wunused-parameter]
    Aws::String email, Aws::String access, Aws::String user_region)

**Comment by singku** [comment]
I think you might want to report this to https://github.com/awsdocs/aws-doc-sdk-examples
