### ISSUE TITLE
Aws::Auth::AWSCredentials missing

### ISSUE THREAD

**Issue by adi619** [aws/aws-sdk-cpp#718]
https://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_auth_1_1_a_w_s_credentials_provider.html

Is this the correct documentation? I cannot find any class declarations for AWSCredentialProvider. Could you please help me with this issue. 

We need to create a s3 client and pass the credentials. There is a class named AWScredentialProvider but it is empty. Please let me know if there is any other way to do it.

**Comment by singku** [comment]
https://github.com/aws/aws-sdk-cpp/blob/da682606e2b693d444c1ed87b40ac23ff3fb7d7a/aws-cpp-sdk-core/include/aws/core/auth/AWSCredentialsProvider.h#L141

**Comment by jonsmirl** [comment]
They are there. Note that the STS Credentials struct is not the same Credentials struct as the core one and you have to copy the fields. This code works for me.

#include <aws/core/auth/AWSCredentialsProvider.h>

    Aws::Auth::AWSCredentials cred(
        sts_cred.GetResult().GetCredentials().GetAccessKeyId(),
        sts_cred.GetResult().GetCredentials().GetSecretAccessKey(),
        sts_cred.GetResult().GetCredentials().GetSessionToken()
    );
    Aws::S3::S3Client s3_client(cred);

**Comment by singku** [comment]
@adi619 If these comments answered your question, please close the issue, thank you.

**Comment by pankajagarwal** [comment]
@jonsmirl what's the class for sts_cred object ?

**Comment by singku** [comment]
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-sts/include/aws/sts/model/Credentials.h
