### ISSUE TITLE
Linux signal SIGRTMIN  cannot be captured after integrated with AWS C++ SDK

### ISSUE THREAD

**Issue by xinyisu79** [aws/aws-sdk-cpp#719]
### What platform/OS are you using?
Red Hat Enterprise Linux Server release 7.1 (Maipo)

### What compiler are you using? what version?
clang++ 3.8.1

### What's your CMake arguments?
cmake  -DBUILD_SHARED_LIBS=OFF -DBUILD_ONLY="s3" ..

### Can you provide a TRACE level log? (sanitize any sensitive information)
I encountered a wield issue when using SDK to access S3. My legacy code register signal SIGRTMIN  to trigger timer events. But it does not work anymore after I integrated AWS code into it. Signal SIGRTMIN is not captured. Instead, program crashed with `Real-time signal 0`.

        sev.sigev_notify = SIGEV_SIGNAL;
	sev.sigev_signo = SIGRTMIN;
	sev.sigev_value.sival_ptr = &(tc->timer_id_);

	::timer_create(CLOCK_REALTIME, &sev, &tc->timer_id_);
	struct itimerspec ts;
	::memset(&ts, 0, sizeof(ts));

	ts.it_interval.tv_sec = timeout;
	ts.it_value.tv_sec = delay;

	::timer_settime(tc->timer_id_, 0,  &ts, 0);

Can you help me to dig this issue? Your help is much appreciated.

**Comment by singku** [comment]
Thank you for reporting this. We will have a look.
