### ISSUE TITLE
Comment change: "authenticationRegion" comment is confusing since it is deprecated

### ISSUE THREAD

**Issue by amirkope** [aws/aws-sdk-cpp#720]
In ClientConfiguration.h, right above the endpointOverride member, you have the following comment regarding the no-longer-exist authenticationRegion field:
`/**
             * override the http endpoint used to talk to a service. Use this in conjunction with authenticationRegion.
*/
Aws::String endpointOverride;`

As far as I understand it authenticationRegion is not longer in use and no longer needed for overriding the endpoint so the second part of the comment can be removed.

**Comment by singku** [comment]
Thank you, will update the comment ASAP.

**Comment by wps132230** [comment]
Removed related comment in https://github.com/aws/aws-sdk-cpp/commit/84ccbb15a0f9dc26eb7f10a60cd399858ad18982, thank you for your suggestions again.
Issue closed, please reopen it if you have any other question.

**Comment by wps132230** [comment]
Removed related comment in https://github.com/aws/aws-sdk-cpp/commit/84ccbb15a0f9dc26eb7f10a60cd399858ad18982, thank you for your suggestions again.
Issue closed, please reopen it if you have any other question.
