### ISSUE TITLE
TransferHandle  performs single file upload

### ISSUE THREAD

**Issue by adi619** [aws/aws-sdk-cpp#721]
I'm trying to implement a multipart upload for a file of 1GB, I was able to upload the file but when I printed the uploadID and etag I could see only one uploadId and etag. How I split the file into multiple parts ?

Aws::S3::Model::ListMultipartUploadsRequest listMultipartUploadRequest;
                       listMultipartUploadRequest.SetBucket(bucket.c_str());
                       Aws::S3::Model::CreateMultipartUploadRequest uploadmultipartrequest;
                       uploadmultipartrequest.SetBucket(bucket.c_str());
                       std::shared_ptr<Aws::Utils::Threading::Executor> sdk_client_executor =  std::make_shared<Aws::Utils::Threading::DefaultExecutor>();
                   //TransferManagerConfiguration(Aws::Utils::Threading::Executor* executor) : s3Client(nullptr), transferExecutor(executor), transferBufferMaxHeapSize(10 * MB5), bufferSize(MB5), maxParallelTransfers(1)
                       Aws::Transfer::TransferManagerConfiguration transferConfig(sdk_client_executor.get());
                       transferConfig.s3Client = s3Client;
                       transferConfig.maxParallelTransfers = 1;
                       //transferConfig.bufferSize = Aws::Transfer::MB5 * 40;

                       transferConfig.uploadProgressCallback =
                                     [](const Aws::Transfer::TransferManager*, const std::shared_ptr<const Aws::Transfer::TransferHandle>&transferHandle)
                                     { std::cout << "Upload Progress: " <<  transferHandle->GetBytesTransferred() << " of " << transferHandle->GetBytesTotalSize() << " bytes\n";};

                       static std::shared_ptr<Aws::Transfer::TransferManager> transferManager = Aws::Transfer::TransferManager::Create(transferConfig);

                       std::shared_ptr<Aws::Transfer::TransferHandle> transferHandle = transferManager->UploadFile(fileToUploadWithPath.c_str(), bucket.c_str(), fileToUpload.c_str(),
                                                                                                                   "multipart/form-data", Aws::Map<Aws::String, Aws::String>());

                       size_t retries = 0;
                       transferHandle -> WaitUntilFinished ();
                       while (transferHandle->GetStatus() == Aws::Transfer::TransferStatus::FAILED && retries++ < 5)
                          {
                              transferManager->RetryUpload(fileToUploadWithPath.c_str(), transferHandle);
                              transferHandle->WaitUntilFinished();
                          }
                        transferHandle->SetIsMultipart(true);

                      
                       Aws::Transfer::PartStateMap completedParts  = transferHandle->GetCompletedParts();
                       string eTagList;
                      
                             for(const auto &p : completedParts )
                             {

                                 std::cout << "completedparts[" << p.first << "]" << p.second->GetETag() << '\n';
                                

                             }
                       

 

                       Aws::Transfer::TransferStatus status = transferHandle->GetStatus();
                       std::string res("Result:");
                       res.append(std::to_string((int)status));

                       std::cout << res.c_str() <<  std::endl;

                       Aws::ShutdownAPI(options);

**Comment by singku** [comment]
Hi, multi-part upload is done automatically for you.

**Comment by adi619** [comment]
Do I need to call any header files? Because as of now it is behaving like a single part upload.

**Comment by adi619** [comment]
uploadId 
oXuuMmSD7a2_A0QXbVPNmHNbSwqFj.x07MR.2ACESembQqlKFY2AB1TLc9Uqk6vJhyysbtTg2grm0K4j7.ZKrAoeDWfEBjLUS3kN4EIV2LkpexuxJ_TlQIWDs_HnbxPufilename 
aguad7_8666655



completedparts[1]"d41d8cd98f00b204e9800998ecf8427e"

{"etags":[{"etag":"d41d8cd98f00b204e9800998ecf8427e","pos":1}],
"uploadId":"oXuuMmSD7a2_A0QXbVPNmHNbSwqFj.x07MR.2ACESembQqlKFY2AB1TLc9Uqk6vJhyysbtTg2grm0K4j7.ZKrAoeDWfEBjLUS3kN4EIV2LkpexuxJ_TlQIWDs_HnbxPu"}

This is how the output looks like.

**Comment by wps132230** [comment]
Hi, the number of `uploadId` should be 1, it's the unique identifier for your multipart upload, but the number of `eTag` should be `ceiling(file_size/buffer_size)`.

For more details about `uploadId` and `eTag`: http://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html

But I could not reproduce the issue you have. Here is the code I am using, just removing some redundant code you provide:
```c++
#include <aws/core/Aws.h>
#include <aws/core/client/ClientConfiguration.h>
#include <aws/core/http/Scheme.h>
#include <aws/core/utils/threading/Executor.h>
#include <aws/s3/S3Client.h>
#include <aws/transfer/TransferManager.h>

using namespace std;
using namespace Aws::S3;
using namespace Aws::S3::Model;
using namespace Aws::Client;
using namespace Aws::Http;

static const char* const ALLOCATION_TAG = "S3_MULTIPART_TEST";

int main(int /*argc*/, char** /*argv*/)
{
    Aws::SDKOptions options;
    Aws::InitAPI(options);

    Aws::String bucket = "your-bucket-name";

    // Set up S3 client
    ClientConfiguration config;
    config.region = "us-east-1";
    config.connectTimeoutMs = 3000;
    config.requestTimeoutMs = 60000;
    auto s3Client = Aws::MakeShared<S3Client>(ALLOCATION_TAG, config, false);

    auto sdk_client_executor = Aws::MakeShared<Aws::Utils::Threading::DefaultExecutor>(ALLOCATION_TAG);
    Aws::Transfer::TransferManagerConfiguration transferConfig(sdk_client_executor.get());
    transferConfig.s3Client = s3Client;
    transferConfig.maxParallelTransfers = 1;

    transferConfig.uploadProgressCallback =
        [](const Aws::Transfer::TransferManager*, const std::shared_ptr<const Aws::Transfer::TransferHandle>&transferHandle)
    { std::cout << "Upload Progress: " << transferHandle->GetBytesTransferred() << " of " << transferHandle->GetBytesTotalSize() << " bytes\n"; };

    static std::shared_ptr<Aws::Transfer::TransferManager> transferManager = Aws::Transfer::TransferManager::Create(transferConfig);

    Aws::String fileToUpload = "MyFile.data";
    std::shared_ptr<Aws::Transfer::TransferHandle> transferHandle = transferManager->UploadFile(fileToUpload.c_str(), bucket.c_str(), fileToUpload.c_str(),
        "multipart/form-data", Aws::Map<Aws::String, Aws::String>());

    size_t retries = 0;
    transferHandle->WaitUntilFinished();
    while (transferHandle->GetStatus() == Aws::Transfer::TransferStatus::FAILED && retries++ < 5)
    {
        transferManager->RetryUpload(fileToUpload.c_str(), transferHandle);
        transferHandle->WaitUntilFinished();
    }
    transferHandle->SetIsMultipart(true);

    Aws::Transfer::PartStateMap completedParts = transferHandle->GetCompletedParts();
    string eTagList;

    for (const auto &p : completedParts)
    {
        std::cout << "completedparts[" << p.first << "]" << p.second->GetETag() << '\n';
    }

    Aws::Transfer::TransferStatus status = transferHandle->GetStatus();
    std::string res("Result:");
    res.append(std::to_string((int)status));

    std::cout << res.c_str() << std::endl;

    Aws::ShutdownAPI(options);
    return 0;
}
```
The buffer size is 5 MB by default, and the size of the file I uploaded is 16.2 MB, the output is:
```
Upload Progress: 8192 of 17039360 bytes
Upload Progress: 16384 of 17039360 bytes
...
Upload Progress: 17039360 of 17039360 bytes
completedparts[1]"708103aa5ed3894e9d18ab47b66a0bbf"
completedparts[2]"cdc72f5f9d9501ec93d2c31630bdd0b3"
completedparts[3]"469983418f66e1ec1ffc48c7b57938d3"
completedparts[4]"b175a7ab0188dd525aee1bee90bce1ac"
Result:5
```
Seems like I have 4 `eTag`s as expected.

Could you share with us how you get the following information in your code?
> uploadId oXuuMmSD7a2_A0QXbVPNmHNbSwqFj.x07MR.2ACESembQqlKFY2AB1TLc9Uqk6vJhyysbtTg2grm0K4j7.ZKrAoeDWfEBjLUS3kN4EIV2LkpexuxJ_TlQIWDs_HnbxPufilename
aguad7_8666655

> {"etags":[{"etag":"d41d8cd98f00b204e9800998ecf8427e","pos":1}],
"uploadId":"oXuuMmSD7a2_A0QXbVPNmHNbSwqFj.x07MR.2ACESembQqlKFY2AB1TLc9Uqk6vJhyysbtTg2grm0K4j7.ZKrAoeDWfEBjLUS3kN4EIV2LkpexuxJ_TlQIWDs_HnbxPu"}

**Comment by adi619** [comment]
Hello,

here is the complete code that I'm trying to  implement.

#include "uploader.h"
#include "carserverrestapi.h"
#include <QApplication>

#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>
#include <aws/core/auth/AWSCredentialsProvider.h>
#include <aws/transfer/TransferManager.h>
#include <aws/transfer/TransferHandle.h>
#include <string>
#include <aws/core/utils/HashingUtils.h>
#include "uploader.h"
#include<aws/s3/model/ListMultipartUploadsRequest.h>
#include<aws/s3/model/ListMultipartUploadsResult.h>
#include <aws/s3/model/CompleteMultipartUploadRequest.h>
#include <aws/s3/model/CreateMultipartUploadRequest.h>
#include <aws/s3/model/MultipartUpload.h>

#include "uploader.h"
#include "ui_uploader.h"
#include <QFileDialog>



static const char* ALLOC_TAG = "main";
const std::string fileToUploadWithPath;
string filename = "aguad7_46865";


int main()
{




    string carId = "aguad7";

    string username = "admin";
    string password = "admin";
    const std::string fileToUpload = filename;
    std::string fileToUploadWithPath =
"/home/op/Logs/MultiContentTransferTestFile.dat";
    //std::string defaultPath = "/home/";

        CarServerRestApi* carRestApi = new CarServerRestApi(carId);

        // Login
        bool loggedIn = carRestApi->CarLogin(carId, username, password);

        if (loggedIn) {

            // Register Event
            CarServerRestApi::RegistrationInfo registrationInfo;
            registrationInfo.vinNumber = "VINNUMBER";
            registrationInfo.description = "DESCRIPTION";
            registrationInfo.driverName = "DRIVERNAME";
            registrationInfo.endDateTime = "2017-11-03T11:45:40.522Z";
            registrationInfo.eventTriggerLatitude = 111111;
            registrationInfo.eventTriggerLongitude = 222222;
            registrationInfo.eventTriggerTime = "2017-11-02T11:45:40.522Z";
            registrationInfo.checksum = "4711";
            registrationInfo.fileName = filename;
            registrationInfo.signalName = "SIGNALNAME";
            registrationInfo.startDateTime = "2017-11-01T11:45:40.522Z";
            registrationInfo.type = "TYPE";
            if (carRestApi->RegisterEvent(carId, registrationInfo)) {

                // Request upload...
                bool shouldSendFile = carRestApi->RequestFileUpload(carId,
filename);
                if (shouldSendFile) {
                    // Get upload info necessary for the actual file
upload...
                    // Can of course be returned from request above but for
the moment...
                    CarServerRestApi::UploadInfo uploadInfo =
carRestApi->GetUploadInfo(carId, filename);

                    //
                    // Do the upload...
                    //


                      Aws::SDKOptions options;
                       Aws::InitAPI(options);
                       Aws::Client::ClientConfiguration clientConfig;
                       clientConfig.scheme = Aws::Http::Scheme::HTTP;
                       clientConfig.region = Aws::Region::EU_WEST_1;
                       clientConfig.requestTimeoutMs = 3000000000;
                       clientConfig.connectTimeoutMs = 600000000;
                       Aws::Auth::AWSCredentials credentials;
                       Aws::String accessKey =uploadInfo.accessKey.c_str();
                       credentials.SetAWSAccessKeyId(accessKey);

 credentials.SetAWSSecretKey(uploadInfo.secretKey.c_str());

                        const std::string bucket =uploadInfo.bucket;

                       auto s3Client =
Aws::MakeShared<Aws::S3::S3Client>(ALLOC_TAG, clientConfig, false);
                       Aws::S3::Model::ListMultipartUploadsRequest
listMultipartUploadRequest;
                       listMultipartUploadRequest.SetBucket(bucket.c_str());
                       Aws::S3::Model::CreateMultipartUploadRequest
uploadmultipartrequest;
                       uploadmultipartrequest.SetBucket(bucket.c_str());
                       std::shared_ptr<Aws::Utils::Threading::Executor>
sdk_client_executor =
std::make_shared<Aws::Utils::Threading::DefaultExecutor>();

 //TransferManagerConfiguration(Aws::Utils::Threading::Executor* executor)
: s3Client(nullptr), transferExecutor(executor),
transferBufferMaxHeapSize(10 * MB5), bufferSize(MB5),
maxParallelTransfers(1)
                       Aws::Transfer::TransferManagerConfiguration
transferConfig(sdk_client_executor.get());
                       transferConfig.s3Client = s3Client;
                       transferConfig.maxParallelTransfers = 1;
                       transferConfig.bufferSize = Aws::Transfer::MB5 * 40;


                       transferConfig.uploadProgressCallback =
                                     [](const
Aws::Transfer::TransferManager*, const std::shared_ptr<const
Aws::Transfer::TransferHandle>&transferHandle)
                                     { std::cout << "Upload Progress: " <<
transferHandle->GetBytesTransferred() << " of " <<
transferHandle->GetBytesTotalSize() << " bytes\n";};




                       static
std::shared_ptr<Aws::Transfer::TransferManager> transferManager =
Aws::Transfer::TransferManager::Create(transferConfig);

                       std::shared_ptr<Aws::Transfer::TransferHandle>
transferHandle = transferManager->UploadFile(fileToUploadWithPath.c_str(),
bucket.c_str(), fileToUpload.c_str(),

                                       "multipart/form-data",
Aws::Map<Aws::String, Aws::String>());

                       size_t retries = 0;
                       transferHandle -> WaitUntilFinished ();
                       while (transferHandle->GetStatus() ==
Aws::Transfer::TransferStatus::FAILED && retries++ < 5)
                          {

transferManager->RetryUpload(fileToUploadWithPath.c_str(), transferHandle);
                              transferHandle->WaitUntilFinished();
                          }
                        transferHandle->SetIsMultipart(true);

                        //const Aws::Transfer::TransferHandle partId=
transferHandle->GetMultiPartId();
                        //const std::string id("partId:");
                      //  id.append(std::to_string((int)partId));
                       Aws::Transfer::PartStateMap completedParts  =
transferHandle->GetCompletedParts();
                       string eTagList;
                       carRestApi->StartEtagList(eTagList);
                       Aws::Map< int, Aws::Transfer::PartPointer
>::iterator it = completedParts.begin();

                       for(it =
completedParts.begin();it!=completedParts.end();it++){

                           std::cout << "completedparts[" << it->first <<
"]" << it->second->GetETag() << '\n';
                           carRestApi->AddEtagToList(eTagList, it->first,
it->second->GetETag().c_str());

                       }

//                             for(const auto &p : completedParts )
//                             {


//                                 std::cout << "completedparts[" <<
p.first << "]" << p.second->GetETag() << '\n';
//                                 carRestApi->AddEtagToList(eTagList,
p.first, p.second->GetETag().c_str());


//                             }
                         carRestApi->EndEtagList(eTagList);
                         std::cout << "\n" << eTagList << "\n";





                       Aws::Transfer::TransferStatus status =
transferHandle->GetStatus();
                       std::string res("Result:");
                       res.append(std::to_string((int)status));

                       std::cout << res.c_str() <<  std::endl;


                       Aws::ShutdownAPI(options);
                      // return 0;









                    bool ok = carRestApi->CompleteFileUpload(carId,
filename, eTagList);
                    if (!ok) {
                        cout <<  "\nCompleteFileUpload failed!\n";
                    }
                }
            }
            else {
                cout << "\nRegisterEvent failed!\n";
            }

            // Logout
            carRestApi->CarLogout(carId);
        }
        else {
            cout << "\nLogin failed!\n";
        }


}
