### ISSUE TITLE
Not uploading if the buffer size is less than file size

### ISSUE THREAD

**Issue by adi619** [aws/aws-sdk-cpp#722]
I'm trying to implement a multipartupload and upload fails if the buffer size is less than the file size. Does anyone have thoughts about it?

**Comment by wps132230** [comment]
Hi, are you using `TransferManager`? It so, it will handle this problem for you.

For more details, first, it will compare the file size with buffer size during uploading (in function `TransferManager::MultipartUploadSupported`):
https://github.com/aws/aws-sdk-cpp/blob/a8e2801c884f46234897097f471d40e4f2a39ae6/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp#L944

And then in `TransferManager::DoMultiPartUpload`, it will divide the file into several parts and do multipart upload.
https://github.com/aws/aws-sdk-cpp/blob/a8e2801c884f46234897097f471d40e4f2a39ae6/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp#L255

And is this issue related to https://github.com/aws/aws-sdk-cpp/issues/721?

**Comment by adi619** [comment]
All of a sudden this error started to appear.


/home/op/aws-sdk-cpp-master/aws-cpp-sdk-core/source/http/HttpClientFactory.cpp:172: std::shared_ptr<Aws::Http::HttpClient> Aws::Http::CreateHttpClient(const Aws::Client::ClientConfiguration&): Assertion `s_HttpClientFactory' failed.
Aborted
