### ISSUE TITLE
Set Content-Type of files in Transfer UploadDirectory

### ISSUE THREAD

**Issue by TyrasNistru** [aws/aws-sdk-cpp#726]
My question is really straightfoward: Is there a way to set the Content-Type of the files to be uploaded using `TransferManager::UploadDirectory`, or should I set it after each upload?

**Comment by JonathanHenson** [comment]
If you want to set them all to the same value, you can set the PutObject template on the configuration.

**Comment by TyrasNistru** [comment]
That's not the case, sadly. I usually have mixed content in the subfolders
