### ISSUE TITLE
I'm getting this error though I created a folder inside the sdk_build , can anyone help me?

### ISSUE THREAD

**Issue by prithvi672** [aws/aws-sdk-cpp#727]
osboxes@osboxes:~/sdk_build/my_example_project/my_project_build$ cd ~/sdk_build

osboxes@osboxes:~/sdk_build$ cmake -Daws-sdk-cpp_DIR=/path/to/sdk_build_dir ../my_example_project
CMake Error: The source directory "/home/osboxes/my_example_project" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by singku** [comment]
Your my_example_project directory is inside sdk_build directory.
Try `cmake -Daws-sdk-cpp_DIR=/path/to/sdk_build_dir ./my_example_project`
Or inside my_project_build directory, run your original command.
