### ISSUE TITLE
JSON arrays

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-sdk-cpp#728]
I see code like this repeated a hundred times all over the SDK...  (actually it is repeated 1,350 times)
Isn't there a better way to do this than copying the array every time?

    Array<JsonValue> edgesJsonList(m_edges.size());
    for(unsigned edgesIndex = 0; edgesIndex < edgesJsonList.GetLength(); ++edgesIndex)
    {
      edgesJsonList[edgesIndex].AsObject(m_edges[edgesIndex].Jsonize());
    }
    payload.WithArray("Edges", std::move(edgesJsonList));

In my case I am copying out of vectors and into fixed size arrays.

            Aws::Utils::Array<Aws::String> strArray(clip_items.size());

            for (unsigned i = 0; i < strArray.GetLength(); ++i) {
                strArray[i] = clip_items[i];
            }

            jsonPayload.WithArray("Items", strArray);

**Comment by marcomagdy** [comment]
>Isn't there a better way to do this than copying the array every time?

When you say copying the array, do you mean this line?
```cpp
payload.WithArray("Edges", std::move(edgesJsonList));
```

**Comment by jonsmirl** [comment]
The Json system could be expanded to support more types. For example a jsonPayload.WithStringVector("items", clip_items);
Then internally optimize the implementation of this to do as little copying as possible.

First step of optimizing would be to look at moving the 1,350 loops in front of the function call to inside the function call where you'd probably just end up with four or five new entry points.

You've already overloaded the standard types like Aws::String.  Maybe you could add a .jsonize() member to those objects and get them to serialize themselves? Getting the objects to serialize themselves should result in very small code.

This code:
    Array<JsonValue> edgesJsonList(m_edges.size());
    for(unsigned edgesIndex = 0; edgesIndex < edgesJsonList.GetLength(); ++edgesIndex)
    {
      edgesJsonList[edgesIndex].AsObject(m_edges[edgesIndex].Jsonize());
    }
    payload.WithArray("Edges", std::move(edgesJsonList));
could turn into this:
    m_edges.jsonize(payload);

The existing implementation does work, it is just generating a lot of code and adding to bloat.

**Comment by jonsmirl** [comment]
Consider taking this a lot further. Currently the SDK is generated C++ code from JSON function descriptions.  C++ has an excellent generation system via templates. I believe it is possible to make 90% of this SDK disappear by implementing a generic RPC scheme and then using C++ templates (generated from the JSON descriptions) to ensure type safety when when calling the generic RPC scheme. You can probably even achieve syntax compatibility by generating macros that match the existing API which then expand into template expressions. 

The basic observation is that if you can write a generator program to make this code it is very likely that the C++ macro/templating system can do the same thing without constructing all of these underlying classes. Maybe something to look at for V2 of the SDK?

The AWS lambda function deployment size limit is 50MB. Granted you can access the SDK without bundling it into your function, but imagine if you had to waste 30-40MB just to bring along the SDK. I suspect that in a more optimal configuration the entire SDK can be done in 2-3MB.

**Comment by marcomagdy** [comment]
Thanks for the suggestion, and although your suggestion could work in theory, the reality is code-generation in the SDK is quite complex. The code generator currently requires, for example, reading input from a file, handling special cases of some services, etc. We often have to debug it actually.
It makes me twitch when I think about dealing with all that stuff in C macros and C++ templates.

**Comment by jonsmirl** [comment]
You could leave the code generator as is, and have it produce template files and macros instead.

**Comment by marcomagdy** [comment]
We'll consider different options to reduce the binary size in V2. I'll have this added to the roadmap.
