### ISSUE TITLE
SIGSEGV when metadata tag value is empty string

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#731]
AWS SDK crashes (vector out-of-bound access) if I try to execute PutObjectRequest that has metadata tag value == empty string (or consists of only spaces); see PutObjectRequest::SetMetadata(). Both Linux and Windows, v1.1.50

**Comment by marcomagdy** [comment]
ugh, that's silly. Will get it fixed. Thank you.

**Comment by crusader-mike** [comment]
Which SDK version was it fixed in?

**Comment by marcomagdy** [comment]
v1.3.5
when we reference the issue# in our private GitHub repo in the commit message and push it, GitHub closes the issue automatically.

**Comment by crusader-mike** [comment]
Thanks!
