### ISSUE TITLE
GetObject segfault

### ISSUE THREAD

**Issue by jmsundar** [aws/aws-sdk-cpp#739]
Running SDK v1.3.1 on Ubuntu 14.04 compiled with gcc 4.9.4. 
`cmake -DBUILD_ONLY="s3" -DCMAKE_CXX_COMPILER="g++-4.9" ..`

When trying to GetObject on a large item, the SDK segfaults upon running out of memory, because it's trying to write the entire object into the curl response buffer.

Is there some way to use GetObjectRequest similar to the MultipartUpload API, to split the object into smaller pieces?

**Comment by crusader-mike** [comment]
You can substitute iostream GetObjectRequest uses and redirect incoming data elsewhere, by default it accumulates in memory and related call doesn't return until entire object is downloaded.

**Comment by jmsundar** [comment]
I see GetObjectRequest gets an iostream from a factory, set using `SetResponseStreamFactory`. I'm assuming I'm supposed to pass it a lambda, but I can't tell from the code what form the lambda is supposed to take, and I'm not familiar with C++, so I'm not sure how to make my own ResponseStreamFactory. Any help would be appreciated.

**Comment by jmsundar** [comment]
@crusader-mike This is my test program, downloading a 4 gb file to a machine with 1gb of ram. Using the get_object.cpp example program causes a segfault when the CurlHttpClient runs out of memory for the response.
```
int main(int argc, char** argv)
{
    using namespace Aws;
    using namespace std;
    int retval = 0;
    SDKOptions options;
    options.loggingOptions.logLevel = Utils::Logging::LogLevel::Trace;
    InitAPI(options);
    {
        String bucket("testbig"), key("fg-02.bin");

        auto s3_client = MakeShared<S3::S3Client>("Large Object Download");
        auto creationFunction = []()
        {
            return Aws::New< Aws::FStream >( "DownloadTag", "MyFile.txt",
                std::fstream::out|std::fstream::binary );
        };
        S3::Model::GetObjectRequest object_request;

        object_request.WithBucket(bucket).WithKey(key);
        object_request.SetResponseStreamFactory(creationFunction);
        auto get_object_outcome = s3_client->GetObject(object_request);

        if (get_object_outcome.IsSuccess())
        {
            OFStream local_file;
            local_file.open(key.c_str(), ios::out | ios::binary);
            local_file << get_object_outcome.GetResult().GetBody().rdbuf();
            cout << "Done!" << endl;
        }
        else
        {
            cout << "GetObject error: " <<
                get_object_outcome.GetError().GetExceptionName() << " " <<
                get_object_outcome.GetError().GetMessage() << std::endl;
            retval = -1;
        }
    }
    ShutdownAPI(options);
    return retval;
}

```

**Comment by crusader-mike** [comment]
Check #715 

`local_file << get_object_outcome.GetResult().GetBody().rdbuf();`

Why? You've already saved data to a file

**Comment by jmsundar** [comment]
Thank you, that explains it.
