### ISSUE TITLE
AWS-SDK-CPP support for Solaris x86/SPARC

### ISSUE THREAD

**Issue by khalfella** [aws/aws-sdk-cpp#743]
Do you support Solaris x86 and Solaris SPARC?
In case of the answer is no, has it been tested? Is there known issues?

**Comment by marcomagdy** [comment]
We do not support Solaris because we don't have a test environment setup for it. That being said, all of the SDK code uses standard C++11. So, if you have a C++11 standard-conforming compiler, theoretically you should have no problems building from source.

**Comment by khalfella** [comment]
Thanks, I might have access to Solaris environment in the near future. I will see if I can test the SDK there and report back.

**Comment by spanikul** [comment]
@khalfella - were you able to build on Solaris?  If yes what architecture and C++ compiler did you use?  SPARC and Oracle Solaris Studio are the ones I'm interested in.  - tia

**Comment by khalfella** [comment]
Sorry for the late update. I ended up following another approach.

**Comment by justinpa-asg** [comment]
justin.palmer@asg.com is no longer a valid e-mail address.  Please contact Tim Wake at tim.wake@asg.com with any questions, comments, or concerns.

Diese justin.palmer@asg.com ist keine gultige Email-Adresse mehr. Bitte setzen Sie sich mit Tim Wake an folgende Email-Adresse tim.wake@asg.com in Verbindung, falls Sie etwaige Fragen, Kommentare oder Bedenken diesbezuglich haben.

Cette justin.palmer@asg.com n'est plus une adresse de courriel valable. Veuillez contacter Tim Wake a l'adresse de courriel suivante tim.wake@asg.com si vous avez des questions, des commentaires ou des preoccupations quelconques.

From: bounces+848413-88bd-justin.palmer=asg.com@sgmail.github.com
Sent: Wednesday, April 22 2020 1:43 AM
To: aws-sdk-cpp@noreply.github.com
CC: subscribed@noreply.github.com
Subject: [BULK] Re: [aws/aws-sdk-cpp] AWS-SDK-CPP support for Solaris x86/SPARC (#743)


Sorry for the late update. I ended up following another approach.

**Comment by justinpa-asg** [comment]
justin.palmer@asg.com is no longer a valid e-mail address.  Please contact Tim Wake at tim.wake@asg.com with any questions, comments, or concerns.

Diese justin.palmer@asg.com ist keine gultige Email-Adresse mehr. Bitte setzen Sie sich mit Tim Wake an folgende Email-Adresse tim.wake@asg.com in Verbindung, falls Sie etwaige Fragen, Kommentare oder Bedenken diesbezuglich haben.

Cette justin.palmer@asg.com n'est plus une adresse de courriel valable. Veuillez contacter Tim Wake a l'adresse de courriel suivante tim.wake@asg.com si vous avez des questions, des commentaires ou des preoccupations quelconques.

From: noreply@github.com
Sent: Wednesday, April 22 2020 1:49 AM
To: aws-sdk-cpp@noreply.github.com
CC: justin.palmer@asg.com, comment@noreply.github.com
Subject: Re: [aws/aws-sdk-cpp] AWS-SDK-CPP support for Solaris x86/SPARC (#743)


Closed #743<http://TOC.ASG.COM:8080/?dmVyPTEuMDAxJiYzZWQ4OTRmOWZlZDc5NDkyNT01RTlGQTJDNF8yOTYyNV80NDcwXzEmJjc2ZTdhY2Y1MWE1YTFiYj0xMjMyJiZ1cmw9aHR0cHMlM0ElMkYlMkZnaXRodWIlMkVjb20lMkZhd3MlMkZhd3Mtc2RrLWNwcCUyRmlzc3VlcyUyRjc0Mw==>.
