### ISSUE TITLE
Building for Android

### ISSUE THREAD

**Issue by mingno** [aws/aws-sdk-cpp#744]
Build Environment :
Windows10 x64 / Git for windows (latest) / Tortoise Git (latest) 
Cmake 3.10.0 x64 (latest) / Python 3.6.3 x86 (latest) / Android NDK R12b

First, I fixed the TypeError
1. Open C:\NVPACK\android-ndk-r12b\build\tools\make_standalone_toolchain.py
2. (line 529) Change       **elif args.verbose >= 2:** to **else:** 

VS2015 Developer Command Prompt
cd C:\Users\mingn\Desktop
mkdir out
cd out
cmake C:\Users\mingn\Downloads\aws-sdk-cpp-master\aws-sdk-cpp-master -G "NMake Makefiles" -DTARGET_ARCH=ANDROID -DNDK_DIR="C:\NVPACK\android-ndk-r12b"

Here is the Log
[Log.txt](https://github.com/aws/aws-sdk-cpp/files/1518676/Log.txt)

**Finally, I got a Makefile in the out folder but now what can i do with this?**

I tryed to "Make" with Cygwin, but there is an error like this
Makefile:35: *** missing separator. stop.

Here is the Makefile
[Makefile.txt](https://github.com/aws/aws-sdk-cpp/files/1518724/Makefile.txt)
(remove the file name extension ".txt" . I added it for uploading.)

**Comment by bretambrose** [comment]
Those instructions are Visual Studio oriented.  Assuming you have it installed, you should be able to run nmake on the result, but you'll need to do it from a Visual Studio Dev Tools command prompt.

**Comment by mingno** [comment]
Yes, I did...

**Comment by bretambrose** [comment]
What were the results?

**Comment by mingno** [comment]
That's what the above is

**Comment by bretambrose** [comment]
The above says "Make on Cygwin", which is not the same as "nmake in a Visual Studio Dev Tools command prompt"

**Comment by mingno** [comment]
Wow... I'm doing it :)

**Comment by mingno** [comment]
Thank you, I'm done.
"external" folder has created in "out" folder,
and "libaws-cpp-sdk-~~.so" files have created in each "aws-cpp-sdk-~~) folders.
Does the build process end with this? What is the next?
It mixed with other premade files like ~.cmake so Should I separate it? and How can I?

I want to make a plugin for UnrealEngine like this https://github.com/YetiTech-Studios/UE4GameLiftClientSDK (Because this plugin is for Windows, I'd like to make it for Android).

**Comment by bretambrose** [comment]
From the build directory, try:

cmake -DCMAKE_INSTALL_CONFIG_NAME=Debug -DCMAKE_INSTALL_PREFIX="<path to install sdk to>" -P cmake_install.cmake  <path to source>

This will give you a standard layout with <include>, <bin>, <lib> directories containing appropriate files for all the SDKs that you built.  How you use or consume them is up to you.

**Comment by mingno** [comment]
I'm doing it :) Thank you so much
