### ISSUE TITLE
AWS Streamer - Stream Response: Failed to parse error payload - RespCode:403

### ISSUE THREAD

**Issue by gv1dev** [aws/aws-sdk-cpp#746]
My system:
Windows 10 Pro 64-bit (Version: 10.0.15063 build 15063)

Building environment:
MS Visual Studio Community 2015 (Version 14.0.25431.01 Update 3)

Libraries:
AWSSDKCPP-Core v1.2.22
AWSSDKCPP-Core.redist v1.2.22
AWSSDKCPP-Kinesis v1.2.20131202.22
AWSSDKCPP-Kinesis.redist v1.2.20131202.2

Poco 1.7.8
Boost 1.63
Avro 1.8.1

I have a problem with the response that i receive from the Amazon kinesis Streamer.
When a proxy is used theresponse is unsuccesfull with:

     m_errorType=UNKNOWN (100) 
     m_exceptionName=""
     m_message="Failed to parse error payload" 
     m_responseCode = FORBIDDEN(403)

If I send the request through my a network not using a proxy it works as it should and the response is succesful.....

I send a stream request towards Amazon kinesis streamer: 

      KinesisClient awsclient = InitAwsClient(requestProxy, sessionToken);
      //set request to Amazon Kinesis streamer
      auto request = new Aws::Kinesis::Model::PutRecordRequest();

      //set to the corresponding streamer
      string streamer = *it;
      request->SetStreamName(streamer.c_str());

      Aws::Utils::Array<unsigned char> arr(buffer.data(), buffer.size());
      request->SetData(arr);
      //set partition key the device id
      request->SetPartitionKey(device_id.c_str());

      auto response = awsclient.PutRecord(*request);
	if (response.IsSuccess())
        ....

Any help is highly welcomed!

**Comment by singku** [comment]
How did you set up the proxy in your client configuration?

**Comment by gv1dev** [comment]
Here is the code that creates the client:

      KinesisClient myReporter::InitAwsClient(const bool requestProxy, const string& sessionToken){
       ...
       	Aws::Client::ClientConfiguration conf;
	if (requestProxy) {
		//in case proxy settings are needed
		conf.proxyHost = _myAccountSession->GetProxy().c_str(); //use c_str for Linux compatibility
		conf.proxyPort = _myAccountSession->GetPort();
	 }
        .....

The declaration:
        unique_ptr<myAccountSessionRequest> _myAccountSession;

Here is the constructor of _myAccountSession:

       		myAccountSessionRequest(	const string& uid, const string& password, 
						const string& proxy, const int port) :
						_proxy(proxy), _port(port);

**Comment by gv1dev** [comment]
Finally the issue was on the local proxy. Access to kinessi stream e.g kinesis.us-east-1.amazonaws.com
was forbidden.
Allowing the access towards the adress it worked.
