### ISSUE TITLE
CopyObject Error:  A header you provided implies functionality that is not implemented

### ISSUE THREAD

**Issue by adityatelidevara** [aws/aws-sdk-cpp#747]
### Can you provide a TRACE level log? (sanitize any sensitive information)

when I invoke CopyObject api on s3 client, I get the following error:
"A header you provided implies functionality that is not implemented"
I'm creating a copy request object, setting the bucket, key and copy source.
When I don't set the copy source, I'm not getting that error. It is just creating an empty file with the bucket and key provided.
I thing copy source is setting 'x-amz-copy-source' header.

**Comment by singku** [comment]
How did you specify CopySource? Note, CopySource is a required field and must be url encoded.

**Comment by adityatelidevara** [comment]
Aws::S3::Model::CopyObjectRequest copyRequest;
copyRequest.WithBucket("s3test").WithKey("newname");
copyRequest.SetCopySource("/s3test/oldname");
auto outcome = s3Client.CopyObject(copyRequest);

Tried s3Client.CopyObject(Aws::Util::s::StringUtils::URLEncode("/s3test/oldname"));
but that did not work either.

outcome.GetError()GetExceptionName()    "NotImplemented"
outcome.GetError().GetMessage()           "Unable to parse ExceptionName: NotImplemented Message: A header you provided implies functionality that is not implemented."
outcome.GetError().GetErrorType()      UNKNOWN

**Comment by singku** [comment]
What about "s3test/oldname"?

**Comment by adityatelidevara** [comment]
Nope. Same error. Doesn't matter what source file name I provide.

**Comment by singku** [comment]
Here is my test code:
```
S3Client client;
CopyObjectRequest req;
req.SetBucket(BUCKET);
req.SetKey(NEW_KEY);
req.SetCopySource(Aws::Utils::StringUtils::URLEncode((BUCKET + "/" + KEY).c_str()));
auto outcome = s3Client.CopyObject(req);
```
And it works.

**Comment by adityatelidevara** [comment]
Thanks. That made me realize that it could be a problem with my local service which supports s3 interface.
