### ISSUE TITLE
PutObject adding unwanted cache-control header

### ISSUE THREAD

**Issue by mramato** [aws/aws-sdk-cpp#752]
I'm having an issue where the below `PutObjectRequest` is causing `cache-control: no-cache` to be set on the bucket after uploading.  I'm not sure this is a bug in aws-sdk-cpp (debugging indicates the header definitely isn't present in the request object), but this only happens when using aws-sdk-cpp, it doesn't happen when uploading through the aws s3 cli or browser console app.  So perhaps there's some interaction with S3 I'm missing?

```c++
Aws::S3::Model::PutObjectRequest object_request;
object_request.SetBucket(bucketName);
object_request.SetKey(keyName);
object_request.SetBody(stream);
object_request.SetContentType(mimeType.value);
object_request.SetContentLength(lengthTile);

if (compressed)
{
    object_request.SetContentEncoding("gzip");
}

// Perform a blocking put to S3
auto put_object_outcome = s3Client->PutObject(object_request);
```

### What platform/OS are you using?
Windows 10

### What compiler are you using? what version?
Visual Studio 2015

### What's your CMake arguments?
```cmake
set(BUILD_ONLY s3 CACHE STRING "")
set(ENABLE_TESTING OFF CACHE BOOL "")
```
### Can you provide a TRACE level log? (sanitize any sensitive information)
[aws_sdk_2017-12-08-10.log](https://github.com/aws/aws-sdk-cpp/files/1543042/aws_sdk_2017-12-08-10.log)

**Comment by tfili** [comment]
This appears to be caused by specifying `WINHTTP_FLAG_REFRESH` in `WinHttpSyncHttpClient::OpenRequest` in the file `aws-cpp-sdk-core\source\http\windows\WinHttpSyncHttpClient.cpp`.

There doesn't appear to be a way to change it without modifying the library.

**Comment by mramato** [comment]
I can confirm @tfili's findings.  This issue does not happen on linux.

**Comment by JonathanHenson** [comment]
Unfortunately turning that “feature” off on both winhttp and ixmlhttprequest2 causes all GET requests to fail (since it all gets cached otherwise). Let’s come up with a temporary workaround, and eventually we’ll have a better http story.
