### ISSUE TITLE
Undefined reference to SIGPIPE when curl enabled on windows.

### ISSUE THREAD

**Issue by dburken** [aws/aws-sdk-cpp#753]
### What platform/OS are you using?
Windows 10

### What compiler are you using? what version?
VS Pro 2015 
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x64

### What's your CMake arguments?
cmake -G "Ninja" ^
-DBUILD_ONLY="core;s3" ^
-DCMAKE_BUILD_TYPE=Release ^
-DCMAKE_INCLUDE_PATH=D:/drb/vs14_x64/deps/include ^
-DCMAKE_INSTALL_PREFIX=D:/drb/vs14_x64/deps ^
-DCMAKE_LIBRARY_PATH=D:/drb/vs14_x64/deps/lib ^
-DENABLE_OPENSSL_ENCRYPTION=ON ^
-DFORCE_CURL=ON ^
D:/drb/vs14_x64/aws/aws-sdk-cpp-1.3.19

### Can you provide a TRACE level log? (sanitize any sensitive information)
Compiler error in file:

Trying to use curl on windows.  
File:  aws-sdk-cpp-1.3.19/aws-cpp-sdk-core/source/http/HttpClientFactory.cpp this code references undefined SIGPIPE (linux signal)

#if ENABLE_CURL_CLIENT
        static void LogAndSwallowHandler(int signal)
        {
            switch(signal)
            {
                case SIGPIPE:
                    AWS_LOGSTREAM_ERROR(HTTP_CLIENT_FACTORY_ALLOCATION_TAG, "Received a SIGPIPE error");
                    break;
                default:
                    AWS_LOGSTREAM_ERROR(HTTP_CLIENT_FACTORY_ALLOCATION_TAG, "Unhandled system SIGNAL error"  << signal);
            }
        }
#endif

Also:

SignalHandlerTest.cpp needs to be fixed...

**Comment by singku** [comment]
So... you were using Ninja to generate VS build artifact and using CURL on windows.?

**Comment by dburken** [comment]
Yes, Ninja is just the build system. Will get the same results with nmake. We'd like to experiment using curl instead of win inet under the hood.  I did hack the code and got everything to compile but code crashed. I did not have time to dig into where it crashed.  If I compile the aws sdk without curl everything works. I was wondering if anyone has had success with aws+curl on windows?

**Comment by Bu11etmagnet** [comment]
"Undefined reference" is a linker error and is misleading. What you have is an undefined symbol.

**Comment by dburken** [comment]
SIGPIPE is not defined on windows. It's a linux signal. On my system it's defined in:
/usr/include/asm/signal.h (Fedora 27).

Code in:
aws/latest/aws-cpp-sdk-core/source/http/HttpClientFactory.cpp
Line: 55 if referencing SIGPIPE here:
#if ENABLE_CURL_CLIENT
        static void LogAndSwallowHandler(int signal)
        {
            switch(signal)
            {
                case SIGPIPE:
                    AWS_LOGSTREAM_ERROR(HTTP_CLIENT_FACTORY_ALLOCATION_TAG, "Received a SIGPIPE error");
                    break;
                default:
                    AWS_LOGSTREAM_ERROR(HTTP_CLIENT_FACTORY_ALLOCATION_TAG, "Unhandled system SIGNAL error"  << signal);
            }
        }
#endif

Thanks...

**Comment by dburken** [comment]
Build error:
[166/373] Building CXX object aws-cpp-sdk-core\CMakeFiles\aws-cpp-sdk-core.dir\source\http\HttpClientFactory.cpp.obj
FAILED: aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/http/HttpClientFactory.cpp.obj
C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe  /nologo /TP -DAWS_CORE_EXPORTS=1 -DENABLE_BCRYPT_ENCRYPTION -DENABLE_CURL_CLIENT -DPLATFORM_WINDOWS -DUSE_IMPORT_EXPORT=1 -DUSE_WINDOWS_DLL_SEMANTICS -Daws_cpp_sdk_core_EXPORTS -ID:\drb\vs14_x64\deps\include -ID:\drb\vs14_x64\aws\aws-sdk-cpp-1.3.19\aws-cpp-sdk-core\include\aws\core\platform\refs -ID:\drb\vs14_x64\aws\aws-sdk-cpp-1.3.19\aws-cpp-sdk-core\include /DWIN32 /D_WINDOWS /W4 /GR /EHsc /MP /bigobj /WX /MD /O2 /Ob2 /DNDEBUG /Zi /showIncludes /Foaws-cpp-sdk-core\CMakeFiles\aws-cpp-sdk-core.dir\source\http\HttpClientFactory.cpp.obj /Fdaws-cpp-sdk-core\CMakeFiles\aws-cpp-sdk-core.dir\ /FS -c D:\drb\vs14_x64\aws\aws-sdk-cpp-1.3.19\aws-cpp-sdk-core\source\http\HttpClientFactory.cpp
D:\drb\vs14_x64\aws\aws-sdk-cpp-1.3.19\aws-cpp-sdk-core\source\http\HttpClientFactory.cpp(64): error C2065: 'SIGPIPE': undeclared identifier
D:\drb\vs14_x64\aws\aws-sdk-cpp-1.3.19\aws-cpp-sdk-core\source\http\HttpClientFactory.cpp(64): error C2131: expression did not evaluate to a constant
D:\drb\vs14_x64\aws\aws-sdk-cpp-1.3.19\aws-cpp-sdk-core\source\http\HttpClientFactory.cpp(64): note: failure was caused by non-constant arguments or reference to a non-constant symbol
D:\drb\vs14_x64\aws\aws-sdk-cpp-1.3.19\aws-cpp-sdk-core\source\http\HttpClientFactory.cpp(64): note: see usage of 'SIGPIPE'
D:\drb\vs14_x64\aws\aws-sdk-cpp-1.3.19\aws-cpp-sdk-core\source\http\HttpClientFactory.cpp(64): error C2051: case expression not constant
D:\drb\vs14_x64\aws\aws-sdk-cpp-1.3.19\aws-cpp-sdk-core\source\http\HttpClientFactory.cpp(71): warning C4065: switch statement contains 'default' but no 'case' labels
D:\drb\vs14_x64\aws\aws-sdk-cpp-1.3.19\aws-cpp-sdk-core\source\http\HttpClientFactory.cpp(129): error C2065: 'SIGPIPE': undeclared identifier

**Comment by singku** [comment]
Fixed at https://github.com/aws/aws-sdk-cpp/commit/1e5c0604259e3f08d3387747fbb677ee369b5b3b
