### ISSUE TITLE
ListObjectsV2Request timeout on Linux

### ISSUE THREAD

**Issue by jmsundar** [aws/aws-sdk-cpp#754]
Using SDK v1.3.1 on Ubuntu 14.04 with curl version 7.57.0, compiled with gcc 4.9.4 with default cmake options.

We are unable to list objects from an s3 bucket. The code is below and TRACE level log is here: 
[aws_sdk_2017-12-11-13.log](https://github.com/aws/aws-sdk-cpp/files/1546961/aws_sdk_2017-12-11-13.log)
The same code works perfectly on macOS 10.13, compiled with Apple LLVM version 9.0.0 (clang-900.0.39.2). 
```
Vector<S3::Model::Object> S3Manager::list_objects()
{
    std::cout << "Objects in S3 bucket: " << m_bucket << std::endl;
    S3::Model::ListObjectsV2Request objects_request;
    objects_request.WithBucket(m_bucket);

    auto list_objects_outcome = s3_client->ListObjectsV2(objects_request);

    if (list_objects_outcome.IsSuccess())
    {
        return list_objects_outcome.GetResult().GetContents();
    }
    else
    {
        ios_log(ERROR, "listObjects error: %s %s\n", list_objects_outcome.GetError().GetExceptionName().c_str(), list_objects_outcome.GetError().GetMessage().c_str());
        return Vector<S3::Model::Object>();
    }
}
```

**Comment by jmsundar** [comment]
This function was originally called from the `_init` function of a shared library. On Linux, moving the function call out of `_init` was successful. Does anyone know why this might be?

**Comment by newpoo** [comment]
Did you use rate limiter to hit the above issue?

I hit a similar issue which is described in https://github.com/aws/aws-sdk-cpp/issues/806

**Comment by jmsundar** [comment]
Nah, our issue was entirely related to dns not working in `_init` for our library. Rate limiter was not set.
