### ISSUE TITLE
Amazon CognitoAuthentication Extension Library for c++

### ISSUE THREAD

**Issue by manishpin** [aws/aws-sdk-cpp#760]
Hi,

I am writing a c++ client app, where a user will sign-up/in/out using the app, I have the sign-up working using `Aws::CognitoIdentityProvider::CognitoIdentityProviderClient`. The problem I am now having is authenticating the username/password and then getting credentials to use other aws services, in particular S3. 

I have posted what I have tried so far using CognitoCachingAuthenticatedCredentialsProvider on Stackoverflow:

https://stackoverflow.com/questions/47796077/authenticate-a-user-using-cognito-aws-sdk-cpp

I am not sure where this is going wrong, or what I have missed. I've been stuck on this a few days now, and have been researching everywhere to no avail. 

Looking around the web, the CognitoAuthentication Extension Library for .NET looks to do exactly what I need, but does not seem to be only available for c++. 

http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/cognito-authentication-extension.html

In particular the "Use AWS Resources after Authentication" section is exactly what I need. 
 
Are there equivalent calls for the aws-sdk-cpp? Or plans to bring this functionality into this sdk? Or perhaps a dev preview available? 

Many thanks, 

Manish

**Comment by singku** [comment]
I believe what you want is actually identity-management
See: https://github.com/aws/aws-sdk-cpp/tree/master/aws-cpp-sdk-identity-management

**Comment by JonathanHenson** [comment]
Have you looked at the identity-management package?

**Comment by manishpin** [comment]
@singku @JonathanHenson  I have looked at the identity-management and mocked up some code, which I posted on Stackoverflow (link above). I have misunderstood something along the way I think, and couldn't figure out where to provide username/password in the flow using the CognitoCachingAuthenticatedCredentialsProvider, CustomPersistentCognitoIdentityProvider and CognitoIdentityClient classes. I tried to follow the examples from the .net sdk, but could not find the matching function calls.

**Comment by manishpin** [comment]
@singku @JonathanHenson . I have now resolved my issues.  I was confusing Cognito federated identities and Cognito Identity provider. I have now implemented SRP using OpenSSL, and the Cognito Identiy Provider now works well, and I can exchange tokens with CognitoIdenty to get AWS Credentials. I have not yet tried the identity-management-package, that will be the next task.

For anyone who comes across this in the future, this [blog post](http://blog.mmlac.com/aws-cognito-srp-login-c-sharp-dot-net/) helped immensely in making sure the implementation was correct.

**Comment by JonathanHenson** [comment]
Can you send us a pr for your srp work?

**Comment by manishpin** [comment]
I'm planning to tidy it up a little bit and add in a few checks. I'll put it up on gist and link it here

**Comment by sirius** [comment]
Hey, @manishpin ! I've just started writing some SRP authentication with OpenSSL code, but your code would help me a lot and save me much needed time. 

Would you mind posting the code as is?

If you publish using e.g. Apache License 2.0 the open source community would probably contribute with improvements, and maybe the code can be either an unofficial extension or included in the upstream sdk?

**Comment by manishpin** [comment]
Hi @sirius, sorry for the delay in posting this code. I got pulled into another project and haven't had a chance to return to this work yet. It's more or less already in a state where I could post it, so hopefully next week i'll throw it up on gist. 

I'll release it under Apache 2.0 and happy to take any comments once up.

**Comment by manishpin** [comment]
@sirius , @JonathanHenson , apologies for the delay. I have uploaded my SRP code to gist:

https://gist.github.com/manishpin/f7d8e9af84068bd9b0220bb2c7d14a4d

Closing this issue.

**Comment by nxrighthere** [comment]
We faced the same problem recently. Is there any official support of SRP in C++ SDK or any secure alternative for it, where we can obtain AWS credentials using username/password?
