### ISSUE TITLE
My IAM user does not work with cpp sdk

### ISSUE THREAD

**Issue by MrAta** [aws/aws-sdk-cpp#761]
So I'm using cpp SDK on Mac OS high serria, I just moved from python boto3 to cpp SDK, the problem is that my IAM user works fine with boto3 but while I'm using it with cpp SDK it does not work!
For example, I'm trying to run [describe instances example](https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/cpp/example_code/ec2/describe_instances.cpp), the output is as below:
`Name                                            ID                  Ami            Type           State          Monitoring `
And as you can see, it does not print my instances, while I have some running instances which my IAM user has all accesses to them as it works with python boto3. I have no idea where is the source problem. I appreciate any advice.

**Comment by wps132230** [comment]
Hi, are you using IAM on your local machine or on EC2 instance?
If you are using it on your local machine, how did you provide the credentials of your IAM users? By environment variables, or file based in `~/.aws/credentials` or hard code?

**Comment by MrAta** [comment]
Hey, Yes I'm using IAM on my local machine and I have my credentials both in `~/.aws.credntials` and `exported` using `export` command. And they are fine as I said my IAM is working fine with boto3.

**Comment by wps132230** [comment]
Your output is `Name ID Ami Type State Monitoring`, which means at least the first request `DescribeInstancesRequest` was successful. If cpp sdk could not find credentials, the output will be something like :
`Failed to describe ec2 instances:Unable to parse ExceptionName: MissingParameter Message: The request must contain the parameter AWSAccessKeyId`

Could you turn on Trace level log by adding `options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;` when initializing sdk and check if you can find your credentials in your log file `aws_sdk_yyyy-yy-dd-hh.log` by searching "Credential=" and double check if that's the correct one? And did you provide a correct region?

**Comment by MrAta** [comment]
Yes, I can see my access key ID in the log:
`... HMAC-SHA256 Credential={MY_ACCESS_KEY_ID}/20171220/us-east-1/ec2/aws4_request, ... Request Successfully signed
`

**Comment by marcomagdy** [comment]
Make sure you’re hitting the right region

**Comment by MrAta** [comment]
Yes! I think you are right. In my log file I see lines like this:
`Making request to https://ec2.us-east-1.amazonaws.com/`
While my instances are in `us-east-2` region. Also, the content of my `~/.aws/config` is:
`[default] `
`region = us-east-2`
Seems the code does not read the config! How can I set the region in the Code?

**Comment by wps132230** [comment]
You can do that by:
```c++
Aws::Client::ClientConfiguration clientConfiguration;
clientConfiguration.region = "us-east-2";
Aws::EC2::EC2Client ec2(clientConfiguration);
```
And don't forget `#include <aws/core/client/ClientConfiguration.h>`

**Comment by MrAta** [comment]
Great! Now the code works fine. I'm still wondering why it does not read the config file.
Thank you anyway.

**Comment by singku** [comment]
Region is read into ProfileConfigLoader, but currently doesn't override region of ClientConfiguration. That's why it doesn't take into effect. This is a bug we should fix.
