### ISSUE TITLE
Install doesn't install NetworkConnection or other web libraries under network directory

### ISSUE THREAD

**Issue by accesio** [aws/aws-sdk-cpp#762]
### What platform/OS are you using?
Linux , Ubuntu 16.04
### What compiler are you using? what version?
g++ 5.4.1
### What's your CMake arguments?
cmake     -DCMAKE_BUILD_TYPE=Release   -DENABLE_TESTING=OFF   -Wno-dev   ..

### Can you provide a TRACE level log? (sanitize any sensitive information)

The issue is that make install with cmake, doesn't include the network  directory, hence your samples aren't buildable outside of the original cmake directory structure.

**Comment by wps132230** [comment]
Hi, what do you mean by "NetworkConnection", "web libraries" and "network directory"?
We are using `libcurl` for linux for example, that means you need to install it separately from cpp sdk.

**Comment by accesio** [comment]
Sorry about the lack of clarity.

What I meant was that after make install, the files OpenSSLConnection.{cpp,hpp} and ConfigCommon.{hpp,cpp} never made it into the AWS library.

The config one isn't a big deal, but so many of your samples rely on the functionality in the OpenSSLConnection files that it kind of requires a lot more work to build the aws-iot library and then the user has to compile in these files as well.

**Comment by singku** [comment]
Are you posting this issue in the wrong repo?
What I found out is that OpenSSLConnection.cpp and ConfigCommon.cpp belong to this repo: https://github.com/aws/aws-iot-device-sdk-cpp/

**Comment by accesio** [comment]
You are correct, pardon my gaffe
