### ISSUE TITLE
Create Auto Scaling Target

### ISSUE THREAD

**Issue by pcaswell** [aws/aws-sdk-cpp#764]
What platform/OS are you using?
Window 7 Professional 64bit

What compiler are you using? what version?
Visual Studio 2017

What's your CMake arguments?
cmake ../aws-sdk-cpp-1.2.20 -G "Visual Studio 15 2017 Win64" -DSIMPLE_INSTALL=OFF 
-DCMAKE_INSTALL_PREFIX="../MyLibs/aws-sdk-cpp-1.2.20"

Can you provide a TRACE level log? (sanitize any sensitive information)
NA

Hello all,
I need to enable auto scaling for my DynamoDB table but I can't see how to achieve this through the C++ SDK.  I have successfully created the table and am comfortable creating IAM roles programatically but I'm stuck with autoscaling.

I can see how to do it with the AWS CLI as that's described in STEP 3 here:
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/AutoScaling.CLI.html#AutoScaling.CLI.CreateServiceRole

How do I achieve the same with the C++ SDK?
Thanks.

**Comment by wps132230** [comment]
You need to create an `ApplicationAutoScalingClient` and call `RegisterScalableTarget` with related parameters. You can find more details under `aws-cpp-sdk-application-autoscaling`.

**Comment by pcaswell** [comment]
Thanks.
