### ISSUE TITLE
Post API in C++ SDK

### ISSUE THREAD

**Issue by prabindh** [aws/aws-sdk-cpp#767]
### What platform/OS are you using?
Windows x64

### What compiler are you using? what version?
Visual studio 2015 u3

### What's your CMake arguments?
Default
### Can you provide a TRACE level log? (sanitize any sensitive information)
NA

What is the recommended way to create a POST request, in C++ SDK ? This is not for part uploads/multipart forms, but just POST request to be sent to an endpoint hosted on S3. I do not see an API / object request exposed in the same manner as GetObject and PutObject.  I can get started using the raw Aws::Http::HttpRequest, but wanted to confirm.

**Comment by JonathanHenson** [comment]
I think it is called “UpdateObject”

**Comment by prabindh** [comment]
Could not find UpdateObject in sdk-S3, but see some references to it in the sdk-clouddirectory, which is not what I need. I wrote up my own using HttpRequest in the meantime. Strange there is no POST support in the cpp sdk for S3.

**Comment by prabindh** [comment]
Updated title to closely reflect what I need.

**Comment by JonathanHenson** [comment]
You are correct, looks like there is no PostObject in the api models. It’s probably only in java and dotnet because those are handwritten and not generated. Do you have a use case where I could ask for the s3 to include it in their model?

**Comment by prabindh** [comment]
I have a C++ (native, non-browser) client that needs to communicate to a S3 endpoint, using POST via the REST API.

**Comment by JonathanHenson** [comment]
As far as I can tell none of the SDKs support POST, working with S3 now to see if we should include it.

**Comment by prabindh** [comment]
Thanks. Any update ?

**Comment by Wylie-Modro** [comment]
Are there any examples for how to setup/create a post request from just the raw AWS::Http::HttpClient?
Trying just to do a basic Post to my API Gateway but there does not seem to be any guides on how to do this.
