### ISSUE TITLE
API to access Redshift tables

### ISSUE THREAD

**Issue by hangfu** [aws/aws-sdk-cpp#768]
I'm trying to use this SDK to access Redshift in my c++ application, but couldn't find any example code.
By looking at the documentation, I couldn't figure out the API to get items from tables.
Is there an API that I can use to fetch data from Redshift tables? Similar to Aws::DynamoDB::Model::GetItemRequest

**Comment by singku** [comment]
Hi, there is no such API(s) in aws-cpp-sdk-redshift. APIs in aws-cpp-sdk-redshift are used to manage redshift clusters. Once you lunched your own redshift cluster, you can connect to and manipulate databases in that cluster with a regular sql client as you normally do with Mysql or MSSQLServer.

**Comment by hangfu** [comment]
I've tried libpqxx, but it throws an error saying "Unsupported server version; 9.0 is the minimum."
So MySQL Connector/C++ should work?

**Comment by singku** [comment]
For that part: see [here](https://docs.aws.amazon.com/redshift/latest/dg/c-dev-guide-prereqs.html)
