### ISSUE TITLE
How to set up parameters to build a library for the iPhone with different arch

### ISSUE THREAD

**Issue by ZSwitch** [aws/aws-sdk-cpp#769]
How to set up parameters to build a library for the iPhone with different arch?
just like arm64、armv7、armv7s、x86, and so on
There is "ANDROID_ABI" for android.I wonder if some parameters like it exist for iOS?

**Comment by wps132230** [comment]
You can try `CMAKE_OSX_ARCHITECTURES`.

**Comment by ZSwitch** [comment]
Thank you very much.
