### ISSUE TITLE
Question - How to include custom log information

### ISSUE THREAD

**Issue by mmustafa-hp** [aws/aws-sdk-cpp#770]
We read about a capability in the REST interface that allows for including custom information to be stored in the access log record for a request. 

Question: is there a way to accomplish the same in the SDK when using the transfer client to getting object?

Here is the link to the information about adding Custom S3 Access log information:

https://docs.aws.amazon.com/AmazonS3/latest/dev/LogFormat.html

Custom Access Log Information
You can include custom information to be stored in the access log record for a request by adding a custom query-string parameter to the URL for the request. Amazon S3 will ignore query-string parameters that begin with "x-", but will include those parameters in the access log record for the request, as part of the Request-URI field of the log record. For example, a GET request for "s3.amazonaws.com/mybucket/photos/2014/08/puppy.jpg?x-user=johndoe" will work the same as the same request for "s3.amazonaws.com/mybucket/photos/2014/08/puppy.jpg", except that the "x-user=johndoe" string will be included in the Request-URI field for the associated log record. This functionality is available in the REST interface only.

### What platform/OS are you using?
Windows 10
### What compiler are you using? what version?
VC 14
### What's your CMake arguments?
Not applicable
### Can you provide a TRACE level log? (sanitize any sensitive information)
Not applicable

**Comment by crusader-mike** [comment]
You can try overriding default [HttpClientFactory](https://github.com/aws/aws-sdk-cpp/blob/f02083e72b1d976a34765a64da4a564d307b2afa/aws-cpp-sdk-core/source/http/HttpClientFactory.cpp#L101) and add extra params to URI.
