### ISSUE TITLE
Add missed virtual destructor to PersistentCognitoIdentityProvider

### ISSUE THREAD

**Issue by pmogilevskiy** [aws/aws-sdk-cpp#771]
Hi there!

When building our own project which uses aws-sdk-cpp there are warnings related to missed virtual dctor in PersistentCognitoIdentityProvider (See details below).  It would be nice to fix that, because we treat all warning as errors. Thanks!

### What platform/OS are you using?

Windows 10 Pro 

### What compiler are you using? what version?

MSVC 2015 x64

### Can you provide a TRACE level log? (sanitize any sensitive information)

aws-sdk-cpp\include\aws\identity-management\auth\PersistentCognitoIdentityProvider.h:70: warning: C4265: 'Aws::Auth::PersistentCognitoIdentityProvider': class has virtual functions, but destructor is not virtual instances of this class may not be destructed correctly

aws-sdk-cpp\include\aws\identity-management\auth\PersistentCognitoIdentityProvider.h:101: warning: C4265: 'Aws::Auth::PersistentCognitoIdentityProvider_JsonFileImpl': class has virtual functions, but destructor is not virtual instances of this class may not be destructed correctly

**Comment by marcomagdy** [comment]
We'll get that added right away. Thank you.

**Comment by singku** [comment]
Hi, this has been fixed in commits: https://github.com/aws/aws-sdk-cpp/commit/9ce3602828743e2f5decf82adc951ee7cab759ff
And is now available in version 1.3.46.
Please reopen if you still have problem.

**Comment by pmogilevskiy** [comment]
Thank you!
