### ISSUE TITLE
Do I need initAndCleanupOpenSSL on Windows? (official nuget build)

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#773]
My application lives on both Windows and Linux, it uses AWS SDK and libcurl (with OpenSSL on Linux and with WinSSL on Windows). I set both `initAndCleanupCurl` and `initAndCleanupOpenSSL` to `false` and initialize libcurl (on both platforms) and OpenSSL (on Linux) myself. WinSSL doesn't require initialization.

Does official "nuget" build of AWS SDK (which uses WinHTTP) use OpenSSL? I.e. do I need to set `initAndCleanupOpenSSL` to `true` in my Windows build?

I also reviewed related part of AWS SDK code and compared it with related [requirements](https://wiki.openssl.org/index.php/Library_Initialization). Here are my notes for AWS SDK team -- I believe they might be useful:
1. You can not use `static_cast<unsigned long>(hash<thread::id>()(this_thread::get_id()))` as unique thread identifier -- hash<thread::id> is not guaranteed to differ for different thread ids. I am afraid right now there is no portable solution -- you have to use platform-specific functions.
2. `ERR_load_CRYPTO_strings()` should probably be changed to `SSL_load_error_strings()`
3. `OPENSSL_add_all_algorithms()` is deprecated (and needed only with very old OpenSSL versions if you want to use SHA2). Should probably be replaced with `SSL_library_init()`
4. `OPENSSL_add_all_algorithms_noconf()` -- what is the reason for using `_noconf`? 
5. `CRYPTO_set_id_callback()` is deprecated in favor of `CRYPTO_THREADID_set_callback()`
6. you don't do any OpenSSL uninitialization (besides unregistering locks/thread_id callbacks), but it is understandable -- apparently right now there [is no way to do it properly](https://wiki.openssl.org/index.php/Library_Initialization)

Deprecated stuff isn't very important, but it probably makes sense to look at other points raised above.

**Comment by pmogilevskiy** [comment]
+1 for review CryptoImpl.cpp. 

No we have crashes on Mac OS X, probably related to thread concurrency. And, it seems, something is wrong with locking callbacks. We are investigating this now.

**Comment by crusader-mike** [comment]
> No we have crashes on Mac OS X

Uhm... Is it an answer to my question? (As in "No, no need to set initAndCleanupOpenSSL to true in your circumstances"?)

> we have crashes on Mac OS X, probably related to thread concurrency

Could it be related to point 1 (thread id)? I'd also get latest libcurl and openssl.

**Comment by JonathanHenson** [comment]
Unless you’re doing something extra, openssl isn’t used on Mac OS builds and the initOpenSSL stuff doesn’t do anything.

**Comment by pmogilevskiy** [comment]
@JonathanHenson, We don't use Security Transport on OS X. We are using openssl instead.

**Comment by crusader-mike** [comment]
@pmogilevskiy if you suspect it to be due to point 1 -- it is easy to check... Just set `initAndCleanupOpenSSL`  to `false` and init openssl yourself (use platform-specific thread id) and run your tests again.

Overall, can we stick to original topic -- that is necessity of `initAndCleanupOpenSSL` in official Windows build (nuget package) of AWS SDK? :)

**Comment by singku** [comment]
You don't need to if using Nuget packages. Also Nuget is not supported anymore.

**Comment by crusader-mike** [comment]
Thanks, Andrew.
