### ISSUE TITLE
How does Cognito Sync in aws-sdk-cpp stores data on different platforms?

### ISSUE THREAD

**Issue by atlascoder** [aws/aws-sdk-cpp#774]
It's a general question.

I use `aws-sdk-cpp` for building a multiplatform mobile app. I've implemented authentication and registration of a user. And now I need to store some data on Aws. These data are mostly textual and those amount is measured in hundreds of symbols.

Basically, Cognito Sync is recommended for such cases. Cognito Sync in mobile Sdk's preforms data persisting in its backend. But how will it work in `aws-sdk-cpp`? I suppose that I need to implement persistence layer myself. What is the right way?

**Comment by atlascoder** [comment]
A little clarification: I mean persisting data between application restarts or device reboots.

**Comment by atlascoder** [comment]
Ok, I don't see any implementation of persistence for CognitoSync.. Just interface of client.

**Comment by JonathanHenson** [comment]
Ive written one complete with push notification support. We just never published it. It’s worth looking in to publishing it, can you give more details on your usecase?

**Comment by atlascoder** [comment]
I am creating an app for Android and iOS platforms using Qt.

I store my data in an sqlite database, it is quiet simple to make for many platforms in the same way.

I just need to have this data synced among devices on single account. As far amount of data is very low, under 500 kB, I've declined to use data storage or database services for such simple data, but maybe I am wrong..? 

I don't need to sync data by push notification - for my app it is enough to sync data at defined points of app's lifecycle.

What I need, is to understand, how to connect my local persistence (sqlite) with aws cloud. I understood, that aws-sdk-cpp contains just interface for CognitoSyncClient and I have to perform all synchronization logic on client side myself. It's ok, for crossplatform library, but synchronization logic is unclear, as for me.

Actually I don's see any `synchronize` or `sync` method in the CPP SDK, which is mentioned in docs for Mobile SDKs.

I've found that I need to track `syncCount` parameter for each record in dataset, and set its value the same, when sending updates to cloud. I suppose, I means that server is incrementing this value and I have to update this value each time before I am trying to update some record.

I also see there `lastMidifiedDate`, `lastModifiedBy`, and `deviceLastModifiedDate` fields.

I see my approach, for a single dataset, lake the following.
1. I request RecordsList for certain dataset and define, by `lastModifiedDate`, what data is newer on the cloud, and update my local storage.
2. I define what records from my local storage is newer than received from the cloud, and perform update requests to the cloud, setting `syncCount` for these records as in results of first request.

And here I have 3 questions:

1. Is it enough to rely only on `lastModifiedField`?
2. Where `lastModifiedField` is set: client or cloud side?
3. I don't need to distinguish user's devices. I need the same data for User account - single User Pool Identity. Do I need to track user device int fields `lastModifiedBy` and `deviceLastModifiedDate`?

Much appreciate your help!

**Comment by atlascoder** [comment]
Ok, I have answers now.

1. `lastModifiedField` is enough to define latest changed record, it is measured in msec.
2. `lastModifiedField` is set on server side and UpdateRecords request, being successful, will contain this value.
3. Device related fields can be ignored.

Probably, someone find it helpful.
