### ISSUE TITLE
Update version of TinyXML2

### ISSUE THREAD

**Issue by oliora** [aws/aws-sdk-cpp#777]
Please update version of TinyXML2 that's used in the SDK.
In particular, we need fix for https://github.com/leethomason/tinyxml2/issues/291 applied.
I hope this should fix #385 (crash inside TinyXML2 when `S3Client` is used)

**Comment by wps132230** [comment]
We've updated `tinyxml2`(ver. 6.1.0) in this commit: https://github.com/aws/aws-sdk-cpp/commit/95665defba19d4bf8b7ad7914c629ddfc6bddc1c.
You can update your sdk to version 1.3.48 or later to support that.
Please reopen this issue if you have more questions.
