### ISSUE TITLE
Assertion failed: (s_HttpClientFactory), function CreateHttpRequest

### ISSUE THREAD

**Issue by atlascoder** [aws/aws-sdk-cpp#778]
I use Cognito libs in my app and use blocking calls from my custom threads.
Application is crashing when I it is closed before active request has completed.

`Assertion failed: (s_HttpClientFactory), function CreateHttpRequest, file /Users/atlascoder/DevLibs/aws-sdk-cpp/src/aws-sdk-cpp/aws-cpp-sdk-core/source/http/HttpClientFactory.cpp, line 186.`

I do not think that any code is necessary, because it is, most probably, a conceptual question. As far an assertion is failing, it means either I do not follow to required API by its design or designed API does not fit to mu use-case.

So, what is right?

**Comment by Bu11etmagnet** [comment]
Did you call InitAPI ?

**Comment by atlascoder** [comment]
Yes, I use both:

    Aws::InitAPI(awsOptions);

    // app execution
    // aws-api calls are executing in worker threadpool
    // cognitoIdentityClient.InitiateAuth(...)
    // cognitoIdentityClient.GetCredentialsForIdentity(...)
    // cognitoSyncClient.ListRecords(...)
    // cognitoSyncClient.UpdateRecords(...)
    // e.t.c.
    mainThread.wait();
    Aws::ShutdownAPI(awsOptions);

The app crashing when it is closed, but aws-api call has not completed.

I can make app waiting for completion of active worker threads, but I am working on mobile application, and it is usual case when user stops application at any moment and continuing operations in background, waiting for thread completion, is not a good idea.

I guess there should be some call that interrupts that does cancelling of active requests correctly, but can't find it.

**Comment by marcomagdy** [comment]
> The app crashing when it is closed, but aws-api call has not completed.

Seems there're multiple things going on here.
1- The assertion failure happens normally if you didn't call init as @Bu11etmagnet mentioned.
2- The crash due to active worker threads. Since you mentioned that you're using blocking calls in the SDK and you have your own worker threads, then depending on your application, you might be able to join or detach the threads and use an atomic variable to indicate to the workers that no further processing should be done.

**Comment by marcomagdy** [comment]
Try `CognitoSyncClient::DisableRequestProcessing()`

**Comment by marcomagdy** [comment]
There's also `SetContinueRequestHandler(...)` method on every request if you'd like a more fine grained control.
But in your case, I think you want to cancel all ongoing requests.
I hope that helps you.

**Comment by atlascoder** [comment]
@marcomagdy, i didn't see `DisableRequestProcessing`...
I will try, thank you!

**Comment by atlascoder** [comment]
Ok, guys, it is my inattentiveness to API processing and not SDK issue, sorry.

The problem is wrong state when an AwsClient is instantiated but not while it is being running. In my thread, AwsClients was instantiated after then `Aws::ShutdownAPI(awsOptions);` was called and the assertion does exactly what it have to.
