### ISSUE TITLE
uploading file to s3 using aws-sdk-cpp-transfer module generate corrupted debug lines

### ISSUE THREAD

**Issue by Eliyahu-Machluf** [aws/aws-sdk-cpp#78]
Hi,

I'm using transfer client to upload files to s3 (using aws-sdk-cpp-transfer module).

I configured my utility to write logs using the line:
    Aws::Utils::Logging::InitializeAWSLogging(Aws::MakeSharedAws::Utils::Logging::DefaultLogSystem("ANW Internal logger", Aws::Utils::Logging::LogLevel::Trace, "aws_sdk_cpp_intern") );

Then I upload a file sized 12MB using up to 25 connections (using TransferClient object). 
When looking at the log file, I see this line which contains garbage:

[DEBUG] 2016-01-13 13:30:10 WinHttpSyncHttpClient [12768] Received content type שֱ‎צu~¥y‏µעמ0^#O%Z¯¡׳Mסו)ג

I did several tests, and always it occurred when printing a line regarding the received content type on debug mode.

Running the test on Windows10 x64.

Thanks.

Eliyahu

**Comment by bretambrose** [comment]
This issue slipped through cracks.  I've added an item to our backlog and we'll try and take a look at it soon.

**Comment by singku** [comment]
@Eliyahu-Machluf Do you still have this problem exist in your project? Did you upload a binary file and output the content of it?

**Comment by Eliyahu-Machluf** [comment]
Hi,

Since I got these corrupted debug lines, I disabled the debug on my application. So I don't know whether the problem still exist or not. I did several tests now, uploading with debug information, and all worked fine (i.e. all logger debug data was with printable characters).
So I suggest you close this issue, I'll turn on the debug, and if I encounter again the problem I'll let you know.
