### ISSUE TITLE
CognitoSync RecordPatch with Operation::remove

### ISSUE THREAD

**Issue by atlascoder** [aws/aws-sdk-cpp#782]
I am integrating CognitoSync into my mobile App project. I want to store small datasets and sync it among user's devices.

I can get records from cloud with `CognitoSyncClient#ListRecords` and update with `CognitoSyncClient#UpdateRecords`.

When updating records, I create `RecordPatch` with operations `replace` and `remove`. `replace` is working well: after such patches, next calls of ListRecords return updated records with lastModificationDate and SyncCount that are set when the record was updated with `UpdateRecord` call.

But `remove` works in some strange way: it does not remove records from the cloud, and that records are still returning in further `ListRecords`. Here is how I prepare `PatchRequest` for deleted records:

   map<Aws::String, int> toDelete; // stores <key> and <syncCount> for records to delete 

    for(auto to_del : toDelete){
        Model::RecordPatch patch;
        patch.SetOp(Aws::CognitoSync::Model::Operation::remove);
        patch.SetKey(Aws::String(to_del.first);
        patch.SetSyncCount(to_del.second);
        updateRequest.AddRecordPatches(patch);
    }

I don't set values to records having `remove` operation, and ListRecords returns these records to me with empty value. But for `replace` patches I set value. Also, I put `remove` and `replace` patches in single request.

It looks like operation does not work properly.

**Comment by singku** [comment]
What's the response of the request? Specially, the value of outcome.IsSuscess()

**Comment by atlascoder** [comment]
@singku , yes, I receive successful response with records having updated fields like syncCounts, lastMedifiedDate, etc...

**Comment by singku** [comment]
I had a look at the Coginito Sync documentation and didn't find out the answer for you.
Maybe you can ask this question on the forum [here](https://forums.aws.amazon.com/forum.jspa?forumID=173&start=0).

**Comment by atlascoder** [comment]
Ok, at this moment I have a single supposing that such behavior is designed to sync empty values instead of deleting of keys.
