### ISSUE TITLE
Avoiding data copy in S3 PutObject flow?

### ISSUE THREAD

**Issue by amirkope** [aws/aws-sdk-cpp#785]
My application layer is already allocating a memory buffers to which it copies/creates data. Optimally, I would like to serialize and send this data to S3 without having to allocate (and copy to) another buffer in the process. Is there an easy way to avoid buffer allocation and data copy in PutObject flow?

As far as I understand it, in order to use PutObject on an already-in-memory data, I need to create an IOStream from some streambuf object. SDK does offers creating a PreallocatedStreamBuf (so one unnecessary copy is saved) but only from an Aws::Utils::Array, which always allocates its own buffer.

Ideally for me, SDK would expose another kind of PreallocatedStreamBuf that takes a pointer of a memory buffer with no additional overhead, or another kind of Array which can be constructed with a preallocated buffer. In any case, buffer ownership should remain at application layer (which also needs to release it later).

One solution can be to change my application layer to allocate its buffers only via AWS SDK Arrays but I don't really like this solution because my application already has its own memory management and also I would have to change too many layers and APIs along the way.

I can probably do the tedious work of deriving another streambuf myself but I was wondering if I was missing something or maybe there are future plans to expose such API?

Help would be appreciated. Thanks!

**Comment by singku** [comment]
I think this is what you need:https://github.com/aws/aws-sdk-cpp/blob/970a729a7d3541b2fd7948f413992e8a851ec329/aws-cpp-sdk-core/include/aws/core/utils/stream/ResponseStream.h#L70-L78

**Comment by amirkope** [comment]
Thanks @singku 
Actually, the data allocation/copy that bothers me occurs before that stage, in the `Aws::Utils::Array` class (which can only be constructed while allocating additional memory). I'll try to demonstrate with the following example from `TransferManager::DoSinglePartUpload`.

Notice that in this code user's stream is duplicated to another stream. The memory copy itself occurs in line 389 where user data is copied to an Array's underlying buffer.

https://github.com/aws/aws-sdk-cpp/blob/cd59bdd1feeefc008d12bff3447c0bc474b22a36/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp#L386-L391

---
I'll try to clarify further by attaching a code snippet, similar to my current code:
`userDataBuff` is a `u8` buffer allocated by the user (application layer). In order to upload `userDataBuff` to S3, it seems I need to do something like this:
```
Aws::Utils::Array<u8> array(userDataBuff, userDataBuffSize); // <== data copy inside!
Aws::Utils::Stream::PreallocatedStreamBuf streamBuf(&array, array.GetLength());
auto preallocatedStreamReader = Aws::MakeShared<Aws::IOStream>("preallocatedStreamReader", &streamBuf);
putObjectRequest.SetBody(preallocatedStreamReader);
```
I'm looking for an option to avoid the data copy in the Array constructor. Two options crossed my mind:
1. Using a different Array that doesn't use allocation/copy (only shallow copy of the buffer pointer).
2. Using a different PreallocatedStreamBuf which uses an underlying buffer of type u8* instead of an Array.

**Comment by crusader-mike** [comment]
> Is there an easy way to avoid buffer allocation and data copy in PutObject flow?

No, you need to write your own `streambuf` implementation -- it is not easy, but doable.  You can probably avoid copy by using `std::strstream<>`, but it is deprecated.

**Comment by taddygrrr** [comment]
This issue has been around for some time, see #64.    Several people have said write your own streambuf without pointing to one that works.  (Have you implemented one, crusader-mike, or did you just read that somewhere?)    Best solution I've found is given in #533.    

Found that my solution leaks; have narrowed it down to the code in posted in #533, suspect version of SDK I'm using leaks.

**Comment by crusader-mike** [comment]
> Have you implemented one, crusader-mike, or did you just read that somewhere?

from #533:
> I had to spend a day or so before I got minimal version right

;)

**Comment by taddygrrr** [comment]
Have yet to see one that works with the AWS SDK for PUT of a large file to S3.    
So, let's see it.

**Comment by crusader-mike** [comment]
Don't want to deal with HR about making company property public. It isn't hard -- just read related docs carefully.

**Comment by taddygrrr** [comment]
Complex enough to be considered IP but simple enough that it's not hard.   I'm calling BS.   Your HR department isn't scanning ASK SDK issues web site for proprietary stream buffer implementations.

You could point to any existing StreamBuf implementation online -- there's several that claim to be complete and correct; why should people have to write their own streambuf implementation? -- and show how it's supposed to work with AWS SDK.   Maybe I'm doing something wrong.    As it stands, people are still having trouble getting it working and your comments are not helpful.

Boost version I posted works.   Nothing proprietary about showing code someone else has written with AWS SDK examples.

**Comment by JonathanHenson** [comment]
We could  just add an extra constructor to preallocated stream and array if you would like.

**Comment by crusader-mike** [comment]
> You could point to any existing StreamBuf implementation online -- there's several that claim to be complete and correct

We both know how to use google.... ;-) I had to do some bugfixing in one of these implementations lifted off internet.


> Maybe I'm doing something wrong.

@taddygrrr I didn't see any leaks in my program (and we moved terrabytes of data already). So, yeah -- chances are you are doing smth wrong. "Whether it is complex enough to be considered an IP" is another sort of conversation I'd like to avoid to have with HR -- those guys aren't technical and it won't go well for me.

(Side note: In case if you think I am paranoid -- just read your contract carefully. Most people would never sign a typical IT job contract if they weren't under pressure of "having to make a living". At least I wouldn't.)

**Comment by taddygrrr** [comment]
It's also worth noting that AWS hasn't posted a complete example showing how to do a PUT of a large  buffer to S3.   Instead, they show how to upload a file.  That works well.     

Read the comments on the referenced tickets.   @JonathanHenson has suggested a simpler interface on a ticket that's been open since January 3rd, 2016,  #64.    I'm asking for some follow up.

**Comment by JonathanHenson** [comment]
The iostream interface can’t be undone, and I take complete responsibility for that design flaw. But in the very near future, we’ll be providing an interface that will make sure you don’t have to ever touch one again if you don’t want to. Basically we have a stream_buf implementation that will run your simpler interface implementation for you automatically.

**Comment by crusader-mike** [comment]
I hear you, @JonathanHenson -- I burned on iostreams long long (like 15 years?) ago, can't stand them since then (funny to hear this from a diehard C++ fan, isn't it?). That library is a walking can of fat worms. It is better to avoid it at all costs.  :-)

**Comment by LarryMarg** [comment]
What I'd like to see is a Aws::AmazonStreamingWebServiceRequest::SetBody(const char *, int64_t).

Take a pointer to my buffer, wrap it however you need without copying the contents, and don't make me jump through hoops.

Thanks.

**Comment by amirkope** [comment]
@JonathanHenson - great, we're looking forward these changes.

Since I opened this ticket, let me just update:
I eventually used Boost's boost::interprocess::bufferstream and initialized it with my own pre-allocated buffer. Works great for me.

As a side note: If you want to avoid 3rd party like Boost, the approach of using std::basic_stringstream as mentioned in the opening comment of #64 (Aws::StringStream), although less neat, can also be OK IMHO, although it's implementation-specific, so this should be checked for the specific std libs. 
At a first glance (and as some forums suggested) I thought there might be a problem using stringstream for data (because of NULL terminating chars) but I found that if you set the size of the buffer explicitly (as in the example there) it handles it with no problem for my uses (unlike a simple string itself).

Thanks for all the responses.

**Comment by LarryMarg** [comment]
@amirkope - Note that I did try StringStream and stream->rdbuf()->pubsetbuf(), but that didn't work, and I wasted time tracing through the VS 2015 implementation to find that pubsetbuf() calls the private setbuf(), which does nothing.

Since I was working on a last-minute requirement that had to be merged that day, there was no time to download and understand the Boost stuff, much less worry about getting permission to use it, so I bit the bullet and accepted the performance overhead of the extra copy, even though it tears me up inside.  :-)

**Comment by amirkope** [comment]
_<oops didn't get a mail update for the last comment !? >_
@LarryMarg - as I mentioned in my previous comment the StringStream worked for my (Linux) setbuf() implementation, sorry it didn't work for yours :-/

I feel your pain :-) it also bothered me a lot... But I had the chance to first make a relatively quick (though extensive and ugly) solution only for one (the busiest) flow, in which I changed the initial memory allocation of the data and replaced it with a respective allocation of Aws::Utils::Array<u8>. This enabled me to later construct an Aws::Utils::Stream::PreallocatedStreamBuf from it and then an Aws::IOStream without the unnecessary data copy.
Handling the busiest flow gave me the peace of mind to continue evaluating the Boost solution and test it more carefully. Eventually I reverted and implemented the Boost solution with minimal changes to my code...

Hope you'll also find peace of mind eventually :-)
Cheers

**Comment by KaibaLopez** [comment]
Hi, I'm not sure there is anything more to add to this thread so I'll be closing it.
If anybody is still having this kind of issue, please open a new one, it'll just be easier to follow up to.
