### ISSUE TITLE
SSL verified connection does not work on Android

### ISSUE THREAD

**Issue by atlascoder** [aws/aws-sdk-cpp#791]
## Unable to connect to endpoint

```
    ClientConfig() : ClientConfiguration()
    {
        region = AWS_REGION;
        scheme = Aws::Http::Scheme::HTTPS;
        connectTimeoutMs = 40000;
        requestTimeoutMs = 60000;
        clientId = AWS_CLIENT_ID;
        userPoolName = AWS_POOL_NAME;
        userPoolId = region + "_" + userPoolName;
        identityPool = AWS_IDENTITY_POOL;
        accoundId = AWS_ACCOUNT_ID;
        verifySSL = true;
    }
```

But it works fine with
```
verifySSL = false;
```

### What platform/OS
Building Android App using Qt 5.9.3 on MacOS 10.12.6
Android build uses NDK 12b, target API level 19

### What compiler
compilers toolchain is generated by aws-sdk-cpp

### What's your CMake arguments?
```
cmake ../src/aws-sdk-cpp -DBUILD_SHARED_LIBS=OFF -DTARGET_ARCH=ANDROID -DBUILD_ONLY="core;iam;access-management;cognito-identity;iot;cognito-idp;cognito-sync;identity-management" -DNDK_DIR=/Users/anton.titkov/Library/Android/android-ndk-r12b -DENABLE_TESTING=OFF -DANDROID_STL=gnustl_shared
```

### TRACE level log

No log outputs with settings:
```
    Aws::SDKOptions awsOptions;
    awsOptions.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Warn;
    Aws::InitAPI(awsOptions);
```

**Comment by bretambrose** [comment]
Default Android setups (as of a year ago at least) do not have a cert record capable of completing the SSL handshake with amazon servers.  If that is still the case, you will need to supply that manually.  As an example, the android testing setup in the SDK manually uploads a sufficient cert set to the emulator before executing the tests (using https).

**Comment by atlascoder** [comment]
Thanks @bretambrose, got it!

**Comment by atlascoder** [comment]
But I think it's better to get some more definitive response rather general "Unable to connect to endpoint". And it looks like that connection is closed by timeout and not by SSL verification failure.
