### ISSUE TITLE
"Unable to connect to endpoint" error when trying to use Batch

### ISSUE THREAD

**Issue by personalis** [aws/aws-sdk-cpp#794]
I'm on CentOS linux, using gcc-4.9.3.  I am attempting to use the AWS Batch part of the C++ SDK.  I have written this very basic demo program:
https://pastebin.com/x5PMQy42

When I run it, I get:
`Could not get JobDefinition list`
`error:  - Unable to connect to endpoint`
`Response code: 0`

Note that the error _message_ (descjob_outcome.GetError().GetMessage()) is "Unable to connect to endpoint", but the _Exception name_ (descjob_outcome.GetError().GetExceptionName()) is actually an empty string, between "error: " and "-" in my formatted output. Also, the Response code is 0, which is not among the codes listed in HttpResponse.h.

I don't think the problem is in my AWS config, because I downloaded the aws-doc-sdk-examples repo from Github, and I can compile and run the C++ examples there just fine (for example, the list_buckets program in the s3 folder). Unfortunately, aws-doc-sdk-examples does not include any Batch example code, which is the part of the API that I am most interested in using.

I also want to note that I am able to run a simple **python** program that uses the AWS Batch API (through the boto3 module), so again I don't think this problem is particular to my AWS configuration.

**Comment by wps132230** [comment]
Try to use `HTTPS`, it works for me.

**Comment by personalis** [comment]
Thanks.  I tried to use HTTPS instead of HTTP, I get the same error.

**Comment by marcomagdy** [comment]
Looks like AWS Batch is sending back "HTTP 307 Temporary Redirect" and CURL is failing to rewind the request stream to replay it.
We need to implement `CURLOPT_SEEKFUNCTION` callback in our `CurlHttpClient` to handle it. Will get this queued up and get fixed.

**Comment by singku** [comment]
I have also tried HTTPS and it worked for me. Could you please set the log options,
`options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;`
 and paste the log here?

**Comment by singku** [comment]
The fix has been merged.
