### ISSUE TITLE
Error  corrupted double-linked list when using Kinesis APi

### ISSUE THREAD

**Issue by dk1301** [aws/aws-sdk-cpp#795]
### What platform/OS are you using?
Armbian Debian Jessie 8.0
### What compiler are you using? what version?
gcc 4.9.2
### What's your CMake arguments?
 cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="config;core;kinesis"
### Can you provide a TRACE level log? (sanitize any sensitive information)

The code that I use is the following:

```
SDKOptions options;
				
options.cryptoOptions.initAndCleanupOpenSSL = false;

Aws::InitAPI(options);

Aws::Client::ClientConfiguration conf;

conf.verifySSL = false;

	
 conf.region = Aws::Region::US_EAST_1;	

auto creds = Aws::Auth::AWSCredentials(accessToken, sk, skt); //I get these form sessionToken

KinesisClient awsclient = InitAwsClient(creds, conf);


auto request = new Aws::Kinesis::Model::PutRecordRequest();


string streamer = "streamer_name";
request->SetStreamName(streamer.c_str());
				

Aws::Utils::Array<unsigned char> arr(buffer.data(), buffer.size());
request->SetData(arr);
request->SetPartitionKey(device_id.c_str());

auto response = awsclient.PutRecord(*request);
if (response.IsSuccess())
   {
	cout << "Measurement uploaded" << endl; 
  }
else {
	cout << "Measurement upload failed" << endl;
}
Aws::ShutdownAPI(options);
cout << "API successfully closed" << endl;
```

It succeded many times and all of a sudden I get the error *** Error in `./my_app': corrupted double-linked list: 0x74207276 ***

The code stopped  according to printout to the line` cout << "Measurement uploaded" << endl; `. It may or may not executed the Aws::ShutdownAPI(options);  Due to the fact that my app uses Openssl I set the line `options.cryptoOptions.initAndCleanupOpenSSL = false;`

Can you tell what might be the problem ? I 'm using SDK version (1.0.50) and also tried with (1.2.22)

**Comment by crusader-mike** [comment]
> Due to the fact that my app uses Openssl I set the line options.cryptoOptions.initAndCleanupOpenSSL = false;

Do you properly initialize OpenSSL before using any of AWS SDK functions? By "properly" I mean "initialize it for multithreading use"

**Comment by dk1301** [comment]
I must have missed it. How can initialize for multithreading use. Is there any relevant example?

**Comment by crusader-mike** [comment]
https://wiki.openssl.org/index.php/Library_Initialization

Pay special attention to "Static locks" chapter

**Comment by KaibaLopez** [comment]
Hi, just checking in on these old issues, I hope the problem was solved for you, and thanks to crusader-mike.
I'll be marking this issue for closure, please comment if there's any related questions.
