### ISSUE TITLE
Compilation error when using aws-sdk-cpp-iot lib

### ISSUE THREAD

**Issue by sapnatodwal** [aws/aws-sdk-cpp#796]
### What platform/OS are you using?
Linux/Ubuntu

### What compiler are you using? what version?
gcc

### What's your CMake arguments?
cmake -Daws-sdk-cpp_DIR=~/aws-sdk-cpp/build ..

### Can you provide a TRACE level log? (sanitize any sensitive information)

This is the program that I am trying to compile:

#include <aws/core/Aws.h>
#include <aws/iot/IoTClient.h>
#include <aws/iot/model/CreateKeysAndCertificateRequest.h>
#include <aws/iot/model/CreateKeysAndCertificateResult.h>
#include <iostream>

int main(int argc, char** argv)
{

    Aws::SDKOptions options;
    Aws::InitAPI(options);
    {
    Aws::IoT::IoTClient iot;
    Aws::IoT::Model::CreateKeysAndCertificateRequest create_request;
    create_request.SetSetAsActive(true);

    auto outcome = iot.CreateKeysAndCertificate(create_request);
    if (!outcome.IsSuccess())
    {
        std::cout << "Error creating certs : " <<
            outcome.GetError().GetMessage() << std::endl;
        return;
    }

    std::cout << "Successfully created certs"  << std::endl;

    }Aws::ShutdownAPI(options);
    return 0;
}

However when trying to compile this I get the following error:

create_cert.cpp:17:63: error: invalid use of incomplete type ‘Aws::IoT::Model::CreateKeysAndCertificateOutcome {aka class Aws::Utils::Outcome<Aws::IoT::Model::CreateKeysAndCertificateResult, Aws::Client::AWSError<Aws::IoT::IoTErrors> >}’
     auto outcome = iot.CreateKeysAndCertificate(create_request);
                                                               ^
In file included from aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/crypto/Hash.h:19:0,
                 from aws-cpp-sdk-core/include/aws/core/client/AWSClient.h:23,
                 from aws-cpp-sdk-iot/include/aws/iot/IoTClient.h:21,
                 from create_cert.cpp:2:
aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/crypto/HashResult.h:26:50: error: declaration of ‘Aws::IoT::Model::CreateKeysAndCertificateOutcome {aka class Aws::Utils::Outcome<Aws::IoT::Model::CreateKeysAndCertificateResult, Aws::Client::AWSError<Aws::IoT::IoTErrors> >}’
         template< typename R, typename E > class Outcome;
   

Any help is greatly appreciated

**Comment by wps132230** [comment]
You need `#include <aws/core/utils/Outcome.h>`
