### ISSUE TITLE
Compilation Error with gtest.h/gtest-all.cc

### ISSUE THREAD

**Issue by pcaswell** [aws/aws-sdk-cpp#797]
### What platform/OS are you using?
Window 7 Professional 64bit

### What compiler are you using? what version?
Visual Studio 2017 (aka Visual Studio 14.1)
Compiler Version 19.12.25831

### What's your CMake arguments?
cmake ../aws-sdk-cpp-1.3.48 -G "Visual Studio 15 2017 Win64" -DSIMPLE_INSTALL=OFF 
-DCMAKE_INSTALL_PREFIX="../MyLibs/aws-sdk-cpp-1.3.48"

### Can you provide a TRACE level log? (sanitize any sensitive information)
NA

**Problem Details**
Hello Forum,
I am trying to build version 1.3.48 on using Visual Studio (details above).  The compile fails because gtest.h (in \aws-sdk-cpp-1.3.48\testing-resources\include\aws\external) uses TR1 code.  My version of Visual Studio issues a warning for this and as such the build fails.  Note that compiler_settings.cmake enables the /WX flag to treat warning as errors which I think is correct.

I tried to use the /D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING but it didn't seem to have any effect? So to 'fix' the error I have changed gtest.h (lines 2 to 4) to disable warning 4996 thus:

#ifdef _MSC_VER
#pragma warning (disable : 4820 4619 4668 4251 4275 4081 **4996**)
#endif

Does this need to be addressed in the AWS code base or can someone point me at how to use D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING properly?
/P

**Comment by marcomagdy** [comment]
We're fixing that. Should be available very soon.

**Comment by wps132230** [comment]
Updated Google test framework in commit: https://github.com/aws/aws-sdk-cpp/commit/98dc3adb8c942acc3197d2b973539ebe66fa6c6f
And ver 1.3.49 should fix this issue.

**Comment by pcaswell** [comment]
Thanks both.
