### ISSUE TITLE
Create S3 Bucket sample example 

### ISSUE THREAD

**Issue by hanaa-abdelgawad** [aws/aws-sdk-cpp#798]
Hi 
I face problem in setting the environment and compiling aws sdk for cpp. i follow steps in https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/getting-started.html but i recieve errors and i couldnt compile the project 
first trial: using Nuget
1- create a cpp console application. 
2- install AWSSDKCPP-S3 from NuGet
3- add main.cpp as follow:

#include "stdafx.h"
using namespace std;
#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>
#include <aws/s3/model/CreateBucketRequest.h>
#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>
#include <aws/s3/model/CreateBucketRequest.h>

/**
* Create an Amazon S3 bucket.
*/
int main(int argc, char** argv)
{
	if (argc < 2)
	{
		std::cout << "create_bucket - create an S3 bucket" << std::endl
			<< "\nUsage:" << std::endl
			<< "  create_bucket <bucket>" << std::endl
			<< "\nWhere:" << std::endl
			<< "  bucket - the bucket to create" << std::endl
			<< "\nExample:" << std::endl
			<< "  create_bucket testbucket\n" << std::endl << std::endl;
		exit(1);
	}

	Aws::SDKOptions options;
	Aws::InitAPI(options);
	{
		
	}
	Aws::ShutdownAPI(options);
}

i received those errors:
1>AWSPlugin.obj : error LNK2019: unresolved external symbol "void __cdecl Aws::InitAPI(struct Aws::SDKOptions const &)" (?InitAPI@Aws@@YAXAEBUSDKOptions@1@@Z) referenced in function main
1>AWSPlugin.obj : error LNK2019: unresolved external symbol "void __cdecl Aws::ShutdownAPI(struct Aws::SDKOptions const &)" (?ShutdownAPI@Aws@@YAXAEBUSDKOptions@1@@Z) referenced in function main

P.s. I decreased the code in main.cpp to know where is the problem, the target is create_bucket.cpp(if i add the whole code, I got 12 unclear errors as above)
it seems there is a certain configuration that is missing in my environment 
P.s for AWS credentials: i used aws configure and added my root access id, besides I created environment variables with my ID(Access Key ID and Secret Access Key as two different environment variables) 
please let me know what is missing in my configuration to successfully  compile any aws s3 cpp project
 
### What platform/OS are you using?
windows 10 
### What compiler are you using? what version?
visual studio 2017

**Comment by singku** [comment]
Hi, by using Nuget packages, you should define USE_IMPORT_EXPOR.

**Comment by wps132230** [comment]
Latest update:
We added Visual Studio 2017 support one week ago, so you don't need `USE_IMPORT_EXPOR` any more when you get AWS SDK for C++ via NuGet, starting from version 1.3.57.
