### ISSUE TITLE
Problem using AWS SDK for cpp - cmake - Creating an Out-of-Source Build

### ISSUE THREAD

**Issue by hanaa-abdelgawad** [aws/aws-sdk-cpp#799]
Hi
I would like to compile cpp https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/cpp/example_code/s3/create_bucket.cpp example 

### What platform/OS are you using?
windows 10 
### What compiler are you using? what version?
visual studio 2017 
### What's your CMake arguments?
cmake -Daws-sdk-cpp_DIR=sdk_build folder1
where: 
folder1 contains create_bucket.cpp as in AWS cpp example in github and CMakeLists.txt as below: 
-----------------------------------------------------------------
cmake_minimum_required(VERSION 2.8)
project(Project1)

#this will locate the aws sdk for c++ package so that we can use its targets
find_package(sdk_build)

add_executable(Project1 create_bucket.cpp)

#since we called find_package(), this will resolve all dependencies, header files, and cflags necessary
#to build and link your executable. 
target_link_libraries(Project1 aws-cpp-sdk-s3)

-------------------------------------------------------------
p.s. sdk_build is the aws-sdk-cpp (after going through cmake commands)
I received this error through using command line commands:
CMake Warning at CMakeLists.txt:6 (find_package):
  By not providing "Findsdk_build.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "sdk_build", but CMake did not find one.

  Could not find a package configuration file provided by "sdk_build" with
  any of the following names:

    sdk_buildConfig.cmake
    sdk_build-config.cmake

  Add the installation prefix of "sdk_build" to CMAKE_PREFIX_PATH or set
  "sdk_build_DIR" to a directory containing one of the above files.  If
  "sdk_build" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    aws-sdk-cpp_DIR

-- Build files have been written to: C:/AWSProjects/Project1

**Comment by singku** [comment]
Hi, find_package will find the literal package name you supplied, not the directory name, it should be aws-sdk-cpp.
