### ISSUE TITLE
Need help to configure for QT Android

### ISSUE THREAD

**Issue by ducmaxime** [aws/aws-sdk-cpp#804]
Hello, 

I try to configure for QT android.

I have downloaded the builded arm android zip file here http://sdk.amazonaws.com/cpp/builds/?prefix=cpp/builds/

And In my .pro I added 

android{
  QT += androidextras
  INCLUDEPATH += $$PWD/android/aws-sdk-cpp/include/
  LIBS += -L $$PWD/android/aws-sdk-cpp/lib/armeabi-v7a/Release/ -libaws-cpp-sdk-core
}

But when I compile I have this error : :-1: error: error: cannot find -libaws-cpp-sdk-core

lib/armeabi-v7a/Release/ is the good folder ?

Someone can help me ?

**Comment by singku** [comment]
Hi in Library specification, try using `-laws-cpp-sdk-core` instead of `-libaws-cpp-sdk-core`.
