### ISSUE TITLE
Include version number in SONAME of .so files

### ISSUE THREAD

**Issue by dave491** [aws/aws-sdk-cpp#807]
To make version management easier in linux, it would be good to set the SONAME for the library. At present there is no version included in .so files:
 
```
# objdump -p /usr/lib64/libaws-cpp-sdk-core.so | grep SONAME
  SONAME               libaws-cpp-sdk-core.so
```
 
This can be achieved via cmake’s SOVERSION property:
`set_property(TARGET bar PROPERTY SOVERSION XXXXX)`
 
The SOVERSION ought to be updated when a binary incompatible change to the library occurs, commonly done in-step with updating the major version of the library:
[http://pusling.com/blog/?p=352](http://pusling.com/blog/?p=352)

**Comment by marcomagdy** [comment]
That's a fair ask, we'll get that queued up. Thank you
