### ISSUE TITLE
Unable to build with cmake on ubuntu 16.04 

### ISSUE THREAD

**Issue by elluck91** [aws/aws-sdk-cpp#810]
Hi there,
I'm trying to build the SDK on Amazon EC2 running Ubuntu 16.04. I follow the instructions from the pdf (https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/aws-sdk-cpp-dg.pdf), installing all dependencies. I am able to run "cmake .." from the build directory, yet while I run make, I get this error:

```
[  1%] Built target aws-cpp-sdk-core
[  1%] Building CXX object aws-cpp-sdk-workdocs/CMakeFiles/aws-cpp-sdk-workdocs.dir/source/WorkDocsClient.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
aws-cpp-sdk-workdocs/CMakeFiles/aws-cpp-sdk-workdocs.dir/build.make:88: recipe for target 'aws-cpp-sdk-workdocs/CMakeFiles/aws-cpp-sdk-workdocs.dir/source/WorkDocsClient.cpp.o' failed
make[2]: *** [aws-cpp-sdk-workdocs/CMakeFiles/aws-cpp-sdk-workdocs.dir/source/WorkDocsClient.cpp.o] Error 4
CMakeFiles/Makefile2:117: recipe for target 'aws-cpp-sdk-workdocs/CMakeFiles/aws-cpp-sdk-workdocs.dir/all' failed
make[1]: *** [aws-cpp-sdk-workdocs/CMakeFiles/aws-cpp-sdk-workdocs.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

I'm using GNU compiler: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

If providing more information would be helpful, what information would be most beneficial?

Thanks a bunch!

**Comment by singku** [comment]
Looks like gcc's internal error. Could you please tell us your hardware configuration? 
What CMake flags you used? If possible could you please try build core only?

**Comment by elluck91** [comment]
`Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
Stepping:              2
CPU MHz:               2400.036
BogoMIPS:              4800.07
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0`

No CMake flags used (typed "cmake .." from build directory, and ".." contains the source).
When using DBUILD_ONLY="core" it builds just fine. I need Amazon Polly specifically, soI'll try to  find what parameter it is.

Thanks!

**Comment by singku** [comment]
I asked about hardware config because I was thinking if you were doing a parallel build, and the load to hardware is too much. If -DBUILD_ONLY="core" worked just fine, this somehow confirmed my concerns. If you only need polly simply try `cmake ../ -DBUILD_ONLY="polly"`

**Comment by elluck91** [comment]
This results in:

`-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating linux build config
-- Building project version: 1.4.3
--   Zlib include directory: /usr/include
--   Zlib library: /usr/lib/x86_64-linux-gnu/libz.so
-- Encryption: Openssl
--   Openssl include directory: /usr/include
--   Openssl library: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Http client: Curl
--   Curl include directory: /usr/include
--   Curl library: /usr/lib/x86_64-linux-gnu/libcurl.so
-- Considering polly
CMake Error at cmake/sdks.cmake:168 (message):
  corecore is required for build, but aws-cpp-sdk-corecore directory is
  missing!
Call Stack (most recent call first):
  CMakeLists.txt:129 (include)


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/Downloads/aws-sdk-cpp/sdk_build/CMakeFiles/CMakeOutput.log".`

**Comment by singku** [comment]
Aha, could you please update the code base to latest?

**Comment by elluck91** [comment]
Yay! It worked. Thanks a lot!
