### ISSUE TITLE
Missing -ldl in tests when using static linkage with openssl

### ISSUE THREAD

**Issue by Sleepyowl** [aws/aws-sdk-cpp#811]
Ubuntu 17.10
gcc 7.2.0
openssl 1.0.2n installed to `/usr/local/ssl`
aws-sdk-cpp checked out at `tags/'1.4.4'`
```
cmake ~/git/aws-sdk-cpp -DOPENSSL_ROOT_DIR=/usr/local/ssl -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_ONLY="s3;sqs;monitoring" -DCPP_STANDARD=14 -DCMAKE_CXX_FLAGS="-Wno-noexcept-type"
```
When building tests build fails with 
```
/usr/bin/ld: /usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
```

Quick and dirty workaround is to add `-DCMAKE_CXX_STANDARD_LIBRARIES="-ldl"`

**Comment by singku** [comment]
You don't have to specify where openssl is.
I tried your cmake command above (removed openssl_root_dir spec), and it worked just fine.

**Comment by Sleepyowl** [comment]
@singku I'm building against different version of openssl than my system has. If I remove OPENSSL_ROOT_DIR, it would dynamically link with a wrong version of openssl and then fail to run on the target system which is different from my build environment.

Anyway, problem seems to be on the cmake side (or in the FindOpenSSL module) as it fails to add -ldl automatically.
