### ISSUE TITLE
How to enable sensitive log information in AVS SDKv1.5?

### ISSUE THREAD

**Issue by kunasiramesh** [aws/aws-sdk-cpp#814]

**Comment by kunasiramesh** [comment]
Hi,
I have enabled "**ACSDK_EMIT_SENSITIVE_LOGS**" macro while building SampleApp with Debug mode. I want logs for every streem under "**ACSDK_EMIT_CURL_LOGS**" macro in the file "**sdk-source/avs-device-sdk-master/ACL/src/Transport/HTTP2Stream.cpp**" . Even though I enabled  "ACSDK_EMIT_CURL_LOGS" macro, I am not getting logs. In that  file below code returning every time without creating logs. If I mask "**return**" it is creating logs, but for one query it is creating 4 logs. how to configure to get logs? 

**CODE:**
void HTTP2Stream::initStreamLog() {
    std::string streamLogPrefix;
    configuration::ConfigurationNode::getRoot()[ACL_CONFIGURATION_KEY].getString(
        STREAM_LOG_PREFIX_KEY, &streamLogPrefix);
    if (streamLogPrefix.empty()) {
        return;
    }

    if (m_streamLog) {
        m_streamLog->close();
        m_streamLog.reset();
    }

    if (m_streamInDump) {
        m_streamInDump->close();
        m_streamInDump.reset();
    }

    if (m_streamOutDump) {
        m_streamOutDump->close();
        m_streamOutDump.reset();
    }

    // Include a 'session id' (just a time stamp) in the log file name to avoid overwriting previous sessions.
    static std::string sessionId;
    if (sessionId.empty()) {
        sessionId = std::to_string(std::chrono::system_clock::now().time_since_epoch().count());
        ACSDK_INFO(LX("initStreamLog").d("sessionId", sessionId));
    }

    auto basePath = streamLogPrefix + STREAM_LOG_NAME_PREFIX + sessionId + "-" + std::to_string(m_logicalStreamId);

    auto streamLogPath = basePath + STREAM_LOG_NAME_SUFFIX;
    m_streamLog.reset(new std::ofstream(streamLogPath));
    if (!m_streamLog->good()) {
        m_streamLog.reset();
        ACSDK_ERROR(LX("initStreamLogFailed").d("reason", "fileOpenFailed").d("streamLogPath", streamLogPath));
    }

    auto streamInDumpPath = basePath + STREAM_IN_DUMP_SUFFIX;
    m_streamInDump.reset(new std::ofstream(streamInDumpPath, std::ios_base::out | std::ios_base::binary));
    if (!m_streamInDump->good()) {
        m_streamInDump.reset();
        ACSDK_ERROR(LX("initStreamLogFailed").d("reason", "fileOpenFailed").d("streamInDumpPath", streamInDumpPath));
    }

    auto streamOutDumpPath = basePath + STREAM_OUT_DUMP_SUFFIX;
    m_streamOutDump.reset(new std::ofstream(streamOutDumpPath, std::ios_base::out | std::ios_base::binary));
    if (!m_streamOutDump->good()) {
        m_streamOutDump.reset();
        ACSDK_ERROR(LX("initStreamLogFailed").d("reason", "fileOpenFailed").d("streamOutDumpPath", streamOutDumpPath));
    }
}

**Comment by bretambrose** [comment]
I think you have the wrong repository.  You probably want to post this on:

https://github.com/alexa/avs-device-sdk
