### ISSUE TITLE
No ability to subscribe to IoT topics?

### ISSUE THREAD

**Issue by bppnw** [aws/aws-sdk-cpp#816]
I'm exploring the IoT and IoT Data Plane APIs and am stumped by the apparent asymmetry between the ability to publish and subscribe, namely that I don't see any support for subscriptions.  What's the intention here?

**Comment by singku** [comment]
Are you looking for IoT device SDK? https://github.com/aws/aws-iot-device-sdk-cpp

**Comment by bppnw** [comment]
No, I'm looking for a way to subscribe to topics via the C++ IoT application SDK (not for devices, but for building applications that can run within AWS as a service).  The device API has the ability to publish and subscribe.  The application API can only publish.  I'm not really sure I understand how that's supposed to work if it can only publish.

**Comment by rdewein-letsdev** [comment]
Any updates on this topic? @bppnw @singku 

I am currently facing the same problems.

Bests

**Comment by bppnw** [comment]
I found an alternative approach of using an AWS IoT rule to republish messages on those topics to an SNS queue, to which an SQS queue is subscribed.  I then use the SQS API to pull out the messages that way.

**Comment by KaibaLopez** [comment]
Hi, this issue has not been updated in more than a year, just checking in, is this still an issue?

**Comment by bretambrose** [comment]
Just a note for anyone coming across this late:

The Aws IoT data plane is fundamentally an mqtt-based service.  The standard AWS SDKs (of which this is one) are http-only, and do not contain support for mqtt or mqtt-over-websockets.  If you need to use the IoT data plane, your best bet is to use the [IoT SDKs](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html) and if you need to do both IoT data and standard AWS api calls, use both SDKs.

Ultimately, the semantics of vanilla http/1.1 are just not compatible with the complete pub-sub model of programming.  Publish is a one-way function that can be reasonably modeled in http, and the fact that IoT provides a Publish function in its http API is for convenience.
