### ISSUE TITLE
request: publish debug symbols (pdb) along with other nuget packages

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#817]
... either as separate .symbols package or part of existing packages. It really helps with debugging.

Thank you.

**Comment by singku** [comment]
PDF files are included in the existing nuget packages right now.

**Comment by singku** [comment]
Hi Symbols packages are published to SymbolSource, not Nuget.org. But unfortunately based on this: https://github.com/SymbolSource/SymbolSource/issues/7  pdb files are not supported by SymbolSource. 

I'd suggest you to use VCPackages https://github.com/Microsoft/vcpkg (aws-cpp-sdk is included)
or download pre-build binaries from http://sdk.amazonaws.com/cpp/builds/index.html?prefix=cpp/builds/

**Comment by crusader-mike** [comment]
@singku Not ideal, but thanks!
