### ISSUE TITLE
s3 static library errror

### ISSUE THREAD

**Issue by klelogitech** [aws/aws-sdk-cpp#819]
### What platform/OS are you using?
windows 10 pro x64
### What compiler are you using? what version?
visual studio 2013
### What's your CMake arguments?
cmake C:\Users\kle\Documents\GitHub\aws-sdk-
cpp -DBUILD_ONLY="s3" -DBUILD_SHARED_LIBS=OFF -DENABLE_UNITY_BUILD=ON -DFORCE_SHARED_CRT=ON -DTARGET_ARCH=WINDOWS -G "Vi
sual Studio 12 2013"
### Can you provide a TRACE level log? (sanitize any sensitive information)
[s3staticbuild_debuglog.txt](https://github.com/aws/aws-sdk-cpp/files/1782969/s3staticbuild_debuglog.txt)

I used cmake to create an S3 static library project and successfully built it. However, when I linked it to my project, it got some lnk 2019 errors (debug log attached).
Even if I set BUILD_SHARED_LIBS to OFF, code generation for release build is still Multi-threaded DLL (/MD).

**Comment by singku** [comment]
What's the version of sdk you used?

**Comment by klelogitech** [comment]
I used sdk version 1.4.9

**Comment by singku** [comment]
Could you please try again with FORCE_SHARED_CRT=OFF?

**Comment by klelogitech** [comment]
I am able to build it successfully with FORCE_SHARED_CRT=OFF and get the same lnk 2019 errors. The generation code is /MTd for debug and /MT for release. I thought it should be /MDd for debug and /MT for release.
