### ISSUE TITLE
Can someone point out any helpful documentation for using a custom API gateway with aws-sdk-cpp?

### ISSUE THREAD

**Issue by mattman71** [aws/aws-sdk-cpp#820]
I'm working with another developer and trying to figure out how to connect our client application with a new custom API gateway created on our aws account. We can figure it out for anything related to java or .NET, but for C++, we're really struggling.

I saw [this other thread](https://github.com/aws/aws-sdk-cpp/issues/301), but it hasn't really helped and seems like a dead thread (he's dead, Jim!).

As best as I can tell, it looks like we need is a json file for our custom API gateway to put in the code-generation/api-descriptions/ folder for building the SDK (and I'm guessing I'd also need to add "apigateway" to my BUILD_ONLY target list.

So far, we've been unable to find a definition or documentation for the json format of these files in api-descriptions. We know how to generate a swagger definition file, but without documentation for these api-descriptions files, we're having trouble figuring out how we could even attempt to manually convert/create one of these for our API.

Can anybody point us in a direction of some docs or definition for whatever this api-descriptions format is and how to use it?

Thanks!

### What platform/OS are you using?
Windows/64-bit (no .NET, raw C++)

### What compiler are you using? what version?
Visual Studio 2015

### What's your CMake arguments?
-DBUILD_ONLY="s3;transfer" -DTARGET_ARCH="WINDOWS" -DBUILD_SHARED_LIBS=OFF -DFORCE_SHARED_CRT=OFF -DMSVC=1 -G "Visual Studio 14 2015 Win64"

### Can you provide a TRACE level log? (sanitize any sensitive information)
N/A

**Comment by wps132230** [comment]
Duplicated
