### ISSUE TITLE
SQS - Message Attributes

### ISSUE THREAD

**Issue by patilarpith** [aws/aws-sdk-cpp#83]
Unable to fetch ```SentTimestamp``` message attribute.

ReceiveMessageRequest class functions like GetAttributeNames() & SetAttributeNames() deals with QueueAttributeName. 

How to set ReceiveMessageRequest to also fetch SentTimestamp during a ReceiveMessage() request?

**Comment by patilarpith** [comment]
@JonathanHenson Could you please take a look at this?

**Comment by JonathanHenson** [comment]
I think you need GetMessageAttributes() and SetMessageAttributes()

**Comment by patilarpith** [comment]
@JonathanHenson Here is my confusion

SQS: Message.h has method
```text
inline const Aws::Map<QueueAttributeName, Aws::String>& GetAttributes()
```

Here is the description of this method
```xml
<p><code>SenderId</code>, <code>SentTimestamp</code>, <code>ApproximateReceiveCount</code>, and/or <code>ApproximateFirstReceiveTimestamp</code>. <code>SentTimestamp</code> and <code>ApproximateFirstReceiveTimestamp</code> are each returned as an integer representing the <a href="http://en.wikipedia.org/wiki/Unix_time">epoch time</a> in milliseconds.</p>
```

This is the QueueAttributeName enum 
```cpp
  enum class QueueAttributeName
  {
    NOT_SET,
    Policy,
    VisibilityTimeout,
    MaximumMessageSize,
    MessageRetentionPeriod,
    ApproximateNumberOfMessages,
    ApproximateNumberOfMessagesNotVisible,
    CreatedTimestamp,
    LastModifiedTimestamp,
    QueueArn,
    ApproximateNumberOfMessagesDelayed,
    DelaySeconds,
    ReceiveMessageWaitTimeSeconds,
    RedrivePolicy
  };
```

It looks like SetMessageAttributeNames() of ReceiveMessageRequest class deals with custom message attributes that can be added to SQS Messages.

It is still unclear how to fetch ```SentTimestamp``` attribute along with the SQS Message

**Comment by JonathanHenson** [comment]
I think the documentation is probably wrong. Try setting SentTimestamp on message attributes and Getting it back out of the message attributes. I'll check around here today to confirm.

**Comment by patilarpith** [comment]
Yes that would be one solution but I don't have access to the en-queuing service. Thanks for the assistance.

**Comment by JonathanHenson** [comment]
I'm slightly confused. Did that work? Is your issue resolved?

**Comment by patilarpith** [comment]
No it didn't solve my problem but what you suggested is a possible work-around. If I had access to the en-queuing service then I could have went ahead with this solution

**Comment by JonathanHenson** [comment]
What type of access do you need? Do you know how to use the sdk to do this?
Are you referring to documentation? Or support with the internal aws team?

Is there some way I can help? If this solves your problem, I will notify
the relevant teams that their documentation is out of date.

**Comment by patilarpith** [comment]
We use SQS internally for processing a bunch of jobs asynchronously. What I meant by not having access to the en-queuing service is that; I don't have access to the service that en-queues the jobs to be processed. 

I want to understand how to fetch SentTimestamp on the de-queuing end using aws cpp sdk. Up until now I used to do this using the SQS REST API

**Comment by JonathanHenson** [comment]
Im assuming you mean "Http" api since SQS isn't restful. Are you certain
you were pulling this out of Attributes and not MessageAttributes? If so,
we can work on fixing this for you ASAP. I need to confirm the behavior
with the SQS team, but the update to the enum is very straight forward
(it's just an update to the json model for the service).

**Comment by patilarpith** [comment]
Yes I can confirm this. Here is a piece of code from (forked and then self maintained) library which does sqs_get_message() over HTTP API
![screenshot from 2016-02-02 15 27 09](https://cloud.githubusercontent.com/assets/1260939/12745914/ea3441aa-c9c1-11e5-8f06-1919f64a3832.png)

**Comment by patilarpith** [comment]
Checking in on this

**Comment by patilarpith** [comment]
@JonathanHenson Did you get a chance to look at this?

**Comment by Bu11etmagnet** [comment]
Currently there is no enum value named SentTimestamp. I did a

`$ find aws-cpp-sdk-* -name *.h | xargs grep -wn SentTimestamp`

and every hit was from a comment, in `sqs/model/ReceiveMessageRequest.h` or `sqs/model/Message.h`

I think using QueueAttributeName for ReceiveMessage is wrong. There should be a separate enum, because the set of attributes that can be requested from ReceiveMessage is different from the set of attributes used by GetQueueAttributes/SetQueueAttributes.

Alternatively, the extra attributes could be added to QueueAttributeName (but the name would be misleading).

**Comment by prestomation** [comment]
Hi,
Message Attributes don't seem to be modeled.

I think this will work but I have not tested.
When you received the message:
receiveMessageRequest.AddMessageAttributeNames("SentTimestamp");
//Now send your request and retrieve your result.
auto sentTimeStamp = receiveMessageResult.GetMessages()[0].GetMessageAttributes()["SentTimestamp]";

The SQS integration tests send and later read some custom message attributes here: https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-sqs-integration-tests/QueueOperationTest.cpp#L259

**Comment by patilarpith** [comment]
@prestomation 
What you are suggesting works as a stop gap solution. SentTimestamp can be added to the message as a custom attribute by the sender and the same can be read at the receiver end. Overhead here would be that every sender has to start adding this custom attribute.

But there is no need to do this as the SQS receive message API already provides dictionary of attributes that SQS keeps about the message.
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html

**Comment by prestomation** [comment]
@patilarpith

This is the same way you retrieve SQS-generated SentTimestamp with the other SDKs as well. Message Attributes is NOT modeled as an enum because the possible input set is the union of both the built-in message attributes as well as your own custom attribute. I did not specify you need to add this on the sending side, you simply need to ask for it on the receiving side.

**Comment by patilarpith** [comment]
That information helps.

So this is what I tried.

SQS get message routine:
```cpp
int sqs_get_message(const string queue_url, SQSMessage &m_object)
{
    if (queue_url.empty()) { return 3; }

    SQS::Model::ReceiveMessageRequest Request;
    Request.SetMaxNumberOfMessages(1);
    Request.AddMessageAttributeNames("All");
    Request.SetQueueUrl(queue_url.c_str());

    SQS::Model::ReceiveMessageOutcome Response = AwsSQSClient->ReceiveMessage(Request);

    int status;
    if (Response.IsSuccess())
    {
        status = 0;
        SQS::Model::ReceiveMessageResult ResponseResult = Response.GetResult();
        if (ResponseResult.GetMessages().size() > 0)
        {
            SQS::Model::Message FetchedMessage = ResponseResult.GetMessages()[0];

            m_object.Body = FetchedMessage.GetBody();
            m_object.ReceiptHandle = FetchedMessage.GetReceiptHandle();
            m_object.MessageId = FetchedMessage.GetMessageId();
            m_object.MD5OfBody = FetchedMessage.GetMD5OfBody();
            m_object.RequestId = ResponseResult.GetResponseMetadata().GetRequestId();

            auto MessageAttribute = FetchedMessage.GetMessageAttributes();
            
            // Debug log
            cout << "sqs_get_message :: MessageAttributes size : " << MessageAttribute.size() << endl;
            for(auto attr:MessageAttribute)
                cout << attr.first << endl;

            if (MessageAttribute.find("SentTimestamp") != MessageAttribute.end())
                m_object.SentTimestamp = MessageAttribute["SentTimestamp"].GetStringValue();
        }
    }
    else
    {
        status = 2;

        auto ErrorResponse = Response.GetError();
        m_object.Type = ErrorResponse.GetExceptionName();
        m_object.Message = ErrorResponse.GetMessage();
        m_object.RequestId = Response.GetResult().GetResponseMetadata().GetRequestId();
    }

    return status;
}
```

Log from my unit test:
```text
@SQS_Put_Message[:Message]:=	SQSImplementationTest-0
OK : SQS_Put_Message
sqs_get_message :: MessageAttributes size : 0
OK : SQS_Get_Message
	@SQS_Get_Message[:Body]:=	SQSImplementationTest-0
	@SQS_Get_Message[:ReceiptHandle]:=	AQEBFk2q7JeRGAT1swg+PULqWjpQO9tyDioy0XiDf0YeSCKXFNkmgZmRyY1Zabx5AS90dIHlGMlU2ApBk357nMKM7l0vRvHUWakncVX6rqWth1H1+aT01kysbI19FuMsl+YERP+a+eL3JVnwr99vQ4OY532UR3GDqLsXJfQUrs9Ma3vd7zFbHwzxB9askqyCqi8jWGmoO/l9yVgc/q/XBgOxLyU2cwfESK6ZYFJyHJTIbccGQL9SdfyXBqMRAVGe476xen3sSn2lg8pln0q8zpS9+2Wo0qqKHzCzh0d/W2gyHU1/d4NmUnxF0MQBtJoo6VwAwnv4TGNbYrq3ovMKM98dgvsgpmpSKh1Dz+t/jcrR97tnUdVVN8L4q30rM4tXsq4L
	@SQS_Get_Message[:MessageId]:=	f40edd8d-feb0-4a91-a18f-9f1d8293d119
	@SQS_Get_Message[:MD5OfBody]:=	16468b12f98ff76bc894a990f0994ba3
	@SQS_Get_Message[:RequestId]:=	3013e38f-f29d-5f56-a2b2-ac12e38f6035
	@SQS_Get_Message[:Type]:=
	@SQS_Get_Message[:Message]:=
	@SQS_Get_Message[:SentTimestamp]:=
OK : SQS_Delete_Message
SQS - Tests complete
```

Still unable to fetch SentTimestamp.

Build information:
SDK 0.10.9 release
Ubuntu 14.04

**Comment by JonathanHenson** [comment]
https://github.com/aws/aws-sdk-cpp/commit/c00923192cc55a640394b8eebf08b0bb6c3a9a30

We added "SentTimestamp", to QueueAttributeName. You are correct above when you say, "I think using QueueAttributeName for ReceiveMessage is wrong. There should be a separate enum, because the set of attributes that can be requested from ReceiveMessage is different from the set of attributes used by GetQueueAttributes/SetQueueAttributes." The problem is that ship has sailed and it would be a breaking change for other SDKs since this enum has been modeled for a while and other SDKs are using it. This is the next best solution I can come up with.

**Comment by Bu11etmagnet** [comment]
@JonathanHenson hindsight is such a wonderful thing, isn't it :)

**Comment by patilarpith** [comment]
@JonathanHenson Thank you

**Comment by ram4031** [comment]
Trying to retrieve messageattributes from aws queue but it doesn't return messageattributes. can anyone help me with this issue. whats wrong with the request?

Request:
    https://sqs.us-east-2.amazonaws.com/123456789012/MyQueue/
    ?Action=ReceiveMessage
    &MaxNumberOfMessages=5
    &VisibilityTimeout=15
    &AttributeName=All
    &MessageAttributeName=All
    &Expires=2020-04-18T22%3A52%3A43PST
    &Version=2012-11-05
    &AUTHPARAMS
Response:
<ReceiveMessageResponse>
  <ReceiveMessageResult>
    <Message>
      <MessageId>5fea7756-0ea4-451a-a703-a558b933e274</MessageId>
      <ReceiptHandle>
        MbZj6wDWli+JvwwJaBV+3dcjk2YW2vA3+STFFljTM8tJJg6HRG6PYSasuWXPJB+Cw
        Lj1FjgXUv1uSj1gUPAWV66FU/WeR4mq2OKpEGYWbnLmpRCJVAyeMjeU5ZBdtcQ+QE
        auMZc8ZRv37sIW2iJKq3M9MFx1YvV11A2x/KSbkJ0=
      </ReceiptHandle>
      <MD5OfBody>fafb00f5732ab283681e124bf8747ed1</MD5OfBody>
      <Body>This is a test message</Body>
      <Attribute>
        <Name>SenderId</Name>
        <Value>195004372649</Value>
      </Attribute>
      <Attribute>
        <Name>SentTimestamp</Name>
        <Value>1238099229000</Value>
      </Attribute>
      <Attribute>
        <Name>ApproximateReceiveCount</Name>
        <Value>5</Value>
      </Attribute>
      <Attribute>
        <Name>ApproximateFirstReceiveTimestamp</Name>
        <Value>1250700979248</Value>
      </Attribute>
    </Message>
  </ReceiveMessageResult>
  <ResponseMetadata>
    <RequestId>b6633655-283d-45b4-aee4-4e84e0ae6afa</RequestId>
  </ResponseMetadata>
</ReceiveMessageResponse>
