### ISSUE TITLE
AWSSDKConfig.cmake fails to find static libraries on Windows

### ISSUE THREAD

**Issue by tdenniston** [aws/aws-sdk-cpp#831]
Hello,

On Windows platforms, the `AWSSDKConfig.cmake` file installed with the SDK will not locate the binaries if the SDK was build with `-DBUILD_SHARED_LIBS=OFF`. I believe this is due to the following check in `AWSSDKConfig.cmake`:

```
# on Windows or Win64 dlls are treated as runtime target and installed in bindir
if (WIN32)
    set(AWSSDK_INSTALL_LIBDIR "${AWSSDK_INSTALL_BINDIR}")
endif()
```

This unconditionally sets the lib search directory to `bin` by default, which is not correct in the case where the shared libraries were not built.

### What platform/OS are you using?

Windows 10

### What compiler are you using? what version?

MSVC 19.12.25835.0 (VS2017 community edition)

### What are your CMake arguments?

`-DBUILD_SHARED_LIBS=OFF -DBUILD_ONLY=s3;core`

### Additional info

Here's the cmake output when using `find_package(AWSSDK CONFIG)`:

```
  -- TARGET_ARCH not specified; inferring host OS to be platform compilation target
  -- Building AWS libraries as static objects
  -- Generating windows build config
  -- Building project version: 1.2.0
  CMake Error at build/externals/install/lib/cmake/AWSSDK/AWSSDKConfig.cmake:125 (message):
    AWS SDK for C++ headers found, but we were unable to locate the binaries.
    Have you deleted or moved it?

                Please make sure header files and binaries are located in INSTALL_ROOT_DIR/INCLUDE_DIR/ and INST_DIR/LIB_DIR/[PLATFORM_PREFIX]/[Debug|Config|OtherConfigs]
```

**Comment by tdenniston** [comment]
A workaround for me is to build the SDK with `-DCMAKE_INSTALL_BINDIR=lib`.

**Comment by singku** [comment]
Thank you for reporting this. Will get it fixed ASAP.

**Comment by singku** [comment]
@tdenniston This bug should have been fixed, please take look at
https://github.com/aws/aws-sdk-cpp/blob/13720f04d54e315ff1162a953b4f290493ab2c27/cmake/AWSSDKConfig.cmake#L61

Reopen if you still have this problem.
