### ISSUE TITLE
CMake failed to create Out-of-Source Build

### ISSUE THREAD

**Issue by parsley72** [aws/aws-sdk-cpp#833]
I used the tag 1.4.26 and tried:
```
cd BUILD_DIR
cmake <path-to-root-of-this-source-code>

```
but I just get:
```
-- Building for: Visual Studio 12 2013
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.10.2.windows.1")
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating windows build config
-- Building project version: gold/57.3.20_Chunky
CMake Error at CMakeLists.txt:107 (project):
  VERSION "gold/57.3.20_Chunky" format invalid.

-- Configuring incomplete, errors occurred!

```
### What platform/OS are you using?
Win7

### What compiler are you using? what version?
Visual Studio 2013

**Comment by singku** [comment]
Any idea what "gold/57.3.20_Chunky" is?

**Comment by parsley72** [comment]
Nope.

**Comment by JonathanHenson** [comment]
It’s the output of git describe, which means the SDK is nested inside another repo, this is its tag output.

**Comment by singku** [comment]
If that's the case as Jonathan said, we have a customer PR to fix this. Will merge it ASAP
https://github.com/aws/aws-sdk-cpp/pull/425#issuecomment-377697140
