### ISSUE TITLE
TransferManager: any plans for supporting resumable download (across sessions)?

### ISSUE THREAD

**Issue by mattman71** [aws/aws-sdk-cpp#835]
Are there any plans for TransferManager (or any other part of the S3 library) to support resumable downloads?

I don't mean pause/resume in same session, I mean for the case that a (multi-part) download is in progress... network or power outage happens... then a new session later comes along requesting to download the same resource (for which there is still a partial download file stored locally). If I have 3.9GB of a 4.0GB file stored locally before an outage, it hurts pretty bad to start back at byte 0.

**Comment by singku** [comment]
To be clear, do you want to do a in process resume or resume after restart of your service? The later one would be tedious since you'll have to maintain the download status in a file.

**Comment by mattman71** [comment]
I suppose I'm talking about a restart scenario -- that's what I tried to describe with not in the same session; there would be no in-memory state persistence.

**Comment by singku** [comment]
I think that is a very interesting feature request, and I appreciate you sharing your suggestion. We regularly review suggestions like these to help prioritize what features we add to the SDK. But currently there are no plans to expand the S3 transfer manager with resumable downloads.
