### ISSUE TITLE
CMake fails to build application

### ISSUE THREAD

**Issue by Fyntasia** [aws/aws-sdk-cpp#838]
### What platform/OS are you using?
RHEL 7.4 on Amazon t2.medium server

### What compiler are you using? what version?
GCC 7.3.0
CMake 3.11.0

### What's your CMake arguments?
-Daws-sdk-cpp_DIR= /path/to/sdk_build

### Can you provide a TRACE level log? (sanitize any sensitive information)

CMakeFiles/ec-test.dir/main.cpp.o: In function `Aws::AmazonSerializableWebServiceRequest::~AmazonSerializableWebServiceRequest()':
main.cpp:(.text._ZN3Aws35AmazonSerializableWebServiceRequestD2Ev[_ZN3Aws35AmazonSerializableWebServiceRequestD5Ev]+0x13): undefined reference to `vtable for Aws::AmazonSerializableWebServiceRequest'
CMakeFiles/ec-test.dir/main.cpp.o: In function `Aws::S3::S3Request::GetHeaders() const':
main.cpp:(.text._ZNK3Aws2S39S3Request10GetHeadersEv[_ZNK3Aws2S39S3Request10GetHeadersEv]+0x76): undefined reference to `Aws::Http::CONTENT_TYPE_HEADER'
main.cpp:(.text._ZNK3Aws2S39S3Request10GetHeadersEv[_ZNK3Aws2S39S3Request10GetHeadersEv]+0xeb): undefined reference to `Aws::Http::CONTENT_TYPE_HEADER'
CMakeFiles/ec-test.dir/main.cpp.o: In function `Aws::S3::Model::GetObjectResult::~GetObjectResult()':
main.cpp:(.text._ZN3Aws2S35Model15GetObjectResultD2Ev[_ZN3Aws2S35Model15GetObjectResultD5Ev]+0x142): undefined reference to `Aws::Utils::Stream::ResponseStream::~ResponseStream()'
CMakeFiles/ec-test.dir/main.cpp.o: In function `S3Connection::get(std::basic_string<char, std::char_traits<char>, Aws::Allocator<char> >)':
main.cpp:(.text._ZN12S3Connection3getESbIcSt11char_traitsIcEN3Aws9AllocatorIcEEE[_ZN12S3Connection3getESbIcSt11char_traitsIcEN3Aws9AllocatorIcEEE]+0x2f): undefined reference to `Aws::InitAPI(Aws::SDKOptions const&)'
main.cpp:(.text._ZN12S3Connection3getESbIcSt11char_traitsIcEN3Aws9AllocatorIcEEE[_ZN12S3Connection3getESbIcSt11char_traitsIcEN3Aws9AllocatorIcEEE]+0x3e): undefined reference to `Aws::Client::ClientConfiguration::ClientConfiguration()'
main.cpp:(.text._ZN12S3Connection3getESbIcSt11char_traitsIcEN3Aws9AllocatorIcEEE[_ZN12S3Connection3getESbIcSt11char_traitsIcEN3Aws9AllocatorIcEEE]+0x5e): undefined reference to `Aws::S3::S3Client::S3Client(Aws::Client::ClientConfiguration const&, Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy, bool)'
main.cpp:(.text._ZN12S3Connection3getESbIcSt11char_traitsIcEN3Aws9AllocatorIcEEE[_ZN12S3Connection3getESbIcSt11char_traitsIcEN3Aws9AllocatorIcEEE]+0x7c): undefined reference to `Aws::S3::Model::GetObjectRequest::GetObjectRequest()'
main.cpp:(.text._ZN12S3Connection3getESbIcSt11char_traitsIcEN3Aws9AllocatorIcEEE[_ZN12S3Connection3getESbIcSt11char_traitsIcEN3Aws9AllocatorIcEEE]+0xc2): undefined reference to `Aws::S3::S3Client::GetObject(Aws::S3::Model::GetObjectRequest const&) const'
main.cpp:(.text._ZN12S3Connection3getESbIcSt11char_traitsIcEN3Aws9AllocatorIcEEE[_ZN12S3Connection3getESbIcSt11char_traitsIcEN3Aws9AllocatorIcEEE]+0x20f): undefined reference to `Aws::ShutdownAPI(Aws::SDKOptions const&)'
main.cpp:(.text._ZN12S3Connection3getESbIcSt11char_traitsIcEN3Aws9AllocatorIcEEE[_ZN12S3Connection3getESbIcSt11char_traitsIcEN3Aws9AllocatorIcEEE]+0x23c): undefined reference to `Aws::S3::S3Client::~S3Client()'
main.cpp:(.text._ZN12S3Connection3getESbIcSt11char_traitsIcEN3Aws9AllocatorIcEEE[_ZN12S3Connection3getESbIcSt11char_traitsIcEN3Aws9AllocatorIcEEE]+0x2b2): undefined reference to `Aws::S3::S3Client::~S3Client()'
CMakeFiles/ec-test.dir/main.cpp.o: In function `Aws::Allocator<char>::deallocate(char*, unsigned long)':
main.cpp:(.text._ZN3Aws9AllocatorIcE10deallocateEPcm[_ZN3Aws9AllocatorIcE10deallocateEPcm]+0x1c): undefined reference to `Aws::Free(void*)'
CMakeFiles/ec-test.dir/main.cpp.o: In function `Aws::Allocator<char>::allocate(unsigned long, void const*)':
main.cpp:(.text._ZN3Aws9AllocatorIcE8allocateEmPKv[_ZN3Aws9AllocatorIcE8allocateEmPKv]+0x21): undefined reference to `Aws::Malloc(char const*, unsigned long)'
CMakeFiles/ec-test.dir/main.cpp.o: In function `Aws::Allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > const, std::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > > > >::deallocate(std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > const, std::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > > >*, unsigned long)':
main.cpp:(.text._ZN3Aws9AllocatorISt13_Rb_tree_nodeISt4pairIKSbIcSt11char_traitsIcENS0_IcEEES6_EEE10deallocateEPS9_m[_ZN3Aws9AllocatorISt13_Rb_tree_nodeISt4pairIKSbIcSt11char_traitsIcENS0_IcEEES6_EEE10deallocateEPS9_m]+0x1c): undefined reference to `Aws::Free(void*)'
CMakeFiles/ec-test.dir/main.cpp.o: In function `Aws::Allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > const, std::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > > > >::allocate(unsigned long, void const*)':
main.cpp:(.text._ZN3Aws9AllocatorISt13_Rb_tree_nodeISt4pairIKSbIcSt11char_traitsIcENS0_IcEEES6_EEE8allocateEmPKv[_ZN3Aws9AllocatorISt13_Rb_tree_nodeISt4pairIKSbIcSt11char_traitsIcENS0_IcEEES6_EEE8allocateEmPKv]+0x2e): undefined reference to `Aws::Malloc(char const*, unsigned long)'
CMakeFiles/ec-test.dir/main.cpp.o:(.rodata._ZTVN3Aws2S39S3RequestE[_ZTVN3Aws2S39S3RequestE]+0x20): undefined reference to `Aws::AmazonSerializableWebServiceRequest::GetBody() const'
CMakeFiles/ec-test.dir/main.cpp.o:(.rodata._ZTIN3Aws2S39S3RequestE[_ZTIN3Aws2S39S3RequestE]+0x10): undefined reference to `typeinfo for Aws::AmazonSerializableWebServiceRequest'
CMakeFiles/ec-test.dir/main.cpp.o: In function `Aws::S3::Model::GetObjectRequest::~GetObjectRequest()':
main.cpp:(.text._ZN3Aws2S35Model16GetObjectRequestD2Ev[_ZN3Aws2S35Model16GetObjectRequestD5Ev]+0x13): undefined reference to `vtable for Aws::S3::Model::GetObjectRequest'
collect2: error: ld returned 1 exit status
make[2]: *** [ec-test] Error 1
make[1]: *** [CMakeFiles/ec-test.dir/all] Error 2
make: *** [all] Error 2

**Comment by singku** [comment]
Hello, thanks for reporting this. Looks like this is a link time error and linker either can't find AWS SDK libraries or didn't link against AWS SDK libraries. If possible, would you please show us your complete CMake scripts? Based on your CMake argument, you are using the outdated way to link against AWS SDK for CPP. I'd suggest to follow example [here](https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/cpp/example_code/s3encryption/CMakeLists.txt), which gives you a much easier way to build applications against AWS SDK for CPP.

**Comment by Fyntasia** [comment]
I've created a new CMake file, it gets passed the compilation! Victory!

Only now I've ran into a "Segmentation fault" when instantiating the AWS::S3::S3Client.

**Comment by singku** [comment]
Would you mind show us a minimal code snippet you used to compile? The segmentation fault maybe caused by multiple reasons.

**Comment by Fyntasia** [comment]
main.ccp:

    #include "s3connection.cpp"

    int main(int argc, char** argv)
    {
        S3Connection::get("folder/filename.xml");

        return 0;
    }
s3connection.ccp:

    #include <aws/core/Aws.h>
    #include <aws/s3/S3Client.h>
    #include <aws/s3/model/GetObjectRequest.h>
    #include <fstream>
    
    using namespace std;
    
    class S3Connection {
    public:
        static void get(Aws::String key) {
            Aws::SDKOptions options;
            Aws::InitAPI(options);
    
            const Aws::String bucket_name = "my-bucket";
            const Aws::String key_name = key;
    
            cout << "Downloading " << key_name << " from S3 bucket: " << bucket_name << endl;

            Aws::S3::S3Client s3_client;

            Aws::S3::Model::GetObjectRequest object_request;
            object_request.WithBucket(bucket_name).WithKey(key_name);

            auto get_object_outcome = s3_client.GetObject(object_request);

            if (get_object_outcome.IsSuccess())
            {
                Aws::OFStream local_file;
                local_file.open(key_name.c_str(), ios::out | ios::binary);
                local_file << get_object_outcome.GetResult().GetBody().rdbuf();
                cout << "Done!" << endl;
            }
            else
            {
                cout << "GetObject error: " <<
                          get_object_outcome.GetError().GetExceptionName() << " " <<
                          get_object_outcome.GetError().GetMessage() << endl;
            }
    
    
            Aws::ShutdownAPI(options);
        }
    };
CMakeLists.txt

    cmake_minimum_required(VERSION 3.11)
    set(CMAKE_CXX_STANDARD 11)
    project(ec-test)
    
    find_package(aws-sdk-cpp)
    
    add_definitions(-DUSE_IMPORT_EXPORT)
    
    add_executable(ec-test main.cpp)
    target_link_libraries(ec-test aws-cpp-sdk-s3)

**Comment by singku** [comment]
The problem here is that your `get` function accept an Aws::String typed parameter, but only inside this function you call Aws::InitAPI().

You should use std::string instead of Aws::String.

**Comment by Fyntasia** [comment]
I've changed the Aws::String to an std::string, the segmentation error persists.

    #include <aws/core/Aws.h>
    #include <aws/s3/S3Client.h>
    #include <aws/s3/model/GetObjectRequest.h>
    #include <fstream>
    
    using namespace std;
    
    class S3Connection {
    public:
        static void get(string key) {
            Aws::SDKOptions options;
            Aws::InitAPI(options);

            const Aws::String bucket_name = "my-bucket";
            const Aws::String key_name = key.data();

            cout << "Downloading " << key_name << " from S3 bucket: " << bucket_name << endl;

            Aws::S3::S3Client s3_client;

            Aws::S3::Model::GetObjectRequest object_request;
            object_request.WithBucket(bucket_name).WithKey(key_name);

            auto get_object_outcome = s3_client.GetObject(object_request);

            cout << "Start?" << endl;

            if (get_object_outcome.IsSuccess())
            {
                Aws::OFStream local_file;
                local_file.open(key_name.c_str(), ios::out | ios::binary);
                local_file << get_object_outcome.GetResult().GetBody().rdbuf();
                cout << "Done!" << endl;
            }
            else
            {
                cout << "GetObject error: " <<
                          get_object_outcome.GetError().GetExceptionName() << " " <<
                          get_object_outcome.GetError().GetMessage() << endl;
            }


            Aws::ShutdownAPI(options);
        }
    };

After running the app I get:
 
    Downloading folder/filename.xml from S3 bucket: my-bucket
    Segmentation fault

**Comment by singku** [comment]
```
#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>
#include <aws/s3/model/GetObjectRequest.h>
#include <fstream>

using namespace std;

class S3Connection {
public:
    static void get(string key) {
        Aws::SDKOptions options;
        Aws::InitAPI(options);
        {
            const Aws::String bucket_name = "my-bucket";
            const Aws::String key_name = key;
            cout << "Downloading " << key_name << " from S3 bucket: " << bucket_name << endl;
            Aws::S3::S3Client s3_client;
            Aws::S3::Model::GetObjectRequest object_request;
            object_request.WithBucket(bucket_name).WithKey(key_name);
            auto get_object_outcome = s3_client.GetObject(object_request);
            if (get_object_outcome.IsSuccess())
            {
                Aws::OFStream local_file;
                local_file.open(key_name.c_str(), ios::out | ios::binary);
                local_file << get_object_outcome.GetResult().GetBody().rdbuf();
                cout << "Done!" << endl;
            }
            else
            {
                cout << "GetObject error: " <<
                          get_object_outcome.GetError().GetExceptionName() << " " <<
                          get_object_outcome.GetError().GetMessage() << endl;
            }
        }
        Aws::ShutdownAPI(options);
    }
};
```

Can you please use this code instead?

**Comment by Fyntasia** [comment]
Segmentation error persist with the revised code.

**Comment by singku** [comment]
Hi I have tested this code piece (ROOT_DIR/src/test.cpp):
```
#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>
#include <aws/s3/model/GetObjectRequest.h>
#include <fstream>

using namespace std;

class S3Connection {
public:                                                                                                                                                                                                                                                                                                                                                                         
       static void get(std::string key) {

        Aws::SDKOptions options;
        Aws::InitAPI(options);
        {                                                                                                                                                                                                                                                                                                                                                                               
            const Aws::String bucket_name = "XXX_BUCKET_NAME";
            const Aws::String key_name = Aws::String(key.c_str());

            cout << "Downloading " << key_name << " from S3 bucket: " << bucket_name << endl;
                                                                                                                                                                                                                                                                                                                                                                                        
            Aws::S3::S3Client s3_client;

            Aws::S3::Model::GetObjectRequest object_request;
            object_request.WithBucket(bucket_name).WithKey(key_name);

            auto get_object_outcome = s3_client.GetObject(object_request);

            if (get_object_outcome.IsSuccess())
            {
                Aws::OFStream local_file;
                local_file.open(key_name.c_str(), ios::out | ios::binary);
                local_file << get_object_outcome.GetResult().GetBody().rdbuf();
                cout << "Done!" << endl;
            }
            else
            {
                cout << "GetObject error: " <<
                    get_object_outcome.GetError().GetExceptionName() << " " <<
                    get_object_outcome.GetError().GetMessage() << endl;
            }

        }
        Aws::ShutdownAPI(options);
    }
};

int main(int argc, char** argv)
{
    S3Connection::get("XXX_KEY_NAME");
    return 0;
}
```
With this CMake script (ROOT_DIR/CMakeLists.txt):
```
cmake_minimum_required(VERSION 3.2)
project(SDKTest)
SET(CMAKE_CXX_STANDARD 11)

# On Windows, AWSSDK_DIR should be provided to Cmake
if (WIN32)
    SET(AWSSDK_DIR "C:/Program Files/aws-cpp-sdk-all/lib/cmake/AWSSDK")
endif()
find_package(AWSSDK REQUIRED)

Message(STATUS "AWSSDK_LIB_DIR ${AWSSDK_LIB_DIR}")
Message(STATUS "AWSSDK_BIN_DIR ${AWSSDK_BIN_DIR}")                                                                                                                                                                                                                                                                                                                          Message(STATUS "AWSSDK_INCLUDE_DIR ${AWSSDK_INCLUDE_DIR}")

SET(SERVICE "s3")
AWSSDK_DETERMINE_LIBS_TO_LINK(SERVICE OUTPUT)
Message(STATUS "All linked libs: ${OUTPUT}")
if (APPLE)
    add_definitions(-DUNDER_MACOS)
endif()

link_directories("${AWSSDK_LIB_DIR}")
add_executable(SDKTest ../src/test.cpp)

if (WIN32)
    AWSSDK_CPY_DYN_LIBS(SERVICE "" ./)
endif()

Message(STATUS "AWSSDK_PLATFORM_DEPS ${AWSSDK_PLATFORM_DEPS}")
target_link_libraries(SDKTest ${OUTPUT})
target_include_directories(SDKTest PRIVATE ${AWSSDK_INCLUDE_DIR})
```

in ROOT_DIR/build/ dir:
```
cmake ../
make
```

Without segment fault and can download the target file correctly.

To better help diagnosing your segment fault. May I ask you couple of questions?

- What's the version of AWS SDK for CPP you used?
- How did you compile and install AWS SDK for CPP? Is it installed as static/shared library?
- Could you please attach a stack trace of your segment fault?

Thank you.

**Comment by Fyntasia** [comment]
- I'm using AWS SDK version 1.4.33

`

    -- TARGET_ARCH not specified; inferring host OS to be platform compilation target
    -- Building AWS libraries as static objects
    -- Generating linux build config
    -- Building project version: 1.4.33
    -- Found AWS SDK for C++, Version: 1.4.33, Install Root:/usr/local, Platform Prefix:, Platform Dependent Libraries: pthread;ssl;z;curl
    -- AWSSDK_LIB_DIR /usr/local/lib64/
    -- AWSSDK_BIN_DIR /usr/local/bin/
    -- AWSSDK_INCLUDE_DIR /usr/local/include
    -- All linked libs: aws-cpp-sdk-s3;aws-cpp-sdk-core
    -- AWSSDK_PLATFORM_DEPS pthread;ssl;z;curl
    -- Configuring done
    -- Generating done

`

- I've followed all the steps on the [official docs](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup.html) to install from source.
- gdb debug tells me:

`
     
     [Thread debugging using libthread_db enabled]
     Using host libthread_db library "/lib64/libthread_db.so.1".
     Downloading folder/filename.xml from S3 bucket: my-bucket

     Program received signal SIGSEGV, Segmentation fault.
     0x000000000040c553 in __gnu_cxx::__exchange_and_add(int volatile*, int) ()
`

**Comment by Fyntasia** [comment]
Have you guys found anything that could cause the Segmentation fault?

**Comment by singku** [comment]
@Fyntasia Do you still face this problem if you update to the latest？
