### ISSUE TITLE
S3 PutObject is successful with HTTP, but fails with 'Unable to connect to endpoint' on HTTPS

### ISSUE THREAD

**Issue by matthewpaul** [aws/aws-sdk-cpp#850]
### What platform/OS are you using?
Android 7.1.2

### What compiler are you using? what version?
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

### What's your CMake arguments?
cmake -DCMAKE_BUILD_TYPE=Release -DANDROID_STL=libc++_static -DBUILD_ONLY="s3" -DFORCE_SHARED_CRT=0 -DBUILD_SHARED_LIBS=0 -DTARGET_ARCH=ANDROID -DANDROID_ABI=arm64-v8a ~/git/aws-sdk-cpp/

### Can you provide a TRACE level log? (sanitize any sensitive information)
Unable to get any logs via adb logcat after attempting to initialize the AWS logs

Below is the function that I'm using to transmit to S3. As stated in the title, this configuration is able to transmit successfully to my bucket via HTTP, but when I try to use HTTPS, I get "Unable to connect to endpoint, with an empty exception name. Any ideas?

int start_transmit_S3(const char *file_path, const char *key_name) {
    // Init AWS Api
    Aws::SDKOptions options;
    Aws::InitAPI(options);

    // Configure bucket/client information
    Aws::Client::ClientConfiguration clientConfig;
    clientConfig.region = Aws::Region::US_EAST_1;
    clientConfig.scheme = Aws::Http::Scheme::HTTPS;
    clientConfig.connectTimeoutMs = 30000;
    clientConfig.requestTimeoutMs = 30000;
    Aws::String bucket_name = "************";
    
    //Aws::S3::S3Client s3_client(clientConfig);
    auto s3_client = Aws::MakeShared<Aws::S3::S3Client>(
        "alloc_tag", Aws::Auth::AWSCredentials("**************", "**************"), clientConfig);

    // Build metadata map to pass in email addresses that we need to send to
    Aws::Map<Aws::String, Aws::String> metadata;
    metadata.insert({"delivery_addresses", "*****************"});

    Aws::S3::Model::PutObjectRequest object_request;
    object_request.WithBucket(bucket_name).WithKey(key_name).WithMetadata(metadata);

    // Determine input file size
    std::ifstream file(file_path, std::ifstream::in | std::ifstream::binary);
    file.seekg(0, std::ios::end);
    int fileSize = file.tellg();
    file.close();
    
    object_request.SetContentLength(fileSize);

    // Binary files must also have the std::ios_base::bin flag or'ed in
    auto input_data = Aws::MakeShared<Aws::FStream>("PutObjectInputStream",
        file_path, std::ios_base::in | std::ios_base::binary);

    object_request.SetBody(input_data);

    auto put_object_outcome = s3_client->PutObject(object_request);

    int response = CMD_FAILURE;
    if (put_object_outcome.IsSuccess())
    {
        ALOGI("HUBD: matt Successfully transmitted data to S3!");
        response = CMD_SUCCESS;
    }
    else
    {
        ALOGE("HUBD: Failed to transmit data to S3 - PutObject error: %s, %s", 
            put_object_outcome.GetError().GetExceptionName().c_str(), 
            put_object_outcome.GetError().GetMessage().c_str());
        
    }
    Aws::ShutdownAPI(options);

    return response;
}

**Comment by KaibaLopez** [comment]
Hi @matthewpaul ,
Sorry for the lack of response on this issue, I'm trying to do a clean up of old issues and wanted to make sure, are you still facing this problem on newer versions of the sdk?
