### ISSUE TITLE
Way to ensure all PoolThreadExecutor tasks have finished?

### ISSUE THREAD

**Issue by mramato** [aws/aws-sdk-cpp#853]
It looks like the `Executor` class and sub-classes only expose the `Submit` function for queuing tasks, but provide no way to wait for all tasks to complete.  Here's a reduced test case:

```c++
int main(int argc, const char *argv[])
{
    Aws::SDKOptions sdkOptions;
    Aws::InitAPI(sdkOptions);

    auto executor = std::make_unique<Aws::Utils::Threading::PooledThreadExecutor>(256);

    for (int i = 0; i < 10000; i++)
    {
        executor->Submit([] {
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
            std::lock_guard<std::mutex> guard(progressMutex);
            counter++;
        });
    }

    // How to wait for executor tasks to finish?

    Aws::ShutdownAPI(sdkOptions);

    std::lock_guard<std::mutex> guard(progressMutex);
    std::cout << "Total: " << counter << std::endl;

    return 0;
}
```

While the above code is a reduced case, we were seeing a hang/segfault in our code that seems to involve the order in which threads were being cleaned up and joined by the AWS API.  Does the `PoolThreadExecutor` destructor wait for all threads to be joined before returning?  I was unable to find information about what guarantees it makes.  I know it cancels submitted but pending tasks, but what about tasks in flight?

Thanks.

**Comment by marcomagdy** [comment]
>Is the rule for Aws::ShutdownAPI that no other AWS objects should exist when it is called?

That's correct.

**Comment by mramato** [comment]
Thanks.
