### ISSUE TITLE
RunPipelineActivityRequest.cpp missing #include <aws/core/utils/HashingUtils.h>

### ISSUE THREAD

**Issue by nitrologic** [aws/aws-sdk-cpp#854]
### What platform/OS are you using?

Linux

### What compiler are you using? what version?

g++ 7.2.0

### What's your CMake arguments?

cmake ..

### Can you provide a TRACE level log? (sanitize any sensitive information)

No

As title says I was unable to build RunPipelineActivityRequest.cpp without adding a #include <aws/core/utils/HashingUtils.h>

**Comment by nitrologic** [comment]
Same issue for aws-cpp-sdk-iotanalytics/source/model/SampleChannelDataResult.cpp

**Comment by marcomagdy** [comment]
Thanks for reporting this. Will get that fixed right away

**Comment by marcomagdy** [comment]
Fixed in v1.4.40
