### ISSUE TITLE
Aws::Client::ClientConfiguration::ClientConfiguration(void)

### ISSUE THREAD

**Issue by mayovtester** [aws/aws-sdk-cpp#866]
### What platform/OS are you using?
Windows
### What compiler are you using? what version?
VS
### What's your CMake arguments?
-
### Can you provide a TRACE level log? (sanitize any sensitive information)
-

error LNK2019: unresolved external symbol "public: __thiscall Aws::Client::ClientConfiguration::ClientConfiguration(void)" (??0ClientConfiguration@Client@Aws@@QAE@XZ) referenced in function "public: __thiscall CppAmazonClient::CppAmazonClient(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0CppAmazonClient@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00@Z)

**Comment by singku** [comment]
Could you please give us a more detailed description of how did this happened?
