### ISSUE TITLE
Many of the C++ examples (of the few there are) are out of date and do not work

### ISSUE THREAD

**Issue by robertwhitcher** [aws/aws-sdk-cpp#867]
https://aws.amazon.com/blogs/aws/aws-sdk-for-c-now-ready-for-production-use/

The example used in this blog post need updating.  It no longer works for several reasons.  Not hard to figure out, but why make people spend the extra hours.  

### What platform/OS are you using?
N/A

### What compiler are you using? what version?
N/A

### What's your CMake arguments?
N/A

### Can you provide a TRACE level log? (sanitize any sensitive information)
N/A

**Comment by Bu11etmagnet** [comment]
For example, aws/transfer/TransferManager.h does not exist.
Jeff Barr should use his time machine and go back to September 2016 to fix the blog post.

**Comment by marcomagdy** [comment]
@robertwhitcher good point, I'll try to reach out and see how we can get the information updated.

@Bu11etmagnet `aws/transfer/TransferManager.h` does still exist. Not sure why you're saying that.

**Comment by Bu11etmagnet** [comment]
@marcomagdy Maybe because I only build a subset which doesn't include aws-cpp-sdk-transfer. Doh!
