### ISSUE TITLE
The 1.4.47 and 1.4.48 tags are the same commit

### ISSUE THREAD

**Issue by pcolby** [aws/aws-sdk-cpp#870]
Both tags reference commit 57fc5afd73006a70cfbaa0d727244af7ef64a8f4. Was that intended?

Cheers.

**Comment by marcomagdy** [comment]
Ops. It's fixed now.
`git pull --tags` to update your copy.

Thanks for reporting this.

**Comment by pcolby** [comment]
Thanks @marcomagdy, there's now a secondary issue with the nuget versioning... I'll create a separate issue for that.

Cheers.
