### ISSUE TITLE
Nuget versions don't match tag 1.4.48

### ISSUE THREAD

**Issue by pcolby** [aws/aws-sdk-cpp#872]
Most (all?) of the Nuget packages for the 1.4.48 tag state the version as 1.4.47, eg:

https://github.com/aws/aws-sdk-cpp/blob/1.4.48/aws-cpp-sdk-access-management/nuget/aws-cpp-sdk-access-management.autopkg#L16

Cheers

**Comment by wps132230** [comment]
Thank you for finding this issue and reporting it to us.

We've already fixed that in the latest version (for 1.4.49 tag)
https://github.com/aws/aws-sdk-cpp/blob/af2ad18eb34ed29f1496fc115ed04fb7c9ad3ce4/aws-cpp-sdk-access-management/nuget/aws-cpp-sdk-access-management.autopkg#L16

**Comment by michaelsbg** [comment]
Where are you seeing 1.4.49 versions? I can only see 1.4.34 on nuget.org and through visual studio.
