### ISSUE TITLE
Build Fails withUndefined symbols for architecture x86_64  MacOS HighSierra.

### ISSUE THREAD

**Issue by jghankins** [aws/aws-sdk-cpp#873]
### What platform/OS are you using?
MacOS 10.13.4
### What compiler are you using? what version?
Apple LLVM version 9.1.0 (clang-902.0.39.1)

### What's your CMake arguments?
 -DBUILD_ONLY="s3;sqs;sns;lambda;kinesis"

**Comment by wps132230** [comment]
Could you provide the error messages?

**Comment by marcomagdy** [comment]
Please provide the output from cmake and the output from your compiler. What are the undefined symbols?

**Comment by jghankins** [comment]
You can close this issue.  I've not been able to recreate the error.  It's building fine currently.
