### ISSUE TITLE
Failed to build S3 in a docker image

### ISSUE THREAD

**Issue by msalah80** [aws/aws-sdk-cpp#874]
Hi. I am using Ubuntu. I managed to clone the library, build it and use it. However, when I tried to replicate the steps in a dockerfile, it failed.

Here is the dockerfile:

----

FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y git
RUN apt-get update -y && apt-get install -y --no-install-recommends g++ make cmake pkg-config build-essential zlib1g-dev 
RUN apt-get update -y && apt-get install -y --no-install-recommends libcurl4-openssl-dev libssl-dev uuid-dev libpulse-dev libssl1.1
RUN git clone --recursive https://github.com/aws/aws-sdk-cpp
RUN mkdir aws-sdk-cpp/aws-cpp-sdk-core/build
WORKDIR aws-sdk-cpp/aws-cpp-sdk-core/build
RUN cmake -DBUILD_ONLY="core" /aws-sdk-cpp
RUN make
WORKDIR /
RUN mkdir aws-sdk-cpp/aws-cpp-sdk-s3/build
WORKDIR aws-sdk-cpp/aws-cpp-sdk-s3/build
RUN cmake -DBUILD_ONLY="s3" /aws-sdk-cpp
RUN make

---

I guess cloning and building the core worked, but building s3 failed. Here is what I got:

---

[ 91%] Building CXX object aws-cpp-sdk-s3-integration-tests/CMakeFiles/aws-cpp-sdk-s3-integration-tests.dir/BucketAndObjectOperationTest.cpp.o
In file included from /aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/ratelimiter/DefaultRateLimiter.h:21:0,
                 from /aws-sdk-cpp/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp:25:
/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSFunction.h:57:3: error: mangled name for 'F Aws::BuildFunction(F) [with F = std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > > (*)() noexcept]' will change in C++17 because the exception specification is part of a function type [-Werror=noexcept-type]
 F BuildFunction(F f)
   ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
aws-cpp-sdk-s3-integration-tests/CMakeFiles/aws-cpp-sdk-s3-integration-tests.dir/build.make:63: recipe for target 'aws-cpp-sdk-s3-integration-tests/CMakeFiles/aws-cpp-sdk-s3-integration-tests.dir/BucketAndObjectOperationTest.cpp.o' failed
CMakeFiles/Makefile2:284: recipe for target 'aws-cpp-sdk-s3-integration-tests/CMakeFiles/aws-cpp-sdk-s3-integration-tests.dir/all' failed
Makefile:129: recipe for target 'all' failed
make[2]: *** [aws-cpp-sdk-s3-integration-tests/CMakeFiles/aws-cpp-sdk-s3-integration-tests.dir/BucketAndObjectOperationTest.cpp.o] Error 1
make[1]: *** [aws-cpp-sdk-s3-integration-tests/CMakeFiles/aws-cpp-sdk-s3-integration-tests.dir/all] Error 2
make: *** [all] Error 2
The command '/bin/sh -c make' returned a non-zero code: 2

---

**Comment by singku** [comment]
Please either update to the latest version in which we have removed AwsFunction.h or see #620
