### ISSUE TITLE
TransferManager::RetryUpload() does not check for unexisting file.

### ISSUE THREAD

**Issue by mpsun** [aws/aws-sdk-cpp#883]
While `TransferManager::UploadFile()` appears to check for the existence of a file and returns a `FAILED` status immediately, a subsequent call to `TransferManager::RetryUpload()` does not appear to do this, and then the transfer incorrectly finishes with status `COMPLETED`. My expectation is that when attempting to upload a file that does not exist, the transfer should always end with status `FAILED`, no matter how many times `RetryUpload()` is called, if ever. This is using the overloads of `UploadFile()` and `RetryUpload()` that take the file path as a string. Please see comments inline in the code example below to see how this happens.

### Minimal code example that reproduces the issue
```cpp
using namespace Aws::S3;
using namespace Aws::Client;
using namespace Aws::Transfer;

std::string filename = "does-not-exist.zip";

std::string accessKeyId = "key";
std::string secretAccessKey = "secret";
std::string sessionToken = "token";
std::string bucketName = "bucket";
std::string region = "us-west-2";
std::string keyName = "keyname";

Aws::SDKOptions options;
Aws::InitAPI(options);

Aws::Auth::AWSCredentials credentials;
credentials.SetAWSAccessKeyId(accessKeyId);
credentials.SetAWSSecretKey(secretAccessKey);
credentials.SetSessionToken(sessionToken);

ClientConfiguration client_config;
client_config.region = region;
auto client = Aws::MakeShared<S3Client>("S3Client", credentials, client_config);

Aws::Utils::Threading::DefaultExecutor executor;
TransferManagerConfiguration config(&executor);
config.s3Client = client;
auto transfer_manager = TransferManager::Create(config);

// This is OK.
// UploadFile() checks for the existence of the file in CreateUploadFileHandle().
auto transfer_handle = transfer_manager->UploadFile(
    sourceFile,
    bucketName,
    keyName,
    "application/zip",
    Aws::Map<Aws::String, Aws::String>()); // no metadata

// Just wait, don't abort.
transfer_handle->WaitUntilFinished();

// OK, it failed.
printf("TRANSFER HANDLE STATUS: %d", transfer_handle->GetStatus()); // 4, FAILED. This is OK.

// This doesn't appear to check for the existence of the file.
transfer_handle = transfer_manager->RetryUpload(sourceFile, transfer_handle);
transfer_handle->WaitUntilFinished();

// And now it succeeds, even though the file (does-not-exist.txt) still doesn't exist.
printf("RETRY STATUS: %d", transfer_handle->GetStatus()); // 5, COMPLETED. But the file still doesn't exist.

Aws::ShutdownAPI(options);
```

### What platform/OS are you using?
Windows

### What compiler are you using? what version?
Visual Studio 2017 with v140 (2015) toolset.

### What's your CMake arguments?
Defaults except for:
- BUILD_SHARED_LIBS = false
- FORCE_SHARED_CRT = false

**Comment by marcomagdy** [comment]
Will look into it and have it fixed as soon as we can.
Thank you

**Comment by mpsun** [comment]
Awesome, thanks! I would pull some merge requests myself, but I am not yet fully acquainted with your SDK, so for now I'm just reporting what I can spot :)

**Comment by singku** [comment]
Hi this bug should have been fixed, https://github.com/aws/aws-sdk-cpp/commit/8082ace481931523a8ed8967f1cda163443dcee9

Reopen if you still face this problem
