### ISSUE TITLE
Does TransferManager guarantee integrity checking on S3 uploads?

### ISSUE THREAD

**Issue by riordanmr** [aws/aws-sdk-cpp#884]
When uploading to an S3 bucket, does Transfer Manager guarantee that the contents of the key match the contents of the original file?  With request signing, we know that each part of the file arrived at AWS intact (assuming a multi-part upload), but it's not clear to me whether the final POST that sends the CompleteMultipartUpload element to stitch the parts together is doing full file integrity checking.
Can anyone help?

**Comment by singku** [comment]
According to this doc:
https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadComplete.html
ETag part.
It seems S3 doesn't guarantee that.

**Comment by nikt12** [comment]
Hello,
So how could I know, when I am using UploadFile() call from TransferManager class that file is uploaded successfully?
How should I check integrity with this call?

**Comment by singku** [comment]
@nikt12 I believe we have already answered your question in #1155
