### ISSUE TITLE
Including C++ SDK in QTCreator for windows application

### ISSUE THREAD

**Issue by aminkatani** [aws/aws-sdk-cpp#885]
Hello, 

I'm developing a windows application in C++ using QT. 
As part of the application, I want the users to be able to upload and download documents using the S3 services. 
However, I have a problem when trying to compile the sdk out of source
I'm using MinGW make to compile them.
I generated a MinGW make file using cmake -G "MinGW" command in CMD. 

I get the following errors when I run the make command:
- in aws/core/utils/Array.h 'stdext' has not been declared
- in aws/core/utils/threading/semaphore.h 'mutex' in namespace 'std' does not name a type

### What platform/OS are you using?
Windows

### What compiler are you using? what version?
MinGW make

Best Regards, 
amin

**Comment by singku** [comment]
Please take a look at this issue  #45

**Comment by aminkatani** [comment]
@singku I have reviewed #45, I still have that issue
