### ISSUE TITLE
How to update metadata of existing object using HeadObject API?

### ISSUE THREAD

**Issue by sdjunaidali** [aws/aws-sdk-cpp#886]
**C++**

I am currently using PutObject API for updating metadata of object which is already present but PutObject is uploading the object every time and I have to **just** upload a metadata of object.

**How to use HeadObject API for the same?**

**Comment by marcomagdy** [comment]
You should use The [CopyObject API](http://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_s3_1_1_s3_client.html#a34971f0fd26331e14a97663f923e0210) instead.

See S3's CopyObject [documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html) for more details.

**Comment by sdjunaidali** [comment]
Hey Marco,

Thank you so much for so fast reply, Actually I wanted to try HeadObject API for metadata(User defined) update but it's confusing as metadata(User defined) body options (AddMetadata & SetMetadata) are provided in HeadObjectResult instead of HeadObjectRequest .

Can you please provide me an example (C++) for metadata update using HeadObject API? , It would be great help actually. Thanks in advance.

**Comment by marcomagdy** [comment]
HeadObject is for *reading* metadata. That's why it's in the result.
To update the metadata, you need to use CopyObject.
