### ISSUE TITLE
Large S3 library size (6.2mb)

### ISSUE THREAD

**Issue by leohahn** [aws/aws-sdk-cpp#888]
### What platform/OS are you using?
macOS 10.13.4

### What compiler are you using? what version?
Apple LLVM version 9.1.0 (clang902.0.39.1)

### What's your CMake arguments?
I am building the project with:
```
include(ExternalProject)

ExternalProject_Add(aws_sdk
    SOURCE_DIR ${CMAKE_SOURCE_DIR}/deps/aws-sdk-cpp
    DOWNLOAD_COMMAND ""
    BUILD_IN_SOURCE 0
    CMAKE_ARGS -DBUILD_ONLY=s3 -DBUILD_SHARED_LIBS=OFF -MINIMIZE_SIZE=ON -DENABLE_RTTI=OFF -ENABLE_UNITY_BUILD=ON -DCMAKE_BUILD_TYPE=Release -DTARGET_ARCH=APPLE
    BINARY_DIR ${CMAKE_BINARY_DIR}/deps/aws-sdk-cpp
    INSTALL_DIR ${CMAKE_BINARY_DIR}/deps/aws-sdk-cpp
    INSTALL_COMMAND ""
)
```

This compiles fine, however the library is 6.2Mb. Is this the normal size for the library?

**Comment by crusader-mike** [comment]
Here is some Linux info with GCC 6.2.0:

SDK v1.4.8

```
cmake -DCUSTOM_MEMORY_MANAGEMENT=0 -DBUILD_SHARED_LIBS=0 -DCMAKE_BUILD_TYPE=Release -DMINIMIZE_SIZE=1 -DBUILD_ONLY="core;s3" -DENABLE_TESTING=OFF -DCMAKE_INSTALL_LIBDIR=lib64 -DCMAKE_CXX_FLAGS="-ffunction-sections -fdata-sections" ~/aws-sdk-cpp
```

```
$ ls -lh /usr/local/lib64/libaws*
-rw-r--r--. 1 root root 2.0M Jan  3 18:29 /usr/local/lib64/libaws-cpp-sdk-core.a
-rw-r--r--. 1 root root 5.4M Jan  3 18:30 /usr/local/lib64/libaws-cpp-sdk-s3.a
```

**Comment by leohahn** [comment]
Thanks for the input.

**Comment by crusader-mike** [comment]
Note that even with `-ffunction-sections -fdata-sections` and static linking your main binary size will suffer because C++ compilers notoriously unable to detect if given virtual function is unused, thus pulling a lot (if not most) of code into final binary.
