### ISSUE TITLE
Segmentation fault when specifying custom RPATH for cmake

### ISSUE THREAD

**Issue by gsandeep1241** [aws/aws-sdk-cpp#889]
### What platform/OS are you using?

Distributor ID:	CentOS
Description:	CentOS Linux release 7.5.1804 (Core) 
Release:	7.5.1804

### What compiler are you using? what version?

./x86_64-unknown-linux-gnu-g++ --version
x86_64-unknown-linux-gnu-g++ (crosstool-NG 1.20.0) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

./x86_64-unknown-linux-gnu-gcc --version
x86_64-unknown-linux-gnu-gcc (crosstool-NG 1.20.0) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### What's your CMake arguments?

sudo cmake3 -DENABLE_TESTING=OFF 
            -DCMAKE_INSTALL_PREFIX:PATH="$CURR/local"        \
            -DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE    \
            -DCMAKE_INSTALL_RPATH="$CURR/lib;$CURR/local/lib;$CURR/aws/aws-sdk-cpp/testing-resources;$CURR/aws/aws-sdk-cpp/aws-cpp-sdk-core;$CURR/aws/aws-sdk-cpp/aws-cpp-sdk-s3"    \
            -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE   \
            -DCMAKE_C_COMPILER="$CC"       \
            -DCMAKE_CXX_COMPILER="$CXX"    \
            -DBUILD_ONLY="s3"    \
            -DOPENSSL_INCLUDE_DIR="$CURR/local/include"    \
            -DOPENSSL_CRYPTO_LIBRARY="$CURR/local/lib/libcrypto.so"       \
            -DOPENSSL_SSL_LIBRARY="$CURR/local/lib/libssl.so"     \
            -DCURL_INCLUDE_DIR="$CURR/local/include"    \
            -DCURL_LIBRARY="$CURR/local/lib/libcurl.so"  \
            -DZLIB_INCLUDE_DIR="$CURR/local/lib/include"      \
            -DZLIB_LIBRARY="$CURR/local/lib/libz.so"

###Description
In our project, we have a custom toolchain and we use all the libraries, compilers and any other dependencies which are part of this toolchain and not directly from the default system directories. 

For example, $CURR/lib,$CURR/local/lib etc. that are mentioned in the cmake command above contain the necessary dependencies such as libcrypto.so, libssl.so, gcc, g++ etc. 

Hence, we had to set the RPATH for the cmake command accordingly. 

Now, if I set the ENABLE_TESTING flag off, all the libraries are built and my sample code which uses these libraries works properly. But with the ENABLE_TESTING flag turned on, I get a segmentation fault during linking the aws-cpp-sdk-core-tests executable like so:

[ 97%] Building CXX object aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/utils/crypto/CryptoStreamsTest.cpp.o
[ 97%] Building CXX object aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/utils/crypto/SymmetricCiphersTest.cpp.o
[ 98%] Building CXX object aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/utils/json/JsonSerializerTest.cpp.o
[ 98%] Building CXX object aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/utils/stream/PreallocatedStreamBufTest.cpp.o
[ 98%] Building CXX object aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/utils/stream/SimpleStreamBufTest.cpp.o
[ 98%] Building CXX object aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/utils/xml/XmlSerializerTest.cpp.o
[ 99%] Building CXX object aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/utils/threading/DefaultExecutorTest.cpp.o
[ 99%] Building CXX object aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/utils/threading/ReaderWriterLockTest.cpp.o
[ 99%] Building CXX object aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/utils/memory/AWSMemoryTest.cpp.o
[ 99%] Building CXX object aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/utils/memory/SimpleStringStreamTests.cpp.o
[100%] Building CXX object aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/utils/logging/LoggingTest.cpp.o
[100%] Building CXX object aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/utils/ratelimiter/RateLimiterTests.cpp.o
[100%] Linking CXX executable aws-cpp-sdk-core-tests
/bin/sh: line 1: 19391 Segmentation fault      (core dumped) ./aws-cpp-sdk-core-tests
make[2]: *** [aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 139
make[2]: *** Deleting file `aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests'
make[1]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
make: *** [all] Error 2

Now, if I remove the RPATH flags, everything works fine again and all the tests pass. But the shared object files like libaws-sdk-s3.so link to the system level dependencies (like /lib64/libcrypto.so etc.)

What could be the reason for this?

**Comment by marcomagdy** [comment]
Have you tried running the tests manually when you set `ENABLE_TESTING=OFF`?

Couple things to help you debug the problem would be:
- run `ldd` on the executable to see which libraries dynamically links to, make sure all the libraries resolve to the correct paths you intended.
- set environment variable `LD_DEBUG=libs` and run the tests executable manually to see where the dynamic linker is loading your libraries from.
- run the tests executable with strace
