### ISSUE TITLE
Resuming incomplete multipart uploads after application restart through TransferManager 

### ISSUE THREAD

**Issue by SomeshDaga** [aws/aws-sdk-cpp#892]
### What platform/OS are you using?
Ubuntu 14.04
### What compiler are you using? what version?
gcc (v 4.8.5)
### What's your CMake arguments?
N/A
### Can you provide a TRACE level log? (sanitize any sensitive information)
N/A

Hi. I am trying to resume previously incomplete multipart uploads upon restart of my application. I was hoping to do this through the `TransferManager` class. However, it seems that this requires the passing of a shared_ptr for a `TransferHandle` object (in the `RetryUpload` function) that is created on the initial `UploadFile` call. If my application restarts, the transfer handle object is no longer in existence, which is the source of my issue.

While I believe a clearer solution exists through the use of the `S3Client` class by obtaining UploadIDs and keys for incomplete transfers, and retrieving completed parts and such, it seems much more painful to use. Is it possible to recreate the `TransferHandle` object to resume multipart uploads through the `TransferManager` class (given that the uploadID for the initial transfer is known)?

**Comment by singku** [comment]
Hi this is the same functional request as #835, please refer to that one. Close it now.
