### ISSUE TITLE
Possible race condition in ReaderWriterLock.cpp

### ISSUE THREAD

**Issue by cygnus9** [aws/aws-sdk-cpp#894]
https://github.com/aws/aws-sdk-cpp/blob/4c686e743e289205b8e4b0f48d472e09ecbd9941/aws-cpp-sdk-core/source/utils/threading/ReaderWriterLock.cpp#L43

I think this line contains a race condition because m_readers and m_holdouts aren't updated at the same time in ```ReaderWriterLock::LockWriter```. So ```m_readers``` could already be negative, but ```m_holdouts``` could still be 0, which will cause ```m_writerSem.Release()``` to not be called.

**Comment by singku** [comment]
Suppose we have **N** readers at the time of `m_readers.fetch_sub(MaxReaders)` inside `LockWriter`, now `current` equals to **N** and m_readers becomes **N - MaxReaders**, which is a small negative number. After that statement, no readers can actually go into reader mode, they will wait. Right now, those **N** readers can call UnlockReader() at most N times, doesn't matter if these calls are before or after we update `m_holdouts`. 

In an extreme situation, all of them call `UnlockReaders()` before we update `m_holdouts`, then `m_holdouts` will become **-N** and **YES** no readers will call `m_writerSem.Release()`, but eventually, we will update `m_holdouts`, at this extreme case, `holdouts` will be **-N**  + `current`, which is 0, and we will not call `WaitOne()`. 

In other cases, some readers will call `UnlockReaders()` after we update `m_holdouts`, in these cases, `m_holdouts` will be greater than **-N** before updating, after plus **N**, it will be positive, and `holdouts` will be positive as well. So we will go into WaitOne(). Those readers which call `UnlockReaders()` after we update `m_holdouts` will eventually call `Release()` in `UnlockReader()`

**Comment by cygnus9** [comment]
Thanks for clearing that up. That seems totally fine if you put it like that.
The thing that I'm really trying to figure out is why my application locks up in the destructor of a ```Semaphore```, which is called from the destructor of the ```ReaderWriterLock```, which is called from the destructor of the ```EnumParseOverflowContainer``` (sorry, I don't have a backtrace at hand) since I upgraded the SDK. And the use of the ```ReaderWriteLock``` in the ```EnumParseOverflowContainer``` happens to be introduced in this upgrade. So the ```ReaderWriterLock``` seems an obvious candidate for blaming.
The actual lockup happens in ```pthread_cond_destroy``` by the way.

Any idea what else could cause that?

**Comment by marcomagdy** [comment]
This might be a bug in the Semaphore class. We need to call notify_all() in the destructor.

**Comment by cygnus9** [comment]
That sounds a bit odd. There shouldn't be any waiters when a Semaphore gets destructed should there? I definitely don't see any waiting threads in my backtrace.

**Comment by marcomagdy** [comment]
I was suspecting the following might have caused the problem you're seeing.
From http://en.cppreference.com/w/cpp/thread/condition_variable/~condition_variable
>It is only safe to invoke the destructor if all threads have been notified.

Also, the documentation of [pthreads_cond_destroy](http://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_cond_destroy.html) says (emphasis mine):
>It shall be safe to destroy an initialized condition variable upon which no threads are currently blocked. **Attempting to destroy a condition variable upon which other threads are currently blocked results in undefined behavior**.

However, you're saying you don't see any waiting threads in your backtrace, so before going any further into debugging this, please provide the full backtrace (of all the threads, if any) of your application.

**Comment by cygnus9** [comment]
I actually suspected the same, but my stacktrace disproves that theory. I do have another theory. The thread that's locked is actually in the process of shutting down the sdk. However, the only other thread that's still running is a thread that polls credentials in the background, for another incarnation of the SDK. But it does use some components from this SDK. This background thread is actually sleeping, but who knows what it was doing a few cycles earlier. So perhaps we're just using it incorrectly and the new lock just breaks on this misuse. Unfortunately this thread is spawned on demand and only terminated at process exit, which seems to happen after we shutdown the sdk.

I think my employer doesn't like me to post a stacktrace here, but I'll get it to you some other way.

**Comment by marcomagdy** [comment]
>So perhaps we're just using it incorrectly

Yes you are.
>another incarnation of the SDK

There should be **ONE** incarnation of the SDK in any given process.
The shutdown call cleans up **static** variables., the static variables are global, not thread_local. That explains the strange behavior you're experiencing.

**Comment by cygnus9** [comment]
So this is indeed caused by our misuse of the API, which didn't cause any issues in the past.
Closing issue.
