### ISSUE TITLE
IdToken in place of AccessToken

### ISSUE THREAD

**Issue by Sunhick** [aws/aws-sdk-cpp#895]
What's the point in passing Idtoken as AccessToken for the LoginAccessTokens.  See https://github.com/aws/aws-sdk-cpp/issues/834

### What platform/OS are you using?
Macos

### What compiler are you using? what version?
gcc

**Comment by KaibaLopez** [comment]
Hi @Sunhick ,
Sorry for the late response, but I'm not sure what you mean by this question. In the issue, using the idToken as an Access Token is an implementation choice, not forced by the sdk. 
For more information on the differences between them and their intended purpose on Cognito refer to:
https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html

**Comment by Sunhick** [comment]
Spoke offline with @KaibaLopez. Needs documentation.
