### ISSUE TITLE
Slow GET requests and high CPU utilization

### ISSUE THREAD

**Issue by sectorsize512** [aws/aws-sdk-cpp#896]
I'm using aws-sdk-cpp to get objects from my local object storage connected via 10Gbit network. With wget and curl I can achieve ~1GB/Sec throughput. However, if I use aws-sdk-cpp's `s3_client->GetObject(object_request)` I get only about 100MB/Sec. At the same time CPU core where the process is running is 100% utilized. Any ideas on what's going on and how can I improve it?

### What platform/OS are you using?
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4.1708 (Core)

### What compiler are you using? what version?
$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)

### What's your CMake arguments?
cmake -DCMAKE_BUILD_TYPE=Release

### Can you provide a TRACE level log? (sanitize any sensitive information)
Not sure where to get this

**Comment by marcomagdy** [comment]
A couple of things to try:
- Use a new compiler (gcc 4.9.x) we use that in our integration tests and we don't have that problem.
- check if your compiler directives are leading you down to [this path ](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/include/aws/core/utils/memory/stl/AWSString.h#L65). In other words, check if `__ANDROID__` is defined and if `_GLIBCXX_FULLY_DYNAMIC_STRING == 0`

**Comment by singku** [comment]
I just tested on my Mac, 
```
Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64 x86_64
```
With program compiled by clang
```
Apple LLVM version 9.0.0 (clang-900.0.39.2)
```

tested GetObject against a 600MB file on S3, **Without** dumping the content from memory to local disk, the speed is about the same with wget. With IOStream dumping to local disk, the speed is 2.5 times slower than wget.

Remember that GetObject just do a single thread downloading. If your file is large, I recommend you to try TransferManager.

**Comment by sectorsize512** [comment]
@marcomagdy, @singku, thank you for your fast replies!

@singku:

1) I do not write the object to local storage, it stays in memory.

2) One might not see the difference between wget and aws-sdk-s3 in case of a real Amazon S3 because the network bandwidth between the client and the server is relatively low and the CPU bottleneck is not exposed. In my experiments I get 1GB/sec with wget and  about 100MB/sec in case of aws-sdk-s3. For Amazon S3 100MB/sec single-threaded throughput from the client to server is quite good, so the aws-sdk-s3's performance is sufficient. But in my case, the network connectivity is so high that it exposes aws-sdk-s3's issue, IMHO.

@marcomagdy:

1) I'll try a newer compiler later

2) I'm not sure I completely understood your second suggestion. I do not run android, it's just CentOS, so naturally __ANDROID__ is not defined. But  _GLIBCXX_FULLY_DYNAMIC_STRING seems to be set to 0:

```
$ grep -r GLIBCXX_FULLY_DYNAMIC_STRING /usr/include/
/usr/include/c++/5/bits/basic_string.tcc:#if _GLIBCXX_FULLY_DYNAMIC_STRING == 0
/usr/include/c++/5/bits/basic_string.tcc:#if _GLIBCXX_FULLY_DYNAMIC_STRING == 0
/usr/include/c++/5/bits/basic_string.tcc:#if _GLIBCXX_FULLY_DYNAMIC_STRING == 0
/usr/include/c++/5/bits/basic_string.tcc:#if _GLIBCXX_FULLY_DYNAMIC_STRING == 0
/usr/include/c++/5/bits/basic_string.h:#if _GLIBCXX_FULLY_DYNAMIC_STRING == 0
/usr/include/c++/5/bits/basic_string.h:#if _GLIBCXX_FULLY_DYNAMIC_STRING == 0
/usr/include/c++/5/bits/basic_string.h:#if _GLIBCXX_FULLY_DYNAMIC_STRING == 0
/usr/include/c++/5/bits/basic_string.h:#if _GLIBCXX_FULLY_DYNAMIC_STRING == 0
/usr/include/c++/5/bits/basic_string.h:#if _GLIBCXX_FULLY_DYNAMIC_STRING == 0
/usr/include/c++/5/bits/basic_string.h:#if _GLIBCXX_FULLY_DYNAMIC_STRING == 0
/usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h:#define _GLIBCXX_FULLY_DYNAMIC_STRING 0
$ grep -r ANDROID /usr/include/
/usr/include/nodejs/deps/v8/include/v8config.h:#if defined(__ANDROID__)
/usr/include/nodejs/deps/v8/include/v8config.h://  V8_OS_ANDROID       - Android
/usr/include/nodejs/deps/v8/include/v8config.h:#if defined(__ANDROID__)
/usr/include/nodejs/deps/v8/include/v8config.h:# define V8_OS_ANDROID 1
/usr/include/uv-unix.h:#ifdef __ANDROID__
``

**Comment by marcomagdy** [comment]
@sectorsize512 are you running this on minio or something similar?
Forget what I said earlier about __ANDROID__ and GLICXX, that's not the problem in this case.

Also, earlier you said you're getting 1MB/Sec, then you said it's 100MB/Sec. Which one is it? And can you give more details on your setup? How are you using the SDK on local network, etc.

**Comment by sectorsize512** [comment]
I'm using fakes3 on the server side. Server and client are connected via 10Gbps network. Both run CentOS 7. Client-side code just calls s3_client->GetObject(object_request). When using wget or curl I achieve 1GB/sec throuhgput. When using aws-sdk-cpp I only get about 100MB/sec (Sorry, for confusion, I meant 100MB/sec in the original post - will correct now).

I tried to run under perf but was not able to get any useful statistics (but I'm not experienced with perf). Could you tell me what exact command line to use with to get the output you want?

Appreciate your help.

**Comment by marcomagdy** [comment]
I'll setup fakes3 and try to reproduce it

**Comment by marcomagdy** [comment]
I've setup fakes3 and everywhere I tried it, I got similar or better performance compared to `wget`.
I've tried with a 1 Gbps link on EC2, and wget downloaded at ~480 MB/s and my sample program below beat it by a few milliseconds. I've also tried it on my development machine and the performance is _always_ on par with `curl` and `wget`. So, I'm not sure about the problem you're facing. I'll need more data to be able to help you.
```cpp
#include <aws/core/Aws.h>
#include <aws/core/client/ClientConfiguration.h>
#include <aws/core/auth/AWSCredentialsProviderChain.h>
#include <aws/core/utils/logging/LogLevel.h>
#include <aws/s3/S3Client.h>
#include <aws/s3/model/GetObjectRequest.h>
#include <iostream>
#include <fstream>
#include <memory>

using namespace Aws;

int main(int argc, char *argv[])
{
    if (argc < 5) {
        std::cout << " Usage: s3sample <endpoint> <bucket> <key> <local destination path>\n";
        return 0;
    }

    SDKOptions options;
    options.loggingOptions.logLevel = Utils::Logging::LogLevel::Error;
    InitAPI(options);
    {
        Client::ClientConfiguration config;
        config.endpointOverride = argv[1];
        config.scheme = Http::Scheme::HTTP;

        S3::S3Client client(std::make_shared<Auth::DefaultAWSCredentialsProviderChain>(), config,
                Client::AWSAuthV4Signer::PayloadSigningPolicy::Never /* signPayloads */,
                false /* useVirtualAddressing */);

        S3::Model::GetObjectRequest request;
        request.WithBucket(argv[2]).WithKey(argv[3]);
        request.SetResponseStreamFactory([argv]
                { return new std::fstream(argv[4], std::ios_base::out | std::ios_base::trunc); });

        auto outcome = client.GetObject(request);
        if (outcome.IsSuccess()) {
            std::cout << "Completed!" << std::endl;
        } else {
            std::cout << "Failed with error: " << outcome.GetError() << std::endl;
        }
    }

    ShutdownAPI(options);
    return 0;
}
```
And my CMake build script:
```cmake
cmake_minimum_required(VERSION 3.5)
project(s3test)
find_package(AWSSDK REQUIRED)
set(CMAKE_CXX_STANDARD 11)
add_executable(s3test "main.cpp")
# list all deps for static linking
target_link_libraries(s3test aws-cpp-sdk-s3 aws-cpp-sdk-core curl ssl crypto pthread)
target_compile_options(s3test PRIVATE "-Wall" "-Werror")

```

**Comment by sectorsize512** [comment]
@marcomagdy 

Apologies for the delay in my response, was out of office. I tried your code but got similar results in my setup:

```
$ time ./s3test bison03fast0 newcont 7e504deb3b8f4848a9c9f9faf63d3f810000  /dev/null
Completed!

real	0m4.050s
user	0m2.419s
sys	0m0.594s

$ time wget -O /dev/null "http://bison03fast0/newcont/7e504deb3b8f4848a9c9f9faf63d3f810000"
--2018-07-17 21:36:33--  http://bison03fast0/newcont/7e504deb3b8f4848a9c9f9faf63d3f810000
Resolving bison03fast0 (bison03fast0)... 10.0.0.3
Connecting to bison03fast0 (bison03fast0)|10.0.0.3|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 512000000 (488M) []
Saving to: ‘/dev/null’

100%[===========================================================>] 512,000,000  744MB/s   in 0.7s   

2018-07-17 21:36:33 (744 MB/s) - ‘/dev/null’ saved [512000000/512000000]


real	0m0.666s
user	0m0.054s
sys	0m0.363s
```

Notice the difference in real time: 0.666 seconds for wget and 4.050 seconds for s3test.

I compiled your code with the following command:
```
g++ -std=c++11 `pkg-config --libs aws-cpp-sdk-s3` -o s3test s3test.C
```

Also, in your last comment, you say that the link was 1Gbps (i.e., max throughput is about 100MB/sec) but the wget showed 480MB/sec (much more than 100MB/sec). Confusing.

Thank you for your help, let me know if I can provide any additional information.

**Comment by sectorsize512** [comment]
OK, for those who will experience the same issue. The problem was in old compiler/libraries. Compiling on Ubuntu 18 (which uses gcc 7+) and newer libraries on which aws-sdk-cpp depend demonstrated performance on par with wget/curl/og.

**Comment by TimLand** [comment]
> OK, for those who will experience the same issue. The problem was in old compiler/libraries. Compiling on Ubuntu 18 (which uses gcc 7+) and newer libraries on which aws-sdk-cpp depend demonstrated performance on par with wget/curl/og.

I got same speed problem with gcc 7+ and latest version of aws-sdk-cpp
