### ISSUE TITLE
s3 build solution error 

### ISSUE THREAD

**Issue by dadaaa123** [aws/aws-sdk-cpp#899]
When  I build the s3 project, use the MT mode, release , and there are some error like error:LNK2005 已经在*.obj中定义. Please someone tell me how to resolve this problem, here is my email: 1907372220@qq.com, Thanks!

**Comment by singku** [comment]
Hello, please supply more detailed information so we can help you, such as:
- Platform you tried to build.
- Compiler and Version
- Version of SDK you used.
- Your Cmake Args
- Is this error happen when building the SDK or your own s3 project.
- What has already been defined in *.obj
