### ISSUE TITLE
Iterator-based APIs

### ISSUE THREAD

**Issue by swinbank** [aws/aws-sdk-cpp#9]
From the readme:

```
a problem remains in that STL types dominate the public interface (primarily string parameters to the model object initialize/set methods). As it currently stands, developers that forgo STL entirely (rolling their own strings/containers/etc...) are forced to create many temporaries...
```

Should I be worried that you're not using the canonical C++ technique for working with generic strings and containers? The standard [algorithms](http://www.cplusplus.com/reference/algorithm/) library is the perfect reference. The [Boost String Algorithms](http://www.boost.org/doc/libs/1_59_0/doc/html/string_algo/quickref.html) library is another one.

At any rate, I am happy to finally see any kind of native API for AWS.

**Comment by JonathanHenson** [comment]
This isn't quite true anymore, check one of the model header files for
dynamodb  or something and see if that works for you.

**Comment by swinbank** [comment]
The dynamodb stuff looks good, although many of the core types used in it, like `AWSCredentials` and the HTTP classes, still use `Aws::String` quite a bit.

I should mention that this doesn't actually affect me, since my own string class interoperates with std::string, but I figured I would go ahead and raise the issue since most C++ developers are used to working with iterators and templates.

**Comment by singku** [comment]
Is this still a problem for you?
