### ISSUE TITLE
ListObject API shows single object if we drag and drop directory structure from s3 console

### ISSUE THREAD

**Issue by sdjunaidali** [aws/aws-sdk-cpp#900]
## Steps to produce the bug:

1) Drag and drop directory structure on s3 console and upload the hierarchy.
e.g: dir1/dir2/dir3/dir4/abc.txt 
upload dir1 directory at once using drag and drop on s3 console.

2) Compile the below code for list objects using 
g++ -std=c++11 list_object.cpp -laws-cpp-sdk-core -laws-cpp-sdk-s3 

3) Run the binary using
Ex: ./a.out "bucket name"

4) Output:
* dir1/dir2/dir3/dir4/abc.txt
Single Path 

Expected Output:
* dir1/
* dir1/dir2/
* dir1/dir2/dir3/
* dir1/dir2/dir3/dir4/
* dir1/dir2/dir3/dir4/abc.txt

Note: If we make a directory hierarchy using create folder option on S3 console then we are getting expected output, Problem is if we upload the directory structure at once using drag and drop.**

**sample program to list objects:**

#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>
#include <aws/core/auth/AWSCredentialsProvider.h>
#include <aws/s3/model/Bucket.h>
#include <aws/s3/model/Object.h>
#include <aws/s3/model/ListObjectsV2Request.h>

/**
 * List objects (keys) within an Amazon S3 bucket.
 */
int main(int argc, char** argv)
{
    Aws::SDKOptions options;
    Aws::InitAPI(options);
    {
        if (argc < 2)
        {
            std::cout << std::endl <<
                "To run this example, supply the name of a bucket to list!" <<
                std::endl << "Ex: list_objects <bucket-name> " << std::endl
                << std::endl;
            exit(1);
        }

        const Aws::String bucket_name = argv[1];
        std::cout << "Objects in S3 bucket: " << bucket_name << std::endl;

        Aws::Client::ClientConfiguration clientConfig;
        clientConfig.region = "ap-south-1";
        Aws::S3::S3Client s3_client(clientConfig);

        Aws::S3::Model::ListObjectsV2Request objects_request;
        objects_request.WithBucket(bucket_name);

        auto list_objects_outcome = s3_client.ListObjectsV2(objects_request);

        if (list_objects_outcome.IsSuccess())
        {
            Aws::Vector<Aws::S3::Model::Object> object_list =
                list_objects_outcome.GetResult().GetContents();

            if(object_list.size() == 0) {
                std::cout << "*Object List Size* " << object_list.size() << std::endl;
                return 1;
            }

            for (auto const &s3_object : object_list)
            {
                std::cout << "* " << s3_object.GetKey() << std::endl;
            }
        }
        else
        {
            std::cout << "ListObjects error: " <<
                list_objects_outcome.GetError().GetExceptionName() << " " <<
                list_objects_outcome.GetError().GetMessage() << std::endl;
        }
    }

    Aws::ShutdownAPI(options);
}

**Comment by marcomagdy** [comment]
Is that a bug in the SDK?
Are you getting different results when listing the contents of the bucket via aws cli for example?

**Comment by wps132230** [comment]
This an issue form S3 side.
With aws cli, you can still get single object.

**Comment by marcomagdy** [comment]
S3 is not a directory structure even though it looks like one.
Every object in S3 has a key, and the key even though looks like directory path, it is not. The SDK does not and should not try to hide that fact and simulate a folder/directory structure.
