### ISSUE TITLE
[UE4] Undefined Reference Aws::Http::CONTENT_TYPE_HEADER

### ISSUE THREAD

**Issue by Tolan87** [aws/aws-sdk-cpp#903]
### What platform/OS are you using?
Windows 10 Pro 1803 17134.112 64-Bit
AWS C++ SDK 1.4.74

### What compiler are you using? what version?
Visual Studio 2017 Community Edition 15.7.3
Unreal Engine 4.19.2

### What's your CMake arguments?
```
cmake ../ -G "NMake Makefiles" -DTARGET_ARCH=WINDOWS -DBUILD_ONLY="core;gamelift" -DCUSTOM_MEMORY_MANAGEMENT=0 -DBUILD_SHARED_LIBS=1
```

### Can you provide a TRACE level log? (sanitize any sensitive information)

Hey,

i have builded the AWS SDK successfully, but if i use the SDK with Unreal Engine 4 in my plugin, to integrate Gamelift, the linker throws the error below. 

> Error: LNK2001 undefined reference "char const * const Aws::Http::CONTENT_TYPE_HEADER" (?CONTENT_TYPE_HEADER@Http@Aws@@3PEBDEB)".	PluginTest	D:\PluginTest\Intermediate\ProjectFiles\Module.GameLiftPlugin.cpp.obj

can anyone help me out?

thanks

**Comment by Tolan87** [comment]
Ok, i have researched a little bit and could found the reason.

My plugin creates session request like so CreateGameSessionRequest, if i comment out the line the build is successfull, otherwise build fails.

**Comment by Tolan87** [comment]
Ok, finally i found a working solution, let me share the solution for other Unreal Developer that run into this problem.

For dynamic linking u need the preprocessor directive below.

> **USE_IMPORT_EXPORT**

How you can add it to your Visual Studio Project Solution?

> When you use a plugin or a module(a game himself is module) u can set a public definition in the _**PluginOrModuleName.Build.cs**_ file like below.

```csharp
PublicDefinitions.Add("USE_IMPORT_EXPORT");
```

If your build  fail again, it´s can be needed to delete the **_Intermediate_** and _**Binaries**_ folder and let regenerate your Visual Studio Project files by Unreal.

Regards ;)

**Comment by SyedAman** [comment]
Make sure to create the cmake output folder inside the sdk source code, didn't work for me outside of it

**Comment by singku** [comment]
Glad that you found a way out. If you generate your project using cmake, you can actually add this Marco into you cmake script.

**Comment by wukakuki** [comment]
@singku How to add this macro into my cmake script? I tried add "add_definitions( -D USE_IMPORT_EXPORT )" in CMakeLists.txt file under aws-sdk-cpp, and then run the cmake command. But It doesn't work. Am I using the wrong method?
