### ISSUE TITLE
Question: How does the AWS SDK handle HTTPS in the Windows recovery environment?

### ISSUE THREAD

**Issue by nathan-alden-hp** [aws/aws-sdk-cpp#904]
### What platform/OS are you using?
Windows 10 (specifically the Windows recovery environment)

My employer uses the AWS SDK for C++ in the Windows recovery environment. Apparently, the SDK is able to make HTTPS calls when it reaches out to S3 to download files. I was under the impression (maybe incorrectly) that there was no certificate store in WinRE.

Questions:
- Is there actually full HTTPS/TLS support in WinRE?
- If not, how does the AWS SDK use HTTPS/TLS and still honor certificates?

**Comment by marcomagdy** [comment]
The SDK uses the certificate store on the system.
The SDK can talk to S3 over standard HTTP in which case it will sign the whole request + payload.

I don't know much about Windows RE, but if you're talking to S3 over TLS, then the certificate store exists.

Reopen if you have more questions
