### ISSUE TITLE
Question: Are there any changes in Aws::S3::S3Errors between v1.4.45 and v1.4.46?

### ISSUE THREAD

**Issue by mokelmbe** [aws/aws-sdk-cpp#905]
After updating sdk from v1.4.45 to v1.4.46, `Aws::S3::S3Errors` that returned by `Aws::Client::AWSError<Aws::S3::S3Errors>::GetErrorType() `is changed in some circumstances.

For example, when I set a invalid bucket key, the `S3Errors` was `NETWORK_CONNECTION` in v1.4.45, but in v1.4.46, the `S3Errors` is `REQUEST_NOT_MADE`.

I can't find any changes about S3 in https://github.com/aws/aws-sdk-cpp/commit/2c1d89b5559eb2678b0f1a7632740556e1605182 .

Are there any details about the change?  Thank you.

**Comment by marcomagdy** [comment]
Which http client are you using? curl, winhttp, etc?

Also, when do you see that error happening? what are the circumstances?

**Comment by mokelmbe** [comment]
I use winhttp. (OS: win8.1)

Here is a simplified code.

```
void foo()
{
      
       Aws::Client::ClientConfiguration config;
	
       config.retryStrategy	= std::make_shared<Aws::Client::DefaultRetryStrategy>(0, 0);
       config.connectTimeoutMs = 1000;
       config.requestTimeoutMs = 1000;
       //★set an invalid region
       config.region ="invalid"; 

       auto client= std::make_shared<Aws::S3::S3Client>(Aws::Auth::AWSCredentials("accesskey",
		"secret key", "session token"), config);

       Aws::S3::Model::PutObjectRequest objectRequest;
       objectRequest.WithBucket("bucket name").WithKey("filename");
       objectRequest.SetBody(ul_file);
	
       auto result = client->PutObject(objectRequest);
       auto errorType = result.GetError().GetErrorType();
}
```

In this case, when I use v1.4.45, `errorType ` is `NETWORK_CONNECTION` and when v1.4.46, it is `REQUEST_NOT_MADE`. 
(When I set correct region, PutObject() succeeded.)

And in the other case, when I access the same bucket by using PutObject() and GetObject() at the same time, the methods return `NETWORK_CONNECTION`  when I use v1.4.45. But when I use v1.4.46, the error type is 'UNKNOWN'. 
( Although there is no confirmation that the cause of this result is simultaneous access.)

**Comment by singku** [comment]
Hi, you are right, there is no change related to **s3**, but to make the behavior of acquiring original request from response safe, we have made some changes in **core** module. In 1.4.45, the http response could be null if the request is not valid, and the error code is set to NETWORK_CONNECTION (in BuildAWSError function of AWSClient.cpp), in 1.4.46, we try the best to make http response not null, and the default errCode when constructing the response is REQUESET_NOT_MADE. 

Hope this answer could help you understanding the different behavior on S3.
