### ISSUE TITLE
Undefined symbols for architecture x86_64 when building MacOS libtesting-resources.dynlib

### ISSUE THREAD

**Issue by jghankins** [aws/aws-sdk-cpp#907]
### What platform/OS are you using?
MacOS 10.13.5
### What compiler are you using? what version?
Apple LLVM version 9.1.0 (clang-902.0.39.2)
### What's your CMake arguments?
-DBUILD_ONLY="s3;sqs;sns;cognito-idp;cognito-identity;dynamodb;kinesis" -DTARGET_ARCH=APPLE
### Can you provide a TRACE level log? (sanitize any sensitive information)
Undefined symbols for architecture x86_64:
  "testing::AssertionResult::AssertionResult(testing::AssertionResult const&)", referenced from:
      testing::AssertionResult testing::internal::CmpHelperOpFailure<unsigned long long, unsigned long long>(char const*, char const*, unsigned long long const&, unsigned long long const&, char const*) in MemoryTesting.cpp.o
      testing::AssertionResult testing::internal::CmpHelperOpFailure<unsigned long long, unsigned long>(char const*, char const*, unsigned long long const&, unsigned long const&, char const*) in MemoryTesting.cpp.o
  "testing::AssertionFailure()", referenced from:
      testing::AssertionResult testing::internal::CmpHelperOpFailure<unsigned long long, unsigned long long>(char const*, char const*, unsigned long long const&, unsigned long long const&, char const*) in MemoryTesting.cpp.o
      testing::AssertionResult testing::internal::CmpHelperOpFailure<unsigned long long, unsigned long>(char const*, char const*, unsigned long long const&, unsigned long const&, char const*) in MemoryTesting.cpp.o
  "testing::AssertionSuccess()", referenced from:
      testing::AssertionResult testing::internal::CmpHelperNE<unsigned long long, unsigned long long>(char const*, char const*, unsigned long long const&, unsigned long long const&) in MemoryTesting.cpp.o
      testing::AssertionResult testing::internal::CmpHelperGE<unsigned long long, unsigned long>(char const*, char const*, unsigned long long const&, unsigned long const&) in MemoryTesting.cpp.o
  "testing::Message::Message()", referenced from:
      BaseTestMemorySystem::FreeMemory(void*) in MemoryTesting.cpp.o
      testing::AssertionResult& testing::AssertionResult::operator<<<char [12]>(char const (&) [12]) in MemoryTesting.cpp.o
      testing::AssertionResult& testing::AssertionResult::operator<<<char const*>(char const* const&) in MemoryTesting.cpp.o
      testing::AssertionResult& testing::AssertionResult::operator<<<char [3]>(char const (&) [3]) in MemoryTesting.cpp.o
      testing::AssertionResult& testing::AssertionResult::operator<<<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in MemoryTesting.cpp.o
      testing::AssertionResult& testing::AssertionResult::operator<<<char [5]>(char const (&) [5]) in MemoryTesting.cpp.o
  "testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)", referenced from:
      BaseTestMemorySystem::FreeMemory(void*) in MemoryTesting.cpp.o
  "testing::internal::AssertHelper::~AssertHelper()", referenced from:
      BaseTestMemorySystem::FreeMemory(void*) in MemoryTesting.cpp.o
  "testing::internal::IsTrue(bool)", referenced from:
      testing::internal::scoped_ptr<std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::reset(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in MemoryTesting.cpp.o
      testing::internal::scoped_ptr<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::reset(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in MemoryTesting.cpp.o
  "testing::Message::GetString() const", referenced from:
      testing::AssertionResult::AppendMessage(testing::Message const&) in MemoryTesting.cpp.o
  "testing::internal::AssertHelper::operator=(testing::Message const&) const", referenced from:
      BaseTestMemorySystem::FreeMemory(void*) in MemoryTesting.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [testing-resources/libtesting-resources.dylib] Error 1
make[1]: *** [testing-resources/CMakeFiles/testing-resources.dir/all] Error 2
make: *** [all] Error 2

**Comment by singku** [comment]
Hello, thank you for reporting this problem. I tried with your above cmake arguments on my Mac (MacOS 10.12.6 With clang 9.0.0 x86_64. it worked fine. 
May I know which version of SDK are you using? Did you make any change to the source?

**Comment by jghankins** [comment]
Hi, I'm using  1.4.78   I'm able to get around it by using:
   `-DTARGET_ARCH=APPLE -DENABLE_TESTING="OFF"'
