### ISSUE TITLE
Linking Error Windows VS2017 LNK2001: unresolved external symbol "char const * const Aws::Http::CONTENT_TYPE_HEADER"

### ISSUE THREAD

**Issue by jghankins** [aws/aws-sdk-cpp#908]
### What platform/OS are you using?
Windows 64bit
### What compiler are you using? what version?
qmake 3.1
### What's your CMake arguments?
-G "Visual Studio 15 2017 Win64"
### Can you provide a TRACE level log? (sanitize any sensitive information)
C:\Qt\Qt5.11.1\Tools\QtCreator\bin\jom.exe -f Makefile.Debug
	link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:WINDOWS "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:debug\amazon.exe @D:\Users\jhankins\AppData\Local\Temp\1\amazon.exe.6992.31.jom
mainwindow.obj : error LNK2001: unresolved external symbol "char const * const Aws::Http::CONTENT_TYPE_HEADER" (?CONTENT_TYPE_HEADER@Http@Aws@@3PEBDEB)
debug\amazon.exe : fatal error LNK1120: 1 unresolved externals
jom: D:\Users\jhankins\Documents\dev\build-amazon-Desktop_Qt_5_11_1_MSVC2017_64bit-Debug\Makefile.Debug [debug\amazon.exe] Error 1120
jom: D:\Users\jhankins\Documents\dev\build-amazon-Desktop_Qt_5_11_1_MSVC2017_64bit-Debug\Makefile [debug] Error 2
13:36:55: The process "C:\Qt\Qt5.11.1\Tools\QtCreator\bin\jom.exe" exited with code 2.

**Comment by singku** [comment]
Hello, looks like this is the same problem as https://github.com/aws/aws-sdk-cpp/issues/151. Could you please taking a look at the solution in that issue?

**Comment by singku** [comment]
Hi, 
- If you use Nuget to pull AWS SDK for C++ libraries, you can update your package version to solve this problem. 
- If you build the libraries by yourself and specify compiler and linker options, you should define preprocessor macros `USE_WINDOWS_DLL_SEMATICS` and `USE_IMPORT_EXPORT`.
- If you use CMake to generate solution file, you can use `find_package(AWSSDK required)` to correctly locate and link against AWS SDK for C++ libraries. Taking a look at this [example](https://github.com/singku/aws-sdk-cpp-test/blob/master/CMakeLists.txt)

**Comment by singku** [comment]
Reopen if you still have problems.

**Comment by btgoodwin** [comment]
I've run into this same linking issue when building [amazon-s3-gst-plugin](https://github.com/amzn/amazon-s3-gst-plugin/issues/13).  The build uses meson which seems to only be happy if we let it use pkg-config, which only becomes happy if we [patch aws-sdk-cpp's pc files](https://github.com/aws/aws-sdk-cpp/issues/1658).

Do you all have any updated recommendations (seeing as this is from '18)?
