### ISSUE TITLE
withFileOffset and withFile options not present in UploadPartRequest of multipart upload in c++ sdk.

### ISSUE THREAD

**Issue by sdjunaidali** [aws/aws-sdk-cpp#909]
AWS SDK for C++

### What platform/OS are you using?
Ubuntu 14.04

In multi part upload request there is no options of  withFileOffset and withFile options in UploadPartRequest of multipart upload in **C++ sdk of AWS S3** and it's present in JAVA sdk, 

**So how to split parts using C++ sdk without using the withFileOffset and withFile options ?**

**Comment by singku** [comment]
I'd suggest you to use transfer manager to manage file upload/download for you.

**Comment by shuzongran** [comment]
Aws::String str(data.data(), size);
auto&& input_data = Aws::MakeShared<Aws::StringStream>("UploadPartStream", str);

通过自行读取文件内容的方式可以完成分片上传,保存在buffer里转换成string就行
