### ISSUE TITLE
Build error using clang3.8

### ISSUE THREAD

**Issue by HowardLander** [aws/aws-sdk-cpp#913]
### What platform/OS are you using?
Ubuntu 16

### What compiler are you using? what version?
Clang 3.8
### What's your CMake arguments?
cmake -DCMAKE_C_COMPILER=/opt/irods-externals/clang3.8-0/bin/clang -DCMAKE_CXX_COMPILER=/opt/irods-externals/clang3.8-0/bin/clang++ -DCMAKE_CXX_FLAGS=-std=c++11 ..

Also added the following to the cmakelisst.txt file
include_directories(BEFORE SYSTEM /opt/irods-externals/clang3.8-0/include/c++/v1)
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${CMAKE_SHARED_LINKER_FLAGS} -stdlib=libc++")
link_directories(/opt/irods-externals/clang-runtime3.8-0/lib)

to make sure we are using all of our distributed compiler tools.

### Can you provide a TRACE level log? (sanitize any sensitive information)

Here's the compiler error:
/usr/bin/ld: CMakeFiles/polly_sample.dir/main.cpp.o: undefined reference to symbol '_ZNSt3__18ios_base5clearEj'
/opt/irods-externals/clang-runtime3.8-0/lib/libc++.so.1: error adding symbols: DSO missing from command line
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
aws-cpp-sdk-polly-sample/CMakeFiles/polly_sample.dir/build.make:99: recipe for target 'aws-cpp-sdk-polly-sample/polly_sample' failed
make[2]: *** [aws-cpp-sdk-polly-sample/polly_sample] Error 1
CMakeFiles/Makefile2:9245: recipe for target 'aws-cpp-sdk-polly-sample/CMakeFiles/polly_sample.dir/all' failed
make[1]: *** [aws-cpp-sdk-polly-sample/CMakeFiles/polly_sample.dir/all] Error 2

**Comment by marcomagdy** [comment]
you can either use update-alternatives to set the symlinks for cc and c++ to point to clang, or you can try exporting C, CXX and AR environment variables and point them to clang-3.8
