### ISSUE TITLE
Object data is not accessible inside Aws::S3::GetObjectResponseReceivedHandler()

### ISSUE THREAD

**Issue by dzjiang91** [aws/aws-sdk-cpp#918]
Trying to use Aws::S3::S3Client::GetObjectAsync and handle the object data in the callback.

`        virtual void GetObjectAsync(const Model::GetObjectRequest& request, const GetObjectResponseReceivedHandler& handler, const std::shared_ptr<const Aws::Client::AsyncCallerContext>& context = nullptr) const;`

`  typedef std::function<void(const S3Client*, const Model::GetObjectRequest&, const Model::GetObjectOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&) > GetObjectResponseReceivedHandler;`

Similar to use of GetObject() in https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/examples-s3-objects.html,
here is what I tried to do:
```
Aws::S3::GetObjectResponseReceivedHandler callback = [](
    const S3Client*,
    const Model::GetObjectRequest& request,
    const Model::GetObjectOutcome& outcome,
    const std::shared_ptr<const Aws::Client::AsyncCallerContext>&){
     Aws::IOStream& body = outcome.GetResult().GetBody();
     <other operations on body>
}
```
This does NOT work because _outcome_ is passed as const reference and Aws::S3::Model::GetObjectResult::GetBody() is not a const accessor.
```
    /**
     * <p>Object data.</p>
     */
    inline Aws::IOStream& GetBody() { return m_body.GetUnderlyingStream(); }
```

So how should we access s3 object data in callback of GetObjectAsync? Is there any workaround?

**Comment by crusader-mike** [comment]
Can you make a local copy of GetObjectOutcome object?

**Comment by dzjiang91** [comment]
@crusader-mike Copy is not efficient and the copy constructor is disabled in class GetObjectResult
`    GetObjectResult(const GetObjectResult&) = delete;
    GetObjectResult& operator=(const GetObjectResult&) = delete;`
Found similar issue posted a few years back https://github.com/aws/aws-sdk-cpp/issues/918.
Solution then is to use const_cast. Do we have any better alternatives now?

**Comment by crusader-mike** [comment]
Doesn't look like it... :-\

**Comment by KaibaLopez** [comment]
Hi, as an update:
As of version 1.7.213 , we've removed constness restriction of outcome of async operation callback.
