### ISSUE TITLE
I have met a problem when using huawei3519 GCC

### ISSUE THREAD

**Issue by weiqiangshen1979** [aws/aws-sdk-cpp#922]
### What platform/OS are you using?
arm-Linux

### What compiler are you using? what version?
COLLECT_GCC=arm-hisiv500-linux-gcc
COLLECT_LTO_WRAPPER=/opt/hisi-linux/x86-arm/arm-hisiv500-linux/bin/../libexec/gcc/arm-hisiv500-linux-uclibcgnueabi/4.9.4/lto-wrapper
Target: arm-hisiv500-linux-uclibcgnueabi
Configured with: ../gcc-linaro-4.9-2015.06/configure --host=x86_64-linux-gnu --build=x86_64-linux-gnu --target=arm-hisiv500-linux-uclibcgnueabi --prefix=/home/sying/toolchain_ljhui/gcc4_9/build-toolchain/gcc-uclibc/install/arm-hisiv500-linux --enable-threads --disable-libmudflap --disable-libssp --disable-libstdcxx-pch --with-arch=armv5te --with-gnu-as --with-gnu-ld --enable-languages=c,c++ --enable-shared --enable-lto --enable-symvers=gnu --enable-__cxa_atexit --enable-nls --enable-clocale=gnu --enable-extra-hisi-multilibs --with-sysroot=/home/sying/toolchain_ljhui/gcc4_9/build-toolchain/gcc-uclibc/install/arm-hisiv500-linux/target --with-build-sysroot=/home/sying/toolchain_ljhui/gcc4_9/build-toolchain/gcc-uclibc/install/arm-hisiv500-linux/target --with-gmp=/home/sying/toolchain_ljhui/gcc4_9/build-toolchain/gcc-uclibc/install/host_lib --with-mpfr=/home/sying/toolchain_ljhui/gcc4_9/build-toolchain/gcc-uclibc/install/host_lib --with-mpc=/home/sying/toolchain_ljhui/gcc4_9/build-toolchain/gcc-uclibc/install/host_lib --with-ppl=/home/sying/toolchain_ljhui/gcc4_9/build-toolchain/gcc-uclibc/install/host_lib --with-cloog=/home/sying/toolchain_ljhui/gcc4_9/build-toolchain/gcc-uclibc/install/host_lib --with-libelf=/home/sying/toolchain_ljhui/gcc4_9/build-toolchain/gcc-uclibc/install/host_lib --enable-libgomp --disable-libitm --disable-libsanitizer --enable-poison-system-directories --with-libelf=/home/sying/toolchain_ljhui/gcc4_9/build-toolchain/gcc-uclibc/install/host_lib --with-pkgversion=Hisilicon_v500_20170329 --with-bugurl=http://www.hisilicon.com/cn/service/claim.html
Thread model: posix
gcc version 4.9.4 20150629 (prerelease) (Hisilicon_v500_20170329) 

### What's your CMake arguments?

I change CMakeList  and add below codes
```
#add below code for cross compile 
SET(CMAKE_SYSTEM_NAME Linux)
SET(TOOLCHAIN_DIR "/opt/hisi-linux/x86-arm/arm-hisiv500-linux")
set(CMAKE_SYSTEM_PROCESSOR ARM)
SET(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_DIR})
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_C_COMPILER ${TOOLCHAIN_DIR}/bin/arm-hisiv500-linux-uclibcgnueabi-gcc)
SET(CMAKE_CXX_COMPILER ${TOOLCHAIN_DIR}/bin/arm-hisiv500-linux-uclibcgnueabi-g++)
#add zlib path
set(CMAKE_INCLUDE_PATH /home/wqs/aws_arm/build/zlib)
set(CMAKE_LIBRARY_PATH /home/wqs/aws_arm/build/zlib)

#end cross compile
```

### Can you provide a TRACE level log? (sanitize any sensitive information)
when i compile aws-cpp-sdk-s3, i have got a error like below , who can help me resolve this issue?

In file included from /home/wqs/aws_arm/aws-sdk-cpp/build/aws-cpp-sdk-s3/ub_S3.cpp:2:0:
/home/wqs/aws_arm/aws-sdk-cpp/aws-cpp-sdk-s3/source/S3Client.cpp: In member function ‘virtual Aws::S3::Model::AbortMultipartUploadOutcomeCallable Aws::S3::S3Client::AbortMultipartUploadCallable(const Aws::S3::Model::AbortMultipartUploadRequest&) const’:
/home/wqs/aws_arm/aws-sdk-cpp/aws-cpp-sdk-s3/source/S3Client.cpp:182:120: error: return type ‘Aws::S3::Model::AbortMultipartUploadOutcomeCallable {aka class std::future<Aws::Utils::Outcome<Aws::S3::Model::AbortMultipartUploadResult, Aws::Client::AWSError<Aws::S3::S3Errors> > >}’ is incomplete
 AbortMultipartUploadOutcomeCallable S3Client::AbortMultipartUploadCallable(const AbortMultipartUploadRequest& request) const

**Comment by yukuilong** [comment]
I have the same problem, how can I solve this problem?

**Comment by OsenLiu** [comment]
Try adding -march=armv6 in CXX_FLAG.

**Comment by KaibaLopez** [comment]
Hi, is this still an issue? did the last comment solve this?
