### ISSUE TITLE
Better throttling handling in EC2MetadataClient & co

### ISSUE THREAD

**Issue by oliora** [aws/aws-sdk-cpp#923]
Currently, `AWSHttpResourceClient` and derived classes `EC2MetadataClient` and `ECSCredentialsClient` uses default configuration to call metadata service and there is no way to configure it. Neither default timeout (3s) nor default retries configuration (no retries) is well suitable for the metadata service when it throttles. I propose to allow to pass `ClientConfiguration` object to `AWSHttpResourceClient` (and derived classes) so user can control retries and timeouts used to call the metadata service.

**Comment by marcomagdy** [comment]
That's a fair ask.
Can you submit a PR please?

**Comment by oliora** [comment]
It’s merged and fixed
