### ISSUE TITLE
PUT Object Large File Upload (Second time)

### ISSUE THREAD

**Issue by sdjunaidali** [aws/aws-sdk-cpp#926]
### PUT Object Question

How does aws sdk PUT object API handles large file, If file is already present on S3 and small modifications are made in some data of it, **Will it upload whole object again OR Is there any other API for updating the small portions of existing file ( like for example patch or something) ?**

**Comment by singku** [comment]
Hi, PutObject in SDK doesn't do anything that is not supported by S3. Taking a look at PutObject's doc at https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html .
