### ISSUE TITLE
Curl returning error 27 out of memory

### ISSUE THREAD

**Issue by srgxor** [aws/aws-sdk-cpp#931]
### What platform/OS are you using?
Ubuntu 16.04

### What compiler are you using? what version?
GCC 5.4

### What's your CMake arguments?
Default

### Can you provide a TRACE level log? (sanitize any sensitive information)
Not applicable

Hello,
I have a rather unpleasant phenomena that might not belong into this forum. However, I was hoping that someone maybe can help or experienced a similar issue.
I can use the AWS SDK without problems and everything works fine. However, when I link to a specific inhouse library AWS SDK stops working and the logfiles indicate that CURL returned error 27. That library is linking against tons of other libraries including libcurl and libcurl-gnutls.

I do not get how linking ( no code of that library is actually executed  before that error occurs ) can lead to CURL failing. Did anyone experience similar issues or can give a tip on what might cause this issue? I am running out of ideas here sadly.

**Comment by crusader-mike** [comment]
curl/openssl initialization? related functions aren't thread-safe, assumption is made that end-user (application author) arranged for them to be called correctly, but sadly, it doesn't happen very often -- libraries tend to call them at will (unsafely) updating library static state and creating annoying bugs like this one.

**Comment by crusader-mike** [comment]
Maybe this one (googled it):
https://curl.haxx.se/mail/lib-2009-02/0042.html
?

**Comment by srgxor** [comment]
Hi @crusader-mike thanks for your help! I fixed it. It turned out that I was linking against the correct curl library however, my application loaded another one at runtime causing it to fail. I fixed that issue. 
I am trying to build a conan package for the AWS SDK but so far I've ran into a lot of problems. This one got fixed though.

**Comment by crusader-mike** [comment]
No probs, you should probably close this issue then

**Comment by srgxor** [comment]
Problem fixed. Thanks!
