### ISSUE TITLE
TransferManager uploads failing to S3 on Windows 10

### ISSUE THREAD

**Issue by shanem2ms** [aws/aws-sdk-cpp#934]
Windows 10, Visual Studio 2017

Notable lines from my log file:
host: max-engage-dm.s3.amazonaws.com
user-agent: aws-sdk-cpp/1.4.33 Windows/10.0.16299.15 AMD64
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20180810T141259Z

[ERROR] 2018-08-10 10:12:59 WinHttpSyncHttpClient [25840] Failed to add HTTP request headers with error code: 12150

Error 12150 says header not found.  See here:
[WinInet Errors](https://support.microsoft.com/en-us/help/193625/info-wininet-error-codes-12001-through-12156)

I was able to work around this error by making a modification to WinHttpSyncHttpClient.cpp, line 164.  I removed the flag WINHTTP_ADDREQ_FLAG_REPLACE from WinHttpAddRequestHeaders.   

[dmserver_aws_2018-08-10-10.log](https://github.com/aws/aws-sdk-cpp/files/2278342/dmserver_aws_2018-08-10-10.log)

**Comment by KaibaLopez** [comment]
Hi @shanem2ms, 
Sorry for the late response, it seems from your comment that you got it to work though , from my side, I was unable to reproduce the error, but I can see that the flag is still there, so I don't think it was necessarily related.
 I'd need a code sample to figure out the root cause.
