### ISSUE TITLE
S3 UploadPartCopy fails to upload a part to a 500MB file.

### ISSUE THREAD

**Issue by pranalitirkhunde** [aws/aws-sdk-cpp#935]
### What platform/OS are you using?
Ubuntu 14.04
### What compiler are you using? what version?
g++ 4.8.4
### Description
When a part is uploaded from a 500MB object already existing on the object store using UploadPartCopy API, it is not successfully uploaded as the md5sum of the source object does not verify with that of the remote copy.However, it is carried out successfully for a 6GB file.

Usage:
UploadPartCopyRequest copy_request;
                copy_request.WithBucket(bucket_name)
                .WithKey(key_name)
                .WithPartNumber(i)
                .WithUploadId(upload_id)
                .WithCopySourceRange(bytes)
                .WithCopySource(Aws::Utils::StringUtils::URLEncode((bucket_name +"/file_name.txt").c_str()));

The SDK states that UploadPartCopy.WithCopySourceRange(bytes) requires a source object greater than 5GB. Is this the limitation of API?
How can we we get around this issue?

**Comment by marcomagdy** [comment]
The documentation says the part must be between 5MB and 5GB (the last part can be less than 5MB). The API limitations can be found [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/qfacts.html)


I'm not sure I understand the issue you're having. You mentioned the API requires the object to be greater than 5 **Gigabytes**, which is not true. Was that a typo? please clarify.

**Comment by pranalitirkhunde** [comment]
When  UploadPartRequest  API is used for uploading a part, it follows the limitations specified [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/qfacts.html).

However, the above concern was regrading the usage of UploadPartCopyRequest API for uploading parts.

The AWS-SDK-CPP states the following in the file "**aws-sdk-cpp/aws-cpp-sdk-s3/include/aws/s3/model/UploadPartCopyRequest.h**"

#########################################################################

/**                                                                         
     * The range of bytes to copy from the source object. The range value must use the
     * form bytes=first-last, where the first and last are the zero-based byte offsets
     * to copy. For example, bytes=0-9 indicates that you want to copy the first ten
     * bytes of the source. **You can copy a range only if the source object is greater
     * than 5 GB.**                                                               
     */                                                                         
    inline UploadPartCopyRequest& WithCopySourceRange(const char* value) { SetCopySourceRange(value); return *this;}

##########################################################################

I just wanted to confirm if we can copy a range of bytes using UploadPartCopyRequest only if the source object is greater than 5GB as the above statement illustrates different behaviour than the normal UploadPartRequest behaviour.

**Comment by KaibaLopez** [comment]
Hi , sorry for the delayed response, can't really be sure what version of the sdk you were using and so finding the change for this typo is a bit time consuming.
But you were right, it was a typo and it was fixed so thanks for pointing it out, I'm pretty sure it was because of you that we found it.
