### ISSUE TITLE
Build failing with Visual Studio 2017

### ISSUE THREAD

**Issue by srgxor** [aws/aws-sdk-cpp#939]
### What platform/OS are you using?
Windows 7

### What compiler are you using? what version?
Visual Studio 2017

### What's your CMake arguments?
Default

### Can you provide a TRACE level log? (sanitize any sensitive information)
N/A

It seems that there is an issue with the code in awshttpresourceclient.cpp (see below)
Entering the namespace Client:: causes a compiler error when compiling with Visual Studio 2017. Haven't tested with other versions so far. However, removing Client:: fixes the problem. 

c:\.conan\s1q1775z\1\aws-sdk-cpp\aws-cpp-sdk-core\source\internal\awshttpresourceclient.cpp(77): error C2653: 'Client': is not a class or namespace name [C:\.conan\s1q1775z\1\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]
c:\.conan\s1q1775z\1\aws-sdk-cpp\aws-cpp-sdk-core\source\internal\awshttpresourceclient.cpp(155): error C2653: 'Client': is not a class or namespace name [C:\.conan\s1q1775z\1\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxpro]
c:\.conan\s1q1775z\1\aws-sdk-cpp\aws-cpp-sdk-core\source\internal\awshttpresourceclient.cpp(243): error C2653: 'Client': is not a class or namespace name [C:\.conan\s1q1775z\1\aws-cpp-sdk-core\aws-cpp-sdk-core.vcxproj]

**Comment by Vawx** [comment]
I have the same issue.

**Comment by wps132230** [comment]
Thank you for your feedback!
And thanks @Vawx 's PR(https://github.com/aws/aws-sdk-cpp/pull/941) to fix this issue. It's already in our code right now.

**Comment by singku** [comment]
This has been fixed in 81671f65be6030c48b927d20de4a496eb9c18830.
