### ISSUE TITLE
last modified double values not set correctly...

### ISSUE THREAD

**Issue by cedral** [aws/aws-sdk-cpp#94]
Not sure why these fields are double because the both come down as strings. last modifed comes in 2 ways. Either in XML response (ie: ListObjects) or in the last-modified header value for Head* requests

These string responses appear to come in 2 formats... 
yyyy-mm-ddThh:mm::ss.000000Z for xml ( this one produces the year in the double field.)
and
Fri, 29 Jan 2016 hh::mm::ss GMT for header. (this one produces 0 in the double field.)

I needed this to work so I wrote 2 functions in StringUtils called

StringHeaderToDoubleDate
and
StringXmlToDoubleDate

and parsed and imported the date time stamp into struct tm and called gmtime (or _mkgmtime on windows) to get a time_t and cast that to the double. These gives me a usable value from outside the library but I am not sure it was the one you were looking for. Would you like me to issue a pull request?

**Comment by JonathanHenson** [comment]
What service is this bug on? S3?

They are double because that is the default for date stamps, but some services specify a datestamp, but actually use something like ISO or millis since epoch. When I find them, I have to go and provide some overrides to the generator.

**Comment by cedral** [comment]
Yes, they are all in S3. HeadObject was calling strod on the last-modified header which is a string representation of a date.
ListObjects was calling strtod on a node in the Xml response documents named LastModified which was a different string representation.

> On Feb 3, 2016, at 5:40 PM, Jonathan M. Henson <notifications@github.com> wrote:
> 
> What service is this bug on? S3?
> 
> They are double because that is the default for date stamps, but some services specify a datestamp, but actually use something like ISO or millis since epoch. When I find them, I have to go and provide some overrides to the generator.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/awslabs/aws-sdk-cpp/issues/94#issuecomment-179507969>.
> 

Joseph Southwell
joseph@southwell.org
The past is history,
The future's a mystery,
The present's a gift.

**Comment by JonathanHenson** [comment]
I've just pushed a major update to the way we handle date timestamps. See if this resolves your issue. Reopen if you have further issues.
