### ISSUE TITLE
How can i include this library as an external dependency in a project that uses bazel ?

### ISSUE THREAD

**Issue by sirajmansour** [aws/aws-sdk-cpp#948]
I'm trying to write an envoy proxy filter which publishes to kinesis. I'm using the sample filter from https://github.com/envoyproxy/envoy-filter-example as a reference. I'm not very familiar with C++ development but i could wrap my head around it enough i guess.

The repo i mentioned uses BAZEL for build and external dependencies and isn't IDE dependent (no obvious way to use visual studio 😞). I'm using vs code to get some intellisense support, so if i could get some guidance on how to use the AWS SDK as a bazel dependency as well as get some intellisense support in vs code while am trying to use it, it would be great and any help is appreciated.

**Comment by KaibaLopez** [comment]
Hi @sirajmansour,
First of all, sorry for the late response, hopefully you've figured this out by now, but in case you haven't. 
You should be able to build the sdk from source and use any other library, we don't really support BAZEL though, and this seems more of a bazel usage problem than an sdk question.
