### ISSUE TITLE
Streaming audio data to Lex using PostConetntAsync

### ISSUE THREAD

**Issue by achaloyan** [aws/aws-sdk-cpp#949]
### What platform/OS are you using?
Linux and Windows
### What compiler are you using? what version?
gcc and VS 2015

AWS SDK CPP 1.5.16

My goal is to use [PostContentAsync](https://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_lex_runtime_service_1_1_lex_runtime_service_client.html#af275c82d23dbccbd46f55150e085d61f) and stream audio data to Lex. The [documentation](https://docs.aws.amazon.com/lex/latest/dg/API_runtime_PostContent.html#API_runtime_PostContent_RequestSyntax
) clearly indicates that the service supports streaming. 

However, it is not clear to me whether the c++ SDK provides any means for that or not. I tried to create an instance of an Aws::IOStream and set it as a body  in PostContentRequest, by continuously writing audio data chunks to the stream, but this does not seem to work. Any usage example would help. In the meantime, non-streaming mode works as intended.

Thanks.

**Comment by dcrogers333** [comment]
I'd like to support this question - can anyone provide information on how to stream audio data to Lex?

I also tried to write to the Aws::IOStream, and it failed, so the PostContentAsync interface seems appropriate, if I could get an example of use.

**Comment by TelephonyMan** [comment]
I don't think this is supported. I too need this feature, but I don't see how the pricing model will allow it. The Amazon Lex API costs $0.004 per request. If you stream the audio, how do you define one request? 

The Amazon Transcribe (streaming API) is charged by the time. Unless Lex adopts the same pricing model as Transcribe, we won't be allowed to stream audio into Lex.
