### ISSUE TITLE
Linux C++ Polly

### ISSUE THREAD

**Issue by EArminjon** [aws/aws-sdk-cpp#950]
Hello,

i tried to use Polly API with aws sdk C++ (11).

I am following https://aws.amazon.com/fr/blogs/developer/cross-platform-text-to-speech-for-c-with-amazon-polly/ so my code is a copy/paste.

When i tried to list available voices i have any result or : 
aws-cpp-sdk-core/source/utils/json/JsonSerializer.cpp:488: aws::Utils::Array<Aws::Utils::Json::JsonView> Aws::Utils::Json::JsonView::GetArray(const String&) const: Assertion `cJSON_IsArray(array)' failed.

I don't understand why, can you help me ?

**Comment by marcomagdy** [comment]
We’re releasing a patch today.

**Comment by zodgevaibhav** [comment]
Thank you for quick response 👍

**Comment by marcomagdy** [comment]
Fixed in v1.6.7
Let us know if you're still having problems.
