### ISSUE TITLE
How to we obtain speech text  by aws-sdk

### ISSUE THREAD

**Issue by cresppo** [aws/aws-sdk-cpp#951]

**Comment by cresppo** [comment]
We hope to get the text after voice recognition.
 Such as we say "Alexa, what time is it"
 We would link to know how to get "what time is it"

**Comment by marcomagdy** [comment]
Please use this forum to report bugs/features.

**Comment by cresppo** [comment]
Dear Marco Magdy, How to navigate to bugs/features?
