### ISSUE TITLE
Response truncated

### ISSUE THREAD

**Issue by mattyouill** [aws/aws-sdk-cpp#952]
Hi,

I have a strange issue with the http client I was hoping you could help me with.

I am running an s3 "select object content" request using the c++ http client (not the s3 client as its not yet supported). I'm encountering a problem when using 36 processes in parallel to download ~750MB+ of data in several parts.

It works well for smaller numbers of processes (I have tested up to 8) but when running with a larger number, like 36, some of the responses are truncated. That is to say... the request completes before I have received all the data. I am using a DataReceivedEventHandler to receive data as it arrives.

Strangely MakeRequest returns 200 before the DataReceivedEventHandler has received everything (but only with a lot of parallel processes).

It's implemented as a Python extension implemented in a C++ shared object. The processes are created in Python with each invoking the so. Build details below. Timeouts a very large and am using separate Aws::InitAPI(options); etc. for each invocation.

Any ideas?

### What platform/OS are you using?
Linux 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### What compiler are you using? what version?
Python 2.7.12
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

### What's your CMake arguments?
Python distutils invokes the following:

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ivenv/local/lib/python2.7/site-packages/numpy/core/include -Ibuild/thirdparty -I/usr/include/python2.7 -c scan/src/scan.cpp -o build/temp.linux-x86_64-2.7/scan/src/scan.o -std=c++11 -Ofast

c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/scan/src/scan.o /usr/local/lib/libaws-c-common.a /usr/local/lib/libaws-checksums.a /usr/local/lib/libaws-c-event-stream.a -laws-cpp-sdk-core -laws-cpp-sdk-s3 -laws-c-common -laws-checksums -laws-c-event-stream -o build/lib.linux-x86_64-2.7/scan.so

### Can you provide a TRACE level log? (sanitize any sensitive information)
It's very big :( Can perhaps send parts if useful?

**Comment by marcomagdy** [comment]
There're too many variables in this issue. It's hard to give any help without having access to a repro case and source code. That being said, we're working on official support for S3 select in the SDK. Hopefully that will resolve the issues you're having.

**Comment by marcomagdy** [comment]
can you provide code to reproduce on our end?

**Comment by mattyouill** [comment]
Code is under repository https://github.com/yxymit/s3filter

It's a research project so hasn't been set up to be easily navigable I'm afraid. That said, main areas of interest are:

- scan/src/scan.cpp - The C++ source file for the Python shared object (there is only one).
- s3filter/sql/native_cursor.py - An example of a Python class that invokes it. You simply feed it with an instance of the library (e.g. import scan) and you can then use select(s3key, s3sql).execute(callback) to run a query against s3 select. Bucket is hardcoded in C++ source at present so you will need to change that to experiment.
- build.sh - a build script of sorts.
- setup.py - config for compiling/linking scan.so.

Oh... and thanks :)

**Comment by mattyouill** [comment]
Have tested a plain s3 get object that follows (largely) the same code path and the issue does not occur. Am guessing it's something to do with the request sent to the s3 select endpoint or capturing the bytes that are returned.

**Comment by singku** [comment]
Can you get the trace level log of SDK itself when that happen?
