### ISSUE TITLE
Kinesis Enhanced fanout

### ISSUE THREAD

**Issue by JeffeApAlves** [aws/aws-sdk-cpp#954]
Linux

GCC 5.4

Cmake 3.5

I cannot subscribe to a Kinesis stream using the new Enhanced Fan-out feature because I did not found methods/types/etc as describe in this link

https://docs.aws.amazon.com/streams/latest/dev/building-enhanced-consumers-api.html

**Comment by marcomagdy** [comment]
Those APIs require HTTP 2.0 support. We're actively working on adding support for that.
