### ISSUE TITLE
Unable to find SynthesizeSpeechRequest method for 'WithSpeechMarkTypes' in Aws::TextToSpeechManager :: aws c++ sdk

### ISSUE THREAD

**Issue by zodgevaibhav** [aws/aws-sdk-cpp#956]
### What platform/OS are you using?
Windows

I am writing program to get SpeechMarks using c++ aws sdk. I am able to get audio stream using "Aws::TextToSpeech::TextToSpeechManager::SendTextToOutputDevice()".

But I am not able to find any method in TextToSpeechManager to get SpeechMarks.

Please let me know if I am missing anything.

**Comment by singku** [comment]
Hi, thanks for reporting this problem. Currently, the `SendTextToOutputDevice` function in `TextToSpeechManager` only accept a `text` and a `callback` as the input mainly for simplicity.

We will add `Consider supporting SynthesizeSpeechRequest as an input for TextToSpeechManager for enhanced visual experience` to our backlog.

**Comment by marcomagdy** [comment]
Also, PRs are welcome

**Comment by zodgevaibhav** [comment]
Closing the issue
