### ISSUE TITLE
How to obtain content(text) after voice recognition using aws-sdk-cpp?

### ISSUE THREAD

**Issue by cresppo** [aws/aws-sdk-cpp#957]

**Comment by singku** [comment]
Hi, please be more specific of your `issue` or `problem` If you found a bug or unexpected behavior when using SDK.
If you are looking for answers of `How to` like questions`, please take a look at 
https://aws.amazon.com/documentation/.
For this question: https://docs.aws.amazon.com/polly/latest/dg/what-is.html

**Comment by cresppo** [comment]
Hi, singku,
I want to get the text of alexa speech recognition through aws-sdk(cpp). What are the suitable interfaces?
