### ISSUE TITLE
Dynmodb repeated putitem request crashesh

### ISSUE THREAD

**Issue by ubuntudeveloper** [aws/aws-sdk-cpp#959]
Hi, 

After some hiccups i have a CPP program instantiating an dynamodb client object and putitem api is called repeatedly( in while loop based on packet listener ) to insert one item in dynamodb table at a time.

For few minutes this it works fine.

The problem is after few minutes of this activity my program crashes. I dont see any information in kern.log or syslog file about it. 

my question is 
1. Do i need to free the dynamodb client after every putitem request? Are there any memory leak issues with this SDK?
2. Are there any timeouts which requires clients to recreate the dybnamodb object after certain duration of activity/inactivity?

### What platform/OS are you using?
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
### What compiler are you using? what version?

gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)

### What's your CMake arguments?

cmake version 3.5.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

### Can you provide a TRACE level log? (sanitize any sensitive information)
kern.log file dump?

**Comment by singku** [comment]
To answer your question.
1. No, otherwise, it's dumb. Currently SDK is tested with address sanitizer and a simple memory management system. There is no memory leak.
2. Timeout would cause underlying AWSClient to retry request until failed the retry strategy. You don't need to recreate dynamodb client.

To better investigate, please be more specific of your problem. `crash` how? Do you have `core dump`? Do you have `dmesg log`? Did you identified any suspicious aws log (please refer to ReadMe to find out how to generate trace level log)?

**Comment by ubuntudeveloper** [comment]
Ok, will share the log shortly. But before that i also wanted to try the gdb debugger on my application.
Do you know how to pass the Debug option for compilation usning Make command in Cmakefiles?

**Comment by singku** [comment]
cmake -DCMAKE_BUILD_TYPE=Debug

**Comment by ubuntudeveloper** [comment]
which file to include this in?

**Comment by singku** [comment]
Just add this command line option to CMake when running your CMake scripts.

**Comment by pgeadas** [comment]
Hi there!

Found out this thread after searching for a long time and I have the exact same issue. My application (Java) works fine for several minutes, but after that it just stops responding. 

I am also doing several putItem requests in a loop and the only thing that changes from one request to the other is a username (which I am checking to be correct). After the app crash, I just restart the process and he completes fine, picking up the list from the last successful username, so I am sure it is not a problem with the request being invalid or corrupted...

My first thought was exactly what @ubuntudeveloper thought, some kind of thread problem or memory leak... I get absolutely no exception or feedback from the SDK, so I'm in the dark about what can the problem be.

Any ideas on how to debug this? Thank you...

**Comment by maxritter** [comment]
I am having exactly the same problem, and it's really a pain in the ass as this system is running in production now.. 
Every minute, I am executing a DynamoDB query. More or less randomly, the application crashes during the execution of that query. In that case I am restarting it automatically, but it's of course not a good solution.
Sometimes, it can take hours for the application to crash, and sometimes it's within a couple of minutes.

I am not able to get a core dump to find the root of this problem, it crashes without any error and any possibility to create that dump.. 

Any help on this?

**Comment by maxritter** [comment]
@singku Thanks for your fast answer.
I am using the latest version 1.6.51 of the SDK, running on an armhf target (Raspi 3 B+).

dmesg does not give any output. If I run the program with GDB, I get the following:

```
It's time to update our reservations..
Thread 36 "terminal_server" received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x68cff190 (LWP 29014)]
0x747b6314 in write () from /lib/arm-linux-gnueabihf/libpthread.so.0
(gdb) backtrace
#0  0x747b6314 in write () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x76950338 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.2
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Which corresponds to this code:
```
cout << "It's time to update our reservations.." << endl;

/* Create the query request */
Aws::DynamoDB::Model::QueryRequest req;

/* Set the table attributes for our query */
req.SetTableName(DB_RESERVATION_TABLE_NAME);
req.SetIndexName("LocationIndex");
req.SetKeyConditionExpression("locationId = :locationval AND #L > :timestampval");

/* Fill in our expression attribute values */
Aws::Map<Aws::String, Aws::DynamoDB::Model::AttributeValue> expressionAttributeValues;
Aws::DynamoDB::Model::AttributeValue location_attribute_value;
location_attribute_value.SetN(to_string(location_id).c_str());
expressionAttributeValues[":locationval"] = location_attribute_value;
Aws::DynamoDB::Model::AttributeValue timestamp_attribute_value;
timestamp_attribute_value.SetN(to_string(last_update_time).c_str());
expressionAttributeValues[":timestampval"] = timestamp_attribute_value;
req.SetExpressionAttributeValues(expressionAttributeValues);

/* Replace protected names */
Aws::Map<Aws::String, Aws::String> expressionAttributeNames;
expressionAttributeNames["#L"] = "timestamp";
req.SetExpressionAttributeNames(expressionAttributeNames);

/* Excecute the query */
auto query_result = db_client->Query(req);

/* Go through the results */
if (query_result.IsSuccess())
{
   ...
}
```

Thanks for any help on this, I am really stuck here..

**Comment by singku** [comment]
@maxritter You need to set up sigPipe handler.
```
Aws::SDKOptions options;
options.HttpOptions.installSigPipeHandler = true;
````
https://github.com/aws/aws-sdk-cpp/blob/2756f9c5da4b2ab2a5264659106d138d9cab9635/aws-cpp-sdk-core/include/aws/core/Aws.h#L94

**Comment by maxritter** [comment]
@singku Thank you very much, this has solved the issue for me!

**Comment by jean343** [comment]
Note that it is using a lowercase `h`.
```
options.httpOptions.installSigPipeHandler = true;
```
