### ISSUE TITLE
Blown out of the water by change of JSON implementation

### ISSUE THREAD

**Issue by bppnw** [aws/aws-sdk-cpp#966]
Hello,

This is as much a question as an RFE: I recently made the switch from SDK 1.4.5 to SDK 1.6.3.  Or at least, I'm still in the middle of making the switch.  I had written a significant amount of code against the JSON implementation present in 1.4.5 (based on JsonCpp), and was absolutely blown out of the water by the change to cJSON in the newer versions.  It would be one thing to simply rewrite all my impacted code for the new APIs, except I need to main compatibility with both variants.  The approach I'm looking into is wrapping both APIs with my own constant API wrapper to insulate myself from this type of API change.  It would be ideal if there was a compile-time macro I could use to facilitate this (e.g. #ifdef AWS_JSON_V2).

If there are any better suggestions on how I can maintain SDK version portability with respect to the JSON implementation, please let me know.

### What platform/OS are you using?
macOS 10.13.6 and SDK v1.4.5, v1.6.3

### What compiler are you using? what version?
clang-902.0.39.2

### What's your CMake arguments?
-DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="iot;iot-data;dynamodb;sqs" -DCUSTOM_MEMORY_MANAGEMENT=0 -DBUILD_SHARED_LIBS=ON -DENABLE_TESTING=OFF -DCURL_INCLUDE_DIR=/opt/local/include/curl -DCURL_LIBRARY=/opt/local/lib/libcurl.dylib -DENABLE_COMMONCRYPTO_ENCRYPTION=OFF -DENABLE_OPENSSL_ENCRYPTION=ON

**Comment by bppnw** [comment]
Thanks for the reply.  I understand the rationale and appreciate the benefits of moving to the reduced-copy view interface.  It's a better interface, and I laud this team for the continued evolution of this SDK.

Ideally, a common set of operators (such as subscript) and consistent error-handling (prefer exceptions over embedded "abort()", etc.) would reduce the effort and side-effects involved in migrating.

Also, it looks like the cJSON wrapper is missing some functionality.  For example, there is no JsonValue::AsNull() method.

**Comment by JonathanHenson** [comment]
Unfortunately, Json null is something aws has never been able to come up with a coherent semantic for. In general, if you want null behavior, just leave the field out of the document.... and yeah I know that’s the dynamic typing way of doing things, but it is what it is.

**Comment by marcomagdy** [comment]
>Also, it looks like the cJSON wrapper is missing some functionality. For example, there is no JsonValue::AsNull() method.

We can easily add that. We probably missed it because had a need for it. I can understand though if you're using the SDK in an application, you want to use the same JSON class for the entire application, and your use case might have a need for `AsNull()`.

**Comment by bppnw** [comment]
> Unfortunately, Json null is something aws has never been able to come up with a coherent semantic for. In general, if you want null behavior, just leave the field out of the document.... and yeah I know that’s the dynamic typing way of doing things, but it is what it is.

If I want to explicitly erase state in a shadow document, don't I need to explicitly set & send a null?  e.g. {"state":{"reported":{null}}}

**Comment by JonathanHenson** [comment]
Yes, but In this case you own the service and the client (we don’t have some service processing and validating your data with a type in between) my point was that aws goes over a strongly typed model on the other side. This definitely makes sense as legitimate use case.
