### ISSUE TITLE
Returned string from Lex unable to be parsed: cJSON_IsString

### ISSUE THREAD

**Issue by rdesmond1991** [aws/aws-sdk-cpp#967]
Returned string from Lex unable to be parsed after updating past the following commit

Built version is commit: 963c7ecc09e4f8363abd47d58fcd22f2b2541d68
Issue introduced in commit: 3f4654721911915d76c3e3a1a50eb46da86eb579

/opt/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/json/JsonSerializer.cpp:414: Aws::String Aws::Utils::Json::JsonView::AsString() const: Assertion `cJSON_IsString(m_value)' failed.

### Reproduce
1. Create the BookTrip Lex bot using the sample app on Amazon Lex get started page
2. Release the BookTrip Lex bot with Alias as Demo
3. Follow the SDK to create a Service Client
4. Create an IAM user with the LexBot permissions
5. Insert your IAM credentials in ~/.aws/credentials
6. Compile the main.cpp file included (change the config.region) with the aws-core and aws-lex libraries
7. Attempt to run
[lex_json_main.tar.gz](https://github.com/aws/aws-sdk-cpp/files/2381263/lex_json_main.tar.gz)

### What platform/OS are you using?
Ubuntu Docker on OSx

### What compiler are you using? what version?
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

### What's your CMake arguments?
-DBUILD_ONLY="lex"
### Can you provide a TRACE level log? (sanitize any sensitive information)
__GI_raise 0x00007f842b056428
__GI_abort 0x00007f842b05802a
__assert_fail_base 0x00007f842b04ebd7
__GI___assert_fail 0x00007f842b04ec82
Aws::Utils::Json::JsonView::AsString[abi:cxx11]() const 0x00007f842c096e73
Aws::LexRuntimeService::Model::PostTextResult::operator=(Aws::AmazonWebServiceResult<Aws::Utils::Json::JsonValue> const&) 0x00007f842bc2dd2c
Aws::LexRuntimeService::Model::PostTextResult::PostTextResult(Aws::AmazonWebServiceResult<Aws::Utils::Json::JsonValue> const&) 0x00007f842bc2da99
Aws::LexRuntimeService::LexRuntimeServiceClient::PostText(Aws::LexRuntimeService::Model::PostTextRequest const&) const 0x00007f842bc17501
main main.cpp:63
__libc_start_main 0x00007f842b041830
_start 0x0000000000423ae9

**Comment by wps132230** [comment]
Thank you for feedback, we made a fix in  https://github.com/aws/aws-sdk-cpp/commit/35c7eeb352caa309914e436a67b50adf581d22b9

**Comment by rdesmond1991** [comment]
Confirmed :) thank you!
