### ISSUE TITLE
Store downloaded files into specific folder

### ISSUE THREAD

**Issue by noyruto5** [aws/aws-sdk-cpp#971]
The sample code for downloading file of from s3 bucket of aws documentation are storing only to the current directory where the code files reside. I have sub folder name "enroll" and I want to store the downloaded files into that folder.

This is the code snippet for opening a directory using dirent.h library:

//=================
DIR *pdir = NULL;
pdir = opendir("enroll");
struct dirent *pent = NULL;

And this is the code snippet from sample code of aws docs. Storing file into pc.
//=================
auto get_object_outcome = s3_client.GetObject(object_request);
if (get_object_outcome.IsSuccess())
{
	Aws::OFStream local_file;
	local_file.open(key_name.c_str(), std::ios::out | std::ios::binary);
	local_file << get_object_outcome.GetResult().GetBody().rdbuf();
	std::cout << "Done!" << std::endl;
}

Does anyone have an idea about this? 
Thank you.

**Comment by crusader-mike** [comment]
Specify full (or relative) pathname (to your file) to `open()` method.

**Comment by noyruto5** [comment]
like this one?
local_file.open("folder_name\\" + key_name.c_str(), std::ios::out | std::ios::binary);

**Comment by noyruto5** [comment]
Oh I got it now:
local_file.open(("enroll/" + key_name).c_str(), std::ios::out | std::ios::binary);

Thanks.
