### ISSUE TITLE
Polly: Missing Authentication Token, when called from CGI script

### ISSUE THREAD

**Issue by dreaming-augustin** [aws/aws-sdk-cpp#972]
# Summary 

I am still struggling with the very basics of using aws-sdk-cpp for Amazon Polly.

Thanks to https://github.com/kPanesar/aws-cpp-sdk-example , I did manage to have a very basic successful call to SynthesizeSpeech(). However, the same call that works works well from a CLI script does not work when the code in embedded within my cgi script run by the web server: I always get the exception: "Missing Authentication Token". 

The problem is obviously related to providing the proper credentials. I have carefully consulted the page:  https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/credentials.html and other related documentation.    

I have found a workaround that is acceptable for my needs, so I am personally ok for now, but I am still puzzled as to why my original attempts were not successful, especially since, as far as I am aware, I had met the documented credential requirements... I still don't know whether I missed something, and I made a mistake in my code, or whether the documentation is erroneous or the aws-sdk-cpp buggy in some way. I admit that the former possibility is much more likely, but then, this may be an opportunity to improve the related documentation...  

# Code 

## Working attempt (CLI)
```
#include <aws/core/Aws.h>
#include <aws/polly/PollyClient.h>
#include <aws/core/utils/Outcome.h>
#include <aws/polly/model/SynthesizeSpeechRequest.h>
#include <iostream>

int main() {
        Aws::SDKOptions options;
        Aws::InitAPI(options);
        {

                auto client = Aws::Polly::PollyClient();
                auto speechRequest = Aws::Polly::Model::SynthesizeSpeechRequest();
                speechRequest.SetText("Missing Authentication Token");
                auto voiceId = Aws::Polly::Model::VoiceIdMapper::GetVoiceIdForName("Matthew");
                speechRequest.SetVoiceId(voiceId);
                auto outputFormat = Aws::Polly::Model::OutputFormatMapper::GetOutputFormatForName("mp3");
                speechRequest.SetOutputFormat(outputFormat);


                auto speechOutcome = client.SynthesizeSpeech(speechRequest);
                if (!speechOutcome.IsSuccess()) {
                        auto error = speechOutcome.GetError();
                        std::cout << error << std::endl;
                }
                else {
                        std::cout << "Success" << std::endl;
                }

        }
        Aws::ShutdownAPI(options);
        return 0;
}
```

The above code works when compiled and run independently from the CLI. 
`~/.aws/credentials` is properly configured, with the proper aws_access_key_id and aws_secret_access_key. 

## Failed attempt (CGI)

The same code as above fails when embedded within my C++ fastCGI script running as a web server under Apache. Obviously, the server is run under the user `apache` which does not have a $HOME directory, so, as per the documentation, I endeavoured to set the proper environment variables. 

For this I used the `SetEnv` directive as per the Apache documentation. 

```
<VirtualHost *:80>
        ServerAdmin webmaster@127.0.0.1
        ServerName polly.test 
        SetEnv aws_access_key_id XXX
        SetEnv aws_secret_access_key XXX
        FastCgiExternalServer /path/to/my_script.fcgi -socket /tmp/my-script-fcgi 
       ... 
</VirtualHost>
```

I know that the environment variables are properly set, since I can access them from within my script. Still, debugging output always show that calls to Amazon Polly always result with the exception "Missing Authentication Token".  

I don't know if it's relevant, but the script is actually a Shared Object (.so file) dynamically loaded by the main fastCGI script that handles all the web server requests.  

Besides the fact that it's compiled as a shared object, the cmake options for Polly are the same as for my CLI script. The c++ code is also identical.

## Workaround (CGI)

After much struggling and searching (often in the wrong direction), I finally found a workaround by delving deeper within the available documentation. 
 
Instead of having the Poly client default initialized: 

```
        Aws::SDKOptions options;
        Aws::InitAPI(options);
        {
                auto client = Aws::Polly::PollyClient();
                // ...
         }
```

I initialize it explicitly  with a `AWSCredentials` object: 

```

                Aws::SDKOptions options;
                Aws::InitAPI(options);
                {
                        // Proof that the environment variables are properly set, 
                        // because I can access them here:
                        auto key_id = request.cgetenv("aws_access_key_id");
                        auto key = request.cgetenv("aws_secret_access_key");
                        Aws::Auth::AWSCredentials credentials = Aws::Auth::AWSCredentials(key_id, key);
                        auto client = Aws::Polly::PollyClient(credentials);
                       // ....
                }
```

https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/credentials.html does mention:

> You can also supply AWS credentials using your own methods by providing credentials to an AWS client class constructor.

which is what prompted me to finally look in the right direction for the workaround. 

However, I still don't know why setting the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables, as also mentioned, was not enough... 

# Other information 
### What platform/OS are you using?
Linux/gentoo 

### What compiler are you using? what version?
$ gcc --version
gcc (Gentoo 6.4.0-r1 p1.3) 6.4.0

### What's your CMake arguments?
cmake -DBUILD_ONLY="polly"

**Comment by singku** [comment]
Surely you can read environment variable aws_access_key_id from your code and pass it to creds class,  because you set it up correctly in your fast cgi configuration. But the environment variable needed by SDK is uppercase AWS_ACCESS_KEY_ID.

**Comment by dreaming-augustin** [comment]
Thank you for the prompt response. The case does not appear to make any difference.

Actually, I had started by setting the variables in upper case as per the documentation. Seeing that the fastCGI script didn't work while the CLI script did, I endeavoured to remove all differences, however slight. I noticed that the aws script I used to set up my environment had automatically configured `~/.aws/credentials` with variables in lower case, so I tried to copy the lower case style for my Apache environment, and this is the version you see above.

After reading your comment, I tried again. I get the same results as before. The following, with upper case variable names, works:

```
auto key_id = request.cgetenv("AWS_ACCESS_KEY_ID");
auto key = request.cgetenv("AWS_SECRET_ACCESS_KEY");
Aws::Auth::AWSCredentials credentials = Aws::Auth::AWSCredentials(key_id, key);
auto client = Aws::Polly::PollyClient(credentials);
```

while this still does not:
```
auto client = Aws::Polly::PollyClient();
```

**Comment by singku** [comment]
Okay, so I assume you did this to set up fast cgi:
```
<VirtualHost *:80>
        ServerAdmin webmaster@127.0.0.1
        ServerName polly.test 
        SetEnv AWS_ACCESS_KEY_ID XXX
        SetEnv AWS_SECRET_ACCESS_KEY XXX
        FastCgiExternalServer /path/to/my_script.fcgi -socket /tmp/my-script-fcgi 
       ... 
</VirtualHost>
```

And this in your C++ code
```
        Aws::SDKOptions options;
        Aws::InitAPI(options);
        {
                auto client = Aws::Polly::PollyClient();
                // ...
         }
```
But it didn't work.

Could you please try again with everything the same as above except setting up the trace level log of C++ SDK and see what's there in the log? Better to upload the log file here.
By:
```
        Aws::SDKOptions options;
        options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
        Aws::InitAPI(options);
        {
                auto client = Aws::Polly::PollyClient();
                // ...
         }
```

There should be an aws_sdk_[date].log file in current working directory of cgi executable.

Also just a reminder for you that. When talking about `CLI` in AWS domain, we usually mean AWS SDK Python/CLI. And we don't normally treat C++ code as script. Here I believe what you mean by working CLI scripts is executing binary from command line, and this binary is compiled from a C++  source code. I was initially a little bit confused by your original issue.

**Comment by dreaming-augustin** [comment]
I am sorry about the confusion. Indeed, I shouldn't have referred to a c++ compiled binary as a script. My mistake, sorry. (English is not my native language, and I am not a full time, professional software developer). So yes, I started with the c++ code posted at the top, which I compiled and ran from within my bash (shell) environment. 

The Apache VirtualHost is configured as you indicate. Here is the requested log.
[aws_sdk_2018-09-19-00.log](https://github.com/aws/aws-sdk-cpp/files/2394986/aws_sdk_2018-09-19-00.log)

**Comment by dreaming-augustin** [comment]
The library I am using is cppcms. The method that I am using to access the environment variables is this one:
http://cppcms.com/cppcms_ref/latest/classcppcms_1_1http_1_1request.html#aafe770ee0e5be833b50ae6998e74b69a

`char const* cppcms::http::request::cgetenv     (       char const *            )       `

> Get CGI environment variable by name. Returns empty string if the variable is not set

I mention this just for the sake of completeness, just in case in provides any insight. I perfectly understand that it is not your role to debug my application, nor the  cppcms  library, nor the fastCGI protocol.  If you suspect that the aws-sdk-cpp works perfectly as designed, feel free to close this issue. Maybe one day I'll figure it out. As mentioned, I have an alternative for the time being. I'd simply hate wasting your time.

If on the other hand, there is still the possibility that aws-sdk-cpp (or the documentation) is at fault, and if you care about solving this which may be, after all, a corner case, then I am happy to work with you, and perform any requested test, including recompiling the sdk with other options, or with a patch applied.

**Comment by dreaming-augustin** [comment]
There is one place where I was indeed referring to the Python script. I wrote:

>  I noticed that the aws script I used to set up my environment had automatically configured `~/.aws/credentials` with variables in lower case (...)

I had actually run: 
`$  pip install awscli --upgrade --user `
then
`$ aws configure`
which is the script I referred to that configured `~/.aws/credentials` and the script that set up the credential variables in lower case. 

In other places, I should have referred to a c++ compiled binary run from the bash shell.

**Comment by singku** [comment]
Based on the log, CPP SDK didn't find those system environment variables.
And based on Apache doc about cgi environment variables. https://httpd.apache.org/docs/2.4/env.html
These CGI environment variables are not the same as system environment variables.
> They only become actual operating system environment variables when they are provided to CGI scripts and Server Side Include scripts

As you stated above that the `cppcms` library actually reads cgi environment variables. This kind explain why did that work.

Maybe you had a miss here to upgrade them as environment variables.
