### ISSUE TITLE
a question about aarch64-linux compile SDK fail, it seems shared-lib not found but I can't find any problem. 

### ISSUE THREAD

**Issue by shenhuaz** [aws/aws-sdk-cpp#980]
### What platform/OS are you using?
OS Ubuntu 16.04
### What compiler are you using? what version?
cmake 3.5 
curl 7.61.1 
openssl 1.1.1 
zlib 1.2.11

### What's your CMake arguments?

At first, I add these in CMakeList.txt: 
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER "/usr/local/linaro-aarch64-2017.08-gcc7.1/bin/aarch64-linux-gnu-gcc")
set(CMAKE_CXX_COMPILER "/usr/local/linaro-aarch64-2017.08-gcc7.1/bin/aarch64-linux-gnu-g++")
set(CMAKE_FIND_ROOT_PATH  "/home/payne/aarch-aws-env") // this path I install curl / openssl / zlib .

And Cmake argument:
cmake /home/payne/Downloads/aws-sdk-cpp-master -DBUILD_ONLY="s3;transfer;core" -DCMAKE_PREFIX_PATH=/home/payne/aws-install

-- Found Git: /usr/bin/git (found version "2.7.4") 
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating linux build config
fatal: Not a git repository: '/home/payne/Downloads/aws-sdk-cpp-master/.git'
-- Building project version: 1.6.18
-- The CXX compiler identification is GNU 7.1.1
-- Check for working CXX compiler: /usr/local/linaro-aarch64-2017.08-gcc7.1/bin/aarch64-linux-gnu-g++
-- Check for working CXX compiler: /usr/local/linaro-aarch64-2017.08-gcc7.1/bin/aarch64-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /home/payne/aarch-aws-env/lib/libz.so (found version "1.2.11") 
--   Zlib include directory: /home/payne/aarch-aws-env/include
--   Zlib library: /home/payne/aarch-aws-env/lib/libz.so
-- Encryption: Openssl
-- Found OpenSSL: /home/payne/aarch-aws-env/lib/libssl.so;/home/payne/aarch-aws-env/lib/libcrypto.so (found version "1.1.1") 
--   Openssl include directory: /home/payne/aarch-aws-env/include
--   Openssl library: /home/payne/aarch-aws-env/lib/libssl.so;/home/payne/aarch-aws-env/lib/libcrypto.so
-- Http client: Curl
-- Found CURL: /home/payne/aarch-aws-env/lib/libcurl.so (found version "7.61.1") 
--   Curl include directory: /home/payne/aarch-aws-env/include
--   Curl library: /home/payne/aarch-aws-env/lib/libcurl.so
-- Performing Test HAVE_ATOMICS_WITHOUT_LIBATOMIC
-- Performing Test HAVE_ATOMICS_WITHOUT_LIBATOMIC - Success
-- Considering s3
-- Considering transfer
-- Considering core
-- The C compiler identification is GNU 7.1.1
-- Check for working C compiler: /usr/local/linaro-aarch64-2017.08-gcc7.1/bin/aarch64-linux-gnu-gcc
-- Check for working C compiler: /usr/local/linaro-aarch64-2017.08-gcc7.1/bin/aarch64-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Updating version info to 1.6.18
-- Custom memory management enabled; stl objects now using custom allocators
-- Configuring done
-- Generating done
-- Build files have been written to: /home/payne/aws_make
payne@38EN1590:~/aws_make$ make install
Scanning dependencies of target aws-cpp-sdk-core
[  0%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/Aws.cpp.o
[  0%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/AmazonSerializableWebServiceRequest.cpp.o

### Can you provide a TRACE level log? (sanitize any sensitive information)
.......
[ 89%] Building CXX object testing-resources/CMakeFiles/testing-resources.dir/source/TestingEnvironment.cpp.o
[ 89%] Building CXX object testing-resources/CMakeFiles/testing-resources.dir/source/MemoryTesting.cpp.o
[ 89%] Building CXX object testing-resources/CMakeFiles/testing-resources.dir/source/external/gtest-all.cc.o
[ 89%] Building CXX object testing-resources/CMakeFiles/testing-resources.dir/source/platform/linux-shared/PlatformTesting.cpp.o
[ 90%] Linking CXX shared library libtesting-resources.so
[ 90%] Built target testing-resources
Scanning dependencies of target aws-cpp-sdk-s3-integration-tests
[ 90%] Building CXX object aws-cpp-sdk-s3-integration-tests/CMakeFiles/aws-cpp-sdk-s3-integration-tests.dir/BucketAndObjectOperationTest.cpp.o
[ 91%] Building CXX object aws-cpp-sdk-s3-integration-tests/CMakeFiles/aws-cpp-sdk-s3-integration-tests.dir/RunTests.cpp.o
[ 91%] Linking CXX executable aws-cpp-sdk-s3-integration-tests
/usr/local/linaro-aarch64-2017.08-gcc7.1/bin/../lib/gcc/aarch64-linux-gnu/7.1.1/../../../../aarch64-linux-gnu/bin/ld: warning: libcurl.so.4, needed by ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so, not found (try using -rpath or -rpath-link)
/usr/local/linaro-aarch64-2017.08-gcc7.1/bin/../lib/gcc/aarch64-linux-gnu/7.1.1/../../../../aarch64-linux-gnu/bin/ld: warning: libssl.so.1.1, needed by ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so, not found (try using -rpath or -rpath-link)
/usr/local/linaro-aarch64-2017.08-gcc7.1/bin/../lib/gcc/aarch64-linux-gnu/7.1.1/../../../../aarch64-linux-gnu/bin/ld: warning: libcrypto.so.1.1, needed by ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so, not found (try using -rpath or -rpath-link)
/usr/local/linaro-aarch64-2017.08-gcc7.1/bin/../lib/gcc/aarch64-linux-gnu/7.1.1/../../../../aarch64-linux-gnu/bin/ld: warning: libz.so.1, needed by ../aws-cpp-sdk-core/libaws-cpp-sdk-core.so, not found (try using -rpath or -rpath-link)
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `EVP_CIPHER_CTX_ctrl@OPENSSL_1_1_0'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `curl_easy_reset'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `EVP_md5@OPENSSL_1_1_0'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `EVP_sha256@OPENSSL_1_1_0'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `ERR_get_error@OPENSSL_1_1_0'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `EVP_DecryptUpdate@OPENSSL_1_1_0'
../aws-cpp-sdk-core/libaws-cpp-sdk-core.so: undefined reference to `EVP_CIPHER_CTX_copy@OPENSSL_1_1_0'
........

**Comment by shenhuaz** [comment]
I found it is the issue that compile integration test will meet , and maybe some problem of my tool-chain, build shared-library no problem. so I will close it.

**Comment by abhijitnathwani** [comment]
Hi @shenhuaz 
I'm facing the same problem. Could you please let us know the steps you used to fix this?

**Comment by shenhuaz** [comment]
Hello @abhijitnathwani 
Integration tests build failed had no influence for me, I can still use cpp sdk shared libs when I meet this error because the shared libs already created. In addition,  I put those not found libs (curl, openssl....and so on) into my toolchain/lib dir, then I can build success, maybe it can help you.

**Comment by abhijitnathwani** [comment]
Hi @shenhuaz 
That still does not help.
If I ignore the `integration-tests` failure, i cannot run `make install`. It throws errors.
Alternatively, I also added the `.so` files in `toolchain/lib` but the error still remains.
Do you have any exact steps I could use? That'd be helpful.

**Comment by shenhuaz** [comment]
hi @abhijitnathwani  
maybe you can use argument -DENABLE_TESTING=OFF when cmake, it can disable Integration Test.
BTW, I don't use make install and I just find .so in build folder and copy it to my install folder(create include and lib by myself).

**Comment by abhijitnathwani** [comment]
@shenhuaz 
Thank you! That works well.
