### ISSUE TITLE
Macros redefinition while using AWS SDK C++ together with JsonCpp

### ISSUE THREAD

**Issue by yanykin** [aws/aws-sdk-cpp#982]
### What platform/OS are you using?
Windows 10 Enterprise, version 1709, build 16299.431

### What compiler are you using? what version?
Microsoft Visual Studio 2013

I am working on project which depends both on AWS SDK C++ and JsonCpp. Eventually I found out that there's a `JSON_USE_EXCEPTION` macros redefinition when you try to include `aws\core\SDKConfig.h` after `json\config.h`. Since AWS SDK C++ uses its own "amalgamated" version of JsonCpp stored in only one header `aws\aws-cpp-sdk-core\include\aws\core\external\json-cpp\json.h` and almost all macroses have `AWS_` prefix, it would probably worth to add this prefix to mentioned macros too for preventing such behavior.

**Comment by singku** [comment]
Hi thanks for bring this up. We have replaced Jsoncpp with CJson in latest SDK. Is that possible for you to update?

**Comment by wps132230** [comment]
Please reopen this issue if you still have questions.
