### ISSUE TITLE
OPENSSL_INCLUDE_DIRS instead of OPENSSL_INCLUDE_DIR

### ISSUE THREAD

**Issue by SimonEbner** [aws/aws-sdk-cpp#987]
Should this line not be replaced by `${OPENSSL_INCLUDE_DIR}` instead of `${OPENSSL_INCLUDE_DIRS}` ?

https://github.com/aws/aws-sdk-cpp/blob/2612d49dc31da2356361ccc4abe5bb7278250561/cmake/external_dependencies.cmake#L51

This is also the directory printed in the previous line
https://github.com/aws/aws-sdk-cpp/blob/2612d49dc31da2356361ccc4abe5bb7278250561/cmake/external_dependencies.cmake#L48

**Comment by wps132230** [comment]
It should be `OPENSSL_INCLUDE_DIR`.
Thank you for you feedback.

**Comment by singku** [comment]
Hi, this problem has been resolve in https://github.com/aws/aws-sdk-cpp/commit/892e4ccf58fdc772e291b29dc07a48a1b02d2d86
