### ISSUE TITLE
Very long creation time of object CognitoIdentityProviderClient

### ISSUE THREAD

**Issue by MrMoose** [aws/aws-sdk-cpp#990]
I am trying to login to a Cognito user pool using CognitoIdentityProviderClient(). The login process itself using SRP is OK, and fast enough but it takes between 10 and 14 seconds to instantiate an object of this type.

### What platform/OS are you using?

Windows 10

### What compiler are you using? what version?

Visual Studio 2017

### What's your CMake arguments?

Release build, Static Libs (with dynamic CRT), with RTTI, nothing fancy besides. Unity build was off

### Can you provide a TRACE level log? (sanitize any sensitive information)

Sadly, I don't have a debug build but only Release without PDBs.

It is simply this line though:

// or any other ptr type
cognito_client_ = std::make_shared<Aws::CognitoIdentityProvider::CognitoIdentityProviderClient>(clientConfig);

This instantiation takes between 10 and 14 seconds to complete.

**Comment by MrMoose** [comment]
I have just dumped a log of one of the tests. It suggests, several unsuccessful HTTP connections are tried and run into timeouts:

[INFO] 2018-10-15 12:54:12 EC2MetadataClient [5024] Creating AWSHttpResourceClient with max connections2 and scheme http
[INFO] 2018-10-15 12:54:12 WinHttpSyncHttpClient [5024] Creating http client with user agent aws-sdk-cpp/1.6.30 Windows/10.0.17134.228 AMD64 MSVC/1915 with max connections 2 request timeout 5000,and connect timeout 1000
[INFO] 2018-10-15 12:54:12 ConnectionPoolMgr [5024] Creating connection pool mgr with handle 000001CBB1035600, and max connections per host 2, request timeout 5000 ms, and connect timeout in 1000 ms.
[INFO] 2018-10-15 12:54:12 InstanceProfileCredentialsProvider [5024] Creating Instance with default EC2MetadataClient and refresh rate 300000
[INFO] 2018-10-15 12:54:12 DefaultAWSCredentialsProviderChain [5024] Added EC2 metadata service credentials provider to the provider chain.
[INFO] 2018-10-15 12:54:12 Aws::Config::AWSConfigFileProfileConfigLoader [5024] Unable to open config file C:\Users\sm\\.aws\credentials for reading.
[INFO] 2018-10-15 12:54:12 Aws::Config::AWSProfileConfigLoader [5024] Failed to reload configuration.
[INFO] 2018-10-15 12:54:12 Aws::Config::AWSConfigFileProfileConfigLoader [5024] Unable to open config file C:\Users\sm\\.aws\config for reading.
[INFO] 2018-10-15 12:54:12 Aws::Config::AWSProfileConfigLoader [5024] Failed to reload configuration.
[INFO] 2018-10-15 12:54:12 InstanceProfileCredentialsProvider [5024] Credentials have expired attempting to repull from EC2 Metadata Service.
[INFO] 2018-10-15 12:54:12 WinHttpConnectionPoolMgr [5024] Attempting to aquire connection for 169.254.169.254:80
[INFO] 2018-10-15 12:54:12 WinConnectionContainer [5024] Pool grown by 2
[INFO] 2018-10-15 12:54:12 WinHttpConnectionPoolMgr [5024] Connection now available, continuing.
[ERROR] 2018-10-15 12:54:12 WinHttpSyncHttpClient [5024] Failed to add HTTP request headers with error code: 12150
[WARN] 2018-10-15 12:54:12 WinHttpSyncHttpClient [5024] Send request failed: Die Serververbindung konnte nicht hergestellt werden.


[ERROR] 2018-10-15 12:54:12 EC2MetadataClient [5024] Http request to retrieve credentials failed
[WARN] 2018-10-15 12:54:12 EC2MetadataClient [5024] Request failed, now waiting 0 ms before attempting again.
[INFO] 2018-10-15 12:54:12 WinHttpConnectionPoolMgr [5024] Attempting to aquire connection for 169.254.169.254:80
[INFO] 2018-10-15 12:54:12 WinHttpConnectionPoolMgr [5024] Connection now available, continuing.
[ERROR] 2018-10-15 12:54:12 WinHttpSyncHttpClient [5024] Failed to add HTTP request headers with error code: 12150
[WARN] 2018-10-15 12:54:12 WinHttpSyncHttpClient [5024] Send request failed: Die Serververbindung konnte nicht hergestellt werden.


[ERROR] 2018-10-15 12:54:12 EC2MetadataClient [5024] Http request to retrieve credentials failed
[WARN] 2018-10-15 12:54:12 EC2MetadataClient [5024] Request failed, now waiting 2000 ms before attempting again.
[INFO] 2018-10-15 12:54:14 WinHttpConnectionPoolMgr [5024] Attempting to aquire connection for 169.254.169.254:80
[INFO] 2018-10-15 12:54:14 WinHttpConnectionPoolMgr [5024] Connection now available, continuing.
[ERROR] 2018-10-15 12:54:14 WinHttpSyncHttpClient [5024] Failed to add HTTP request headers with error code: 12150
[WARN] 2018-10-15 12:54:14 WinHttpSyncHttpClient [5024] Send request failed: Die Serververbindung konnte nicht hergestellt werden.


[ERROR] 2018-10-15 12:54:14 EC2MetadataClient [5024] Http request to retrieve credentials failed
[WARN] 2018-10-15 12:54:14 EC2MetadataClient [5024] Request failed, now waiting 4000 ms before attempting again.
[INFO] 2018-10-15 12:54:18 WinHttpConnectionPoolMgr [5024] Attempting to aquire connection for 169.254.169.254:80
[INFO] 2018-10-15 12:54:18 WinHttpConnectionPoolMgr [5024] Connection now available, continuing.
[ERROR] 2018-10-15 12:54:18 WinHttpSyncHttpClient [5024] Failed to add HTTP request headers with error code: 12150
[WARN] 2018-10-15 12:54:18 WinHttpSyncHttpClient [5024] Send request failed: Die Serververbindung konnte nicht hergestellt werden.


[ERROR] 2018-10-15 12:54:18 EC2MetadataClient [5024] Http request to retrieve credentials failed
[WARN] 2018-10-15 12:54:18 EC2MetadataClient [5024] Request failed, now waiting 8000 ms before attempting again.
[INFO] 2018-10-15 12:54:26 WinHttpConnectionPoolMgr [5024] Attempting to aquire connection for 169.254.169.254:80
[INFO] 2018-10-15 12:54:26 WinHttpConnectionPoolMgr [5024] Connection now available, continuing.
[ERROR] 2018-10-15 12:54:26 WinHttpSyncHttpClient [5024] Failed to add HTTP request headers with error code: 12150
[WARN] 2018-10-15 12:54:26 WinHttpSyncHttpClient [5024] Send request failed: Die Serververbindung konnte nicht hergestellt werden.


[ERROR] 2018-10-15 12:54:26 EC2MetadataClient [5024] Http request to retrieve credentials failed
[ERROR] 2018-10-15 12:54:26 EC2MetadataClient [5024] Can not retrive resource /latest/meta-data/iam/security-credentials
[INFO] 2018-10-15 12:54:26 Aws::Config::AWSProfileConfigLoader [5024] Failed to reload configuration.
[INFO] 2018-10-15 12:54:26 WinHttpSyncHttpClient [5024] Creating http client with user agent aws-sdk-cpp/1.6.30 Windows/10.0.17134.228 AMD64 MSVC/1915 with max connections 25 request timeout 3000,and connect timeout 1000
[INFO] 2018-10-15 12:54:26 ConnectionPoolMgr [5024] Creating connection pool mgr with handle 000001CBB107DAC0, and max connections per host 25, request timeout 3000 ms, and connect timeout in 1000 ms.
[INFO] 2018-10-15 12:54:26 WinHttpConnectionPoolMgr [5024] Attempting to aquire connection for cognito-idp.eu-central-1.amazonaws.com:443
[INFO] 2018-10-15 12:54:26 WinConnectionContainer [5024] Pool grown by 2

As I take it, it's trying to access the AWS internal magic IP 169.254.169.254 and fails as I run this code from the outside world.

**Comment by atlascoder** [comment]
I confirm same troubles on Android build:
* Call `MakeShared<CognitoIdentity::CognitoIdentityClient>` takes more than 15 sec!
* Call `MakeShared<CognitoIdentityProvider::CognitoIdentityProviderClient>` takes more than 10 sec!

Android libs build was configured by `cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="core;sts;iot;iam;identity-management;cognito-sync;cognito-idp;cognito-identity;access-management;logs;dynamodb" -DBUILD_SHARED_LIBS=OFF -DTARGET_ARCH=ANDROID -DENABLE_TESTING=OFF -DANDROID_STL=gnustl_shared -DNDK_DIR=/Libs/Android/android-ndk-r12b ..`

The project was working faster on the same Android phone before when I used some earlier version of the SDK.

Please, help..

**Comment by atlascoder** [comment]
One more observation - it work fast on MacOS. Maybe the source in new curl version? Because on MacOS it is build agains system curl dynamic lib.

**Comment by marcomagdy** [comment]
By default the service client will use `AWSCredentialsProviderChain` , which tries to get credentials from:
1. Environment variables
1. AWS credentials file (usually located under ~/.aws/credentials)
1. ECS metadata (assuming it's running on ECS)
1. Instance metadata (assuming it's running on EC2)

If you know what credentials and where to get them from, then it's best to specify that in the constructor.

**Comment by atlascoder** [comment]
Marco @marcomagdy, I don't use `AWSCredentialsProviderChain`. In my app I build credentials provider using my implementation of `Aws::Auth::PersistentCognitoIdentityProvider`:

```
    persistentCredentialsProvider = MakeShared<PersistentCredentialsProviderSQLite>(nullptr, AWS_IDENTITY_POOL, AWS_ACCOUNT_ID);

    identityClient = MakeShared<CognitoIdentity::CognitoIdentityClient>(nullptr, ClientConfig::instance());

    idpClient = MakeShared<Aws::CognitoIdentityProvider::CognitoIdentityProviderClient>(nullptr, ClientConfig::instance());

    mCredentialsProvider = MakeShared<CognitoCredentialsProvider>(
                nullptr,
                persistentCredentialsProvider,
                identityClient,
                idpClient
            );
```

How to fix this?

**Comment by marcomagdy** [comment]
@MrMoose 
> About your comment, yes after extensive research I came to a similar conclusion. But this required a lot of reading of code. The way I understand it, the purpose of this particular service is for outside world implementations to be able to log into a cognito pool. So there will not be any AWS credentials or metadata available.
> Which means that a) there should be a different default or b) there should be docs mentioning this.
> Would you agree with this?

I agree. Probably this default doesn't make much sense for Cognito specifically. I will review this and potentially add an exception in the code generator.

**Comment by marcomagdy** [comment]
@atlascoder  There are multiple constructor for the `CognitoIdentityClient` class.
```cpp
       /**
        * Initializes client to use DefaultCredentialProviderChain, with default http client factory, and optional client config. If client config
        * is not specified, it will be initialized to default values.
        */
        CognitoIdentityClient(const Aws::Client::ClientConfiguration& clientConfiguration = Aws::Client::ClientConfiguration());

       /**
        * Initializes client to use SimpleAWSCredentialsProvider, with default http client factory, and optional client config. If client config
        * is not specified, it will be initialized to default values.
        */
        CognitoIdentityClient(const Aws::Auth::AWSCredentials& credentials, const Aws::Client::ClientConfiguration& clientConfiguration = Aws::Client::ClientConfiguration());

       /**
        * Initializes client to use specified credentials provider with specified client config. If http client factory is not supplied,
        * the default http client factory will be used
        */
        CognitoIdentityClient(const std::shared_ptr<Aws::Auth::AWSCredentialsProvider>& credentialsProvider,
            const Aws::Client::ClientConfiguration& clientConfiguration = Aws::Client::ClientConfiguration());

```

Your code snippet above is using the first overload. You should be using the third overload; passing the credentials provider first then the configuration instance.

As far as the tag passed when heap allocating objects, that is useful when attempting to detect memory leaks.
An example of that usage is in the unit tests.

**Comment by atlascoder** [comment]
Marco @marcomagdy , thank you for the advice. But how can I do it if I want to get `CognitoIdentityClient` that uses `PersistentCognitoIdentityProvider` subclass? I don't have right `AWSCredentialsProvider` when I call `CognitoIdentityClient` - maybe I use wrong steps?

**Comment by MrMoose** [comment]
@atlascoder just out of curiosity, why don't you use Aws::Auth::AnonymousAWSCredentialsProvider like I posted a week ago. It works for me. Not an option?

**Comment by atlascoder** [comment]
Well, @MrMoose , thanks for suggestion - but what is the logic for me - I don't understand..
I need in result credentials provider that uses caching and persistent storage for tokens. Such clients incapsulates all routines for storing, restoring and updating tokens.

In my case I understand roles of the components:

`PersistentCredentialsProviderSQLite` - responsible for persistence of tokens in sqlite db

`CognitoIdentityClient` - needed to get identity Id and AWSCredentials using tokens

`CognitoIdentityProviderClient` - needed to get and refresh tokens for logins

`CognitoCredentialsProvider` - fuses others making all working automatically: refresh tokens and update persistence, retrieving credentials and caching them

What's the sense to use `Aws::Auth::AnonymousAWSCredentialsProvider` here?

Anyway, I observe delays on while creating `CognitoIdentityClient` and `CognitoIdentityProviderClient` - both.

**Comment by manishpin** [comment]
@atlascoder, not sure if you are still having issues here, I was experiencing similar problems with long times to create clients after upgrading to a newer version of the sdk, and found @MrMoose suggestion to work well. 

For anyone else who comes across this post, have you tried using:

```
Aws::Client::ClientConfiguration client_config;
std::shared_ptr<Aws::Auth::AnonymousAWSCredentialsProvider> anon_creds = std::make_shared<Aws::Auth::AnonymousAWSCredentialsProvider>();
auto cognito_identity_client_ = std::make_shared<Aws::CognitoIdentity::CognitoIdentityClient>(anon_creds, client_config);
```
And similarly for the `CognitoIdentityClient`. 

This cut my time from 30s to a couple of seconds. Hope it helps.
