### ISSUE TITLE
Errors when build for Android

### ISSUE THREAD

**Issue by atlascoder** [aws/aws-sdk-cpp#991]
Build fails on first run, but just re-run continues with warning and passes without errors.

### What platform/OS are you using?

MacOS 10.14

### What compiler are you using? what version?

clang 3.8

### What's your CMake arguments?

`cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="core;sts;iot;iam;identity-management;cognito-sync;cognito-idp;cognito-identity;access-management;logs;dynamodb" -DBUILD_SHARED_LIBS=OFF -DTARGET_ARCH=ANDROID -DENABLE_TESTING=OFF -DANDROID_STL=gnustl_shared -DNDK_DIR=/Library/Android/android-ndk-r12b ..`

### Can you provide a TRACE level log? (sanitize any sensitive information)

```
-- Performing Test HAVE_MSG_NOSIGNAL
-- Performing Test HAVE_MSG_NOSIGNAL - Success
-- Performing Test HAVE_STRUCT_TIMEVAL
-- Performing Test HAVE_STRUCT_TIMEVAL - Success
-- Performing Test HAVE_POLL_FINE
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   HAVE_POLL_FINE_EXITCODE (advanced)
   HAVE_POLL_FINE_EXITCODE__TRYRUN_OUTPUT (advanced)
For details see /Users/anton.titkov/DevLibs/aws-sdk-cpp/build-android/CURL-prefix/src/CURL-build/TryRunResults.cmake
-- Performing Test HAVE_POLL_FINE - Success
-- Check size of sig_atomic_t
-- Check size of sig_atomic_t - done
-- Performing Test HAVE_SIG_ATOMIC_T_NOT_VOLATILE
-- Performing Test HAVE_SIG_ATOMIC_T_NOT_VOLATILE - Success
-- Check size of struct sockaddr_storage
-- Check size of struct sockaddr_storage - done
-- Enabled features: OpenSSL IPv6 unix-sockets libz NTLM
-- Enabled protocols: DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS POP3 POP3S RTSP SMTP SMTPS TELNET TFTP
-- Configuring incomplete, errors occurred!
```

### Rerun

- starts with warning but completes successfully

```
loading initial cache file /Users/anton.titkov/DevLibs/aws-sdk-cpp/android-build/CurlAndroidCrossCompile.cmake
CMake Warning at CMakeLists.txt:49 (message):
  the curl cmake build system is poorly maintained.  Be aware


-- curl version=[7.52.1-DEV]
CMake Warning at CMakeLists.txt:224 (message):
  Found no *nroff program
```

**Comment by jkoutavas** [comment]
Any news on this front?

**Comment by atlascoder** [comment]
@jkoutavas look at this https://github.com/atlascoder/aws-sdk-cpp/commit/67ae16c2077928fd22bdfc5fb89f2c11a896af82

maybe this will help

**Comment by jkoutavas** [comment]
> @jkoutavas look at this [atlascoder@67ae16c](https://github.com/atlascoder/aws-sdk-cpp/commit/67ae16c2077928fd22bdfc5fb89f2c11a896af82)
> 
> maybe this will help

Thanks, @atlascoder. PR #1007 also covers this issue.

**Comment by singku** [comment]
Now we support latest NDK r19c (back to 13b) with their own toolchain files, 12b is not supported anymore. Please reopen if you still have problem.
