### ISSUE TITLE
Test FileSystem::CreateDirectoryIfNotExists fails in Windows 10

### ISSUE THREAD

**Issue by yanykin** [aws/aws-sdk-cpp#993]
### What platform/OS are you using?
Microsoft Windows 10 Enterprise 1709, build 16299.611

### What compiler are you using? what version?
Microsoft Visual Studio 12.0 (version of cl.exe: 18.0.31101.0)
Microsoft Visual Studio 2017 (version of cl.exe: 19.15.26730.0)

### What's your CMake arguments?
BUILD_ONLY = s3
CUSTOM_MEMORY_MANAGEMENT = 0

While compiling AWS 1.6.32, I encountered that all tests passed except one `FileSystem::CreateDirectoryIfNotExists` in aws-cpp-sdk-core-tests using in post build event.
(source file https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core-tests/utils/FileSystemUtilsTest.cpp)

After little investigating source code of the test I found out that there's a mention of maximum path length limitation in Win32 (MAX_PATH = 260), but nonetheless the path length using in this test exceeds the limitation: `len(longDirName)` + `len("dir2")` + `len("dir3")` is truly more that 260. As a result, this test fails in Windows 10.
Of course, you can set explicitly `LongPathDirs` variable in registry according to https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file since Windows 10 1607, but for me it looks a little unfair and unobvious.

**Comment by singku** [comment]
Could you please show us the error when it failed? The path length is more than 260 chars by purpose to test long path name. 
https://github.com/aws/aws-sdk-cpp/blob/e40d691f239f068794c268ac3d75ff6b62ddb7db/aws-cpp-sdk-core/source/platform/windows/FileSystem.cpp#L39

We have tested it on Windows 10 and it passed.

**Comment by nplotnik** [comment]
@singku , thank you for your help a lot.
But issue is still present:
     4>F:\packages\aws\1.7.80-align1-3\aligntech\stable\source\aws-cpp-sdk-core-tests\utils\FileSystemUtilsTest.cpp(293): error : Value of: FileSystem::CreateDirectoryIfNotExists(FileSystem::Join(FileSystem::Join(dir2, "dir3"), longDirName).c_str(), true ) [F:\packages\aws\1.7.80-align1-3\aligntech\stable\build\4b0db3f9c95b4a077f7330f8d1a28d199e064411\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]

aws-sdk-cpp version: 1.7.80
Windows 10 version: Version 1803(OS Build 17134.590)

I changed settings to enable long paths on windows according to https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file

**Comment by mcote57** [comment]
We are seeing the same problem.  Has anyone resolved this please?

**Comment by KaibaLopez** [comment]
Hi @mcote57 , sorry to say but no, we still require you to manually enable LongPathDirs on windows and we don't have any immediate plans to change this. 
Not saying we are not thinking about it, just kind of low priority at the moment.

**Comment by mcote57** [comment]
I have manually enabled longpaths and still see this problem.


Regards and be well!

Marlene


 
 

    On Friday, October 18, 2019, 7:30:53 PM EDT, Gilberto Lopez Zayas <notifications@github.com> wrote:  
 
 
Hi @mcote57 , sorry to say but no, we still require you to manually enable LongPathDirs on windows and we don't have any immediate plans to change this.
Not saying we are not thinking about it, just kind of low priority at the moment.

**Comment by KaibaLopez** [comment]
Hi @mcote57, may I ask how did you enable the long paths?  Also, are you getting the exact same error? And finally, are you using the same version of the sdk?

**Comment by mcote57** [comment]
Microsoft Visual Studio Professional 2017 
Version 15.9.17
VisualStudio.15.Release/15.9.17+28307.905
Microsoft .NET Framework
Version 4.7.02053

Installed Version: Professional

Visual C++ 2017   00369-60000-00001-AA349
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake
E:\B_AWS_SDK_Win\aws-cpp-sdk-core-tests\utils\FileSystemUtilsTest.cpp(293): error : Value of: FileSystem::CreateDirectoryIfNotExists(FileSystem::Join(FileSystem::Join(dir2, "dir3"), longDirName).c_str(), true ) [E:\B_AWS_SDK_Win\bld\aws-cpp-sdk-core-tests\aws-cpp-sdk-core-tests.vcxproj]





 Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.14393.
  -- The C compiler identification is MSVC 19.16.27034.0
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works

Marlene


 
 

    On Tuesday, October 22, 2019, 1:00:04 PM EDT, Gilberto Lopez Zayas <notifications@github.com> wrote:  
 
 
Hi @mcote57, may I ask how did you enable the long paths? Also, are you getting the exact same error? And finally, are you using the same version of the sdk?

**Comment by mcote57** [comment]
and this is the command that is failing. aws-cpp-sdk-core-tests.vcxproj -> E:\B_AWS_SDK_Win\bld\bin\Release\aws-cpp-sdk-core-tests.exe
PostBuildEvent:
  setlocal
  ..\bin\Release\aws-cpp-sdk-core-tests.exe --gtest_shuffle --gtest_repeat=3
  if %errorlevel% neq 0 goto :cmEnd
  :cmEnd
  endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
  :cmErrorLevel
  exit /b %1
  :cmDone
  if %errorlevel% neq 0 goto :VCEnd
  :VCEnd
  


Regards and be well!

Marlene


 
 

    On Tuesday, October 22, 2019, 1:00:04 PM EDT, Gilberto Lopez Zayas <notifications@github.com> wrote:  
 
 
Hi @mcote57, may I ask how did you enable the long paths? Also, are you getting the exact same error? And finally, are you using the same version of the sdk?

**Comment by mcote57** [comment]
the odd thing is that the same commands work in the cmd window, but fail when run by jenkins.  both cmd window and jenkins are running as the same user.

**Comment by mcote57** [comment]
I opened a new issue for this.  
https://github.com/aws/aws-sdk-cpp/issues/1266
