### ISSUE TITLE
CreateMultipartUpload() Asserts with Japanese Characters (Unicode) Key encoded as UTF8

### ISSUE THREAD

**Issue by pcaswell** [aws/aws-sdk-cpp#994]
### What platform/OS are you using?
Windows 7 64bit Professional

### What compiler are you using? what version?
Microsoft (R) C/C++ Optimizing Compiler Version 19.14.26430 for x64

### What's your CMake arguments?
cmake ../${AWS_SDK_BASENAME} -G "Visual Studio 15 2017 Win64" 
-DSIMPLE_INSTALL=OFF 
-DAUTORUN_UNIT_TESTS=OFF 
-DCMAKE_INSTALL_PREFIX="${TOOLS_X64}/${AWS_SDK_BASENAME}" 
-DCMAKE_PDB_OUTPUT_DIRECTORY="${TOOLS_X64}/${AWS_SDK_BASENAME}/bin/windows/intel64" 
-DCPP_STANDARD=17 
-DBUILD_ONLY="s3;dynamodb;lambda;iam;autoscaling;application-autoscaling;sts"

Where ${AWS_SDK_BASENAME} = 1.6.25

### Can you provide a TRACE level log? (sanitize any sensitive information)
Later if required.

I am trying to get our code to work reliably with Unicode and S3.

The Key I'm using for the object is Japanese : STORE{存儲一個}/文件夾一/文件夾二/安全
Obviously encoded as UTF8 in the requests.

I can create this key as a 0 byte object using PutObject(..) successfully but I'm having problems with Multipart uploads to the same key.   Here's what I've figured out so far:

In the the file "S3Client.cpp" and method S3Client::CreateMultipartUpload(reguest) on line 317  the call to MakeRequest() succeeds but then on line 320 the SDK tries to parse the response - this asserts with this error:
![win-asserts](https://user-images.githubusercontent.com/10559188/47210949-330a5f00-d38c-11e8-8952-a5b0d1450591.png)

Tracing down through the code in file "AwsClient.cpp" through AWSClient::AttemptOneRequest(...) 
then file "WinSyncHttpClient.cpp" and WinSyncHttpClient::MakeRequestInternal(...) I see that the result from the server is XML as follows:

`<?xml version="1.0" encoding="UTF-8"?>
<InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>BUCKET_NAME_REMOVED</Bucket>
<Key>_STORE{ã‚¹ãƒˆã‚¢ãƒ¯ãƒ³}/ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆ1/ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆ2/ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£</Key><UploadId>eMWVZt_X_hjeBGK8.lYwjfgk6I7T3_URuDkGSXeVloNspr4Dr99SCAksyv4UdLxmhYik3Pi7dK4xrFnUsD.UrhLS97yVT80nxXIpmllbkF0998TmmVxN6k37X_WCG3Tr</UploadId></InitiateMultipartUploadResult>
`

The <Key> part of this XML is the UTF8 encoding of the Japanese key I mentioned at the top of this issue.  When this XML is processed in file "CreatMultipartUploadResult.cpp" in the operator=() method on Line 42 the code asserts when trying to 'Trim' the key.  Here's the code:
m_key = StringUtils::Trim(keyNode.GetText().c_str())

I can repeat the assert with this simple bit of code:
`	Aws::String copy("_STORE{å­˜å„²ä¸€å€‹}/æ–‡ä»¶å¤¾ä¸€/æ–‡ä»¶å¤¾äºŒ/å®‰å…¨");
	copy.erase(std::find_if(copy.rbegin(), copy.rend(), [](int ch) { return !::isspace(ch); }).base(), copy.end());`

So, am I doing something wrong or is there a bug in the way this response is handled.  Coincidentally I see the same error when trying to ListMultipartUploads().  
Thanks in advance for the help.

**Comment by pcaswell** [comment]
Aw flip.  This looks like the culprit:
https://developercommunity.visualstudio.com/content/problem/235300/universalcrt-incorrect-assert-in-isspace.html
That's 2 hours I'll never get back.

**Comment by singku** [comment]
Thanks for reporting this, we are working on a fix.

**Comment by wps132230** [comment]
Hi, we've fixed this issue in https://github.com/aws/aws-sdk-cpp/commit/c210e2f6486d8b4306cd06abf3d9eea662bee94a.
