### ISSUE TITLE
Any way to pass install directory to make install?

### ISSUE THREAD

**Issue by sipvoip** [aws/aws-sdk-cpp#997]
### What platform/OS are you using?
Centos 7

### What compiler are you using? what version?
GCC

### What's your CMake arguments?
cmake3 .. -DBUILD_ONLY="polly"

I am trying to build an RPM and getting stuck because it looks like the install directory is hardcoded to /usr/local. Is there a way to pass install directory on make install?

I tried the standard:
make install prefix=/home/nathan/rpmbuild/BUILDROOT/amazon-poly-1.6.39-1.x86_64/usr/local

**Comment by singku** [comment]
pass CMAKE_INSTALL_PREFIX to cmake command

**Comment by Bu11etmagnet** [comment]
This is typical of CMake. It hard-codes every information at CMake run time. You can't override those values after CMake has run.
